### ISSUE TITLE
样式：简化首页 ：清爽模式下 兼容 首页外加 猜你喜欢 脚本

### ISSUE THREAD

**Issue by cmmdwl** [the1812/Bilibili-Evolved#1000]
**关于哪一项功能**

https://github.com/indefined/UserScripts/tree/master/bilibiliHome
该脚本在首页未改动情况下运行正常
**期望的效果**

**脚本版本**
Stable v1.10.39
内容包: 1c8eac4

**Comment by the1812** [comment]
简化首页不会与首页推荐兼容.
