### ISSUE TITLE
简化首页清爽模式下移动热门时候移动一整个格子

### ISSUE THREAD

**Issue by cmmdwl** [the1812/Bilibili-Evolved#1001]
**关于哪一项功能**

移动列表时候如果只走一半，撕裂一半不太配另一半的圆角，有些不太符合审美，要是能自动回正就好了
![image](https://user-images.githubusercontent.com/21263352/94987778-8c7cf000-059b-11eb-8d5e-ae1a121351c6.png)

**期望的效果**

![image](https://user-images.githubusercontent.com/21263352/94987878-1036dc80-059c-11eb-9e67-0590517f04bd.png)

**脚本版本**
Stable v1.10.39
内容包: 1c8eac4

**Comment by the1812** [comment]
(这个以前是可以吸附的 后来Chrome出bug了就又取消了)
现在试了下Chrome和Firefox可以, Safari仍然不支持, 不过放出来也没啥关系
