### ISSUE TITLE
关于#499的加强版宽屏失效的问题

### ISSUE THREAD

**Issue by SpoonerCake** [the1812/Bilibili-Evolved#1003]
之前用了修改代码的加强版宽屏很好用,现在更新了之后就变成普通宽屏了,请问这个版本有什么合适的代码吗

**Comment by SpoonerCake** [comment]
现在的代码是这样的
bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `.player-mode-widescreen #app {
    position: relative !important;
}
.player-mode-widescreen #bofqi {
    width: 100vw !important;
    height: calc(100vh) !important;
    position: absolute !important;
    left: 0 !important;
}
.player-mode-widescreen .player-wrap,
.player-mode-widescreen .danmaku-box {
    height: calc(100vh + 50px) !important;
}
.player-mode-widescreen .custom-navbar {
    transform: translateY(100vh);
}
.player-mode-widescreen .bilibili-player-video-bottom-area {
    display: none !important;
}
.player-mode-widescreen {
    scrollbar-width: none !important;   
}
.player-mode-widescreen #app {
    transform: translateY(-70px) !important;
}
.player-mode-widescreen::-webkit-scrollbar {
    height: 0 !important;
    width: 0 !important;
}`, displayName: '加强版宽屏', mode: 'important'})

**Comment by the1812** [comment]
```JavaScript
bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `
.player-mode-widescreen #app {
    position: relative !important;
    transform: translateY(-70px) !important;
}
.player-mode-widescreen .v-wrap {
    max-width: unset !important;
} 
.player-mode-widescreen #bilibili-player {
    position: static !important;    
}
.player-mode-widescreen .bilibili-player {
    width: calc(100vw - 12px) !important;
    height: calc(100vh + 20px) !important;
    position: absolute !important;
    left: 6px !important;
    top: 0px !important;
}
.player-mode-widescreen #playerWrap {
    height: calc(100vh) !important;
}
.player-mode-widescreen #danmukuBox
{
    margin-top: 12px !important; 
    height: auto !important;
    order: 0 !important;
}
.player-mode-widescreen .up-info
{
    margin-top: calc(100vh + 20px) !important;
}
.player-mode-widescreen .custom-navbar,
.player-mode-widescreen .gui-settings-icon-panel,
.player-mode-widescreen .bilibili-player-video-bottom-area {
    display: none !important;
}
.player-mode-widescreen {
    scrollbar-width: none !important;   
}
.player-mode-widescreen::-webkit-scrollbar {
    height: 0 !important;
    width: 0 !important;
}`, displayName: '加强版宽屏', mode: 'important'})
```

**Comment by SpoonerCake** [comment]
> ```js
> bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `
> .player-mode-widescreen #app {
>     position: relative !important;
>     transform: translateY(-70px) !important;
> }
> .player-mode-widescreen .v-wrap {
>     max-width: unset !important;
> } 
> .player-mode-widescreen #bilibili-player {
>     position: static !important;    
> }
> .player-mode-widescreen .bilibili-player {
>     width: calc(100vw - 12px) !important;
>     height: calc(100vh + 20px) !important;
>     position: absolute !important;
>     left: 6px !important;
>     top: 0px !important;
> }
> .player-mode-widescreen #playerWrap {
>     height: calc(100vh) !important;
> }
> .player-mode-widescreen #danmukuBox
> {
>     margin-top: 12px !important; 
>     height: auto !important;
>     order: 0 !important;
> }
> .player-mode-widescreen .up-info
> {
>     margin-top: calc(100vh + 20px) !important;
> }
> .player-mode-widescreen .custom-navbar,
> .player-mode-widescreen .gui-settings-icon-panel,
> .player-mode-widescreen .bilibili-player-video-bottom-area {
>     display: none !important;
> }
> .player-mode-widescreen {
>     scrollbar-width: none !important;   
> }
> .player-mode-widescreen::-webkit-scrollbar {
>     height: 0 !important;
>     width: 0 !important;
> }`, displayName: '加强版宽屏', mode: 'important'})
> ```

感谢!!!!

**Comment by 2220209876** [comment]
> ```js
> bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `
> .player-mode-widescreen #app {
>     position: relative !important;
>     transform: translateY(-70px) !important;
> }
> .player-mode-widescreen .v-wrap {
>     max-width: unset !important;
> } 
> .player-mode-widescreen #bilibili-player {
>     position: static !important;    
> }
> .player-mode-widescreen .bilibili-player {
>     width: calc(100vw - 12px) !important;
>     height: calc(100vh + 20px) !important;
>     position: absolute !important;
>     left: 6px !important;
>     top: 0px !important;
> }
> .player-mode-widescreen #playerWrap {
>     height: calc(100vh) !important;
> }
> .player-mode-widescreen #danmukuBox
> {
>     margin-top: 12px !important; 
>     height: auto !important;
>     order: 0 !important;
> }
> .player-mode-widescreen .up-info
> {
>     margin-top: calc(100vh + 20px) !important;
> }
> .player-mode-widescreen .custom-navbar,
> .player-mode-widescreen .gui-settings-icon-panel,
> .player-mode-widescreen .bilibili-player-video-bottom-area {
>     display: none !important;
> }
> .player-mode-widescreen {
>     scrollbar-width: none !important;   
> }
> .player-mode-widescreen::-webkit-scrollbar {
>     height: 0 !important;
>     width: 0 !important;
> }`, displayName: '加强版宽屏', mode: 'important'})
> ```

![YuanEn_2020-10-15_16-23-32](https://user-images.githubusercontent.com/7346652/96097025-0f3e6d00-0f03-11eb-896a-9477f515a12a.png)
第一行的弹幕会不显示的
