### ISSUE TITLE
在看番时，“跳过充电鸣谢”功能失效

### ISSUE THREAD

**Issue by SSDRQAQ** [the1812/Bilibili-Evolved#1006]
**关于哪一项功能**
“跳过充电鸣谢”功能失效

**脚本版本**

Stable v1.10.39

**浏览器版本**

Chrome  85.0.4183.121（正式版本）（64 位）

**错误信息**

无报错

**附加截图**

![image](https://user-images.githubusercontent.com/72328535/95006481-97855e00-0637-11eb-980a-bc86fdf3f94d.png)
![image](https://user-images.githubusercontent.com/72328535/95006487-a0762f80-0637-11eb-9a09-0495f230a1ba.png)
![image](https://user-images.githubusercontent.com/72328535/95006492-acfa8800-0637-11eb-9e81-45241b3741fb.png)

**Comment by the1812** [comment]
注意区分哦  充电是充给up主的  这个是番剧承包 跳不过的
