### ISSUE TITLE
字幕导出功能 在Firefox中不能正确导出字幕位置导致字幕在第一行堆叠

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#1008]
**关于哪一项功能**
字幕导出功能

**问题描述**

我记得很久之前有人提过这个问题，但是最终认为是那个人的播放器问题所以没有解决。

在Chrome中导出ASS字幕文件是正常的，但是在Firefox中导出的字幕文件所有字幕的纵向位置都是相同的数值，最终导致播放器播放时字幕挤压在同一行。这不是播放器的问题，我尝试在chrome和firefox中下载同一个视频的字幕文件，Chrome中下载的可以正常播放，而Firefox中的就会出现这个问题。

**脚本版本**

1.10.39

**浏览器版本**

在chrome 85和Firefox 81中测试。

**错误信息**

**附加截图**

以[这部番剧](https://www.bilibili.com/bangumi/play/ep341220)的第10秒为例：

**使用Chrome下载的ASS文件**

![使用Chrome下载的ASS文件](https://user-images.githubusercontent.com/11648014/95087098-d6a8d180-0753-11eb-95fc-598954804796.png)

**使用Firefox下载的ASS文件**

![使用Firefox下载的ASS文件](https://user-images.githubusercontent.com/11648014/95087164-ed4f2880-0753-11eb-9ad2-42fb0e3a77ee.png)

一并测试了Potplayer并且得到了相同的结果。

**Comment by the1812** [comment]
其实最近就有这个问题 #921

**Comment by CKylinMC** [comment]
> 其实最近就有这个问题 #921

对，我记得有人提过，但是搜了半天没搜到就又发了一个。
我还以为是火狐浏览器那边的兼容性问题。
