### ISSUE TITLE
期望顶端工具栏跳转页面时打开新标签页而不是覆盖当前网页，比如动态，消息这些功能

### ISSUE THREAD

**Issue by 233YUZI** [the1812/Bilibili-Evolved#1009]
**关于哪一项功能**

**期望的效果**

**脚本版本**

**Comment by Geeyun-JY3** [comment]
动态订阅消息不就是在新标签页打开的吗

**Comment by 233YUZI** [comment]
我觉得完全可以添加一个勾选按钮来决定是否保留原版的页面布局和跳转效果




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月5日(星期一) 晚上10:57
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"懒の鸽子"<2511290204@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 期望顶端工具栏跳转页面时打开新标签页而不是覆盖当前网页，比如动态，消息这些功能 (#1009)





 
右键新标签页打开
 或者按住Ctrl点击

**Comment by Coulomb-G** [comment]
鼠标右键不就是你要的按钮吗?

**Comment by Geeyun-JY3** [comment]
鼠标中键单击可后台新标签页打开

**Comment by 233YUZI** [comment]
你说的这些功能都是浏览器自带的，我都知道，可是本来B站你在主页面单击一下会新开一个标签页并且跳转过去，而您的插件直接改成了单击覆盖当前标签页，这很难受，如果我右键新建标签页打开的话又多此一举，我鼠标中键还特么坏了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月5日(星期一) 晚上11:08
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"懒の鸽子"<2511290204@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 期望顶端工具栏跳转页面时打开新标签页而不是覆盖当前网页，比如动态，消息这些功能 (#1009)





 
鼠标中键单击可后台新标签页打开

**Comment by the1812** [comment]
这样吗 以前是b站也是覆盖的  (太久没用原版的了

**Comment by 233YUZI** [comment]
我这边一直是跳转新标签页的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月5日(星期一) 晚上11:13
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"懒の鸽子"<2511290204@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 期望顶端工具栏跳转页面时打开新标签页而不是覆盖当前网页，比如动态，消息这些功能 (#1009)





 
这样吗 以前是b站也是覆盖的  (太久没用原版的了

**Comment by Geeyun-JY3** [comment]
目前 Bilibili-Evolved 自定义顶栏中我这边测试消息、动态、订阅、稍后再看、收藏、历史都是在新标签页打开的，覆盖当前网页的是 Logo、排行、相簿、音频、游戏中心、直播、会员购、漫画、用户信息，你确定你那边所有都是覆盖当前网页？

**Comment by 233YUZI** [comment]
我这边顶栏所有选项点击都是覆盖当前页面




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月5日(星期一) 晚上11:22
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"懒の鸽子"<2511290204@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 期望顶端工具栏跳转页面时打开新标签页而不是覆盖当前网页，比如动态，消息这些功能 (#1009)





 
目前 Bilibili-Evolved 自定义顶栏中我这边测试消息、动态、订阅、稍后再看、收藏、历史都是在新标签页打开的，覆盖当前网页的是 Logo、排行、相簿、音频、游戏中心、直播、会员购、漫画、用户信息，你确定你那边所有都是覆盖当前网页？

**Comment by Geeyun-JY3** [comment]
诶那我这边消息、动态、订阅、稍后再看、收藏、历史都是在新标签页打开是怎么回事🤔

**Comment by the1812** [comment]
你浏览器的特殊设置?

**Comment by Geeyun-JY3** [comment]
是我理解错了，我这边好像是因为某个扩展的原因导致自定义顶栏的用户信息、消息、动态、订阅、稍后再看、收藏、历史点击后不会跳转，根本不是什么在新标签页打开🌚。
我自己再排除一下吧🤦‍♂️。

**Comment by the1812** [comment]
不跳转那是开了触摸吧

**Comment by 233YUZI** [comment]
那我用您的脚本之前还是正常的，用了反而变了，跟我浏览器设置无关的吧
还有我触摸关了的，我是edge浏览器


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月6日(星期二) 上午10:55
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"懒の鸽子"<2511290204@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 期望顶端工具栏跳转页面时打开新标签页而不是覆盖当前网页，比如动态，消息这些功能 (#1009)





 
你浏览器的特殊设置?

**Comment by the1812** [comment]
没说你...  我是回复 @Geeyun-JY3

**Comment by 233YUZI** [comment]
咋发我这了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月6日(星期二) 中午11:35
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"懒の鸽子"<2511290204@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 期望顶端工具栏跳转页面时打开新标签页而不是覆盖当前网页，比如动态，消息这些功能 (#1009)





 
没说你...  我是回复 @Geeyun-JY3

**Comment by the1812** [comment]
因为是你发起的问题  所有讨论都会发邮件给你

**Comment by 233YUZI** [comment]
你们两个人名字还有点像，回答我时感觉就像一个人，我才发现是两个人，艹




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月6日(星期二) 中午11:37
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"懒の鸽子"<2511290204@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 期望顶端工具栏跳转页面时打开新标签页而不是覆盖当前网页，比如动态，消息这些功能 (#1009)





 
因为是你发起的问题  所有讨论都会发邮件给你

**Comment by Geeyun-JY3** [comment]
> 不跳转那是开了触摸吧

啊我都忘了我开了 `顶栏触摸优化`……那确实和其他扩展无关，就是设置项的问题。

> 咋发我这了

相关嘛……说不定以后能帮到同样有这问题的用户。

**Comment by 233YUZI** [comment]
我这边是没开优化之前点顶端那些按钮会覆盖当前网页而不是新建标签页打开，优化后依旧如此并且只有搜索栏左边那排按钮能点，右边那排甚至点不了了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月6日(星期二) 中午11:44
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"懒の鸽子"<2511290204@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 期望顶端工具栏跳转页面时打开新标签页而不是覆盖当前网页，比如动态，消息这些功能 (#1009)





  
不跳转那是开了触摸吧
  
啊我都忘了我开了 顶栏触摸优化……那确实和其他扩展无关，就是设置项的问题。
  
咋发我这了
  
相关嘛……说不定以后能帮到同样有这问题的用户。

**Comment by Geeyun-JY3** [comment]
> 并且只有搜索栏左边那排按钮能点，右边那排甚至点不了了

因为 `顶栏触摸优化` 就是让上面提到的组件（右侧的）点击无跳转啊……
![image](https://user-images.githubusercontent.com/49396421/95157661-507ca180-07cc-11eb-9bc7-726a25633bab.png)

**Comment by 233YUZI** [comment]
那覆盖原页面也让我很难受




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月6日(星期二) 中午12:09
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"懒の鸽子"<2511290204@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 期望顶端工具栏跳转页面时打开新标签页而不是覆盖当前网页，比如动态，消息这些功能 (#1009)





  
并且只有搜索栏左边那排按钮能点，右边那排甚至点不了了
  
因为 顶栏触摸优化 就是让上面提到的组件（右侧的）点击无跳转啊……

**Comment by Geeyun-JY3** [comment]
> 那覆盖原页面也让我很难受

不都已经打 tag 了嘛……
