### ISSUE TITLE
能否显示缓存名？

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [the1812/Bilibili-Evolved#1012]
**关于哪一项功能**

显示视频缓存名

**期望的效果**
能够在某个地方显示视频缓存名，JJDown就可以

**脚本版本**
v1.10.41
内容包: 110e07c

**Comment by the1812** [comment]
缓存名是啥？

**Comment by Misaka-Mikoto-Tech** [comment]
每个分P的视频都有个缓存名的，up主都喜欢在这里搞彩蛋，这个名字在手机端点缓存可以直接看到，PC上的下载器 "JJDown" 选择批量下载也可以看到名字，所以希望 Bilibili-Evolved 也能显示一下

**Comment by Misaka-Mikoto-Tech** [comment]
> 缓存名是啥？

每个分P的视频都有个缓存名的，up主都喜欢在这里搞彩蛋，这个名字在手机端点缓存可以直接看到，PC上的下载器 "JJDown" 选择批量下载也可以看到名字，所以希望 Bilibili-Evolved 也能显示一下
