### ISSUE TITLE
【离线预览版】开启后导致网页内诸多项目（播放弹幕数，Up主头像，评论区，视频选集，相关推荐封面）无法正常加载

### ISSUE THREAD

**Issue by CwavGuy** [the1812/Bilibili-Evolved#1014]
**关于哪一项功能**
Bug回报

**问题描述**

**【离线预览版】开启后导致网页内诸多项目（播放弹幕数，Up主头像，评论区，视频选集，相关推荐封面）无法正常加载，仅开启了Evolved这一个插件，其余全部关闭了，Evolved插件设置在下面附上。此问题在所有页面均有出现**，测试页面 https://www.bilibili.com/video/av1415480

**脚本版本**

// 离线预览版 @version      619.11

**浏览器版本**

Microsoft Chromium Edge 版本 85.0.564.68 (官方内部版本) (64 位)

**错误信息**

![image](https://user-images.githubusercontent.com/25190647/95323294-85721c80-08d0-11eb-8a1c-b70576ae55ff.png)

**然后这里是附上我的插件导出设置的json内容：**

> `{"useDarkStyle":true,"compactLayout":false,"hideBanner":false,"expandDanmakuList":true,"expandDescription":true,"watchLaterRedirect":true,"touchNavBar":false,"touchVideoPlayer":false,"customControlBackgroundOpacity":0.64,"customControlBackground":true,"darkScheduleStart":"18:00","darkScheduleEnd":"6:00","darkSchedule":true,"toast":true,"fullTweetsTitle":true,"fullPageTitle":true,"removeVideoTopMask":false,"removeLiveWatermark":true,"harunaScale":false,"removeAds":true,"showBlockedAdsTip":true,"hideTopSearch":false,"touchVideoPlayerDoubleTapControl":false,"customStyleColor":"#F06292","preserveRank":true,"blurBackgroundOpacity":0.382,"useDefaultPlayerMode":false,"applyPlayerModeOnPlay":true,"defaultPlayerMode":"常规","useDefaultVideoQuality":false,"defaultVideoQuality":"自动","useDefaultDanmakuSettings":false,"enableDanmaku":true,"rememberDanmakuSettings":false,"danmakuSettings":{"subtitlesPreserve":false,"smartMask":false},"defaultPlayerLayout":"新版","defaultBangumiLayout":"新版","skipChargeList":false,"comboLike":false,"autoLightOff":false,"useCache":true,"autoContinue":false,"allowJumpContinue":false,"autoPlay":false,"deadVideoTitleProvider":"稍后再看","useBiliplusRedirect":false,"biliplusRedirect":true,"framePlayback":true,"useCommentStyle":true,"imageResolution":false,"imageResolutionScale":"auto","toastInternalError":false,"i18n":false,"i18nLanguage":"日本語","playerFocus":true,"playerFocusOffset":-10,"simplifyLiveroom":true,"simplifyLiveroomSettings":{"vip":true,"fansMedal":true,"title":true,"userLevel":true,"guard":false,"systemMessage":false,"welcomeMessage":false,"giftMessage":false,"guardPurchase":false,"giftPanel":false,"kanban":false,"userEffect":false,"eventsBanner":false,"rankList":false,"popup":false,"skin":true},"customNavbar":false,"customNavbarFill":false,"customNavbarTransparent":true,"customNavbarShadow":true,"customNavbarCompact":false,"customNavbarBlur":true,"customNavbarBlurOpacity":0.7,"customNavbarOrder":{"blank1":0,"logo":1,"category":2,"rankingLink":3,"drawingLink":4,"musicLink":5,"gamesIframe":6,"livesIframe":7,"shopLink":8,"mangaLink":9,"blank2":10,"search":11,"blank3":20,"userInfo":12,"messages":13,"activities":14,"bangumi":15,"watchlaterList":16,"favoritesList":17,"historyList":18,"upload":19},"customNavbarHidden":[],"customNavbarBoundsPadding":5,"playerShadow":true,"narrowDanmaku":true,"favoritesRedirect":true,"outerWatchlater":true,"hideOldEntry":false,"videoScreenshot":false,"hideBangumiReviews":false,"filenameFormat":"[title][ - ep]","batchFilenameFormat":"[n - ][ep]","sideBarOffset":0,"noLiveAutoplay":true,"hideHomeLive":true,"noMiniVideoAutoplay":false,"useDefaultVideoSpeed":false,"defaultVideoSpeed":"1.0","hideCategory":false,"foldComment":true,"downloadVideoDefaultDanmaku":"无","aria2RpcOption":{"secretKey":"","dir":"","host":"localhost","port":"6800","method":"get","skipByDefault":false,"maxDownloadLimit":"","baseDir":"C:\\Users\\zheng\\Downloads"},"aria2RpcOptionSelectedProfile":"","aria2RpcOptionProfiles":[{"name":"local","secretKey":"","dir":"","host":"127.0.0.1","port":"6800","method":"get","skipByDefault":false,"maxDownloadLimit":"","baseDir":""}],"searchHistory":[],"seedsToCoins":true,"autoSeedsToCoins":true,"lastSeedsToCoinsDate":0,"autoDraw":true,"keymap":true,"doubleClickFullscreen":true,"doubleClickFullscreenPreventSingleClick":false,"simplifyHome":false,"simplifyHomeStyle":"清爽","minimalHomeSettings":{"showSearch":true,"backgroundImage":""},"ajaxHook":false,"scriptLoadingMode":"延后(自动)","scriptDownloadMode":"bundle","guiSettingsDockSide":"左侧","fullActivityContent":true,"feedsFilter":false,"feedsFilterPatterns":[],"feedsFilterTypes":[],"feedsFilterSideCards":[],"activityImageSaver":true,"scriptBlockPatterns":[],"customNavbarSeasonLogo":false,"selectableColumnText":true,"downloadVideoFormat":"flv","downloadVideoDashCodec":"HEVC/H.265","watchlaterExpireWarningDays":14,"superchatTranslate":false,"miniPlayerTouchMove":false,"hideBangumiSponsors":true,"hideRecommendLive":true,"hideRelatedVideos":false,"defaultMedalID":245232,"autoMatchMedal":true,"customStyles":[],"simpleHomeCategoryOrders":{"anime":0,"bangumi":1,"china":2,"manga":3,"music":4,"dance":5,"game":6,"tech":7,"digital":8,"life":9,"kichiku":10,"fashion":11,"ads":12,"entertainment":13,"column":14,"movie":15,"tv":16,"film":17,"documentary":18},"simpleHomeBangumiLayout":"时间表","keymapJumpSeconds":85,"urlParamsClean":true,"collapseLiveSideBar":true,"removeGameMatchModule":true,"noDarkOnMember":true,"feedsTranslate":false,"feedsTranslateProvider":"Bing","feedsTranslateLanguage":"","downloadVideoQuality":120,"defaultLiveQuality":"原画","useDefaultLiveQuality":false,"recordLiveDanmaku":false,"foregroundColorMode":"自动","preserveEventBanner":false,"about":true,"bvidConvert":true,"guiSettings":true,"viewCover":true,"notifyNewVersion":true,"clearCache":true,"downloadVideo":true,"enableDashDownload":true,"downloadDanmaku":true,"downloadSubtitle":true,"downloadAudio":true,"downloadLiveRecords":true,"medalHelper":true,"playerLayout":false,"forceWide":false,"useNewStyle":false,"overrideNavBar":false,"touchVideoPlayerAnimation":false,"allNavbarFill":false,"showDeadVideoTitle":false,"blurVideoControl":false,"oldTweets":false,"watchlaterExpireWarnings":false,"latestVersionLink":"https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@preview/bilibili-evolved.preview-offline.user.js","currentVersion":"619.11","foreground":"#fff","blueImageFilter":"hue-rotate(145deg) saturate(59.00000000000001%)","pinkImageFilter":"hue-rotate(-3deg) saturate(104%)","brightness":"0%","filterInvert":"invert(1)"}`

**附加截图**
![image](https://user-images.githubusercontent.com/25190647/95323924-86577e00-08d1-11eb-87b7-1234ccb7dfa0.png)
![image](https://user-images.githubusercontent.com/25190647/95324098-c6b6fc00-08d1-11eb-92f6-46b4548bc2fd.png)

**Comment by the1812** [comment]
是否有其他相关的Edge插件 特别是会改动网页里的文字的?

**Comment by CwavGuy** [comment]
> 是否有其他相关的Edge插件 特别是会改动网页里的文字的?

你好，感谢回复！☺我试着把除了油猴以外的扩展都禁用了，并重启了浏览器，但问题似乎还是没有好转vv😥
![image](https://user-images.githubusercontent.com/25190647/95325410-c28bde00-08d3-11eb-8a70-c795d4d73b3b.png)

**Comment by the1812** [comment]
你脚本的版本太旧了...
现在都出到 814.09 了

**Comment by CwavGuy** [comment]
> 你脚本的版本太旧了...
> 现在都出到 814.09 了

臥槽😂我就说为什么脚本这么久都不更新了~被游猴自动更新坑了~感谢！！
