### ISSUE TITLE
增加发表评论快捷键

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1015]
**关于哪一项功能**
评论快捷键

**期望的效果**
增加发表评论快捷键，如 <kbd>Ctrl</kbd>+<kbd>Enter</kbd>

**脚本版本**
正式版 v1.10.39 内容包: 625b7ca

**Comment by yun-Tong** [comment]
请问这个功能是还没有做，还是有什么其他的问题啊，我在快捷键上没有看到此功能

**Comment by the1812** [comment]
还没做

**Comment by yun-Tong** [comment]
好的

**Comment by Geeyun-JY3** [comment]
做了的话发正式版的时候会将这个 issue close 掉的

**Comment by Geeyun-JY3** [comment]
话说这个功能做进 v2 的哪个组件了

**Comment by Geeyun-JY3** [comment]
[v2 TP8](https://github.com/the1812/Bilibili-Evolved/releases/tag/v2.0.0-tp8) 加入此功能，正式版已于 [v2.0.7](https://github.com/the1812/Bilibili-Evolved/releases/tag/v2.0.7) 实装。
