### ISSUE TITLE
无法双击全屏

### ISSUE THREAD

**Issue by spphinslove** [the1812/Bilibili-Evolved#1016]
**关于哪一项功能**
双击全屏

**问题描述**

打开任意视频，指针不会变手型。单击能暂停。

**脚本版本**

Stable v1.10.39
内容包: 4bce53a

**浏览器版本**

firefox 81.0.1 (64 位)

**错误信息**

![图片](https://user-images.githubusercontent.com/11383988/95477267-bdee2500-09ba-11eb-8cfb-4aa3272739f0.png)

**附加截图**

**Comment by spphinslove** [comment]
预览版正常的。。。

**Comment by Geeyun-JY3** [comment]
看置顶 #966

> 预览版正常的。。。

就是因为预览版刚修了呀。。。
