### ISSUE TITLE
播放器触摸支持不管用了

### ISSUE THREAD

**Issue by muxuuu** [the1812/Bilibili-Evolved#1017]
**关于哪一项功能**
播放器触摸功能，单击播放器现在是暂停了。

**问题描述**

**脚本版本**
正式版1.2.21

**浏览器版本**
Microsoft Edge Chromium
版本 86.0.622.31 (官方内部版本) beta (64 位)

**Comment by Geeyun-JY3** [comment]
你该更新了。。。

**Comment by the1812** [comment]
(不过要到1.10.40以上才有修复
