### ISSUE TITLE
B站建议

### ISSUE THREAD

**Issue by Imankind** [the1812/Bilibili-Evolved#1018]
**关于哪一项功能**

经常看B站的排行榜，但它默认的排行榜是三日内，比app端更新慢很多。想看和app一样的排行榜，需要每次自己点右上角切换成日排行，很麻烦。插件能不能提供这个功能

**期望的效果**

**脚本版本**

**Comment by imThree** [comment]
手机端排行榜可能被注水了吧，排在前几的经常是叔叔力推的东西，我觉得没必要

**Comment by Imankind** [comment]
B站现在自己改了，四个排行榜自己选择并记住
---原始邮件---
发件人:&quot;Sam Three&quot;<notifications@github.com&gt;
发送时间:2020年10月18日 星期日 上午10:14
收件人:&quot;the1812/Bilibili-Evolved&quot;<Bilibili-Evolved@noreply.github.com&gt;
抄送:&quot;Imankind&quot;<3474449465@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;
主题:Re: [the1812/Bilibili-Evolved] B站建议 (#1018)



手机端排行榜可能被注水了吧，排在前几的经常是叔叔力推的东西，我觉得没必要

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;authored&nbsp;the&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.
