### ISSUE TITLE
手机版脚本向支持

### ISSUE THREAD

**Issue by RainEffect** [the1812/Bilibili-Evolved#102]
希望能再独立做一个手机版面向的支持功能，因为部分旧手机(Android和Ios旧系统均相同)已经无法安装最新版B站，且旧版B站因为原API转移等问题已无法正常使用，但旧版手机仍然可以支持B站的正常播放，所以希望可以针对手机版页面做一个定向支持。
![image](https://user-images.githubusercontent.com/14258727/55403134-b78e1a00-5587-11e9-9b19-28826cc6072e.png)

当然如果作者您没有时间进行这个的话，我这边希望和您进行一个深度的讨论，然后我来执行手机版页面这块的设计和制作。

手机版TamperMonkey的浏览器插件目前在线的仅只有海豚浏览器可用了，以前的UC浏览器插件似乎已经被官方下架，原因未知。(最后一条关于Tampermonkey的其他版本相关是来自官方github issue的[#437](https://github.com/Tampermonkey/tampermonkey/issues/437)帖子内)

目前我手机内使用的是 Yandex 浏览器，效果不错。

**Comment by u2shana** [comment]
我只建议你换手机

**Comment by RainEffect** [comment]
> 我只建议你换手机

你也太真实了。。。

**Comment by u2shana** [comment]
> > 我只建议你换手机
> 
> 你也太真实了。。。

不是真不真实的问题,现在一个400块的超低端手机都能完美支持B站客户端了

**Comment by RainEffect** [comment]
但问题是如果是安卓的PC系统呢。。。它很大部分还是会读取成手机页面，即使你使用“电脑版模式”

所以我才会有这个想法，因为我家的自组机顶盒就是用的[凤凰系统](http://www.phoenixos.com/phoenixos)作为主系统...

**Comment by RainEffect** [comment]
> > > 我只建议你换手机
> > 
> > 
> > 你也太真实了。。。
> 
> 不是真不真实的问题,现在一个400块的超低端手机都能完美支持B站客户端了

但问题是如果是安卓的PC系统呢。。。它很大部分还是会读取成手机页面，即使你使用“电脑版模式”

所以我才会有这个想法，因为我家的自组机顶盒就是用的凤凰系统作为主系统...

**Comment by the1812** [comment]
这...你fork一下做个改版吧, 我确实没精力弄手机版了.
我的代码你可以拿去自由发挥(虽然有些组件可重用性不太好)
