### ISSUE TITLE
默认直播画质选择4K后，进入无4K流直播间不会默认选择最高画质（原画）

### ISSUE THREAD

**Issue by Wnky6457** [the1812/Bilibili-Evolved#1020]
**关于哪一项功能**
直播-使用默认直播画质

**问题描述**
默认画质选择4K时，进入具有4K流的直播间（如13242941号直播间），会默认切换为4K画质，但如果进入其他不具有4K流且直播间有多档画质的直播间（如6号直播间），这个功能则会失效，默认只会使用蓝光画质。推测触发原因为B站直播间画质优先级为“原画＞4K（见附图）”即使在4K直播间原画画质并不如4K

**脚本版本**
Preview v1.10.41

**浏览器版本**
Chrome Canary 88.0.4286.0 64位

**错误信息**
无

**附加截图**
![image](https://user-images.githubusercontent.com/65058098/95559861-fe957f00-0a4a-11eb-8ddf-9c913c265abf.png)

**Comment by the1812** [comment]
默认画质选择为`原画`就行
目前做了特殊处理, 原画的设置遇到4K会保留4K, 不切为原画, 见#975

**Comment by Wnky6457** [comment]
> 默认画质选择为`原画`就行
> 目前做了特殊处理, 原画的设置遇到4K会保留4K, 不切为原画, 见#975

似乎不行。默认直播画质选择原画的话进入4K直播间依然不会使用4K画质，而是原画
