### ISSUE TITLE
彈幕下載後重疊問題

### ISSUE THREAD

**Issue by XPRAMT** [the1812/Bilibili-Evolved#1022]
彈幕下載後，Y軸都是30，所有彈幕重疊在一起
另外預設使用的黑体無法顯示，需改成其他字體才能正常顯示
<img src="https://i.imgur.com/KL56VN7.jpg">

**脚本版本**
1.10.39

**浏览器版本**
Chrome 85

**Comment by the1812** [comment]
同 #921
