### ISSUE TITLE
b站顶栏透明失效

### ISSUE THREAD

**Issue by yuijker** [the1812/Bilibili-Evolved#1023]
**关于哪一项功能**
b站所有可以看到该脚本修改的自定义顶栏中的透明填充、投影、背景模糊功能无效（补充：在b站使用今年秋天的全新的顶栏背景图时出现）（补充：季节logo也会导致这个问题产生）

**问题描述**

此问题将出现在所有的可看见自定义顶栏的网页，包括主页、历史记录、个人空间等地方。（补充：在b站使用今年秋天的全新的顶栏背景图时出现）

**脚本版本**

正式版  v1.10.39

**浏览器版本**

360极速版12.0.1550.0 chrome 78.0.3904.108

**错误信息**

无问题。
![360截图20201010124952410](https://user-images.githubusercontent.com/72558803/95646051-22160380-0af7-11eb-98ee-23f3a12888b9.jpg)

**附加截图**
![image](https://user-images.githubusercontent.com/72558803/95646057-407bff00-0af7-11eb-8826-601cddcc26ae.png)
![image](https://user-images.githubusercontent.com/72558803/95646067-55f12900-0af7-11eb-9d06-07d22db54ae3.png)
![image](https://user-images.githubusercontent.com/72558803/95646077-63a6ae80-0af7-11eb-99a2-92599f438497.png)
![image](https://user-images.githubusercontent.com/72558803/95646079-6dc8ad00-0af7-11eb-9196-cec9f3254490.png)

**Comment by Geeyun-JY3** [comment]
#983 刚被人顶上来……
