### ISSUE TITLE
增加设置视频播放默认分辨率功能

### ISSUE THREAD

**Issue by pzh200707** [the1812/Bilibili-Evolved#1026]
**关于哪一项功能**
视频播放

**期望的效果**
希望可以设置视频播放的默认分辨率，例如4K，或者自动选择最高清选项（即大会员自动选择4K，非大会员自动选择1080P）

**脚本版本**
Bilibili Evolved (Preview Offline)v816.22

**Comment by Coulomb-G** [comment]
这个功能不是有吗?

**Comment by pzh200707** [comment]
欸？研究了下还真的是。。。
