### ISSUE TITLE
“样式”-“使用自定义顶栏"中设置顶栏为透明不生效

### ISSUE THREAD

**Issue by HiMeHM** [the1812/Bilibili-Evolved#1027]
如题，在Firefox上使用的正式版1.10.39设置不了顶栏为透明

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.10.41-preview
> 修复顶栏透明模式不支持动画横幅的问题.

且重复：#983 #1023

**Comment by HiMeHM** [comment]
> 
> 
> 重复：#983 #1023
> 
> 且已修复：https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.10.41-preview
> 
> > 修复顶栏透明模式不支持动画横幅的问题.

感谢告知！！
