### ISSUE TITLE
作者你好,现在难道不能下载视频了吗？？？？

### ISSUE THREAD

**Issue by Gelanfendo** [the1812/Bilibili-Evolved#1029]
**关于哪一项功能**
下载视频，在附加功能这里就没有下载视频这个选项

**问题描述**

**脚本版本**

每个版本

**浏览器版本**

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/55726299/95706731-30e0ef80-0c8a-11eb-9489-b7fa70de78d7.png)

**Comment by the1812** [comment]
进视频页面才有

**Comment by Coulomb-G** [comment]
你的截图不是在主页吗?你得去视频页

**Comment by Gelanfendo** [comment]
好的，太感谢了 wwwww
