### ISSUE TITLE
加载速度与未开启脚本相比有明显迟滞

### ISSUE THREAD

**Issue by anklcaptain** [the1812/Bilibili-Evolved#1030]
如果未开启脚本，点击某个视频右侧的相关推荐视频会秒开不存在迟滞感，开启脚本后点击就像刷新了整个页面一样出现卡顿2到3秒的现象，请问可能是什么原因导致的呢？

**Comment by Mendeler** [comment]
我也发现了，今天更新过后，刷新网页明显感觉加载慢了一些，而且动态卡片模式不习惯，我还是倾向于看标题
