### ISSUE TITLE
暗色模式字体颜色问题

### ISSUE THREAD

**Issue by gavinwyf** [the1812/Bilibili-Evolved#1031]
**关于哪一项功能**
页面显示

**问题描述**

排行榜页面，暗色模式字体颜色问题

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/11659339/95944545-007c8b00-0e1b-11eb-83d9-b54cba4796e5.png)

**Comment by whynotjinx** [comment]
我的情况是在暗色模式下，选择了某个主题颜色之后，部分位置（点赞转发、消息等）变成所选颜色的对比色
![image](https://user-images.githubusercontent.com/33567283/96279904-03e26300-1023-11eb-9c3a-adb9aae8f03f.png)

**Comment by the1812** [comment]
这个是因为白天下的点赞从粉色变成蓝色了 下次都会一块修复的
