### ISSUE TITLE
建议新增速率调节，新增多倍速率播放功能

### ISSUE THREAD

**Issue by Aopodo** [the1812/Bilibili-Evolved#1032]
**关于哪一项功能**

**期望的效果**

**脚本版本**

**Comment by the1812** [comment]
???
![image](https://user-images.githubusercontent.com/26504152/95982450-b8795a80-0e52-11eb-95c6-db7ae61efa05.png)

**Comment by Aopodo** [comment]
能否新增自定义的多倍率播放速度，比如3,4,5倍速率，官方的2倍速有些视频看起来太慢了

**Comment by Aopodo** [comment]
已在快捷键中找到相应功能，打开视频->快捷键扩展，使用shift+↑/↓即可
