### ISSUE TITLE
关灯模式下下载弹窗被遮挡

### ISSUE THREAD

**Issue by FxckIt** [the1812/Bilibili-Evolved#1033]
**关于哪一项功能**
视频下载

**问题描述**

视频下载界面在播放器关灯模式下显示在视频窗口之后，无法操作选项。

**脚本版本**

Stable v1.10.39
内容包: 1bc5777

**浏览器版本**

Chrome 86.0.4240.75（正式版本） （64 位）
**附加截图**
![不关灯](https://user-images.githubusercontent.com/71419190/95983644-8ff26000-0e54-11eb-9d39-750e8662a937.png)
![关灯](https://user-images.githubusercontent.com/71419190/95983670-9e407c00-0e54-11eb-87c4-06e3e79b6950.png)

**Comment by the1812** [comment]
请开灯再下载  关灯状态下视频会被提升到最前面

**Comment by imThree** [comment]
我常年“关灯”，下载的时候没有发现这个问题，可能不是每个人都会遇到？
