### ISSUE TITLE
自定义播放器大小-加强版宽屏失效

### ISSUE THREAD

**Issue by 2220209876** [the1812/Bilibili-Evolved#1034]
https://github.com/the1812/Bilibili-Evolved/issues/492

`bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `
.player-mode-widescreen #app {
    position: relative !important;
}
.player-mode-widescreen #bofqi {
    width: 100vw !important;
    height: calc(100vh + 46px) !important;
    position: absolute !important;
    left: 0 !important;
}
.player-mode-widescreen .player-wrap,
.player-mode-widescreen .danmaku-box {
    height: calc(100vh + 50px + 46px) !important;
}
.player-mode-widescreen .custom-navbar {
    transform: translateY(calc(100vh + 46px));
}
.player-mode-widescreen {
    scrollbar-width: none !important;   
}
.player-mode-widescreen #app {
    transform: translateY(-70px);
}
.player-mode-widescreen::-webkit-scrollbar {
    height: 0 !important;
    width: 0 !important;
}`, displayName: '加强版宽屏', mode: 'important'})`

无效了

**Comment by the1812** [comment]
见 #1003
