### ISSUE TITLE
希望增加背景颜色自定义选项

### ISSUE THREAD

**Issue by trswygg** [the1812/Bilibili-Evolved#1035]
**关于哪一项功能**

希望增加背景颜色自定义选项

**期望的效果**

可以像修改主题颜色一样修改背景颜色
~~主要是不想再开一个styleus之类的~~
（暗黑模式的深黑背景颜色也不一定让所有人满意）

**脚本版本**
Stable v1.10.39
内容包: 179ce43

**Comment by Coulomb-G** [comment]
这个我真的只能建议你开stylus之类的,夜间模式的背景设置和主题色设置不一样,你需要背景自定义的话,可能得从头写一个,不少页面的背景元素也不一样

**Comment by the1812** [comment]
难不成还想要彩色的背景吗, 那就真只能stylus了

**Comment by trswygg** [comment]
好吧我最初的想法只是想让背景颜色和`主题颜色`一样可以在`设置/样式`里面直接选择
更多花里胡哨的没有考虑，毕竟不是主要功能
