### ISSUE TITLE
希望能新增一个批量下载动态图片的功能

### ISSUE THREAD

**Issue by FlareMonso** [the1812/Bilibili-Evolved#1036]
**关于哪一项功能**

批量下载动态图片

**期望的效果**

像其他作者的脚本一样，在右边的三个点新增若干个用于下载原图的选项
![image](https://user-images.githubusercontent.com/67825783/96245704-3025c180-0fda-11eb-805e-3c1e4b4d9753.png)
此图为微博上的脚本

**脚本版本**
v1.10.39

**Comment by FlareMonso** [comment]
我试用了最新的预览版，除了打包下载之外，希望“逐个下载图片”的选项也能有

**Comment by the1812** [comment]
两个你都常用吗? 我是想放个选项在设置里, 控制所有多文件下载时的行为是打包还是逐个

**Comment by Geeyun-JY3** [comment]
> 我是想放个选项在设置里, 控制所有多文件下载时的行为是打包还是逐个

要不像以前弹幕和字幕下载一样用快捷键如 <kbd>Alt</kbd> 区分？

**Comment by the1812** [comment]
Shift绝大部分人发现不了的... 所以现在弹幕那边也是直接出两个按钮了

**Comment by FlareMonso** [comment]
> 我是想放个选项在设置里, 控制所有多文件下载时的行为是打包还是

可以在选项里设置，我一般会用"逐个下载"，我觉得应该默认"逐个下载"，因为动态最多只有9张图，打包还要解压有点麻烦

**Comment by the1812** [comment]
逐个得浏览器设成自动保存到某个位置才方便些, 不然就连续9个另存为弹窗了

**Comment by FlareMonso** [comment]
我用的自动保存的，做个提醒会比较好吧

**Comment by FlareMonso** [comment]
我用的是Microsoft Edge浏览器，它这里面有个默认下载地址，图片逐个下载到“默认下载地址”这样？
![image](https://user-images.githubusercontent.com/67825783/96403717-a8bf9480-120b-11eb-96ef-44c8a759f6d0.png)

**Comment by the1812** [comment]
对 chrome内核都有这个功能的 我是开着每次询问的

**Comment by FlareMonso** [comment]
还希望能自定义下载图片名称。像是在这个微博上的脚本，我一般用的原贴的up用户名，而不是转发的。

![image](https://user-images.githubusercontent.com/67825783/96405419-d3135100-120f-11eb-916b-ef310afa92de.png)

**Comment by the1812** [comment]
命名之后再弄, 这一次先把这功能做出来

**Comment by FlareMonso** [comment]
嗯，我觉得“多文件下载模式”还能再加个"aria2 RPC"和“下载链接文本”的选项

**Comment by the1812** [comment]
那不至于 而且这个下载模式控制的是最后只有文件名和内容的时候 RPC和链接信息都已经没有了
