### ISSUE TITLE
顶栏的透明填充失效

### ISSUE THREAD

**Issue by EricSUID** [the1812/Bilibili-Evolved#1040]
**关于哪一项功能**
“样式”里的“使用自定义顶栏”功能

**问题描述**

顶栏的透明填充失效

**脚本版本**

Stable v1.10.39

**浏览器版本**

Vivaldi | 3.4.2066.76 (Stable channel) （64 位）
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.101 Safari/537.36

**错误信息**

**附加截图**
 @![image](https://user-images.githubusercontent.com/43235133/96338762-caf9cb00-10c2-11eb-89e2-365a8cc62acf.png)

**Comment by Geeyun-JY3** [comment]
重复：#983 #1023 #1027

且已修复：https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.10.41-preview
> 修复顶栏透明模式不支持动画横幅的问题.
