### ISSUE TITLE
网页端排行榜深色模式部分文字“消失”

### ISSUE THREAD

**Issue by imThree** [the1812/Bilibili-Evolved#1043]
**关于哪一项功能**
B站改了网页端排行榜，现在的排行榜在深色模式下背景颜色与部分字体颜色是一样的，啥也看不清。
![事故现场](https://user-images.githubusercontent.com/4982919/96357188-0af49880-112b-11eb-93c8-b61fda601ebc.png)

**问题描述**

https://www.bilibili.com/v/popular/rank/all

**脚本版本**

刚更新的版本v1.11.0
但是以前的版本也有这个问题
另外，**去掉屑点赞功能的开发者是人间之鉴**。

**浏览器版本**
Chrome 86.0.4240.75（正式版本） （64 位）
应该与浏览器的关系不大

**错误信息**
不存在

**Comment by Geeyun-JY3** [comment]
就是 v1.11.0 刚修的，清清缓存 #1031

**Comment by imThree** [comment]
> 就是 v1.11.0 刚修的，清清缓存 #1031

确实，我以为没修复，大意了。

**Comment by Geeyun-JY3** [comment]
（另外这个页面去掉了什么点赞功能吗？

**Comment by imThree** [comment]
不是的，你现在可以给视频弹幕点赞了，就像爱奇艺腾讯视频西瓜视频等等一样。叔叔我啊，为了业绩什么都能做出来。、
但是网页端这个弹幕点赞功能跟以前的触屏操作冲突了，新版本插件就把点赞功能去掉了。
与排行榜页面没关系。😂

**Comment by Geeyun-JY3** [comment]
哦哦哦
不过弹幕点赞这功能在移动端都是出来很久了

**Comment by the1812** [comment]
这个做的太敷衍了 不加在原来的右键菜单里 非要新弄个浮层 我就直接屏蔽了

**Comment by Geeyun-JY3** [comment]
@the1812 顺道提醒，自定义顶栏的这个排行链接该换了
