### ISSUE TITLE
新版 Ass字幕透明度低

### ISSUE THREAD

**Issue by Youmio** [the1812/Bilibili-Evolved#1044]
**关于哪一项功能**
ASS字幕下载

**问题描述**

之前因为ASS字幕全挤在一行，看到更新后，马上更新了。下载视频发现出现了新的问题

就是下载ASS透明度极低。我下载的AV号是：av969097872。我试过好几个播放器，都是一样的。而之前下载的就不会

**脚本版本**

V1.11.0

**浏览器版本**

Mac Chrome 86

**错误信息**

**附加截图**
<img width="955" alt="image" src="https://user-images.githubusercontent.com/36833961/96363032-4d869700-1164-11eb-8b7d-ff9e58d2caf9.png">

原本是这样的
<img width="958" alt="image" src="https://user-images.githubusercontent.com/36833961/96363154-0351e580-1165-11eb-9459-67c9581415ab.png">

**Comment by the1812** [comment]
在Console里看看? (<kbd>Ctrl + Shift + I</kbd>)
点击下载弹幕后会输出一个当前播放器的弹幕设置, 展开后`alpha`代表不透明度
顺便也可以测试运行一下`JSON.parse(localStorage.getItem('bilibili_player_settings')).setting_config.opacity`看看结果

![image](https://user-images.githubusercontent.com/26504152/96368072-4cfdf880-1184-11eb-84a8-f123042d6c2f.png)
![image](https://user-images.githubusercontent.com/26504152/96368075-512a1600-1184-11eb-9727-d3ffb9b1ff1c.png)

**Comment by Youmio** [comment]
是这个吗？显示0.8呢
<img width="1908" alt="image" src="https://user-images.githubusercontent.com/36833961/96368754-57ba8c80-1188-11eb-8879-2b49931b6f7a.png">

**Comment by the1812** [comment]
明白了... 我写反了  你播放器设80%最后转出来变成了20%不透明度

**Comment by Youmio** [comment]
喔，那我现在再更新下就好了？

**Comment by the1812** [comment]
离线的更新就行, 非离线的等自动热更新, 或者从 Fast.io 源重装即可(记得备份设置)

**Comment by Youmio** [comment]
好的，感谢~！！
