### ISSUE TITLE
将网页窗口缩放至显示器4分之一后打开网页全屏出现概率性视频狂闪

### ISSUE THREAD

**Issue by Eisanm** [the1812/Bilibili-Evolved#1048]
**问题描述**
【BUG】
https://www.bilibili.com/video/av6842967
1
将网页窗口缩放至显示器大概4分之一后点击鼠标中键向左滑打开网页全屏后出现视频狂闪.拖动网页窗口比例也会
（概率性）

2
在哔哩哔哩主页网页窗口2分之一点击鼠标中键向左滑网页似乎出现错误？

**脚本版本**
Stable v1.11.0

**浏览器版本**
Microsoft Edge 86.0.622.43

**错误信息**
无

**附加截图**
1
![无标题](https://user-images.githubusercontent.com/41187157/96374589-29e44080-11a6-11eb-90ce-45c5cbb54c60.png)

2
![标题](https://user-images.githubusercontent.com/41187157/96374958-8b0d1380-11a8-11eb-8a6d-607d7befe00b.png)

**Comment by the1812** [comment]
**鼠标中键向左划**是什么操作?

**Comment by the1812** [comment]
另外 本脚本只支持1400px以上的宽度, 拉到这么窄的情况是不予考虑的

**Comment by Eisanm** [comment]
> [1400px]，

呃.那好吧
