### ISSUE TITLE
夜间模式下鼠标移至二级分区页排行榜的视频上时的小 bug

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1052]
**关于哪一项功能**
夜间模式

**问题描述**
强迫症扣个细节
夜间模式下鼠标移至二级分区页排行榜的视频上时标题会先缩到封面下再恢复正常

**脚本版本**
正式版本 v1.11.0 内容包: 6431da8
预览离线版 825.35

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 86.0.4240.75（正式版本） （64 位）

**错误信息**

**附加截图**
夜间模式：
![image](https://user-images.githubusercontent.com/49396421/96475328-78f1aa80-1266-11eb-9cfa-8dd6c8b1b6bf.gif)
未开启夜间模式：
![image](https://user-images.githubusercontent.com/49396421/96475234-58295500-1266-11eb-812b-8bcda4f3935b.gif)

**Comment by Tinhone** [comment]
https://github.com/the1812/Bilibili-Evolved/blob/67d61b5ef9dd817a4b2063b51bafa5a3ad4ba382/registry/lib/components/style/dark-mode/old/dark-slice-1.css#L1439-L1454

移除`p.ri-title`这一行可以恢复原状

**Comment by Geeyun-JY3** [comment]
Fixed by #4001

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/220354414-10ac6dc0-e514-434a-bdbe-19b809cffe3d.png)
这居然没自动关闭...

**Comment by Geeyun-JY3** [comment]
> ![image](https://user-images.githubusercontent.com/26504152/220354414-10ac6dc0-e514-434a-bdbe-19b809cffe3d.png) 
> 这居然没自动关闭...

这是不是有权限相关要求的
