### ISSUE TITLE
开启脚本后无法与弹幕进行交互

### ISSUE THREAD

**Issue by wwzw27** [the1812/Bilibili-Evolved#1053]
例如这种交互，整个视频框的鼠标光标也会变成手指样式。记得前几天开脚本也能进行正常交互的
**附加截图**
![QQ515](https://user-images.githubusercontent.com/64151098/96673851-0bdf3180-139a-11eb-9c24-dac61c3a84af.png)

**Comment by Coulomb-G** [comment]
会使触屏功能失效,所以屏蔽了

**Comment by the1812** [comment]
我禁了 见 https://github.com/the1812/Bilibili-Evolved/issues/966#issuecomment-702522679

**Comment by wwzw27** [comment]
> 我禁了见[＃966（评论）](https://github.com/the1812/Bilibili-Evolved/issues/966#issuecomment-702522679)

好的 明白了。还以为是bug
