### ISSUE TITLE
希望能改一下横向条用鼠标滚轮滚动时的速度

### ISSUE THREAD

**Issue by carotte13b** [the1812/Bilibili-Evolved#1054]
首页风格为清爽时，动态栏用鼠标滚起来太慢了…希望能改进一下体验

**Comment by carotte13b** [comment]
或者有没有大佬知道改哪个参数哇，我找了一下没找到

**Comment by carotte13b** [comment]
或者有没有大佬知道改哪个参数哇，我找了一下没找到

**Comment by the1812** [comment]
装离线版, 搜索`.deltaY,`, 改成`.deltaY * 2,`或者更大些的数字
![image](https://user-images.githubusercontent.com/26504152/96742150-285c8780-13f5-11eb-9369-abdb59e6f615.png)

**Comment by carotte13b** [comment]
woc 舒服了 谢谢大佬  网不好不能直接回复你的回复了 就直接发这了
