### ISSUE TITLE
动态过滤正则关键词不知道怎么设置

### ISSUE THREAD

**Issue by rilegoule** [the1812/Bilibili-Evolved#1059]
[为什么过滤不掉啊，我用这个方法
![image](https://user-images.githubusercontent.com/16163003/96951610-6fdf3280-151f-11eb-98e6-5d7fbd34da9b.png)

**Comment by Coulomb-G** [comment]
哈哈哈,是团长,你直接按类型可以过滤的,"转发"类型

**Comment by the1812** [comment]
文本是带转发内容来着的
`/^转发动态/`应该可以, 不过上面直接屏蔽转发类型更简单一些

**Comment by rilegoule** [comment]
> 文本是带转发内容来着的
> `/^转发动态/`应该可以, 不过上面直接屏蔽转发类型更简单一些

他这个后面还隐藏了什么吗？我在$前面加过\s?或\n?都没用

**Comment by the1812** [comment]
后面是转发的内容 `这是一个普通女孩...`
