### ISSUE TITLE
希望可以像移动端一样，在直播间添加一个仅播放声音的模式

### ISSUE THREAD

**Issue by 31415926loli** [the1812/Bilibili-Evolved#1062]
**关于哪一项功能**

直播间

**期望的效果**

希望在直播间添加一个仅播放声音而屏蔽画面（黑屏）的模式。因为有的时候会开着直播间听听歌听听闲聊，手里做些别的事情。如果开着画面的话浏览器会产生不小的gpu占用，这样的话无论是玩游戏或者是做工作gpu都会有额外的开销，网络也会有额外的带宽占用，所以希望能在清晰度选择那一栏里或者其他合适的地方添加一个仅播放声音的模式。

**脚本版本**
预览版

**Comment by Coulomb-G** [comment]
这你得找b站，脚本只能让你看不见画面，但实际画面还是在的

**Comment by the1812** [comment]
不知道该怎么不让他加载视频, 所以网络还是会占用的, 不过我觉得最小化/切换标签页就不会占用GPU了啊

**Comment by 31415926loli** [comment]
> 不知道该怎么不让他加载视频, 所以网络还是会占用的, 不过我觉得最小化/切换标签页就不会占用GPU了啊

还真是，我都没注意。谢谢提醒

**Comment by ER010010** [comment]
可以用potplayer播放直播源，将视频渲染器设置为空，就可以实现
