### ISSUE TITLE
默认播放速度设置没有起到作用

### ISSUE THREAD

**Issue by Sam2007-coder** [the1812/Bilibili-Evolved#1064]
**关于哪一项功能**

默认播放速度设置

**问题描述**

我把默认速度播放设置为 2.0，当我打开视频时，却没有设置播放速度。

测试了5个视频都会出现此问题，参考情况可见下图。

**脚本版本**

v1.11.0

**浏览器版本**

Edge 86.0.622.51

**附加截图**

![BV6QgI.jpg](https://s1.ax1x.com/2020/10/24/BV6QgI.jpg)

![BV6lvt.jpg](https://s1.ax1x.com/2020/10/24/BV6lvt.jpg)

**Comment by CyberTNT** [comment]
用edge beta试了一下确实使用`默认播放速度`无效了，明明前两天还能用
