### ISSUE TITLE
顶栏动态显示投稿时间

### ISSUE THREAD

**Issue by LuvEven** [the1812/Bilibili-Evolved#1067]
**关于哪一项功能**

顶栏-动态

**期望的效果**

    现有的效果：没有办法标记视频投稿时间以及上次记录点的分割线

![image](https://user-images.githubusercontent.com/56387141/97104872-0e22f200-16f2-11eb-8c6b-fc896fca14ea.png)

    1.希望能像原版一样呈现投稿时间

![image](https://user-images.githubusercontent.com/56387141/97104860-fcd9e580-16f1-11eb-8bec-8fe08173ca68.png)

    2.（出现原版选项）

**脚本版本**
1.11.0 github正式版

感谢作者的开发

**Comment by Geeyun-JY3** [comment]
重复 #628
