### ISSUE TITLE
希望能有直播自动签到,自动领领瓜子功能,然后主页右上角能把官方原有的番剧按钮加上

### ISSUE THREAD

**Issue by BunnySmasher** [the1812/Bilibili-Evolved#1069]
**关于哪一项功能**

**期望的效果**

**脚本版本**

**Comment by Geeyun-JY3** [comment]
部分重复：#548
自定义顶栏有番剧，叫「订阅」

**Comment by BunnySmasher** [comment]
> 部分重复：#548
> 自定义顶栏有番剧，叫「订阅」

对我就是有点不习惯,我点番剧界面的目的是希望能看看有什么我没订阅的番剧,但是点查看更多不是进入番剧界面而是进入订阅界面然后我还要跳转主页去点番剧界面入口进入,这一点让我有点没习惯.

**Comment by Geeyun-JY3** [comment]
> 希望能看看有什么我没订阅的番剧

这个需求的话你可以通过「主站」组件的番剧分区进入

**Comment by BunnySmasher** [comment]
> > 希望能看看有什么我没订阅的番剧
> 
> 这个需求的话你可以通过「主站」组件的番剧分区进入

好的, 十分感谢.
