### ISSUE TITLE
夜间模式下直播间天选时刻的显示问题

### ISSUE THREAD

**Issue by FlareMonso** [the1812/Bilibili-Evolved#1070]
**关于哪一项功能**

**问题描述**

类似 #1043 所出现的显示问题 ，在夜间模式下，“天选”外面的透明层被黑色替换了，“天选”内中奖的用户名显示为白色

**脚本版本**
Preview v1.11.1
内容包: 884998a

**浏览器版本**

**错误信息**

**附加截图**
![截图_2020-10-27_13h47m01s](https://user-images.githubusercontent.com/67825783/97262327-91138c00-185b-11eb-85ea-9bcadfef8423.png)
![截图_2020-10-26_23h41m07s](https://user-images.githubusercontent.com/67825783/97262334-953fa980-185b-11eb-8bab-d9d426b50d51.png)

**Comment by Coulomb-G** [comment]
应该是误伤，会修的，但我不知道有哪个直播间会有稳定的天选时刻，所以也不一定马上就修

**Comment by LonelySteve** [comment]
![image](https://user-images.githubusercontent.com/34429322/103090846-45981700-462d-11eb-8332-25ad70c599a7.png)
![image](https://user-images.githubusercontent.com/34429322/103091206-67de6480-462e-11eb-8965-4d222f6e80ea.png)
![image](https://user-images.githubusercontent.com/34429322/103091223-79c00780-462e-11eb-84d0-4d44005be019.png)
