### ISSUE TITLE
在开启「简化评论区」功能后，评论区子评论操作的按钮占据了过长的空间

### ISSUE THREAD

**Issue by LonelySteve** [the1812/Bilibili-Evolved#1072]
**关于哪一项功能**

简化评论区

**问题描述**

- 在开启「简化评论区」功能后，评论区排版出了点小问题，子评论操作按钮占据了过长的空间，目测和 flex 布局有关系（原按钮用了浮动）
- 在夜间模式下，鼠标悬停下此按钮背景颜色依旧是 #E5E9EF，改成暗色应该会更好

**脚本版本**

Stable v1.11.0

**浏览器版本**

Chrome 86.0.4240.111

**附加截图**

![image](https://user-images.githubusercontent.com/34429322/97288659-2117fc80-1881-11eb-8bee-14841756e08a.png)

![image](https://user-images.githubusercontent.com/34429322/97288708-34c36300-1881-11eb-873e-1cf41bb2a384.png)

**Comment by Geeyun-JY3** [comment]
好像只是把按钮往左缩进了一下吧

**Comment by LonelySteve** [comment]
> 好像只是把按钮往左缩进了一下吧

问题描述已更新，这要打开「简化评论区」的功能才能复现

**Comment by Geeyun-JY3** [comment]
不开「简化评论区」功能夜间模式下这个按钮也没有适配。还有就是不开「简化评论区」功能时翻译按钮的位置是不是也错位了

**Comment by LonelySteve** [comment]
> 不开「简化评论区」功能夜间模式下这个按钮也没有适配。

是的，我已经在问题描述里补充了，不过这个问题倒不是很大，主要是开了「简化评论区」之后，这个按钮应用了一个 `operation` 类的样式，导致它会占据了过长的空间

> 还有就是不开「简化评论区」功能时翻译按钮的位置是不是也错位了

这个不清楚，我没怎么用过这个功能，不过我刚才开了一下这个功能，感觉也没啥大问题（虽然不知道原来的排版是不是这样的）

![image](https://user-images.githubusercontent.com/34429322/97319501-eb3a3e80-18a7-11eb-9618-9fe74e92afb4.png)

**Comment by Geeyun-JY3** [comment]
楼中楼的翻译按钮感觉有问题，原本应该是和楼层一样在评论下方的（不过我一直开着「简化评论区」功能也不知道之前是咋样🌚）
