### ISSUE TITLE
直播动态页直播列表显示重复

### ISSUE THREAD

**Issue by sq9960** [the1812/Bilibili-Evolved#1073]
**关于哪一项功能**
直播动态页直播列表显示重复

**问题描述**
某特定up直播会重复显示

**脚本版本**
Stable v1.11.0
内容包: 4764f4e

**浏览器版本**
Chromium 80.0.3987.163

**错误信息**
这个不会看，不好意思了

**附加截图**
![](https://ftp.bmp.ovh/imgs/2020/10/8b73811c2a6052b4.png)

**Comment by Geeyun-JY3** [comment]
重复：#924
