### ISSUE TITLE
关于鼠标中键点击B站链接 不加载脚本的问题

### ISSUE THREAD

**Issue by Fsky666** [the1812/Bilibili-Evolved#1074]
习惯了 鼠标中间先连续在后台新标签点开多个要看的视频 然后一个一个的标签看过来
发现只要用中间点击的 都不会加载网页 请问有什么方法可以兼容鼠标中间

**Comment by CKylinMC** [comment]
你试试看中键点视频标题  我这边可以的。

**Comment by the1812** [comment]
是火狐吗

**Comment by MC-dusk** [comment]
我是火狐，问题同，应该是触发模式的问题，必须左键单击，也就是"click"；右键然后点“在新标签页打开”，或中键单击直接在新标签页打开，脚本均不生效
