### ISSUE TITLE
打开视频页面，在登陆状态下，依然弹出登录框

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#1075]
**关于哪一项功能**

**问题描述**

[出问题时所在页面](https://www.bilibili.com/video/av970071946)
打开页面后 （确定是登陆状态）一部分图片（如up头像）无法加载，点赞等按钮弹出登陆，在弹出弹窗登陆后点赞继续弹出登录框。关闭脚本后正常。

**脚本版本**

Stable v1.11.0
内容包: 7b19953

**浏览器版本**

chrome 86.0.4240.111

**错误信息**

![image](https://user-images.githubusercontent.com/11648014/97389854-61758a00-1916-11eb-85e2-28d721fa2c08.png)
<details>
<summary>控制台日志</summary>
Navigated to https://www.bilibili.com/video/av970071946
DevTools failed to load SourceMap: Could not load content for chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
[Violation] '2P_238f095b-c637-4185-8bee-7791cdab94f4' handler took 228ms
VM4704:3 [Violation] Added synchronous DOM mutation listener to a 'DOMSubtreeModified' event. Consider using MutationObserver to make the page more responsive.
(anonymous) @ VM4704:3
R.d.addEventListener @ VM4715:49
eval @ userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:330
eval @ userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:356
(anonymous) @ VM4704:3
eval @ userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:1
eval @ userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:1
eval @ userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:357
eval @ userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:359
(anonymous) @ VM4704:3
c @ VM4704:2
(anonymous) @ VM4704:3
la @ VM4715:60
create @ VM4715:71
d @ VM4715:13
script_injector.js:2 pakku ajax: injecting hook
48XHR finished loading: GET "<URL>".
vendors.bundle.js:2539  ____ _____ _      _____ ____ _____ _      _____ _    _ ______ _      _____  ______ _____|  _ |_   _| |    |_   _|  _ |_   _| |    |_   _| |  | |  ____| |    |  __ \|  ____|  __ \| |_) || | | |      | | | |_) || | | |      | | | |__| | |__  | |    | |__) | |__  | |__) ||  _ < | | | |      | | |  _ < | | | |      | | |  __  |  __| | |    |  ___/|  __| |  _  /| |_) _| |_| |____ _| |_| |_) _| |_| |____ _| |_| |  | | |____| |____| |    | |____| | \ \|____|_____|______|_____|____|_____|______|_____|_|  |_|______|______|_|    |______|_|  \_\-... .. .-.. .. -... .. .-.. ..    .... . .-.. .--. . .-.   version: 1.2.24 from: video
vendors.bundle.js:2539  ____ _____ _      _____ ____ _____ _      _____ _    _ ______ _      _____  ______ _____|  _ |_   _| |    |_   _|  _ |_   _| |    |_   _| |  | |  ____| |    |  __ \|  ____|  __ \| |_) || | | |      | | | |_) || | | |      | | | |__| | |__  | |    | |__) | |__  | |__) ||  _ < | | | |      | | |  _ < | | | |      | | |  __  |  __| | |    |  ___/|  __| |  _  /| |_) _| |_| |____ _| |_| |_) _| |_| |____ _| |_| |  | | |____| |____| |    | |____| | \ \|____|_____|______|_____|____|_____|______|_____|_|  |_|______|______|_|    |______|_|  \_\-... .. .-.. .. -... .. .-.. ..    .... . .-.. .--. . .-.   version: 1.2.24 from: global
xhr_hook.js:2 pakku: [to developers] Web Worker is disabled for compatibility reasons
(anonymous) @ xhr_hook.js:2
(anonymous) @ xhr_hook.js:2
xhr_hook.js:2 pakku ajax: hook set
VM4778:1 <span class=​"tit">​[原神工具]原神面板模拟器V1.0​</span>​
VM4778:1 86 -10 72
userscript.html?name=Bilibili%20Evolved.user.js&id=d4004699-6139-4bd0-b825-8ad2eec86bf0:16152 scheduled bundle update
[Violation] Forced reflow while executing JavaScript took 42ms
2userscript.html?name=Bilibili%20Evolved.user.js&id=d4004699-6139-4bd0-b825-8ad2eec86bf0:13995 XHR finished loading: POST "https://api.bilibili.com/x/web-frontend/data/collector".
hook @ userscript.html?name=Bilibili%20Evolved.user.js&id=d4004699-6139-4bd0-b825-8ad2eec86bf0:13995
XMLHttpRequest.send @ userscript.html?name=Bilibili%20Evolved.user.js&id=d4004699-6139-4bd0-b825-8ad2eec86bf0:14018
XMLHttpRequest.send @ xhr_hook.js:2
value @ log-reporter.js:1
value @ log-reporter.js:1
value @ 3.5cb70.function.chunk.js:1
(anonymous) @ 3.5cb70.function.chunk.js:1
value @ 3.5cb70.function.chunk.js:1
success @ 3.5cb70.function.chunk.js:1
n.onreadystatechange @ log-reporter.js:1
thisArg.<computed> @ userscript.html?name=Bilibili%20Evolved.user.js&id=d4004699-6139-4bd0-b825-8ad2eec86bf0:14004
XMLHttpRequest.send (async)
hook @ userscript.html?name=Bilibili%20Evolved.user.js&id=d4004699-6139-4bd0-b825-8ad2eec86bf0:13995
XMLHttpRequest.send @ userscript.html?name=Bilibili%20Evolved.user.js&id=d4004699-6139-4bd0-b825-8ad2eec86bf0:14018
value @ log-reporter.js:1
(anonymous) @ 3.5cb70.function.chunk.js:1
value @ 3.5cb70.function.chunk.js:1
e @ 3.5cb70.function.chunk.js:1
(anonymous) @ log-reporter.js:1
Promise.then (async)
value @ log-reporter.js:1
value @ log-reporter.js:1
value @ log-reporter.js:1
t @ log-reporter.js:1
(anonymous) @ log-reporter.js:1
(anonymous) @ log-reporter.js:1
f @ log-reporter.js:1
(anonymous) @ log-reporter.js:1
(anonymous) @ log-reporter.js:1
userscript.html?name=Bilibili%20Evolved.user.js&id=d4004699-6139-4bd0-b825-8ad2eec86bf0:16154 downloading bundle
[Violation] 'setTimeout' handler took 531ms
userscript.html?name=Bilibili%20Evolved.user.js&id=d4004699-6139-4bd0-b825-8ad2eec86bf0:16267 zip version = 1.11.0
userscript.html?name=Bilibili%20Evolved.user.js&id=d4004699-6139-4bd0-b825-8ad2eec86bf0:16292 bundle updated
9[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:330 [Violation] 'setTimeout' handler took 299ms
jsc-player.a758e049.js:334 [Violation] 'setTimeout' handler took 408ms
VM4976:2 Fetch finished loading: GET "https://api.bilibili.com/x/player/playurl?cid=249562850&avid=970071946&qn=64&otype=json&fourk=0&requestFrom=bilibili-helper".
(anonymous) @ VM4976:2
e.getFlvResponse @ features.bundle.js:4688
(anonymous) @ features.bundle.js:4616
features.bundle.js:5158 Fetch finished loading: GET "https://api.bilibili.com/x/player.so?id=cid%3A249562850&aid=970071946&bvid=BV18p4y1k7Vi&buvid=B6A36DC4-5881-4AB3-8227-DF929EDF2E91155835infoc&from=bilibili-helper".
(anonymous) @ features.bundle.js:5158
xhr_hook.js:2 pakku ajax: ignoring request as no onload callback found https://api.bilibili.com/x/dm/filter/user?jsonp=jsonp
18XHR finished loading: GET "<URL>}}".
jsc-player.a758e049.js:264 load module pbp
DevTools failed to load SourceMap: Could not load content for chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
jsc-player.a758e049.js:279 [Websocket]: On Open.
[Violation] '2P_7bdaa0f0-74a2-4575-b5b1-88e05adf93ce' handler took 200ms
userscript.html?name=Bilibili%20Evolved.user.js&id=d4004699-6139-4bd0-b825-8ad2eec86bf0:16684 Skipped <iframe> loading for https://message.bilibili.com/pages/nav/index_new_pc_sync
VM4999:3 [Violation] Added synchronous DOM mutation listener to a 'DOMSubtreeModified' event. Consider using MutationObserver to make the page more responsive.
(anonymous) @ VM4999:3
R.d.addEventListener @ VM5003:49
eval @ userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:330
eval @ userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:356
(anonymous) @ VM4999:3
eval @ userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:1
eval @ userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:1
eval @ userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:357
eval @ userscript.html?name=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E7%AB%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA%20BilibiliLinksInfos.user.js&id=4317b894-abec-4b73-ace1-d5f6a81975b3:359
(anonymous) @ VM4999:3
c @ VM4999:2
(anonymous) @ VM4999:3
la @ VM5003:60
create @ VM5003:71
d @ VM5003:13
script_injector.js:2 pakku ajax: injecting hook
xhr_hook.js:2 pakku: [to developers] Web Worker is disabled for compatibility reasons
(anonymous) @ xhr_hook.js:2
(anonymous) @ xhr_hook.js:2
xhr_hook.js:2 pakku ajax: hook set
stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:1                      //         \\         //          \\       //    ##DDDDDDDDDDDDDDDDDDDDDD##    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|    ## MMMMMMMMMMMMMMMMMMMM ##    ##MMMMMMMMMMMMMMMMMMMMMM##                             Release 2.6.1. Powered by jinkela-core 2.8.3.         \/            \/
stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:40898)
    at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:57231)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:56494
    at f (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:56726)
    at h (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:57317)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:60655)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:60590)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:60590)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:61055)
    at a.t._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:34369)
hn.get @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7
hn @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7
(anonymous) @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7
Tn.$mount @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7
Tn.$mount @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7
(anonymous) @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:46
fo.onReady @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:46
So.onReady @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:46
(anonymous) @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:46
n @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:1
(anonymous) @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:32
n @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:1
(anonymous) @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:1
(anonymous) @ stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:1
xhr_hook.js:2 pakku ajax: ignoring request as no onload callback found https://data.bilibili.com/log/web?00111116038580229971603858021787|ugc|2.43.2-170fe612|web_load_danmuku|//api.bilibili.com/x/v2/dm/web/seg.so?type=1&oid=249562850&pid=970071946&segment_index=1|6b58a24ecf8c83a1667eb79f0e9cb035|||970071946|249562850|1|0|4|3|2|3|64|0||||{%22pcdn_video_type%22:%22dash%22,%22pcdn_stage%22:%22release%22,%22pcdn_group%22:%22nil%22,%22pcdn_version%22:%22nil%22,%22pcdn_vendor%22:%22nil%22,%22webAbTest%22:{}}
xhr_hook.js:2 pakku ajax: ignoring request as no onload callback found https://data.bilibili.com/log/web?00111116038580231001603858021907|ugc|2.43.2-170fe612|web_load_danmuku|//api.bilibili.com/x/v2/dm/web/seg.so?type=1&oid=249562850&pid=970071946&segment_index=3|6b58a24ecf8c83a1667eb79f0e9cb035|||970071946|249562850|1|0|4|3|2|3|64|0||||{%22pcdn_video_type%22:%22dash%22,%22pcdn_stage%22:%22release%22,%22pcdn_group%22:%22nil%22,%22pcdn_version%22:%22nil%22,%22pcdn_vendor%22:%22nil%22,%22webAbTest%22:{}}
xhr_hook.js:2 pakku ajax: ignoring request as no onload callback found https://data.bilibili.com/log/web?00111116038580232041603858021954|ugc|2.43.2-170fe612|web_load_danmuku|//api.bilibili.com/x/v2/dm/web/seg.so?type=1&oid=249562850&pid=970071946&segment_index=2|6b58a24ecf8c83a1667eb79f0e9cb035|||970071946|249562850|1|0|4|3|2|3|64|0||||{%22pcdn_video_type%22:%22dash%22,%22pcdn_stage%22:%22release%22,%22pcdn_group%22:%22nil%22,%22pcdn_version%22:%22nil%22,%22pcdn_vendor%22:%22nil%22,%22webAbTest%22:{}}
</details>

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/97389722-ff1c8980-1915-11eb-8ded-4d325c1cad75.png)

**Comment by the1812** [comment]
报错上跟#1076是一致的

**Comment by the1812** [comment]
已测试  是相同原因导致  可以参考 #1076 的解决办法
