### ISSUE TITLE
[外置稍后再看/启用快速收藏] 评论区, 选集, 相关推荐无法显示 / 弹出登录框

### ISSUE THREAD

**Issue by Shi-Guang-0901** [the1812/Bilibili-Evolved#1076]
**关于哪一项功能**

**问题描述**

**脚本版本**

正式版1.11.0

**浏览器版本**

Microsoft Edge
版本 86.0.622.56 (官方内部版本) (64 位)

**错误信息**

页面滚动到评论区出现如下错误
s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:40898)
    at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:57231)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:56494
    at f (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:56726)
    at h (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:57317)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:60655)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:60590)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:60590)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:61055)
    at a.t._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:7:34369)

**附加截图**

**Comment by WY-WY-W** [comment]
同问

**Comment by wwzw27** [comment]
同问 Google浏览器也是一样

**Comment by HCl233** [comment]
我也，但是退出登录的时候能够显示

**Comment by deathwood** [comment]
加一

**Comment by mrliu666666** [comment]
加一

**Comment by the1812** [comment]
关掉`外置稍后再看`和`启用快速收藏`

**Comment by Shi-Guang-0901** [comment]
我开了`外置稍后再看`没开`启用快速收藏`
关闭后恢复正常

**Comment by Shi-Guang-0901** [comment]
我开了`外置稍后再看`没开`启用快速收藏`

**Comment by the1812** [comment]
其实 #770 一样的  b站又改版  他那些代码还是一如既往的"因为页面多了几个按钮就会导致各种业务代码原地爆炸"

**Comment by Geeyun-JY3** [comment]
估计又会和 #770 一样 issue 爆炸了🤣

**Comment by the1812** [comment]
新 issue 模板里我加了个"记得看置顶"的提示, 但愿能起点作用

**Comment by BROBIRD** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
Firefox 82.0.1 x64
相同问题

**Comment by God-B** [comment]
哈哈哈，没看置顶的我太憨了，主要是随便翻了下没看到相似问题直接就反馈了，下次一定注意，打扰之处请多见谅，作者加油！

**Comment by Geeyun-JY3** [comment]
我在想，要是重复的 issue 暂时都不要关，全都给打上 `duplicate` 的 tag，就让进来 issue page 的人第一眼看到第一页的 issue 全是这些重复的 issue，这样震撼的场景能不能起到一点作用，让 issue 相对不那么爆炸🤔。

当然，要是全都通过更多菜单的 [反馈](https://github.com/the1812/Bilibili-Evolved/issues/new/choose) 直接进来反馈，那好像也没什么用🌚。

**Comment by the1812** [comment]
> 当然，要是全都通过更多菜单的 [反馈](https://github.com/the1812/Bilibili-Evolved/issues/new/choose) 直接进来反馈，那好像也没什么用🌚。

然而这里的链接直接进到 choose 就是你提的建议(

**Comment by Geeyun-JY3** [comment]
> 然而这里的链接直接进到 choose 就是你提的建议(

是的🌚
失算了（

**Comment by BROBIRD** [comment]
建议紧急发布一个修复版本

**Comment by Geeyun-JY3** [comment]
> 建议紧急发布一个修复版本

@BROBIRD 已经发了个热更新

**Comment by BROBIRD** [comment]
@Geeyun-JY3 并没有，很显然，1.11.0版本的tag还在12天前的commit上

**Comment by the1812** [comment]
热更新需要24h全部生效, 我昨晚发布的, 至少今晚才能有效

另外, 热更新不需要更新版本, tag 是不会变动的

**Comment by BROBIRD** [comment]
@the1812 刚才试了一下，似乎需要手动清除缓存才能生效

**Comment by Geeyun-JY3** [comment]
@BROBIRD 你得看 master 分支下这四个文件。而且 master 分支已经有 merge #1102 这个热更新 pr 的 commit 了（这样说没错吧）
![image](https://user-images.githubusercontent.com/49396421/97555417-10978b80-1a13-11eb-855e-56b023e243bc.png)
延迟是因为 jsDelivr。
~~←不懂装懂~~

**Comment by BROBIRD** [comment]
@Geeyun-JY3 测试过，其他源也是一样的，应该是需要清除缓存才能生效

**Comment by Geeyun-JY3** [comment]
反正热更新 [这个时候](https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-718280424) 已经出来了🌚（
清缓存更新才生效好像是常态，确实得优化一下

**Comment by consideration-ak** [comment]
哈哈哈, 好家伙, 我还以为我b站账号被官方黑了(捂脸

**Comment by capitalwell** [comment]
+1，这些问题都有

**Comment by Geeyun-JY3** [comment]
> 就让进来 issue page 的人第一眼看到第一页的 issue 全是这些重复的 issue

或者就留两三个在第一页顶部，打上 `duplicate` 的 tag。置顶看不到，位于第一页顶部的 issue 我看还是有不少人能看到并进去 +1 的。

**Comment by the1812** [comment]
> 或者就留两三个在第一页顶部，打上 `duplicate` 的 tag。置顶看不到，位于第一页顶部的 issue 我看还是有不少人能看到并进去 +1 的🌚。

挂了5个上去

**Comment by deathwood** [comment]
邮件爆炸了，我觉得可能是引导路径的问题
在插件页点击反馈的时候，跳转到 https://github.com/the1812/Bilibili-Evolved/issues/new/choose 
然后有些人没看就开始报告bug了，要是直接跳转到issues
https://github.com/the1812/Bilibili-Evolved/issues ，可能就不会重复提交了

**Comment by Geeyun-JY3** [comment]
> 挂了5个上去

要是后面还有新的，就轮替，最好保证挂着五个标题各不相同的🐶，差别越大越好🌚

> 我觉得可能是引导路径的问题
> 在插件页点击反馈的时候，跳转到 https://github.com/the1812/Bilibili-Evolved/issues/new/choose
> 然后有些人没看就开始报告bug了，要是直接跳转到issues
> https://github.com/the1812/Bilibili-Evolved/issues ，可能就不会重复提交了

当初跳转到 `https://github.com/the1812/Bilibili-Evolved/issues/new/choose` 的 [建议](https://github.com/the1812/Bilibili-Evolved/issues/892#issuecomment-687945910) 是 [我提的](https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-718036466)🌚，先出来挨打谢罪。

其实 issue 模板里也有写：
> 发之前记得看下置顶问题 (Pinned issues)(如果有的话)
> https://github.com/the1812/Bilibili-Evolved/issues

可大把人就是 [不看](https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717701804)🌚。

我不知道和设置面板这个 `反馈` 有没有关系，但上一次 #770 的时候设置面板也还没加这个反馈按钮，issue 照样爆炸🌚。

**Comment by Geeyun-JY3** [comment]
估计和这次改版这个刚出来的记笔记也有关系：
![image](https://user-images.githubusercontent.com/49396421/98209060-455a9400-1f79-11eb-99e8-172754e2bb39.png)

**Comment by consideration-ak** [comment]
> 估计和这次改版这个刚出来的记笔记也有关系：
> ![image](https://user-images.githubusercontent.com/49396421/98209060-455a9400-1f79-11eb-99e8-172754e2bb39.png)<img alt="" width="16" height="16" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAdtJREFUOBHFUs9LVGEUPfe9lzb+ahQ0Bg1sEdaQC2nhM4nMTZg2C6GF06JN0CLobwihf8BWgWtdSIqmhm1GMFNo4aaFUKQoAyFBBaON1Jvbvdf5hsfkMugM3/ede+4537y5b4D/Dep/m2mMvkdPmLj+DNPk2vDiTricGaVSdB1EnfaAzLvs+e827yzM3lgaufiL+CExHfpJf4LCxeF5Zs6okYjyYD5goMeCVRsBW2JqE3972b8QgDHofOWGNZ0WP+1ilt1Bsh7AOVfHz7oggaGOQVvKTwfnvLMN9Vl5tElnOHrzFT55eN77DI/bH9hSrpr2HDSjWW/11kyBibZcI3GzBWHrNTQV6tAfhraUq6Y9B81oNlBBbrvifhnVekgnu5BKpTB2P2t+5emfXVg/eO/yltHCLgDxkQyzgmRNE4IgwNPx8Yp2rqaxwo1oRiBDtGPn5DzZi1ExXho/jo6rNM8ydoGH0ma8u/3jU7w0Xq25jK/d/amPXy5kL3ULTWu9V8ijpbYZ5xOtKMo3r+RXMfV5DiX5KGRmLzdGlifK3DQM5O41FAuHL5gwJvMQzykgyD8e0/L6HukbUMdfxr6Vu5f5dzTETFel2awmme83Iv5Agf964/arbdX+Gf4AGR+gT8wubJYAAAAASUVORK5CYII=">

啥玩意, b站真把自己当学习网站了? 还出个记笔记, 笑死. 建议去舞蹈区记笔记

**Comment by Coulomb-G** [comment]
> 啥玩意, b站真把自己当学习网站了? 还出个记笔记, 笑死. 建议去舞蹈区记笔记
不喜欢也别往这倒垃圾,这个功能确实是有实际需求的

**Comment by deathwood** [comment]
> > 估计和这次改版这个刚出来的记笔记也有关系：
> > ![image](https://user-images.githubusercontent.com/49396421/98209060-455a9400-1f79-11eb-99e8-172754e2bb39.png)
> 
> 啥玩意, b站真把自己当学习网站了? 还出个记笔记, 笑死. 建议去舞蹈区记笔记

自己不用就不让别人用？要对线去b站客服，在这里开团就挺离谱的

**Comment by Geeyun-JY3** [comment]
> 要对线去b站客服，在这里开团就挺离谱的

所以请你也这么做。

**Comment by Geeyun-JY3** [comment]
@consideration-ak 莫名其妙，我在这正常反馈。

@deathwood 刚刚那条看错了，会错了，已删。

**Comment by deathwood** [comment]
> @consideration-ak 莫名其妙，我在这正常反馈。
> 
> @deathwood 刚刚那条看错了，回错了，抱歉，已删。

fine，辛苦了

**Comment by the1812** [comment]
不过要彻底解决这个问题我还没什么头绪...
必须要找到一个“标志”, 判断出b站的播放器彻底加载完成, 可以安全地把稍后再看按钮之类的加进去

最早是判断“点赞/投币的数字从`--`变成实际数字”, 过了段时间发生了 #770 
之后改成了“视频信息里的弹幕数出现实际数字”, 过了段时间就是本次的 #1076
现在我也找不到该拿什么判断了(

**Comment by Geeyun-JY3** [comment]
难道要打上 `help wanted` 的 tag 了🤣？

**Comment by the1812** [comment]
<img src="https://i0.hdslb.com/bfs/emote/bba7c12aa51fed0199c241465560dfc2714c593e.png" width="20" height="20" alt="doge">

**Comment by 11111111111ge1** [comment]
> 不过要彻底解决这个问题我还没什么头绪...
> 必须要找到一个“标志”, 判断出b站的播放器彻底加载完成, 可以安全地把稍后再看按钮之类的加进去
> 
> 最早是判断“点赞/投币的数字从`--`变成实际数字”, 过了段时间发生了 #770
> 之后改成了“视频信息里的弹幕数出现实际数字”, 过了段时间就是本次的 #1076
> 现在我也找不到该拿什么判断了(

要不直接给用户一个选项, 打开页面后*秒 添加按钮 
(刚才又出这个问题了,还以为是插件又有bug 看这边没人反馈,去找了下 结果发现是adblock的问题😂)

**Comment by the1812** [comment]
adblock也是我的锅, 简化首页要求安装的规则今天突然也会炸掉播放器

**Comment by Geeyun-JY3** [comment]
最近播放页改动挺多的，暂停的小电视图标微调了；鼠标经过迷你播放器能看到暂停小电视图标
还有用正式版开启自定义顶栏后页面一开始加载还能看到一会原版顶栏，要等一会才会完全消失

**Comment by the1812** [comment]
找到个办法了, 预计 v1.11.5 开放测试 (仅预览/预览离线版可用), 禁掉的 3 个功能可以再度开启了

**Comment by Geeyun-JY3** [comment]
`外置稍后再看` 开启后 `稿件投诉` 和 `记笔记` 按钮位置错位
![image](https://user-images.githubusercontent.com/49396421/101176429-71089100-3681-11eb-8357-40441279ba90.png)

（话说 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-722980800 的狗头是怎么弄的鸭🙈

**Comment by the1812** [comment]
这... 你宽度实在太小了吧
![image](https://user-images.githubusercontent.com/26504152/101186116-9e5b3c00-368d-11eb-94b6-7671e58d46a2.png)

狗头<img src="https://i0.hdslb.com/bfs/emote/bba7c12aa51fed0199c241465560dfc2714c593e.png" width="20" height="20" alt="doge">是用 img 来指定尺寸 `<img src="https://i0.hdslb.com/bfs/emote/bba7c12aa51fed0199c241465560dfc2714c593e.png" width="20" height="20" alt="doge">`

**Comment by Geeyun-JY3** [comment]
> 这... 你宽度实在太小了吧

（卑微，所以一直就外置了一个稍后再看
或者做个类似于响应式布局的适配（即当宽度过小时后面的 `稿件投诉` `记笔记` 收进更多菜单里，至少 `稿件投诉` 可以收进去）？

b 站表情图片链接是直接去 b 站复制？

**Comment by Geeyun-JY3** [comment]
> 这... 你宽度实在太小了吧

（卑微，所以一直就外置了一个稍后再看
或者做个类似于响应式布局的适配（即当宽度过小时后面的 `稿件投诉` `记笔记` 收进更多菜单里，至少 `稿件投诉` 可以收进去）？

b 站表情图片链接是直接去 b 站复制？

**Comment by the1812** [comment]
对啊, 复制图片链接

**Comment by Geeyun-JY3** [comment]
> 或者做个类似于响应式布局的适配（即当宽度过小时后面的 `稿件投诉` `记笔记` 收进更多菜单里，至少 `稿件投诉` 可以收进去）？

要不干脆就做一个 `隐藏记笔记` 的功能，将 `记笔记` 收进更多菜单里，反正应该也有不少人不想看到这个按钮。

**Comment by the1812** [comment]
应该可以响应式布局, 把那两个的文字缩一下

**Comment by Geeyun-JY3** [comment]
像我这种窄得得要命同时开 `快速收藏` 和 `外置稍后再看` 就算缩文字也还会折行的情况考虑适配吗🌚
![image](https://user-images.githubusercontent.com/49396421/111060089-70c82f00-84d5-11eb-9e1d-2b49b11dbd06.png)
