### ISSUE TITLE
开启“外置稍后再看”或者“启用快速收藏”后，视频播放页面会出bug

### ISSUE THREAD

**Issue by VXleaf** [the1812/Bilibili-Evolved#1077]
**关于哪一项功能**

**问题描述**
在 设置-视频 中 开启“外置稍后再看”或“启用快速收藏”后，视频播放页面会出bug，up主头像、视频选集还有下方的评论区会加载不出来。

**脚本版本**
1.11.0

**浏览器版本**
Edge(chromium内核) 86.0.622.51

**错误信息**
不知道应该填哪些....

**附加截图**
![image](https://user-images.githubusercontent.com/56925098/97392328-7bb26680-191c-11eb-8cfa-7dd14d2d665f.png)

**Comment by Geeyun-JY3** [comment]
看置顶：#1076
重复了
