### ISSUE TITLE
视频选集不显示，关闭插件后显示恢复

### ISSUE THREAD

**Issue by GGBond20** [the1812/Bilibili-Evolved#1078]
**插件开启后视频选集不显示视频**

**问题描述**
打开插件后任意一个视频选集不显示视频，关闭插件后正常显示。
例如：https://www.bilibili.com/video/BV1G54y1B7Hn/

**脚本版本**
正式版1.11.0

**浏览器版本**

QQ浏览器10.6.1（4212）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/18441916/97400315-e027f280-1929-11eb-816c-9e5ca5136583.png)

**Comment by the1812** [comment]
解决方法见 #1076

**Comment by ShainEli** [comment]
+1 
脚本版本 1.11.1

Google Chrome Version 88.0.4305.0 (Official Build) canary (x86_64)

**Comment by GGBond20** [comment]
> 解决方法见 #1076

已按方法解决，反馈之前也看了搜了issue，可能没看仔细。谢谢。
