### ISSUE TITLE
[问题反馈]开启脚本后某些功能显示不正常

### ISSUE THREAD

**Issue by 1135108813** [the1812/Bilibili-Evolved#1079]
**关于哪一项功能**

脚本本身与b站选集列表，up主头像，视频选集，相关推荐冲突

**问题描述**

开启脚本后冲突的界面不显示，关闭脚本后正常。
今天开始发现的，所有的视频都出现了这个问题。最近一段时间没有修改过脚本的设置项。

**脚本版本**

1.11.0

**浏览器版本**

86.0.4240.75

**错误信息**

![image](https://user-images.githubusercontent.com/46586346/97403858-1f594200-1930-11eb-854f-141dd4213040.png)
![image](https://user-images.githubusercontent.com/46586346/97403894-2e3ff480-1930-11eb-8cad-6f23fa9e6005.png)

**附加截图**
![image](https://user-images.githubusercontent.com/46586346/97403956-46b00f00-1930-11eb-8880-5032064600ea.png)
![image](https://user-images.githubusercontent.com/46586346/97403970-4dd71d00-1930-11eb-92f2-e749ab8bc880.png)

**Comment by the1812** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
