### ISSUE TITLE
今日(2020.10.28)上午开始出现的开启脚本就无法看到评论区且无法看到右侧推荐视频封面的问题

### ISSUE THREAD

**Issue by MOYUtianming** [the1812/Bilibili-Evolved#1080]
**关于哪一项功能**
脚本整体

**问题描述**

问题如题 , 已经尝试过如下方法:
* 重新安装脚本;
* 切换多个视频;
* 重启电脑;
* 重启脚本;
![屏幕截图 2020-10-28 150813](https://user-images.githubusercontent.com/47681299/97403509-80344a80-192f-11eb-8a6d-d374deeb3418.jpg)

**脚本版本**

正式版1.11.0

**浏览器版本**

使用的是MicrosoftEdgeBeta , 版本号:87.0.664.12

**错误信息**

依据你提供的教程找到的错误提示 , 由于我不是专业的网页编辑人员 , 无法指明那些有用 , 只好全都截图了.
![image](https://user-images.githubusercontent.com/47681299/97404175-9f7fa780-1930-11eb-9322-eb161b3f5183.png)

**附加截图**

**Comment by MOYUtianming** [comment]
补充:脚本开启之后点赞投币和评论功能都失效了.

**Comment by MOYUtianming** [comment]
作者加油.

**Comment by the1812** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
