### ISSUE TITLE
快捷键调整播放速度，视频下栏的 倍速 不会跟着变动

### ISSUE THREAD

**Issue by zkzmba793** [the1812/Bilibili-Evolved#1083]
**关于哪一项功能**
快捷键扩展 -> shift+↑/↓ 播放速度调整

**问题描述**
使用 快捷键调整速度，视频下面的 倍速 不会跟着变动，但是视频的速度还是会改变的

**脚本版本**
Preview Offline v831.97

**浏览器版本**
Chrome 86.0.4240.111（正式版本） （64 位）

**错误信息**
没有

**附加截图**
![1](https://user-images.githubusercontent.com/73212412/97413538-df00c080-193d-11eb-90dd-aef3047ed3f3.png)

**Comment by the1812** [comment]
这里我可以改成同步一下, 但是鼠标放上去出来那个菜单可能不会更新

**Comment by x1shi** [comment]
@the1812 
- - -
小菜鸟有一些疑惑。

我看了下[默认播放速度的实现](https://github.com/the1812/Bilibili-Evolved/blob/master/src/video/default-video-speed.ts)，里面直接改了video标签对象的播放速度（不知道这个issues提到的快捷键是否为同样的实现）。为什么不 `.click()` B站H5播放器的 **倍速** 里的选项呢？

感觉这样直接越过B站提供的交互系统，很容易出现问题啊。比如我看代码的原因，就是发现默认播放速度设置为 **2.0** 后，H5播放器的 **倍速** 还是保持在 **1.0** ；我想切回实际上的1.0播放速度，还需要通过随便点个其它速度（ **1.0** 之外）的选项，再点 **1.0** 才行。

**Comment by the1812** [comment]
@x1shi 
当时还没有这个选项, 以前倍速是放在右键菜单里的
而且以前的右键菜单是和 video 同步数据的, 我直接改 video 的速度, 它那里也会自动变过来, 不像现在这样反而退化了
不过无论是在右键菜单还是现在控制栏上, 倍速列表都是懒加载的, 也就是你必须先至少模拟右键点击/鼠标经过倍速字样那里, 才有东西可以`.click()`, 所以我想不要去假设 b 站有哪些元素可以点, 否则将来哪天又换了个位置这个功能直接就用不了了
