### ISSUE TITLE
播放界面右侧播放列表消失

### ISSUE THREAD

**Issue by ateekamori** [the1812/Bilibili-Evolved#1085]
最开始出现在EDGE，以为是浏览器的问题，故重装，未出现，重新安装脚本之后再次出现列表消失的情况，使用最新版chrome，安装脚本之后同样出现。

**附加截图**
![image](https://user-images.githubusercontent.com/17025315/97417419-a0213980-1942-11eb-8f29-d3d0b97afbb2.png)

**Comment by the1812** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
