### ISSUE TITLE
“外置稍后再看”会导致选P列表空白，”相关推荐“的缩略图空白且无法点击

### ISSUE THREAD

**Issue by kyobox** [the1812/Bilibili-Evolved#1086]
问题描述：打开该脚本后，选P列表空白，”相关推荐“的缩略图空白且无法点击。但B站自己的番剧则不受影响。经查证，是“外置稍后再看”这个功能所影响，关闭则正常了

浏览器：Microsoft Edge 86.0.622.56 (官方内部版本) (64 位)
脚本：1.11.0

**Comment by 123336-mike** [comment]
“外置稍后再看”会导致评论区消失，关闭后显示正常
浏览器：百分浏览器版本 4.2.10.171（正式版本） （32 位） (Chromium 80.0.3987.163)
脚本版本：1.11.0

**Comment by Coulomb-G** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
