### ISSUE TITLE
视频界面up主头像和下方评论无法显示

### ISSUE THREAD

**Issue by darkness4399** [the1812/Bilibili-Evolved#1089]
**关于哪一项功能**
页面改动

**问题描述**

进入页面后，up主头像和推荐视频的图片无法显示，下方评论界面无法显示，点击视频下方点赞投币等显示账号未登录。
其他功能正常
https://www.bilibili.com/video/BV1gy4y1871o
**脚本版本**

1.11.0

**浏览器版本**

版本 86.0.4240.111（正式版本） （32 位） 谷歌
**错误信息**

**附加截图**
![%(TPTS8O1W3}2}@V0UE}75X](https://user-images.githubusercontent.com/73587388/97424889-52a9ca00-194c-11eb-9672-60405543bb03.png)

**Comment by Coulomb-G** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
