### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by lemako** [the1812/Bilibili-Evolved#109]
两个都测试过了

**关于哪一项功能**

高分辨率图片
**问题描述**

首页，所有图片无法显示，关闭脚本则正常

**脚本版本**

全部都是最新版

**浏览器版本**

Chromium 72.0.3626.121

**错误信息**

Failed to load resource: the server responded with a status of 400 (Bad Request)

**附加截图**

**Comment by the1812** [comment]
我可能忘记对125%, 150%这些倍数计算的分辨率取整数了... 多刷新几次, 现在应该正常了

**Comment by lemako** [comment]
已经解决 感谢
