### ISSUE TITLE
通过快捷键或点击播放器静音按钮将视频静音时出现静音提示

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1090]
**关于哪一项功能**
快捷键扩展
播放器相关

**期望的效果**
通过快捷键 <kbd>m</kbd> 或点击播放器静音按钮将视频静音时，希望能出现静音提示，就像现有的通过 <kbd>↓</kbd> 将音量调至 0% 时出现的提示（其实挺奇怪为啥官方没给点静音按钮做这个提示）
![image](https://user-images.githubusercontent.com/49396421/97424067-25a8e780-194b-11eb-83d6-2ad3597f48e6.png)

**脚本版本**
正式版本 v1.11.0 内容包: e951ab1
预览离线版 v831.97

**Comment by Geeyun-JY3** [comment]
是不是忘了点击播放器控制栏的静音按钮也显示提示文字（

**Comment by the1812** [comment]
那个是 b 站的事情了, 我的提示文字是快捷键扩展里发起的 (

**Comment by Geeyun-JY3** [comment]
好的吧（
