### ISSUE TITLE
无法加载评论

### ISSUE THREAD

**Issue by fly9593** [the1812/Bilibili-Evolved#1091]
**关于哪一项功能**

**问题描述**

看视频无法加载评论，关掉这个脚本能够加载

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**
![屏幕截图 2020-10-28 190441](https://user-images.githubusercontent.com/59961051/97428123-80910d80-1950-11eb-9e30-66650b936abe.png)
#

**Comment by Geeyun-JY3** [comment]
看
置
顶
#1076
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
