### ISSUE TITLE
删除问题

### ISSUE THREAD

**Issue by stanhuo** [the1812/Bilibili-Evolved#1092]
**关于哪一项功能**
删除不了

**问题描述**

**脚本版本**

预览版v1.11.0

**浏览器版本**

Google Chrome 
版本 86.0.4240.111

**错误信息**

Unchecked runtime.lastError: The message port closed before a response was received.

scheduled bundle update
VM516:9052 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
VM516:9061 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
VM518:16156 downloading bundle
sentry-5.7.1.min.js:2 zip version = 1.11.0
VM518:16269 zip version = 1.11.0
sentry-5.7.1.min.js:2 bundle updated
VM518:16294 bundle updated
DevTools failed to load SourceMap: Could not load content for chrome-extension://pjhmkencgbobkkmdhiolfliahmfejlko/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://pjhmkencgbobkkmdhiolfliahmfejlko/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/vue.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**附加截图**

**Comment by the1812** [comment]
进 Tampermonkey 看下脚本列表?
![image](https://user-images.githubusercontent.com/26504152/97430430-d7e4ad00-1953-11eb-83a1-fefc382e64f5.png)
