### ISSUE TITLE
开着插件时b站评论和推荐视频封面会打不开，点赞投币收藏这几个功能会弹出登陆选项框但是登陆没有用

### ISSUE THREAD

**Issue by rotorf** [the1812/Bilibili-Evolved#1094]
**关于哪一项功能**

**问题描述**

开着插件时b站评论和推荐视频封面会打不开，点赞投币收藏这几个功能会弹出登陆选项框但是登陆没有用

**脚本版本**

Bilibili Evolved (Preview Offline) | 831.97

**浏览器版本**

Microsoft Edge 
版本 88.0.673.0 (官方内部版本) Dev (64 位)

**错误信息**

<img width="1601" alt="iShot2020-10-28 19 17 02" src="https://user-images.githubusercontent.com/73589179/97429294-30b34600-1952-11eb-8630-780d2df785e9.png">

**附加截图**

**Comment by Geeyun-JY3** [comment]
看
置
顶
#1076
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480

**Comment by Coulomb-G** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
