### ISSUE TITLE
观看视频时的问题

### ISSUE THREAD

**Issue by Zxixiichan** [the1812/Bilibili-Evolved#1096]
**关于哪一项功能**
视频

**问题描述**

观看任意视频时，up主头像不显示，只有灰白；选集列表不显示内容，只有一片灰白；相关推荐不显示视频封面，封面区域也同样为灰白。此问题在关闭脚本后可以正常显示。

**脚本版本**

Stable 1.11.0

**浏览器版本**

86.0.4240.111（正式版本）

**错误信息**

**附加截图**
![截图](https://user-images.githubusercontent.com/67000455/97431982-29207c80-1913-11eb-843c-022b4685d077.png)

**Comment by Coulomb-G** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
