### ISSUE TITLE
登录之后投币还提示登录,禁用插件之后登陆投币就没有问题

### ISSUE THREAD

**Issue by 1471246901** [the1812/Bilibili-Evolved#1099]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
