### ISSUE TITLE
选集列表无法正常显示

### ISSUE THREAD

**Issue by LC19990929** [the1812/Bilibili-Evolved#1100]
**关于哪一项功能**
视频选集列表

**问题描述**
视频选集列表里面的字无法加载出来，网页内的某些图片（视频up的头像、下方推荐视频的封面图片）无法加载

**脚本版本**
1.11.0

**浏览器版本**
QQ浏览器（Chrome 70.0.3538.25）

**错误信息**
![image](https://user-images.githubusercontent.com/45485912/97434944-b935e480-195a-11eb-8dbe-e18abaa479c1.png)

**附加截图**
![image](https://user-images.githubusercontent.com/45485912/97434725-678d5a00-195a-11eb-90af-8dba3ffd736b.png)

**Comment by hhecc** [comment]
Microsoft Edge 版本 86.0.622.51 (官方内部版本) (64 位) 出现一样的情况

**Comment by Coulomb-G** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)

**Comment by LC19990929** [comment]
> 解决方法见 [#1076 (comment)](https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480)
> (Duplicate of #1076)

啊 好了！ 感谢！！！
