### ISSUE TITLE
新版本更新之后评论区被更新没了

### ISSUE THREAD

**Issue by Yoclouislp** [the1812/Bilibili-Evolved#1101]
新版本更新之后原有的页面内的评论功能直接变为空白内容，对评论相关的开关按钮反复尝试打开关闭后，并无效果，直至整个脚本关闭后生效，确认非AD工具屏蔽所导致的失效。

加载过程中发现H5的评论区域是直接被屏蔽掉的

**Comment by LonelySteve** [comment]
请看置顶 issue（#1076）
