### ISSUE TITLE
视频页面点赞弹出B站登录窗口,尽管已经是登录状态,且console持续报错

### ISSUE THREAD

**Issue by alleriagit** [the1812/Bilibili-Evolved#1104]
**关于哪一项功能**

**问题描述**

【BUG】打开某个视频, 在视频页面点赞时, 弹出B站登录窗口, 尽管已经是登录状态, 且console持续报错. 关闭本脚本后可以正常点赞.

视频:https://www.bilibili.com/video/BV1LZ4y1V7LP

**脚本版本**

@name         Bilibili Evolved
@version      1.11.0

**浏览器版本**

版本 85.0.4183.83（正式版本） （64 位）

**错误信息**

stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:46 

Uncaught TypeError: Cannot read property 'clearRect' of null
    at a.drawRing (stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:46)
    at stardust-video.02ab45c3129d024d1d65cbf917f4c9680685c76e.js:46

**附加截图**
![bug-1](https://user-images.githubusercontent.com/30452490/97440763-db336500-1962-11eb-91b3-674551539cff.png)
![bug-2](https://user-images.githubusercontent.com/30452490/97440777-df5f8280-1962-11eb-807f-cfc3d86dc8e4.png)

**配置文件**
[bilibili-evolved-settings.zip](https://github.com/the1812/Bilibili-Evolved/files/5452077/bilibili-evolved-settings.zip)

**Comment by Coulomb-G** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
