### ISSUE TITLE
加载问题

### ISSUE THREAD

**Issue by ben714** [the1812/Bilibili-Evolved#1106]
**关于哪一项功能**

**问题描述**

从10/29/2020开始，进入B站任何视频，评论区为空，视频选集为空，相关推荐的视频图片为空。
关闭脚本后，一切正常。

**脚本版本**

1.11.0

**浏览器版本**

Chrome 81.0.4044.138

**错误信息**

**附加截图**
![1](https://user-images.githubusercontent.com/58157926/97442431-f495da80-197d-11eb-90cd-808da89b5079.JPG)
![2](https://user-images.githubusercontent.com/58157926/97442439-f8296180-197d-11eb-8185-fd7024883edb.JPG)
![3](https://user-images.githubusercontent.com/58157926/97442464-fe1f4280-197d-11eb-97c0-43e07bb07a6e.JPG)
![4](https://user-images.githubusercontent.com/58157926/97442481-037c8d00-197e-11eb-97ba-4ec86f28e9ab.JPG)

**Comment by Geeyun-JY3** [comment]
看
置
顶
#1076
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
而且已经有一个热更新了#1102

**Comment by the1812** [comment]
@Geeyun-JY3 (热更新要明晚才能起效

**Comment by Geeyun-JY3** [comment]
> 热更新要明晚才能起效

更新源换 GitHub  是不是马上就行了

**Comment by the1812** [comment]
> 更新源换 GitHub 是不是马上就行了

啊, 那个有墙已经被我遗忘了(
