### ISSUE TITLE
在视频播放页点赞会反复提示登录并且评论栏无显示

### ISSUE THREAD

**Issue by CreamPan99** [the1812/Bilibili-Evolved#1107]
**关于哪一项功能**
视频播放

**问题描述**

在视频播放页点赞会反复提示登录并且评论栏无显示

**脚本版本**

1.11.0

**浏览器版本**

Chrome 86.0.4240.111
**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/73597974/97447656-bd69fe00-196a-11eb-94e1-bb9f8a6504c1.png)

**Comment by Geeyun-JY3** [comment]
看
置
顶
#1076
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
