### ISSUE TITLE
up上传视频看不到评论和相关推荐视屏封面

### ISSUE THREAD

**Issue by God-B** [the1812/Bilibili-Evolved#1108]
由up上传视频看不到评论和相关推荐视屏封面
![image](https://user-images.githubusercontent.com/56873262/97450234-7af5f080-196d-11eb-8a93-8891b814e60c.png)
![image](https://user-images.githubusercontent.com/56873262/97450275-86e1b280-196d-11eb-9c71-c3c5ee86f949.png)
番剧中能显示
![image](https://user-images.githubusercontent.com/56873262/97450356-9eb93680-196d-11eb-80c3-4b413d55112c.png)
关闭此脚本后都能正常显示，只开此脚本也无法显示，故判断为此脚本的bug

**Comment by Damage0413** [comment]
感觉b站又改了播放界面，之前改的时候也是这种情况

**Comment by Coulomb-G** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
