### ISSUE TITLE
最新版视频播放页不显示小图

### ISSUE THREAD

**Issue by lsh1215225** [the1812/Bilibili-Evolved#1109]
![image](https://user-images.githubusercontent.com/20274559/97451582-d8d70800-196e-11eb-8159-16d4504ce84c.png)

**Comment by Coulomb-G** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)

**Comment by God-B** [comment]
置顶问题

**Comment by God-B** [comment]
里有解决方案
