### ISSUE TITLE
播放界面无法获取账号信息

### ISSUE THREAD

**Issue by starseekers** [the1812/Bilibili-Evolved#1111]
**关于哪一项功能**
播放界面

**问题描述**

视频播放页无法加载评论
无法投币点赞收藏

**脚本版本**

stable v1.11

**浏览器版本**

版本 86.0.4240.111（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/35815213/97453095-5f401980-1970-11eb-8ff5-cd8a326a00ff.png)
![image](https://user-images.githubusercontent.com/35815213/97453203-7c74e800-1970-11eb-851c-e96d01b3ce82.png)
![image](https://user-images.githubusercontent.com/35815213/97453302-8eef2180-1970-11eb-8aa1-9f44fcc28bd1.png)
![image](https://user-images.githubusercontent.com/35815213/97453352-9a424d00-1970-11eb-856f-0a5b048704c1.png)

**Comment by Coulomb-G** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
