### ISSUE TITLE
没有评论，在点赞投币时需要登陆，但是登录后无法点赞投币，需要再登录，无线套娃

### ISSUE THREAD

**Issue by died23333** [the1812/Bilibili-Evolved#1114]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
看！
置！
顶！
#1076
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
