### ISSUE TITLE
2个问题1自动定位到播放器和网页无法访问问题

### ISSUE THREAD

**Issue by nyano** [the1812/Bilibili-Evolved#1115]
**关于哪一项功能**

**问题描述**
2个问题都存在很长时间
1.自动定位到播放器：当视频页面在后台（非前台）时，等一段时间转到前台时，此项无效。因为只有当视频页面转为前台时，页面才加载播放器，可能定位在打开页面（后台）时定位了，但转到前台时才加载播放器，造成失效。=》指宽屏状态页面被下拉了
2.【部分时候】，打开插件会造成【*.hdslb.com】无法访问，体现为视频能播放，但弹幕列表、评论、视频清单、图片等等等全部无法被访问，切换代理也无效=》【测试证明为 设置-视频-外置稍后再看 A和启用快速收藏 B双重 所造成的问题，关闭解决】
测试A开B关 失败，A开B开，失败,A关B开，失败 A关B关正常

**脚本版本**
任意版本

**浏览器版本**
EDGE

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
看！
置！
顶！
#1076
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480

可以肯定的是第二个问题同 #1076，没猜错的话第一个问题也是 #1076 相关的 bug。

**Comment by the1812** [comment]
自动定位一样是 #1076 的, 只是不会炸掉评论区那些, 所以我就没说关不关, 不过热更新后都是会禁用掉的
