### ISSUE TITLE
视频不加载评论区及右侧推荐封面

### ISSUE THREAD

**Issue by SephyrZ** [the1812/Bilibili-Evolved#1116]
**关于哪一项功能**
俺也不知道具体啥功能

**问题描述**

任何普通视频页 截图里是av797500958

**脚本版本**

Stable v1.11.0

**浏览器版本**

Edge Chromium 86.0.622.56

**错误信息**

视频页边上推荐封面加载不出
视频评论加载不出
视频下面点赞投币收藏都要我登录 登录也没用
普通视频有以上问题 番剧视频没问题
人在海外 装了回国脚本 不知道有没有关系

**附加截图**
![image](https://user-images.githubusercontent.com/71286157/97468975-e01cf800-1913-11eb-8ad1-d34d8137f543.png)

**Comment by AnyoeDove** [comment]
人在国内 一样的情况

**Comment by yanweijia** [comment]
浏览器 safari,  国内, 未挂代理, 一样情况

**Comment by Lz1y** [comment]
人在国内 一样的情况

**Comment by GM01010** [comment]
Chrome 國外 沒掛
同樣沒評論

**Comment by Lz1y** [comment]
解决了：
关掉外置稍后再看和启用快速收藏


https://github.com/the1812/Bilibili-Evolved/issues/1076

**Comment by DFExpress** [comment]
同样不加载评论区，360极速浏览器(chrome78.0内核)，脚本版本1.11.0。

**Comment by Geeyun-JY3** [comment]
求求你们
看！
置！
顶！
#1076
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
