### ISSUE TITLE
火狐+暴力猴无下载等附加功能

### ISSUE THREAD

**Issue by Felix2yu** [the1812/Bilibili-Evolved#112]
**关于哪一项功能**
附加功能

**问题描述**
使用火狐 67+暴力猴 2.10.4，即使是在全新的火狐个人配置下也没有查看封面、下载视频等附加功能。Chrome+同版本2.10.4的暴力猴测试无问题。

**脚本版本**
278.79

**浏览器版本**
火狐 67

**错误信息**

**附加截图**

**Comment by the1812** [comment]
(同#90)
这个我也没搞懂为什么, 而且暴力猴还找不到调试的地方
结合你的测试结果, 现在变成这样了:

|  | Chrome | Firefox |
|--|--|--|
| Tampermonkey | √ | √ |
| Violentmonkey(暴力猴) | √ | × |

到底是暴力猴有什么特殊点还是火狐有什么特殊点呢...

**Comment by the1812** [comment]
更新下预览离线版试试吧, 我总算让火狐+暴力猴出现附加功能了...
火狐确实有些特殊的地方,  详见 #90. 另外, 我测试的时候暴力猴也出了点问题(编辑脚本是空的), 重装了一下才正常.

**Comment by Felix2yu** [comment]
可以了，谢谢。
