### ISSUE TITLE
无法点赞三连，点击点赞后提示登录，关闭脚本后点赞成功，再打开脚本后依然不显示

### ISSUE THREAD

**Issue by blm21** [the1812/Bilibili-Evolved#1120]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
看！
置！
顶！
#1076
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
