### ISSUE TITLE
加载错误

### ISSUE THREAD

**Issue by Hilf20181024** [the1812/Bilibili-Evolved#1121]
**关于哪一项功能**
未知

**问题描述**
打开b站任意一个视频页面显示不了up头像，评论区，推荐列表，多p视频无法显示视频列表，点赞投币收藏等功能点击后会显示登录的窗口，实际上已经登陆。

**脚本版本**
Stable v1.11.0
内容包: e0d1186

**浏览器版本**
 85.0.4183.121

**Comment by Geeyun-JY3** [comment]
看！
置！
顶！
#1076
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
