### ISSUE TITLE
评论加载不出

### ISSUE THREAD

**Issue by Aoesun** [the1812/Bilibili-Evolved#1123]
**关于哪一项功能**

**问题描述**

任何一个视频的评论都加载不出来，但动态里可以点开评论

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**
![QQ截图20201029161519](https://user-images.githubusercontent.com/37470931/97542575-f608e680-1a01-11eb-90b8-b5472c061ad4.png)

**Comment by LonelySteve** [comment]
见置顶 #1076

**Comment by the1812** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
