### ISSUE TITLE
最近两天开启evolved之后b站评论无法加载，合集列表无法加载，收藏反复弹出登录无法使用

### ISSUE THREAD

**Issue by cutebabyzhi** [the1812/Bilibili-Evolved#1125]
**问题描述**

最近两天开启evolved之后b站评论无法加载，合集列表无法加载，收藏反复弹出登录无法使用

**脚本版本**
v1.11.0

**浏览器版本**
chrome 86

**错误信息**
无

**附加截图**

**Comment by lansama** [comment]
![image](https://user-images.githubusercontent.com/19707411/97552018-b3014000-1a0e-11eb-9be9-bb5533b99599.png)
一样

**Comment by lansama** [comment]
尝试关闭自动定位到播放器 外置稍后再看 启用快速收藏应该可行，或者更新到预览版

**Comment by the1812** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
