### ISSUE TITLE
展开选集列表

### ISSUE THREAD

**Issue by theabg** [the1812/Bilibili-Evolved#1127]
**关于哪一项功能**
展开列表

**问题描述**

多点几下展开列表
av9430200

**脚本版本**

Stable v1.11.0
内容包: b310eb8

**浏览器版本**

qq浏览器10.6.1
**错误信息**

**附加截图**
![Snipaste_2020-10-29_19-07-52](https://user-images.githubusercontent.com/73643743/97562014-f7470d00-1a1b-11eb-839f-4f737d0754af.png)
![Uploading Snipaste_2020-10-29_19-08-35.png…]()

**Comment by the1812** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
