### ISSUE TITLE
1.11.0  chrome86.0.4240.111  开启脚本后评论区不显示

### ISSUE THREAD

**Issue by VerweileDoch** [the1812/Bilibili-Evolved#1128]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Loyisa** [comment]
+1

**Comment by Geeyun-JY3** [comment]
> 发之前记得看下置顶问题 (Pinned issues)(如果有的话)
> https://github.com/the1812/Bilibili-Evolved/issues

看！
置！
顶！
#1076
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480

**Comment by Coulomb-G** [comment]
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)
