### ISSUE TITLE
Preview预览版无限初始化

### ISSUE THREAD

**Issue by RainEffect** [the1812/Bilibili-Evolved#113]
RT，很奇怪的情况，加载最新预览版后每一次更新都会进行一次初始化。。。且部分设置内容丢失。。。图标未正确加载等。。。
![image](https://user-images.githubusercontent.com/14258727/56854451-4b75ba80-6969-11e9-81dc-f4ae2c75d2ed.png)

**Comment by the1812** [comment]
最近在换新的设置算法, 还有一些bug, Preview暂时用不了了, 可以先用预览离线版
