### ISSUE TITLE
B站港澳台番剧无法下载字幕文件

### ISSUE THREAD

**Issue by zir-ChiHo** [the1812/Bilibili-Evolved#1133]
B站港澳台版全员恶玉无法正常下载字幕文件，但其他港澳台番剧都能正常下载，目前问题在EDGE86及88均能复现
![image](https://user-images.githubusercontent.com/70327841/97609644-d055fe80-1a4e-11eb-82a1-fc5f94fb5ecb.png)
![image](https://user-images.githubusercontent.com/70327841/97609689-e237a180-1a4e-11eb-882c-5ccc505b51ca.png)

**Comment by zir-ChiHo** [comment]
https://www.bilibili.com/bangumi/play/ep349525

**Comment by Coulomb-G** [comment]
这边不提供港澳台相关使用体验及改善

**Comment by zir-ChiHo** [comment]
> 这边不提供港澳台相关使用体验及改善

这样吗.....

**Comment by Coulomb-G** [comment]
另外看了下，这番是app特供的，网页端根本没有弹幕池给你抓

**Comment by zir-ChiHo** [comment]
我用的那个解除区域限制脚本来解析到这片地址，其他类似的新版港澳台APP特供片子（应该是B还没整好网页版的相关版面之类的）是可以正常抓到字幕的，比如强袭魔女第三季（https://www.bilibili.com/bangumi/play/ss35176/），不知道为什么就这片抓不到

**Comment by Coulomb-G** [comment]
这边确实解决不了，不过你可以试试去biliplus那边找找方法

**Comment by zir-ChiHo** [comment]
> 这边确实解决不了，不过你可以试试去biliplus那边找找方法

我尝试通过网上给出的方法通过F12工具是可以正常获取到显式存储的json文件的（https://i0.hdslb.com/bfs/subtitle/515a212b0d3ac1cef2fb1a84403606d63181fca3.json ）
不知道是什么问题...其他的字幕文件也是以相同的方式存储的，不知道为什么就这个抓不到

**Comment by the1812** [comment]
我们是调用 b 站的字幕 API 获取的, 自然这种番剧只会得到“啥都木有”

**Comment by zir-ChiHo** [comment]
> 我们是调用 b 站的字幕 API 获取的, 自然这种番剧只会得到“啥都木有”

那不清楚了，按道理说@anime_ongoing 这个号所有投稿的动画理论上都是无法获取的但是实际上不清楚为什么就这部不可以
