### ISSUE TITLE
点开新视频时候自动播放了，能不能加一个设置开关点开视频是否自动播放啊

### ISSUE THREAD

**Issue by Jason-Richtung** [the1812/Bilibili-Evolved#1144]
**关于哪一项功能**

**期望的效果**

**脚本版本**

**Comment by Geeyun-JY3** [comment]
官方不是有吗：![image](https://user-images.githubusercontent.com/26504152/86350265-01871380-bc95-11ea-8579-fe33343ff365.png)
重复：#491，#522，#542，#618，#646，#691

**Comment by Jason-Richtung** [comment]
谢谢回复，才发现原来是自动设置点开就播放的/笑哭




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月31日(星期六) 下午5:09
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"richtung"<1943796495@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 点开新视频时候自动播放了，能不能加一个设置开关点开视频是否自动播放啊 (#1144)





 
官方不是有吗：
 重复：#491，#522，#542，#618，#646，#691
