### ISSUE TITLE
自定义顶栏在创作中心页面相关建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1146]
**关于哪一项功能**
自定义顶栏

**期望的效果**
1. 自定义顶栏全局固定排除创作中心；
2. 自定义顶栏 `投稿入口`组件下五个入口的网址得更新了，网址中的 `v2#` 需替换成 `platform`

**脚本版本**
正式版 v1.11.0 内容包: 6a9f9c2
预览离线版 v836.81

**Comment by LonelySteve** [comment]
这个创作中心的夜间模式是放弃治疗了嘛（

**Comment by the1812** [comment]
是的 内容又多 改版还贼快 做了没多久就又失效了

**Comment by Geeyun-JY3** [comment]
就离谱，原来原版顶栏入口的网址也还没改

**Comment by Geeyun-JY3** [comment]
其实有没有考虑过将深色模式拆分出一个 UserCSS（Bilibili Dark？），就像 [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark)，把适配工作交给开源社区，并同时适配市面上各种使用人数比较多的插件／脚本，也不用重复造轮子。

我知道的有在做 b 站深色模式的插件／脚本／样式就有隔壁 Bilibili Helper、[bilibili-lite](https://github.com/tolking/usercss/tree/master/bilibili-lite)
就是不知道同时兼容各种插件／脚本的难度，尤其是涉及 Bilibili Evolved 这种破坏性较大的。

**Comment by the1812** [comment]
有的 https://github.com/the1812/Bilibili-Evolved/blob/preview/min/dark.user.css
不过相应的设置项目前还是隐藏的

**Comment by the1812** [comment]
见 #347

**Comment by Geeyun-JY3** [comment]
要不单独开个 repo🤔（未来如果有可能的话）？

**Comment by the1812** [comment]
或许可以

**Comment by Geeyun-JY3** [comment]
像 [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark) 一样，从 Bilibili Evolved 独立出去，相关设置项用 UserCSS 实现，。

**Comment by Geeyun-JY3** [comment]
建议在完成#431 后进行拆分
