### ISSUE TITLE
稍后再看中播放器不显示进度条

### ISSUE THREAD

**Issue by cyanide233** [the1812/Bilibili-Evolved#1149]
**关于哪一项功能**

**问题描述**

点击播放后播放进度条等内容不在显示，无法调节清晰度与播放速度，只在稍后再看中打开会出现这种情况，并且无法双击全屏

**脚本版本**

**浏览器版本**

**错误信息**

没有显示错误信息

**附加截图**
![image](https://user-images.githubusercontent.com/68052879/97781894-3f576280-1bc9-11eb-987b-db1a0d7460be.png)

**Comment by Geeyun-JY3** [comment]
正式版 v1.11.5 可复现，预览离线版 v861.19 貌似无法复现
