### ISSUE TITLE
新版顶栏略肥

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#115]
而且稍后再看,消息,历史记录等弹出款,太肥了不好看

稍后再看少了一个播放全部的功能,虽然这功能本来没啥用
![QQ截图20190501195916](https://user-images.githubusercontent.com/14146754/57016253-b239f300-6c4b-11e9-91e5-64ec4be9da57.png)

**Comment by u2shana** [comment]
啊,忘记我开了显示全文的功能了,所以显得特别肥

**Comment by the1812** [comment]
设定就是这么肥的, 跟显示全文没关系. 需要的话我再整个紧凑点的样式.
播放全部那个因为跟点第一个视频效果一样所以就不加上去了(疯狂偷懒)
