### ISSUE TITLE
反馈个小问题

### ISSUE THREAD

**Issue by zkzmba793** [the1812/Bilibili-Evolved#1150]
**关于哪一项功能**
主题颜色 和 夜间模式

**问题描述**
开启 夜间模式 后，视频页面里的点赞、投币等按钮都会和设置里主题颜色匹配，关闭 夜间模式 之后就不会了，请问这是有意要这样的吗？

**脚本版本**
Preview Offline v836.81

**浏览器版本**
Chrome 86.0.4240.111（正式版本） （64 位）

**附加截图**
动态图：
![1234](https://user-images.githubusercontent.com/73212412/97784313-8bf66a00-1bd8-11eb-86b0-5f58228e0857.gif)
开启前：
![12](https://user-images.githubusercontent.com/73212412/97784803-0b396d00-1bdc-11eb-99b9-03dd99086ecb.png)
关闭后：
![123](https://user-images.githubusercontent.com/73212412/97784841-4e93db80-1bdc-11eb-9bb3-2f76ccb57ca5.png)

**Comment by Coulomb-G** [comment]
主题色尽量不要用亮色吧，是专门适配夜间模式的

**Comment by Geeyun-JY3** [comment]
确实是这样：
![image](https://user-images.githubusercontent.com/49396421/97793244-7a3ab400-1c24-11eb-96a4-8a476711fe4d.png)
#431

**Comment by zkzmba793** [comment]
好的，感谢各位了
