### ISSUE TITLE
季节logo和评论区菜单按钮出现了一些问题

### ISSUE THREAD

**Issue by KJZH001** [the1812/Bilibili-Evolved#1152]
**关于哪一项功能**

季节logo和简化评论区

**问题描述**

1. 季节logo无法正常显示（在b站全站中都会发生）
2. 简化评论区后评论区的菜单按钮占位过大（在所有视频或番剧的下方评论区中都会出现）
[不是很影响使用但是在一定程度上影响了美观，因为有点强迫症所以还是来提一下，如果您认为无需修复请直接无视就好]

示列页面地址 https://www.bilibili.com/bangumi/play/ep341245

**脚本版本**

正式版

Stable v1.11.0

内容包: 6be4d8b

**浏览器版本**

QQ浏览器 | 10.6.4212.400

**错误信息**

并未在Console中找到错误信息

![36.png](https://icdn.7t5j.cn/2020/11/01/c2896606465b5.png)

**附加截图**

![6.png](https://icdn.7t5j.cn/2020/11/01/6e9544c111e04.png)

![9.png](https://icdn.7t5j.cn/2020/11/01/342e884ef6ca7.png)

![0.png](https://icdn.7t5j.cn/2020/11/01/810a495c92e63.png)

**Comment by the1812** [comment]
1. 只是因为今天的季节logo是纯白色的
2. 会修的

**Comment by KJZH001** [comment]
> 1. 只是因为今天的季节logo是纯白色的
> 2. 会修的

emmn...好吧，第一点我也是真的没有想到会是这样的

感谢你的回复

**Comment by Geeyun-JY3** [comment]
2 已经修了，见 #1072，#1097

**Comment by the1812** [comment]
> 2 已经修了，见 #1072，#1097

正式版还没发这个

**Comment by Geeyun-JY3** [comment]
> 正式版还没发这个

知道，但 issue 还是部分重复了。

**Comment by adf1178** [comment]
我这边开了插件之后评论就无法加载了

**Comment by the1812** [comment]
@adf1178 
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
