### ISSUE TITLE
是否可以添加一个是否收缩弹幕列表的选项?

### ISSUE THREAD

**Issue by dotabht** [the1812/Bilibili-Evolved#1155]
**关于哪一项功能**

搜过没有相关的内容

**期望的效果**
大多数视频第一时间都看不到分集
是否可以添加一个是否收缩弹幕列表的选项?

**脚本版本**
最新

**Comment by the1812** [comment]
不是有吗  叫`自动展开弹幕列表`  关掉就行

**Comment by Coulomb-G** [comment]
有这个功能,在「视频」类功能里

**Comment by dotabht** [comment]
抱歉我傻了,只在github中搜索了问题,刚发现设置界面是可以搜索的
