### ISSUE TITLE
预览版及正式版都会导致搜索页面空白

### ISSUE THREAD

**Issue by TTTPOB** [the1812/Bilibili-Evolved#116]
**关于哪一项功能**

我也不知道关于哪一项功能，但是我把脚本停掉就好了。

**问题描述**

只要搜索就会触发这个问题，会导致搜索页面空白

**脚本版本**

正式版：1.7.28
测试版：1.7.31
非离线版，但以通过科学上网取得良好网络连接

**浏览器版本**

73.0.3683.103 Chrome x64 on Windows

**错误信息**

我试着打开了脚本的内部错误信息报告然而并没有发现弹窗之类的输出

**附加截图**
![image](https://user-images.githubusercontent.com/19909103/57025253-3353b300-6c69-11e9-8599-b299f3b8ac88.png)
新安装并已经通过初始化的测试版
![image](https://user-images.githubusercontent.com/19909103/57025271-4797b000-6c69-11e9-842f-cdb2a9496a4a.png)
同一个页面，但使用的是之前安装并长期使用的正式版
![image](https://user-images.githubusercontent.com/19909103/57025323-67c76f00-6c69-11e9-9162-bed871ace45b.png)
正式版与测试版均关闭得到的结果

**Comment by the1812** [comment]
细查了一下, 估计是b站把搜索的超时时间设错了, 原本应该是60秒超时, 却设成了0.6秒, 时间一到就会那样子变成空白. 0.6秒作为超时时间实在是太短了点...我猜是b站程序员手误了
关掉所有脚本, 打开开发者工具里的网速阻塞(模拟慢一些的网速), 就能够还原这一现象.
我的脚本需要约0.1\~0.2秒的加载时间, 所以加大了空白的出现几率, 特别是原本的页面就需要0.4\~0.5秒的时候.

网速模拟还原:
![image](https://user-images.githubusercontent.com/26504152/57056111-da206980-6cd2-11e9-846e-92962572a4ce.png)
开了脚本的时候, 要在0.6秒之内加载出来才可以正常:
![image](https://user-images.githubusercontent.com/26504152/57056367-a6deda00-6cd4-11e9-9c31-38bc8b1f4ead.png)

关于超时时间的代码:
![image](https://user-images.githubusercontent.com/26504152/57056151-1fdd3200-6cd3-11e9-8871-c813656474d9.png)
![image](https://user-images.githubusercontent.com/26504152/57056215-89f5d700-6cd3-11e9-9f41-5f726f17263d.png)

**Comment by the1812** [comment]
官方已修复此问题, 超时时间延长为10秒了. (不过为什么还留着那个0.6秒, 难道是测试用的)
![image](https://user-images.githubusercontent.com/26504152/57215184-b89ae700-701e-11e9-8963-0b5795948d1e.png)
