### ISSUE TITLE
IDM下载视频显示无权限

### ISSUE THREAD

**Issue by 2370177068** [the1812/Bilibili-Evolved#1161]
**关于哪一项功能**
下载视频

**问题描述**

本插件配上IDM下载视频，IDM显示无权限下载视频，但是网页可以下载（av668162661）

**脚本版本**
正式版1.11.0

**浏览器版本**
Microsoft Edge：88.0.685.3 (官方内部版本) dev (64 位)
操作系统：Windows 10 OS Version 2009 (Build 19042.610)

**错误信息**
下载视频，然后显示链接，然后打开IDM下载，就出现“服务器响应您没有权限下载此文件”，但是直接用浏览器就可以下载。

**附加截图**
![1](https://user-images.githubusercontent.com/51988982/98194967-9e1b3400-1f5b-11eb-960d-379e186a94c9.png)
![2](https://user-images.githubusercontent.com/51988982/98194971-9fe4f780-1f5b-11eb-8ecc-d908b2d91093.png)
![3](https://user-images.githubusercontent.com/51988982/98194974-a1aebb00-1f5b-11eb-97d1-787542a222c1.png)
![4](https://user-images.githubusercontent.com/51988982/98194976-a2dfe800-1f5b-11eb-9b29-afdbc02e1a50.png)

**Comment by the1812** [comment]
需要直接在浏览器里调用IDM下载那个链接才行, 复制粘贴过去是不行的
或者也可以选IDM导出一个文件, 再导进IDM里
