### ISSUE TITLE
针对安卓平板用户，希望禁止自动跳转成移动模式

### ISSUE THREAD

**Issue by kuonji-arisu** [the1812/Bilibili-Evolved#1164]
即使在浏览器中设置了优先使用桌面模式，但打开新界面b站依旧会优先使用移动页面并跳转客户端
Device 小新pad pro
OS zui for pad based on Android10
browser kiwi browser git201030
plugin version 1.11.0

**Comment by the1812** [comment]
这是b站控制的 我做不了什么
