### ISSUE TITLE
弹幕文件xml下载不完全

### ISSUE THREAD

**Issue by killsskillss** [the1812/Bilibili-Evolved#1166]
**关于哪一项功能**
弹幕文件xml下载不完全

**问题描述**

恩, 这几天才发现的
当视频长度超过90分钟(1小时30分钟), 此后出现的弹幕不会在xml文件之中, 同样,也不会出现在此脚本的转换的ass文件中
作为参考这个视频可以作为试验对象 BV1j7411N7Dz 

**脚本版本**

正式版1.11.0

**浏览器版本**

Firefox 81.0

**错误信息**

脚本正常工作,我感觉这是目前存在的所有问题,我用you-get这个python工具下载的xml文件在弹幕时长超过90分钟的时候超过的部分都没有存在于下载的xml文件中

**附加截图**
![issue](https://user-images.githubusercontent.com/74049685/98360268-78c61d00-2064-11eb-8cbc-304a6b303883.jpg)

**Comment by the1812** [comment]
同 #1093

**Comment by killsskillss** [comment]
ok
