### ISSUE TITLE
使用了简化页面功能后页面加载过慢

### ISSUE THREAD

**Issue by 1525249038** [the1812/Bilibili-Evolved#1169]
入标题所示，使用了此功能B站的加载页面极慢

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/blob/preview/src/style/simplify-home/simplify-home.md

**Comment by 1525249038** [comment]
> https://github.com/the1812/Bilibili-Evolved/blob/preview/src/style/simplify-home/simplify-home.md

多谢 通过这个方法解决了
