### ISSUE TITLE
新版对直播区适配不佳

### ISSUE THREAD

**Issue by aliofwind** [the1812/Bilibili-Evolved#117]
**关于哪一项功能**

适配问题

**问题描述**

1.开启脚本后直播区头像悬浮查看个人信息样式出现问题
2.开启自定义顶栏及填充其他顶栏后直播区顶栏字体没有修改、搜索框边框消失

**脚本版本**

288.90

**浏览器版本**

Chrome 72

**附加截图**
1.
![image](https://user-images.githubusercontent.com/35068322/57053411-62e1da00-6cc0-11e9-9736-5f154fc3a39b.png)
2.
![image](https://user-images.githubusercontent.com/35068322/57053504-1945bf00-6cc1-11e9-921c-a9e0d7383c04.png)

**Comment by the1812** [comment]
颜色的问题已修复, 但是个人信息那里我这是正常的, 还原不出图里的样子, 会不会是别的选项导致的?

**Comment by aliofwind** [comment]
问题找到了，Preview Offline的界面翻译i18n-style css的问题

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Grant Howard <notifications@github.com>
发送时间: Saturday, May 4, 2019 5:19:44 PM
收件人: the1812/Bilibili-Evolved
抄送: aliofwind; Author
主题: Re: [the1812/Bilibili-Evolved] 新版对直播区适配不佳 (#117)


颜色的问题已修复, 但是个人信息那里我这是正常的, 还原不出图里的样子, 会不会是别的选项导致的?

―
