### ISSUE TITLE
希望直播间添加屏蔽舰长入场的特效

### ISSUE THREAD

**Issue by bcloli** [the1812/Bilibili-Evolved#1170]
在舰长多的直播间 弹幕输入框上面会有个欢迎舰长xxx入场的特效 会刷个不停 希望能屏蔽

**Comment by Coulomb-G** [comment]
同样在弹幕输入框上面，还有个「屏蔽特效」的魔法棒，这是b站自带的功能

**Comment by bcloli** [comment]
> 同样在弹幕输入框上面，还有个「屏蔽特效」的魔法棒，这是b站自带的功能

好的 解决了 之前点了无效是因为另一个脚本冲突导致的 卸载另一个脚本就没事了 谢谢
