### ISSUE TITLE
退出功能失效。

### ISSUE THREAD

**Issue by xukai19941231** [the1812/Bilibili-Evolved#1171]
Preview v1.11.2 头像点击退出登录，跳转到了失效页面，刷新后还是原账号，未能成功退出。

**Comment by Geeyun-JY3** [comment]
预览离线版 v843.19 可复现，点击退出登录后会跳转至 https://passport.bilibili.com/login?act=exit ，页面截图如下
![image](https://user-images.githubusercontent.com/49396421/98655648-a8359c00-237a-11eb-9d3b-58eee265dc6d.png)
