### ISSUE TITLE
创作中心在开启夜间模式后可见性极差

### ISSUE THREAD

**Issue by Lijingze2019** [the1812/Bilibili-Evolved#1172]
如题

**脚本版本1.11.0**

**浏览器版本Edge  86.0.622.63**

![image](https://user-images.githubusercontent.com/52600662/98462523-ea7ea200-21ef-11eb-8453-52419c34e303.png)

**Comment by the1812** [comment]
按理说这里应该自动关闭夜间的, 创作中心链接是不是变了来着?

**Comment by Lijingze2019** [comment]
https://member.bilibili.com/platform/upload/video/frame
这个链接
我用你的这个脚本时间不长，所以不知道之前是什么样的，加个排除这个解决办法挺好的，稳妥省事2333

**Comment by Geeyun-JY3** [comment]
@the1812 #1145 
因为还在 [预览版](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.11.2-preview) 啊……
tag 打错了吧🤣

**Comment by the1812** [comment]
噢 没注意到已经修过了

**Comment by Lijingze2019** [comment]
哦哦，OK

**Comment by Geeyun-JY3** [comment]
@Lijingze2019 忘说了，夜间其实已经放弃创作中心了：https://github.com/the1812/Bilibili-Evolved/issues/759#issuecomment-664268233
