### ISSUE TITLE
一直提示有新版本需要安装,但是安装完成后依然如此

### ISSUE THREAD

**Issue by SmRiley** [the1812/Bilibili-Evolved#1173]
**关于哪一项功能**
更新相关

**问题描述**

RT,一直在左下角提示有新版本待更新,但是更新后依然如此,安装预览版后仍旧发现此问题,更新源切换后依然如此

**脚本版本**

1.11.0

**浏览器版本**

Edge Chrome版本

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/45205313/98542126-6863ab80-22cb-11eb-8904-a6980fda17f3.png)

**Comment by the1812** [comment]
检查下是不是装了两个

**Comment by the1812** [comment]
我怀疑从 GreasyFork 安装的会和这里安装的分成两个

**Comment by SmRiley** [comment]
确实如此...已解决.好奇怪的问题.

**Comment by the1812** [comment]
GreasyFork 那边上传后会强行往我代码里加个 namespace
原版代码是没有 namespace 的, 不同的 namespace 即使相同名称也会被当成 2 个脚本

![image](https://user-images.githubusercontent.com/26504152/98542853-854cae80-22cc-11eb-9bcc-4ab8cefeafcd.png)

**Comment by Geeyun-JY3** [comment]
以前在 Greasy Fork 安装然后通过弹窗更新好像也不会覆盖，最终变成安装两个脚本。
