### ISSUE TITLE
加入切换界面语言为繁体中文入口

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1175]
**关于哪一项功能**
自定义顶栏
界面翻译

**期望的效果**
b 站原版顶栏的用户信息面板有个切换界面语言的入口，可切换为繁体中文：
![image](https://user-images.githubusercontent.com/49396421/98656347-87217b00-237b-11eb-9327-2b6ed4e61579.png)
开启了自定义顶栏后好像就没有别的地方有这个切换入口了。
要不往自定义顶栏或者 `界面翻译` 里加这个入口？

**脚本版本**
正式版 v1.11.0
预览离线版 v843.19

**Comment by the1812** [comment]
这个繁体是完整支持了吗
当初看只支持首页, 就没加

**Comment by Coulomb-G** [comment]
这个功能就是个废案或者说半成品,当初是想做国际化界面,后来官方团队放弃了

**Comment by Geeyun-JY3** [comment]
啊这……
那好吧
