### ISSUE TITLE
动态详情页导出图片出错

### ISSUE THREAD

**Issue by FlareMonso** [the1812/Bilibili-Evolved#1176]
**关于哪一项功能**
动态导出图片

**问题描述**

在”t.bilibili.com/xxxx”的页面上使用`动态图片导出`，会获取到多余的图片。像是自己的头像，评论区内的头像、表情、头像框，和不清楚哪来的成就勋章的图片。

**脚本版本**

Preview v1.11.2
内容包: 71d5167

**浏览器版本**

Microsoft Edge 
版本 86.0.622.51

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/67825783/98683602-31ab9500-23a0-11eb-8c4b-24da70bf0bc7.png)
![image](https://user-images.githubusercontent.com/67825783/98682877-63702c00-239f-11eb-9c90-5bdf890cb81d.png)

**Comment by the1812** [comment]
忘记去掉评论区里的图了...

**Comment by FlareMonso** [comment]
确实，只要打开评论区就会这样，我之前都是没点开评论区就下载的
