### ISSUE TITLE
`迷你播放器触摸拖动` 失效

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1179]
**关于哪一项功能**
迷你播放器触摸拖动

**问题描述**
`迷你播放器触摸拖动` 功能失效，https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-725496950 忘说了。
迷你播放器这次最明显的改动应该是变宽了。

**脚本版本**
正式版 v1.11.0
预览离线版 v843.19

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 86.0.4240.198（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/49396421/98901187-49912f00-24ee-11eb-9678-793acf15f39a.png)

**Comment by Geeyun-JY3** [comment]
看来播放页的广告也顺便改了：
![image](https://user-images.githubusercontent.com/49396421/98902012-ce307d00-24ef-11eb-850f-83fa8d59fb36.png)

**Comment by the1812** [comment]
你那不能拖了吗  我昨天看改版了自带触摸拖动支持了

**Comment by Geeyun-JY3** [comment]
我大意了啊，开 issue 前没有试试，原来是自带触摸拖动支持了🤣🤦‍♂️。
那我关 issue 了，记得干掉新广告就是。

**Comment by the1812** [comment]
重新试了下, 功能是正常的, 关掉就不能触摸拖动了
