### ISSUE TITLE
关于直播界面的附加功能

### ISSUE THREAD

**Issue by LabmenNo001** [the1812/Bilibili-Evolved#118]
关于哪一项功能
直播房间页

请问这个附加功能在哪里？
![屏幕截图(50)](https://user-images.githubusercontent.com/38105143/57066403-ace9b080-6cfe-11e9-8561-d63a1c43353c.png)

**Comment by the1812** [comment]
2019英雄联盟的那个直播页面比较特殊, 背景是黑的, 脚本是日间模式的话很难看清楚附加功能的按钮在哪.
附加功能位置大概在左侧中央偏上的位置, 鼠标移到那里会变成手, 具体可以开一个白底的页面参考一下.
另外, 这个页面的直播板块是嵌入的, 改变了简化直播间之类的设置仍然需要刷新才能看到效果.
