### ISSUE TITLE
Edge 中主题颜色会自动设置为绿色

### ISSUE THREAD

**Issue by LMing123** [the1812/Bilibili-Evolved#1180]
**关于哪一项功能**
样式->主题颜色

**问题描述**

主页的开启使用自定义顶栏，设置项均为默认，主题颜色设置为蓝色，但是刷新之后会自动变回绿色。

**脚本版本**

正式版  v1.11.0
测试版  v1.11.2 

**浏览器版本**

Edge 版本 88.0.692.0 (官方内部版本) dev (64 位)

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
正式版和测试版同时只能开一个,你关掉其中一个后,再试试?

**Comment by LMing123** [comment]
> 正式版和测试版同时只能开一个,你关掉其中一个后,再试试?

分别试了两个版本， 正式和测试都是单独测试的， 两个版本都是这个问题

**Comment by Coulomb-G** [comment]
控制台报错信息写了什么?是否开着其他脚本或插件?

**Comment by LMing123** [comment]
> 控制台报错信息写了什么?是否开着其他脚本或插件?
 控制台信息，如下图：
![QQ截图20201112231850](https://user-images.githubusercontent.com/16752325/98958925-c0a1e400-253d-11eb-8547-7a395b359b7d.png)

**Comment by LMing123** [comment]
> 控制台报错信息写了什么?是否开着其他脚本或插件?

找到问题了， 是前一段时间 在其他pc 浏览器装的插件 同步到了现在这个pc， 这个插件造成的这个问题。
扩展是edge store内的 恰译
[恰译地址](https://microsoftedge.microsoft.com/addons/detail/%E6%81%B0%E8%AF%91-qiayi/oepgkbjlelllmijjhdkeghpclcopapnb)
