### ISSUE TITLE
在选择 Issue 类型页面加入「记得看置顶」的提示

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1181]
**关于哪一项功能**
Repo 选择 Issue 类型页面优化

**期望的效果**
既然在 [Bug 反馈](https://github.com/the1812/Bilibili-Evolved/issues/new?template=bug_report.md)、[功能建议](https://github.com/the1812/Bilibili-Evolved/issues/new?template=feature-request.md) issue template 中的「记得看置顶」的提示用处不大（#770，#966，#1076），不如利用 [issue template config](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) 在 [选择 Issue 类型页面](https://github.com/the1812/Bilibili-Evolved/issues/new/choose) 也加个「记得看置顶」的提示，指向：https://github.com/the1812/Bilibili-Evolved/issues
参考：https://github.blog/2020-05-14-github-protips-tips-tricks-hacks-and-secrets-from-luke-hefson/#issue-template-config-options

**脚本版本**
正式版 v1.11.0
预览离线版 v843.19

**Comment by the1812** [comment]
有意思 还可以加参数 https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters
