### ISSUE TITLE
彻底隐藏弹幕列表？

### ISSUE THREAD

**Issue by Siheyuan98** [the1812/Bilibili-Evolved#1182]
想请问能否彻底隐藏弹幕列表，不仅列表主体收起，而且连列头也隐藏。

设想布局是播放页面完全不纵向分栏，而是仅保留一栏，顶端标题和播放器，中间视频简介，底下评论区这样。右侧栏的其它内容都隐藏成功，仅剩弹幕列表最多收起不能隐藏（或者我没找到怎么隐藏）。感谢  :-)

**Comment by the1812** [comment]
宽屏模式?

**Comment by Siheyuan98** [comment]
你好，请问宽屏模式在哪切换？V1.11.3 没看到这个选项呀。

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/99019727-f2479900-2597-11eb-9546-bc4651bf0aa7.png)

**Comment by Siheyuan98** [comment]
感谢，原来是播放器…

但这样似乎也只是让弹幕列表下移，并没有将其隐藏。

![图片](https://user-images.githubusercontent.com/6215580/99020268-bffc5400-2523-11eb-919a-bd6fdcbd847e.png)

**Comment by the1812** [comment]
居然改版了.. 以前会直接挡住弹幕列表的

**Comment by Siheyuan98** [comment]
看来我刚才还没把问题想透，选集列表和弹幕列表占用的也是同一列。

大佬如果有闲心不知可否追加隐藏弹幕 & 隐藏选集列表或将其移到和播放器同列的功能。即使隐藏选集列表后切 P 变麻烦，留着弹幕列表挂在旁边也更闹心…

![图片](https://user-images.githubusercontent.com/6215580/99020944-2afa5a80-2525-11eb-865d-fd6e7eedf166.png)

**Comment by Coulomb-G** [comment]
这种的话,我推荐你使用stylus,直接自己改造吧

**Comment by the1812** [comment]
控制台(<kbd>Ctrl + Shift + I</kbd>)里运行
```JavaScript
bilibiliEvolved.installStyle({ name:'hideDanmakuList', displayName: '隐藏弹幕列表', style: `.r-con .danmaku-box { display: none }` })
```

**Comment by Siheyuan98** [comment]
成功隐藏，感谢 :-)

**Comment by Geeyun-JY3** [comment]
这个宽屏模式算是往 YouTube 的剧场模式靠近了一点点？~~（并不~~
不过现在看之前 [创作团队展示方式的改动](https://github.com/the1812/Bilibili-Evolved/issues/926#issue-697896681) 好像有给这个宽屏模式改版铺路的意思（想不到如何在不大改原先展示方式的基础上响应现在的新版宽屏模式？）。但我个人还是不是很喜欢现在这种和播放器、弹幕列表风格不协调、不统一的展示方式。
