### ISSUE TITLE
视频页面的右侧广告没有删除

### ISSUE THREAD

**Issue by Mirionr** [the1812/Bilibili-Evolved#1183]
**关于哪一项功能**
删除广告

**问题描述**

开启删除广告后，视频页面的右侧广告还是存在

**脚本版本**

1.11.2

**浏览器版本**

86.0.4240.198

**错误信息**

无

**附加截图**
![1](https://user-images.githubusercontent.com/51433180/99029882-9b998980-25ae-11eb-88e2-de74937bbbb8.png)

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/1179#issuecomment-725859055
我其实提了（

**Comment by Mirionr** [comment]
已解决
