### ISSUE TITLE
建议在“简化直播间”功能内新增屏蔽“高能榜”

### ISSUE THREAD

**Issue by FlareMonso** [the1812/Bilibili-Evolved#1185]
**关于哪一项功能**

B站成天新增些奇奇怪怪的东西，希望能屏蔽下直播间内弹幕区的“高能榜”

**期望的效果**
![image](https://user-images.githubusercontent.com/67825783/99042535-d9ef7280-25c7-11eb-91a5-8651a3e30677.png)

**脚本版本**
Preview v1.11.2
内容包: a84569e

**Comment by FlareMonso** [comment]
顺带一提，b站把直播间内弹幕用户的“用户等级"给移除了，感觉”用户等级”那个可以移除了

**Comment by Shi-Guang-0901** [comment]
弹幕区的“高能榜”刷新那是真的烦人，有人上榜就刷一遍。恶心
