### ISSUE TITLE
增加横向滚轮控制进度条

### ISSUE THREAD

**Issue by zycsss** [the1812/Bilibili-Evolved#1186]
本人使用的是master 2s鼠标，希望有一个使用横向滚轮控制进度条的功能方便发挥鼠标的全部功能，谢谢大佬

**Comment by anatolyxu** [comment]
逗呢，我用的也是这个鼠标，横向滚轮几乎就没有能发挥作用的地方。各种各样的硬件功能千奇百怪，第三方软件开发者挨个去适配不得累死，你在这里反馈还不如去给罗技发邮件让他们给横向滚轮多开发点应用场景

**Comment by the1812** [comment]
我可没这鼠标, 控制进度条直接用键盘吧
