### ISSUE TITLE
建议加入可选开启的“追剧”在“追番”旁

### ISSUE THREAD

**Issue by huangsijun17** [the1812/Bilibili-Evolved#1187]
**关于哪一项功能**

“自定义顶栏”的“动态”标签加入“追剧”相关内容。

**期望的效果**
“自定义顶栏”的“动态”标签加入“追剧”相关内容。

**脚本版本**
1.11.0

**Comment by the1812** [comment]
顶栏上的`订阅`就有

**Comment by Geeyun-JY3** [comment]
![image](https://user-images.githubusercontent.com/49396421/99074863-77ac6700-25f3-11eb-8520-79e1f55afc04.png)
