### ISSUE TITLE
自定义顶栏打开添加到收藏夹的音频会跳转至 av 号与目标音频 au 号相同的视频

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1188]
**关于哪一项功能**
自定义顶栏

**问题描述**
自定义顶栏打开添加到收藏夹的音频会跳转至 av 号与目标音频 au 号相同的视频

**脚本版本**
正式版 v1.11.0
预览离线版 v843.19

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 86.0.4240.198（正式版本） （64 位）

**错误信息**

**附加截图**
懒得截

**Comment by the1812** [comment]
为啥音频能加到普通收藏夹了...?

**Comment by Geeyun-JY3** [comment]
我也不知道为啥：
![image](https://user-images.githubusercontent.com/49396421/99075084-d8d43a80-25f3-11eb-8616-56c79d394845.png)
