### ISSUE TITLE
能否关闭b站新出的「接下来播放」功能

### ISSUE THREAD

**Issue by sino1641** [the1812/Bilibili-Evolved#1189]
**关于哪一项功能**

视频播放器 「接下来播放」功能

**期望的效果**
应该是B站新出的功能，会自动跳转播放下一个相关视频，请问能否关闭
![](https://mikupics-1253369011.file.myqcloud.com/2020/11/14/5a5cc95ace866.png)

**脚本版本**
Preview v1.11.3
内容包: e5209d7

**Comment by Geeyun-JY3** [comment]
旁边有开关：
![image](https://user-images.githubusercontent.com/49396421/99101911-409c7c80-2618-11eb-8123-a844f71b0119.png)
