### ISSUE TITLE
开启弹幕导致视频卡顿

### ISSUE THREAD

**Issue by Alexkington** [the1812/Bilibili-Evolved#119]
**问题描述**
1、在使用脚本打开弹幕，播放视频卡顿；
2、关闭弹幕，视频卡顿卡顿；
3、打开弹幕，关闭脚本，视频不卡顿；
4、I7需要升级I9么。。。。。。。。

**脚本版本**
正式版1.7.28 

**浏览器版本**
Chrome 74.

**Comment by the1812** [comment]
是有什么插件冲突了吗, 我低压i5都不卡啊...
