### ISSUE TITLE
关于截图功能的建议

### ISSUE THREAD

**Issue by anatoliux2233** [the1812/Bilibili-Evolved#1192]
**关于哪一项功能**

截图功能建议

**期望的效果**
似乎是在去年的某个版本中（记不太清了），点击截图按钮，系统会自动去除视频黑边，只保留视频有效区域，效果如下图
（前排修改：上传图片后发现显示不出透明图层，如需要查看实际效果请将图片保存到本地）
![QQ截图20201114114616](https://user-images.githubusercontent.com/38915367/99138972-c5ff4b80-266f-11eb-8fb6-4eac11dbb8bc.png)

现在的版本在截图时则会将黑边保存为透明图层，而且视频窗口不同（标准、宽屏、网页全屏、全屏），截图的分辨率也不同，效果如下图
![1917 - 原版 @37-05 44 1605283002218](https://user-images.githubusercontent.com/38915367/99138535-3b691d00-266c-11eb-86ee-31ce38d24aee.png)
![1917 - 原版 @37-05 44 1605283014618](https://user-images.githubusercontent.com/38915367/99138537-3d32e080-266c-11eb-9443-166e3aad2ca9.png)
![1917 - 原版 @37-05 44 1605283025938](https://user-images.githubusercontent.com/38915367/99138541-3e640d80-266c-11eb-928f-95816e743975.png)
![1917 - 原版 @37-05 44 1605283040075](https://user-images.githubusercontent.com/38915367/99138544-3f953a80-266c-11eb-9134-f1931fe76b3f.png)
![名侦探柯南 - 237 @24-25 90 1605322006957](https://user-images.githubusercontent.com/38915367/99138970-c0096a80-266f-11eb-8d21-f5f387b06daf.png)

希望能够恢复到原来的效果，去除透明图层，只保留视频有效区域

**脚本版本**
1.11.0

**Comment by the1812** [comment]
以前是因为原方法会导致弹幕截进去比例变形/错位, 所以改成了后来的样子

**Comment by MY1L** [comment]
@the1812 由于我经常需要压缩png，也发现这个透明会导致截屏体积变大，如果有方法可以确定透明边并裁掉就好了。

**Comment by anatoliux2233** [comment]
> 以前是因为原方法会导致弹幕截进去比例变形/错位, 所以改成了后来的样子

请问可以对该功能进行优化吗，用图片查看器浏览截图时四周的图层边框太突兀了

**Comment by the1812** [comment]
那就不带弹幕的时候按原方法吧

**Comment by anatoliux2233** [comment]
> 那就不带弹幕的时候按原方法吧

感谢大佬
