### ISSUE TITLE
[功能请求]音画同步功能的请求

### ISSUE THREAD

**Issue by twlightlin** [the1812/Bilibili-Evolved#1194]
**关于哪一项功能**

音画同步功能，某些视频音画不同步

**期望的效果**
设置项视频组中增加一个可选开关，打开后在视频播放页更改音频条的时间，填上时间（使音频条滞后为+增加为-）并按下旁边确定按钮，让音频条滞后或者提前于视频播放

**脚本版本**

**Comment by Coulomb-G** [comment]
这个功能怎么做？

**Comment by muye975** [comment]
啊这。。我目前也不知道啊 ，我去各论坛问一问， 有解决办法了回复您

Coulomb-G <notifications@github.com> 于2020年11月14日周六 下午3:16写道：
