### ISSUE TITLE
希望顶栏的稍后再看-播放全部，能够使用新版的播放界面

### ISSUE THREAD

**Issue by kethoven** [the1812/Bilibili-Evolved#1195]
**关于哪一项功能**

希望顶栏的稍后再看-播放全部，能够使用新版的播放界面

**期望的效果**
感觉新版的稍后再看播放界面，使用体验更加统一，操作更加习惯。
希望稍后再看-播放全部，能够使用新版的播放界面
**脚本版本**

**Comment by 921j** [comment]
界面我倒不在意，我倒是觉得播放全部默认的是从最新到最旧的视频不能反序有点烦
