### ISSUE TITLE
放映厅电影频道改版，夜间模式不适配

### ISSUE THREAD

**Issue by jacknyy** [the1812/Bilibili-Evolved#1198]
RT

**Comment by Geeyun-JY3** [comment]
你指的是不是这个点赞按钮：https://github.com/the1812/Bilibili-Evolved/issues/1143#issuecomment-726897929

**Comment by jacknyy** [comment]
> 你指的是不是这个点赞按钮：[#1143 (comment)](https://github.com/the1812/Bilibili-Evolved/issues/1143#issuecomment-726897929)

并不是

**Comment by Geeyun-JY3** [comment]
> 并不是

那截个图？

**Comment by jacknyy** [comment]
![夜间模式](https://user-images.githubusercontent.com/29568890/99149137-28376b00-26c7-11eb-9994-0dfafa1d3925.png)
![非夜间](https://user-images.githubusercontent.com/29568890/99149142-338a9680-26c7-11eb-8d98-081131f4444f.png)

**Comment by jacknyy** [comment]
> > 并不是
> 
> 那截个图？

![夜间模式](https://user-images.githubusercontent.com/29568890/99149174-5d43bd80-26c7-11eb-9d04-10fafe712b01.png)
![非夜间](https://user-images.githubusercontent.com/29568890/99149176-60d74480-26c7-11eb-8c94-2e6195eb7bcc.png)

**Comment by Geeyun-JY3** [comment]
其实可以集中反馈在 #1143
（截图发一次就行，不用专门回复我的，我能收到通知的

**Comment by jacknyy** [comment]
> 给个传送门？（我猜还在灰度
> 
> 另外其实可以集中反馈在 #1143
> （截图发一次就行，不用专门回复我的，我能收到通知的
https://www.bilibili.com/movie/
你不在B站看电影的么？

**Comment by Geeyun-JY3** [comment]
是的还没全量推送，我这边还是老样子。
