### ISSUE TITLE
播放器更新导致控制区底色一直存在

### ISSUE THREAD

**Issue by aliofwind** [the1812/Bilibili-Evolved#12]
**关于哪一项功能**

播放器控制区底色

**问题描述**

B站播放器更新之后，进度条会留在播放器底部不隐藏，导致控制区底色一直存在

**脚本版本**

107.73

**附加截图**
![image](https://user-images.githubusercontent.com/35068322/47949263-f1c4a280-df7a-11e8-8fdb-fb9840ffbebc.png)

**Comment by the1812** [comment]
b站换了一种隐藏方式, 以前是隐藏整个控制区, 现在是只隐藏那些按钮保留进度条. 但是多刷新几次两种方式都会交替出现, 我现在还搞不明白什么条件下才会用新的隐藏方式...

目前在110.11版本中提供了初步的修复.

**Comment by aliofwind** [comment]
![image](https://user-images.githubusercontent.com/35068322/47951291-a2da3580-df99-11e8-9f30-d2a8599d3b96.png)
还是有点问题，进度条背景色没了，控制区底色区域不对，能不能提供个选项自定义控制区底色

**Comment by the1812** [comment]
现在应该可以了, 控制区底色开放了不透明度

**Comment by aliofwind** [comment]
好的，可以用了
