### ISSUE TITLE
Safari 中预览/预览离线版的设置/功能页无法弹出的问题

### ISSUE THREAD

**Issue by PatZhuang** [the1812/Bilibili-Evolved#120]
**关于哪一项功能**
左侧设置/功能按钮弹出界面问题

**问题描述**
在任意页面点击设置/功能按钮时，无法弹出侧边栏，只会出现黑色遮罩
四个版本的脚本中，离线版无此问题，预览/预览离线版均有此问题（正式版在 Safari 中一直是不可用的状态，会导致页面卡死）

**脚本版本**
预览离线版 v295.96
预览版 v1.7.32

**浏览器版本**
Safari 12.1（Chrome 无此问题）

**Comment by the1812** [comment]
应该是指针事件导致的问题, 因为预览那边改成了首次经过齿轮图标处时才把设置面板设为可见, 今天因为这个问题才发现 Safari 不支持指针事件...
预览现在改成用鼠标事件了, Safari 应该能跑了.
正式版的问题我还没找到原因, 先用着离线版吧.
