### ISSUE TITLE
建议在分part视频中自动关闭展开弹幕列表

### ISSUE THREAD

**Issue by OctRaging** [the1812/Bilibili-Evolved#1200]
**关于哪一项功能**

自动展开弹幕列表

**期望的效果**
建议在分part视频中自动关闭展开弹幕列表，这样选part方便很多，但在但part视频中默认展开弹幕列表，这样能清爽点。

**脚本版本**
1.11

**Comment by HanlinWei** [comment]
支持。每次弹幕列表展开以后，分p（视频选集）就跑到屏幕外面去了。我是一般情况下关闭弹幕的，如果可以选择隐藏掉整个弹幕列表就更好了。

**Comment by Coulomb-G** [comment]
选part直接在视频播放器下方的控制栏就可以选择

**Comment by OctRaging** [comment]
> 选part直接在视频播放器下方的控制栏就可以选择

不可以啊，只有在全屏状态下播放器才能选集

**Comment by the1812** [comment]
@Coulomb-G 触摸模式才是常驻的(
