### ISSUE TITLE
建议在相簿里批量下载图片 / 支持自定义命名

### ISSUE THREAD

**Issue by FlareMonso** [the1812/Bilibili-Evolved#1208]
**关于哪一项功能**

相簿下载图片

**期望的效果**
在 h.bilibili.com/* 页面里，做一个和”专栏图片导出“一样功能。

![image](https://user-images.githubusercontent.com/67825783/99357268-97d77100-28e6-11eb-8ae1-359426e972ee.png)

**脚本版本**
Preview v1.11.4
内容包: 9b8c974

**Comment by the1812** [comment]
要不你们想想都还有什么地方需要批量下图片的, 我全部整合在一个功能里得了

**Comment by Geeyun-JY3** [comment]
发图的动态都有一个相应的相簿页🤣

**Comment by FlareMonso** [comment]
其实我还想直接下up主相簿所有图片，不知道可不可行😅

**Comment by FlareMonso** [comment]
感觉没什么了，顶多就是up主所有相簿图片，或者up主空间里的封面图片，不过觉得没什么必要😅

**Comment by the1812** [comment]
@Geeyun-JY3 那相簿页是不是一定有个对应动态? 是的话我直接加在动态的导出图片里了

**Comment by Geeyun-JY3** [comment]
> 那相簿页是不是一定有个对应动态?

这个不是很敢打包票，但我猜应该是。你是说设置项放在一起吗？

**Comment by the1812** [comment]
开了动态图片导出, 在相簿也能导, 并没有多设置项

**Comment by Geeyun-JY3** [comment]
哦哦哦就不单独搞一个设置项的意思是吧

**Comment by Geeyun-JY3** [comment]
说到这个我还想问一句，有可能实现相簿页和对应动态页的互相跳转吗（类似于 #970）？

**Comment by the1812** [comment]
不大可能

**Comment by Geeyun-JY3** [comment]
好的吧

**Comment by FlareMonso** [comment]
建议#1036别close先，还有个自定义命名的功能未实现。

**Comment by the1812** [comment]
就当是这个 issue 的吧
