### ISSUE TITLE
BiliPlus跳转部分链接不支持 修复项

### ISSUE THREAD

**Issue by RainEffect** [the1812/Bilibili-Evolved#121]
RT，目前发现有部分的视频链接是使用bangumi作为链接，但在BiliPlus中并无法进行直接跳转，例如山下智博的《穷豪旅游记系列》(最新一集AV51728502)。

但因为进入页面时，其播放器本身之上是有一个原AV号的，可否改一下在页面当前为bangumi页时使用旧AV号进行biliplus跳转？
简单的获取方式: $('.info-sec-av')[0].innerText

**Comment by the1812** [comment]
已修复. 顺便一提, b站很贴心的给我们设了个全局变量`aid`, 里面就是av号

**Comment by RainEffect** [comment]
![image](https://user-images.githubusercontent.com/14258727/57852714-793a7a80-7816-11e9-8deb-65559c456102.png)
![image](https://user-images.githubusercontent.com/14258727/57852723-7dff2e80-7816-11e9-9df5-fc05aa557af0.png)
你好像。。。产生了什么误解

**Comment by the1812** [comment]
噢 忘了原本不能播放的情况了...

**Comment by RainEffect** [comment]
你忘了回复issue而且。。。1.8.1版本点击跳转无效了。。

**Comment by the1812** [comment]
无效了? 我4天前就修了啊, 测试过了穷豪旅游记系列, 贤者之孙, 港澳台番剧, 都可以正常跳转的...
无效的话控制台有报错吗?

**Comment by RainEffect** [comment]
Uncaught TypeError: Cannot read property 'innerText' of null
    at HTMLButtonElement.i.addEventListener (eval at applyComponent (userscript.html?id=03b320e1-0402-4fae-9f2e-7c7c2798cff4:NaN), <anonymous>:1:751)

PS: 恩，求你在这之前加一个 if(someone != null) 233333333;

**Comment by the1812** [comment]
噢 原来是又忘记考虑旧版播放器了

**Comment by RainEffect** [comment]
问题解决，轻轻松松狗狗笑笑~
