### ISSUE TITLE
动态相关功能支持直播间下的「TA的动态」tab

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1210]
**关于哪一项功能**
动态翻译
禁止跳转动态详情
动态反折叠

**期望的效果**
`动态翻译`、`禁止跳转动态详情` 、`动态图片导出` 等动态相关功能支持直播间下的「TA的动态」tab。
`展开动态内容`、`评论翻译`、~~`动态链接复制`~~、~~`评论链接复制`~~ 和 `动态反折叠` 是支持的，所以上述提到的功能是忘了适配？
~~`动态反折叠` 找不到可测试的对象，如果有适配请无视。~~
其实应该把 #596 的提到的 `快速收起动态评论区` 也算进来。
***
2020-11-26 补充：经测试，`动态反折叠` 已适配。
***
2021-06-05 发现 `动态链接复制` 已失效，需重新适配。
***
2021-07-19 发现 `评论链接复制` 的适配有问题
***
2023-04-01 测试发现动态相关功能在直播间下的「TA的动态」tab 的工作状态已和其他地方无异。

适配情况：

~~`动态翻译`~~
~~`评论翻译`~~
- [x] `禁止跳转动态详情`
- [x] `动态链接复制`
- [x] `评论链接复制` 
- [x] `动态图片导出`

**脚本版本**
正式版 v1.11.0
预览离线版 v853.01

**Comment by the1812** [comment]
(#596 一直没 close 的原因就是还没支持直播间)

**Comment by Geeyun-JY3** [comment]
别忘了个人空间动态tab下的这两个小 bug👀：https://github.com/the1812/Bilibili-Evolved/issues/596#issuecomment-695217892

**Comment by Geeyun-JY3** [comment]
今天发现 `评论链接复制` 在这里的适配有问题，复制出来的链接是直接在直播间 URL 后加参数。

**Comment by Geeyun-JY3** [comment]
今天测试发现动态相关功能在直播间下的「TA的动态」tab 的工作状态已和其他地方无异。
