### ISSUE TITLE
可以添加一个下载视频中的音频的功能吗

### ISSUE THREAD

**Issue by long45343** [the1812/Bilibili-Evolved#1211]
**关于哪一项功能**

**期望的效果**
可以直接把视频中的音频提取成mp3，而不是dash-m4a-mp3

**脚本版本**

**Comment by the1812** [comment]
虽然这个从想法上来说很合理, 但是下载视频那块的代码写的太辣鸡了实在难加, 以后如果有机会整改了我就把这个功能带上

**Comment by long45343** [comment]
https://github.com/IvanRave/convert-wma-m4a-wav-to-mp3-online
可不可以把m4a的地址提取出来，然后套用这个转换？
或者直接批量下载m4a？

**Comment by the1812** [comment]
你可以批量导出 aria2, 得到的 txt 里有链接

**Comment by KokeCacao** [comment]
可以用 aria2 导出, 然后用正则表达式
`((.*\n){3}).*mp4\n((.*\n){1})`
删除多余部分
