### ISSUE TITLE
夜间模式未匹配漫画详情页

### ISSUE THREAD

**Issue by Posthumz** [the1812/Bilibili-Evolved#1215]
**关于哪一项功能**
夜间模式

**问题描述**
manga.bilibili.com的漫画详情页，[如](https://manga.bilibili.com/detail/mc28376)

**附加截图**
![图片](https://user-images.githubusercontent.com/63167402/99544111-e6703280-29ee-11eb-8881-9c1d7d86a417.png)

**Comment by Geeyun-JY3** [comment]
重复 #826
最新预览离线版
