### ISSUE TITLE
重定向几个移动端网页版页面至电脑版网页

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1219]
**关于哪一项功能**
重定向移动端网页版页面

**期望的效果**
别紧张，不是在重复 #1164。

就重定向以下两个页面：
1.  h5 版的 [B站热门](https://www.bilibili.com/h5/popular) 至 [综合热门](https://www.bilibili.com/v/popular/all)；
2.  h5 版的动态页至电脑版网页，即重定向 `https://t.bilibili.com/h5/dynamic/detail/*` 至 `https://t.bilibili.com/*`。

2020-11-25 补充：

3. h5 版的 [bilibili每周必看](https://www.bilibili.com/h5/weekly-recommend) 至 [哔哩哔哩每周必看](https://www.bilibili.com/v/popular/weekly)，如果能让期数对上就更好了。

2020-12-27 补充：

4. h5 版的 Ta 的好友页：https://space.bilibili.com/h5/follow?mid=8047632 / https://space.bilibili.com/h5/follow_i18n?mid=8047632 至对应个人空间关注页（其实想区分 `Ta的关注` 和 `Ta的粉丝` 两个 tab 的，奈何 URL 一样），对应前面例子就是：https://space.bilibili.com/8047632/fans/follow
这里还有个我们的共同关注页：https://space.bilibili.com/h5/samefollow?mid=8047632 ，不过目前网页端也没这东西的对应页面，或者先不管或者一并重定向至对应个人空间关注页吧。

说来挺奇怪的，其他的移动端网页版页面电脑网页打开 B 站自己会跳转，就这几个不会。

另外，在测试过程中偶然发现在手机浏览器打开相簿页会重定向至相应的 h5 版动态页，即从 `https://h.bilibili.com/*` 重定向至 `https://t.bilibili.com/h5/dynamic/detail/*`。
或许能利用这个特性实现相簿页跳转至对应动态页（起码是单向的跳转）？

**脚本版本**
正式版 v1.11.0
预览离线版 v853.01

**Comment by Geeyun-JY3** [comment]
有趣的是，现在从个人空间投稿 tab 相簿分栏进入照片不再是 `https://h.bilibili.com/{id}` 的相簿页而是地址为如下的动态页：`https://t.bilibili.com/{id}?type=2`，但相簿页目前还打得开，于是就出现了同时存在以下三个链接的情况：
- https://t.bilibili.com/463701857738397214
- https://t.bilibili.com/99981647?type=2
- https://h.bilibili.com/99981647

结合手机端个人空间现在已经看不到相簿 tab，越来越感觉相簿这是要被砍的节奏。后面要是真被砍，上述第 2 点就没什么必要了。

（B站这试着砍音乐不成，又想来试试砍掉相簿？）

**Comment by Geeyun-JY3** [comment]
啊这真不做啊🌚

**Comment by the1812** [comment]
移动端页面不是被那几个 PR 排除掉了吗

**Comment by Geeyun-JY3** [comment]
emmmm
当时为啥 merge 了

**Comment by the1812** [comment]
因为脚本本来就不关心移动端, 我就直接 merge 了 (

**Comment by Geeyun-JY3** [comment]
今天的首页横幅入站必刷上新打开的还就是手机端页面我也是服了
![image](https://user-images.githubusercontent.com/49396421/104094958-1d681380-52cf-11eb-85bb-924549375585.png)
