### ISSUE TITLE
1.11.5整页白屏,向下滚动才能看到内容

### ISSUE THREAD

**Issue by 2314933036** [the1812/Bilibili-Evolved#1225]
**关于哪一项功能**
页面显示

**问题描述**

首页,视频播放页等

**脚本版本**

1.11.5

**浏览器版本**

360极速11.0

**错误信息**

![image](https://user-images.githubusercontent.com/38069007/99750256-0270f280-2b1b-11eb-9f00-492ecc486493.png)

**附加截图**
![image](https://user-images.githubusercontent.com/38069007/99750184-e2d9ca00-2b1a-11eb-9dbc-5e55a1923206.png)

**Comment by 2314933036** [comment]
![image](https://user-images.githubusercontent.com/38069007/99750333-259ba200-2b1b-11eb-82fe-c870898f3bf9.png)

**Comment by gayhub-com** [comment]
我视频页也是这样的问题

**Comment by the1812** [comment]
可能和浏览器太旧有点关系, #1224 里更新到 79 以上就没问题了, 我看 360 还是在 78

**Comment by gayhub-com** [comment]
> 可能和浏览器太旧有点关系, #1224 里更新到 79 以上就没问题了, 我看 360 还是在 78

我用的是遨游5,那是不是凉了?

**Comment by Coulomb-G** [comment]
不建议使用360以及其他套皮浏览器
请换用新版的edge,chrome,Firefox

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved#浏览器

> 不保证脚本能在"[套壳类浏览器](https://www.jianshu.com/p/67d790a8f221)"或者较长时间没更新的浏览器中完美运行.

**Comment by gayhub-com** [comment]
哪怎么回滚更新?上个版本的的js找不到了

**Comment by the1812** [comment]
https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@v1.11.0/bilibili-evolved.offline.user.js
装完删掉里面的 `@updateURL` 和 `@downloadURL` 两行, 以及别开 #1076 提到的那 2 个功能

**Comment by gayhub-com** [comment]
感谢

> https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@v1.11.0/bilibili-evolved.offline.user.js
> 装完删掉里面的 `@updateURL` 和 `@downloadURL` 两行, 以及别开 #1076 提到的那 2 个功能

感谢!

**Comment by nd002723** [comment]
> 可能和浏览器太旧有点关系，[＃1224](https://github.com/the1812/Bilibili-Evolved/issues/1224)里更新到79以上就没问题了，我看360还是在78

360的18号就上了86了[下载链接](https://down.360safe.com/cse/360cse_13.0.2132.0.exe)

**Comment by the1812** [comment]
> 360的18号就上了86了[下载链接](https://down.360safe.com/cse/360cse_13.0.2132.0.exe)

那 360 极速更到 13 之后应该也行

**Comment by KJZH001** [comment]
> https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@v1.11.0/bilibili-evolved.offline.user.js
> 装完删掉里面的 `@updateURL` 和 `@downloadURL` 两行, 以及别开 #1076 提到的那 2 个功能

同样感谢

不过对于我使用的QQ浏览器这类的套壳浏览器对于chrome内核可能更新频率不会太高
所以关于脚本这边以后如果可能的话会稍微做下兼容性方面的适配吗？
（虽然可能不会很有必要，但是个人还是希望能够进行一下适配
因为QQ浏览器这边的内核版本好像现在也才70【大汗-_-||】
）

**Comment by Coulomb-G** [comment]
> 不过对于我使用的QQ浏览器这类的套壳浏览器对于chrome内核可能更新频率不会太高
> 所以关于脚本这边以后如果可能的话会稍微做下兼容性方面的适配吗？
> （虽然可能不会很有必要，但是个人还是希望能够进行一下适配
> 因为QQ浏览器这边的内核版本好像现在也才70【大汗-_-||】
> ）

不会，一方面是没精力，另一方面是旧版本内核不支持很多新功能

**Comment by KJZH001** [comment]
> > 不过对于我使用的QQ浏览器这类的套壳浏览器对于chrome内核可能更新频率不会太高
> > 所以关于脚本这边以后如果可能的话会稍微做下兼容性方面的适配吗？
> > （虽然可能不会很有必要，但是个人还是希望能够进行一下适配
> > 因为QQ浏览器这边的内核版本好像现在也才70【大汗-_-||】
> > ）
> 
> 不会，一方面是没精力，另一方面是旧版本内核不支持很多新功能

好的，感谢回复
那我现在也只能向腾讯这边发个反馈看看能不能让他们更新下内核了= =(虽然感觉成功率不大)

**Comment by pikaqian** [comment]
诶的确有这个问题[捂脸]所以说除了换浏览器以外还有其他办法么，因为只有360有老板键（滑稽，所以不太想换浏览器

**Comment by Geeyun-JY3** [comment]
@pikaqian https://github.com/the1812/Bilibili-Evolved/issues/1225#issuecomment-730810943
而且百分也有：
![image](https://user-images.githubusercontent.com/49396421/99875151-5f0e0380-2c28-11eb-838b-1db9c2f12187.png)

**Comment by the1812** [comment]
@pikaqian 你可以把全部功能关闭 然后一个个开起来试 最后应该可以确认是哪个功能导致的
确认出功能我说不定能兼容下

**Comment by pikaqian** [comment]
哦哦哦谢谢二位！

以及我看貌似是【样式】里面的【播放器投影】、【强制保留弹幕栏】和【删除视频标题层】会影响。关了貌似就好了……
不过不知道别的还有没有影响……

**Comment by 892601059** [comment]
> 哦哦哦谢谢二位！
> 
> 以及我看貌似是【样式】里面的【播放器投影】、【强制保留弹幕栏】和【删除视频标题层】会影响。关了貌似就好了……
> 不过不知道别的还有没有影响……

我【播放器投影】和【删除视频标题层】都没开 同样情况，把【强制保留弹幕栏】关掉就好了

**Comment by KJZH001** [comment]
> > 哦哦哦谢谢二位！
> > 以及我看貌似是【样式】里面的【播放器投影】、【强制保留弹幕栏】和【删除视频标题层】会影响。关了貌似就好了……
> > 不过不知道别的还有没有影响……
> 
> 我【播放器投影】和【删除视频标题层】都没开 同样情况，把【强制保留弹幕栏】关掉就好了

感谢

空白的问题同样解决了

**Comment by the1812** [comment]
似乎是我之前为了修火狐不能后台打开的问题导致的 看来得再改改

**Comment by seven-CloWn** [comment]
> > 哦哦哦谢谢二位！
> > 以及我看貌似是【样式】里面的【播放器投影】、【强制保留弹幕栏】和【删除视频标题层】会影响。关了貌似就好了……
> > 不过不知道别的还有没有影响……
> 
> 我【播放器投影】和【删除视频标题层】都没开 同样情况，把【强制保留弹幕栏】关掉就好了

感谢感谢

**Comment by drw2005** [comment]
> 把【强制保留弹幕栏】关掉就好了
最近一段时间一直也是这个错误，今天看到这个帖子，参照你的这个方法：“把【强制保留弹幕栏】关掉”，果然页面恢复正常了，太感谢了。

**Comment by gayhub-com** [comment]
> > 哦哦哦谢谢二位！
> > 以及我看貌似是【样式】里面的【播放器投影】、【强制保留弹幕栏】和【删除视频标题层】会影响。关了貌似就好了……
> > 不过不知道别的还有没有影响……
> 
> 我【播放器投影】和【删除视频标题层】都没开 同样情况，把【强制保留弹幕栏】关掉就好了

厉害厉害，你们都是大佬

**Comment by renmu123** [comment]
@the1812 chrome 78.0.3904.108版本也有这个问题出现，关闭【强制保留弹幕栏】后消失

**Comment by Geeyun-JY3** [comment]
@renmu123 所以请用内核版本更高的浏览器：https://github.com/the1812/Bilibili-Evolved/issues/1225#issuecomment-731127039
或像你说的关闭 `强制保留弹幕栏`：https://github.com/the1812/Bilibili-Evolved/issues/1225#issuecomment-731571923
