### ISSUE TITLE
错误：Unexpected identifier

### ISSUE THREAD

**Issue by Kaneki521** [the1812/Bilibili-Evolved#1227]
**关于哪一项功能**
错误：Unexpected identifier

**问题描述**

打开视频、UP主页、个人主页、活动界面等都会出现此问题
具体见下方截图、GIF

**Bilibili-Evolved设置：**
[个人设置.zip](https://github.com/the1812/Bilibili-Evolved/files/5572431/default.zip)

**脚本版本**

正式版
Stable v1.11.5
内容包: 174aa28

**浏览器版本**

Chrome ：
版本 87.0.4280.66（正式版本） （64 位）

**错误信息**

Unexpected identifier
SyntaxError: Unexpected identifier
    at ResourceManager.applyComponent (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved.user.js&id=79b64f49-7b64-47a9-9a8d-deb7cf65fb95:13203:2421816)
    at ResourceManager.fetchByKey (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved.user.js&id=79b64f49-7b64-47a9-9a8d-deb7cf65fb95:13203:2420145)

**附加截图**
![2](https://user-images.githubusercontent.com/50744308/99780984-3a475c80-2b52-11eb-8cc6-8c659c95a685.gif)
![视频](https://user-images.githubusercontent.com/50744308/99780993-3c112000-2b52-11eb-8d9d-1eb7e39d07a1.png)
![主页](https://user-images.githubusercontent.com/50744308/99780996-3ca9b680-2b52-11eb-9bc9-b73122091c2b.png)

**Comment by caliban511** [comment]
我也遇到了。。。

**Comment by the1812** [comment]
热更新有点问题, 我晚上看一下
可以先用着离线版

**Comment by Kaneki521** [comment]
ok

**Comment by Kaneki521** [comment]
> 热更新有点问题, 我晚上看一下
> 可以先用着离线版

OK

**Comment by the1812** [comment]
可以切换热更新源至GitHub并清除缓存试试

**Comment by CKylinMC** [comment]
相同的问题
<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/11648014/99818814-a2656500-2b89-11eb-8a51-71b13090a22c.png" />
</details>

**Comment by the1812** [comment]
> 可以切换热更新源至GitHub并清除缓存试试

所以你们试过这个办法吗, 可以的话我就当做解决方案了

**Comment by CMy0ng** [comment]
> > 可以切换热更新源至GitHub并清除缓存试试
> 
> 所以你们试过这个办法吗, 可以的话我就当做解决方案了

好像只需要清楚缓存就好了

**Comment by the1812** [comment]
清除缓存只能生效一次

**Comment by RtYkk** [comment]
好像不行。已清除chrome缓存并重启chrome
`Stable v1.11.5 内容包: 2045fb5`

**Comment by the1812** [comment]
jsDelivr 提供的文件有点问题, 请求 2KB 的代码却报错说文件超出 50MB 限制, 然后解析运行就 `Unexpected identifier` 了
不知道今天恢复了没

**Comment by RtYkk** [comment]
卸载重装了一遍，好像解决了。
`Stable v1.11.5 内容包: 35fe60b`

**Comment by Kaneki521** [comment]
@the1812 貌似已经解决了，jsDelivr更新源貌似也没有问题了
PS：我是这样操作的

1. 将更新源换成GitHub

1. Bilibili-Evolved--侧边栏（附加功能）--清除缓存

1. 刷新页面，不再报错

1. 更新源换回jsDelivr，重复2、3，不再报错

**Comment by Suigezi0** [comment]
清除缓存
有效果

**Comment by WaylanPunch** [comment]
我用的edge浏览器

SyntaxError: Unexpected identifier
    at ResourceManager.applyComponent (userscript.html?name=Bilibili%20Evolved.user.js&id=9c7e0cf2-8dba-4248-97ba-7257ec247bdd:13203)
    at ResourceManager.fetchByKey (userscript.html?name=Bilibili%20Evolved.user.js&id=9c7e0cf2-8dba-4248-97ba-7257ec247bdd:13203)
logError @ userscript.html?name=Bilibili%20Evolved.user.js&id=9c7e0cf2-8dba-4248-97ba-7257ec247bdd:13203

**Comment by Kaneki521** [comment]
> 我用的edge浏览器
> 
> SyntaxError: Unexpected identifier
> at ResourceManager.applyComponent (userscript.html?name=Bilibili%20Evolved.user.js&id=9c7e0cf2-8dba-4248-97ba-7257ec247bdd:13203)
> at ResourceManager.fetchByKey (userscript.html?name=Bilibili%20Evolved.user.js&id=9c7e0cf2-8dba-4248-97ba-7257ec247bdd:13203)
> logError @ userscript.html?name=Bilibili%20Evolved.user.js&id=9c7e0cf2-8dba-4248-97ba-7257ec247bdd:13203



> @the1812 貌似已经解决了，jsDelivr更新源貌似也没有问题了
> PS：我是这样操作的
> 
> 1. 将更新源换成GitHub
> 2. Bilibili-Evolved--侧边栏（附加功能）--清除缓存
> 3. 刷新页面，不再报错
> 4. 更新源换回jsDelivr，重复2、3，不再报错

**Comment by Kaneki521** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/1227#issuecomment-731558372 
@WaylanPunch
