### ISSUE TITLE
屏蔽直播间”高能榜“

### ISSUE THREAD

**Issue by zhangsan102** [the1812/Bilibili-Evolved#1230]
![1](https://user-images.githubusercontent.com/69232146/99799790-388b9200-2b6e-11eb-95fc-2c132d8ba9cb.png)

**Comment by the1812** [comment]
<img height="500" src="https://user-images.githubusercontent.com/26504152/99800166-eb5bf000-2b6e-11eb-8e45-068b03f6e71a.png">

**Comment by zhangsan102** [comment]
感谢
