### ISSUE TITLE
建议增加提取音频的功能

### ISSUE THREAD

**Issue by yuannancheng** [the1812/Bilibili-Evolved#1231]
**关于哪一项功能**

**期望的效果**
希望能在增加一个无损提取音频的功能，因为，下载视频后使用格式工厂转换的音频音量变小了很多，可能是受损了，但是网上找其他工具有点麻烦，如果技术上不难的话建议可以整合到这里面。

![image](https://user-images.githubusercontent.com/52841727/99807542-9f16ad00-2b7a-11eb-8bcf-bb491dc5984e.png)

**脚本版本**
1.11.5

**Comment by the1812** [comment]
下DASH格式自带音频

**Comment by Geeyun-JY3** [comment]
重复：#1211

**Comment by yuannancheng** [comment]
谢谢，不过好像出什么问题了。

使用DASH格式下载，出现提示：
> 错误
> 视频片段12请求失败, response = 416

![223754](https://user-images.githubusercontent.com/52841727/99812239-26671f00-2b81-11eb-9f1a-3ea93f2137a5.png)

**Comment by the1812** [comment]
416的话得换用下面的导出了
