### ISSUE TITLE
使用简化首页后,在首页打开视频会出错

### ISSUE THREAD

**Issue by Vergissmeinnichts** [the1812/Bilibili-Evolved#1232]
如题,但是只要关闭简化首页就可以正常打开视频
![bili](https://user-images.githubusercontent.com/53445024/99808379-b7d39280-2b7b-11eb-95b7-219f5dcd545c.png)

**Comment by Coulomb-G** [comment]
仅开启该脚本情况下也是这样吗？

**Comment by Vergissmeinnichts** [comment]
**关于哪一项功能**
简化首页


**问题描述**
开启简化首页功能后,在首页打开视频就会出错,两种简化风格都会出错.
但偶尔也有可以正常打开的视频(很少很少,点了十几个视频才能有一个可以正常打开)
而且只要一关闭简化首页就可以正常打开所有视频.
(我已经把别的扩展以及脚本都关了)

**脚本版本**
1.11.5

**浏览器版本**
Microsoft Edge 88.0.702.0 (官方内部版本) dev (64 位)

**错误信息**

![bili2](https://user-images.githubusercontent.com/53445024/99811921-c1132e00-2b80-11eb-91df-fc25280aecc1.png)

**Comment by Vergissmeinnichts** [comment]
解决了,确实应该是因为我用了一些别的东西导致的,不是这个脚本的问题,不好意思..
