### ISSUE TITLE
开启首页后报错。

### ISSUE THREAD

**Issue by huangsijun17** [the1812/Bilibili-Evolved#1234]
**关于哪一项功能**
未知

**问题描述**

开启B站（首页）后出现画面0.5秒内全白并报错“Unexpected identifier”

**脚本版本**

1.11.5

**浏览器版本**

![image](https://user-images.githubusercontent.com/31504595/99814531-0edd6580-2b84-11eb-81f6-94d7542e559e.png)

**错误信息**

Unexpected identifier

**附加截图**
![image](https://user-images.githubusercontent.com/31504595/99814581-20bf0880-2b84-11eb-998b-a6cd38696d25.png)

**Comment by Geeyun-JY3** [comment]
看两个置顶：#1225 、#1227

**Comment by huangsijun17** [comment]
> 看两个置顶：#1225 、#1227

最奇怪的是前面还都好好的，再去一次主页就这样了。

**Comment by Geeyun-JY3** [comment]
> 最奇怪的是前面还都好好的，再去一次主页就这样了。

清除缓存
正常现象

**Comment by huangsijun17** [comment]
360公测Chromium86了，问题解决。
