### ISSUE TITLE
不能观看视频一直在加载中，退出登录就可以加载出来。

### ISSUE THREAD

**Issue by gavinwyf** [the1812/Bilibili-Evolved#1235]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/11659339/99867628-ff970000-2bf5-11eb-9525-1fc20c472b97.png)

**Comment by ben714** [comment]
同问，而且启用插件之后，视频加载慢了超级多。

**Comment by Coulomb-G** [comment]
请按照issue模板,详细反馈造成问题的相关设置信息

> 同问，而且启用插件之后，视频加载慢了超级多。

试试离线版
