### ISSUE TITLE
开启后顶部很大一片空白

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [the1812/Bilibili-Evolved#1237]
**关于哪一项功能**
页面布局

**问题描述**

B站主页，打开网页搜索条以下就是非常大一片空白，空白下面才是banner，关闭脚本后恢复正常

**脚本版本**

Preview v1.11.3
内容包: 0693377

**浏览器版本**

傲游v5.3.8.2000

**错误信息**

**附加截图**

**Comment by 574094130** [comment]
我也出现了这个问题，打开视频后会出现一整页的空白界面，往下滑一段才能看见视频，是更新最新版之后出现的问题

**Comment by Geeyun-JY3** [comment]
难道说在 [New issue](https://github.com/the1812/Bilibili-Evolved/issues/new/choose) 页加了个「记得看置顶」的提示也还是没用吗：#1225

**Comment by cxy360123** [comment]
关闭 【强制保留弹幕栏】即可

**Comment by Misaka-Mikoto-Tech** [comment]
不好意思没看到，从插件跳过来直接就是New issue页面

**Comment by Geeyun-JY3** [comment]
看来 New issue 页面和 template 里的「记得看置顶」提示作用还是不大啊🌚

**Comment by Geeyun-JY3** [comment]
> 从插件跳过来直接就是New issue页面

而且不应该这样啊，v1.11.0 就推了个热更新改了反馈地址：#1130
