### ISSUE TITLE
暗黑模式下，首页鼠标放置在动态，弹出动态框背景透明，无法看清内容

### ISSUE THREAD

**Issue by cxy360123** [the1812/Bilibili-Evolved#1238]
暗黑模式下，首页鼠标放置在动态，弹出动态框背景透明，无法看清内容
除了动态，其他类似“消息”、“收藏”、“历史”都正常
![image](https://user-images.githubusercontent.com/43236827/99877683-c46af000-2c3a-11eb-9cf9-fddf224071c2.png)
![image](https://user-images.githubusercontent.com/43236827/99877698-eb292680-2c3a-11eb-9cb1-aa027ac01c4c.png)

**Comment by Geeyun-JY3** [comment]
和 #1201 的「夜间模式可在`<iframe>` 中展示透明背景」有关？

**Comment by the1812** [comment]
应该是的

**Comment by cxy360123** [comment]
> 应该是的

能修复嘛=。=

**Comment by Geeyun-JY3** [comment]
> 发布后默认您已阅读发贴须知
> https://github.com/the1812/Bilibili-Evolved/blob/preview/issue-rules.md
> > Bug 反馈和功能建议不一定会做出回复, 特别是内容写得非常清晰时, 我就会直接加上相应的标签(bug或feature-request), 表示我将会处理.

**Comment by cxy360123** [comment]
> > 发布后默认您已阅读发贴须知
> > https://github.com/the1812/Bilibili-Evolved/blob/preview/issue-rules.md
> > > Bug 反馈和功能建议不一定会做出回复, 特别是内容写得非常清晰时, 我就会直接加上相应的标签(bug或feature-request), 表示我将会处理.

好的谢谢

**Comment by cxy360123** [comment]
> > 发布后默认您已阅读发贴须知
> > https://github.com/the1812/Bilibili-Evolved/blob/preview/issue-rules.md
> > > Bug 反馈和功能建议不一定会做出回复, 特别是内容写得非常清晰时, 我就会直接加上相应的标签(bug或feature-request), 表示我将会处理.

好的谢谢，辛苦了

**Comment by Geeyun-JY3** [comment]
建议顺便把 https://github.com/the1812/Bilibili-Evolved/issues/1143#issuecomment-721141173 的最后一条也修了
