### ISSUE TITLE
1.8.0版本设置菜单二级子菜单bug

### ISSUE THREAD

**Issue by Jolkssn** [the1812/Bilibili-Evolved#124]
**关于哪一项功能**
二级子菜单

**问题描述**
设置菜单中”视频“、”样式“、”工具“等一级菜单下的二级子菜单只显示开关按钮，却不显示功能名称

**脚本版本**
正式版1.8.0

**浏览器版本**
Chrome 74.0.3729.131（正式版本）（64 位）

**附加截图**
![QQ截图20190513150212](https://user-images.githubusercontent.com/50570270/57602070-bbeb2100-7590-11e9-994b-c7c1143b6b0f.png)
![QQ截图20190513150229](https://user-images.githubusercontent.com/50570270/57602072-bc83b780-7590-11e9-8279-8058d02f81f3.png)

**Comment by the1812** [comment]
Console里有报错吗? 看起来像是到加载功能名称时失败了
![image](https://user-images.githubusercontent.com/26504152/57603658-d7f0c180-7594-11e9-8040-f4473b2b33b6.png)

**Comment by Jolkssn** [comment]
有两个，不确定是不是这两个




------------------ 原始邮件 ------------------
发件人: "Grant Howard"<notifications@github.com>; 
发送时间: 2019年5月13日(星期一) 下午3:38
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com>; 
抄送: " "<843341609@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [the1812/Bilibili-Evolved] 1.8.0版本设置菜单二级子菜单bug (#124)




Console里有报错吗? 看起来像是到加载功能名称时失败了

**Comment by Jolkssn** [comment]
> Console里有报错吗? 看起来像是到加载功能名称时失败了
> ![image](https://user-images.githubusercontent.com/26504152/57603658-d7f0c180-7594-11e9-8040-f4473b2b33b6.png)

有两个，不确定这两个是不是
![QQ截图20190513154100](https://user-images.githubusercontent.com/50570270/57604266-51d57a80-7596-11e9-9a4e-fb6e82c83893.png)

**Comment by the1812** [comment]
第一个是了, 现在再刷新几次应该就好了

**Comment by Jolkssn** [comment]
> 第一个是了, 现在再刷新几次应该就好了

嗯，已经好了，十分感谢。
