### ISSUE TITLE
关于视频截图的全部保存

### ISSUE THREAD

**Issue by Yaklo** [the1812/Bilibili-Evolved#1240]
请问一下视频截图的全部保存为什么从压缩包改成了图包（随便想的词，不是很懂）不过也依然能以压缩包的格式打开保存就是

**Comment by the1812** [comment]
下的是.png 实际是个压缩包?

**Comment by Yaklo** [comment]
是一个图集，使用png也能正常打开和阅览里面的多张图片 但同时也能使用压缩包格式打开查看
只是问一下为什么修改成这样的格式而已haha

**Comment by the1812** [comment]
是个意外, 文件名我弄错了, 只是一连串png合在一个png里居然还能正常打开还挺神奇的

**Comment by Yaklo** [comment]
可能也是一种兼容格式吧😂原来是搞错了😂
