### ISSUE TITLE
b站页面改版把排行榜的入口直接改成了热门，希望能用脚本改回来

### ISSUE THREAD

**Issue by wwzw27** [the1812/Bilibili-Evolved#1241]
![ssss1](https://user-images.githubusercontent.com/64151098/99903106-3c99ea00-2cfd-11eb-861b-10ca20c86703.png)
就这个按钮，能改回直接进入排行榜吗？

**Comment by Geeyun-JY3** [comment]
现在自定义顶栏的 `排行` 还是排行榜（

**Comment by the1812** [comment]
从顶栏进吧

**Comment by wwzw27** [comment]
靠 没看到 我脑瘫了。

**Comment by Geeyun-JY3** [comment]
@the1812 顺便提醒 [鬼畜分区调整](https://www.bilibili.com/read/cv8405765)😁（日常该怎么反馈这种分区调整？）

**Comment by the1812** [comment]
开个 issue
(这可别成为日常啊

**Comment by Geeyun-JY3** [comment]
> 开个 issue

感觉就鸡毛点事（应该不会成日常的😂
