### ISSUE TITLE
稍后再看里面  播放器进度条消失

### ISSUE THREAD

**Issue by shishenbiaosha** [the1812/Bilibili-Evolved#1244]
**问题描述**
在稍后观看里面将鼠标放在视频上面会消失不见，同时也不能正常调节视频时间等。

**脚本版本**
Preview v1.11.5

**浏览器版本**
87.0.4280.66 (正式版本) （64 位）

**附加截图**
![DN~M 7U@J3AI({6XP7~0CHU](https://user-images.githubusercontent.com/57054088/99983678-1e101d80-2de7-11eb-90c9-5aec52825c9d.png)

**Comment by shishenbiaosha** [comment]
当在稍后观看里的视频刚打开的时候会有短暂的时间出现进度条，这个时候鼠标放在进度条上进度条不会消失。如果移动鼠标让进度条消失，再放到相同位置进度条就不会出现了

**Comment by Geeyun-JY3** [comment]
重复：#1149
