### ISSUE TITLE
动画横幅优化

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1247]
**关于哪一项功能**
自定义顶栏

**期望的效果**
鼠标悬停动画横幅会出现提示的情况，自定义顶栏考虑兼容一下？
![image](https://user-images.githubusercontent.com/49396421/100177227-9fad9b80-2f0c-11eb-9edd-63686fb271aa.png)

**脚本版本**
正式版 v1.11.5
预览离线版 v857.15

**Comment by the1812** [comment]
它和左边的logo, 还有上面的整个顶栏是一起的, 隐藏上面的原顶栏必然会隐藏这个...

**Comment by Geeyun-JY3** [comment]
啊这……好的吧
