### ISSUE TITLE
黑间模式能否调整一下？

### ISSUE THREAD

**Issue by BaiXianMoYun** [the1812/Bilibili-Evolved#1248]
**期望的效果**
可以的话……对夜间模式调整或者增加一些自定义选项，有些地方比如弹幕栏，搜索栏，弹幕列表，已关注按钮的一些地方可以弄得更深一些。灰色的对于其它来说有点亮了，

**Comment by the1812** [comment]
夜间模式是很早期的功能, 现在改这些早就来不及了...
晚上总归比白色要好很多的

**Comment by BaiXianMoYun** [comment]
> 夜间模式是很早期的功能，现在改这些早就来不及了...
> 晚上总归比白色要好很多的

那好吧。
但是黑间模式下的个人收藏界面有个bug
![2%YTI%XLJK7_G2LVZZYWJWI](https://user-images.githubusercontent.com/75004485/100233096-33f71d00-2f64-11eb-8d06-c69382ef4804.png)

**Comment by Geeyun-JY3** [comment]
@BaiXianMoYun 有 bug 可以在 #1143 统一反馈

**Comment by BaiXianMoYun** [comment]
> @BaiXianMoYun 有 bug 可以在 #1143 统一反馈

好的了解
