### ISSUE TITLE
关于脚本的消息提示窗口建议

### ISSUE THREAD

**Issue by kethoven** [the1812/Bilibili-Evolved#1249]
**关于哪一项功能**

消息提示窗口建议，希望能够改成：
1. 点击窗口上的任意位置，即可关闭消息窗口。
2. 限定时间（如15秒左右）可以自动关闭窗口。
**期望的效果**

**脚本版本**
1.11.5

**Comment by the1812** [comment]
1. 消息是有交互需求的 (复制内容/点击按钮等), 所以点叉才能关闭
2. 除了一些需要用户关注的 (某项功能的结果, 错误提示等), 其他一般 3~5 秒就会自动关闭

**Comment by kethoven** [comment]
> 
> 
>     1. 消息是有交互需求的 (复制内容/点击按钮等), 所以点叉才能关闭
> 
>     2. 除了一些需要用户关注的 (某项功能的结果, 错误提示等), 其他一般 3~5 秒就会自动关闭
稍后再看操作失败: 塞满啦！先看看库存吧
稍后再看操作失败: 非常抱歉，版权内容暂时无法添加到稍后再看
这两个是我自己使用中，比较常出现提示。这类提示能够在10秒左右自动关闭吗？

**Comment by the1812** [comment]
这个属于错误提示, 所以不会自动关, 我可以加个隐藏选项控制这个, 到时候发个解决办法给你

**Comment by kethoven** [comment]
> 
> 
> 这个属于错误提示, 所以不会自动关, 我可以加个隐藏选项控制这个, 到时候发个解决办法给你

好的!
我自己觉得这两条消息算不得错误，可以归类为是提示吧。
因为它不是脚本发生错误，或者有bug。只是提示库存满了，无法添加。或者提示版权内容，无法添加。
