### ISSUE TITLE
两个地方显示不正常……？

### ISSUE THREAD

**Issue by BaiXianMoYun** [the1812/Bilibili-Evolved#1250]
浏览器：Google Chrome86.0.4240.198（64位）
脚本版本：Stable v1.11.5
![N{5PAB6J@ON3$E8A62WLVYL](https://user-images.githubusercontent.com/75004485/100239632-95bb8500-2f6c-11eb-888e-f71e65e3b5c6.png)
![2%YTI%XLJK7_G2LVZZYWJWI](https://user-images.githubusercontent.com/75004485/100239637-97854880-2f6c-11eb-82d5-d9c4963d5c53.png)

**Comment by Geeyun-JY3** [comment]
第一个你是不是在页面加载完后手动开启的夜间模式？

**Comment by BaiXianMoYun** [comment]
> 第一个你是不是在页面加载完后手动开启的夜间模式？

无论如何打开都是这样

**Comment by the1812** [comment]
原版顶栏的消息是没有夜间的 我记得有个对应issue

**Comment by Geeyun-JY3** [comment]
@the1812 有的啊，只是如果加载页面前设置项没开启夜间模式，加载完成后再手动开启夜间模式，这里的这个消息和动态弹窗就还是白天样式。开启夜间模式后再手动关闭亦然。
之前就有发现，好像一些弹窗（比如番剧 `分享到动态` 对话框）也有这种延迟情况，不知道是 B 站的问题还是 Bilibili Evolved 的 bug
有夜间模式：
![image](https://user-images.githubusercontent.com/49396421/100308792-35682a00-2fe4-11eb-93cb-c8e0fb41c12f.png)
加载完成后再手动关闭夜间模式：
![image](https://user-images.githubusercontent.com/49396421/100308910-73654e00-2fe4-11eb-96f4-ed7d61b4e351.png)

**Comment by the1812** [comment]
> 有的啊
啊 我可能后来又改了...

> 有这种延迟情况
因为是 iframe 嵌入的, 所以那里面又要重新运行一次脚本, 主页面上开关夜间模式传不到里面

**Comment by Geeyun-JY3** [comment]
> 因为是 iframe 嵌入的, 所以那里面又要重新运行一次脚本, 主页面上开关夜间模式传不到里面

那就没问题了，不知道 issue 主是什么情况

**Comment by BaiXianMoYun** [comment]
emmmmmm

**Comment by BaiXianMoYun** [comment]
> > 有的啊
> 
> 啊 我可能后来又改了...
> 
> > 有这种延迟情况
> 
> 因为是 iframe 嵌入的, 所以那里面又要重新运行一次脚本, 主页面上开关夜间模式传不到里面

怎么个重新运存法啊？？？

**Comment by Geeyun-JY3** [comment]
> 怎么个重新运存法啊？？？

ta 回复的是我的疑问。
你确定你设置项开启夜间模式后进入任意界面，这个消息弹窗还是没有夜间模式吗？

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/100310993-a4944d00-2fe9-11eb-8e1f-9cc3dd30fbed.png)
Tampermonkey 编辑脚本设置这里开`否`

**Comment by BaiXianMoYun** [comment]
> > 怎么个重新运存法啊？？？
> 
> ta 回复的是我的疑问。
> 你确定你设置项开启夜间模式后进入任意界面，这个消息弹窗还是没有夜间模式吗？

啊……消息弹窗是黑暗的了，但是……
![)T_T_C4}Q)~0%M7 H5P`5 1](https://user-images.githubusercontent.com/75004485/100311139-0a80d480-2fea-11eb-9fae-339829d77100.png)

**Comment by Geeyun-JY3** [comment]
> ![)T_T_C4}Q)~0%M7 H5P`5 1](https://user-images.githubusercontent.com/75004485/100311139-0a80d480-2fea-11eb-9fae-339829d77100.png)

这个预览版修了

**Comment by BaiXianMoYun** [comment]
> > ![)T_T_C4}Q)~0%M7 H5P`5 1](https://user-images.githubusercontent.com/75004485/100311139-0a80d480-2fea-11eb-9fae-339829d77100.png)
> 
> 这个预览版修了

好的

**Comment by BaiXianMoYun** [comment]
> ![image](https://user-images.githubusercontent.com/26504152/100310993-a4944d00-2fe9-11eb-8e1f-9cc3dd30fbed.png)
> Tampermonkey 编辑脚本设置这里开`否



> ![image](https://user-images.githubusercontent.com/26504152/100310993-a4944d00-2fe9-11eb-8e1f-9cc3dd30fbed.png)
> Tampermonkey 编辑脚本设置这里开`否`

我这有问题……图片一直加载不出来

**Comment by Geeyun-JY3** [comment]
> 图片一直加载不出来

GitHub 里的图片加载不出来？和墙相关。

**Comment by BaiXianMoYun** [comment]
> > 图片一直加载不出来
> 
> GitHub 里的图片加载不出来？和墙相关。

后仰
