### ISSUE TITLE
【稍后再看的两个bug】链接更新了和默认播放速度失效

### ISSUE THREAD

**Issue by rabbit2099** [the1812/Bilibili-Evolved#1252]
**稍后再看**

**1.从顶栏观看稍后再看的视频链接错误，会无法播放 2.稍后再看页面默认播放速度失效**

**正式版1.11.5**

**Chrome 86**

**应该是b站稍后再看规则更新了，更新成了https://www.bilibili.com/medialist/play/watchlater/，顶栏的稍后再看还是老链接https://www.bilibili.com/watchlater/#/**

**附加截图
![image](https://user-images.githubusercontent.com/75069083/100333856-0797db00-300e-11eb-9b03-017228990399.png)
![image](https://user-images.githubusercontent.com/75069083/100333983-2a29f400-300e-11eb-9a9e-e27f126db516.png)

**

**Comment by Geeyun-JY3** [comment]
开一下 `稍后再看重定向`
