### ISSUE TITLE
`网址AV号转换` 偶尔失效

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1254]
**关于哪一项功能**
网址AV号转换

**问题描述**
（老实说这 bug 我也不知道怎么复现，但遇到的频次也不低）
开启 `网址AV号转换` 后，会出现点击右方推荐视频后视频链接不转换的情况。和正常转换情况的区别是不会出现一段虽短但可明确察觉的白屏阶段（夜间模式下），地址栏能看到未清理网址参数的时间特别短。

**脚本版本**
正式版 v1.11.5

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)

**错误信息**

**附加截图**
![popup](https://user-images.githubusercontent.com/49396421/100357095-278bc680-302f-11eb-9037-828792b4d668.gif)

**Comment by the1812** [comment]
没事 以后就没有这个功能了 (#1243)

**Comment by Geeyun-JY3** [comment]
啊这……不要吧，我还是挺希望保留这个功能的

**Comment by the1812** [comment]
附加功能里可以复制av号的链接

**Comment by Geeyun-JY3** [comment]
主要是我个人偏好 av 号，也会影响到复制出来的评论链接和配合其他脚本的复制出来的带时间的链接……算是一个强迫症选项吧😕

**Comment by Geeyun-JY3** [comment]
不过 #1243 的性能问题确实挺麻烦

**Comment by Geeyun-JY3** [comment]
我也知道现在还用 av 号其实是在逆 B 站潮流，所以我其实也能接受开启 `网址AV号转换` 这个功能后带来的 #1243 的问题~~（习惯了）~~。
还是希望能考虑保留该选项，开启后维持现在的样子，关闭后顶栏等地方提供的链接换成 BV 号，即优化 #1243 的问题。

**Comment by the1812** [comment]
嗯 可以考虑只去掉开关 代码层面上还是能开启的

**Comment by MC-dusk** [comment]
考虑关闭此功能并同时使用这个脚本？：https://greasyfork.org/zh-CN/scripts/398535-bv2av

**Comment by MC-dusk** [comment]
其实设一个优先使用BV号或av号的开关就好了，打开就所有链接自动转av号，关闭就全是BV号，各取所需

**Comment by Geeyun-JY3** [comment]
> 其实设一个优先使用BV号或av号的开关就好了，打开就所有链接自动转av号，关闭就全是BV号，各取所需

问题是现在 `网址AV号转换` 这功能不会转页面中所有的BV号， 要转的话 #1243 的性能问题怎么解决呢？

**Comment by MC-dusk** [comment]
如果所有链接都是自然BV号就没有https://github.com/the1812/Bilibili-Evolved/issues/1243 的性能问题了。
如果开启开关使用av号，目前会有https://github.com/the1812/Bilibili-Evolved/issues/1243 的性能问题，但应该能修复，现在就当是av号使用成本了。

不是很明白

> 问题是现在 网址AV号转换 这功能不会转页面中所有的BV号， 要转的话 #1243 的性能问题怎么解决呢？

这句话的意思

**Comment by Geeyun-JY3** [comment]
> 但应该能修复

现在就是不知道有没有能全局转换BV为av而不消耗性能的方法，怎么修复呢？成本到底有多少呢？
见：https://github.com/the1812/Bilibili-Evolved/issues/1243#issuecomment-732213292

**Comment by MC-dusk** [comment]
https://greasyfork.org/zh-CN/scripts/398535-bv2av 这个可以直接转页面内所有av号到BV号，但是点击切p会先跳转BV号，跟click操作的响应有关，应该好改。
作者用b站的api转换BV到av号，性能消耗自然大，换用本地计算就没什么消耗了。

实在不好改的话，其实像我上面说的

> 设一个优先使用BV号或av号的开关就好了，打开就所有链接自动转av号，关闭就全是BV号，各取所需

av号的二次跳转就当做副作用了，也能接受。

现在的问题是脚本内强制使用av号，比如上方横幅的稍后再看、收藏里的视频，所以所有人都会遇到#1243 的性能问题。

**Comment by Geeyun-JY3** [comment]
> 现在的问题是脚本内强制使用av号，比如上方横幅的稍后再看、收藏里的视频，所以所有人都会遇到#1243 的性能问题。

这个 https://github.com/the1812/Bilibili-Evolved/issues/1243#issuecomment-734275038 https://github.com/the1812/Bilibili-Evolved/issues/1243#issuecomment-734309847 说了，会改成 BV 号

> 作者用b站的api转换BV到av号，性能消耗自然大，换用本地计算就没什么消耗了。

那得问作者愿不愿意改了，包括自定义顶栏会不会根据设置项使用av或BV号。

**Comment by the1812** [comment]
- 不会提供选项改 av / BV
- 网址AV号转换功能隐藏, 原先开着的不受影响, 只能在 Console 中开关
- 脚本内的链接会更换到 BV 号, 以得到更好的性能

**Comment by Geeyun-JY3** [comment]
感觉可以关了
