### ISSUE TITLE
添加or加载本地弹幕的功能

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#1256]
有时候一些冷番很冷清,可以从别的平台下载弹幕文件添加上去

不过实现这功能是不是得着重写播放器啊

**Comment by Coulomb-G** [comment]
请下载视频到本地后,自己手动加载

**Comment by the1812** [comment]
可能得劫持原弹幕的数据? 我不太清楚, 但好像见过这种功能的脚本
