### ISSUE TITLE
快捷键失效

### ISSUE THREAD

**Issue by killer45690** [the1812/Bilibili-Evolved#1257]
今天突然使用快捷键无反应了

**Comment by Coulomb-G** [comment]
请按照issue模板,详细反馈错误信息,另外是否有开启其他脚本?

**Comment by killer45690** [comment]
**关于哪一项功能**
快捷键

**问题描述**

快捷键无反应

**Bilibili-Evolved设置：**

[bilibili-evolved-settings.zip](https://github.com/the1812/Bilibili-Evolved/files/5607784/bilibili-evolved-settings.zip)


**脚本版本**


正式版
Stable v1.11.5
内容包: 5cce766

**浏览器版本**

Chrome ：
版本 87.0.4280.66（正式版本） （64 位）

**个人使用脚本截图：**
![image](https://user-images.githubusercontent.com/42988826/100448870-f1614c00-30ed-11eb-82b4-ffa7cfe67666.png)

**Comment by killer45690** [comment]
另外，在您的提示下，我测试了是否为脚本冲突问题，关闭了除本脚本外的所有脚本，任无反应
**附带截图：**
![image](https://user-images.githubusercontent.com/42988826/100449183-70ef1b00-30ee-11eb-96ce-3c02bb535d79.png)

**Comment by the1812** [comment]
还有其他的浏览器插件吗

**Comment by killer45690** [comment]
**谷歌插件如下：**
![image](https://user-images.githubusercontent.com/42988826/100452260-bcf08e80-30f3-11eb-807d-82d26a667cec.png)

**Comment by the1812** [comment]
看不出来有啥冲突的可能..

**Comment by killer45690** [comment]
那行吧，谢谢大佬了

**Comment by Coulomb-G** [comment]
控制台那边有报错信息吗？

**Comment by killer45690** [comment]
我尝试使用视频加速快捷键
**控制台有报错信息：**
![image](https://user-images.githubusercontent.com/42988826/100455454-b06f3480-30f9-11eb-97b5-6a556e0ccbfb.png)

**Comment by the1812** [comment]
应该是版本号有点问题, 我一会把版本号+1一下

**Comment by killer45690** [comment]
啊这，辛苦大佬了

**Comment by killer45690** [comment]
问题已解决，感谢大佬

**Comment by shilaopia** [comment]
也是播放速度的问题 .1.11.5 没有插件 脚本冲突 求解决方法 控制台无报错

**Comment by mrdobejelly** [comment]
同样失效！控制台也报错。
![2020-11-28_011523](https://user-images.githubusercontent.com/19746097/100472508-57ae9480-3117-11eb-9ffa-85c9c11e6258.png)

**Comment by the1812** [comment]
> 也是播放速度的问题 .1.11.5 没有插件 脚本冲突 求解决方法 控制台无报错

播放速度之前提过了, 我还没修, 不过跟这个快捷键没啥关系
