### ISSUE TITLE
希望能把极简化首页的热门视频去掉哦谢谢~

### ISSUE THREAD

**Issue by Sylvanas-gzh** [the1812/Bilibili-Evolved#1259]
**关于哪一项功能**

**期望的效果**

**脚本版本**

**Comment by Coulomb-G** [comment]
啊这，你只看动态视频的话，去动态页看不就行了么？

**Comment by Sylvanas-gzh** [comment]
也是诶 谢谢啦～ 在2020年11月27日 23:57，Coulomb-G 写道： 

啊这，你只看动态视频的话，去动态页看不就行了么？



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/the1812/Bilibili-Evolved/issues/1259#issuecomment-734896162",

"url": "https://github.com/the1812/Bilibili-Evolved/issues/1259#issuecomment-734896162",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
