### ISSUE TITLE
直播回放页面中左侧隐藏栏的bug

### ISSUE THREAD

**Issue by Along109** [the1812/Bilibili-Evolved#1261]
![image](https://user-images.githubusercontent.com/23724895/100530307-4a82ca00-322b-11eb-9486-7e7aa4128c34.png)
在直播回放页面中，将鼠标放在左侧两个隐藏标签中间，会触发一个无内容黑框，而且只能通过刷新页面来关闭。并且这个黑框极其容易触发，鼠标随便往左边一摆就很容易放到bug触发位置。

**Comment by the1812** [comment]
给个网址?
