### ISSUE TITLE
在视频页面右侧广告位未拦截

### ISSUE THREAD

**Issue by Leisuredpootle** [the1812/Bilibili-Evolved#1268]
**关于哪一项功能**
 广告删除

**问题描述**
出现了新的广告位，不知是否为个例，以下贴出我看到该广告位的部分av号
昨晚未看到广告出现（2020.12.3）
（已打开广告删除功能）
BV1WK411V7Bx
BV1JK4y1f79d
BV1Wz4y1C7Kc
BV1By4y1S7NK
BV1xv411b7DD
**脚本版本**
Preview v1.11.6
内容包: c6eea8e

**浏览器版本**
edge 87.0.664.41

**错误信息**

**附加截图**
![屏幕截图 2020-12-04 171146](https://user-images.githubusercontent.com/50063366/101145535-e3af4780-3654-11eb-867b-98530d8edcbb.png)

**Comment by the1812** [comment]
是新的广告 下次更新会屏蔽掉

**Comment by Geeyun-JY3** [comment]
刚修……#1267
https://github.com/the1812/Bilibili-Evolved/pull/1267/commits/a89593fe78bd65ea9a6b556235829eb907d5a61b

**Comment by Leisuredpootle** [comment]
> 刚修……#1267
> [a89593f](https://github.com/the1812/Bilibili-Evolved/commit/a89593fe78bd65ea9a6b556235829eb907d5a61b)

非常抱歉，未查阅pr（

**Comment by Leisuredpootle** [comment]
> 是新的广告 下次更新会屏蔽掉

麻烦您了
