### ISSUE TITLE
夜间模式下在播放列表（包括收藏夹播放和稍后再看播放）播放合辑视频时，正在播放的视频标题颜色跟其他标题没有区分

### ISSUE THREAD

**Issue by peace-max** [the1812/Bilibili-Evolved#1269]
**关于哪一项功能**
夜间模式在播放列表（包括收藏夹播放和稍后再看播放），播放合辑时，正在播放的视频标题颜色跟其他标题没有区分

**问题描述**

这个问题在一般的合辑播放页面，播放列表（包括收藏夹播放和稍后再看播放）在夜间模式下播放，合辑下的视频标题夜色没有区分。

**脚本版本**

1.11.5

**浏览器版本**

火狐83

**错误信息**

**附加截图**
白天模式下，正在播放的合辑下的视频，标题颜色是主体色。跟其他标题有区分。
![图片](https://user-images.githubusercontent.com/65992527/101158693-182bff00-3667-11eb-9ed9-c4791f30ae53.png)
夜间模式下，合辑下的视频，标题颜色都是白色的，没有了区分。
![图片](https://user-images.githubusercontent.com/65992527/101158708-2417c100-3667-11eb-8574-4586dbf110c4.png)

**Comment by Geeyun-JY3** [comment]
普通播放页的分 P 视频也可以跟进一下这个。现在分 P 名在夜间也是没跟随主题色的，只是最左边有个播放按钮所以也就没发觉有什么问题。

**Comment by Geeyun-JY3** [comment]
噢要不普通视频播放页鼠标悬停右方视频标题附近标题文字跟随主题色也顺便做了吧🙈

**Comment by peace-max** [comment]
> 
> 
> 噢要不普通视频播放页鼠标悬停右方视频标题附近标题文字跟随主题色也顺便做了吧see_no_evil

@LonelySteve 这个问题还没解决。
这个问题应该是：多p视频正在播放的视频标题样色未跟随主题色。

**Comment by the1812** [comment]
@peace-max 如果你用的是正式版 应该还没 现在的修复只发放在预览版上

**Comment by Geeyun-JY3** [comment]
> > 噢要不普通视频播放页鼠标悬停右方视频标题附近标题文字跟随主题色也顺便做了吧see_no_evil
> 
> @LonelySteve 这个问题还没解决。

我这说的其实是相关推荐的视频，确实是没做。

> 这个问题应该是：多p视频正在播放的视频标题样色未跟随主题色。

至于你说的这个，我倒是觉得没什么大问题，只是确实是和白天样式不太一样，但在普通视频页还是能区分的。
而且原版鼠标悬停当前播放 P 也没给用户什么视觉上的反馈，夜间现在这样反而有。

@the1812 我刚刚在预览离线版测试了一下，这个 issue 一开始提的问题好像确实还有

**Comment by LonelySteve** [comment]
> > 噢要不普通视频播放页鼠标悬停右方视频标题附近标题文字跟随主题色也顺便做了吧see_no_evil
> 
> @LonelySteve 这个问题还没解决。
> 这个问题应该是：多p视频正在播放的视频标题样色未跟随主题色。

因为当时没有找有分 p 的视频，不过随手把第一点修了，现在我已经复现了你的问题，马上修
