### ISSUE TITLE
无法下载某些视频

### ISSUE THREAD

**Issue by Risky4Biscuit** [the1812/Bilibili-Evolved#127]
关于哪一项功能
下载视频

问题描述
使用最新版的chrome和Firefox浏览器，点击下载视频，不能弹出清晰度选择下拉菜单，无法正常下载以下视频，但是可以下载其它（更长）视频。

有问题的链接：
https://www.bilibili.com/bangumi/play/ep29882

https://www.bilibili.com/bangumi/play/ss1639?from=search&seid=3794615960476152815

https://www.bilibili.com/bangumi/play/ss1640?from=search&seid=3794615960476152815

脚本版本
正式版1.8

浏览器版本

Firefox浏览器
版本号： 66.0.5 (64-bit)

Google Chrome
版本：74.0.3729.131（正式版本） （64 位）

**Comment by the1812** [comment]
不能弹出菜单时, 浏览器控制台有什么[错误信息](https://github.com/the1812/Bilibili-Evolved/wiki/%E6%9F%A5%E7%9C%8B%E6%B5%8F%E8%A7%88%E5%99%A8%E8%BE%93%E5%87%BA%E7%9A%84%E4%BF%A1%E6%81%AF)吗? 

![console](https://user-images.githubusercontent.com/26504152/57603658-d7f0c180-7594-11e9-8040-f4473b2b33b6.png)

试了下, 都是可以正常下载的

![Snipaste-2019-05-14-12-42-19](https://user-images.githubusercontent.com/26504152/57671376-20b48300-7646-11e9-82da-b4482406d57d.png)

![image](https://user-images.githubusercontent.com/26504152/57671367-17c3b180-7646-11e9-87b6-f7888a9d1c20.png)

**Comment by Risky4Biscuit** [comment]
刚刚试过了，还是不行，这是按下载键后我的console error截图， 请大神过目

![image](https://user-images.githubusercontent.com/39141530/57742406-e2cf5300-7675-11e9-9fe8-4e6e3ea8680a.png)

![image](https://user-images.githubusercontent.com/39141530/57742508-38a3fb00-7676-11e9-933a-9940956fdb28.png)

**Comment by Risky4Biscuit** [comment]
> 不能弹出菜单时, 浏览器控制台有什么[错误信息](https://github.com/the1812/Bilibili-Evolved/wiki/%E6%9F%A5%E7%9C%8B%E6%B5%8F%E8%A7%88%E5%99%A8%E8%BE%93%E5%87%BA%E7%9A%84%E4%BF%A1%E6%81%AF)吗?

刚刚试过了，还是不行，这是按下载键后我的console error截图， 请大神过目

![image](https://user-images.githubusercontent.com/39141530/57742576-7f91f080-7676-11e9-970d-b72e79c31346.png)

![image](https://user-images.githubusercontent.com/39141530/57742581-86b8fe80-7676-11e9-892e-c0b2f43b5fdd.png)

**Comment by the1812** [comment]
我这下载功能用的官方的源, 如果原本无法观看, 即使用了解除区域限制脚本也是无法下载的...

**Comment by Risky4Biscuit** [comment]
我可以用解除区限脚本看这些视频没问题,但是很奇怪就是不能下载,点了没分辨率的选项啊

**Comment by the1812** [comment]
可能我说得不太清楚...
假如那个视频(地区限制, 会员抢先之类的)无法用你的账号**直接观看**(不借助任何脚本), 那么我的脚本便**无法下载**.
解除区域限制是从**别的服务器**加载并播放视频的, 我的脚本是从**官方服务器**下载视频的, 所以会造成你能观看却无法下载的情况.
要下载只能去解除区域限制用的服务器那里去找了, 比如[biliplus](https://www.biliplus.com)

**Comment by Risky4Biscuit** [comment]
欧。。。明白了，多谢多谢
