### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by TTTPOB** [the1812/Bilibili-Evolved#1270]
**关于哪一项功能**

自定义弹幕字体

**期望的效果**
我能够使用自己喜欢的字体作为弹幕字体

**脚本版本**
865.32 Preview Offline

**Comment by the1812** [comment]
见 #807
如果想所有网页都换成自己想要的字体, 可以看下 #370

**Comment by TTTPOB** [comment]
唔，我居然没搜到，抱歉
嗯我在用stylish类似物
