### ISSUE TITLE
b站现在可以免大会员看 720p60 了，能不能出一个选项，照顾一下愿意牺牲清晰度换帧数的非大会员用户？

### ISSUE THREAD

**Issue by zkzmba793** [the1812/Bilibili-Evolved#1271]
**期望的效果**
发现视频画质有 720p60 的时候就自动切换，没有的话就选择 非大会员用户能选的最高画质

**脚本版本**
Preview Offline v865.32

**Comment by Tinhone** [comment]
感觉这issue可以关了...B站目前已经不再提供720p60选项
