### ISSUE TITLE
显示空白

### ISSUE THREAD

**Issue by Hzmaaa** [the1812/Bilibili-Evolved#1272]
![K{@PTR`Z)V5I_@KIJ`RBO`5](https://user-images.githubusercontent.com/73585448/101245479-2bfb6200-3748-11eb-8c6e-3077cb9c8a90.png)
![O63V7P)H)K7$KTBT%5WG6DS](https://user-images.githubusercontent.com/73585448/101245495-43d2e600-3748-11eb-9b8b-7b1e797b9e5e.png)
主页和直播界面显示空白

**Comment by Coulomb-G** [comment]
请按照issue模板,详细反馈详细信息

**Comment by the1812** [comment]
见 #1225
