### ISSUE TITLE
“夜间模式跟随系统”可能存在问题

### ISSUE THREAD

**Issue by shenzhiming88** [the1812/Bilibili-Evolved#1273]
**关于哪一项功能**
夜间模式跟随系统

**问题描述**

主题为“深色”时，仍不会打开“夜间模式”；手动打开，刷新后又自动关闭

**脚本版本**

正式版1.11.5

**浏览器版本**

Microsoft Edge
版本 87.0.664.47 (官方内部版本) (64 位)

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/66902050/101269050-36981480-37a5-11eb-8e15-1909c677721d.png)

**Comment by Coulomb-G** [comment]
跟随系统是跟随系统的「夜间模式」，而不是跟随系统的「主题色」

**Comment by the1812** [comment]
Windows 版本是多少?

**Comment by shenzhiming88** [comment]
> 跟随系统是跟随系统的「夜间模式」，而不是跟随系统的「主题色」

您好！
打开了夜间模式，但是仍然无效

**Comment by shenzhiming88** [comment]
> Windows 版本是多少?

您好！
20H2（内部版本：19042.630）

**Comment by shenzhiming88** [comment]
抱歉，这个问题是因为我的Microsoft Edge的默认设置中，“默认主题”是浅色而不是系统默认，而这个跟随的是浏览器而非系统的深/浅色变化。如果可能的话，建议改一下吧，以免引起误导

**Comment by the1812** [comment]
原来如此...我改下说明吧
