### ISSUE TITLE
希望增加可选视频和番剧的默认画质

### ISSUE THREAD

**Issue by DarknessLeaf** [the1812/Bilibili-Evolved#1274]
**关于哪一项功能**

视频和番剧的播放画质

**期望的效果**
现有的是可选直播默认画质，观看B站视频经常会调到自动，而不是最高画质，希望可以增加视频和番剧默认画质，或者是可选默认最高画质

**脚本版本**
1.11.5

**Comment by Coulomb-G** [comment]
b站现在是自带视频画质记忆功能啊

**Comment by the1812** [comment]
找个真彩HDR的视频, 手动选下真彩HDR, 以后的视频就都是最高画质

**Comment by DarknessLeaf** [comment]
好吧，谢啦

**Comment by Windman1320** [comment]
悲，现在视频默认会选择720p画质
