### ISSUE TITLE
弹幕的点赞和举报功能

### ISSUE THREAD

**Issue by Misaka-master** [the1812/Bilibili-Evolved#1276]
弹幕不能点赞和举报,脚本禁用就可以

**Comment by Coulomb-G** [comment]
请按照issue模板，详细反馈信息
比如脚本版本是多少？

**Comment by the1812** [comment]
我故意禁了的, 否则很多附到视频上的额外功能都会无效, 比如双击全屏

**Comment by Misaka-master** [comment]
那能不能加回来,让这两个功能不冲突
双击全屏打开就自动禁用弹幕点赞和举报

**Comment by Coulomb-G** [comment]
又不只是这两个功能有冲突

**Comment by the1812** [comment]
开浏览器控制台(<kbd>Ctrl+Shift+I</kbd>), 运行这段代码:
```JavaScript
bilibiliEvolved.installStyle({name: 'restoreDanmakuLayer', style: `
.bilibili-player-dm-tip-wrap {
  pointer-events: initial !important;
}`, displayName: '恢复弹幕点赞', mode: 'important'})
```

**Comment by Misaka-master** [comment]
> 开浏览器控制台(Ctrl+Shift+I), 运行这段代码:
> 
> ```js
> bilibiliEvolved.installStyle({name: 'restoreDanmakuLayer', style: `
> .bilibili-player-dm-tip-wrap {
>   pointer-events: initial !important;
> }`, displayName: '恢复弹幕点赞', mode: 'important'})
> ```

好的谢谢,那请问这是每次都得运行,还是只用运行这一次

**Comment by the1812** [comment]
永久有效, 除非你重装脚本

**Comment by Misaka-master** [comment]
好的,谢谢
