### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by victorchen304** [the1812/Bilibili-Evolved#1279]
**关于哪一项功能**

**期望的效果**

**脚本版本**

**Comment by victorchen304** [comment]
希望能有分组查看动态的功能

**Comment by victorchen304** [comment]
比如按关注分组查看、屏蔽特定up之类的

**Comment by Coulomb-G** [comment]
分组查看这个估计得找b站比较方便,或者使用特别关注功能,在关注栏会放置在前排
屏蔽特定up请使用取关,拉黑,或者动态过滤器功能

**Comment by Geeyun-JY3** [comment]
在动态首页是吧？可以试试这个脚本：https://greasyfork.org/scripts/396032

**Comment by victorchen304** [comment]
是的，我知道这个脚本，但是遗憾的是它不能保存我的设置，有些不便www


发送自我的盖乐世



-------- 原始信息 --------
发件人： Geeyun-JY3 <notifications@github.com>
日期: 2020/12/6 23:47 (GMT+08:00)
收件人： the1812/Bilibili-Evolved <Bilibili-Evolved@noreply.github.com>
抄送： victorchen304 <victor20040418@hotmail.com>, Author <author@noreply.github.com>
主题： Re: [the1812/Bilibili-Evolved] 建议 (#1279)


在动态首页是吧？可以试试这个脚本：https://greasyfork.org/scripts/396032

―

**Comment by Geeyun-JY3** [comment]
> 是的，我知道这个脚本，但是遗憾的是它不能保存我的设置，有些不便www

那为啥不去跟这个脚本作者提……
