### ISSUE TITLE
自动从历史点播放视频在番剧页表现糟糕

### ISSUE THREAD

**Issue by aliofwind** [the1812/Bilibili-Evolved#128]
**关于哪一项功能**

自动从历史点播放视频
**问题描述**

因为是追剧，所以每次打开新的一集都会自动刷新跳转到上一集的末尾，体验非常差
**脚本版本**

305.87
**浏览器版本**

chrome72
**错误信息**

**Comment by the1812** [comment]
那就加个不跨集跳转的选项吧
