### ISSUE TITLE
最近b站访问是不是变慢了

### ISSUE THREAD

**Issue by deathwood** [the1812/Bilibili-Evolved#1280]
其他都出来了，顶栏一直不出来，也可能是Edge的原因，用Safari就不会

**Comment by the1812** [comment]
哪个页面?

**Comment by deathwood** [comment]
> 哪个页面?

首页

**Comment by the1812** [comment]
有用简化首页的话可以看下 https://github.com/the1812/Bilibili-Evolved/blob/master/src/style/simplify-home/simplify-home.md

**Comment by deathwood** [comment]
> 有用简化首页的话可以看下 https://github.com/the1812/Bilibili-Evolved/blob/master/src/style/simplify-home/simplify-home.md

添加规则之后除了推荐全白了qwq
![image](https://user-images.githubusercontent.com/39521541/101485634-61958a80-3996-11eb-803d-26fcaf1d4b6f.png)

**Comment by the1812** [comment]
这是`简化首页`功能用的... 你如果没开就要不用这个规则
