### ISSUE TITLE
希望能把【顶栏】-【历史】-【直播】里的正在直播的项目变色

### ISSUE THREAD

**Issue by 879846730** [the1812/Bilibili-Evolved#1282]
**关于哪一项功能**

**期望的效果**

**脚本版本**

**Comment by LonelySteve** [comment]
事实上原版顶栏这块也没有在鼠标悬浮的时候使标题变色，如果希望有这种效果的话，可以尝试开启「自定义顶栏」这个功能

**Comment by the1812** [comment]
开了自定义顶栏要看正在直播的话, 可以到`动态`里的`直播`标签下查看
