### ISSUE TITLE
关闭自动连播

### ISSUE THREAD

**Issue by LonelySteve** [the1812/Bilibili-Evolved#1285]
**关于哪一项功能**

目前「隐藏视频推荐」这个功能会将「自动连播」的开关也一起隐藏掉：

![image](https://user-images.githubusercontent.com/34429322/101453527-70664800-396a-11eb-84c7-b950c5dfa6fb.png)

建议增加一个设置项，方便在「隐藏视频推荐」功能开启时关闭自动连播

**脚本版本**

Preview v1.11.6

**Comment by Coulomb-G** [comment]
你是需要反复开关自动连播?

**Comment by the1812** [comment]
这个开关没有记忆？

**Comment by LonelySteve** [comment]
不是，之前启用这个功能的时候没注意它还隐藏了自动连播的开关，后来发现在没有明显提示的情况下自动连播了，用户需要关闭「隐藏视频推荐」这个功能才能找到这个开关，然而只在设置项中搜索「自动连播」是没有任何相关项的，如果偷懒一点的话，可以在功能提示中加上这点

**Comment by Coulomb-G** [comment]
因为自动播放这个功能还没上线,还是灰度中,很多人还没有,在功能上b站是将其和视频推荐组合在一起的,提醒的话,下次正式版更新还没上线这个功能的话,可以加上

**Comment by the1812** [comment]
懂了 我加到功能提示里吧

**Comment by nullnullnullnull0** [comment]
> 这个开关没有记忆？

自动连播手动关闭后,有时候重启浏览器又自动开启了,真的很烦.希望可以把永久关闭自动连播加入脚本中.

**Comment by VergilGao** [comment]
b站这个功能真的太阴间了，时不时就会自动打开，希望能把这个开关加到脚本里，强制关闭掉。

**Comment by the1812** [comment]
我这里至今没有这功能
你们有没有开了别的插件/脚本可能影响这里的?

**Comment by VergilGao** [comment]
> 我这里至今没有这功能
> <img alt="" width="400" src="https://user-images.githubusercontent.com/26504152/109791611-98093b80-7c4d-11eb-9bbc-a57bedd37df4.png">
> 
> 你们有没有开了别的插件/脚本可能影响这里的?

没有
![2021-03-03_21-23-29](https://user-images.githubusercontent.com/8655163/109812211-c34c5480-7c66-11eb-8f29-9366460c28eb.png)
隐私模式，没插件也有这个。
公司的电脑没有这个。。。

**Comment by VergilGao** [comment]
找到了这个开关的问题了：
这种多P的视频：
https://www.bilibili.com/video/BV1Ev41187oc
播放器上齿轮选择 更多设置 - 自动切集 会同时打开自动连播。
不是很懂为什么这两个开关会是关联的。

**Comment by the1812** [comment]
多P的连播开关和单P的推荐视频开关是同一个, 这显然不对, 等 b 站修复吧
