### ISSUE TITLE
夜间模式下搜索结果页标签的字体颜色问题

### ISSUE THREAD

**Issue by TTTTTony32** [the1812/Bilibili-Evolved#129]
**关于哪一项功能**
夜间模式

**问题描述**
开启夜间模式后，搜索结果页的各个标签字体颜色没有变化，融于背景色中导致看不清
复现率100%

**脚本版本**
正式版 1.8.0

**浏览器版本**
Chrome 74.0.3729.169

**错误信息**
无

**附加截图**
![Snipaste_2019-05-24_23-32-43](https://user-images.githubusercontent.com/33298361/58339812-fac88300-7e7c-11e9-91f8-7ca60aedd699.png)

**Comment by Coulomb-G** [comment]
预览版已修复,下次正式版更新后会正常显示
