### ISSUE TITLE
下载某些DASH视频会出现 视频片段20请求失败, response = 416 请问如何解决

### ISSUE THREAD

**Issue by zsguy** [the1812/Bilibili-Evolved#1294]
**关于哪一项功能**

**问题描述**

**脚本版本**

Stable v1.11.5
内容包: d5d92dc

**浏览器版本**

Cent Browser
版本 4.3.9.210（正式版本） （64 位） (Chromium 86.0.4240.198)

**错误信息**

**附加截图**
![QQ截图20201210152246](https://user-images.githubusercontent.com/32629359/101734726-ae46a600-3afb-11eb-9c8b-c611fc2894a6.jpg)
![QQ截图20201210152303](https://user-images.githubusercontent.com/32629359/101734736-b272c380-3afb-11eb-822b-86afac9646b7.jpg)

**Comment by the1812** [comment]
多试几次 或者用下面的导出

416是直接下载的老bug了

**Comment by zsguy** [comment]
> 多试几次 或者用下面的导出
> 
> 416是直接下载的老bug了
原来是老bug了啊,那我多试几次吧.的确喝多视频都正常,就其中几个视频才这样.
