### ISSUE TITLE
与 解除B站区域限制 冲突

### ISSUE THREAD

**Issue by Kougami-YT** [the1812/Bilibili-Evolved#1295]
开启插件某些仅限港澳台的番剧会加载不出来
如 安达与岛村 （巨人可以加载）

**Comment by nd002723** [comment]
[https://www.bilibili.com/bangumi/media/md28230188/](![安达与岛村](https://i.loli.net/2020/12/11/5829vqDVXyo3w1C.png))
不冲突，有个别番剧仅限客户端看这个无解

**Comment by nd002723** [comment]
![安达与岛村](https://i.loli.net/2020/12/11/5829vqDVXyo3w1C.png)
不冲突，有个别番剧仅限客户端看这个无解

**Comment by Kougami-YT** [comment]
> 开启插件某些仅限港澳台的番剧会加载不出来
> 如 安达与岛村 （巨人可以加载）
