### ISSUE TITLE
建议截图添加可右键复制和弹幕支持

### ISSUE THREAD

**Issue by MapleRecall** [the1812/Bilibili-Evolved#130]
**关于哪一项功能**
视频截图

**期望的效果**
截图一种十分常见的场景是马上复制粘贴到群之类的地方，但是现在截图浮层上有个mask，没法直接右键复制……

另外对于canvas渲染方式的弹幕甚至可以十分轻松的合成带有弹幕的截图~

**Comment by the1812** [comment]
给mask加了点击穿透, 现在可以右键了
弹幕先鸽了 以后再弄🕊

**Comment by the1812** [comment]
已支持加shift键截带弹幕的图(仅限canvas渲染)
