### ISSUE TITLE
下载页面（封面、弹幕、视频）保存时加入 AV 号和视频发布日期

### ISSUE THREAD

**Issue by doio** [the1812/Bilibili-Evolved#131]
**关于哪一项功能**
附加功能的`查看封面`、`下载弹幕`、`下载视频`的**保存文件名**

**期望的效果**
保存的不仅仅有投稿标题，在开头还加上 AVxxxxxxxx 2019-05-25 (12:12:12) 以方便整理
或者能添加个开关？

**脚本版本**

离线版 301.00

**Comment by the1812** [comment]
现在可以[自定义文件名](https://github.com/the1812/Bilibili-Evolved#%E5%8A%9F%E8%83%BD)了.
如果需要文件名带上av号和日期时间, 可以改成`[AVaid ][y]-[M]-[d] ([h]-[m]-[s]) [title][ - ep]`

**Comment by doio** [comment]
好棒！！给作者点个大大的赞！！ ☆(￣▽￣)/$:*
