### ISSUE TITLE
使用插件顶栏时，稍后再看和收藏页面在加载过一次之后第二次载入不会刷新

### ISSUE THREAD

**Issue by AQ-Official** [the1812/Bilibili-Evolved#1311]
**关于哪一项功能**
使用插件顶栏时，稍后再看和收藏页面在加载过一次之后第二次载入不会刷新

**问题描述**
任何页面，
使用插件顶栏时，稍后再看和收藏页面在加载过一次之后第二次载入不会刷新
b站原生顶栏每次鼠标移入时都会重新拉取一次。

**脚本版本**
Stable v1.11.5
内容包: c1a6ce9

**浏览器版本**
版本 87.0.4280.88（正式版本） （64 位）

**Comment by the1812** [comment]
这样的吗, 以前写这个的时候原生顶栏也是不刷新的, 我之后改下吧

**Comment by the1812** [comment]
其他还有需要刷新的吗 我一起解决掉

**Comment by AQ-Official** [comment]
目前我发现比较印象体验的就这两个吧 可以把顶栏都检查一遍 都改成每次鼠标移入就刷新一次

**Comment by Geeyun-JY3** [comment]
> 其他列表还有需要刷新的吗

还有个历史吧……开了个新的标签页后产生了新的浏览历史

另外消息中心我提到的 [这种](https://github.com/the1812/Bilibili-Evolved/issues/902#issuecomment-730374402) 算不算（老实说没测试过原版顶栏这种情况会怎样）？

**Comment by AQ-Official** [comment]
> > 其他列表还有需要刷新的吗
> 
> 还有个历史吧……开了个新的标签页后产生了新的浏览历史
> 
> 另外消息中心我提到的 [这种](https://github.com/the1812/Bilibili-Evolved/issues/902#issuecomment-730374402) 算不算（老实说没测试过原版顶栏这种情况会怎样）？

算吧 刷新不及时

**Comment by kanzakiken** [comment]
你好,请问这个问题你最终解决了吗,强迫症看着太不舒服了.

**Comment by Geeyun-JY3** [comment]
@kanzakiken https://github.com/the1812/Bilibili-Evolved/commit/38f39be9c5891b395e6372b797d1d906241b0c84 修了
