### ISSUE TITLE
B站直播更新后默认直播画质功能失效

### ISSUE THREAD

**Issue by aliofwind** [the1812/Bilibili-Evolved#1324]
**关于哪一项功能**
默认直播画质

**问题描述**

B站直播更新后默认直播画质功能失效

**脚本版本**

882.74

**浏览器版本**

Chrome 86 Stable

**错误信息**

在Bilibili HTML5 Live Player 2.5.2出现问题

**附加截图**
![image](https://user-images.githubusercontent.com/35068322/102340927-1270da80-3fd2-11eb-8943-0e69b0b893fc.png)

**Comment by FlareMonso** [comment]
顺带一提，直播全屏弹幕栏也没了
![image](https://user-images.githubusercontent.com/67825783/102372823-9048dc00-3ffa-11eb-9aaf-da50348cb9b6.png)

**Comment by GalaxySnail** [comment]
另外因为直播间改版，夜间模式也有一些问题，粉丝勋章的背景色不能正常变为深色

![开夜间模式前](https://user-images.githubusercontent.com/53637421/102501844-d82e3880-40b8-11eb-963f-a216a265964e.png)
![开夜间模式后1](https://user-images.githubusercontent.com/53637421/102501872-debcb000-40b8-11eb-8323-588ab741efc4.png)

另外，这一部分的背景似乎会被静默地替换，我观察到有一会儿突然变成白色的了但没有截图，后来又变成了下面这张图片

![开夜间模式后2](https://user-images.githubusercontent.com/53637421/102503565-cd74a300-40ba-11eb-8e86-f930bcd94819.png)
![QQ截图20201217225538](https://user-images.githubusercontent.com/53637421/102504888-55a77800-40bc-11eb-981e-52fb964bfd00.png)

**Comment by daofeng2015** [comment]
还不如用js把改的全都改回去..新的直播也没太拉跨了

**Comment by GShyx** [comment]
同直播间夜间模式聊天框部分问题
![image](https://user-images.githubusercontent.com/39543437/102612463-ae821980-416b-11eb-95ba-1627d828a48b.png)

**Comment by Geeyun-JY3** [comment]
@GalaxySnail @GShyx 夜间模式的问题在 #1289 有反馈了

**Comment by the1812** [comment]
默认画质得搞清楚这玩意怎么用:
```js
unsafeWindow.livePlayer.switchQuality
```
原先是直接模拟鼠标点击那个切换画质的地方, 但现在改版后那里只有鼠标经过的时候才有

弹幕栏倒是可以适配过去

**Comment by wyq977** [comment]
好像现在也是不行呢 @the1812 

v2.2.2

试了几个插件也还是不行

[bilibili直播默认最高画质](https://greasyfork.org/en/scripts/441090-bilibili%E7%9B%B4%E6%92%AD%E9%BB%98%E8%AE%A4%E6%9C%80%E9%AB%98%E7%94%BB%E8%B4%A8)

[哔哩哔哩（bilibili）播放器辅助设置](https://greasyfork.org/zh-CN/scripts/429133-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9-bilibili-%E6%92%AD%E6%94%BE%E5%99%A8%E8%BE%85%E5%8A%A9%E8%AE%BE%E7%BD%AE)

**Comment by the1812** [comment]
这个当时只修复了弹幕栏, 默认直播画质暂时不做了, 太麻烦

**Comment by catshitz** [comment]
> > 这个当时只修复了弹幕栏, 默认直播画质暂时不做了, 太麻烦
> 
> 请求重新适配直播默认原画功能 目前一些可用实现 [bilibili直播默认原画画质](https://greasyfork.org/zh-CN/scripts/451099-bilibili%E7%9B%B4%E6%92%AD%E9%BB%98%E8%AE%A4%E5%8E%9F%E7%94%BB%E7%94%BB%E8%B4%A8) [bilibili直播默认最高画质](https://greasyfork.org/zh-CN/scripts/458957-bilibili%E7%9B%B4%E6%92%AD%E9%BB%98%E8%AE%A4%E6%9C%80%E9%AB%98%E7%94%BB%E8%B4%A8)

不是 一个直播自动最高画质的基本需求市场里没有 还要单独另外装一个脚本才能实现 要这evolve脚本还有啥用？😅
