### ISSUE TITLE
右下角提示unexpected token: identifier

### ISSUE THREAD

**Issue by silky-heart** [the1812/Bilibili-Evolved#1326]
我需要提交什么信息帮助判断问题？

**Comment by Geeyun-JY3** [comment]
> 我需要提交什么信息帮助判断问题？

模板不是有写吗……

**Comment by the1812** [comment]
#1227 ?

**Comment by silky-heart** [comment]
@Geeyun-JY3 


关于哪一项功能：我也不知道，打开什么视频都有。

问题描述：就弹对话框。其他好像什么都没影响。
脚本版本：Stable v1.11.5 内容包: 2755e05
浏览器版本：firefox 83.0 64位
错误信息：错误——unexpected token: identifier

**Comment by silky-heart** [comment]
我自己看看研究一下……
