### ISSUE TITLE
复制链接功能无法使用

### ISSUE THREAD

**Issue by MC-dusk** [the1812/Bilibili-Evolved#1330]
>（我理解的“复制链接”功能指“复制动态/评论对应的url，比如“https://t.bilibili.com/111 ”或“https://www.bilibili.com/video/av123#reply456 ”）

>如题，无论是“复制评论链接”还是“复制动态链接”，开启功能后菜单有按钮，但按下后无反应，点粘贴什么也没有。
如果之前剪贴板有内容，比如已经复制了“abc”，按下“复制链接”后再粘贴，粘贴不出东西，也就是说剪贴板被重写了，但没写入链接。

火狐83.0
暴力猴v2.12.8
脚本 Stable v1.11.5 内容包: 7a73519

_Originally posted by @MC-dusk in https://github.com/the1812/Bilibili-Evolved/discussions/1329_

已验证在TamperMonkey可复制，但菜单不会消失 #1196 

（如果经常出现暴力猴的兼容问题，干脆写上“本脚本不支持暴力猴”？）

**Comment by Geeyun-JY3** [comment]
@the1812 Bug 反馈这个 issue template 或者可以加个所使用的脚本管理器及其版本？

**Comment by the1812** [comment]
应该不用吧 大部分情况下都是兼容 Violentmonkey 的

**Comment by Geeyun-JY3** [comment]
> @the1812 Bug 反馈这个 issue template 或者可以加个所使用的脚本管理器及其版本？

emm 说不准呢……总会有些差异……随你吧
