### ISSUE TITLE
解除B站地域限制无效

### ISSUE THREAD

**Issue by DIFCODE-002** [the1812/Bilibili-Evolved#1343]
**关于哪一项功能**
脚本显示运行 但是网页显示找不到 或 当前地区无法观看

**问题描述**

搜索进击的巨人 点开第二季会显示找不到 点开第三季会显示当前区域不可观看 因为版权

**脚本版本**

// @version      8.0.7

**浏览器版本**

版本 87.0.4280.88（正式版本） （64 位）

**错误信息**

无自动报错 前三天左右发现有出问题
再早一点，我想看第二季，可以点开第三季，从右侧相关番剧点进第二季观看。最近两天就不行了，因为第三季也不能看了，右边相关番剧也不推送了。

**附加截图**

**Comment by Geeyun-JY3** [comment]
反馈错地了吧……
