### ISSUE TITLE
B站使用清爽界面之后，不显示排行榜的视频了。

### ISSUE THREAD

**Issue by yanyudalao** [the1812/Bilibili-Evolved#1345]
**关于哪一项功能**
界面显示问题

**问题描述**

在清爽界面下，不显示排行榜的视频了。只有推荐。

**脚本版本**

Stable v1.11.5

**浏览器版本**

版本 87.0.4280.88（正式版本） (x86_64)

**错误信息**

无

**附加截图**
![image](https://user-images.githubusercontent.com/50091215/102759784-8f73c980-43af-11eb-975a-649e3039e602.png)

**Comment by Coulomb-G** [comment]
是否有开其他脚本？控制台报错信息是什么？

**Comment by the1812** [comment]
窗口宽度太窄了

**Comment by yanyudalao** [comment]
> 窗口宽度太窄了

果然如此。。。_(:з」∠)_ 
是我的电脑太辣鸡，不是BUG
