### ISSUE TITLE
下载的视频使用.txt后缀

### ISSUE THREAD

**Issue by LemonedQ** [the1812/Bilibili-Evolved#1347]
**关于哪一项功能**
下载

 **问题描述**
下载后的视频使用.txt后缀，改为.flv后可以正常播放

**脚本版本**
Stable v1.11.5

**浏览器版本**
Chrome 版本 87.0.4280.88（正式版本） （64 位）

**附加截图**
![image.png](https://i.loli.net/2020/12/22/8cxl3F5JjabmAp4.png)

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/102840689-5b93b500-443e-11eb-936e-f00b456a2061.png)

**Comment by Night0Stalker** [comment]
我也有同样的问题 
Stable v1.11.5 内容包: 3d40984
浏览器：Microsoft Edge 版本 87.0.664.66 (官方内部版本) (64 位)
电脑：MacBookpro 版本10.15.4
