### ISSUE TITLE
希望添加直播弹幕白名单过滤功能以及禁止直播首页自动播放功能

### ISSUE THREAD

**Issue by yuyuyzl** [the1812/Bilibili-Evolved#135]
**关于哪一项功能**
刚从NGA的帖子过来，了解到有这样一个脚本非常感谢！
对于我自己用b站的两个痛点有两个希望增加的功能。

**期望的效果**
1.本人是虚拟主播区的DD，平时在看直播的时候会有同传大佬用弹幕翻译，但是B站没有提供针对特定用户或者特定发言规则的白名单功能，只有用户黑名单和关键词黑名单。
我觉得，如果实现方便的话，希望增加正则匹配弹幕内容和/或匹配特定用户的白名单功能。
这样也可以方便我们在客户端自行过滤脚本哥（最近有一批高级脚本很烦）
2.需要进特定用户直播间的时候总会经过哔哩哔哩直播首页，但是首页上那个自动播放的直播间比较吵，不知道能否增加直播首页自动静音/自动暂停的功能呢

再次感谢。

**脚本版本**

预览版

**Comment by Coulomb-G** [comment]
关于脚本哥方面的问题,事实上已经有杀脚本哥的脚本了[https://github.com/bilibili-dd-center/bilibili-live-noscript](url)
我个人觉得对待直播间弹幕环境并不应该是过滤脚本哥,更好的方法应该是直接由房管使用脚本批量封禁脚本哥,以此来彻底净化整个弹幕环境

**Comment by Coulomb-G** [comment]
> 关于脚本哥方面的问题,事实上已经有杀脚本哥的脚本了https://github.com/bilibili-dd-center/bilibili-live-noscript
> 我个人觉得对待直播间弹幕环境并不应该是过滤脚本哥,更好的方法应该是直接由房管使用脚本批量封禁脚本哥,以此来彻底净化整个弹幕环境

**Comment by the1812** [comment]
预览版已添加直播首页自动暂停的功能
