### ISSUE TITLE
顶部栏下拉菜单在视屏页有时候无法选中选项

### ISSUE THREAD

**Issue by ZLHad** [the1812/Bilibili-Evolved#1353]
**关于哪一项功能**
顶部栏下拉菜单在视屏页有时候无法选中选项

**问题描述**
当在具体视频页内，点击网页头部顶部栏的时候，比如“消息”，无法选中下拉列表中的选项，会被默认到鼠标正在点击视频，怀疑是因为这个列表层级问题，因为关注到右侧“弹幕列表”左上角的地方会遮住“动态下拉框”

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by the1812** [comment]
有截图吗, 以及有没有开`关灯模式`?
