### ISSUE TITLE
希望能够调整左边小齿轮的位置

### ISSUE THREAD

**Issue by wildeparadox** [the1812/Bilibili-Evolved#136]
只是小小的建议，如果可以调整的话是最好不过了

**Comment by the1812** [comment]
具体想放在哪里呢, 是右边还是上下移动位置?

**Comment by wildeparadox** [comment]
上下移动吧，我个人的话想稍微能放下面一点……

**Comment by wildeparadox** [comment]
上下移动吧，我个人的话想稍微能放下面一点……

**Comment by linwan623910** [comment]
左边中间或右边中间，真的超级难找，建议考虑下四个角，因为能直接鼠标直接达到，

在左边中间的时候，我真的找的好哭，好像在摸鱼一样，特别是如果经常设置或下载需要点开的时候。

**Comment by the1812** [comment]
角落不是更难碰到 又不是整个屏幕的角落
上面是浏览器标签界面 下面是系统任务栏

**Comment by linwan623910** [comment]
刚忘了我是隐藏任务栏的，不过即使不隐藏，真的也比中间好找，因为中间是没概念的，差一点点就不出出现，

**Comment by the1812** [comment]
那就别隐藏脚本的图标啊

**Comment by linwan623910** [comment]
原来还有不隐藏图标的功能，我的天……我哪找漏了么。。。我。。。

**Comment by the1812** [comment]
而且就算隐藏了 鼠标直接碰到边上 图标就会弹出来 你再把鼠标移过去就行了 (#513 的功能提议)

**Comment by linwan623910** [comment]
不是的，我之前的体验不是这样的，之前鼠标碰到边上，是不会出来齿轮的，除非是很准很准的正正中间

不过刚设置了下不隐藏，再改成隐藏，就有你说的效果了，随便碰下边，就能出来齿轮。

不过我最终还是换成了不隐藏，哈，开心。

谢谢作者，插件真的好用。
