### ISSUE TITLE
顶栏搜索框无法展开

### ISSUE THREAD

**Issue by Harmonyano** [the1812/Bilibili-Evolved#1363]
**问题描述**
顶栏搜索框默认不展开，鼠标放到上面去也不会展开，可能是什么样式设置 overwrite 了
但是我没有开启“使用自定义顶栏”这一功能，反而开启它以后搜索栏正常了，但是收藏夹关注啥的就变成自定义版了。

**脚本版本**
Offline 857.15 （原来用的正式版也有这个问题）

**浏览器版本**
Firefox 84.0.1

**附加截图**
![问题截图](https://user-images.githubusercontent.com/30450690/103097852-9f0b4080-4643-11eb-8fb6-72890b186989.png)
![正常截图](https://user-images.githubusercontent.com/30450690/103097954-09bc7c00-4644-11eb-8a29-289d5faa8835.png)

**Comment by Geeyun-JY3** [comment]
是不是窗口宽度太窄了

**Comment by Harmonyano** [comment]
还真是…缩放调到100%就好了
自定义顶栏会让它重新显示出来好像是因为自定义顶栏是固定宽度不是按比例？

**Comment by Geeyun-JY3** [comment]
> 自定义顶栏会让它重新显示出来好像是因为自定义顶栏是固定宽度不是按比例？

自定义顶栏和原版顶栏已经没关系了，那是自定义顶栏的组件。
