### ISSUE TITLE
倍速调节快捷键失效

### ISSUE THREAD

**Issue by PR2403** [the1812/Bilibili-Evolved#1368]
**关于哪一项功能**
倍速调节快捷键

**问题描述**
倍速快捷键shift+↑失效。但正式版1.11.5正常。

**脚本版本**
预览版1.11.9

**浏览器版本**
Chrome87.0.4280.88

**错误信息**

**附加截图**

**Comment by the1812** [comment]
我漏打了个空格...
![image](https://user-images.githubusercontent.com/26504152/103123996-1e8b2500-46c1-11eb-8e29-c7ee993114a7.png)

**Comment by PR2403** [comment]
我可不可以在本地临时修改一下，还是只能等下次更新

**Comment by PR2403** [comment]
> 我漏打了个空格...
> ![image](https://user-images.githubusercontent.com/26504152/103123996-1e8b2500-46c1-11eb-8e29-c7ee993114a7.png)

我可不可以在本地修改一下，还是只能等下次更新

**Comment by PR2403** [comment]
@the1812 我可不可以在本地修改一下，还是只能等下次更新

**Comment by the1812** [comment]
应该可以改的:
https://github.com/the1812/Bilibili-Evolved/blob/preview/src/video/keymap/key-bindings.md
```JavaScript
bilibiliEvolved.customKeyBindings = {
  videoSpeedIncrease: 'shift > 》 arrowUp',
}
```

**Comment by PR2403** [comment]
@the1812 指令没有生效
![image](https://user-images.githubusercontent.com/64511917/103133741-22ca3900-46e7-11eb-9ff2-4f043e5b2b15.png)

**Comment by the1812** [comment]
抱歉这里也漏打了, 应该是
```JavaScript
bilibiliEvolved.settings.customKeyBindings = {
  videoSpeedIncrease: 'shift > 》 arrowUp',
}
```

**Comment by PR2403** [comment]
@the1812 好了，感谢。不过你这错了2次，2333.。。。。

**Comment by the1812** [comment]
<img src="https://i0.hdslb.com/bfs/emote/1afb5eb96846e0876071eeecb47be95dbf55f08d.png" width="22">
