### ISSUE TITLE
视频简介“字幕制作者”信息丢失

### ISSUE THREAD

**Issue by MC-dusk** [the1812/Bilibili-Evolved#1369]
**关于哪一项功能**

自动展开视频简介

**问题描述**

开启“自动展开视频简介”功能后，“字幕制作者”信息丢失
测试视频：https://www.bilibili.com/video/BV1JE411N7UD

**脚本版本**

Stable v1.11.5
内容包: e0abbe8

**浏览器版本**

火狐84.0.1

**错误信息**

太多了，暂时没放上来，需要再贴

**附加截图**
![image](https://user-images.githubusercontent.com/52311860/103131580-38b10d00-4699-11eb-828b-02dfcac1d42e.png)
开启功能：
![image](https://user-images.githubusercontent.com/52311860/103131694-ac531a00-4699-11eb-9f8e-e07bb8981af7.png)
关闭功能：
![image](https://user-images.githubusercontent.com/52311860/103131709-b8d77280-4699-11eb-8d93-f9a278549157.png)

**Comment by the1812** [comment]
竟然要点一下那个`展开`才会出现字幕制作者... 我目前是直接把文字全部展示, 然后隐藏`展开`按钮的

**Comment by MC-dusk** [comment]
如果简介很短，无需展开（没有`展开`按钮），则能显示`字幕制作者`
比如：https://www.bilibili.com/video/BV1kX4y1u7GJ

Stable v1.11.12
内容包: 69696ca
