### ISSUE TITLE
播放器触摸支持代码与B站防剧透进度条代码出现冲突

### ISSUE THREAD

**Issue by cmmdwl** [the1812/Bilibili-Evolved#1371]
**关于哪一项功能**
播放器触摸支持代码

**问题描述**

任何视频页播放页
播放器触摸支持代码与B站防剧透进度条代码出现冲突,表现为无法自动隐藏
**脚本版本**

**浏览器版本**

Microsoft Edge
版本 87.0.664.60 (官方内部版本) (64 位)

**错误信息**

未见代码错误

**附加截图**
https://greasyfork.org/zh-CN/scripts/411092-b%E7%AB%99%E9%98%B2%E5%89%A7%E9%80%8F%E8%BF%9B%E5%BA%A6%E6%9D%A1/discussions/71118#comment-175875

**Comment by the1812** [comment]
好像是让全屏下也能看见进度条来着, 不然全屏检查进度每次都得暂停
当然, 你们要是有鼠标大可不必开这个`触摸播放器`功能

**Comment by cmmdwl** [comment]
surface 不知道应该说一些什么😂

**Comment by the1812** [comment]
那就控制台里跑下这个吧:
```JavaScript
bilibiliEvolved.installStyle({ name:'progressBarCompatibility', displayName: '防剧透进度条兼容', style: `
  .bilibili-player-area:not(.video-control-show) .bilibili-player-video-control-top [class$='scriptControl'] { opacity: 0 }
` })
```
