### ISSUE TITLE
“稍后观看”不能及时更新视频

### ISSUE THREAD

**Issue by BenjaminGao** [the1812/Bilibili-Evolved#1375]
**问题描述**
在首页，动态中或首页其他位置，单击每个视频缩略图的右下角“添加到稍后观看”时，正常来说过2、3秒钟“稍后观看会出现该视频。但是应用脚本后并不能这样。

我将脚本关闭，用原生的网页尝试了几次，没有发现问题，我猜测是脚本的问题。

**脚本版本**
正式版：1.11.5

**浏览器版本**
Chrome 87 正式版(Arm64)

**错误信息**
我看了，Console 里没有错误报告输出。

**附加截图**
我上传两个几秒钟的录屏文件，以便加以说明。

https://user-images.githubusercontent.com/16028320/103150731-a7818980-47b1-11eb-9a3c-af7ba819eabe.mp4

https://user-images.githubusercontent.com/16028320/103150732-acded400-47b1-11eb-9633-ef1a71da75b6.mp4

**Comment by LonelySteve** [comment]
最新预览版已修复（ 38f39be9c5891b395e6372b797d1d906241b0c84 ），根据你的描述和 #1311 应该是一回事

**Comment by BenjaminGao** [comment]
> 最新预览版已修复（ [38f39be](https://github.com/the1812/Bilibili-Evolved/commit/38f39be9c5891b395e6372b797d1d906241b0c84) ），根据你的描述和 #1311 应该是一回事

确实是一回事儿，发之前我还搜索好几遍有没有相应的 issus，就是没搜到...
不好意思，发重复了。
