### ISSUE TITLE
下载字幕后导入无效，检查后发现是字幕里少了个Fontsize

### ISSUE THREAD

**Issue by Mirionr** [the1812/Bilibili-Evolved#1377]
**关于哪一项功能**

**问题描述**

ass字幕
[V4+ Styles]
Format: Name, Fontname, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: BottomCenter,等线,30,&H0FFFFFF,&H0FFFFFF,&H99000000,&000000000,0,0,0,0,100,100,0,0,3,1,0,2,32,32,32,0

添加Fontsize后解决

[V4+ Styles]
Format: Name, Fontname, **Fontsize**, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: BottomCenter,等线,30,&H0FFFFFF,&H0FFFFFF,&H99000000,&000000000,0,0,0,0,100,100,0,0,3,1,0,2,32,32,32,0

**脚本版本**

Preview 1.11.9

**浏览器版本**

87.0.4280.88

**错误信息**

无

**附加截图**
无

**Comment by the1812** [comment]
所有字幕下载ASS都这样是吗

**Comment by Cartagra** [comment]
怪不得下完的字幕手机都不能识别，用Aegisub保存下才能正常用。。

**Comment by the1812** [comment]
弹幕那边有 Fontsize, 我记得当时字幕下载是直接复制那边的, 怎么就离奇消失了...

**Comment by Mirionr** [comment]
> 所有字幕下载ASS都这样是吗

是的
