### ISSUE TITLE
个人信息界面和动态的排版

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#138]
![aaaaaaaaaaa](https://user-images.githubusercontent.com/14146754/58893568-ffb1f000-8722-11e9-9153-17f8c575b451.png)
这种投稿名长到要死的情况显示怪怪的

![bbbbbbbbb](https://user-images.githubusercontent.com/14146754/58893576-02ace080-8723-11e9-887e-32f2c2dd6341.png)
这里没有图标也看起来怪怪的,应该可以把官方的扣下来用吧

**Comment by the1812** [comment]
这里是有图标的, 你那里看来是主题颜色没显示出来
![image](https://user-images.githubusercontent.com/26504152/58925244-6a8e1600-8779-11e9-812c-8dce8c4c104c.png)

控制台里有报错吗?

**Comment by u2shana** [comment]
> 这里是有图标的, 你那里看来是主题颜色没显示出来
> ![image](https://user-images.githubusercontent.com/26504152/58925244-6a8e1600-8779-11e9-812c-8dce8c4c104c.png)
> 
> 控制台里有报错吗?

原来如此,因为我的主题色是白色
