### ISSUE TITLE
下载器下载到一半就没有速度了

### ISSUE THREAD

**Issue by rsj123** [the1812/Bilibili-Evolved#139]
下载器下载到一半就没有速度了
目前测试为下载番剧和电影
例如ep264969
使用导出数据，然后下载，在多个网络环境下都可以复现

**Comment by the1812** [comment]
请换用aria2, 天之杯已测试可以下载. 详细说明见[https://github.com/the1812/Bilibili-Evolved/blob/preview/aria2-notice.md](https://github.com/the1812/Bilibili-Evolved/blob/preview/aria2-notice.md)
