### ISSUE TITLE
个人空间某情景动态相关功能失效

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1391]
**关于哪一项功能**
快速收起动态评论区
动态翻译
禁止跳转动态详情
动态链接复制
动态反折叠
动态图片导出

**问题描述**
原本以为只是 `快速收起动态评论区` 的 bug 就发在 https://github.com/the1812/Bilibili-Evolved/issues/596#issuecomment-695217892 下了，今天发现还有很多功能有相同状况，就另开个 issue 了。

个人空间中，`快速收起动态评论区`、`动态翻译`、`禁止跳转动态详情`、`动态链接复制`、`动态反折叠`、`动态图片导出` 功能会在第二次及之后切换至动态 tab 时（不刷新页面）失效。相关功能没阵亡的好像就只有 `展开动态内容`、`评论链接复制` 和 `评论翻译`。

**脚本版本**
正式版 v1.11.5
预览离线版 v892.96

**浏览器版本**
百分浏览器 4.3.9.241（正式版本） （64 位） (Chromium 86.0.4240.198)
Chrome 87.0.4280.88（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by the1812** [comment]
这个我是不是修掉了?

**Comment by Geeyun-JY3** [comment]
> 这个我是不是修掉了? (发更新的时候可能忘 close 了?

确实
