### ISSUE TITLE
弹窗“错误 unexpected token: identifier”

### ISSUE THREAD

**Issue by DUYUSHANMAXC** [the1812/Bilibili-Evolved#1394]
除了一直弹窗以外，好像也没什么使用上的影响，但是每个页面都弹，着实非常令人烦躁，而且必须手动关闭才行
![图片](https://user-images.githubusercontent.com/75711120/103396811-39054880-4b70-11eb-82eb-8a920b6cb156.png)

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/1227#issuecomment-731558372
请按照 issue 模板正常填写反馈信息

发之前能不能先搜索一下

**Comment by Geeyun-JY3** [comment]
#1227
#1233，#1234，#1326，#1393
