### ISSUE TITLE
关于导出Aria2下载列表的使用方式

### ISSUE THREAD

**Issue by gx0803** [the1812/Bilibili-Evolved#1395]
你好，问一个和下载有关的疑问。我选择批量下载，然后导出方式选择aria2，导出为txt，内容如下：
# Generated by Bilibili Evolved Video Export
# https://github.com/the1812/Bilibili-Evolved/
https://upos-sz-mirrorhw.bilivideo.com/upgcxcode/08/08/204220808/204220808-1-32.flv?e=ig8euxZM2rNcNbTg7WdVtWTg7WdVNEVEuCIv29hEn0lqXg8Y2ENvNCImNEVEUJ1miI7MT96fqj3E9r1qNCNEtodEuxTEtodE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&uipk=5&nbs=1&deadline=1609406551&gen=playurl&os=hwbv&oi=1954607454&trid=f00512423d8243919874871fec80b00eu&platform=pc&upsig=1ad5f319e485479f29cfeb8dc3c32a9d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=7808085&orderid=0,3&agrr=1&logo=80000000
  referer=https://www.bilibili.com/video/BV1Bg4y1q7q2
  user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
  out=03 - 02-Spring简介-Spring发展历程.flv
  split=12
https://upos-sz-mirrorhw.bilivideo.com/upgcxcode/32/08/204220832/204220832-1-32.flv?e=ig8euxZM2rNcNbUa7WdVtWUa7WdVNEVEuCIv29hEn0lqXg8Y2ENvNCImNEVEUJ1miI7MT96fqj3E9r1qNCNEtodEuxTEtodE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&uipk=5&nbs=1&deadline=1609406551&gen=playurl&os=hwbv&oi=1954607454&trid=0bae291432424f58a82846579632fd9au&platform=pc&upsig=a19af614a9fcf154fc2810b1aeac89c8&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=7808085&orderid=0,3&agrr=1&logo=80000000
  referer=https://www.bilibili.com/video/BV1Bg4y1q7q2
  user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
  out=04 - 03-Spring简介-Spring的优势.flv
  split=12

我想请问的是这个txt里的文件，要用什么下载器打开，下载时才会自动获取out=xxxx.flv的文件名呢？
试了好几个下载器，复制链接以后，得到的文件名都不是中文名，而是服务器上的原文件名
![image](https://user-images.githubusercontent.com/8998033/103401757-32cd9700-4b85-11eb-8122-1eca574af72d.png)
有没有办法导入以后直接保存为视频列表里的中文文件名呢？
还是说和IDM下载一样，不支持获取文件名呢？

**Comment by the1812** [comment]
aria2 就是一个下载器 它能够读取脚本提供给它的正确文件名
