### ISSUE TITLE
Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by oOTnTOo** [the1812/Bilibili-Evolved#1396]
**关于哪一项功能**
下载ASS弹幕

**问题描述**

BV1vy4y1i7bS，下载该视频的ASS弹幕时报一下错误
Cannot read property 'content' of undefined

但JSON弹幕可以正常下载

**脚本版本**

v1.11.5

**浏览器版本**

Chrome 87.0.4280.88（正式版本） （64 位）

**错误信息**

Cannot read property 'content' of undefined

**附加截图**
![image](https://user-images.githubusercontent.com/31060590/103408815-1f2f2a00-4b9f-11eb-9a2a-26720eaa71d4.png)

JSON却可以正常下载
![image](https://user-images.githubusercontent.com/31060590/103408839-3241fa00-4b9f-11eb-8e20-58325a19887b.png)

**Comment by Lijingze2019** [comment]
此问题+1，版本 1.11.12/14，浏览器 Microsoft Edge | 87.0.664.75
