### ISSUE TITLE
直播间聊天栏区域夜间模式未覆盖

### ISSUE THREAD

**Issue by WindSKE** [the1812/Bilibili-Evolved#1397]
关于哪一项功能
界面显示问题。

问题描述
在夜间模式下观看直播，聊天框区域依然是白色。

脚本版本
Stable v1.11.5

浏览器版本
Google Chrome 已是最新版本
版本 87.0.4280.88（正式版本） （64 位）

错误信息
无

附加截图
![QQ截图20210101141334](https://user-images.githubusercontent.com/28365038/103434411-d9746f00-4c3b-11eb-8e6b-ec268a9f2055.png)

**Comment by Geeyun-JY3** [comment]
最新预览版已修，而且在 #1289 有反馈了：https://github.com/the1812/Bilibili-Evolved/issues/1289#issuecomment-746055210 https://github.com/the1812/Bilibili-Evolved/issues/1289#issuecomment-747368872

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved/blob/preview/issue-rules.md
> 提示: 最好先在预览离线版(Preview Offline)中测试一下, 有些问题可能已经修复了但还未正式发布.
