### ISSUE TITLE
功能上的一点小建议

### ISSUE THREAD

**Issue by juking** [the1812/Bilibili-Evolved#14]
1. 查看封面 和 下载视频 功能藏在设置里面很不方便，完全可以直接嵌入网页中，比如放在标题的后面就蛮好。
2. 更改默认的播放模式（宽屏模式，全屏模式，网页全屏模式）(B站没有像ytb一样记录视频样式就很烦)。
3. 关灯模式了解一下？

**Comment by juking** [comment]
忘了ps
PS: 脚本很好用！ 改过的版面比原来的好看多了，多谢！

**Comment by the1812** [comment]
1. 其实我一开始就是嵌在网页里的, 但是视频页面有个奇怪的自我保护机制, 一旦页面被改动就删除视频和弹幕, 只剩个评论区, 所以我最后只好加在设置里了.
2. 很好的建议, 我会尽快加上的.
3. 这条不太理解, 如果是指关灯模式能替代夜间模式的话, 我认为他们的作用不完全一样. 关灯是播放器的功能, 能够遮住其他内容专注于视频; 夜间模式在非视频页面中依然有效, 能够调整颜色而不遮挡内容.

**Comment by juking** [comment]
![image](https://user-images.githubusercontent.com/4278193/48398993-58a54100-e75d-11e8-892a-a971b098100b.png)
我尝试了一下，貌似还行，实现方式略dirty

`
$(function () {
    var addbutton = function () {
        if ($("#gui-settings-downloadb").length != 0) return;
        $("#viewbox_report > h1").append($('<div id="gui-settings-downloadb" style="display: inline-block;">' +
            '<button class="gui-settings-button">查看封面</button>' +
            '<button class="gui-settings-button">下载视频</button></div>'));
    };
    $("video").on("playing", addbutton);
    setTimeout(addbutton, 2000);
});
`

**Comment by juking** [comment]
这个插入代码很不好用
![image](https://user-images.githubusercontent.com/4278193/48402832-8ee7be00-e767-11e8-8f87-4c8cf6db6824.png)

**Comment by juking** [comment]
关灯模式不是替代夜间模式，就是多一个模式，我自己感觉好用，如果有兴趣的话你可以加上

**Comment by the1812** [comment]
关灯模式不是本来就有的功能吗?
![image](https://user-images.githubusercontent.com/26504152/48403137-35cc5a00-e768-11e8-8783-d93455601492.png)

**Comment by juking** [comment]
嗯嗯，关灯模式本来就有，但很坑的就是像宽屏模式一样也不记录状态，刷新一下就没了

**Comment by the1812** [comment]
按你的思路试了一下, `setTimeout`延迟2秒依然会被删视频, video播放事件里加如果是一进去马上点播放也是会被删.

以下是测试用的脚本
```JavaScript
// ==UserScript==
// @name          Video button test
// @description   test
// @version       0.1
// @author        xxx
// @match         https://www.bilibili.com/*
// @require       https://code.jquery.com/jquery-3.2.1.min.js
// @grant         none
// ==/UserScript==

($ =>
{
   $(function () {
       var addbutton = function () {
           if ($("#gui-settings-downloadb").length != 0) return;
           $("#viewbox_report > h1").append(
               $('<div id="gui-settings-downloadb" style="display: inline-block;">'+
                 '<button class="gui-settings-button">查看封面</button>'+
                 '<button class="gui-settings-button">下载视频</button></div>'));
       };
       $("video").on("playing", addbutton);
       setTimeout(addbutton, 2000);
   });
})(window.jQuery.noConflict(true));
```

**Comment by the1812** [comment]
播放时全屏这个鸽了快一个月了... 我还是做不出来

全屏请求限制必须在click事件中发起, 如果直接调用全屏按钮的click处理函数, 附在播放按钮上有效, 但附在视频区域无效.
打了断点后播放按钮和视频区域点击都能命中, 视频区域那个执行下去却偏偏不触发全屏, 想不明白怎么回事_(:3」∠)_

**Comment by the1812** [comment]
全屏开放了一段时间了, 没啥问题我就当搞定了
