### ISSUE TITLE
希望增加敏感词检测功能

### ISSUE THREAD

**Issue by silascript** [the1812/Bilibili-Evolved#140]
**关于哪一项功能**

希望增加敏感词检测功能
天朝言论自由受限，发个评论各种敏感词不能发，快增加敏感词检测功能
**期望的效果**
希望增加敏感词检测功能

**脚本版本**

**Comment by the1812** [comment]
emmmmm 我也不知道哪些是敏感词啊
而且这种功能等于把敏感词公开了, 不太好吧

**Comment by bf1942** [comment]
天朝似乎并没有公开的敏感词词库
