### ISSUE TITLE
夜间模式追番按钮样式不明显

### ISSUE THREAD

**Issue by xzk-kokodayo** [the1812/Bilibili-Evolved#1400]
**关于哪一项功能**
夜间模式

**问题描述**
追番按钮样式不正常，不能凸显

**脚本版本**
预览版1.11.9

**浏览器版本**
Microsoft Edge 87.0.664.66

**附加截图**
![屏幕截图 2021-01-01 214802](https://user-images.githubusercontent.com/69005158/103439797-0e53e680-4c7b-11eb-90ec-445d40c01817.png)

**Comment by Geeyun-JY3** [comment]
个人空间的 `订阅` tab 也有一样的情况

**Comment by the1812** [comment]
已追剧的话这个样式应该是正确的吧
未追剧时确实应该用主题色

**Comment by Geeyun-JY3** [comment]
主题色的问题倒是其次，主要是追剧后下面的三个 `标记为` 总有一个会灰掉（表示先前选中的状态）

**Comment by the1812** [comment]
哦哦 懂了
