### ISSUE TITLE
关于页面布局、直播和动态页的功能建议

### ISSUE THREAD

**Issue by XZL16** [the1812/Bilibili-Evolved#141]
### 功能建议

**页面布局**

1. 顶栏布局中增加“追番”入口，这是油猴上脚本的一个功能，不过会被evolve覆盖XD，所以希望能移植

> https://greasyfork.org/zh-CN/scripts/370127-b站首页增加已追番入口/code

2. 提供首页顶栏下方中的“首页、动画、番剧.....”一排分区栏的显示开关，（几乎没从这里进入到各个分区过┓( ´∀` )┏

**直播**

1. 屏蔽直播主页自动播放视频的区域

> https://live.bilibili.com

2. 直播间添加自动网页全屏的功能，如果可能的话更希望能做成一般视频的宽屏播放样式，即播放框居中，隐藏右侧直播弹幕列表，附带直播框定位功能和直播框快捷输入弹幕功能

3. 将直播间界面的顶栏样式统一为首页的样式

**动态**

1. 屏蔽各种次要的小卡片，只留下左侧的个人信息栏和右侧的“目前正在直播的直播间”（虽然用ABP的拦截元素也可以做到，不过会使两侧小卡片的绝对高度位置不同，即不在同一条水平线上有点难受......或许可以参考以下CSS代码

> /* 屏蔽名为xxx的元素 */
> .xxx{
>    display:none !important;
> }`

2. 对于某动态，点击评论区下滑查看评论时，若加载出过多条数的评论，希望能自动浮现“收起”按钮

3. 动态屏蔽功能，不是希望能做成像“Yet Another Weibo Filter”那样复杂，如果可以的话看能否根据动态的发布类型来屏蔽，比如屏蔽纯转发动态（即只有“转发动态”四个字的动态；或可以设置成对于某up主，只显示其发布视频或小视频的动态消息。

4. 动态页左侧个人信息的卡片下方，增加一个链接到up主空间主页的卡片，样式类似右侧“正在直播”的小卡片，可令使用者自主输入域名自定义卡片上面显示的up主

**脚本版本：正式版**

**Comment by the1812** [comment]
感谢建议. 不过这么多东西要弄完需要很长很长的时间, 近期要期末考也不会有太大动静.
但可能不是所有的都会做:
- 直播1: 见 #135, 预览版已经有了
- 直播2: 弹幕列表不是本来就可以隐藏的吗?
- 直播3: 不太明白什么意思, 样式上挺统一的了, 是要内容也换成首页的?
- 动态1: 推荐Stylus插件
- 动态4: 这个可能会做得比较慢

**Comment by XZL16** [comment]
啊感谢你的留言，有点担心提建议的语气是不是太甲方或书面了一点，怕引起误会......
有机会的话我也想研究github或stylus来进行样式美化，所以也算个备忘录吧，要是觉得其中有可取之处的话就更好了XD
最后感谢作者对这个脚本的制作与维护，祝期末考顺利~

**Comment by shugen002** [comment]
直播首页正在灰度一个新版本，请留意相关代码变化。。。

**Comment by the1812** [comment]
居然更新了.. 好多功能在那都失效了

**Comment by the1812** [comment]
(总算把我想做的做完了)
