### ISSUE TITLE
清爽首页热门不见了

### ISSUE THREAD

**Issue by rabbit2099** [the1812/Bilibili-Evolved#1415]
**简化首页**

**简化首页清爽风格中，热门不见了**

**Preview v1.11.10**

**Chrome 86**

**错误信息**

**
![image](https://user-images.githubusercontent.com/75069083/103729411-59734e00-501b-11eb-8439-e441fab92216.png)
**

**Comment by RIKR6735** [comment]
更新了脚本就有这问题了

**Comment by the1812** [comment]
跟更新没关系, 只是b站热门视频数据名字改了, 正式版一样加载不了

**Comment by ElluIFX** [comment]
帮补充一下错误信息，在极简风格下切换热门tab报错 " Cannot read property 'map' of undefined "

**Comment by the1812** [comment]
b 站还把播放量以外的ton统计数据全砍了
修复后下面会变成这样
![image](https://user-images.githubusercontent.com/26504152/103730970-013e4b00-501f-11eb-97f6-657fa8112f7c.png)

**Comment by Charlie-Mars** [comment]
等修复吧

**Comment by PSGAGA** [comment]
等大佬修复~

**Comment by Joycesteven** [comment]
坐等大佬修复🤗
