### ISSUE TITLE
Firefox Out of memory. Can't make Blob

### ISSUE THREAD

**Issue by partment** [the1812/Bilibili-Evolved#142]
似乎下載過大的影片時就會Catch到這個例外錯誤，試問有無辦法通過調整about:config中的參數解決?
[Exception... "Out of Memory"  nsresult: "0x8007000e (NS_ERROR_OUT_OF_MEMORY)"  location: "JS frame :: moz-extension://bd073d67-6476-41c8-8811-7948adcd7da8/userscript.html?id=20b03014-fbfb-4644-8cf5-223b78bae016 :: makeBlob :: line 13014"  data: no]

**Comment by the1812** [comment]
about:config里没有相关的参数, 大影片目前只能通过[特殊工具](https://www.npmjs.com/package/bilibili-evolved-video-link-downloader)下载.

关于Firefox对此的限制, 我能查到的只有[说无限制的](https://stackoverflow.com/questions/28307789/is-there-any-limitation-on-javascript-max-blob-size), 但是这种说法并没有确切的出处. 从你的情况看这个限制应该是存在的.

**Comment by partment** [comment]
感謝回覆，使用特殊工具後成功
