### ISSUE TITLE
同时打开【外置稍后再看】和【启用快速收藏】后，出现排版错误

### ISSUE THREAD

**Issue by jiang9527** [the1812/Bilibili-Evolved#1421]
**关于哪一项功能**

页面布局

**问题描述**

【同时】打开【外置稍后再看】和【启用快速收藏】后，【div id=arc_toolbar_report】的【稿件投诉】和【记笔记会被挤到下一行】，进行页面【缩小为80%】可以暂时缓解，同理，只打开上述一项，页面放大到110%也可以复现。

**脚本版本**

Preview v1.11.10

**浏览器版本**

Google Chrome  版本 87.0.4280.88（正式版本） （64 位）

**错误信息**

【同时】打开【外置稍后再看】和【启用快速收藏】后，【div id=arc_toolbar_report】的【稿件投诉】和【记笔记会被挤到下一行】，进行页面【缩小为80%】可以暂时缓解，同理，只打开上述一项，页面放大到110%也可以复现。

**附加截图**
![屏幕截图(1)_LI](https://user-images.githubusercontent.com/23352053/103756295-21373400-504a-11eb-87d2-d46bcd413ffe.jpg)

**Comment by Geeyun-JY3** [comment]
因为你的屏幕宽度太小了：https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-738868570
和我一样：https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-738838576

应该可以响应式布局：https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-740458872
