### ISSUE TITLE
chrome浏览器报错

### ISSUE THREAD

**Issue by MicMAO** [the1812/Bilibili-Evolved#1423]
**关于哪一项功能**

**问题描述**
报错误 提示是：Unexpected identifier

**脚本版本**
正式版1.11.5

**浏览器版本**
版本 87.0.4280.88（正式版本） （64 位）

**错误信息**
左下角弹窗显示错误提示内容为：Unexpected identifier

**附加截图**

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/1227#issuecomment-731558372
#1233，#1234，#1326，#1393
