### ISSUE TITLE
下載器「片段下载失败」

### ISSUE THREAD

**Issue by partment** [the1812/Bilibili-Evolved#143]
Reproduce : https://www.bilibili.com/bangumi/play/ep259676

Error Code :

正在下载: 盾之勇者成名录：第3话
0% [                    ]internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

[Error: EPERM: operation not permitted, open 'C:\盾之勇者成名录：第3话.part0'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\盾之勇者成名录：第3话.part0'
}

acgvideo.com和akamaized.net這兩種國內國外CDN都試過了
也試著在別的機器或Linux跑過，都是一樣的結果

**Comment by the1812** [comment]
这个问题好像有点严重, 所有的视频都因为这个错误无法下载了.

调试了一下发现 Node.js 对下载链接无法处理(视为无效了)
```JavaScript
const request = require('request')
const fs = require('fs')

request.get('https://upos-hz-mirrorks3u.acgvideo.com/upgcxcode/25/49/99934925/99934925-1-112.flv?e=ig8euxZM2rNcNbhVhb4BhwdlhzdgnwUVhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEVEuxTEto8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&deadline=1561877792&gen=playurl&nbs=1&oi=0&os=ks3u&platform=pc&trid=24fb38a04143467dbaff4f7fe80eae27&uipk=5&upsig=47452310f6bb5da65df07f470123763a&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&mid=39717974', {
  headers: {
    Origin: "https://www.bilibili.com",
    Referer: "https://www.bilibili.com",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36",
  }
}).pipe(fs.createWriteStream('test.flv'))
```
这会产生以下错误 (在下载器中向上传递表现为Error: EPERM: operation not permitted)
```
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: Parse Error
    at TLSSocket.socketOnData (_http_client.js:447:20)
    at TLSSocket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:145:17)
```
如果换成一些普通的网站却可以, 比如`https://www.bing.com`.
网上查到的资料表明这有两种情况:
1. 链接里有空格
2. 服务器返回的数据长度不匹配请求头的`Content-Length`

下载链接里没有任何空格, 服务器也不是我能控制的, 所以我目前没有什么解决办法, 长期得不到解决的话我可能会考虑把下载器迁移到.NET Core上.

**Comment by partment** [comment]
試著修改下請求頭，對應解析出連結使用的瀏覽器之User-Agent並修改Referer至此番劇連結
const request = require('request')
const fs = require('fs')

request.get('https://upos-hz-mirrorks3u.acgvideo.com/upgcxcode/52/88/72848852/72848852-1-112.flv?e=ig8euxZM2rNcNbNMnw4BhwdlhbK3nwUVhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&deadline=1561886571&gen=playurl&nbs=1&oi=1696929724&os=ks3u&platform=pc&trid=63b431cb93e846dda1da6bd686c4f4a9p&uipk=5&upsig=1489353a98a40b446bfe65e04e9e1c30&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk', {
  headers: {
    Origin: "https://www.bilibili.com",
    Referer: "https://www.bilibili.com/bangumi/play/ep259676",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:67.0) Gecko/20100101 Firefox/67.0",
  }
}).pipe(fs.createWriteStream('test.flv'))
成功下載

**Comment by partment** [comment]
使用[這個頁面](https://github.com/the1812/Bilibili-Evolved/wiki/%E4%BD%BF%E7%94%A8%E4%B8%8B%E8%BD%BD%E8%A7%86%E9%A2%91%E7%9A%84%E5%A4%8D%E5%88%B6%E9%93%BE%E6%8E%A5)提供的curl命令列測試，發現一樣返回403。就懷疑是不是請求頭被伺服器返回Close了，就改了下請求頭發現可以成功下載

**Comment by partment** [comment]
只修改User-Agent一樣成功
<img width="783" alt="sublime_text_20190630_155700" src="https://user-images.githubusercontent.com/5278061/60393981-c9179b80-9b4f-11e9-88a3-1799b17e964b.png">
<img width="207" alt="powershell_20190630_160045" src="https://user-images.githubusercontent.com/5278061/60394020-3c211200-9b50-11e9-828f-d99025f1c4fa.png">

**Comment by the1812** [comment]
非常感谢! 我已在下载器的新版本和文档中更换了User-Agent.

但是关于User-Agent的测试结果, 还是有些奇怪:
原本使用的User-Agent取自Chrome 73, 它在下载器和curl中无法使用, 但是在Invoke-WebRequest命令中却能顺利下载
![image](https://user-images.githubusercontent.com/26504152/60394266-3b8a7a80-9b54-11e9-9785-6140bf19d91e.png)

**Comment by partment** [comment]
根據Powershell的[文檔](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-6)，要指定User-Agent要使用-UserAgent參數，不能使用-Header
如果使用-Header修改User-Agent的話，會送出預設的User-Agent
`Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.15063; en-US) PowerShell/6.0.0`

**Comment by partment** [comment]
所以可以說是B站的伺服器拒絕了Chrome 73的UA

**Comment by the1812** [comment]
原来如此. 还是得好好根据文档来写, 那个Invoke-WebRequest也是当时由Chrome开发者工具生成的.

**Comment by partment** [comment]
解決問題，皆大歡喜
