### ISSUE TITLE
课程播放页快捷键扩展和双击全屏无效

### ISSUE THREAD

**Issue by yjh126yjh** [the1812/Bilibili-Evolved#1434]
**关于哪一项功能**
快捷键扩展、双击全屏

**问题描述**

https://www.bilibili.com/cheese/play/ 开头的课程播放页中，快捷键扩展和双击全屏都用不了。
看了一下这里支持的url列表里确实没有课程播放页
https://github.com/the1812/Bilibili-Evolved/blob/28340d20a209ad437e5286736162a916294664bd/src/video/keymap.ts#L1-L6

但是我用离线版v857.15试了一下，把”https://www.bilibili.com/cheese/play/“ 加进去之后快捷键就能用了。
不知道这里一开始是出于什么原因没有加上呢？

至于双击全屏，我试了一下确实加上去也不支持。
https://github.com/the1812/Bilibili-Evolved/blob/28340d20a209ad437e5286736162a916294664bd/src/video/double-click-fullscreen.ts#L2-L5
另外，https://www.bilibili.com/medialist/play/watchlater/ 开头的稍后再看列表也没法支持双击全屏。

双击全屏的问题如果暂时无法解决的话，希望可以在”已知问题“或者别的什么地方说明一下。

**脚本版本**

测试了正式版1.11.5和预览版1.11.10，都有这个问题

> 

**浏览器版本**

Chromium 86

**错误信息**

**附加截图**

**Comment by the1812** [comment]
快捷键扩展写的时候并不知道有课程这类视频...我之后会补上
双击全屏因为是老功能了, 实现方式比较怪异, 目前兼容不了课程和稍后再看
