### ISSUE TITLE
附加功能里的“查看封面”功能不见了？

### ISSUE THREAD

**Issue by doio** [the1812/Bilibili-Evolved#144]
**关于哪一项功能**
附加功能里面的“查看封面”

**问题描述**
用 Bilibili Evolved (Offline)  321.26 下载封面就不见了，刚才试了试 Preview Offline 347.12 版本，原本是下载封面的按钮面成了“顶栏布局”，不知道是因为什么原因这样呢...
刚才试了试把 Tampermonkey 里面的 Storage 的那些设置都清空，可还是没出现“下载封面”的选项... 

清空以后没了，然后加载回备份的设置又出现了，然后刷新一下页面又不见了，
后来再也不出现了。。

**脚本版本**
Bilibili Evolved (Offline)  321.26
Bilibili Evolved Preview (Offline) 347.12

**浏览器版本**
Firefox 67.0.4

**错误信息**

**附加截图**

![2019-06-30_10-50-35](https://user-images.githubusercontent.com/4461202/60391653-0830f700-9b26-11e9-8ddf-0517226c49db.png)

![2019-06-30_10-56-43](https://user-images.githubusercontent.com/4461202/60391671-5f36cc00-9b26-11e9-9a1e-279a281c9ee0.png)

**Comment by the1812** [comment]
应该只有旧版炸了, Preview Offline已修复

**Comment by doio** [comment]
嗯刷新了 10 来次以后再也没有消失了，原来是用旧版播放器会出现的问题啊
暂时确认问题已经解决了！！
