### ISSUE TITLE
某些视频用DASH格式下载会出现错误

### ISSUE THREAD

**Issue by DEabcdp** [the1812/Bilibili-Evolved#1449]
**问题描述**

b站许多视频，用dash格式下载就会在下载过程左下角出现“视频片段××请求失败, response = 416”，但是用flv格式下载就没问题。并不是所有视频用dash格式都会出现这样的问题，有些是没问题的。
举两个有问题的例子https://www.bilibili.com/video/BV1gQ4y1N7iu   https://www.bilibili.com/video/BV1Si4y1w7GX

**脚本版本**

预览版1.11.11

**浏览器版本**

Microsoft Edge chromium 88.0.705.29

**错误信息**

Failed to load resource: the server responded with a status of 416 ()
视频片段19请求失败, response = 416
logError @ userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=2a449805-b30b-4ab9-9ed9-c0fb230c6590:13210
![错误信息（](https://user-images.githubusercontent.com/62452364/104096282-8bfc9f80-52d6-11eb-80cb-3c044a40742c.png)

**附
![Snipaste_2021-01-09_23-46-09（](https://user-images.githubusercontent.com/62452364/104096136-a4b88580-52d5-11eb-99a7-88b61704d709.png)
加截图**

**Comment by the1812** [comment]
老 bug 了, DASH 尽量都用导出吧

**Comment by DEabcdp** [comment]
秒回，棒！(๑•̀ㅂ•́)و✧

**Comment by wuhaocheng29** [comment]
采用导出的话有的高码率视频音画是分开下载的，有没有加入ffmpeg整合的打算

**Comment by the1812** [comment]
ffmpeg 请自行在本地操作
