### ISSUE TITLE
显卡占用过高

### ISSUE THREAD

**Issue by Izumiko** [the1812/Bilibili-Evolved#145]
**问题描述**
Chrome 75 中，安装脚本后打开B站，GPU利用率直接到将近50%，之后禁用脚本刷新，占用率恢复到之前的5%以下。   
显卡：AMD RX550

**脚本版本**
1.8.5

**浏览器版本**
Chrome 75

**错误信息**
无

**附加截图**

**Comment by the1812** [comment]
删掉了一个很吃显卡的动画, 现在好些了吗? 我这边利用率测试从40%降到3%了.

**Comment by Izumiko** [comment]
没问题了，我这边也是在5%以下
