### ISSUE TITLE
清爽首页对于Chrome 插件“哔哩哔哩·猜你喜欢”的支持问题

### ISSUE THREAD

**Issue by AQ-Official** [the1812/Bilibili-Evolved#1451]
**关于哪一项功能**
清爽首页对于Chrome 插件“哔哩哔哩·猜你喜欢”的支持问题

**问题描述**
主页
Chrome插件“哔哩哔哩·猜你喜欢”是一款好用的插件，解决了b站在web端上无法接收到个性化推荐的问题。
插件id：ngjddnobeppdekpmimhiamkoonoaccdf

其实现原理应该是在观看视频是拉取对应标题和标签，进行推荐，并展示在主页上

开启bilibili evolved的清爽主页后，会覆盖掉“哔哩哔哩·猜你喜欢”的推荐内容

应该是有办法解决的，因为evolved的首页简化过程是在页面加载完毕后执行的，此时“哔哩哔哩·猜你喜欢”已经执行完成

**脚本版本**
Stable v1.11.12
内容包: 0d91cde

**浏览器版本**
版本 87.0.4280.141（正式版本） （64 位）

**Comment by Geeyun-JY3** [comment]
简化首页应该不会考虑对这些插件的兼容，至少一个同类脚本是这样：https://github.com/the1812/Bilibili-Evolved#bilibili网页端添加app首页推荐

**Comment by the1812** [comment]
猜你喜欢是添加在原版首页的, 开启简化首页是覆盖整个原版首页, 相当于你选择完全放弃原版首页
