### ISSUE TITLE
LPL赛事页面,直播全屏弹幕框出现问题

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#1454]
![QQ截图20210110201829](https://user-images.githubusercontent.com/14146754/104122662-3fba6980-5381-11eb-840d-44c56a397905.png)

**Comment by the1812** [comment]
给个直播间链接?

**Comment by u2shana** [comment]
> 给个直播间链接?

https://live.bilibili.com/6

**Comment by the1812** [comment]
已修复, jsDelivr 那边可能还得等一天才更新

**Comment by u2shana** [comment]
今天这个bug又死灰复燃了

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/110782448-1abf7580-82a2-11eb-812a-d12bd7b9c6b2.png)
