### ISSUE TITLE
首页可以增加猜你喜欢的功能吗？

### ISSUE THREAD

**Issue by MyFaith** [the1812/Bilibili-Evolved#146]
**关于哪一项功能**

类似手机APP上的猜你喜欢功能

**期望的效果**

**脚本版本**

**Comment by the1812** [comment]
目前没找到合适的API, 暂时做不了

**Comment by MyFaith** [comment]
https://app.bilibili.com/x/feed/index?appkey=1d8b6e7d45233436&build=508000&idx=0&login_event=1&mobi_app=android&network=wifi&open_event=cold&platform=android&pull=true&style=2&ts=1499589051&sign=394a36c0a4fcd89c858e3e77a304aa43
你可以研究一下，之前抓的包

**Comment by the1812** [comment]
这个返回的内容貌似只是一些热门视频? 跟我实际在手机上看到的完全不是一个画风

**Comment by MyFaith** [comment]
这个会根据看过的视频推荐，但是我不清楚是不是根据sign来决定账号的

**Comment by the1812** [comment]
感觉这个API根本不管有没有账号, 删掉sign和appkey返回的东西并没有明显变化. (最短能只剩一个参数[https://app.bilibili.com/x/feed/index?build=508000](https://app.bilibili.com/x/feed/index?build=508000))

**Comment by MyFaith** [comment]
有可能是Cookie，我现在用的一个脚本就是请求的这个API，但是推荐的内容和我观看的内容比较吻合

**Comment by ZCXLLOD** [comment]
@the1812 
楼主说的那个脚本可能是这个：https://greasyfork.org/zh-CN/scripts/368446，可以参考一下，其中API的授权是从B站用户反馈论坛（link.acg.tv）那里获取的，也用到了cookie，我看了一下，发现没有获取授权时推荐的内容是不定的，获取授权后大部分内容就变成我经常看的类型了。

**Comment by ZCXLLOD** [comment]
。。。为啥链接后面的文字会被识别成链接的一部分？

**Comment by the1812** [comment]
这个做得挺好的了, 要不我就做一下适配? (其实也就只有夜间模式需要适配)

**Comment by ZCXLLOD** [comment]
@the1812 
我认为如果没什么难度的话可以添加进去，从B站用户反馈论坛中有关的帖子来看，感觉这个首页推荐功能的需求也很多，B站官方回应说以后会添加，但过了很久都没有什么进展。

**Comment by the1812** [comment]
已完成适配, 只要装一下楼上的脚本就有首页推荐的功能了.
[https://greasyfork.org/zh-CN/scripts/368446](https://greasyfork.org/zh-CN/scripts/368446)
