### ISSUE TITLE
直播回放有个半透明黑条

### ISSUE THREAD

**Issue by KnightEmperor** [the1812/Bilibili-Evolved#1469]
**问题描述**
在B站直播的直播回放里，无论任何一个回放，只要鼠标不小心划到左侧的悬浮设置图标，就会有一个半透明黑色悬浮条且不能消除，我尝试使用广告屏蔽元素去选择也无法选择上。这bug应该有一长段时间了。

随便扔个直播回放连接：https://live.bilibili.com/record/R19x411c7Rj

**脚本版本**
v1.11.12

**浏览器版本**
Edge 87.0.664.75

**附加截图**
![Snipaste_2021-01-14_23-53-58](https://user-images.githubusercontent.com/69032631/104615773-7645fc00-5681-11eb-9b6e-54ec54aaeb50.png)
![Snipaste_2021-01-14_23-54-10](https://user-images.githubusercontent.com/69032631/104615792-79d98300-5681-11eb-890e-c9d6a0d0e433.png)

**Comment by the1812** [comment]
和那个页面 b 站的 css 有点冲突, 因为带了个 `show` 被强制一直显示了
![image](https://user-images.githubusercontent.com/26504152/105620830-ebf95700-5e3b-11eb-9505-bb838b7c0500.png)

**Comment by Geeyun-JY3** [comment]
说起来，直播回放也有不少要适配夜间模式的地方
