### ISSUE TITLE
逐帧调整快捷键失效

### ISSUE THREAD

**Issue by DepressionL** [the1812/Bilibili-Evolved#1470]
**关于哪一项功能**
逐帧调整

**问题描述**

逐帧调整快捷键无效，shift + ←/→ 是正常快进 

**脚本版本**

Preview Offline v909.25

**浏览器版本**

Chrome 87.0.4280.88

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
这边测试没问题啊……确定按的是 <kbd>Shift</kbd>+<kbd>←</kbd>/<kbd>→</kbd> 而不是 <kbd>Shift</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd>？还是有别的插件或脚本？

**Comment by the1812** [comment]
要开快捷键扩展

**Comment by Geeyun-JY3** [comment]
@the1812 要不写进 `逐帧调整` 的功能提示（`视频截图` 也是）？

**Comment by the1812** [comment]
是的 我才发现我忘改这里了

**Comment by DepressionL** [comment]
@the1812 可以像原来那样把这个快捷键单独拿出来吗？快捷键扩展里的快捷键太多，好多都和我现有冲突o(╥﹏╥)o 或者将来可以用户自己选择禁用某些快捷键？

**Comment by the1812** [comment]
现在就可以禁用不想要的快捷键
https://github.com/the1812/Bilibili-Evolved/blob/preview/src/video/keymap/key-bindings.md

**Comment by DepressionL** [comment]
@the1812 好的，谢谢
