### ISSUE TITLE
使用插件后播放卡死较严重

### ISSUE THREAD

**Issue by Asiimoviet** [the1812/Bilibili-Evolved#1487]
**关于哪一项功能**
只要是开启了使用脚本都会出发

**问题描述**

播放视频的时候经常进度条卡在一个位置不会继续buffer，然后视频画面卡住但是音频还在继续，过了一会儿才音频停止提示正在缓存

**脚本版本**

909.25

**浏览器版本**

 87.0.4280.141 (Official Build) (x86_64)
系统macOS Big Sur 11.1

**错误信息**

console未发现错误信息

**附加截图**

**Comment by Asiimoviet** [comment]
同一个网络环境 其他变量不变 关掉脚本 进度条缓存会多出很多

**Comment by the1812** [comment]
我也遇到过, 网络比较卡的话就会这样, 只能换网络解决

**Comment by Asiimoviet** [comment]
嗯的确，感觉是b站的问题。我同一个网络用YouTube就不卡
应该是h264和h265的问题吧

**Comment by the1812** [comment]
我当时换个手机 4G 热点就解决了
