### ISSUE TITLE
新功能建议 - IDM下载支持

### ISSUE THREAD

**Issue by Philogag** [the1812/Bilibili-Evolved#149]
**提出**
IDM下载支持

**期望的效果**
提供IDM中可用的下载链接到剪切板或者直接调用IDM插件

**脚本版本**

**Comment by the1812** [comment]
不是很了解IDM, 请问哪里可以查到相关资料? 我在它官网上没找着链接格式和调用它的方式

**Comment by Philogag** [comment]
其实主要就是要能够用浏览器直接下载的链接
浏览器能下IDM就能下

现在生成的链接复制进去403

**Comment by Philogag** [comment]
IDM的下载原理就是普通文件分块然后多线程
所以应该要的是直链

**Comment by the1812** [comment]
光有一个链接是下载不了的, 视频的链接能下载的关键是要能设置[Referer](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Referer). 比如我在aria2官网找到了设置Referer的[方法](https://aria2.github.io/manual/en/html/aria2c.html#input-file), 所以才会支持aria2导出. 但IDM怎么设这个Referer我就不知道了.
下载菜单里的`直接下载`, `VLD数据`, `aria2`都是会带上Referer去下载的, 而如果选`复制链接`, 直接浏览器里新标签页粘贴打开是一样会403的

**Comment by lidoworld** [comment]
IDM不需要别的插件啊 直接在浮动条设置里手动增加M4S M4V 就能抓B站了

**Comment by the1812** [comment]
这样吗 那我就不做IDM支持了

**Comment by liesauer** [comment]
@the1812 装了idm后，可在js里直接调com对象进行下载（当然仅限windows）

**Comment by liesauer** [comment]
安装idm后，在浏览器有两种下载方式，idm开启浏览器集成后，可直接提供一个直链（在页面上直接a标签显示），用户进行右击->使用idm下载，或者干脆直接将idm设为默认的下载方式，第二种就是如楼上所述，使用代码调idm的com对象，可传自定义header

**Comment by liesauer** [comment]
[Internet Download Manager COM based Application Programming Interface (API)](http://www.internetdownloadmanager.com/support/idm_api.html)

**Comment by the1812** [comment]
@liesauer js能调COM?

**Comment by liesauer** [comment]
用`ActiveXObject`，但是`ActiveXObject`是IE专有的，chrome系可以通过`ActiveX for Chrome`这个插件做到



 
发件人： Grant Howard
发送时间： 2019-09-19 18:55
收件人： the1812/Bilibili-Evolved
抄送： L!εsAμεr; Mention
主题： Re: [the1812/Bilibili-Evolved] 新功能建议 - IDM下载支持 (#149)
@liesauer js能调COM?

**Comment by the1812** [comment]
那不兼容Firefox和Safari啊

**Comment by liesauer** [comment]
😂确实是




发件人: Grant Howard


发送时间: 9月19日星期四 19:39


主题: Re: [the1812/Bilibili-Evolved] 新功能建议 - IDM下载支持 (#149)


收件人: the1812/Bilibili-Evolved


抄送: L!εsAμεr, Mention






那不兼容Firefox和Safari啊

**Comment by Webster-Van** [comment]
IDM是可以设置Referer，如果是英文版，双击下载的文件或右键-属性，就能看到Referer，中文版的则是叫参见。（ps：IDM虽然本身可以抓取，但B站是将视频分段的，所以要下载完整的视频要手动拖进度条，一般5~6分钟一段，即使下载完了，也还要用别的工具拼接，所以还是复制链接下载比较方便。）

**Comment by Webster-Van** [comment]
本人复制下载导出aria2的文本中的链接，直接选开始下载，之后弹出403，然后按上面的步骤设置，再开始下载即可。

**Comment by Webster-Van** [comment]
之前的版本有复制下载链接选项更方便，不过现在也不是不能用IDM下载。

**Comment by the1812** [comment]
啊, 我还以为复制链接没什么用就隐藏掉了. 之后会再放出来的

**Comment by Webster-Van** [comment]
其实不放出来也没什么大问题，不会设置Referer的，再方便也没用，在导出文件里截链接也很容易，从
https://upos截到Referer之前就是了，Referer也在文件里，可以直接复制使用（虽然Referer统一是https://www.bilibili.com也完全没有问题），所以不会用多超过10秒，这是客观的分析。我个人认为下载功能用得还是比较少的，一般用在学习、比较正式的视频或是版权受限的、但以收藏为目的的视频，再或者就是一些可能会被B站删除的视频，其他的基本不会去下载，原因很简单——弹幕，弹幕是B站视频的灵魂，虽说能弄离线弹幕，但离线弹幕还是不够在线的好的。

**Comment by lidoworld** [comment]
就真的不用啊 
老视频是FLV的 分段 下下来自己合并
新的视频是DASH 浮动条设置中增加M4S
![QQ截图20190922142208](https://user-images.githubusercontent.com/24887103/65383219-92af7e00-dd44-11e9-89e0-5a6ccf0069a4.png)

![QQ截图20190922142134](https://user-images.githubusercontent.com/24887103/65383220-9b07b900-dd44-11e9-9651-7fb2e54a1cea.png)
然后视频播放器上弹窗就有了 最大的是视频轨道 最小的是64k劣质音频轨道 还一个是320k音频轨道

**Comment by the1812** [comment]
放个`复制链接`至少能让会设置Referer的人方便些, 而且移除IDM的按钮后正好用这个占一下位, 不然aria2的按钮拉得跟下面RPC一样长...

下载支持基本上没什么问题了, 用浮动条的话参考 @lidoworld 的方法, 不用浮动条就参考 @Webster-Van 的.

**Comment by Webster-Van** [comment]
震惊！看来我已经很久没用IDM浮动条下载B站视频了，我的IDM版本6.35.1，MP4也可以。
![image](https://user-images.githubusercontent.com/55628378/65384699-e7a8bf80-dd57-11e9-846b-0294bccb5682.png)

**Comment by bo-yue** [comment]
其实idm直接在网页中右键链接下载会自动捕获referer、cookies和user-agent什么的，可以试试像一些bai度yun直接下载jiao本一样把直链直接显示出来而不是复制到剪切板里，这样idm下载就很方便了
如[百度网盘直链下载助手](https://github.com/syhyz1990/baiduyun)的显示链接
![2019-10-01_084401](https://user-images.githubusercontent.com/56006608/65926441-d6327800-e427-11e9-9b0a-f3481e109304.png)

又如[EX-百度云盘](https://github.com/gxvv/ex-baiduyunpan)的复制链接
![2019-10-01_085320](https://user-images.githubusercontent.com/56006608/65926703-21995600-e429-11e9-82fa-c706963d00a9.png)
百度云下载也需要referer什么的，能右键下载的话idm就会自己处理，[EX-百度云盘]的实现方式什么还触发了idm悬浮窗

像楼上说的手动设置referer什么的对于我们来说太难了，希望大神能把[复制链接]按钮改成[显示链接]，以明文方式在文本框里显示出直链，这样就可以右键idm下载了，需要的话再在链接旁边添加上[复制链接][Aira2]什么的，像这个P图的效果
![2019-10-01_081730](https://user-images.githubusercontent.com/56006608/65926222-bfd7ec80-e426-11e9-9dfc-53f6d587a29f.png)

真的很希望您能再次考虑一下支持idm的问题，习惯了idm的下载速度不能用的话简直浑身难受，所以不懂编程也特地注册了GirHub账号来评论您已关闭的问题

**Comment by the1812** [comment]
感谢科普, 我之后会改进为`显示链接`的
