### ISSUE TITLE
脚本无法安装

### ISSUE THREAD

**Issue by shanleyao** [the1812/Bilibili-Evolved#1495]
下载好脚本后，用Tampermonkey 的文件导入进行安装，提示无法解析该脚本，安装失败，请问原因是什么？

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/discussions/1413

**Comment by shanleyao** [comment]
（1）脚本双击打不开，显示编译错误，错误信息：行53 ，字符174，语法错误，代码800A03EA，源：Microsoft JScript 编译错误。（2）用记事本打开后，复制粘贴到新建脚本问题成功解决。
（3）但是问什么直接无法安装呢？

**Comment by the1812** [comment]
1. 双击是让 Windows 执行, 但 Windows 不能执行 js 脚本
2. 这就是下载好的脚本安装的正确方法
3. 下载耗时太长被浏览器转成下载了, 正常情况下是直接唤起 Tampermonkey 来安装的

**Comment by shanleyao** [comment]
网页左侧中央没有出现齿轮

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/105620486-b3a44980-5e38-11eb-8a8e-1ba2d31294a7.png)
