### ISSUE TITLE
空白

### ISSUE THREAD

**Issue by xivi1839** [the1812/Bilibili-Evolved#1496]
你的脚本跟这个脚本一起使用会出现B站视频空白
https://greasyfork.org/zh-CN/scripts/375881-bilibili-%E6%B8%AF%E6%BE%B3%E5%8F%B0
![_20213124063135](https://user-images.githubusercontent.com/24610024/105627593-c20f5700-5e72-11eb-8eee-082e8cde18d5.png)

**Comment by Coulomb-G** [comment]
港澳台的版本是1.3.9吗?我这边是显示正常的

**Comment by xivi1839** [comment]
我懂了，应该是他的脚本问题
