### ISSUE TITLE
开启样式-播放器置顶时，无法定位到准确的视频位置

### ISSUE THREAD

**Issue by sssstar** [the1812/Bilibili-Evolved#1498]
**关于哪一项功能**
播放器置顶的定位

**问题描述**

开启播放器置顶功能后，播放器窗口仍然会定位到没有置顶的位置，如图
![开启视频置顶时](https://user-images.githubusercontent.com/49156927/105657760-16144d00-5f00-11eb-8180-57279e1f5b84.jpg)
以上为开启视频置顶时的定位。
![未开启视频置顶时](https://user-images.githubusercontent.com/49156927/105657773-1a406a80-5f00-11eb-86ed-a73fa18385ba.jpg)
以上为未开启视频置顶时的定位。

以上均未开启自动定位到播放器功能，若开启后输入正参数或负参数皆无效。

**脚本版本**

一直以来都有，包括1.11.12、1.11.15。

**浏览器版本**

Chrome 87.0.4280.141（正式版本） （64 位）

**错误信息**

无报错信息

**附加截图**

以下是我的配置文件
[bilibili-evolved-settings.zip](https://github.com/the1812/Bilibili-Evolved/files/5863995/bilibili-evolved-settings.zip)

**Comment by the1812** [comment]
因为你还开了默认宽屏, b站启用宽屏时有个定位的行为, 我阻止不了, 详见 #483
