### ISSUE TITLE
加载组件 设置 失败

### ISSUE THREAD

**Issue by RainSola** [the1812/Bilibili-Evolved#15]
**关于哪一项功能**

设置

**问题描述**

安装后打开B站左下角会显示加载组件 设置 失败的提示，设置按钮没有加载出来。
浏览器：FIREFOX

**脚本版本**

包括正式版、预览版、离线预览等最新版本

**附加截图**

**Comment by the1812** [comment]
可以提供开发者工具(`F12`或`Ctrl+Shift+I`)中控制台的输出信息吗, 我在我的FireFox上测试是可以加载的.
![image](https://user-images.githubusercontent.com/26504152/48532637-28d07780-e8dc-11e8-98b9-74474f969f38.png)

**Comment by RainSola** [comment]
> 
> 
> 可以提供开发者工具(`F12`或`Ctrl+Shift+I`)中控制台的输出信息吗, 我在我的FireFox上测试是可以加载的.
> ![image](https://user-images.githubusercontent.com/26504152/48532637-28d07780-e8dc-11e8-98b9-74474f969f38.png)

直接截图了，不知道可以吗，既然您的FIREFOX没有问题，该不会是我装的其他插件冲突了吧。

![default](https://user-images.githubusercontent.com/45036193/48533591-207a3b80-e8e0-11e8-9336-fae86e3b37da.JPG)

**Comment by the1812** [comment]
可以的, 错误信息是`GM_addValueChangeListener`未定义, 这个东西是Tampermonkey自带的API, 请问您使用的脚本插件是哪个?

**Comment by RainSola** [comment]
> 
> 
> 可以的, 错误信息是`GM_addValueChangeListener`未定义, 这个东西是Tampermonkey自带的API, 请问您使用的脚本插件是哪个?

暴力猴v2.9.10

**Comment by RainSola** [comment]
> 
> 
> 可以的, 错误信息是`GM_addValueChangeListener`未定义, 这个东西是Tampermonkey自带的API, 请问您使用的脚本插件是哪个?

已装UC插件如下：
![2](https://user-images.githubusercontent.com/45036193/48535955-02b0d480-e8e8-11e8-8116-40ef5244c4e8.JPG)

**Comment by the1812** [comment]
了解了, [`预览版1.5.34`](https://github.com/the1812/Bilibili-Evolved/raw/preview/bilibili-evolved.preview.user.js)/[`预览离线版121.98`](https://github.com/the1812/Bilibili-Evolved/raw/preview/bilibili-evolved.preview-offline.user.js)中已提供修复.

**Comment by RainSola** [comment]
> 
> 
> 了解了, [`预览版1.5.34`](https://github.com/the1812/Bilibili-Evolved/raw/preview/bilibili-evolved.preview.user.js)/[`预览离线版121.98`](https://github.com/the1812/Bilibili-Evolved/raw/preview/bilibili-evolved.preview-offline.user.js)中已提供修复.

预览离线版测试没有问题，非常感谢！
