### ISSUE TITLE
顶部搜索栏推荐交互问题

### ISSUE THREAD

**Issue by AlaricGilbert** [the1812/Bilibili-Evolved#150]
**关于哪一项功能**

顶部搜索栏推荐交互问题

**问题描述**

任意界面，顶部搜索栏默认推荐内容直接搜索（回车和点击均会）跳转到空的搜索页面，与b站本身的直接跳转到推荐视频的行为不同，我认为这是一个bug。

**脚本版本**

正式版1.8.8、离线测试版360.03

**浏览器版本**

75.0.3770.100

**错误信息**

无

**附加截图**
![image](https://user-images.githubusercontent.com/36405110/61036554-ea07a880-a3fb-11e9-87a8-27a76e7c6ee0.png)

**Comment by the1812** [comment]
已修复, 刷新几次看看吧
