### ISSUE TITLE
自定义顶栏收藏中少了已被UP主删除的视频

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1500]
**关于哪一项功能**
自定义顶栏

**问题描述**
自定义顶栏收藏中少了已被UP主自主删除的视频

**脚本版本**
正式版  v1.11.12 内容包: a8cd0f5
预览离线版 923.29

**浏览器版本**
百分浏览器 4.3.9.248（正式版本） （64 位） (Chromium 86.0.4240.198)
Chrome 88.0.4324.104 （正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by the1812** [comment]
故意的(
https://github.com/the1812/Bilibili-Evolved/blob/476b0a966ed5aabc6d1b916bdc6b7f28ae067b44/src/style/custom-navbar/favorites-list/custom-navbar-favorites-list.ts#L166-L168

**Comment by Geeyun-JY3** [comment]
但好像也不是全部失效视频都会过滤啊，非UP主自主删除的视频就都还在

**Comment by Geeyun-JY3** [comment]
话说为啥要故意过滤掉已失效视频

**Comment by the1812** [comment]
眼不见心不烦(

**Comment by Geeyun-JY3** [comment]
加个控制台能开的开关？🙈（而且好像也不是全部失效视频都看不见啊

**Comment by the1812** [comment]
我之前不知道失效还有好几种 `attr`, 当时就随便找了个失效的记录下来是 `9`
那我留个开关吧

**Comment by the1812** [comment]
还有哪种失效类型? 我翻遍收藏夹全都是已被up主删除

**Comment by Geeyun-JY3** [comment]
> 还有哪种失效类型? 我翻遍收藏夹全都是已被up主删除

我这边就一个视频写着被 UP 主删除，大部分都是被 B 站因版权或者别的啥原因给下架的
![image](https://user-images.githubusercontent.com/49396421/106442186-f0fe7c00-64b5-11eb-80df-760a615d80d2.png)

我可以干啥么

**Comment by the1812** [comment]
开着network 然后在空间里查看收藏夹 把失效视频的 `attr` 看一下
![image](https://user-images.githubusercontent.com/26504152/106445523-155c5780-64ba-11eb-983b-6a397ce75eb9.png)

**Comment by Geeyun-JY3** [comment]
是 1
![image](https://user-images.githubusercontent.com/49396421/106449302-ca910e80-64be-11eb-9b49-a09c51d8c3ee.png)

**Comment by the1812** [comment]
将由`bilibiliEvolved.settings.customNavbarShowDeadVideos`控制
