### ISSUE TITLE
360无痕浏览器在开启bilibili evolved时无法加载出视频。

### ISSUE THREAD

**Issue by pikaqian** [the1812/Bilibili-Evolved#1503]
360**无痕**浏览器最新版
bilibili evolved 1.11.12

**问题描述**

加载不出的时候感觉最初是加载出来了的，能够看到视频位置有黑色的影子（就是平常视频最初的样子），然后在浏览器标题栏就会从本来的视频名称改成“视频去哪了？”，接着在变回去，可是视频原来的影子也就没了，就会变成下面第一张图的样子。

**脚本版本**

正式版1.11.12

**浏览器版本**

360浏览器：12.2.1813.0
内核版本：78.0.3904.108

**错误信息**

错误信息我看不懂[捂脸]，所以还是给您截图吧

<img width="960" alt="搜狗截图20210128205158" src="https://user-images.githubusercontent.com/42432134/106141208-c0af9880-61aa-11eb-80ae-1d5aa12da4f0.png">

**附加截图**
360**无痕**浏览器在开启evolved并b站视频的时候会出现视频无法显示的情况。（edge和非无痕模式的360浏览器没问题）
哪怕把evolved里面的所有设置和选项都关了也同样会无法显示。
↓↓↓↓↓
<img width="960" alt="2无标题" src="https://user-images.githubusercontent.com/42432134/106108036-b083c300-6182-11eb-9a2d-146d7b89d65d.png">

当在tampermonkey中把evolved关闭后就可以正常显示了，如果此时再打开然后刷新，则会能够播放视频，但是无法加载评论区和右侧视频封面。

<img width="960" alt="1无标题" src="https://user-images.githubusercontent.com/42432134/106108415-2f78fb80-6183-11eb-9a9c-419fbf9f0633.png">

谢谢您！！！！！

**Comment by Geeyun-JY3** [comment]
请按照 issue 模板正常填写反馈信息。
比如这里你的 Chromium 内核版本就很重要

https://github.com/the1812/Bilibili-Evolved#浏览器
> 不保证脚本能在["套壳类浏览器"](https://www.jianshu.com/p/67d790a8f221)或者较长时间没更新的浏览器中完美运行.

可能相关：#1225

**Comment by pikaqian** [comment]
啊抱歉抱歉
我以为只要写出浏览器和脚本版本就行了呢[捂脸]

我把上面的又修改了一下，希望能够更有用
（chromium内核版本是78.0.3904.108）

**Comment by Geeyun-JY3** [comment]
？你不是在 #1225 问过了吗？https://github.com/the1812/Bilibili-Evolved/issues/1225#issuecomment-730808961

**Comment by pikaqian** [comment]
诶那个是视频在下方，只是上面有一串空白，这个就看不到视频了……

**Comment by Geeyun-JY3** [comment]
为啥还要死磕内核这么老的浏览器……都说了不保证兼容
Chrome 都到 88 了……

**Comment by the1812** [comment]
上次不是取消79以下了(

**Comment by pikaqian** [comment]
哦哦哦这样啊[捂脸]
抱歉抱歉
其实我想用360主要是因为有老板键，咳咳……
不过用其他的就好啦
谢谢！！！Thanks♪(･ω･)ﾉ

**Comment by Geeyun-JY3** [comment]
百分也有老板键……不过百分这种小厂第三方 Chromium 浏览器在 Google 搞了不允许第三方浏览器接入 Google 帐号数据后也不好活了

而且 360 不是上 86 了吗：https://github.com/the1812/Bilibili-Evolved/issues/1225#issuecomment-730843949
