### ISSUE TITLE
通过快捷键将倍速从2倍升至2.5倍后，无法通过快捷键或点击倍速按钮，将倍速改回2倍速

### ISSUE THREAD

**Issue by youngerstar** [the1812/Bilibili-Evolved#1504]
**关于哪一项功能**
倍速调节功能

**问题描述**

通过快捷键将倍速从2倍升至2.5倍后，无法将倍速改回2倍

**脚本版本**

1.11.12

**浏览器版本**

Edge Dev 89.0.774.4 

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/46211595/106257098-12156180-6257-11eb-8b68-ddf50d7f0442.png)

**Comment by LonelySteve** [comment]
你好，请问浏览器控制台有输出什么错误信息吗？

另外，请尝试使用[最新预览版](https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@preview/bilibili-evolved.preview.user.js)，如果仍然能复现此问题，请提供你的配置文件，如果该问题仅发生在特定视频页，还请提供该视频页的地址。

**Comment by youngerstar** [comment]
> 你好，请问浏览器控制台有输出什么错误信息吗？
> 
> 另外，请尝试使用[最新预览版](https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@preview/bilibili-evolved.preview.user.js)，由于预览版和正式版的配置是独立的，因此如果在导入你现有的配置文件之后仍能复现此问题，请提供你的配置文件，如果该问题仅发生在特定视频页，还请提供该视频页的地址。

我更新了最新预览版后，先设置好2.5倍速，然后切P后，倍速就无法从2.5倍速降到2倍了
[视频链接](https://www.bilibili.com/video/BV1YE411D7nH?p=67&spm_id_from=pageDriver)
[控制台错误信息](https://github.com/the1812/Bilibili-Evolved/files/5897205/www.bilibili.com-1611973463542.log)

**Comment by LonelySteve** [comment]
@youngerstar  我已经在 #1509 中修复了此问题，不过理论上来说，正式版应该没有这个问题，这个 BUG 应该是在 [v1.11.12](https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@v1.11.12/bilibili-evolved.user.js) 之后引入的。

你使用 v1.11.12 的版本，也是在换 P 的时候出现这个问题吗？

**Comment by youngerstar** [comment]
> @youngerstar 我已经在 #1509 中修复了此问题，不过理论上来说，正式版应该没有这个问题，这个 BUG 应该是在 [v1.11.12](https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@v1.11.12/bilibili-evolved.user.js) 之后引入的。
> 
> 你使用 v1.11.12 的版本，也是在换 P 的时候出现这个问题吗？

对的，1.11.12是在自动播放下一P后，无法调节倍速至2倍。最新预览版也是

**Comment by LonelySteve** [comment]
没能在正式版中复现此问题，你可以先导出保存一下自己的设置，然后重装一下最新的正式版，看问题是否解决（注意，这个版本有个 BUG，扩展倍速要打开「记忆上次播放速度」功能才能用）。

![image](https://user-images.githubusercontent.com/34429322/106354089-38580180-632a-11eb-9b7c-6ee385133526.png)

如果问题解决，说明可能是你的设置项导致了这个问题，请提供你的设置文件以供后续测试。

如果问题依旧，那就等待预览版更新吧。

**Comment by LonelySteve** [comment]
@youngerstar [新的预览版](https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@preview/bilibili-evolved.preview.user.js)已经发布，能帮忙确认一下问题是否已经解决了吗？

**Comment by youngerstar** [comment]
> @youngerstar [新的预览版](https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@preview/bilibili-evolved.preview.user.js)已经发布，能帮忙确认一下问题是否已经解决了吗？

更新后测试了一下，问题没有出现了
