### ISSUE TITLE
收藏夹中的音频的链接存在问题

### ISSUE THREAD

**Issue by shenzhiming88** [the1812/Bilibili-Evolved#1507]
**关于哪一项功能**
收藏

**问题描述**

收藏夹中的音频的链接存在问题，收藏的音频链接应该是形如“https://www.bilibili.com/audio/au*”，但是开启脚本后，链接变为了“https://www.bilibili.com/video/av*”
实例：https://www.bilibili.com/audio/au418827

**脚本版本**

1.11.12

**浏览器版本**

Microsoft Edge
版本 88.0.705.50 (官方内部版本) (64 位)

**错误信息**

无需

**附加截图**
如图，原版链接正确
![image](https://user-images.githubusercontent.com/66902050/106288315-d7c1b980-6282-11eb-8f82-0e9b7597ccb7.png)
如图，开启脚本后链接错误
![image](https://user-images.githubusercontent.com/66902050/106288171-a648ee00-6282-11eb-96a2-308c6193bc7c.png)

请尽快修复这一问题（如果是脚本的问题），谢谢！

**Comment by Geeyun-JY3** [comment]
重复：#1188
自定义顶栏当然是本脚本的问题

**Comment by shenzhiming88** [comment]
> 重复：#1188
> 自定义顶栏当然是本脚本的问题

抱歉，太急了没有看issues，原来重复了
