### ISSUE TITLE
视频播放页 右边齿轮 样式 播放器置顶

### ISSUE THREAD

**Issue by bAdOoWindy** [the1812/Bilibili-Evolved#1508]
**关于哪一项功能**
视频播放页 右边齿轮 样式 播放器置顶

**问题描述**

打开开关后 网页宽屏 视频上部走到显示区域外

**脚本版本**

// @name         Bilibili Evolved (Offline)
// @version      857.15

**浏览器版本**

Microsoft Edge
88.0.705.53

**错误信息**

我觉得无关

**附加截图**
github无法上图=-=

**Comment by Geeyun-JY3** [comment]
GitHub 直接粘贴或点击输入框下方可以上传图片

**Comment by bAdOoWindy** [comment]
![image](https://user-images.githubusercontent.com/4119845/106353500-f3ca6700-6325-11eb-965f-58fa2a8e4ddc.png)

**Comment by Geeyun-JY3** [comment]
滚动条不是还可以往上滚动吗……指的是强迫症不希望点击宽屏后视频上部走到显示区域外？这可能和 B 站启用宽屏时有个定位的行为有关，见：#483

**Comment by bAdOoWindy** [comment]
是的 强迫症 图中那个Scroll To Video Top就是我自己写的“播放器不置顶”设置下 间隔自动滚动到视频顶部的脚本

顶不住啊

**Comment by the1812** [comment]
最简单的办法就是别用宽屏

**Comment by bAdOoWindy** [comment]
我选择不用播放器置顶 告辞
