### ISSUE TITLE
B站新版块(动物圈)无法通过首页过滤功能管理

### ISSUE THREAD

**Issue by DuskShadows** [the1812/Bilibili-Evolved#1513]
**关于哪一项功能**
首页过滤
**问题描述**
B站新划分的板块"动物圈"无法通过该功能进行管理
**脚本版本**
Preview Offline v923.29
**浏览器版本**
FireFox 85.0
**附加截图**

![2021-1-31](https://user-images.githubusercontent.com/65220815/106381005-ef1eb500-63f0-11eb-930d-8f9771523e3a.png)

**Comment by DuskShadows** [comment]
![2021-1-31](https://user-images.githubusercontent.com/65220815/106381074-55a3d300-63f1-11eb-9c90-66a26ff9ae3b.png)

**Comment by Geeyun-JY3** [comment]
#1511 别急
