### ISSUE TITLE
话题栏的图片无法显示

### ISSUE THREAD

**Issue by konghirt** [the1812/Bilibili-Evolved#152]
**问题描述**
话题栏的图片会有1-2张显示不出
打开插件就出现这个问题，关闭后就好了

**脚本版本**
正式版 1.8.8

**浏览器版本**
Chrome 75.0.3770.100

**错误信息**
无

**附加截图**
![2019-07-11_231235](https://user-images.githubusercontent.com/51156881/61064237-fb6ca700-a433-11e9-8094-c8a48c80e4a0.jpg)

**Comment by the1812** [comment]
那一两张是广告... 想看的话把`删除广告`关掉

**Comment by konghirt** [comment]
原来是这样，谢谢啦！建议这里可以用图片代替空白显示，不然强迫症受不了--！
