### ISSUE TITLE
“网址参数清理”功能错误清理必要参数

### ISSUE THREAD

**Issue by sunfkny** [the1812/Bilibili-Evolved#1520]
**关于哪一项功能**
网址参数清理

**问题描述**

打开网址参数清理后，在个人空间-相簿打开任意一个动态（编号长度是10位），跳转404
复制带`?type=2`参数的网址打开，正常打开，刷新，404
其他地方相簿（编号长度18位），正常
关闭网址参数清理，正常

综上，对于编号长度是10位的动态不能清理`?type=2`

**脚本版本**

Preview v1.11.16

**浏览器版本**

Google Chrome 已是最新版本
版本 88.0.4324.104（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
我的锅我的锅🤦‍♂️，之前 [还知道](https://github.com/the1812/Bilibili-Evolved/issues/1219#issuecomment-739523276) 要带这个参数，后来就不知道为啥开了个 discussion 要清掉：#1425

以前在个人空间 > 相簿打开的都是相簿页，如 https://h.bilibili.com/110048615 ，这里的编号长度是 10 位。
然后这里前段时间改版了，结合客户端的更新应该是 B 站想把相簿砍了，打开的变成了动态页（如 https://t.bilibili.com/110048615?type=2 ），但和之前的相簿页的编号还是一样的。
编号长度 18 位的是普通动态，上面说到的也有一个对应的，如：https://t.bilibili.com/486740058018738580

**Comment by Geeyun-JY3** [comment]
现在在个人空间 > 相簿点击图片是直接打开编号长度 18 位的动态了。
