### ISSUE TITLE
下载较大视频时页面崩溃

### ISSUE THREAD

**Issue by Jolkssn** [the1812/Bilibili-Evolved#153]
**关于哪一项功能**
下载视频

**问题描述**
下载较大视频时页面会崩溃，具体上限不清楚，只测试了2.2G和4.9G的视频，2.2G在99.9%时崩溃，4.9G下载到一半左右崩溃

**脚本版本**
正式版1.8.8

**浏览器版本**
Chrome 75.0.3770.142（正式版本） （64 位）

**Comment by Coulomb-G** [comment]
### Chrome浏览器对单个文件大小有限制
详情可以去阅读[README](https://github.com/the1812/Bilibili-Evolved/blob/master/README.md)中的「下载视频」部分的说明
这边的建议是：可以考虑通过[Aria2](https://aria2.github.io/)或者[Bilibili Evolved 视频链接下载器](https://github.com/the1812/Bilibili-Evolved/blob/master/extras/video-link-downloader/README.md)来下载体积较大的视频

**Comment by Jolkssn** [comment]
> ### Chrome浏览器对单个文件大小有限制
> 详情可以去阅读[README](https://github.com/the1812/Bilibili-Evolved/blob/master/README.md)中的「下载视频」部分的说明
> 这边的建议是：可以考虑通过[Aria2](https://aria2.github.io/)或者[Bilibili Evolved 视频链接下载器](https://github.com/the1812/Bilibili-Evolved/blob/master/extras/video-link-downloader/README.md)来下载体积较大的视频

谢谢！之前没留意到readme里的详细说明
