### ISSUE TITLE
当前视频页切换至其它视频后参数不会被清理

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1531]
**关于哪一项功能**
网址参数清理

**问题描述**
在当前视频页切换至其它视频后参数不会被清理

**脚本版本**
正式版 v1.11.12
预览离线版 931.25

**浏览器版本**
百分浏览器 4.3.9.248（正式版本） （64 位） (Chromium 86.0.4240.198)
Chrome 88.0.4324.150（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by the1812** [comment]
调试了下发现换视频后确实运行了清理, 但是那时候那些参数还没加上去

**Comment by the1812** [comment]
调试了下发现换视频后确实运行了清理, 但是那时候那些参数还没加上去

**Comment by Geeyun-JY3** [comment]
好像已经没这问题了。
