### ISSUE TITLE
清爽首页排行榜显示异常

### ISSUE THREAD

**Issue by ccyykk0330** [the1812/Bilibili-Evolved#1539]
**关于哪一项功能**
简化首页-清爽首页

**问题描述**
清爽首页分区中的排行榜显示不完全，且无法滚动
![屏幕截图 2021-02-08 230848.png](https://i.loli.net/2021/02/08/iA9eBFoMvzCjYgP.png)

**脚本版本**
Preview Offline v936.97

**浏览器版本**
chrome88.0.4324.150

**错误信息**

**附加截图**

**Comment by the1812** [comment]
一直都可以滚动的啊
![scroll](https://user-images.githubusercontent.com/26504152/111602489-58764e00-880e-11eb-82ef-860063974168.gif)

**Comment by ccyykk0330** [comment]
现在没有这个问题了，之前好几个版本偶尔出现不能滚动，可能是我的网络问题
