### ISSUE TITLE
附加功能里没有下载视频选项

### ISSUE THREAD

**Issue by chenliu1993** [the1812/Bilibili-Evolved#154]
我在下载台湾地区限制的视频，但是附加功能里没有下载视频选项。请问这是什么原因？

**Comment by the1812** [comment]
请先阅读首页里下载视频的注意事项:
> - 能够下载的清晰度取决于当前登录的账号, 例如`高清 1080P60`需要已登录大会员账号.
> - 如果以您的账号权限无法观看某些视频(**地区限制**, 大会员专享等), 那么这种视频也是无法下载的.

**Comment by chenliu1993** [comment]
欧克，谢谢
