### ISSUE TITLE
直播“包裹”功能失效

### ISSUE THREAD

**Issue by DEabcdp** [the1812/Bilibili-Evolved#1541]
**问题描述**
<任意一个直播间，只有网页全屏“包裹”有效，屏幕全屏点击“包裹”没有反应>

**脚本版本**
<预览版1.11.17>

**浏览器版本**
<Microsoft Edge chormium
版本 89.0.774.23 (官方内部版本) beta (64 位)>

**Comment by DEabcdp** [comment]
已经打开“直播全屏包裹”

**Comment by the1812** [comment]
因为只有网页全屏才能显示那个包裹的弹窗, 我应该在全屏的时候隐藏这个按钮的

**Comment by DEabcdp** [comment]
> 因为只有网页全屏才能显示那个包裹的弹窗, 我应该在全屏的时候隐藏这个按钮的

懂了
