### ISSUE TITLE
Aria RPC 下载失效

### ISSUE THREAD

**Issue by BakaJzon** [the1812/Bilibili-Evolved#1547]
**关于哪一项功能**
Aria RPC 下载

**问题描述**

https://www.bilibili.com/festival/2021bnj?bvid=BV1Do4y1d7K7
正片无法用aria下载，SP和单品正常
但通过显示链接下载有效
疑似Chrome添加了其他HTTP Headers（如sec-ch-ua,sec-ch-...）

**脚本版本**

1.11.12

**浏览器版本**

Chrome 88

**错误信息**

null

**附加截图**
![image](https://user-images.githubusercontent.com/55239052/107726443-e351bd80-6d23-11eb-9c82-5a554feea45f.png)
失败的均为正片，（顺带提一下这些名字也不对

**Comment by the1812** [comment]
拜年祭需要特殊处理 请等待适配
