### ISSUE TITLE
拜年祭视频网页全屏时顶部栏不能自动隐藏

### ISSUE THREAD

**Issue by adfnkjasd** [the1812/Bilibili-Evolved#1549]
脚本版本：1.11.17和1.11.12都不行
浏览器：Chrome 版本 88.0.4324.150
问题视频网址：https://www.bilibili.com/festival/2021bnj?bvid=BV1Do4y1d7K7
![QQ截图20210212165106](https://user-images.githubusercontent.com/39746646/107748128-879f2880-6d53-11eb-89e9-67d6baaa2872.jpg)

**Comment by adfnkjasd** [comment]
忘了补充：其他视频不会出现这个问题

**Comment by the1812** [comment]
全屏 / 宽屏凑合下吧, 拜年祭过段时间就变成普通视频播放页了(
