### ISSUE TITLE
视频下载批量导出时，每个画质不统一会报错

### ISSUE THREAD

**Issue by gendseo** [the1812/Bilibili-Evolved#155]
**关于哪一项功能**

视频下载批量导出时，因为每个视频画质不统一，所以选择高的画质以后会报没有用户权限（其实权限是有的，是因为其中有几个视频没有这个画质）

**问题描述**

1. 选择了一个画质（假如第一集视频选了1080p）
2. 选择批量导出
3. 报错（是因为其中某个视频没有到达这个画质（可能它只有720p））

举例网页：https://www.bilibili.com/video/av52122836

**脚本版本**

1.8.8

**浏览器版本**

Chrome 最新

**错误信息**

提示信息：
批量下载
 获取下载链接失败, 请确认当前账号有下载权限后重试.

**附加截图**

**Comment by the1812** [comment]
已修复, 现在应该会降低到那个视频的最高画质
