### ISSUE TITLE
能否添加下载指定日期历史弹幕的功能

### ISSUE THREAD

**Issue by anatoliux2233** [the1812/Bilibili-Evolved#1554]
首先给大佬拜年！
不是biliplus全弹幕装填的意思，是在网页播放器中选择加载某一天的历史弹幕后下载该指定日期的弹幕，目前的状况是在播放器中加载历史弹幕后下载弹幕，内容还是最近一天的最新弹幕。
另外我在使用历史弹幕接口时无法加载，显示“本视频弹幕功能已被关闭”，实际上网页端是可以正常加载的，不知https://api.bilibili.com/x/v2/dm/history?type=1&date=xxxx-xx-xx&oid=xxxxxxxxx 这个端口是否还能正常使用？（以《宝石幻想：光芒重现》第十二集2020年10月7日的弹幕为例）
![screencapture-api-bilibili-x-v2-dm-history-2021-02-13-14_11_23](https://user-images.githubusercontent.com/38915367/107843660-18cfd700-6e08-11eb-8562-a32d8080a215.png)
使用gayhub还不太熟练，帖子好像重复发送了，并非故意刷屏，请见谅。
_Originally posted by @anatoliux2233 in https://github.com/the1812/Bilibili-Evolved/discussions/1553_

**Comment by Geeyun-JY3** [comment]
功能建议和提问像 #1553 那样开 discussion 就行
https://github.com/the1812/Bilibili-Evolved/blob/preview/issue-rules.md
> Issues 用于记录 Bug 等发生异常问题的情况, 如果您希望讨论新功能或是提问 / 答疑, 请到[讨论区](https://github.com/the1812/Bilibili-Evolved/discussions)进行.
