### ISSUE TITLE
拜年祭活动视频页面夜间模式显示异常

### ISSUE THREAD

**Issue by Duanyll** [the1812/Bilibili-Evolved#1556]
**夜间模式**

**问题描述**

如 [2021拜年祭](https://www.bilibili.com/festival/2021bnj?bvid=BV1Do4y1d7K7)

**脚本版本**

Offline v909.25

**浏览器版本**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.47 Safari/537.36 Edg/89.0.774.27 

在 Firefox (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0) 中也能复现

**错误信息**

应当是 css 注入有误，可以考虑有特殊 css 的活动页面暂时禁用夜间模式

**附加截图**
![image](https://user-images.githubusercontent.com/24842865/107879906-941fae80-6f16-11eb-9996-c97a79510fab.png)

![image](https://user-images.githubusercontent.com/24842865/107880113-c7af0880-6f17-11eb-80a7-9b96c5cd8f7a.png)

活动页面的css修改了背景颜色导致夜间模式失效

**Comment by LonelySteve** [comment]
最新预览版已经修了，要说的话，确实直接屏蔽拜年纪活动页来的方便，修修补补又用不了几天（
