### ISSUE TITLE
夜间模式定时在首次到点时部分失效

### ISSUE THREAD

**Issue by Youwenqwq** [the1812/Bilibili-Evolved#1558]
**关于哪一项功能**
夜间模式

**问题描述**

问题页面：
（动态）https://t.bilibili.com/

复现操作：设置->样式->夜间模式计划时段开启
到达时段后刷新页面，发现首次刷新时页面呈现附加截图中的画面（即仅导航栏应用了夜间模式），再次刷新后恢复正常
在设置里手动关闭夜间模式（此时计划时段功能仍然保持开启）再刷新，问题复现

**脚本版本**

Stable v1.11.12

**浏览器版本**

Chromium Edge 88.0.705.68

**错误信息**

![屏幕截图 2021-02-15 182919.png](https://i.loli.net/2021/02/15/OjVeHInt2i95Qdp.png)

**附加截图**
![屏幕截图 2021-02-15 183401.png](https://i.loli.net/2021/02/15/Wjkve9yCLiNzmQE.png)

**Comment by Geeyun-JY3** [comment]
看着好像有关联：#1435
