### ISSUE TITLE
删除已经截的图的时候会出现多余的滚动条

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#1559]
emm这个小小的问题实际上是属于强迫症。

**关于哪一项功能**
视频截图

**问题描述**

使用视频截图后再删除右上角那个截图时，下方会瞬间出现一个横向滚动条。
（一开始没注意就觉得有什么一闪而过，于是就多截了几次特意去看了一下，结果就是滚动条。）

**脚本版本**

Preview v1.11.17
内容包: 391d208

**浏览器版本**

88.0.4324.150

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/107964952-de6f6100-6fe4-11eb-8311-74784f0d66b4.png)
[GIF](https://p.imoe.xyz/s/9R1ta)

**Comment by Geeyun-JY3** [comment]
GIF 也是图片，能直接上传（

**Comment by CKylinMC** [comment]
> GIF 能直接上传（

我也记得能，但是昨晚发的时候突然忘了怎么发了...（因为我一般是剪贴板上传...

**Comment by Geeyun-JY3** [comment]
就图片，直接剪贴板或本地文件上传都行

**Comment by CKylinMC** [comment]
> 就图片，直接剪贴板或本地文件上传都行

我用ShareX录屏然后直接点复制，在这边黏贴就会变成png...

直接拖动文件没事，那估计是ShareX的锅...

~(😂这不是重点)~

**Comment by the1812** [comment]
调着调着发现另一个bug, 截多了上下滚不动了

**Comment by CKylinMC** [comment]
> 调着调着发现另一个bug, 截多了上下滚不动了

截图过几秒自动隐藏到侧栏，侧栏点开单独给一个面板可以回顾这次之前截过的图，这样既不占用页面空间，也可以更好的翻找之前的截图...

_就像这样？_
![VpOsXPMhm9](https://user-images.githubusercontent.com/11648014/109604581-bba18880-7b5e-11eb-80f5-414ce86055e0.gif)

现在截图栏会挡住一些按钮：
![image](https://user-images.githubusercontent.com/11648014/109603763-441f2980-7b5d-11eb-9177-164258ff8816.png)

> 不过好像工程量有点大，那当我没说23333

**Comment by the1812** [comment]
那样的话 如果设置也放在右边加自动隐藏侧栏开启就会冲突
