### ISSUE TITLE
加速、减速调整顺序不一致

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#1565]
**关于哪一项功能**
倍速播放

**问题描述**

通过快捷键`shift`+`↑`和`shift`+`↓`进行倍速调整时，遍历倍速的顺序并不一致。

我现在的倍速栏：
![image](https://user-images.githubusercontent.com/11648014/108160225-a4f13f80-7123-11eb-959e-d319130c7fbf.png)

此时我进行加速顺序：（方便观察，我先减速了一次，从0.75x开始）

`1x`→`1.25x`→`1.5x`→`2x`→`2.5x`  _(1.75x呢？)_

![ssZOookOfq](https://user-images.githubusercontent.com/11648014/108160242-af133e00-7123-11eb-9f02-8412fc80f7e0.gif)

然后我再减速：（方便查看我再次按了一下加速，所以这里是从3x开始向下）

`2.5x`→`1.75x`→`1.5x`→`1.25x`→`1x` _(2x呢？)_

![qbL2HBN1Bt](https://user-images.githubusercontent.com/11648014/108160365-e681ea80-7123-11eb-9d22-23f7ddcea4bf.gif)

观察倍速栏

`1.75`以上是额外的
`2`是自带的

![image](https://user-images.githubusercontent.com/11648014/108160431-06191300-7124-11eb-8d2d-b62c5f3e39a4.png)
![image](https://user-images.githubusercontent.com/11648014/108160447-0fa27b00-7124-11eb-95cb-9bd0024c4e76.png)

那这个顺序就很诡异了。

似乎是标准的调速和附加的调速两个之间切换的时候，总会跳过一个。

（另外倍速可以不可以排序...）

~不确定有没有其他人发过，但是稍微搜了一下issues没看到相似的，这个bug从可以添加自定义倍速开始就有了，只是觉得问题不大，但是最近看网课就感觉很蛋疼了~

**脚本版本**

Preview v1.11.17
内容包: 391d208

**浏览器版本**

88.0.4324.182

**错误信息**

**附加截图**

**Comment by LonelySteve** [comment]
快捷键可以做到按顺序调整倍数（#1566），但是因为技术原因，倍数菜单不行，如果你非要添加一个原生倍速之间的扩展倍速，它一定会在所有原生倍速之上，可以看看 [feature.md](https://github.com/the1812/Bilibili-Evolved/blob/preview/features.md) 中有关「扩展视频倍数菜单」的功能介绍。

**Comment by the1812** [comment]
(可以拿css整点歪招
```js
dqa('.bilibili-player-video-btn-speed-menu-list[data-value]').forEach(it => it.style.order = (16 - parseFloat(it.getAttribute('data-value'))) * 10000)
```
```css
.bilibili-player-video-btn-speed-menu {
  display: flex;
  flex-direction: column;
}
```

**Comment by LonelySteve** [comment]
@the1812 确实，有点意思，我试试👌

**Comment by CKylinMC** [comment]
> 快捷键可以做到按顺序调整倍数（#1566），但是因为技术原因，不会在原生倍速项之间插入扩展倍速项，如果你非要添加一个原生倍速之间的扩展倍速，它一定会在所有原生倍速项之上插入，可以看看 [feature.md](https://github.com/the1812/Bilibili-Evolved/blob/preview/features.md) 中有关「扩展视频倍数菜单」的功能介绍。

懂了，其实只要有规律可循就问题不大。主要是如果顺序不一样每次调整的时候都要多按几下...
