### ISSUE TITLE
请求加入功能，漫画站解锁地区限制

### ISSUE THREAD

**Issue by david082321** [the1812/Bilibili-Evolved#157]
**关于哪一项功能**

漫画站，部分漫画海外不能看。能像视频一样自动翻墙吗？

**期望的效果**
例如：
海外
![1](https://user-images.githubusercontent.com/7046617/62369677-eed6fc80-b562-11e9-8be7-5a50b4b57232.jpg)
翻墙进入中国
![2](https://user-images.githubusercontent.com/7046617/62369683-f39bb080-b562-11e9-912c-4e4891109754.jpg)

**脚本版本**

我用的是预览离线版

**Comment by Coulomb-G** [comment]
1.这边并没有视频自动翻墙功能
2.其他插件的自带翻墙功能是需要服务器来实现的,这边也并没有服务器相关的功能
3.你或者可以试试通过plus那边看相关漫画(这点我本人并不在海外,尚未尝试过
