### ISSUE TITLE
[稍后再看] 中多余的分p参数

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#1574]
又是一个强迫症的小问题...

**关于哪一项功能**
顶栏的稍后再看弹窗。

**问题描述**

从顶栏的稍后再看点进**任何项目**都会多一个`?p=1`的参数。p本身是分p我知道，但是**原视频本来也只有1p**...而且每一个视频都加这么一个后缀...

另外，建议清理掉所有 `p=1`、`t=0`的参数，这两个值对于选项来说没啥意义。。。
`t=0`并不会自动播放，`t=0.1`可以。

**脚本版本**

Preview v1.12.0
内容包: 2f10fd3

**浏览器版本**

88.0.4324.182

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/108312945-67a7b300-71f2-11eb-8a84-6c08266edcbc.png)
![image](https://user-images.githubusercontent.com/11648014/108313021-89089f00-71f2-11eb-88c6-b59bb6c4080d.png)

**Comment by the1812** [comment]
其实是我想偷懒少写两个`if`, 直接把 API 给的数据放到参数上了(
