### ISSUE TITLE
没有见到左上角的齿轮

### ISSUE THREAD

**Issue by Jarrycow** [the1812/Bilibili-Evolved#158]
没有见到左上角的页面啊

**Comment by Coulomb-G** [comment]
设置按钮在b站页面的左侧中央位置
![Uploading 截图.png…]()

**Comment by the1812** [comment]
<img src="https://user-images.githubusercontent.com/26504152/62786404-1430b100-baf5-11e9-968c-33f95ef00e12.png" height="400">

**Comment by GoogleBeEvil** [comment]
我这里也没有
firefox+violentmonkey

**Comment by the1812** [comment]
已测试 Firefox+Violentmonkey, 我这里是可以正常使用的, 请问控制台(`Ctrl + Shift + I`)有输出什么错误信息吗?

**Comment by MaxMadcc** [comment]
![CSP Error](https://user-images.githubusercontent.com/19978097/64018115-15865400-cb5e-11e9-93c6-8e4afb783c86.png)
我这里提示了csp错误，我这是firefox+tampermonkey

**Comment by the1812** [comment]
CSP跟这个应该没关系, 我这也报CSP错误但是并不影响使用

**Comment by the1812** [comment]
没见着齿轮的而且网页没有任何变化的, 可能是脚本安装不完整, 可以参考 #222 里的讨论.

**Comment by GoogleBeEvil** [comment]
看邮件列表i的时候才发现，我这里安装最新的1.9.16任然是没齿轮，进violentmonkey看了下，是安装的时候脚本没加载完全（显示脚本已加载完全，但实际代码页是空的），手动下载下来加载就有了。我注意到本脚本有1.45mb左右，不知道是不是violentmonkey 对脚本文件大小有限制还是gayhub的问题，因为我记得githubraw的文件实际上是在amazon的云上，在我这里是被gfwed（间歇被墙），另外也没试vue jq等第三方库是否被墙。greasyfork上的脚本没去试

**Comment by the1812** [comment]
Violentmonkey可以装, 但是编辑器里无法显示也无法修改, 所以很难确定到底下完整了没有
vue那些CDN倒不会被间歇墙, greasyfork相对github raw要稳定很多

**Comment by GoogleBeEvil** [comment]
vmonkey本身是支持修改脚本的，你这个脚本似乎是太大了或者vmonkey存在什么bug导致无法显示且无法修改。改天去vmonkey报个issue

Grant Howard <notifications@github.com> 于2019年11月17日周日 下午12:43写道：

**Comment by the1812** [comment]
应该是太大了，其他一些小的脚本我可以编辑

**Comment by GoogleBeEvil** [comment]
vm的问题，新版本应该修复了，等新版本上架吧
