### ISSUE TITLE
打开动态评论粉丝套装显示会拉伸

### ISSUE THREAD

**Issue by aurxs** [the1812/Bilibili-Evolved#1583]
**关于哪一项功能**
动态-评论(bug)

**问题描述**

打开动态评论粉丝套装显示会拉伸

**脚本版本**

 正式版v1.12.0

**浏览器版本**

edge 版本 88.0.705.74 (官方内部版本) (64 位)

**错误信息**

![I}}T 24ZMQ2)$%Z(J97A%M9](https://user-images.githubusercontent.com/79303639/108473741-66958500-72c9-11eb-8594-5f8cc078d21b.png)

**附加截图**
开启脚本前：
![YN}L62 ZI(DS1SW WB~I`BN](https://user-images.githubusercontent.com/79303639/108473802-79a85500-72c9-11eb-9ef3-6f15e7d9ce5f.png)
开启脚本后：
![GXK(L{OA$26 LA_FNAF% CM](https://user-images.githubusercontent.com/79303639/108473832-82009000-72c9-11eb-8523-c70a3465fa2f.png)

**Comment by aurxs** [comment]
视频也会：
![J7A%LI~(4CX@P~VGC715LDF](https://user-images.githubusercontent.com/79303639/108474069-cee46680-72c9-11eb-8fed-4c4e8c9c79f9.png)

**Comment by Geeyun-JY3** [comment]
应该是老问题了（之前发现过找不到有没有发过在 issue 了

**Comment by aurxs** [comment]
那到时会修复吗？

**Comment by yuban01652** [comment]
问题出在设置-工具-高分辨率图片上，关掉即可，望早日修复

**Comment by the1812** [comment]
感谢 已确认问题原因
