### ISSUE TITLE
显示失效视频信息又双叒叕被ban了

### ISSUE THREAD

**Issue by the1812** [the1812/Bilibili-Evolved#159]
#80 中的通过稍后再看恢复失效视频信息的方法现在无效了, 因为已失效视频现在无法加入稍后再看.
稍后再看API将返回:
```json
{
  "code":90003,
  "message":"稿件已经被删除",
  "ttl":1
}
```

`显示失效视频信息`将在下次更新时换用BiliPlus方法或者也可能再次隐藏.

**Comment by LinEvil** [comment]
建议在 features.md 中加入相关说明

-------------------
找了半天（

**Comment by the1812** [comment]
我忘记在features里去掉这条了...
