### ISSUE TITLE
OVA集数异常（

### ISSUE THREAD

**Issue by BakaJzon** [the1812/Bilibili-Evolved#1592]
这该算啥？特性！
![image](https://user-images.githubusercontent.com/55239052/107730222-d043eb00-6d2d-11eb-9c2f-d19d69606573.png)
![image](https://user-images.githubusercontent.com/55239052/107730237-d934bc80-6d2d-11eb-9a83-235a62b3f07b.png)

_Originally posted by @BakaJzon in https://github.com/the1812/Bilibili-Evolved/discussions/1548_

**Comment by the1812** [comment]
你那是怎么试出来的 我导出来文件名是`01 - 1.mp4` (`n`对应的是`01`)
![image](https://user-images.githubusercontent.com/26504152/108614833-edb53b00-7438-11eb-94c3-f69a23e02ed9.png)

**Comment by BakaJzon** [comment]
emmm，B站又改了？？？
旧版本特性，特性

 
![image](https://user-images.githubusercontent.com/55239052/108623840-1ca0d080-747c-11eb-874a-e87a92a20c35.png)
