### ISSUE TITLE
请求将“bilibili订阅+”脚本的功能添加进去

### ISSUE THREAD

**Issue by HCLonely** [the1812/Bilibili-Evolved#160]
装了这个脚本后[bilibili订阅+](https://greasyfork.org/zh-CN/scripts/30283)脚本的功能不能用了，希望作者大大能把它的功能加进去

**Comment by the1812** [comment]
自定义顶栏的布局设置里可以调出`订阅`, 不过没有列表显示, 是直接转到个人空间里. 列表以后应该会加上.
<img height="400" src="https://user-images.githubusercontent.com/26504152/62835938-8ab5e600-bc90-11e9-8e82-d92f47429460.png">

或者也可以用先用着预览版, 那里的`动态`里直接有`番剧`一栏.
<img height="400" src="https://user-images.githubusercontent.com/26504152/62835972-d2d50880-bc90-11e9-8487-f30408d5fbcf.png">

**Comment by HCLonely** [comment]
好的，谢谢
