### ISSUE TITLE
主页动态图片失效

### ISSUE THREAD

**Issue by LiuXiahong** [the1812/Bilibili-Evolved#1601]
**关于哪一项功能**
样式--简化主页

**问题描述**

打开简化主页

**脚本版本**

1.12

**浏览器版本**

Microsoft Edge 

**错误信息**

**附加截图**
![使用前](https://user-images.githubusercontent.com/63397435/109252823-65180f80-7829-11eb-82bc-a81c2d36cb13.png)

![使用后](https://user-images.githubusercontent.com/63397435/109252443-84626d00-7828-11eb-897b-2422dddf47eb.png)

**Comment by the1812** [comment]
你之前配置过adblock规则吗
就是这里的: https://github.com/the1812/Bilibili-Evolved/blob/master/src/style/simplify-home/simplify-home.md

**Comment by the1812** [comment]
那应该是简化主页阻止了原页面功能
