### ISSUE TITLE
开启夜间模式后，历史记录的搜索框依旧为白色

### ISSUE THREAD

**Issue by ChenMoFeiJin** [the1812/Bilibili-Evolved#1607]
**关于哪一项功能**
夜间模式

**问题描述**

如下图，开启夜间模式后，历史记录的搜索框依旧为白色

**脚本版本**

Stable v1.12.0
内容包: 328d2ac

**浏览器版本**

MicrosoftEdge 版本 88.0.705.53 (官方内部版本) (64 位)

**错误信息**

无

**附加截图**
![image](https://user-images.githubusercontent.com/42508525/109376989-32424a00-7903-11eb-8188-45b006983b3f.png)

**Comment by Geeyun-JY3** [comment]
哦吼吼，网页端的历史记录搜索终于来了
