### ISSUE TITLE
将B站首页极简化

### ISSUE THREAD

**Issue by YogiLiu** [the1812/Bilibili-Evolved#161]
**关于哪一项功能**
B站首页极简化，在我日常的使用中我发现，我几乎不会关注顶栏往下的任何信息，我只在乎我关注的UP是否有更新以及搜索功能及排行榜功能，我不知道我这样的习惯是否普遍。

**期望的效果**
Goole首页是一个比较理想的效果，够简单，够干净。
![Screenshot_20190813_093345.png](https://i.loli.net/2019/08/13/tT9fjF78bBR2aHY.png)

**脚本版本**
正式版

**Comment by the1812** [comment]
很不错的想法, 我也有把首页改得清爽一些的计划. 不过大概要在9月份之后开始做, 到时候会先做你的极简化的.
(顺便放个之前摸的效果图, 看了你的建议我觉得还可以放个UP的更新动态进去)
<img height="400" src="https://user-images.githubusercontent.com/26504152/62910418-fe501400-bdb2-11e9-8e7d-dd1886c622fc.png">

**Comment by YogiLiu** [comment]
感谢回复，期待这个功能上线！

**Comment by MI55-845** [comment]
> 很不错的想法, 我也有把首页改得清爽一些的计划. 不过大概要在9月份之后开始做, 到时候会先做你的极简化的.
> (顺便放个之前摸的效果图, 看了你的建议我觉得还可以放个UP的更新动态进去)
> <img alt="" height="400" src="https://user-images.githubusercontent.com/26504152/62910418-fe501400-bdb2-11e9-8e7d-dd1886c622fc.png">

这个页面太棒了！！！很期待！！！

**Comment by the1812** [comment]
初步完工, 接下来应该会结合 #270 改进一下极简模式

**Comment by ldy16889** [comment]
您好  我是一个china用户，我和你使用习惯相似，也许我还激进一些，我希望拥有一个：B站首页极简化（只需要一个搜索功能入口和收藏夹和关注），我只在乎我关注的UP是否有更新以及搜索功能，不需要推荐 也不热搜，希望早日看到您的作品

**Comment by ldy16889** [comment]
Hello, I am a user of china, I have similar usage habits with you, maybe I am more radical, I hope to have a: the homepage of website B is extremely simple (only need a search function entry and favorites and follow), I only care about whether the UP I follow has updates and search functions, do not need recommendation and hot search, I hope to see your works as soon as possible

**Comment by Tinhone** [comment]
> 您好 我是一个china用户，我和你使用习惯相似，也许我还激进一些，我希望拥有一个：B站首页极简化（只需要一个搜索功能入口和收藏夹和关注），我只在乎我关注的UP是否有更新以及搜索功能，不需要推荐 也不热搜，希望早日看到您的作品

也许可以尝试一下组件 `极简首页`
