### ISSUE TITLE
使用插件下载b站视频，点击下载按钮后，浏览器左下角提示“错误 Failed to fetch” 不能进行视频的下载

### ISSUE THREAD

**Issue by Iamyourbaba** [the1812/Bilibili-Evolved#1614]
**关于哪一项功能**
如题，使用插件下载b站视频，点击下载按钮后，谷歌浏览器左下角提示“错误Failed to fetch”。

插件下载视频功能以前可以使用，但是今天不知道是什么原因导致下载功能不能使用。在此期间，电脑未进行系统的升级，只是安装了IDM软件，并且谷歌浏览器中的IDM插件也被本人禁止。在退出IDM软件和关闭谷歌浏览器中的IDM插件后，也不能进行b站视频的下载

还有，从家回到学校，网络环境进行了更改（但是网络能正常使用）。不知道是否是这个原因。

**问题描述**
我也不知道能否在你们的电脑浏览器中重现此现象，本人使用谷歌浏览器在多个b站视频下进行测试，均不能进行视频的下载，提示错误均为 Failed to fetch

**脚本版本**
1.12.0   正式版

**浏览器版本**
谷歌浏览器    版本 89.0.4389.72（正式版本） （64 位）

**错误信息**

Access to fetch at 'https://cn-sh-fx-bcache-03.bilivideo.com/upgcxcode/77/94/305379477/305379477_nb2-1-80.flv?e=ig8euxZM2rNcNbTM7zUVhoMj7wuBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1614777037&gen=playurlv2&os=bcache&oi=3670129929&trid=0b1f2af5553c45758cad9bbed47c5cc5u&platform=pc&upsig=fb299eca18e6dd85b7c09783fed599b5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&cdnid=3742&mid=30741255&orderid=0,3&agrr=0&logo=80000000' from origin 'https://www.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
cn-sh-fx-bcache-03.bilivideo.com/upgcxcode/77/94/305379477/305379477_nb2-1-80.flv?e=ig8euxZM2rNcNbTM7zUVhoMj7wuBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1614777037&gen=playurlv2&os=bcache&oi=3670129929&trid=0b1f2af5553c45758cad9bbed47c5cc5u&platform=pc&upsig=fb299eca18e6dd85b7c09783fed599b5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&cdnid=3742&mid=30741255&orderid=0,3&agrr=0&logo=80000000:1 Failed to load resource: net::ERR_FAILED
userscript.html?name=Bilibili%20Evolved.user.js&id=da713cec-e451-4eeb-a633-3cbfdff843b5:13210 TypeError: Failed to fetch

**附加截图**
![image](https://user-images.githubusercontent.com/48672460/109798361-9cd1ed80-7c55-11eb-9a57-309d0d44866f.png)

**Comment by the1812** [comment]
你换几个网络试试? 比如手机开热点

**Comment by Iamyourbaba** [comment]
@the1812  可行，谢谢。不知是学校校园网的问题还是路由器的问题，我再试试，tks
