### ISSUE TITLE
偶尔插件不启动

### ISSUE THREAD

**Issue by DavidZhang53** [the1812/Bilibili-Evolved#162]
有时候又恢复到原页面，请问如何解决，是我个人的问题吗

**Comment by the1812** [comment]
离线版也这样吗？

**Comment by DavidZhang53** [comment]
> 离线版也这样吗？

离线版是不是加载在油猴子里的脚本呀，可能是我的油猴子问题，其他脚本也时常不启动，请问作者大大对此有没有解决方法啊

**Comment by the1812** [comment]
重新装一下油猴试试吧，你的油猴是Violentmonkey还是Tampermonkey？

**Comment by DavidZhang53** [comment]
是Tampermonkey，没关系这点小错误无伤大雅，万分感谢您为我们制作那么好的插件




------------------ 原始邮件 ------------------
发件人: "Grant Howard"<notifications@github.com>; 
发送时间: 2019年8月15日(星期四) 中午11:01
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com>; 
抄送: "饮冰"<1779652461@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [the1812/Bilibili-Evolved] 偶尔插件不启动 (#162)




重新装一下油猴试试吧，你的油猴是Violentmonkey还是Tampermonkey？
