### ISSUE TITLE
用方向键调整进度条时CC字幕不能正常跟随视频进度

### ISSUE THREAD

**Issue by solitary-sails** [the1812/Bilibili-Evolved#1625]
上条issue手滑了。。。
**问题描述**
网页全屏或全屏时用方向键调整带CC字幕的视频
**脚本版本**
Stable v1.12.0 内容包: a7f0ebb
**浏览器版本**
Edge 89.0.774.45
**补充说明**
仅会在用方向键调整时出现，开启脚本时用鼠标点击调整进度条无问题。关闭脚本后方向键也可以正常调整。

**Comment by Geeyun-JY3** [comment]
[[预览]v1.12.1](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.12.1-preview) 刚修…… #1514

**Comment by solitary-sails** [comment]
啊这，那我close吧
