### ISSUE TITLE
暗色模式下视频合集还是白色

### ISSUE THREAD

**Issue by EasyRain** [the1812/Bilibili-Evolved#1626]
**关于哪一项功能**
暗色模式

**问题描述**

暗色模式下视频合集还是白色

**脚本版本**

Preview v1.12.1

**浏览器版本**

Chrome 版本 88.0.4324.150（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/46843500/110334426-b8763300-805d-11eb-85b0-277eeba0231c.png)

**Comment by Geeyun-JY3** [comment]
新功能诶

**Comment by paletree** [comment]
![屏幕截图 2021-03-10 195628](https://user-images.githubusercontent.com/38284716/110628389-e97d7180-81dd-11eb-87cd-aab2722e34be.png)
问题依旧没解决，当前测试BV1h54y1a7fT，Stable v1.12.0
内容包: 6c674f2

**Comment by Geeyun-JY3** [comment]
> 问题依旧没解决，当前测试BV1h54y1a7fT，Stable v1.12.0
内容包: 6c674f2

修也要时间的啊，更何况要修也是预览版先修（预览版现在还没修，别急）……

**Comment by Geeyun-JY3** [comment]
没想到我这么快也被灰度到了
无分 P 视频的自动连播按钮没跟随主题色，下边多了条分割线
![image](https://user-images.githubusercontent.com/49396421/110929804-553d1700-8363-11eb-98e1-089e6e969c7d.png)
