### ISSUE TITLE
头像挂件有偏移

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#1627]
**关于哪一项功能**
头像挂件

**问题描述**

头像挂件偏移

**脚本版本**

Preview v1.12.1
内容包: 8f263a2

**浏览器版本**

88.0.4324.190

**错误信息**

![image](https://user-images.githubusercontent.com/11648014/110473636-b7a2d700-8119-11eb-94fc-43b23051e409.png)

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/110473601-ac4fab80-8119-11eb-8c06-185aedfebea1.png)

**Comment by the1812** [comment]
昨天修了 热更新大概明早就有

**Comment by CKylinMC** [comment]
> 昨天修了 热更新大概明早就有

![image](https://user-images.githubusercontent.com/11648014/110748252-6d853700-827a-11eb-880a-7b5c849f992c.png)
Preview v1.12.1
内容包: 8f263a2

emmm...我是不是应该删了重装一下

**Comment by the1812** [comment]
你确定热更装上了? 我内容包是 bd2b0d9
![image](https://user-images.githubusercontent.com/26504152/110749225-cd301200-827b-11eb-96d9-9deb66c2adf8.png)

**Comment by CKylinMC** [comment]
> 你确定热更装上了? 我内容包是 bd2b0d9
> ![image](https://user-images.githubusercontent.com/26504152/110749225-cd301200-827b-11eb-96d9-9deb66c2adf8.png)

有什么办法主动检查更新内容包吗？

**Comment by the1812** [comment]
每次刷新都会检查

**Comment by CKylinMC** [comment]
![image](https://user-images.githubusercontent.com/11648014/110749373-11231700-827c-11eb-8913-91a1e38684cc.png)
![image](https://user-images.githubusercontent.com/11648014/110749578-44fe3c80-827c-11eb-81f4-8018553a0c4c.png)

**Comment by the1812** [comment]
怪了
运行这个看看?
```js
bilibiliEvolved.settings.cache.imageResolution.includes('width: 100% !important')
```

**Comment by CKylinMC** [comment]
> 怪了
> 运行这个看看?
> 
> ```js
> bilibiliEvolved.settings.cache.imageResolution.includes('width: 100% !important')
> ```

![Uploading image.png…]()

**Comment by CKylinMC** [comment]
> 怪了
> 运行这个看看?
> 
> ```js
> bilibiliEvolved.settings.cache.imageResolution.includes('width: 100% !important')
> ```

![image](https://user-images.githubusercontent.com/11648014/110750302-3cf2cc80-827d-11eb-823b-5c2609da244f.png)

**Comment by the1812** [comment]
那是已经更上了啊... 怎么还偏移

**Comment by CKylinMC** [comment]
重装了一遍Preview版本。
Preview v1.12.1
内容包: 8aea9f1
还是偏移...

**Comment by CKylinMC** [comment]
我看到刚刚加载完成的一瞬间是对的，紧接着偏移的。

![image](https://user-images.githubusercontent.com/11648014/110750912-2bf68b00-827e-11eb-8cac-1af970f033c8.png)

如果加一个自动宽度，就没事了

![image](https://user-images.githubusercontent.com/11648014/110751099-5d6f5680-827e-11eb-85d6-5e595355e394.png)

看上去宽度是写的img属性上的。

![image](https://user-images.githubusercontent.com/11648014/110751172-76780780-827e-11eb-92e0-3bccab9d6105.png)

**Comment by CKylinMC** [comment]
> 你确定热更装上了? 我内容包是 bd2b0d9

我的内容包版本依然和这个不一样，这是我今天见过的第三个版本号了：a6a365e

上一次的是 8aea9f1

重装之前是 8f263a2

**Comment by the1812** [comment]
热更包里加了`width: 100%`的, 你那边没有吗
![image](https://user-images.githubusercontent.com/26504152/110751426-ce167300-827e-11eb-9156-63abcd284e56.png)
![image](https://user-images.githubusercontent.com/26504152/110751451-d5d61780-827e-11eb-9409-b89630b51e8c.png)

**Comment by CKylinMC** [comment]
> 热更包里加了`width: 100%`的, 你那边没有吗

没有。我觉得我这边可能更新出了问题。

**Comment by CKylinMC** [comment]
![image](https://user-images.githubusercontent.com/11648014/110751809-57c64080-827f-11eb-8d76-cbaaf3ff3b96.png)
诡异

**Comment by the1812** [comment]
那换预览离线用着先吧

**Comment by CKylinMC** [comment]
行吧...

**Comment by CKylinMC** [comment]
Preview v1.12.1
内容包: e7dada4

Preview v1.12.1
内容包: d845e2c

解决了。。。我点了删除缓存。。。但是我发现每次删除缓存，这个内容包版本号都不一样，这是正常的吗？

**Comment by the1812** [comment]
内容包的计算应该也有点问题(
不过按理来说新代码会直接覆盖掉旧缓存的

**Comment by CKylinMC** [comment]
> 内容包的计算应该也有点问题(
> 不过按理来说新代码会直接覆盖掉旧缓存的

更奇怪的。
我刚刚又点了一下删除缓存，然后内容包版本号又改变了。ba0f77d
然后问题又回来了。

于是我直接跑了一个`bilibiliEvolved.settings.cache = {}`然后刷新，又好了。2d1e97d
（但是一刷新就又回去了。）

而且每次出现问题的时候，我发现都是同一个问题，那条宽度100%规则有但是缺少一个分号。
![image](https://user-images.githubusercontent.com/11648014/110753706-dae89600-8281-11eb-8145-050d152525be.png)

**Comment by the1812** [comment]
你的热更新源是哪个?
看起来像是你又把旧代码下回去了 (那个缺分号跟偏移没关系, 是完全少了一条规则)
![image](https://user-images.githubusercontent.com/26504152/110754006-3fa3f080-8282-11eb-9e17-1bd19ed80056.png)

**Comment by CKylinMC** [comment]
安装是从这个链接安装：

![image](https://user-images.githubusercontent.com/11648014/110754483-d96b9d80-8282-11eb-824f-9268af9564cb.png)

设置中是jsDelivr的源：

![image](https://user-images.githubusercontent.com/11648014/110754542-eab4aa00-8282-11eb-97ed-9c2f5509bec2.png)

**Comment by the1812** [comment]
我也是 jsDelivr 啊
你手动下一个更新包看看? 我下载解压出来也是新代码
https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@preview/min/bundle.zip

**Comment by CKylinMC** [comment]
[bundle.zip](https://github.com/the1812/Bilibili-Evolved/files/6121706/bundle.zip)
@the1812

**Comment by the1812** [comment]
这么魔幻? 同一个链接都能下到不同的文件?
![image](https://user-images.githubusercontent.com/26504152/110762005-513dc600-828b-11eb-9940-4d7f49267495.png)

**Comment by the1812** [comment]
这么魔幻? 同一个链接都能下到不同的文件?
![image](https://user-images.githubusercontent.com/26504152/110762005-513dc600-828b-11eb-9940-4d7f49267495.png)

**Comment by CKylinMC** [comment]
> 这么魔幻? 同一个链接都能下到不同的文件?
> ![image](https://user-images.githubusercontent.com/26504152/110762005-513dc600-828b-11eb-9940-4d7f49267495.png)

是不是我这边的cdn节点的问题？

**Comment by the1812** [comment]
应该是cdn的问题, 我这边ip跟你不一样
```powershell
ping cdn.jsdelivr.net

正在 Ping cdn.jsdelivr.net.mwcloudcdn.com [2409:8c30:1000:901::2a] 具有 32 字节的数据:
来自 2409:8c30:1000:901::2a 的回复: 时间=15ms
来自 2409:8c30:1000:901::2a 的回复: 时间=15ms
来自 2409:8c30:1000:901::2a 的回复: 时间=15ms
来自 2409:8c30:1000:901::2a 的回复: 时间=15ms

2409:8c30:1000:901::2a 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 15ms，最长 = 15ms，平均 = 15ms

ping cdn.jsdelivr.net -4

正在 Ping cdn.jsdelivr.net.mwcloudcdn.com [117.149.154.85] 具有 32 字节的数据:
来自 117.149.154.85 的回复: 字节=32 时间=7ms TTL=58
来自 117.149.154.85 的回复: 字节=32 时间=8ms TTL=58
来自 117.149.154.85 的回复: 字节=32 时间=8ms TTL=58
来自 117.149.154.85 的回复: 字节=32 时间=8ms TTL=58

117.149.154.85 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 7ms，最长 = 8ms，平均 = 7ms
```

**Comment by CKylinMC** [comment]
> 应该是cdn的问题, 我这边ip跟你不一样

CDN的话不同地区IP不一样倒是正常，主要是这个刷新延迟就挺感人，我发现问题到今天肯定超过24h了。
