### ISSUE TITLE
视频卡在加载界面

### ISSUE THREAD

**Issue by miria0** [the1812/Bilibili-Evolved#163]
**关于哪一项功能**
默认 初始

**问题描述**
打开B站某个视频，有时候无法播放。一直卡住，然后回到了。flash模式，只能刷新才有一定的几率播放视频。但是大部分都是会卡住。一直刷新，或者等个几分钟自然好！

**脚本版本**
1.8.14

**浏览器版本**
谷歌 76.0.3809.100

**错误信息**

**附加截图**
https://s2.ax1x.com/2019/08/15/mAgYHH.png

**Comment by the1812** [comment]
我最近也遇到这个问题, 只能确定是视频分类下的某个功能导致的, 因为全关了就没事了.
我这几天会逐个尝试的, 按照图里的设置目前没有问题.
<img height="400" src="https://user-images.githubusercontent.com/26504152/63070953-c6ca9e80-bf4f-11e9-88f4-3aa67993cc12.png">

**Comment by Coulomb-G** [comment]
可查看[反馈论坛](http://link.acg.tv/forum.php?mod=viewthread&tid=24261&extra=page%3D1)相关讨论
近期不少网友反馈过网页播放器加载失败,目前的解决方法:User-Agent更改为Firefox on Windows或者Chrome on Ubuntu
也可以通过打开开发者工具disable cache解决此问题

**Comment by Tcloser** [comment]
呃呃..ubuntu用户表示确实没啥问题

**Comment by the1812** [comment]
听说b站已经修复这个问题了, 最近几天应该都正常了

**Comment by miria0** [comment]
更新后又出现了这个问题。
1：有一定几率屏幕卡死声音还在，画面不动。
2：有一定的几率会加载。
这是更新了1.91版本后就这样了。
之前解决这个问题，是我把谷歌游览器删了。换成了百分游览器（用谷歌的可以尝试用百分游览器，因为百分的接口是谷歌的，可以用谷歌账号登录，谷歌游览器的基本功能都在）

**Comment by cooper1x** [comment]
我这也出现了这个问题
