### ISSUE TITLE
页面顶部一片空白的现象

### ISSUE THREAD

**Issue by echozuilaoxian** [the1812/Bilibili-Evolved#1630]
**关于哪一项功能**
页面顶部空白

**问题描述**

所有页面

**脚本版本**

v1.12.1

**浏览器版本**

360安全浏览器
user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

**错误信息**

不知道其他浏览器是不是也这样

**附加截图**

![20210310122508196](https://user-images.githubusercontent.com/61530237/110576648-1446d600-819c-11eb-8756-c25b22ae6c6c.jpg)
![360截图20210310122820835](https://user-images.githubusercontent.com/61530237/110576704-27f23c80-819c-11eb-8b05-c6f273064ac4.jpg)

**Comment by Geeyun-JY3** [comment]
善 用 搜 索：https://github.com/the1812/Bilibili-Evolved/issues/1225#issuecomment-731571923
