### ISSUE TITLE
请问支持批量下载吗

### ISSUE THREAD

**Issue by lyjhyjyes** [the1812/Bilibili-Evolved#1632]
比如我关注了一个up主，想下载全部视频，但并非播单内，请问如何批量下载
已经用了好几年该牛逼脚本，之前都是单独下载，最近需要批量下载

**Comment by the1812** [comment]
随便开个视频下载, 里面切到手动下载一栏, 把 av 号填进去
(不过同一up主的全部av号就得你自己想办法了
