### ISSUE TITLE
脚本显示英文无法更改，并且脚本不生效是什么问题

### ISSUE THREAD

**Issue by fenglingzhuye** [the1812/Bilibili-Evolved#1637]
![image](https://user-images.githubusercontent.com/80513122/110914540-785ecb00-8351-11eb-941e-58edb8a94c30.png)

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/discussions/1301

**Comment by Geeyun-JY3** [comment]
都感觉可以专门为 360 浏览器用户写几条注意事项了（

**Comment by fenglingzhuye** [comment]
> 都感觉可以专门为 360 浏览器用户写几条注意事项了（

用的是chrome，重装脚本的时候没在GitHub看到注意事项
