### ISSUE TITLE
“aria2 RPC 配置”界面无法关闭

### ISSUE THREAD

**Issue by YogiLiu** [the1812/Bilibili-Evolved#164]
**关于哪一项功能**
aria2 RPC 配置

**问题描述**
~~重现：导出aria2 RPC -> aria2 RPC 配置，此时无法放弃下载，因为“aria2 RPC 配置”界面无法关闭，即便是关闭“下载视频”界面并重新打开，“aria2 RPC 配置”界面依然存在，覆盖“下载视频”界面，需要刷新页面才能使“下载视频”功能恢复正常。~~（[164#issuecomment-522203346](https://github.com/the1812/Bilibili-Evolved/issues/164#issuecomment-522203346)）

两点建议：
1.  “aria2 RPC 配置”的配置项中，主机、端口、密钥、方法属于不常修改的配置项（路径属于常修改配置项），可以放到设置里，不需要在“aria2 RPC 配置”界面中修改。
2. 可否在“aria2 RPC 配置”增加一个max-download-limit（单任务最大下载速度）的配置项，因为速度过快会导致下载失败（16个连接数下载起来跟疯狗一样233）。

**脚本版本**
正式版1.8.14

**浏览器版本**
chrome 版本 76.0.3809.100（正式版本） （64 位）

**附加截图**
![Screenshot_20190817_103046.png](https://i.loli.net/2019/08/17/U8lVByfmera79Yo.png)

**Comment by Coulomb-G** [comment]
关于“aria2 RPC 配置”界面无法关闭的问题,你通过点击「导出aria2 RPC」按钮来关闭配置页面

**Comment by YogiLiu** [comment]
感谢回复，这个细节隐藏得太深了

**Comment by the1812** [comment]
1. RPC目前的配置项还没多到要按是否常用来分开的地步
2. 已添加`max-download-limit`的选项
