### ISSUE TITLE
头像和头框匹配问题

### ISSUE THREAD

**Issue by yitain** [the1812/Bilibili-Evolved#1642]
**关于哪一项功能**
动态页面显示

**问题描述**

**脚本版本**
Offline v959.79

**浏览器版本**
版本 89.0.4389.82（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/49146766/111027474-83445900-8440-11eb-987d-977938b9c9e9.png)

**Comment by Geeyun-JY3** [comment]
预览版修了
