### ISSUE TITLE
快速收藏和外置稍后再看折行

### ISSUE THREAD

**Issue by the1812** [the1812/Bilibili-Evolved#1648]
> 像我这种窄得得要命同时开 `快速收藏` 和 `外置稍后再看` 就算缩文字也还会折行的情况考虑适配吗🌚
![image](https://user-images.githubusercontent.com/49396421/111060089-70c82f00-84d5-11eb-9e1d-2b49b11dbd06.png)

_Originally posted by @Geeyun-JY3 in https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-798848195_

当时做的时候调过这种很窄的情况, 不过三连的数据都不到100, 这种十几万点赞的还是会折行
我得再改改

**Comment by CKylinMC** [comment]
emmm可不可以顺便把投诉和记笔记藏进右边那三个点里，那俩实在用不到，开了快速收藏 和 外置稍后再看之后就算不换行也显得很挤

**Comment by Geeyun-JY3** [comment]
> emmm可不可以顺便把投诉和记笔记藏进右边那三个点里，那俩实在用不到，开了快速收藏 和 外置稍后再看之后就算不换行也显得很挤

和我当初提的一样：https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-738898732

**Comment by the1812** [comment]
你分辨率是多少来着 我这缩到最小都能挤得下
![image](https://user-images.githubusercontent.com/26504152/111574624-cf4c2080-87e7-11eb-8585-86121ed97f2a.png)

**Comment by Geeyun-JY3** [comment]
浏览器 Chrome 缩放 100%
![image](https://user-images.githubusercontent.com/49396421/111577558-767f8680-87ed-11eb-980c-8cd0629f17be.png)

**Comment by the1812** [comment]
1080p 除去 150% 缩放也有 1280x720 啊
你那个那么窄是怎么做到的
![image](https://user-images.githubusercontent.com/26504152/111578935-fd356300-87ef-11eb-8749-2a67c1750fbd.png)

**Comment by Geeyun-JY3** [comment]
> 1080p 除去 150% 缩放也有 1280x720 啊
> 你那个那么窄是怎么做到的

那我就真的不知道了🤣

**Comment by the1812** [comment]
写了些间距更紧缩的代码, 总不能还折行吧
(图里是我能调出的最窄的样子了
![image](https://user-images.githubusercontent.com/26504152/111764885-ad819500-88de-11eb-9bee-d1476d83bc41.png)

**Comment by Geeyun-JY3** [comment]
用新宝岛来做个极限挑战<img src="https://i0.hdslb.com/bfs/emote/bba7c12aa51fed0199c241465560dfc2714c593e.png" width="20" height="20" alt="doge">（
折行倒是不折了，倒是有文字重叠了<img src="https://i0.hdslb.com/bfs/emote/bba7c12aa51fed0199c241465560dfc2714c593e.png" width="20" height="20" alt="doge">
![image](https://user-images.githubusercontent.com/49396421/111766342-65fc0880-88e0-11eb-83f8-eb2fd75c9be6.png)

**Comment by the1812** [comment]
这个我就不管了, 等着把右边那几个收起来的功能吧
