### ISSUE TITLE
自动定位到播放器功能与默认播放器状态冲突

### ISSUE THREAD

**Issue by sadkmoon** [the1812/Bilibili-Evolved#1649]
当默认播放器状态为宽屏时,使用自动定位功能,有时会出现下面这种情况
![X$R6JHRH}AXJY$1`VF6UXN6](https://user-images.githubusercontent.com/53417811/111068907-9bca7700-8505-11eb-9f02-8f69bf05315d.png)
试了好多次 是因为先后顺序导致的
得要是先运行宽屏才能定位到自己想要的位置
如果先定位的话,就只是宽屏的位置了
所以能给他排个次序吗  让宽屏先

**Comment by the1812** [comment]
#483
