### ISSUE TITLE
直播间播放器界面的全区广播希望能屏蔽掉

### ISSUE THREAD

**Issue by ZOMBIE39** [the1812/Bilibili-Evolved#165]
印象中好像之前是屏蔽掉的 但是现在又有了 估计是页面代码变了之类的 现在开启屏蔽全区广播只有弹幕区那边的广播会消失 播放器上面的滚动广播还是会有

**Comment by Coulomb-G** [comment]
有截图吗?是哪种样式的滚动广播,或者方便的话,可以提供一下选择器么

**Comment by ZOMBIE39** [comment]
![QQ截图20190819191657](https://user-images.githubusercontent.com/37724369/63287259-e4538b80-c2f4-11e9-9bbf-dcc87de12080.png)
没注意看 折騰了好久 才發現上傳圖片的地方就在文本框下面 = =
至於選擇器 這個 隨便在一個直播間用審查元素應該就能看到吧

**Comment by ZOMBIE39** [comment]
![QQ截图20190820033440](https://user-images.githubusercontent.com/37724369/63290040-89716280-c2fb-11e9-9410-0c6680d1c0d1.png)
選中的那一行代碼就是滾動廣播的

**Comment by ZOMBIE39** [comment]
> 有截图吗?是哪种样式的滚动广播,或者方便的话,可以提供一下选择器么

咦 回復在這裡面嗎 。。。。。 github用太少

**Comment by the1812** [comment]
我总算是抓到选择器了... 你那张图里广播已经结束了只有个外层容器
