### ISSUE TITLE
动态页面视频果冻效果

### ISSUE THREAD

**Issue by FoundTheWOUT** [the1812/Bilibili-Evolved#1651]
**问题描述**

动态页面, video-container(类名), 有比较严重的果冻效果(?maybe).

https://user-images.githubusercontent.com/47922588/111161334-02b76100-85d6-11eb-9b3e-3ddc9edc50e9.mov

**脚本版本**

1.12.0 && 1.12.1

**浏览器版本**
chrome 89

**Comment by the1812** [comment]
你是 macOS 吗

**Comment by FoundTheWOUT** [comment]
> 你是 macOS 吗

是, emm? 这是个在macOS里才有的问题?

**Comment by the1812** [comment]
换个浏览器试试, 我觉得可能是 mac 版的 Chrome 不对劲

**Comment by FoundTheWOUT** [comment]
看来mac上chromuim基浏览器都有这个问题.
现在测试了Edge, Firefox. Edge问题一摸一样, Firefox是没问题的, 估计safari也是没问题的, 不过没测试, 这玩意上的Tampermonkey要收费.
