### ISSUE TITLE
鼠标悬停在弹幕上无法正常点赞

### ISSUE THREAD

**Issue by TRasdzz** [the1812/Bilibili-Evolved#1655]
**关于哪一项功能**
无法点赞弹幕

**问题描述**

随便点开一个视频都可以

**脚本版本**

v1.12.0

**浏览器版本**

版本 88.0.4324.182（正式版本） （64 位

**错误信息**

无错误信息 知识建议哦
如果是哪一项功能可打开点赞或者关闭  烦请告知  我已经仔仔细细看了几遍功能 好像没有这个  
如果可以  做成一个接口  有时候看到出彩的弹幕实在无法忍受不能给他点个赞   
**附加截图**

**Comment by CKylinMC** [comment]
见 https://github.com/the1812/Bilibili-Evolved/issues/966#issuecomment-702522679

**Comment by TRasdzz** [comment]
那好吧   谢谢解答了

**Comment by Geeyun-JY3** [comment]
@the1812 感觉得想办法或者写清楚不支持弹幕点赞

**Comment by TRasdzz** [comment]
不如做一个接口 直接一键屏蔽所有功能  然后点个赞  然后再打开

**Comment by TRasdzz** [comment]
虽然把插件关闭 刷新网页 点赞 再打开插件 刷新网页 可以做到  但总之来说还是很麻烦的

**Comment by the1812** [comment]
很多功能关闭都是要刷新后生效的
总之, 要用这脚本, 你就当没有弹幕点赞这种功能的存在好了
