### ISSUE TITLE
自定义顶栏的头像格式问题

### ISSUE THREAD

**Issue by LonelySteve** [the1812/Bilibili-Evolved#1658]
**关于哪一项功能**

自定义顶栏

**问题描述**

启用自定义顶栏功能，确保个人头像上传格式为 webp，并具有透明区域

**脚本版本**

Preview v1.12.1

**浏览器版本**

Chrome 89.0.4389.82

**附加截图**

![image](https://user-images.githubusercontent.com/34429322/111579209-949ab600-87f0-11eb-8d6d-ac4786da6bfd.png)
![image](https://user-images.githubusercontent.com/34429322/111579265-af6d2a80-87f0-11eb-9c84-7a10aa63b0e0.png)

**期望的效果**

![image](https://user-images.githubusercontent.com/34429322/111579451-007d1e80-87f1-11eb-896e-3c07a0ab3e20.png)

**Comment by the1812** [comment]
说起来 webp 是不是可以传动图上去

**Comment by LonelySteve** [comment]
是的，远古时期还能直接上传 gif 格式呢，现在 webp 都不一定能上传了
