### ISSUE TITLE
无法回复楼层，但可回复楼中楼

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1659]
**关于哪一项功能**
就是排查不出来

**问题描述**
遇到个很奇怪的 bug，无法回复楼层（点击回复后无回复框出现），但可回复楼中楼。刷新页面后该 bug 有一定概率消失。可以确定的是和某个功能有关。
附设置项：[bilibili-evolved-settings.zip](https://github.com/the1812/Bilibili-Evolved/files/6164115/bilibili-evolved-settings.zip)

**脚本版本**
正式版 v1.11.12
预览离线版 v970.18

**浏览器版本**
百分浏览器 4.3.9.248（正式版本） （64 位） (Chromium 86.0.4240.198)
Chrome 89.0.4389.90（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by JimmyJLNU** [comment]
我也发现了，而且点赞也有问题，一次性点两个赞，刷新页面后恢复正常数目。

**Comment by Dragon1573** [comment]
# 关联功能

**未知**

# 问题描述

与 https://github.com/the1812/Bilibili-Evolved/issues/1659#issue-834764865 和 https://github.com/the1812/Bilibili-Evolved/issues/1659#issuecomment-803356089 的描述相同。

# 脚本版本

- Stable v1.12.4 (正式版)
- 内容包：a0efeb1
- UUID：1725df76-b00c-41a9-aa31-1de9d54d4f7a
- 设置文件：[bilibili-evolved-settings.json](https://github.com/the1812/Bilibili-Evolved/files/6283712/bilibili-evolved-settings.json.txt)

# 浏览器版本

- Microsoft Edge (Chromium)
  - 版本号：89.0.774.68 (官方内部版本)
  - 架构：64位
- TamperMonkey
  - 版本号：4.11.6120
  - 下载来源：[Microsoft Store](https://microsoftedge.microsoft.com/addons/detail/tampermonkey/iikmkjmpaadaobahmlepeloendndfphd)

**Comment by Dragon1573** [comment]
脚本内容包更新至 04f3af7 ，再次出现以上问题。

**Comment by the1812** [comment]
还没修, 我也只是遇到过, 定位不了原因

**Comment by Geeyun-JY3** [comment]
今天已无法复现该 bug🌚

**Comment by Geeyun-JY3** [comment]
既然已无法复现那我关了🌚
