### ISSUE TITLE
视频系列界面夜间模式未覆盖

### ISSUE THREAD

**Issue by 1421356447** [the1812/Bilibili-Evolved#1663]
**关于哪一项功能**
视频系列界面夜间模式未覆盖

**问题描述**
av374679570
视频右侧显示系列的界面没有夜间模式

**脚本版本**
Stable v1.12.0
内容包: 209a63f

**浏览器版本**
chrome 版本 89.0.4389.90（正式版本） （64 位）

**错误信息**
未显示错误信息

**附加截图**
![image](https://user-images.githubusercontent.com/30023789/111727506-5a8fe980-88ae-11eb-8baa-cb876c87d86f.png)

**Comment by LonelySteve** [comment]
最新预览版已修

**Comment by LonelySteve** [comment]
最新预览版已修

**Comment by Geeyun-JY3** [comment]
重复：#1626

**Comment by Geeyun-JY3** [comment]
@the1812 要不在 New issue 页面加个指向 Release 的提示吧。感觉放在 Issues 须知里还是太深了
