### ISSUE TITLE
深色模式下评论区页码显示不正常

### ISSUE THREAD

**Issue by cmmdwl** [the1812/Bilibili-Evolved#1667]
![image](https://user-images.githubusercontent.com/21263352/111785269-5805b200-88f7-11eb-8c48-cfa49fd2b1e9.png)

给当前页面上个颜色吧,加粗部分大果粒屏幕看不见

**附加截图**
![image](https://user-images.githubusercontent.com/21263352/111785370-7bc8f800-88f7-11eb-8ca4-f71de4b2835c.png)

**Comment by Geeyun-JY3** [comment]
重复：#1605，不过确实应该是 bug 应该开 issue

**Comment by cmmdwl** [comment]
我就是看到你们说是bug才开的iss,看没人在这开我就顺手开了
