### ISSUE TITLE
自定义快捷键扩展问题

### ISSUE THREAD

**Issue by sunfkny** [the1812/Bilibili-Evolved#1668]
**关于哪一项功能**
快捷键扩展

**问题描述**

按照 [key-bindings.md](https://github.com/the1812/Bilibili-Evolved/blob/preview/src/video/keymap/key-bindings.md) 内的说明，留空表示永远不会触发  
但是我自定义某个动作为空字符串`''`或者空格`' '`时，按下笔记本键盘<kbd>Fn</kbd>键时错误触发  

**脚本版本**

Preview v1.12.2

**浏览器版本**

Google Chrome 已是最新版本
版本 89.0.4389.90（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by sunfkny** [comment]
顺便说一下，按下<kbd>Fn</kbd>键时
```
document.onkeydown=function(e){
  console.log(e.keyCode);
}; 
```
获取到的keyCode是237

**Comment by the1812** [comment]
打印下`e`本身看看? 我按 <kbd>Fn</kbd> 怎么得到的是 Alt
![image](https://user-images.githubusercontent.com/26504152/112265829-19347b00-8cae-11eb-93cf-eff0433f71be.png)

**Comment by sunfkny** [comment]
![QQ截图20210324143713](https://user-images.githubusercontent.com/30853461/112266054-78928b00-8cae-11eb-85ed-1fc0b570de56.png)

**Comment by the1812** [comment]
这个居然正好是空按键...
