### ISSUE TITLE
aria2c rpc 导出 http 请求被浏览器拦截

### ISSUE THREAD

**Issue by SeraphJACK** [the1812/Bilibili-Evolved#167]
**关于哪一项功能**

aria2c jsonrpc

**问题描述**

bilibili 是用 https 加载的，而 jsonrpc 是 http 协议，请求会被浏览器拦截。

**脚本版本**

正式版 1.8.14

**浏览器版本**

Chrome 76.0.3809.100

**错误信息**

```
Mixed Content: The page at 'https://...' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://...'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by SeraphJACK** [comment]
也许可以通过创建新页面发送请求的方式解决？

**Comment by the1812** [comment]
Console里会留下那个请求的链接, 你可以点开来创建新页面. 创建新页面确实能发过去, 不过那个页面还会弹一个下载, 内容是aria2对这个请求的响应JSON.
因为每一次请求都会弹下载我当时就没有设为创建新页面.

**Comment by SeraphJACK** [comment]
> hmm... 
- 但普通用户不会看 console 的，我也是突然想起来 http 请求会被拦截打开 console 才看到的。
- 也许可以插件内置一个页面，然后从页面里的脚本发送请求之后再关掉呢？

**Comment by the1812** [comment]
刚试了下, 一样Mixed Content.
![image](https://user-images.githubusercontent.com/26504152/63652592-af33b700-c794-11e9-8224-b1e08d2850c8.png)
![image](https://user-images.githubusercontent.com/26504152/63652608-be1a6980-c794-11e9-967c-e8ef48849196.png)

**Comment by SeraphJACK** [comment]
不，是指插件创建一个独立页面，比如 `chrome-extensions://foo/bar.html`
~~不过我没写过 Chrome 插件，不知道可不可行~~

**Comment by the1812** [comment]
我这只是个脚本, 不是插件, 插件是脚本管理器Tampermonkey或Violentmonkey.

**Comment by SeraphJACK** [comment]
~~Help-Wanted~~ @Yesterday17

**Comment by Yesterday17** [comment]
用 window.open 呢

**Comment by the1812** [comment]
`window.open`就跟最上面说的创建新页面一样了

**Comment by Yesterday17** [comment]
@the1812 我的意思是在windows.open出来的窗口发完xhr之后再close

**Comment by the1812** [comment]
哦哦 这样应该可以 我明天试一下

**Comment by the1812** [comment]
即使是`window.open`打开的新窗口, 看来也依然受到了原页面的限制...

```html
<html><body><script>fetch('http://xxx.....').then(() => window.close())</script></body></html>
```
![image](https://user-images.githubusercontent.com/26504152/63660694-2f383c00-c7ea-11e9-9e8c-76227cf18e12.png)

**Comment by SeraphJACK** [comment]
要不干脆弄个静态页面丢 GitHub Pages 上...

**Comment by Yesterday17** [comment]
![image](https://user-images.githubusercontent.com/8667822/63663613-ac1ce300-c7f5-11e9-88ff-9f9f56e90dc2.png)
~~这一节英语课我到底干了什么~~

**Comment by Yesterday17** [comment]
![image](https://user-images.githubusercontent.com/8667822/63663660-dff80880-c7f5-11e9-987e-fd9a0aeebfbe.png)
还有这个(

**Comment by Yesterday17** [comment]
由此衍生出来的思路是可以指定某一个原来肯定没有的页面（比如 api.bilibili.com/bilibili-evolved/settings 做专门的设置页面之类的

**Comment by the1812** [comment]
postMessage好像没什么反应...

脚本添加:
```JavaScript
if (document.URL === 'http://api.bilibili.com/1') {
  window.addEventListener('message', e => {
    console.log(e)
    fetch(e.data)
  })
}
```
原页面:
```JavaScript
let w = window.open('','','autoHideMenuBar=1')
w.window.location.href='http://api.bilibili.com/1'
w.postMessage(`http://xxx.....`)
```

**Comment by Yesterday17** [comment]
@the1812 好像要 `w.postMessage('http://xxx...', '*')` 指定 targetOrigin 为 * （或者其他）

**Comment by HCLonely** [comment]
用GM_xmlhttpRequest不行吗

**Comment by the1812** [comment]
`GM_xmlhttpRequest`试验成功了, 下次更新将解决这个问题, 感谢大家的帮助\_(:3」∠)\_
