### ISSUE TITLE
夜间模式吃图片背景

### ISSUE THREAD

**Issue by cmmdwl** [the1812/Bilibili-Evolved#1677]
纯白背景变全灰
![image](https://user-images.githubusercontent.com/21263352/112471143-7d3a6a80-8da6-11eb-9f9b-c57c151bf78d.png)

**Comment by the1812** [comment]
这本来就是透明背景的图

**Comment by cmmdwl** [comment]
> 这本来就是透明背景的图

有办法给图片背后自动生成一个白色背景么？

**Comment by the1812** [comment]
夜间模式就是去除大片的白色背景的功能, 想看清这张图可以暂时关闭夜间模式, 或者在上面右键新标签页打开
