### ISSUE TITLE
记笔记的编辑器，夜间模式适配现已失效

### ISSUE THREAD

**Issue by LonelySteve** [the1812/Bilibili-Evolved#1680]
**关于哪一项功能**

夜间模式

曾在 e221888e21f08cd05ac2aa091c320f465699fa9b 中进行完成适配

**脚本版本**

Preview v1.12.2
 
**附加截图**

![image](https://user-images.githubusercontent.com/34429322/112593930-26cf3980-8e43-11eb-98fb-e2d502fd6fd6.png)

**Comment by the1812** [comment]
可能容器的class变了？

**Comment by LonelySteve** [comment]
> 可能容器的class变了？

应该是，内部的元素的 class 好像基本没变

**Comment by the1812** [comment]
已修, 顺便把配色调深了一些

**Comment by LonelySteve** [comment]
OK
