### ISSUE TITLE
首页无法查看番剧更新和专栏

### ISSUE THREAD

**Issue by 1421356447** [the1812/Bilibili-Evolved#1682]
**关于哪一项功能**
首页无法查看番剧更新和专栏

**问题描述**
首页动态界面无法加载番剧和专栏更新

**脚本版本**
Stable v1.12.2
内容包: e296008

**浏览器版本**
版本 89.0.4389.90（正式版本） （64 位）

**错误信息**
加载番剧动态失败, error = TypeError: Cannot read property 'title' of undefined
logError @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210
fetchData @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210
async function (async)
fetchData @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210
mounted @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2019
callHook @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4370
insert @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:3302
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2019
invoker @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2340
invokeInsertHook @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:6491
patch @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:6708
Vue._update @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4099
updateComponent @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4217
get @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4628
run @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4703
flushSchedulerQueue @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4461
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2145
flushCallbacks @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2071
Promise.then (async)
timerFunc @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2098
nextTick @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2155
queueWatcher @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4553
update @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4693
Vue.$forceUpdate @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4120
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8979
wrappedHook @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2400
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2019
invoker @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2340
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8476
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:507
end @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8176
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8187
(anonymous) @ VM1526:3
E.z.<computed> @ VM1552:43
setTimeout (async)
(anonymous) @ VM1526:3
H.<computed> @ VM1526:9
(anonymous) @ VM1526:3
E @ VM1552:43
enhance @ VM1552:56
whenTransitionEnds @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8185
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8508
sentryWrapped @ sentry-5.7.1.min.js:2
requestAnimationFrame (async)
(anonymous) @ sentry-5.7.1.min.js:2
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8143
sentryWrapped @ sentry-5.7.1.min.js:2
requestAnimationFrame (async)
(anonymous) @ sentry-5.7.1.min.js:2
nextFrame @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8142
performLeave @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8500
leave @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8484
remove$$1 @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8577
removeAndInvokeRemoveHook @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:6300
removeVnodes @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:6274
patch @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:6701
Vue._update @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4099
updateComponent @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4217
get @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4628
run @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4703
flushSchedulerQueue @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4461
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2145
flushCallbacks @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2071
Promise.then (async)
timerFunc @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2098
nextTick @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2155
queueWatcher @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4553
update @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4693
notify @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:901
reactiveSetter @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:1226
proxySetter @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4780
update:tab @ VM1939:3
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2019
invoker @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2344
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2019
Vue.$emit @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4039
changeTab @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210
click @ VM1947:3
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2019
invoker @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2344
original._wrapper @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:7697
sentryWrapped @ sentry-5.7.1.min.js:2
userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210 infinite scroll
userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210 [IntersectionObserverEntry]
userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210 disconnect
userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210 destroy
userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210 加载专栏动态失败, error = TypeError: Cannot read property 'name' of undefined

加载番剧动态失败, error = TypeError: Cannot read property 'title' of undefined
logError @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210
fetchData @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210
async function (async)
fetchData @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210
mounted @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2019
callHook @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4370
insert @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:3302
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2019
invoker @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2340
invokeInsertHook @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:6491
patch @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:6708
Vue._update @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4099
updateComponent @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4217
get @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4628
run @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4703
flushSchedulerQueue @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4461
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2145
flushCallbacks @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2071
Promise.then (async)
timerFunc @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2098
nextTick @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2155
queueWatcher @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4553
update @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4693
Vue.$forceUpdate @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4120
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8979
wrappedHook @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2400
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2019
invoker @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2340
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8476
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:507
end @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8176
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8187
(anonymous) @ VM1526:3
E.z.<computed> @ VM1552:43
setTimeout (async)
(anonymous) @ VM1526:3
H.<computed> @ VM1526:9
(anonymous) @ VM1526:3
E @ VM1552:43
enhance @ VM1552:56
whenTransitionEnds @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8185
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8508
sentryWrapped @ sentry-5.7.1.min.js:2
requestAnimationFrame (async)
(anonymous) @ sentry-5.7.1.min.js:2
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8143
sentryWrapped @ sentry-5.7.1.min.js:2
requestAnimationFrame (async)
(anonymous) @ sentry-5.7.1.min.js:2
nextFrame @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8142
performLeave @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8500
leave @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8484
remove$$1 @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:8577
removeAndInvokeRemoveHook @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:6300
removeVnodes @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:6274
patch @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:6701
Vue._update @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4099
updateComponent @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4217
get @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4628
run @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4703
flushSchedulerQueue @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4461
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2145
flushCallbacks @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2071
Promise.then (async)
timerFunc @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2098
nextTick @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2155
queueWatcher @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4553
update @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4693
notify @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:901
reactiveSetter @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:1226
proxySetter @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4780
update:tab @ VM1939:3
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2019
invoker @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2344
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2019
Vue.$emit @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:4039
changeTab @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210
click @ VM1947:3
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2019
invoker @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:2344
original._wrapper @ userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:7697
sentryWrapped @ sentry-5.7.1.min.js:2
userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210 infinite scroll
userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210 [IntersectionObserverEntry]
userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210 disconnect
userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210 destroy
userscript.html?name=Bilibili%20Evolved.user.js&id=b0bf6b5c-aa90-4a57-b152-4e29a14b0b98:13210 加载专栏动态失败, error = TypeError: Cannot read property 'name' of undefined

**附加截图**
![image](https://user-images.githubusercontent.com/30023789/112602116-a0245780-8e56-11eb-9a21-a15686a449c3.png)
![image](https://user-images.githubusercontent.com/30023789/112602141-a74b6580-8e56-11eb-86da-d34f4873af7f.png)

**Comment by the1812** [comment]
大概是里面有什么比较特殊的番剧? 脚本取标题的时候失败了

**Comment by the1812** [comment]
好像是预订了啥视频后, 这个视频在查询时无论是番剧还是专栏动态里都会出现, 可能之后会在网页版动态里有啥特殊显示用, 不过不按照类型过滤就很离谱...

**Comment by 15948707537** [comment]
预约视频之后这个功能就废掉了，而预约视频没法取消，这怎么搞。。。

**Comment by the1812** [comment]
过几天我会修复
