### ISSUE TITLE
动态页有新广告了

### ISSUE THREAD

**Issue by the1812** [the1812/Bilibili-Evolved#1683]
![image](https://user-images.githubusercontent.com/26504152/112660630-9ddeef00-8e90-11eb-9d73-07d5bfaa6aec.png)

预览版`删除广告`功能已适配.

**Comment by RtYkk** [comment]
草，居然是今天新加的吗，就说之前从来没注意过有。刚准备来 issue 区看有没有人提过了……结果正好在第一个
