### ISSUE TITLE
特定搞活动直播间，简化等功能失效

### ISSUE THREAD

**Issue by oscarwty** [the1812/Bilibili-Evolved#1685]
比如说【路理Kuri】今日的出道直播，现在还在播
个人空间：https://space.bilibili.com/646432928/
点进直播间：https://live.bilibili.com/22918711
会自动跳转到：https://www.bilibili.com/blackboard/live/activity-2zIFcApkMC.html
无法回到正常直播间页面，该页面因为是blackboard活动页面，无法使用直播间简化等功能
github传图片太慢了我上个图床，可以看到没有直播间判定
[![6zbKIJ.md.png](https://z3.ax1x.com/2021/03/27/6zbKIJ.md.png)](https://imgtu.com/i/6zbKIJ)

**Comment by the1812** [comment]
https://live.bilibili.com/blanc/22918711

**Comment by oscarwty** [comment]
> 
> 
> https://live.bilibili.com/blanc/22918711

好的，非常感谢，学会了
