### ISSUE TITLE
视频合集处的夜间模式不正常

### ISSUE THREAD

**Issue by isolitude** [the1812/Bilibili-Evolved#1687]
**关于哪一项功能**
夜间模式

**问题描述**

对于有合集的视频，合集处是白色的
https://www.bilibili.com/video/BV12t4y1z7p8
https://www.bilibili.com/video/BV1FX4y1G7aM

**脚本版本**

1.12.0

**浏览器版本**

 chrome  89.0.4389.90

**错误信息**

**附加截图**
![屏幕截图 2021-03-28 234345.jpg](https://i.loli.net/2021/03/28/F1s9Vr4zivH2l6Y.jpg)

**Comment by Geeyun-JY3** [comment]
累了：#1626，#1663

下次开 issue 前请先试试预览版
