### ISSUE TITLE
希望添加两个小功能

### ISSUE THREAD

**Issue by HCLonely** [the1812/Bilibili-Evolved#169]
**关于哪一项功能**
1.双击全屏；
2.全屏时鼠标移动到破播放器顶部时显示视频标题

**期望的效果**
1.双击播放器全屏，全屏时双击则退出全屏；
2.如下图，选择器：`.bilibili-player-video-top`
![image](https://user-images.githubusercontent.com/26346802/63685361-b0ff8800-c831-11e9-8c28-143bb522024c.png)

**脚本版本**
预览版

**Comment by the1812** [comment]
第2个不是本来就有的吗, 除非开了`删除视频标题层`

**Comment by HCLonely** [comment]
> 第2个不是本来就有的吗, 除非开了`删除视频标题层`

哦哦，原来是开了这个啊，功能太多了没注意到😂😂😂

**Comment by the1812** [comment]
双击全屏有两种实现:
1. 双击时屏蔽单击(暂停), 但是会导致暂停功能延迟0.2s运行 (0.2s内两次单击算作一次双击)
2. 双击时不屏蔽单击, 但是双击过程中会看到视频`播放→暂停→播放` (或`暂停→播放→暂停`)

你更喜欢哪一种呢?

**Comment by HCLonely** [comment]
> 双击全屏有两种实现:
> 
> 1. 双击时屏蔽单击(暂停), 但是会导致暂停功能延迟0.2s运行 (0.2s内两次单击算作一次双击)
> 2. 双击时不屏蔽单击, 但是双击过程中会看到视频`播放→暂停→播放` (或`暂停→播放→暂停`)
> 
> 你更喜欢哪一种呢?

第二种吧
