### ISSUE TITLE
[Feature Request] 功能选择提示文字的 toast 收起面板后自动消失

### ISSUE THREAD

**Issue by RtYkk** [the1812/Bilibili-Evolved#1690]
**关于哪一项功能**

**问题描述**

https://live.bilibili.com/545342
1、直播页面
2、点击左侧齿轮
3、光标随便浮动在功能上，弹出 toast
4、移走光标
5、toast 不消失，甚至关闭设置页面再次打开仍会保留上次的 toast

**脚本版本**

Preview v1.12.2 内容包: eced64b
Preview v1.12.3 内容包: 1e92fa3

**浏览器版本**

Google Chrome 版本 89.0.4389.90（正式版本） （64 位）
Microsoft Edge 版本 89.0.774.63 (官方内部版本) (64 位)

**错误信息**

不好意思好像没看到有相关的 log

**附加截图**
![msedge_FUEszP1x3i](https://user-images.githubusercontent.com/45971730/112991317-8e65eb80-9199-11eb-8a66-b86bd0c6f4af.png)
我总记得这个本来是会自动消失的，但是我不太确定，如果我汇报了错误的 bug，那不好意思。
我已经关闭所有其它同页面可能产生影响的脚本。

**Comment by the1812** [comment]
正常来说是会自动消失的, 可能跟 #1469 有点联系?
要不你在那个上面审查元素截图看看
![image](https://user-images.githubusercontent.com/26504152/113085884-3a97e880-9213-11eb-81f3-82f5bd15ce04.png)

**Comment by RtYkk** [comment]
是的。
![msedge_fThDN1wBzK](https://user-images.githubusercontent.com/45971730/113086966-4684aa00-9215-11eb-9e12-30d627f1c939.png)

**Comment by the1812** [comment]
看起来挺正常.. 再选中这里截一下样式代码看看?
![image](https://user-images.githubusercontent.com/26504152/113120405-24565080-9244-11eb-950e-d98d8e1056b6.png)

**Comment by the1812** [comment]
可能是我之前理解错了? 这个设置面板关闭的话, 是不是能够消失掉?
目前的设定是: 鼠标经过功能时显示说明(也就是你说的 toast), 这个说明除非选择别的功能否则不会更改, 是为了方便选中复制里面的文字以及页面高度不足时进行滚动, 但关闭设置面板后也会跟着隐藏掉的.
以前这些说明的内容比较简略就是无法选中且自动消失的.

**Comment by RtYkk** [comment]
如果这样是正常的，那抱歉……

**Comment by the1812** [comment]
是正常的, 如果你觉得很怪的话, 我可以让面板收起的时候消除这个 toast

**Comment by RtYkk** [comment]
我的个人意见是这样会合理一点，因为再次打开的时候如果还在，还停留在上次的操作，确实有一点奇怪。
