### ISSUE TITLE
评论区不能回复层主

### ISSUE THREAD

**Issue by lsh1215225** [the1812/Bilibili-Evolved#1691]
**问题描述**

评论区点回复层主不能弹出回复框，可以回复层中层

**脚本版本**
正式版1.12.0 

**浏览器版本**
Chrome 89 

![image](https://user-images.githubusercontent.com/20274559/113023467-3d192480-91b8-11eb-9d4e-5f37e118d528.png)
![image](https://user-images.githubusercontent.com/20274559/113023495-44d8c900-91b8-11eb-952e-60e0a93ab624.png)

**Comment by Geeyun-JY3** [comment]
重复：#1659，#1670

下次开 issue 前请先善用搜索。
