### ISSUE TITLE
启动脚本上B站后浏览器奔溃

### ISSUE THREAD

**Issue by 906584305** [the1812/Bilibili-Evolved#1702]
**问题描述**
打开B站后浏览器就奔溃，禁用脚本后恢复正常，没有开启其他脚本。昨天还好好的

**脚本版本**
1.12.0

**浏览器版本**
88.0b6 (64 位)

**附加截图**
![屏幕截图 2021-04-03 112522](https://user-images.githubusercontent.com/32992704/113466882-c444f180-9471-11eb-9fc7-9a9c9c96e947.jpg)

**Comment by Geeyun-JY3** [comment]
建议说说电脑配置

**Comment by 906584305** [comment]
CPU: I7-8750H
GPU: 1050Ti
内存：48GB
系统版本：20H2

**Comment by the1812** [comment]
应该是火狐或者油猴的问题? 你这配置很高了, 我低配试了下火狐也没事

**Comment by 906584305** [comment]
> 
> 
> 应该是火狐或者油猴的问题? 你这配置很高了, 我低配试了下火狐也没事

今天脚本更新到1.12.4。。。
结果莫名其妙就好了诶！！
现在应该没事了。。谢谢
