### ISSUE TITLE
笔记本小分辨率屏幕兼容问题

### ISSUE THREAD

**Issue by fjqingyou** [the1812/Bilibili-Evolved#1703]
**关于哪一项功能**
UI界面兼容。

**问题描述**

因为不支持滚动条。在1280*768分辨率的笔记本上，有一些选项是显示不出来的，它们在屏幕底部的外面。

因为点不到好像功能被阉割了似的，期望添加滚动条支持。

**脚本版本**

1.12.0

**浏览器版本**

Google Chrome 已是最新版本
版本 89.0.4389.114（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
你说的是类似于 #1648 吗？

建议附截图。

**Comment by fjqingyou** [comment]
@Geeyun-JY3  并不是。
真实状态例如截图的这个。。左边的菜单列表按钮中，最后的按钮没在屏幕范围之内。
[然后弹出的二级界面也有些在屏幕范围之外。并且窗口还不能拖拽移动改变位置也不太方便如果方便的话还请添加拖拽移动支持。

因为 github这里上传文件尝试很多次都一直失败。所以截图我放网盘共享了。7天内都能查看！

链接：https://pan.baidu.com/s/1jnv4yeDrWWy7t9tz3dVSHw 
提取码：32m9

**Comment by Geeyun-JY3** [comment]
直接粘贴截图可能有网络条件要求……

**Comment by the1812** [comment]
只是视觉上没有滚动条啊, 一样是能滚轮/触控板滚动的

**Comment by fjqingyou** [comment]
恩，实际测试确实可行！不过还是建议有个滚动条在视觉显示比较好吧？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Grant Howard ***@***.***&gt;
发送时间: 2021年4月3日 21:06
收件人: the1812/Bilibili-Evolved ***@***.***&gt;
抄送: FuLong ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[the1812/Bilibili-Evolved] 笔记本小分辨率屏幕兼容问题 (#1703)





 
只是视觉上没有滚动条啊, 一样是能滚轮/触控板滚动的

**Comment by Geeyun-JY3** [comment]
这个面板放右边再有个滚动条就很怪了……

**Comment by the1812** [comment]
滚动条会占据内容区域的宽度, 很多地方我都去掉了滚动条
等各大浏览器都支持覆盖式的滚动条(类似 Safari 里那种), 我才会加回来

**Comment by fjqingyou** [comment]
客观问题是，用这个插件好久了，要不是偶然用过一次大屏幕的环境，甚至不知道屏幕之外还有东西。


滚动条可以是自动的，默认没有，显示不全时动态显示就行了！推荐是这样的形式！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Geeyun-JY3 ***@***.***&gt;
发送时间: 2021年4月3日 21:12
收件人: the1812/Bilibili-Evolved ***@***.***&gt;
抄送: FuLong ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[the1812/Bilibili-Evolved] 笔记本小分辨率屏幕兼容问题 (#1703)





 
这个面板放右边再有个滚动条就很怪了……

**Comment by Geeyun-JY3** [comment]
不过说起来，设置面板确实搞了两个滚动条
![image](https://user-images.githubusercontent.com/49396421/113479581-7a382c00-94c2-11eb-9c55-7f2e5c44f9e6.png)

**Comment by the1812** [comment]
行吧.. 我给附加功能这加一下
