### ISSUE TITLE
b站把自动连播和自动下一p绑定了，救救孩子

### ISSUE THREAD

**Issue by victorchen304** [the1812/Bilibili-Evolved#1710]

**Comment by the1812** [comment]
我救不了 跟b站反馈去吧

**Comment by Geeyun-JY3** [comment]
重复……
#1634、#1647

**Comment by Geeyun-JY3** [comment]
见：https://github.com/the1812/Bilibili-Evolved/discussions/1634#discussioncomment-593169

**Comment by Mirionr** [comment]
> 我救不了 跟b站反馈去吧

能否考虑设置里增加一个按钮，将原按钮隐藏，多P视频中时自动开启连播，最后一P时自动关闭，非多P视频关闭连播？

**Comment by the1812** [comment]
最近好多提关于这个的, 我就详细说明下:
上面说救不了是指我也不知道怎么切断自动播放推荐视频和自动下一P的绑定 (也就是根源问题
但是能治标的办法大家也提了一些了:
1. https://github.com/the1812/Bilibili-Evolved/discussions/1634#discussioncomment-593169 强制退出灰度, 但看现在的状况很可能最后灰度结束就强制上这个绑定了, 届时这个方法就会失效.
2. @Mirionr (#1742) 提的, 看情况去自动改变开关, 下次预览版更新我可能会写出来试试

如果还有什么想法也欢迎分享下

**Comment by VergilGao** [comment]
原来这个阴间功能现在才公测吗？我作为灰度用户已经被恶心快一年了。

**Comment by the1812** [comment]
(而且是因为 bug 而公测的 https://www.bilibili.com/read/cv10762558

**Comment by yubanmeiqin9048** [comment]
这功能太阴间了，不过好在现在脚本有个传统连播模式，但是在番剧下还是无法像以前那样自动播放下一集
