### ISSUE TITLE
动态页功能“禁止跳转动态详情”间歇性失效，或者需要等待较长时间才会生效

### ISSUE THREAD

**Issue by GalaxySnail** [the1812/Bilibili-Evolved#1720]
## 关于哪一项功能

动态 - 禁止跳转动态详情

## 问题描述

我在今天 (2021-04-09) 发现，开启“禁止跳转动态详情”的情况下，刷新或新标签页内打开[B站动态页](https://t.bilibili.com/)，在动态页任选一个动态，用鼠标划取一段文字后松开、或者单击动态文字，会在新标签页打开这个动态。需要等待短至十数秒、长至一分钟以上甚至数分钟，“禁止跳转动态详情”才会正常生效。

在此前（昨天）没有注意到这个问题，推测可能是B站更新所致。

## 脚本版本

Preview v1.12.4, 内容包: cced86b

## 浏览器版本

Windows10 20H2 64bit
Chromium 87.0.4280.66 64bit （从[Woolyss](https://chromium.woolyss.com/)下载的Installer版本）

## 错误信息

在刚刷新/打开动态页时，Console 的输出大致如下图：

![截图20210409141911](https://user-images.githubusercontent.com/53637421/114138612-7718c200-9940-11eb-9022-4413ea7e18a5.png)

在这个状态下“禁止跳转动态详情”不能正常生效。

等待一段时间后，Console 中出现一片带有 `null` 字样的警告，此时开始“禁止跳转动态详情”功能正常生效。

![截图20210409142533](https://user-images.githubusercontent.com/53637421/114138746-a8918d80-9940-11eb-968b-6c6ec48498bb.png)

[完整 log 在此](https://gist.github.com/GalaxySnail/b28c3897c45c360c2a45643c2d631743)

**Comment by GalaxySnail** [comment]
又经过几次测试发现，似乎是需要触发一次自动打开动态详情，之后十数秒会恢复正常，如果不触发的话可能即使等很久点击动态仍然会触发。但之前也有过完全不点击动态、只等待数分钟后正常生效的情况。只是随便测试了数次，并没有严格控制变量进行多次测试。

**Comment by GalaxySnail** [comment]
浏览器更新至 89.0.4389.114 版本后仍然能复现该问题，现象一致

**Comment by the1812** [comment]
最近动态页确实更新了

**Comment by GalaxySnail** [comment]
我刚从[GitHub仓库](https://github.com/the1812/Bilibili-Evolved/blob/master/bilibili-evolved.preview.user.js?raw=true)里手动更新了脚本，可是这个问题仍然存在啊（手动捂脸）

**Comment by the1812** [comment]
热更新源也换了吗

**Comment by GalaxySnail** [comment]
就是刚从master分支更新的（应该是 [f9521e71bac1258940c2758a9cc9e4e9c0eb8bad](https://github.com/the1812/Bilibili-Evolved/commit/f9521e71bac1258940c2758a9cc9e4e9c0eb8bad) 这个提交吧）

**Comment by the1812** [comment]
我是指脚本设置里的更新源

**Comment by GalaxySnail** [comment]
![截图20210410175532](https://user-images.githubusercontent.com/53637421/114265923-1368c480-9a26-11eb-9a87-c01b69ead1fe.png)

是这个吗？改过了，还是一样不行。

**Comment by the1812** [comment]
不是 是网页上左侧齿轮点开的

**Comment by GalaxySnail** [comment]
哦我明白了，改过以后内容包版本号变了就好了，非常感谢。
抱歉，对这个不太熟悉（手动捂脸），以前也一直没搞清楚这个内容包到底是什么，我觉得可以在 README 或者 FAQ 里面介绍一下更新机制

**Comment by the1812** [comment]
可以的
