### ISSUE TITLE
浮动评论区相关，一个十分影响体验的夜间模式不匹配，

### ISSUE THREAD

**Issue by Mirionr** [the1812/Bilibili-Evolved#1721]
**关于哪一项功能**
夜间模式

**问题描述**

如图所示，今天好像评论区改版了，没有了页码选项，而是用浮动评论框代替了，而这个评论框在夜间模式下一片白色，十分影响体验

**脚本版本**

最新预览版

**浏览器版本**

最新谷歌

**错误信息**

**附加截图**
![1](https://user-images.githubusercontent.com/51433180/114193211-ddbdd000-9980-11eb-8c9f-ee07f47b2ab5.jpg)

**Comment by Geeyun-JY3** [comment]
慢慢来：#1718

**Comment by the1812** [comment]
没收到更新的记得`附加功能`里清下缓存.
