### ISSUE TITLE
直播间全屏底部弹幕栏及去除直播水印功能在部分直播间失效

### ISSUE THREAD

**Issue by Mint328** [the1812/Bilibili-Evolved#1722]
**关于哪一项功能**
直播

**问题描述**
部分直播间可重现，如：
https://live.bilibili.com/1046

**脚本版本**
Stable v1.12.4

**浏览器版本**
EDGE 版本 89.0.774.68 (官方内部版本) (64 位)

**错误信息**

DevTools 无法加载 SourceMap： 无法加载 https://s1.hdslb.com/bfs/static/blive/blfe-live-room/static/js/jquery.min.map: 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载 SourceMap： 无法加载 https://activity.hdslb.com/room-player.css.map: 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
app.d4990a1aa772e416ce1f.js:1 222
DevTools 无法加载 SourceMap： 无法加载 https://activity.hdslb.com/room-player.js.map: 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM928:1 live watch
userscript.html?name=Bilibili%20Evolved.user.js&id=c961df1c-97fd-4eeb-9890-df7010f029b7:13210 scheduled bundle update
room-player.min.js:21 fMp4Player v1.28
userscript.html?name=%E7%BD%91%E7%9B%98%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%86%99%E8%AE%BF%E9%97%AE%E7%A0%81%E3%80%90%E5%A8%81%E5%8A%9B%E5%8A%A0%E5%BC%BA%E7%89%88%E3%80%91.user.js&id=31f5c2cf-3727-4ee4-9126-f3c9070e9d35:810 {pwdRule: /(?:提取|访问)[码碼]?\s*[:： ]?\s*([a-z\d]{4})/, codeRule: /(?:(?:提取|访问|密[码碼]|艾|Extracted-code)[码碼]?)\s*[:： ]?\s*([a-z\d]{4})/i, YunDisk: {…}, JumpUrl: {…}, Support: {…}}
userscript.html?name=%E7%BD%91%E7%9B%98%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%86%99%E8%AE%BF%E9%97%AE%E7%A0%81%E3%80%90%E5%A8%81%E5%8A%9B%E5%8A%A0%E5%BC%BA%E7%89%88%E3%80%91.user.js&id=31f5c2cf-3727-4ee4-9126-f3c9070e9d35:815 conf:  undefined
DevTools 无法加载 SourceMap： 无法加载 chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/jquery.min.map: 的内容HTTP 错误：状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
VM969:1 no matchMedal, fallback to defaultMedal (248405)
script_injector.js:2 pakku ajax: injecting hook
xhr_hook.js:2 pakku: [to developers] Web Worker is disabled for compatibility reasons
(匿名) @ xhr_hook.js:2
(匿名) @ xhr_hook.js:2
xhr_hook.js:2 pakku ajax: hook set
userscript.html?name=Bilibili%20Evolved.user.js&id=c961df1c-97fd-4eeb-9890-df7010f029b7:13210 downloading bundle
room-player.min.js:21 Chrome verion: 89
userscript.html?name=Bilibili%20Evolved.user.js&id=c961df1c-97fd-4eeb-9890-df7010f029b7:13210 zip version = 1.12.4
main.d9f35d9055c58b27d95a.js:84 Bilibili Live V4.0.0 "Life Experience" Lovingly By © 2014 - 2021 Bilibili Live Department  ...(●'◡'●)ﾉ♥   # Renascence #
main.d9f35d9055c58b27d95a.js:84 Version: V4.0.0 "Life Experience", CodeName: Neptune.
VM928:1 leave feeds tab
VM920:1 draw button = null
script_injector.js:2 pakku ajax: injecting hook
userscript.html?name=Bilibili%20Evolved.user.js&id=c961df1c-97fd-4eeb-9890-df7010f029b7:13210 scheduled bundle update
xhr_hook.js:2 pakku: [to developers] Web Worker is disabled for compatibility reasons
(匿名) @ xhr_hook.js:2
(匿名) @ xhr_hook.js:2
xhr_hook.js:2 pakku ajax: hook set
userscript.html?name=Bilibili%20Evolved.user.js&id=c961df1c-97fd-4eeb-9890-df7010f029b7:13210 bundle updated
userscript.html?name=Bilibili%20Evolved.user.js&id=c961df1c-97fd-4eeb-9890-df7010f029b7:13210 downloading bundle
userscript.html?name=Bilibili%20Evolved.user.js&id=c961df1c-97fd-4eeb-9890-df7010f029b7:13210 zip version = 1.12.4
userscript.html?name=Bilibili%20Evolved.user.js&id=c961df1c-97fd-4eeb-9890-df7010f029b7:13210 bundle updated

**附加截图**

**Comment by Mint328** [comment]
无关的几行请忽略。。。😢

**Comment by Mint328** [comment]
![屏幕截图(10)](https://user-images.githubusercontent.com/79647628/114261709-a0078880-9a0e-11eb-85a0-7281561ede96.png)

**Comment by Mint328** [comment]
![屏幕截图(10)](https://user-images.githubusercontent.com/79647628/114261744-df35d980-9a0e-11eb-9d52-0604604bcd2b.png)

**Comment by Mint328** [comment]
![屏幕截图(12)](https://user-images.githubusercontent.com/79647628/114261805-46ec2480-9a0f-11eb-8772-915fc2080b97.png)
![屏幕截图(11)](https://user-images.githubusercontent.com/79647628/114261808-4c496f00-9a0f-11eb-8f55-05f7d2a7762d.png)

**Comment by Mint328** [comment]
@the1812 我发了几张截图，网页全屏和全屏，弹幕栏都是没有的，水印还在。我又试了下，发现礼物包裹也没有。。而且几乎所有直播间都是这样，唯一两个正常的直播间是有官方活动的，可以在播放器上方切换直播间那种。关闭除油猴外所有浏览器扩展和其他脚本，问题还是存在
![屏幕截图(13)](https://user-images.githubusercontent.com/79647628/114262083-aa2a8680-9a10-11eb-89d5-856fe62855d5.png)
就这种直播间是正常的，还有这个https://live.bilibili.com/55

**Comment by Mint328** [comment]
https://airportal.cn/106685/bW6xKue70a 脚本设置是这样的，

**Comment by Mint328** [comment]
@the1812 脚本设置是这样的 https://airportal.cn/106685/bW6xKue70a

**Comment by Mint328** [comment]
@the1812 刚刚试了下，退出b站账号后脚本功能恢复正常。。账号是大会员，不知道普通账号会不会有这个问题。。

**Comment by the1812** [comment]
我也是大会员啊... 而且这种功能也并不依赖帐号的, 再登录回去还是有这问题?

**Comment by Mint328** [comment]
> 我也是大会员啊... 而且这种功能也并不依赖帐号的, 再登录回去还是有这问题?

是的。。登陆回去之后好像只有第一次打开是正常，刷新之后就又有问题了（？）这个具体没有试，只是有这个印象。。但是的确退出账号后功能会正常，登录会复现。。我试了好几次。。。难道我这有其他原因？。。。我再试试。。

**Comment by Mint328** [comment]
> 我也是大会员啊... 而且这种功能也并不依赖帐号的, 再登录回去还是有这

**Comment by the1812** [comment]
只能先放着了, 我也不知道啥原因, 之后如果遇到会再注意的

**Comment by KOHAKUchan** [comment]
我也出现了同样的问题……

**Comment by the1812** [comment]
好了我也遇到了, 直播的播放器改版了

**Comment by EearlyDew** [comment]
我也出现这样的问题
![20210413203230](https://user-images.githubusercontent.com/53134066/114552896-a2c8de80-9c97-11eb-9a88-a37d6b25898a.png)
