### ISSUE TITLE
视频播放时的弹幕点赞

### ISSUE THREAD

**Issue by birthfromfire** [the1812/Bilibili-Evolved#1723]
现在开启插件貌似没有办法启用弹幕点赞？就是把鼠标移到某个弹幕上就可以点赞或者举报的功能，不知道能不能兼容下，感觉还是挺好用的

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved#安装
> - 做好觉悟, 脚本开启后不能使用弹幕点赞和举报, 对性能也有较大影响.

**Comment by birthfromfire** [comment]
其实也没有那么需要，不能就算了，不过对我的性能到没有太大影响。
能抽时间回复我的建议还是多谢了

Geeyun-JY3 ***@***.***> 于2021年4月10日周六 上午2:13写道：

**Comment by linghan026** [comment]
我还挺喜欢点赞的。。。就很纠结

**Comment by Geeyun-JY3** [comment]
> 我还挺喜欢点赞的。。。就很纠结

有时候鱼和熊掌不能兼得……
