### ISSUE TITLE
动态加载出更多内容的时候脚本失效

### ISSUE THREAD

**Issue by gayhub-com** [the1812/Bilibili-Evolved#1724]
一打开动态页面的时候全部功能正常,
但是一旦往下拉到最下面触发加载, 然后出来更多动态之后
脚本对所有新出来的动态内容全部失效. 比如动态过滤器这个功能就不能用了
侧边栏正常, 关键词,类型过滤,评论区快速折叠等功能失效
如果往上拉到最上面的最新动态(不是被加载出来的部分), 功能又正常使用.

**Comment by the1812** [comment]
动态好像改版了...

**Comment by KurohaneNioko** [comment]
动态那个卡片的class之前有一项是data-did 现在改名叫data-v-240e4acb了 感觉应该就是这个问题

**Comment by the1812** [comment]
不是, 是因为外面多了一层 `<div>`
原先是对着有 `data-did` 的元素取 `.__vue__` 属性, 现在要改成 `.parentElement.__vue__` 才能取到
