### ISSUE TITLE
扩展快捷键与全景视频冲突问题

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1725]
现在全景视频是不是又有本 issue 一开始提的第一条的问题🌚

_Originally posted by @Geeyun-JY3 in https://github.com/the1812/Bilibili-Evolved/issues/534#issuecomment-796724238_

即扩展快捷键会与全景视频内用 WASD 键移动调节视角冲突。

另外全景视频无法用鼠标拖拽调整视角。

**Comment by the1812** [comment]
试了下没有冲突啊 https://www.bilibili.com/video/BV1NC4y1x75f

不过确实拖不动了, 和弹幕点赞是同一原理, 看来全景视频也因为这弹幕点赞把所有东西盖住了被迫把拖拽功能转移到弹幕点赞层了

**Comment by Geeyun-JY3** [comment]
啊是别的脚本的问题（跪倒。草率了忘记先单独测试一下

**Comment by Geeyun-JY3** [comment]
或者可以在 README 提一下全景视频拖拽视角这事（

**Comment by the1812** [comment]
会的
