### ISSUE TITLE
直播间全屏底部弹幕栏及去除直播水印功能在部分直播间失效2

### ISSUE THREAD

**Issue by Mint328** [the1812/Bilibili-Evolved#1728]
抱歉，刚才手残不小心把issues给关了。。。

我这边没有其他设备，就找了台云电脑试了下，不知道会不会对脚本本身有影响。。

EDGE 版本 89.0.774.75 (官方内部版本) (64 位)  新下载的，只安装了油猴
油猴版本为4.11.6120 脚本版本为Stable v1.12.4 内容包: 3284e19

登录账号，会出现我所描述的问题，退出账号正常。。

不是搞这个的，不知道哪些东西具体会影响什么功能，我只能做到这了。。。

（上个问题 #1722）

**Comment by the1812** [comment]
那个你再点一下 Reopen 就开了的(

**Comment by Mint328** [comment]
> 那个你再点一下 Reopen 就开了的(

一直在github上下东西，没怎么反馈过问题，不太了解这些，，，（尴尬。。

**Comment by the1812** [comment]
这个我先关了 之后继续在 #1722 发就行了
