### ISSUE TITLE
动态的快速收起动态评论区失效

### ISSUE THREAD

**Issue by sugeinmy** [the1812/Bilibili-Evolved#1729]
**关于哪一项功能**
快速收起动态评论区

**问题描述**
没有出现那个收起评论的按钮

**脚本版本**
Stable v1.12.4

**浏览器版本**
360极速浏览器13  chrome86

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.12.4
#1724 刚修，等热更新
