### ISSUE TITLE
动态里的番剧和专栏界面混乱

### ISSUE THREAD

**Issue by Keilwerth** [the1812/Bilibili-Evolved#173]
RT
![image](https://user-images.githubusercontent.com/54608878/63819478-080f7500-c978-11e9-91f2-0e72d6bcc3d5.png)
![image](https://user-images.githubusercontent.com/54608878/63819507-1b224500-c978-11e9-97ca-ff815f94531b.png)

**Comment by the1812** [comment]
你用的是什么浏览器?

**Comment by Keilwerth** [comment]
> 你用的是什么浏览器?

星愿浏览器

**Comment by the1812** [comment]
已修复, 你刷新几下试试
