### ISSUE TITLE
「自动展开弹幕列表 - 合集类页面不展开」功能失效

### ISSUE THREAD

**Issue by LiRunZhe** [the1812/Bilibili-Evolved#1736]
**关于哪一项功能**
自动展开弹幕列表 - 合集类页面不展开

**问题描述**

打开合集类视频如[该视频](https://www.bilibili.com/video/BV1cW411T7va)，在勾选「合集类页面不展开」的情况下弹幕列表依旧展开

**脚本版本**

Stable v1.12.4 内容包: 1044088

**浏览器版本**

Chrome Version 89.0.4389.114 (Official Build) (64-bit)
Firefox 87.0 (64-bit)
Edge Version 89.0.774.75 (Official build) (64-bit)

**错误信息**

无

**附加截图**
<img width="1695" alt="Snipaste_2021-04-12_18-54-11" src="https://user-images.githubusercontent.com/25532422/114384533-688d0d80-9bc1-11eb-914e-b197cca96077.png">

**Comment by the1812** [comment]
合集类是指收藏夹/稍后再看列表播放, 这个只是个多P视频, 或许我可以再加个`多P视频不展开`

**Comment by LiRunZhe** [comment]
> 合集类是指收藏夹/稍后再看列表播放, 这个只是个多P视频, 或许我可以再加个`多P视频不展开`

😂好的，不好意思是我误会了，就当是提了个需求吧。

**Comment by zbodo** [comment]
> 合集类是指收藏夹/稍后再看列表播放, 这个只是个多P视频, 或许我可以再加个`多P视频不展开`

同希望有此功能

**Comment by MC-dusk** [comment]
> 
> 
> > 合集类是指收藏夹/稍后再看列表播放, 这个只是个多P视频, 或许我可以再加个`多P视频不展开`
> 
> 同希望有此功能

+1，同时希望`使用默认播放器模式`-`宽屏`也能如法炮制，也就是多p就不宽屏，方便切p。
