### ISSUE TITLE
B站出新功能了

### ISSUE THREAD

**Issue by Tinhone233** [the1812/Bilibili-Evolved#1737]
**关于哪一项功能**
b站刚出的功能，视频刷着刷着就出现了，触发方式为往下翻评论区

**问题描述**
未适配夜间模式

**脚本版本**
正式版1.12.4

**浏览器版本**
FirefoxV85

**错误信息**
无

**附加截图**
![图片](https://user-images.githubusercontent.com/82388566/114401693-bf044700-9bd5-11eb-8a2c-4b042b79455a.png)
![图片](https://user-images.githubusercontent.com/82388566/114402113-1a363980-9bd6-11eb-94d3-d32c0eccebc6.png)

**Comment by Tinhone233** [comment]
关联问题：#1289

**Comment by Geeyun-JY3** [comment]
#1718、#1721
看看 [v1.12.4](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.12.4) 的更新日志，有写 10 号已经修了，等热更新。

**Comment by Tinhone233** [comment]
> 
> 
> #1718、#1721
> 看看 [v1.12.4](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.12.4) 的更新日志，有写 10 号已经修了，等热更新。

谢谢
