### ISSUE TITLE
想要下载b站批量分P视频，这个有这个功能吗

### ISSUE THREAD

**Issue by fjm0615** [the1812/Bilibili-Evolved#1738]
问题如题，第一次留言，也不知道格式对不对，见谅。我如果直接下载的话就只有一个视频，如果按旁边批量的，下载的好像不太对。如果有知道的小伙伴可以给我发邮箱。1780309788@qq.com
![image](https://user-images.githubusercontent.com/54699769/114515098-92e8d480-9c6e-11eb-991d-39aff1d7cf85.png)

**Comment by FoundTheWOUT** [comment]
批量导出后用对应软件(如IDM, aria2)下载, 建议了解一下aria2, 与aria2 RPC的设置
[motrix](https://motrix.app/)

**Comment by fjm0615** [comment]
好的，谢谢你大善人~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月13日(星期二) 下午5:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 想要下载b站批量分P视频，这个有这个功能吗 (#1738)





 
批量导出后用对应软件(如IDM, aria2)下载, 建议了解一下aria2, 与aria2 RPC的设置
 motrix

**Comment by Geeyun-JY3** [comment]
这种提问下次去 discussion 开 Q&A：#1297
https://github.com/the1812/Bilibili-Evolved/blob/preview/doc/issue-rules.md

**Comment by fjm0615** [comment]
好的，感谢大佬指路




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月15日(星期四) 上午9:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 想要下载b站批量分P视频，这个有这个功能吗 (#1738)





 
这种提问下次去 discussion 开 Q&amp;A：#1297
 https://github.com/the1812/Bilibili-Evolved/blob/preview/doc/issue-rules.md
