### ISSUE TITLE
视频评论区无法显示

### ISSUE THREAD

**Issue by youngerstar** [the1812/Bilibili-Evolved#1745]
**关于哪一项功能**
视频下方的评论区无法显示

**问题描述**

使用默认配置即可
https://www.bilibili.com/video/BV1XV411E7t1

**脚本版本**

正式版1.12.4

**浏览器版本**

Edge Dev 91.0.845.2

**错误信息**

**附加截图**
![屏幕截图 2021-04-15 194355](https://user-images.githubusercontent.com/46211595/114863935-f61b6800-9e22-11eb-9065-22d0212991af.png)

**Comment by Geeyun-JY3** [comment]
我这边无法复现，建议提供更多信息或者排查一下是不是别的插件脚本的问题。

**Comment by youngerstar** [comment]
> 我这边无法复现，建议提供更多信息或者排查一下是不是别的插件脚本的问题。

只打开了Bilibili-Evolved。同样的url，今天评论区又可以加载了。
![屏幕截图 2021-04-16 212608](https://user-images.githubusercontent.com/46211595/115031253-87a9d900-9efa-11eb-8dfa-17dad5dd85c4.png)

出现问题的时候，关闭脚本始终能刷出评论区。

**Comment by Tinhone** [comment]
这个问题最近大家还有遇到嘛🤔

**Comment by Geeyun-JY3** [comment]
这种 V1 时期且无多人复现的 issue 我建议直接关。
