### ISSUE TITLE
多页视频切换到其它页后读取视频内容失败，无法播放

### ISSUE THREAD

**Issue by LenKiMo** [the1812/Bilibili-Evolved#1746]
**关于哪一项功能**
视频播放

**问题描述**
1. 打开任意多页（多P）视频
2. 待第一页视频加载完毕，可以开始播放后，切换到其它分页
3. 视频无法加载，读取到`加载视频内容`步骤时报错 `[Dash] Call getCurrentPlayURLFor function error, type: video, qualityIndex: 0`
4. 刷新当前页面后，视频可以正常加载
5. 再次切换到其它分页，回到第三步

**脚本版本**
Stable v1.12.4 内容包: baa6c3c

**浏览器版本**
Chrome 版本 91.0.4469.4（正式版本）dev （64 位）

**错误信息**
加载视频内容[错误]  `[Dash] Call getCurrentPlayURLFor function error, type: video, qualityIndex: 0`

**附加截图**
控制台错误截图：
![2021-04-15_214932.png](https://i.loli.net/2021/04/15/tvLiYMKzsQEO1PS.png)

**Comment by the1812** [comment]
有试过关闭其他插件/脚本吗?

**Comment by LenKiMo** [comment]
最近是连单个视频都不能播放了，报错 `[Dash] Load dash plater script error, src: https://static.hdslb.com/player/js/dash.mediaplayer.min.js`

经过排查，是与 https://github.com/reek/anti-adblock-killer/ 这个脚本产生了冲突。禁用后就可以了。
