### ISSUE TITLE
开启插件导致标题全部变成英文

### ISSUE THREAD

**Issue by Originator2019** [the1812/Bilibili-Evolved#1757]
**关于哪一项功能**
界面显示问题

**问题描述**

**脚本版本**

1.12.4

**浏览器版本**

![image](https://user-images.githubusercontent.com/51257957/115385283-8b936f00-a20a-11eb-860d-330b80d6b044.png)

**错误信息**

![image](https://user-images.githubusercontent.com/51257957/115385238-7ddde980-a20a-11eb-936e-6bc636776467.png)

开启脚本前
**附加截图**
![image](https://user-images.githubusercontent.com/51257957/115384473-a9ac9f80-a209-11eb-8966-16f9943d790d.png)

开启脚本后
![image](https://user-images.githubusercontent.com/51257957/115384620-d496f380-a209-11eb-8a4b-8459abd2a152.png)

**Comment by the1812** [comment]
#1301
