### ISSUE TITLE
评论栏深色模式，弹幕列表自动打开

### ISSUE THREAD

**Issue by waffff** [the1812/Bilibili-Evolved#1759]
**关于哪一项功能**
深色模式，弹幕列表展开

**问题描述**
评论框滞留在界面，深色模式无用。
弹幕列表仍然会自动打开。

**脚本版本**
< v1.12.4 >

**浏览器版本**
< 89.0.4389.90（正式版本） (x86_64)>

**错误信息**
![截屏2021-04-21 上午1 04 48](https://user-images.githubusercontent.com/77989932/115499628-bc40cc00-a23d-11eb-95eb-8b0ad8eedfd1.jpg)
![截屏2021-04-21 上午1 04 33](https://user-images.githubusercontent.com/77989932/115499633-bea32600-a23d-11eb-9b67-282d5d6a052f.jpg)
我看不懂代码。。。(┯_┯)

**附加截图**

评论框深色模式无效
![截屏2021-04-21 上午12 51 36](https://user-images.githubusercontent.com/77989932/115499758-fc07b380-a23d-11eb-9730-3ae62d81a8b3.jpg)

弹幕列表仍然会自动打开
![截屏2021-04-21 上午12 51 46](https://user-images.githubusercontent.com/77989932/115499760-fc07b380-a23d-11eb-858e-a75b14e5d240.jpg)

![截屏2021-04-21 上午12 51 55](https://user-images.githubusercontent.com/77989932/115499719-e5615c80-a23d-11eb-8236-f9ba3dede2fc.jpg)

**Comment by Geeyun-JY3** [comment]
评论栏深色模式清一下缓存，热更新已修。

**Comment by BaiBuCYBGT** [comment]
> 
> 
> 评论栏深色模式清一下缓存，热更新已修。

该如何清理缓存呢？

**Comment by Geeyun-JY3** [comment]
> 该如何清理缓存呢？

附加功能中
