### ISSUE TITLE
脚本与插件Stylish相冲突

### ISSUE THREAD

**Issue by Kulahala** [the1812/Bilibili-Evolved#176]
当使用stylish的Amazing blibili时，脚本的主题颜色会在刷新桌面时重置为蓝色
![QQ截图20190830112939](https://user-images.githubusercontent.com/54696830/63991242-86574d00-cb19-11e9-9b19-9c74d598bc0f.png)

**Comment by the1812** [comment]
对, 会冲突的, 主题颜色都叫`--theme-color`, 两个你只能留一个

**Comment by Kulahala** [comment]
那个作者也已经退坑了，想留Evolved，但他的背景和美化也很好看，我也只能关闭自定义了（谢谢你(￣▽￣)~*）



------------------ 原始邮件 ------------------
发件人: "Grant Howard"<notifications@github.com>; 
发送时间: 2019年8月30日(星期五) 中午11:43
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com>; 
抄送: "Kulahala"<1378554398@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [the1812/Bilibili-Evolved] 脚本与插件Stylish相冲突 (#176)




对, 会冲突的, 主题颜色都叫--theme-color, 两个你只能留一个

**Comment by the1812** [comment]
没关系 类似功能我以后也会做的
