### ISSUE TITLE
MAXTHON 5.3.8.2100+Violentmonkey 2.8.4加载不了。。。

### ISSUE THREAD

**Issue by drw2005** [the1812/Bilibili-Evolved#1765]
**关于哪一项功能**

**问题描述**

不能正常加载，但是有时侯不定某个版本又可以正常使用了，不知道可有用傲游5的各位有没有这种情况。
**脚本版本**

正式版或者预览版都是这样，换不同版本都不行。

**浏览器版本**

傲游5.3.8.2100+油猴2.8.4
习惯用傲游5了，目前该版本的油猴只有2.8.4版本了，好像没发现有新版本升级。所以恳请大佬能解决一下这个问题，感谢！

**错误信息**

**附加截图**
![QQ截图20210422170715](https://user-images.githubusercontent.com/33473981/115687905-3764c800-a38d-11eb-9a2f-22f0013329e7.jpg)

**Comment by the1812** [comment]
我看了下遨游5, 是2015年的, 脚本当然不会支持
![image](https://user-images.githubusercontent.com/26504152/115688755-033dd700-a38e-11eb-8277-970be4125214.png)
最低限度要求的 Chrome 80 是2020年2月发布的

**Comment by drw2005** [comment]
> 我看了下遨游5, 是2015年的, 脚本当然不会支持
> ![image](https://user-images.githubusercontent.com/26504152/115688755-033dd700-a38e-11eb-8277-970be4125214.png)
> 最低限度要求的 Chrome 80 是2020年2月发布的

感谢回复。不过，之前的版本有时是能用的，就是不知道什么原因，比如遇到升级到下一个版本时，就不能用了。
