### ISSUE TITLE
快捷键和和Ctrl组合键冲突了，不能复制了_(:3」∠)_

### ISSUE THREAD

**Issue by MapleRecall** [the1812/Bilibili-Evolved#177]
**关于哪一项功能**
快捷键

**问题描述**
突然发现不能复制，原来是投币快捷键`c`和`ctrl`+`c`冲突啦，试了一下其它的也存在相同的问题……

**脚本版本**
预览版

**Comment by the1812** [comment]
我10分钟前刚修复\_(:3」∠)\_
