### ISSUE TITLE
夜间模式未适配/b站更新了动态评论输入框/

### ISSUE THREAD

**Issue by paletree** [the1812/Bilibili-Evolved#1772]
**关于哪一项功能**

**问题描述**

测试用BV号：BV1iU4y1h7sq，实际上任何一个视频都可以

**脚本版本**

Stable v1.12.4
内容包: 7f8ee6f

**浏览器版本**

chrome版本 89.0.4389.128

**错误信息**

这不是代码的bug，单纯b站用了新的动态输入框，请添加夜间模式的适配

**附加截图**
![屏幕截图 2021-04-23 214923](https://user-images.githubusercontent.com/38284716/115881119-ff897d80-a47d-11eb-897d-e57d1bd069e5.png)

**Comment by Geeyun-JY3** [comment]
清清缓存，[1.12.4](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.12.4) 热更新早修了：#1721、#1759

@the1812 这个新评论输入框的适配是不是得置顶一下
