### ISSUE TITLE
出现新分区-汽车，不在首页过滤功能管理范围内

### ISSUE THREAD

**Issue by DuskShadows** [the1812/Bilibili-Evolved#1774]
**关于哪一项功能**
首页过滤

**问题描述**
出现新分区-汽车，当前首页过滤功能无法对其进行管理

**脚本版本**
1007.77

**浏览器版本**
FireFox 86.0

**Comment by FoundTheWOUT** [comment]
...前天修了, 手滑restore掉了
过滤功能还要一个`电竞赛事`要补的.

@the1812 我要提个PR吗, 还是说等你有空补上.
这个功能以后能不能改成获取B站首页的信息, 然后自动添加可过滤项🤔

**Comment by the1812** [comment]
> 然后自动添加可过滤项

我觉得可以
