### ISSUE TITLE
在有活动的直播间资源加载有限制

### ISSUE THREAD

**Issue by HCLonely** [the1812/Bilibili-Evolved#178]
**关于哪一项功能**

直播间功能

**问题描述**

在有活动的直播间（例[https://live.bilibili.com/1017](https://live.bilibili.com/1017)）有安全限制，资源加载不了

**脚本版本**

预览版1.8.19

**浏览器版本**

Chrome 76

**错误信息**

[Report Only] Refused to connect to '<URL>' because it violates the following Content Security Policy directive: "connect-src 'self' <URL> *.bilibili.com *.hdslb.com *.biliapi.net *.biliapi.com".

**附加截图**
![image](https://user-images.githubusercontent.com/26346802/64063551-12f03100-cc28-11e9-86d8-22c6e36d52b3.png)

**Comment by the1812** [comment]
Firefox那最近也报CSP, 我得改一下资源加载的方式了

**Comment by shugen002** [comment]
现在看样子是B站上CSP的准备阶段，只报告不拦截，要快点处理好这个问题，我现在用离线版本来避免控制台被刷屏。。。
