### ISSUE TITLE
存在图片加载失败的情况

### ISSUE THREAD

**Issue by Wdam** [the1812/Bilibili-Evolved#1781]
**关于哪一项功能**
首页图片加载偶尔会出错

![image](https://user-images.githubusercontent.com/42366809/116062132-38139c00-a6b6-11eb-9a3c-afc893756687.png)

**问题描述**

如何复现尚不可知，但是在我使用v2ray全局代理时不会出现图片加载错误，使用pac模式时小概率出现，不使用代理时大概率出现

**脚本版本**

1.12.4

**浏览器版本**

版本 90.0.4430.85（正式版本） （64 位）
**错误信息**

![image](https://user-images.githubusercontent.com/42366809/116063155-3a2a2a80-a6b7-11eb-9865-f5108b025e95.png)

![image](https://user-images.githubusercontent.com/42366809/116063036-123ac700-a6b7-11eb-9f4e-e52f2a6b4951.png)
**附加截图**

**Comment by the1812** [comment]
清下浏览器缓存? 我以前是这么解决的

**Comment by Wdam** [comment]
> 清下浏览器缓存? 我以前是这么解决的

有效果

**Comment by Wdam** [comment]
问题还是存在，估计和我的网络和v2ray有关（？）

**Comment by the1812** [comment]
尽量让b站一直能直连, 即便开全局代理也不要代理b站

**Comment by Wdam** [comment]
调查清楚了，是host文件出了大问题，可能是游戏加速器导致的
