### ISSUE TITLE
想问下弹幕渲染模式是否可以设置？

### ISSUE THREAD

**Issue by RainSola** [the1812/Bilibili-Evolved#1782]
不知道是不是灰度测试，我现在PC网页端的弹幕渲染模式的选项没了，默认的弹幕在视频白色背景下完全看不清，以前我都是直接调成另一种渲染模式就行，现在没了。不知道这个在插件里能否实现？或者有我不知道的哪里可以设置的？谢谢！

**Comment by the1812** [comment]
我也找不到了...没想到这个居然也会取消掉
白色背景可以换一下描边类型

**Comment by RainSola** [comment]
> 我也找不到了...没想到这个居然也会取消掉
> 白色背景可以换一下描边类型

不管是重墨还是描边还是投影，都不行，视频白色背景下肯定是看不清默认的白色弹幕的了

**Comment by the1812** [comment]
我用的重墨还行啊
![image](https://user-images.githubusercontent.com/26504152/116546943-d6a53480-a924-11eb-9a4d-1c0f7f819fe1.png)

顺便试了下描边和投影
![image](https://user-images.githubusercontent.com/26504152/116547002-e6247d80-a924-11eb-8313-2a42b616d06b.png)
![image](https://user-images.githubusercontent.com/26504152/116547074-fe949800-a924-11eb-8a99-39ca44198116.png)

**Comment by RainSola** [comment]
> 我也找不到了...没想到这个居然也会取消掉
> 白色背景可以换一下描边类型

喷了，刚刚换了下FIREFOX浏览器换描边就行，CHROME和EDGE换描边都无效，可是FIREFOX浏览器又神奇的有自动切P和连播推荐绑定的灰度测试，喷了。

**Comment by RainSola** [comment]
> 我用的重墨还行啊
> ![image](https://user-images.githubusercontent.com/26504152/116546943-d6a53480-a924-11eb-9a4d-1c0f7f819fe1.png)
> 
> 顺便试了下描边和投影
> ![image](https://user-images.githubusercontent.com/26504152/116547002-e6247d80-a924-11eb-8313-2a42b616d06b.png)
> ![image](https://user-images.githubusercontent.com/26504152/116547074-fe949800-a924-11eb-8a99-39ca44198116.png)

不知道你用的是什么浏览器，还是CHROME内核的就不行。

**Comment by the1812** [comment]
Chrome 90.0.4430.93 (原版)

**Comment by RainSola** [comment]
> Chrome 90.0.4430.93 (原版)

那看来是插件的原因，刚刚试着把暴力猴关了也没用，再排查下其他扩展吧。。。

**Comment by RainSola** [comment]
> Chrome 90.0.4430.93 (原版)

原来是Font Rendering Enhancer的原因，终于舒服了，不会眼瞎了，感谢回复！
