### ISSUE TITLE
拦截替换js资源加载？

### ISSUE THREAD

**Issue by shugen002** [the1812/Bilibili-Evolved#179]
**关于哪一项功能**

**期望的效果**
添加接口，可以在js动态添加到页面时触发事件可以更改请求地址或直接取消这个js的加载。
主要是发现现有ajax并不能拦截jsonp的请求，所以希望可以加上。
文档方面可以参考这篇文章
https://medium.com/snips-ai/how-to-block-third-party-scripts-with-a-few-lines-of-javascript-f0b08b9c4c0
中的部分操作。

顺带，虽然我也想贡献代码，不过看到依然依赖dotnet就放弃了。。。
我也会去自己实现一个自己的版本的。。。

**脚本版本**

预览离线版

**Comment by the1812** [comment]
我没啥实现思路, 那篇文章里的方法并不管用. 你能实现的话直接可以开pr, 不用dotnet, 直接加个文件就行.

**Comment by the1812** [comment]
我找到办法了, 已添加 [ScriptBlocker API](https://github.com/the1812/Bilibili-Evolved/blob/preview/src/client/script-blocker.md).
