### ISSUE TITLE
全站使用说明 深色模式适配

### ISSUE THREAD

**Issue by ChenMoFeiJin** [the1812/Bilibili-Evolved#1791]
**关于哪一项功能**
深色模式

**问题描述**

B站的全站使用说明界面在深色模式下只有小部分元素适配了，大部分没变动
https://www.bilibili.com/blackboard/help.html

**脚本版本**

Stable v1.12.4 内容包: cb38180
Preview v1.12.6 内容包: 254907d
均存在该问题

**浏览器版本**

Edge 90.0.818.49 (官方内部版本) (64 位)

**错误信息**

无

**附加截图**
![image](https://user-images.githubusercontent.com/42508525/116258325-6f15aa80-a7a7-11eb-9692-4ad0924c7a21.png)

**Comment by Geeyun-JY3** [comment]
重复：https://github.com/the1812/Bilibili-Evolved/issues/731#issuecomment-711111127

**Comment by Geeyun-JY3** [comment]
我觉得这种 issue 也可以留着，毕竟连我也不是很想进那三个长得要命的 issue 看（
