### ISSUE TITLE
在21:9显示屏上 简化首页字体大小问题

### ISSUE THREAD

**Issue by AQ-Official** [the1812/Bilibili-Evolved#1797]
**关于哪一项功能**
在21:9显示屏上 简化首页字体大小问题

**问题描述**
近期b站好像更新了针对于首页的21:9的自适应大小，在21:9比例的显示器上，原版首页会自适应放大。导致字体的font-size:也会变大。
插件的『简化首页』功能中，应该是直接使用了b站原本首页的font-size属性，导致21:9的『简化首页』中元素大小未变，但是字体变得很大

**脚本版本**
Stable v1.12.4
内容包: 29b4af4

**浏览器版本**
版本 90.0.4430.93（正式版本） (x86_64)

**错误信息**

**附加截图**
![截屏2021-04-30 20 15 30](https://user-images.githubusercontent.com/69107895/116694019-4d0f6880-a9f1-11eb-97f1-9144e2e239fe.png)

**Comment by the1812** [comment]
没试出来 用的模拟尺寸是 3675x1575 (21:9)
我下一版指定下 `font-size` 再看看吧

**Comment by AQ-Official** [comment]
这两天发现已经正常，打开原版b站首页也回归以前。感觉b站又改回去了。
但还是指定一下font-size有备无患
