### ISSUE TITLE
香港网络环境无法正常下载视频

### ISSUE THREAD

**Issue by Futrime** [the1812/Bilibili-Evolved#1800]
**关于哪一项功能**
下载视频

**问题描述**
在香港网络环境下，脚本内置下载视频功能无法正常工作。下载的视频仅有META数据。

无论选择FLV格式还是DASH格式都是如此。

包括番剧和普通视频（示例：https://www.bilibili.com/video/BV1bh411m7w4）。

即使是仅限港澳番剧也是如此。

与此同时，通过下半部分导出功能中“显示链接”得到的链接直接访问可以正常下载视频，用Aria2、IDM等方式也可以导出正常可用的文件下载链接。

使用代理，通过内地网络环境则正常使用。

需要的文件在附件中:
[相关信息.zip](https://github.com/the1812/Bilibili-Evolved/files/6409192/default.zip)

**脚本版本**
正式版1.12.4

**浏览器版本**
Chrome 90.0.4430.93（正式版本）（64位）

**错误信息**
```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
```
更多信息在附件中：[相关信息.zip](https://github.com/the1812/Bilibili-Evolved/files/6409192/default.zip)

**附加截图**
请参考附件：[相关信息.zip](https://github.com/the1812/Bilibili-Evolved/files/6409192/default.zip)

**Comment by Coulomb-G** [comment]
不支持港澳台相关的功能适配

**Comment by the1812** [comment]
503我还是头一次见, 不过导出能用就先用着吧...

**Comment by Futrime** [comment]
> 
> 
> 不支持港澳台相关的功能适配
> 另外多说一句,人在港澳台的同胞试过脚本可以正常下载,可能是你的途径有问题

报503错误的链接，手动复制访问，可以正常下载

**Comment by Futrime** [comment]
经测试，不是Header的问题。将报503错误的连接重新发送，可以正常获取文件。

**Comment by Coulomb-G** [comment]
不是说有什么问题或者错误,而是这边不会去主动适配以及修复,该脚本不会去涉及港澳台相关功能

**Comment by the1812** [comment]
可能是那个香港网络的问题?

**Comment by Futrime** [comment]
> 
> 
> 可能是那个香港网络的问题?

根据测试，发现很有意思的情况：

报503的链接，只要在原来的网页环境，使用开发者工具发包访问都是503.

但是如果新建标签页再用开发者工具发包，即使已经换上源请求的Header，也可以正常下载。

怀疑是哔哩哔哩自己有点问题，可能识别Cookie出了问题？

**Comment by Futrime** [comment]
作者辛苦了。

测试完毕，证实是B站自己的问题。

只要清除Cookies和网站数据，即使在原页面重新发包也可以正常下载。
