### ISSUE TITLE
下载视频手动输入aria2导出没有文件名

### ISSUE THREAD

**Issue by Futrime** [the1812/Bilibili-Evolved#1801]
**关于哪一项功能**
下载视频

**问题描述**

下载视频手动输入aria2导出没有文件名。

任何视频都是这样，例如：https://www.bilibili.com/video/av630364725

不过番剧批量导出功能没有问题。  

![1](https://user-images.githubusercontent.com/35801754/116779285-016bc600-aaa8-11eb-9aed-51232295a966.jpg)
![2](https://user-images.githubusercontent.com/35801754/116779288-03358980-aaa8-11eb-92c3-0201a084ac49.jpg)

**脚本版本**
正式版1.12.4

**浏览器版本**
Chrome 90.0.4430.93（正式版本）（64位）

**错误信息**
[console.log](https://github.com/the1812/Bilibili-Evolved/files/6409359/console.log)

**附加截图**
在上面有了

**Comment by FoundTheWOUT** [comment]
看了下, 由于这个手动输入最终使用的是`批量下载`, 在默认设置中`批量下载`的命名格式是没有设置`title`的.
所以结果如你所见, 从逻辑上来讲这个单个输入av号确实应该默认的添加`title`, 可感觉有点麻烦(
我给出的解决方案是, 修改一下批量命名格式, 比如改成`[n - ][title][ep]`, 当然在这个场景下可能直接`[title]`更好. 
![截屏2021-05-01 下午9 21 59](https://user-images.githubusercontent.com/47922588/116783791-56690580-aac3-11eb-9b91-3845f45f7c47.png)
