### ISSUE TITLE
主站上端菜单栏无法显示

### ISSUE THREAD

**Issue by chen850790** [the1812/Bilibili-Evolved#1811]
**关于哪一项功能**
页面加载

**问题描述**

主站，一进即有

**脚本版本**

 1.12.4

**浏览器版本**

chrome 89.0.4389.114

**错误信息**

**附加截图**

**Comment by the1812** [comment]
有图吗

**Comment by chen850790** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 主站上端菜单栏无法显示 (#1811)





 
有图吗

**Comment by the1812** [comment]
不要用邮箱发, 图会被吞

**Comment by the1812** [comment]
你开了两个脚本吧
