### ISSUE TITLE
aria2 导出rpc下载报告 target machine actively refused it(aria2报错而非脚本，猜测需要让脚本传递更多信息给aria2)

### ISSUE THREAD

**Issue by TTTPOB** [the1812/Bilibili-Evolved#1816]
**关于哪一项功能**
aria2 rpc下载

**问题描述**

在任意视频页面，例如我刚刚测试的 https://www.bilibili.com/av672971836
使用附加功能的下载视频--aria2 rpc功能aria2会成功创建任务但无法开始下载，报告
![image](https://user-images.githubusercontent.com/19909103/117099967-1a74bf80-ada5-11eb-8b65-6df83f208e91.png)
而直接下载可以正常使用。
本来直接下载可以用也不影响什么体验，但有些视频尤其是番剧无法直接下载，只能使用导出下载(由于体积)。
四天前这个功能应该还正常工作

**脚本版本**

preview offline 1015.19 应当是最新

**浏览器版本**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.51
就是 edge chromium版 90（最新stable）

**错误信息**

是aria2报的错，应该是b站新的什么限制之类
![image](https://user-images.githubusercontent.com/19909103/117099902-f618e300-ada4-11eb-9243-2d1695a72cf8.png)

**附加截图**

**Comment by the1812** [comment]
可能跟你rpc的配置有关系? 我试了下你发的视频可以用rpc下

**Comment by TTTPOB** [comment]
> 可能跟你rpc的配置有关系? 我试了下你发的视频可以用rpc下

非常抱歉，可能是偶发现象，我今天看到评论去试了一下确实已经可以了
