### ISSUE TITLE
部分 `互动视频` 标签丢失

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#1817]
**关于哪一项功能**
自动定位到播放器

**问题描述**
启用 `自动定位到播放器` 后，部分标题较长的互动视频标题前的 `互动视频` 标签会被挤掉一部分或者没掉，如 [av498409662](https://www.bilibili.com/video/av498409662)、[av97998722](https://www.bilibili.com/video/av61901788)

**脚本版本**
正式版 v1.12.4
预览离线版 v1015.19

**浏览器版本**
百分浏览器 4.3.9.248（正式版本） （64 位） (Chromium 86.0.4240.198)
Chrome 90.0.4430.93（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/49396421/117238536-a4815e80-ae5f-11eb-85dc-de8b9b709bbd.png)
![image](https://user-images.githubusercontent.com/49396421/117238555-b06d2080-ae5f-11eb-93ee-bd4151ada9d3.png)

**Comment by the1812** [comment]
根本原因应该和 #1808 一致.
