### ISSUE TITLE
b站首页变成了原版的样式，并且左边的菜单按钮也不见了

### ISSUE THREAD

**Issue by TTTPOB** [the1812/Bilibili-Evolved#182]
**关于哪一项功能**

**问题描述**

打开B站即可（

**脚本版本**

offline preview 413.12

**浏览器版本**

在我的所有浏览器上都出现
edge chromium 78.0.262.0
chrome 76.0.3809.132
firefox 71.0a1 (2019-09-03) (64 位)

**错误信息**

userscript.html?id=0aed4e84-f284-4f99-8cd5-c72bbee3f7c9:4 ERROR: Execution of script 'Bilibili Evolved (Preview Offline)' failed! Cannot access 'offlineData' before initialization
eval @ userscript.html?id=0aed4e84-f284-4f99-8cd5-c72bbee3f7c9:4

**附加截图**
![image](https://user-images.githubusercontent.com/19909103/64186010-b2b7f400-cea0-11e9-9c58-262ff144c616.png)

**Comment by the1812** [comment]
再检查下更新吧, 这是中午的一个有问题的测试版本, 下午1点左右已经修复了

**Comment by TTTPOB** [comment]
啊这样，好的
