### ISSUE TITLE
在视频播放页的简介 夜间模式下字体是黑色的（和背景是一个颜色的），看不见

### ISSUE THREAD

**Issue by whoisfancy** [the1812/Bilibili-Evolved#1822]
**关于哪一项功能**

**问题描述**
在视频播放页的简介 夜间模式下字体是黑色的（和背景是一个颜色的），看不见 所有的视频都是

**脚本版本**
Preview v1.12.6

**浏览器版本**
EDGE 90.0.818.51

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/51506435/117533111-7a759b00-b01d-11eb-8619-faac5364816c.png)

**Comment by the1812** [comment]
同时`自动展开视频简介`也失效了

**Comment by pcpc8888** [comment]
确实，我也发现了

**Comment by HCShuai** [comment]
chrome浏览器夜间模式也是同样的问题、貌似是简介颜色变了。

**Comment by MaxwellYe0815** [comment]
B站那边对简介更新了，就都失效了

**Comment by the1812** [comment]
~~b站改名部~~

**Comment by imThree** [comment]
+1 遇到了同样的问题。

**Comment by PurpleBeeZX** [comment]
+1同

**Comment by wlm3201** [comment]
+1，用光标反白麻烦

**Comment by tliu14** [comment]
我做了粗糙修复,
插件安装链接: https://greasyfork.org/zh-CN/scripts/426295-bilibili-evolved-issues-partial-and-temporary-fix
插件源码: (其实就两行)
// ==UserScript==
// @name         Bilibili Evolved Issues Partial and Temporary Fix
// @namespace    http://tampermonkey.net/
// @version      1.1
// @description  Fix Bilibili Evolved issue: video description color and auto-spread
// @author       Tianbao
// @match        *://*.bilibili.com/*
// @grant        none
// ==/UserScript==
 
(function() {
    'use strict';
 
    // Your code here...
    window.onload = function() {
        document.getElementsByClassName('desc-info desc-v2 open')[0].style.color = 'grey'
        console.log('视频简介区文字显示修复, 颜色: 灰')
        document.getElementsByClassName('desc-info desc-v2 open')[0].style.height = 'auto'
        console.log('视频简介区自动展开修复, 高度: 自动')
    };
 
})();
