### ISSUE TITLE
开启触摸支持后出现多余 且无法点击的按钮

### ISSUE THREAD

**Issue by HinataKato** [the1812/Bilibili-Evolved#1825]
**关于哪一项功能**
播放器触摸支持

**问题描述**
在设置界面 开启 其他-播放器触摸支持即可触发这个无法点击的按钮
元素看起来是选集按钮 但是我测试的视频没有多P

**脚本版本**
Preview Offline v1027.13
Preview v1.12.7

**浏览器版本**
Chrome 90.0.4430.93

**错误信息**
无错误输出

**附加截图**
关闭播放器触摸支持
![image](https://user-images.githubusercontent.com/57648531/117547699-79fff300-b063-11eb-9b11-783941ce55ef.png)

开启播放器触摸支持
![image](https://user-images.githubusercontent.com/57648531/117547629-27263b80-b063-11eb-80b5-55cd113470ed.png)

**Comment by the1812** [comment]
是选集, 触摸支持会强制所有按钮显示
