### ISSUE TITLE
极小部分视频播放页不适配夜间模式

### ISSUE THREAD

**Issue by Tinhone** [the1812/Bilibili-Evolved#1827]
**关于哪一项功能**
夜间模式适配

**问题描述**
有时候点开一个视频就会出现这个bug，有些可以通过刷新页面恢复原样，但有些不能
比如：https://www.bilibili.com/video/av760470732

**脚本版本**
正式版1.12.4

**浏览器版本**
Firefox85.0（64位）

**错误信息**
![图片](https://user-images.githubusercontent.com/81268244/117622119-e0d8f580-b1a4-11eb-8d1b-4aefd0e01d9d.png)

**附加截图**
![图片](https://user-images.githubusercontent.com/81268244/117622726-87bd9180-b1a5-11eb-9546-aa84810d59e0.png)

**Comment by the1812** [comment]
设置里换一下热更新源试试? 看截图里连接 GitHub 的源失败了

**Comment by the1812** [comment]
会不会是有别的插件冲突了?

**Comment by pcpc8888** [comment]
我这里点开没问题orz

**Comment by Tinhone** [comment]
> 
> 
> 会不会是有别的插件冲突了?

我应该是没有装含类似功能的插件...

**Comment by Tinhone** [comment]
问题已经无法复现，issue关掉了
