### ISSUE TITLE
添加DASH格式下载

### ISSUE THREAD

**Issue by aliofwind** [the1812/Bilibili-Evolved#183]
**关于哪一项功能**

现在正在测试的4K分辨率和已实装在客户端的HEVC编码都是DASH独占，FLV封装正在逐渐变成低优先级的兼容或备份选项
**期望的效果**
受限于DASH特性的原因，下载DASH确实需要手动重新封装音视频，但可以把DASH下载作为一个实验性功能先提供解析下载的部分

**脚本版本**

预览离线版

**Comment by the1812** [comment]
对编码有要求吗, 有的视频同时有`avc1.640033`和`hev1.1.6.L150.90`两种编码, 我应该选择哪一个?

**Comment by aliofwind** [comment]
默认avc吧，hevc可以作为第二选项
其实hevc更省码率，网页播放器只能avc的原因是chrome为了推广VP9编码不提供hevc的解码器，Firefox就跟屁虫，所以现在hevc编码的流只在手机app里提供

**Comment by the1812** [comment]
可以更新试试了, 格式选`DASH`应该就能够下载`.m4s`文件

**Comment by aliofwind** [comment]
下载是可以了，就是文件名能不能把视频用mp4，音频用m4a区分开来，现在1.m4s和2.m4s做合并的时候容易搞混

**Comment by the1812** [comment]
可以了, 顺便问一下应该怎么合并它们?

**Comment by aliofwind** [comment]
合并的话我是直接用ffmpeg合并
`ffmpeg -i 视频.mp4 -i 音频.m4a -c copy 合并后视频.mp4`

**Comment by the1812** [comment]
好的 多谢
