### ISSUE TITLE
夜间模式的视频简介文字透明

### ISSUE THREAD

**Issue by locustetc** [the1812/Bilibili-Evolved#1830]
**关于哪一项功能**
夜间模式 视频播放页面的简介

**问题描述**

夜间模式的视频简介文字透明

**脚本版本**

正式版的1.12.4，发现问题后安装offline版测试依然有问题

**浏览器版本**

360急速
**错误信息**

**附加截图**
没找到截图上传按钮，请参考另一条关于夜间模式的Issue，截图内的视频简介有同样问题。

**Comment by the1812** [comment]
你都知道有另一条为啥又开一个...

**Comment by locustetc** [comment]
> 你都知道有另一条为啥又开一个...

我反应的是问题，图片可以参考那边的，但是他没有反应这个问题。

**Comment by locustetc** [comment]
![image](https://user-images.githubusercontent.com/14189813/117653961-ac2a6580-b1c7-11eb-86e3-747602c97adf.png)

**Comment by the1812** [comment]
你这不就跟 #1822 的一样吗

**Comment by locustetc** [comment]
原来已经有人反应了，那我删掉？

**Comment by the1812** [comment]
close 掉就行了
