### ISSUE TITLE
脚本无法适用于遨游6浏览器。

### ISSUE THREAD

**Issue by c982852681** [the1812/Bilibili-Evolved#1833]
**关于哪一项功能**

**问题描述**
正式版和离线版安装后无法在遨游6里实装应用

**脚本版本**
所有版本

**浏览器版本**
版本6.1.2.1000（64 位）0508

**错误信息**

**附加截图**

**Comment by the1812** [comment]
遨游6的Chromium内核版本是多少? (不是遨游的浏览器版本

**Comment by Geeyun-JY3** [comment]
看 [官网更新日志](https://www.maxthon.cn/mx6/changelog/) 就应该不是 Chromium 内核版本的问题。不过这些国产套壳浏览器也说不准……
![image](https://user-images.githubusercontent.com/49396421/117758938-7fbd2a80-b255-11eb-8d86-0a6f1e8e0b36.png)

**Comment by the1812** [comment]
那得看看控制台输出了
