### ISSUE TITLE
顶栏添加页面判断

### ISSUE THREAD

**Issue by SettingDust** [the1812/Bilibili-Evolved#184]
**关于哪一项功能**

全部功能

**问题描述**

打开任意api页面（无顶栏），会自动添加顶栏

**脚本版本**

Bilibili Evolved (Preview)
1.8.21

**Comment by Coulomb-G** [comment]
你用的是哪款浏览器和用户脚本管理器?方便截个控制台报错的图么?

**Comment by SettingDust** [comment]
> 你用的是哪款浏览器和用户脚本管理器?方便截个控制台报错的图么?

问题不是错误，是打开任意一个本身没有顶栏的页面会被添加，导致一些api页面也会有顶栏

**Comment by Coulomb-G** [comment]
居然是568么233333
我这边在api页面没有复现这个情况
![(@(~1@9T1IIGADFEKF@THGC](https://user-images.githubusercontent.com/43007114/64343981-1d436e00-d020-11e9-935e-c8ae64f7acda.png)

**Comment by the1812** [comment]
顶栏是有页面判断的, 正常情况下api页面没有顶栏的.

`src/styles/custom-navbar/custom-navbar.js`
```JavaScript
/*...*/
const supportedUrls = [
  "/www.bilibili.com",
  "/t.bilibili.com",
  "/search.bilibili.com",
  "/space.bilibili.com",
  "/account.bilibili.com",
  "/pay.bilibili.com",
  "/member.bilibili.com",
  "/big.bilibili.com",
  "/message.bilibili.com",
  "/app.bilibili.com",
  "/passport.bilibili.com",
]
const unsupportedUrls = [
  "/t.bilibili.com/lottery/h5/index/#/result",
  "/member.bilibili.com/video/upload",
]
if (!supportedUrls.some(it => document.URL.includes(it))
  || unsupportedUrls.some(it => document.URL.includes(it))) {
  showWidget = false
  return attributes
}
/*...*/
```

**Comment by SettingDust** [comment]
> 顶栏是有页面判断的, 正常情况下api页面没有顶栏的.
> 
> `src/style/custom-navbar/custom-navbar.js`
> 
> ```js
> /*...*/
> const supportedUrls = [
>   "/www.bilibili.com",
>   "/t.bilibili.com",
>   "/search.bilibili.com",
>   "/space.bilibili.com",
>   "/account.bilibili.com",
>   "/pay.bilibili.com",
>   "/member.bilibili.com",
>   "/big.bilibili.com",
>   "/message.bilibili.com",
>   "/app.bilibili.com",
>   "/passport.bilibili.com",
> ]
> const unsupportedUrls = [
>   "/t.bilibili.com/lottery/h5/index/#/result",
>   "/member.bilibili.com/video/upload",
> ]
> if (!supportedUrls.some(it => document.URL.includes(it))
>   || unsupportedUrls.some(it => document.URL.includes(it))) {
>   showWidget = false
>   return attributes
> }
> /*...*/
> ```

https://space.bilibili.com/ajax/member/getSubmitVideos?pagesize=100&mid=433351

所以我说别用域名，用class/id

**Comment by the1812** [comment]
早说是space嘛... 我们一直以为是`api.bilibili.com`

**Comment by the1812** [comment]
如果用class/id的话应该怎么做?

**Comment by SettingDust** [comment]
> 如果用class/id的话应该怎么做?

判断本身的topbar是否存在

**Comment by the1812** [comment]
原版的顶栏不同页面class都不一样, 而且有些页面比如动态的顶栏是延迟加载的...
