### ISSUE TITLE
question：加载时间问题

### ISSUE THREAD

**Issue by pcpc8888** [the1812/Bilibili-Evolved#1845]
**关于哪一项功能**
样式相关功能

**问题描述**
页面在完全加载后才受到脚本的影响，故夜间模式会先白一下，主页会先显示一下原版主页。加载模式已经选了自动
（与Greasemonkey兼容性描述中表现的一样）

**脚本版本**
Stable v1.12.8

**脚本管理器**
Tampermonkey4.12

**浏览器版本**
版本 90.0.4430.212

**错误信息**
                         Release 2.6.1. Powered by jinkela-core 2.8.9.         \/            \/
script_injector.js:2 pakku ajax: injecting hook
sentry-5.7.1.min.js:2 pakku: [to developers] Web Worker is disabled for compatibility reasons
(anonymous) @ sentry-5.7.1.min.js:2
sentry-5.7.1.min.js:2 pakku ajax: hook set
script_injector.js:2 pakku ajax: injecting hook
xhr_hook.js:2 pakku: [to developers] Web Worker is disabled for compatibility reasons
(anonymous) @ xhr_hook.js:2
xhr_hook.js:2 pakku ajax: hook set
userscript.html?name=%E4%B8%80%E9%94%AE%E7%A6%BB%E7%BA%BF%E4%B8%8B%E8%BD%BD%2B.user.js&id=b0c7bcc4-133a-4f9b-80dd-06e61bfc3d42:5 Tampermonkey: couldn't load @require from URL https://greasyfork.org/scripts/398224-base64-v0-2-1/code/base64_v021.js
tms_b0c7bcc4_133a_4f9b_80dd_06e61bfc3d42 @ userscript.html?name=%E4%B8%80%E9%94%AE%E7%A6%BB%E7%BA%BF%E4%B8%8B%E8%BD%BD%2B.user.js&id=b0c7bcc4-133a-4f9b-80dd-06e61bfc3d42:5
userscript.html?name=Bilibili%20Evolved.user.js&id=abe8d7f2-1dc4-4246-9e11-087c192a229f:13210 scheduled bundle update
userscript.html?name=%E4%B8%80%E9%94%AE%E7%A6%BB%E7%BA%BF%E4%B8%8B%E8%BD%BD%2B.user.js&id=b0c7bcc4-133a-4f9b-80dd-06e61bfc3d42:5 Tampermonkey: couldn't load @require from URL https://greasyfork.org/scripts/398224-base64-v0-2-1/code/base64_v021.js
tms_b0c7bcc4_133a_4f9b_80dd_06e61bfc3d42 @ userscript.html?name=%E4%B8%80%E9%94%AE%E7%A6%BB%E7%BA%BF%E4%B8%8B%E8%BD%BD%2B.user.js&id=b0c7bcc4-133a-4f9b-80dd-06e61bfc3d42:5
userscript.html?name=Bilibili%20Evolved.user.js&id=abe8d7f2-1dc4-4246-9e11-087c192a229f:13210 scheduled bundle update
userscript.html?name=Bilibili%20Evolved.user.js&id=abe8d7f2-1dc4-4246-9e11-087c192a229f:13210 downloading bundle
userscript.html?name=Bilibili%20Evolved.user.js&id=abe8d7f2-1dc4-4246-9e11-087c192a229f:13210 downloading bundle
userscript.html?name=Bilibili%20Evolved.user.js&id=abe8d7f2-1dc4-4246-9e11-087c192a229f:13210 zip version = 1.12.4
userscript.html?name=Bilibili%20Evolved.user.js&id=abe8d7f2-1dc4-4246-9e11-087c192a229f:13210 bundle version not match. current = 1.12.8, latest = 1.12.4
userscript.html?name=Bilibili%20Evolved.user.js&id=abe8d7f2-1dc4-4246-9e11-087c192a229f:13210 zip version = 1.12.4
userscript.html?name=Bilibili%20Evolved.user.js&id=abe8d7f2-1dc4-4246-9e11-087c192a229f:13210 bundle version not match. current = 1.12.8, latest = 1.12.4
script_injector.js:2 pakku ajax: injecting hook
xhr_hook.js:2 pakku: [to developers] Web Worker is disabled for compatibility reasons
(anonymous) @ xhr_hook.js:2
xhr_hook.js:2 pakku ajax: hook set
userscript.html?name=%E4%B8%80%E9%94%AE%E7%A6%BB%E7%BA%BF%E4%B8%8B%E8%BD%BD%2B.user.js&id=b0c7bcc4-133a-4f9b-80dd-06e61bfc3d42:5 Tampermonkey: couldn't load @require from URL https://greasyfork.org/scripts/398224-base64-v0-2-1/code/base64_v021.js
tms_b0c7bcc4_133a_4f9b_80dd_06e61bfc3d42 @ userscript.html?name=%E4%B8%80%E9%94%AE%E7%A6%BB%E7%BA%BF%E4%B8%8B%E8%BD%BD%2B.user.js&id=b0c7bcc4-133a-4f9b-80dd-06e61bfc3d42:5
userscript.html?name=Bilibili%20Evolved.user.js&id=abe8d7f2-1dc4-4246-9e11-087c192a229f:13210 scheduled bundle update
userscript.html?name=Bilibili%20Evolved.user.js&id=abe8d7f2-1dc4-4246-9e11-087c192a229f:13210 downloading bundle
userscript.html?name=Bilibili%20Evolved.user.js&id=abe8d7f2-1dc4-4246-9e11-087c192a229f:13210 zip version = 1.12.4
userscript.html?name=Bilibili%20Evolved.user.js&id=abe8d7f2-1dc4-4246-9e11-087c192a229f:13210 bundle version not match. current = 1.12.8, latest = 1.12.4
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/international-home/1.international-home.edac28a06479bec4eb85cbcb8c949fc732b48613.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/international-home/international-home.edac28a06479bec4eb85cbcb8c949fc732b48613.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/vue.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/international-home/css/international-home.0.edac28a06479bec4eb85cbcb8c949fc732b48613.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/international-home/css/international-home.1.edac28a06479bec4eb85cbcb8c949fc732b48613.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**附加截图**
![捕获](https://user-images.githubusercontent.com/57062426/118005846-54355f80-b37d-11eb-8e4a-0e1f8bf85908.PNG)

**Comment by Devil-Z** [comment]
加载模式换成自动（同时）呢？我看了你的issue，才发现更新以后变成自动（延时），我刚该回去发现效果好多了，我的是90.0.818.56 版本的edge。不过这样也还是会先加载一瞬间的初始页面。

**Comment by the1812** [comment]
一瞬间的初始页面目前避免不了 (应该是因为脚本太大了)
夜间模式之类的样式是不受`加载模式`的影响的, 总是会尽快注入.
(Greasemonkey 比这要慢得多)

**Comment by pcpc8888** [comment]
> 加载模式换成自动（同时）呢？我看了你的issue，才发现更新以后变成自动（延时），我刚该回去发现效果好多了，我的是90.0.818.56 版本的edge。不过这样也还是会先加载一瞬间的初始页面。

我直接改成同时了，还是会有一下白

**Comment by pcpc8888** [comment]
> 一瞬间的初始页面目前避免不了 (应该是因为脚本太大了)
> 夜间模式之类的样式是不受`加载模式`的影响的, 总是会尽快注入.
> (Greasemonkey 比这要慢得多)

然而还是会慢一下，也就是说这是没办法的问题咯？

**Comment by pcpc8888** [comment]
> 一瞬间的初始页面目前避免不了 (应该是因为脚本太大了)
> 夜间模式之类的样式是不受`加载模式`的影响的, 总是会尽快注入.
> (Greasemonkey 比这要慢得多)

结果过了一晚上突然好了？很怪，打个close关了这个issue吧

**Comment by the1812** [comment]
有时候是可以马上进入夜间的, 取决于浏览器的时序调整了
