### ISSUE TITLE
移除电竞赛事失效

### ISSUE THREAD

**Issue by Jeremy-Hibiki** [the1812/Bilibili-Evolved#1851]
**关于哪一项功能**
首页移除电竞赛事功能失效

**问题描述**

设置里找不到这个选项了

**脚本版本**

离线预览版1029.12，正式版1.12.8

**浏览器版本**

Chrome 90.0.4430.212

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved/discussions/1839#discussioncomment-730411

**Comment by SHU-Jeremy-Hibiki** [comment]
emm我这附加功能只有“顶栏布局”

**Comment by Geeyun-JY3** [comment]
> emm我这附加功能只有“顶栏布局”

……
设置项搜索首页过滤
可能有 bug

**Comment by SHU-Jeremy-Hibiki** [comment]
OK谢谢

**Comment by the1812** [comment]
我更新日志忘写了, 这个功能移动到首页过滤里了
