### ISSUE TITLE
专栏中笔记夜间模式适配有问题

### ISSUE THREAD

**Issue by qiuyuyang910** [the1812/Bilibili-Evolved#1852]
**关于哪一项功能**
夜间模式适配
**问题描述**

https://www.bilibili.com/read/cv11271216
旁边的字体为黑色导致看不清
笔记为白色亮瞎眼
评论区也是白色

**脚本版本**

Stable v1.12.8

**浏览器版本**

Google Chrome 90.0.4430.212（正式版本） （64 位）

**错误信息**
![ ](https://user-images.githubusercontent.com/60593418/118149234-f0299e80-b443-11eb-9d32-65b827cbb81d.png)

**附加截图**
![QQ截图20210513233337](https://user-images.githubusercontent.com/60593418/118149473-29faa500-b444-11eb-99b6-39ae6b167131.png)

**Comment by the1812** [comment]
专栏改版了

**Comment by Geeyun-JY3** [comment]
答案在这里：
- https://www.bilibili.com/blackboard/activity-note.html
- https://www.bilibili.com/read/cv10976550

而且还多了个笔记分类的专栏首页要适配：https://www.bilibili.com/read/note
