### ISSUE TITLE
v1.12.8夜间模式视频简介依旧不显示

### ISSUE THREAD

**Issue by Devil-Z** [the1812/Bilibili-Evolved#1860]
**关于哪一项功能**

**问题描述**
夜间模式下全部视频，视频简介颜色与背景相同。置顶问题 #1822 里说在1.12.8里已经修复了，但是我目前看到简介里有艾特信息的时候才发现还是有这个问题，已经尝试过重装脚本。

**脚本版本**

Stable v1.12.8
![image](https://user-images.githubusercontent.com/19424844/118385013-d2278e00-b63d-11eb-8914-b180a70f17b8.png)
**浏览器版本**

Microsoft Edge
版本 90.0.818.62 (官方内部版本) (64 位).

**油猴版本**
![image](https://user-images.githubusercontent.com/19424844/118385209-a0172b80-b63f-11eb-9506-a5ad954b5e62.png)

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/19424844/118384956-2a11c500-b63d-11eb-9b3e-d5cd35370275.png)
![image](https://user-images.githubusercontent.com/19424844/118385095-a1942400-b63e-11eb-85ac-f66bba01826e.png)

**Comment by Geeyun-JY3** [comment]
清清缓存？

顺便借 issue 反馈：简介中高亮内容如 av/BV 号、用户在夜间模式均无跟随主题色

**Comment by Devil-Z** [comment]
> 清清缓存？
> 
> 顺便借 issue 反馈：简介中高亮内容如 av/BV 号、用户在夜间模式均无跟随主题色

多谢，我去研究了一下，原来是清理插件缓存，我之前清理过浏览器缓存，没得用。
得是从侧边栏里调用插件提供的缓存清理.
![image](https://user-images.githubusercontent.com/19424844/118386422-f721fe00-b649-11eb-8fc0-e9757f4396b4.png)
