### ISSUE TITLE
关于批量导出到IMD的问题

### ISSUE THREAD

**Issue by abcd8652** [the1812/Bilibili-Evolved#1869]
批量下载新番，导出IMD文件后，导入进IMD中下载来一堆未命名的视频文件，看的我一脸懵逼。
请问有没有办法让导出的IMD文件在IMD下载的时候，自动命名文件呢？

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/discussions/1301
没有.

**Comment by chaos-wan** [comment]
> 批量下载新番，导出IMD文件后，导入进IMD中下载来一堆未命名的视频文件，看的我一脸懵逼。
> 请问有没有办法让导出的IMD文件在IMD下载的时候，自动命名文件呢？

同问
