### ISSUE TITLE
TypeError: Cannot read property 'export' of undefined 

### ISSUE THREAD

**Issue by PrOmPt0** [the1812/Bilibili-Evolved#187]
TypeError: Cannot read property 'export' of undefined
    at ResourceManager.fetch (userscript.html?id=ff77d33f-70fc-485f-92d2-e326d4008c19:14246)

![image](https://user-images.githubusercontent.com/18552607/64469277-8a125180-d161-11e9-8389-2f2ac535ac70.png)

**Comment by the1812** [comment]
版本是多少? 1.9.0的话要更新到1.9.1

**Comment by PrOmPt0** [comment]
![image](https://user-images.githubusercontent.com/18552607/64469384-9f887b00-d163-11e9-952b-4f32f5c9ea65.png)
版本确实是1.9.0，更新完好了
