### ISSUE TITLE
1.9.1新版本 CPU占用率奇高 且很卡

### ISSUE THREAD

**Issue by fengziX** [the1812/Bilibili-Evolved#189]
8700K@5G 打开一个页面 占用率直接100%.....多个页面打开很久很久

**脚本版本**
1.9.1正式版

**浏览器版本**
Chrome 74

**Comment by the1812** [comment]
方便在预览版(v1.9.4)中试试吗? 我做了一些调整

**Comment by fengziX** [comment]
> 方便在预览版(v1.9.4)中试试吗? 我做了一些调整

CPU占用率大幅下降了 , 也恢复了流畅
