### ISSUE TITLE
新功能请求：热门视频去个性化

### ISSUE THREAD

**Issue by Commiter16** [the1812/Bilibili-Evolved#1891]
最近B站好像在搞灰度测试，把PC首页的热门视频换成跟手机端一样的个性化推荐了，希望能看到更多高质量的视频而不是被困在小圈子里。
可以用未登录的热门视频替换登录后的来实现这个功能吗？

**Comment by Geeyun-JY3** [comment]
重复，请善用搜索：#1842

另外，功能建议请发到讨论区。
