### ISSUE TITLE
拜年纪播放页显示问题

### ISSUE THREAD

**Issue by NightSharp** [the1812/Bilibili-Evolved#1895]
**关于哪一项功能**
自定义顶栏
另外拜年纪播放页的背景图片希望能够适配屏幕宽度

**问题描述**

“页面全屏”方式播放拜年纪播放页面的视频时
[https://www.bilibili.com/festival/2021bnj?bvid=BV1A54y1x7Dj](url)
顶栏无法被隐藏

**脚本版本**

预览版1.12.9

**浏览器版本**

Firefox 88.0.1 x64

**错误信息**

**附加截图**
![火狐截图_2021-05-29T10-21-59 741Z](https://user-images.githubusercontent.com/9748063/120066901-5c92d780-c0ab-11eb-8c7f-7a26ad783b39.png)

**Comment by Geeyun-JY3** [comment]
重复：#1549

不过说不定会修

**Comment by the1812** [comment]
懒得修了(
暂时关掉自定义顶栏直接看完就行了
