### ISSUE TITLE
高分屏下动态页出现元素重叠问题

### ISSUE THREAD

**Issue by JDYuuki** [the1812/Bilibili-Evolved#1897]
**关于哪一项功能**
显示问题

**问题描述**

[t.bilibili.com](t.bilibili.com)
在高分屏设备上会出现显示问题。
1. 高分辨率：
 ![image](https://user-images.githubusercontent.com/28827378/120083135-3eec5f00-c0f9-11eb-9d77-b96345a17edc.png)

2. 限定分辨率（1080p）：
 ![image](https://user-images.githubusercontent.com/28827378/120083170-604d4b00-c0f9-11eb-837e-051602ff39eb.png)

**脚本版本**
Stable v1.12.8

**浏览器版本**
Microsoft Edge with Chromium 91.0.864.37

**错误信息**
![image](https://user-images.githubusercontent.com/28827378/120083117-28460800-c0f9-11eb-9f1d-7292c4924646.png)

**附加截图**
index.8dd35ff3.css
![image](https://user-images.githubusercontent.com/28827378/120085009-57fc0c80-c107-11eb-8a88-1865a29134cf.png)

**其他**
删除以下CSS后，页面即恢复正常：
![image](https://user-images.githubusercontent.com/28827378/120085035-909be600-c107-11eb-9313-2bd7f95d67f5.png)
![image](https://user-images.githubusercontent.com/28827378/120085049-a7dad380-c107-11eb-95b0-60d49c8b1012.png)
![image](https://user-images.githubusercontent.com/28827378/120085058-b7f2b300-c107-11eb-8cf8-bf862f209a22.png)
![image](https://user-images.githubusercontent.com/28827378/120085070-c6d96580-c107-11eb-9f92-0838a6727d7e.png)
![image](https://user-images.githubusercontent.com/28827378/120085084-d35dbe00-c107-11eb-8961-78cbc9b4451e.png)
![image](https://user-images.githubusercontent.com/28827378/120085089-dc4e8f80-c107-11eb-9e16-bb4850d69e34.png)
![image](https://user-images.githubusercontent.com/28827378/120085099-e6708e00-c107-11eb-92ae-e28cd81080dc.png)
![image](https://user-images.githubusercontent.com/28827378/120085115-01430280-c108-11eb-8564-4771bef3790c.png)
![image](https://user-images.githubusercontent.com/28827378/120085125-0f911e80-c108-11eb-8a13-a78a53791f1c.png)

_删除后：_
![image](https://user-images.githubusercontent.com/28827378/120085151-3f402680-c108-11eb-8583-9901b18cfca5.png)

_临时解决：_
![image](https://user-images.githubusercontent.com/28827378/120085467-e920b280-c10a-11eb-8d4f-43c1829588c5.png)

**Comment by JDYuuki** [comment]
![image](https://user-images.githubusercontent.com/28827378/120085520-77953400-c10b-11eb-9f5f-143fbd777a77.png)
换了个干净的浏览器看了下，看上去是啊b做了所谓的高分屏优化，但其实还不如不做

**Comment by the1812** [comment]
同 #1888

**Comment by JDYuuki** [comment]
> 同 #1888

啊这，昨晚报issue的时候看了三页，愣是把1888跳过去了😂
