### ISSUE TITLE
现在哔哩哔哩进入视频页面后会自动播放视频，导致显示封面功能失效

### ISSUE THREAD

**Issue by GalaxySnail** [the1812/Bilibili-Evolved#1906]
## 关于哪一项功能

视频 - 播放前显示封面

## 问题描述

我在最近两天 (大约 2021-06-01) 发现，打开哔哩哔哩视频页面会自动开始播放视频，而不会等待，导致播放前显示封面功能失效。不知能否通过脚本恢复之前的打开页面后不自动播放视频的行为。

## 脚本版本

Preview v1.12.9, 内容包: c3f1b40

## 浏览器版本

Windows10 20H2 64bit
Chromium 89.0.4389.114 64bit （从[Woolyss](https://chromium.woolyss.com/)下载的Installer版本）

**Comment by Geeyun-JY3** [comment]
自动开播可以关……：
![image](https://user-images.githubusercontent.com/49396421/120433986-76376600-c3ae-11eb-8487-7cbcd9af8d5c.png)

**Comment by GalaxySnail** [comment]
抱歉（手动捂脸）很长时间没用过这个设置了，发issue前还找了半天没找到。
非常感谢

**Comment by shimakotodo** [comment]
> 自动开播可以关……：
> ![image](https://user-images.githubusercontent.com/49396421/120433986-76376600-c3ae-11eb-8487-7cbcd9af8d5c.png)

捂脸...特意翻墙来GitHub准备发issue求助，幸好先搜索了一下。

**Comment by GalaxySnail** [comment]
> 捂脸...特意翻墙来GitHub准备发issue求助，幸好先搜索了一下。

你也遇到了这个问题了？好奇你是不是在用 bilibili helper 浏览器拓展，我经过测试发现很可能是这个拓展更新导致“自动开播”被打开的。我刚在那边提交了 [issue](https://github.com/bilibili-helper/bilibili-helper-o/issues/850)

**Comment by MC-dusk** [comment]
> 
> 
> > 捂脸...特意翻墙来GitHub准备发issue求助，幸好先搜索了一下。
> 
> 你也遇到了这个问题了？好奇你是不是在用 bilibili helper 浏览器拓展，我经过测试发现很可能是这个拓展更新导致“自动开播”被打开的。我刚在那边提交了 [issue](https://github.com/bilibili-helper/bilibili-helper-o/issues/850)

去看了一下这个`bilibili helper`，功能感觉大同小异，但最近负面评价很多啊😅
