### ISSUE TITLE
B站动态评论区UP主图标

### ISSUE THREAD

**Issue by Tinhone** [the1812/Bilibili-Evolved#1909]
**关于哪一项功能**
应该是主题色相关
**问题描述**
如果动态里up主有再发一条评论，那么这条评论会带up主标识
![图片](https://user-images.githubusercontent.com/81268244/120634024-621e6200-c49d-11eb-817e-2c0162ffbb42.png)
（↑这是插件关闭状态下的）
![图片](https://user-images.githubusercontent.com/81268244/120634174-85e1a800-c49d-11eb-8580-8043d9e581c6.png)
（↑这是插件开启状态下的）
非常难看啊
**脚本版本**
正式版1.12.8
**浏览器版本**
Firefox85.0（64位）
**错误信息**
![图片](https://user-images.githubusercontent.com/81268244/120634447-d6f19c00-c49d-11eb-8c7e-f11ef6176629.png)

**Comment by Geeyun-JY3** [comment]
改了，改成客户端的样式了。忘记以前是长啥样的了。

**Comment by Tinhone** [comment]
> 
> 
> 改了，改成客户端的样式了。~忘记以前是长啥样的了。~
> 之前长这样：
> ![](https://user-images.githubusercontent.com/79303639/108473802-79a85500-72c9-11eb-9ef3-6f15e7d9ce5f.png)

但问题在于它周围的那一圈蓝色描边啊...

**Comment by the1812** [comment]
等更新吧

**Comment by Geeyun-JY3** [comment]
> 但问题在于它周围的那一圈蓝色描边啊

我知道，补充一下信息而已。修肯定是会修的。
