### ISSUE TITLE
简化直播间功能加载问题

### ISSUE THREAD

**Issue by HCLonely** [the1812/Bilibili-Evolved#191]
**关于哪一项功能**

简化直播间

**问题描述**

直播间加载完成后简化直播间功能不起效果，鼠标移动到侧边按钮的时候才会加载

**脚本版本**

预览版1.9.4

**浏览器版本**

Chrome 76

**错误信息**

**附加截图**

**Comment by the1812** [comment]
已修复 侧边的功能延迟加载忘了这个了\_(:3」∠)\_
