### ISSUE TITLE
汇报个bug，动态首页的右侧公告栏位置错误遮挡动态内容

### ISSUE THREAD

**Issue by mylongdays** [the1812/Bilibili-Evolved#1911]
已经确定是插件的问题，关闭后公告栏回到正确位置。Chrome版本 91.0.4472.77，之前因为别的bug升级过Chrome，然后没留意是不是立即就变成现在这样了，不确定是b站的问题还是升级Chrome的问题。

**Comment by Geeyun-JY3** [comment]
重复：#1888
而且预览版已经修了
