### ISSUE TITLE
评论区粉丝徽章显示错误

### ISSUE THREAD

**Issue by Malus-Mill** [the1812/Bilibili-Evolved#1914]
**关于哪一项功能**
评论区粉丝徽章显示错误

**问题描述**

打开动态，找到一个带牌子的评论

**脚本版本**

离线正式版 1029.10

**浏览器版本**

版本 91.0.4472.77（正式版本） （64 位）

**错误信息**

无

**附加截图**

  以下 为原版

**Comment by Malus-Mill** [comment]
![120734424-6db06e00-c51b-11eb-8524-a73cdc4658ca](https://user-images.githubusercontent.com/53999738/120735319-fa0f6080-c51c-11eb-8f3c-d934c4579b9a.png)
![120734164-04305f80-c51b-11eb-944b-28f60ad1c205](https://user-images.githubusercontent.com/53999738/120735321-fb408d80-c51c-11eb-84c7-e6cc759af241.png)
![120734181-0b576d80-c51b-11eb-9edf-87074aa5815c](https://user-images.githubusercontent.com/53999738/120735323-fb408d80-c51c-11eb-8ea6-58a114de00df.png)
![120734282-3215a400-c51b-11eb-933c-14462c5fd6da](https://user-images.githubusercontent.com/53999738/120735327-fbd92400-c51c-11eb-9ecd-5a5c11fff682.png)
![120734349-4fe30900-c51b-11eb-840d-6718f40aeb40](https://user-images.githubusercontent.com/53999738/120735328-fbd92400-c51c-11eb-8e05-37b08281390c.png)
以下为原版
![120734490-891b7900-c51b-11eb-9449-2665ca2260e3](https://user-images.githubusercontent.com/53999738/120735338-04315f00-c51d-11eb-942d-5ef9e4f46e30.png)
![120734530-9d5f7600-c51b-11eb-9b67-74eb537e0388](https://user-images.githubusercontent.com/53999738/120735339-04c9f580-c51d-11eb-938a-5af2480fc967.png)
![120734539-a3555700-c51b-11eb-8414-90688d3d577a](https://user-images.githubusercontent.com/53999738/120735341-05628c00-c51d-11eb-8d83-9dda38e4f09b.png)
![120734570-af411900-c51b-11eb-8543-9a7652de4860](https://user-images.githubusercontent.com/53999738/120735343-05fb2280-c51d-11eb-9d50-321538f7935a.png)

**Comment by Geeyun-JY3** [comment]
网页端才刚上的吧，和 #1909 一样，网页端终于跟上客户端了。
等适配吧。
