### ISSUE TITLE
b站某些链接更改导致简洁模式无法正常跳转

### ISSUE THREAD

**Issue by 1553767977** [the1812/Bilibili-Evolved#1918]
b站数码区归类到了科技区里面，好像现在不止这个区改了链接。
![QQ截图20210606180903](https://user-images.githubusercontent.com/39228172/120920652-71e2b400-c6f2-11eb-9c19-3b5abbddfdd5.png)
![QQ截图20210606181055](https://user-images.githubusercontent.com/39228172/120920678-8de65580-c6f2-11eb-9ba9-96a739869da0.png)

**Comment by Geeyun-JY3** [comment]
别急啊：https://github.com/the1812/Bilibili-Evolved/discussions/1511#discussioncomment-811558
