### ISSUE TITLE
创作中心没有适配暗黑模式

### ISSUE THREAD

**Issue by jack-0811** [the1812/Bilibili-Evolved#1922]
希望能够适配下

**Comment by Geeyun-JY3** [comment]
之前的表态是夜间放弃创作中心：https://github.com/the1812/Bilibili-Evolved/issues/759#issuecomment-664268233 、https://github.com/the1812/Bilibili-Evolved/issues/1146#issuecomment-720541842

**Comment by the1812** [comment]
懒得适配, 它老改来改去的
