### ISSUE TITLE
缩略图无法正确加载/不走梯子缩略图相应地址概率返回reset

### ISSUE THREAD

**Issue by th3weird0** [the1812/Bilibili-Evolved#1923]
你好朋友 我这边坐标北京联通 遇到了加载不出缩略图的问题

**关于哪一项功能**
首页缩略图加载

**问题描述**
![`U~MC4O~7)1`X6K}A50~_OB](https://user-images.githubusercontent.com/68617067/121273781-98c00680-c8fb-11eb-9d2a-07f4ed6bfe25.png)
![C)~LOUWGKWN$)1_25GX56%O](https://user-images.githubusercontent.com/68617067/121273788-9c538d80-c8fb-11eb-9d95-ff71484f5007.png)
右键错误图片资源inspect发现图片链接都是[i0.hdslb.com](https://i0.hdslb.com/),相似的[i1.hdslb.com](https://i1.hdslb.com/)无此问题 梯子设置DIRECT直连未解决*
***更新08点24分：右键相应图片资源新标签页打开有几率可以加载出来 也有几率reset**
**脚本版本**
离线预览版v1055.07
正式版v1.12.8

**浏览器版本**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
Google Chrome 版本 91.0.4472.77（正式版本） （64 位）

**错误信息**
![3O2 H@{_{V$0W)AGCNKSHAP](https://user-images.githubusercontent.com/68617067/121274245-aaee7480-c8fc-11eb-9750-c45997a0ae1f.png)

**附加截图**
已经附在上面项目里面了

**Comment by th3weird0** [comment]
或许并不是插件本身的问题(?)但是确实比较奇怪了

**Comment by the1812** [comment]
这是b站图片CDN的问题吧, 我只是把图片显示一下, 链接是b站给的

**Comment by th3weird0** [comment]
好的 谢谢你！
