### ISSUE TITLE
首页联系方式（联系客服）消失

### ISSUE THREAD

**Issue by yun-Tong** [the1812/Bilibili-Evolved#1929]
**关于哪一项功能**

首页过滤上联系客服

**问题描述**

不知道其他人怎么样，我这里联系客服直接没有了

**脚本版本**

tampermonkey
Stable v1.12.8

**浏览器版本**

谷歌双核浏览器
版本 4.1.7.26 （32 位）

**错误信息**

**附加截图**
错误截图
![image](https://user-images.githubusercontent.com/57837738/121386126-4f63cb80-c97c-11eb-8335-b288ab8ee991.png)
正常情况
![image](https://user-images.githubusercontent.com/57837738/121386269-6f938a80-c97c-11eb-96b5-5c95b48664f9.png)

**Comment by Tinhone** [comment]
我也有这情况  cwc

**Comment by the1812** [comment]
不是首页过滤, 开脚本就是会去掉这个
因为默认情况下挡住设置了

**Comment by Geeyun-JY3** [comment]
> 不是首页过滤, 开脚本就是会去掉这个
> 因为默认情况下挡住设置了

那为啥还要在 `首页过滤` 给个选项🌚

**Comment by the1812** [comment]
那是`联系方式`吧, 是网页最底下的那一块

**Comment by Geeyun-JY3** [comment]
> 那是`联系方式`吧, 是网页最底下的那一块

原来是搞错了🌚我是看到「联系」两字就以为是 `联系客服`。

**Comment by yun-Tong** [comment]
> > 不是首页过滤, 开脚本就是会去掉这个
> > 因为默认情况下挡住设置了
> 
> 那为啥还要在 `首页过滤` 给个选项🌚

那能不能添加一个选项是否开启，有时候想找客服真的很不方便

**Comment by yun-Tong** [comment]
> 不是首页过滤, 开脚本就是会去掉这个
> 因为默认情况下挡住设置了

那能不能添加一个选项是否开启，有时候想找客服真的很不方便

**Comment by the1812** [comment]
可以考虑设置在右边的时候不隐藏客服

**Comment by Mirionr** [comment]
把“联系客服”塞到附加功能里面试试？
