### ISSUE TITLE
启动时跳错

### ISSUE THREAD

**Issue by lidoworld** [the1812/Bilibili-Evolved#193]
**关于哪一项功能**

**问题描述**

跳错

**脚本版本**

正式1.9。5

**浏览器版本**

76.0.3809.132正式版
暴力猴v2.11.2

**错误信息**

index.html:12152 TypeError: Illegal invocation
    at ResourceManager.fetch (index.html:14328)

错误
Illegal invocation

**附加截图**
安装的时候似乎就看不到脚本内容 也无法在暴力猴中编辑
![image](https://user-images.githubusercontent.com/24887103/64579850-e91cd400-d3b6-11e9-9ebf-c4a194b41574.png)

但功能似乎都还正常展开中
![image](https://s2.ax1x.com/2019/09/10/nN0a3F.png)

**Comment by the1812** [comment]
脚本内容太多的话, 暴力猴不会显示也不能编辑
我试着修复了一下这个报错, 但是需要您重新安装脚本
