### ISSUE TITLE
【BUG】开启快捷键拓展后左右按键失效

### ISSUE THREAD

**Issue by DEabcdp** [the1812/Bilibili-Evolved#1931]
**关于哪一项功能**
默认快捷键（左←右→键）前进后退5s失效

**问题描述**
开启快捷键拓展，设置默认，播放任意视频时，按键盘上的←→两个键没有反应，没有前进或后退。
关闭快捷键拓展后，←→两键功能正常。
页面重现https://www.bilibili.com/video/BV11p411o73u

**脚本版本**
预览版1.12.9

**浏览器版本**
Microsoft Edge chromium 版本 91.0.864.41 (官方内部版本) (64 位)

**错误信息**
[Deprecation]SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See <URL> for more details.
4fc7f2c5-14c2-40d7-b670-b5f972e5ca53:18 [Deprecation]SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
(anonymous) @ 4fc7f2c5-14c2-40d7-b670-b5f972e5ca53:18
n @ video.70497832.js?v=20201013:170
load (async)
value @ video.70497832.js?v=20201013:171
n @ video.70497832.js?v=20201013:169
r @ video.70497832.js?v=20201013:177
e.createVideoElement @ video.70497832.js?v=20201013:236
t @ video.70497832.js?v=20201013:215
e.load @ video.70497832.js?v=20201013:222
(anonymous) @ video.70497832.js?v=20201013:222
(anonymous) @ video.70497832.js?v=20201013:218
e.urlChecker @ video.70497832.js?v=20201013:218
e.r @ video.70497832.js?v=20201013:218
e.getVideoData @ video.70497832.js?v=20201013:222
e.init @ video.70497832.js?v=20201013:219
e @ video.70497832.js?v=20201013:219
e.gray_loader_html5 @ video.70497832.js?v=20201013:230
e._initCallBack @ video.70497832.js?v=20201013:226
e._init @ video.70497832.js?v=20201013:226
e.init @ video.70497832.js?v=20201013:226
(anonymous) @ video.70497832.js?v=20201013:225
(anonymous) @ video.70497832.js?v=20201013:3
(anonymous) @ video.70497832.js?v=20201013:3
o @ video.70497832.js?v=20201013:3
Promise.then (async)
u @ video.70497832.js?v=20201013:3
(anonymous) @ video.70497832.js?v=20201013:3
u @ video.70497832.js?v=20201013:3
le @ video.70497832.js?v=20201013:224
(anonymous) @ BV11p411o73u:105
1ff471cf-64fc-4bcd-8ba8-157648f5d6db:1 [Deprecation]SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
onmessage @ 1ff471cf-64fc-4bcd-8ba8-157648f5d6db:1
1ff471cf-64fc-4bcd-8ba8-157648f5d6db:1 [Deprecation]SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
onmessage @ 1ff471cf-64fc-4bcd-8ba8-157648f5d6db:1
1ff471cf-64fc-4bcd-8ba8-157648f5d6db:1 [Deprecation]SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
onmessage @ 1ff471cf-64fc-4bcd-8ba8-157648f5d6db:1
1ff471cf-64fc-4bcd-8ba8-157648f5d6db:1 [Deprecation]SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
onmessage @ 1ff471cf-64fc-4bcd-8ba8-157648f5d6db:1
1ff471cf-64fc-4bcd-8ba8-157648f5d6db:1 [Deprecation]SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
onmessage @ 1ff471cf-64fc-4bcd-8ba8-157648f5d6db:1
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/seed/jinkela/header-v2/international-header-6e342487159cd3ec4dc73648bb29483e4dfce262-header.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

**附加截图**
![image](https://user-images.githubusercontent.com/62452364/121482923-300e8200-ca00-11eb-8822-93ffc8275656.png)

**Comment by DEabcdp** [comment]
已解决，原来是我的驱动问题

**Comment by DEabcdp** [comment]
emmm不是我驱动的问题，还是看视频时间长了大概率左右键失效，关闭“快捷键拓展”恢复正常。

**Comment by the1812** [comment]
是不是按`J`键的长跳跃也失效了

**Comment by DEabcdp** [comment]
> 是不是按`J`键的长跳跃也失效了

是这样的

**Comment by DEabcdp** [comment]
在更新日志中看到了作者的回复。我刚刚又试了试，试过正式版（重置设置）、预览版（重置设置），均存在一开启快捷键拓展即无法触发按键调整进度条。最后在控制台发现我每按一次左/右键，会多出两条信息。
![image](https://user-images.githubusercontent.com/62452364/122668992-b5a6e480-d1ed-11eb-956a-8b7d195c92b5.png)
![image](https://user-images.githubusercontent.com/62452364/122669027-e25afc00-d1ed-11eb-912c-e058511c1189.png)
点击后
![image](https://user-images.githubusercontent.com/62452364/122669046-028abb00-d1ee-11eb-8632-fbaa64989c77.png)
`(()=>(e,i)=>{const t=["https://www.bilibili.com/bangumi/","https://www.bilibili.com/video/","https://www.bilibili.com/cheese/","https://www.bilibili.com/watchlater/","https://www.bilibili.com/medialist/play/","https://www.bilibili.com/festival/2021bnj"];let o=undefined;if(t.some((e=>document.URL.startsWith(e)))){const t=e=>({event:i})=>{const t=new MouseEvent("click",{..._.pick(i,"ctrlKey","shiftKey","altKey","metaKey")});if(typeof e==="string"){var o;(o=dq(e))===null||o===void 0?void 0:o.dispatchEvent(t)}else{e.dispatchEvent(t)}};const n=e=>()=>{const i=dq(".bilibili-player-video video");console.log(`[keymap] requested video time change, delta = ${e}`);if(!i){console.log("[keymap] video element not found");return}if(!unsafeWindow.player){console.log("[keymap] fallback");i.currentTime+=e}console.log("[keymap] player API seek");unsafeWindow.player.seek(i.currentTime+e,i.paused)};let a;const l=(e,i)=>{let t=dq(".keymap-tip");if(!t){const o=dq(".bilibili-player-video-wrap");if(!o){return}o.insertAdjacentHTML("afterbegin",`\n<div class="keymap-tip-container">\n<i class="keymap-tip-icon mdi ${i}"></i>\n<div class="keymap-tip">${e}</div>\n</div>\n`);t=dq(".keymap-tip")}t.innerHTML=e;const o=dq(".keymap-tip-container");const n=dq(o,".mdi");n.classList.remove(...n.classList.values());n.classList.add("mdi",i);if(a){clearTimeout(a)}o.classList.add("show");a=window.setTimeout((()=>{o.classList.remove("show")}),2e3)};const s=e=>async()=>{const{VideoSpeedController:t}=await i.importAsync("video-speed-controller");const o=await t.getInstance();e(o,t.supportedRates);l(`${o.playbackRate}x`,"mdi-fast-forward")};const r={fullscreen:t(".bilibili-player-video-btn-fullscreen"),webFullscreen:t(".bilibili-player-video-web-fullscreen"),wideScreen:t(".bilibili-player-video-btn-widescreen"),volumeUp:()=>{const e=unsafeWindow.player.volume();unsafeWindow.player.volume(e+.1);l(`${Math.round(unsafeWindow.player.volume()*100)}%`,"mdi-volume-high")},volumeDown:()=>{const e=unsafeWindow.player.volume();unsafeWindow.player.volume(e-.1);const i=Math.round(unsafeWindow.player.volume()*100);if(i===0){l("静音","mdi-volume-off")}else{l(`${i}%`,"mdi-volume-high")}},mute:e=>{t(".bilibili-player-video-btn-volume .bilibili-player-iconfont-volume")(e);const i=unsafeWindow.player.isMute();if(i){l("已静音","mdi-volume-off")}else{l("已取消静音","mdi-volume-high")}},pictureInPicture:t(".bilibili-player-video-btn-pip"),coin:t(".video-toolbar .coin,.tool-bar .coin-info, .video-toolbar-module .coin-box, .play-options-ul > li:nth-child(2)"),favorite:t(".video-toolbar .collect, .video-toolbar-module .fav-box, .play-options-ul > li:nth-child(3)"),pause:t(".bilibili-player-video-btn-start"),like:(()=>{let e=true;return({event:i})=>{const t=dq(".video-toolbar .like, .tool-bar .like-info");i.preventDefault();const o=(e,i)=>{const o=new CustomEvent(e,i);t.dispatchEvent(o)};e=true;setTimeout((()=>e=false),200);o("mousedown",i);document.body.addEventListener("keyup",(i=>{i.preventDefault();o("mouseup",i);if(e){o("click",i)}}),{once:true})}})(),danmaku:()=>{const e=dq(".bilibili-player-video-danmaku-switch input");if(!e){return}e.checked=!e.checked;raiseEvent(e,"change")},longJumpBackward:n(-e.keymapJumpSeconds),longJumpForward:n(e.keymapJumpSeconds),jumpBackward:n(-5),jumpForward:n(5),playerMenu:()=>{const e=dq(".bilibili-player-video-wrap");if(!e){return}const i=e.getBoundingClientRect();e.dispatchEvent(new MouseEvent("contextmenu",{bubbles:true,cancelable:false,view:unsafeWindow,button:2,buttons:0,clientX:i.x+i.width/2-176.65/2,clientY:i.y+i.height/2-194/2}))},watchlater:t(".video-toolbar .ops .watchlater, .more-ops-list .ops-watch-later, .video-toolbar-module .see-later-box"),quickFavorite:t(".quick-favorite"),videoSpeedIncrease:s(((e,i)=>{e.setVideoSpeed(i.find((i=>i>e.playbackRate))||i[i.length-1])})),videoSpeedDecrease:s(((e,i)=>{e.setVideoSpeed([...i].reverse().find((i=>i<e.playbackRate))||i[0])})),videoSpeedReset:s((e=>{e.toggleVideoSpeed()})),videoSpeedForget:s((e=>{e.reset(true)})),takeScreenshot:t(".video-take-screenshot"),previousFrame:t(".prev-frame"),nextFrame:t(".next-frame"),seekBegin:()=>{if(!unsafeWindow.player){return}unsafeWindow.player.play();setTimeout((()=>{unsafeWindow.player.seek(0);const e=dq(".bilibili-player-video-toast-bottom .bilibili-player-video-toast-item:first-child .bilibili-player-video-toast-item-text span:nth-child(2)");if(e){e.textContent=" 00:00"}}))}};const d={fullscreen:"f",webFullscreen:"w",wideScreen:"t",volumeUp:"arrowUp",volumeDown:"arrowDown",mute:"m",pictureInPicture:"p",coin:"c",favorite:"s",pause:"space",like:"l",playerMenu:"`",longJumpForward:"j",longJumpBackward:"shift j",jumpBackward:"arrowLeft",jumpForward:"arrowRight",watchlater:"shift w",quickFavorite:"shift s",danmaku:"d",videoSpeedIncrease:"shift > 》 arrowUp",videoSpeedDecrease:"shift < 《 arrowDown",videoSpeedReset:"shift ? ？",videoSpeedForget:"shift : ：",takeScreenshot:"ctrl [shift] alt c",previousFrame:"shift arrowLeft",nextFrame:"shift arrowRight",seekBegin:"0"};const c=e=>Object.entries(e).map((([e,i])=>{const t=i.split(" ").filter((e=>e!==""));return{keys:t,action:r[e]||(()=>{})}}));(async()=>{const{loadKeyBindings:t}=await i.importAsync("key-bindings");const{presets:n}=await i.importAsync("key-binding-presets");addSettingsListener("keymapPreset",(()=>{const i=n[e.keymapPreset]||{};const a=c({...d,...i,...e.customKeyBindings});if(o){console.log("load preset",e.keymapPreset);o.bindings=a}else{o=t(a)}}),true);i.applyImportantStyle("keymapStyle")})()}return{reload:()=>o&&(o.enable=true),unload:()=>o&&(o.enable=false)}})();`

**Comment by DEabcdp** [comment]
最新发现，大部分视频可以调进度，少数视频不能调，比如我发的重现链接，目前还没有找到规律。

**Comment by GeassAng** [comment]
自定义倍速失效的话，自定义快捷键也会失效。。。

**Comment by the1812** [comment]
在视频上右键两次然后审查元素看看? 看日志似乎找不到视频元素了
大概长这样的:
![image](https://user-images.githubusercontent.com/26504152/122766104-ba45c880-d2d3-11eb-9d58-59b33224191e.png)

顺便也可以切换到 Console 里运行下这些代码试试:
```js
document.querySelector('.bilibili-player-video video')
bilibiliEvolved.dq('.bilibili-player-video video')
```
![image](https://user-images.githubusercontent.com/26504152/122766268-eb25fd80-d2d3-11eb-8e26-9ba39d529cc4.png)

**Comment by DEabcdp** [comment]
> 在视频上右键两次然后审查元素看看? 看日志似乎找不到视频元素了
> 大概长这样的:
> ![image](https://user-images.githubusercontent.com/26504152/122766104-ba45c880-d2d3-11eb-9d58-59b33224191e.png)
> 
> 顺便也可以切换到 Console 里运行下这些代码试试:
> 
> ```js
> document.querySelector('.bilibili-player-video video')
> bilibiliEvolved.dq('.bilibili-player-video video')
> ```
> 
> ![image](https://user-images.githubusercontent.com/26504152/122766268-eb25fd80-d2d3-11eb-8e26-9ba39d529cc4.png)

元素是这样的：
![image](https://user-images.githubusercontent.com/62452364/122767920-b3b85080-d2d5-11eb-8891-d65ac38d4fc7.png)

控制台运行代码后无效，显示如下：
![image](https://user-images.githubusercontent.com/62452364/122767869-a9965200-d2d5-11eb-994c-455eca536e1d.png)

**Comment by the1812** [comment]
原来如此, 不过有点难修, 这个东西影响范围还挺大的

**Comment by binsee** [comment]
相关内容：
![image](https://user-images.githubusercontent.com/5285894/125279126-2309e900-e346-11eb-9cb8-d26a281e2f6a.png)

> `closed` 拒绝从js外部访问关闭的shadow root节点
参考文档： https://developer.mozilla.org/zh-CN/docs/Web/API/Element/attachShadow

**Comment by binsee** [comment]
我这边测试修改以下代码可解决此问题，但不确定是否会引发其他问题，请参考

https://github.com/the1812/Bilibili-Evolved/blob/262a3f48919608ec13e0ae76c68522704b2482c1/src/video/keymap/keymap.ts#L29

```js
//  const video = dq('.bilibili-player-video video') as HTMLVideoElement 
// 改为
 const video = dq('.bilibili-player-video video,bwp-video') as HTMLVideoElement 
```

**Comment by the1812** [comment]
不只这一个功能用到`video`, `dq('video')` / `dq('.bilibili-player-video video')`的地方非常多, 如果 `bwp-video` 对象上的方法和 `video` 一样的话我可以让 `dq` 收到 `'video'` 之类的查询时自动加上 `', bwp-video'` 来解决

**Comment by binsee** [comment]
> 不只这一个功能用到`video`, `dq('video')` / `dq('.bilibili-player-video video')`的地方非常多, 如果 `bwp-video` 对象上的方法和 `video` 一样的话我可以让 `dq` 收到 `'video'` 之类的查询时自动加上 `', bwp-video'` 来解决

如果只是用来检测video是否已存在，用 `bwp-video` 代替是没有问题的，但用于操作video的状态，就不行了。
由于其他功能用的不多，所以我暂时不确定是否需要全部替换，但至少前进后退是可以的。

**Comment by binsee** [comment]
我在代码库中搜索 `dq('video')` / `dq('.bilibili-player-video video')`，认为是可以做替代的，但部分代码需要进行修改：

- 快捷键左右前进后退，见上述

- 点空降弹幕跳转到时间，需要改用 `unsafeWindow.player.getCurrentTime()` 和 `unsafeWindow.player.seek(time)` 、 `unsafeWindow.player.play()`  来操作
https://github.com/the1812/Bilibili-Evolved/blob/3626c5bf4bcc00af10690fcfadf4c1ecaacfd0dc/src/video/airborne-old.js#L54-L55

- 用 `unsafeWindow.player.getDuration()` 代替 `document.querySelector('.bilibili-player-video video').duration`
https://github.com/the1812/Bilibili-Evolved/blob/3626c5bf4bcc00af10690fcfadf4c1ecaacfd0dc/src/video/airborne-old.js#L67

- 调整音量，改用 `unsafeWindow.player.volume()` 获取 / `unsafeWindow.player.volume(i)` 设置
https://github.com/the1812/Bilibili-Evolved/blob/3626c5bf4bcc00af10690fcfadf4c1ecaacfd0dc/src/video/volume-overdrive.ts#L93-L94

- 这处我没明白是干嘛的，不确定是否要改及怎么改。或许用 `unsafeWindow.player.seek(time)` 和  `unsafeWindow.player.pause()` 组合
https://github.com/the1812/Bilibili-Evolved/blob/3626c5bf4bcc00af10690fcfadf4c1ecaacfd0dc/src/video/frame-playback/frame-playback.js#L20-L23

**Comment by binsee** [comment]
补充一下播放器js的信息：
https://s1.hdslb.com/bfs/static/player/main/video.3c7a3ebf.js?v=20201013

```js
/*! #metadata# @jsc/video: 2.61.1-rc.8634.0-55509dbf (2021-07-09T06:32:34.435Z) */
```

**Comment by binsee** [comment]
已更换预览版1.12.11，当前快捷键正常

**Comment by the1812** [comment]
新预览版里正常了是吗

**Comment by DEabcdp** [comment]
> 新预览版里正常了是吗

正常了
