### ISSUE TITLE
专栏再度改版所导致的暗黑模式不适配

### ISSUE THREAD

**Issue by Tinhone** [the1812/Bilibili-Evolved#1933]
**关于哪一项功能**
暗黑模式（话说它有几个名字了来着）

**问题描述**
样例：https://www.bilibili.com/read/cv114514
未开启插件↓
![图片](https://user-images.githubusercontent.com/81268244/121519326-2a2a9800-ca24-11eb-854c-6c3fece986c4.png)
开启插件↓
![图片](https://user-images.githubusercontent.com/81268244/121519405-429ab280-ca24-11eb-8137-f4c0ae814151.png)

**脚本版本**
正式版1.12.8

**浏览器版本**
Firefox85.0（64位）

**错误信息**
![图片](https://user-images.githubusercontent.com/81268244/121519786-b5a42900-ca24-11eb-9ae2-a5e8995b510e.png)

**附加截图**

**Comment by Tinhone** [comment]
这个挺影响体验的

**Comment by Geeyun-JY3** [comment]
重复：https://github.com/the1812/Bilibili-Evolved/issues/1692#issuecomment-858397278

**Comment by GZ-Juice** [comment]
> **关于哪一项功能**
> 暗黑模式（话说它有几个名字了来着）
> 
> **问题描述**
> 样例：https://www.bilibili.com/read/cv114514
> 未开启插件↓
> ![图片](https://user-images.githubusercontent.com/81268244/121519326-2a2a9800-ca24-11eb-854c-6c3fece986c4.png)
> 开启插件↓
> ![图片](https://user-images.githubusercontent.com/81268244/121519405-429ab280-ca24-11eb-8137-f4c0ae814151.png)
> 
> **脚本版本**
> 正式版1.12.8
> 
> **浏览器版本**
> Firefox85.0（64位）
> 
> **错误信息**
> ![图片](https://user-images.githubusercontent.com/81268244/121519786-b5a42900-ca24-11eb-9ae2-a5e8995b510e.png)
> 
> **附加截图**

啊对我也遇到了 专栏的字看不清也太难受了

**Comment by GZ-Juice** [comment]
> 这个挺影响体验的

啊对这个我也遇到了 太难受了

**Comment by TroyLin0218** [comment]
唔，专栏只能看图了，文字完全不能看了

**Comment by Jazzwind** [comment]
同样有这个问题，插眼

**Comment by pcpc8888** [comment]
同样，插眼

**Comment by Geeyun-JY3** [comment]
不用插了，几天前的 #1954 及后续的几个 commit 已修。
想知道 bug 修没修在最新预览离线版（Preview Offline）测一测便知。

摘抄 Issues 须知里的一段：
> 提示: 最好先在预览离线版(Preview Offline)中测试一下, 有些问题可能已经修复了但还未正式发布.
