### ISSUE TITLE
播放名侦探柯南时，不会自动连播。

### ISSUE THREAD

**Issue by huangsijun17** [the1812/Bilibili-Evolved#1941]
**关于哪一项功能**
“传统连播模式”

**问题描述**

播放名侦探柯南时，**不会**自动连播。

**脚本版本**

Preview v1.12.9
内容包: 952d0bf

**浏览器版本**

Microsoft Edge
版本 91.0.864.41 (官方内部版本) (64 位)

**错误信息**

略

**附加截图**
略

**Comment by the1812** [comment]
`传统连播模式`只控制有"自动连播"开关的地方, 我看了下番剧那边似乎没有.

**Comment by huangsijun17** [comment]
> `传统连播模式`只控制有"自动连播"开关的地方, 我看了下番剧那边似乎没有.

有开关，在这里：
![image](https://user-images.githubusercontent.com/31504595/122646932-4cbf5e00-d154-11eb-994e-deaa85d1c3e5.png)

现在每次打开番剧，都会被自动关闭。

**Comment by the1812** [comment]
那可就糟糕了... 这个地方脚本点不着, 自不自动继承的是上一次自动连播调整的值

**Comment by huangsijun17** [comment]
> 那可就糟糕了... 这个地方脚本点不着, 自不自动继承的是上一次自动连播调整的值

现在的问题是，这个值不继承了。

**Comment by the1812** [comment]
我刚试了是继承的啊, 继承是指上一次在另一个视频里因为`传统连播模式`而变动的那个开关的值, 比如看了一个多P视频后进入番剧就是自动下一集的

**Comment by huangsijun17** [comment]
> 我刚试了是继承的啊, 继承是指上一次在另一个视频里因为`传统连播模式`而变动的那个开关的值, 比如看了一个多P视频后进入番剧就是自动下一集的

继承非番剧的“自动连播”设置，但是在**番剧内**点“自动切集”则是不继承的。

也就是说，我必须开一个多P的非番剧，这样刷剧才会自动切集。要不然这个设置一改，刷新就改回去了。

**Comment by the1812** [comment]
番剧内点"自动切集"也是可以切集的, 中途没有观看其他视频的话刷新应该也会保留, 毕竟这个继承是b站的机制, 脚本只是在视频页那里动一动那个开关
