### ISSUE TITLE
无法视频内左键停留点赞/举报弹幕

### ISSUE THREAD

**Issue by lttlcj** [the1812/Bilibili-Evolved#1942]
**关于哪一项功能**
RT

**问题描述**
B站播放视频时左键停留弹幕会出现举报/点赞按钮，右键点击则会出现屏蔽/复制按钮，开启脚本后左键停留弹幕时无法实现举报/点赞的功能

**脚本版本**

正式版1.12.8

--

**浏览器版本**

QQ浏览器 10.8.4405.400 极速内核

**错误信息**
开启前：
![image](https://user-images.githubusercontent.com/68736436/121765217-f2366880-cb7b-11eb-8648-6bef9449f62f.png)
开启后：
![image](https://user-images.githubusercontent.com/68736436/121765249-2578f780-cb7c-11eb-9b03-eb4295778fc5.png)
左下角无脚本内部错误信息

**附加截图**
![F2C2GL388X%UGNM$}C)RFI8](https://user-images.githubusercontent.com/68736436/121765260-37f33100-cb7c-11eb-9141-6dae04ca56f1.jpg)
脚本开启后无法实现红框内停留功能

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved#安装
> 做好觉悟, 脚本开启后不能使用弹幕点赞和举报,
