### ISSUE TITLE
文章页面文字颜色错误

### ISSUE THREAD

**Issue by ZgblKylin** [the1812/Bilibili-Evolved#1943]
**关于哪一项功能**
深色模式
Win10系统启用深色模式，浏览器自动跟随深色模式

**问题描述**

https://www.bilibili.com/read/cv7646864/
文章页面的除了背景色，其它文字颜色、评论区颜色都没有反转，正文颜色和背景色完全相同，无法阅读

**脚本版本**

Preview v1.12.9

**浏览器版本**

Microsoft Edge Canary 版本 93.0.916.0 (官方内部版本) 

**错误信息**

**附加截图**
![Snipaste_2021-06-12_14-06-34](https://user-images.githubusercontent.com/13114351/121766865-75a98700-cb87-11eb-8fe0-5950790a7aa4.jpg)
![Snipaste_2021-06-12_14-06-43](https://user-images.githubusercontent.com/13114351/121766866-77734a80-cb87-11eb-8383-0eff7ffe97e2.jpg)

**Comment by Geeyun-JY3** [comment]
重复：#1933、https://github.com/the1812/Bilibili-Evolved/issues/1692#issuecomment-858397278
