### ISSUE TITLE
用的chrome，快捷键失效，不知道什么原因，油猴和Evolved都卸载重装过了也没用，但是Edge正常。

### ISSUE THREAD

**Issue by GeassAng** [the1812/Bilibili-Evolved#1944]
Bilibili Evolved | 1.12.8
-- | --

chrome版本 91.0.4472.101（正式版本） （64 位）
![1623542376(1)](https://user-images.githubusercontent.com/76535630/121791552-84427d80-cc1d-11eb-842f-b3268114315d.jpg)

只有↑↓音量键能用，其他连←→快进后退都用不了

**Comment by GeassAng** [comment]
![Uploading 1623542376(1).jpg…]()

**Comment by fujimiyagamu** [comment]
+1

**Comment by GeassAng** [comment]
严重影响使用。。望修复

**Comment by GeassAng** [comment]
顶不住 已经改用edge了。。。

**Comment by the1812** [comment]
影响使用就关掉`快捷键扩展`功能, 我这边试不出来也没法给你修复

**Comment by GeassAng** [comment]
> 影响使用就关掉`快捷键扩展`功能, 我这边试不出来也没法给你修复

不只是快捷键，倍速也失效了。。估计是我浏览器问题吧，小问题，导出一下脚本配置 用edge也挺香的
