### ISSUE TITLE
番剧和电影无法下载

### ISSUE THREAD

**Issue by yu-0209** [the1812/Bilibili-Evolved#1945]
**关于哪一项功能**
下载

**问题描述**

在电影播放页面和番剧播放页面开启脚本据没有下载选项

**脚本版本**

正式版1.12.8

**浏览器版本**

Chrome 91.0.4472.101

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/75165470/121800856-baf0b600-cc66-11eb-9460-7e8f2162cd8c.png)

**Comment by GeassAng** [comment]
那肯定啊，这收费内容给你下载人家法务部直接把作者冲了

**Comment by the1812** [comment]
什么电影

**Comment by yu-0209** [comment]
> 什么电影，我去学习看看

不用试了，之前是能下载的，现在不行了

**Comment by the1812** [comment]
是只有你不能下载吧

**Comment by yu-0209** [comment]
> 是只有你不能下载吧

？？你能下载？我之前是能下载的，后来就没了

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/122191811-a2320b80-cec5-11eb-92bd-b994e3e3f47a.png)

**Comment by Coulomb-G** [comment]
经测试,我这边是正常的.你需要反馈的话,请正常提供必要的信息

**Comment by Misaaya** [comment]
> 经测试,我这边是正常的.你需要反馈的话,请正常提供必要的信息

https://www.bilibili.com/bangumi/play/ep292002
您好，我的三体番剧也是同样的问题
![image](https://user-images.githubusercontent.com/23096078/124241852-b9702a80-db4e-11eb-9e94-db03e578aac6.png)

**Comment by yxh0** [comment]
出现这个问题的关键是chrome91导致的，试试看使用Firefox，使用Firefox可以解决这个问题

**Comment by Geeyun-JY3** [comment]
看起来是新版播放器的事：#1992

**Comment by the1812** [comment]
应该是新版播放器的问题了
