### ISSUE TITLE
关于夜间模式的问题

### ISSUE THREAD

**Issue by whoisfancy** [the1812/Bilibili-Evolved#1960]
**关于哪一项功能**
夜间模式

**问题描述**

https://www.bilibili.com/read/cv4669703/
在类似的专栏（B站专栏）页面中夜间模式会出现bug，详见附件

**脚本版本**

Preview v1.12.9
内容包: 56ca0ed

**浏览器版本**

EDGE 版本 91.0.864.48 (官方内部版本) (64 位)

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/51506435/122513526-15aa5900-d03d-11eb-9550-76059749c71c.png)
![image](https://user-images.githubusercontent.com/51506435/122513557-1e029400-d03d-11eb-915a-4b81be8c01e9.png)

**Comment by Geeyun-JY3** [comment]
看 置 顶：#1933

而且最新的预览离线版已经修了：https://github.com/the1812/Bilibili-Evolved/discussions/1956#discussioncomment-881475
