### ISSUE TITLE
不显示点赞、举报弹幕的菜单

### ISSUE THREAD

**Issue by Young-Lord** [the1812/Bilibili-Evolved#1963]
**关于哪一项功能**
播放器中，鼠标移动到弹幕上时无法显示点赞、举报的菜单

**问题描述**
随便打开一个视频，将鼠标移到弹幕上

**脚本版本**
正式版1.12.8

**浏览器版本**
Edge 92

**错误信息**
无

**附加截图**
![image](https://user-images.githubusercontent.com/51789698/122627469-38427d80-d0e2-11eb-91ae-00c3bc852833.png)
（此截图为关闭脚本后的截图，如果打开脚本就不会显示这个👍和❗）

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/122627520-8eafbc00-d0e2-11eb-929d-8613da42391f.png)

**Comment by Young-Lord** [comment]
好吧 谢谢答复

**Comment by Young-Lord** [comment]
话说为什么要这样设计呢

**Comment by the1812** [comment]
见 #966
