### ISSUE TITLE
"快捷键扩展"功能阻止方向键滚动网页

### ISSUE THREAD

**Issue by Young-Lord** [the1812/Bilibili-Evolved#1966]
**关于哪一项功能**
快捷键扩展

**问题描述**
开启"快捷键扩展"功能后，焦点在播放器外时无法使用方向键滚动网页

**脚本版本**
正式版1.12.8

**浏览器版本**
Edge 92

**Comment by Geeyun-JY3** [comment]
不是 bug，这功能就是这样的：
https://github.com/the1812/Bilibili-Evolved/blob/master/doc/features.md#视频
![image](https://user-images.githubusercontent.com/49396421/122643859-c0596f00-d144-11eb-929a-f58b861367df.png)
https://github.com/the1812/Bilibili-Evolved/discussions/1325#discussioncomment-214959

**Comment by the1812** [comment]
上下键是调整音量了, 不需要可以删掉
https://github.com/the1812/Bilibili-Evolved/blob/master/src/video/keymap/key-bindings.md

**Comment by Young-Lord** [comment]
经过实验，发现去除控制音量的快捷键（`bilibiliEvolved.settings.customKeyBindings={volumeUp:'',volumeDown:''}`）的话，就能实现聚焦时调用原生的音量控制，不聚焦时滚动网页，那为什么还要开启这个快捷键呢
况且应该没多少人会在看评论的时候用方向键调音量吧

**Comment by Geeyun-JY3** [comment]
> 经过实验，发现去除控制音量的快捷键（`bilibiliEvolved.settings.customKeyBindings={volumeUp:'',volumeDown:''}`）的话，就能实现聚焦时调用原生的音量控制，不聚焦时滚动网页，那为什么还要开启这个快捷键呢
> 况且应该没多少人会在看评论的时候用方向键调音量吧

就……你可以当做是在做其它原生快捷键扩展到全网页范围时顺便做的吧

**Comment by the1812** [comment]
我平时都是用滚轮的, 所以觉得不聚焦也能调音量挺方便
反正不需要可以删掉, 问题不大
