### ISSUE TITLE
能否增加关闭视频详情页直接播放的选项

### ISSUE THREAD

**Issue by K1zmo** [the1812/Bilibili-Evolved#1969]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
自动开播可以关……：
![image](https://user-images.githubusercontent.com/49396421/120433986-76376600-c3ae-11eb-8487-7cbcd9af8d5c.png)
