### ISSUE TITLE
稍后再看异常

### ISSUE THREAD

**Issue by Junonin** [the1812/Bilibili-Evolved#197]
**关于哪一项功能**
稍后再看

**问题描述**
稍后再看操作失败

**脚本版本**
正式版1.9.5

**浏览器版本**
Chrome 77

**错误信息**
稍后再看操作失败: strconv.ParseInt: parsing "undefined": invalid syntax

**附加截图**
![image](https://user-images.githubusercontent.com/45154395/65116137-23235100-da1b-11e9-98e6-05fad6a9b789.png)

**Comment by the1812** [comment]
是在哪个地方失败的? 视频里加稍后再看还是动态弹窗里加?

**Comment by Junonin** [comment]
在观看视频里点击
![image](https://user-images.githubusercontent.com/45154395/65404884-fa310080-de0c-11e9-85c7-4f3626640345.png)

**Comment by the1812** [comment]
似乎是因为没获取到av号... 请再在预览离线版中试试, 我把这个改成点击时再获取av号了
