### ISSUE TITLE
夜间模式番剧点评好像没适配

### ISSUE THREAD

**Issue by RingingVolcano** [the1812/Bilibili-Evolved#1971]
**关于哪一项功能**

夜间模式

**问题描述**

在番剧介绍页的点评中 字体颜色没有适配
eg.https://www.bilibili.com/bangumi/media/md28224095/

**脚本版本**

Preview v1.12.10

**浏览器版本**

Chrome 91

**错误信息**

**附加截图**
![4{(6%6NM2M3Y7DL3QR}%8A4](https://user-images.githubusercontent.com/72140353/122679569-fdddfb00-d21d-11eb-90e5-a1a0df116802.png)

**Comment by Geeyun-JY3** [comment]
强行关联，可以顺带做了🌚：https://github.com/the1812/Bilibili-Evolved/issues/1143#issuecomment-723038510
