### ISSUE TITLE
网页全屏顶栏没有隐藏,导致视频顶部被遮挡住了

### ISSUE THREAD

**Issue by miaokaicheng** [the1812/Bilibili-Evolved#1975]
**关于哪一项功能**

**问题描述**

使用网页全屏观看这个系列视频时:https://www.bilibili.com/bangumi/play/ss26291/
别的视频暂时没遇到过

**脚本版本**

正式版:1.12.10

**浏览器版本**

Chrome 版本 91.0.4472.106（正式版本） （64 位）

**错误信息**

控制台没有错误信息

**附加截图**
![image](https://user-images.githubusercontent.com/29976178/122757682-80bc8f80-d2ca-11eb-8308-9ab5428c41fc.png)
![image](https://user-images.githubusercontent.com/29976178/122758061-ef99e880-d2ca-11eb-8d33-3787168259ac.png)
![image](https://user-images.githubusercontent.com/29976178/122757883-b8c3d280-d2ca-11eb-8879-94a50791aeb8.png)

**Comment by zhang-anzhi** [comment]
我在名侦探柯南也遇到了，番剧视频出现此Bug #2021

**Comment by Geeyun-JY3** [comment]
应该就是播放器 3.0 的问题，建议归入 #1992
