### ISSUE TITLE
Safari版tampermonkey无法安装脚本

### ISSUE THREAD

**Issue by l8higher** [the1812/Bilibili-Evolved#1978]
系统版本：Catalina10.15.7
Safari版本：14.1.2
顺利点开安装界面，但是无法点击**安装**按钮。其余脚本没有问题。
![Snipaste_2021-06-22_11-05-47](https://user-images.githubusercontent.com/57839836/122857051-75a94400-d34a-11eb-8d20-bc24c10d35bd.png)

**Comment by FoundTheWOUT** [comment]
这个脚本体积比较大，又由于Safari 的“特性”，你可能要等个十来秒才能安装。

**Comment by l8higher** [comment]
> 这个脚本体积比较大，又由于Safari 的“特性”，你可能要等个十来秒才能安装。

等了十几秒，安装网页直接自动关闭了哎。

**Comment by FoundTheWOUT** [comment]
> 等了十几秒，安装网页直接自动关闭了哎。

点击下载源后除了油猴的标签页，还有一个新的标签页吧🤔，那个标签页你是不是退了。
`GitHub`源我没试过，你可以尝试一下`jsDelivr`源。

**Comment by l8higher** [comment]
更新了MacOS 11后，已可使用。
