### ISSUE TITLE
Mini播放窗口控件用户交互bug

### ISSUE THREAD

**Issue by th3weird0** [the1812/Bilibili-Evolved#1983]
**关于哪一项功能**
页面往下滚到评论区区域的右侧mini播放窗口

**问题描述**
如果在小窗口那个控件点住左键拖拽它 同时不松开左键滚轮往上滚动到页面头 会造成播放器主控件锁死跟随鼠标 不管松不松开按键不会取消跟随，取消方法是重新用滚轮滚到评论区区域 在点一下左键 才能解锁跟随鼠标位置 我觉得是bug
录了个视频 你可以点开看https://www.bilibili.com/video/av973826958

**脚本版本**
Preview Offline v1069.35

**浏览器版本**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36

**错误信息**
![image](https://user-images.githubusercontent.com/68617067/122984832-07a76000-d3d0-11eb-97e1-c2498e98dfa2.png)

**附加截图**
![image](https://user-images.githubusercontent.com/68617067/122984882-17bf3f80-d3d0-11eb-8029-63d5abb2a984.png)

**Comment by RingingVolcano** [comment]
已尝试复现。
1.只有在宽屏模式下会有这个问题 标准布局下拖拽mini播放器回顶部是正常的
2.将脚本关闭后仍能够复现 证明是B站官方的bug而非脚本问题

**Comment by RingingVolcano** [comment]
恢复的话把页面滚到下面变成Mini播放器再暂停关闭就行了

**Comment by th3weird0** [comment]
那我先操作Close吗还是等项目那个人回复 没太issue过没啥经验……

**Comment by the1812** [comment]
close 就行了
