### ISSUE TITLE
up主个人主页预约卡片的夜间适配有点问题

### ISSUE THREAD

**Issue by RingingVolcano** [the1812/Bilibili-Evolved#1984]
eg.https://space.bilibili.com/290548469
![J12MK3FY{C%2RB4KW~8ALC0](https://user-images.githubusercontent.com/72140353/123021841-65a36a00-d407-11eb-9002-7d815d8524d7.png)

**Comment by Geeyun-JY3** [comment]
重复：https://github.com/the1812/Bilibili-Evolved/issues/1692#issuecomment-841322198
