### ISSUE TITLE
顶部消息栏重复提醒有新消息，无法消除新消息提醒

### ISSUE THREAD

**Issue by Ricardoxma** [the1812/Bilibili-Evolved#1985]
**关于哪一项功能**
B站顶部功能区的“消息”中的“我的消息“

**问题描述**

只要有顶部功能条就会出现，消息——我的消息里面重复提醒有新消息，进入查看却发现事实上没有新消息进入，且提醒我的新消息数量一直是34条。

**脚本版本**

Stable v1.12.10
内容包: b6a149e

**浏览器版本**

Microsoft Edge
版本 91.0.864.54 (官方内部版本) (64 位)

**错误信息**

脚本没有报错。

**附加截图**
![image](https://user-images.githubusercontent.com/48750020/123076627-eab07280-d44b-11eb-95d4-85a13b38fb45.png)
![image](https://user-images.githubusercontent.com/48750020/123076713-fa2fbb80-d44b-11eb-828c-0fb7e37a2e18.png)
![image](https://user-images.githubusercontent.com/48750020/123076991-395e0c80-d44c-11eb-9c75-325a5bb2472a.png)

**Comment by Geeyun-JY3** [comment]
是不是未关注人消息里还有

**Comment by Ricardoxma** [comment]
> 是不是未关注人消息里还有

谢谢，检查之后发现确实是这个问题。
请问该脚本有办法关闭该消息提醒吗？我在无插件时是看不到这个消息的，也不想看，希望能跟随默认消息提醒设置或者开放用户进行设置，感谢。

**Comment by Geeyun-JY3** [comment]
看来是一个问题：https://github.com/the1812/Bilibili-Evolved/issues/1406#issuecomment-754461743
