### ISSUE TITLE
瓜子换硬币的功能失效了

### ISSUE THREAD

**Issue by LOVE-END** [the1812/Bilibili-Evolved#1988]
**关于哪一项功能**

瓜子换硬币的功能

**问题描述**

在所有b站相关的网页都是失效的

**脚本版本**

Preview v1.12.10
内容包: e56a0dd

**浏览器版本**

Google Chrome
版本 91.0.4472.114（正式版本） （64 位）

**错误信息**
瓜子换硬币的功能失效了,点击那个按钮没有反应

**附加截图**

**Comment by iDTer** [comment]
+1

**Comment by Tinhone** [comment]
+1
