### ISSUE TITLE
消息中心部分夜间模式失效

### ISSUE THREAD

**Issue by cywy** [the1812/Bilibili-Evolved#1990]
**关于哪一项功能**
https://message.bilibili.com/#/whisper/

**问题描述**
消息中心部分夜间模式失效

**脚本版本**
Bilibili Evolved (Preview Offline) 1069.35

**浏览器版本**
Chrome 91.0.4472.77

**错误信息**
![Snipaste0](https://user-images.githubusercontent.com/15707136/123401838-be2a6100-d5d9-11eb-9868-be784e895ed2.png)

**附加截图**
![Snipaste](https://user-images.githubusercontent.com/15707136/123401382-4eb47180-d5d9-11eb-9435-8b90c0eb3ac5.png)

**Comment by Geeyun-JY3** [comment]
这个好像是特别关注的消息，最新正式版似乎并没有适配

**Comment by Coulomb-G** [comment]
特别关注的消息要如何收到?我设置了特别关注,对方发视频了我却并没有收到消息

**Comment by Geeyun-JY3** [comment]
> 特别关注的消息要如何收到?我设置了特别关注,对方发视频了我却并没有收到消息

放进特别关注分组就行了啊。我这边好像没这问题。
