### ISSUE TITLE
黑暗模式的专栏，同格式的字体，有的黑有的白

### ISSUE THREAD

**Issue by paletree** [the1812/Bilibili-Evolved#1991]
**关于哪一项功能**
黑暗模式下的专栏，同样的字体，有的黑有的白。
![反馈1](https://user-images.githubusercontent.com/38284716/123427695-88947080-d5f7-11eb-967f-0f2c8a30dfd3.png)
![反馈2](https://user-images.githubusercontent.com/38284716/123427714-8fbb7e80-d5f7-11eb-9c4e-f5da52f34290.png)

**问题描述**

https://www.bilibili.com/read/cv11878898

**脚本版本**

Stable v1.12.10
内容包: 1d5375b

**浏览器版本**

**错误信息**

**附加截图**

**Comment by paletree** [comment]
这篇专栏后文还有大段的字体显色错误

**Comment by Geeyun-JY3** [comment]
有些刁钻笔记类专栏似乎还要适配：https://www.bilibili.com/read/cv11991365
顺便提醒：https://github.com/the1812/Bilibili-Evolved/issues/1692#issuecomment-864526041
