### ISSUE TITLE
网页全屏模式时，播放器的右侧会出现一条白线

### ISSUE THREAD

**Issue by Aaronatomy** [the1812/Bilibili-Evolved#200]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Aaronatomy** [comment]
![image](https://user-images.githubusercontent.com/25522771/65708915-30e37100-e0c2-11e9-9a8a-7728977213e1.png)

**Comment by Coulomb-G** [comment]
这不是播放器左侧么...另外请检查一下是否有开着其他插件或脚本,并提供一下浏览器版本和控制台错误信息

**Comment by Aaronatomy** [comment]
手滑了。。。抱歉
Chrome版本 77.0.3865.90
TamperMonkey版本  4.8.41
脚本版本 1.9.5
刚刚注意到脚本启用后B站所有页面都有这条线，目测应该是设置面板的一部分。
![image](https://user-images.githubusercontent.com/25522771/65710527-c2a0ad80-e0c5-11e9-9e42-4a1b1c668346.png)
![image](https://user-images.githubusercontent.com/25522771/65710535-c59b9e00-e0c5-11e9-90e0-f5795ccdda1b.png)

**Comment by Aaronatomy** [comment]
你好，si似乎是bilibili-evolved-about这个div的问题，将其背景设为透明线就消失了。
![image](https://user-images.githubusercontent.com/25522771/65711381-5de65280-e0c7-11e9-916e-c46d0c7a96dd.png)

**Comment by the1812** [comment]
我把这几个div再往外边移了一点, 试试看还有没有白线?

**Comment by Aaronatomy** [comment]
:) 已经没有白线了
