### ISSUE TITLE
建议批量下载时生成合并视频用的连接文本

### ISSUE THREAD

**Issue by Steve-xmh** [the1812/Bilibili-Evolved#201]
**关于哪一项功能**
可以根据分段视频的数目和文件名自动生成可以用在 ffmpeg 合并视频的命令行中，例如：
```
file '1 - 001 - 1.flv'
file '1 - 001 - 2.flv'
file '1 - 001 - 3.flv'
```
这样就能够通过自己写批处理来合并生成出来的分段视频了：
```
ffmpeg -f concat -i filelist.txt -c copy "1 - 001.flv"
```
**期望的效果**
如上，能生成一个 filelist.txt 按顺序记录每个分割视频的文件名

**脚本版本**
能出了的话就可以了~ 作者大大辛苦了~

**Comment by licovery** [comment]
我今天试了一下，似乎在filelist.txt中视频文件带有中文或特殊中文符号的时候，ffmepg合并读取文件会出错，特别是有【】这个符号的时候。

**Comment by the1812** [comment]
@licovery 貌似还要加个`-safe 0`才能中文文件名不报错
```powershell
ffmpeg -safe 0 -f concat -i ffmpeg-files.txt -c copy final.flv
```

**Comment by Steve-xmh** [comment]
> @licovery 貌似还要加个`-safe 0`才能中文文件名不报错
> 
> ```powershell
> ffmpeg -safe 0 -f concat -i ffmpeg-files.txt -c copy final.flv
> ```

是需要加 `-safe 0` 才能允许一些不安全链接，而且当文件清单中文件名有特殊字符的时候需要转义，似乎是 ASCII，ffmpeg 文档也没有写明怎么转义，也许是`\`？

**Comment by the1812** [comment]
应该只有单引号需要转义, 查了下, 是个很奇妙的写法: `'\''`
https://ffmpeg.org/ffmpeg-formats.html#Examples

**Comment by the1812** [comment]
现已支持导出文件列表. (选项仅`flv`格式可见)

**Comment by necan** [comment]
这样还是要手动操作，如果能直接一次为所有视频生成 ffmpeg 命令就好了，放在批处理文件中。

**Comment by GrandArth** [comment]
还是觉得有一个ffmpeg命令生成比较好
我想想 如果是powershell Core 7以上的话(5.1应该也可以)
应该是写成: 
`Get-ChildItem *.txt | %{ffmpeg -safe 0 -f concat -i $_.FullName -c copy "$($_.Basename).flv"}`
