### ISSUE TITLE
chrome 91版本下，所有番剧下载等功能是无法使用的

### ISSUE THREAD

**Issue by yxh0** [the1812/Bilibili-Evolved#2012]
**关于哪一项功能**
番剧、电视剧下载在chrome91这版本下是无法正常使用的

**问题描述**

所有的番剧都无法使用下载、获取封面、字幕下载等功能

**脚本版本**

正式版1.12.10 
预览版1.12.11
均无法使用

**浏览器版本**

Chrome  91.0.4472.124
**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/41407555/124302079-44731400-db93-11eb-882f-fb76e5a9f452.png)

**Comment by RingingVolcano** [comment]
和之前的issue重复了
B站现在在番剧灰度新版播放器 目前脚本还没适配

**Comment by yxh0** [comment]
> 和之前的issue重复了
> B站现在在番剧灰度新版播放器 目前脚本还没适配

是，可以将这个issue关闭，如果管理员看到的话，也不用合并了
