### ISSUE TITLE
调整播放速度失效

### ISSUE THREAD

**Issue by Ln-G0179** [the1812/Bilibili-Evolved#2014]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Ln-G0179** [comment]
救救孩子吧，调整播放速度的快捷键出问题了，只能在0.75和1.25之前变化，好麻烦

**Comment by LonelySteve** [comment]
普通视频也会这样吗？貌似番剧页新版的播放器对脚本的很多功能产生了影响。

**Comment by Ln-G0179** [comment]
没问题了，刷新一下好像又好了，番剧也正常，谢谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月3日(星期六) 下午5:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 调整播放速度失效 (#2014)





 
普通视频也会这样吗？貌似番剧页新版的播放器对脚本的很多功能产生了影响。
