### ISSUE TITLE
番剧视频无下载选项

### ISSUE THREAD

**Issue by lajilizi** [the1812/Bilibili-Evolved#2015]
功能：下载视频（包括弹幕、封面等）

问题
自Preview1.12.11开始（Offline1069.35），番剧（包括国创与电影）的视频、弹幕、封面无法下载，在附加功能中无下载选项

*脚本版本*
截至预览版1.12.11 离线版1069.35 正式版1.12.10

浏览器版本
Chrome 80 93.0.4557.2（正式版本）dev （64 位）

**附加截图**
普通视频可以下载
![BaiduShurufa_2021-7-3_17-9-51](https://user-images.githubusercontent.com/42664724/124349246-c65d4e80-dc20-11eb-80c7-9031d56f79cb.png)
番剧、电影、国创区无下载选项
![BaiduShurufa_2021-7-3_17-11-14](https://user-images.githubusercontent.com/42664724/124349430-85196e80-dc21-11eb-8859-7308460677ee.png)

**Comment by lajilizi** [comment]
目前已知：所有bangumi/play视频都没有下载选项

**Comment by Geeyun-JY3** [comment]
重复：#1992

**Comment by lajilizi** [comment]
感谢归类

**Comment by RingingVolcano** [comment]
> 感谢归类

可以把这个issue关掉了（一天见到了好几个重复的）
