### ISSUE TITLE
【快捷键扩展】在电影页面 开启快捷键扩展功能后 所有快捷键功能均失效

### ISSUE THREAD

**Issue by OCDCheng** [the1812/Bilibili-Evolved#2017]
**关于哪一项功能**
快捷键扩展

**问题描述**
在电影页面 开启快捷键扩展功能后 所有快捷键功能均失效
在普通视频页面 开启快捷键扩展功能 所有快捷键功能正常
https://www.bilibili.com/bangumi/play/ep325216

**脚本版本**
正式版1.12.10

**浏览器版本**
双核浏览器5.1.2.10
内核版本 Chromium 86.0.4240.198

**错误信息**
见截图

**附加截图**
所有报错信息截图
![2](https://user-images.githubusercontent.com/50943826/124383561-b7999900-dcff-11eb-9c87-01a6757b6bab.png)
按下方向键后出现的报错截图
![1](https://user-images.githubusercontent.com/50943826/124383587-d9931b80-dcff-11eb-9a78-0dc0980b1ad6.png)

**Comment by Geeyun-JY3** [comment]
重复：#1992
