### ISSUE TITLE
脚本加载失败

### ISSUE THREAD

**Issue by HCLonely** [the1812/Bilibili-Evolved#202]
**关于哪一项功能**

**问题描述**

ERROR: Execution of script 'Bilibili Evolved (Preview)' failed! Vue is not defined

**脚本版本**

1.9.10预览版

**浏览器版本**

Chrome 76

**错误信息**

ERROR: Execution of script 'Bilibili Evolved (Preview)' failed! Vue is not defined

**附加截图**

**Comment by the1812** [comment]
Vue没下载成功?
试试看这个网址能访问吗: [https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js](https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js)

**Comment by HCLonely** [comment]
> Vue没下载成功?
> 试试看这个网址能访问吗: https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js

能访问
好了。。
