### ISSUE TITLE
夜间模式下进度条“已播放”和“已缓存”色差较小，区分困难

### ISSUE THREAD

**Issue by ouuan** [the1812/Bilibili-Evolved#2020]
**关于哪一项功能**

夜间模式

**问题描述**

现在进度条的小电视在 hover 后过 0.5s 左右才出现，在没有小电视时夜间模式的进度条“已播放”和“已缓存”色差较小，区分比较困难。

视频背景为浅色时问题比较明显。

**脚本版本**

1.12.10

**浏览器版本**

Mozilla Firefox 89.0.2

**播放器版本**

2.60.9-rc.8371.0-476c0466

**附加截图**

夜间模式无小电视：

![图片](https://user-images.githubusercontent.com/30581822/124602450-72aa6980-de9b-11eb-9f3d-0a0b2d20cbf3.png)

夜间模式有小电视（hover 后过 0.5s 左右）：

![图片](https://user-images.githubusercontent.com/30581822/124602562-91106500-de9b-11eb-8161-fb99ef5a40d8.png)

非夜间模式：

![图片](https://user-images.githubusercontent.com/30581822/124602642-a7b6bc00-de9b-11eb-81ff-98f7da4d9aa3.png)

**Comment by the1812** [comment]
确实
