### ISSUE TITLE
夜间模式时，播放器周围的框部分未变色。

### ISSUE THREAD

**Issue by ixnij** [the1812/Bilibili-Evolved#2022]
**关于哪一项功能**
黑暗模式

**问题描述**

系统：macOS 11.4 
视频：https://www.bilibili.com/bangumi/play/ep66744

**脚本版本**

Preview Offline 1081.19

**浏览器版本**

浏览器：Google Chrome 版本 91.0.4472.114（正式版本） (arm64)

**播放器版本**

3.0.2

**错误信息**

夜间模式时，播放器周围的框部分未变色。尝试过刷新、重新浏览器、删除缓存等操作，无效。

**附加截图**

<img width="1552" alt="截屏2021-07-07 19 31 54" src="https://user-images.githubusercontent.com/61684794/124753682-dd22de80-df5b-11eb-94b1-e054a951d3a5.png">

**Comment by Geeyun-JY3** [comment]
重复，属于：#1992

**Comment by ixnij** [comment]
> 重复，属于：#1992

也就是说我的问题也是由于番剧区的新播放器灰度测试而造成的改动造成的？

**Comment by Geeyun-JY3** [comment]
> 也就是说我的问题也是由于番剧区的新播放器灰度测试而造成的改动造成的？

也可以算进了，我这边旧版播放器就没这问题。既然都是和番剧播放页有关，放一起也无妨。

**Comment by the1812** [comment]
新播放器夜间模式不支持, 当然算 #1992 的

**Comment by ixnij** [comment]
那我就把它关了吧。
