### ISSUE TITLE
"下一帧"图标消失

### ISSUE THREAD

**Issue by SYW-JS** [the1812/Bilibili-Evolved#2023]
**关于哪一项功能**
下一帧的图标.mdi mdi-chevron-right.mdi-24px:after在网页全屏时会消失

**问题描述**

以网页全屏模式播放视频

**脚本版本**

正式版1.12.10

**浏览器版本**

msedge 91.0.864.64

**播放器版本**

2.60.9

**错误信息**

下一帧的图标.mdi mdi-chevron-right.mdi-24px:after在网页全屏时会消失

**附加截图**
![](https://user-images.githubusercontent.com/78242026/124441573-64325400-ddae-11eb-87c4-0946896a9b1b.png)

**Comment by the1812** [comment]
宽度太小了被挤没了

**Comment by SYW-JS** [comment]
宽屏模式、全屏模式中,这个图标都有,但当网页全屏时却消失了.
应该不是宽度太小的缘故

**Comment by the1812** [comment]
网页全屏是按钮最多的模式 最容易挤
