### ISSUE TITLE
夜间模式 个人空间系统警告图标错误上色

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#2024]
**关于哪一项功能**
夜间模式

**问题描述**

夜间模式关于系统警告（如：纪念账号、争议账号）顶部条前置的icon会被错误上色，颜色与底色太相近了。

**脚本版本**

Preview v1.12.11
内容包: dd44c97

**浏览器版本**

Chrome 91.0.4472.124

**播放器版本**

**错误信息**

**附加截图**

显示效果：(https://space.bilibili.com/258150656)
![image](https://user-images.githubusercontent.com/11648014/124870527-73efa980-dff5-11eb-8900-f8a6fcc86f59.png)

原始图片：
![image](https://user-images.githubusercontent.com/11648014/124870778-ccbf4200-dff5-11eb-91a4-d0334a3a1793.png)

**Comment by Geeyun-JY3** [comment]
纪念账号例子：https://space.bilibili.com/212535360
各种争议账号：
- https://space.bilibili.com/472747194
- https://space.bilibili.com/777536

**Comment by the1812** [comment]
吐槽一下, b站没发现这有两个箭头吗...
![image](https://user-images.githubusercontent.com/26504152/129465255-57f11633-b68a-4948-aeba-653b80a2a9ee.png)
![image](https://user-images.githubusercontent.com/26504152/129465260-2d38dfa2-506f-402d-8e12-ee267888dcba.png)

**Comment by CKylinMC** [comment]
> 吐槽一下, b站没发现这有两个箭头吗...

文案可能没看过实际效果...
开发：我得给这里加个箭头表示这个能点
文案：我是不是应该整个箭头表示这个能点
