### ISSUE TITLE
个人空间新增粉丝勋章墙导致夜间模式不适配

### ISSUE THREAD

**Issue by cnoim** [the1812/Bilibili-Evolved#2025]
**关于哪一项功能**
夜间模式

**问题描述**

访问https://live.bilibili.com/p/html/live-fansmedal-wall/#/view-medal

**脚本版本**

Preview Offline v1081.19

**浏览器版本**

Microsoft Edge 91.0.864.64 x64

**错误信息**

无错误信息

**附加截图**
![QQ截图20210708224116](https://user-images.githubusercontent.com/52961523/124942156-f69c5700-e03d-11eb-8e43-5d346136de15.png)

**Comment by Tinhone** [comment]
“展示设置”里甚至主题色都不匹配
![图片](https://user-images.githubusercontent.com/81268244/124971455-c6fc4780-e05b-11eb-8232-446292c75a20.png)

**Comment by cnoim** [comment]
> “展示设置”里甚至主题色都不匹配
> ![图片](https://user-images.githubusercontent.com/81268244/124971455-c6fc4780-e05b-11eb-8232-446292c75a20.png)

所以说现在b站改来改去真的挺烦的

**Comment by Geeyun-JY3** [comment]
个人空间的粉丝勋章墙
![image](https://user-images.githubusercontent.com/49396421/125053029-2d727b80-e0d7-11eb-8b0c-8f47dd1c1028.png)
