### ISSUE TITLE
空降功能错误

### ISSUE THREAD

**Issue by aurxs** [the1812/Bilibili-Evolved#2026]
**关于哪一项功能**
视频空降功能

**问题描述**

当一条正常弹幕里带有类似时间的文字时会错误识别成空降弹幕
（如带有屏幕比例 16:9 的弹幕，下见图片）

**脚本版本**

正式版 v1.12.10

**浏览器版本**

Edge 91.0.864.6

**播放器版本**

2.61.0

**错误信息**

优化问题，不是错误

**附加截图**
![捕获](https://user-images.githubusercontent.com/79303639/125024729-f2ab1c00-e0b3-11eb-84a4-310adeffb3a8.PNG)

**Comment by the1812** [comment]
符合格式就识别的, 你需要更严格些吗, 比如冒号后面至少两位数

**Comment by aurxs** [comment]
> 符合格式就识别的, 你需要更严格些吗, 比如冒号后面至少两位数

或许可以像手机端那样，弹幕里有“空降”二字才识别为空降弹幕吧

**Comment by the1812** [comment]
那匹配的可就太少了, 反正匹配了只是多个下划线并不会自动跳过去, 多识别一些可能的时间点才能尽量发挥这个功能的作用吧

**Comment by Geeyun-JY3** [comment]
> 或许可以像手机端那样，弹幕里有“空降”二字才识别为空降弹幕吧

没必要啊……何必为了这么些小错自废武功
