### ISSUE TITLE
出现头像外框的异常显示

### ISSUE THREAD

**Issue by FrankchenCjc** [the1812/Bilibili-Evolved#2030]
**问题描述**

对于部分UP主的头像框头像框，在视频播放页面出现头像框异常

具体表现为头像框只显示一半，并向左做一个平移移动。似乎移动是有周期的，两个半个的头像之后会重来一次。

出现机制尚不清楚，个人猜测可能是使用了自定义头像框的UP

该问题只在FireFox上出现，并未在Edge中出现，可能Blink核心的浏览器不会出现类似问题，仅在Gecko中出现。

由于未安装Webkit类的浏览器，不知道是否在Safari上出现。

出现问题的视频地址

[https://www.bilibili.com/video/BV1Mv411p7NS](https://www.bilibili.com/video/BV1Mv411p7NS)

----

**脚本版本**

1.12.10

**浏览器版本**

FireFox 89.0.2

**播放器版本**

2.61.0

----

**错误信息**

Error: port is undefined 2 undefined
[Vue warn]: Duplicate keys detected: '89511903'. This may cause an update error.

(found in <Root>) Bilibili Evolved.user.js:790:17
    warn moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:790
    checkDuplicateKeys moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:6391
    updateChildren moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:6329
    patchVnode moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:6464
    patch moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:6625
    _update moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4099
    _update moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:9025
    updateComponent moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4217
    get moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4628
    run moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4703
    flushSchedulerQueue moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4461
    nextTick moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:2145
    flushCallbacks moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:2071
[Vue warn]: Duplicate keys detected: '89511903'. This may cause an update error.

(found in <Root>) Bilibili Evolved.user.js:790:17
    warn moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:790
    checkDuplicateKeys moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:6391
    updateChildren moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:6329
    patchVnode moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:6464
    patch moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:6625
    _update moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:9017
    updateComponent moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4217
    get moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4628
    run moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4703
    flushSchedulerQueue moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4461
    nextTick moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:2145
    flushCallbacks moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:2071
[Vue warn]: Duplicate keys detected: '89511903'. This may cause an update error.

(found in <Root>) Bilibili Evolved.user.js:790:17
    warn moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:790
    checkDuplicateKeys moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:6391
    updateChildren moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:6329
    patchVnode moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:6464
    patch moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:6625
    _update moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4099
    _update moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:9025
    updateComponent moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4217
    get moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4628
    run moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4703
    flushSchedulerQueue moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:4461
    nextTick moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:2145
    flushCallbacks moz-extension://5541ad72-f5ee-4603-aa6b-f611538e5085/userscripts/Bilibili Evolved.user.js?id=9bccb9df-0141-4198-aaec-340a403a37ec:2071
Error: port is undefined 11 undefined
Error: Promised response from onMessage listener went out of scope 4 common.js:4:491
Error: port is undefined 23 undefined
Error: port is undefined undefined
Error: port is undefined undefined
Error: port is undefined 78 undefined
Error: Promised response from onMessage listener went out of scope common.js:4:491
Error: Promised response from onMessage listener went out of scope common.js:4:491
Error: Promised response from onMessage listener went out of scope 2 common.js:4:491
Error: Promised response from onMessage listener went out of scope 2 common.js:4:491
Error: Promised response from onMessage listener went out of scope common.js:4:491
Error: Promised response from onMessage listener went out of scope 6 common.js:4:491
Error: Promised response from onMessage listener went out of scope 3 common.js:4:491
Error: Promised response from onMessage listener went out of scope 3 common.js:4:491

----

**附加截图**

![Screenshot 2021-07-10 at 22-20-15 哈阿姨进大观园_哔哩哔哩_bilibili](https://user-images.githubusercontent.com/45476087/125166660-3cd4f000-e1cf-11eb-8c7c-05cfbec2a8bb.png)

**Comment by cnoim** [comment]
有没有尝试过关闭脚本再试

**Comment by the1812** [comment]
是`高分辨率图标`限制了它的宽度, 可以先关掉
这个头像框是一个很长的关键帧序列, 加上平移动画去模拟动态头像框

**Comment by FrankchenCjc** [comment]
问题得到了部分解决，谢谢大佬
