### ISSUE TITLE
快捷键扩展导致左右方向键失效。

### ISSUE THREAD

**Issue by mrdobejelly** [the1812/Bilibili-Evolved#2033]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**播放器版本**

**错误信息**

之前有人讨论过的上下方向键没法滚动网页只能调节音量就算了，说是可以自己在代码里改掉。
但这个左右方向键调节视频进度也不能这就说不过去了吧。

**Comment by the1812** [comment]
播放器版本？

**Comment by binsee** [comment]
同样情况，播放器2.61.1
![image](https://user-images.githubusercontent.com/5285894/125272796-d4a51c00-e33e-11eb-9634-0232fc1368a3.png)

**Comment by the1812** [comment]
是不是跟 #1931 一样

**Comment by LonelySteve** [comment]
#2034 也是这个版本，我这边只是落后一个修订号，但是可以用，不知道 B 站改了啥，导致找不到 video 元素

**Comment by binsee** [comment]
> 是不是跟 #1931 一样

确实是这个原因，改用了shadow DOM，导致jquery找不到真正的video元素。

**Comment by FangchenHu** [comment]
现在仍然不能用，且有些快捷键如静音m，按m就是取消静音，一直取消静音，不能静音了
