### ISSUE TITLE
番剧播放夜间模式有瑕疵

### ISSUE THREAD

**Issue by daydreamknight** [the1812/Bilibili-Evolved#2039]
**关于哪一项功能**
番剧播放夜间模式有瑕疵

**问题描述**

ep409656
番剧播放页面都这样

**脚本版本**

v1.12.11

**浏览器版本**

Chromium 86.0.4240.198

**播放器版本**

3.0.2-beta.2-dd53b8b6

**错误信息**

**附加截图**
![屏幕截图 2021-07-13 084023](https://user-images.githubusercontent.com/44191849/125374128-ef1bdb80-e3b8-11eb-9d0e-972be0017407.png)

**Comment by Geeyun-JY3** [comment]
重复：#2022，属于：#1992
