### ISSUE TITLE
自定义播放速度时好时坏

### ISSUE THREAD

**Issue by Iamyourbaba** [the1812/Bilibili-Evolved#2041]
**关于哪一项功能**
问题内容为https://github.com/the1812/Bilibili-Evolved/issues/2034

**问题描述**

**脚本版本**

**浏览器版本**

**播放器版本**

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
直接重开 #2034 就行，没必要开新 issue

**Comment by megaslx** [comment]
最近1、2个月碰到的情况是调速后暂停再继续播放有概率会播放速度重制，而且界面上显示的还是调整过的速度，不是1x
