### ISSUE TITLE
关于使用脚本后弹幕操作窗口无法弹出

### ISSUE THREAD

**Issue by acteds** [the1812/Bilibili-Evolved#2043]
**关于哪一项功能**
关闭脚本所有开关后依然有该问题.

鼠标指向弹幕无法出现举报按钮
不启用脚本会正常出现:
![image](https://user-images.githubusercontent.com/49467817/125458910-25f72ad9-e62b-45f9-ba49-ad1393b0864b.png)
**问题描述**

任意视频,脚本启用后,移动到弹幕不会出现弹幕操作按钮

**脚本版本**

1.12.10
**浏览器版本**

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36

**播放器版本**
2.62.0-f764338b

**错误信息**

无

**附加截图**

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/125460354-295bd564-4b79-4185-ab69-966fa5f0211b.png)

**Comment by Geeyun-JY3** [comment]
@the1812 干脆弄个在首次安装脚本后出现的提示弹窗得了
