### ISSUE TITLE
edge浏览器扩展视频倍数失效

### ISSUE THREAD

**Issue by xhseed** [the1812/Bilibili-Evolved#2052]
**关于哪一项功能**
扩展视频倍数菜单

**问题描述**

edge浏览器中除扩展视频倍数以外其他功能均有效，同样设置前提下chrome浏览器的扩展视频倍数生效。无法判断是浏览器问题还是播放器版本更新问题。

**脚本版本**

正式版1.12.10

**浏览器版本**

edge版本 91.0.864.70 (官方内部版本) (64 位)，chrome版本 91.0.4472.124（正式版本） （64 位）

**播放器版本**

edge：3.03-rc.1-8a43abe8，chrome：2.62.1-88d54e1c

**错误信息**

无错误信息

**附加截图**
![image](https://user-images.githubusercontent.com/87577817/126043548-c42fb723-dea7-4498-bca7-6a122a3389f8.png)
![image](https://user-images.githubusercontent.com/87577817/126043556-f0496149-3a0b-4ec5-83d2-d11830e41f58.png)

**Comment by the1812** [comment]
播放器3.0的问题

**Comment by LonelySteve** [comment]
我来跟进吧，终于灰度到我了（

![image](https://user-images.githubusercontent.com/34429322/126641203-1bf1fcb7-7e2a-4057-a87d-02d1c02d5dff.png)
