### ISSUE TITLE
夜间模式：笔记列表未适配

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#2056]
**关于哪一项功能**
夜间模式

**问题描述**

点击笔记按钮之后出来的公开笔记列表页面完全没有适配夜间模式。

按这个按钮：
![image](https://user-images.githubusercontent.com/11648014/126062226-56c89d70-dfe5-48c8-9611-e6b173ec088a.png)

然后出来的面板：
![image](https://user-images.githubusercontent.com/11648014/126062242-189ee0c1-8e85-49bb-86a9-5646a389686e.png)

**脚本版本**

Preview v1.12.11
内容包: 619aeeb

**浏览器版本**

chrome 91

**播放器版本**

![image](https://user-images.githubusercontent.com/11648014/126062259-31a25d13-1482-431c-a28f-fb59a5441c90.png)

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/126062192-6733cd90-5d4c-4865-bb4e-78d16933ac65.png)

**Comment by CKylinMC** [comment]
另外层级似乎也很高 
![image](https://user-images.githubusercontent.com/11648014/126164817-841873d7-696d-4469-b78e-be1ef9a54014.png)
![image](https://user-images.githubusercontent.com/11648014/126164842-71592512-d535-4315-98cb-c98a9c4069f4.png)

**Comment by the1812** [comment]
这反正能拖动, 层级高也没事

**Comment by CKylinMC** [comment]
> 这反正能拖动, 层级高也没事

笔记列表是拖不动的
