### ISSUE TITLE
夜间模式：看点(分时标题)未适配

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#2058]
**关于哪一项功能**
夜间模式

**问题描述**

看点列表未适配。这是个新功能，类似油管那个关键时刻。
https://www.bilibili.com/video/av846681066

**脚本版本**

Preview v1.12.12
内容包: b0d65b5

**浏览器版本**

Chrome 91

**播放器版本**

![image](https://user-images.githubusercontent.com/11648014/126164187-fd2e3ea0-16ff-4580-ab96-387e547000de.png)

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/126164055-2e1f723a-4cb7-47cd-9a33-61e4e65a7d1a.png)
![image](https://user-images.githubusercontent.com/11648014/126164068-1f65d97d-52c3-459f-90e3-90fe22dd04a2.png)

**Comment by CKylinMC** [comment]
没有直接看到那个窗口的话点一下分段就有了
![image](https://user-images.githubusercontent.com/11648014/126165078-8548cfd3-4ec4-42d6-a9ff-47a222a07f06.png)

**Comment by Geeyun-JY3** [comment]
不得不说 B 站这「跟进」YouTube 的速度是真快。
这样的话下载这块是不是也得跟进了？

**Comment by CKylinMC** [comment]
> 不得不说 B 站这「跟进」YouTube 功能（无论好坏）的速度是真快。
> 这样的话下载这块是不是也得跟进章节（分段）功能了？

但是我在油管的体验是哪怕页面文字什么都没加载完，播放器已经可以开始播放了，卡的时候甚至可以看到页面上全是占位动画但是播放器加载完了。

b站完全反过来的，播放器才是最后加载的。

不知道b站什么时候可以学到这一点。

**Comment by Geeyun-JY3** [comment]
> 但是我在油管的体验是哪怕页面文字什么都没加载完，播放器已经可以开始播放了，卡的时候甚至可以看到页面上全是占位动画但是播放器加载完了。
> 
> b站完全反过来的，播放器才是最后加载的。
> 
> 不知道b站什么时候可以学到这一点。

2333 这点就真的不太可能了。毕竟叔叔还是要赚钱。
其他的像这次的这种章节就还能期待一下，比如可以看看接下来会不会做指向视频特定时段的评论🌚
