### ISSUE TITLE
番剧区 无下载功能

### ISSUE THREAD

**Issue by wulingyijiu** [the1812/Bilibili-Evolved#2059]
**关于哪一项功能**
番剧区 无下载功能

**问题描述**

随机打开几部番都没有下载选项（视频、弹幕、字幕
视频类暂未发现（包括多p视频
**脚本版本**

Stable v1.12.10内容包: 240c7c4

**浏览器版本**

Microsoft Edge版本 91.0.864.70 (官方内部版本) (64 位)

**播放器版本**

更新历史 3.0.3-rc.1-8a43abe8

**错误信息**

[www.bilibili.com-1626749270478.log](https://github.com/the1812/Bilibili-Evolved/files/6845152/www.bilibili.com-1626749270478.log)

**附加截图**
![321](https://user-images.githubusercontent.com/46135524/126253978-69cc6f8d-0131-4e6b-986f-6bbab5746d1c.png)

**Comment by wulingyijiu** [comment]
另外我在7月18号12点还用过番剧下载功能

**Comment by the1812** [comment]
#1992

**Comment by kiritad** [comment]
清除浏览器全部缓存和cookie，让bilibili的播放器版本退回2.6就可以下

**Comment by kiritad** [comment]
在播放页面右键看播放器版本

**Comment by kiritad** [comment]
话说作者，这问题有20来天了，为啥还不更新

**Comment by the1812** [comment]
因为这20来天我都是2.6播放器啊
