### ISSUE TITLE
夜间模式:番剧区播放器未适配

### ISSUE THREAD

**Issue by lswl53413** [the1812/Bilibili-Evolved#2065]
关于哪一项功能**
夜间模式

问题描述**
基本上所有番剧(包括港澳番剧)的播放器都无夜间模式

脚本版本**
1.12.10

浏览器版本**
Microsoft Edge版本 91.0.864.71 (官方内部版本) (64 位)

播放器版本**
更新历史 2.62.3-92d0d613

错误信息**
www.bilibili.com-1626749270478.log

附加截图**
![bandicam 2021-07-22 15-29-51-986](https://user-images.githubusercontent.com/87801731/126606345-50cab619-e925-4421-b224-374f9a2386b3.jpg)

**Comment by Coulomb-G** [comment]
开新issue前能不能先搜索关键词?

**Comment by Geeyun-JY3** [comment]
看置顶。
再指一次路吧：#1992、#2022
