### ISSUE TITLE
您好，查看选项后，仍然找不到使右侧合集集数自动跟踪在播集数的设置

### ISSUE THREAD

**Issue by lyjhyjyes** [the1812/Bilibili-Evolved#2070]
**关于哪一项功能**

**问题描述**

https://www.bilibili.com/video/av91849600?p=71&spm_id_from=pageDriver
您好，查看选项后，仍然找不到使右侧合集集数自动跟踪在播集数的设置。在学习时候不知道右侧的标题

**脚本版本**

win10 chrome90
Stable v1.12.10
内容包: 0e095db

**浏览器版本**

**播放器版本**

**错误信息**

**附加截图**
![](https://github.com/lyjhyjyes/pic/blob/main/04.png)
https://github.com/lyjhyjyes/pic/blob/main/04.png
[https://github.com/lyjhyjyes/pic/blob/main/04.png](https://github.com/lyjhyjyes/pic/blob/main/04.png)
<a href="https://github.com/lyjhyjyes/pic/blob/main/04.png">04.png</a>

**Comment by the1812** [comment]
本来就没有这种功能啊

**Comment by Coulomb-G** [comment]
你截图的不是「展开视频简介」吗？
和你说的功能有什么关系，另外播放器底部的设置栏就有选集可以看标题

**Comment by lyjhyjyes** [comment]
当一个合集有200个视频，每次只显示最上面的标题。后面正在播放的视频，需要手动拉下去看标题

Coulomb-G ***@***.***> 于2021年7月23日周五 下午9:03写道：

**Comment by lyjhyjyes** [comment]
> 本来就没有这种功能啊

哦哦。原来右侧不能自动跳转正在播放的标题

**Comment by Geeyun-JY3** [comment]
~~我想我大概猜到楼主的意思了。~~

楼主是不是希望选集列表能和未使用脚本时一样，在视频的正右方就能看见当前播放选集的标题？
![image](https://user-images.githubusercontent.com/49396421/126892069-98cd4863-ad12-4151-9e79-9e89db70e540.png)

看楼主截图可以判断开启了 `展开选集列表` 功能。所以楼主开启这个功能是希望选集列表能显示完整标题吗？
如果是，开本 issue 的是不是可以理解为：以为本脚本有在不展开选集列表的同时显示完整标题的设置项？
如果这也是，建议关注 #692，我提了这个需求。
