### ISSUE TITLE
BUG 音量↑↓键功能异常

### ISSUE THREAD

**Issue by DEabcdp** [the1812/Bilibili-Evolved#2073]
😁😁😁我老BUG反馈员了
**关于哪一项功能**
键盘上下↑↓键调节音量功能。

**问题描述**
如此页面https://www.bilibili.com/video/BV1E64y1t7Kb
1.**开启**快捷键拓展后（默认设置）视频音量键↑↓键按一下会变**20%**，原来应该是10%的。F12控制台没有任何报错。
2.**关闭**快捷键拓展后（默认设置）视频音量键↑↓键失效，**没有反应**，鼠标悬停到那个音量条也没有变化，**但是事实上音量是变了的**，这就很诡异！实（盲）测按一下变化10%。F12控制台没有任何报错。
（结合到1我猜测是不是开启快捷键拓展之后两个叠加成20%了？）
3.F键全屏功能异常，播放时按一下会自动暂停，原来不会暂停。F12控制台没有任何报错。

**脚本版本**
<预览版1.12.12>

**浏览器版本**
<Microsoft Edge Chromium
版本 92.0.902.55 (官方内部版本) (64 位)>

**播放器版本**
<2.62.3-92d0d613>

**附加截图**
静音时图1如下：
![1](https://user-images.githubusercontent.com/62452364/126852819-1081a531-714c-4a8e-99e9-4b1d8e457ad0.png)

按一下↑键如下：
![2](https://user-images.githubusercontent.com/62452364/126852827-365e0e16-1093-482d-97fb-fc1bf3fc005e.png)

再按一下↑键如下：
![3](https://user-images.githubusercontent.com/62452364/126852832-a843b2e0-fbbc-4735-9c10-f50661d9ff96.png)

**Comment by the1812** [comment]
一个都没试出来... 你有没有开多个脚本

> 1.开启快捷键拓展后（默认设置）视频音量键↑↓键按一下会变20%，原来应该是10%的。F12控制台没有任何报错。

我怎么按都是调整10%音量

> 2.关闭快捷键拓展后（默认设置）视频音量键↑↓键失效，没有反应，鼠标悬停到那个音量条也没有变化，但是事实上音量是变了的，这就很诡异！实（盲）测按一下变化10%。F12控制台没有任何报错。
（结合到1我猜测是不是开启快捷键拓展之后两个叠加成20%了？）

关闭后↑↓键是移动页面, 聚焦到播放器时会调整10%音量

> 3.F键全屏功能异常，播放时按一下会自动暂停，原来不会暂停。F12控制台没有任何报错。

按一下 F 会全屏但不会暂停

**Comment by DEabcdp** [comment]
可能是我浏览器更新了，就今天突然这样🤔

**Comment by DEabcdp** [comment]
真相：和某脚本冲突了
