### ISSUE TITLE
edge浏览器，上下帧和截图键消失

### ISSUE THREAD

**Issue by PINKRA** [the1812/Bilibili-Evolved#2076]
**关于哪一项功能**
视频

**问题描述**

截图和上下帧的键没了

**脚本版本**

1.12.11

**浏览器版本**

Edge Bate

**播放器版本**

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
提issue前,请先搜索关键词

**Comment by SatoSouta** [comment]
Google Chrome 也有同样的问题

**Comment by the1812** [comment]
#1992
