### ISSUE TITLE
自定义顶栏在新番动画的网页全屏模式下不能自动隐藏

### ISSUE THREAD

**Issue by Adiwon** [the1812/Bilibili-Evolved#2077]
**脚本版本**
1.12.10

**浏览器版本**
Cent浏览器（Chrome86）

**播放器版本**
V3.0.3
**附加截图**

![FireShot Capture 077 - 异世界迷宫黑心企业：第3话_番剧_bilibili_哔哩哔哩 - www bilibili com](https://user-images.githubusercontent.com/16150302/126877085-f1450aee-c0c8-49fe-8268-a8973d560aee.png)

**Comment by Geeyun-JY3** [comment]
看置顶：#1992
请善用搜索：#1975、#2021
