### ISSUE TITLE
BUG 默认播放器模式（全屏）前台打开显示网页全屏

### ISSUE THREAD

**Issue by DEabcdp** [the1812/Bilibili-Evolved#2078]
**关于哪一项功能**
视频设置-默认播放器模式（全屏）

**问题描述**
如此页面：https://www.bilibili.com/video/BV1E64y1t7Kb
设置完默认播放器模式为**全屏**后，进入页面，右键任意1个**推荐视频**，从新标签打开（即后台不是前台），等10秒（短了不行）加载完成后，然后点击打开的新页面，会发现页面变成了**网页全屏**，并且**按ESC键、F快捷键、视频右下角的退出全屏按钮都没有反应**不能退出网页全屏状态，只能F5刷新。

**脚本版本**
<预览版1.12.12>

**浏览器版本**
<Microsoft Edge
版本 92.0.902.55 (官方内部版本) (64 位)>

**播放器版本**
<2.62.3-92d0d613>

**附加截图**
![image](https://user-images.githubusercontent.com/62452364/126882472-8971b021-85d6-43ac-9b29-f0006b4c0954.png)
![image](https://user-images.githubusercontent.com/62452364/126882474-eceef09f-ba26-4182-994c-9647e0da732a.png)
![image](https://user-images.githubusercontent.com/62452364/126882476-790818a5-49b0-4fef-9b92-610c632eed94.png)

**Comment by the1812** [comment]
浏览器后台标签页禁止全屏的, 全屏失败了就变成那个奇怪的"网页全屏"模式了

**Comment by CKylinMC** [comment]
> 浏览器后台标签页禁止全屏的, 全屏失败了就变成那个奇怪的"网页全屏"模式了

有没有可能如果不在前台的时候加个事件等前台了再继续注入某些需要前台的功能？

**Comment by the1812** [comment]
> 有没有可能如果不在前台的时候加个事件等前台了再继续注入某些需要前台的功能？

应该可以
