### ISSUE TITLE
瓜子换硬币功能失效

### ISSUE THREAD

**Issue by JesseMcccree** [the1812/Bilibili-Evolved#2082]
**问题描述**
瓜子换硬币功能无反应

**脚本版本**
Stable v1.12.10  内容包: 3b46758

**浏览器版本**
Chrome 92.0.4515.107（正式版本） （64 位）

**错误信息**
DevTools failed to load source map: Could not load content for chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
userscript.html?name=Bilibili%20Evolved.user.js&id=887ad01b-f756-468a-942f-4a52fc9b077b:13210 Skipped <iframe> loading for https://message.bilibili.com/pages/nav/index_new_pc_sync
userscript.html?name=Bilibili%20Evolved.user.js&id=887ad01b-f756-468a-942f-4a52fc9b077b:13210 scheduled bundle update
userscript.html?name=Bilibili%20Evolved.user.js&id=887ad01b-f756-468a-942f-4a52fc9b077b:13210 downloading bundle
userscript.html?name=Bilibili%20Evolved.user.js&id=887ad01b-f756-468a-942f-4a52fc9b077b:13210 zip version = 1.12.10
userscript.html?name=Bilibili%20Evolved.user.js&id=887ad01b-f756-468a-942f-4a52fc9b077b:13210 bundle updated
sentry-5.7.1.min.js:2 GET https://api.live.bilibili.com/pay/v1/Exchange/silver2coin 405
(anonymous) @ sentry-5.7.1.min.js:2
eval @ userscript.html?name=Bilibili%20Evolved.user.js&id=887ad01b-f756-468a-942f-4a52fc9b077b:13210
send @ userscript.html?name=Bilibili%20Evolved.user.js&id=887ad01b-f756-468a-942f-4a52fc9b077b:13210
getTextWithCredentials @ userscript.html?name=Bilibili%20Evolved.user.js&id=887ad01b-f756-468a-942f-4a52fc9b077b:13210
getJsonWithCredentials @ userscript.html?name=Bilibili%20Evolved.user.js&id=887ad01b-f756-468a-942f-4a52fc9b077b:13210
action @ VM1476:1
eval @ VM1476:1
sentryWrapped @ sentry-5.7.1.min.js:2
VM1598:1 Uncaught (in promise) SyntaxError: Unexpected token M in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.getJsonWithCredentials (userscript.html?name=Bilibili%20Evolved.user.js&id=887ad01b-f756-468a-942f-4a52fc9b077b:13210)
    at async Object.action (eval at applyComponent (userscript.html?name=Bilibili%20Evolved.user.js&id=887ad01b-f756-468a-942f-4a52fc9b077b:1), <anonymous>:1:174)
getJsonWithCredentials @ userscript.html?name=Bilibili%20Evolved.user.js&id=887ad01b-f756-468a-942f-4a52fc9b077b:13210
async function (async)
action @ VM1476:1
eval @ VM1476:1
sentryWrapped @ sentry-5.7.1.min.js:2
![屏幕截图(69)](https://user-images.githubusercontent.com/87928575/126893447-e61b824e-c76b-42ff-b1f4-2a68096a6edf.png)

**Comment by Geeyun-JY3** [comment]
正式版刚修……：[v1.12.13](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.12.13)
重复：#1988
