### ISSUE TITLE
请问现在怎么能够从上次播放位置继续播放？

### ISSUE THREAD

**Issue by shimakotodo** [the1812/Bilibili-Evolved#2086]
记得以前有个记忆播放位置的选项，而现在变成了记忆上次播放速度。我也没找到B站自身的从上次播放位置继续播放的设置选项。请问现在在哪里能设置这个呢？

**Comment by the1812** [comment]
以前只有个自动点击b站弹出的`上次看到xx:xx`消息, 现在b站改成直接跳过去了(不用设置什么就有的)

**Comment by shimakotodo** [comment]
啊咧？奇怪，我用保持自动更新的edge试了一下，是会跳出那个已为您定为至几分几秒的提示的，但是我常用的禁止更新的旧Chrome，就从不跳出这个，只能从开头播放。
既然与增强脚本无关，那就不打扰了。

最后再次感谢制作这个脚本，一直用了好多年了，谢谢。

**Comment by Geeyun-JY3** [comment]
现在对于多 p 视频 B 站是不会直接跨集跳转的，还是显示 `上次看到 第x个 xx:xx`。只有在当前播放分 p 和上次看到的分 p 一致时，才会自动跳转至上次播放位置
![image](https://user-images.githubusercontent.com/49396421/126921168-1d3361a3-5658-4f1e-aac7-a8956bb4a631.png)

**Comment by MC-dusk** [comment]
从历史记录进入，链接带有时间戳比如`?t=10`都会自动播放吧，我倒是想禁掉自动跳转播放，目前也没有找到解决办法。

**Comment by Geeyun-JY3** [comment]
> 从历史记录进入，链接带有时间戳比如`?t=10`都会自动播放吧，我倒是想禁掉自动跳转播放，目前也没有找到解决办法。

历史记录的这个通过带时间戳的链接的从上次播放位置继续播放是 B 站学 YouTube 的偷懒做法吧，因为打开的是指向某个时间点的链接，所以肯定会跳转至某个时间点。我 [上面](https://github.com/the1812/Bilibili-Evolved/issues/2086#issuecomment-886313316) 提到的这种情况链接不带时间戳都会出现图中的提示，就是不清楚这玩意会不会同步。

**Comment by MC-dusk** [comment]
> 
> 
> > 从历史记录进入，链接带有时间戳比如`?t=10`都会自动播放吧，我倒是想禁掉自动跳转播放，目前也没有找到解决办法。
> 
> 历史记录的这个通过带时间戳的链接的从上次播放位置继续播放是 B 站学 YouTube 的偷懒做法吧，因为打开的是指向某个时间点的链接，所以肯定会跳转至某个时间点。我 [上面](https://github.com/the1812/Bilibili-Evolved/issues/2086#issuecomment-886313316) 提到的这种情况链接不带时间戳都会出现图中的提示，就是不清楚这玩意会不会同步。

不带时间戳的链接，跳转（提示）有时灵有时不灵，不能一直复现，挺迷的，也没有深入研究。

**Comment by shimakotodo** [comment]
> 从历史记录进入，链接带有时间戳比如`?t=10`都会自动播放吧，我倒是想禁掉自动跳转播放，目前也没有找到解决办法。

原来能这样，我把原本关掉的历史记录重新启用，果然从这里就可以跳转记忆播放了。非常感谢提供方法！
