### ISSUE TITLE
音效调节器，均衡器bug

### ISSUE THREAD

**Issue by 0x00Finch** [the1812/Bilibili-Evolved#2088]
**关于哪一项功能**

**问题描述**

所有视频均会出现这个bug
bug描述： 音效调节均衡器菜单好像层级关系有点混乱，均衡器应该在最上层的

**脚本版本**

1.12.13

**浏览器版本**

chrome  92.0.4515.107

**播放器版本**

2.62.3-92d0d613

**错误信息**

**附加截图**
![15615611961](https://user-images.githubusercontent.com/26269474/126932985-db962c01-dd2e-4310-a773-c275a4c9fa34.jpg)

**Comment by the1812** [comment]
这锅我不背啊

![image](https://user-images.githubusercontent.com/26504152/126936751-10a0bf48-f156-4cc8-a3b2-cf5b23e902ea.png)
![image](https://user-images.githubusercontent.com/26504152/126936709-f34805bb-1cad-4336-b796-d543322843b1.png)

**Comment by 0x00Finch** [comment]
> 这锅我不背啊
> 
> ![image](https://user-images.githubusercontent.com/26504152/126936751-10a0bf48-f156-4cc8-a3b2-cf5b23e902ea.png)
> ![image](https://user-images.githubusercontent.com/26504152/126936709-f34805bb-1cad-4336-b796-d543322843b1.png)
> 

那没事了，抱歉
