### ISSUE TITLE
自定义快捷键扩展后 快捷键在番剧区不能正常生效

### ISSUE THREAD

**Issue by c6h8o6ovo** [the1812/Bilibili-Evolved#2092]
**关于哪一项功能**
快捷键扩展

**问题描述**
在通过控制台自定义快捷键扩展后，所有快捷键在番剧区失效，且删除自定义后仍然无效 （视频区正常生效， 包括自定义）

**脚本版本**
1.12.13预览版

**浏览器版本**
Microsoft Edge
版本 92.0.902.55 (官方内部版本) (64 位)

**播放器版本**
视频播放器：2.62.3-92d0d613
番剧播放器：3.0.3-rc.1-8a43abe8

**Comment by Geeyun-JY3** [comment]
不 要 急
{v1.12.13}(https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.12.13)
> 仅做了一些小适配, 很多地方我也还没摸清楚

**Comment by DEabcdp** [comment]
我也刚发现，亲测关闭快捷键拓展后正常。

**Comment by Geeyun-JY3** [comment]
你们要真的忍不了的话可以先关掉 `快捷键扩展` 然后用这个扩展：https://chrome.google.com/webstore/detail/ffoljpljalicgkljioegejmigkkkincm
