### ISSUE TITLE
本脚本与哔哩哔哩助手：bilibili.com 综合辅助扩展产生了冲突

### ISSUE THREAD

**Issue by yuijker** [the1812/Bilibili-Evolved#2095]
**关于哪一项功能**
无法定位（可能与直播间的功能有关，也可能与脚本本身有关）

**问题描述**

1.在tampermonkey中安装本脚本
2.在如下网址安装哔哩哔哩助手的最新测试版2.2.2.3
3.来到一个直播间
4.启动网页全屏
5.问题发生：该扩展的浮动图标消失了，一旦退出就马上显示

**脚本版本**

1.12.13

**浏览器版本**

Edge 92.0.902.55

**播放器版本**

bilibili HTML5 Live Player 3.3.8

**错误信息**

看附加截图1吧。

**附加截图**
1.
![捕获2](https://user-images.githubusercontent.com/72558803/127252769-848229ff-2f6e-41cd-ac4e-13c955ff84fb.PNG)

2.同时开启脚本与哔哩哔哩助手时开启网页全屏
![捕获4](https://user-images.githubusercontent.com/72558803/127253620-9a846c4f-fb30-40da-8f6e-9fe8a76a0d3b.PNG)

3.只有哔哩哔哩助手时开启网页全屏
![捕获5](https://user-images.githubusercontent.com/72558803/127253886-71232a89-af34-403c-8181-7b71cc805d99.PNG)

**Comment by jjj201200** [comment]
感谢反馈，经排查是由于贵脚本的这段css导致网页全屏时出现问题
```
.player-full-win .app-content, .player-full-win .live-room-app .app-content, .player-mode-webfullscreen .player-module, .player-mode-webfullscreen .player-module .player-container {
    z-index: 100000!important;
}
```
助手的悬浮球z-index恰好是比这小1
请问我们互相是否能够协调一下以处理解决这个问题

**Comment by the1812** [comment]
我试下把我这边 `z-index` 都调低点吧
