### ISSUE TITLE
火狐浏览器下点击左侧齿轮任意项均无反应

### ISSUE THREAD

**Issue by miranquil** [the1812/Bilibili-Evolved#2098]
**关于哪一项功能**

左侧齿轮设置菜单

**问题描述**

macOS 12.0 Beta(21A5284e) MacBook Pro 2020 Intel 15.4 Inch

使用Tampermonkey安装脚本后进入Bilibili首页，左侧齿轮显示正常，但点开后所有选项点击均无响应。
同时也无法通过点击其他区域关闭齿轮菜单。
同一台机器上 Safari + Adguard 工作正常。

**脚本版本**

1.12.13

**浏览器版本**

Firefox Developer Edition 91.0b8 (64 位)

**播放器版本**

**错误信息**

<details>
<summary>点击展开Firefox控制台警告&错误</summary>

<code>
即使其 MIME 类型（“text/plain”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://www.bilibili.com/gentleman/polyfill.js?features=Promise%2CObject.assign%2CString.prototype.includes%2CNumber.isNaN”的脚本。 www.bilibili.com
XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XML 解析错误：语法错误
位置：https://injections.adguard.org/adguard-ajax-api/api
行 1，列 1： api:1:1
XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XML 解析错误：语法错误
位置：https://injections.adguard.org/adguard-ajax-api/api
行 1，列 1： api:1:1
XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XML 解析错误：语法错误
位置：https://injections.adguard.org/adguard-ajax-api/api
行 1，列 1： api:1:1
XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XML 解析错误：语法错误
位置：https://injections.adguard.org/adguard-ajax-api/api
行 1，列 1： api:1:1
XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XML 解析错误：语法错误
位置：https://injections.adguard.org/adguard-ajax-api/api
行 1，列 1： api:1:1
XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 1ms]

XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 1ms]

XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XHRPOSThttps://injections.adguard.org/adguard-ajax-api/api
[HTTP/2 400 Bad Request 0ms]

XML 解析错误：语法错误
位置：https://injections.adguard.org/adguard-ajax-api/api
行 1，列 1： 11 api:1:1
该页面使用非标准属性“zoom”。请考虑在相关属性值中使用 calc()，或将“transform”与“transform-origin: 0 0”一同使用。 www.bilibili.com
GEThttps://s1.hdslb.com/bfs/seed/log/report/log-reporter.js
[HTTP/2 500 Internal Server Error 1ms]

指向“https://s1.hdslb.com/bfs/seed/log/report/log-reporter.js”的 <script> 加载失败。 www.bilibili.com:1:1
源映射错误：Error: request failed with status 404
源 URL：https://s1.hdslb.com/bfs/static/jinkela/international-home/international-home.3d1140b51763436f412379600a484c68d3518909.js
源映射 URL：international-home.3d1140b51763436f412379600a484c68d3518909.js.map
GEThttps://s1.hdslb.com/bfs/seed/log/report/log-reporter.js
[HTTP/2 500 Internal Server Error 1ms]

指向“https://s1.hdslb.com/bfs/seed/log/report/log-reporter.js”的 <script> 加载失败。 www.bilibili.com:1:1
[Vue warn]: Property or method "items" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>) sentry-5.7.1.min.js:2:43660
[Vue warn]: Error in render: "TypeError: can't access property "length", items is undefined"

(found in <Root>) sentry-5.7.1.min.js:2:43660
TypeError: can't access property "length", items is undefined
    anonymous https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script line 48 > Function line 11783 > Function:3
    _render Bilibili%20Evolved.user.js:3700
    updateComponent Bilibili%20Evolved.user.js:4216
    get Bilibili%20Evolved.user.js:4627
    Watcher Bilibili%20Evolved.user.js:4616
    mountComponent Bilibili%20Evolved.user.js:4223
    $mount Bilibili%20Evolved.user.js:9193
    $mount Bilibili%20Evolved.user.js:12078
    _init Bilibili%20Evolved.user.js:5161
    Vue Bilibili%20Evolved.user.js:5227
    anonymous/</onlineData["https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/min/custom-navbar.min.js"]</</</< Bilibili%20Evolved.user.js:13207
    async*anonymous/</onlineData["https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/min/custom-navbar.min.js"]</</< Bilibili%20Evolved.user.js:13207
    anonymous/</onlineData["https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/min/custom-navbar.min.js"]</< Bilibili%20Evolved.user.js:13207
    applyComponent Bilibili%20Evolved.user.js:13207
    fetchByKey Bilibili%20Evolved.user.js:13207
    fetch Bilibili%20Evolved.user.js:13207
    i Bilibili%20Evolved.user.js:13207
    fullyLoaded Bilibili%20Evolved.user.js:13207
    addEventListener eval:4
    fullyLoaded Bilibili%20Evolved.user.js:13207
    anonymous Bilibili%20Evolved.user.js:13207
    anonymous Bilibili%20Evolved.user.js:13207
    anonymous Bilibili%20Evolved.user.js:3
    anonymous Bilibili%20Evolved.user.js:3
    <anonymous> https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script:49
    <anonymous> https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script:47
    <anonymous> https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script:46
    <anonymous> https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script:48
sentry-5.7.1.min.js:2:43660
某些 Cookie 滥用推荐的“SameSite“属性 4
Uncaught TypeError: can't access property "querySelector", e is null
    checkPosition eval line 4 > eval line 13210 > eval:1
    i eval line 4 > eval line 13210 > eval:1
    addSettingsListener moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:13210
    i eval line 4 > eval line 13210 > eval:1
    requestIdleCallback handler*mounted eval line 4 > eval line 13210 > eval:1
    invokeWithErrorHandling moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:2019
    callHook moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:4370
    mountComponent moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:4237
    $mount moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:9194
    $mount moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:12079
    _init moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:5162
    Vue moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:5228
    <anonymous> eval line 4 > eval line 13210 > eval:1
    async* eval line 4 > eval line 13210 > eval:1
    <anonymous> eval line 4 > eval line 13210 > eval:1
    applyComponent moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:13210
    fetchByKey moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:13210
    fetch moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:13210
    i moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:13210
    fullyLoaded moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:13210
    addEventListener eval:4
    fullyLoaded moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:13210
    tms_f401e74b_45dd_446b_89f5_20486d0936cc moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:13210
    tms_f401e74b_45dd_446b_89f5_20486d0936cc moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:13210
    s eval:4
    <anonymous> moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:1
    <anonymous> moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:1
    <anonymous> moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:13211
    <anonymous> moz-extension://4620c99b-16ec-7c41-bb16-6604a4d7455b/userscripts/Bilibili Evolved.user.js?id=f401e74b-45dd-446b-89f5-20486d0936cc:13213
    s eval:4
    t eval:3
    E_u eval:4
    create eval line 2 > Function:67
    create eval line 2 > Function:69
    c eval line 2 > Function:7
    n eval line 2 > Function:6
    run eval line 2 > Function:7
    anonymous eval line 2 > Function:70
    s eval:4
    t eval:3
    anonymous eval line 2 > Function:70
    anonymous eval line 2 > Function:70
    TM_back eval line 2 > Function:71
    anonymous eval line 2 > Function:71
    s eval:4
eval line 4 > eval line 13210 > eval:1:1588
Uncaught TypeError: can't access property "querySelector", t is null
    checkPosition Bilibili%20Evolved.user.js:13207
    t Bilibili%20Evolved.user.js:13207
    addSettingsListener Bilibili%20Evolved.user.js:13207
    t Bilibili%20Evolved.user.js:13207
    requestIdleCallback handler*mounted Bilibili%20Evolved.user.js:13207
    invokeWithErrorHandling Bilibili%20Evolved.user.js:2018
    callHook Bilibili%20Evolved.user.js:4369
    mountComponent Bilibili%20Evolved.user.js:4236
    $mount Bilibili%20Evolved.user.js:9193
    $mount Bilibili%20Evolved.user.js:12078
    _init Bilibili%20Evolved.user.js:5161
    Vue Bilibili%20Evolved.user.js:5227
    anonymous/</onlineData["https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/min/custom-navbar.min.js"]</</</< Bilibili%20Evolved.user.js:13207
    async*anonymous/</onlineData["https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/min/custom-navbar.min.js"]</</< Bilibili%20Evolved.user.js:13207
    anonymous/</onlineData["https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/min/custom-navbar.min.js"]</< Bilibili%20Evolved.user.js:13207
    applyComponent Bilibili%20Evolved.user.js:13207
    fetchByKey Bilibili%20Evolved.user.js:13207
    fetch Bilibili%20Evolved.user.js:13207
    i Bilibili%20Evolved.user.js:13207
    fullyLoaded Bilibili%20Evolved.user.js:13207
    addEventListener eval:4
    fullyLoaded Bilibili%20Evolved.user.js:13207
    anonymous Bilibili%20Evolved.user.js:13207
    anonymous Bilibili%20Evolved.user.js:13207
    anonymous Bilibili%20Evolved.user.js:3
    anonymous Bilibili%20Evolved.user.js:3
    <anonymous> https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script:49
    <anonymous> https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script:47
    <anonymous> https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script:46
    <anonymous> https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script:48
injections.adguard.org:13207:270867
某些 Cookie 滥用推荐的“SameSite“属性 2
源映射错误：Error: request failed with status 404
源 URL：https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/sentry-5.7.1.min.js
源映射 URL：bundle.min.js.map
Uncaught (in promise) Error: Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?
    prepareContent Bilibili%20Evolved.user.js:154
    promise callback*anonymous/</</<[32]</c.prepareContent Bilibili%20Evolved.user.js:154
    exports Bilibili%20Evolved.user.js:153
    checkUpdates Bilibili%20Evolved.user.js:13207
    t Bilibili%20Evolved.user.js:13207
    requestIdleCallback handler*fetch Bilibili%20Evolved.user.js:13207
    i Bilibili%20Evolved.user.js:13207
    fullyLoaded Bilibili%20Evolved.user.js:13207
    addEventListener eval:4
    fullyLoaded Bilibili%20Evolved.user.js:13207
    anonymous Bilibili%20Evolved.user.js:13207
    anonymous Bilibili%20Evolved.user.js:13207
    anonymous Bilibili%20Evolved.user.js:3
    anonymous Bilibili%20Evolved.user.js:3
    <anonymous> https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script:49
    <anonymous> https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script:47
    <anonymous> https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script:46
    <anonymous> https://injections.adguard.org/?ts=1627538466854&name=AdGuard Extra&name=Bilibili Evolved&type=user-script:48
injections.adguard.org:154:3825
</code>

</details>

**附加截图**
<img width="1415" alt="图片" src="https://user-images.githubusercontent.com/25676311/127439957-eda23dac-1308-4604-ae60-3501f5b52a0b.png">

**Comment by miranquil** [comment]
禁用Adguard中的对应扩展后正常了，似乎是由于Firefox同时加载了Adguard和TamperMonkey的Bilibili-Evolved脚本导致冲突。

**Comment by the1812** [comment]
不能同时开两个脚本的
