### ISSUE TITLE
自动宽屏功能切换大幅延迟.

### ISSUE THREAD

**Issue by YamatoRyou** [the1812/Bilibili-Evolved#2107]
**问题描述**
现在播放器 (包括网页全屏 / 全屏) 要很长时间才能切换到自动宽屏.
似乎和弹幕的数量有关? 
https://www.bilibili.com/video/av759073013, 没有弹幕, 能瞬间切换.
https://www.bilibili.com/video/av26798082, 少量弹幕, 开始播放后约 20 秒内切换.
https://www.bilibili.com/video/av56185784, 4000 多条弹幕, 开始播放后 30 秒 ~ 2 分钟左右才切换

**脚本版本**
1.12.13 预览版

**浏览器版本**
Cent Browser 4.3.9.248 (Chromium 86), x64

**播放器版本**
2.63.2-rc.8997.0.-32d49610

**错误信息**
n/a

**附加截图**
n/a

**Comment by the1812** [comment]
4000多条那个 你那边弹幕是一直装填中吗? 我试了下都是可以马上切换的

**Comment by YamatoRyou** [comment]
> 4000多条那个 你那边弹幕是一直装填中吗? 我试了下都是可以马上切换的

弹幕可以立即显示出来, 但自动宽屏要延迟好久.

**Comment by YamatoRyou** [comment]
> 4000多条那个 你那边弹幕是一直装填中吗? 我试了下都是可以马上切换的

疑似找到原因.
设置播放器 "禁止 HEVC" 可解, 但诡异的是 Chrome 92 不会出现这种问题 (仔细检查播放器发现 Chrome 92 中的播放器不会出现 "播放策略" 选项).

Chrome 92, x64
![{33E750BA-FA72-54FD-8512-EA17E52C35AD}](https://user-images.githubusercontent.com/48104960/128631963-b5018ed4-b1a1-40bc-b591-d4d1c74f4e5a.png)

Cent Browser 4.3.9.248 (Chromium 86), x64
![{4AADEDE4-0BE7-0C5E-5BFA-071288CFAFE2}](https://user-images.githubusercontent.com/48104960/128631965-64afc929-3e78-4b26-ac2a-1146c7f088c6.png)

**Comment by YamatoRyou** [comment]
仍然为上述设置的情况下更新到 2.0.x, 也不能 100% 有效了.
有一定几率出现以下情况: 
a) 无法自动切换到宽屏;
b) 能切换到宽屏, 但画面未能填满播放器. 如果视频画面为宽屏, 四周会出现黑边. 此时需要手动单击一次宽屏按钮.
![{021E03DA-2E59-5323-EC92-8C0BB6ED9002}](https://user-images.githubusercontent.com/48104960/145644769-8bded4e2-6e9b-4c2c-936e-cc1f9a332130.jpg)
