### ISSUE TITLE
1.9.10版本Violentmonkey好像加载不了

### ISSUE THREAD

**Issue by SodaShin** [the1812/Bilibili-Evolved#211]
**问题描述**
Violentmonkey好像都加载不了，但Firefox换了Tampermonkey可以加载

**脚本版本**
1.9.10

**浏览器版本**
maxthon5.2.7+Violentmonkey 2.8.4
Firefox66 +Violentmonkey 2.10.3

**错误信息**

**附加截图**

**Comment by the1812** [comment]
我这可以正常使用 Firefox 69.0.1 + Violentmonkey 2.11.2
控制台(`Ctrl + Shift + I`)有报错吗? 或者也可以先更新一下浏览器和Violentmonkey再试试
![image](https://user-images.githubusercontent.com/26504152/66128087-b06fc380-e61f-11e9-96e8-3b738cb58645.png)

**Comment by jrkkei** [comment]
waterfox56  Violentmonkey 2.11.2不能加载了
![waterfox_2019-10-05_13-36-21](https://user-images.githubusercontent.com/17683750/66250426-36e9e980-e775-11e9-9b54-aafa9846135a.jpg)

**Comment by Sierra33** [comment]
maxthon5.2.7+Violentmonkey 2.8.4不能加载
<img width="959" alt="image" src="https://user-images.githubusercontent.com/56274518/66341908-2755d680-e916-11e9-9083-706b45ad666d.png">

**Comment by GitHubDer** [comment]
1.9.10 Chrome63.0.3239.108 也是加载不出来 macOS下的就可以

**Comment by Coulomb-G** [comment]
请先更新一下各自的浏览器版本和Violentmonkey版本 至最新版
并阅读RAEDME中的兼容性相关部分的说明

**Comment by GitHubDer** [comment]
嗯 估计是需要新版本的Chrome了吧

**Comment by the1812** [comment]
~~我不记得最近有用什么很新的API了...~~
如果你们说的maxthon是傲游浏览器的话, 我在5.3.8版中加Violentmonkey 2.8.4测试, 可以正常使用

**Comment by Sierra33** [comment]
已下载maxthon5.3.8，可以正常使用
（5.3.8是beta版本，怪不得默认更新一直是5.2.7最新.........)

**Comment by the1812** [comment]
(我没找到5.2.7的安装包才装的5.3.8
之后再找找旧版Chrome吧

**Comment by SodaShin** [comment]
更新了5.3.8beta可以用了  感谢
