### ISSUE TITLE
网页全屏时控制条显示不全

### ISSUE THREAD

**Issue by Xiaoyuan-xyz** [the1812/Bilibili-Evolved#2110]
**关于哪一项功能**

播放器的控制条。

**问题描述**

网页全屏时，如果页面宽度不够，一个特别长的“发送弹幕”会把右边的所有按键挤到窗口外去。

**脚本版本**

Stable v1.12.13 内容包: a1270fb

**浏览器版本**

Microsoft Edge
版本 92.0.902.62 (官方内部版本) (64 位)

**播放器版本**

2.63.1-6d677cca

**错误信息**

**附加截图**

网页全屏时：
![Snipaste_2021-08-01_10-51-34](https://user-images.githubusercontent.com/50108649/127758036-41d1f47a-473d-4881-b463-1c8c5222a572.png)
没有网页全屏时，即使此时宽度比网页全屏宽度还窄：
![Snipaste_2021-08-01_10-54-38](https://user-images.githubusercontent.com/50108649/127758052-cd942e81-7aa6-4adf-8891-ff54876617f3.png)

关闭脚本，在网页全屏时：
![Snipaste_2021-08-01_10-52-00](https://user-images.githubusercontent.com/50108649/127758064-0f70e8e8-f782-4727-8832-968985d46b37.png)

**Comment by the1812** [comment]
你开了强制保留弹幕栏吧

**Comment by Xiaoyuan-xyz** [comment]
原来如此，在“视频”里翻了几次也没找到就来了，用功能搜索的时候也没考虑到这一点。
可能是之前不小心点到了吧...
麻烦您了。
