### ISSUE TITLE
还有一个新issue，部分用户头像不加载

### ISSUE THREAD

**Issue by StudentTang** [the1812/Bilibili-Evolved#2112]
**关于哪一项功能**
不算某种功能，可能是扩展连带加重问题

**问题描述**

评论或动态，图片可能都会

**脚本版本**

v1.12.13

**浏览器版本**

Microsoft Edge
版本 92.0.902.62 (官方内部版本) (64 位) （最新）

**播放器版本**

2.63.2-rc.8997.0-32d49610（和本问题无关）

**错误信息**

![image](https://user-images.githubusercontent.com/29865920/127760969-6f073574-ded3-4981-ad35-d4909123ff23.png)
![image](https://user-images.githubusercontent.com/29865920/127760980-522918d4-aa3f-4a55-93a2-060c499008cb.png)
其他报错信息大概可见我之前另一个问题的，大概
我觉得是网络问题，但网络不加载图前就报错，无法提供更多思路
**附加截图**
![image](https://user-images.githubusercontent.com/29865920/127761002-f95e0a5d-7c01-4369-abf7-c66f4f3a93e6.png)

**Comment by 1357310795** [comment]
怕是网络问题。看着和脚本无关。

**Comment by RingingVolcano** [comment]
可能是网络问题 与脚本无关

**Comment by the1812** [comment]
b 站图片 cdn 偶尔会抽风的
