### ISSUE TITLE
1.12.13版本下使用番剧时左右快捷键仍不可用

### ISSUE THREAD

**Issue by Cypas** [the1812/Bilibili-Evolved#2113]
**问题描述**
番剧:https://www.bilibili.com/bangumi/play/ss36170
关闭该脚本时左右快捷键可用，启用脚本后左右快捷键不可用，控制台输出为找不到视频节点
![图片](https://user-images.githubusercontent.com/53274578/127764666-24a601a3-15bb-4d25-8ede-a0b88ba4a85f.png)

**脚本版本**
Stable v1.12.13
内容包: 16f171b

**浏览器版本**
firefox90.0.2 国际版

**播放器版本**
version: 3.0.3-rc.1
revision: 8a43abe8

**错误信息**
![图片](https://user-images.githubusercontent.com/53274578/127764666-24a601a3-15bb-4d25-8ede-a0b88ba4a85f.png)

**附加截图**
视频区域的html结构
![图片](https://user-images.githubusercontent.com/53274578/127764845-368a3e2e-b162-4f0e-af0f-a36e0ecac0d1.png)
控制台用jqury查找时为null
![图片](https://user-images.githubusercontent.com/53274578/127764873-da036d17-de37-4a71-9ebe-e8641991a933.png)

**Comment by Geeyun-JY3** [comment]
重复：#2092

不 要 急：[v1.12.13](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.12.13)
> 仅做了一些小适配, 很多地方我也还没摸清楚
