### ISSUE TITLE
[夜间模式适配] 视频投票框改版导致应用主题色失败

### ISSUE THREAD

**Issue by RingingVolcano** [the1812/Bilibili-Evolved#2115]
视频播放器投票框 又 双 叒 改版了（之前是线 现在改成圆角矩形）
导致应用主题色失败
![UZNWV)G W3UQ8A ~E5CYFL](https://user-images.githubusercontent.com/72140353/127777548-e1ce21d5-e440-4ff8-ad75-080e5a26d441.png)
eg.https://www.bilibili.com/video/BV1uT4y1T734

**Comment by Geeyun-JY3** [comment]
这玩意之前就一直没适配过……

**Comment by RingingVolcano** [comment]
> 这玩意之前就一直没适配过……：[#1289 (comment)](https://github.com/the1812/Bilibili-Evolved/issues/1289#issuecomment-768001001) [#1332 (reply in thread)](https://github.com/the1812/Bilibili-Evolved/discussions/1332#discussioncomment-475043)

我记得后来好像适配了主题色
可能是记错了（？
~~也可能之前线条的时候还没显得这么不协调(~~

**Comment by Geeyun-JY3** [comment]
旧版投票框就那个已选选项的那个圈跟随了主题色，应该是别处的适配误打误撞应用到的，现在依然是这样，还多了个外面关闭按钮的「✖」。
但就现在这个投票框的样式，这个圈还不能跟随主题色了。

**Comment by RingingVolcano** [comment]
> 但就现在这个投票框的样式，这个圈还不能跟随主题色了。

官方这个蓝色取得还挺丑的（
