### ISSUE TITLE
B站今天直播更新了个表情特效 希望能屏蔽

### ISSUE THREAD

**Issue by KnightEmperor** [the1812/Bilibili-Evolved#2116]
**问题描述**
大概是大部分大主播直播间 应该需要主播开播才可看到
我刚刚就在散人直播间有看到，其他直播间不清楚 （直播间号：1017） 应该需要主播开播才可看到
在主播间输入弹幕框有个表情符号 点开可以发送对应弹幕的表情格式（大概学的是Twitch，而且大部分是梗）
虽然B站给了关闭表情特效（魔法棒处），但也就关闭个右侧的气泡显示
弹幕还是以表情格式显示 希望能屏蔽表情样式 不想弹幕区乱糟糟的 

**脚本版本**
v1.12.13

**浏览器版本**
92.0.902.62

**附加截图**
![image](https://user-images.githubusercontent.com/69032631/127847045-bb254d21-1cfe-4100-8ad2-69d033c105c4.png)
![image](https://user-images.githubusercontent.com/69032631/127847089-0ad9af46-222b-4e4c-83d7-4459807086f8.png)

**Comment by the1812** [comment]
这个东西会在直播画面的弹幕里出现, 也会在右侧弹幕列表出现
但画面里那个没有留字, 只能隐藏掉
右侧列表里的可以把图换成字
