### ISSUE TITLE
播放器下面的一条操作栏无法显示完全

### ISSUE THREAD

**Issue by zt0408** [the1812/Bilibili-Evolved#2122]
**关于哪一项功能**

**问题描述**

**脚本版本**
 v1.12.13

**浏览器版本**
Microsoft Edge 92.0.902.62

**播放器版本**
2.63.3 

**错误信息**

**附加截图**

![image](https://user-images.githubusercontent.com/63178522/128133435-b24dbde2-5aee-414b-89a7-40b8312f6711.png)

**Comment by the1812** [comment]
你页面宽度太小了
关掉播放器触摸支持, 视频截图和逐帧调整可以减少宽度占用
