### ISSUE TITLE
触摸屏下mini播放器支持触摸移动

### ISSUE THREAD

**Issue by tabris233** [the1812/Bilibili-Evolved#213]
**关于哪一项功能**

触摸优化

**期望的效果**

支持触摸移动mini播放器
目前只能用鼠标才能移动

**脚本版本**

正式版， 
ps：我也可以用预览版的

**Comment by tabris233** [comment]
发现chrome有一个 叫 哔哩哔哩助手 的插件  
其中的画中画模式 很好的支持了画中画的触摸  
可以自由调整大小，触摸移动，点击暂停等  切换标签页也可以使用
![image](https://user-images.githubusercontent.com/29500388/66500862-e4058e80-eaf4-11e9-850a-1598c5dd44e9.png)

**Comment by the1812** [comment]
那个是Chrome的功能，视频上右键两次就可以选择
