### ISSUE TITLE
动态相关功能不支持个人空间搜索结果中的动态

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#2137]
**关于哪一项功能**
快速收起动态评论区
动态翻译
评论翻译
禁止跳转动态详情
动态链接复制
评论链接复制
动态图片导出

**问题描述**
`快速收起动态评论区`、`动态翻译`、`评论翻译`、`禁止跳转动态详情`、`动态链接复制`、`评论链接复制`、`动态图片导出` 等动态相关功能不支持个人空间搜索结果中的动态。
经测试目前支持的只有 `展开动态内容`。

**脚本版本**
正式版 v1.12.13
预览离线版 v1125.95

**浏览器版本**
百分浏览器 4.3.9.248（正式版本） （64 位） (Chromium 86.0.4240.198)
Chrome 92.0.4515.131（正式版本） （64 位）

**播放器版本**

不涉及播放器

**错误信息**

**附加截图**

**Comment by the1812** [comment]
做得真是粗糙, 圆角和边框都没有

<span>
<img src="https://user-images.githubusercontent.com/26504152/129438784-e2a72672-6b55-4f88-b6bb-6a0482e67e9f.png" height="200">
<img src="https://user-images.githubusercontent.com/26504152/129438786-2d4c611e-d2f9-47f3-b25d-27eaee54717d.png" height="200">
</span>

**Comment by Geeyun-JY3** [comment]
最近新功能上得也多( ´_ゝ` )

**Comment by Geeyun-JY3** [comment]
挖到一个年初发的 discussion：#1450，也是动态相关功能在特定页面的适配🌚。

**Comment by the1812** [comment]
话题不是支持了吗

**Comment by Geeyun-JY3** [comment]
~~其实我刚刚发之前也没去验证过~~
啊好像确实是已经支持了（我这边收起评论可以诶）

**Comment by Geeyun-JY3** [comment]
~~其实我刚刚发之前也没去验证过~~
啊好像确实是已经支持了（我这边收起评论可以诶）
