### ISSUE TITLE
能否出个开关关闭长按快进自动倍数的功能

### ISSUE THREAD

**Issue by cnoim** [the1812/Bilibili-Evolved#2138]
**关于哪一项功能**
视频播放

**问题描述**
任何视频都可触发，长按快进键即可触发

**脚本版本**
Preview Offline v1118.07

**浏览器版本**
Microsoft Edge 92.0.902.67

**播放器版本**
2.64.2-f5ce9dea

**错误信息**

![QQ截图20210812220555](https://user-images.githubusercontent.com/52961523/129211193-23a4db7d-f616-40ff-9da9-22cc70348807.png)

**Comment by Geeyun-JY3** [comment]
纯好奇，这个需求的使用场景是什么？

**Comment by the1812** [comment]
没看懂

**Comment by cnoim** [comment]
> 没看懂

看视频的时候你长按快进试试看

**Comment by the1812** [comment]
是指按住右方向会快进很多吗

**Comment by Geeyun-JY3** [comment]
![image](https://user-images.githubusercontent.com/49396421/129436045-8d3e3551-e9a4-4224-abd2-fe23f82f3999.png)
![哔哩](https://user-images.githubusercontent.com/49396421/129436049-680ba92c-9d18-45d6-acba-cd234bfb1874.jpg)

> 是指按住右方向会快进很多吗

其实左右好像都有，不过机制好像不太一样（左快退好像还指示，经典没做完）

**Comment by cnoim** [comment]
> ![image](https://user-images.githubusercontent.com/49396421/129436045-8d3e3551-e9a4-4224-abd2-fe23f82f3999.png)
> ![哔哩](https://user-images.githubusercontent.com/49396421/129436049-680ba92c-9d18-45d6-acba-cd234bfb1874.jpg)
> 
> > 是指按住右方向会快进很多吗
> 
> 其实左右好像都有，不过机制好像不太一样（长按左方向快退好像还没有指示，经典没做完）

对的

**Comment by the1812** [comment]
不太懂b站这个原理, 先记下了

**Comment by Geeyun-JY3** [comment]
@cnoim 是单纯不喜欢这样吗？这个需求的使用场景是什么？

**Comment by Geeyun-JY3** [comment]
以前长按 <kbd>→</kbd> 是怎样的行为？和现在长按 <kbd>←</kbd> 一样每不知道几秒快退 30 秒（即当前画面不变，播放器控制栏视频时间会显示 30 秒 30 秒地往前退）？
如果是的话，是否可以将这个需求理解为希望长按 <kbd>→</kbd> 的变回每不知道几秒快进 30 秒？

**Comment by cnoim** [comment]
> 以前长按 → 是怎样的行为？和现在长按 ← 一样每不知道几秒快退 30 秒（即当前画面不变，播放器控制栏视频时间会显示 30 秒 30 秒地往前退）？
> 如果是的话，是否可以将这个需求理解为希望长按 → 的变回每不知道几秒快进 30 秒？

差不多是这个意思 对比以前这个快进速度慢多了
以及番剧还未改版，但是快进快退的策略和视频不一样

**Comment by Geeyun-JY3** [comment]
另外，开启了 `快捷键扩展` 的情况下，今天我这边的播放器好像就无法长按播放了。忘记前几天和 Bilibili Evolved  兼不兼容了。
今天已有相关反馈：https://github.com/the1812/Bilibili-Evolved/issues/2150#issuecomment-899199903

所以现在其实可以通过开启 `快捷键扩展` 来暂时实现该需求。

**Comment by Geeyun-JY3** [comment]
另外，开启了 `快捷键扩展` 的情况下，今天我这边的播放器好像就无法长按播放了。忘记前几天和 Bilibili Evolved  兼不兼容了。
今天已有相关反馈：https://github.com/the1812/Bilibili-Evolved/issues/2150#issuecomment-899199903

所以现在其实可以通过开启 `快捷键扩展` 来暂时实现该需求。

**Comment by 11111111111ge1** [comment]
> 纯好奇，这个需求的使用场景是什么？
https://www.bilibili.com/video/BV1G44y1C7kL
https://www.bilibili.com/video/BV1V3411r77J
文字游戏的实况流程, 每个人阅读速度不一样. up主为了照顾阅读较慢的观众 会把演出速度拉到最慢. 
正常情况下 应该通过开倍速来解决
但语音倍速后会变得不正常, 所以我会用这个功能

**Comment by 424778940z** [comment]
同样遇到这个问题, 希望提供一个以前长按行为的选项 而不是加速播放 跳跃效率不一样 具体参考ytb播放器

**Comment by Geeyun-JY3** [comment]
> 没事了, 好像快捷键扩展里长跳跃范围设置成5秒, 快捷键绑定成 arrowLeft 和 arrowRight 在目前版本是可以实现的

呃`快捷键扩展`中有专门的`前进`/`倒退`可供自定义的，[2.8.6](https://github.com/the1812/Bilibili-Evolved/releases/tag/v2.8.6) 开始默认不启用了而已，不用去动长跳跃。

**Comment by Geeyun-JY3** [comment]
顺便@the1812，这个 issue 和 #2352 都可以关了。
