### ISSUE TITLE
[功能请求]为快捷键添加定位到播放器功能

### ISSUE THREAD

**Issue by MasterOfStar** [the1812/Bilibili-Evolved#2150]
## 在快捷键中添加定位到播放器功能
已经有自动定位到播放器功能了，能否添加快速调用该功能的快捷键？宽屏播放器只用鼠标滚轮调节的话播放器位置要么偏上要么偏下（即要么标题显示不全，要么一键三连功能区显示不全或不显示），不如定位到播放器那样直接居中合适。

## 另：能否加入缩小up主头像区域的功能？
宽屏播放器下，在非联合投稿时，up主头像大小（如下图）较大，在保证标题和一键三连功能区完全显示时，up主头像区域无法显示完整。
![image](https://user-images.githubusercontent.com/21274896/129509120-d3b0f686-c93b-4a4c-a267-6e1a70a4f089.png)
在联合投稿时（如下图），up主头像较小，在保证标题和一键三连功能区完全显示时，up主头像区域可以显示完整。
![image](https://user-images.githubusercontent.com/21274896/129509416-119a5d27-ff47-4b21-95aa-733e5896528f.png)
能否加入将单独投稿时的up主头像显示为联合投稿时的样式的功能？

**Comment by MasterOfStar** [comment]
## 另：反馈一个问题 自动定位到播放器似乎会在应用播放模式之前就生效，导致点开页面之后变成宽屏播放之前就定位了。然后变成宽屏播放，定位又歪了，一键三连区显示不全。
![image](https://user-images.githubusercontent.com/21274896/129510507-d11f066d-a32c-4593-b947-19048e6fef69.png)

**Comment by Geeyun-JY3** [comment]
针对 https://github.com/the1812/Bilibili-Evolved/issues/2150#issuecomment-899199903 反馈的两个问题：
1. 自动定位是老问题：#483
2. 最近播放器加的新功能都没怎么做适配：#2131、#2138
https://github.com/the1812/Bilibili-Evolved/discussions/2141#discussioncomment-1181000

**Comment by MasterOfStar** [comment]
closed
