### ISSUE TITLE
能否加个外挂字幕的翻译功能？

### ISSUE THREAD

**Issue by BrandonStudio** [the1812/Bilibili-Evolved#2153]
现在外挂字幕陆续变成繁体的了，能否加个自动翻译成简体的功能？

**Comment by Geeyun-JY3** [comment]
如果是港澳台建议还是自力更生：#2143

**Comment by the1812** [comment]
所以是哪的外挂字幕

**Comment by qiuyuyang910** [comment]
> 所以是哪的外挂字幕

仅限港澳台番剧的外挂字幕

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/2143#issuecomment-899042625
可以按这里说的下载下来, 自行找工具翻译 (我听说 PotPlayer 好像有这种功能)

**Comment by RingingVolcano** [comment]
有个脚本是网页繁简转换 不过我不清楚这个能不能实现你提的需求 可以试试
https://greasyfork.org/zh-CN/scripts/24300-switch-traditional-chinese-and-simplified-chinese
