### ISSUE TITLE
视频的【播放前显示封面】功能问题

### ISSUE THREAD

**Issue by Chi1024** [the1812/Bilibili-Evolved#2155]
**关于哪一项功能**
视频的【播放前显示封面】

**问题描述**

播放时暂停，然后在视频上悬浮鼠标时，会【出现大约0.3秒的封面图，然后消失】。移动鼠标时【也会出现此现象】。当鼠标在视频外移动时没有此现象。
加载模式由【同时】改为【延后】之后，此现象会变化，变为【出现大约0.8秒的封面图，然后消失】

**脚本版本**

Stable v1.12.13
内容包: 0329421

**浏览器版本**

Chrome 版本 92.0.4515.131（正式版本）

**播放器版本**

2.64.3

**错误信息**

Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
BV1nQ4y1m7CP:1 Error handling response: TypeError: Cannot destructure property 'yt' of 'undefined' as it is undefined.
    at chrome-extension://cmedhionkhpnakcndndgjdbohmhepckk/scripts/contentscript.js:535:6

Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
index_new_pc_sync:1 Error handling response: TypeError: Cannot destructure property 'yt' of 'undefined' as it is undefined.
    at chrome-extension://cmedhionkhpnakcndndgjdbohmhepckk/scripts/contentscript.js:535:6
userscript.html?name=Bilibili%20Evolved.user.js&id=07aa9e5e-998f-4ff4-9167-f201299d8142:13210 Skipped <iframe> loading for https://message.bilibili.com/pages/nav/index_new_pc_sync

**附加截图**

**Comment by the1812** [comment]
#2103 ?
