### ISSUE TITLE
“轻视频”适配

### ISSUE THREAD

**Issue by taozhiyu** [the1812/Bilibili-Evolved#2156]
**关于哪一项功能**
“轻视频页面”的适配（或者说是排除页面？）

**问题描述**
用的人不多，但是会报错，例如[这个页面](https://bbq.bilibili.com/video/?id=1628392801077034891)（随变找的一个例子）
如果不方便适配的话可以直接取消页面匹配🤔，反正知道的人不多，用的人不多，电脑上看的人更不多🤣

**脚本版本**
正式版1.12.13（prev也测试过了）

**错误信息&&附加截图**
控制台报错

![image](https://user-images.githubusercontent.com/49258735/129818277-bfd1246b-acbe-4ff5-bd29-c08addcd0092.png)

报错的地方

![image](https://user-images.githubusercontent.com/49258735/129818693-c8221407-ff11-4a20-a18b-b855cb4ac8e3.png)

**Comment by Geeyun-JY3** [comment]
建议排除，这一看就是引流至 App，更不用说 PC 网页端

**Comment by RingingVolcano** [comment]
直接排除就行 反正也没多少人用（
