### ISSUE TITLE
`评论翻译` 导致楼中楼评论文本有个多余的缩进（和换行？）

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#2159]
**关于哪一项功能**
评论翻译

**问题描述**
开启 `评论翻译` 后楼中楼会像简化评论区一样评论文本换行，还有个缩进。
原版好像是不换行的。不过这个我没什么所谓，主要是缩进。

**脚本版本**
正式版 v1.12.13
预览离线版 v1125.95

**浏览器版本**
百分浏览器 4.3.9.248（正式版本） （64 位） (Chromium 86.0.4240.198)
Chrome 92.0.4515.159（正式版本） （64 位）

**播放器版本**
不涉及播放器

**错误信息**

**附加截图**
未开启功能
![image](https://user-images.githubusercontent.com/49396421/129836880-d4317a10-08b2-4c80-872c-03355c0813c8.png)
开启功能后
![image](https://user-images.githubusercontent.com/49396421/129837318-294a3ca3-1a2e-4424-9fcc-0dabe90b8c96.png)

**Comment by RingingVolcano** [comment]
![image](https://user-images.githubusercontent.com/72140353/129889733-4c734362-8b8a-41f6-a85c-05d1348b08bb.png)
简化版评论区是正常的
~~不过我觉得应该也没多少人用这功能 要翻译某条评论不如额外装个划词翻译来得方便~~
![image](https://user-images.githubusercontent.com/72140353/129890071-199f4304-7707-4e03-9d1d-3b9195eb10c9.png)
