### ISSUE TITLE
简化首页后的个性化推荐刷新

### ISSUE THREAD

**Issue by FengQi312** [the1812/Bilibili-Evolved#2168]
**关于哪一项功能**
简化首页后像热门等区域的标题会被认为文本格式

**问题描述**
把鼠标悬浮在简化首页后像热门等区域的标题上，会出现文本样式的鼠标

**脚本版本**
正式版v1.12.13

**浏览器版本**
Chrome 92.0.4515.159

**播放器版本**
不用吧

**错误信息**
无需

**附加截图**
![image](https://user-images.githubusercontent.com/82657010/130224742-0bf44ee5-aba1-44fb-8b4d-abe819354553.png)

**Comment by the1812** [comment]
就是文本啊

**Comment by FengQi312** [comment]
不应改是直接跳转到热门等专区吗？

**Comment by the1812** [comment]
那个地方现在改成个性化推荐了, 我这边标题名字还没换, 个性化推荐有专区页面吗?

**Comment by FengQi312** [comment]
但是就是官方的个性化推荐，右边有一个换一批按钮。

**Comment by FengQi312** [comment]
就是能不能加上一个换一批的按钮

**Comment by the1812** [comment]
能啊 不过会加在右边
