### ISSUE TITLE
为什么播放器默认为旧版？

### ISSUE THREAD

**Issue by zhouwenhai616** [the1812/Bilibili-Evolved#217]
我习惯使用新版播放器页面，但是启用插件后，却总是默认给跳回旧版，还要自己手动切换，就很烦恼

**Comment by the1812** [comment]
如果开了`指定播放器布局`, 请确认都是设的`新版` (或者也可以选一下`旧版`再选`新版`让脚本重新设一遍新版)
如果没开, 应该是不会影响新旧播放器的

**Comment by ZCXLLOD** [comment]
@the1812 
看了一下，发现正式版（1.9.12）、预览版（1.9.13）和预览离线版（458.89）确实有这个问题，离线版（453.28）的话是概率发生，测试发现默认播放器的选择上与脚本的视频--指定播放器布局功能中具体的布局设置有关，与该功能是否开关无关，例如先开启指定播放器布局功能，然后设置视频区布局为旧版，最后再关闭该功能，之后打开普通视频播放器为旧版，手动切换为新版后刷新网页，播放器会又变回旧版。
-----
谷歌浏览器 77.0.3865.120（正式版本） （64 位）

**Comment by ZCXLLOD** [comment]
@the1812
看了一下，发现正式版（1.9.12）、预览版（1.9.13）和预览离线版（458.89）确实有这个问题，离线版（453.28）的话是概率发生，测试发现默认播放器的选择上与脚本的视频--指定播放器布局功能中具体的布局设置有关，与该功能是否开关无关，例如先开启指定播放器布局功能，然后设置视频区布局为旧版，最后再关闭该功能，之后打开普通视频播放器为旧版，手动切换为新版后刷新网页，播放器会又变回旧版。

谷歌浏览器 77.0.3865.120（正式版本） （64 位）

**Comment by the1812** [comment]
确实有这个bug, 不过测试的时候我还发现会跟b站原本的新旧版选择产生一些严重冲突, 所以这个功能我打算删掉了, 届时请使用b站原本的新旧版选择吧.
