### ISSUE TITLE
任意用户主页搜索任意内容后部分区域样式不正确

### ISSUE THREAD

**Issue by BiliGoldenWater** [the1812/Bilibili-Evolved#2170]
**关于哪一项功能**
夜间模式

**问题描述**

任意用户主页搜索任意内容(具体看附加截图

**脚本版本**

Stable v1.12.13 内容包: 03df601

**浏览器版本**

Microsoft Edge
版本 92.0.902.73 (官方内部版本) (64 位)

**播放器版本**

**错误信息**

**附加截图**
![Snipaste_2021-08-21_03-24-17](https://user-images.githubusercontent.com/53564043/130283943-2745e09b-8a8f-41ef-ab62-9bdb3b3f37c1.png)
![Snipaste_2021-08-21_03-24-10](https://user-images.githubusercontent.com/53564043/130283948-50fe03ac-9e0d-41ff-adc8-73fcaf939154.png)

**Comment by Geeyun-JY3** [comment]
重复，且预览版修了：#2136
https://github.com/the1812/Bilibili-Evolved/blob/preview/doc/issue-rules.md
> > 提示: 最好先在预览离线版(Preview Offline)中测试一下, 有些问题可能已经修复了但还未正式发布.
