### ISSUE TITLE
自定义顶栏的消息无法正常显示

### ISSUE THREAD

**Issue by q56535** [the1812/Bilibili-Evolved#2171]
**关于哪一项功能**
自定义顶栏

**问题描述**

自定义顶栏的消息因B站消息接口改动而无法正常显示

**脚本版本**

正式版1.12.13

**浏览器版本**

Chrome 92

**播放器版本**

2.64.2

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/26663837/130315398-07d5fa5d-a4af-41e6-a2d3-3b7dc7507c09.png)
![image](https://user-images.githubusercontent.com/26663837/130315415-f89d0f89-68be-4ab6-bffd-f151a264898d.png)

**Comment by the1812** [comment]
有人找到新接口了吗, 原先那个好像一直返回 0 条未读

**Comment by q56535** [comment]
bilibili助手找到了

**Comment by the1812** [comment]
原来是私信数目连 `0` 都懒得返回了... 我这计算总数一加起来就变成 `NaN` 了
