### ISSUE TITLE
希望可以增加解除b站直播检测的功能

### ISSUE THREAD

**Issue by Ting-fYuan** [the1812/Bilibili-Evolved#2172]
**关于哪一项功能**
b站直播检测

**问题描述**

在b站挂直播的时候，大概十来分钟鼠标没有移动的话，b站会跳出一个提示，导致无法继续挂直播

**脚本版本**

Preview v1.12.15

**浏览器版本**

Edge版本 92.0.902.78 

**播放器版本**

bilibili html5 live player 3.3.24

**错误信息**

无
**附加截图**
暂无

**Comment by Geeyun-JY3** [comment]
重复：#1159
