### ISSUE TITLE
只能用滚轮，所有的都不能点击

### ISSUE THREAD

**Issue by theabg** [the1812/Bilibili-Evolved#2176]
**关于哪一项功能**

**问题描述**
08-20刷新了一下页面就突然成这样。
只能用滚轮滚动页面，滚轮点击也不能用，所有的都不能点击。
应该是浏览器的问题，试过qq浏览器能用

**脚本版本**
正式版 1.12.13

**浏览器版本**
Microsoft Edge
版本 92.0.902.78 (官方内部版本）

**播放器版本**

**错误信息**
所有页面都不能点击，就像是一张图片，只能用滚轮滚动页面，Bilibili-Evolved 菜单也不能点击。

**附加截图**
![Snipaste_2021-08-21_23-07-46](https://user-im
![Uploading Snipaste_2021-08-21_23-09-41.png…]()
ages.githubusercontent.com/73643743/130326290-9216908e-b39b-47e6-b64a-92d7f9a56e16.png)
![Snipaste_2021-08-21_23-09-08](https://user-images.githubusercontent.com/73643743/130326334-5b7386b9-610b-42cd-9c50-6984ef49dc16.png)
检查里面
![Snipaste_2021-08-21_23-15-08](https://user-images.githubusercontent.com/73643743/130326365-c01233c1-d92d-41cd-919d-aad04fb26e6f.png)

**Comment by theabg** [comment]
![Uploading Snipaste_2021-08-21_23-09-08.png…]()
![Snipaste_2021-08-21_23-07-46](https://user-images.githubusercontent.com/73643743/130326276-67f42f09-26f0-4cce-9c13-0f76c63da85d.png)

**Comment by theabg** [comment]
![Uploading Snipaste_2021-08-21_23-09-41.png…]()

**Comment by RingingVolcano** [comment]
建议卸载脚本后重装试试 应该不是脚本本身的问题

**Comment by theabg** [comment]
> 建议卸载脚本后重装试试 应该不是脚本本身的问题

应该是浏览器的问题，qq浏览器能用

**Comment by theabg** [comment]
已经解决，是另一个插件，叫梦想划词翻译—聚合词典搜索中自动解除访问页面选中文字和右键限制设置有关，
