### ISSUE TITLE
【适配】简化评论区的底部评论框在不可新增评论的视频内有一些显示问题

### ISSUE THREAD

**Issue by RingingVolcano** [the1812/Bilibili-Evolved#2185]
**关于哪一项功能**
简化评论区

**问题描述**
eg.https://www.bilibili.com/video/BV1pJ411R7KZ
官方的底部评论框在不可新增评论的视频中 还有一个窄样式
![image](https://user-images.githubusercontent.com/72140353/130336032-cd044c49-4afc-44a5-ac13-81f0ab13276f.png)

开启简化评论区后此处会有一些显示问题
![image](https://user-images.githubusercontent.com/72140353/130336050-1bc71404-ecfd-4b1a-afb5-77c2b1802618.png)
![image](https://user-images.githubusercontent.com/72140353/130336055-78d04755-cbf1-4bfe-8a41-c48eaf444b79.png)

**脚本版本**
Preview v1.12.16

**浏览器版本**
Chrome 92

**Comment by the1812** [comment]
以前只在未登录时这样, 忘了还有关闭评论区了

**Comment by RingingVolcano** [comment]
> 以前只在未登录时这样, 忘了还有关闭评论区了

关闭评论区没底栏这个框 不可新增评论是另外一种状态
