### ISSUE TITLE
网页全屏时无法隐藏顶部栏，已持续多个版本

### ISSUE THREAD

**Issue by adfnkjasd** [the1812/Bilibili-Evolved#2189]
问题描述
<最新版脚本仍然无法实现网页全屏时隐藏顶部栏>

脚本版本
<v1.12.16>

浏览器版本
<版本 92.0.4515.159（正式版本） （64 位）>

播放器版本
<3.0.4-rc.1-2c0dae5e>

错误信息
控制台无错误信息

![QQ截图20210822164813](https://user-images.githubusercontent.com/39746646/130348753-f7235a8c-d3e6-4410-b162-2f6ff8fe8dd7.jpg)

**Comment by Geeyun-JY3** [comment]
重复，番剧 3.0 播放器问题：#1992。
[v1.12.13](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.12.13) 修过这个自定义顶栏，B 站又改了。

**Comment by the1812** [comment]
居然又改了

**Comment by Geeyun-JY3** [comment]
> 居然又改了

https://github.com/the1812/Bilibili-Evolved/issues/1992#issuecomment-895314598
1.12.14 就有相关反馈了……

**Comment by wwzw27** [comment]
之前修好了，现在又出问题了。麻了

**Comment by xzk-kokodayo** [comment]
补充，最新的1.12.16依然存在

**Comment by Geeyun-JY3** [comment]
> 补充，最新的1.12.16依然存在

不用补充，本 issue 反馈的就是 1.12.16

**Comment by Geeyun-JY3** [comment]
@the1812 可以关了
