### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 1090430027** [the1812/Bilibili-Evolved#219]
顶栏从左往右第三个“排行”点进去显示
请求地址: http://www.bilibili.com/ranking?query=%2Fetc%2Fpasswd  
由于触发哔哩哔哩安全风控策略，该次访问请求被拒绝。
The request was rejected because of the bilibili security control policy.  
![image](https://user-images.githubusercontent.com/36582192/67147384-19fdfc00-f2c7-11e9-89d4-0b50e4635dce.png)

**Comment by Coulomb-G** [comment]
这个地址打得开吗?https://www.bilibili.com/ranking

**Comment by 1090430027** [comment]
打开就是这样





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Coulomb-G"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月19日(星期六) 晚上11:34
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"周俊"<1090430027@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] bug (#219)




这个地址打得开吗?https://www.bilibili.com/ranking

**Comment by Coulomb-G** [comment]
是b站的锅,不是这个脚本造成的

**Comment by 1090430027** [comment]
刚刚b站客服联系我了，说已经工程师已经解决了，刚刚重新打开就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Coulomb-G"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月19日(星期六) 晚上11:40
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"周俊"<1090430027@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] bug (#219)




是b站的锅,不是这个脚本造成的
