### ISSUE TITLE
顶部动态栏只显示单列

### ISSUE THREAD

**Issue by uk4646** [the1812/Bilibili-Evolved#2191]
**关于哪一项功能**

动态视频展示

**问题描述**

顶部动态视频只显示一列，不能显示双列

**脚本版本**

正式版1.12.16

**浏览器版本**
Microsoft Edge 版本 92.0.902.78

**错误信息**

**附加截图**
![QQ截图20210823120755](https://user-images.githubusercontent.com/89371547/130389591-2da0f74a-4361-4be9-bcb3-8ebfabc3de64.jpg)
![QQ截图20210823121800](https://user-images.githubusercontent.com/89371547/130389595-d72fa403-8e35-424e-996c-dec985e2675f.jpg)

**Comment by Geeyun-JY3** [comment]
根据 <https://github.com/the1812/Bilibili-Evolved/issues/3990#issuecomment-1426999111>、<https://github.com/the1812/Bilibili-Evolved/issues/3990#issuecomment-1427061949> 的反馈，这个 bug 应该已经修了。
