### ISSUE TITLE
macOS 中文输入法选词与搜索建议冲突

### ISSUE THREAD

**Issue by KElee01** [the1812/Bilibili-Evolved#2197]
**关于哪一项功能**
顶栏搜索框的搜索建议/搜索历史

**问题描述**

如图，在 macOS 输入法设置中将拼音输入法的候选字框显示方向设置为垂直，这样选词时需要用方向键上/下进行选择。
<img width="780" alt="截屏2021-08-23 下午8 00 54" src="https://user-images.githubusercontent.com/54350573/130444677-83060d77-cce7-4c25-8e9b-733cd335e2ab.png">

如图，在顶栏上的搜索框选词时，如果搜索框下方有搜索建议/搜索历史，则在选词时方向键上/下会被脚本识别，焦点移到搜索建议/搜索历史上，导致选词失败。
<img width="1436" alt="截屏" src="https://user-images.githubusercontent.com/54350573/130444989-e04ce2eb-8dcf-444e-8446-e0b9d2538457.png">

**脚本版本**

Stable v1.12.16

**浏览器版本**

Safari 14.1.2

**播放器版本**

HTML5播放器 V2.64.0

**错误信息**

**附加截图**
<img width="1436" alt="截屏" src="https://user-images.githubusercontent.com/54350573/130444989-e04ce2eb-8dcf-444e-8446-e0b9d2538457.png">

**Comment by AQ-Official** [comment]
补充，不设为垂直，即使候选词是水平的。当按+键开启扩展选择菜单时，按上下键依旧会复现该bug
