### ISSUE TITLE
触摸拖动进度条与音量亮度功能失效

### ISSUE THREAD

**Issue by xhmooc** [the1812/Bilibili-Evolved#2198]
**关于哪一项功能**
触摸功能

**问题描述**

进度条拖动不了

**脚本版本**

正式版1.12.16

**浏览器版本**

edge92.0.902.78

**播放器版本**

3.04

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
3.0 播放器还没适配，参考：#1992
