### ISSUE TITLE
希望能有解除区域限制的功能

### ISSUE THREAD

**Issue by YuhangSco** [the1812/Bilibili-Evolved#220]
希望能解除区域限制，观看仅限港澳台的视频。

**Comment by the1812** [comment]
https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6

**Comment by YuhangSco** [comment]
好的，谢谢，不过我希望能进行一下功能整合

**Comment by YuhangSco** [comment]
多谢回复，了解了。
