### ISSUE TITLE
视频播放页自动定位问题

### ISSUE THREAD

**Issue by JackASil** [the1812/Bilibili-Evolved#2202]
“自动定位到播放器”功能与“默认播放器-宽屏”同时开启时，有时会先定位视频后切换至宽屏，导致定位失效。先切换宽屏情况下正常。

Stable v1.12.16 浏览器Firefox for windows 91.0.1 (64 位)

（老实说蛮卡的.. 开了脚本之后每次进视频页都要等一会儿才能加载出来。可能是机器配置过时了）

**Comment by Geeyun-JY3** [comment]
重复：#483
