### ISSUE TITLE
番剧与影视这类视频网页全屏播放时，顶栏不消失

### ISSUE THREAD

**Issue by ListeningRift** [the1812/Bilibili-Evolved#2206]
**关于哪一项功能**
顶栏

**问题描述**

番剧与影视等

**脚本版本**

1.12.16

**浏览器版本**

Edge  92.0.902.78 

**播放器版本**

**错误信息**

**附加截图**
![屏幕截图 2021-08-24 193816](https://user-images.githubusercontent.com/47731748/130610014-b1d3d3ba-c351-40a2-819e-00f233113b1b.png)

**Comment by Geeyun-JY3** [comment]
能不能先看看置顶：#1992
善用一下搜索：#2189
