### ISSUE TITLE
使用脚本下载B站视频（尤其是竖屏视频）时，如果视频封面高度较大会造成显示异常

### ISSUE THREAD

**Issue by ZCXLLOD** [the1812/Bilibili-Evolved#221]
**问题描述**
如图：
![image](https://user-images.githubusercontent.com/19368077/67173453-5a599900-f3f1-11e9-8545-ae00ec2e8c21.png)

视频举例：https://www.bilibili.com/video/av71758415

经测试正式版（1.9.12）、预览版（1.9.13）、离线版（453.28）和预览离线版（458.89）均有此问题。

临时解决方法：按Ctrl+减号缩小浏览器页面缩放比例
![image](https://user-images.githubusercontent.com/19368077/67173778-5d08be00-f3f2-11e9-93ce-2e76ec8e3e45.png)

**浏览器版本**
谷歌浏览器 77.0.3865.120（正式版本） （64 位）

**错误信息**
无报错。

**附加**
建议相关弹窗可以适应视频封面大小，并且当弹窗超出屏幕显示范围时不要使弹窗始终保持在屏幕中间，这样向下滑动页面即可看到弹窗超出的部分。

**Comment by the1812** [comment]
我限制下封面高度吧
