### ISSUE TITLE
番剧，电影，纪录片无法使用快捷键

### ISSUE THREAD

**Issue by EurekaThink** [the1812/Bilibili-Evolved#2210]
**关于哪一项功能**
快捷键

**问题描述**

无法使用快捷键
https://www.bilibili.com/bangumi/play/ep374724

**脚本版本**

v1.12.16

**浏览器版本**

Edge92.0.902.78

**播放器版本**

V2.64.0

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
能不能先看看置顶：#1992
