### ISSUE TITLE
功能建议：动态列左侧【“正在直播”列】改进

### ISSUE THREAD

**Issue by Chi1024** [the1812/Bilibili-Evolved#2211]
功能建议：
能否加长动态页左侧“正在直播”列表的长度，或者全部展示，或者自定义显示的个数

**Comment by the1812** [comment]
不是有个直播信息扩充的功能吗

**Comment by Chi1024** [comment]
嗯，已经用了那个功能了，但是感觉展示的行数还不太够

**Comment by yvvvan** [comment]
关于【直播信息扩充】组件，能不能把其中 registry/lib/components/feeds/extend-live/extend-feeds-live.scss
```
.live-up-list {
    max-height: calc(100vh - 380px);
    ...
```
修改一下。
380px好像有点太多了，以至于添加这个组件后，反而一次只能显示2-3个直播间，其他的直播间需要配合滚轮才能看到。
感觉减去80px到100px，体验会好一些。谢谢。
