### ISSUE TITLE
自定义顶栏在番剧网页全屏下没有隐藏

### ISSUE THREAD

**Issue by qibill** [the1812/Bilibili-Evolved#2212]
**关于哪一项功能**
样式-使用自定义顶栏

**问题描述**
自定义顶栏在番剧网页全屏下没有隐藏
视频举例：https://www.bilibili.com/bangumi/play/ep409822
https://www.bilibili.com/bangumi/play/ss29358

**脚本版本**
1.12.16

**浏览器版本**
Firefox 88.0.1

**播放器版本**
HTML5播放器 V2.64.0

**错误信息**
Error: Promised response from onMessage listener went out of scope   common.js:4:491

**附加截图**
![图片](https://user-images.githubusercontent.com/27934234/130644639-623815e4-f071-412a-90c9-37f0a07d4b93.png)
![图片](https://user-images.githubusercontent.com/27934234/130644748-4fb1502e-dc2b-4d06-8abf-b0eff57863d6.png)

**Comment by Geeyun-JY3** [comment]
能不能先看看置顶：#1992
善用一下搜索：#2189、#2206。上一个重复的 issue 就早你四个小时，都还没关，先去 issue 列表扫一眼都做不到吗……

**Comment by Geeyun-JY3** [comment]
能不能先看看置顶：#1992
善用一下搜索：#2189、#2206。上一个重复的 issue 就早你四个小时，都还没关，先去 issue 列表扫一眼都做不到吗……
