### ISSUE TITLE
为什么看不到齿轮呀，开了脚本没变化

### ISSUE THREAD

**Issue by CMHlover** [the1812/Bilibili-Evolved#222]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
浏览器版本和控制台报错是什么

**Comment by CMHlover** [comment]
谷歌最新版，
![image](https://user-images.githubusercontent.com/49261284/67999610-0d4eb000-fc98-11e9-9603-4ba3e129e713.png)

**Comment by CMHlover** [comment]
控制台是这个吗

**Comment by CMHlover** [comment]
35个错误1个警告........

**Comment by the1812** [comment]
那张图里点Console

**Comment by CMHlover** [comment]
![image](https://user-images.githubusercontent.com/49261284/67999704-569eff80-fc98-11e9-804f-fc7a7b1a80c9.png)
![image](https://user-images.githubusercontent.com/49261284/67999722-63bbee80-fc98-11e9-901a-dfa7504487fe.png)

**Comment by CMHlover** [comment]
![image](https://user-images.githubusercontent.com/49261284/67999837-c57c5880-fc98-11e9-830b-79dde83c4a6b.png)

**Comment by the1812** [comment]
你开的真的是b站? Elements那里完全不一样

**Comment by CMHlover** [comment]
![image](https://user-images.githubusercontent.com/49261284/67999919-1429f280-fc99-11e9-9fc7-92f573d8858c.png)
抱歉

**Comment by the1812** [comment]
谷歌浏览器版本是78吗

**Comment by CMHlover** [comment]
![image](https://user-images.githubusercontent.com/49261284/68000037-771b8980-fc99-11e9-99b4-996f1322ea8b.png)

**Comment by the1812** [comment]
脚本是装在Tampermonkey上吗?

**Comment by CMHlover** [comment]
是的

**Comment by CMHlover** [comment]
![image](https://user-images.githubusercontent.com/49261284/68000485-489eae00-fc9b-11e9-919a-637b648fff9b.png)

**Comment by the1812** [comment]
脚本是完整的吗? 你可以在Tampermonkey里打开看看, 应该一共是2901行代码

**Comment by CMHlover** [comment]
![image](https://user-images.githubusercontent.com/49261284/68000567-95828480-fc9b-11e9-9405-04bf14abc9c9.png)

**Comment by CMHlover** [comment]
好像才1000多行

**Comment by CMHlover** [comment]
怎么回事呀

**Comment by the1812** [comment]
那应该是装的时候没下载完, 你重新装一遍

**Comment by CMHlover** [comment]
好了好了非常感谢

**Comment by CMHlover** [comment]
麻烦你了
