### ISSUE TITLE
下載視頻的.ass部分內容沒有

### ISSUE THREAD

**Issue by w0853** [the1812/Bilibili-Evolved#223]
**关于哪一项功能**
下载视频

**问题描述**
https://www.bilibili.com/video/av70349488/?p=1
這個網站雖然我用"下载弹幕"這個功能得到的.xml是有我要的日文歌詞
但是用"下载视频"這功能我彈幕選ass得到出來的壓縮檔用記事本看.ass檔卻沒看到日文歌詞(連中文歌詞都沒有),那個是影片作者弄上去的,無法也變成ass檔嗎?

**脚本版本**
Bilibili Evolved (Preview Offline)472.87

**浏览器版本**
Chrome 78 

**错误信息**

**附加截图**

https://imgur.com/i4sYvC5

**Comment by the1812** [comment]
那个歌词属于字幕弹幕类型, ass转换器目前还不支持这种类型

**Comment by w0853** [comment]
謝謝

**Comment by w0853** [comment]
還是沒用喔

**Comment by the1812** [comment]
因为我目前没办法给ass弹幕做字幕弹幕支持, 所以close掉了...
要是将来支持了, 我会再通知你的

**Comment by w0853** [comment]
謝謝
