### ISSUE TITLE
安装好了，也能启用，但是侧边的按钮不显示

### ISSUE THREAD

**Issue by uyjhgkjbkhvyhjjyhvkjyhkjyhvhjv** [the1812/Bilibili-Evolved#2232]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**播放器版本**

**错误信息**

**附加截图**
![1736756142](https://user-images.githubusercontent.com/89767451/131295968-ea8c0e59-4932-4501-a33a-c5b19cdbc376.jpg)

**Comment by the1812** [comment]
油猴版本多少, 看图里好老的样子

**Comment by uyjhgkjbkhvyhjjyhvkjyhkjyhvhjv** [comment]
4.0的

Grant Howard ***@***.***>于2021年8月30日 周一14:51写道：

**Comment by the1812** [comment]
4.0 太老了

**Comment by uyjhgkjbkhvyhjjyhvkjyhkjyhvhjv** [comment]
哦，是这样啊。感谢感谢！！


Grant Howard ***@***.***>于2021年8月30日 周一15:09写道：
