### ISSUE TITLE
下载视频的路径是什么？

### ISSUE THREAD

**Issue by wanzuiqingfeng** [the1812/Bilibili-Evolved#224]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by the1812** [comment]
如果你说的是aria2 RPC里那个
> 默认路径: 设置一个默认路径, 脚本最后会把默认路径和路径拼在一起产生最终路径发送给aria2.
> 路径: 如果需要下载到默认路径里的子文件夹, 可以在这里设置.
