### ISSUE TITLE
扩展快捷键自定义：如z减速，x加速

### ISSUE THREAD

**Issue by painttist** [the1812/Bilibili-Evolved#2240]
**关于哪一项功能**
快捷键扩展

**问题描述**
我想用「z」来减速，「x」来加速，但是貌似现有版本做不到

**脚本版本**
正式版v1.12.16

我找遍了所有插件都找不到一款能让我做到 z 减速 x 加速的插件，求助！
如果能界面里轻松改最好，如果需要我下载然后加载设置文件也很可以了，只要能实现这个功能就好（或者说其实现有版本也能实现只是我不知道怎么设置？）

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/blob/master/src/video/keymap/key-bindings.md

**Comment by painttist** [comment]
感谢！完美解决了我的问题
