### ISSUE TITLE
快捷键失效

### ISSUE THREAD

**Issue by aa1149479355** [the1812/Bilibili-Evolved#2246]
**问题描述**
开启快捷键扩展后使用快捷键失效，B站自带快捷键可用

**脚本版本**
最新离线预览版

**浏览器版本**
Edge 92.0.902.84 

**错误信息**
没有报错

**Comment by Geeyun-JY3** [comment]
乏了，能不能先看置顶：#1992

**Comment by zhj9709** [comment]
![image](https://user-images.githubusercontent.com/13991774/133101335-e0c73683-c662-4c63-800b-a7138b7540f2.png)
![image](https://user-images.githubusercontent.com/13991774/133101474-1f5a375b-886c-49b0-b582-8bd090bb6117.png)
空格键都失效了

![image](https://user-images.githubusercontent.com/13991774/133101630-3f490d4e-02c1-40ff-bd2e-7596d96620b8.png)
这种正常

**Comment by Geeyun-JY3** [comment]
@zhj9709 这就是番剧区快捷键失效：#1992。试试预览版。
