### ISSUE TITLE
动态菜单-导出图片：链接拼接错误

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#2247]
**关于哪一项功能**
动态-导出图片

**问题描述**

在动态页面点击右侧三个点菜单，点击导出图片，转到的页面地址拼接错误

**脚本版本**

Preview v1.12.16
内容包: 6db732e

**浏览器版本**

Chrome 93

**播放器版本**

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/131834913-b9df072b-3831-45e7-ae97-6d3f3dc4242c.png)

![image](https://user-images.githubusercontent.com/11648014/131834866-f8b479ff-1fff-43f5-a81f-5b3ff2a56f6b.png)

**Comment by the1812** [comment]
这到底怎么回事... 链接生成得没错, 直接点击也是可以下载的, 但是 js 里 `a.click()` 就不对了. 在专栏里一样的 API 却可以正常导出.
![image](https://user-images.githubusercontent.com/26504152/132351935-80bcb616-22d1-4cc8-add1-3806db1ff133.png)

**Comment by CKylinMC** [comment]
> 这到底怎么回事... 链接生成得没错, 直接点击也是可以下载的, 但是 js 里 `a.click()` 就不对了. 在专栏里一样的 API 却可以正常导出.

我看到https后面没有冒号，被识别为相对路径了，会不会是什么东西把符号干掉了

**Comment by Aric-Sun** [comment]
我也有同样的问题。我还以为是我内存不够了导致插件没加载完全。

**Comment by CKylinMC** [comment]
@the1812 我发现一个问题，链接悬停的时候会被改掉
![image](https://user-images.githubusercontent.com/11648014/132675860-c9b1a5c9-be41-4775-a0da-51528944329c.png)

我实际加进去的是
```html
<a href="blob:https://t.bilibili.com/dea4581c-4987-41cc-b3ba-0c0b94d2ee82" download="thliveparty-567703524440613907.zip">test</a>"
```
这个地址是确实可用的。

然后过了一会，不知道是悬停还是过一段时间，就变成图片里那样，并且鼠标悬停最下角那个链接地址就是issue最早反馈的出错地址。

**Comment by the1812** [comment]
神奇, 难道 b 站改了 `<a>` 的原型, 注入了某种逻辑

**Comment by CKylinMC** [comment]
> 神奇, 难道 b 站改了 `<a>` 的原型, 注入了某种逻辑

```HTML
<a href="blob:https://t.bilibili.com/89475268-52d5-42a2-b273-45f8c1cfe7ba" download="test.zip">adasdasd</a>
```

b站自动替换了`https://t.bilibili.comhttps//t.bilibili.com/89475268-52d5-42a2-b273-45f8c1cfe7ba?spm_id_from=444.41.0.0`，修改发生在第一次右键打开时。
修改后链接末尾多了`?spm_id_from=444.41.0.0`，而之后前边链接修改回去不会触发自动替换。
随后我把后面的`?spm_id_from=444.41.0.0`删除，修改链接后打开再次触发替换。

结论：自动替换链接和末尾`?spm_id_from=444.41.0.0`可能有一定的关系，或许想个办法提前把这个加进去就不会被替换了。

**Comment by indefined** [comment]
这个东西是一个广告或者追踪脚本加上去的，反正正常人肯定不会喜欢这种东西，脚本内容很简单就是点击或者右键链接时读取文档头的一个spm_prefix meta的数值然后加到链接后面，可以直接拦截掉这个脚本，或者和楼上说的可以事先加上去就不会被更改，也可以删掉spm_prefix meta让脚本执行的时候直接出错，或者加个click和contextmenu事件然后stopPropagation()
![QQ截图20210912000941](https://user-images.githubusercontent.com/37869994/132954188-081c3d71-6490-40fb-8bd7-13f72e2de84d.jpg)

**Comment by CKylinMC** [comment]
> 这个东西是一个广告或者追踪脚本加上去的，反正正常人肯定不会喜欢这种东西，脚本内容很简单就是点击或者右键链接时读取文档头的一个spm_prefix meta的数值然后加到链接后面，可以直接拦截掉这个脚本，或者和楼上说的可以事先加上去就不会被更改，也可以删掉spm_prefix meta让脚本执行的时候直接出错，或者加个click和contextmenu事件然后stopPropagation()
> ![QQ截图20210912000941](https://user-images.githubusercontent.com/37869994/132954188-081c3d71-6490-40fb-8bd7-13f72e2de84d.jpg)
> 

应该是那个sentry，我记得这家就是做错误跟踪什么的。

**Comment by the1812** [comment]
有 AdBlock 之类的用户可以先屏蔽掉这个, 就正常了
```
https://s1.hdslb.com/bfs/seed/jinkela/short/auto-append-spmid.js
```

**Comment by Crystal-RainSlide** [comment]
https://github.com/the1812/Bilibili-Evolved/blob/668b54b9e1aec674eeef77530feac793b7d6fc25/src/client/compatibility.ts#L34

`window.__spm_prefix` 似乎变成了 `window.__MIRROR_CONFIG__.spmId`；

时过境迁，新版主页和现在的视频页中，已经没有单独的 `auto-append-spmid.js`，而是直接整合在 [`index.js`](https://s1.hdslb.com/bfs/static/shanks/laputa-home/assets/index-d8884365.js)（搜索 `spm_id_from=` 直达相关代码）甚至页面渲染代码里，删除 `spm_prefix` 应该已经没有作用。好在B站也限制了会添加追踪的链接元素，不至于使这个问题再现。（真再现了，其实也可以用 [`GM_download`](https://violentmonkey.github.io/api/gm/#gm_download) 来解决…）

保守角度，删东西一样可能导致错误，比如 AdGuard 的中文列表里有一条 `||bilibili.com$removeparam=source_id`，没有排除 API 域名，会导致 404 页面上请求的 `api.bilibili.com/x/activity_components/eva_operation/list` 无法返回漫画图片列表，导致出错。而且，因为B站代码写太烂，错误还是个无限循环调用。

如果没问题的话，可以考虑不再删除 `spm_prefix`，转而提供去除链接追踪功能。劫持 `document.body.addEventListener` 过滤掉带 `spm_id_from` 的函数应该就行了。也可以参考 [Ublock Origin](https://github.com/gorhill/uBlock/wiki/Resources-Library#addeventlistener-defuserjs-) 的实现，以及我刚写的规则：

```
bilibili.com##+js(aeld, click, spm_id_from, elements, body)
bilibili.com##+js(aeld, contextmenu, spm_id_from, elements, body)
```
