### ISSUE TITLE
UI问题>顶栏

### ISSUE THREAD

**Issue by Jumping5** [the1812/Bilibili-Evolved#225]
**关于哪一项功能**
定位：顶栏>动态>番剧>h1.title

**问题描述**
番剧标题显示不全（文字下方会被截断）
分析：h1.title高度不够，F12查看（100%缩放），把高度从20调整到22问题消失
不是100%复现，可能跟字体和浏览器字体大小或者系统缩放有关
建议：在不影响布局的前提加高h1.title的那个框（不知前端怎么称呼这个）

**脚本版本**
正式版1.9.12

**浏览器版本**
edge chromium 稳定版

**错误信息**

**附加截图**

**Comment by the1812** [comment]
这应该跟当前页面有关, 比如在`消息中心`页面里会被那里的样式设成`12px`高导致显示不全, 我倒是没给标题设固定的高度值.
预览离线版10天前有做过一些修复, 你可以试用一下
