### ISSUE TITLE
简化首页后的热门没有刷新按钮

### ISSUE THREAD

**Issue by Deltaanno** [the1812/Bilibili-Evolved#2256]
**关于哪一项功能**
就是样式里的简化首页，本来首页的热门右侧有个换一换按钮可以刷新热门，简化首页后热门不能刷新了

**问题描述**

**脚本版本**

Stable v1.12.16
内容包: a831806

**浏览器版本**

edge最新版

**播放器版本**

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
重复：#2168、#2178
