### ISSUE TITLE
弹幕点赞功能失效，没有在设置中找到有关弹幕点赞的开关

### ISSUE THREAD

**Issue by RxinnotRstar** [the1812/Bilibili-Evolved#2261]
根据我的观察，开启作者的插件之后会出现无法点赞弹幕的情况（即弹幕不悬停，不出现点赞按钮）。
我没有在设置里找到关于弹幕点赞的开关。

以下是我的部分设置的截图，可能对我们的交流有帮助：
![图片](https://user-images.githubusercontent.com/56676566/132297045-85e1fda9-f6c7-4883-90a2-0b0fcf2bce34.png)![图片](https://user-images.githubusercontent.com/56676566/132297075-e69ffce3-2cf1-4d2b-87cb-98436b1b952c.png)![图片](https://user-images.githubusercontent.com/56676566/132297144-2729b37f-76b5-40ea-90a8-fa55e85ade9a.png)![图片](https://user-images.githubusercontent.com/56676566/132297192-a838db7b-39c6-4d25-8e4c-25c0bf8d1d1f.png)

希望得到作者的答复，同时感谢作者为这个插件的付出！

**Comment by Geeyun-JY3** [comment]
希望先看看 README。这已经是一个被问了很多次的问题：https://github.com/the1812/Bilibili-Evolved#安装
> 做好觉悟, 脚本开启后不能使用弹幕点赞和举报
