### ISSUE TITLE
反馈：b 站首页更新后【样式】设置中的【简化首页】及【隐藏横幅】功能失效

### ISSUE THREAD

**Issue by shaigu31135** [the1812/Bilibili-Evolved#2271]
**关于哪一项功能**
【样式】设置中的【简化首页】及【隐藏横幅】功能

**问题描述**

2021年9月9日，更新脚本后，首页的样式设置失效。
重启浏览器及清除浏览器缓存均无法有效解决。

**脚本版本**

Stable v1.12.16   内容包: 1fbc9cb

**浏览器版本**

Mozilla Firefox (International Edition) Version 92.0 (x64)

**播放器版本**

Null

**错误信息**

[Vue warn]: Error in mounted hook (Promise/async): "TypeError: e is null"

found in

---> <Blackboards>
       <SimpleHome>
         <SimplifyHome>
           <Root> Bilibili Evolved.user.js:790:17
    warn moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:790
    logError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2049
    globalHandleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2044
    handleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2004
    invokeWithErrorHandling moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2021
TypeError: e is null
    r eval line 4 > eval line 13211 > eval:1
    mounted eval line 4 > eval line 13211 > eval:1
Bilibili Evolved.user.js:2053:15
    logError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2053
    globalHandleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2044
    handleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2004
    invokeWithErrorHandling moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2021
[Vue warn]: Error in created hook (Promise/async): "Error: unsafeWindow.__INITIAL_STATE__ not available"

found in

---> <TrendingVideos>
       <SimpleHome>
         <SimplifyHome>
           <Root> Bilibili Evolved.user.js:790:17
    warn moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:790
    logError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2049
    globalHandleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2044
    handleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2004
    invokeWithErrorHandling moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2021
Error: unsafeWindow.__INITIAL_STATE__ not available
    a eval line 4 > eval line 13211 > eval:1
Bilibili Evolved.user.js:2053:15
    logError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2053
    globalHandleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2044
    handleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2004
    invokeWithErrorHandling moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2021
[Vue warn]: Error in mounted hook (Promise/async): "TypeError: e is null"

found in

---> <Blackboards>
       <SimpleHome>
         <SimplifyHome>
           <Root> Bilibili Evolved.user.js:790:17
    warn moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:790
    logError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2049
    globalHandleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2044
    handleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2004
    invokeWithErrorHandling moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2021
TypeError: e is null
    r eval line 4 > eval line 13211 > eval:1
    mounted eval line 4 > eval line 13211 > eval:1
Bilibili Evolved.user.js:2053:15
    logError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2053
    globalHandleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2044
    handleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2004
    invokeWithErrorHandling moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2021
[Vue warn]: Error in created hook (Promise/async): "Error: unsafeWindow.__INITIAL_STATE__ not available"

found in

---> <TrendingVideos>
       <SimpleHome>
         <SimplifyHome>
           <Root> Bilibili Evolved.user.js:790:17
    warn moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:790
    logError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2049
    globalHandleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2044
    handleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2004
    invokeWithErrorHandling moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2021
Error: unsafeWindow.__INITIAL_STATE__ not available
    a eval line 4 > eval line 13211 > eval:1
Bilibili Evolved.user.js:2053:15
    logError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2053
    globalHandleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2044
    handleError moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2004
    invokeWithErrorHandling moz-extension://e5a6e05e-f427-48d6-a602-eb6d30294c0a/userscripts/Bilibili Evolved.user.js?id=29920630-18c7-4479-ac0e-f9505fbdf324:2021

**附加截图**
![1](https://user-images.githubusercontent.com/81251409/132894848-ce7f345c-f54d-4a71-8aad-0498151307d1.png)

**Comment by shaigu31135** [comment]
**附加截图**

![1](https://user-images.githubusercontent.com/81251409/132895013-6e7d80b0-4322-4c9a-bbfc-8df9383aa4d8.png)

**Comment by Timberglingg** [comment]
对，我也是一样的问题

**Comment by the1812** [comment]
是 b 站首页更新了, 脚本适配还在路上, 可以用预览版提前体验下

**Comment by yubanmeiqin9048** [comment]
同样的问题，更新后B站首页更丑了，我还是喜欢脚本改过之后的页面（不使用首页简化）
