### ISSUE TITLE
默认弹幕设置部分情境下失灵

### ISSUE THREAD

**Issue by MHzsz** [the1812/Bilibili-Evolved#228]
**关于哪一项功能**

默认弹幕设置

**问题描述**

默认设置是关闭弹幕，
任意点开某一个视频，弹幕是关闭的；
但是当在视频播放结束后的相关推荐中点击新视频，功能会失灵；
从侧边栏的相关推荐点击新视频，弹幕能够正常自动关闭

**脚本版本**

正式版 | 1.9.12
Preview | 1.9.15

**浏览器版本**

Chrome/78.0.3904.92
Vivaldi/2.9.1705.38

**错误信息**

**附加截图**
![批注 2019-11-09 174338](https://user-images.githubusercontent.com/39558996/68526780-5a76f580-031a-11ea-89a8-5498394fc0cb.jpg)
![批注 2019-11-09 174400](https://user-images.githubusercontent.com/39558996/68526781-5b0f8c00-031a-11ea-8e00-09d749e77a3b.jpg)
![批注 2019-11-09 174409](https://user-images.githubusercontent.com/39558996/68526782-5ba82280-031a-11ea-824d-67c523d6fb32.jpg)
![批注 2019-11-09 174415](https://user-images.githubusercontent.com/39558996/68526783-5c40b900-031a-11ea-96d9-9b9afb5518bd.jpg)
![批注 2019-11-09 174422](https://user-images.githubusercontent.com/39558996/68526784-5c40b900-031a-11ea-8722-f3bbf09e7535.jpg)

**Comment by the1812** [comment]
v1.9.16已修复.

**Comment by MHzsz** [comment]
感谢开发维护～
