### ISSUE TITLE
视频设置播放器模式为宽屏不能正常使用

### ISSUE THREAD

**Issue by lamcodes** [the1812/Bilibili-Evolved#2280]
**关于哪一项功能**
视频，播放器模式，开启宽屏

**问题描述**

视频，播放器模式，开启宽屏，点开任意视频不能生效

**脚本版本**

预览版1.12.18

**浏览器版本**

Microsoft Edge
版本 93.0.961.47 (官方内部版本) (64 位)

**播放器版本**

dashplayer

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
重复，参考：#2107、#2225
