### ISSUE TITLE
开启 [ 播放器置顶 ]，点击宽屏模式 视频播放器窗口无法对齐到页面

### ISSUE THREAD

**Issue by zyh-zyh-zyh** [the1812/Bilibili-Evolved#2283]
**关于哪一项功能：**
样式-播放器置顶

**问题描述：**
* 开启样式 - 播放器置顶 选项后，点击宽屏模式 视频播放器窗口无法对齐到页面（浏览器页面会向下滚动。）；
* 多P视频 自动跳转到下一P时，播放器会再次定位错位。

**脚本版本：**
`v1.12.16`

**浏览器版本：**
`Chrome 93.0.4577.82（正式版本） （64 位）`

**播放器版本：**
`更新历史 26703ce7b678`

**错误信息：**

**附加截图**
* 宽屏前：
![image](https://user-images.githubusercontent.com/89998150/133588130-1bec4299-1f18-434a-8f1e-774f63f097d1.png)

* 宽屏后：
![image](https://user-images.githubusercontent.com/89998150/133588256-af2fb169-d146-407a-98ae-08a80c06fb4b.png)

**Comment by the1812** [comment]
见 #483
