### ISSUE TITLE
批量下载失效

### ISSUE THREAD

**Issue by dingdong1874** [the1812/Bilibili-Evolved#2284]
在番剧详情页下（https://www.bilibili.com/bangumi/play/ss38950；https://www.bilibili.com/bangumi/play/ep417020）点击bilibili-evolved的附加功能，再点下载视频，再点批量导出，然后左下角就显示
“批量下载
获取番剧数据失败: 无法找到 Season ID”

版本：1.12.18
谷歌浏览器版本：70.0.3538.77 (正式版本)

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved#推荐配置
你这内核版本太旧了吧。

**Comment by the1812** [comment]
我试了下两种地址都可以啊, 应该是你浏览器太旧了
