### ISSUE TITLE
夜间模式：搜索结果中的UP主文字颜色错误

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#2288]
**关于哪一项功能**
夜间模式

**问题描述**

搜索一个可以直接提示UP主的搜索结果。
ep.  https://search.bilibili.com/all?keyword=%E8%90%A8%E9%A1%B6%E9%A1%B6

**脚本版本**

Preview v1.12.18
内容包: ddc6594

**浏览器版本**

Chrome 93

**播放器版本**

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/133797551-867670d4-2206-4059-93f3-02affcd45469.png)

**Comment by Geeyun-JY3** [comment]
补充：部分 UP 会有一个横幅（目前已知的是拿过百大的 UP，不知道还有没有其他种类的横幅）：
![image](https://user-images.githubusercontent.com/49396421/135119137-173da799-d4ea-4c1b-9484-e27c59bd3ab7.png)
![image](https://user-images.githubusercontent.com/49396421/135119391-736fe370-55c9-4544-83f6-93be93b5daec.png)

**Comment by Geeyun-JY3** [comment]
几个地方的主题色忘跟随了
![image](https://user-images.githubusercontent.com/49396421/141666342-1d100285-e25a-4ee5-b951-97384e0f4a66.png)
