### ISSUE TITLE
简化首页：动态和推荐末端阴影

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#2289]
**关于哪一项功能**
简化首页

**问题描述**

动态和推荐滚动到最右侧的时候阴影不会消失，总是遮挡半个最后卡片

**脚本版本**

Preview v1.12.18
内容包: ddc6594

**浏览器版本**

Chrome 93

**播放器版本**

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/133873476-03f5a5f3-7d5c-4d81-9253-0b4ec0246063.png)

**Comment by the1812** [comment]
奇怪, 按理来说阴影会跑到前面去才对
![image](https://user-images.githubusercontent.com/26504152/133913122-9243aeee-222f-4d17-8153-0d4909e33bc5.png)
