### ISSUE TITLE
展开选集列表

### ISSUE THREAD

**Issue by xiao-mantou** [the1812/Bilibili-Evolved#229]
**关于哪一项功能**

展开选集列表

**期望的效果**

自动展开视频选集列表
往常都是展开的,仔细看了一下貌似没有相关的功能.

**脚本版本**

预览离线版 481.93 ?

**Comment by the1812** [comment]
这个功能其实以前是在夜间模式里的, 因为以前Chrome渲染那里的滚动条有bug, 所以就展开防止滚动条出现. 前几天看了下已经没这bug了我就把这段从夜间模式里移除了.
我之后加到`展开选集标题`里如何?

**Comment by xiao-mantou** [comment]
麻烦您了,直接滚动还是挺方便地避免了鼠标悬停等待.
