### ISSUE TITLE
[REQ] 能否增加 上次看到 xx 【自动】“跳转播放” 的功能？

### ISSUE THREAD

**Issue by waldens** [the1812/Bilibili-Evolved#23]
**关于哪一项功能**

进页面后，适当时机「自动」跳转播放，不再需要像现在一样手动点

**期望的效果**

官方是：默认从头播放，要跳转播放，自己手动点一下
能否添加一个选项，允许用户：默认跳转播放，要从头播放，自己手动点一下？
谢谢

![](https://i.loli.net/2018/12/08/5c0acd2d2a1cc.png)

**Comment by the1812** [comment]
1.6.14版中已加入此功能, 欢迎试用及反馈

**Comment by waldens** [comment]
@the1812 感谢！刚刚测试了，效果很好！太感激了![](https://ooo.0o0.ooo/2017/04/16/58f32b4724eae.png)
