### ISSUE TITLE
自动宽屏出现问题

### ISSUE THREAD

**Issue by Kulahala** [the1812/Bilibili-Evolved#2302]
最近看视频，自动宽屏有时不触发，有时需要等几秒才有

**Comment by Geeyun-JY3** [comment]
请先善用搜索：#2107、#2225

**Comment by CKylinMC** [comment]
> 请先善用搜索：#2107、#2225

这样的经典老问题要不然整理一个Q&A页面算了...很多人搜也不知道搜什么关键字...

**Comment by Geeyun-JY3** [comment]
> > 请先善用搜索：#2107、#2225
> 
> 这样的经典老问题要不然整理一个Q&A页面算了...很多人搜也不知道搜什么关键字...

FAQ 还是有的，在讨论区：#1301
