### ISSUE TITLE
默认播放器模式 带来的宽屏问题

### ISSUE THREAD

**Issue by FoundTheWOUT** [the1812/Bilibili-Evolved#2304]
**关于哪一项功能**
开启`默认播放器模式`后的开启宽屏(无论是手动还是自动), 在页面向下滚动时布局出错, 表现为视频盒子回折成未宽屏状态.
在我手动关掉`默认播放器模式`后, 一切正常.
这是在番剧页面发现的, 其它页面没见有.

**脚本版本**
v2, 组件最新

**播放器版本**
3.1.1

https://user-images.githubusercontent.com/47922588/134312659-191d0861-3cd5-4739-9ec4-becdcee9cb31.mov

**Comment by wulifuji** [comment]
同出现
