### ISSUE TITLE
从前天开始 每点一个视频左下角就跳 错误 ：加载组件 下载视频 失败

### ISSUE THREAD

**Issue by AkiyamaMint** [the1812/Bilibili-Evolved#231]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
请附上脚本版本,目前正式版最新版为1.9.16,如果已经是最新版,请附上控制台报错信息截图

**Comment by Jumping5** [comment]
更新一下脚本就好了……
