### ISSUE TITLE
使用会出现异响

### ISSUE THREAD

**Issue by Sakuma-Rei** [the1812/Bilibili-Evolved#2310]
**关于哪一项功能**

**问题描述**

就是看啥都会发出异响或者静音（异响次数多） 主板喇叭已更换 还是不行 经排查怀疑脚本问题 静音异响无 音量大异响大

**脚本版本**
 v1.12.16

**浏览器版本**
firefox 92.0

**播放器版本**

2.67.1
**错误信息**

**附加截图*

https://user-images.githubusercontent.com/55101422/134609773-cea6cba0-b6fe-446b-9077-4bdb808ed91d.mp4

*

**Comment by the1812** [comment]
播放器设置里关掉 HEVC
