### ISSUE TITLE
希望能隱藏主站首頁左下角的電視

### ISSUE THREAD

**Issue by ZOMBIE39** [the1812/Bilibili-Evolved#232]
![1](https://user-images.githubusercontent.com/37724369/68650935-7de3af80-0569-11ea-97cd-225cfec6e203.png)
批站總是能想盡辦法來折磨強迫症呀 。。。。。 雖然有簡化首頁了 不過畢竟貳刺螈嘛 還是要看番的 番劇表沒了不太方便我這種老年人

**Comment by the1812** [comment]
这个会直接按照广告处理的 (简化首页的番剧部分还没做
