### ISSUE TITLE
网页默认大小下视频进度条部分错位

### ISSUE THREAD

**Issue by pikaqian** [the1812/Bilibili-Evolved#2321]
**关于哪一项功能**
进度条样式及显示

**问题描述**

在浏览器默认的大小（100%）下带有“字幕”选项的视频下进度条发生错位，导致“全屏”按钮只有不到一半在视频界面内，“网页全屏”中按钮有些拥挤（不知道算不算，以前没有出现过）
（截图在最后
**脚本版本**

Stable v1.12.16

**浏览器版本**

Microsoft edge 94.0.992.31

**播放器版本**

2.67.1-c7f9b615

**错误信息**

![image](https://user-images.githubusercontent.com/42432134/134770400-ff5782be-02ab-4d01-9014-46bdb39deb98.png)

**附加截图**
<img width="960" alt="无标题" src="https://user-images.githubusercontent.com/42432134/134770129-973c64e7-3e25-4045-97eb-6e461816e3cb.png">
<img width="958" alt="2无标题" src="https://user-images.githubusercontent.com/42432134/134770147-ed097372-88b1-4696-b7c7-f97134834b5c.png">

**Comment by the1812** [comment]
你屏幕太窄了, 加上截图和逐帧的按钮就放不下了, 这几个功能关掉就行了

**Comment by pikaqian** [comment]
> 你屏幕太窄了, 加上截图和逐帧的按钮就放不下了, 这几个功能关掉就行了

哦哦这样啊[捂脸]
主要之前没出现过，所以以为是刚有的问题[捂脸]
谢谢！
