### ISSUE TITLE
会不定时卡死

### ISSUE THREAD

**Issue by 694185819** [the1812/Bilibili-Evolved#2328]
这个插件会导致直播间加载时间过长、其他哔哩哔哩页面不定时卡死，怎么设置才解决？或者是已知状态，但无法解决？

**Comment by CKylinMC** [comment]
有没有可能是插件或者脚本冲突什么的？或者浏览器不支持？

请不要删除issue的默认模板，好好填写有利于定位问题。

**Comment by RingingVolcano** [comment]
卡死是因为虚拟内存占满了吧
Chrome挺吃虚拟内存的
