### ISSUE TITLE
aria2 prc 无法连接到rpc主机 已经配置端口,其它脚本比如百度云调动rpc可以正常下载,但是这个就是不行

### ISSUE THREAD

**Issue by Lactococcuslactis** [the1812/Bilibili-Evolved#2330]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**播放器版本**

**错误信息**

**附加截图**

**Comment by xxldm** [comment]
是不是“主机”一栏没加 https://
我上次研究了半天，发现如果aria2那边代理成https了，这边需要自己添加https://
