### ISSUE TITLE
加入自动适应浏览器尺寸

### ISSUE THREAD

**Issue by sensty** [the1812/Bilibili-Evolved#234]
**希望能够让B站界面能够自动适应屏幕尺寸**
![image](https://user-images.githubusercontent.com/24983339/68833811-5b7b9e80-06ef-11ea-86f7-5fada8596c19.png)

**期望的效果**
B站的网页版显得很乱，在精简模式下看着很舒服，如果能和手机页面差不多就非常完美了。

**Comment by the1812** [comment]
顶多是我做的一些界面能适应, 比如首页, 其他地方基本不大可能

**Comment by 285914450** [comment]
界面适应就够了，B站的其他地方还是可以的。
另外，能不能再打开触控支持的情况下播放时提供锁定按钮啊？
