### ISSUE TITLE
新风纪委投票页面播放器报错

### ISSUE THREAD

**Issue by HCLonely** [the1812/Bilibili-Evolved#2340]
**关于哪一项功能**
新版风纪委员会

**问题描述**

新版风纪委员会投票页面的视频播放器报错。

**脚本版本**

Preview 1.12.19

**浏览器版本**

Microsoft Edge 94.0.992.31

**播放器版本**

2.68.3-ddf3ba5f

**错误信息**

```
utils.playerReady 失败
Error: utils.playerReady 失败
    at eval (eval at applyComponent (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=fde63207-a866-473e-91bf-d828ca124ed8), 
:1:230)
```

**附加截图**
![image](https://user-images.githubusercontent.com/26346802/135219519-3112a514-d229-4020-b4ea-6f0f3de4e0f3.png)

**Comment by xiaoyuban1213** [comment]
我和你报错不一样我是
utils.playerReady 失败
d/<@eval line 4 > eval line 13211 > eval:1:230
![图片](https://user-images.githubusercontent.com/81410052/135693215-6573e554-6c5f-49ab-b26f-bc1039fc8ea8.png)

**Comment by the1812** [comment]
可以抓一下这个内嵌播放器的网址, 我排除一下

**Comment by HCLonely** [comment]
> 可以抓一下这个内嵌播放器的网址, 我排除一下

https://www.bilibili.com/blackboard/newplayer.html?crossDomain=1&lightWeight=true&fjw=true&cid=403128572&aid=377796863&t=64
