### ISSUE TITLE
无法获取勋章列表

### ISSUE THREAD

**Issue by xzk-kokodayo** [the1812/Bilibili-Evolved#2341]
**关于哪一项功能**
自动选择当前直播间勋章

**问题描述**
打开“自动选择当前直播间勋章”功能，打开一个直播间。

**脚本版本**
正式版1.12.19

**浏览器版本**
Microsoft Edge
版本 94.0.992.31 (官方内部版本) (64 位)

**错误信息**
无法获取勋章列表. 错误码:520002 pageSize最多10个

**附加截图**
![屏幕截图 2021-09-29 204358](https://user-images.githubusercontent.com/69005158/135270759-e1072d4e-63f3-4bed-86a4-a69d1b8c1ae8.png)

**Comment by yokinanya** [comment]
我也一样，目前确定不是个例，应该是b站改东西了

**Comment by the1812** [comment]
以前是 256 个的, 怎么给改成 10 了, 这下得发好几个请求才能获取完勋章了

**Comment by rezer-o** [comment]
我也是

**Comment by xxldm** [comment]
> 以前是 256 个的, 怎么给改成 10 了, 这下得发好几个请求才能获取完勋章了

勋章上线有1000个，最多的时候要发100个请求。。。。。
页面：https://live.bilibili.com/p/html/live-fansmedal-wall/#/view-medal
接口：https://api.live.bilibili.com/xlive/web-ucenter/user/MedalWall?target_id={uid}
这个页面可以查看自己的勋章，相关接口目前没有限制单次数量，不知道能不能作为替代品

**Comment by the1812** [comment]
> medal 接口：[https://api.live.bilibili.com/xlive/web-ucenter/user/MedalWall?target_id={uid}](https://api.live.bilibili.com/xlive/web-ucenter/user/MedalWall?target_id=%7Buid%7D)

看了下, 这个好像不能获取到勋章是否点亮

**Comment by xxldm** [comment]
> > medal 接口：[https://api.live.bilibili.com/xlive/web-ucenter/user/MedalWall?target_id={uid}](https://api.live.bilibili.com/xlive/web-ucenter/user/MedalWall?target_id=%7Buid%7D)
> 
> 看了下, 这个好像不能获取到勋章是否点亮

啊这，雀食
那这一个呢，刚从安卓上扒拉下来的，还可以高亮{target_id}的牌子，不知道内容全不全
https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/panel?page=1&page_size=50&target_id={uid}

**Comment by CierraAlter** [comment]
我这边也不能用了，所以有解决办法吗，隔壁有个插件改了一个代码貌似能用了

**Comment by E1SA-ux** [comment]
我也是，无法获取勋章列表就无法自动打卡了

**Comment by zjqwtm543** [comment]
获取到的信息或许可以存在某个位置，不用反复申请更新或者给个按钮手动更新？

**Comment by dubaiii** [comment]
咋解决捏 我也有这个问题

**Comment by high0** [comment]
加一，相同问题

**Comment by xzk-kokodayo** [comment]
我也不太懂，但是我知道如果有勋章的话，进入直播间是显示“粉丝团”，没有勋章但是关注了是显示“+粉丝团”，没有关注是“+关注”

**Comment by 20051125** [comment]
加一，我也一样

**Comment by ruimin276** [comment]
> > > medal 接口：[https://api.live.bilibili.com/xlive/web-ucenter/user/MedalWall?target_id={uid}](https://api.live.bilibili.com/xlive/web-ucenter/user/MedalWall?target_id=%7Buid%7D)
> > 
> > 
> > 看了下, 这个好像不能获取到勋章是否点亮
> 
> 啊这，雀食 那这一个呢，刚从安卓上扒拉下来的，还可以高亮{target_id}的牌子，不知道内容全不全 [https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/panel?page=1&page_size=50&target_id={uid}](https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/panel?page=1&page_size=50&target_id=%7Buid%7D)

这个好像可以用，找了几个上百粉丝牌的人看了一下，应该是全的

**Comment by E1SA-ux** [comment]
> > > > medal 接口：[https://api.live.bilibili.com/xlive/web-ucenter/user/MedalWall?target_id={uid}](https://api.live.bilibili.com/xlive/web-ucenter/user/MedalWall?target_id=%7Buid%7D)
> > > 
> > > 
> > > 看了下, 这个好像不能获取到勋章是否点亮
> > 
> > 
> > 啊这，雀食 那这一个呢，刚从安卓上扒拉下来的，还可以高亮{target_id}的牌子，不知道内容全不全 [https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/panel?page=1&page_size=50&target_id={uid}](https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/panel?page=1&page_size=50&target_id=%7Buid%7D)
> 
> 这个好像可以用，找了几个上百粉丝牌的人看了一下，应该是全的

这个要怎么用？？？

**Comment by Janet-Baker** [comment]
应该是把这里换一下吧？

https://github.com/the1812/Bilibili-Evolved/blob/aa1243945d23539e3c8d0be19c37cf47b7315d1c/src/live/medal-helper/medal-helper.ts#L33

改成`pageSize=10`

或者换API再改一堆东西[例子](https://github.com/indefined/UserScripts/commit/3587478b1d80260b22d918c5b3b051d24e98e9dc)

当然也许[用客户端的API](https://github.com/the1812/Bilibili-Evolved/issues/2341#issuecomment-930770119)也不错？

**Comment by sino1641** [comment]
@the1812 更新 85442453f30f75ce622081ca3fb4fea4383cf4aa 后的` v1.12.19`之后还是会提示这个错误

**Comment by DynamIKK** [comment]
俺也一样，Stable v1.12.19版本

**Comment by nita0318** [comment]
有同样的错误
无法获取勋章列表. 错误码:520002 pageSize最多10个
Preview v1.12.19 内容包: 1ccca4f

**Comment by high0** [comment]
b站这是逼着所有人用手机端

**Comment by GalaxySnail** [comment]
我觉得我有必要善意地提醒一下各位，GitHub issue不是论坛或者贴吧，它是“问题追踪器（bug tracker）”，也就是汇报bug、研究bug成因、讨论如何修复的地方。对于一个bug，如果已经确定了复现它的方式，那么就不必重复地说“我按与XXX一样的方式复现了bug”。
与此同时还有一个问题是，这种问题追踪器与[邮件列表](https://www.zhihu.com/question/23757640)类似，订阅某个issue的用户会在每次这个issue有新的动态时收到一封新的提醒邮件。也就是说，在issue中的一个不能提供新的信息的评论，相当于给所有订阅这个issue的用户发了一封垃圾邮件（spam）。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
不知者无罪，希望各位今后多加注意。
