### ISSUE TITLE
无法获取勋章列表. 错误码:520002 pageSize最多10个

### ISSUE THREAD

**Issue by SunnyEU** [the1812/Bilibili-Evolved#2345]
**关于哪一项功能**

自动换牌子功能
**问题描述**

进入直播间提示无法获取勋章列表. 错误码:520002 pageSize最多10个
**脚本版本**

Bilibili Evolved (Offline)1169.28

**浏览器版本**
 chrome 94.0.4606.61

**播放器版本**

Bilibili HTML5 Live Player 3.5.4

**错误信息**

错误码:520002

**附加截图**

**Comment by Geeyun-JY3** [comment]
重复：#2341
