### ISSUE TITLE
那个快捷键快进85秒提个建议可以改成10秒或者自定义

### ISSUE THREAD

**Issue by uAnden** [the1812/Bilibili-Evolved#2346]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**播放器版本**

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
重复：#1411、#1615、#1629

是可以自定义的，v1 选项是隐藏的：https://github.com/the1812/Bilibili-Evolved/issues/534#issuecomment-757089739

v2 已经做出了 GUI，安装 `快捷键扩展` 就能看见。

而且你这个不应该开 issue，应该去 discussion
