### ISSUE TITLE
新版Safari中加载和Chrome中行为不一致

### ISSUE THREAD

**Issue by 8790** [the1812/Bilibili-Evolved#2347]
**关于哪一项功能**
简化首页，暗黑模式等

**问题描述**

开启简化首页 - 清爽模式 或者开启暗黑模式，在Safari中加载页面的时候，会先显示原网页才进入功能，而在Chrome中会直接开启功能。
在使用暗黑模式的时候，会瞬间出现日间模式，再切换为暗黑模式，这样的话在晚上就会非常瞎眼。在此反馈，希望能够查看原因。

**脚本版本**

Stable v1.12.19

**浏览器版本**

Safari 15.0

**Comment by the1812** [comment]
这个只是浏览器的限制, 脚本优先级不高, 不像扩展那样能第一时间运行
我这边低配置电脑上用 Chrome 也是和你在 Safari 遇到的现象一样的
