### ISSUE TITLE
[v2] Safari 无法加载

### ISSUE THREAD

**Issue by FoundTheWOUT** [the1812/Bilibili-Evolved#2349]
Safari 14 无法加载V2( Firefox 可正常加载 ), 原因未找到.
debugger了一下, 发现在脚步加载到这行时, 神奇的停止向前了(直接退出执行). 很迷.
https://github.com/the1812/Bilibili-Evolved/blob/e11540897acb20233e3febb6b3a333b1b7548b0a/src/client/init.ts#L31

我觉得不用急着解决吧. 先放个 issue 在这里.

Tampermonkey版本: 4.13.6140
Safari版本: 14.1

**Comment by the1812** [comment]
这个可能也得麻烦你来调试了, 我这边 App Store 抽风了登录不了账号...

**Comment by FoundTheWOUT** [comment]
我有空就去看看吧，最近比较少开苹果的系统

**Comment by FoundTheWOUT** [comment]
## 🚧 WIP 🚧
### 21.11.27
调试了一段时间, 初步发现是 `core-api` 中以下四个模块导致脚本加载失败. 分别是 `feedsApis`, `VideoCard`, `notify`, `watchlater`(四个模块任何一个都会导致脚本加载失败). 在注释掉此四个模块后, 插件能够正常加载出面板, 不过也就只是能加载出面板仅此而已.
尚未知道该四个模块为何会导致脚本失败.
> 相关引用 #2362
