### ISSUE TITLE
希望补全B站UI的日文翻译文本

### ISSUE THREAD

**Issue by Lets-Halloween** [the1812/Bilibili-Evolved#235]
您好，我是某字幕组的翻译man。近期有一些我认识的日本用户在尝试使用您的Bilibili-Evolve，由于现在的B站UI日文翻译文本有部分缺失，而日文和中文都会使用汉字，两者混用的情况下容易造成理解障碍，因此希望能补全日文翻译文本。

如果可以的话，希望可以从直播相关功能的UI开始进行补全。这部分是他们比较常用的功能。
除此以外，不知道注册用户转正的题库是否也可以进行翻译。

如果您不嫌弃的话，我可以做文本的翻译，只是因为还有工作要做，效率可能不会很高。

**脚本版本**
1.9.16

**Comment by Coulomb-G** [comment]
我的锅,近期因学业摸鱼太久了,能否提供一下相关页面地址,当然你也可以提供相关文本的翻译,我这边也会优先对这些页面进行翻译

**Comment by Lets-Halloween** [comment]
嗯……主要我也不清楚哪些是能提取出来的文本，哪些是提取不出来的，而且很杂。

那就先从随便哪一个直播的直播间开始吧
https://live.bilibili.com/650?visit_id=au0xciuc0y80
https://live.bilibili.com/21449083

![image](https://user-images.githubusercontent.com/55982108/68838682-13ae4480-06fa-11ea-9420-b8a5a6d8bb44.png)
![image](https://user-images.githubusercontent.com/55982108/68838801-4b1cf100-06fa-11ea-8aef-71d11bf60766.png)
![image](https://user-images.githubusercontent.com/55982108/68838819-5708b300-06fa-11ea-9939-7df415c58dbc.png)
![image](https://user-images.githubusercontent.com/55982108/68838839-60921b00-06fa-11ea-941c-bd6bd388c27e.png)
![image](https://user-images.githubusercontent.com/55982108/68839485-c0d58c80-06fb-11ea-846b-409e9fa2608b.png)
（比如这边的功能性按钮以及说明）

![image](https://user-images.githubusercontent.com/55982108/68838904-891a1500-06fa-11ea-91a4-031ca1fd72a4.png)
![image](https://user-images.githubusercontent.com/55982108/68838948-9e8f3f00-06fa-11ea-921a-0a5134a9ec83.png)
（还有这边虽然只截了两个，但弹幕框上面的按钮说明几乎都没有翻译）

除此以外还有翻译错误的地方，或是有其他更好、更常用的对应翻译文本的情况，比如
![image](https://user-images.githubusercontent.com/55982108/68839149-0cd40180-06fb-11ea-974c-c6b11059542f.png)
（消音→ミュート）

![image](https://user-images.githubusercontent.com/55982108/68839268-51f83380-06fb-11ea-94ed-a9af53402460.png)
（金ヒマワリの種→ひまわりの金の種）

除此以外还有很多……
我没有网页翻译或类似的工作经历，我也不知道怎么样更有效率地把这些传达给你，或是更有效率地帮助你进行对应的工作。如果有我帮得上忙的地方请告诉我具体该怎么做，谢谢。

**Comment by Coulomb-G** [comment]
关于静音的翻译,并不是错翻,消音和ミュート都是同一个意思,油管上也是ミュート(消音),这边翻译会优先采用文本较短或和原文本字数相近的翻译,不然很多地方容易产生错乱,至于金瓜子的翻译之后会进行修正

**Comment by Lets-Halloween** [comment]
原来如此，也要考虑文本长度啊，了解了
另外请问其他有问题的部分也需要我逐一反馈吗，还是说你们会自己进行校对

**Comment by Lets-Halloween** [comment]
（没有催工的意思，只是单纯问一下）

**Comment by Coulomb-G** [comment]
反馈当然是欢迎的,我这边日常使用也会将日语界面和其他海外视频站进行对比,关于翻译文本长度的问题,你可以直接在Devtools中的Elements找到相应的文本元素进行文本替换预览(当然这种修改一刷新就会消失,不会产生任何影响),快捷键:CTRL+shift+C,不习惯的话直接右键-检查(N)

**Comment by Lets-Halloween** [comment]
好的，请问反馈的方式还是把截图贴在这里进行说明吗，还有其他更有效率的方法吗

**Comment by Coulomb-G** [comment]
反馈脚本bug的话,可以在GitHub这边提Issues,翻译相关的话可以加群讨论:963709592

**Comment by Lets-Halloween** [comment]
搜了一下并没有看到群
如果加群是邀请制的话，我的qq是407710085
