### ISSUE TITLE
无法使用原生的长按方向键倍速播放功能

### ISSUE THREAD

**Issue by 11111111111ge1** [the1812/Bilibili-Evolved#2352]
**关于哪一项功能**

![image](https://user-images.githubusercontent.com/39661677/135567313-0369c6dd-0e03-41b3-b3d9-7029b0bf8097.png)
b站官方说明中, 长按方向键可倍速播放, 未开启插件时能正常使用, 但开了插件却不行
**问题描述**

![image](https://user-images.githubusercontent.com/39661677/135567483-357c4057-5419-4da7-88f1-6ae2c7a51816.png)
![image](https://user-images.githubusercontent.com/39661677/135567517-bb3e0dd4-1f49-4da9-bd29-66ec879760c1.png)
这是我关于视频模块的设置, 所有视频都有这个问题

**脚本版本**

1.12.19

**浏览器版本**

edge 93

**播放器版本**

V2.68.4
**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
有的人想关掉，有的人想用……：#2138

关掉 `快捷键扩展` 能暂时解决这个问题：https://github.com/the1812/Bilibili-Evolved/issues/2138#issuecomment-899258534
