### ISSUE TITLE
预约弹窗未清除

### ISSUE THREAD

**Issue by Mirionr** [the1812/Bilibili-Evolved#2361]
**关于哪一项功能**

**问题描述**

见图。预约弹窗未清除

**脚本版本**

preview 1.12.19

**浏览器版本**

最新chrome

**播放器版本**

2.68.4

**错误信息**

**附加截图**
![Uploading 1.JPG…]()

**Comment by Geeyun-JY3** [comment]
你图好像没传上来……

**Comment by Mirionr** [comment]
> 你图好像没传上来……

图片现在已经清除了，因为是临时的（（
就是视频中会出现一个预约xx的弹窗。算了，我close吧
