### ISSUE TITLE
批量下载重复下载同一文件

### ISSUE THREAD

**Issue by YazawaOj** [the1812/Bilibili-Evolved#237]
关于使用Aria2批量下载番剧的功能，最近遇到了批量下载结果下载文件全是同一文件的bug

**问题描述**
以 关于我转生变成史莱姆这档事 和 我们无法一起学习 为例，批量下载下来的文件都是相同大小，通过导出txt查看脚本内容，发现txt文件中仅仅修改了文件名，没有修改源。txt内容可见附件。
[史莱姆.txt](https://github.com/the1812/Bilibili-Evolved/files/3851289/default.txt)
[我们无法一起学习：第1话.txt](https://github.com/the1812/Bilibili-Evolved/files/3851297/1.txt)

**脚本版本**

1.9.16

**浏览器版本**

 78.0.3904.97

**错误信息**

**附加截图**

**Comment by the1812** [comment]
之前手误了, 1.9.17已经修复
