### ISSUE TITLE
隐藏顶部横幅后首页显示异常

### ISSUE THREAD

**Issue by Alexius66** [the1812/Bilibili-Evolved#2373]
**关于哪一项功能**
隐藏顶部横幅

**问题描述**

1080P 125DPI屏幕下，主页使用隐藏顶部横幅后出现不正常上移

**脚本版本**

Preview v1.12.19

**浏览器版本**

Microsoft Edge 版本 94.0.992.38

**播放器版本**

与播放器无关

**错误信息**

未发现错误报告

**附加截图**
![image](https://user-images.githubusercontent.com/73510996/136326992-c93b3f74-b5fc-4efe-b9f0-08bded1b7e71.png)
![image](https://user-images.githubusercontent.com/73510996/136327026-5bced8bf-eb11-4e5d-a36a-22f0a77b105e.png)
![image](https://user-images.githubusercontent.com/73510996/136327475-c009860f-c678-4877-bea6-36c5b36bbf1a.png)
![image](https://user-images.githubusercontent.com/73510996/136327511-447d73b7-e441-4864-9a29-f7e378ce5a7d.png)

**Comment by shanyan-wcx** [comment]
似乎还没有修复

**Comment by Alexius66** [comment]
> 我用最新正式版，显示异常，用了测试版分区之类的直接没了

可能是我用自定义首页，所以没问题🤯
