### ISSUE TITLE
1.12.19版本，全局固定顶栏失效.

### ISSUE THREAD

**Issue by yun-wulian** [the1812/Bilibili-Evolved#2386]
**关于哪一项功能**
顶栏全局固定

**问题描述**

b站主页面

**脚本版本**

1.12.19

**浏览器版本**

chrome 94

**播放器版本**

无关

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/92302733/136768661-8d47c5a9-ea27-4f07-b661-6b5f34da1281.png)

**Comment by Geeyun-JY3** [comment]
现在还能复现吗？

**Comment by yun-wulian** [comment]
现在已经好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月13日(星期六) 下午4:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 1.12.19版本，全局固定顶栏失效. (#2386)





 
现在还能复现吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Geeyun-JY3** [comment]
那可以 close 掉了

**Comment by yun-wulian** [comment]
现在有个问题：播放器默认模式无效；
我开的是宽屏，但是进去还是默认的小屏模式




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月13日(星期六) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 1.12.19版本，全局固定顶栏失效. (#2386)





 
那可以 close 掉了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Geeyun-JY3** [comment]
另外的问题另外开 issue。

而且已经有非常多类似反馈：#2351、#2399、#2408、#2424

**Comment by Geeyun-JY3** [comment]
@the1812 这个 issue 能关掉了。
