### ISSUE TITLE
快速收起评论区设置会导致无法回复普通视频评论

### ISSUE THREAD

**Issue by HaoTian22** [the1812/Bilibili-Evolved#239]
**关于哪一项功能**

快速收起评论区

**问题描述**

开启快速收起评论区的设置后，点击普通视频的评论回复按钮无反应（除了评论中的评论回复可以）

**脚本版本**

1.9.16

**浏览器版本**

Microsoft Edge 80.0.328.4

**错误信息**

无错误信息

**附加截图**
![image](https://user-images.githubusercontent.com/48882584/68991404-7c7ff300-0899-11ea-9d2b-453c59e5f81a.png)

**Comment by the1812** [comment]
请问还有使用其他插件吗? 以及开发者工具(`Ctrl+Shift+I`)里也没报错?

<img height="400" src="https://user-images.githubusercontent.com/26504152/68991730-c7e7d080-089c-11ea-9665-99a19557de0d.png">

**Comment by HaoTian22** [comment]
![image](https://user-images.githubusercontent.com/48882584/68991790-768c1100-089d-11ea-9499-22b3f5d8cf2c.png)
就这样了（其他有关B站的扩展都关了，几个视频播放相关的扩展应该不影响吧）

**Comment by HaoTian22** [comment]
但是貌似有几率，有时会，有时不会（不知道是不是我说的这个设置，但是我觉得肯定跟这个插件有关系）

**Comment by the1812** [comment]
其他视频插件也关掉试试, 包括反广告插件

**Comment by HaoTian22** [comment]
都关了，还发现个现象：评论在网页加载时会闪出来两次，第一次可以正常使用，但是大约1秒后会再刷新一次，就不行了

**Comment by HaoTian22** [comment]
[2019-11-16 18-48-40.zip](https://github.com/the1812/Bilibili-Evolved/files/3854091/2019-11-16.18-48-40.zip)
参考视频0:45处（视频为原版视频，未经过任何编辑）

**Comment by the1812** [comment]
我还是试不出来.. 不过应该跟快速收起评论区没啥关系, 那个功能只要网址不是`https://t.bilibili.com/`就直接退出了.
能否分享一下你对脚本的设置? 我改成跟你一样的设置再去试试

**Comment by HaoTian22** [comment]
是这个吗？
[设置.txt](https://github.com/the1812/Bilibili-Evolved/files/3854115/default.txt)

**Comment by the1812** [comment]
是, 不过我还是遇不上回复失效...

**Comment by HaoTian22** [comment]
可能是因为我网络环境以及电脑卡顿导致B站评论的异步加载与脚本相冲突？(我4G笔记本)

**Comment by the1812** [comment]
说不定是b站评论区本身的问题, 我想了想跟评论区有关的就两个功能, 一个`简化评论区`只是个皮肤, 另一个`快速收起评论区`只在动态页里运行. 应该没有什么东西会去改动这个回复按钮的

**Comment by HaoTian22** [comment]
然而我关了脚本试了十几次都正常，开脚本5次就有3-4次都有问题

**Comment by the1812** [comment]
关了脚本 加载变快了 就不触发了?

**Comment by HaoTian22** [comment]
有没有动作是要刷新网页或者刷新缓存的？我看是闪的那次刷新导致的，正常的都不会闪两次加载

**Comment by the1812** [comment]
没有什么功能会突然刷新网页, 倒是顶栏会写入cookies记录动态的时间, 这算不算写入缓存?

**Comment by HaoTian22** [comment]
要不每天用teamviewer或者QQ什么的远程调试下？
3128463615

**Comment by the1812** [comment]
行吧 我明天加你QQ
