### ISSUE TITLE
希望能够添加视频的CC字幕下载功能

### ISSUE THREAD

**Issue by Mrodot** [the1812/Bilibili-Evolved#240]
**关于哪一项功能**

视频下载模块

**期望的效果**
希望能够添加视频的CC字幕下载功能。

**脚本版本**

Bilibili Evolved (Preview Offline)
484.22

**Comment by the1812** [comment]
需要原格式(JSON)还是转换一下变成ASS?

**Comment by xiaole3349** [comment]
> 需要原格式(JSON)还是转换一下变成ASS?

其实str就可以了，不需要转码成ass

**Comment by the1812** [comment]
那直接点`下载字幕`就行了, 按shift才会转ass
