### ISSUE TITLE
外置稍后再看 / 快速收藏 功能失效

### ISSUE THREAD

**Issue by rain-0** [the1812/Bilibili-Evolved#2406]
**关于哪一项功能**
外置稍后再看

**问题描述**
在所有视频播放页启用稍后再看后没有出现按钮

**脚本版本**
1.12.19
**浏览器版本**
Microsoft Edge 版本 94.0.992.50

**错误信息**

**附加截图**
![捕获](https://user-images.githubusercontent.com/47851758/138026103-62a25962-75ae-4816-8953-90904b2d4c81.PNG)

![捕获2](https://user-images.githubusercontent.com/47851758/138026081-ec614c9d-2ddb-4788-838a-491cdc576f66.PNG)

**Comment by johnsteveabc** [comment]
我怀疑B站视频页的源码改了，导致功能不兼容
