### ISSUE TITLE
动态首页动态更新横幅不应跟随主题色

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#2411]
### 关于哪一项功能

夜间模式

### 问题描述

目前该横幅跟随了主题色，应该保持原样为黄色。（这是真 bug）

### 脚本版本

正式版 v1.12.19 内容包: 1904cf7

### 浏览器版本

百分浏览器 4.3.9.248（正式版本） （64 位） (Chromium 86.0.4240.198)

### 播放器版本

不需要

### 是否开启 HEVC

- [ ] 是的

### 错误信息

```shell
无
```

### 附加截图

![正在加载中](https://user-images.githubusercontent.com/49396421/138217607-e13928de-ee4c-4022-aeba-0beef78a5a29.jpg)
![有新动态，点击查看](https://user-images.githubusercontent.com/49396421/138217611-9896810b-6b87-4e77-921b-e85e832f9d25.jpg)

**Comment by the1812** [comment]
这个是我故意写成比较醒目的样式, 不一定非得是黄色, 毕竟这不是警告

**Comment by Geeyun-JY3** [comment]
还记得几天前看到视频下方的公告横幅又跟随了主题色，好像还不是完全跟随的那种，总之需要适配。

之后看到会另开 issue 或在夜间模式 issue 下 comment 的。
