### ISSUE TITLE
新的季节logo api

### ISSUE THREAD

**Issue by loktindyi** [the1812/Bilibili-Evolved#2420]
### 关于哪一项功能

样式-使用季节logo

### 问题描述

旧的api虽然仍能使用，但内容已经停止更新
新的api已启用：
https://api.bilibili.com/x/web-show/page/header?resource_id=142

### 脚本版本

Stable v1.12.19

### 浏览器版本

极速浏览器13.5

### 是否开启 HEVC

优先 HEVC

### 错误信息

```shell
none
```

**Comment by the1812** [comment]
> https://api.bilibili.com/x/web-show/page/header?resource_id=142

需要传入一个变化的 resource_id (所以上面这个链接早就失效了), 在任意页面获取季节 Logo 目前似乎不太现实了, 我先撤掉这个功能了

**Comment by the1812** [comment]
原来如此, 好像传 1 能得到真正的季节 logo (bilibili 秋)
