### ISSUE TITLE
希望能在附加功能裡添加領取B幣的選項

### ISSUE THREAD

**Issue by ZOMBIE39** [the1812/Bilibili-Evolved#243]
也不知道批站怎麼想的 之前大會員每月自動發放的5B幣跟10元優惠券改成手動領取了 難道這個之前都是人工發放的 現在為了省事讓用戶自己去領 。。。。 所以 可以的話 希望能把這倆都加到附加功能裡去
![1](https://user-images.githubusercontent.com/37724369/69358251-ea794f80-0cc9-11ea-80a4-3988f3a45e4b.png)
![2](https://user-images.githubusercontent.com/37724369/69358270-f06f3080-0cc9-11ea-868c-6d49fa2588f5.png)

**Comment by Coulomb-G** [comment]
预览离线版(493.11)中已有该功能,相关按钮在顶栏的个人信息弹窗中

**Comment by ZOMBIE39** [comment]
> 预览离线版(493.11)中已有该功能,相关按钮在顶栏的个人信息弹窗中

安裝了預覽離線版之後看到了 放在了更方便使用的地方 感覺不用這個腳本都快不會用B站了 B站什麼時候能人性化一點呀
