### ISSUE TITLE
[V2] 组件（获取）更新失败导致输入弹窗

### ISSUE THREAD

**Issue by FoundTheWOUT** [the1812/Bilibili-Evolved#2450]
### 关于哪一项功能

`core`

### 问题描述

这几天出现的, 疯狂弹出`input`的文件输入.
没测试, 但估摸着应该是这里.
https://github.com/the1812/Bilibili-Evolved/blob/preview/src/core/file-picker.ts#L30

### 脚本版本

2.0.0 Pre

### 浏览器版本

Chrome  95.0.4638.69

### 错误信息

```shell
空
🤔 现在这个模版是必填的了吗
```

### 附加截图

就不截图了, 就是 `<input type='file'>` 点击后的效果.

**Comment by the1812** [comment]
这个应该只有调用 `pickFile` 的时候才会触发吧, 怎么会疯狂弹出...

**Comment by FoundTheWOUT** [comment]
我也觉得奇怪，可能还要继续确认一下是不是这个脚本导致的问题。

**Comment by FoundTheWOUT** [comment]
又遇到这个 Bug 了. 我打了下断点, 以下是调用栈
![截屏2021-11-02 下午10 43 19](https://user-images.githubusercontent.com/47922588/139870027-ff1ede32-dee2-4235-b719-8c2c24e06ad7.png)
是由`自动更新更新器`引发的问题. 它貌似是会依次对每个组件进行更新检查?
从断点的情况来看是拿不到某些组件的代码.

**Comment by the1812** [comment]
更新失败时自动跳过了, 应该不会弹窗了
