### ISSUE TITLE
设置完刷新完后网页左侧边菜单按钮丢失，但功能依旧生效

### ISSUE THREAD

**Issue by djkcyl** [the1812/Bilibili-Evolved#2452]
### 关于哪一项功能

主菜单

### 问题描述

刚升级完v2调完设置后刷新页面，菜单按钮丢失

### 脚本版本

2.0.0

### 浏览器版本

Microsoft Edge 版本 95.0.1020.40 (官方内部版本) (64 位)

### 错误信息

```shell
大概没有报错（
```

### 附加截图

![image](https://user-images.githubusercontent.com/59153990/139621386-fd4e9c85-fddb-4298-ae45-df592aa8bdca.png)
![image](https://user-images.githubusercontent.com/59153990/139621400-879995de-e55c-4391-9f30-9f513da22b79.png)

**Comment by NightSharp** [comment]
是不是开启了按钮隐藏，试着在边缘悬停试试

**Comment by Felix2yu** [comment]
确实是自动隐藏侧栏导致的，使用我全都要合集包会默认选中隐藏侧栏，但在我这鼠标移到页面左侧并不会显示侧栏。
系统：macOS 12.0.1
浏览器：Vivaldi 4.4.2465.3 内核Chromium/94.0.4606.104

**Comment by djkcyl** [comment]
草，离谱就，我得放到最边上的一个像素才能按到
![image](https://user-images.githubusercontent.com/59153990/139654465-b34b2736-99ce-4444-bef0-e0ae33e5f3aa.png)

**Comment by the1812** [comment]
自动隐藏侧栏是给最大化窗口用的, 平时习惯小窗口就不要装这个功能了

**Comment by djkcyl** [comment]
> 自动隐藏侧栏是给最大化窗口用的, 平时习惯小窗口就不要装这个功能了

明白了
