### ISSUE TITLE
在稍有再看界面, 如果启用了逐帧调整视频截图, 有三个按钮会不断重复生成.

### ISSUE THREAD

**Issue by lolisix** [the1812/Bilibili-Evolved#2453]
### 关于哪一项功能

启用逐帧调整与启用视频截图

### 问题描述

在稍有再看界面, 如果启用了逐帧调整视频截图, 这三个按钮会不断重复生成.
<a href="https://sm.ms/image/L1sdgyBMkZSWIic" target="_blank"><img src="https://i.loli.net/2021/11/01/L1sdgyBMkZSWIic.png" ></a>

### 脚本版本

v2.0.0-preview-13-gf6451c7d0

### 浏览器版本

Chrome浏览器  版本 95.0.4638.54（正式版本） （64 位）

### 播放器版本

2.69.1-3e469c5b

### 是否开启 HEVC

禁止 HEVC

### 错误信息

```shell
<a href="https://sm.ms/image/hwNYRXbeHOWm2Li" target="_blank"><img src="https://i.loli.net/2021/11/01/hwNYRXbeHOWm2Li.png" ></a>
```

**Comment by lolisix** [comment]
<a href="https://sm.ms/image/hwNYRXbeHOWm2Li" target="_blank"><img src="https://i.loli.net/2021/11/01/hwNYRXbeHOWm2Li.png" ></a>

**Comment by Yun-Shan** [comment]
相同的问题，仅启用了启用了逐帧调整后上一帧和下一帧的按钮会重复生成
目前我测试出来的稳定复现的方式是互动视频作出选择(然后触发了视频切换？)后会重复生成( https://www.bilibili.com/video/BV1W44y1e7GG )，之前在非互动视频也出现过这样的情况但是我忘记记录不知道是怎么出现的
浏览器：Chrome 95.0.4638.69
播放器版本：2.70.2-68aa2124 禁止HEVC
![image](https://user-images.githubusercontent.com/14977331/141647072-5bfebc67-acc0-4d17-8d64-2211ce35d61d.png)

**Comment by the1812** [comment]
原来如此, 快速收藏也崩了

**Comment by the1812** [comment]
现在应该不会重复生成了吧, 我测了互动视频是没问题的
