### ISSUE TITLE
设置里可以加一项，默认宽屏播放吗？

### ISSUE THREAD

**Issue by shifangwunian** [the1812/Bilibili-Evolved#246]
**关于哪一项功能**

设置-视频
**期望的效果**
进入视频默认宽屏播放

**脚本版本**

**Comment by Coulomb-G** [comment]
播放页左侧设置,「视频」中选择开启「使用默认播放器模式」,设置默认播放器模式「宽屏」

**Comment by shifangwunian** [comment]
> 式

谢谢

**Comment by shifangwunian** [comment]
> 播放页左侧设置,「视频」中选择开启「使用默认播放器模式」,设置默认播放器模式「宽屏」

但是要点击播放才能转换成宽屏，能不能进入视频就是宽屏模式呀

**Comment by Coulomb-G** [comment]
你可以选择关闭「播放时应用模式」

**Comment by shifangwunian** [comment]
> 你可以选择关闭「播放时应用模式」,建议阅读readme

非常感谢
