### ISSUE TITLE
[V2] 组件`播放前显示封面`，鼠标在暂停看到一半的视频上移动，也会显示封面

### ISSUE THREAD

**Issue by Yun-Shan** [the1812/Bilibili-Evolved#2463]
### 关于哪一项功能

播放前显示封面

### 问题描述

该问题曾在v1中出现并修复，最新的v1预览版也没有该问题 #2103
更新到v2预览版后出现该问题，问题与当时v1的情况完全一样，暂停后鼠标在视频上滑动会显示封面
应该任意视频都能触发

### 脚本版本

v2.0.0-preview-23-g3ec9dc326

### 浏览器版本

Chrome 95.0.4638.54

### 播放器版本

2.69.2-b40dad38

### 是否开启 HEVC

优先 HEVC

### 错误信息

```shell
无报错
```

**Comment by the1812** [comment]
没试出来, 不过关闭 HEVC 应该能解决.

这个问题当初还是 v2 先修的, 然后代码复制到 v1 里(

**Comment by Yun-Shan** [comment]
> 没试出来, 不过关闭 HEVC 应该能解决.
> 
> 这个问题当初还是 v2 先修的, 然后代码复制到 v1 里(

关闭HEVC确实解决了

**Comment by Yun-Shan** [comment]
刚刚看互动视频的时候发现禁止HEVC这个方法在互动视频不管用，禁止HEVC了还是会有这个问题
https://www.bilibili.com/video/BV1W44y1e7GG
浏览器：Chrome 95.0.4638.69
播放器版本：2.70.2-68aa2124 禁止HEVC
脚本版本：v2.0.1-preview-3-g97b51e17e
~互动视频真可怕~

**Comment by Yun-Shan** [comment]
在 v2.0.2-preview-1-g3b5d09b3f
该问题已解决 优先/强制HEVC也不会出现该问题了
