### ISSUE TITLE
图片加载不出来

### ISSUE THREAD

**Issue by Yofo-me** [the1812/Bilibili-Evolved#247]
> 不知道为什么启用这个插件后访问bilibili,个人头像没法加载出来,很多视频封面丢失,连个缩略图都没有

` 第一张截图 `
![screenshot](https://user-images.githubusercontent.com/55388087/69726806-40337900-115c-11ea-8a22-38a89cbef759.png)

` 第二张截图 `
![pg](https://user-images.githubusercontent.com/55388087/69726897-635e2880-115c-11ea-9874-f11cd29a56dc.png)

**Comment by the1812** [comment]
控制台(`Ctrl+Shift+I`)有什么报错信息吗?
