### ISSUE TITLE
2.0版本下拉动态不会自动刷新

### ISSUE THREAD

**Issue by rabbit2099** [the1812/Bilibili-Evolved#2472]
### 关于哪一项功能

顶栏动态

### 问题描述

顶栏动态下拉不会刷新，只有一点

### 脚本版本

v2.0.0-preview-23-g3ec9dc326

### 浏览器版本

95

### 错误信息

```shell
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/vue.min.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### 附加截图

![image](https://user-images.githubusercontent.com/75069083/140061039-6208ed31-25a6-4d41-8a8b-698b8196547c.png)

**Comment by the1812** [comment]
窗口高度太低了, 自动刷新那东西触发不到
