### ISSUE TITLE
[V2] 组件-在线仓库界面在浏览器 110% 缩放下字体变得模糊

### ISSUE THREAD

**Issue by GalaxySnail** [the1812/Bilibili-Evolved#2475]
### 关于哪一项功能

组件-在线仓库

### 问题描述

如题。这里的缩放指的是浏览器中使用 `CTRL` + 鼠标滚轮进行的缩放。

### 脚本版本

v2.0.0-preview-26-gd9e1c7223

### 浏览器版本

Chromium 91.0.4472.164（正式版本）（64 位）

### 错误信息

```shell
无错误信息
```

### 附加截图

![截图20211104004454](https://user-images.githubusercontent.com/53637421/140107138-27860fbd-2f2b-4c93-8c0d-440fb0a2538c.png)

**Comment by the1812** [comment]
看下 v2.0.1 正常了没? 我测不了你那种情况, 所以不确定修复了没

**Comment by GalaxySnail** [comment]
在 `v2.0.1-preview-3-g97b51e17e` 上正常了，非常感谢！
