### ISSUE TITLE
[V2] 设置中“简化首页”、“简化直播间”条目的选项菜单展开后，菜单部分内容被遮挡

### ISSUE THREAD

**Issue by GalaxySnail** [the1812/Bilibili-Evolved#2476]
### 关于哪一项功能

简化首页、简化直播间

### 问题描述

如题。文字不便于描述，直接贴截图吧：

![动态页-简化首页](https://user-images.githubusercontent.com/53637421/140159486-a93c1e1d-9bde-4c3d-90ad-f7c60a8dd5cf.png)

![动态页-简化直播间](https://user-images.githubusercontent.com/53637421/140160002-abfbee62-6aa1-40a0-8e92-9394f8533193.png)

上面两张图是在动态页截图的。图片下方的蓝黑色条是 Windows10 任务栏。

![首页-简化首页](https://user-images.githubusercontent.com/53637421/140162336-6b223e40-3415-4772-8fd5-7441bca6ba50.png)

上面这张图是在B站首页截的。

此问题与浏览器缩放比无关，50% 到 150% 均存在遮挡。

可见问题应该出在这个“选项”菜单的实现方式上，受影响的应该不止这两个设置。此外这个选项菜单背景透明，在某些网页背景上看不清楚。

### 脚本版本

v2.0.0-preview-26-gd9e1c7223

### 浏览器版本

Chromium 91.0.4472.164（正式版本）（64 位）

### 错误信息

```shell
无错误信息
```

**Comment by the1812** [comment]
遮挡的问题应该解决了, 不过我遇到过背景透明的情况, 应该是有白色背景的

**Comment by GalaxySnail** [comment]
下面倒是没有遮挡了，但是现在又被右边遮挡了（

![首页-简化首页](https://user-images.githubusercontent.com/53637421/140924853-3a027814-a117-48a7-8a8d-5e5ab439c04c.png)

![视频页-简化直播间](https://user-images.githubusercontent.com/53637421/140924882-eed9fb4a-2e48-42b0-8210-3adf9770021a.png)

脚本版本：`v2.0.1-preview-3-g97b51e17e`
浏览器版本：`Chromium 95.0.4638.69（正式版本）（64 位）`

**Comment by Charlie-Mars** [comment]
![image](https://user-images.githubusercontent.com/74394539/141610504-526bca29-4c80-4392-a82d-78f9a1444832.png)

**Comment by Geeyun-JY3** [comment]
那我来个上面被遮挡：
![image](https://user-images.githubusercontent.com/49396421/141674979-59921455-0190-4fc0-a9a5-d7018eafda38.png)
