### ISSUE TITLE
[V2] 在动态页点击“导出设置”不会正常导出，而是打开了一个格式不正确的网址

### ISSUE THREAD

**Issue by GalaxySnail** [the1812/Bilibili-Evolved#2477]
### 关于哪一项功能

关于-导出设置

### 问题描述

进入[哔哩哔哩动态页](https://t.bilibili.com)，点击关于-导出设置，不会正常弹出选择路径保存的对话框，而是打开一个格式不正确的网址，格式如下：

```
https://t.bilibili.comhttps//t.bilibili.com/{一个随机的uuid}?spm_id_from=444.41.0.0
```

例如：

```
https://t.bilibili.comhttps//t.bilibili.com/176d966b-dd3d-4552-8f61-ae0887b55c09?spm_id_from=444.41.0.0
```

控制台输出没有看到明显异常：

![截图20211104025418](https://user-images.githubusercontent.com/53637421/140174844-d8472b05-c4b8-4fb9-9e66-61d1845b4357.png)

### 脚本版本

v2.0.0-preview-26-gd9e1c7223

### 浏览器版本

Chromium 91.0.4472.164（正式版本）（64 位）

### 错误信息

浏览器很快试图打开新的 url，导致控制台被清空，来不及复制输出，不过上面已经提供了截图

**Comment by the1812** [comment]
v1 的自动破坏 spm_id 的功能忘同步到 v2 了
