### ISSUE TITLE
下载视频崩溃了

### ISSUE THREAD

**Issue by PE3FwV** [the1812/Bilibili-Evolved#248]
### **问题描述**

测试时使用的视频地址：https://www.bilibili.com/bangumi/play/ep280975
> 点击下载按钮，下载到大概接近50%进度时，浏览器显示崩溃了，内存不足
> 然后下载的视频也就4.9个GB，而我电脑内存是16GB
> 监视了一下浏览器运行轨迹，个人猜测是这样的：你的脚本下载时，是把视频数据下载到内存里，我看内存动态是浏览器占用的内存一直在涨，浏览器是64位的，不存在32位软件内存的限制问题，所以理论上64位浏览器可以使用很多内存，但至于为什么你下载到接近一半时内存不足，个人猜测是浏览器对脚本运行的限制，浏览器不允许开发者使用很多的内存占用？我不是脚本开发者，我不是很懂
> ### 个人建议：不要直接把整个视频写到内存，请直接输出到文件中，这样就不会出现内存不足的问题了

### **错误信息：喔唷，崩溃了，内存不足**

**附加截图**
![下载示例图](http://i2.tiimg.com/519870/bc18b360a9851efc.png)

![喔唷，崩溃了](http://i2.tiimg.com/519870/d6a24d5d07a18611.png)

**Comment by the1812** [comment]
这是浏览器的限制, 一个标签页最多占1~2G, 而且另一个限制就是不能直接输出到文件
4.9G的视频只能用下面的aria2导出了, 可以参考[这篇说明](https://github.com/the1812/Bilibili-Evolved/blob/master/aria2-notice.md).

**Comment by PE3FwV** [comment]
感谢您的回复，我去试试，但问题是，这是版权受限的视频，确定能用第三方软件下载吗？我点击您的显示链接功能，把视频源的链接用迅雷或者FDM等下载功能下载是被服务器拒绝的，即使用Chrome下载也是无效的，用aria2是可行的吗？

**Comment by the1812** [comment]
因为还需要一个Referer信息才能下载, 我只知道用IDM才可以捕获这个Referer, 所以这个功能就是留给IDM的.
aria2是由脚本传信息过去, 当然带了那个Referer, 是可以下载的. (顺便一提我也下载了哈利波特全集, 就是用的aria2)

**Comment by PE3FwV** [comment]
非常感谢，已经成功了，正在下载中，非常感谢您的脚本，简直是杀器啊，实现了下载版权受限视频的梦想！
