### ISSUE TITLE
左侧设置栏在有特殊皮肤的直播间可能被遮挡

### ISSUE THREAD

**Issue by Yun-Shan** [the1812/Bilibili-Evolved#2484]
### 关于哪一项功能

页面左侧设置栏

### 问题描述

https://live.bilibili.com/3044248

### 脚本版本

v2.0.0-preview-23-g3ec9dc326

### 浏览器版本

Chrome 95.0.4638.69

### 播放器版本

Bilibili HTML5 Live Player 3.5.25

### 是否开启 HEVC

优先 HEVC

### 错误信息

```shell
无
```

### 附加截图

p1是直播间的z-index，p2是左侧设置栏的z-index
可以看到左侧的设置按钮已经被遮挡了一半，继续往下拉就会全部被遮挡
![image](https://user-images.githubusercontent.com/14977331/140319605-ad16a4ec-ef08-433e-b064-313ba458d461.png)
![image](https://user-images.githubusercontent.com/14977331/140319156-3799edcb-13c9-46f5-8cf8-71ed9ddd2e09.png)

**Comment by the1812** [comment]
提高层级又会在直播网页全屏的时候挡不住...

**Comment by Yun-Shan** [comment]
研究了一下，可以判断player-full-win这个class，红框是我加上的，后面是原有的
![image](https://user-images.githubusercontent.com/14977331/141603204-b06be3de-52a9-4612-a5ac-b8efbff81f86.png)
不确定这个class是哪里生成的，因为在仓库里搜不到be-settings？盲猜是在这里加
https://github.com/the1812/Bilibili-Evolved/blob/9f4e62f50979ec97ab57d3bd8e93f2e7b254bf49/src/utils/gui-settings/gui-settings.scss#L20-L22

**Comment by the1812** [comment]
原来直播间也有这种 class, 那还可以
