### ISSUE TITLE
固定动态顶栏，并不能固定顶栏中个人信息、大会员、收藏、历史的悬浮展开栏

### ISSUE THREAD

**Issue by eythou** [the1812/Bilibili-Evolved#2493]
### 关于哪一项功能

强制固定动态侧栏 内部名称: fixedFeedsSidebars

### 问题描述

固定动态顶栏，并不能固定顶栏中个人信息、大会员、收藏、历史的悬浮展开栏，会随动态页面移动

### 脚本版本

v2.0.0-preview-31-g2fa5b5a73

### 浏览器版本

Microsoft Edge 版本 95.0.1020.40 (官方内部版本) (64 位)

### 错误信息

```shell
没有报错
```

**Comment by the1812** [comment]
我试了下能固定的啊?

**Comment by eythou** [comment]
![image](https://user-images.githubusercontent.com/59753492/140650248-a472cc05-a1a6-42e5-b5b8-c2cf29d76b65.png)
![image](https://user-images.githubusercontent.com/59753492/140650268-4456864e-41f0-4809-93c3-201a808039d2.png)

**Comment by the1812** [comment]
原来是原版顶栏啊...

**Comment by Geeyun-JY3** [comment]
v2.0.2-preview-1-g3b5d09b3f
Chrome 96.0.4664.45 测试
原版顶栏的 `主站`、`游戏中心`、`直播`、个人信息、`大会员`、`收藏`、`历史` 组件仍然无法固定
`漫画` 组件会抖动

**Comment by the1812** [comment]
版本跟你一样的, 我这边已经能固定了... 看来得赶紧弄下组件的 hash 生成了

**Comment by Geeyun-JY3** [comment]
今天确实都能固定了，就剩上面提到的 `漫画` 和 `动态` 组件的问题了。

**Comment by the1812** [comment]
漫画那个是因为 b 站给这里用 js 加了个定位 (还贼卡的那种), 我强制固定这个会导致弹窗直接跑到屏幕外去了

**Comment by Geeyun-JY3** [comment]
等动态首页也用上新版顶栏这个功能或许就能砍了：https://github.com/the1812/Bilibili-Evolved/issues/1217#issuecomment-984439411
新版顶栏会全局固定，漫画也不会抖动🌚。

**Comment by the1812** [comment]
新版顶栏的实现去掉那几个 iframe 了, 可喜可贺
