### ISSUE TITLE
在去问过B站客服之后，说推荐使用新版的播放器，所以会自动切换过去

### ISSUE THREAD

**Issue by Malus-Mill** [the1812/Bilibili-Evolved#250]
**关于哪一项功能**

**期望的效果**
在去问过B站客服之后，说推荐使用新版的播放器，所以会自动切换过去，希望可以添加固定新旧版的开关

**脚本版本**

正式版1.9.19

**Comment by the1812** [comment]
时代变了.

这个功能刚删掉 (#217)
![image](https://user-images.githubusercontent.com/26504152/69815338-097b6280-1231-11ea-9deb-039d13dfbd79.png)
