### ISSUE TITLE
自定义顶栏布局设置定时会被重置

### ISSUE THREAD

**Issue by SekiBetu** [the1812/Bilibili-Evolved#2501]
### 关于哪一项功能

自定义顶栏

### 问题描述

自定义顶栏的布局设置每次保存之后，过了一段时间又变回默认了，
如下面的附图，我之前开启了番剧、游戏中心、赛事，然后过了不知道多久，下次打开Chrome就又变回默认设置了(只有这个组件的设置被重置了，另外的比如播放器宽屏设置是没被重置的)，
在这礼拜已经发生无数次了，
是否是因为布局设置是和脚本一起走的，导致更新之后变回默认？
我不太确定，手动点了更新这个组件刷新也没事，但是就是定期会被重置回默认

### 脚本版本

v2.0.1-preview-3-g97b51e17e

### 浏览器版本

Chrome 95.0.4638.69

### 播放器版本

与问题无关

### 是否开启 HEVC

禁止 HEVC

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/38283893/141072272-e5cc105a-b0f8-4599-8226-0ca4f37485c1.png)

**Comment by SekiBetu** [comment]
[settings.zip](https://github.com/the1812/Bilibili-Evolved/files/7510844/settings.zip)
附上个人的配置文件以供测试，可以手动设置显示上述的三个元素，然后使用，用着用着就没了

**Comment by SekiBetu** [comment]
我还发现，这个弹性空白1和4，默认设置里是不显示的，所以说明，只有上述三个设置被重置了，弹性空白没被重置

**Comment by the1812** [comment]
你导出的设置是开启了番剧那些之前的还是之后的?

**Comment by SekiBetu** [comment]
> 你导出的设置是开启了番剧那些之前的还是之后的?

就目前图里状态，你可以手动开启这三个选项，然后用几天看看

**Comment by SekiBetu** [comment]
或者关浏览器重启电脑之类的，我没琢磨出规律，也有可能是我设置的1小时一次的更新

**Comment by SekiBetu** [comment]
> 你导出的设置是开启了番剧那些之前的还是之后的?

草，我刚才还设置了图里的三个选项，然后拉了个屎回来，刷新了一下页面，又变成图里状态了，没重启浏览器和系统，估计真是自动更新

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/141111516-dfa05226-3774-465f-9716-f9e5311beaca.png)
这个自动更新器更新的是哪个源啊，我上个版本记得我设置了github，然后全部点了下更新，刷新，再导出，发现还是cdn的

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/141112079-d7c79bd2-8b1e-4e37-9fa4-4d9c4c1123d0.png)
草，刚设置完又回去了，什么情况

**Comment by the1812** [comment]
我看了你导出的设置, 有点奇怪, 相簿和音频出现了两次
<img width="200" src="https://user-images.githubusercontent.com/26504152/141112289-9e98330d-cfd9-4dd3-add6-6f8fef199c02.png">

这个我觉得跟更新时的设置合并方式有关, 你先把更新间隔设长点吧, 自定义顶栏可以试试卸载再重装把设置重置掉

**Comment by SekiBetu** [comment]
卸载脚本，重开Chrome，重新安装脚本，导入
```
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/feeds/copy-link.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/feeds/fixed-sidebars.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/feeds/full-content.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/live/badge-helper.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/live/download-records.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/live/home-mute.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/style/auto-hide-sidebar.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/style/dark-mode.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/style/player-on-top.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/utils/comments/copy-link.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/utils/download-audio.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/utils/image-exporter.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/utils/url-params-clean.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/utils/view-cover.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/video/danmaku/download.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/video/download.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/video/player/default-mode.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/video/player/screenshot.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/video/player/seek-by-frames.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/video/player/show-cover.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/video/seo-redirect.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/video/subtitle/download.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/components/style/custom-navbar.js

https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/plugins/launch-bar/trending-search.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/plugins/video/download/aria2-output.js
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/registry/dist/plugins/video/download/idm-output.js
```

手动配置好，导出设置，依旧是出现两次

![image](https://user-images.githubusercontent.com/38283893/141113565-415b1e8d-4ddb-4679-9f81-1faf329c576e.png)

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/141113727-37fe1173-19fe-4468-adb8-38a4d4f0bf62.png)
设置成1分钟一次，过了一分钟，刷新，
![image](https://user-images.githubusercontent.com/38283893/141113761-18f51f86-46b9-40b1-b048-aad516b3c4c5.png)
又没了

**Comment by the1812** [comment]
那应该就是设置合并有 bug 了

**Comment by SekiBetu** [comment]
https://user-images.githubusercontent.com/38283893/141115246-fcdc59fb-6eba-4106-b429-398b12e490bf.mp4
[视频中导出的配置.zip](https://github.com/the1812/Bilibili-Evolved/files/7512773/default.zip)

**Comment by SekiBetu** [comment]
github只让传10M大小文件，压缩成480P了，将就看看，中间等了一分钟，刷新之后顶栏设置就没了

**Comment by Itzamana** [comment]
我这也出现了这个自定义顶栏布局设置重置 的bug…
我和楼主一样用的是暴力猴，会不会是暴力猴的问题…？

**Comment by the1812** [comment]
试下 v2.0.2 还有这问题吗

**Comment by SekiBetu** [comment]
> 试下 v2.0.2 还有这问题吗

v2.0.2-preview-1-g3b5d09b3f

![image](https://user-images.githubusercontent.com/38283893/142422882-6b3dc33e-0bb0-43e7-bc68-617fab0087a6.png)
![image](https://user-images.githubusercontent.com/38283893/142422911-ae605695-3004-4572-bbe3-45c490e20533.png)
![image](https://user-images.githubusercontent.com/38283893/142422943-d68d4e7b-0c74-429c-b07d-c96bc3dd6fa0.png)

仍然存在

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/142424221-c1cc91d8-b771-464a-943e-168c7028eef6.png)
单独安装这个组件甚至没有选项了

**Comment by the1812** [comment]
选项要登录才有

**Comment by SekiBetu** [comment]
刚设置完时候的配置文件
![image](https://user-images.githubusercontent.com/38283893/142424851-7b52da0f-c31a-42b3-87e7-8612bd92a471.png)
更新后的配置文件
![image](https://user-images.githubusercontent.com/38283893/142424886-c653919b-022c-4840-9682-2c0c17fdcb95.png)

**Comment by the1812** [comment]
我再排查排查

**Comment by SekiBetu** [comment]
[爆炸前后配置文件.zip](https://github.com/the1812/Bilibili-Evolved/files/7563165/default.zip)

**Comment by Itzamana** [comment]
![image](https://user-images.githubusercontent.com/20204389/142465981-cf63bbbd-6a1a-438c-bee5-b0e3d03761bf.png)

我的更新时间是默认的24小时，似乎到每天0点检查更新后，设置就会变成这样，各项的顺序不会变，但那7项每次都自动改为隐藏…

**Comment by the1812** [comment]
其他几种类似的功能有这个问题吗?
- 动态过滤器: 设置过滤类型 / 关键词 / 侧栏
- 倍速记忆: 添加自定义扩展倍速

**Comment by Itzamana** [comment]
> 其他几种类似的功能有这个问题吗?
> 
> * 动态过滤器: 设置过滤类型 / 关键词 / 侧栏
> * 倍速记忆: 添加自定义扩展倍速

没有，其他的都一切正常

**Comment by Itzamana** [comment]
> 其他几种类似的功能有这个问题吗?
> 
> * 动态过滤器: 设置过滤类型 / 关键词 / 侧栏
> * 倍速记忆: 添加自定义扩展倍速

昨天和今天似乎自定义顶栏设置没有重置了，我再观察两天看看…

**Comment by SekiBetu** [comment]
v2.0.3-preview-7-ge4cb3ccfa 版本正常
