### ISSUE TITLE
希望大佬能增加adguard的脚本管理器支持，现在是无效的状态

### ISSUE THREAD

**Issue by AllanFLan** [the1812/Bilibili-Evolved#251]
**关于哪一项功能**
增强兼容性

**期望的效果**
希望兼容adguard的脚本管理器
<img width="665" alt="截屏2019-11-30上午7 26 09" src="https://user-images.githubusercontent.com/36136750/69892664-dde89d00-1342-11ea-821b-918410f15274.png">

**脚本版本**
1.9.19

**Comment by the1812** [comment]
这是Mac版的功能吗? 我没找着Adguard哪有加扩展的地方
![image](https://user-images.githubusercontent.com/26504152/71171667-4c14e580-2299-11ea-9c41-4941afce5ca3.png)

**Comment by AllanFLan** [comment]
Windows版也有
![批注 2019-12-21 213414](https://user-images.githubusercontent.com/36136750/71308624-f6c40a00-2439-11ea-86ce-209ff9d7ecf0.png)

**Comment by AllanFLan** [comment]
Windows版也有
![批注 2019-12-21 213414](https://user-images.githubusercontent.com/36136750/71308654-3854b500-243a-11ea-8a4f-1949103c3346.png)

**Comment by the1812** [comment]
AdGuard不支持储存复杂数据 (数组, 对象等), 我无法兼容它. 请使用 Tampermonkey 或 Violentmonkey 插件.
![image](https://user-images.githubusercontent.com/26504152/72231610-6c656500-35f7-11ea-9dcf-fe5b3b9ec82b.png)
![image](https://user-images.githubusercontent.com/26504152/72231688-d41bb000-35f7-11ea-8450-e83aae3fb484.png)

**Comment by foisonocean** [comment]
@the1812 将配置序列化之后再保存不就行了么 (`JSON.stringify(config)`)，需要读取配置的时候再反序列化一下 (`JSON.parse(text)`)

**Comment by the1812** [comment]
这是脚本管理器应该做的事, 请向AdGuard反馈.

**Comment by Arron196** [comment]
> 这是脚本管理器应该做的事, 请向AdGuard反馈.

目前已经支持了
