### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by f59375543** [the1812/Bilibili-Evolved#2511]
编辑

已解决

**Comment by Geeyun-JY3** [comment]
会不会是偶发 bug，建议过两天再看看

**Comment by f59375543** [comment]
> 会不会是偶发 bug，建议过两天再看看

已经好几天都是这样了

**Comment by Geeyun-JY3** [comment]
那就建议贴报错，排除有没有冲突的脚本或扩展

**Comment by f59375543** [comment]
> 那就建议贴报错，排除有没有冲突的脚本或扩展。
> 
> 我这边百分一直都能加载出来。

已关闭所有扩展，仅留一个油猴运行Offline

**Comment by f59375543** [comment]
> 那就建议贴报错，排除有没有冲突的脚本或扩展。
> 
> 我这边百分一直都能加载出来。

怪事，卸载Offline后重装，重新导入设置就没问题了

**Comment by Geeyun-JY3** [comment]
不用改标题，解决后把 issue close 掉就行。
