### ISSUE TITLE
希望可以增加对直播弹幕的记录功能

### ISSUE THREAD

**Issue by 31415926loli** [the1812/Bilibili-Evolved#252]
**关于哪一项功能**
直播页面 附加功能

**期望的效果**
希望可以在直播间页面的附加功能添加一个记录直播弹幕的开关或按钮，开启后开始记录直播弹幕，并在关闭后生成xml文件。说实话我并不知道只是否是b站网页端可以实现的功能，所以只能问问，希望大佬解答。

**脚本版本**
Bilibili Evolved (Preview)

**Comment by Coulomb-G** [comment]
https://ngabbs.com/read.php?tid=17199360
你可以参考一下,已经有人做过类似的功能了

**Comment by 31415926loli** [comment]
> https://ngabbs.com/read.php?tid=17199360
> 你可以参考一下,已经有人做过类似的功能了

那个我去看了，似乎是纯文本形式的记录。我还是更希望能以弹幕这种时间轴的形式记录下来。主要是参考了ytb自身的直播评论回放功能，然后又有个评论转弹幕形式的插件，于是就想能不能回放b站直播的弹幕。

**Comment by the1812** [comment]
我之后会试试的 (不过可能会鸽挺久, 还有些以前的功能没做完

**Comment by 31415926loli** [comment]
> 我之后会试试的 (不过可能会鸽挺久, 还有些以前的功能没做完

没关系的，麻烦大佬了

**Comment by shitianshiwa** [comment]
https://github.com/CHKZL/DDTV
这个也可以参考下，有弹幕记录功能(虽然实际使用频繁下不到弹幕且无样式)
新版本ddtv2还没有下载弹幕功能
---
https://github.com/xfgryujk/blivetts
直播弹幕要求的最低格式大概是：
开始时间(秒),模式,字体,颜色,时间戳(blivedm得到的应该是毫秒，ddtv1下载用的是秒),0,0,0,内容
参考：https://github.com/xfgryujk/blivedm/blob/master/blivedm.py#L56 （开始时间(秒)不存在，要自己另加，后面3个0亦同。参考ddtv1下载的弹幕结果）
需要知道直播间当前已播放时间才能填写弹幕开始时间（暂没找到如何得到直播时间）
我个人还想知道开始直播事件和结束事件
