### ISSUE TITLE
关于批量下载视频后视频无顺序的问题

### ISSUE THREAD

**Issue by yun-Tong** [the1812/Bilibili-Evolved#2520]
### 关于哪一项功能

下载视频

### 问题描述

找一个多p的视频，下载过后视频没有顺序，视频过多的话很难受

### 脚本版本

v1.12.22

### 浏览器版本

4.1.7.26 （32 位）

### 错误信息

```shell
输入的下载idm文件，下载后没有顺序
```

**Comment by the1812** [comment]
需要顺序用 aria2 下, idm 就是乱序的

**Comment by yun-Tong** [comment]
> 需要顺序用 aria2 下, idm 就是乱序的

好的，不过你怎么回复的这么快
