### ISSUE TITLE
部分动态反折叠功能失效

### ISSUE THREAD

**Issue by Tinhone** [the1812/Bilibili-Evolved#2529]
### 关于哪一项功能

动态反折叠

### 问题描述

![图片](https://user-images.githubusercontent.com/81268244/142039396-17cc9774-b9fc-406e-8dfd-78b4f8ffece9.png)
功能失效，无法自动展开动态
![图片](https://user-images.githubusercontent.com/81268244/142040043-f1621488-d566-4759-a94c-33fa042e716e.png)

### 脚本版本

V1.12.22

### 浏览器版本

Firefox85.0

### 错误信息

```shell
-
```

**Comment by Geeyun-JY3** [comment]
我碰到过，目前还能复现，找某些提到抖音或骂叔叔的动态就能。

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/1692#issuecomment-870601031 提到的也能复现

**Comment by Tinhone** [comment]
由于 Bilibili Evolved V1 已不再受支持 & 无后续反馈，故认为这个 issue 已过时，我会关闭它

**Comment by Geeyun-JY3** [comment]
但愿`动态反折叠`已经能自动展开被限流动态。

**Comment by Tinhone** [comment]
> 但愿`动态反折叠`已经能自动展开被限流动态。

也许只能等待下一次反馈了
