### ISSUE TITLE
希望能增加自動勾選直播彈幕屏蔽功能

### ISSUE THREAD

**Issue by ZOMBIE39** [the1812/Bilibili-Evolved#253]
![1](https://user-images.githubusercontent.com/37724369/70135377-4f22aa00-16cd-11ea-80e7-911929e0ba45.png)
這個屏蔽關鍵詞跟屏蔽用戶不知道為什麼每次重進直播間 甚至是刷新一次 都要重新去勾上 所以希望能實現進直播間的時候自動全選屏蔽關鍵詞跟全選屏蔽用戶的功能

**Comment by the1812** [comment]
勾选不是用来删除的吗, 不勾选时只要在那就是生效的

**Comment by ZOMBIE39** [comment]
> 勾选不是用来删除的吗, 不勾选时只要在那就是生效的

是嗎 。。。。。。 因為有時候屏蔽了還是能看見 實在不太清楚這個屏蔽怎麼用
