### ISSUE TITLE
鼠标悬停动态预览，右键在新标签打开页面后，动态自动收起

### ISSUE THREAD

**Issue by qianbinbin** [the1812/Bilibili-Evolved#2538]
### 关于哪一项功能

动态

### 问题描述

预期：动态不应该自动收起，方便连续后台打开多个页面

### 脚本版本

v1.12.22

### 浏览器版本

Chrome 94.0.4606.54

### 错误信息

```shell
/
```

**Comment by Geeyun-JY3** [comment]
连续后台打开多个页面的话建议直接中键单击

**Comment by qianbinbin** [comment]
mac没有中键

**Comment by Geeyun-JY3** [comment]
不对啊目前自定义顶栏就是不会收起啊，我这边测试就不会收起。

**Comment by Geeyun-JY3** [comment]
#878

排查一下有没有相似扩展或脚本：https://github.com/the1812/Bilibili-Evolved/issues/878#issuecomment-735565935

**Comment by qianbinbin** [comment]
好的，谢谢，我回去再看看

**Comment by the1812** [comment]
正常情况下不会这样就收起了的, 另外 cmd + 点击也可以新标签页打开

**Comment by qianbinbin** [comment]
删除了其他b站相关的脚本和扩展，还是不行（之前就禁用了）
macOS 版本 10.15.7，Chrome 94.0.4606.54
cmd + 点击确实可以

**Comment by Geeyun-JY3** [comment]
我的建议是只开启本脚本进行测试，部分不相关扩展和脚本亦有可能影响。

不行的话也没办法，https://github.com/the1812/Bilibili-Evolved/issues/878#issuecomment-687096713 就是这样的情况，我之前也碰到过，后续你可以看 #878 讨论串。

**Comment by qianbinbin** [comment]
禁用了所有其他脚本和扩展，no luck

**Comment by qianbinbin** [comment]
不知道从哪个版本开始这个 bug 已经解决了，感谢各位😄
