### ISSUE TITLE
V2的设置面板在火狐浏览器中无法呼出

### ISSUE THREAD

**Issue by ELF0230** [the1812/Bilibili-Evolved#2539]
### 关于哪一项功能

设置面板

### 问题描述

刚安装脚本的时候可以呼出，但是下载完在线插件之后无法呼出设置面板，直接通过导入V1设置也是如此

### 脚本版本

V2.0.2

### 浏览器版本

Firefox 94.0.1 (64 位)

### 错误信息

```shell
.
```

**Comment by the1812** [comment]
你是不是开了 `自动隐藏侧栏`, 鼠标在窗口最左侧 1px 停留才会出现设置

**Comment by ELF0230** [comment]
> 你是不是开了 `自动隐藏侧栏`, 鼠标在窗口最左侧 1px 停留才会出现设置

鼠标停留在最左侧也无法呼出，不过给了我一个思路，安装插件时不要选简洁合集包以及自动隐藏侧栏，这样子就能进到设置面板了，看样子应该是 自动隐藏侧栏 这个插件在火狐上有问题（edge可以正常使用）

**Comment by the1812** [comment]
挺奇怪, 火狐上触发区域位置是正常的, 但鼠标放那就变成调整窗口大小了, 我得把这区域调大一些
