### ISSUE TITLE
在某些视频应用脚本播放器区域会消失（已找到原因

### ISSUE THREAD

**Issue by ClariSMOMO** [the1812/Bilibili-Evolved#254]
**问题描述**

https://www.loom.com/share/29784179c8b848adbb6585b789c01474

视频里演示的：https://www.bilibili.com/video/av67169186
点击右下角相关推荐第一个 av67415469 又没问题

***不是所有视频都有问题***
https://www.bilibili.com/video/av76369579 有
https://www.bilibili.com/video/av78135967 没有
https://www.bilibili.com/video/av77963556 有

**找到的原因**
安装了这个：扩展程序【为什么你们就是不能加个空格呢？】https://chrome.google.com/webstore/detail/%E7%82%BA%E4%BB%80%E9%BA%BC%E4%BD%A0%E5%80%91%E5%B0%B1%E6%98%AF%E4%B8%8D%E8%83%BD%E5%8A%A0%E5%80%8B%E7%A9%BA%E6%A0%BC%E5%91%A2%EF%BC%9F/paphcfdffjnbcgkokihcdjliihicmbpd
不知道是哪里出了问题，不知道怎么解决

**暂时的办法**
扩展程序添加白名单或B站切换到旧版【但还是希望作者能看下

**Comment by the1812** [comment]
B站的新版播放器在加载完成之前, 如果改动了里面任何内容, 播放器就会直接消失
至于这播放器加载得有多快就难说了, 你想稳定不消失就只能加白名单

**Comment by ClariSMOMO** [comment]
> B 站的新版播放器在加载完成之前，如果改动了里面任何内容，播放器就会直接消失
> 至于这播放器加载得有多快就难说了，你想稳定不消失就只能加白名单

好我大概懂了，现在给扩展程序加了下延时，两个都可以用，强迫症有救了...
