### ISSUE TITLE
V2 无法加载

### ISSUE THREAD

**Issue by jjj201200** [the1812/Bilibili-Evolved#2542]
### 关于哪一项功能

功能下载与加载问题

### 问题描述

除油猴外，没有启用其他扩展，油猴只启用了本脚本。

我应该是在2.0.1版本（大概，反正不是最新的2.0.2）点击下载的「简洁之上」。
过没多久弹出更新提示，然后我点击安装后刷新的网页，然后整个脚本界面就出不来了，就像没加载一样。

在油猴编辑页面使用「重置到出厂」后刷新网页可显示脚本界面，此时只有三个原始组件，重定点击下载安装「简洁之上」后刷新页面问题可以稳定复现

context页面无任何报错信息

2.0真不错，好顶赞

### 脚本版本

2.0.2

### 浏览器版本

chrome 96.0.4664.55

### 是否开启 HEVC

禁止 HEVC

### 错误信息

```shell
```

**Comment by jjj201200** [comment]
找到问题了，报404
![image](https://user-images.githubusercontent.com/3397549/142725478-fb797eda-d21a-42f1-a050-5017e4012ce6.png)

**Comment by the1812** [comment]
请下载 `preview` 分支的脚本, `v2` 是以前技术预览版测试用的, 现已弃用

**Comment by jjj201200** [comment]
收到

**Comment by the1812** [comment]
那有 `bilibiliEvolved` 这个全局变量吗

**Comment by jjj201200** [comment]
@the1812 有

**Comment by the1812** [comment]
因为简洁至上里有个自动隐藏侧栏, 启用后只有鼠标放在最边缘才会触发

**Comment by jjj201200** [comment]
@the1812 嗷还真是这样，感谢答疑，应该没问题了

**Comment by the1812** [comment]
感觉 v2 preview 发布以来有好多因为意外开了这个找不到设置面板的问题, 我还是别在合集包里带这个了

**Comment by jjj201200** [comment]
hmmm可以给这个功能加一个首次提醒，例如影藏起来后在左侧给一个小气泡提示隐藏
