### ISSUE TITLE
希望增加个将播放器窗口移到最左侧的功能

### ISSUE THREAD

**Issue by z333342** [the1812/Bilibili-Evolved#255]
**关于哪一项功能**

**期望的效果**
这样右侧可以空出更多的地方放聊天窗口或者一些文档

**脚本版本**

**Comment by the1812** [comment]
这样不行吗?
![Snipaste-2019-12-09-13-37-14](https://user-images.githubusercontent.com/26504152/70421885-b19cf100-1aa5-11ea-9128-e58ae1677167.png)
