### ISSUE TITLE
油猴更新后该脚本失效

### ISSUE THREAD

**Issue by William-02-02** [the1812/Bilibili-Evolved#2558]
### 关于哪一项功能

整体布局

### 问题描述

我用edge试了一下应该是红猴更新引起的
更新前还能用 重启浏览器更新红猴后就没法用了。
红猴v4.14.6147   
bilibili-Evolved 1.12.22

### 脚本版本

1.12.22

### 浏览器版本

版本 96.0.4664.45

### 错误信息

```shell
Failed to load resource.
```

### 附加截图

![image](https://user-images.githubusercontent.com/63051334/143733661-6918506c-947a-4d59-9154-f02182e5cd8c.png)

**Comment by PSGAGA** [comment]
同红猴6147
这个脚本在B站无效了删除后重新安装刷新后左边设置面板就不见了，设置项也没有生效，黑猴的Edge没问题，其他插件、脚本均相同就是，只有Chrome上的红猴一个变量。

**Comment by doio** [comment]
同6147
左边设置面板、图标，顶部banner都不见了

**Comment by leintos** [comment]
几乎就没法用了，也是红油猴更新后，希望能尽快修复....

**Comment by Rushoutw** [comment]
同chrome 油猴beta 4.14.6147  今天更新了油猴版本，然后b站首页进去后，就一片空白了

**Comment by the1812** [comment]
感觉像是红猴出 bug 了, `GM_setValue` 一个数组, 再 `GM_getValue` 取出来就变成空对象了
<img src="https://user-images.githubusercontent.com/26504152/143814503-e9775342-25a3-4bbb-8386-87851233a487.png" width="400">
而且原本应该有个 `存储` 的 tab 也不见了
![image](https://user-images.githubusercontent.com/26504152/143814732-8da51f9c-6047-49fb-93dd-ed10a3c69e15.png)
![image](https://user-images.githubusercontent.com/26504152/143814626-11855e66-8a00-4eac-9ce6-b999d68e8007.png)

**Comment by doio** [comment]
昨天晚上看是有「储存」的，我还特意因为出了问题在「储存」里面重置设置然后看看会不会解决，解决不了又恢复了原先里面的内容，用回黑猴了

**Comment by Rushoutw** [comment]
> 感觉像是红猴出 bug 了, `GM_setValue` 一个数组, 再 `GM_getValue` 取出来就变成空对象了 <img alt="" width="400" src="https://user-images.githubusercontent.com/26504152/143814503-e9775342-25a3-4bbb-8386-87851233a487.png"> 而且原本应该有个 `存储` 的 tab 也不见了 ![image](https://user-images.githubusercontent.com/26504152/143814732-8da51f9c-6047-49fb-93dd-ed10a3c69e15.png) ![image](https://user-images.githubusercontent.com/26504152/143814626-11855e66-8a00-4eac-9ce6-b999d68e8007.png)

刚去看了一下，存储是有的啊

**Comment by rick-yao** [comment]
我这里离线预览版是没有存储选项的

**Comment by the1812** [comment]
有存储的看一下里面 customStyles 被存成什么了?

**Comment by Rushoutw** [comment]
> customStyles

"customStyles": [],

文本编辑器里只有一个这个，显示是空

**Comment by doio** [comment]
Tampermonkey Beta 刚刚更新 4.14.6148
```
2021-11-28
General:
Sandbox improvements
Regression:
Fix GM_getValue with array type values
```

好像修复了

**Comment by the1812** [comment]
4.14.6148 中测试已正常

**Comment by changyexing** [comment]
同，红猴更新后界面按钮都没了，这是我的B站主页....
![image](https://user-images.githubusercontent.com/47708150/144080243-fb08d2ba-6834-49cf-80c8-d515745370fc.png)

**Comment by rick-yao** [comment]
@changyexing 别在商店版下载，去Tampermonkey/tampermonkey#1376作者回复的地方下载，那里是4.14.6148，商店还没更新
