### ISSUE TITLE
倍速记忆/重置倍速快捷键/扩展倍速菜单bug

### ISSUE THREAD

**Issue by sunfkny** [the1812/Bilibili-Evolved#2561]
### 关于哪一项功能

倍速记忆/重置倍速快捷键/扩展倍速菜单

### 问题描述

关闭`倍速记忆`，重置倍速表现为：无论哪个速度按下会变成1x
打开`倍速记忆`以及子项`扩展倍速菜单`时，重置倍速表现为：
1，按下重置倍速快捷键，自带速度（0.5x, 0.75x, 1.25x, 1.75x, 2）会变成1x，再按下就变成0.5x；
2，自己添加的速度按下就会先变成1x，再重置倍速就变成之前的速度；

除了会异常切换成0.5x，同一个快捷键功能不一致，我建议改成切换1x和之前的速度这种

### 脚本版本

v2.0.2-preview-1-g3b5d09b3f

### 浏览器版本

Chrome 已是最新版本 版本 96.0.4664.45（正式版本） （64 位）

### 播放器版本

2.70.9-2565d7fb

### 错误信息

```shell
见附加截图
```

### 附加截图

![image](https://user-images.githubusercontent.com/30853461/143836943-0db4af9d-0e40-4059-877b-9ff274df9d7b.png)

**Comment by LonelySteve** [comment]
可能需要改一种监听方式了，v1版也有这个问题了

**Comment by the1812** [comment]
这个是监听的问题吗, 我以为是我迁移 v2 没弄好
