### ISSUE TITLE
建议恢复新旧版播放器切换功能

### ISSUE THREAD

**Issue by KuhaQueen** [the1812/Bilibili-Evolved#257]
**关于哪一项功能**

12月9日下午, B站强制采用新版播放器, 且没有返回旧版按钮了, 因此建议恢复该功能
**期望的效果**
RT

**脚本版本**
1.9.19

**Comment by the1812** [comment]
毕竟是**强制采用**, 我也没有办法, 只能建议你尽快适应新版.

**Comment by KuhaQueen** [comment]
23333如果真的找不到什么"隐藏开关"的话也不勉为其难啦, thx
