### ISSUE TITLE
Violentmonkey 2.0版本会更新到1.0版本

### ISSUE THREAD

**Issue by Sabiary** [the1812/Bilibili-Evolved#2579]
### 关于哪一项功能

更新

### 问题描述

Violentmonkey 安装2.0开始，每次自动更新都会更新回1.0。

### 脚本版本

2.0

### 浏览器版本

Microsoft Edge 96.0.1054.41

### 错误信息

```shell
无
```

**Comment by NightSharp** [comment]
我也是这样，每次都需要在github页面手动更新

**Comment by the1812** [comment]
Violentmonkey 里手动检查更新会变成 v1 吗

**Comment by NightSharp** [comment]
> Violentmonkey 里手动检查更新会变成 v1 吗

@the1812 现在v2没有新版本，倒是会提示未发现新版本，不知道等有新版本后会不会又给更新回去

**Comment by Sabiary** [comment]
> Violentmonkey 里手动检查更新会变成 v1 吗

2.0.5更新了又自动更新回到1.0版本了

**Comment by the1812** [comment]
用这个 2.0.4 版测试看看? 装了然后手动检查更新
https://github.com/the1812/Bilibili-Evolved/raw/v2.0.5-preview/dist/bilibili-evolved.preview.user.js

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/145019063-66ee9134-8d87-4644-a9ef-7044cc6048d7.png)
自己用了老版本，升上来的时候没改这个吧

**Comment by NightSharp** [comment]
> 用这个 2.0.4 版测试看看? 装了然后手动检查更新 https://github.com/the1812/Bilibili-Evolved/raw/v2.0.5-preview/dist/bilibili-evolved.preview.user.js

会回到旧版

**Comment by the1812** [comment]
可以检查下 @SekiBetu 那里的设置, 或者导出设置删掉脚本再重装
(不过 v1 覆盖安装 v2 难道不会更新这个链接的吗

**Comment by NightSharp** [comment]
> 可以检查下 @SekiBetu 那里的设置, 或者导出设置删掉脚本再重装 (不过 v1 覆盖安装 v2 难道不会更新这个链接的吗

这是我用你的[链接](https://github.com/the1812/Bilibili-Evolved/raw/v2.0.5-preview/dist/bilibili-evolved.preview.user.js)安装2.0.4后的相关链接截图
![屏幕截图 2021-12-07 192632](https://user-images.githubusercontent.com/9748063/145021159-ff3a6db2-6130-4253-87a4-7bc79638cf7c.png)

**Comment by Sabiary** [comment]
下载地址和更新地址改成2.0的就正常了，这个地址不会自动替换是真的有些奇怪。

**Comment by NightSharp** [comment]
> 下载地址和更新地址改成2.0的就正常了，这个地址不会自动替换是真的有些奇怪。

我更新后地址是cdn.jsdelivr.net开头

**Comment by the1812** [comment]
最后那里有个 `/dist/` 就是对的

**Comment by NightSharp** [comment]
> 最后那里有个 `/dist/` 就是对的

我从你的preview分支下的预览版链接点进去后就是如图所示的地址，会导致更新到1.0

**Comment by the1812** [comment]
刚试了先装 v1, 然后升级到 v2, 再检查更新也没问题, 更新地址是 v2 的

**Comment by NightSharp** [comment]
> 刚试了先装 v1, 然后升级到 v2, 再检查更新也没问题, 更新地址是 v2 的

我看了一下，应该是脚本里面虽然自带了更新和下载地址，但脚本管理器还有个手动修改的地方可以覆盖掉脚本本身的下载地址设置，这个地方无法被脚本本身修改，我是直升的然后一直没注意以为下载地址链接会随着脚本更新，改成git那个后就没问题了，不知道cds.jsdelivr是否也可行
