### ISSUE TITLE
希望增加去除播放器的up主头像

### ISSUE THREAD

**Issue by ifwlzs** [the1812/Bilibili-Evolved#258]
**期望的效果**
去除视频播放时，播放器左上角的关注UP主按钮
![image](https://user-images.githubusercontent.com/49548316/70439107-37cb2e80-1aca-11ea-8667-353dec9f4383.png)

**脚本版本**
1.9.19

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/70439458-0a32b500-1acb-11ea-8924-d26e13af3b3a.png)
