### ISSUE TITLE
自动定位到播放器功能在同时开启了默认播放模式的情况下失效

### ISSUE THREAD

**Issue by dooooraemon** [the1812/Bilibili-Evolved#2580]
### 关于哪一项功能

自动定位到播放器

### 问题描述

同时开启自动定位到播放器功能和默认播放模式，默认播放模式选择了宽屏

打开一个视频，首先生效的功能是自动定位到播放器，然后自动切换到宽屏模式，B站切换宽屏会重新定位至能完整显示视频标题和up主头像，在电脑屏幕比较小的情况下不能完整显示播放器部分。

希望能调整这两个功能生效的先后顺序

### 脚本版本

Stable v1.12.22 内容包: b5055b3

### 浏览器版本

版本 95.0.4638.54 (正式版本) (64 位元)

### 错误信息

```shell
无
```

**Comment by Geeyun-JY3** [comment]
善用搜索，重复：#483

**Comment by dooooraemon** [comment]
> 善用搜索，重复：#483

谢谢！
