### ISSUE TITLE
希望出快捷键增加跳过OPED（90秒）的时间的功能

### ISSUE THREAD

**Issue by CCCAUCHY** [the1812/Bilibili-Evolved#259]
**关于哪一项功能**

**期望的效果**

**脚本版本**

**Comment by Coulomb-G** [comment]
现在的番剧已经不怎么遵守90秒的规则了(这都上世纪动画的规矩了),甚至op插入时间也没有严格规定了,有些甚至放了大半才开始op,时间长了短了都得重新调整,是吃力不讨好的功能,目前播放器控制栏那边的「00:00/24:00」是可以直接输入时间跳转的,评论区发空降时间点也可以点击跳转

**Comment by CCCAUCHY** [comment]
> 现在的番剧已经不怎么遵守90秒的规则了(这都上世纪动画的规矩了),甚至op插入时间也没有严格规定了,有些甚至放了大半才开始op,时间长了短了都得重新调整,是吃力不讨好的功能,目前播放器控制栏那边的「00:00/24:00」是可以直接输入时间跳转的,评论区发空降时间点也可以点击跳转

https://greasyfork.org/zh-CN/scripts/377235-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9-bilibili-com-%E7%95%AA%E5%89%A7%E8%B7%B3%E8%BF%87%E7%89%87%E5%A4%B4
这是我之前用的脚本（我自己修改过，原版是90秒，我改成了85秒），新版不能用了。
我标题没有表述清楚，我是希望在“快捷键扩展”里增加一个功能，按一下就能跳跃一段时间，这个时间如果不能自己设置的话就设为85秒，这是我长期使用积累的经验，可以适用大部分番剧了，或者您上面这个脚本怎么修改才能适用于新版本呢？或者帮联系一下原作者？我实在不知道怎么搞。感谢。

**Comment by TTTPOB** [comment]
(要不硬编码一个数据库记录各集的oped长度

**Comment by CCCAUCHY** [comment]
不需要啊，85秒足以，不爽自己调




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TPOB"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 晚上8:32
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"CAUCHY"<850726775@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 希望出快捷键增加跳过OPED（90秒）的时间的功能 (#259)




(要不硬编码一个数据库记录各集的oped长度

**Comment by the1812** [comment]
```JavaScript
// ==UserScript==
// @name         Bilibili Jump
// @version      1.0.0
// @description  按J跳跃时间
// @author       Grant Howard
// @license      MIT
// @match        *://*.bilibili.com/*
// @run-at       document-start
// @grant        unsafeWindow
// @icon         https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/images/logo-small.png
// @icon64       https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/images/logo.png
// ==/UserScript==

// 要跳跃的秒数
const jumpTime = 85
const supportedUrls = [
  'https://www.bilibili.com/bangumi/',
  'https://www.bilibili.com/video/',
]
if (supportedUrls.some(url => document.URL.startsWith(url))) {
  document.addEventListener('keydown', e => {
    if (document.activeElement && ['input', 'textarea'].includes(document.activeElement.nodeName.toLowerCase())) {
      return
    }
    if (e.key.toLowerCase() === 'j') {
      document.querySelector('video').currentTime += jumpTime
    }
  })
}
```

**Comment by CCCAUCHY** [comment]
感谢thx




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Grant Howard"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月13日(星期五) 中午11:57
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"CAUCHY"<850726775@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 希望出快捷键增加跳过OPED（90秒）的时间的功能 (#259)



// ==UserScript== // @name         Bilibili Jump // @version      1.0.0 // @description  按J跳跃时间 // @author       Grant Howard // @license      MIT // @match        *://*.bilibili.com/* // @run-at       document-start // @grant        unsafeWindow // @icon         https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/images/logo-small.png // @icon64       https://raw.githubusercontent.com/the1812/Bilibili-Evolved/preview/images/logo.png // ==/UserScript== // 要跳跃的秒数 const jumpTime = 85 const supportedUrls = [   'https://www.bilibili.com/bangumi/',   'https://www.bilibili.com/video/', ] if (supportedUrls.some(url =&gt; document.URL.startsWith(url))) {   document.addEventListener('keydown', e =&gt; {     if (document.activeElement &amp;&amp; ['input', 'textarea'].includes(document.activeElement.nodeName.toLowerCase())) {       return     }     if (e.key.toLowerCase() === 'j') {       document.querySelector('video').currentTime += jumpTime     }   }) }

**Comment by poly000** [comment]
这个功能已经被移除了吗？……
本地设置（番号对应跳跃时间）应该就足够了
一般不会每集都换OPED，而且换的频繁的话也不很需要这个功能……
