### ISSUE TITLE
视频页夜间模式BUG

### ISSUE THREAD

**Issue by regentropfen2013** [the1812/Bilibili-Evolved#2597]
### 关于哪一项功能

无

### 问题描述

https://www.bilibili.com/video/BV1s34y1X74a
![image](https://user-images.githubusercontent.com/62187507/145014458-4db3d1b7-b588-4c5a-a9d0-f6f5e7f7f383.png)

### 脚本版本

Stable v1.12.22 内容包: 5ec2ced

### 浏览器版本

版本 96.0.4664.45（正式版本） （64 位）

### 错误信息

```shell
BV1Dq4y1z7J3:1 Unchecked runtime.lastError: The message port closed before a response was received.
nc-loader-1.4.10.min.js:2 WebSocket connection to 'wss://web-player-tracker.biliapi.net/socket.io/?buvid=56E3E946-B828-4064-8B6D-4C4CB87C567C184981infoc&sdkVersion=1.4.10-1053a7b&aid=592162582&cid=456409820&EIO=4&transport=websocket' failed: 
doOpen @ nc-loader-1.4.10.min.js:2
nc-loader-1.4.10.min.js:2 WebSocket connection to 'wss://web-player-tracker.biliapi.net/socket.io/?buvid=56E3E946-B828-4064-8B6D-4C4CB87C567C184981infoc&sdkVersion=1.4.10-1053a7b&aid=592162582&cid=456409820&EIO=4&transport=websocket' failed: 
doOpen @ nc-loader-1.4.10.min.js:2
nc-loader-1.4.10.min.js:2 WebSocket connection to 'wss://web-player-tracker.biliapi.net/socket.io/?buvid=56E3E946-B828-4064-8B6D-4C4CB87C567C184981infoc&sdkVersion=1.4.10-1053a7b&aid=592162582&cid=456409820&EIO=4&transport=websocket' failed: 
doOpen @ nc-loader-1.4.10.min.js:2
nc-loader-1.4.10.min.js:2 WebSocket connection to 'wss://web-player-tracker.biliapi.net/socket.io/?buvid=56E3E946-B828-4064-8B6D-4C4CB87C567C184981infoc&sdkVersion=1.4.10-1053a7b&aid=592162582&cid=456409820&EIO=4&transport=websocket' failed: 
doOpen @ nc-loader-1.4.10.min.js:2
```

### 附加截图

![image](https://user-images.githubusercontent.com/62187507/145014458-4db3d1b7-b588-4c5a-a9d0-f6f5e7f7f383.png)
![image](https://user-images.githubusercontent.com/62187507/145015023-454757c5-9abc-4e54-b6ee-544f25be810a.png)

**Comment by nk1710210** [comment]
一样的情况

**Comment by 12039-droid** [comment]
+1

**Comment by ZvZvZ** [comment]
我也是

**Comment by the1812** [comment]
后面来的点个赞 别新增回复了

**Comment by bes1355** [comment]
+1 突然出现

**Comment by the1812** [comment]
v2.0.5 版以上, GitHub 更新源的用户可以更新夜间模式组件了, 组件的 Commit Hash 为 `a13ef02f2`

**Comment by the1812** [comment]
目前 v2 修复的是旧版视频界面的夜间, 可以看"记笔记"那一块的界面来分辨
![image](https://user-images.githubusercontent.com/26504152/145313282-fc4b179b-4589-4d7e-b92f-ccce8cb477e4.png)

一部分人可能会收到新版视频界面的灰度, 在这个界面下夜间模式仍然是有问题的, 有关新版视频界面的问题在 #2615 记录. 如果之后有人发现退出这个新版界面的方法我也会再在这里更新.
![image](https://user-images.githubusercontent.com/26504152/145313149-b313c867-45cd-4057-b783-e54aaf19d943.png)
