### ISSUE TITLE
夜间模式突然失效

### ISSUE THREAD

**Issue by Chovypls** [the1812/Bilibili-Evolved#2599]
### 关于哪一项功能

夜间模式

### 问题描述

![image](https://user-images.githubusercontent.com/92515662/145014555-8e0f1ef7-5e8d-4317-a5bb-df964fac3241.png)
如图所示，页面中间部分夜间模式失效，所有视频都是如此

### 脚本版本

Preview v1.12.22 内容包: 3478070

### 浏览器版本

Microsoft Edge 版本 96.0.1054.43 (官方内部版本) (64 位)

### 播放器版本

HTML5播放器 V2.71.0

### 错误信息

```shell
Error handling response: Error: Syntax error, unrecognized expression: .c-container /deep/ .c-container
    at Function.se.error (<URL>)
    at se.tokenize (<URL>)
    at se.select (<URL>)
    at Function.se [as find] (<URL>)
    at S.fn.init.find (<URL>)
    at new S.fn.init (<URL>)
    at S (<URL>)
    at <URL>
```

### 附加截图

![image](https://user-images.githubusercontent.com/92515662/145015330-5a16860d-dcec-4e8c-b186-6f8afe6cc8f9.png)

**Comment by the1812** [comment]
#2597
