### ISSUE TITLE
关于新版播放器的公告

### ISSUE THREAD

**Issue by the1812** [the1812/Bilibili-Evolved#260]
2019年12月9号官方已设定为强制使用新版播放器, 并且我也没有找到什么隐藏入口来返回旧版.
请大家尽快适应新版播放器.

附播放器相关功能:
![new-player](https://user-images.githubusercontent.com/26504152/70450027-f775ab80-1add-11ea-8afb-4a0bd2338adb.jpg)

**Comment by bo-yue** [comment]
在bilibili贴吧[切换旧版播放器的一个方法](https://tieba.baidu.com/p/6384077459)看到使用稍后再看功能启用旧版播放器的方法，不知道是否可以给您提供一点找回旧版播放器接口的参考呢

在回复这条时亲测这个方法是有效的

**Comment by shitianshiwa** [comment]
2019-12-11访问原贴发现被**删贴**，这里接力下。
1、首先需要登陆B站
2、访问：https://www.bilibili.com/watchlater/#/av2
3、点击“添加进稍后再看并播放”

**Comment by the1812** [comment]
有人根据这个做了个脚本: [https://greasyfork.org/zh-CN/scripts/393546-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9bilibili%E6%9B%BF%E6%8D%A2%E6%97%A7%E7%89%88%E6%92%AD%E6%94%BE-%E7%A8%8D%E5%90%8E%E5%86%8D%E7%9C%8B](https://greasyfork.org/zh-CN/scripts/393546-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9bilibili%E6%9B%BF%E6%8D%A2%E6%97%A7%E7%89%88%E6%92%AD%E6%94%BE-%E7%A8%8D%E5%90%8E%E5%86%8D%E7%9C%8B)

**Comment by shitianshiwa** [comment]
> 2019-12-11访问原贴发现被**删贴**，这里接力下。
> 1、首先需要登陆B站
> 2、访问：https://www.bilibili.com/watchlater/#/av2
> 3、点击“添加进稍后再看并播放”

经测试，该方法已经失效了。
