### ISSUE TITLE
播放页面夜间模式失效

### ISSUE THREAD

**Issue by shlouissh** [the1812/Bilibili-Evolved#2600]
### 关于哪一项功能

夜间模式

### 问题描述

2021.12.7 18:00后，所有视频播放页面的夜间模式局部（大部分）失效

### 脚本版本

v1.12.22

### 浏览器版本

chrome 96.0.4664.93

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/36627217/145015769-804d4824-6f11-4f1f-b056-12a48d6e98e1.png)
![image](https://user-images.githubusercontent.com/36627217/145015929-bf296eb0-8361-4c96-a83d-b96b12fb664d.png)

**Comment by canyinga** [comment]
同

**Comment by the1812** [comment]
见 #2597
