### ISSUE TITLE
关于V2.0粉丝牌的一个建议

### ISSUE THREAD

**Issue by RYX-3212103383** [the1812/Bilibili-Evolved#2604]
### 关于哪一项功能

粉丝牌子显示问题

### 问题描述

在 功能-更换勋章 页面勋章显示不完整
勋章超过7个就会有显示不全的问题，超过14个勋章如果全显示于容器内会不太美观，

### 脚本版本

v2.0.5-preview

### 浏览器版本

Edge 96.0.1054.43

### 错误信息

```shell
没有错误信息
```

### 附加截图

![image](https://user-images.githubusercontent.com/55491921/145053701-0df8ba1d-b183-4f49-a935-3df08cabe4fd.png)
直接改边距后
![image](https://user-images.githubusercontent.com/55491921/145055609-36862626-35f9-4c7b-b0db-9ca6b917d2ee.png)
建议粉丝牌grid的层级高于padding一级

**Comment by ZiSaAcZ7** [comment]
+1，我也想说这个问题捏

**Comment by the1812** [comment]
v1 风格面板下这应该是朝下的而不是朝右, 属于 bug 了
