### ISSUE TITLE
夜间模式问题发现

### ISSUE THREAD

**Issue by KesaubeEire** [the1812/Bilibili-Evolved#2609]
### 关于哪一项功能

夜间模式 css 颜色不对

### 问题描述

预览版 v2.0.6 的夜间模式没有修复, 至少在我这里
我发现夜间模式颜色问题就是一个小小的 css `background: #fff;` 的问题
![image](https://user-images.githubusercontent.com/20382002/145158275-85a2faec-3c1d-482d-8429-12e230f820ba.png)

![image](https://user-images.githubusercontent.com/20382002/145158222-da63c4ea-8b87-413a-bad9-96a9932e8f59.png)

![image](https://user-images.githubusercontent.com/20382002/145157469-0ce6fc65-40de-475a-b0c8-447aa90364b5.png)
建议在那个相应的 css 类里搞一个 `background: transparent !important;` 直接搞定, 我在浏览器里加上就搞定了
最新版的预览版 2.0.6 依然没有解决这个问题 

### 脚本版本

preview 2.0.6

### 浏览器版本

版本 96.0.4664.55（正式版本） (x86_64)

### 错误信息

```shell
...
```

**Comment by SekiBetu** [comment]
已经修复了，更新下脚本和夜间模式的插件

**Comment by the1812** [comment]
再更新下, 组件和脚本是独立更新的 (其实 v2.0.5 也能装上最新的夜间模式

**Comment by Lz1y** [comment]
> 

装了2.0.6了，夜间模式插件也反复卸载安装，但是还是存在这个bug（

**Comment by Lz1y** [comment]
哦知道了，通用设置 -> 开发者模式 -> 更换插件源成GitHub，我一直以为脚本用Github装得，源就是Github（
