### ISSUE TITLE
自定义顶栏的两个问题

### ISSUE THREAD

**Issue by SekiBetu** [the1812/Bilibili-Evolved#2610]
### 关于哪一项功能

自定义顶栏

### 问题描述

一、有两个图标超出了自定义顶栏主页的界面
二、自定义顶栏主页中的番剧的超链接已经更新为 `https://www.bilibili.com/anime/` 而不是 `https://www.bilibili.com/v/anime/`

### 脚本版本

v2.0.6-preview-2-ga13ef02f2

### 浏览器版本

Chrome 96.0.4664.93

### 错误信息

```shell
不需要
```

### 附加截图

![image](https://user-images.githubusercontent.com/38283893/145159067-02658870-4c2e-44a3-9df8-52be2c9cb75e.png)
![image](https://user-images.githubusercontent.com/38283893/145159351-b8074472-6a23-4d8e-9033-c2b43f907b4a.png)

**Comment by Geeyun-JY3** [comment]
1. 关联：https://github.com/the1812/Bilibili-Evolved/discussions/2586#discussioncomment-1752838

**Comment by 2314933036** [comment]
1.顺便建议把旧版的"订阅"也放进来,表示已经用习惯了
2.自动刷新消息感觉没效果

**Comment by Geeyun-JY3** [comment]
@2314933036 请先善用搜索：#2472、#2689、#2712
如果更新相关组件后还是没用，建议补充更多信息单独开 issue。
