### ISSUE TITLE
v2的js插件合集或单个功能的插件在哪里，找了半天没找到

### ISSUE THREAD

**Issue by selfdialog** [the1812/Bilibili-Evolved#2612]
### 关于哪一项功能

v2的js插件合集或单个功能的插件

### 问题描述

v2的js插件合集或单个功能的插件

### 脚本版本

V2

### 浏览器版本

98.0.4750.0

### 错误信息

```shell
v2的js插件合集或单个功能的插件
```

**Comment by Geeyun-JY3** [comment]
看到你在 https://github.com/the1812/Bilibili-Evolved/discussions/2607#discussioncomment-1770961 问了……
这事等不急开 discussion 就行，你还真不嫌开 issue 麻烦啊……下次在一个地方问耐心等待就好

@the1812 README 好像确实没给出直接入口……

单功能: https://github.com/the1812/Bilibili-Evolved/blob/preview/doc/features/features.md
合集包: https://github.com/the1812/Bilibili-Evolved/blob/preview/doc/features/pack/pack.md

点击设置面板左下角组件或插件，点击 `🌐 在线` 出来的面板头几个结果应该是合集包的啊……

**Comment by selfdialog** [comment]
> 看到你在 [#2607 (reply in thread)](https://github.com/the1812/Bilibili-Evolved/discussions/2607#discussioncomment-1770961) 问了…… 这事等不急开 discussion 就行，你还真不嫌开 issue 麻烦啊……下次在一个地方问耐心等待就好
> 
> 单功能: https://github.com/the1812/Bilibili-Evolved/blob/preview/doc/features/features.md 合集包: https://github.com/the1812/Bilibili-Evolved/blob/preview/doc/features/pack/pack.md
> 
> 点击设置面板左下角组件或插件，点击 `🌐 在线` 出来的面板头几个结果应该是合集包的啊……
> 
> @the1812 不过 README 好像确实没给出直接入口……

![image](https://user-images.githubusercontent.com/30248712/145181405-c2152dd0-c212-413f-a767-a15a7f6ae570.png)

获取在线仓库数据失败, 请尝试在通用设置中设置其他更新源, 然后再试一次

**Comment by Geeyun-JY3** [comment]
> 获取在线仓库数据失败, 请尝试在通用设置中设置其他更新源, 然后再试一次

我这边也碰到了相同情况。建议直接用直链安装

**Comment by the1812** [comment]
你们都是 Tampermonkey beta 吗?

**Comment by Geeyun-JY3** [comment]
确实。我这边是 v4.14.6148

**Comment by the1812** [comment]
v4.14.6147 ~ 6148 有 bug, 建议先用非 beta 版
https://github.com/Tampermonkey/tampermonkey/issues/1381

**Comment by Geeyun-JY3** [comment]
哦对我把 #2560 给忘了
