### ISSUE TITLE
关于分区的问题

### ISSUE THREAD

**Issue by xiaole3349** [the1812/Bilibili-Evolved#262]
**关于哪一项功能**

希望分区可以提供一个删除分区的按钮，有些分区是真的不太常用，让他放着真的太占地方了。
**期望的效果**
在设置中可以直接修改或者点击排序之后分区选项可以多一个删除按钮。

**脚本版本**

预览版

**Comment by the1812** [comment]
可以先试试`简化首页`, 分区那比较省地方. (不过有几个特殊分区还没做完)
