### ISSUE TITLE
视频页改版

### ISSUE THREAD

**Issue by JDYuuki** [the1812/Bilibili-Evolved#2621]
### 关于哪一项功能

播放器置顶、快速收藏等

### 问题描述

全视频页，包括游戏区、科技区、数码区等

目前发现播放器置顶、快速收藏失效

看了第一页的 issus，好像还没报过这个问题（可能我瞎了（逃）

### 脚本版本

Stable v1.12.22

### 浏览器版本

Edge with Chromium 96.0.1054.43

### 播放器版本

2.71.1-5d8ba34f

### 是否开启 HEVC

优先 HEVC

### 错误信息

```shell
-
```

### 附加截图

![image](https://user-images.githubusercontent.com/28827378/145232800-165a6774-b4c9-4ea8-9ef3-13e2aa89991e.png)

**Comment by the1812** [comment]
都在 #2615 反馈吧
