### ISSUE TITLE
夜间模式依旧有 bug

### ISSUE THREAD

**Issue by Y65NG** [the1812/Bilibili-Evolved#2622]
### 关于哪一项功能

夜间模式

### 问题描述

视频播放页的简介和标签颜色显示不正常

### 脚本版本

v2.0.6-preview-2-ga13ef02f2

### 浏览器版本

96.0.4664.55

### 播放器版本

2.71.1-5d8ba34f

### 是否开启 HEVC

优先 HEVC

### 错误信息

```shell
Unchecked runtime.lastError: The message port closed before a response was received.
```

### 附加截图

![image](https://user-images.githubusercontent.com/74285192/145309055-d0b940bd-c565-43e4-9a70-084e43426735.png)

**Comment by the1812** [comment]
你这个是灰度到新版播放页面了, 统一在 #2615 反馈吧
