### ISSUE TITLE
添加去除跳转时网址参数(?大概)功能的

### ISSUE THREAD

**Issue by bo-yue** [the1812/Bilibili-Evolved#263]
**关于哪一项功能**

去除左键点击某个视频时新打开页面网址栏后面的?spm_id_from=333.************.*这一长串东西
类似的还有?from=search&seid=***********等等这种参数（？大概），美化地址栏

**期望的效果**
本来点击一个视频坐下角显示的是正常的非常干净的链接，如https://www.bilibili.com/video/av78537651
![1](https://user-images.githubusercontent.com/56006608/70497076-dbf5b980-1b4c-11ea-8e6e-84f180fdfa4d.png)

左键点击进入打开视频页网址栏的链接就变成了https://www.bilibili.com/video/av78537651?spm_id_from=333.851.b_7265706f7274466972737431.7
![2](https://user-images.githubusercontent.com/56006608/70497152-2c6d1700-1b4d-11ea-9721-5497f607aa25.png)

看着就很脏，我目前的解决方法是所有能用在bilibili所有能用左键跳转的地方用右键打开，这样就需要两步——右键菜单——在新标签页打开，这样地址栏就很干净很舒服
![3](https://user-images.githubusercontent.com/56006608/70497422-098f3280-1b4e-11ea-914f-b94d2ed4caf3.png)

但是就很烦！！！而且有些东西右键也解决不了……

您的这个脚本提供了这么多布局、去除广告等美化功能，希望也可以关注一下地址栏这种地方，添加一个去除这些参数(？大概是叫参数吧)的功能，还强迫症一个干净整洁的界面。
我整理了一下大概有这些

1.大部分页面跳往其他页面的?spm_id_from=333.851.b_7265706f7274466972737431.7（都是以spm_id_from=333开头的）
2.搜索页面的from_source=banner_search以及搜索页跳往视频播放页的?from=search&seid=3665278186567389140（这种最难受，右键都无效，还得复制链接手动截取干净）
3.播放器下面tag链接后面的from_source=video_tag（这种同上不过很少用到）

PS:猜想这些东西大概是bilibili为了统计数据什么的用的，也许不该去掉，去掉就等于没有通过推荐、搜索等方式直接就打开了页面，但也没规定不能去掉吧（！直播站的?visit_id=********和?room_id=*******这种是真的不能去掉，这个去掉了容易被封号！）
曾经试过用chrome商店的[uMatrix](https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf)这个扩展禁用了bilibili主页的部分请求，发现
![4](https://user-images.githubusercontent.com/56006608/70498536-ae5f3f00-1b51-11ea-9cb4-c7acb6f1967e.png)
（脚本，www.bilibili.com）只需禁用（标红）这个就可以暴力实现期望的效果——左键点击打开的是干净链接，不过代价是主页除了推荐、推广以外包括分区、个人信息等全部消失，干净是真的干净，就是太干净了，而且没有个人数据所以也不能长久只好请求您了

**脚本版本**

正式版1.9.19

**Comment by the1812** [comment]
在网页加载完成时清理当前网页的网址, 可以接受吗? (包括历史记录里也会留下清理后的网址)
如果事先探测网页里所有链接会比较影响性能

**Comment by HashLiver** [comment]
处理网址跟踪参数用上uMatrix这种极客扩展也算是大炮打蚊子了，推荐用 [Redirector](https://chrome.google.com/webstore/detail/redirector/ocgpenflpmgnfapjedencafcfakcekcd) （也是开源的）解决，如下图所示，好处在于不限于用在B站

![vadavadico](https://user-images.githubusercontent.com/42889797/71459287-b40b8480-27e1-11ea-85b3-83e12991a4f6.png)
