### ISSUE TITLE
新版界面显示问题

### ISSUE THREAD

**Issue by shang-he** [the1812/Bilibili-Evolved#264]
**关于哪一项功能**

**问题描述**
进入消息中心之后消息显示气泡背景颜色对比不容易看清文字

**脚本版本**
1.9.19

**浏览器版本**

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/40030698/70524971-41fc3400-1b81-11ea-8e5d-ee39656462f8.png)

**Comment by Coulomb-G** [comment]
收到,现已修复
