### ISSUE TITLE
夜间模式，标题，简介等无法自动转色

### ISSUE THREAD

**Issue by liyuhaolol** [the1812/Bilibili-Evolved#2643]
### 关于哪一项功能

夜间模式

### 问题描述

夜间模式，标题，简介等无法自动转色

### 脚本版本

v2.0.7-10-gd85b75b43

### 浏览器版本

 96.0.1054.43

### 错误信息

```shell
无
```

### 附加截图

![1111](https://user-images.githubusercontent.com/16422963/145664805-3eac35b3-4438-4199-ba9d-07d81a0d49b2.png)

**Comment by Geeyun-JY3** [comment]
看置顶，新版播放页问题统一到：#2615
