### ISSUE TITLE
在線倉庫用不了

### ISSUE THREAD

**Issue by marco8885200** [the1812/Bilibili-Evolved#2650]
### 关于哪一项功能

在線倉庫

### 问题描述

顯示獲取數据失敗，已試过切換更新源和刷新网頁都沒用

### 脚本版本

v2.0.7-10-gd85b75b43

### 浏览器版本

edge 96.0.1054.53

### 错误信息

```shell
获取在线仓库数据失败, 请尝试在通用设置中设置其他更新源, 然后再试一次
```

### 附加截图

![image](https://user-images.githubusercontent.com/71377350/145673626-2178b222-4bd9-44d5-9d3a-f0f7c82ffb22.png)

**Comment by jh13champion** [comment]
我也是这样

**Comment by Geeyun-JY3** [comment]
用的是不是 Tampermonkey Beta：https://github.com/the1812/Bilibili-Evolved/issues/2612#issuecomment-988762308 、#2614、#2664
