### ISSUE TITLE
为什么2.0.7的包下载以后，安装的版本号最高是2.0.6

### ISSUE THREAD

**Issue by 694185819** [the1812/Bilibili-Evolved#2655]
### 关于哪一项功能

版本号是不是忘了改了

### 问题描述

为什么2.0.7的包下载以后，安装的版本号最高是2.0.6

### 脚本版本

2.0.7

### 浏览器版本

V2.71.0

### 错误信息

```shell
.
```

**Comment by the1812** [comment]
你是哪下的

**Comment by 694185819** [comment]
> 你是哪下的

可不就在这里下的，下完用Tampermonkey导入压缩包，版本号最高就看见206，不是207
![QQ截图20211212112743](https://user-images.githubusercontent.com/51364259/145699084-cd1eba6b-bdb0-4394-a56c-cdddade95c32.png)
图片就是207包解压之后的样子，206已经是版本号最高，不是近期的207

**Comment by the1812** [comment]
首页 README 才是下载链接, zip 包是错误的

**Comment by Geeyun-JY3** [comment]
最近怎么这么多在 Release 下 zip 压缩包然后导入安装的。

我建议得在 Release 提一下了。
