### ISSUE TITLE
脚本无法安装和使用

### ISSUE THREAD

**Issue by LIPiston** [the1812/Bilibili-Evolved#2656]
### 关于哪一项功能

安装脚本

### 问题描述

__无法安装至油猴__

使用类油猴工具 CSDN助手 时可安装

__但不可安装任何组件__

卡在获取中

### 脚本版本

2.0.7

### 浏览器版本

edge v96.0.1054.53 (官方内部版本) (64 位)

### 播放器版本

2.71.2

### 错误信息

```shell
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/international-home/1.international-home.df6122dfa34a6a03c793b99bea5c9b02ac09998f.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_F
```

### 附加截图

![image](https://user-images.githubusercontent.com/75552696/145679976-4f73eb02-35e4-45d1-a83b-c84dddd04a1f.png)

**Comment by the1812** [comment]
你是怎么往油猴装的? 组件的装法也不对, 这里要粘贴的是链接不是代码

**Comment by LIPiston** [comment]
点链接弹出油猴的界面点安装  
__之后就没见到在管理界面__

粘贴链接吗原来,wssb
