### ISSUE TITLE
[Bug Report] Firefox顶栏颜色不生效

### ISSUE THREAD

**Issue by TTTPOB** [the1812/Bilibili-Evolved#266]
**关于哪一项功能**

关于 设置 - 样式 - 自定义顶栏 - 主题色填充

**问题描述**

将上述主题色填充开关打开，未见效果；
于b站所有页面都能出现这个问题，而在chrome内核浏览器中不会

**脚本版本**

预览离线版

**浏览器版本**

Firefox nightly 73.0a1

**错误信息**

无

**附加截图**
![图片](https://user-images.githubusercontent.com/19909103/70530432-cf458580-1b8d-11ea-8dd9-ec3600351d82.png)
上图为firefox情况
![图片](https://user-images.githubusercontent.com/19909103/70530458-df5d6500-1b8d-11ea-8e1c-c82891b744b3.png)
上图为edge chromium情况，二者采用相同设置和相同版本的脚本

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/70769928-5bca9080-1da6-11ea-97ed-37cb8f24317d.png)
![image](https://user-images.githubusercontent.com/26504152/70769951-71d85100-1da6-11ea-88c4-75391c7f857a.png)
我这里是正常的, 可否看看开发者工具(顶栏上右键查看元素)里的`class`有没有包含`fill`? 或者控制台一栏中有没有包含错误信息?

**Comment by TTTPOB** [comment]
???我一两周之前到昨天一直这样，提完issue就好了？？？
