### ISSUE TITLE
首页番剧按钮独立在外面

### ISSUE THREAD

**Issue by xcing937** [the1812/Bilibili-Evolved#2665]
### 关于哪一项功能

首页简化

### 问题描述

首页番剧按钮独立在外面
![image](https://user-images.githubusercontent.com/80184406/145698567-b7f11b1b-32aa-4616-8bd8-bf31788686d5.png)

### 脚本版本

2.0.7

### 浏览器版本

 96.0.1054.34 (官方内部版本) (64 位)

### 播放器版本

我这边看不到哎，应该是最新的吧

### 是否开启 HEVC

优先 HEVC

### 错误信息

```shell
没有错误，布局问题
```

### 附加截图

![屏幕截图 2021-12-12 110501](https://user-images.githubusercontent.com/80184406/145698631-c42c1e28-b09e-4144-abd3-e8026b2f7873.png)

**Comment by Geeyun-JY3** [comment]
自定义顶栏的布局设置里调不了吗？

**Comment by xcing937** [comment]
忘了可以调了，不过v1没转过来的时候也没在外面。。。已经调整好了


| |
xecvz3
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年12月12日 ***@***.***> 写道：

自定义顶栏的布局设置里调不了吗？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
