### ISSUE TITLE
设置脚本菜单置于右边时。当鼠标移到屏幕左边尽头，两个菜单按钮从右边浮出

### ISSUE THREAD

**Issue by nonmoneyguy** [the1812/Bilibili-Evolved#2667]
### 关于哪一项功能

菜单按钮

### 问题描述

安装好后，首先设置脚本菜单置于右边时。当鼠标移到屏幕左边尽头，两个菜单按钮从右边出来。
Chrome版本 96.0.4664.93，Tampermonkey v4.13

### 脚本版本

2.0.7

### 浏览器版本

96.0.4664.93

### 错误信息

```shell
无
```

### 附加截图

![Uploading 屏幕截图 2021-12-12 114541.png…]()

**Comment by Geeyun-JY3** [comment]
你图没传上来……

**Comment by Geeyun-JY3** [comment]
你图没传上来……

**Comment by Geeyun-JY3** [comment]
你图没传上来……

**Comment by the1812** [comment]
已经复现了, 没图也行
