### ISSUE TITLE
报告BUG，部分页面无法播放

### ISSUE THREAD

**Issue by CCCAUCHY** [the1812/Bilibili-Evolved#267]
https://www.bilibili.com/bangumi/play/ep299985?spm_id_from=333.334.b_63686965665f7265636f6d6d656e64.1
百分百复现，可能其他页面也存在问题

**Comment by Coulomb-G** [comment]
我这边正常播放,请在关掉其他脚本/插件后,再打开该页面,如果还是无法播放,请提交控制台报错信息,浏览器版本以及脚本版本等相关信息

**Comment by the1812** [comment]
![play](https://user-images.githubusercontent.com/26504152/70699220-bf4fb200-1d03-11ea-9780-622916cc9d1f.jpg)
