### ISSUE TITLE
新版网页播放页后出现的问题

### ISSUE THREAD

**Issue by Prodution** [the1812/Bilibili-Evolved#2670]
### 关于哪一项功能

简化评论区，自定义顶栏

### 问题描述

新版网页播放页评论区回复别人会出现表情包卡在旁边推荐视频里，

### 脚本版本

v2.0.7-10-gd85b75b43

### 浏览器版本

版本 96.0.1054.53 (官方内部版本)

### 错误信息

```shell
不清楚，抱歉了
```

### 附加截图

![3453](https://user-images.githubusercontent.com/73606434/145700831-b2571031-4cea-4faa-8e61-41f760639b53.jpg)
![1](https://user-images.githubusercontent.com/73606434/145700455-0ad389bd-7fa7-4f0e-a4a5-64d9b12d54da.jpg)

**Comment by Geeyun-JY3** [comment]
还是新版视频页的适配问题：#2615

**Comment by Prodution** [comment]
换回旧版网页端播放页后就不会出现这些情况

**Comment by Geeyun-JY3** [comment]
> 换回旧版网页端播放页后就不会出现这些情况

正常，因为还在适配
