### ISSUE TITLE
设置栏正常，功能栏“空空如也”，没办法下载视频

### ISSUE THREAD

**Issue by reiamkira** [the1812/Bilibili-Evolved#2673]
### 关于哪一项功能

下载视频

### 问题描述

chrome

### 脚本版本

2.0.7

### 浏览器版本

chrome

### 错误信息

```shell
？
```

**Comment by chicotzz** [comment]
same here

**Comment by the1812** [comment]
装了下载视频没

**Comment by reiamkira** [comment]
没有装 直接安的脚本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 中午1:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 设置栏正常，功能栏“空空如也”，没办法下载视频 (Issue #2673)





 
装了下载视频没
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by the1812** [comment]
脚本默认不预装任何功能了, 去[主页](https://github.com/the1812/Bilibili-Evolved)学学使用方法吧

**Comment by nanbobike** [comment]
相同问题
1.已经安装
![image](https://user-images.githubusercontent.com/59313112/169687476-fa31e229-75c8-4546-ab5d-cd5a24c3c0de.png)

![image](https://user-images.githubusercontent.com/59313112/169687495-98c72fa1-0a82-4e2c-99f4-734db8e8363a.png)
![image](https://user-images.githubusercontent.com/59313112/169687504-27d12e8c-e308-4061-a466-798dfa7584fb.png)
2.但还是空的
![image](https://user-images.githubusercontent.com/59313112/169687552-2ba61f66-c964-4b80-8673-62c35c0dbae1.png)

![image](https://user-images.githubusercontent.com/59313112/169687545-3ebf491b-3f0e-43ed-921d-a171a25077be.png)
