### ISSUE TITLE
在通用设置把按钮设置为停靠右侧后, 然后刷新网站设置按钮的入口就消失了

### ISSUE THREAD

**Issue by FairyWorld** [the1812/Bilibili-Evolved#2674]
### 关于哪一项功能

通用设置, 设置按钮的停靠位置

### 问题描述

在通用设置把按钮设置为停靠右侧后, 然后刷新网站设置按钮的入口就消失了。
我尝试卸载脚本重新安装，也无法显示出设置按钮，已设置过的功能是正常运行的，只是整个设置入口不见了

### 脚本版本

2.0.7

### 浏览器版本

Chromium 86.0.4240.198

### 错误信息

```shell
无错误信息
```

**Comment by Geeyun-JY3** [comment]
那就是重复了：#2647
