### ISSUE TITLE
简化评论区功能bug反馈-表情栏被遮挡

### ISSUE THREAD

**Issue by Qm-jmz** [the1812/Bilibili-Evolved#2679]
### 关于哪一项功能

简化评论区

### 问题描述

在评论区出现问题，我想发表新评论（带表情），但简化评论区功能改变了表情按钮的位置，导致弹出的表情列表与网页右侧的接下来再看栏目下方的视频封面图片重叠并被遮挡。如果关闭此功能，表情列表可正常显示。

一开始插件的其他功能并没有关闭（我怀疑是不是功能之间产生了冲突），后续我关闭了所有其他的功能，只保留简化评论区，但问题依然存在。并且我确定我只开了bilibili-evolved这一个插件。

我在两个视频下面进行了测试，出现了同样的问题。
我在两个浏览器（chrome/firefox）上进行了测试，出现了同样的问题。

### 脚本版本

v2.0.7-10-gd85b75b43

### 浏览器版本

chrome 版本 96.0.4664.93（正式版本） （64 位）

### 播放器版本

非播放器问题

### 错误信息

```shell
无直接报告
```

### 附加截图

![image](https://user-images.githubusercontent.com/50917637/145706163-97ca29f5-f377-475f-b6fa-cc06cbb2fe03.png)
![image](https://user-images.githubusercontent.com/50917637/145706447-8737db0f-8ade-45a1-a190-d520a19d620d.png)
![image](https://user-images.githubusercontent.com/50917637/145706479-6bc619c5-518e-4ae2-bc39-e0cf70922ec3.png)

**Comment by Geeyun-JY3** [comment]
重复：#2679

新版视频页还在适配：#2615

**Comment by the1812** [comment]
> 重复：#2679

@Geeyun-JY3 原地 TP 了(

**Comment by Geeyun-JY3** [comment]
> 原地 TP 了(

复制多了就粘贴错了（
应该是：#2670
