### ISSUE TITLE
稍后再看打开视频后有错误

### ISSUE THREAD

**Issue by MonK1949** [the1812/Bilibili-Evolved#2683]
### 关于哪一项功能

稍后再看

### 问题描述

稍后再看打开视频后会进入打开稍后再看列表的页面，且列表在不断正在加载

### 脚本版本

v2.0.7-10-gd85b75b43

### 浏览器版本

96.0.1054.43

### 错误信息

```shell
无
```

### 附加截图

![0000000000000000000000000000000000000000](https://user-images.githubusercontent.com/56068740/145711267-ec696a4d-77da-4b43-8fda-b6d9fc35e0df.JPG)

**Comment by MonK1949** [comment]
旧版本只是打开普通视频页面，那样比较好。

**Comment by Geeyun-JY3** [comment]
`稍后再看重定向` 开了没有

**Comment by MonK1949** [comment]
感谢！已解决！刚更新需要自己添加插件还有点不太习惯。麻烦维护者了！


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月12日 20:16:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [the1812/Bilibili-Evolved] 稍后再看打开视频后有错误 (Issue #2683)




 
稍后再看重定向 开了没有
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 921j** [comment]
因为不是反馈bug所以借楼说话
首先感谢开发者 @the1812  这么棒的脚本！
其次提个小小的建议：希望开发者大佬在维护之余考虑添加一个能在B站Up主的 个人页面-投稿 页面中添加一个 “一键添加本页所有视频到稍后再看” 的功能，最好是右下角的视频到左上角的排序，这样方便按序补视频，每页次都要点30多次实在太累了，我在 GreasyFork 上找到了这个脚本 https://greasyfork.org/zh-CN/scripts/393440-b%E7%AB%99-%E6%92%AD%E6%94%BE%E5%85%A8%E9%83%A8-%E7%A8%8D%E5%90%8E%E7%9C%8B%E5%A2%9E%E5%BC%BA?locale_override=9%27A%3D0 但貌似太旧了现在不能准确添加，而且作者貌似没有继续维护打算，除此之外没有其他的类似的脚本了，https://greasyfork.org/zh-CN/scripts/395456-b%E7%AB%99%E7%A8%8D%E5%90%8E%E5%86%8D%E7%9C%8B%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA?locale_override=9%27A%3D0 这个脚本的自动移除 “已观看视频” 的功能也很好，但它的批量添加功能太诡异，我只想要这两个功能，可惜我不会写脚本……

**Comment by Geeyun-JY3** [comment]
@921j 别什么借楼不借楼的，有功能需求就应该去单独开个 discussion。
