### ISSUE TITLE
直播间、专栏无法使用查看封面功能

### ISSUE THREAD

**Issue by yuijker** [the1812/Bilibili-Evolved#2688]
### 关于哪一项功能

查看封面

### 问题描述

在v1.12.22时，查看封面功能可用于直播间、专栏、视频等地方。
而在v2.0.7时，我翻找了很久，可是只看到查看封面在视频中生效，直播间、专栏没有这一功能。

### 脚本版本

v2.0.7-10-gd85b75b43

### 浏览器版本

edge 96.0.1054.53

### 播放器版本

/

### 错误信息

```shell
/
```

### 附加截图

![screenshot-live bilibili com-2021 12 12-22_19_54](https://user-images.githubusercontent.com/72558803/145716676-b2bfa004-779c-4187-bfb8-c403be25e958.jpg)

![屏幕截图 2021-12-12 223507](https://user-images.githubusercontent.com/72558803/145716677-56cf99a6-7733-421f-bc6c-05d300943db1.png)

![屏幕截图 2021-12-12 223732](https://user-images.githubusercontent.com/72558803/145716756-e761369b-ab5c-446c-8f30-893180fc95e6.png)

![屏幕截图 2021-12-12 223908](https://user-images.githubusercontent.com/72558803/145716813-24094254-1e05-4168-a3ed-fb03e2a68d2e.png)

**Comment by the1812** [comment]
- 直播间因为改版, 早就失效了 (包括 v1)
- 专栏早就没了, 新版专栏根本没有头图, 文章内的图可以用专栏图片导出来下载
