### ISSUE TITLE
自定义顶栏刷新策略问题

### ISSUE THREAD

**Issue by AQ-Official** [the1812/Bilibili-Evolved#2689]
### 关于哪一项功能

自定义顶栏刷新策略问题

### 问题描述

之前v1的时候反馈过，就是自定义顶栏每次鼠标移入不会自动刷新，v1后期改掉了，目前v2有这个问题。

比如我在其他端添加了一个视频到稍后再看，再去顶栏看的时候，不会刷新，必须得刷新页面才能看到新添加的视频。

### 脚本版本

v2.0.7-12-g259797c28

### 浏览器版本

版本 96.0.4664.55（正式版本） (arm64)

### 错误信息

```shell
nope跟这个应该没关系
```

**Comment by StqGo** [comment]
蹲一个更新

**Comment by 921j** [comment]
同样有这个问题
还有 默认播放器模式 这个插件，第一次打开视频不会生效，刷新或再次打开才可以。

**Comment by 83992713** [comment]
2.0.8稍后再看无法外置。
