### ISSUE TITLE
希望增加一个能批量下载一个UP主所有视频的功能

### ISSUE THREAD

**Issue by snowingwang** [the1812/Bilibili-Evolved#269]
希望能在其他用户的用户页增加一个下载其所有视频的批量下载功能，因为担心有的UP主可能会被BAN，整理视频也会方便一些。并没有找到类似功能的脚本。

**Comment by the1812** [comment]
所有视频的话太多了, 导出来的下载链接是有时间限制的, 建议还是逐个下载

**Comment by snowingwang** [comment]
能否提供一个视频网址批量转换Aria2下载文件的功能？类似于弹出一个文本框，在文本框中输入一堆视频的网址，能直接生成Aria2可以下载的链接文件。
如果有类似功能的话我就能慢慢把一些UP的视频全部备份到本地了，因为现在的批量下载功能太依赖合集。
顺便祝大佬新年快乐。

**Comment by the1812** [comment]
年后我会试试的, 新年快乐

**Comment by the1812** [comment]
做的差不多了, 还剩一个清晰度的问题, 不是所有视频都有当前选择的清晰度, 默认貌似会降到1080P, 如果你可以接受的话下次更新就会上这个功能

**Comment by snowingwang** [comment]
> 做的差不多了, 还剩一个清晰度的问题, 不是所有视频都有当前选择的清晰度, 默认貌似会降到1080P, 如果你可以接受的话下次更新就会上这个功能

可以接受的 辛苦大佬了
