### ISSUE TITLE
顶栏适配问题

### ISSUE THREAD

**Issue by 0x00Finch** [the1812/Bilibili-Evolved#2694]
### 关于哪一项功能

自定义顶栏

### 脚本版本

v2.0.7-12-g259797c28

### 浏览器版本

firefox 95.0

### 错误信息

```shell
N/A
```

### 附加截图

![adfhgdaghad](https://user-images.githubusercontent.com/26269474/145734797-45c1604a-52da-49e9-9c98-7ea891ebce46.png)

**Comment by the1812** [comment]
你是开了隐藏横幅?

**Comment by 0x00Finch** [comment]
> 你是开了隐藏横幅?

开了，但是我们可不可以让下拉菜单往下开呢？不要往上开

**Comment by the1812** [comment]
不能, 但你可以直接从顶栏的主站里进入音乐的子分区

**Comment by 0x00Finch** [comment]
> 不能, 但你可以直接从顶栏的主站里进入音乐的子分区

能不能加一些弹性空白呢？在横幅的位置

**Comment by the1812** [comment]
弹性空白只有顶栏有, 横幅是首页的区域, 只能加固定的空白 (自然也不美观
