### ISSUE TITLE
可否兼容或制作类似bilibili-simple-new-home的效果

### ISSUE THREAD

**Issue by Wcraft233** [the1812/Bilibili-Evolved#270]
**关于哪一项功能**

简化首页和顶栏自定义
**期望的效果**
可以与[bilibili-simple-new-home
](https://github.com/kkd20/bilibili-simple-new-home)脚本联动运作来实现首页第一屏为搜索框，向下拉可以看到热门视频和动态。
同时由于bilibili-simple-new-home的顶栏仅在首页作用，所以我希望能在非首页的位置使用本脚本的自定义顶栏功能。

以下信息中bilibili-simple-new-home的配置如下
![image](https://user-images.githubusercontent.com/30252123/70864258-62fec380-1f8b-11ea-8aea-92cc7ab9f191.png)
其中，背景是我自定义的

目前版本的顶栏自定义和简化首页的功能与bilibili-simple-new-home有所冲突，具体表现为：
原版（仅开启bilibili-simple-new-home）：
![image](https://user-images.githubusercontent.com/30252123/70864313-cbe63b80-1f8b-11ea-9818-229ad676f3ba.png)
![image](https://user-images.githubusercontent.com/30252123/70864416-942bc380-1f8c-11ea-9349-81878c40b433.png)

与“简化主页”同时使用：首页的顶栏头像 消息 动态 收藏 历史 创作中心按钮消失
![image](https://user-images.githubusercontent.com/30252123/70864349-f7692600-1f8b-11ea-90b6-054f25b5ec9d.png)

与“自定义顶栏”同时使用：Logo 搜索栏消失（被自定义顶栏覆盖）
![image](https://user-images.githubusercontent.com/30252123/70864362-12d43100-1f8c-11ea-9c34-9c5db6486fb2.png)

**脚本版本**

正式版

**Comment by the1812** [comment]
已增加对此样式的特别兼容, 在浏览器控制台(<kbd>Ctrl + Shift + I</kbd>)中粘贴运行:
```js
bilibiliEvolved.settings.bilibiliSimpleNewHomeCompatible = true
```

**Comment by yorokami** [comment]
昨天晚上才看见邮件，已经成功了兼容了。谢谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Grant Howard"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月25日(星期一) 上午9:54
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"腾简"<yorokami@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 可否兼容或制作类似bilibili-simple-new-home的效果 (#270)





 
已增加对此样式的特别兼容, 在浏览器控制台(Ctrl + Shift + I)中粘贴运行:
 bilibiliEvolved.settings.bilibiliSimpleNewHomeCompatible = true
 
@yorokami @once-bastion
