### ISSUE TITLE
自定义顶栏的背景模糊功能会导致弹幕变卡

### ISSUE THREAD

**Issue by zwj2333** [the1812/Bilibili-Evolved#2700]
### 关于哪一项功能

自定义顶栏

### 问题描述

在打开自定义顶栏的背景模糊功能后，观看视频时，滚动弹幕会变的很卡，甚至有残影。怀疑是刷新率的影响。

### 脚本版本

v2.0.7-12-g259797c28

### 浏览器版本

Chrome版本 96.0.4664.93（正式版本） （64 位）

### 错误信息

```shell
无
```

**Comment by zwj2333** [comment]
关掉背景模糊就瞬间变正常了

**Comment by the1812** [comment]
背景模糊在 Chrome 和 Firefox 下优化很差的, 不建议打开
