### ISSUE TITLE
尝试在港澳台脚本创建的页面中禁用本脚本

### ISSUE THREAD

**Issue by youngerstar** [the1812/Bilibili-Evolved#2704]
### 关于哪一项功能

打开设置/功能界面异常

### 问题描述

1. 在港澳台番剧页面，打开设置/功能页的UI异常，内容不显示
2. 顶栏/搜索栏UI异常
链接：https://www.bilibili.com/bangumi/play/ep425577
![image](https://user-images.githubusercontent.com/46211595/145806146-f6bef2d8-5ea5-4aa5-aa6a-09dd347bd628.png)

![image](https://user-images.githubusercontent.com/46211595/145806432-91a2de59-b676-4491-8cb0-dda93defb460.png)

### 脚本版本

2.0.7 稳定版

### 浏览器版本

Edge Dev 98.0.1093.6

### 播放器版本

2.49.2-f7ef9cd5

### 附加截图

![image](https://user-images.githubusercontent.com/46211595/145806767-8bf8ca9f-85cb-493a-a799-797eee17a3ec.png)
无HEVC选项
![image](https://user-images.githubusercontent.com/46211595/145806951-89581cc9-16bc-43ad-bc40-77dbbf26692f.png)
![image](https://user-images.githubusercontent.com/46211595/145807234-0f7f0bf2-0ed1-4c1d-9dc1-6fa523437f0c.png)
![image](https://user-images.githubusercontent.com/46211595/145807268-3ca7cca3-94bf-4fbc-b782-643f934e4de8.png)
![image](https://user-images.githubusercontent.com/46211595/145807307-e5a87543-cc06-4595-b248-59f0954b92fc.png)
![image](https://user-images.githubusercontent.com/46211595/145807341-0f48445e-e95d-4f13-8965-0c4b728f910f.png)

**Comment by youngerstar** [comment]
> 是要播放起来才会出问题吗？试了下好像没问题 ![image](https://user-images.githubusercontent.com/26504152/154518773-c394cd8c-eadf-4514-bd6d-45c244df4f98.png)

对，设置好了能播放了后，UI会有问题，如图：
![0](https://user-images.githubusercontent.com/46211595/154828053-217a4e24-d368-40fb-85c2-0f4332619fbf.png)

[版本信息]
Bilibili-Evolved 版本为最新2.1.5。
“解除 B 站区域限制”脚本版本为最新8.2.15，链接：https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6

[脚本设置过程]
1. 打开此番剧页面 https://www.bilibili.com/bangumi/media/md5551， 点击图标设置公共服务器（自定义服务器和三个代理服务器）， 此处设置的是api.qiu.moe， 所有公共服务器：
https://github.com/yujincheng08/BiliRoaming/wiki/%E5%85%AC%E5%85%B1%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8
![1](https://user-images.githubusercontent.com/46211595/154828121-da5eea92-309f-47c4-9a23-6ffb72a340f5.png)
![2](https://user-images.githubusercontent.com/46211595/154828129-5c882249-5cde-4673-904c-83a0a358b8be.png)
2. 打开受限的番剧页面 https://www.bilibili.com/bangumi/play/ep425577， 会提示授权存储权限，存储成功后刷新进入播放页。

**Comment by youngerstar** [comment]
> 是要播放起来才会出问题吗？试了下好像没问题 ![image](https://user-images.githubusercontent.com/26504152/154518773-c394cd8c-eadf-4514-bd6d-45c244df4f98.png)

只保留Tampermonkey扩展插件和必要的脚本，仍然会有问题，应该不是其他扩展的影响导致

**Comment by n337pp** [comment]
Bilibili evolved版本2.1.8 Biliplus版本8.2.16
两者配合使用会出现包括但不限于以下异常
1.界面UI错误
2.夜间模式失效
3.下载功能不可用
<img width="1440" alt="截屏2022-05-01 18 12 12" src="https://user-images.githubusercontent.com/68136163/166142177-b11360bb-e9e7-4e65-91df-6c9057af8a84.png">
界面uicu
<img width="1440" alt="截屏2022-05-01 18 13 11" src="https://user-images.githubusercontent.com/68136163/166142180-1ee27eb7-a653-49f0-825c-d41b23eb03a7.png">
<img width="1440" alt="截屏2022-05-01 18 11 48" src="https://user-images.githubusercontent.com/68136163/166142171-60357a27-8533-432c-a4fd-668991b19cf6.png">

**Comment by n337pp** [comment]
Bilibili evolved版本2.1.8 Biliplus版本8.2.16
两者配合使用会出现包括但不限于以下异常
1.界面UI错误
2.夜间模式失效
3.下载功能不可用
<img width="1440" alt="截屏2022-05-01 18 11 48" src="https://user-images.githubusercontent.com/68136163/166142284-a8711f4f-391d-43c6-ae1f-5b53a0722a6b.png">
<img width="1440" alt="截屏2022-05-01 18 12 12" src="https://user-images.githubusercontent.com/68136163/166142349-9928e302-4ec6-4a6b-b67f-8b3e43fe867b.png">
<img width="1440" alt="截屏2022-05-01 18 13 11" src="https://user-images.githubusercontent.com/68136163/166142371-d9aa126a-2323-4be8-945c-78e820c39787.png">

**Comment by machine-doll** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/87234334/184531563-923dc776-3918-474e-8946-5bd53dcdd059.png">
现在依旧有这个问题  
使用的浏览器是Edge 104，Bilibili Evolved 2.2.2，解除b站区域限制 8.2.26
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/87234334/184531645-cf4a4760-35d7-4131-96a8-5d071d09e14a.png">
而且顶栏会变成这个样子，搜索记录会跑到视频里面来，而且隐藏不掉。搜索栏也显示不出来

**Comment by zacred0rryn** [comment]
我这边大陆番剧页面和港澳台区是一样的问题：
![大陆番剧页面](https://user-images.githubusercontent.com/34595052/222954612-e35c3814-3a95-4ecf-89f8-cea74c9a6a6a.png)
![特区番剧页面](https://user-images.githubusercontent.com/34595052/222711368-9b89db4f-d108-4f56-b474-8f3a1db416df.png)

**Comment by u2shana** [comment]
我这边普通视频也会触发这个禁用脚本的功能

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/discussions/4095#discussioncomment-5432331
