### ISSUE TITLE
v2版顶栏稍后再看列表不能实时更新

### ISSUE THREAD

**Issue by StqGo** [the1812/Bilibili-Evolved#2705]
### 关于哪一项功能

顶栏稍后再看列表

### 问题描述

当我取消一个视频的 稍后再看 状态后，顶栏的 稍后再看 列表并不会立即更新，需要手动刷新一下
v1是可以立即更新的  昨天更新到v2发现这个问题后  试了很多次都不行

### 脚本版本

v2.0.7-12-g259797c28

### 浏览器版本

Microsoft Edge 版本 96.0.1054.53 (官方内部版本) (64 位)

### 是否开启 HEVC

优先 HEVC

### 错误信息

```shell
/
```

**Comment by Geeyun-JY3** [comment]
重复：#2689
