### ISSUE TITLE
v2版导致专栏视频卡片排版错乱

### ISSUE THREAD

**Issue by Allenlee521** [the1812/Bilibili-Evolved#2709]
### 关于哪一项功能

脚本本身

### 问题描述

打开脚本不开启任何功能，会导致专栏视频卡片排版出现问题。
在油猴中关闭脚本，问题不会出现。

### 脚本版本

v2.0.7-12-g259797c28

### 浏览器版本

96.0.1054.53

### 播放器版本

无

### 错误信息

```shell
无
```

### 附加截图

![QQ截图20211213212421](https://user-images.githubusercontent.com/70263724/145820556-491c474a-43e9-4af9-81c3-d703a1228f5c.png)
![QQ截图20211213212429](https://user-images.githubusercontent.com/70263724/145820561-e1fa1d6c-b720-4ddc-b609-42a9c99ef0d3.png)
![QQ截图20211213212454](https://user-images.githubusercontent.com/70263724/145820571-0ca0dbf3-5f3e-4e77-8723-dc9fe3d32af8.png)

**Comment by the1812** [comment]
专栏的链接也发一下?

**Comment by Allenlee521** [comment]
> 专栏的链接也发一下?

https://www.bilibili.com/read/cv14260111

**Comment by rainpenber** [comment]
遇到了相同的问题 v2.0.8-3-ga2dc6949a
https://www.bilibili.com/read/cv14433305
和夜间模式无关 始终有这样的BUG
