### ISSUE TITLE
Safari 顶栏溢出

### ISSUE THREAD

**Issue by Sheey11** [the1812/Bilibili-Evolved#271]
### 关于哪一项功能
顶栏调整

### 问题描述
顶栏的投稿按钮已经溢出顶栏了。
安装好，不作任何调整就是这样。（把分辨率调低一点？我的 Mac 目前是 `1440 x 900` 的分辨率）

### 脚本版本
预览离线版

### 浏览器版本
Safari

### 附加截图
<img width="1440" alt="截屏2019-12-19下午3 24 44" src="https://user-images.githubusercontent.com/13375959/71153292-b2870d00-2273-11ea-911a-8fcc314f3f15.png">

**Comment by Coulomb-G** [comment]
若开启了 「使用自定义顶栏」,可在附加功能中设置「顶栏布局」,根据分辨率可以自行调整「边缘间距」

**Comment by the1812** [comment]
`顶栏布局`里可以把上面你觉得多余的入口隐藏掉, 这样总长度就会小很多

**Comment by Sheey11** [comment]
OK我懂了，希望可以加一个通过入口的个数自动改变`边缘间距`的功能。
