### ISSUE TITLE
顶栏的动态在125%的缩放下，下拉不能自动加载新内容

### ISSUE THREAD

**Issue by keeker233** [the1812/Bilibili-Evolved#2712]
### 关于哪一项功能

自定义顶栏

### 问题描述

首页，chrome浏览器缩放设置为125%时，鼠标悬停在动态按钮上弹出的浏览框下拉到最底时不能自动填充新内容，
之前v1可以
拉到底会有一段空白，缩放调小一点才会加载出来，110%就可以了

### 脚本版本

v2.0.7-12-g259797c28

### 浏览器版本

chrome 96.0.4664.93

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/49800820/145919451-5495bc25-cf5e-4267-8521-44b8ed91d0f2.png)

**Comment by Geeyun-JY3** [comment]
可能算重复：#2472、#2512

**Comment by xsdyd** [comment]
问一下 我更新了2.0.8 为什么125%缩放下还是不能自动刷新动态啊

**Comment by the1812** [comment]
自定义顶栏也要更新下
![image](https://user-images.githubusercontent.com/26504152/146379581-8e7c4f23-e9d0-407b-b13d-f1c7b2418523.png)

**Comment by xsdyd** [comment]
> 

不管用 我还试了卸载再装一次自定义顶栏插件 也不行
