### ISSUE TITLE
下载视频的按钮没了

### ISSUE THREAD

**Issue by ELMJ** [the1812/Bilibili-Evolved#2718]
### 关于哪一项功能

视频下载

### 问题描述

更新后下载视频的按钮没了（？）   也无法导出IDM下载的文件
![image](https://user-images.githubusercontent.com/74416560/145947329-0a6a1b28-62d4-4e87-93f0-ced108070596.png)

### 脚本版本

Bilibili Evolved	2.0.6  、 Bilibili Evolved (Offline)	1215.24

### 浏览器版本

chrome

### 错误信息

```shell
-
```

**Comment by nianianshinian** [comment]
我也是这样 寻求方法

**Comment by l-fay** [comment]
我也是这样，经过排查，我的问题是和另一个脚本冲突了，你排查一下。
“(电脑 && 手机 全网唯一自动脚本) VIP会员视频自动解析”，就是那个切换标签页自动暂停的脚本。
把这个脚本关了，开始按钮就出来了。

**Comment by l-fay** [comment]
@ELMJ

**Comment by ELMJ** [comment]
> 排查，我的问题是和另一个脚本冲突了，你排查一下。
> “(电脑 && 手机 全网唯一自动脚本) VIP会员视频自动解析”，就是那个

果然，，，，我也装了这个脚本，，，，，
搞定了~

**Comment by jaguar-lf** [comment]
> 我也是这样，经过排查，我的问题是和另一个脚本冲突了，你排查一下。 “(电脑 && 手机 全网唯一自动脚本) VIP会员视频自动解析”，就是那个切换标签页自动暂停的脚本。 把这个脚本关了，开始按钮就出来了。

没这篇帖子怎么能知道是这个问题  厉害了！！！
