### ISSUE TITLE
两个问题，番剧弹幕量0，无法加载港澳台番剧

### ISSUE THREAD

**Issue by gittohabo** [the1812/Bilibili-Evolved#272]
新版播放器
所有的番剧弹幕是0
看港澳台是用了解除b站限制脚本
关闭evolved脚本后以上问题消失
可否请作者查一下？或者需要我提供什么，也请说明，我会尽量提供

**Comment by Coulomb-G** [comment]
请关闭解除区域限制脚本,换用正常且稳定的港澳台节点. 若在关闭解除区域限制脚本后,番剧弹幕仍然为0,请附上控制台报错截图和浏览器版本号,以及脚本管理器版本

**Comment by the1812** [comment]
亲测可看, 而且有弹幕, 请提供控制台(`Ctrl + Shift + I`)的输出信息
![image](https://user-images.githubusercontent.com/26504152/71336360-c7201980-2581-11ea-9c92-a61b5b07464b.png)

**Comment by gittohabo** [comment]
> 亲测可看, 而且有弹幕, 请提供控制台(`Ctrl + Shift + I`)的输出信息
> ![image](https://user-images.githubusercontent.com/26504152/71336360-c7201980-2581-11ea-9c92-a61b5b07464b.png)

![Uploading 4_}CX9{Z4UFZ6TJ}4T{J[T7.png…]()
![Uploading AEZ6]5{{2E~HV2@$U5BM_RY.png…]()
这样吗？

**Comment by gittohabo** [comment]
![4_}CX9{Z4UFZ6TJ}4T{J T7](https://user-images.githubusercontent.com/50357956/71337089-fbe1a000-2584-11ea-8c32-57fe553457ba.png)
![AEZ6 5{{2E~HV2@$U5BM_RY](https://user-images.githubusercontent.com/50357956/71337090-fc7a3680-2584-11ea-84a3-41e37c4ad3c5.png)

这样的吗

> 亲测可看, 而且有弹幕, 请提供控制台(`Ctrl + Shift + I`)的输出信息
> ![image](https://user-images.githubusercontent.com/26504152/71336360-c7201980-2581-11ea-9c92-a61b5b07464b.png)

**Comment by the1812** [comment]
这里的
![image](https://user-images.githubusercontent.com/26504152/71337174-5bd84680-2585-11ea-8356-7f7d22c0b709.png)

**Comment by gittohabo** [comment]
![image](https://user-images.githubusercontent.com/50357956/71337251-c5f0eb80-2585-11ea-8575-c6d8966826a0.png)

**Comment by the1812** [comment]
你的解除限制用的服务器不对? 我这里是www.biliplus.com
![image](https://user-images.githubusercontent.com/26504152/71338577-6564ad00-258b-11ea-9003-5a4655a4841c.png)

**Comment by gittohabo** [comment]
两个服务器都试过了，这个是用biliplus的jie'mia界面
![image](https://user-images.githubusercontent.com/50357956/71338842-54686b80-258c-11ea-807a-847693f4fe0a.png)

**Comment by the1812** [comment]
那我也不太清楚了...我这脚本也没有什么港澳台番剧相关的功能, 理论上应该不会有什么影响的

**Comment by Coulomb-G** [comment]
关掉其他插件及脚本,仅保留「解除区域限制」和「evolved」两个脚本,再截图看看控制台报错信息

**Comment by gittohabo** [comment]
![image](https://user-images.githubusercontent.com/50357956/71345128-6bfd1f80-259f-11ea-9c70-4f2df311bbc9.png)

![image](https://user-images.githubusercontent.com/50357956/71345101-55ef5f00-259f-11ea-9ffc-5a4cade7ec3d.png)

![image](https://user-images.githubusercontent.com/50357956/71345213-a8c91680-259f-11ea-9031-1dfeb233590e.png)





> 关掉其他插件及脚本,仅保留「解除区域限制」和「evolved」两个脚本,再截图看看控制台报错信息
