### ISSUE TITLE
自动宽屏+播放器顶置会造成播放器偏移，需要手动复位

### ISSUE THREAD

**Issue by LabmenNo001** [the1812/Bilibili-Evolved#2727]
### 关于哪一项功能

所有播放器

### 问题描述

自动宽屏+播放器顶置会造成播放器偏移，需要手动复位

### 脚本版本

v2.0.8-10-g16157b4de

### 浏览器版本

96.0.4664.93（正式版本） （64 位）

### 播放器版本

HTML5播放器 V2.71.0

### 是否开启 HEVC

禁止 HEVC

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/38105143/146383315-41179ee0-4650-46f2-87c9-fca5499e1754.png)

**Comment by Geeyun-JY3** [comment]
重复：#483
请善用搜索，认真看功能说明：https://github.com/the1812/Bilibili-Evolved/blob/master/doc/features/features.md#%E9%BB%98%E8%AE%A4%E6%92%AD%E6%94%BE%E5%99%A8%E6%A8%A1%E5%BC%8F
