### ISSUE TITLE
关于v2里“倍速记忆”功能缺失v1的记忆开关

### ISSUE THREAD

**Issue by rennemaki** [the1812/Bilibili-Evolved#2744]
### 关于哪一项功能

倍速记忆

### 问题描述

v2里将拓展倍速功能与倍速记忆功能合成一个插件，但是没有给记忆功能开关导致只能一直开着记忆功能
v1里是有分开的两个功能开关的

### 脚本版本

v2.0.8-3-ga2dc6949a

### 浏览器版本

Microsoft Edge 版本 96.0.1054.62

### 是否开启 HEVC

禁止 HEVC

### 错误信息

```shell
none
```

### 附加截图

<img width="288" alt="image" src="https://user-images.githubusercontent.com/11786799/146666697-ee1f3b8c-ca1b-4730-b707-3a76f05821d9.png">
<img width="259" alt="image" src="https://user-images.githubusercontent.com/11786799/146666777-75798bc5-9c7c-4004-ab91-0662c4f43597.png">

**Comment by Geeyun-JY3** [comment]
关于已经有好多人提过你却没先善用搜索这件事：#2478、#2623、#2660、#2723
