### ISSUE TITLE
(v2.0.8) 新版页面下几乎所有视频的夜间模式均适配不佳

### ISSUE THREAD

**Issue by zhiyuanzhai** [the1812/Bilibili-Evolved#2755]
### 关于哪一项功能

暗色模式

### 问题描述

在任何已测试的视频中均有此现象。例如`BV133411x7A4?`.

### 脚本版本

v2.0.8-12-g758500b73

### 浏览器版本

Safari 15.1

### 错误信息

```shell
无。
```

### 附加截图

<img width="1449" alt="截屏2021-12-22 上午1 10 46" src="https://user-images.githubusercontent.com/37478391/146971919-35ef5a77-9e5d-40ea-a80e-074924c7ba56.png">

**Comment by Geeyun-JY3** [comment]
新版夜间有问题是知道的：https://github.com/the1812/Bilibili-Evolved/issues/2597#issuecomment-989342430
不过你这不还是旧版播放页么（

**Comment by zhiyuanzhai** [comment]
> 新版夜间有问题是知道的：https://github.com/the1812/Bilibili-Evolved/issues/2597#issuecomment-989342430
> 
> 
> 
> 不过你这不还是旧版播放页么（

是从新版首页进的，所以b站会从新版给我导航到旧版么（

**Comment by Geeyun-JY3** [comment]
> 是从新版首页进的，所以b站会从新版给我导航到旧版么（

新版首页和新版视频播放页的内测好像是分开的，开始的时间都不一样的。我目前也只有新版首页。

**Comment by the1812** [comment]
看着像夜间模式组件没更新啊
