### ISSUE TITLE
关于简化评论区的一点小建议

### ISSUE THREAD

**Issue by abo2029** [the1812/Bilibili-Evolved#2765]
### 关于哪一项功能

简化评论区

### 问题描述

发表评论位置的背景是透明的，感觉跟背面评价一起回有点挡视线，能不能改成原来不透明背景呢？发表按钮有点对不齐。

### 脚本版本

v2.0.8-12-g758500b73

### 浏览器版本

edge：96.0.1054.62

### 播放器版本

V2.72.1

### 是否开启 HEVC

优先 HEVC

### 错误信息

```shell
无
```

### 附加截图

![发表评论](https://user-images.githubusercontent.com/23325792/147184779-76104891-c42f-4017-bae0-88600ddb728d.png)

**Comment by the1812** [comment]
属于 #2615, 新版视频页的问题, 你可以先返回旧版
