### ISSUE TITLE
无法自动进入宽屏加夜间模式

### ISSUE THREAD

**Issue by eyinwei** [the1812/Bilibili-Evolved#2767]
### 关于哪一项功能

播放时自动宽屏，并自动关灯

### 问题描述

大概从12.19这个版本开始就无法在播放时自动应用上面这个功能了，后来我回退版本就可以正常使用。最近更新成12.22版本发现并没有修复这个问题。

### 脚本版本

v1.12.22

### 浏览器版本

Chromium 86.0.4240.198

### 是否开启 HEVC

禁止 HEVC

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/43311626/147226798-6b29ca2b-94fe-466f-9a3a-9860af1c8421.png)

**Comment by Geeyun-JY3** [comment]
v1 不维护啦。认真看 README 怎么用 v2 吧。

**Comment by eyinwei** [comment]
好的，谢谢
