### ISSUE TITLE
新版页面黑夜模式顶栏问题反馈

### ISSUE THREAD

**Issue by bmizhou** [the1812/Bilibili-Evolved#277]
**关于哪一项功能**

开启夜间模式后顶栏异常。
**问题描述**

我一直开启黑夜模式，之前一切正常，自从bilibili首页改版后，在首页一切正常，搜索页面和播放页面的顶栏是白色的。
开启自定义顶栏后夜间模式正常，但是又出现新的问题。
我的账号从来没有上传过头像。换了自定义顶栏后偷袭那里有出错了，详细情况见图片。

**脚本版本**

@name         Bilibili Evolved (Preview Offline)
@version      526.21
**浏览器版本**

Cent Browser
版本 4.0.9.112（正式版本） （64 位） (portable) (Chromium 74.0.3729.169)

**错误信息**

**附加截图**
夜间模式未开启自定义顶栏
![QQ截图20191227005805](https://user-images.githubusercontent.com/40421798/71483799-712ec880-2844-11ea-981c-a64e665bb9eb.png)
夜间模式开启自定义顶栏
![QQ截图20191227005134](https://user-images.githubusercontent.com/40421798/71483800-712ec880-2844-11ea-94a0-866c349c5464.png)

**Comment by bmizhou** [comment]
今天更新后现在开启自定义顶栏是不显示头像了，能不能改成显示默认头像？

**Comment by the1812** [comment]
噢  忘了默认是透明的图了  我一会再加上默认头像

**Comment by bmizhou** [comment]
> 噢 忘了默认是透明的图了 我一会再加上默认头像

哈哈，谢谢大佬。
像我这种不上传头像的应该不多了。。
