### ISSUE TITLE
视频下评论发表按钮文字竖直方向不居中

### ISSUE THREAD

**Issue by NoahELE** [the1812/Bilibili-Evolved#2771]
### 关于哪一项功能

简化评论区

### 问题描述

如题，视频下评论发表按钮文字竖直方向不居中

### 脚本版本

v2.0.8-10-g16157b4de

### 浏览器版本

Vivaldi: 5.0.2497.32 (Stable channel) (64-bit)

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/49080986/147330446-907c9b9b-1581-4a05-89ae-d9633da856d1.png)

**Comment by the1812** [comment]
属于新版视频页问题 (#2615)
