### ISSUE TITLE
自定义顶栏功能显示异常

### ISSUE THREAD

**Issue by SakuraIAT** [the1812/Bilibili-Evolved#2774]
### 关于哪一项功能

自定义顶栏

### 问题描述

在新版页面情况下于https://www.bilibili.com 上把鼠标移至顶栏的主站文字悬停，会看见活动、课堂、小黑屋、新歌热榜不在功能区的范围内显示，呈透明状，且仅在主页如此显示，在视频页就正常了

### 脚本版本

2.0.8

### 浏览器版本

edge

### 播放器版本

无

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/96630990/147367232-62218565-5f85-4a60-b705-72e9b75fe876.png)

**Comment by Geeyun-JY3** [comment]
请先善用搜索，重复：#2610

而且最新预览版已修：https://github.com/the1812/Bilibili-Evolved/releases/tag/v2.0.9-preview
