### ISSUE TITLE
关于自动定位播放器的bug？

### ISSUE THREAD

**Issue by Chennyh** [the1812/Bilibili-Evolved#278]
**关于哪一项功能**

自动定位播放器

**问题描述**

在视频播放页面，开启自动定位播放器后，并不会马上自动定位，一般是播放10多秒后才定位

**脚本版本**

正式版1.9.19

**浏览器版本**

Chrome 79

**错误信息**

**附加截图**

**Comment by the1812** [comment]
已修复, 应该会在点赞数那些出来的时候定位过去
