### ISSUE TITLE
`夜间模式跟随系统`在休眠唤醒后可能不会工作

### ISSUE THREAD

**Issue by DeepChirp** [the1812/Bilibili-Evolved#2780]
### 关于哪一项功能

夜间模式

### 问题描述

- 安装 `Bilibili-Evolved` 的`夜间模式`和`夜间模式跟随系统`，打开`夜间模式跟随系统`
- 使用 [Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) 等能够支持自动切换亮/暗模式的软件
- 设置自动切换模式（例如自定义时间），以便自动切换主题
- 保持浏览器打开，让电脑进入睡眠/休眠状态
- 等到切换主题的预设时间后唤醒电脑，此时系统主题应该自动切换
- `Bilibili-Evolved` 的`夜间模式跟随系统`没有工作，不会切换主题。此时即使刷新也不会自动切换主题
可以参考这个issue：https://github.com/darkreader/darkreader/issues/7041 ，`Dark Reader`似乎也有相同问题（我未在B站上启用此插件）

### 脚本版本

v2.0.8-10-g16157b4de

### 浏览器版本

Microsoft Edge 版本 96.0.1054.62 (官方内部版本) (64 位)

### 错误信息

_No need_

### 附加截图

![image](https://user-images.githubusercontent.com/66902050/147398718-0686e594-c7fe-40a5-a417-bfe413f3eab2.png)

**Comment by rick-yao** [comment]
我用的chrome，直接不生效，无法确定是不是休眠的问题。
v2.0.9-preview-1-gf5c4f2d04

**Comment by the1812** [comment]
我也是用的 Auto Dark Mode, 不过没遇到这个问题

**Comment by shenzhiming88** [comment]
> 我也是用的 Auto Dark Mode, 不过没遇到这个问题

我发现在这种情况下，虽然能够切换，但是时间很长，需要约半分钟。

**Comment by DeepChirp** [comment]
似乎不再复现
