### ISSUE TITLE
自动隐藏侧栏功能bug

### ISSUE THREAD

**Issue by SinPetec** [the1812/Bilibili-Evolved#2793]
### 关于哪一项功能

自动隐藏侧栏

### 问题描述

若打开自动隐藏侧栏功能，则刷新后有几率无法通过指针悬停呼出侧栏
其余功能正常加载
此时按F12呼出控制台则侧栏显示并可用，关闭控制台则不可用

### 脚本版本

v2.0.8-10-g16157b4de

### 浏览器版本

chrome 96.0.4664.110（正式版本） （64 位）

### 错误信息

```shell
international-home.3…78640cc20b9bb4.js:1 
 Uncaught TypeError: Cannot read properties of undefined (reading 'forceCommit')
    at HTMLDocument.<anonymous> (international-home.3…78640cc20b9bb4.js:1)
﻿
​
```

**Comment by Geeyun-JY3** [comment]
请先善用搜索，重复 issue 就在你上边：#2790，而且相关 issue 不止这一个：#2766
