### ISSUE TITLE
安装完只有两个按钮但是按钮内并没有任何功能

### ISSUE THREAD

**Issue by lengendaryff** [the1812/Bilibili-Evolved#2804]
### 关于哪一项功能

安装问题

### 问题描述

我尝试了从github和je两种方式安装,但是安装完之后都是只有功能和设置两个按钮,点进去显示空空如也
尝试了卸载油猴和重新装脚本,但是都不行.

### 脚本版本

v2.0.8-13-g93accf2ac

### 浏览器版本

chrome内核的edge版本 96.0.1054.62 (官方内部版本) (64 位)

### 错误信息

```shell
Mixed Content: The page at 'https://search.bilibili.com/all?keyword=bilibili%20evolved&from_source=websuggest_search' was loaded over HTTPS, but requested an insecure element 'http://tts.baidu.com/text2audio?lan=en&ie=UTF-8&spd=5&text=v2.0.8-13-g93accf2ac'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
```

### 附加截图

![image](https://user-images.githubusercontent.com/56516136/147802612-4b5dae40-d47f-4be4-885f-22610209be4f.png)
![image](https://user-images.githubusercontent.com/56516136/147802616-4afe95bd-9537-4ab8-954b-ff8e32d3d2f8.png)

**Comment by the1812** [comment]
本来就没有功能啊, 去把使用说明看看完吧: https://github.com/the1812/Bilibili-Evolved/tree/master#%E8%AE%BE%E7%BD%AE

**Comment by lengendaryff** [comment]
> 本来就没有功能啊, 去把使用说明看看完吧: https://github.com/the1812/Bilibili-Evolved/tree/master#%E8%AE%BE%E7%BD%AE

是我没把使用说明看完....辛苦大佬了 已经解决啦
