### ISSUE TITLE
ComponentOption 中的 displayName 应该是非必须属性

### ISSUE THREAD

**Issue by timongh** [the1812/Bilibili-Evolved#2809]
### 关于哪一项功能

./src/components/types.ts

### 问题描述

文件：`./src/components/types.ts`
接口: `ComponentOption`

一般情况下，该接口中的 `displayName` 是作为输入内容的标签文本。但是，如果我需要启用 `hidden`，仅将选项作为一个数据持久化方式，这个选项似乎是非必要的。

### 脚本版本

preview

### 浏览器版本

无

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/46739861/147839348-41de23a3-5184-48af-a60e-10429019744a.png)

**Comment by the1812** [comment]
这里类型写的比较潦草, 得改进下
