### ISSUE TITLE
开启自定义顶栏后，主站下的“番剧”按钮指向的页面不存在

### ISSUE THREAD

**Issue by zbodo** [the1812/Bilibili-Evolved#2813]
### 关于哪一项功能

自定义顶栏

### 问题描述

番剧按钮指向的 https://www.bilibili.com/v/anime/ 是不存在的页面
正确的页面应为 https://www.bilibili.com/anime/ 

### 脚本版本

v2.0.8-10-g16157b4de

### 浏览器版本

Edge

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/39948021/147845014-b2c47b07-15be-4c18-bad9-1f411a625e0f.png)

**Comment by Geeyun-JY3** [comment]
重复：#2610
