### ISSUE TITLE
夜间模式下- "视频选集"模块 显示异常！

### ISSUE THREAD

**Issue by okhuazai1011** [the1812/Bilibili-Evolved#2822]
### 关于哪一项功能

夜间模式

### 问题描述

夜间模式下- "视频选集"模块 显示异常！
（无法看清楚文字）
![Snipaste_2022-01-03_16-43-48](https://user-images.githubusercontent.com/51896383/147912515-ab06098a-1591-4dbb-b2f1-579b34d0d529.png)

### 脚本版本

v2.0.8-10-g16157b4de

### 浏览器版本

Google Chrome 版本 96.0.4664.110（正式版本） （64 位）

### 错误信息

```shell
无
```

### 附加截图

![Snipaste_2022-01-03_16-43-48](https://user-images.githubusercontent.com/51896383/147912663-e3baf591-499b-4a4e-a1af-e61c997d2caa.png)

**Comment by okhuazai1011** [comment]
选中某一集视频的时候才会出现问题，以下是问题图片

![image](https://user-images.githubusercontent.com/51896383/147912859-46913be3-a347-4a91-892a-514b96f7790b.png)

**Comment by yxk383** [comment]
我遇到了同样的问题，应该是B站最近又改版了视频页面，可以用页面右下方的“回到旧版”按钮暂时解决

**Comment by the1812** [comment]
重复 #2615
