### ISSUE TITLE
视频下载如果是多p，选框太长，无法拖动选框，点不到下载按钮

### ISSUE THREAD

**Issue by q33420540** [the1812/Bilibili-Evolved#2823]
### 关于哪一项功能

视频下载

### 问题描述

视频下载如果是多p，选框太长，无法拖动选框，点不到下载按钮

### 脚本版本

v2.0.8-13-g93accf2ac

### 浏览器版本

Chrome 96.0.4664.110

### 错误信息

```shell
无错误信息
```

### 附加截图

![image](https://user-images.githubusercontent.com/68733003/147939904-7279e1a4-4278-420a-bd21-57ead131b7f6.png)

**Comment by the1812** [comment]
网页往下滚动啊...
