### ISSUE TITLE
Bilibili新版网页夜间模式适配

### ISSUE THREAD

**Issue by TankNee** [the1812/Bilibili-Evolved#2831]
### 关于哪一项功能

夜间模式

### 问题描述

新版网页的视频详情，多集视频的选择，评论栏等处在使用了夜间模式组件之后会出现样式异常。

### 脚本版本

v2.0.8-10-g16157b4de

### 浏览器版本

版本 96.0.1054.62 (官方内部版本) (64 位)

### 错误信息

```shell
无直接错误信息。
```

### 附加截图

![image](https://user-images.githubusercontent.com/43956168/148043028-5aa044ca-4ea2-4968-9b27-b90ac9f2cb41.png)

**Comment by TankNee** [comment]
与这个issue相似 #2755

**Comment by Mrneet** [comment]
这个问题一直没有修复，夜间模式，视频下方的介绍文字还是黑的，旁边多P列表文字又是白的
