### ISSUE TITLE
多p视频,视频内显示时间在播放完成,自动换p后时间不显示

### ISSUE THREAD

**Issue by Lactococcuslactis** [the1812/Bilibili-Evolved#2839]
### 关于哪一项功能

视频内显示时间

### 问题描述

多p视频,首个视频视频内显示时间正常,视频内显示时间在播放完成,自动换p后时间不显示,手动换p也不显示,重新刷新后又显示时间了

### 脚本版本

v2.0.8-13-g93accf2ac

### 浏览器版本

版本 96.0.4664.45（正式版本） （64 位）

### 是否开启 HEVC

优先 HEVC

### 错误信息

```shell
无
```

**Comment by FoundTheWOUT** [comment]
已修复
@the1812 可以关了
