### ISSUE TITLE
关于新版界面的一点建议 （新年快乐）

### ISSUE THREAD

**Issue by Malus-Mill** [the1812/Bilibili-Evolved#284]
**关于哪一项功能**

![image](https://user-images.githubusercontent.com/53999738/71620181-705eb380-2c03-11ea-81f8-04dbdb3afdc8.png)
![image](https://user-images.githubusercontent.com/53999738/71620189-879da100-2c03-11ea-9f54-8575eaaee358.png)
![image](https://user-images.githubusercontent.com/53999738/71620218-a439d900-2c03-11ea-8acf-c23bfc916b4e.png)
![image](https://user-images.githubusercontent.com/53999738/71620229-b3b92200-2c03-11ea-8707-23cea60fc4d1.png)

**期望的效果**
上面的俩张图当中，感觉留白有点太大了，并表示以前的样子就挺好看的
下面的俩张图中，希望可以把主播公告和挂绘马做一个开关，并表示放在右边也挺方便的

**脚本版本**

离线版 531.09

**Comment by Coulomb-G** [comment]
b站原版主页是选择将留白位置放在两侧,因为需要适配不同分辨率,留白位置是难以避免的,你可以尝试在控制台切换分辨率体验一下,这边是照顾了12.3英寸的小屏幕,直播间那个按钮可以做到

**Comment by Malus-Mill** [comment]
![image](https://user-images.githubusercontent.com/53999738/71628816-065f0200-2c35-11ea-8e59-b70535cb2227.png)
![image](https://user-images.githubusercontent.com/53999738/71628864-44f4bc80-2c35-11ea-80ab-7c775a8fb25b.png)
![image](https://user-images.githubusercontent.com/53999738/71628895-77061e80-2c35-11ea-8fc9-d40e88ff477d.png)

发现直播间绘马跑掉可能是因为，加载的的原因，多次刷新之后，加载完全之后就好了

**Comment by the1812** [comment]
首页那个还没做好 我是想把右边排行榜再宽一点 这样中间不会空很多
