### ISSUE TITLE
本地调试本体时，安装在线脚本失败

### ISSUE THREAD

**Issue by timongh** [the1812/Bilibili-Evolved#2849]
### 关于哪一项功能

core

### 问题描述

依据 `CONTRIBUTING.md` 的描述，在本地调试脚本本体时，无法安装在线仓库的组件。使用的"基于 Chromium 的浏览器"的调试方式。

组件无论是 `master` 还是 `preview` 不影响结果。安装源无论是 `jsDelivr` 还是 `GigHub` 都不影响结果。

经调试发现，问题在 "Bilibili-Evolved/src/core/install-feature.ts:24"，这里返回的 `response` 的值是 `404: Not Found`

### 脚本版本

v2.0.9-preview-29-gf47ee380d

### 浏览器版本

Microsoft Edge 版本 96.0.1054.62 (官方内部版本) (64 位)

### 播放器版本

无

### 错误信息

```shell
external-input.ts:59 
 SyntaxError: Unexpected token ':'
    at parseExternalInput (external-input.ts:46)
    at installFeatureFromCode (install-feature.ts:57)
    at async Promise.all (index 0)
    at async VueComponent.install (RegistryItem.vue?./n…e-loader-options:99)
parseExternalInput	@	external-input.ts:59
installFeatureFromCode	@	install-feature.ts:57
await in installFeatureFromCode(异步)		
installFeature	@	install-feature.ts:98
await in installFeature(异步)		
eval	@	RegistryItem.vue?./n…e-loader-options:99
install	@	RegistryItem.vue?./n…e-loader-options:99
click	@	RegistryItem.vue?./n…e-loader-options:75
invokeWithErrorHandling	@	vue.esm.js:1862
invoker	@	vue.esm.js:2187
original._wrapper	@	vue.esm.js:7555
log.ts:22 
 Error: 无效的功能代码
    at eval (install-feature.ts:84)
    at installFeatureFromCode (install-feature.ts:85)
    at async Promise.all (index 0)
    at async VueComponent.install (RegistryItem.vue?./n…e-loader-options:99)
logError	@	log.ts:22
await in logError(异步)		
install	@	RegistryItem.vue?./n…-loader-options:106
await in install(异步)		
click	@	RegistryItem.vue?./n…e-loader-options:75
invokeWithErrorHandling	@	vue.esm.js:1862
invoker	@	vue.esm.js:2187
original._wrapper	@	vue.esm.js:7555
```

### 附加截图

![image](https://user-images.githubusercontent.com/46739861/148523996-9b70a57b-b385-4dac-9d5f-2db077d4e94b.png)

**Comment by timongh** [comment]
问题找到了。是脚本里拼接组件 url 时，branch 获取环节出的错。

url 是在这个函数里拼接的："./src/components/settings-panel/sub-pages/online-registry/RegistryItem.vue:getFeatureUrl:58"
其中 branch 部分写的是："meta.compilationInfo.branch" 而这个值追根究底是 webpack 全局注入的，来自于 "./webpack/compilation-info.js" 里的 branch 变量。

也就是说最终 branch 获取自本地执行 "git rev-parse --abbrev-ref HEAD" 得到的值（即本地当前分支名）。

这里的逻辑错误在于，安装在现脚本不应该从本地获取当前分支名，而应该根据安装面板里的选择来安装。

我无法安装在现脚本就是因为，我本地的分支名不是 "master" 或 "preview"，所以拼接得到的 url 是错误的。

**Comment by timongh** [comment]
这个问题似乎也会导致安装在现组件时，选择分支无效，始终下载的都是脚本本体分支的组件。

**Comment by the1812** [comment]
奇怪, 我记得以前 TP 的时候就修复过这个了

**Comment by timongh** [comment]
> 奇怪, 我记得以前 TP 的时候就修复过这个了

请教一下，TP 是什么意思

**Comment by the1812** [comment]
Technical Preview, 在 v2 发布预览版前的特殊开发版, 半年前的事情了

**Comment by the1812** [comment]
看了下原来是我只做了分支选择的记忆, RegistryItem 里确实还没改掉
