### ISSUE TITLE
脚本无法加载启动

### ISSUE THREAD

**Issue by DannyVim** [the1812/Bilibili-Evolved#285]
**关于哪一项功能**

脚本启动

**问题描述**

脚本无法启动；
无法访问 https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js

**脚本版本**

预览版 1.9.23

**浏览器版本**

Chrome 79.0.3945.88

**错误信息**

ERROR: Execution of script 'Bilibili Evolved (Preview)' failed! Vue is not defined

**附加截图**

**Comment by the1812** [comment]
不应该啊 这个网站也没有墙...
进代码里改成这个网址试试?
```
@require      https://unpkg.com/vue@2.6.10/dist/vue.js
```
