### ISSUE TITLE
下载视频功能的Toast输出页面403

### ISSUE THREAD

**Issue by zwj2333** [the1812/Bilibili-Evolved#2869]
### 关于哪一项功能

下载视频

### 问题描述

点击下载视频，选择Toast（默认的那个），点击开始会从左下方跳出来下载链接弹窗。点击或右键打开，就会跳到403 Forbidden的网页。原本是会自动下载视频文件。

### 脚本版本

v2.0.8-13-g93accf2ac

### 浏览器版本

96.0.4664.110（正式版本） （64 位）

### 错误信息

```shell
无
```

### 附加截图

![QQ截图20220109143452](https://user-images.githubusercontent.com/45174459/148671917-f3467e75-23a4-4e5b-a6ca-2ed98ba055e9.png)

**Comment by the1812** [comment]
视频链接来一个

**Comment by magic-monkey** [comment]
我也是

**Comment by magic-monkey** [comment]
> 视频链接来一个

https://www.bilibili.com/video/BV1fK4y1t7hj

**Comment by zwj2333** [comment]
> 视频链接来一个

所有视频下载都是失效的，我现在用idm输出还是正常的

**Comment by zwj2333** [comment]
哦，对 如果用1.0版本（停止更新那个），下载是OK的

**Comment by zwj2333** [comment]
好像是和我的另一个插件冲突了 我把所有插件脚本全关了就正常了（只留这一个） 现在在测试和哪个冲突

**Comment by zwj2333** [comment]
找到原因了 被AdGuard当广告拦截了，关掉AdGuard插件就没事了
