### ISSUE TITLE
希望ARIA2也遵从文件名的设定，以及记住下载的清晰度选项。

### ISSUE THREAD

**Issue by vvyoko** [the1812/Bilibili-Evolved#288]
**关于哪一项功能**
下载功能

**期望的效果**
1，现在下载有文件名的设定，但是ARIA2不遵从这个设定，希望ARIA2也遵从文件名设定。
搜了下脚本里应该是由out=${t.title}${n}${this.extension(e.url,s)}\n  split=${i}\n 控制文件名的
但是这个变量好像与文件名设定里的变量是不一样的，文件名设定里title是标题，ARIA2里的title好像是选集标题。所以自己也不知道怎么修改

2，下载希望记住默认选项
大会员是没有任何问题的，但是普通用户每次都要调整清晰度.(是future,不是bug……)
如果可能希望记住最后选定的清晰度。
也可以像win10 uwp 里的 哔哩吡哔哩动画 一样默认选定最高画质，但是在你没权限的情况下下载你能下载的最高画质（这种可能会让以为自己下载的是大会员的画质。个人觉得不太好）

**脚本版本**
正式版 1.9.22

**Comment by the1812** [comment]
应该是只有批量导出的时候不遵从文件名设定, 当时是考虑到批量和单集下载的适用场景不同, 不应该直接拿单集的格式去套.
之后可能会再增加一个`批量文件命名格式`
