### ISSUE TITLE
首页的样式-隐藏顶部横幅被遮挡

### ISSUE THREAD

**Issue by 1353604736** [the1812/Bilibili-Evolved#2884]
### 关于哪一项功能

样式-隐藏顶部横幅

### 问题描述

首页的样式-隐藏顶部横幅被遮挡

### 脚本版本

Stable v1.12.22 内容包: 0168ed1 

### 浏览器版本

百分最新

### 播放器版本

b

### 是否开启 HEVC

禁止 HEVC

### 错误信息

```shell
首页的样式-隐藏顶部横幅被遮挡
```

### 附加截图

![image](https://user-images.githubusercontent.com/12869582/149440883-32c2514f-9310-46a5-b6cc-78d54ff5c1ef.png)

**Comment by the1812** [comment]
你脚本没更新
