### ISSUE TITLE
导出设置失败

### ISSUE THREAD

**Issue by wurarara** [the1812/Bilibili-Evolved#2890]
### 关于哪一项功能

V1导出设置失败

### 问题描述

提示如下：
www.bilibili.comhttps 意外终止了连接。
切换了网络也是这样显示。
其他网页正常。

### 脚本版本

Stable v1.12.22 内容包: 0163310

### 浏览器版本

chrome，版本 95.0.4638.69（正式版本） （64 位）

### 错误信息

```shell
输入了，不过没有变化。
请看附件截图。
（输入前后显示的都是图片里的内容，没有增减）
```

### 附加截图

![0](https://user-images.githubusercontent.com/73343292/149486607-80ab9e84-7ec8-41d5-b271-0c310778afc0.jpg)
![1](https://user-images.githubusercontent.com/73343292/149486623-ac05cb6d-3f47-4a87-92b7-8cced8f9ae1e.jpg)

**Comment by FoundTheWOUT** [comment]
#2846
