### ISSUE TITLE
头像悬窗排版出现错误

### ISSUE THREAD

**Issue by ssyximmlove** [the1812/Bilibili-Evolved#2893]
### 关于哪一项功能

顶栏

### 问题描述

鼠标悬浮在顶栏头像时出现的悬浮窗排版存在问题

### 脚本版本

2.0.8

### 浏览器版本

95.0.4638.69

### 是否开启 HEVC

优先 HEVC

### 错误信息

```shell
无报错
PS，如果图1也算的话
```

### 附加截图

![image](https://user-images.githubusercontent.com/23517759/149621815-ece209d7-ddd2-4650-9d38-d84255c443e2.png)
![image](https://user-images.githubusercontent.com/23517759/149621706-d5f349de-2640-4e34-b04d-1422fbd8d555.png)

**Comment by Geeyun-JY3** [comment]
重复：#2740
