### ISSUE TITLE
默认播放器模式不生效

### ISSUE THREAD

**Issue by Henry-ZHR** [the1812/Bilibili-Evolved#2894]
### 关于哪一项功能

默认播放器模式

### 问题描述

![](https://user-images.githubusercontent.com/51886614/149624219-89e4988c-6041-442c-9b6a-d3f9e6f11455.png)

![](https://user-images.githubusercontent.com/51886614/149624345-f2ba694a-6629-4644-a382-6a5470c8dd05.png)

前面是默认状态下，后面是鼠标放上设置按钮之后  
可见 `.bilibili-player-video-btn-setting-wrap` 一开始并不存在  
所以脚本这里的逻辑就没用了

https://github.com/the1812/Bilibili-Evolved/blob/5c299afad3b3e90775dff89c6ef7e45a2e9f1e9c/registry/lib/components/video/player/default-mode/index.ts#L24-L29

https://github.com/the1812/Bilibili-Evolved/blob/5c299afad3b3e90775dff89c6ef7e45a2e9f1e9c/src/core/utils/lazy-panel.ts#L50-L53

这里拿到的 `panel` 是 `null`，然后整个默认播放器模式功能就报废了

### 脚本版本

 v2.0.10-preview-31-g5c299afad 

### 浏览器版本

Firefox 97.0b3

### 播放器版本

2.73.1-07859f81

**Comment by Henry-ZHR** [comment]
哦不对 可能上面说的不是问题所在

另外注意到一个情况  宽屏、全屏等元素没有 `mouseover` 和 `mouseout`

![](https://user-images.githubusercontent.com/51886614/149624883-6116bdd1-d330-4cd5-83df-4ddf60d843bc.png)

**Comment by FoundTheWOUT** [comment]
吸。。。原来是火狐的问题吗
#2815

**Comment by Henry-ZHR** [comment]
> 吸。。。原来是火狐的问题吗 #2815

其他浏览器没问题吗？我还没试

**Comment by Henry-ZHR** [comment]
有点没看懂 `loadButton` 和 `loadLazyPlayerSettingsPanel` 的逻辑

是在试图通过 `settings.widescreen` 的 `mouseover` 和 `mouseout` 把 `settings.wrap` 干出来吗？

**Comment by Henry-ZHR** [comment]
> ~吸。。。原来是火狐的问题吗~ #2815 奇怪，另一个Edge也有问题，怎么感觉全世界只有我能正常运行 ，我这边试了两台都没问题

可能播放器版本不一样之类的？

**Comment by Henry-ZHR** [comment]
我这边 Chrome 97.0.4692.71 也是不行的

**Comment by FoundTheWOUT** [comment]
哦~我知道，宽屏那些按钮都不在`.bilibili-player-video-btn-setting-wrap`里面，其它并不需要把这个东西干出来。
~~但是为啥我用了两周一点问题没有~~
> 是在试图通过 settings.widescreen 的 mouseover 和 mouseout 把 settings.wrap 干出来吗？

对，但我发现干的对象错了，这么干原先的目的是解决 #2815

**Comment by jiang-yuan** [comment]
我也来反馈一下,我用的edge,默认播放模式是时灵时不灵
有时会宽屏有时不会,经常要手动点,头疼

**Comment by Henry-ZHR** [comment]
> 我也来反馈一下,我用的edge,默认播放模式是时灵时不灵 有时会宽屏有时不会,经常要手动点,头疼

建议另开 issue 或 discussion

**Comment by the1812** [comment]
可以看下组件选项里的 Commit, 最新版是 `da1de09b8`

**Comment by Henry-ZHR** [comment]
`b6ea3caa7`，确实不是最新
