### ISSUE TITLE
批量下载：获取番剧数据失败

### ISSUE THREAD

**Issue by wladder** [the1812/Bilibili-Evolved#290]
**问题描述**
批量下载番剧页面报错，批量导出列表无内容。

获取番剧数据失败: 无法找到 Season ID

**脚本版本**
(Preview Offline)
541.20

**浏览器版本**
Google Chrome 版本 79.0.3945.117

**错误信息**
Console
flv.js报Playback seems stuck at 0, seek to 0.092
脚本报updateWatchlaterList、dash change、format change，无报错。
左下弹窗报 无法找到 Season ID

**Comment by the1812** [comment]
是哪部番?

**Comment by wladder** [comment]
> 是哪部番?

所有的

但刚刚又无法复现了
