### ISSUE TITLE
有关脚本安装地址的改进建议

### ISSUE THREAD

**Issue by BROBIRD** [the1812/Bilibili-Evolved#291]
**关于哪一项功能**

脚本安装地址

**期望的效果**

使用jsDelivr的CDN地址加载

https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@master/bilibili-evolved.user.js

**脚本版本**

All

**Comment by the1812** [comment]
感谢建议 下次更新就会使用

**Comment by BROBIRD** [comment]
其他资源文件也可以如法炮制
