### ISSUE TITLE
无法使用视频下载功能下载dash格式

### ISSUE THREAD

**Issue by CCCAUCHY** [the1812/Bilibili-Evolved#2911]
### 关于哪一项功能

视频下载功能

### 问题描述

点击如图所示的地方，

![image](https://user-images.githubusercontent.com/55306290/150638989-87e491cf-887f-48f8-a30c-fb3078b6cb47.png)

会跳转至这个页面，无法下载，但flv可以下载。

![image](https://user-images.githubusercontent.com/55306290/150638958-f7b11f97-1fe4-4a84-9824-2d5f8e0d776e.png)

### 脚本版本

2.0.8

### 浏览器版本

Microsoft Edge 版本 97.0.1072.62 (官方内部版本) (64 位)

### 错误信息

```shell
无，b站页面一切正常
```

### 附加截图

点击这里后会跳转

![image](https://user-images.githubusercontent.com/55306290/150639100-3896a8b1-f27e-451a-b2d7-2889f726d928.png)

跳转到这里，无法下载

![image](https://user-images.githubusercontent.com/55306290/150639121-88936b08-fe4d-4e17-a93f-8826135bff01.png)

**Comment by CCCAUCHY** [comment]
更新：
浏览器更新到Microsoft Edge 版本98.0.1108.50 (官方内部版本) (64 位)，脚本更新到2.1.3，依旧有这个问题，但选择“dash（仅音频）”有概率可以下载，选择其他两个dash选项暂时没有试出有概率的可以下载。

**Comment by liquidhelium** [comment]
我复现了，这个问题并非脚本的问题，而是edge不开始下载而试图播放视频，只要用idm下载方法就好了

**Comment by liquidhelium** [comment]
我复现了，这个问题并非脚本的问题，而是edge不开始下载而试图播放视频，只要用idm下载方法就好了（甚至仅音频的文件都有mp4格式结尾的，无法直接下载
