### ISSUE TITLE
评论区错误

### ISSUE THREAD

**Issue by Doorming** [the1812/Bilibili-Evolved#2912]
### 关于哪一项功能

Bilibili Evolved本体

### 问题描述

在安装Bilibili Evolved本体前如图1
![屏幕截图 2022-01-23 205758](https://user-images.githubusercontent.com/98263833/150679718-7c054ea5-2383-46e5-8a07-8ecfb235da85.png)
安装后如图2
![屏幕截图 2022-01-23 205811](https://user-images.githubusercontent.com/98263833/150679691-b261b691-b175-46d9-8c8c-cd7a634850a5.png)
注：还没安装其他插件

### 脚本版本

v2.1.0-preview-2-gc50963478

### 浏览器版本

Microsoft Edge 版本 97.0.1072.69 (官方内部版本) (64 位)

### 错误信息

```shell
userscript.html?name=Bilibili%20Evolved%20(Offline).user.js&id=9a4de6ea-3805-46e3-aa52-f1ec5dc41721:13211 
        
       TypeError: Cannot set property settings of #<Object> which has only a getter
    at Function.assign (<anonymous>)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved%2520(/video/Offline).user.js&id=9a4de6ea-3805-46e3-aa52-f1ec5dc41721:13211:2666443)
logError @ userscript.html?name=Bilibili%20Evolved%20(Offline).user.js&id=9a4de6ea-3805-46e3-aa52-f1ec5dc41721:13211
userscript.html?name=Bilibili%20Evolved%20(Preview%20Offline).user.js&id=e11a5f5e-46ae-4000-a731-a1fc3c24ab28:13211 
        
       TypeError: Cannot set property settings of #<Object> which has only a getter
    at Function.assign (<anonymous>)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved%2520(/video/Preview%2520Offline).user.js&id=e11a5f5e-46ae-4000-a731-a1fc3c24ab28:13211:2666452)
logError @ userscript.html?name=Bilibili%20Evolved%20(Preview%20Offline).user.js&id=e11a5f5e-46ae-4000-a731-a1fc3c24ab28:13211
userscript.html?name=Bilibili%20Evolved.user.js&id=cafeda5a-8b11-4e48-9531-4418bb72ee46:13211 
        
       TypeError: Cannot set property settings of #<Object> which has only a getter
    at Function.assign (<anonymous>)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=cafeda5a-8b11-4e48-9531-4418bb72ee46:13211:2666831)
logError @ userscript.html?name=Bilibili%20Evolved.user.js&id=cafeda5a-8b11-4e48-9531-4418bb72ee46:13211
userscript.html?name=Bilibili%20Evolved%20(Offline).user.js&id=9a4de6ea-3805-46e3-aa52-f1ec5dc41721:13211 
        
       TypeError: Cannot set property settings of #<Object> which has only a getter
    at Function.assign (<anonymous>)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved%2520(/video/Offline).user.js&id=9a4de6ea-3805-46e3-aa52-f1ec5dc41721:13211:2666443)
logError @ userscript.html?name=Bilibili%20Evolved%20(Offline).user.js&id=9a4de6ea-3805-46e3-aa52-f1ec5dc41721:13211
userscript.html?name=Bilibili%20Evolved%20(Preview%20Offline).user.js&id=e11a5f5e-46ae-4000-a731-a1fc3c24ab28:13211 
        
       TypeError: Cannot set property settings of #<Object> which has only a getter
    at Function.assign (<anonymous>)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved%2520(/video/Preview%2520Offline).user.js&id=e11a5f5e-46ae-4000-a731-a1fc3c24ab28:13211:2666452)
logError @ userscript.html?name=Bilibili%20Evolved%20(Preview%20Offline).user.js&id=e11a5f5e-46ae-4000-a731-a1fc3c24ab28:13211
userscript.html?name=Bilibili%20Evolved.user.js&id=cafeda5a-8b11-4e48-9531-4418bb72ee46:13211 
        
       TypeError: Cannot set property settings of #<Object> which has only a getter
    at Function.assign (<anonymous>)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=cafeda5a-8b11-4e48-9531-4418bb72ee46:13211:2666831)
```

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/150680302-30987e9f-44cd-4184-98eb-119060600a47.png)
你旧版卸了没, 这报错咋是 v1 的脚本名字

**Comment by Doorming** [comment]
我就没安装v1啊
我先安装了2.1.1，后来覆盖安装了2.0.8的正式版
今天重新安装了2.1.1发现还是这样


除此以外，b站顶栏插件也直接消除了

注：我是直接删了油猴重装的，还没安装任何Bilibili-Evolved内置的其他插件
版本为v2.1.0-preview-2-gc50963478


目前的错误信息：
TypeError: Cannot set property settings of #<Object> which has only a getter
    at Function.assign (<anonymous>)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved%2520(/video/Offline).user.js&id=14e2e37c-dcca-42dc-9153-ffb4c601b1f6:13211:2666443)
logError @ userscript.html?name=Bilibili%20Evolved%20(Offline).user.js&id=14e2e37c-dcca-42dc-9153-ffb4c601b1f6:13211
userscript.html?name=Bilibili%20Evolved%20(Preview%20Offline).user.js&id=d9bbf79b-1645-45d4-951f-fa7e465b9e88:13211 
        
       TypeError: Cannot set property settings of #<Object> which has only a getter
    at Function.assign (<anonymous>)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved%2520(/video/Preview%2520Offline).user.js&id=d9bbf79b-1645-45d4-951f-fa7e465b9e88:13211:2666452)
logError @ userscript.html?name=Bilibili%20Evolved%20(Preview%20Offline).user.js&id=d9bbf79b-1645-45d4-951f-fa7e465b9e88:13211
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7ad9d15a-a5a2-4800-bd72-0aedbbf039b1:190 [自动更新器] 开始检查更新
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7ad9d15a-a5a2-4800-bd72-0aedbbf039b1:190 暂无组件更新
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7ad9d15a-a5a2-4800-bd72-0aedbbf039b1:190 暂无插件更新
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7ad9d15a-a5a2-4800-bd72-0aedbbf039b1:190 暂无样式更新
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7ad9d15a-a5a2-4800-bd72-0aedbbf039b1:190 [自动更新器] 完成更新检查
userscript.html?name=Bilibili%20Evolved.user.js&id=948ee91b-217b-4b52-9d3c-48d2a79c14fe:190 [自动更新器] 开始检查更新
userscript.html?name=Bilibili%20Evolved.user.js&id=948ee91b-217b-4b52-9d3c-48d2a79c14fe:190 暂无组件更新
userscript.html?name=Bilibili%20Evolved.user.js&id=948ee91b-217b-4b52-9d3c-48d2a79c14fe:190 暂无插件更新
userscript.html?name=Bilibili%20Evolved.user.js&id=948ee91b-217b-4b52-9d3c-48d2a79c14fe:190 暂无样式更新
userscript.html?name=Bilibili%20Evolved.user.js&id=948ee91b-217b-4b52-9d3c-48d2a79c14fe:190 [自动更新器] 完成更新检查
log-reporter.js:1 
        
       Uncaught (in promise) Error: COLS: response timeout
    at log-reporter.js:1:3757
bili-header.umd.js:12 [Intervention]Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
sentry-5.7.1.min.js:2 
        
       Error: COLS: response timeout
    at s1.hdslb.com/bfs/seed/laputa-header/bili-header.umd.js:25:5573
    at sentryWrapped (sentry-5.7.1.min.js:2:37371)
(匿名) @ sentry-5.7.1.min.js:2
userscript.html?name=Bilibili%20Evolved%20(Offline).user.js&id=14e2e37c-dcca-42dc-9153-ffb4c601b1f6:13211 
        
       TypeError: Cannot set property settings of #<Object> which has only a getter
    at Function.assign (<anonymous>)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved%2520(/video/Offline).user.js&id=14e2e37c-dcca-42dc-9153-ffb4c601b1f6:13211:2666443)
logError @ userscript.html?name=Bilibili%20Evolved%20(Offline).user.js&id=14e2e37c-dcca-42dc-9153-ffb4c601b1f6:13211
userscript.html?name=Bilibili%20Evolved%20(Preview%20Offline).user.js&id=d9bbf79b-1645-45d4-951f-fa7e465b9e88:13211 
        
       TypeError: Cannot set property settings of #<Object> which has only a getter
    at Function.assign (<anonymous>)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved%2520(/video/Preview%2520Offline).user.js&id=d9bbf79b-1645-45d4-951f-fa7e465b9e88:13211:2666452)
logError @ userscript.html?name=Bilibili%20Evolved%20(Preview%20Offline).user.js&id=d9bbf79b-1645-45d4-951f-fa7e465b9e88:13211
sentry-5.7.1.min.js:2 load module pbp
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 Object
sentry-5.7.1.min.js:2 https://live-trace.bilibili.com/xlive/data-interface/v1/index/log?sessionID=eee9f9461956da10773bdf9b6761769a_A7C27722-3F09-41E5-8D02-BE4B0E43D527&group_id=1000221&biz=live&event_id=live_card_show&rule_key=&special_id=0&roomid=21218036&parent_id=1&area_id=123&page=0&position=1&platform=web
从 Windows 版邮件发送

发件人: Grant Howard
发送时间: 2022年1月23日 21:17
收件人: the1812/Bilibili-Evolved
抄送: Doorming; Author
主题: Re: [the1812/Bilibili-Evolved] 评论区错误 (Issue #2912)


你旧版卸了没, 这报错咋是 v1 的脚本名字
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Doorming** [comment]
> 我就没安装v1啊 我先安装了2.1.1，后来覆盖安装了2.0.8的正式版 今天重新安装了2.1.1发现还是这样 ![屏幕截图 2022-01-24 194733](https://user-images.githubusercontent.com/98263833/150777637-7fb04d84-74f0-4b4c-a67f-85f98d56bbf5.png) 除此以外，b站顶栏插件也直接消除了 ![屏幕截图 2022-01-24 194712](https://user-images.githubusercontent.com/98263833/150777659-a6d0751e-3b5a-4b3f-bbf2-0d16179c7b33.png) 注：我是直接删了油猴重装的，还没安装任何Bilibili-Evolved内置的其他插件 版本为v2.1.0-preview-2-gc50963478 目前的错误信息： TypeError: Cannot set property settings of #<Object> which has only a getter at Function.assign (<anonymous>) at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved%2520(/video/Offline).user.js&id=14e2e37c-dcca-42dc-9153-ffb4c601b1f6:13211:2666443) logError @ userscript.html?name=Bilibili%20Evolved%20(Offline).user.js&id=14e2e37c-dcca-42dc-9153-ffb4c601b1f6:13211 userscript.html?name=Bilibili%20Evolved%20(Preview%20Offline).user.js&id=d9bbf79b-1645-45d4-951f-fa7e465b9e88:13211 TypeError: Cannot set property settings of #<Object> which has only a getter at Function.assign (<anonymous>) at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved%2520(/video/Preview%2520Offline).user.js&id=d9bbf79b-1645-45d4-951f-fa7e465b9e88:13211:2666452) logError @ userscript.html?name=Bilibili%20Evolved%20(Preview%20Offline).user.js&id=d9bbf79b-1645-45d4-951f-fa7e465b9e88:13211 userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7ad9d15a-a5a2-4800-bd72-0aedbbf039b1:190 [自动更新器] 开始检查更新 userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7ad9d15a-a5a2-4800-bd72-0aedbbf039b1:190 暂无组件更新 userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7ad9d15a-a5a2-4800-bd72-0aedbbf039b1:190 暂无插件更新 userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7ad9d15a-a5a2-4800-bd72-0aedbbf039b1:190 暂无样式更新 userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=7ad9d15a-a5a2-4800-bd72-0aedbbf039b1:190 [自动更新器] 完成更新检查 userscript.html?name=Bilibili%20Evolved.user.js&id=948ee91b-217b-4b52-9d3c-48d2a79c14fe:190 [自动更新器] 开始检查更新 userscript.html?name=Bilibili%20Evolved.user.js&id=948ee91b-217b-4b52-9d3c-48d2a79c14fe:190 暂无组件更新 userscript.html?name=Bilibili%20Evolved.user.js&id=948ee91b-217b-4b52-9d3c-48d2a79c14fe:190 暂无插件更新 userscript.html?name=Bilibili%20Evolved.user.js&id=948ee91b-217b-4b52-9d3c-48d2a79c14fe:190 暂无样式更新 userscript.html?name=Bilibili%20Evolved.user.js&id=948ee91b-217b-4b52-9d3c-48d2a79c14fe:190 [自动更新器] 完成更新检查 log-reporter.js:1 Uncaught (in promise) Error: COLS: response timeout at log-reporter.js:1:3757 bili-header.umd.js:12 [Intervention]Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113 sentry-5.7.1.min.js:2 Error: COLS: response timeout at s1.hdslb.com/bfs/seed/laputa-header/bili-header.umd.js:25:5573 at sentryWrapped (sentry-5.7.1.min.js:2:37371) (匿名) @ sentry-5.7.1.min.js:2 userscript.html?name=Bilibili%20Evolved%20(Offline).user.js&id=14e2e37c-dcca-42dc-9153-ffb4c601b1f6:13211 TypeError: Cannot set property settings of #<Object> which has only a getter at Function.assign (<anonymous>) at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved%2520(/video/Offline).user.js&id=14e2e37c-dcca-42dc-9153-ffb4c601b1f6:13211:2666443) logError @ userscript.html?name=Bilibili%20Evolved%20(Offline).user.js&id=14e2e37c-dcca-42dc-9153-ffb4c601b1f6:13211 userscript.html?name=Bilibili%20Evolved%20(Preview%20Offline).user.js&id=d9bbf79b-1645-45d4-951f-fa7e465b9e88:13211 TypeError: Cannot set property settings of #<Object> which has only a getter at Function.assign (<anonymous>) at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved%2520(/video/Preview%2520Offline).user.js&id=d9bbf79b-1645-45d4-951f-fa7e465b9e88:13211:2666452) logError @ userscript.html?name=Bilibili%20Evolved%20(Preview%20Offline).user.js&id=d9bbf79b-1645-45d4-951f-fa7e465b9e88:13211 sentry-5.7.1.min.js:2 load module pbp sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 Object sentry-5.7.1.min.js:2 https://live-trace.bilibili.com/xlive/data-interface/v1/index/log?sessionID=eee9f9461956da10773bdf9b6761769a_A7C27722-3F09-41E5-8D02-BE4B0E43D527&group_id=1000221&biz=live&event_id=live_card_show&rule_key=&special_id=0&roomid=21218036&parent_id=1&area_id=123&page=0&position=1&platform=web 从 Windows 版邮件发送 发件人: Grant Howard 发送时间: 2022年1月23日 21:17 收件人: the1812/Bilibili-Evolved 抄送: Doorming; Author 主题: Re: [the1812/Bilibili-Evolved] 评论区错误 (Issue #2912) 你旧版卸了没, 这报错咋是 v1 的脚本名字 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by the1812** [comment]
好好检查下, 是不是有好几个油猴, 你就没发现这错误信息里都出现 4 个不同名字的脚本了吗, 2 个旧版 2 个新版, 那个自动更新器都出现了两次
![image](https://user-images.githubusercontent.com/26504152/150779424-65aa5a91-c9f4-48e2-82ea-b10bb5471c5a.png)

**Comment by Doorming** [comment]
嗯，搞明白了，因为我是下载压缩包导入的，导入的四个插件都打开了造成的
所以这事是我踩坑了（尴尬）
建议主页写一下“压缩包导入的四个插件不能都打开”这事
