### ISSUE TITLE
还是绘马祈愿和主播公告消失的问题

### ISSUE THREAD

**Issue by Malus-Mill** [the1812/Bilibili-Evolved#292]
**关于哪一项功能**

**问题描述**

https://live.bilibili.com/8899503；
在任一直播界面中同时使用Bilibili直播间挂机助手（https://github.com/SeaLoong/Bilibili-LRHH）和Evolved；
挂机助手使用默认设置；
Evolved使用简化直播间，简化付费礼物；

**脚本版本**

离线版531.09

**浏览器版本**

版本 79.0.3945.117（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/53999738/72199932-f5589100-347d-11ea-8d8d-07dd6314b9cb.png)
![image](https://user-images.githubusercontent.com/53999738/72199936-02758000-347e-11ea-86df-7a091ae1e23d.png)

**Comment by Coulomb-G** [comment]
关闭Bilibili直播间挂机助手后是否还存在该现象?

**Comment by Malus-Mill** [comment]
当俩个同时开启后，并简化付费礼物才会

**Comment by Malus-Mill** [comment]
> 关闭Bilibili直播间挂机助手后是否还存在该现象？

当俩个同时开启后，并简化发现礼物才会

**Comment by Coulomb-G** [comment]
因为简化付费礼物功能会对直播页面进行修改,建议只开一个

**Comment by Malus-Mill** [comment]
> 因为简化了礼物功能临时直播页面进行修改，建议只开一个

好，好吧
