### ISSUE TITLE
能支持一下iPad吗？

### ISSUE THREAD

**Issue by howecheung** [the1812/Bilibili-Evolved#2926]
iOS有一个叫userscripts的软件  支持safari拓展  可以支持一下就好了  谢谢

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by FoundTheWOUT** [comment]
这个要看这个软件对 油猴API 的支持程度，比如`unsafeWindows`它就没有，现在这个插件本身还是比较依赖于油猴的，没那么容易支持其它脚本加载软件😂

**Comment by Seele0oO** [comment]
好消息，快要有了。
https://github.com/Tampermonkey/tampermonkey/issues/1258
