### ISSUE TITLE
希望添加屏蔽直播间入场特效功能

### ISSUE THREAD

**Issue by HCLonely** [the1812/Bilibili-Evolved#293]
**关于哪一项功能**

简化直播间：希望添加屏蔽入场特效功能

**期望的效果**
屏蔽这种入场特效：
![image](https://user-images.githubusercontent.com/26346802/72199999-dad2e780-347e-11ea-80f2-fe1073fac7f1.png)

**脚本版本**
预览版

**Comment by HCLonely** [comment]
我看更新了屏蔽入场特效功能，但是开启了没有屏蔽掉

![image](https://user-images.githubusercontent.com/26346802/72218720-0c2fde00-3579-11ea-893c-142a22f9a318.png)
![image](https://user-images.githubusercontent.com/26346802/72218721-0f2ace80-3579-11ea-8b02-2222bcb09b46.png)
![image](https://user-images.githubusercontent.com/26346802/72218723-1225bf00-3579-11ea-9309-9ba40f729240.png)

**Comment by the1812** [comment]
有个地方字打错了 一会就更新
