### ISSUE TITLE
播放视频的时候，点击个人头像，显示的ui排列错乱

### ISSUE THREAD

**Issue by DockerCS** [the1812/Bilibili-Evolved#2931]
### 关于哪一项功能

ui问题

### 问题描述

播放视频的时候，点击个人头像，显示的ui排列错乱
![image](https://user-images.githubusercontent.com/26867628/150916630-b0a485fd-e60f-412b-ba14-846f7f09ec3a.png)

### 脚本版本

2.0.8和2.1.2

### 浏览器版本

chrome96和97

### 错误信息

```shell
无
```

**Comment by Geeyun-JY3** [comment]
给个自定义顶栏组件的版本？这个 bug 应该已经修了的：#2740
