### ISSUE TITLE
新版播放页面bug

### ISSUE THREAD

**Issue by YZ-HZ** [the1812/Bilibili-Evolved#2938]
### 关于哪一项功能

夜间模式、展开视频简介、快捷键扩展

### 问题描述

新版播放页面不自动展开简介，
简介和一部分文本在夜间模式不转换颜色，添加到收藏夹夜间模式失效。
脚本的快捷键扩展失效。

### 脚本版本

v2.1.0-preview-2-gc50963478

### 浏览器版本

Chrome 版本 97.0.4692.99（正式版本） （64 位）

### 错误信息

```shell
没有错误信息
```

### 附加截图

![image](https://user-images.githubusercontent.com/71547026/151039349-8c1b1192-eceb-4434-a0bd-8af7de544ef5.png)
![image](https://user-images.githubusercontent.com/71547026/151043064-2fec967e-ba45-4834-858b-f95b267e2bf6.png)

**Comment by Geeyun-JY3** [comment]
看置顶，新版页面没怎么适配：#2615
