### ISSUE TITLE
在火狐上，用鼠标中键或者ctrl+左键打开视频时，脚本不会加载，其他脚本会加载（比如港澳台脚本）

### ISSUE THREAD

**Issue by CCCAUCHY** [the1812/Bilibili-Evolved#294]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
我这边是正常的,请提供仅开启evolved脚本时的控制台报错信息以及脚本管理器版本

**Comment by the1812** [comment]
有些功能用后台新标签页打开是不运行的 等到你切换过去才会开始

**Comment by CCCAUCHY** [comment]
好吧，重启电脑后好了
