### ISSUE TITLE
清爽首页卡片显示问题

### ISSUE THREAD

**Issue by Y65NG** [the1812/Bilibili-Evolved#2944]
### 关于哪一项功能

清爽首页

### 问题描述

开启清爽首页后若视频标题过长会与其他元素重叠

### 脚本版本

v2.1.2-1-g5cf979c5b

### 浏览器版本

97

### 错误信息

```shell
None
```

### 附加截图

<img width="418" alt="image" src="https://user-images.githubusercontent.com/74285192/151173039-7556a62a-91ff-43f7-8ed6-dab8cd964423.png">

**Comment by the1812** [comment]
导份设置看看?

**Comment by Y65NG** [comment]
> 导份设置看看?

[settings.zip](https://github.com/the1812/Bilibili-Evolved/files/7942529/settings.zip)

**Comment by the1812** [comment]
是 `展开动态标题` 的 bug, 可以暂时关闭这个功能

**Comment by the1812** [comment]
已修复
