### ISSUE TITLE
下载不打包视频

### ISSUE THREAD

**Issue by ThebestkillerTBK** [the1812/Bilibili-Evolved#2948]
### 关于哪一项功能

下载不打包视频

### 问题描述

如果下载中选择了弹幕/字母下载，下载不会打包视频，需要点下链接才会单独下载（老版本模式）

例如小视频打包，大视频分开下

### 脚本版本

v2.1.2-1-g5cf979c5b

### 浏览器版本

none

### 播放器版本

none

### 错误信息

```shell
none
```

### 附加截图

![7zFM_a14rndPQGT](https://user-images.githubusercontent.com/62250232/151289102-819f2d9c-a672-4cba-96b2-27abe873f37c.png)
![explorer_11EjTuviOt](https://user-images.githubusercontent.com/62250232/151289211-20970722-690b-4675-935b-26bdd7a48e9a.png)

**Comment by the1812** [comment]
只有弹幕/字幕会额外打包, 和视频的下载方式无关.
