### ISSUE TITLE
请求扩展广告屏蔽功能

### ISSUE THREAD

**Issue by freeAbrams** [the1812/Bilibili-Evolved#295]
**关于哪一项功能**
希望能扩展广告屏蔽功能，提供选项屏蔽 电竞赛事 一栏

**期望的效果**
在广告屏蔽功能下额外添加一个扩展选项用于屏蔽lol内容

**脚本版本**
正式版

**Comment by the1812** [comment]
哪个地方的

**Comment by freeAbrams** [comment]
> 哪个地方的
![Screenshot](https://user-images.githubusercontent.com/49235713/72311476-c4679e80-36bf-11ea-9186-652cc2e6e4f2.png)
