### ISSUE TITLE
夜间模式未适配合集

### ISSUE THREAD

**Issue by hamber5566** [the1812/Bilibili-Evolved#2956]
### 关于哪一项功能

夜间模式

### 问题描述

https://www.bilibili.com/video/BV1U34y1o7qh
https://www.bilibili.com/video/BV1eS4y1R7Ga
这2个视频 右边出现的选集 还是白色的

### 脚本版本

v2.1.2-1-g5cf979c5b

### 浏览器版本

google chrome

### 错误信息

```shell
https://www.bilibili.com/video/BV1U34y1o7qh
https://www.bilibili.com/video/BV1eS4y1R7Ga
这2个视频 右边出现的选集 还是白色的
```

### 附加截图

![DSVSDVSDV](https://user-images.githubusercontent.com/98660075/151671232-57a9ce80-e53d-4644-9cf0-984326ba5518.png)

**Comment by Geeyun-JY3** [comment]
重复：https://github.com/the1812/Bilibili-Evolved/issues/2136#issuecomment-1021020336

**Comment by CodeSissi** [comment]
https://www.bilibili.com/video/BV17U4y1H7KU这个也是的

**Comment by Geeyun-JY3** [comment]
不需要重复反馈，只要是合集都是一样的。
