### ISSUE TITLE
脚本功能完全失效

### ISSUE THREAD

**Issue by ApolloniusSun** [the1812/Bilibili-Evolved#2959]
### 关于哪一项功能

脚本完全失效

### 问题描述

在B站所有页面中脚本功能均消失，且左侧浮窗不出现，

### 脚本版本

2.1.2

### 浏览器版本

Google Chrome 97.0.4692.99

### 错误信息

```shell
详见截图
```

### 附加截图

![QQ截图20220130195012](https://user-images.githubusercontent.com/74149618/151700754-8744fd09-1208-475a-8c81-0b8372207bbe.png)

**Comment by horizon98** [comment]
参见 #2928 。
