### ISSUE TITLE
希望下载分段视频能够有合并选项，下载结果为单个视频文件。

### ISSUE THREAD

**Issue by vendettar** [the1812/Bilibili-Evolved#296]
**关于哪一项功能**

视频下载
**期望的效果**
希望下载分段视频能够有合并选项，下载结果为单个视频文件。

**脚本版本**

1.9.22

**Comment by the1812** [comment]
请使用 ffmpeg 工具
分段合并见 #201
DASH格式合并见 #183

**Comment by vendettar** [comment]
收到，谢谢作者。
