### ISSUE TITLE
ComponentMetadata 中的 extraOptions 的类型定义错误

### ISSUE THREAD

**Issue by timongh** [the1812/Bilibili-Evolved#2967]
### 关于哪一项功能

core

### 问题描述

`.\src\components\types.ts` 中对 `FunctionalMetadata.extraOptions` 的类型定义是 `Executable<VueModule>`。即既能是普通函数，也能是异步函数。

但在实际测试中，此处只能使用异步函数（或返回 Promise 的函数）；使用普通函数无法显示该 Vue 组件。

注：使用普通函数指的是——在文件顶部引入 Vue 组件，然后在 extraOptions 处使用同步的返回该组件的闭包。

### 脚本版本

v2.1.2-1-g5cf979c5b

### 浏览器版本

无

### 播放器版本

无

### 错误信息

```shell
无
```

**Comment by the1812** [comment]
> 使用普通函数指的是——在文件顶部引入 Vue 组件，然后在 extraOptions 处使用同步的返回该组件的闭包。

这个有例子吗

**Comment by timongh** [comment]
我新提交的 PR #2960 用了这个
还有 customNavbar, keymap 都用到了这个 extraOption

**Comment by timongh** [comment]
比如 customNavbar 里面
``` javascript
import ExtraOptions from './settings/ExtraOptions.vue'
//...
extraOptions: () => ExtraOptions
```
