### ISSUE TITLE
下载对话框需要向上移动些

### ISSUE THREAD

**Issue by ivysrono** [the1812/Bilibili-Evolved#2968]
### 关于哪一项功能

下载

### 问题描述

使用Aria2下载时对话框很长，如果配合系统或者浏览器页面放大比例到一定程度，那么有可能下载按钮跑到了下一页。
可以考虑对话框上移，或者开始下载按钮上移

### 脚本版本

2.1.2

### 浏览器版本

Firefox96.0.3

### 播放器版本

2.73.7

### 错误信息

```shell
无
```

### 附加截图

![图片](https://user-images.githubusercontent.com/2649544/151926456-79c291e3-c753-42e7-919e-76489532e116.png)

**Comment by the1812** [comment]
往下滚动网页不就行了

**Comment by ivysrono** [comment]
麻烦啊。
而且好像还不能用鼠标去拖滚动条，只能用键盘pagedown

**Comment by the1812** [comment]
鼠标可以滚轮, 触控板可以手势, 不用管滚动条在哪

**Comment by ivysrono** [comment]
要不在顶部下载视频那里也加个开始按钮？
 一头一尾都能按键也很符合逻辑。

**Comment by the1812** [comment]
那就合并至 #2990 吧
