### ISSUE TITLE
希望增加直播录像下载功能

### ISSUE THREAD

**Issue by hhucqian** [the1812/Bilibili-Evolved#297]
目前直播录像不支持下载，希望增加直播录像下载功能
比如下面这个视频
https://live.bilibili.com/record/R14x411c7cJ

**Comment by the1812** [comment]
做成功能没这么快
下载链接可以先给你 [records.txt](https://github.com/the1812/Bilibili-Evolved/files/4069025/records.txt)

**Comment by hhucqian** [comment]
能说下怎么找到下载链接吗？我可以手动下载

**Comment by the1812** [comment]
打开控制台(`Ctrl + Shift + I`), 粘贴这段代码:
```js
(await (await fetch(`https://api.live.bilibili.com/xlive/web-room/v1/record/getLiveRecordUrl?rid=${document.URL.match(/record\/(.+)/)[1]}&platform=html5`)).json()).data.list.map(it => it.url).join('\n')
```
回车执行, 稍等一会就有链接出来
![image](https://user-images.githubusercontent.com/26504152/72497512-aa68c000-3867-11ea-811f-5804c8bb804f.png)

**Comment by hhucqian** [comment]
既然可以直接找到下载链接，那么做个功能，直接弹出对话框显示下载链接，然后我自己点击链接用下载软件就行了。

**Comment by the1812** [comment]
要做成功能得等很久, 我前面还有一堆功能要做, 所以先直接告诉你方法凑合一下先

**Comment by lbcake** [comment]
> 打开控制台(`Ctrl + Shift + I`), 粘贴这段代码:
> 
> ```js
> (await (await fetch(`https://api.live.bilibili.com/xlive/web-room/v1/record/getLiveRecordUrl?rid=${document.URL.match(/record\/(.+)/)[1]}&platform=html5`)).json()).data.list.map(it => it.url).join('\n')
> ```
> 
> 回车执行, 稍等一会就有链接出来
> ![image](https://user-images.githubusercontent.com/26504152/72497512-aa68c000-3867-11ea-811f-5804c8bb804f.png)

300分钟 分了10段

**Comment by lbcake** [comment]
> 打开控制台(`Ctrl + Shift + I`), 粘贴这段代码:
> 
> ```js
> (await (await fetch(`https://api.live.bilibili.com/xlive/web-room/v1/record/getLiveRecordUrl?rid=${document.URL.match(/record\/(.+)/)[1]}&platform=html5`)).json()).data.list.map(it => it.url).join('\n')
> ```
> 
> 回车执行, 稍等一会就有链接出来
> ![image](https://user-images.githubusercontent.com/26504152/72497512-aa68c000-3867-11ea-811f-5804c8bb804f.png)

我能在问一个问题吗  就是 普通投稿的视频 控制台输入什么得下载地址？

**Comment by the1812** [comment]
@lbcake 普通视频直接在`下载视频`里选`显示链接`

**Comment by lbcake** [comment]
> @lbcake 普通视频直接在`下载视频`里选`显示链接`
但是不能默认封装成mp4啊  只能flv   能否直接调用ffmpeg实现解封格式 重新封装mp4

**Comment by lbcake** [comment]
> @lbcake 普通视频直接在`下载视频`里选`显示链接`

dash  下载下来的直接是音、频分开的啊

**Comment by the1812** [comment]
> dash 下载下来的直接是音、频分开的啊

dash需要用ffmpeg合并为单个视频, 方法见 #183

**Comment by lbcake** [comment]
> > dash 下载下来的直接是音、频分开的啊
> 
> dash需要用ffmpeg合并为单个视频, 方法见 #183

我现在往b站传4k视频  貌似压出来的 没有4k 选项
