### ISSUE TITLE
下载限免番剧会出现code-404

### ISSUE THREAD

**Issue by amronbook** [the1812/Bilibili-Evolved#2971]
### 关于哪一项功能

下载视频功能

### 问题描述

当出现现在限免视频时出现code-404
BV1cs411Q71j
某科学的超电磁炮

### 脚本版本

2.1.2

### 浏览器版本

chrome 版本 97.0.4692.99（正式版本） （64 位）

### 错误信息

```shell
获取视频链接失败 code=-404
message=啥都没有
```

### 附加截图

<img width="276" alt="image" src="https://user-images.githubusercontent.com/51790146/152321075-1a2bc66f-c451-402c-94bf-3285d1b0f336.png">

**Comment by the1812** [comment]
已修复, 更新下 `下载视频` 组件

**Comment by amronbook** [comment]
> 已修复, 更新下 `下载视频` 组件

好的谢谢
