### ISSUE TITLE
收藏夹有纪录片后，显示错误

### ISSUE THREAD

**Issue by ciring** [the1812/Bilibili-Evolved#2973]
### 关于哪一项功能

收藏夹

### 问题描述

纪录片 例如
https://www.bilibili.com/bangumi/play/ep188243
加入收藏夹后显示有问题
<img width="372" alt="image" src="https://user-images.githubusercontent.com/33834625/152525078-f3af97f7-d3df-4aa8-83d3-156eb6910dd6.png">
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/33834625/152525114-4cd55a4a-0d0f-4604-b9d2-2659f68636e7.png">
关闭插件后正常
<img width="376" alt="image" src="https://user-images.githubusercontent.com/33834625/152525228-48fdfb8d-662d-4f31-aa4d-feef4662eca3.png">

### 脚本版本

v2.1.2-3-g28f22f84f

### 浏览器版本

chrome版本 98.0.4758.80（正式版本） (x86_64)

### 播放器版本

3.5.3

### 是否开启 HEVC

优先 HEVC

### 错误信息

```shell
VM23:397 Error executing AG js: TypeError: Cannot read properties of undefined (reading 'close')
（匿名） @ VM23:397
sentry-5.2.1.min.js:2 log-reporter.js加载失败，放弃上报
（匿名） @ sentry-5.2.1.min.js:2
VM69:1 [URL params clean] https://space.bilibili.com/38800559/favlist?spm_id_from=..0.0 https://space.bilibili.com/38800559/favlist
VM105:397 Error executing AG js: TypeError: Cannot read properties of undefined (reading 'close')
（匿名） @ VM105:397
3VM67:28 requestedPopup true
```

### 附加截图

-

**Comment by the1812** [comment]
这是怎么加到收藏夹里的?
![image](https://user-images.githubusercontent.com/26504152/154504675-5454ed6b-d405-4a72-9a5c-560007e9fc65.png)

**Comment by the1812** [comment]
试着加了一下, 这个纪录片出现在`订阅`里了, 默认收藏夹里没有变化

**Comment by the1812** [comment]
我知道是怎么回事了, 脚本用的是旧版收藏夹 API, 请求 20 个只返回 19 个 (纪录片没返回), 这时候翻页就开始乱了
