### ISSUE TITLE
Aria2 RPC下载推送失败

### ISSUE THREAD

**Issue by LJLHLH** [the1812/Bilibili-Evolved#2974]
### 关于哪一项功能

Aria2 RPC下载推送

### 问题描述

使用Aria2 RPC下载点击开始会提示发送了2个请求，成功0个，失败2个。不知道是否是自己的ARIA设置的有问题，但是我试了一个别的RPC下载推送器是可正常下载的

### 脚本版本

v2.1.2-3-g28f22f84f

### 浏览器版本

edge 98.0.1108.43

### 播放器版本

2.73.7-a306a712

### 是否开启 HEVC

优先 HEVC

### 错误信息
nc-loader-1.10.0.min.js:2 
 Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (nc-loader-1.10.0.min.js:2:202073)
    at he.window (nc-loader-1.10.0.min.js:2:222176)
    at Module.<anonymous> (nc-loader-1.10.0.min.js:2:222944)
    at r (nc-loader-1.10.0.min.js:2:146)
    at Object.<anonymous> (nc-loader-1.10.0.min.js:2:85991)
    at r (nc-loader-1.10.0.min.js:2:146)
    at nc-loader-1.10.0.min.js:2:945
    at t (nc-loader-1.10.0.min.js:2:955)
    at nc-loader-1.10.0.min.js:2:226362
I	@	nc-loader-1.10.0.min.js:2
he.window	@	nc-loader-1.10.0.min.js:2
(匿名)	@	nc-loader-1.10.0.min.js:2
r	@	nc-loader-1.10.0.min.js:2
(匿名)	@	nc-loader-1.10.0.min.js:2
r	@	nc-loader-1.10.0.min.js:2
(匿名)	@	nc-loader-1.10.0.min.js:2
t	@	nc-loader-1.10.0.min.js:2
(匿名)	@	nc-loader-1.10.0.min.js:2
userscript.html?name…f2-7217740528ef:228 updated widgets 
[__ob__: $e]
VM2396:12 
{rpcProfiles: Proxy, selectedRpcProfileName: 'Synology', basicConfig: Proxy}
 
Proxy {…}
VM2372:14 [updateTestVideoInfo] 
{aid: '808162032', cid: '484736894', title: '【WW2-CCCP】“同志，你还追随着列宁吗？”'}
aid: (...)
cid: (...)
quality: (...)
title: (...)
__ob__: $e {value: {…}, dep: fe, vmCount: 0}
get aid: ƒ ()
set aid: ƒ (t)
get cid: ƒ ()
set cid: ƒ (t)
get quality: ƒ ()
set quality: ƒ (t)
get title: ƒ ()
set title: ƒ (t)
[[Prototype]]: Object
VM2372:12 [downloadExtraAssets] 
[]
length: 0
[[Prototype]]: Array(0)
2
VM2355:26 
 Refused to connect to "http://192.168.1.189:9167/jsonrpc": Request was blocked by the user
eval	@	VM2355:26
eval	@	VM2355:26
ee	@	VM2355:24
eval	@	VM2355:25
eval	@	VM2355:9
nt	@	VM2336:13
t	@	VM2336:14
message	@	VM2355:9
message	@	VM2355:10
eval	@	VM2355:66
x	@	VM2336:6
s	@	VM2334 content.js:105
send	@	VM2334 content.js:106
postMessage	@	VM2334 content.js:106
(匿名)	@	VM2334 content.js:116
s	@	VM2334 content.js:115
(匿名)	@	VM2334 content.js:116
VM2396:12 
(索引)
param
success
message
0	{…}	false	'无法连接到RPC主机, error = {"responseText":"","response":…YPE_JSON":"json","RESPONSE_TYPE_STREAM":"stream"}'
1	{…}	false	'无法连接到RPC主机, error = {"responseText":"","response":…YPE_JSON":"json","RESPONSE_TYPE_STREAM":"stream"}'
Array(2)
0:
message: "无法连接到RPC主机, error = {\"responseText\":\"\",\"response\":null,\"readyState\":4,\"responseHeaders\":\"\",\"status\":0,\"statusText\":\"\",\"error\":\"Refused to connect to \\\"http://192.168.1.189:9167/jsonrpc\\\": Request was blocked by the user\",\"DONE\":4,\"HEADERS_RECEIVED\":2,\"LOADING\":3,\"OPENED\":1,\"UNSENT\":0,\"RESPONSE_TYPE_TEXT\":\"text\",\"RESPONSE_TYPE_ARRAYBUFFER\":\"arraybuffer\",\"RESPONSE_TYPE_BLOB\":\"blob\",\"RESPONSE_TYPE_DOCUMENT\":\"document\",\"RESPONSE_TYPE_JSON\":\"json\",\"RESPONSE_TYPE_STREAM\":\"stream\"}"
param: {params: Array(3), id: '%E3%80%90WW2-CCCP%E3%80%91%E2%80%9C%E5%90%8C%E5%BF…%E5%88%97%E5%AE%81%E5%90%97%EF%BC%9F%E2%80%9D.mp4'}
success: false
[[Prototype]]: Object
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
__proto__: (...)
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
1:
message: "无法连接到RPC主机, error = {\"responseText\":\"\",\"response\":null,\"readyState\":4,\"responseHeaders\":\"\",\"status\":0,\"statusText\":\"\",\"error\":\"Refused to connect to \\\"http://192.168.1.189:9167/jsonrpc\\\": Request was blocked by the user\",\"DONE\":4,\"HEADERS_RECEIVED\":2,\"LOADING\":3,\"OPENED\":1,\"UNSENT\":0,\"RESPONSE_TYPE_TEXT\":\"text\",\"RESPONSE_TYPE_ARRAYBUFFER\":\"arraybuffer\",\"RESPONSE_TYPE_BLOB\":\"blob\",\"RESPONSE_TYPE_DOCUMENT\":\"document\",\"RESPONSE_TYPE_JSON\":\"json\",\"RESPONSE_TYPE_STREAM\":\"stream\"}"
param: {params: Array(3), id: '%E3%80%90WW2-CCCP%E3%80%91%E2%80%9C%E5%90%8C%E5%BF…%E5%88%97%E5%AE%81%E5%90%97%EF%BC%9F%E2%80%9D.m4a'}
success: false
[[Prototype]]: Object
length: 2
[[Prototype]]: Array(0)
﻿
Aria2 RPC下载推送失败

### 附加截图

![image](https://user-images.githubusercontent.com/62316437/152541021-400cc909-7ddc-40b5-ba73-4ccba798c687.png)
![image](https://user-images.githubusercontent.com/62316437/152541052-093bc54a-4ddc-46c7-829e-42916482e46c.png)
![image](https://user-images.githubusercontent.com/62316437/152541070-c23fd2f1-2579-4759-a66d-0abf7aabe5af.png)
![image](https://user-images.githubusercontent.com/62316437/152541084-ebd65998-031e-49a2-8eb8-491896cd8e97.png)

**Comment by the1812** [comment]
#2440 和你的报错信息类似, 看看是不是 Tampermonkey 的问题?

**Comment by LJLHLH** [comment]
> #2440 和你的报错信息类似, 看看是不是 Tampermonkey 的问题?

我原先使用的是chrome web store的4.14版本，更换了microsoftstore的4.13.6138版本恢复正常，这个版本会正常提示脚本尝试访问跨源资源是否允许，而webstore的版本不会提示，感谢解惑！！
