### ISSUE TITLE
切换选集后默认播放速度/双击全屏等功能失效

### ISSUE THREAD

**Issue by happyTonakai** [the1812/Bilibili-Evolved#298]
**关于哪一项功能**

默认播放速度/双击全屏

**问题描述**

打开任意番剧，默认播放速度为1.25，双击全屏功能on，这两项功能均正常工作，在手动切换选集或者播放结束自动切换至下一集后，播放速度恢复为1，双击全屏失效。刷新后正常工作。

**脚本版本**

1.9.22

**浏览器版本**

Edge Chromium 79.0.309.68
Chrome  79.0.3945.117

**错误信息**

**附加截图**

**Comment by the1812** [comment]
已修复
