### ISSUE TITLE
VideoPlayerAgent 中缺少对 unsafeWindow.bPlayer 的包装

### ISSUE THREAD

**Issue by timongh** [the1812/Bilibili-Evolved#2980]
### 对应功能

VideoPlayerAgent

### 问题描述

在 B 站的视频页面，除了 `unsafeWindow.player`，还有一个很重要的变量：`unsafeWindow.bPlayer`。

这个变量的重要功能之一是与 player 结合起来使用事件。例如：

```Typescript
unsafeWindow.player.addEventListener(bPlayer.events.play, () => { /* ... */ })
```

唯一难点在于，这个东西应该如何加到现有 api 里进去。或者直接不加了，反正可以直接通过 unsafeWindow 使用。

### 脚本版本

v2.1.2-1-g5cf979c5b

### 浏览器版本

无

### 播放器版本

无

### 错误信息

```shell
无
```

**Comment by the1812** [comment]
还有这东西吗, 我之前没用过(

**Comment by the1812** [comment]
现在想想感觉也不适合加到 PlayerAgent 里, PlayerAgent 的作用是为不同的播放器提供统一的接口, 但这个只有普通视频播放器有.
需要的话直接用 unsafeWindow 调用吧
