### ISSUE TITLE
安装简洁至上后插件功能全部失效

### ISSUE THREAD

**Issue by MrLv0816** [the1812/Bilibili-Evolved#2984]
### 对应功能

简洁至上

### 问题描述

功能全部失效

### 脚本版本

2.1.3

### 浏览器版本

97.0.1072.76

### 错误信息

```shell
VM3937 all_injected.js:2 
        
       Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at VM3937 all_injected.js:2:21564
    at wait_until_success (VM3937 all_injected.js:2:19392)
    at VM3937 all_injected.js:2:19443
```

### 附加截图

![Snipaste_2022-02-08_00-56-53](https://user-images.githubusercontent.com/46812909/152835209-5f4da435-1992-4db0-9b85-cf6104c80263.png)

**Comment by the1812** [comment]
`简洁至上` 默认自动隐藏侧栏, 鼠标移到附近才会出现
