### ISSUE TITLE
4K画质下载

### ISSUE THREAD

**Issue by starxjys** [the1812/Bilibili-Evolved#299]
https://www.bilibili.com/bangumi/play/ep311200
小破站有4K画质了！

正式版

**Comment by the1812** [comment]
格式选DASH就可以下哦, 合并见 #183.
<img height="600" src="https://user-images.githubusercontent.com/26504152/72704051-86242080-3b92-11ea-8be4-f47cbc60b29d.png">

**Comment by starxjys** [comment]
94%翻车_(:з」∠)_
![image](https://user-images.githubusercontent.com/42333314/72707391-444ba800-3b9b-11ea-9e16-eacbb1e7792c.png)

**Comment by the1812** [comment]
那直接下载可能还有点bug, 可以试试下面的aria2和RPC

**Comment by starxjys** [comment]
没问题了，感谢感谢
