### ISSUE TITLE
播放器自动定位下沉

### ISSUE THREAD

**Issue by nyanoteam** [the1812/Bilibili-Evolved#300]
开启：使用默认播放器模式 =》选择【宽屏】后
会自动下沉定位到播放器，播放器到网页TOP，有时候过分下沉，遮住上部分一点，希望取消这功能

开启【自动定位到播放器后】 +1000 可以 up网页至最上方
但是同之前的有一个issues，这个功能需要几乎10秒钟后才能打开，这时候基本上视频已经播放很久了，严重影响感观了

**Comment by the1812** [comment]
已取消下沉的代码, 不过b站开启宽屏本身就会有点下沉, 另外也修复了一下定位播放器的问题
