### ISSUE TITLE
MP4视频无法下载

### ISSUE THREAD

**Issue by elulee** [the1812/Bilibili-Evolved#3006]
### 对应功能

下载组件相关

### 问题描述

底下弹窗弹出来点击无论是MP4文件还是m4a文件，怎么下载都是m4s文件

### 脚本版本

2.1.3

### 浏览器版本

Chrome  版本 98.0.4758.82（正式版本）

### 播放器版本

2.73.8-rc.2860.0-63447fdd

### 错误信息

```shell
没有报错
```

### 附加截图

![image](https://user-images.githubusercontent.com/99628232/153793293-68cbcfeb-3e89-4fce-be13-d5b463d60c9b.png)

**Comment by the1812** [comment]
本来就是 m4s, 那个 mp4, m4a 只是给你参考用的文件名
