### ISSUE TITLE
aria2 rpc 无法发送请求给远程主机

### ISSUE THREAD

**Issue by mouzi3102** [the1812/Bilibili-Evolved#3010]
### 对应功能

在下载页面请求局域网内的aria2和远程服务器的aria2均无法推送 连接不上

### 问题描述

在下载页面请求局域网内的aria2和远程服务器的aria2均无法推送 连接不上

### 脚本版本

v2.1.3-preview

### 浏览器版本

Google Chrome 版本 98.0.4758.82

### 播放器版本

最新版

### 错误信息

```shell
没有
```

### 附加截图

![QQ截图20220214185632](https://user-images.githubusercontent.com/46465612/153852599-2647d0e2-5130-449e-a964-d1edd17c8b9b.png)
![QQ截图20220214185713](https://user-images.githubusercontent.com/46465612/153852630-77e7e6cf-3909-4185-ad3f-a03c782e3b2f.png)

**Comment by mouzi3102** [comment]
跪求作者大大给我解决办法

**Comment by the1812** [comment]
检查下油猴的 XHR 安全权限有没有开
<img width="844" alt="image" src="https://user-images.githubusercontent.com/26504152/153853784-3d681159-4d0b-4e62-b175-589c6f382243.png">
<img width="865" alt="image" src="https://user-images.githubusercontent.com/26504152/153853817-b2854484-8f3e-4b2d-bc37-218f603e6b83.png">

类似 issue: #2974

**Comment by mouzi3102** [comment]
> 类似问题：#2974
> 
> 检查下油猴的 XHR 安全权限没有开启 <img alt="图片" width="844" src="https://user-images.githubusercontent.com/26504152/153853784-3d681159-4d0b-4e62-b175-589c6f382243.png"> <img alt="图片" width="865" src="https://user-images.githubusercontent.com/26504152/153853817-b2854484-8f3e-4b2d-bc37-218f603e6b83.png">
开了

**Comment by mouzi3102** [comment]
查看为开了
请看图
现在已经关闭
![QQ截图20220214192350](https://user-images.githubusercontent.com/46465612/153855471-43cf1eb2-f66a-437d-bb6c-d51d3b8ab1b7.png)

**Comment by the1812** [comment]
白名单要打开, 用户域名那里添加一个 `*`

**Comment by mouzi3102** [comment]
感谢作者大大，我添加了192.168.31.2，也成功了，我再加一个*
![成功](https://user-images.githubusercontent.com/46465612/153856055-3c3166d0-a1a2-494e-b94a-3272da57d994.png)

**Comment by mouzi3102** [comment]
成功反馈图片+1
![成功返图](https://user-images.githubusercontent.com/46465612/153856365-7518b12d-6b28-4904-a26b-21e9d6256fbd.png)
