### ISSUE TITLE
打开删除广告后夜间模式失效

### ISSUE THREAD

**Issue by KiDisplayBlueScreen** [the1812/Bilibili-Evolved#302]
**关于哪一项功能**

**问题描述**

**脚本版本**

1.10.0

**浏览器版本**

 Chrome 79.0.3945.79 64bit

**错误信息**

**附加截图**

**Comment by the1812** [comment]
控制台(Ctrl+Shift+I)有无报错? 顺便确认一下脚本是否安装完整? (拉到最底下应该是3267行)
<img width="400" src="https://user-images.githubusercontent.com/26504152/72957970-844f9c80-3de0-11ea-9a8f-93a109d50063.png">

**Comment by KiDisplayBlueScreen** [comment]
现在可以了,应该是更新时出了点问题

**Comment by zaonie** [comment]
同样问题过来的，其实每次更新时夜间模式都会有几天不能用。（只黑顶栏，不黑剩下的页面。）
都是过几天莫名奇妙就好了的。

（因为我重置浏览器次数较多。。所以经常会重装or更新脚本）

**Comment by the1812** [comment]
那应该是夜间模式加载方式的bug, 其他功能内置于脚本直接能用, 夜间模式需要从GitHub预览版分支那下载最新的夜间样式后才能启动
而从GitHub下载东西的成功率来看, 确实就会导致几天不能用...
我改一改 在下载成功前也先用着脚本内置的先

**Comment by zaonie** [comment]
原来如此~~感谢大佬~~
爱你。
