### ISSUE TITLE
插件无法加载

### ISSUE THREAD

**Issue by LittleSky233** [the1812/Bilibili-Evolved#303]
版本1.10.0
进入bilibili后插件侧栏与导航栏全部消失，刷新无法解决
图片：https://sm.ms/image/t2VHM3ObfEhcuAx

**Comment by the1812** [comment]
控制台(Ctrl+Shift+I)有什么错误信息吗?

**Comment by LittleSky233** [comment]
没有报错

**Comment by LittleSky233** [comment]
> 控制台(Ctrl+Shift+I)有什么错误信息吗?

没有报错。
![屏幕截图](https://user-images.githubusercontent.com/49095615/73061454-2badfb80-3ed5-11ea-9db3-8f0ea951216d.png)

**Comment by the1812** [comment]
脚本安装是否完整? 进入编辑拉到底下应该有3267行

**Comment by LittleSky233** [comment]
重新安装脚本后问题已解决，谢谢
