### ISSUE TITLE
最近使用网页左侧对应功能和设置按钮消失

### ISSUE THREAD

**Issue by PFP1st** [the1812/Bilibili-Evolved#3032]
### 对应功能

下载部分新功能后，网页左侧设置和功能开关按钮消失

### 问题描述

功能都能运行，但是按钮消失导致无法进行各个功能开关调整

### 脚本版本

2.1.3

### 浏览器版本

chrome

### 错误信息

```shell
未显示报错但是网页左侧设置按钮消失
```

### 附加截图

![image](https://user-images.githubusercontent.com/52556889/154786872-b4ec7680-434a-4bf3-8a0e-ebe436e128ad.png)

**Comment by haaayoo** [comment]
注意到这个问题了，应该是一个“无效的功能代码错误”之后触发的bug。目前我的解决方案是完全卸载脚本后，重新安装

**Comment by sakuraMY** [comment]
注意，下载组件包会自动下载一个“自动隐藏侧栏”的组件，彻底卸载脚本后，再下次安装组件包时，在“工具”一栏里面找到，关闭即可

**Comment by myaijarvis** [comment]
卸载后重新安装还是没有显示左侧设置按钮，控制台无任何报错信息

**Comment by sakuraMY** [comment]
> 卸载后重新安装还是没有显示左侧设置按钮，控制台无任何报错信息

请检查卸载后是否在管理面板完全清楚脚本数据
