### ISSUE TITLE
更新后RPC功能失效，发送的下载链接无法下载

### ISSUE THREAD

**Issue by dfmjndm** [the1812/Bilibili-Evolved#3048]
### 对应功能

更新前两台服务器都是正常使用的，更新后一台服务器显示无法连结，一台成功发送了链接但是下载大小为0kb
附截图
![image](https://user-images.githubusercontent.com/57401901/155132463-51223522-24d5-4509-9dc2-d621f4cbc10b.png)

非插件fa发送链接下载功能正常

### 问题描述

任意视频

### 脚本版本

1.12.22

### 浏览器版本

98.0.4758.102（正式版本） （64 位）

### 播放器版本

*

### 错误信息

```shell
*
```

**Comment by the1812** [comment]
旧版脚本早停更了

**Comment by dfmjndm** [comment]
> 旧版脚本早停更了

更新了v2，安装RPC插件后，以数字域名连结会报“无法连接到RPC主机, error = {"responseText":"","response":null,"readyState":4,"responseHeaders":"","status":0,"statusText":"","error":"Refused to connect to”
以域名连结下载可行。

**Comment by the1812** [comment]
可以看看 #3010 的解决方法

**Comment by dfmjndm** [comment]
可以解决，感谢作者大大
