### ISSUE TITLE
大佬做个根据文件名自动混流的脚本行不？

### ISSUE THREAD

**Issue by tfl117** [the1812/Bilibili-Evolved#3057]
### 对应功能

大佬做个根据文件名自动混流的脚本行不？

### 问题描述

大佬做个根据文件名自动混流的脚本行不？
下载好多p视频还要手动混流比较麻烦
做个基于ffmpeg.exe或者mkvtoolnix的自动混流工具行不行？
就是跟具文件名和文件类型能把Bilibili-Evolved下载的音频视频一键混流到一起（同一文件夹下的）

### 脚本版本

。。。

### 浏览器版本

。。。

### 错误信息

```shell
。。。
```

**Comment by the1812** [comment]
#1472

**Comment by tfl117** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    当前b站h.265音视频分离文件有体积优势，问题是手动合并略显麻烦h.264编码flv封装MP4啥的不是问题，有工具的大佬可能理解错我意图了，下265哪怕手动混流也是比flv快不少的，尤其是长视频
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    在2022年2月26日 19:03，Grant ***@***.***> 写道： 



#1472

**Comment by the1812** [comment]
那个只是 flv 转 mp4, 自己换下命令就可以合并两个 m4s
