### ISSUE TITLE
求支持拜年祭视频下载！（祝作者新年快乐）

### ISSUE THREAD

**Issue by 1357310795** [the1812/Bilibili-Evolved#307]
拜年祭视频地址：https://www.bilibili.com/blackboard/bnj2020.html
当前程序版本：1.10.0

**Comment by the1812** [comment]
新年快乐 单集目前应该可以下载的 等我看完拜年祭就弄批量

**Comment by 1357310795** [comment]
谢谢作者！回复很及时呢！

**Comment by FujimaruJin** [comment]
可下载了，谢谢

**Comment by the1812** [comment]
由于拜年祭页面比较特殊 需要在里面至少切换一集后再进入附加功能才会有下载视频的选项 下载窗口加载完成后还会自动关闭一次 这之后才能正常下载
预览版刚刚更新了批量支持 稍后会推送给正式版
当然也可以等活动过去了 拜年祭变成普通视频页面就可以像往常那样下载
