### ISSUE TITLE
功能栏里空空如也

### ISSUE THREAD

**Issue by RomanticMG** [the1812/Bilibili-Evolved#3070]
### 对应功能

![image](https://user-images.githubusercontent.com/29222534/155880827-141cae78-8492-4322-9d7b-4384f3efdd11.png)

### 问题描述

edge和chrome都试过，油猴和暴力猴也试过了，功能里一直空空如也，没有效果

### 脚本版本

v2.1.5-4-gc5921fb3b

### 浏览器版本

Microsoft Edge 版本 98.0.1108.62 (官方内部版本) (64 位)

### 播放器版本

HTML5播放器 V2.75.0

### 错误信息

```shell
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/international-home/international-home.7e4f94bb23fb00630f149c6a65e3d222854a8a69.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/vue.min.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/international-home/css/international-home.1.7e4f94bb23fb00630f149c6a65e3d222854a8a69.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/international-home/1.international-home.7e4f94bb23fb00630f149c6a65e3d222854a8a69.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/international-home/css/international-home.0.7e4f94bb23fb00630f149c6a65e3d222854a8a69.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### 附加截图

![QQ图片20220227193105](https://user-images.githubusercontent.com/29222534/155880764-fa1b8565-35c5-4244-a398-72e44207d9fd.png)

**Comment by the1812** [comment]
默认就是空的啊, 想要什么功能自己装
![image](https://user-images.githubusercontent.com/26504152/155883325-ea582041-f28d-483e-b2ff-258eef4d623e.png)

**Comment by RingingVolcano** [comment]
本体只是一个管理器 需要在仓库里选择想用的功能组件安装

**Comment by RomanticMG** [comment]
> 本体只是一个管理器 需要在仓库里选择想用的功能组件安装



> 默认就是空的啊, 想要什么功能自己装 ![image](https://user-images.githubusercontent.com/26504152/155883325-ea582041-f28d-483e-b2ff-258eef4d623e.png)

谢谢

**Comment by DDuann027** [comment]
仓库里面在线  安装了   刷新重启还是空空如也

**Comment by zoeycz66** [comment]
我也是在仓库里在线安装了但是刷新重新还是空的

**Comment by nanbobike** [comment]
相同问题
1.已经安装
![image](https://user-images.githubusercontent.com/59313112/169687476-fa31e229-75c8-4546-ab5d-cd5a24c3c0de.png)

![image](https://user-images.githubusercontent.com/59313112/169687495-98c72fa1-0a82-4e2c-99f4-734db8e8363a.png)
![image](https://user-images.githubusercontent.com/59313112/169687504-27d12e8c-e308-4061-a466-798dfa7584fb.png)
2.但还是空的
![image](https://user-images.githubusercontent.com/59313112/169687517-85aa32e1-0c05-4a7e-9458-a4ba5f7bcba0.png)

**Comment by actforjason** [comment]
到视频页面刷新会出来相应功能
