### ISSUE TITLE
下载字幕失败

### ISSUE THREAD

**Issue by michaellongge163** [the1812/Bilibili-Evolved#3073]
### 对应功能

下载视频

### 问题描述

选的json字幕，0个成功15失败
还有，下载视频 - aria2 输出支持这个怎么用
还有，下载视频能不能保存文件名改成标题

### 脚本版本

没找到

### 浏览器版本

edge

### 错误信息

```shell
没
```

**Comment by Geeyun-JY3** [comment]
文件名问题：#3062

**Comment by leefty-1024** [comment]
这个问题好像还是没有解决呀
