### ISSUE TITLE
开启清爽首页后首页上的视频封面会快速频闪

### ISSUE THREAD

**Issue by Dopamine2333** [the1812/Bilibili-Evolved#3074]
### 对应功能

清爽首页
Commit: b1ca632fb
内部名称: freshHome

### 问题描述

开启清爽首页后首页上的视频封面会快速频闪，由正常有封面切换到空白，再切换回来，频率非常高，大概1s能够切换两三次（见附录截图）并且只要开启该功能后会持续进行频闪。尝试清除B站的cookies也无法解决该问题。
此外朋友的电脑上开启该功能不会频闪，我们两个人都是新下载的该功能，只有我开启之后会出现该问题，他只下载了脚本的部分功能，我下载了脚本几乎全部的功能，但是并没有全部开启

### 脚本版本

v2.1.5-preview

### 浏览器版本

 Chrome 版本 98.0.4758.102（正式版本） （64 位）

### 播放器版本

2.75.3-rc.3220.0

### 播放策略

AVC

### 错误信息

```shell
Failed to load resource: the server responded with a status of 403 ()
```

### 附加截图

<img width="1280" alt="Snipaste_2022-03-02_16-09-49" src="https://user-images.githubusercontent.com/38375576/156322544-b6a9d186-6a18-4910-aaec-c9432464951b.png">
<img width="1280" alt="Snipaste_2022-03-02_16-09-58" src="https://user-images.githubusercontent.com/38375576/156322567-b92d8208-9f4a-4e5e-9fe7-c50a7b8c8435.png">
<img width="416" alt="Snipaste_2022-03-02_16-21-06" src="https://user-images.githubusercontent.com/38375576/156322845-544272cf-f367-482d-bfef-fb4968e519a2.png">

**Comment by the1812** [comment]
是不是 #3043 那种

**Comment by theblueandblackcrow** [comment]
我猜你应该安装了某个去广告扩展插件
