### ISSUE TITLE
360全景视频 鼠标拖动改变视角 功能失效

### ISSUE THREAD

**Issue by frostnotfall** [the1812/Bilibili-Evolved#3088]
### 对应功能

无对应功能

### 问题描述

禁用Bilibili-Evolved，原生观看360度全景视频时，可以使用鼠标拖动来改变视角。
启用 Bilibili-Evolved 后，禁用所有安装的插件，观看360度全景视频时，改变视角的功能失效，只变成了播放/暂停

### 脚本版本

v2.1.5-4-gc5921fb3b

### 浏览器版本

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.105 Safari/537.36

### 播放器版本

2.75.3-3cdbff07

### 播放策略

默认

### 错误信息

```shell
未观察到错误信息
```

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved#安装
> 注意事项
> - 做好觉悟, 脚本开启后不能使用弹幕点赞和举报, 全景视频不能用鼠标拖拽视角(只能用键盘操作), 对性能也有较大影响.

**Comment by frostnotfall** [comment]
> [https://github.com/the1812/Bilibili-Evolved#安装](https://github.com/the1812/Bilibili-Evolved#%E5%AE%89%E8%A3%85)
> 
> > 注意事项
> > 
> > * 做好觉悟, 脚本开启后不能使用弹幕点赞和举报, 全景视频不能用鼠标拖拽视角(只能用键盘操作), 对性能也有较大影响.

Got it
