### ISSUE TITLE
清爽首页有两个模块貌似获取不到

### ISSUE THREAD

**Issue by Amhertx** [the1812/Bilibili-Evolved#3092]
### 对应功能

清爽首页
Commit: b1ca632fb

![Snipaste_2022-03-06_22-26-28](https://user-images.githubusercontent.com/46993971/156927524-1b3ed8f9-b602-435f-95ff-2bad74e5e1e5.png)
![Snipaste_2022-03-06_22-26-35](https://user-images.githubusercontent.com/46993971/156927536-33e5de3c-8acf-4644-b7e7-851c3dd3b902.png)

### 问题描述

这两个模块没获取到值，没在页面显示

### 脚本版本

v2.1.5-4-gc5921fb3b

### 浏览器版本

版本 4.3.9.248（正式版本） （32 位） (Chromium 86.0.4240.198)

### 错误信息

```shell
控制台没有返回报错信息， 如上图
```

**Comment by the1812** [comment]
我还没做完呢

**Comment by Amhertx** [comment]
😂😂啊这，刚看了下是预览频道，催更催更，加油
