### ISSUE TITLE
下载视频能否提供原生mp4格式

### ISSUE THREAD

**Issue by lianmengkexin** [the1812/Bilibili-Evolved#310]
**关于哪一项功能**
目前下载视频只支持flv和DASH，这两种格式都可能需要手动整合，很不方便，能否提供如图这种原生mp4格式的视频下载呢？

**期望的效果**
![1](https://user-images.githubusercontent.com/60421663/73334786-929e2c80-42a8-11ea-9cb2-3fadd4eb70f9.jpg)
![2](https://user-images.githubusercontent.com/60421663/73334807-a0ec4880-42a8-11ea-90ae-4300b8cf53b9.jpg)

**脚本版本**

正式版 1.10.0

**Comment by the1812** [comment]
因为b站没有提供原生的mp4源 所以我这也没有

**Comment by lianmengkexin** [comment]
图上这种应该是B站原生的mp4源吧
http://upos-sz-mirrorcos.bilivideo.com/upgcxcode/47/40/126654047/126654047-1-208.mp4?e=ig8euxZM2rNcNbNj7zdVhwdlhbTahwdVhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&ua=tvproj&uipk=5&nbs=1&deadline=1580294619&gen=playurl&os=cosbv&oi=1964809609&trid=73158663e81048558f0034e6af39ed8fT&upsig=cab13c92ebaf860324db82df65e490dd&uparams=e,ua,uipk,nbs,deadline,gen,os,oi,trid&mid=49811844&WMHME=1

**Comment by the1812** [comment]
这条链接你是如何获取到的?
(网络问题看不到图)

**Comment by lianmengkexin** [comment]
用Android APP“投屏”功能得到的，我是想既然这种方式能得到原生的mp4地址那b站大概是有提供原生的mp4源，所以冒昧提了这个建议。
投屏功能原生是投给电视的，我的出发点本来是想知道它为什么不支持投屏弹幕，百度一下就有了如下操作：
1. 打开Windows 8系统自带的Windows Media Player→媒体流→勾选“允许远程控制我的播放器”和“自动允许设备播放我的媒体”
2. 让处于同一WIFI网络下的Android APP打开任意视频并点击右上角“TV”标志的投屏功能，就可以搜索到Windows Media Player，选中它Windows Media Player就开始播放视频
3. 在Windows Media Player里右键该视频打开播放列表，右键列表中正在播放的视频就可以从属性中复制到该地址
ps：百度说似乎是要开始Windows的共享与网络发现功能，这大概是默认开启的，所以操作时跳过了
  Windows 10好像自带接收投屏的功能所以不用使用Windows Media Player这么麻烦
  这条地址下载时好像不会报403，用百度网盘都可以离线，但似乎是有时效，所以我贴出的地址与图片中不完全一致，是重新获取过的

不知道以上内容能否为你提供思路，发现这种方法时是真的很惊喜，个人猜想投屏这种功能是投给电视的，而TV端大概不支持flv和DASH吧(联想到HTML5也不原生支持flv)，所以b站大概是真的有而且不得不提供原生mp4源吧。只是不知道用脚本能不能获取到，对比本脚本提供下载的flv地址，差异好像只有文件名mp4和参数最后的&WMHME=1，其他的内容是真的看不懂……

**Comment by the1812** [comment]
下载地址也都是由某个API生成的, 所以会有一大堆神秘参数和时效性. 我对Android不了解, 或许你有办法抓包找到这个API的网址, 这样我可以再进一步研究下.
有没有mp4源不好说, 也有可能是拿DASH源即时合并的(DASH合并成mp4速度很快).

**Comment by lianmengkexin** [comment]
很遗憾我并不会抓包，百度着尝试了手机端的Packet Capture、HTTPCanary和PC端的Fiddler，其他手机端app包括qq、微信都能抓到，唯独bilibili只要一抓包就提示“电波无法到达”，Fiddler报403错误，我是不知道bilibili怎么做到的

**Comment by the1812** [comment]
辛苦了, 这么看来bilibili还有反抓包机制?

**Comment by 63enjoy** [comment]
如果用flash播放器就可以抓到flv原格式

**Comment by dongdongkeer** [comment]
> 辛苦了, 这么看来bilibili还有反抓包机制?

太难了, 我研究的好多app也有反抓包, 我都要吐了
