### ISSUE TITLE
插件安装失败

### ISSUE THREAD

**Issue by UxNeas** [the1812/Bilibili-Evolved#3106]
### 对应功能

在线仓库安装插件

### 问题描述

在iPad等苹果移动设备上通过【拦截100】app 安装此脚本。打开b站后通过在线仓库可成功安装插件，但是一旦刷新网页之前安装的所有插件又会消失。

### 脚本版本

v2.1.5-6-gf0e551a94

### 浏览器版本

ipad OS 15.3.1

### 播放器版本

2.75.5-5291d7f1

### 错误信息

```shell
无法获取
```

### 附加截图

<img width="1366" alt="20220312_030032722_iOS" src="https://user-images.githubusercontent.com/23080096/158001240-af76c8b6-061e-4e23-b4be-486a56f83f2c.png">

**Comment by the1812** [comment]
不支持 iPad
