### ISSUE TITLE
后台打开视频网页脚本没有加载

### ISSUE THREAD

**Issue by agsdxcze** [the1812/Bilibili-Evolved#311]
火狐浏览器72.0.2 (64 位)
Tampermonkey v4.10.6105
正常打开没有问题，在后台打开视频网页，特别是多个网页，脚本通常不会加载，必须刷新才行
Chrome正常

**Comment by Coulomb-G** [comment]
请参考[#294 ](urlhttps://github.com/the1812/Bilibili-Evolved/issues/294)

**Comment by agsdxcze** [comment]
重启后没有效果
TypeError: "document.head is null"
    applyStyleFromText moz-extension://8cf02c56-ce4c-4d72-b4d4-810b2f5c286f/userscripts/Bilibili Evolved.user.js?id=501293ad-1aad-4451-9e86-8aae0adb0053:15512
    key moz-extension://8cf02c56-ce4c-4d72-b4d4-810b2f5c286f/userscripts/Bilibili Evolved.user.js?id=501293ad-1aad-4451-9e86-8aae0adb0053:15576
    setupColors moz-extension://8cf02c56-ce4c-4d72-b4d4-810b2f5c286f/userscripts/Bilibili Evolved.user.js?id=501293ad-1aad-4451-9e86-8aae0adb0053:15606
    ResourceManager moz-extension://8cf02c56-ce4c-4d72-b4d4-810b2f5c286f/userscripts/Bilibili Evolved.user.js?id=501293ad-1aad-4451-9e86-8aae0adb0053:15579
    tms_501293ad_1aad_4451_9e86_8aae0adb0053 moz-extension://8cf02c56-ce4c-4d72-b4d4-810b2f5c286f/userscripts/Bilibili Evolved.user.js?id=501293ad-1aad-4451-9e86-8aae0adb0053:16288
Bilibili Evolved.user.js:13241:11
    logError moz-extension://8cf02c56-ce4c-4d72-b4d4-810b2f5c286f/userscripts/Bilibili Evolved.user.js?id=501293ad-1aad-4451-9e86-8aae0adb0053:13241
    tms_501293ad_1aad_4451_9e86_8aae0adb0053 moz-extension://8cf02c56-ce4c-4d72-b4d4-810b2f5c286f/userscripts/Bilibili Evolved.user.js?id=501293ad-1aad-4451-9e86-8aae0adb0053:16422

**Comment by agsdxcze** [comment]
初步判定是和插件冲突，正在排除

**Comment by the1812** [comment]
从报错信息看跟 #283 挺像

**Comment by agsdxcze** [comment]
现在失灵时不灵的，放弃了

**Comment by the1812** [comment]
我试出来一次了 但后来又正常了
根据`document.head is null`也没查到跟火狐有关的什么信息

**Comment by the1812** [comment]
可能跟油猴的注入时机有关
https://github.com/greasemonkey/greasemonkey/issues/2515

**Comment by agsdxcze** [comment]
有什么办法呢？我试过了加载模式，无论“同时”还是“延后”都差不多。
现在情况是有的页面有效，有的无效

**Comment by the1812** [comment]
我想之后试试让脚本等`document.head`出来先

**Comment by agsdxcze** [comment]
操作不来，放弃了，谢谢了

**Comment by the1812** [comment]
目前只能先尽量别后台打开了 等我解决了再告诉你

**Comment by agsdxcze** [comment]
谢谢你的关注，期待你的好消息，真心感谢

**Comment by agsdxcze** [comment]
> 
> 
> 谢谢你的关注，期待你的好消息，真心感谢

**Comment by the1812** [comment]
试试看把这里改成`document-body`?
![image](https://user-images.githubusercontent.com/26504152/73604866-39990600-45d2-11ea-80dd-6d038d1f5e48.png)

**Comment by agsdxcze** [comment]
改过了，现在运行正常，非常感谢
