### ISSUE TITLE
夜间模式下头像出现灰色方块

### ISSUE THREAD

**Issue by suyi1117** [the1812/Bilibili-Evolved#3113]
### 对应功能

Commit: f0e551a94

### 问题描述

请问头像出现灰色方块是什么问题？ 脚本的夜间模式和系统主题冲突吗？

### 脚本版本

v2.1.5-6-gf0e551a94

### 浏览器版本

百分浏览器4.3.9.248

### 播放策略

AVC

### 错误信息

```shell
脚本无报错，只是功能不正常
```

### 附加截图

![Snipaste_2022-03-12_21-27-44](https://user-images.githubusercontent.com/48323038/158019841-1d5c82cf-05a4-40f7-ba6e-efc8b12bb87a.png)

**Comment by the1812** [comment]
哪个页面的

**Comment by suyi1117** [comment]
![Snipaste_2022-03-12_23-37-45](https://user-images.githubusercontent.com/48323038/158024593-f31b5d0c-1956-4763-8433-85a83d682196.png)
个人动态首页，在查看全部动态时点开评论就会出现回复者的ID头像会出现方块

**Comment by the1812** [comment]
你开了 dark reader 吧

**Comment by suyi1117** [comment]
没有安装dark reader，浏览器的主题为白天模式

**Comment by suyi1117** [comment]
找到原因了，与安装的自动翻页脚本冲突，禁用脚本后恢复正常，请关闭此主题
