### ISSUE TITLE
若头像是动态头像,自定义顶栏会造成在动态页面的长时间GPU高负载

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#3116]
### 对应功能

自定义顶栏

### 问题描述

前提1:在动态页面
前提2:头像是gif动图
前提3:开启自定义顶栏

依照我个人老爷机750ti的情况,在页面没有头像外的动态资源情况下,GPU占用约4%
![image](https://user-images.githubusercontent.com/14146754/158048295-9dc8f866-c133-4c0a-be2a-cf5c2c48163d.png)

但是页面偶尔会看着看着就出现GPU高占用的情况而且长时间无法释放
而且此时切换标签或者动态页面手动滑下一点,GPU就会瞬间恢复正常
![3](https://user-images.githubusercontent.com/14146754/158048465-9870133a-450e-4a01-a02b-fc847f322b18.gif)

其他B站的页面包括卡死人的首页都没发现这个情况

### 脚本版本

2.1.5

### 浏览器版本

99

### 错误信息

```shell
0
```

**Comment by the1812** [comment]
关掉背景模糊试试? Chrome 对这个效果的优化很差

**Comment by u2shana** [comment]
> 关掉背景模糊试试? Chrome 对这个效果的优化很差

关了背景模糊之后好像还真不出现了
