### ISSUE TITLE
插件有些视频没法下载。

### ISSUE THREAD

**Issue by positionm** [the1812/Bilibili-Evolved#312]
**关于哪一项功能**

哔哩哔哩有些视频不能下载

**问题描述**

视频链接获取失败，请确认当前账号有下载权限后再试

**脚本版本**

正式版1.10版

**浏览器版本**

firefox68.4.2esr

**错误信息**

**附加截图**
![图片](https://user-images.githubusercontent.com/42512824/73452186-53550600-43a4-11ea-84c9-aa88d5694189.png)

**Comment by Coulomb-G** [comment]
能够下载的清晰度取决于当前登录的账号, 例如「高清 1080P60」需要已登录大会员账号.

**Comment by positionm** [comment]
弄好了 谢谢
