### ISSUE TITLE
清爽首页最大宽度无法更改，超宽屏下体验较差

### ISSUE THREAD

**Issue by SunnySissi** [the1812/Bilibili-Evolved#3120]
### 对应功能

清爽首页，Commit: 03af3fac2

### 问题描述

[主页面](https://www.bilibili.com/)

### 脚本版本

v2.1.6-preview

### 浏览器版本

版本 99.0.1150.39 (正式版本) (64 位)

### 播放器版本

HTML5播放器 V2.71.0

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

![Snipaste_2022-03-14_10-51-38](https://user-images.githubusercontent.com/92515662/158096666-e4f0c37a-3ff6-4fea-8ec5-f8ea37ff6c85.png)

**Comment by the1812** [comment]
不是有个最大宽度的选项吗

**Comment by SunnySissi** [comment]
设置后自动恢复1440

**Comment by the1812** [comment]
范围是 1000~3000, 超了的话会弹回 1440

**Comment by SunnySissi** [comment]
设置2560也是自动恢复1440

**Comment by SunnySissi** [comment]
![动画](https://user-images.githubusercontent.com/92515662/158124018-a25ba1df-cb70-41e9-97c1-028fa8ea9279.gif)

**Comment by the1812** [comment]
了解了, 之后会修复一下

**Comment by SunnySissi** [comment]
嗯嗯，辛苦啦
