### ISSUE TITLE
自定义顶栏的透明填充失效

### ISSUE THREAD

**Issue by StqGo** [the1812/Bilibili-Evolved#3126]
### 对应功能

自定义顶栏
Commit: 77d4e04d0

### 问题描述

首页

### 脚本版本

v2.1.6

### 浏览器版本

Microsoft Edge 版本 99.0.1150.39 (正式版本) (64 位)

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/96059236/158135872-ab71d81a-71fa-4994-9245-54d2d51da5b9.png)

**Comment by syj819** [comment]
我也变成这样了

**Comment by the1812** [comment]
绝了, b 站首页横幅刚好更新了

**Comment by yuijker** [comment]
现在情况更加复杂了，b站直接把一个游戏也加进顶栏里了。
