### ISSUE TITLE
极简首页样式显示问题

### ISSUE THREAD

**Issue by XZL16** [the1812/Bilibili-Evolved#313]
**问题描述**
极简首页样式显示有些许问题，疑似为up主无头像所致，如下图所示
![1.jpg](https://i.loli.net/2020/01/31/UuryhS6Jnioq9Xp.jpg)

[该up主个人空间](https://space.bilibili.com/3208744)

**脚本版本**
正式版1.10.0

**浏览器版本**
360极速浏览器
版本号：11.0.2216.0
内核版本：69.0.3497.100

**Comment by the1812** [comment]
我忘设尺寸了...

**Comment by LTHarry** [comment]
这个问题在 Surface Pro 4 这样的高缩放百分比显示设备上没有遇到（未修改样式），在 1080P 100% 缩放的时候会遇到。
