### ISSUE TITLE
在比较罕见的情况下，isBwpVideo 判断逻辑错误

### ISSUE THREAD

**Issue by LonelySteve** [the1812/Bilibili-Evolved#3131]
### 对应功能

https://github.com/the1812/Bilibili-Evolved/blob/9f452209fed54a6e7a9bdf8cb3c3f7c87bb71e5e/src/core/utils/index.ts#L71

### 问题描述

来自 PR #2746 的测试异常追踪：

![image](https://user-images.githubusercontent.com/34429322/158396994-b876dcd2-a630-4827-9a6a-fecaa881f706.png)

在特定情况下，页面中会同时出现满足 `.bilibili-player-video` 和 `bwp-video` 选择器的情况：

![demo](https://user-images.githubusercontent.com/34429322/158398631-7d91a77c-e59c-42a6-9744-65e73f5b72b7.gif)

我也不清楚如何 100% 复现，目前是在多 P 视频，例如 [BV1wT4y1D729](https://www.bilibili.com/video/BV1wT4y1D729/) 中，通过反复切换分集，并调整倍速触发的（不过看起来和倍速没关系）.

出现这种情况时，`isBwpVideo` 的判断就有问题，会错误地将非 `bwp` 播放器判断为 `bwp` 播放器，从而导致 `playerAgent.query.video.element()` 无法获取到正确的元素.

**推荐修复方式**：

```javascript
 export const isBwpVideo = () => unsafeWindow.__ENABLE_WASM_PLAYER__ as boolean || Boolean(dq('.bilibili-player-video bwp-video')) 
```

### 脚本版本

v2.1.6

### 浏览器版本

Chrome 99.0.4844.51

### 错误信息

```shell
无
```

**Comment by the1812** [comment]
- `.bilibili-player-video` 在番剧区是不存在的, 可能用 `#bilibili-player` 好些
- `isBwpVideo` 在最新版中因为 #3046 已经更换为异步的了, 你可能得检查下调用的地方

另外, 看截图里日志的 API 你是打算直接写在 PR 里了? 我以为是我来写的(

**Comment by LonelySteve** [comment]
> isBwpVideo 在最新版中因为 https://github.com/the1812/Bilibili-Evolved/issues/3046 已经更换为异步的了, 你可能得检查下调用的地方

好吧，我的代码有点落后，但即使基于最新版本估计也会有该问题.

> 另外, 看截图里日志的 API 你是打算直接写在 PR 里了? 我以为是我来写的(

这个是我用 vsc 的 clg 插件临时打上去的，用来调试.  嗯，确实应该你来写，我肝不动了（
