### ISSUE TITLE
火狐 快速收藏 右键失效。

### ISSUE THREAD

**Issue by visiLi** [the1812/Bilibili-Evolved#3137]
### 对应功能

快速收藏【Commit 03af3fac2】 

### 问题描述

火狐浏览器【快速收藏 】右键失效。右键是浏览器默认的右键

### 脚本版本

 v2.1.6-preview 

### 浏览器版本

火狐浏览器V98.0

### 播放策略

默认

### 错误信息

```shell
没有错误信息
```

### 附加截图

![截图_20223118023136](https://user-images.githubusercontent.com/42717403/158950702-fd5a7777-29c1-4561-9bd7-26e020ae4abe.png)

**Comment by the1812** [comment]
你是不是开了什么解除右键限制的插件/脚本

**Comment by visiLi** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        嗯 是有一个
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年3月20日 10:26，Grant ***@***.***> 写道： 




你是不是开了什么解除右键限制的插件/脚本

**Comment by visiLi** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    但是 在edge没事啊
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年3月20日 ***@***.***> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        嗯 是有一个
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年3月20日 10:26，Grant ***@***.***> 写道： 




你是不是开了什么解除右键限制的插件/脚本

**Comment by visiLi** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    设置了排除  好了
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年3月20日 ***@***.***> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    但是 在edge没事啊
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年3月20日 ***@***.***> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        嗯 是有一个
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年3月20日 10:26，Grant ***@***.***> 写道： 




你是不是开了什么解除右键限制的插件/脚本

**Comment by visiLi** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            https://www.github.com/Cat7373/ 
        
    这个是他的链接
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年3月20日 ***@***.***> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    设置了排除  好了
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年3月20日 ***@***.***> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    但是 在edge没事啊
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年3月20日 ***@***.***> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        嗯 是有一个
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年3月20日 10:26，Grant ***@***.***> 写道： 




你是不是开了什么解除右键限制的插件/脚本

**Comment by Holiday2019** [comment]
无论是在火狐101，还是Edge102，开启快速收藏后，均未在页面中出现“快速收藏”的图标
![图片](https://user-images.githubusercontent.com/54856595/173164203-ce0e39cc-4ea6-4706-aada-09c3c72c0d47.png)
![图片](https://user-images.githubusercontent.com/54856595/173164211-2287f265-17b6-4078-9267-ff0ab2031325.png)
