### ISSUE TITLE
自定义顶栏功能在台式机中显示有问题，显示不完整

### ISSUE THREAD

**Issue by githubli2020** [the1812/Bilibili-Evolved#314]
**问题描述**
自定义顶栏功能在台式机中显示有问题，显示不完整。页面错位。

看到类似问题，缩放可以解决，但是缩放后，播放历史界面页面错位。但是笔记本没有问题，台式机显示不正常。

**脚本版本**
<预览离线版 560.97-->

**浏览器版本**
<!-百分浏览器  4.1.7.182-->

**错误信息**
![1](https://user-images.githubusercontent.com/60499920/73517865-b9d73400-4437-11ea-9c73-e50f9f616729.png)

**附加截图**
![2](https://user-images.githubusercontent.com/60499920/73517886-cd829a80-4437-11ea-9fa1-d2c63927a5c2.png)

**Comment by the1812** [comment]
分辨率是多少？

**Comment by githubli2020** [comment]
> 分辨率是多少？

1440*900

**Comment by the1812** [comment]
可以去附加功能里的`顶栏布局`隐藏掉一些你用不着的入口, 减少总长度
