### ISSUE TITLE
下载视频和弹幕的选项消失，获取封面同样无法使用

### ISSUE THREAD

**Issue by 2019087linghao** [the1812/Bilibili-Evolved#3145]
### 对应功能

下载视频和弹幕；
获取封面；

### 问题描述

如题，我尝试了好多视频，结果都是无法显示下载视频和弹幕的选项

### 脚本版本

Bilibili Evolved v2.1.6

### 浏览器版本

chrome 97.0.4692.99

### 播放策略

默认

### 错误信息

```shell
我也不是很懂，所以给你截图在下面
```

### 附加截图

![image](https://user-images.githubusercontent.com/63346962/159096818-ee9c1f52-329e-4111-a221-7588e0ae0170.png)
![image](https://user-images.githubusercontent.com/63346962/159096587-d6671532-b28a-4459-9980-0ee99547485f.png)

**Comment by cheshuai123** [comment]
同，换了正式版和测试版都一样。

**Comment by 2019087linghao** [comment]
来自QQ邮箱自动回复邮件。出现BUG。我将在维护结束后给你回复。工具：传送门数学：传送门--Odin

**Comment by kkzhh** [comment]
大概率是播放器更新了的原因，大部分功能失效了，期待作者早日适配吧

**Comment by the1812** [comment]
原因可能同 #3147, 但是这里没有反馈播放器版本所以不是很确定

**Comment by kkzhh** [comment]
![图片](https://user-images.githubusercontent.com/8279143/159602061-c7720f9c-e5f9-48f0-8e16-fe3b189f3a46.png)

目前我这里也是出现了无法获取封面，默认播放器模式、倍速播放、快捷键、下载音频、逐帧播放等等和播放器相关的功能都失效了 ，刚看了一下播放器已经更新到3.6.9了

**Comment by the1812** [comment]
合并至 #3187
