### ISSUE TITLE
跳过90秒功能

### ISSUE THREAD

**Issue by Cleverambo** [the1812/Bilibili-Evolved#315]
**希望在播放器的工具栏上添加一个“跳过90秒”的按钮**

**一般番剧的片头曲都是90秒，此功能可以实现精准跳过片头曲**

**Comment by the1812** [comment]
打开`快捷键扩展`, 按`j`跳过85秒.

**Comment by Cleverambo** [comment]
> 打开`快捷键扩展`, 按`j`跳过85秒.

谢谢。
但是平板电脑模式下使用快捷键还是稍显麻烦。

**Comment by the1812** [comment]
触屏直接往右划啊

**Comment by Cleverambo** [comment]
> 触屏直接往右划啊

可是这样容易划得太多或者太少

**Comment by the1812** [comment]
记个大致的距离就行了, 我电脑用中速划过2/5左右的屏幕刚好跳op, 就算少几秒也问题不大
