### ISSUE TITLE
2.1.7在主页左侧的图标需要等待很久才出现

### ISSUE THREAD

**Issue by SunnySissi** [the1812/Bilibili-Evolved#3158]
### 对应功能

似乎是脚本本身的问题，未安装任何额外脚本仍有此问题

### 问题描述

没有找到具体的影响原因，但是重新安装脚本后无任何额外插件的情况下在主页依旧需要很久才会出现设置的小齿轮，在视频播放界面和以前一样都是立即出现的

### 脚本版本

v2.1.7-preview

### 浏览器版本

版本 99.0.1150.46 (正式版本) (64 位)

### 错误信息

```shell
[Intervention]Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
sentry-5.15.0.min.js:2 
        
       [Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
(匿名) @ sentry-5.15.0.min.js:2
warn$3 @ vendor.7eb80af4.js:1
useSSRContext @ vendor.7eb80af4.js:1
setup @ index.03779ba5.js:1
callWithErrorHandling @ vendor.7eb80af4.js:1
setupStatefulComponent @ vendor.7eb80af4.js:1
setupComponent @ vendor.7eb80af4.js:1
x @ vendor.7eb80af4.js:1
c @ vendor.7eb80af4.js:1
(匿名) @ vendor.7eb80af4.js:1
mount @ vendor.7eb80af4.js:1
t.mount @ vendor.7eb80af4.js:1
(匿名) @ index.03779ba5.js:1
```

### 附加截图

![image](https://user-images.githubusercontent.com/92515662/159460686-4cc73241-d0f2-49b2-89e4-1b893e793b6f.png)

![image](https://user-images.githubusercontent.com/92515662/159460947-d4b8920d-ee0e-41dc-9a02-61d80657f2d9.png)

**Comment by SunnySissi** [comment]
![image](https://user-images.githubusercontent.com/92515662/159462031-f8a1fa44-ce22-47da-8814-0c0524202347.png)

**Comment by SunnySissi** [comment]
![image](https://user-images.githubusercontent.com/92515662/159462258-bb32fd26-81aa-42dc-8cb9-2b1da9f1b271.png)

**Comment by Java-S12138** [comment]
> 

他是那种完全无法运行的状态, 左侧都没有显示出来功能按钮

**Comment by SunnySissi** [comment]
改成同时还是延迟很久才出现
大概有个5s到10s

**Comment by the1812** [comment]
打开 DevTools (F12 打开) 里 Network 面板, 刷新一次页面, 看看里面有没有啥东西卡了特别久? (Waterfall 那一栏会看起来很长)
![image](https://user-images.githubusercontent.com/26504152/159506754-f7d6f0c5-8647-4242-b8b1-6f834c03051c.png)

**Comment by SunnySissi** [comment]
下面这些都是在首页刷新完成后开始记录的
![image](https://user-images.githubusercontent.com/92515662/159634082-859dc06b-6e27-4d19-b44f-fa2f71a14703.png)

**Comment by SunnySissi** [comment]
这个是记录了所有的，红框内的隔了一会才出现
![image](https://user-images.githubusercontent.com/92515662/159634322-459a9c74-d68e-405a-b183-8329734cfd7d.png)

**Comment by SunnySissi** [comment]
不过今天看来比昨天好了很多，大概三四秒就可以出现

**Comment by myaijarvis** [comment]
我的一直都未出现过，不知道什么原因，控制台也没有任何报错

**Comment by SunnySissi** [comment]
目前来说已经没有这个问题了

**Comment by the1812** [comment]
估计是前阵子网络有波动
