### ISSUE TITLE
 无法下载 根本没有下载视频按钮

### ISSUE THREAD

**Issue by CanonLs** [the1812/Bilibili-Evolved#316]

**Comment by CanonLs** [comment]
已经登陆账号 一直错误错误

**Comment by Coulomb-G** [comment]
错误是指什么方面的错误,请截图报错信息和反馈相关信息

**Comment by Master-cai** [comment]
![image](https://user-images.githubusercontent.com/37432881/76044734-3361c500-5f96-11ea-9b0f-7a95624c6acb.png)
您好，我也遇到了这个问题，控制台报错如图

**Comment by the1812** [comment]
@Master-cai 你这个是依赖的库下载失败了, 请访问 https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js 试试看能不能正常加载
能的话再刷新看看, 或者重新装一下脚本

**Comment by Master-cai** [comment]
好的，确实是这个问题。
我把依赖换成了https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.15/lodash.min.js，就可以正常访问了。
cdn.jsdelivr.net的库我有梯子也无法访问，包括前边那个vue的库我也进行了替换才解决问题，不知道为什么，建议将 cdn更换一下。

**Comment by the1812** [comment]
过段时间再试试吧, 因为cdn.jsdelivr.net还被脚本用于提供GitHub的文件进行更新, 连不上的话就收不到任何脚本更新了

**Comment by Master-cai** [comment]
好的谢谢。
