### ISSUE TITLE
自定义顶栏的透明模式修复失效

### ISSUE THREAD

**Issue by StqGo** [the1812/Bilibili-Evolved#3162]
### 对应功能

自定义顶栏
Commit: 77d4e04d0

### 问题描述

2.1.7版本自定义顶栏修复失效

### 脚本版本

v2.1.7

### 浏览器版本

Microsoft Edge 版本 99.0.1150.46 (正式版本) (64 位)

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/96059236/159512643-e5c866a2-a07e-46d6-887b-761cde13faea.png)

**Comment by the1812** [comment]
你的组件没更新, 最新的应该是 65f5f15
可以用这个链接强制更新下:
https://github.com/the1812/Bilibili-Evolved/raw/master/registry/dist/components/style/custom-navbar.js

**Comment by doio** [comment]
好奇怪，我也是怎么更新都是 jsdelivr 的旧 commit 的版本，即使在自动更新器里面检查更新了。
看来只能一个一个全部都换成 github 的源了

**Comment by the1812** [comment]
jsDelivr 有 24h 的延迟, 现在还没刷新
