### ISSUE TITLE
夜间模式部分反色异常

### ISSUE THREAD

**Issue by AzusaHana** [the1812/Bilibili-Evolved#3167]
### 对应功能

样式-夜间模式
Commit: 84b92e6e4
内部名称: darkMode

### 问题描述

直播间部分牌子的等级反色异常
首页顶栏数字提示反色异常（原来是白色）

### 脚本版本

v2.1.7-preview

### 浏览器版本

Chrome 99.0.4844.74

### 错误信息

```shell
无
```

### 附加截图

![GPAP8@5R5%2NVECIXQ{KKUV](https://user-images.githubusercontent.com/100906636/159691430-72db6a7b-979c-437f-b30b-4d36e754cc12.png)
![D {%MWZ21{0B1$5C8NT@39Q](https://user-images.githubusercontent.com/100906636/159691921-ba8cb2a8-8328-4951-bc22-445928871a5d.png)
![image](https://user-images.githubusercontent.com/100906636/159691975-33968002-dd23-4775-9b3c-8f935cb128ba.png)

**Comment by the1812** [comment]
通用设置里, 文字颜色改成白色
