### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by Sliver-Ash** [the1812/Bilibili-Evolved#317]
所有视频都无法下载？说是请确认下载权限。

**Comment by Coulomb-G** [comment]
能够下载的清晰度取决于当前登录的账号, 例如高清 1080P60需要已登录大会员账号.
请确认你的账号下载权限

**Comment by Sliver-Ash** [comment]
抱歉，我傻了。没看到清晰度。谢谢大佬提供的插件。
