### ISSUE TITLE
清爽首页热门的刷新按钮没有请求新数据

### ISSUE THREAD

**Issue by Amhertx** [the1812/Bilibili-Evolved#3171]
### 对应功能

清爽首页

### 问题描述

热门的刷新按钮没有请求新数据，导致热门一直只有几个视频

### 脚本版本

v2.1.7

### 浏览器版本

版本 4.3.9.248（正式版本） （32 位） (Chromium 86.0.4240.198)

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/46993971/159828938-33b30d44-3871-4bab-9b49-281a115daea3.png)
![image](https://user-images.githubusercontent.com/46993971/159829316-0c0fe1f8-2a1b-4282-b212-910d502e5dee.png)

**Comment by the1812** [comment]
热门是一个全站榜单，你短时间内刷新怎么可能变

**Comment by Amhertx** [comment]
![image](https://user-images.githubusercontent.com/46993971/159842265-cb458b8b-49a4-4bc9-b384-979acdfa07c2.png)
我以为是哔哩哔哩的这个呢

**Comment by the1812** [comment]
你要原版那种得去组件选项里把个性化推荐打开

**Comment by Amhertx** [comment]
这样子🤣，谢谢
