### ISSUE TITLE
播放器升级,又一堆功能失效

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#3176]
### 对应功能

播放器

### 问题描述

![image](https://user-images.githubusercontent.com/14146754/159960263-ca3f8153-ad1d-4de9-af85-110534fb7169.png)
番剧区还是3.6,正常

### 脚本版本

2.1.7

### 浏览器版本

99

### 错误信息

```shell
1
```

**Comment by the1812** [comment]
合并至 #3187
