### ISSUE TITLE
EDGE浏览器下插件无法生效

### ISSUE THREAD

**Issue by zwr1036989059** [the1812/Bilibili-Evolved#3179]
### 对应功能

EDGE浏览器下插件无法生效
同时已测试，在chrome及Firefox中可正常生效

### 问题描述

在使用插件时无法生效，具体见下图
首页：
最上方栏位无显示，左侧功能无显示
![111](https://user-images.githubusercontent.com/102339948/160050486-ef835cd8-22ef-4985-a176-6d6b63780edf.png)

视频页：
插件未生效，最上方栏位无显示，左侧功能无显示
![222](https://user-images.githubusercontent.com/102339948/160050804-ecc4cd4b-8f3a-4fb5-9426-29c6f30bdfd3.png)

### 脚本版本

2.1.7

### 浏览器版本

Microsoft Edge 99.0.1150.52

### 错误信息

```shell
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/international-home/css/international-home.1.c1c88129c24496026c1d86d039b9350208473612.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/international-home/css/international-home.0.c1c88129c24496026c1d86d039b9350208473612.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### 附加截图

![image](https://user-images.githubusercontent.com/102339948/160052699-b26b3c3d-9138-457c-828d-c4e82b3bf7db.png)

**Comment by cumberjie** [comment]
我也是无法生效，无论是edge还是Chrome 都不行，都升级最新版了的。但v1版的office版就可以生效

**Comment by 37294** [comment]
找到解决方法了吗请问
