### ISSUE TITLE
夜间模式对选集列表适配不佳

### ISSUE THREAD

**Issue by hmk0407** [the1812/Bilibili-Evolved#3186]
### 对应功能

夜间模式

### 问题描述

开启夜间模式后，视频播放页的选集列表颜色未置暗，导致文字与背景同色，无法看清文字内容。

### 脚本版本

2.1.7

### 浏览器版本

360极速X 21.0.1082

### 错误信息

```shell
无错误。
```

### 附加截图

![微信截图_20220326103823](https://user-images.githubusercontent.com/50434062/160221890-1271cbb7-22ef-4656-be90-f8b08eced92e.png)

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/160221978-e39be5d8-ca05-4c8a-ac0c-5d8c15a02925.png)
