### ISSUE TITLE
视频播放器 3.x 版 问题汇总

### ISSUE THREAD

**Issue by the1812** [the1812/Bilibili-Evolved#3187]
### 对应功能

包括但不限于: 下载视频, 下载弹幕, 下载字幕, 查看封面, 跳过充电鸣谢

### 问题描述

#3145, #3147, #3176, #3177, #3182

由于我还是 2.x 版本, 所以无法复现以及适配, 如果有可以进入 3.x 版本播放器的方法也可以发在这.

### 脚本版本

v2.1.7

### 浏览器版本

Chrome 99.0.4844.84

### 播放器版本

大于 3

### 播放策略

默认

### 错误信息

```shell
N/A
```

**Comment by GeassAng** [comment]
还有快捷键也失效了。。

**Comment by kkzhh** [comment]
“默认播放器模式”也失效了

**Comment by programmerZe** [comment]
传统连播模式 也失效了

**Comment by czy006** [comment]
这个提升倍速播放也是无法使用了 重新安装也一样

**Comment by cheshuai123** [comment]
视频截图和逐帧调整也没了

**Comment by weituotian** [comment]
不能自动宽屏了

**Comment by ZetsuLAM** [comment]
去除投票等弹窗也失效了

**Comment by nicduke** [comment]
播放界面该有的功能都失效了。

**Comment by zhangningsd** [comment]
外置稍后再看也没了，快速收起评论好像也不行了

**Comment by H-a-r-r-o-w** [comment]
![image](https://user-images.githubusercontent.com/77455480/160599404-1744deea-43bf-46b9-b093-4806cf6c2f32.png)
插件新用户，想问一下黑夜模式这样应该不合理吧……？
文字没有反色，左右侧边栏没有变暗底白字

**Comment by Geeyun-JY3** [comment]
@H-a-r-r-o-w 动态去 #3191（这个 `夜间模式` 的问题已经知道了的：#3192）

**Comment by dongxiansuixin** [comment]
倍速相关的都没法用了

**Comment by homooooo** [comment]
功能那块视频下载没了，查看封面也用不了

**Comment by BaiBuCYBGT** [comment]
时间空降失效了

**Comment by lbq1121** [comment]
同样 倍速播放出了问题

![image](https://user-images.githubusercontent.com/24562314/163998574-936b6382-4cc3-45a5-8ecc-93a10e43efd1.png)

**Comment by REimyumi** [comment]
我是试着安装了一个插件，回到B站老版本，然后找回的
https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5

**Comment by REimyumi** [comment]
这个解决方案并不好，不推荐

**Comment by zhuo2019318103** [comment]
还是没有解决呗，也没有办法退到2.0以上版本啊？我看还在同步更新，但只有未登录状态才是2.x版本的播放器，很好奇你们是怎么保持在2.x的

**Comment by TOA-HI** [comment]
就目前为止似乎登录后是html5 3.xx的版本，无法显示侧边栏功能。
用无痕（不登录），开启Violentmonkey无痕，浏览器就是2.xx的版本，侧边栏正常。
凑合用一下没有问题，下载也正常，就是没那么清晰而已了

**Comment by qiuyue0** [comment]
直播全屏弹幕发送栏使用回车上屏编码会将已编辑内容发送，如果内容为空会隐藏播放控件，但是网页全屏时功能正常

**Comment by gaowez** [comment]
下载视频只有flv 格式有声音 其他格式都没有声音

**Comment by imshixin** [comment]
3.X中对倍速播放按钮的类名进行了修改，导致扩展倍速失效(或许还有其他改动)

> \registry\lib\components\video\player\common\speed\context.ts
```javascript
  video: {
    speedMenuList: '.bilibili-player-video-btn-speed-menu', /*3.X为 bpx-player-ctrl-playbackrate-menu  */
    speedMenuItem: '.bilibili-player-video-btn-speed-menu-list',/*3.X为 bpx-player-ctrl-playbackrate-menu-item   */
    speedNameBtn: '.bilibili-player-video-btn-speed-name',/*3.X为 bpx-player-ctrl-playbackrate-result  */
    speedContainer: '.bilibili-player-video-btn-speed',/*3.X为 bpx-player-ctrl-playbackrate  */
    active: '.bilibili-player-active',
    show: '.bilibili-player-speed-show',
  },
```

个人目前看到3.X对播放器class和`window.player.getMessageInfo`进行了修改

同时，为了让`播放前查看封面`功能恢复，需要对`observer.ts`做一定修改
https://github.com/the1812/Bilibili-Evolved/blob/0c128ba3f2d1a51eb1c20d5e630e9ca24644bbb2/src/core/observer.ts#L228-L229
```javascript
  if (unsafeWindow.player && unsafeWindow.player.getUserParams) {
    const info = unsafeWindow.player.getUserParams().input
```

https://github.com/the1812/Bilibili-Evolved/blob/0c128ba3f2d1a51eb1c20d5e630e9ca24644bbb2/src/core/observer.ts#L269-L270
```javascript
    aid: unsafeWindow?.aid?unsafeWindow.aid:unsafeWindow.player.getUserParams().input.aid,
    cid: unsafeWindow?.cid?unsafeWindow.cid:unsafeWindow.player.getUserParams().input.cid,
```

**Comment by sniperdown** [comment]
相比之下我更好奇作者为什么能保持在2.x版本，包括我在内登录之后都是3.x版本啊

**Comment by sniperdown** [comment]
> 相比之下我更好奇作者为什么能保持在2.x版本，包括我在内登录之后都是3.x版本啊

如果有能保持在2.x版本的方法也可以踢我一脚:/

**Comment by imshixin** [comment]
退出登录就会回到2.X-------- 原始邮件 --------发件人： sniperdown ***@***.***>日期： 2022年5月11日周三 凌晨2:13收件人： the1812/Bilibili-Evolved ***@***.***>抄送： imshixin ***@***.***>, Comment ***@***.***>主    题： Re: [the1812/Bilibili-Evolved] 视频播放器 3.x 版 问题汇总 (Issue #3187)



相比之下我更好奇作者为什么能保持在2.x版本，包括我在内登录之后都是3.x版本啊



如果有能保持在2.x版本的方法也可以踢我一脚:/

**Comment by imshixin** [comment]
> > 相比之下我更好奇作者为什么能保持在2.x版本，包括我在内登录之后都是3.x版本啊
> 
> 如果有能保持在2.x版本的方法也可以踢我一脚:/

退出登录就行了

**Comment by sniperdown** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我几乎不用邮箱，所以可能的话请换一种联系方式（QQ或者微信）。为因此造成的麻烦道歉。

**Comment by Geeyun-JY3** [comment]
灰度就是这样的

**Comment by shido520** [comment]
> 就目前为止似乎登录后是html5 3.xx的版本，无法显示侧边栏功能。 用无痕（不登录），开启Violentmonkey无痕，浏览器就是2.xx的版本，侧边栏正常。 凑合用一下没有问题，下载也正常，就是没那么清晰而已了

不是所有登陆后都是3.xx播放器，大会员登陆后就是3.xx，普通会员登陆后还是2.xx的播放器

**Comment by TOA-HI** [comment]
> > 就目前为止似乎登录后是html5 3.xx的版本，无法显示侧边栏功能。 用无痕（不登录），开启Violentmonkey无痕，浏览器就是2.xx的版本，侧边栏正常。 凑合用一下没有问题，下载也正常，就是没那么清晰而已了
> 
> 不是所有登陆后都是3.xx播放器，大会员登陆后就是3.xx，普通会员登陆后还是2.xx的播放器

甚是如此，无痕浏览就是不登录的模式，我没解释清楚
总之就是不登陆还是2.xx，登录就变3.xx了

**Comment by sniperdown** [comment]
> > 就目前为止似乎登录后是html5 3.xx的版本，无法显示侧边栏功能。 用无痕（不登录），开启Violentmonkey无痕，浏览器就是2.xx的版本，侧边栏正常。 凑合用一下没有问题，下载也正常，就是没那么清晰而已了
> 
> 不是所有登陆后都是3.xx播放器，大会员登陆后就是3.xx，普通会员登陆后还是2.xx的播放器

3.x是大会员专享？这大会员，不充也罢（摔

**Comment by sn0w01f** [comment]
> > 就目前为止似乎登录后是html5 3.xx的版本，无法显示侧边栏功能。 用无痕（不登录），开启Violentmonkey无痕，浏览器就是2.xx的版本，侧边栏正常。 凑合用一下没有问题，下载也正常，就是没那么清晰而已了
> 
> 不是所有登陆后都是3.xx播放器，大会员登陆后就是3.xx，普通会员登陆后还是2.xx的播放器

我是普通会员，登陆前2.xx版本，登陆后是3.xx，我账号是lv6（不知道和等级有没有关系）

**Comment by okyan123** [comment]
我目前找到一个解决方法，把视频加入到稍后再看，然后打开稍后再看进行播放，这个时候的播放器还是2.x，下载视频之类的各种插件都可以使用

**Comment by imshixin** [comment]
可以试试我的fork，自己编译一下基本功能能用了，在preview-fixes分支上

**Comment by ZetsuLAM** [comment]
说明一下最新遇到的情况。
在3月底播放器版本变成了3.X。
没有大会员，使用过firefox，chrome账号登录前后播放器版本均为3.X。
前两天（准确时间忘了，应该是20-24号这几天）跟人工客服资讯过切换播放器版本问题，并未得到解决。
今天登录账号播放器版本回到了2.X，并且出现前往新版选项，使用firefox隐私模式不登陆账号播放器版本为3.X。
现在感觉这个播放器版本可以通过给人工客服压力解决。

**Comment by sniperdown** [comment]
有大会员，今天上了一下发现变成2.x版本了

**Comment by yfw918** [comment]
今天莫名其妙回到2.x了，挺好

**Comment by imshixin** [comment]
我今晚播放器一直打不开，过了一会莫名其妙到2.X

**Comment by Howard20181** [comment]
貌似番剧区一直3.x播放器
这和普通投稿的3.x
播放器一样吗？

**Comment by Geeyun-JY3** [comment]
> 貌似番剧区一直3.x播放器 这和普通投稿的3.x 播放器一样吗？

番剧区的播放器上 3.x 其实早很多：#1992

**Comment by Howard20181** [comment]
> > 貌似番剧区一直3.x播放器 这和普通投稿的3.x 播放器一样吗？
> 
> 番剧区的播放器上 3.x 其实早很多：#1992

所以能不能基于番剧区的播放器适配？
不知道有没有区别

**Comment by imshixin** [comment]
> 貌似番剧区一直3.x播放器 这和普通投稿的3.x 播放器一样吗？

有一部分不一样

**Comment by Ln-G0179** [comment]
倍速无法选择，2.x版本的正常，3.x版本可以受在2.x版本调节后的倍速影响，但在3.x界面倍速按钮点击无反馈

**Comment by sniperdown** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我几乎不用邮箱，所以可能的话请换一种联系方式（QQ或者微信）。为因此造成的麻烦道歉。

**Comment by Ln-G0179** [comment]
> 倍速无法选择，2.x版本的正常，3.x版本可以受在2.x版本调节后的倍速影响，但在3.x界面倍速按钮点击无反馈

倍速快捷键可以使用

**Comment by JackASil** [comment]
播放器3.12.7  同样，浏览器开隐私是2.x（火狐win10）
播放器控制栏背景色失效 
```
Uncaught TypeError: e.querySelector(...) is null
    Pn moz-extension://8da2e59c-be67-4128-97fc-dd8d7bcab03b/userscripts/Bilibili Evolved.user.js?id=4c90a78c-3fc8-44e0-899a-842329a90b97:196
    <anonymous> moz-extension://8da2e59c-be67-4128-97fc-dd8d7bcab03b/userscripts/Bilibili Evolved.user.js?id=4c90a78c-3fc8-44e0-899a-842329a90b97:196
    <anonymous> moz-extension://8da2e59c-be67-4128-97fc-dd8d7bcab03b/userscripts/Bilibili Evolved.user.js?id=4c90a78c-3fc8-44e0-899a-842329a90b97:196
    <anonymous> moz-extension://8da2e59c-be67-4128-97fc-dd8d7bcab03b/userscripts/Bilibili Evolved.user.js?id=4c90a78c-3fc8-44e0-899a-842329a90b97:196
BV1R34y1W7Xn:196:31756
    Pn moz-extension://8da2e59c-be67-4128-97fc-dd8d7bcab03b/userscripts/Bilibili Evolved.user.js?id=4c90a78c-3fc8-44e0-899a-842329a90b97:196
    <anonymous> moz-extension://8da2e59c-be67-4128-97fc-dd8d7bcab03b/userscripts/Bilibili Evolved.user.js?id=4c90a78c-3fc8-44e0-899a-842329a90b97:196
    forEach self-hosted:164
    <anonymous> moz-extension://8da2e59c-be67-4128-97fc-dd8d7bcab03b/userscripts/Bilibili Evolved.user.js?id=4c90a78c-3fc8-44e0-899a-842329a90b97:196
    forEach self-hosted:164
    <anonymous> moz-extension://8da2e59c-be67-4128-97fc-dd8d7bcab03b/userscripts/Bilibili Evolved.user.js?id=4c90a78c-3fc8-44e0-899a-842329a90b97:196
```

**Comment by weituotian** [comment]
好~(￣▽￣)~*

**Comment by Majjcom** [comment]
跳过充电鸣谢：在三秒倒计时中，虽然没有充电鸣谢，但没有立即进入视频结束状态

**Comment by dssle** [comment]
视频倍速快捷键失效了

**Comment by CloudyEagle** [comment]
感觉又改了些，我这反复更新内置脚本，
加上排除是否与其他脚本或插件，
视频内的推荐又弹出来了，
以及弹幕里的快捷操作又有了。
![image](https://user-images.githubusercontent.com/58777085/181917863-6eb4f58e-4b2f-4c6c-b037-15270490506a.png)
![image](https://user-images.githubusercontent.com/58777085/181917936-430ad8ba-e2e8-49c5-aa72-5214abf2edbf.png)
播放器右键的版本号：
![image](https://user-images.githubusercontent.com/58777085/181917902-2d2b11f5-37c5-4b3d-9679-a04c9a69ff8e.png)

**Comment by NightSharp** [comment]
## 对应功能
 Commit: 95fbb00c7
内部名称: showCoverBeforePlay 


## 问题描述
在任意视频(比如[这个](https://www.bilibili.com/video/av2231425)播放一段时间后，刷新页面
封面会正常显示，但还会显示一个播放器Layer，包含播放条，左上角，右上角的信息，以及**弹幕**
如下图所示
![屏幕截图 2022-07-30 220709](https://user-images.githubusercontent.com/9748063/181918348-e1129e96-528d-4f2e-bd22-d6c84e4c2ef4.png)

## 脚本版本
v2.3.1-preview

## 浏览器版本
Firefox 103.0 (64 位)

## 播放策略
默认

## 错误信息
```lang=log
Bilibili Evolved plugins block time: 0ms for 30 items Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved plugins resolve time: 5ms for 30 items Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved 
Array(7) [ {…}, {…}, {…}, {…}, {…}, {…}, {…} ]
Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved reply 0 0 Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved at 0 0 Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved like 0 1 Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved sys_msg 0 0 Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved user_msg 0 1 Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved plugins block time: 2ms for 30 items Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved plugins resolve time: 14ms for 30 items Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved 
Array(4) [ 470926071, 941404023, 842105038, 753557334 ]
 2231425 false Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved videoChange 2231425 2231425 Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved components block time: 3ms for 43 items Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved components resolve time: 14867ms for 43 items Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved init block time: 2ms for 6 items Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved init resolve time: 2959ms for 6 items Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved 
Array(4) [ 470926071, 941404023, 842105038, 753557334 ]
 2231425 false Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved requestedPopup true 2 Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved requestedPopup true 2 Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved plugins block time: 0ms for 30 items Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved plugins resolve time: 12ms for 30 items Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved requestedPopup true 2 Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved plugins block time: 2ms for 30 items Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved plugins resolve time: 15ms for 30 items Bilibili Evolved (Preview).user.js:216:1992
Bilibili Evolved requestedPopup false 2 Bilibili Evolved (Preview).user.js:216:1992

```

**Comment by the1812** [comment]
太不容易了, 我今天终于被灰度到 3.x 播放器了

**Comment by yfw918** [comment]
> 太不容易了, 我今天终于被灰度到 3.x 播放器了

感觉3.x远不如2.x好用，有没有回退的办法

**Comment by awsl2546** [comment]
我是昨晚开始出问题，几乎是所有功能全部失效，包括安装的其他扩展。

**Comment by CloudyEagle** [comment]
> 太不容易了, 我今天终于被灰度到 3.x 播放器了

![QQ图片20220805104413](https://user-images.githubusercontent.com/58777085/182990571-69a4e61a-4644-4020-a26a-077992a517a5.png)
emm

**Comment by SnowMeteors** [comment]
删除视频弹窗中的关注失效
<img width="622" alt="无标题" src="https://user-images.githubusercontent.com/47601098/183216432-a3e894f3-de47-4053-a1ba-bf03da8b6e3b.png">
脚本版本  v2.2.2-7-g095ddcc03
chrome 版本 104.0.5112.79（正式版本） （64 位）
播放器版本 V3.15.0

**Comment by MirionQs** [comment]
”隐藏视频标题层“失效，”播放器控制栏背景色“失效，全屏时下方那几个插件新增按钮会偏上，”传统连播方式”失效，“启用弹幕空降”失效（应该问题不止这么点）
脚本：v2.3.2-preview-7-g63e6ee0f7
chrome：104.0.5112.81
播放器：3.17.1

**Comment by CloudyEagle** [comment]
![image](https://user-images.githubusercontent.com/58777085/187858246-25c290e7-16ff-42ce-ae70-d51e51c976c3.png)
![image](https://user-images.githubusercontent.com/58777085/187858667-8c359229-dadb-4abd-bf4f-2da674071674.png)
我这个是在旧版播放页面上的一个问题，请问可以解决不？
Microsoft Edge
Version 105.0.1343.23 (Official build) beta (64-bit)

**Comment by WanAna3kai** [comment]
> ![image](https://user-images.githubusercontent.com/58777085/187858246-25c290e7-16ff-42ce-ae70-d51e51c976c3.png) ![image](https://user-images.githubusercontent.com/58777085/187858667-8c359229-dadb-4abd-bf4f-2da674071674.png) 我这个是在旧版播放页面上的一个问题，请问可以解决不？ Microsoft Edge Version 105.0.1343.23 (Official build) beta (64-bit)

我这里刚才也遇到了这个问题
![image](https://user-images.githubusercontent.com/110894944/187862709-3f1e7e3f-c6a2-459b-b650-bdaa3dce0557.png)

Google Chrome
Version 105.0.5195.54（正式版本） （64 位）

**Comment by sniperdown** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我几乎不用邮箱，所以可能的话请换一种联系方式（QQ或者微信）。为因此造成的麻烦道歉。

**Comment by AzusaHana** [comment]
夜间模式，网页全屏或全屏下，弹幕发送窗口样式异常，会出现黑色背景
![image](https://user-images.githubusercontent.com/100906636/188273306-8b109175-e643-4510-b598-c29b7c1565e3.png)
白色模式下是正常的
![image](https://user-images.githubusercontent.com/100906636/188273375-3b5f1969-1033-4cf9-aedd-abd0f826853c.png)
播放器版本 3.17.1
插件版本 v2.4.0-preview
夜间模式版本：9f8ec1779
浏览器 Chrome 105.0.5195.54

**Comment by Londemon** [comment]
> [Commit: [095ddcc](https://github.com/the1812/Bilibili-Evolved/commit/095ddcc03ff52b9726715fc84688f37ec5c37475) ](https://github.com/the1812/Bilibili-Evolved/issues/3187#issuecomment-1177698792)
但issue #261 我不知道怎么处理了，因为现在直接通过控制台注入style在v2版本是不行的？

在原issue #261 里提了下解决方法，还能够应付过去

**Comment by KJZH001** [comment]
我发了个issue，尝试下载视频返回403

不知道和v3的播放器有没有关系，请问有没有暂时切换回到v2的方法？我想做个排查试试

**Comment by CloudyEagle** [comment]
这个扩展倍速的手动输入的框好像没有嘞，是跟播放器版本有关吗？
不像是数量有限吧，因为自己有手过已添加进去的倍数选项。
不过这个现象好像很久了，应该是3.0播放器出来后就这样了吧？
![image](https://user-images.githubusercontent.com/58777085/192090899-be38cfe4-c827-4ce6-a29c-06e41a813cdf.png)
![image](https://user-images.githubusercontent.com/58777085/192090910-034c0749-85bc-4bfb-b374-5e81a9cb91c8.png)

**Comment by sniperdown** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我几乎不用邮箱，所以可能的话请换一种联系方式（QQ或者微信）。为因此造成的麻烦道歉。

**Comment by NightSharp** [comment]
播放前查看封面的功能
我只想在真正开始播放前查看封面，不想在暂停时也查看
有时候想要截屏或者查看相关信息时还得专门把这个功能关掉
@the1812

**Comment by Geeyun-JY3** [comment]
@NightSharp 善用搜索，已经有人开了相关 issue 反馈该 bug：#3698

**Comment by xsdyd** [comment]
发现快捷键扩展中改键有效果但是禁用快捷键失效

**Comment by the1812** [comment]
如果 b 站自带的快捷键也是这个那就还是有效的, 可以用 `快捷键扩展 - 无动作` 插件来解决.

**Comment by fxcsuannicc** [comment]
下载视频功能出问题。
右键在新窗口打开下载链接后，不是像之前那样 显示下载弹窗， 而是出现了下面这个新窗口。重新安装脚本，组件，挂梯子，等方法均无效。
![微信图片_20221021142057](https://user-images.githubusercontent.com/116335865/197126569-e678c10e-1494-42ee-b586-b0c668c899d6.png)

**Comment by jingyill** [comment]
我在edge上用最新版有个问题，在已登录的情况下我如果开启自定义顶栏的话，就会跳转回未登录状态。非常奇怪，但是这可能只是表象，我觉得它有些读取不到我的信息，因为我的动态也读取不到了。我的chrome和edge配置都一样，结果去不同。
![image](https://user-images.githubusercontent.com/40361123/207058962-27dc0a49-ba6b-4dfa-8b6f-560ca9b1412f.png)
以及edge
![image](https://user-images.githubusercontent.com/40361123/207059134-0f22b74e-6de7-49eb-9a2f-0e639358591b.png)

**Comment by Tinhone** [comment]
#3873

**Comment by wialny** [comment]
删除视频弹窗 和 禁用特殊弹幕样式 这两个插件失效了. 现在会看到高赞弹幕前的大拇指, 还有一键三连的弹窗

**Comment by zheyiyuezhuo** [comment]
现在b站播放器版本3.26.2，插件2.6.0，里面的组件都是最新版本，但是都没有用了，功能显示空空如也。。麻烦问下什么时候能修复啊
![图片](https://user-images.githubusercontent.com/46232425/217283439-c5a7c168-b1af-40e5-a342-9ef5104eb277.png)
![图片](https://user-images.githubusercontent.com/46232425/217283523-727dc975-ba97-46f4-94e8-ac6219a22a4f.png)

**Comment by qw4096** [comment]
不能自动宽屏了，从稍后再看进去，快速收藏的按钮也不见了。但是从其他地方比如首页点进去，即使是新版页面，功能也是正常的

**Comment by Geeyun-JY3** [comment]
@qw4096 稍后再看看这里：#3916

**Comment by qw4096** [comment]
> 

大佬，我看了，但还是不知道怎么解决

**Comment by qw4096** [comment]
> 

好的，感谢回复

**Comment by the1812** [comment]
3.x 播放器现在还有哪些功能不行的 (稍后再看不算)

**Comment by lovingzyz** [comment]
希望能修复支持flv格式的4K的下载视频供呢个，有大会员也无法下载4K，虽然使用ffmpeg等工具合并音画，终归还是一步到位方便

**Comment by SnowMeteors** [comment]
删除视频弹窗失效

**Comment by CatOverrun** [comment]
3.x视频页面下载我之前是可以用的，播放器4.0开始，整个页面的脚本都不会生效（夜间模式，广告屏蔽，屏蔽推荐，下载视频等），侧边栏都不会出现。（首页，动态，直播，这些地方脚本依旧生效）

Tampermonkey BETA 4.19.6180
Bilibili Evolved v2.7.0-39-gac29c0ec6
Chromium 111.0.5563.111 (Official Build) (64-bit)
播放器 version: 4.0.1-rc.868.0 revision: f93946da

**Comment by the1812** [comment]
忘了关这个了, 4.0 都适配完了(
