### ISSUE TITLE
下载出来的视频在哪里？默认存在哪个位置?

### ISSUE THREAD

**Issue by MicMAO** [the1812/Bilibili-Evolved#319]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by the1812** [comment]
直接下载的话 下好会弹出一个另存为的窗口给你选位置

**Comment by MicMAO** [comment]
> 直接下载的话 下好会弹出一个另存为的窗口给你选位置

我下载完成后显示的是浏览器崩溃了，这个怎么办。

**Comment by the1812** [comment]
视频太大了不能直接下载, 只能用下面的导出

**Comment by MicMAO** [comment]
> 视频太大了不能直接下载, 只能用下面的导出

什么导出？下面是显示链接和aria2 没有到处选项呢

**Comment by the1812** [comment]
那些就是导出
![image](https://user-images.githubusercontent.com/26504152/73602006-fd9c7b80-45a6-11ea-988c-91e776be2ac0.png)

**Comment by MicMAO** [comment]
> 那些就是源自
> ![图片](https://user-images.githubusercontent.com/26504152/73602006-fd9c7b80-45a6-11ea-988c-91e776be2ac0.png)

大佬能加个qq说一下吗  我的qq是1753845372

**Comment by the1812** [comment]
先试试显示链接? 那个还不行我再加你

**Comment by MicMAO** [comment]
> 先试试显示链接？那个还不行我再加你

1，显示链接出来的是分段的各个链接吗？
2，我是用idm没法使用这个显示链接
3，这个要用什么软件去使用显示连接

**Comment by the1812** [comment]
1. 是
2. IDM我没用过, 但据此前的IDM用户所说可以从这个链接开始下载
3. 这个功能就是留给IDM的, 不过最近好像可以直接点开用浏览器下载了

![image](https://user-images.githubusercontent.com/26504152/73602125-62f16c00-45a9-11ea-96f1-cb9399e70d19.png)

**Comment by MicMAO** [comment]
> 1. 是
> 2. IDM我没用过，但据空军的IDM用户说可以从这个链接开始下载
> 3. 这个功能就是留给IDM的，不过最近好像可以直接点开用浏览器下载了
> 
> ![图片](https://user-images.githubusercontent.com/26504152/73602125-62f16c00-45a9-11ea-96f1-cb9399e70d19.png)

好的 那我再去研究研究
谢谢大佬
