### ISSUE TITLE
新版动态首页 问题汇总

### ISSUE THREAD

**Issue by 2SHANINGITHUB** [the1812/Bilibili-Evolved#3191]
### 对应功能

动态过滤器失效Commit: 84b92e6e4

### 问题描述

中午用还好好的，下午就失效了

### 脚本版本

v2.1.7-preview

### 浏览器版本

Chrome 版本 99.0.4844.84（正式版本） （64 位）

### 播放器版本

和播放器没有关系

### 播放策略

默认

### 错误信息

```shell
见图
```

### 附加截图

![image](https://user-images.githubusercontent.com/90484463/160347976-45fb49b4-8919-4a55-9c97-1087582b5acd.png)

**Comment by Kegekkk** [comment]
顺便提一下，夜间模式在动态页面也同时失效了

**Comment by zackBRAVE** [comment]
同样遇到上述两个问题，这个可能是因为b站刚对动态页做了重构，很多元素样式类名都变了，我的stylus很多配置也失效了，需要根据新类名重新设置

**Comment by the1812** [comment]
关于灰度的开关可以参考 #3192

**Comment by u2shana** [comment]
界面缩到顶栏上面去了

**Comment by CloudyEagle** [comment]
![Snipaste_2022-03-31_10-58-57](https://user-images.githubusercontent.com/58777085/160968515-3e96c14a-9cd5-4599-9396-425e4f4984bd.png)
对应功能
动态反折叠
动态过滤器
展开动态内容

包含已有的#3192

**Comment by zackBRAVE** [comment]
那么如何退回呢，将这个键删掉，或者设为0或-1，以及将i-wanna-go-back设为1，都没能退回

**Comment by GoogleGAT** [comment]
在“动态首页”下，“快速收起评论”这个功能也失效了

**Comment by Hiiro570** [comment]
一样和动态有关的四舍五入全部失效，只有《强制固定动态侧栏》算还能用

**Comment by Umshiro** [comment]
动态页强制新版了？

**Comment by Cierra-Runis** [comment]
新版动态又改了，确实很烦人

**Comment by johnsteveabc** [comment]
所以说什么时候更新呢，等很久了

**Comment by the1812** [comment]
不太确定, 这次改了好多地方

**Comment by upsetdone** [comment]
主题色失效，昨天还能用，今天才发现的（应该）
![image](https://user-images.githubusercontent.com/71574060/162457724-851c6608-cf86-4468-b38f-2fd7905bb1c3.png)
![image](https://user-images.githubusercontent.com/71574060/162457625-858cc351-5688-459f-b5d0-276952b42c87.png)

**Comment by YaeSakuraQvQ** [comment]
> 主题色失效，昨天还能用，今天才发现的（应该） ![image](https://user-images.githubusercontent.com/71574060/162457724-851c6608-cf86-4468-b38f-2fd7905bb1c3.png) ![image](https://user-images.githubusercontent.com/71574060/162457625-858cc351-5688-459f-b5d0-276952b42c87.png)

老哥你的暗夜模式是咋还生效的？求教...我动态页的功能直接全挂

**Comment by upsetdone** [comment]
> > 主题色失效，昨天还能用，今天才发现的（应该）![图像](https://user-images.githubusercontent.com/71574060/162457724-851c6608-cf86-4468-b38f-2fd7905bb1c3.png) ![图像](https://user-images.githubusercontent.com/71574060/162457625-858cc351-5688-459f-b5d0-276952b42c87.png)
> 
> 老哥你的暗夜模式是咋还生效的？求教...我动态页的功能直接全挂

我用的扩展dark reader

**Comment by upsetdone** [comment]
> > 主题色失效，昨天还能用，今天才发现的（应该） ![image](https://user-images.githubusercontent.com/71574060/162457724-851c6608-cf86-4468-b38f-2fd7905bb1c3.png) ![image](https://user-images.githubusercontent.com/71574060/162457625-858cc351-5688-459f-b5d0-276952b42c87.png)
> 
> 老哥你的暗夜模式是咋还生效的？求教...我动态页的功能直接全挂

我用的扩展dark reader

**Comment by thouser8** [comment]
期待能修好吧...新版动态首页点赞特效已经没了，再失去插件功能我将不能呼吸😭

**Comment by CloudyEagle** [comment]
不知道是账号阶段性灰测，还是与Chromium的内核版本有关，我登陆Edge beta版的那个账号失效了
![Snipaste_2022-04-11_09-22-15](https://user-images.githubusercontent.com/58777085/162650491-01e69c8e-a798-4ac8-a1af-8eaa47a25125.png)
![Snipaste_2022-04-11_09-22-59](https://user-images.githubusercontent.com/58777085/162650508-0b1da7e1-ac31-4933-bf33-fdecdf3c8705.png)

————————————————————————————————

![Snipaste_2022-04-11_09-24-26](https://user-images.githubusercontent.com/58777085/162650546-2ebdce37-5503-40d5-a0dc-cc56fd92350c.png)
![Snipaste_2022-04-11_09-24-51](https://user-images.githubusercontent.com/58777085/162650556-e876ec93-9184-4d59-890a-4c1946e0f347.png)

**Comment by Modurll** [comment]
直播扩充信息 也失效了

**Comment by Umshiro** [comment]
InPrivate 试了4个号，只有主号失效，小号动态页功能全部正常。

**Comment by n0000000000o** [comment]
> 我这和动态有关的组件都寄了

我也是。

**Comment by wingslu** [comment]
找到解决方法了，把ua改成safari7动态页面的bug基本就全都好了

**Comment by thouser8** [comment]
> 找到解决方法了，把 ua 改成 safari7 动态页面的 bug 基本就全都好了

请问下具体怎么更改？

**Comment by yfw918** [comment]
> 

感谢，试了下改成老EDGE也可以(18.19041)

**Comment by upsetdone** [comment]
> > 找到解决方法了，把ua改成safari7动态页面的bug基本就全都好了
> 
> 感谢，试了下改成老EDGE也可以(18.19041)

确实，变回旧版的动态了

**Comment by Eric-the-Red-00** [comment]
> 找到解决方法了，把 ua 改成 safari7 动态页面的 bug 基本就全都好了

实测有效，似乎解决了所有问题，十分感谢

**Comment by Jazzwind** [comment]
> > 找到解决方法了，把 ua 改成 safari7 动态页面的 bug 基本就全都好了
> 
> 实测有效，似乎解决了所有问题，十分感谢

请问一下是怎么改的呀？使用额外的插件吗

**Comment by yfw918** [comment]
> > 找到解决方法了，把 ua 改成 safari7 动态页面的 bug 基本就全都好了
> 
> 实测有效，似乎解决了所有问题，十分感谢

你播放器版本回到2.x了吗？我虽然动态恢复了但是播放器版本还是3.x

**Comment by yfw918** [comment]
> > > 找到解决方法了，把 ua 改成 safari7 动态页面的 bug 基本就全都好了
> > 
> > 
> > 实测有效，似乎解决了所有问题，十分感谢
> 
> 请问一下是怎么改的呀？使用额外的插件吗

用浏览器插件，User-Agent Switcher and Manager

**Comment by Eric-the-Red-00** [comment]
> > > 找到解决方法了，把 ua 改成 safari7 动态页面的 bug 基本就全都好了
> > 
> > 
> > 实测有效，似乎解决了所有问题，十分感谢
> 
> 请问一下是怎么改的呀？使用额外的插件吗

是的，我使用的[这个](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg)，同类插件都可以

**Comment by Eric-the-Red-00** [comment]
> > > 找到解决方法了，把 ua 改成 safari7 动态页面的 bug 基本就全都好了
> > 
> > 
> > 实测有效，似乎解决了所有问题，十分感谢
> 
> 你播放器版本回到 2.x 了吗？我虽然动态恢复了但是播放器版本还是 3.x

我这边是2.x，不过并不是因为修改了ua，不太清楚是如何选择的版本。

**Comment by Jazzwind** [comment]
> > > > 找到解决方法了，把 ua 改成 safari7 动态页面的 bug 基本就全都好了
> > > 
> > > 
> > > 实测有效，似乎解决了所有问题，十分感谢
> > 
> > 请问一下是怎么改的呀？使用额外的插件吗
> 
> 是的，我使用的[这个](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg)，同类插件都可以

请问一下，我用了这个确实完美解决了。但是，他能不能指针对动态首页生效呢？怕ua改成safari，别的网站会不会出现认证问题之类的

**Comment by Eric-the-Red-00** [comment]
> > > > > 找到解决方法了，把 ua 改成 safari7 动态页面的 bug 基本就全都好了
> > > > 
> > > > 
> > > > 实测有效，似乎解决了所有问题，十分感谢
> > > 
> > > 
> > > 请问一下是怎么改的呀？使用额外的插件吗
> > 
> > 
> > 是的，我使用的[这个](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg)，同类插件都可以
> 
> 请问一下，我用了这个确实完美解决了。但是，他能不能指针对动态首页生效呢？怕 ua 改成 safari，别的网站会不会出现认证问题之类的

<img width="370" alt="Snipaste_2022-04-15_21-32-38" src="https://user-images.githubusercontent.com/30338855/163576898-861f4441-6b8c-4c11-9dd1-540d2b976246.png">

**Comment by Umshiro** [comment]
Safari 10.1 （不含）以下的 UA 都可以回到旧版动态。
User-Agent Switcher and Manager 的 white-list mode，把 t.bilibili.com 加进去就行。

**Comment by maidangdang1** [comment]
脚本更到最新版后快速收起评论失效了:(
UA改成safari7也不管用
脚本版本：v2.1.8-4-g01590d883
浏览器版本：Chrome 100.0.4896.127（正式版本） （64 位）
![1650169886(1)](https://user-images.githubusercontent.com/46847241/163700572-a244a645-2c8c-4c7c-9a47-ba58daa2d05c.png)

**Comment by wingslu** [comment]
> 找到解决方法了，把ua改成safari7动态页面的bug基本就全都好了
chrome用这个两个插件：
User-Agent Switcher for Chrome，用这个最高可以改到safari7
User-Agent Switcher and Manager，用这个最高可以改到safari 10.0.3
这两个插件都可以单独设置动态页面https://t.bilibili.com/不影响播放器版本

**Comment by wingslu** [comment]
> 找到解决方法了，把ua改成safari7动态页面的bug基本就全都好了

chrome用这个两个插件：
User-Agent Switcher for Chrome，用这个最高可以改到safari7
User-Agent Switcher and Manager，用这个最高可以改到safari 10.0.3
这两个插件都可以单独设置动态页面[https://t.bilibili.com/不影响播放器版本](https://t.bilibili.com/%E4%B8%8D%E5%BD%B1%E5%93%8D%E6%92%AD%E6%94%BE%E5%99%A8%E7%89%88%E6%9C%AC)

**Comment by icateav** [comment]
开启固定动态侧栏会多一个蓝色的背景
![Snipaste_2022-04-18_18-48-02](https://user-images.githubusercontent.com/103933830/163798212-748938eb-501a-4dc3-b5ed-e807e01bbf7e.png)
![Snipaste_2022-04-18_18-48-25](https://user-images.githubusercontent.com/103933830/163798218-c8efb911-5366-46dd-a011-488720d9e30d.png)

**Comment by WZdaze** [comment]
> 开启固定动态侧栏会多一个蓝色的背景 ![Snipaste_2022-04-18_18-48-02](https://user-images.githubusercontent.com/103933830/163798212-748938eb-501a-4dc3-b5ed-e807e01bbf7e.png) ![Snipaste_2022-04-18_18-48-25](https://user-images.githubusercontent.com/103933830/163798218-c8efb911-5366-46dd-a011-488720d9e30d.png)

原来是这个会出现背景，太感谢了

**Comment by Leiiis** [comment]
使用的是edge浏览器
<img width="501" alt="image" src="https://user-images.githubusercontent.com/103985633/163938215-561296ab-d74c-4a6f-beb8-1d7422956d08.png">
信仰充值（UI显示不正确）
![image](https://user-images.githubusercontent.com/103985633/163938354-f4d1b1f9-9e89-4c8c-b780-0c54deaa2d2b.png)
动态页面夜间模式显示错误（昨天还好好的呢）
😭

**Comment by Tinhone** [comment]
今天被灰度了😭
V1版本残党：亚达哟😭

**Comment by NamelessAstral** [comment]
**对应功能**
动态过滤

**问题描述**
似乎有部分功能无法正常使用
类型过滤中的开播记录这项无法生效。不论如何，开播记录都会存在于动态流里；

很多过滤选项在初次进入动态页时能用，但通过关注栏切到某位UP主的动态流之后便会失效，比如视频、正则表达式等选项。
并且，在过滤失效后再切回“全部动态”，那些被过滤掉的内容都会显示出来，若想重新过滤，则需要刷新网页。

**脚本版本**
2.1.8

**浏览器版本**
Chrome 100.0.4896.127（正式版本） （64 位）

**Comment by Neo-Ze** [comment]
**脚本版本**
v2.1.8-4-g01590d883

**浏览器版本**
Chrome 版本 100.0.4896.127（正式版本） （64 位）

**问题描述**
“动态快速收起评论”、“禁止跳转动态详情”失效

**相关截图**
“收起评论”无
![image](https://user-images.githubusercontent.com/81399833/164731005-c74b5c0f-be16-4f5b-ae05-b02fda271e47.png)
点击动态文字会跳转
![20220422_220042](https://user-images.githubusercontent.com/81399833/164730562-a158a84a-8ec3-49b2-a043-672dd394a2c1.gif)
edge则是正常的
![image](https://user-images.githubusercontent.com/81399833/164731386-288859da-da10-4860-b1dd-a34f0dbf9621.png)

**Comment by Asusiky** [comment]
禁止跳转动态详情，这个功能目前也失效了

**Comment by 2SHANINGITHUB** [comment]
动态过滤组件中的开播记录过滤目前还是失效的
组件版本2f6e86289
脚本版本v2.1.8-preview
浏览器版本Chrome 101.0.4951.41（正式版本） （64 位）

**Comment by icateav** [comment]
更新了2.1.9 开启**强制固定动态侧栏**还是会出现蓝色背景，**禁止跳转动态详情**依旧会导致动态的**展开**按钮无效
是我这边出了bug还是还没修啊

**Comment by CloudyEagle** [comment]
敢问这新版动态界面的夜间模式大致何时能弄好呀，
已经有很长一段时间了，一个月应该快有了吧，还是等B站稳定了再改？
组件版本73fa9af28
脚本版本v2.1.10-preview-1
浏览器版本
Microsoft Edge Version 101.0.1210.47 (Official build) (64-bit)
Microsoft Edge Version 102.0.1245.12 (Official build) beta (64-bit)
![QQ图片20220514200916](https://user-images.githubusercontent.com/58777085/168425522-4bae9c54-bf46-4495-804f-9445676c0cc6.jpg)
![QQ图片20220514200921](https://user-images.githubusercontent.com/58777085/168425549-8469613f-65f9-4e43-8be5-c4807502ea10.jpg)

**Comment by shiroyukki** [comment]
动态里的站内链接貌似也失效了，点击没反应，应该不是其他脚本冲突导致的
![image](https://user-images.githubusercontent.com/72260642/168427773-0c87b6ac-7ade-41e7-88d4-a65d17907e4c.png)

**Comment by icateav** [comment]
> 动态里的站内链接貌似也失效了，点击没反应，应该不是其他脚本冲突导致的 !(https://user-images.githubusercontent.com/72260642/168427773-0c87b6ac-7ade-41e7-88d4-a65d17907e4c.png)

你关掉禁止跳转动态详情试试

**Comment by shiroyukki** [comment]
> > 动态里的站内链接貌似也失效了，点击没反应，应该不是其他脚本冲突导致的 !(https://user-images.githubusercontent.com/72260642/168427773-0c87b6ac-7ade-41e7-88d4-a65d17907e4c.png)
> 
> 你关掉禁止跳转动态详情试试

关掉可以了，看来是有冲突

**Comment by legend418** [comment]
那个快速收起动态评论和禁止动态跳转在点开某一人的头像查看此人动态后不能使用了
![QQ截图20220519194403](https://user-images.githubusercontent.com/65126289/169285808-e627780d-ce2b-474c-b3d5-6f4c05cad6ff.png)
![QQ截图20220519194431](https://user-images.githubusercontent.com/65126289/169285852-5b06703d-f95c-4e06-be51-398db8dd9924.png)
![QQ截图20220519194450](https://user-images.githubusercontent.com/65126289/169285863-9752c7e5-345e-4553-a748-102d66101f46.png)

**Comment by CloudyEagle** [comment]
![image](https://user-images.githubusercontent.com/58777085/169677813-66ff9d74-9c61-4f85-9113-4ce402a1050f.png)
个人主页的动态界面也出问题了，不知道也是不少这个问题导致的

**Comment by OpsEscarrrrrrr** [comment]
![image](https://user-images.githubusercontent.com/34292127/170686502-5f939110-b34c-4d87-b5bb-999035fe314c.png)
发现了一个问题，希望作者可以看到。在夜间模式时，点开动态首页下的评论栏，夜间模式的字体无法正常适配（可见于我所上传的图片），视频中的评论区在夜间模式下是会正常适配

**Comment by gongfuture** [comment]
> ![image](https://user-images.githubusercontent.com/34292127/170686502-5f939110-b34c-4d87-b5bb-999035fe314c.png) 发现了一个问题，希望作者可以看到。在夜间模式时，点开动态首页下的评论栏，夜间模式的字体无法正常适配（可见于我所上传的图片），视频中的评论区在夜间模式下是会正常适配

一样，我也刚想提这个来着

**Comment by skinhc** [comment]
![image](https://user-images.githubusercontent.com/45780801/170900365-3ca9e469-b12f-4e88-a156-3ca8607c2c1b.png)
早上刚刚发生的,安装组件全部是错误,好像是cdn走不通了

**Comment by DIXX-qqfr** [comment]
> 对应功能 快速收起评论
> 
> 问题描述 功能失效，chrome和edge都没用，只开这一个插件也没有显示 ![image](https://user-images.githubusercontent.com/50895871/170952490-d7325649-7f7c-412c-a6bf-74219c9854aa.png)
> 新发现：F5刷新后第一次展开评论功能正常使用，之后就失效了
> 脚本版本 v2.1.9-8-g9c9c5fd27
> 
> 浏览器版本 8.0.1000.2204 ( Chromium: 98.0.4758.139 Res: 2204.521 ) （64 位）

**Comment by AzusaHana** [comment]
**“禁止跳转动态”**详情在个人空间页面的动态里失效，点击文字依旧会跳转，示例个人空间动态：https://space.bilibili.com/171818544/dynamic
Bilibili Evolved (Preview): v2.2.1-preview
Commit: 24744b203
Chrome: 102.0.5005.63

**Comment by DIXX-qqfr** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Geeyun-JY3** [comment]
> 左侧工具按钮消失了，好像是被墙了，有没有国内源

@Majjcom 请善用搜索：#3356，看置顶：#3331，并阅读 [v2.2.0](https://github.com/the1812/Bilibili-Evolved/releases/tag/v2.2.0) 更新日志

**Comment by MC-dusk** [comment]
复制动态链接、复制评论链接都失效了，不知是否有关？

**Comment by DIXX-qqfr** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
