### ISSUE TITLE
【BUG/夜间模式】在动态v2失效

### ISSUE THREAD

**Issue by Akegarasu** [the1812/Bilibili-Evolved#3192]
### 对应功能

夜间模式

### 问题描述

大概是最近开始灰度测试的动态v2版本，没被灰度到的用户可以在
`t.bilibili.com` 中的 cookie 添加键`hit-dyn-v2` （值任意，默认为1）来进入v2版本的动态页面
来自`https://s1.hdslb.com/bfs/static/stone-free/dyn-home/dyn-home.92d0b415b7f1b427b20b3751f16473d2e3ef0132.js`
![image](https://user-images.githubusercontent.com/36563862/160363674-2941cb20-9bf0-4677-8b3b-d8ef1dc2ab81.png)

### 脚本版本

v2.1.7-preview

### 浏览器版本

Chromium 86.0.4240.198

### 播放器版本

-

### 播放策略

默认

### 错误信息

```shell
-
```

### 附加截图

![image](https://user-images.githubusercontent.com/36563862/160363316-72c89db7-0007-43e5-83ba-c77cd36335fb.png)

**Comment by the1812** [comment]
合并至 #3191

**Comment by zackBRAVE** [comment]
那么如何退回呢，将这个键删掉，或者设为0或-1，以及将i-wanna-go-back设为1，都没能退回
