### ISSUE TITLE
自定义顶栏把不该顶掉的元素顶掉了

### ISSUE THREAD

**Issue by wdlpiaoyi** [the1812/Bilibili-Evolved#3194]
### 对应功能

自定义顶栏

### 问题描述

https://member.bilibili.com/platform/home
会把右上角原有的下载投稿工具的地方整不见

### 脚本版本

Offline v1246.26

### 浏览器版本

离最新版本只有一步之遥了！重新启动 Chrome 即可完成更新。 版本 99.0.4844.82（正式版本） （64 位）

### 播放器版本

3.7.1

### 播放策略

HEVC

### 错误信息

```shell
NaN
```

**Comment by the1812** [comment]
脚本版本太低了

**Comment by wdlpiaoyi** [comment]
> 

懂了，谢谢
