### ISSUE TITLE
未设置夜间模式自动变黑

### ISSUE THREAD

**Issue by aliofwind** [the1812/Bilibili-Evolved#32]
**关于哪一项功能**

未设置夜间模式自动变黑
**问题描述**

默认打开页面就黑

**脚本版本**

154.10
**浏览器版本**

Chrome 69

**附加截图**
![image](https://user-images.githubusercontent.com/35068322/50084611-8553e900-0232-11e9-9d50-578bdc71bcc5.png)

**Comment by the1812** [comment]
用的插件是ViolentMonkey吗?

**Comment by aliofwind** [comment]
Tampermonkey

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Grant Howard <notifications@github.com>
发送时间: Monday, December 17, 2018 10:35:31 PM
收件人: the1812/Bilibili-Evolved
抄送: aliofwind; Author
主题: Re: [the1812/Bilibili-Evolved] 未设置夜间模式自动变黑 (#32)


用的插件是ViolentMonkey吗?

―

**Comment by the1812** [comment]
相关代码现在就先暂时注释掉了, 可以刷新几次看看还有没有问题
