### ISSUE TITLE
希望提供一个快速添加弹幕关键词屏蔽的功能

### ISSUE THREAD

**Issue by xiaole3349** [the1812/Bilibili-Evolved#320]
**关于哪一项功能**

主要是弹幕正则的快速添加。
**期望的效果**

**脚本版本**

预览版

**Comment by the1812** [comment]
这里不快速吗?
<img width="400" src="https://user-images.githubusercontent.com/26504152/73808336-86672180-480a-11ea-977e-e617aad3e8c9.png">

**Comment by xiaole3349** [comment]
> 这里不快速吗?
> <img alt="" width="400" src="https://user-images.githubusercontent.com/26504152/73808336-86672180-480a-11ea-977e-e617aad3e8c9.png">

想一次性添加一堆正则有点麻烦（

**Comment by the1812** [comment]
那我弄个批量添加给你吧

**Comment by the1812** [comment]
等等 批量导入b站也是支持的
<img width="400" src="https://user-images.githubusercontent.com/26504152/73815934-5fb4e500-4822-11ea-8b6d-3502241dd945.png">
