### ISSUE TITLE
图片批量导出不可用。

### ISSUE THREAD

**Issue by xxx-lb** [the1812/Bilibili-Evolved#3209]
### 对应功能

图片批量导出在动态右上角 的三点未显示出来。

### 问题描述

在个人动态界面：https://t.bilibili.com/
以前点右上角的是有“下载图片”的选项，但是现在没有了。
重新装插件，换浏览器，从Tampermonkey换到Violentmonkey，插件正式版换预览版也一样。

### 脚本版本

v2.1.7-4-gc7a7e0267

### 浏览器版本

Microsoft Edge 版本 100.0.1185.29 (正式版本) (64 位)

### 播放器版本

2.7.4-f3df8d33

### 播放策略

默认

### 错误信息

```shell
bili-header.umd.js:1 [Intervention]Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
```

### 附加截图

<img width="497" alt="屏幕截图 2022-04-03 103225" src="https://user-images.githubusercontent.com/58838717/161409350-31dacfb6-6331-46f0-b481-7101a587cb98.png">
<img width="456" alt="屏幕截图 2022-04-03 103246" src="https://user-images.githubusercontent.com/58838717/161409352-668cd99a-d7ab-4a82-b782-08f56b2cc079.png">

**Comment by the1812** [comment]
#3191

**Comment by xxx-lb** [comment]
> 
偶然发现，进入up主空间后可用。
<img width="812" alt="屏幕截图 2022-04-05 144744" src="https://user-images.githubusercontent.com/58838717/161695377-05e47118-a40a-4600-9692-d17f21b91a59.png">

**Comment by MC-dusk** [comment]
不仅是动态图片导出失效，专栏图片导出也失效了
