### ISSUE TITLE
作者你好。

### ISSUE THREAD

**Issue by DIL9527** [the1812/Bilibili-Evolved#321]
能不能在设置里加一个功能，就是点进视频页之后自动进入宽屏模式？就像截图这样
![SharedScreenshot](https://user-images.githubusercontent.com/60689271/73824488-db317a80-47bf-11ea-8894-6533a41a4c9b.jpg)

**Comment by the1812** [comment]
<img width="400" src="https://user-images.githubusercontent.com/26504152/73824870-e45d2e80-4835-11ea-91aa-96f17b6e9ea5.png">

**Comment by DIL9527** [comment]
哦哦，没发现这个。谢谢你。祝你新年快乐

**Comment by the1812** [comment]
新年快乐
