### ISSUE TITLE
win11系统edge和chrome浏览器顶部栏全部失效，只截图了chrome浏览器的

### ISSUE THREAD

**Issue by LuvEven** [the1812/Bilibili-Evolved#3211]
### 对应功能

自定义顶栏

### 问题描述

顶栏消失

### 脚本版本

2.1.7

### 浏览器版本

版本 100.0.4896.60（正式版本） （64 位）

### 播放器版本

未知

### 播放策略

默认

### 错误信息

```shell
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/laputa-home/client/assets/index.5f4eab4d.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

The resource https://s1.hdslb.com/bfs/static/laputa-home/client/assets/vip-default-banner.6db4a7ed.png was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

### 附加截图

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/56387141/161557574-b4982869-e0a7-4592-94f7-95c4e30042d7.png">

**Comment by LuvEven** [comment]
排除其他插件和扩展的干扰了，比较确定是脚本自身的问题.....

**Comment by LuvEven** [comment]
附带：换了暴力猴也不行，同样的问题，不过发现另外一个脚本也出现乱码问题，我查了一下别人换用暴力猴其他脚本乱码问题都能解决，按理说暴力猴应该是utf-8编码

**Comment by LuvEven** [comment]
问题已解决，其他电脑导出油猴脚本导入新电脑使用的bug，重装油猴和脚本之后正常

**Comment by XCSenior** [comment]
> 

重装油猴与脚本之后，亲测有效。解决了左侧功能与设置侧拉框消失的问题
![image](https://user-images.githubusercontent.com/77381715/194712574-0a8ad2ef-4883-41b2-a360-9eb84c0e5f55.png)

**Comment by XCSenior** [comment]
> > 
> 
> 重装油猴与脚本之后，亲测有效。解决了左侧功能与设置侧拉框消失的问题 ![image](https://user-images.githubusercontent.com/77381715/194712574-0a8ad2ef-4883-41b2-a360-9eb84c0e5f55.png)

新电脑使用旧电脑导出的油猴脚本，导致B站的顶部栏消失，左侧功能与设置侧拉窗消失。重装油猴并重新下载最新脚本后，导入旧电脑脚本的设置，成功恢复
