### ISSUE TITLE
这个脚本越来越垃圾

### ISSUE THREAD

**Issue by hchzdh** [the1812/Bilibili-Evolved#3213]
### 对应功能

下载功能无效，第三方脚本无法加载，离线版N年没有更新了吧

### 问题描述

下载功能无效，第三方脚本无法加载，离线版N年没有更新了吧

### 脚本版本

2.1.7

### 浏览器版本

Edge、Vivaldi

### 播放器版本

3.0

### 播放策略

默认

### 错误信息

```shell
没什么可说的
```

### 附加截图

懒得沾了

**Comment by Geeyun-JY3** [comment]
3.0 播放器没适配原因见 #3187

v2 为啥没离线版写得很清楚：https://github.com/the1812/Bilibili-Evolved/releases/tag/v2.0.7
> 不再有离线版, 你可以自行控制功能的更新

综上所述，啊对对对。

**Comment by the1812** [comment]
啊对对对, 太垃圾了, 赶紧卸了吧
