### ISSUE TITLE
夜间模式下动态首页的样式问题

### ISSUE THREAD

**Issue by GVD20** [the1812/Bilibili-Evolved#3215]
### 对应功能

夜间模式

### 问题描述

![image](https://user-images.githubusercontent.com/75466651/161677770-e7d017c4-7b14-49fb-abc3-e1a7eb425dc9.png)

## 系统环境：
- win10企业版LTSC 2022/2 64位
- 浏览器1：Microsoft Edge 92.0.902.67
- 浏览器2：Google Chrome 100.0.4896.75
- 脚本管理器：Tampermonkey v4.15

### 脚本版本

2.1.7

### 浏览器版本

Microsoft Edge 92.0.902.67/Google Chrome 100.0.4896.75

### 播放器版本

2.76.2

### 播放策略

HEVC

### 错误信息

```shell
网页样式错误 不存在报错
```

### 附加截图

![image](https://user-images.githubusercontent.com/75466651/161677770-e7d017c4-7b14-49fb-abc3-e1a7eb425dc9.png)

**Comment by the1812** [comment]
#3191
