### ISSUE TITLE
自定义顶栏出错

### ISSUE THREAD

**Issue by NeilTohno** [the1812/Bilibili-Evolved#3219]
### 对应功能

自定义顶栏
customNavbar
Commit: 93939adb9

https://t.bilibili.com/
或者新标签打开的动态 （全部，并非单个）
https://t.bilibili.com/639593606253903895?tab=2

### 问题描述

关掉这个功能就没事了

### 脚本版本

 @the1812 the1812  v2.1.7  65f5f15 v2.1.7

### 浏览器版本

Chrome 100.0.4896.60

### 播放器版本

无

### 播放策略

默认

### 错误信息

```shell
未找到相关内容
```

### 附加截图

![sThm1.png](https://imglink.win/image/2022/04/06/sThm1.png)
![sTZWi.png](https://imglink.win/image/2022/04/06/sTZWi.png)

**Comment by the1812** [comment]
#3191
