### ISSUE TITLE
Tampermonkey 和暴力猴还是凉凉

### ISSUE THREAD

**Issue by DDuann027** [the1812/Bilibili-Evolved#3220]
### 对应功能

![image](https://user-images.githubusercontent.com/102145298/161883588-90bc4058-df6d-4570-99bf-00f5ad0fbdff.png)

### 问题描述

Tampermonkey  和暴力猴 都用了  还是凉凉  卸载chorme 重新安装很多次  AdvancedSystemCarePortable清理注册表  什么垃圾文件 重启 还是凉凉

### 脚本版本

v2.1.7-3-g93939adb9

### 浏览器版本

版本 100.0.4896.75（正式版本） （64 位）

### 播放器版本

3.7.3-of8ee256

### 播放策略

默认

### 错误信息

```shell
Uncaught DOMException: Failed to construct 'RTCPeerConnection': Plan B SDP semantics is a legacy version of the Session Description Protocol that has severe compatibility issues on modern browsers and is no longer supported. See https://www.chromestatus.com/feature/5823036655665152 for more details, including the possibility of registering for a Deprecation Trial in order to extend the Plan B deprecation deadline for a limited amount of time.
    at new WrappedRTCPeerConnection (<anonymous>:275:28)
    at DynamicDetails.getWebRTCIP (chrome-extension://jgphnjokjhjlcnnajmfjlacjnjkhleah/js/chrome.js:47955:15)
    at collectMovement (chrome-extension://jgphnjokjhjlcnnajmfjlacjnjkhleah/js/chrome.js:48079:11)
    at chrome-extension://jgphnjokjhjlcnnajmfjlacjnjkhleah/js/chrome.js:64043:7
```

### 附加截图

![image](https://user-images.githubusercontent.com/102145298/161883164-587d899f-0ccd-4076-b5a7-5736998702fd.png)
![image](https://user-images.githubusercontent.com/102145298/161883205-2b7fd73a-9b3e-4e38-ba4e-f5e6d1952b47.png)
![image](https://user-images.githubusercontent.com/102145298/161883244-077f1093-c33f-4fa8-9907-04248618d8cb.png)

**Comment by DDuann027** [comment]
![image](https://user-images.githubusercontent.com/102145298/161884167-58c102fc-8b7a-4818-9a9f-e84401e81cff.png)

**Comment by Geeyun-JY3** [comment]
#3187
请
善
用
搜
索
， 
看
置
顶

**Comment by Vocare123** [comment]
> ![image](https://user-images.githubusercontent.com/102145298/161884167-58c102fc-8b7a-4818-9a9f-e84401e81cff.png)

同样的情况，我一登录账号，就显示这个灰色的查看封面

**Comment by Dobby233Liu** [comment]
> 同样的情况，我一登录账号，就显示这个灰色的查看封面

这个根据 #3187 可能也是3.0播放器的问题
