### ISSUE TITLE
【bug】快捷方式修改问题

### ISSUE THREAD

**Issue by Cyiming** [the1812/Bilibili-Evolved#3224]
### 对应功能

快捷键扩展

### 问题描述

我修改了快捷方式 但是新快捷和旧快捷都生效

我把开关弹幕d修改成了x  摁x能开关 摁d也能开关 但我就是因为快捷冲突才修改的啊

### 脚本版本

v2.1.7-3-g93939adb9

### 浏览器版本

13.5

### 播放器版本

2.76

### 播放策略

默认

### 错误信息

```shell
没有
```

### 附加截图

![image](https://user-images.githubusercontent.com/45073586/161974337-1c7f8d97-3759-4b04-9ba9-e1e0961f4790.png)

**Comment by the1812** [comment]
因为 b 站原版也是按 d, 需要屏蔽的话可以装一个 `无动作` 插件, 然后把 d 指派到那上面
![image](https://user-images.githubusercontent.com/26504152/161977536-0dade70f-1fd6-4c9a-b554-4e0fbb49660b.png)

**Comment by Cyiming** [comment]
> 因为 b 站原版也是按 d, 需要屏蔽的话可以装一个 `无动作` 插件, 然后把 d 指派到那上面 ![image](https://user-images.githubusercontent.com/26504152/161977536-0dade70f-1fd6-4c9a-b554-4e0fbb49660b.png)

谢谢 我会了  

我发现屏蔽那个快捷必须指定个新的快捷 要不光屏蔽也不生效
