### ISSUE TITLE
似乎不能直接下载过大的视频？

### ISSUE THREAD

**Issue by 35point5** [the1812/Bilibili-Evolved#323]
尝试直接下载两个2g+大小的视频，分别出现了以下错误
![1](https://user-images.githubusercontent.com/29851652/74024644-44daa000-49dd-11ea-9c8e-53fff0f24c29.PNG)
![2](https://user-images.githubusercontent.com/29851652/74024786-81a69700-49dd-11ea-812b-c77e42e60a5e.PNG)

另:有没有合并下载完的分段视频的办法？

**Comment by Coulomb-G** [comment]
下载功能的预计大小那边有一个警告内容,你可以先阅读一下,浏览器本身有限制
过大的视频请使用导出功能
合并请手动通过ffmpeg

**Comment by 35point5** [comment]
> 
> 
> 下载功能的预计大小那边有一个警告内容,你可以先阅读一下,浏览器本身有限制
> 过大的视频请使用导出功能
> 合并请手动通过ffmpeg

感谢
