### ISSUE TITLE
直播信息扩充异常

### ISSUE THREAD

**Issue by lexcy-Lee** [the1812/Bilibili-Evolved#3230]
### 对应功能

直播信息扩充

### 问题描述

直播信息扩充不能再显示多余10个直播间

### 脚本版本

v2.1.7

### 浏览器版本

版本 99.0.4844.51（正式版本） （64 位）

### 播放器版本

2.76.8

### 播放策略

默认

### 错误信息

```shell
无
```

**Comment by Geeyun-JY3** [comment]
请
善
用
搜
索
，
看
置
顶
#3191

**Comment by lexcy-Lee** [comment]
回来了，都回来了
