### ISSUE TITLE
标题和默认显示区域问题

### ISSUE THREAD

**Issue by Cyiming** [the1812/Bilibili-Evolved#3231]
### 对应功能

不清楚

### 问题描述

不知道哪个插件造成的

1、打开新的页面 默认不是显示视频区域 而是视频介绍 这就导致我每新开一个页面看视频都要手动拉到最顶部观看

2、默认视频标题在上边 现在跑下边了 我关了隐藏标题层还是这样

### 脚本版本

2.1.7-3-g93939adb9

### 浏览器版本

13.5

### 播放器版本

2.76

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

显示区域以下方标题为最顶点 不显示播放窗口
![image](https://user-images.githubusercontent.com/45073586/162338025-16f5e9c8-17e1-4109-905c-e033833ef16c.png)

**Comment by the1812** [comment]
看着像是播放器定位 + 播放器置顶的效果
但是你自己装的功能都不清楚啥作用?

**Comment by Cyiming** [comment]
> 看着像是播放器定位 + 播放器置顶的效果 但是你自己装的功能都不清楚啥作用?

谢谢 好了 

功能太多了 有时候弄不清楚了
