### ISSUE TITLE
传统连播模式 及 快捷键拓展 问题

### ISSUE THREAD

**Issue by mofayukeji** [the1812/Bilibili-Evolved#3233]
### 对应功能

传统连播模式+快捷键拓展

### 问题描述

传统连播模式：
![image](https://user-images.githubusercontent.com/103252346/162414216-460d3f0c-0253-4361-a11d-210c24410245.png)
使用的为旧版网页，并未使用新版

在类似
https://www.bilibili.com/video/BV1UL4y1L7bx/
一类视频合集中，手动点击跳转视频时，传统连播的自动开关是正常的，但是如果是倒数第二个播完，自动播最后一个的时候，可能是因为非手动跳转的动作没有被捕捉到，自动开关是没有反应的，依然保持开启状态。
![image](https://user-images.githubusercontent.com/103252346/162413906-c7874c83-6f60-4af8-8a17-2b3cf8563c80.png)
但是在取消分p之前的分p视频时可以正常开关的，如：
https://www.bilibili.com/video/BV1gp4y1D73E?p=11

快捷键拓展：
在开启快捷键拓展并设置自定义按键的情况下，
![image](https://user-images.githubusercontent.com/103252346/162414809-4404d7b3-15a4-447d-ba57-26a62d211f4a.png)
原版按键仍然起效（尝试过不设为空，效果是两个按键都起效）
问题同时出现于默认按键与脚本中显示不同的（可能是因为播放器改版，如点赞改为了q，投币改为w，但脚本中仍是l和c）和如静音（m）一样没改按键的

附播放器版本（非3.X）截图，作为下方播放器版本的补充
![image](https://user-images.githubusercontent.com/103252346/162416118-de8a9cc2-261d-461d-9e8c-e677be341012.png)

### 脚本版本

v2.1.7

### 浏览器版本

Chrome 已是最新版本 版本 100.0.4896.75（正式版本） （64 位）

### 播放器版本

V2.76.5

### 播放策略

AVC

### 错误信息

```shell
图1 加载界面（连播）
图2 跳转信息（连播）
图3 与图1类似，在使用快捷键过程中并无报错
```

### 附加截图

![image](https://user-images.githubusercontent.com/103252346/162416899-35904123-bfba-4484-a680-b18de0997332.png)

![image](https://user-images.githubusercontent.com/103252346/162416703-9f4a1838-295c-4480-9738-a0c31fa146aa.png)

![image](https://user-images.githubusercontent.com/103252346/162417478-bc3db7ea-5c7d-43c3-a0d5-9134741cfa6c.png)

**Comment by the1812** [comment]
传统连播模式的问题了解了, 快捷键扩展你可能需要这个: #3224

**Comment by mofayukeji** [comment]
非常感谢！

**Comment by the1812** [comment]
现在还有这问题吗, 我今天想修一下结果它又正常了...

**Comment by mofayukeji** [comment]
> 现在还有这问题吗, 我今天想修一下结果它又正常了...

啊，刚看到，试了试还是有这个问题，合集里还是不行

**Comment by AnzhiZhang** [comment]
我遇到相同问题，合集视频、稍后观看和收藏的播放全部，这些功能生成的播放列表无法自动关闭连播

**Comment by mofayukeji** [comment]
离谱了，刚才我后台放合集视频，放完它确实正常起效了，在最后一个视频停下来了，但是我再想复现他又不给停了，很怪

**Comment by mofayukeji** [comment]
@the1812 老哥，我好像发现是咋回事了，这事有点玄学，我大概试了几次，不一定是对的。就是合集里边倒数第二个视频，如果是顺顺利利从头放到尾，没有暂停，没有卡顿，那切最后一p的时候会把连播关掉，但是，只要倒数第二个视频不是直接播完，哪怕是暂停了一下，那播完切最后一p就不会关连播。
https://www.bilibili.com/video/BV1rY411p7kH/
我是在这个视频的合集试的，大致上符合我上边说的情况，很玄学，也不知道咋回事。
非常神奇.jpg

**Comment by AnzhiZhang** [comment]
在**合集视频**，直接打开最后一个会关连播
在**收藏夹全部播放**和**稍后观看**，直接打开最后一个不会关连播
猜测合集视频是因为没有下一个视频了才关连播，其它的可能是bug没做判断

**Comment by AnzhiZhang** [comment]
> https://github.com/the1812/Bilibili-Evolved/issues/3233#issuecomment-1128923845

我在收藏夹 <https://www.bilibili.com/medialist/play/ml482004918/BV1jW41157Lm> 测试了，播完倒数第二个到最后一个不会关连播

**Comment by mofayukeji** [comment]
> > [#3233 (comment)](https://github.com/the1812/Bilibili-Evolved/issues/3233#issuecomment-1128923845)
> 
> 提供的合集测试未成功，但是我使用的是二倍速，下面这个也是二倍速测试
> 
> 我在收藏夹 https://www.bilibili.com/medialist/play/ml482004918/BV1jW41157Lm 测试了，播完倒数第二个到最后一个不会关连播

就是说一点都不能动，二倍速也不能开，任何操作都不能有，它就能自己关上，只要不是顺利播完，就关不上

**Comment by mofayukeji** [comment]
> > [#3233 (comment)](https://github.com/the1812/Bilibili-Evolved/issues/3233#issuecomment-1128923845)
> 
> 提供的合集测试未成功，但是我使用的是二倍速，下面这个也是二倍速测试
> 
> 我在收藏夹 https://www.bilibili.com/medialist/play/ml482004918/BV1jW41157Lm 测试了，播完倒数第二个到最后一个不会关连播

我在我那个合集试是开2倍没问题，你二倍速不能在倒数第二个视频开，你得在倒数第三个视频开二倍速，然后再点到倒数第二个，切进倒数第二个之后，倍速什么的一点都不能再动了，而且如果你网络不太好，开始那几秒有卡顿的话就会有问题。在你说的那个合集里边，倒数第二个视频开始几秒总会卡，就是画面不动但是进度条在走，很怪

**Comment by AnzhiZhang** [comment]
> 我在我那个合集试是开2倍没问题，你二倍速不能在倒数第二个视频开，你得在倒数第三个视频开二倍速，然后再点到倒数第二个，切进倒数第二个之后，倍速什么的一点都不能再动了，而且如果你网络不太好，开始那几秒有卡顿的话就会有问题。在你说的那个合集里边，倒数第二个视频开始几秒总会卡，就是画面不动但是进度条在走，很怪

就是从打开倒数第二个就一点不能动，无论前面是否开倍速等，不能碰播放器。卡顿可能是视频码率太高了的问题，无关

**Comment by AUT76** [comment]
传统连播模式好像又用不了了
