### ISSUE TITLE
插件夜间模式适配不全

### ISSUE THREAD

**Issue by Sakura1943** [the1812/Bilibili-Evolved#3235]
### 对应功能

夜间模式

### 问题描述

夜间模式适配不全， 仍有部分页面存在亮色元素
![image](https://user-images.githubusercontent.com/62229444/162557484-53bae6e7-43c8-4b5a-baaf-d46547df6f5d.png)

### 脚本版本

v2.0.8-13-g93accf2ac

### 浏览器版本

Microsoft Edge 100.0.1185.29

### 播放器版本

2.76-9-d4111aec

### 播放策略

默认

### 错误信息

```shell
[Intervention]Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
644973615433908226:1 
GET https://t.bilibili.com/undefined 404
```

### 附加截图

![image](https://user-images.githubusercontent.com/62229444/162557484-53bae6e7-43c8-4b5a-baaf-d46547df6f5d.png)

**Comment by Geeyun-JY3** [comment]
请
善
用
搜
索
#3191
