### ISSUE TITLE
ass字幕在Mac10.15.7系统下omniplayer无法使用，而Bilibili CC字幕工具下载的ass字幕可以，请参考号哈

### ISSUE THREAD

**Issue by adrlil** [the1812/Bilibili-Evolved#3238]
### 对应功能

下载字幕

### 问题描述

下载的ass字幕在Mac10.15.7系统下omniplayer1.4.11版本无法使用，具体情况就是字幕不显示
而Bilibili CC字幕工具下载的ass字幕可以，请参考号哈

两个工具下载的虽然都是ass文件，在具体数据上有区别，具体见下图。

<img width="1206" alt="截屏2022-04-10 22 43 01" src="https://user-images.githubusercontent.com/2324887/162625571-ce8f23bb-cd8f-4f59-9039-f4e5834a0ef8.png">

另外，建议字幕下载功能支持一个多集视频节目的所有集合字幕的下载。
比如：https://www.bilibili.com/video/BV1fV411m7nj 。
感谢辛苦开发！！！

### 脚本版本

2.1.7

### 浏览器版本

chrome 100

### 播放器版本

2.76.9

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

<img width="1206" alt="截屏2022-04-10 22 43 01" src="https://user-images.githubusercontent.com/2324887/162625700-4603c301-20df-4a8f-81a7-2f39a175bf66.png">

**Comment by the1812** [comment]
把两份 ass 文件发一下?

**Comment by adrlil** [comment]
[2个ass文件.zip](https://github.com/the1812/Bilibili-Evolved/files/8499062/2.ass.zip)

**Comment by adrlil** [comment]
srt格式简单，兼容性好，建议增加下载功能哈。

**Comment by the1812** [comment]
对比了一下, 时间轴和内容都是一样的, 可能是 OmniPlayer 的问题
