### ISSUE TITLE
批量下载，除了编号，名称都是一样的？

### ISSUE THREAD

**Issue by Albertliu2012** [the1812/Bilibili-Evolved#324]
**关于批量下载以及拖动选择**

**命名更加智能，多选更加便捷**

**正式版**

**Comment by the1812** [comment]
av号给一下?

**Comment by Albertliu2012** [comment]
> av号给一下?
av84440661

**Comment by Albertliu2012** [comment]
> > av号给一下?
> > av84440661
链接：https://www.bilibili.com/video/av84440661?p=645
导出是不是按照p645的标题命名。。

**Comment by Albertliu2012** [comment]
> > > av号给一下?
> > > av84440661
> > > 链接：https://www.bilibili.com/video/av84440661?p=645
> > > 导出是不是按照p645的标题命名。。
还是一样 
641 - 全面掌握Linux C语言嵌入式系统移植教程(完)
642 - 全面掌握Linux C语言嵌入式系统移植教程(完)

**Comment by the1812** [comment]
没有问题啊, 导出就是那几P的标题, 你选的是哪种导出方式?
```
641 - 20 - wifi开发与应用D5 - WIFI智能家居项目开发（上）－５.flv
642 - 20 - wifi开发与应用D6 - WIFI智能家居项目开发（下）－１.flv
```

<img width="400" src="https://user-images.githubusercontent.com/26504152/74079881-
40af9080-4a78-11ea-8481-d34afcee4b19.png">

<img width="500" src="https://user-images.githubusercontent.com/26504152/74079888-545af700-4a78-11ea-9555-01f6b5caebc0.png">

**Comment by Albertliu2012** [comment]
> 没有问题啊, 导出就是那几P的标题, 你选的是哪种导出方式?
> 
> 641 - 20 - wifi开发与应用D5 - WIFI智能家居项目开发（上）－５.flv
> 642 - 20 - wifi开发与应用D6 - WIFI智能家居项目开发（下）－１.flv

ARIA2 rpc

**Comment by Albertliu2012** [comment]
> > 没有问题啊, 导出就是那几P的标题, 你选的是哪种导出方式?
> > 641 - 20 - wifi开发与应用D5 - WIFI智能家居项目开发（上）－５.flv
> > 642 - 20 - wifi开发与应用D6 - WIFI智能家居项目开发（下）－１.flv
> 
> ARIA2 rpc

# Generated by Bilibili Evolved Video Export
# https://github.com/the1812/Bilibili-Evolved/

  user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
  out=641 - 全面掌握Linux C语言嵌入式系统移植教程(完).flv
  split=12

  user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
  out=642 - 全面掌握Linux C语言嵌入式系统移植教程(完).flv
  split=12

  user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
  out=643 - 全面掌握Linux C语言嵌入式系统移植教程(完).flv
  split=12

  user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
  out=644 - 全面掌握Linux C语言嵌入式系统移植教程(完).flv
  split=12

  user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
  out=645 - 全面掌握Linux C语言嵌入式系统移植教程(完).flv
  split=12

**Comment by the1812** [comment]
检查下设置里的`批量命名格式`, 是不是设成`[n - ][title]`了?
分P标题应该是`[n - ][ep]`

**Comment by Albertliu2012** [comment]
> 检查下设置里的`批量命名格式`, 是不是设成`[n - ][title]`了?
> 分P标题应该是`[n - ][ep]`

THX，解决了
