### ISSUE TITLE
展开弹幕列表跟简化评论区同时使用时 看视频发评论的时候表情栏会被旁边的弹幕列表盖住

### ISSUE THREAD

**Issue by balh55y** [the1812/Bilibili-Evolved#3241]
### 对应功能

展开弹幕列表和简化评论区

### 问题描述

展开弹幕列表跟简化评论区同时使用时
看视频发评论的时候表情栏会被旁边的弹幕列表盖住
![image](https://user-images.githubusercontent.com/85926883/162929728-1ab10c39-cee0-4f06-82d6-967d841f4af5.png)

### 脚本版本

简化评论区Commit: 28933d6c6 展开弹幕列表Commit: 28933d6c6

### 浏览器版本

100.0.4896.75（正式版本） （64 位）

### 播放器版本

V2.76.5

### 播放策略

默认

### 错误信息

```shell
错误信息貌似没啥
(7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}]0: {__ob__: Ie}count: （…）href: （…）name: （…）prop: （…）__ob__: Ie {value: {…}, dep: fe, vmCount: 0}get count: ƒ ()set count: ƒ (t)get href: ƒ ()set href: ƒ (t)get name: ƒ ()set name: ƒ (t)get prop: ƒ ()set prop: ƒ (t)[[Prototype]]: Object1: {__ob__: Ie}2: {__ob__: Ie}3: {__ob__: Ie}4: {__ob__: Ie}5: {__ob__: Ie}6: {__ob__: Ie}length: 7[[Prototype]]: Array(0)
VM7187:28 reply 0 0
VM7187:28 at 0 0
VM7187:28 like 0 2
VM7187:28 sys_msg 0 0
VM7187:28 user_msg 0 132
```

### 附加截图

![image](https://user-images.githubusercontent.com/85926883/162932085-ae5dcd53-8859-4e91-be96-e7d7ebda8e4a.png)

**Comment by the1812** [comment]
为啥你的弹幕列表这么长?

**Comment by balh55y** [comment]
我也不清楚，换edge看（没用插件）也挺长的
![image](https://user-images.githubusercontent.com/85926883/162963939-75f776d5-84c7-44c2-b8df-e782f6e41576.png)

**Comment by Geeyun-JY3** [comment]
新版播放页没适配：#2615

**Comment by the1812** [comment]
原来如此, 那也算新版播放页的问题吧
