### ISSUE TITLE
夜间模式不适配动态页面，不知道是不是我BUG了

### ISSUE THREAD

**Issue by fgo1212** [the1812/Bilibili-Evolved#3257]
### 对应功能

夜间模式不适配动态页面，不知道是不是我BUG了

### 问题描述

夜间模式不适配动态页面，不知道是不是我BUG了
谷歌浏览器Tampermonkey BETA 版本4.12.6127
地址https://t.bilibili.com/?tab=video

### 脚本版本

Bilibili Evolved	2.1.8

### 浏览器版本

Chromium 80.0.3987.163

### 播放器版本

播放器没问题

### 播放策略

AVC

### 错误信息

```shell
夜间模式不适配动态页面，不知道是不是我BUG了
```

**Comment by Geeyun-JY3** [comment]
请
善
用
搜
索
#3191
，
更
新
日
志
也
写
得
十
分
清
楚
https://github.com/the1812/Bilibili-Evolved/releases/tag/v2.1.8
