### ISSUE TITLE
会导致B站开放平台的文档导航显示错乱

### ISSUE THREAD

**Issue by SetoKaiba** [the1812/Bilibili-Evolved#3259]
### 对应功能

似乎不是某个功能引起的，把所有功能都关闭还是这样。然后把整个油猴脚本关闭是好的。

### 问题描述

会导致B站开放平台的文档导航显示错乱

### 脚本版本

v2.1.8-4-g01590d883

### 浏览器版本

Chrome 已是最新版本 版本 102.0.4997.0（正式版本）dev （64 位）

### 播放器版本

和播放器脚本无关，视频的2.76.13-79e71521，直播的3.6.38

### 播放策略

默认

### 错误信息

```shell
open-live.bilibili.com/:1 Unchecked runtime.lastError: The message port closed before a response was received.
WorkshopPatchouli.umd.min.1.js:9 [bxios error]: CSRF TOKEN 获取失败，请重新登录后再试
O @ WorkshopPatchouli.umd.min.1.js:9
```

### 附加截图

![image](https://user-images.githubusercontent.com/159540/163755836-b2c68617-8eb6-4f71-837e-6deeb7da6648.png)
这是使用Bilibili Evolved导致错乱的
![image](https://user-images.githubusercontent.com/159540/163755912-62524fcf-c2c8-4e67-8e08-1a3d8ac3b8cf.png)
这是不使用Bilibili Evolved正常的

**Comment by the1812** [comment]
我这看起来是正常的
![image](https://user-images.githubusercontent.com/26504152/164033861-c7bb41e0-f6b0-4a07-ad8a-dcd9d0e77867.png)

**Comment by SetoKaiba** [comment]
![image](https://user-images.githubusercontent.com/159540/164035218-f0dcc32b-6a38-492a-94c6-ba742562a672.png)
我看了一下，是bilibili-evolved注入的sidebar遮住了。然后看了一下class，刚好bilibili-evolved的class是sidebar，然后文档的导航的class也是sidebar，应该是bilibili-evolved的sidebar用了导航的class，然后遮住了。

**Comment by SetoKaiba** [comment]
我这是匿名窗口，并且，只激活了bilibili-evolved一个油猴脚本。

**Comment by SetoKaiba** [comment]
我应该也开了自动隐藏侧边栏，默认不是自动隐藏么，是两个小球缩了一半进去是自动隐藏么？
嗯，排除应该也能解决问题。
