### ISSUE TITLE
每个视频下载了三遍？

### ISSUE THREAD

**Issue by 180505** [the1812/Bilibili-Evolved#326]
[n][_ep] 批量下载用的是这个格式 但是每个视频都有多下载两份 比如demo.avi  下载到本地就有demo-1.avi  demo-2.avi demo-3.avi  求解决 
另外  求视频改名字通配符号
![360截图167204087713485](https://user-images.githubusercontent.com/59764624/74115559-ba678b80-4bea-11ea-8e2a-87db851c17ea.png)

**Comment by the1812** [comment]
请提供视频av号

**Comment by 180505** [comment]
> 请提供视频av号

av号怎么查询呢 不懂 第一次用 昨天用的还好好地 今天试了两个视频都这样

**Comment by the1812** [comment]
噢不用了 刚看到图
这个视频是分段的, 3个连着才是完整的一集

**Comment by 180505** [comment]
> 噢不用了 刚看到图
> 这个视频是分段的, 3个连着才是完整的一集


> 噢不用了 刚看到图
> 这个视频是分段的, 3个连着才是完整的一集

嗷嗷 我刚看内容 确实是连续的 有办法连在一起吗 如果操作麻烦的话就算了

**Comment by the1812** [comment]
连一块需要用到 [ffmpeg](https://ffmpeg.org/), 用法见 #201 的讨论

**Comment by 180505** [comment]
> 连一块需要用到 [ffmpeg](https://ffmpeg.org/), 用法见 #201 的讨论

好的 谢谢
