### ISSUE TITLE
下载视频界面没有开始按钮

### ISSUE THREAD

**Issue by seasonxuan** [the1812/Bilibili-Evolved#3263]
### 对应功能

下载视频

### 问题描述

下载视频的界面，向下滚动到底部都没有开始按钮。
![image](https://user-images.githubusercontent.com/16759124/163969025-44265cef-8773-44cd-8c03-f5a9a4123a4c.png)
![image](https://user-images.githubusercontent.com/16759124/163969318-9496212f-d455-4a35-8b93-68007533b916.png)

### 脚本版本

2.1.8

### 浏览器版本

Chrome版本: 100.0.4896.127（正式版本） （64 位）

### 播放器版本

2.76.14

### 播放策略

默认

### 错误信息

```shell
没有错误
```

**Comment by Geeyun-JY3** [comment]
#2718？

**Comment by ID1094368067** [comment]
欸，您居然能看见下载界面？我添加了一堆功能后只看到“转到biliplus”
