### ISSUE TITLE
自定义顶栏会导致页面变宽

### ISSUE THREAD

**Issue by cometeme** [the1812/Bilibili-Evolved#327]
**关于哪一项功能**
自定义顶栏

**问题描述**
在开启自定义顶栏之后，会导致页面变宽（具体现象可见附加截图）
此时会发现网页能够向右滚动，滚动后就会出现白边
在首页和视频播放页均有此现象

**脚本版本**
- 离线版 560.80
- 预览离线版 574.34

**浏览器版本**
Firefox 72.0.2 (64-bit)

**错误信息**
无

**附加截图**
<img width="1442" alt="Xnip2020-02-11_16-40-52" src="https://user-images.githubusercontent.com/22635759/74222376-524e9d80-4cef-11ea-89ce-555d3a8d75b4.png">
<img width="1494" alt="Screen Shot 2020-02-11 at 4 41 37 PM" src="https://user-images.githubusercontent.com/22635759/74222379-54186100-4cef-11ea-9c66-bf7fd28a0a99.png">

**Comment by xqin** [comment]
遇到了相同的情况.

正常情况:

![image](https://user-images.githubusercontent.com/1265888/74598485-7de5d500-50ad-11ea-8cd0-ba797dc1c19e.png)

开启使用自定义顶栏之后, 导航坏掉了(变宽, 头像URL出错)

![image](https://user-images.githubusercontent.com/1265888/74598495-9c4bd080-50ad-11ea-9600-2e71c82f7e23.png)

PS: 我的账号没有头像, 所以是使用的默认头像.

关于头像那里, 我看一下代码, 应该是代码的bug导致的.

源头像URL地址:
`//i0.hdslb.com/bfs/face/member/noface.jpg@154w_155h_1c_100q.webp`
开启自定义导航之后的地址:
`https://www.bilibili.com/static.hdslb.com/images/member/noface.gif`

出错的代码应该是下面这两行:

https://github.com/the1812/Bilibili-Evolved/blob/master/src/style/custom-navbar/simple/custom-navbar-user-info.ts#L186

https://github.com/the1812/Bilibili-Evolved/blob/master/src/style/custom-navbar/simple/custom-navbar-user-info.ts#L191

![image](https://user-images.githubusercontent.com/1265888/74598578-ad491180-50ae-11ea-99e8-dd4afa5ccee0.png)

186 行的代码 指定的URL没有加 协议头,也没有使用自适应协议, 所以在设置 `src` 被当成了相对地址.

![image](https://user-images.githubusercontent.com/1265888/74598599-f4370700-50ae-11ea-8f63-219d66b4a6e8.png)


@the1812

**Comment by the1812** [comment]
感谢提醒 头像的问题很快会在预览版中修复 不过Firefox里向右滚动的问题我还没找着原因

**Comment by the1812** [comment]
向右滚动也修复了

**Comment by jeffswt** [comment]
Firefox 73.0 同向右滚动 bug

（补充）以及另一个应该跟这个问题相关的 bug

缩放只有在 90%, 120% 时候顶栏宽度显示正常，否则都会有顶栏过宽的问题（并不能自适应宽度）
