### ISSUE TITLE
多P番剧中特殊剧集无法下载

### ISSUE THREAD

**Issue by Fish-Who** [the1812/Bilibili-Evolved#3276]
### 对应功能

下载视频  Commit: 01590d883 

### 问题描述

无法下载如总集篇, SP等不在主剧集范围内的剧集
e.g.: https://www.bilibili.com/bangumi/play/ss5989 or https://www.bilibili.com/bangumi/play/ep103876 or https://www.bilibili.com/video/BV1Jx411v7cG

### 脚本版本

 v2.1.8-4-g01590d883

### 浏览器版本

firefox 99.0.1 (64-bit) manjaro linux

### 播放器版本

3.8.2

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/56763355/165158936-c683e7dc-0d1e-43a6-a660-9d5b4516365d.png)

**Comment by Geeyun-JY3** [comment]
请善用搜索：#2834
