### ISSUE TITLE
下载插件不能下载mp4格式的视频

### ISSUE THREAD

**Issue by hexi** [the1812/Bilibili-Evolved#3286]
### 对应功能

下载插件不能下载mp4格式的视频

### 问题描述

[v2.1.8-4-g01590d883](https://www.bilibili.com/video/BV1iB4y1K7q8?p=7)
【100集全】中国传统文化双语纪录片 第七个视频

### 脚本版本

v2.1.8-4-g01590d883

### 浏览器版本

版本 101.0.4951.41（正式版本） (x86_64)

### 播放器版本

V2.77.2

### 播放策略

默认

### 错误信息

```shell
点击下载会打开一个新的页面
```

### 附加截图

点击下载会打开一个新的页面

**Comment by the1812** [comment]
#3234?

**Comment by MaiReversal** [comment]
如果你是打算下载视频（不是番剧）的播放列表，我建议你安装和使用github上的yt-dlp和ffmpeg，实际上很多视频本身是不具有mp4格式的，或者它们虽然有mp4格式，但是是video only或者audio only的，所以对于这种非番剧的视频，可以使用yt-dlp下载下来，再配合ffmpeg将其合并。如果你完全不会使用，你可以参考我截图中的命令，即
先cd进你要下载的目录
yt-dlp.exe --newline -i -ignore-config --hls-prefer-ffmpeg "你要下载视频的url"(截图中的其它命令是我下播放列表的时候用的，实际上下单个视频的时候并不起作用)
如果你对我推荐的两个项目有疑问，你可以联系我，我会抽空给你回复。
![image](https://user-images.githubusercontent.com/58775597/169438393-96897798-ed4a-45e8-b3c3-7ad74a61307f.png)
![image](https://user-images.githubusercontent.com/58775597/169438368-65cc69a4-91ff-440e-8059-8452f7bf7fb3.png)
![image](https://user-images.githubusercontent.com/58775597/169438420-34ef0026-da5e-486e-820d-40d36b4b2e69.png)
