### ISSUE TITLE
希望加入自动跳过”5秒后播放下一个“

### ISSUE THREAD

**Issue by CodeLunatic** [the1812/Bilibili-Evolved#329]
**关于哪一项功能**

自动跳过5秒后播放下一个，5秒很漫长

**期望的效果**

![image](https://user-images.githubusercontent.com/40259896/74437776-aac69c00-4ea3-11ea-8b61-db0f936312a7.png)

**脚本版本**

预览离线版【最新版】

**Comment by the1812** [comment]
<img width="400" src="https://user-images.githubusercontent.com/26504152/74454024-3e0ccb00-4ebe-11ea-8514-db27f72a81e2.png">

**Comment by CodeLunatic** [comment]
感谢，用了这么久真不知道这个功能😄
