### ISSUE TITLE
番剧不能下载问题

### ISSUE THREAD

**Issue by QRQF001** [the1812/Bilibili-Evolved#3294]
### 对应功能

其他番剧都正常，目前只发现 名侦探柯南日语版https://www.bilibili.com/bangumi/play/ep321808这个不能下载
但是柯南国语版却可以，日语版获取不到分P
我有大会员！

### 问题描述

番剧ep321808

### 脚本版本

已经更新到最新版本2.1.8.4

### 浏览器版本

谷歌浏览器91.0.4472.77

### 播放器版本

3.8.2

### 播放策略

AV1

### 错误信息

```shell
其他番剧都正常，目前只发现 名侦探柯南日语版https://www.bilibili.com/bangumi/play/ep321808这个不能下载
但是柯南国语版却可以，日语版获取不到分P
我有大会员！
```

### 附加截图

![image](https://user-images.githubusercontent.com/62094806/166217745-1a702dd4-05fa-4b02-9f01-4d8b03390026.png)

**Comment by CloudyEagle** [comment]
![image](https://user-images.githubusercontent.com/58777085/166455642-6b2a6a94-ac93-4d1b-befc-74fa0d09aa52.png)
我这边没问题，点一下全选试试，能不能抓到列表

**Comment by the1812** [comment]
这个列表太长了, 打开后会先显示 0 个, 要等一会才会加载出来
