### ISSUE TITLE
极简模式下，首页头图丢失的问题

### ISSUE THREAD

**Issue by Malus-Mill** [the1812/Bilibili-Evolved#330]
**关于哪一项功能**

**问题描述**

打开首页

**脚本版本**

离线版560.80

**浏览器版本**

Google Chrome 已是最新版本
版本 80.0.3987.106（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/53999738/74523806-ccce2600-4f58-11ea-926e-4f64460b9e6c.png)
![image](https://user-images.githubusercontent.com/53999738/74523826-d5266100-4f58-11ea-8661-fd138698fd10.png)

**Comment by Malus-Mill** [comment]
![image](https://user-images.githubusercontent.com/53999738/74524127-61388880-4f59-11ea-9201-e783cd8ac55c.png)

**Comment by Coulomb-G** [comment]
是否还开着和b站相关的其他的插件或者脚本?

**Comment by Malus-Mill** [comment]
> 是否还开着和b站相关的其他的插件或者脚本?
开着，但在首页只有那一个脚本在运行
![image](https://user-images.githubusercontent.com/53999738/74528180-8d0c3c00-4f62-11ea-9f76-d127ef48162c.png)

**Comment by Coulomb-G** [comment]
设置弹窗的右上角有个「导出设置」,你可以导出后将文件发过来看看

**Comment by Malus-Mill** [comment]
> 设置弹窗的右上角有个「导出设置」,你可以导出后将文件发过来看看

[bilibili-evolved-settings.zip](https://github.com/the1812/Bilibili-Evolved/files/4204399/bilibili-evolved-settings.zip)

**Comment by Malus-Mill** [comment]
> 是否还开着和b站相关的其他的插件或者脚本?
拓展程序中的AdBlock — 最佳广告拦截工具，书签侧边栏，迅雷下载支持和IDM Integration Module开着的时候有一定几率不加载
![image](https://user-images.githubusercontent.com/53999738/74531741-7f59b500-4f68-11ea-85cf-2eba38037292.png)
![image](https://user-images.githubusercontent.com/53999738/74531761-884a8680-4f68-11ea-966e-0d30854a13b3.png)
![image](https://user-images.githubusercontent.com/53999738/74531888-cfd11280-4f68-11ea-9076-28cf46d3a390.png)

**Comment by the1812** [comment]
在Console里能正常运行这段代码吗?
```js
const { getBlackboards } = await bilibiliEvolved.resources.importAsync('blackboard')
console.table(await getBlackboards())
```

**Comment by Malus-Mill** [comment]
> 在Console里能正常运行这段代码吗?
> 
> ```js
> const { getBlackboards } = await bilibiliEvolved.resources.importAsync('blackboard')
> console.table(await getBlackboards())
> ```
看样子不行
userscript.html?id=d43db4c1-5719-4797-ad34-f97dfb174968:14298 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null TypeError: Cannot read property 'querySelector' of null
    at r (userscript.html?id=d43db4c1-5719-4797-ad34-f97dfb174968:14297)
    at <anonymous>:3:29
userscript.html?id=d43db4c1-5719-4797-ad34-f97dfb174968:14297 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at r (userscript.html?id=d43db4c1-5719-4797-ad34-f97dfb174968:14297)
    at <anonymous>:3:29
![image](https://user-images.githubusercontent.com/53999738/74551617-7da2e800-4f8e-11ea-906d-fdcb08a33db2.png)
![image](https://user-images.githubusercontent.com/53999738/74551723-a9be6900-4f8e-11ea-948d-917724da2e5c.png)

**Comment by Malus-Mill** [comment]
[image: image.png]
[image: image.png]

Grant Howard <notifications@github.com> 于2020年2月14日周五 下午8:37写道：

**Comment by Malus-Mill** [comment]
> > 在Console里能正常运行这段代码吗?
> > ```js
> > const { getBlackboards } = await bilibiliEvolved.resources.importAsync('blackboard')
> > console.table(await getBlackboards())
> > ```
> 
> 看样子不行
> userscript.html?id=d43db4c1-5719-4797-ad34-f97dfb174968:14298 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null TypeError: Cannot read property 'querySelector' of null
> at r (userscript.html?id=d43db4c1-5719-4797-ad34-f97dfb174968:14297)
> at :3:29
> userscript.html?id=d43db4c1-5719-4797-ad34-f97dfb174968:14297 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
> at r (userscript.html?id=d43db4c1-5719-4797-ad34-f97dfb174968:14297)
> at :3:29
> ![image](https://user-images.githubusercontent.com/53999738/74551617-7da2e800-4f8e-11ea-906d-fdcb08a33db2.png)
> ![image](https://user-images.githubusercontent.com/53999738/74551723-a9be6900-4f8e-11ea-948d-917724da2e5c.png)
但在二次刷新之后会正常运行
![image](https://user-images.githubusercontent.com/53999738/74552079-66182f00-4f8f-11ea-802f-3a112e1542ed.png)

**Comment by the1812** [comment]
那看来是没获取到活动信息, 有什么反广告插件拦截了吗?

**Comment by Malus-Mill** [comment]
> 那看来是没获取到活动信息, 有什么反广告插件拦截了吗?
。。。好像是被拦截了。。。禁止运行之后好了。。。
AdBlock 
![image](https://user-images.githubusercontent.com/53999738/74583242-23db0600-5000-11ea-984c-3c0a6ce722c2.png)

**Comment by Malus-Mill** [comment]
> 那看来是没获取到活动信息, 有什么反广告插件拦截了吗?

虽然想这样说，但 估计是联合作案的，单独设置某一个选项并没有解决问题
![image](https://user-images.githubusercontent.com/53999738/74583297-9946d680-5000-11ea-9a56-54f971e078e7.png)

**Comment by the1812** [comment]
调一下反广告的规则列表吧, 可能AdBlock检测到有广告就整个给删掉了, 正常运行的那次截图里5个活动刚好都不是广告(`isAd`为`false`)

**Comment by Malus-Mill** [comment]
> 调一下反广告的规则列表吧, 可能AdBlock检测到有广告就整个给删掉了, 正常运行的那次截图里5个活动刚好都不是广告(`isAd`为`false`)

没用，我把它关了，还是那样

**Comment by the1812** [comment]
#647 有类似的问题, 是被AdGuard屏蔽了, 不知道你有没有装AdGuard?

**Comment by Malus-Mill** [comment]
> [＃647](https://github.com/the1812/Bilibili-Evolved/issues/647)有类似的问题，是被AdGuard屏蔽了，不知道你有没有装AdGuard？

我装的是adblock
在我反馈后，不知道多长时间之后，就神奇的自己消失了，表示什么都没有动，现在想来可能是我网的问题
