### ISSUE TITLE
外置稍后再看组件失效

### ISSUE THREAD

**Issue by whyjxz14** [the1812/Bilibili-Evolved#3301]
### 对应功能

外置稍后再看
commit 2f6e86289

### 问题描述

外置以后还是在。。。里面

### 脚本版本

v2.1.8-preview

### 浏览器版本

chrome 100.0.4896.127（正式版本） （64 位）

### 播放器版本

2.77.2

### 播放策略

默认

### 错误信息

```shell
这个开发者工具控制台log的样子和截图里完全不一样啊。要复制吗。脚本没报错
```

**Comment by hanshuo0531** [comment]
一样，外置稍后在看没有效果。
Commit: 73fa9af28
内部名称: outerWatchlater
v2.1.10-preview-1-g73fa9af28
Edge版本 101.0.1210.47 (正式版本) (64 位)

**Comment by AnzhiZhang** [comment]
Same issue
v2.1.9-10-g757a595fd
Chrome 101.0.4951.67
播放器 V2.78.4
![image](https://user-images.githubusercontent.com/37402126/170007785-ab7b55a0-92c4-4748-b7d0-dab9815dbb81.png)

**Comment by AnzhiZhang** [comment]
> #2615 右下返回旧版

临时解决方案，需要更新支持信标播放器
