### ISSUE TITLE
批量下载所有文件名字都相同的问题

### ISSUE THREAD

**Issue by anchuanyuan** [the1812/Bilibili-Evolved#331]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by anchuanyuan** [comment]
是使用的aria2 rpc 的批量下载功能

**Comment by the1812** [comment]
同 #324 , 在设置里的`批量命名格式`改成`[n - ][ep]`. (才发现我把默认的写错了)

**Comment by anchuanyuan** [comment]
好的，原来还有设置啊..一直不知道哎.....

**Comment by Happiness-in-Danger** [comment]
@the1812 
![@C)PZR)KI39KJ$PKRK@RC`U](https://user-images.githubusercontent.com/45912561/75094821-92ecc780-55c9-11ea-8aac-775777198df1.png)
out那一行的最后那个 - 1.flv这里-前后的空格有法子有法子去了吗？

**Comment by the1812** [comment]
那个是分段FLV产生的, 暂时去不掉
