### ISSUE TITLE
下载功能不见了

### ISSUE THREAD

**Issue by lzstellata** [the1812/Bilibili-Evolved#3318]
### 对应功能

下载视频功能。目前打开功能区变成了灰色的不可点击的查看封面

### 问题描述

昨天还可以下载视频，今天下载功能不见了

### 脚本版本

2.1.9

### 浏览器版本

100.0

### 播放器版本

3.8.12

### 播放策略

默认

### 错误信息

```shell
没有错误信息报告·-
```

### 附加截图

https://user-images.githubusercontent.com/62923862/167704154-8d0e5ff9-f78b-4180-86f2-3d89c9bee151.png

**Comment by lzstellata** [comment]
测试后发现退出登录账号就可以下载视频·0·，但是登录之后就不能下载了

**Comment by y85272** [comment]
俺也一样
![Snipaste_2022-05-11_10-04-59](https://user-images.githubusercontent.com/87901010/167754383-d4af4059-f461-45da-9913-c9f6f92ea0e4.png)
![Snipaste_2022-05-11_10-04-44](https://user-images.githubusercontent.com/87901010/167754388-f909dc15-0b9d-48c0-a0cf-1814bc2b1685.png)

**Comment by lzstellata** [comment]
Thank you for your email. If your message requires a reply, I will respond as soon as possible.Best Regards LU Zhen（Stellata）

**Comment by Geeyun-JY3** [comment]
请
善
用
搜
索
#3187

**Comment by the1812** [comment]
哭了，即使这样都拦不住
![8C08F161-E4D6-4D97-BB11-D1BEEB4FA2D8](https://user-images.githubusercontent.com/26504152/167766482-214c8546-6953-4cf4-b8f0-c5d53c6c97f8.jpeg)
