### ISSUE TITLE
希望能不顯示黑名單

### ISSUE THREAD

**Issue by ZOMBIE39** [the1812/Bilibili-Evolved#332]
![1](https://user-images.githubusercontent.com/37724369/74588345-14c77880-503f-11ea-8338-1bedbd179779.png)
這個應該能隱藏吧 。。。。 就比較多餘啊 這個黑名單顯示在這 非要告訴我 這裡有一個我不喜歡的人 所以可以的話 希望能把評論區的這個黑名單給隱藏了

**Comment by the1812** [comment]
可否提供一下含有这个的评论区结构? (右键-检查元素)
类似这样的
![image](https://user-images.githubusercontent.com/26504152/76934897-02d14200-692b-11ea-8c73-04c150ea7078.png)

**Comment by ZOMBIE39** [comment]
> 可否提供一下含有这个的评论区结构? (右键-检查元素)
> 类似这样的
> ![image](https://user-images.githubusercontent.com/26504152/76934897-02d14200-692b-11ea-8c73-04c150ea7078.png)

![123456](https://user-images.githubusercontent.com/37724369/77737907-38c0a580-7052-11ea-8532-c750466a6f5b.png)
是這個了吧

**Comment by the1812** [comment]
是的

**Comment by the1812** [comment]
似乎目前没有很好的办法隐藏掉
从截图来看 只能从黑名单用户那里出发 但是CSS没法往父级选 只能隐藏掉同级的
也就是说最后会剩个头像和一些边距
![image](https://user-images.githubusercontent.com/26504152/80074657-156b1680-857c-11ea-8cc6-e1c6db251e83.png)
![image](https://user-images.githubusercontent.com/26504152/80074712-2c116d80-857c-11ea-8039-ab66dbee3133.png)
