### ISSUE TITLE
图片批量导出文件名错误

### ISSUE THREAD

**Issue by 7654** [the1812/Bilibili-Evolved#3326]
### 对应功能

图片批量导出
Commit: 9c9c5fd27

### 问题描述

动态图片批量导出图片名称错误
动态图片命名格式[user][ - id][ - n]
导出的图片名称u22er - i13 - 4
user段随机
id从i10到i13,每天增加1
另外UP动态页和动态详情页没有导出图片功能了

### 脚本版本

 v2.1.9-8-g9c9c5fd27

### 浏览器版本

Firefox 100

### 播放器版本

2.77.5

### 播放策略

默认

### 错误信息

```shell
文件下载 u38er - i13 - 1.jpg Bilibili Evolved.user.js:216:1442
```

**Comment by xxx-lb** [comment]
我也是。
Microsoft Edge
版本 102.0.1245.33 (正式版本) (64 位)
Bilibili Evolved v2.2.1
violentmonkey v2.13.0
