### ISSUE TITLE
触摸---播放器触摸支持 功能BUG

### ISSUE THREAD

**Issue by zhaoyu999** [the1812/Bilibili-Evolved#3329]
### 对应功能

触摸---播放器触摸支持

### 问题描述

打开     播放器触摸支持 这个功能的时候，视频播放界面  进度条 和 底部的功能按钮，离的太近啦。导致视频放到后半段的时候，拖不动进度条。

### 脚本版本

Stable v1.12.22  内容包: 61f038c

### 浏览器版本

      edge  版本 101.0.1210.39 (正式版本) (64 位)

### 播放器版本

更新历史 2.77.5-ccdf4987

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

打开   播放器触摸支持 这个功能的时候，视频播放界面 的 进度条 和 底部的功能按钮，离的太近啦。导致视频放到后半段的时候，拖不动进度条。
![图片1](https://user-images.githubusercontent.com/69742912/168478336-eef77388-bc45-435f-a200-45dd534f8f4e.png)
![图片2](https://user-images.githubusercontent.com/69742912/168478345-42bde2b6-43f1-48a7-98c9-864e3222ded2.png)

**Comment by Geeyun-JY3** [comment]
v1 不维护啦……

**Comment by zhaoyu999** [comment]
好吧

**Comment by zhaoyu999** [comment]
> v1 不维护啦......

好吧
