### ISSUE TITLE
下载视频的时候考虑自适应清晰度吗？

### ISSUE THREAD

**Issue by CodeLunatic** [the1812/Bilibili-Evolved#333]
**问题描述**

当前是下载视频的时候清晰度必须等于用户手动设定的清晰度的时候下载链接才能获取成功，但是这样并不好，给人的感觉是插件有问题了，因为很多时候当设置参数qn=116和qn=74的时候都会提示“获取下载链接失败, 请确认当前账号有下载权限后重试.”

推荐修改成，如果用户设置的清晰度高于获取到的清晰度，要以接口提供的清晰度为准，低于也一样，其他情况按用户设定的清晰度走
https://github.com/the1812/Bilibili-Evolved/blob/b127b08b7fec1d90111c323006a7446432304666/src/video/download-video/download-video.ts#L175

**脚本版本**

预览离线版[最新版本]

**浏览器版本**

Chrome 80.0.3987.106（正式版本） （64 位）

**错误信息**

```javascript
userscript.html?id=cc807b0b-c1a5-4c55-a89b-7ef1155fc628:2057 Error: 获取下载链接失败, 请确认当前账号有下载权限后重试.
    at u.fetchVideoInfo (userscript.html?id=cc807b0b-c1a5-4c55-a89b-7ef1155fc628:14362)
    at async h.downloadInfo (userscript.html?id=cc807b0b-c1a5-4c55-a89b-7ef1155fc628:14362)
    at async Vue.formatChange (userscript.html?id=cc807b0b-c1a5-4c55-a89b-7ef1155fc628:14362)
```
**附加截图**
![image](https://user-images.githubusercontent.com/40259896/74589649-f44ced80-5041-11ea-8cb6-90931fac2bfa.png)

**Comment by the1812** [comment]
qn=116和qn=74 对应 1080P60和720P60, 这两档清晰度是需要大会员的, 没有大会员就会返回低一些的清晰度, 如果不报错用户可能就以为真的就能下1080P60了(实际上得到的可能就是普通的1080P), 或者说是破解了大会员限制的错觉.
当然这个报错确实也迷惑了很多人, 我在考虑要不要再判断一下用户是否为大会员, 不是的话就移除掉这几档清晰度

**Comment by CodeLunatic** [comment]
或者改一下报错信息也不错的，比如说“当前选择的清晰度可能需要大会员，您可以更改清晰度后重试”，我第一次使用这个插件看到这个报错信息的时候感觉插件出问题了，如果不看源码我会一直感觉应该是插件问题？总之这种错觉不太好。

**Comment by the1812** [comment]
嗯 这样也行
