### ISSUE TITLE
(脚本不能正常加载 问题汇总)jsdelivr的CDN已遭到DNS污染及SNI阻断

### ISSUE THREAD

**Issue by DUXING130** [the1812/Bilibili-Evolved#3331]
### 对应功能

所有功能

### 问题描述

在一些情况下，由于托管脚本依赖的jsdeliver的CDN在某些情况下国内无法连接，导致脚本不能正常启用

### 脚本版本

v2.1.9-8-g9c9c5fd27

### 浏览器版本

Microsoft Edge 版本 101.0.1210.47

### 播放器版本

3.8.11

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/95281874/168605341-b9ba7286-071f-4299-8582-2e4f82b8574e.png)

**Comment by the1812** [comment]
给 jsDelivr 挂个梯子吧

**Comment by DUXING130** [comment]
那我关闭这个issue后，您把它pin到首页吧，提醒他们jsDeliver在国内连接不畅，自行解决，不另开issue

**Comment by 1983sxj** [comment]
> 

一直有梯子也没用，请问有办法吗

**Comment by Geeyun-JY3** [comment]
jsDelivr 不再可靠已经是去年年底的事了：#2748

#2826

**Comment by DUXING130** [comment]
> > 
> 
> 一直有梯子也没用，请问有办法吗

请注意该域名是否被代理，如未被代理请自行添加规则

**Comment by hulnonn** [comment]
给SwitchyOmega加了条规则好了，我说怎么这两天一直用不了，谢谢😘

**Comment by HashLiver** [comment]
`fastly.jsdelivr.net`目前还可用，不过未来不排除GFW将`*.jsdelivr.net`一级域名拉清单。

**Comment by HeisensOppings** [comment]
用不了了，这几周加载巨慢，每次都需要二次刷新，然后昨天我重新安装脚本(得挂梯子才能安装)，但没按钮了，没法使用了，得挂梯子才能，有没有办法不挂梯子使用，梯子不常有
![Snipaste_2022-05-20_00-20-33](https://user-images.githubusercontent.com/73877739/169530921-c746a0b8-2624-43c7-9d8e-ac4695a390d7.png)

**Comment by Workear34** [comment]
https://www.landiannews.com/archives/93591.html
_“彼时访问错误是因为jsDelivr的ICP备案被注销，按规定使用国内服务器必须取得ICP备案，因此在备案被注销后CDN方面直接屏蔽了域名访问导致大量网站访问出现异常。
随后项目组将国内访问转到香港服务器基本恢复访问，就是加载速度方面肯定是不如国内服务器加载快的。”_

**Comment by starliiit** [comment]
好奇怪，SwitchyOmega 加了梯子也訪問不了，手動把 lodash 改成字節的 cnd 就可以用了

**Comment by DUXING130** [comment]
> 好奇怪，SwitchyOmega 加了梯子也訪問不了，~手動把 lodash 改成字節的 cdn 就可以用了。~改完功能按鈕裏空空如也，還是寄 ><

那直接让梯子接管系统代理吧

**Comment by mjz16** [comment]
目前cdn.jsdelivr.net的污染不是加梯子规则可以解决的，但是现在污染似乎只针对cdn这个子域名，可以尝试替换为其他CDN供应商的专用子域名，比如这几个

> CloudFlare可以用：test1.jsdelivr.net、testingcf.jsdelivr.net
> Fastly可以用：fastly.jsdelivr.net
> GCORE可以用：gcore.jsdelivr.net

作者没更新之前可以直接在猴子里编辑代码，把cdn替换成对应子域名即可

**Comment by 66Leo66** [comment]
可否增加使用 https://raw.githubusercontents.com/ 的资源地址？

**Comment by the1812** [comment]
对，之后可能会完全转移到 GitHub raw
（反正都要梯子

**Comment by 66Leo66** [comment]
我上面这个链接是另一个反代服务（ 后面多了个s

**Comment by i0ux1yU** [comment]
看#3356解决方案

**Comment by BakaJzon** [comment]
插个眼

另：如有更新，希望能在插件中加入自定义源
如 `cdn.jsdelivr.net` => `ghproxy.example.com/https://github.com`

**Comment by YheonYeung** [comment]
我設更新網址為raw.githubusercontent，不要每次更新都把地址改jsdelivr！

**Comment by DUXING130** [comment]
> 对，之后可能会完全转移到 GitHub raw （反正都要梯子
把这问题PINNED一下吧，我再改个名字，全搁这问为啥用不了呢

**Comment by wdy-bit** [comment]
我已解决有梯子开到全局就好了，好了后试一下按钮还在吗，在就改到你原来的设置

**Comment by Lidongde** [comment]
owner能描述清楚些嘛，没get到问题是什么、怎么解决，糊里糊涂的

**Comment by mjz16** [comment]
> owner能描述清楚些嘛，没get到问题是什么、怎么解决，糊里糊涂的

如果没有遇到插件的使用问题（无法更新/加载插件）说明你应该未受到污染影响
如果遇到上述问题，可以使用raw.githubusercontent更新，或者参考我之前的处理方法处理（https://github.com/the1812/Bilibili-Evolved/issues/3331#issuecomment-1133831873）

**Comment by DUXING130** [comment]
> owner能描述清楚些嘛，没get到问题是什么、怎么解决，糊里糊涂的

这个问题指那些脚本不能正常启动或者功能丧失的，因为脚本的大部份依赖托管于jsdelivr的CDN之上，你每次在B站想用这个甲苯是，都会从jsdelivr的CDN同步数据到本地，然而这个CDN在国内大部分区域已无法直连，所以才要换掉加载域名，或者挂提子

**Comment by BakaJzon** [comment]
虽说加插件能解决问题，再怎么着也不是个事啊。有没有能自定义的可能？或是使用gitee？

**Comment by the1812** [comment]
会支持自定义，不过需要自行 fork

**Comment by superen7527** [comment]
还是用不了有梯子

**Comment by Awakumori** [comment]
设置V2ray为全局代理,仍然没有解决问题。

**Comment by wdy-bit** [comment]
假期自动回复邮件。你好，我最近正在休习中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Mini-suger** [comment]
更换DNS就可以了

**Comment by Tinhone** [comment]
试了一下，发现改host也可以

**Comment by wdy-bit** [comment]
假期自动回复邮件。你好，我最近正在休习中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by overvantch** [comment]
开发者你好我想反馈一下：（样式）极简首页插件，内部名称：minimalHome，Commit: 3869a146c
其中一项“默认标签页”选项无法生效，具体表现为：我设置了默认标签页为推荐，但首页还是显示动态，推荐在第二页。

**Comment by Ethkuil** [comment]
> 开发者你好我想反馈一下：（样式）极简首页插件，内部名称：minimalHome，Commit: [3869a14](https://github.com/the1812/Bilibili-Evolved/commit/3869a146c41e96d518645564b38ac3adf08a02cc) 其中一项“默认标签页”选项无法生效，具体表现为：我设置了默认标签页为推荐，但首页还是显示动态，推荐在第二页。

复现成功。不过你发的位置似乎不对，我帮你新发个 issue 吧。#3817

**Comment by overvantch** [comment]
> > 开发者你好我想反馈一下：（样式）极简首页插件，内部名称：minimalHome，Commit: [3869a14](https://github.com/the1812/Bilibili-Evolved/commit/3869a146c41e96d518645564b38ac3adf08a02cc) 其中一项“默认标签页”选项无法生效，具体表现为：我设置了默认标签页为推荐，但首页还是显示动态，推荐在第二页。
> 
> 复现成功。不过你发的位置似乎不对，我帮你新发个 issue 吧。#3817

非常感谢！我还以为的找对反馈的板块了（悲）
