### ISSUE TITLE
Dash协议视频FFMpeg问题

### ISSUE THREAD

**Issue by CodeLunatic** [the1812/Bilibili-Evolved#334]
**关于哪一项功能**

**期望的效果**

对于Dash视频的合并可以使用下面的FFMpeg命令：

```shell
./ffmpeg.exe -i "视频文件" -i "音频文件" -c:v copy -c:a aac -strict experimental -map 0:v:0? -map 1:a:0? "输出文件"
```
如果可以自动生成这些命令就好了

**脚本版本**

预览离线版【最新版本】

**Comment by the1812** [comment]
可以给Powershell的Profile里加个函数
```powershell

function Merge-Video ($name) {
  $video = "$($name).mp4"
  $audio = "$($name).m4a"
  $merged = "$($name).merged.mp4"
  ffmpeg -i $video -i $audio -c copy $merged
  if ($LASTEXITCODE -eq 0) {
    Remove-Item $video -Force
    Remove-Item $audio -Force
    Rename-Item $merged $video -Force
  }
}
Set-Alias concat Merge-Video
```
然后就可以运行
```powershell
concat 'xxx'
```
把`xxx.mp4`和`xxx.m4a`合并为一个文件

**Comment by ChaingTsung** [comment]
> 可以给 Powershell 的 Profile 里加个函数
> 
> ```powershell
> function Merge-Video ($name) {
>   $video = "$($name).mp4"
>   $audio = "$($name).m4a"
>   $merged = "$($name).merged.mp4"
>   ffmpeg -i $video -i $audio -c copy $merged
>   if ($LASTEXITCODE -eq 0) {
>     Remove-Item $video -Force
>     Remove-Item $audio -Force
>     Rename-Item $merged $video -Force
>   }
> }
> Set-Alias concat Merge-Video
> ```
> 
> 然后就可以运行
> 
> ```powershell
> concat 'xxx'
> ```
> 
> 把`xxx.mp4`和`xxx.m4a`合并为一个文件

有没有批量合并的
