### ISSUE TITLE
简化评论区导致点赞 点踩 三点显示错误，以及脚本本身设置的图片显示错误

### ISSUE THREAD

**Issue by RickSanchezy** [the1812/Bilibili-Evolved#3341]
### 对应功能

简化评论区

### 问题描述

全部视频和动态都是一样的情况（win7 64位）

### 脚本版本

2.1.9

### 浏览器版本

Edge  101.0.1210.53 64位 正式版

### 播放器版本

2.78.3-1b639637

### 播放策略

默认

### 错误信息

```shell
1
```

### 附加截图
![Z8QTE7{{70E9RO1ABS(R23G](https://user-images.githubusercontent.com/75956223/169634780-158ea0dd-4af4-43e7-9aa2-30f5991cf4d2.png)

![6QG)P 3B8I2Y(5W()QPXJ17](https://user-images.githubusercontent.com/75956223/169634779-cfed4a6d-5596-454a-80e9-328108251395.png)

**Comment by Geeyun-JY3** [comment]
估计也是 jsDelivr 相关问题：#3331

**Comment by icateav** [comment]
发生了一样的问题 折腾了半天浏览器 原来是这个组件导致的吗

**Comment by the1812** [comment]
不是组件的问题, 见 #3331
