### ISSUE TITLE
看不到脚本，找不到任何功能、界面和入口

### ISSUE THREAD

**Issue by Bilx-ZL** [the1812/Bilibili-Evolved#3342]
### 对应功能

脚本启用后看不到脚本，找不到任何功能、界面和入口

<img width="1914" alt="屏幕截图 2022-05-21 175322" src="https://user-images.githubusercontent.com/104142438/169646269-f86090a6-e940-45c1-b684-cee82f78107e.png">

### 问题描述

脚本启用后看不到脚本，找不到任何功能、界面和入口

### 脚本版本

2.1.9

### 浏览器版本

101.0.1210.47 (正式版本) (64 位)

### 播放器版本

3.9.2

### 播放策略

HEVC

### 错误信息

```shell
无此类数据
```

### 附加截图

<img width="1914" alt="屏幕截图 2022-05-21 175322" src="https://user-images.githubusercontent.com/104142438/169646327-1c940104-ef5d-443c-843e-8b48990e4117.png">
<img width="1920" alt="屏幕截图 2022-05-21 175835" src="https://user-images.githubusercontent.com/104142438/169646371-fa31d69a-b9a3-4ecc-8910-bedf0d084b94.png">

**Comment by imshixin** [comment]
#3331

**Comment by Bilx-ZL** [comment]
> #3331

也就是说，现在得挂梯子用了？

**Comment by 36EMiyuki** [comment]
我也是一样的

**Comment by Bang0518** [comment]
我也是一样的，不挂梯子加载不了功能

**Comment by fengziX** [comment]
我挂了梯子 passwall2 proxy里添加了cdn.jsdelivr.net , 还是没用

**Comment by Bilx-ZL** [comment]
直接close可还行

**Comment by the1812** [comment]
重复的当然 close 了

**Comment by fengziX** [comment]
我本来挂了梯子也不行, 后来发现我把cdn.jsdelivr.net丢进直连规则里了, 优先级比代理高, 太尴尬了

**Comment by Bilx-ZL** [comment]
> 我本来挂了梯子也不行, 后来发现我把cdn.jsdelivr.net丢进直连规则里了, 优先级比代理高, 太尴尬了

所以这个脚本，本地没东西，其实是个云端脚本，依靠这个jsdeliver网站运行？然后被墙了就无了

**Comment by the1812** [comment]
依赖的库在 jsDelivr, 被墙了本地代码自然运行不了
