### ISSUE TITLE
关于复原稍后再看位置和网址参数清理的建议

### ISSUE THREAD

**Issue by CodesHunger** [the1812/Bilibili-Evolved#335]
**关于哪一项功能**

1.建议添加  复原稍后再看  功能
2.网址参数清理
**期望的效果**
1.希望可以把网页顶端收藏夹里面的稍后再看复原出来，不知道b站为什么要放进去，多点两下明明比较麻烦
2.网址参数清理能否可以直接去掉点击时链接里面的参数？不然每次都会再刷新一下，电脑反应比较慢，加载时间会变长。
**脚本版本**

正式版1.10.0

请考虑一下建议，谢谢作者！

**Comment by the1812** [comment]
1. 开`自定义顶栏`就在外面了
2. 清理参数不会刷新页面, 提前检测链接反而更消耗性能

**Comment by CodesHunger** [comment]
OK 问题解决了，不知道前几天为什么会自动刷新，现在可以了，感谢！
