### ISSUE TITLE
港澳台番剧页面脚本无法正常运行

### ISSUE THREAD

**Issue by Apkeniqo** [the1812/Bilibili-Evolved#3351]
### 对应功能

所有

### 问题描述

如题，大陆视频、番剧页面脚本工作正常，仅港澳台番剧页面脚本无法正常运行

### 脚本版本

v2.1.9-10-g757a595fd

### 浏览器版本

ms edge 101.0.1210.53

### 播放器版本

2.49.2-f7ef9cd5

### 播放策略

默认

### 错误信息

```shell
userscript.html?name=Bilibili%2520Evolved.user.js&id=4b4ce60a-4bb1-4d86-a9f0-1463b732d0c5:191 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at t (userscript.html?name=Bilibili%2520Evolved.user.js&id=4b4ce60a-4bb1-4d86-a9f0-1463b732d0c5:191:30697)
    at userscript.html?name=Bilibili%2520Evolved.user.js&id=4b4ce60a-4bb1-4d86-a9f0-1463b732d0c5:191:31009
ss41481:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 ()
```

### 附加截图

![屏幕截图 2022-05-22 192442](https://user-images.githubusercontent.com/90621995/169692853-597440d9-7936-4966-93a5-30d972df5cda.png)

**Comment by DUXING130** [comment]
目前可以确认的是，如果你网络正常，Evolved没有问题
![image](https://user-images.githubusercontent.com/95281874/169693837-30db47d7-abbe-4acb-a362-bbfce1ab36aa.png)

**Comment by AzusaHana** [comment]
> ### 对应功能
> 所有
> 
> ### 问题描述
> 如题，大陆视频、番剧页面脚本工作正常，仅港澳台番剧页面脚本无法正常运行
> 
> ### 脚本版本
> v2.1.9-10-g757a595fd
> 
> ### 浏览器版本
> ms edge 101.0.1210.53
> 
> ### 播放器版本
> 2.49.2-f7ef9cd5
> 
> ### 播放策略
> 默认
> 
> ### 错误信息
> ```shell
> userscript.html?name=Bilibili%2520Evolved.user.js&id=4b4ce60a-4bb1-4d86-a9f0-1463b732d0c5:191 
>         
>        Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
>     at t (userscript.html?name=Bilibili%2520Evolved.user.js&id=4b4ce60a-4bb1-4d86-a9f0-1463b732d0c5:191:30697)
>     at userscript.html?name=Bilibili%2520Evolved.user.js&id=4b4ce60a-4bb1-4d86-a9f0-1463b732d0c5:191:31009
> ss41481:1 
>         
>       
>         
>         
>       
>         
>       
>        
>         
>        Failed to load resource: the server responded with a status of 404 ()
> ```
> 
> ### 附加截图
> ![屏幕截图 2022-05-22 192442](https://user-images.githubusercontent.com/90621995/169692853-597440d9-7936-4966-93a5-30d972df5cda.png)

新的港澳台番剧在页面上也加了验证，你看到的是其他脚本重构的页面而不是b站原本的页面，如果是老的番剧不用重构页面的话就能用Evolved，否则用不了

**Comment by the1812** [comment]
#2704

**Comment by Apkeniqo** [comment]
了解。我使用台湾ip观看时页面正常，脚本也正常，但使用脚本“解除B站区域限制”会出现该问题。请问有什么方法可以让脚本不使用重构的页面吗

AzusaHana ***@***.***> 于2022年5月22日周日 23:25写道：
