### ISSUE TITLE
夜间模式下左侧的播放菜单是白底白字的

### ISSUE THREAD

**Issue by jy125131** [the1812/Bilibili-Evolved#3352]
### 对应功能

![image](https://user-images.githubusercontent.com/58042869/169763898-7051db2e-4a54-459a-90d5-b8e825870e82.png)

### 问题描述

夜间模式下左侧的播放菜单是白底白字的，或者是黑底黑字。。很好用，但也很耗机器资源，修复了就不用再添加别的脚本改深色了。

v2.1.9

**Comment by Geeyun-JY3** [comment]
请善用搜索，看置顶。新版播放页见：#2615

**Comment by jy125131** [comment]
明白了，要用旧版模式

Geeyun-JY3 ***@***.***> 于2022年5月23日周一 15:37写道：
