### ISSUE TITLE
关闭所有开关弹幕仍无法显示

### ISSUE THREAD

**Issue by ajian2002** [the1812/Bilibili-Evolved#336]
**脚本版本**
1.10.0
**视频链接**
https://www.bilibili.com/bangumi/play/ss12444
**附加截图**
![image.png](https://i.loli.net/2020/02/17/uymdf6lFZK3vhxR.png)未开启脚本前
![image.png](https://i.loli.net/2020/02/17/ihAxlJbrTHkeF7s.png)开启脚本并关闭所有功能

**Comment by the1812** [comment]
之前似乎有类似的情况, 是本脚本和解除区域限制一起开就会出现的问题

**Comment by ajian2002** [comment]
> 之前似乎有类似的情况, 是本脚本和解除区域限制一起开就会出现的问题

是的,关闭那个区域限制的脚本后即可正常使用

**Comment by Coulomb-G** [comment]
那就关闭吧,用港澳台节点也可以看限制番
