### ISSUE TITLE
视频分P播放标题看不清

### ISSUE THREAD

**Issue by ongerd** [the1812/Bilibili-Evolved#3360]
### 对应功能

![image](https://user-images.githubusercontent.com/105695890/170408351-e4db14a7-2884-4dac-817c-2d43164b8fb7.png)
![image](https://user-images.githubusercontent.com/105695890/170408392-999ff28a-d132-43a2-88b4-e0e0b0b0bfa4.png)
![image](https://user-images.githubusercontent.com/105695890/170408421-f3c018aa-1b9c-4b91-8012-fb6bfe3466df.png)

### 问题描述

分P视频，所有标题都看不清

### 脚本版本

v2.1.9-8-g9c9c5fd27

### 浏览器版本

Microsoft Edge 版本 101.0.1210.53 (正式版本) (64 位)

### 播放器版本

2.78.4

### 播放策略

默认

### 错误信息

```shell
api.github.com/_private/browser/stats:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 400 ()
api.github.com/_private/browser/stats:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 400 ()
```

### 附加截图

![image](https://user-images.githubusercontent.com/105695890/170406867-86c06800-def0-433b-8768-d3d63c86c092.png)

**Comment by Geeyun-JY3** [comment]
看
置
顶
，
请
善
用
搜
索
#2615
