### ISSUE TITLE
Safari浏览器油猴插件更新至4.17.6162版本后，bilibili evolved失效了

### ISSUE THREAD

**Issue by LieQiZai** [the1812/Bilibili-Evolved#3362]
### 对应功能

全部

### 问题描述

Safari油猴插件更新至4.17.6162版本后，bilibili evolved失效，但其他插件目前正常

### 脚本版本

2.1.9

### 浏览器版本

Safari 版本15.5 (17613.2.7.1.8)

### 播放器版本

V2.78.4

### 播放策略

默认

### 错误信息

```shell
无
```

**Comment by i0ux1yU** [comment]
> ### 对应功能
> 全部
> 
> ### 问题描述
> Safari油猴插件更新至4.17.6162版本后，bilibili evolved失效，但其他插件目前正常
> 
> ### 脚本版本
> 2.1.9
> 
> ### 浏览器版本
> Safari 版本15.5 （17613.2.7.1.8）
> 
> ### 播放器版本
> 版本2.78.4
> 
> ### 播放策略
> 默认
> 
> ### 错误信息
> ```shell
> 无
> ```
> 
> ### 附加截图
> _无响应_

解决方法在
https://github.com/the1812/Bilibili-Evolved/issues/3356

**Comment by themrv1ck** [comment]
试了,没用

**Comment by themrv1ck** [comment]
> > ### 对应功能
> > 全部
> > ### 问题描述
> > Safari油猴插件更新至4.17.6162版本后，bilibili evolved失效，但其他插件目前正常
> > ### 脚本版本
> > 2.1.9
> > ### 浏览器版本
> > Safari 版本15.5 （17613.2.7.1.8）
> > ### 播放器版本
> > 版本2.78.4
> > ### 播放策略
> > 默认
> > ### 错误信息
> > ```shell
> > 无
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 附加截图
> > _无响应_
> 
> 解决方法在 #3356

试了 没用 还是一样用不了

**Comment by LieQiZai** [comment]
> > ### 对应功能
> > 全部
> > ### 问题描述
> > Safari油猴插件更新至4.17.6162版本后，bilibili evolved失效，但其他插件目前正常
> > ### 脚本版本
> > 2.1.9
> > ### 浏览器版本
> > Safari 版本15.5 （17613.2.7.1.8）
> > ### 播放器版本
> > 版本2.78.4
> > ### 播放策略
> > 默认
> > ### 错误信息
> > ```shell
> > 无
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 附加截图
> > _无响应_
> 
> 解决方法在 #3356

没用哦，试过了

**Comment by the1812** [comment]
换个浏览器吧，Safari 我现在测不了

**Comment by PatZhuang** [comment]
这个问题应该是 safari 不支持 requestIdleCallback API，目前没有任何办法可以解决，除非作者重写相关代码

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/blob/bc268c1fd2aecdce4fa4f610d48c3efa6dc14a8c/src/client/compatibility.ts#L29-L34

这个有做过兼容性处理的

**Comment by Tongzhao9417** [comment]
实测按照#3356的解决方案之后Safari还是不行

**Comment by 775720665** [comment]
> 实测按照#3356的解决方案之后Safari还是不行

把App Store的油猴卸了，装个旧版的

**Comment by themrv1ck** [comment]
> > 实测按照#3356的解决方案之后Safari还是不行
> 
> 把App Store的油猴卸了，装个旧版的

...旧版的装不了

**Comment by 775720665** [comment]
> > > 实测按照#3356的解决方案之后Safari还是不行
> > 
> > 
> > 把App Store的油猴卸了，装个旧版的
> 
> ...旧版的装不了

去华军软件搜Tampermonkey for Mac我就这么干的

**Comment by Kev1nZheng** [comment]
> 

正版软件受害者

**Comment by Kev1nZheng** [comment]
> > > > 实测按照#3356的解决方案之后Safari还是不行
> > > 
> > > 
> > > 把App Store的油猴卸了，装个旧版的
> > 
> > 
> > ...旧版的装不了
> 
> 去华军软件搜Tampermonkey for Mac我就这么干的

正版软件受害者

**Comment by 775720665** [comment]
> > > > > 实测按照#3356的解决方案之后Safari还是不行
> > > > 
> > > > 
> > > > 把App Store的油猴卸了，装个旧版的
> > > 
> > > 
> > > ...旧版的装不了
> > 
> > 
> > 去华军软件搜Tampermonkey for Mac我就这么干的
> 
> 正版软件受害者

唉、等什么时候更下一版本再回去吧。暂时也就这么个方法了。不然就换浏览器。

**Comment by Hukeqing** [comment]
来问一句解决了嘛，我好多设置在 Tampermonkey😭

**Comment by themrv1ck** [comment]
> > > > > > 实测按照#3356的解决方案之后Safari还是不行
> > > > > 
> > > > > 
> > > > > 把App Store的油猴卸了，装个旧版的
> > > > 
> > > > 
> > > > ...旧版的装不了
> > > 
> > > 
> > > 去华军软件搜Tampermonkey for Mac我就这么干的
> > 
> > 
> > 正版软件受害者
> 
> 唉、等什么时候更下一版本再回去吧。暂时也就这么个方法了。不然就换浏览器。

正版软件受害者+1 目前好像就只有这个办法了. 没辙

**Comment by zhiyuanzhai** [comment]
@the1812 我来提供一个Safari控制台报错信息，不知道有没有帮助。
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/37478391/172060320-cd6abb67-e3fe-4c75-89f2-a5be878e554c.png">
打开控制台，一大串错误，全都是这个。

**Comment by the1812** [comment]
看起来是反广告插件屏蔽了 b 站的用户日志上传, 和 Evolved 没啥关系

**Comment by Felix2yu** [comment]
我开了个隐私窗口，关闭所有扩展，以及只保留Tampermonkey控制台输出如下，不知道有没有帮助

关闭全部扩展：
```
[Error] Failed to load resource: the server responded with a status of 404 () (vendor.314a607f.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (index.905bdf7e.js.map, line 0)
[Log] [correspond] – {code: -101, message: "账号未登录", ttl: 1, …} (sentry-5.15.0.min.js, line 2)
{code: -101, message: "账号未登录", ttl: 1, data: null}Object
[Warning] The resource https://s1.hdslb.com/bfs/static/laputa-home/client/assets/vip-default-banner.6db4a7ed.png was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
```

仅开启Tampermonkey
```
[Error] Unhandled Promise Rejection: TypeError: requestIdleCallback is not a function. (In 'requestIdleCallback((async()=>{const{getUID:e}=await Promise.resolve().then(n.bind(n,4742));e()&&we()}))', 'requestIdleCallback' is undefined)
	（匿名函数） (userscript.html:234:79928)
	asyncFunctionResume
	（匿名函数）
	promiseReactionJobWithoutPromise
	appendChild
	eval (common.js:8:137)
	（匿名函数） (content.js:135)
	E (content.js:135)
	（匿名函数） (content.js:129:302)
	f (topee-content.js:10543)
[Error] Failed to load resource: the server responded with a status of 404 () (index.905bdf7e.js.map, line 0)
[Log] [correspond] – {code: -101, message: "账号未登录", ttl: 1, …} (sentry-5.15.0.min.js, line 2)
{code: -101, message: "账号未登录", ttl: 1, data: null}Objectcode: -101data: nullmessage: "账号未登录"ttl: 1“Object”原型
[Error] Failed to load resource: the server responded with a status of 404 () (vendor.314a607f.js.map, line 0)
[Warning] The resource https://s1.hdslb.com/bfs/static/laputa-home/client/assets/vip-default-banner.6db4a7ed.png was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
```

**Comment by zhiyuanzhai** [comment]
> 看起来是反广告插件屏蔽了 b 站的用户日志上传, 和 Evolved 没啥关系

然而关闭广告插件并没有让Evolved活过来……

**Comment by the1812** [comment]
当然不是反广告的问题，上面也说了没啥关系了
根据 @Felix2yu 提供的日志，`requestIdleCallback` 仍然存在问题

**Comment by zhiyuanzhai** [comment]
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/37478391/173179878-21e12d34-3d27-4013-a505-788f4a9e6c02.png">
事实上我也找到了这个错误

**Comment by mogeko** [comment]
我在**实验性功能**中开启 `requestIdleCallback` 后，脚本能部分可用：比如黑暗模式；

但是只能加载半个页面的内容：

<img width="1436" alt="截屏2022-06-11 21 05 57" src="https://user-images.githubusercontent.com/26341224/173201648-bf69054d-344f-4d85-a1ea-91b75289eb1b.png">

以下是控制台的报错信息：

```
[Error] Failed to load resource: the server responded with a status of 404 () (vendor.1027721c.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (index.10286ded.js.map, line 0)
[Warning] The resource https://s1.hdslb.com/bfs/static/laputa-home/client/assets/vip-default-banner.6db4a7ed.png was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
```

**Comment by chenghaopeng** [comment]
> https://github.com/the1812/Bilibili-Evolved/blob/bc268c1fd2aecdce4fa4f610d48c3efa6dc14a8c/src/client/compatibility.ts#L29-L34
> 
> 这个有做过兼容性处理的

不知道为什么这段代码没有起效。我在全局的位置（代码一开头）加了这些代码“window.requestIdleCallback=e=>window.setTimeout(e,0),window.cancelIdleCallback=e=>{window.clearTimeout(e)}”以后就可以正常使用了。

**Comment by Felix2yu** [comment]
> > https://github.com/the1812/Bilibili-Evolved/blob/bc268c1fd2aecdce4fa4f610d48c3efa6dc14a8c/src/client/compatibility.ts#L29-L34
> > 
> > 这个有做过兼容性处理的
> 
> 不知道为什么这段代码没有起效。我在全局的位置（代码一开头）加了这些代码“window.requestIdleCallback=e=>window.setTimeout(e,0),window.cancelIdleCallback=e=>{window.clearTimeout(e)}”以后就可以正常使用了。

加入后确实就正常了，感谢

**Comment by kid-oh** [comment]
> > https://github.com/the1812/Bilibili-Evolved/blob/bc268c1fd2aecdce4fa4f610d48c3efa6dc14a8c/src/client/compatibility.ts#L29-L34
> > 
> > 这个有做过兼容性处理的
> 
> 不知道为什么这段代码没有起效。我在全局的位置（代码一开头）加了这些代码“window.requestIdleCallback=e=>window.setTimeout(e,0),window.cancelIdleCallback=e=>{window.clearTimeout(e)}”以后就可以正常使用了。

牛逼了 Safari亲测成功解决脚本失效问题 希望作者可以看一下

**Comment by DEabcdp** [comment]
> > https://github.com/the1812/Bilibili-Evolved/blob/bc268c1fd2aecdce4fa4f610d48c3efa6dc14a8c/src/client/compatibility.ts#L29-L34
> > 
> > 这个有做过兼容性处理的
> 
> 不知道为什么这段代码没有起效。我在全局的位置（代码一开头）加了这些代码“window.requestIdleCallback=e=>window.setTimeout(e,0),window.cancelIdleCallback=e=>{window.clearTimeout(e)}”以后就可以正常使用了。

没有完全起作用，动态按钮就显示不正常，全是空白内容，鼠标却能选中。

**Comment by CookieJaySJ** [comment]
> 正版软件受害者+1

正版软件受害者+1

**Comment by ChasYuan** [comment]
4.17.6162版本Tampermonkey
Safari依然无法正常使用

**Comment by zhiyuanzhai** [comment]
> https://github.com/the1812/Bilibili-Evolved/blob/bc268c1fd2aecdce4fa4f610d48c3efa6dc14a8c/src/client/compatibility.ts#L29-L34
> 
> 这个有做过兼容性处理的

可能是一句废话：看起来
```js
!('requestIdleCallback' in window)
```
在新版tampermonkey中不适用了，但是`requestIdleCallback`功能实际上还是没有开启。

**Comment by DEabcdp** [comment]
预览版2.2.4已修复！！！！！！
