### ISSUE TITLE
预览版出现贴图错误问题

### ISSUE THREAD

**Issue by animationplayer** [the1812/Bilibili-Evolved#3363]
### 对应功能

不是某一具体功能

### 问题描述

部分图片变成□
关闭脚本后不会出现该问题
非预览版也不会出现该问题

### 脚本版本

2.1.10-preview

### 浏览器版本

Chrome 版本 101.0.4951.67（正式版本） （64 位）

### 播放器版本

和播放器没有关系

### 播放策略

默认

### 错误信息

```shell
见图
```

### 附加截图

![微信图片_20220527094136](https://user-images.githubusercontent.com/78839082/170617583-97fb7b6b-ac57-4405-91e4-208f08ff1d98.jpg)
![2](https://user-images.githubusercontent.com/78839082/170617593-f01db276-1fc3-4e28-8772-27922fdff1b4.JPG)

**Comment by the1812** [comment]
#3331
