### ISSUE TITLE
为什么在Chrome102.0.5005.63（正式版本）上更新了bilibili evolved插件后无法使用？今天想起来可以更新，但是更新后就无法使用了

### ISSUE THREAD

**Issue by OpsEscarrrrrrr** [the1812/Bilibili-Evolved#3364]
### 对应功能

为什么在Chrome102.0.5005.63（正式版本）上更新了bilibili evolved插件后无法使用？今天想起来可以更新，但是更新后就无法使用了之前使用的是2.0.8，更新到2.1.9

### 问题描述

为什么在Chrome102.0.5005.63（正式版本）上更新了bilibili evolved插件后无法使用？今天想起来可以更新，但是更新后就无法使用了之前使用的是2.0.8，更新到2.1.9

### 脚本版本

2.1.9

### 浏览器版本

Chrome102.0.5005.63（正式版本）

### 播放器版本

unknow

### 播放策略

默认

### 错误信息

```shell
插件在新版Chrome浏览器上失效,图片左侧并不显示设置框，右上油猴显示插件已经在运行
```

### 附加截图

![image](https://user-images.githubusercontent.com/34292127/170668995-7f164028-24a1-478e-892b-6209834c46f0.png)

**Comment by the1812** [comment]
#3331

**Comment by OpsEscarrrrrrr** [comment]
> #3331

好的，挂上梯子后插件已经应用，左侧出现设置栏
