### ISSUE TITLE
在Firefox上页面右侧出现多余空白区域

### ISSUE THREAD

**Issue by storyInAugest** [the1812/Bilibili-Evolved#337]
**问题描述**
在Firefox上页面右侧出现多余空白区域
脚本的正式版、预览版都试过了，我用的是win10，Firefox73，tempermonkey
在RunningCheese定制版上也有同样的问题，不知道是不是我的个例，新edge试了下，没有此类问题

**脚本版本**
Bilibili Evolved (Preview Offline)  579.83

**浏览器版本**
Firefox 73.0

![20200217175114](https://user-images.githubusercontent.com/31837371/74643702-1d8b8c00-51b0-11ea-8cac-b19bc82fcbd5.png)

**Comment by the1812** [comment]
预览离线版请更新到579.88版以上, 昨天刚做的修复
