### ISSUE TITLE
收藏夹不能显示互动视频&下载视频只有480P和360P画质

### ISSUE THREAD

**Issue by pbxs666** [the1812/Bilibili-Evolved#338]
问题描述
1.自定义顶栏后，收藏夹面板（浮窗）不能显示（唯独漏了）互动视频，历史面板正常。
2.下载视频只能下载480P和360P画质，没有下载其他画质的选项。
脚本版本
Bilibili Evolved (Preview) 1.10.3

**Comment by the1812** [comment]
`v1.10.4`已修复

**Comment by pbxs666** [comment]
thank you
