### ISSUE TITLE
话题页面，“自定义顶栏”，搜索功能，弹出内容异常

### ISSUE THREAD

**Issue by timongh** [the1812/Bilibili-Evolved#3383]
### 对应功能

自定义顶栏 搜索

### 问题描述

如下图，在话题页面，搜索框显示异常。话题即动态页面右侧的话题版块中的链接指向的网页，其网址以 www.bilibili.com/v/topic/detail 开头。

![image](https://user-images.githubusercontent.com/46739861/171434702-2f4a0968-8ac3-47b4-9bb5-1ec7a0189f6d.png)

### 脚本版本

v2.1.10-preview-1-g73fa9af28

### 浏览器版本

Microsoft Edge 版本 101.0.1210.53 (正式版本) (64 位)

### 播放器版本

/

### 播放策略

默认

### 错误信息

```shell
/
```

**Comment by Geeyun-JY3** [comment]
新版话题应该一直就没适配过🤪：https://github.com/the1812/Bilibili-Evolved/issues/2136#issuecomment-959647600
