### ISSUE TITLE
关于自定义顶栏的搜索框和简化首页的显示建议

### ISSUE THREAD

**Issue by pbxs666** [the1812/Bilibili-Evolved#339]
关于哪一项功能
1.顶栏的自定义；
2.简化首页

期望的效果
1.自定义顶栏的搜索框希望可以显示搜索历史，最好能加上搜索历史开关功能。
2.简化首页后，不管哪种的简化模式都能与“bilibili网页端添加APP首页推荐”脚本兼容，目前虽然在未简化首页时两个脚本不冲突，但简化首页后上述脚本就失效了，希望可以在简化首页后也能使用上述脚本。至于预期效果随便啦，您自己发挥吧😁。
脚本链接https://greasyfork.org/zh-CN/scripts/368446-bilibili%E7%BD%91%E9%A1%B5%E7%AB%AF%E6%B7%BB%E5%8A%A0app%E9%A6%96%E9%A1%B5%E6%8E%A8%E8%8D%90

脚本版本
Bilibili Evolved (Preview) 1.10.3

**Comment by the1812** [comment]
搜索历史本来就支持的啊, 开关倒是可以加一下
首页推荐不太好迁移到简化首页里, 我想等b站官方放出网页版的推荐API再加上

**Comment by pbxs666** [comment]
不好意思，我的意思没表达清楚，我想说的是这样：自定义顶栏的搜索历史本来有，自己会记录，这个没错。但是在开启自定义顶栏后搜索历史是一个新的开始，原版的搜索历史没有继承迁移过来。而在搜索界面却能显示所有（不管是原版还是自定义的）搜索框的历史。

※还有，搜索历史可不可以在每一条后加一个叉号，方便单条删除，现在只能全部删除。

原始搜索框
![图片1](https://user-images.githubusercontent.com/47630168/74734109-da511c00-5288-11ea-80d4-994a4ab1b368.png)
自定义搜索框
![图片2](https://user-images.githubusercontent.com/47630168/74734215-0cfb1480-5289-11ea-8464-16b72de71bff.png)
搜索界面搜索框
![图片3](https://user-images.githubusercontent.com/47630168/74734644-ee494d80-5289-11ea-9002-e4db6f2084f4.png)

我要反馈的就是这些，谢谢

**Comment by Coulomb-G** [comment]
搜索历史的删除快捷键和一般搜索栏的删除快捷键是一样的,都是「shift+del」
