### ISSUE TITLE
大家插件加载的速度慢么？

### ISSUE THREAD

**Issue by Cyiming** [the1812/Bilibili-Evolved#3397]
### 对应功能

打开b站 插件得等几分钟才能生效

我开了插件记忆倍速和快速收藏 要几分钟才能显示

而且一旦打开3个以上b站页面容易把浏览器弄蹦了 

### 问题描述

打开b站 插件得等几分钟才能生效

我开了插件记忆倍速和快速收藏 要几分钟才能显示

而且一旦打开3个以上b站页面容易把浏览器弄蹦了 

### 脚本版本

最新

### 浏览器版本

95

### 播放器版本

最新

### 播放策略

默认

### 错误信息

```shell
有什么优化方法么？
```

**Comment by DUXING130** [comment]
去看https://github.com/the1812/Bilibili-Evolved/issues/3331，所有脚本失效问题都是因为这，浏览器崩溃暂不清楚

**Comment by zhangch259** [comment]
确实打开插件之后网页一直在加载，自定义顶栏出来很慢。关闭插件，整个网站秒开

**Comment by cirouma** [comment]
确实很慢，通常要加载十几二十秒，关掉插件以后瞬间就打开了

**Comment by hongyijun-00** [comment]
我也是

**Comment by DUXING130** [comment]
> 我也是

挂提解决，因为Tampermonkey默认脚本与网页同时加载，因脚本无法加载而不会加载主页面，直到脚本管理器认为脚本失效才会加载主页

**Comment by the1812** [comment]
#3331
