### ISSUE TITLE
扩展倍速功能异常

### ISSUE THREAD

**Issue by CCXXXI** [the1812/Bilibili-Evolved#3398]
### 对应功能

Commit: 70a2709ba
内部名称: extendVideoSpeed

### 问题描述

在普通视频页面（播放器版本 2.78.5-04bf8055），不显示 3.0x 等扩展倍速，无法通过设定的快捷键调整倍速。

在番剧页面（播放器版本 3.8.11-e522ba57），可以通过快捷键调整倍速，可以调整至 3.0x 等扩展倍速，但鼠标移至倍速按钮不会弹出 b 站自带的倍速菜单。

问题可能是最后一次脚本更新引入的。我注意到问题后，在另一台尚未更新的电脑上测试正常，更新后复现了问题。

### 脚本版本

v2.2.1

### 浏览器版本

Microsoft Edge 版本 102.0.1245.33 (正式版本) (64 位)

### 播放器版本

2.78.5-04bf8055 & 3.8.11-e522ba57

### 播放策略

默认

### 错误信息

```shell
userscript.html?name=Bilibili%2520Evolved.user.js&id=d9c58af3-5eed-4f47-ac70-0390b2045d5d:219 
        
       Bilibili Evolved Error: video element not found!
    at T (eval at loadFeatureCode (BV1QY4y1V7RY:196:65540), <anonymous>:1:5171)
```

**Comment by sky-279** [comment]
![image](https://user-images.githubusercontent.com/60536042/171983772-0d305694-380d-4c60-bea0-b96046f3f71d.png)
同问

扩展倍速变黑了

播放器版本 2.78.5-04bf8055
v2.2.1
Cent Browser
版本 4.3.9.248（正式版本） （32 位） (Chromium 86.0.4240.198)

**Comment by CCXXXI** [comment]
刚刚 b 站普通视频中途卡住，刷新之后发现扩展倍速正常了。

检查了下各种版本，都没有变化。

**Comment by CCXXXI** [comment]
再次刷新发现无效了 🤔

**Comment by suyi1117** [comment]
和楼主出现的情况一模一样，我刚想提交这个问题来着，哈哈

**Comment by LonelySteve** [comment]
在修复这个问题之前，可以先卸载最新版本的扩展倍速，安装适配 3.x 之前的版本应急：

https://raw.githubusercontent.com/the1812/Bilibili-Evolved/v2.1.10-preview/registry/dist/components/video/player/extend-speed.js

**Comment by imshixin** [comment]
🤔怎么我遇不到这种情况

**Comment by LonelySteve** [comment]
> 🤔怎么我遇不到这种情况

看一下 #3400 ，我不确定这么修会不会影响你那边的情况

**Comment by imshixin** [comment]
> 同问
> 
> 扩展倍速变黑了
> 
> 播放器版本 2.78.5-04bf8055 v2.2.1 Cent Browser 版本 4.3.9.248（正式版本） （32 位） (Chromium 86.0.4240.198)

没有3.0x倍速我大概知道原因了


变黑的原因应该是浏览器版本太低，`2.2.1`使用了较新的css特性，所以浏览器内核至少得88才行,[兼容性参考](https://caniuse.com/?search=%3Ais)
![image](https://user-images.githubusercontent.com/36874714/172012620-988763f0-ca5f-4db6-b164-5e7d852626c1.png)

**Comment by Cyiming** [comment]
新版本问题很多啊 我扩展倍速和快速收藏都不生效

**Comment by yellowgg** [comment]
我也一样, 好几天没开电脑了, 这两天发现扩展倍速功能失效了
<img width="73" alt="image" src="https://user-images.githubusercontent.com/27286340/172411490-d55ff6b3-58b2-4b71-90a3-4f6fc77f603d.png">
不支持扩展

**Comment by LonelySteve** [comment]
> 我也一样, 好几天没开电脑了, 这两天发现扩展倍速功能失效了 <img alt="image" width="73" src="https://user-images.githubusercontent.com/27286340/172411490-d55ff6b3-58b2-4b71-90a3-4f6fc77f603d.png"> 不支持扩展

你这看起来和他们遇到的问题不一样，不过也请试试回到之前的版本能不能恢复

**Comment by imshixin** [comment]
应该是bwp-video模式的问题了，我已经提了新的pr了

**Comment by yellowgg** [comment]
> > 我也一样, 好几天没开电脑了, 这两天发现扩展倍速功能失效了 <img alt="image" width="73" src="https://user-images.githubusercontent.com/27286340/172411490-d55ff6b3-58b2-4b71-90a3-4f6fc77f603d.png"> 不支持扩展
> 
> 你这看起来和他们遇到的问题不一样，不过也请试试回到之前的版本能不能恢复

你好,请问怎么回退版本呢,我看release那里说不要直接下载,用首页推荐的方式安装,但是首页版本就是2.2.1(我就是这个版本失效的)

**Comment by sky-279** [comment]
> 

https://raw.githubusercontent.com/the1812/Bilibili-Evolved/v2.1.10-preview/registry/dist/components/video/player/extend-speed.js

先把原来的组件卸了
然后在管理界面输入这个链接就行

**Comment by yellowgg** [comment]
> > 
> 
> https://raw.githubusercontent.com/the1812/Bilibili-Evolved/v2.1.10-preview/registry/dist/components/video/player/extend-speed.js
> 
> 先把原来的组件卸了 然后在管理界面输入这个链接就行

你好, 用了这个方式还是不行,倍速还是原始倍速,没有其他操作

**Comment by HCl233** [comment]
改用AV1编码播放或许可以解决

**Comment by yellowgg** [comment]
> 改用AV1编码播放或许可以解决

有效!!

**Comment by wangfeng35** [comment]
> 编

有效！！！！

**Comment by BERT202206** [comment]
引用上楼：改用AV1编码播放可以解决！！！

**Comment by yellowgg** [comment]
可是为什么今天发现连设置里的编码都没有了, 于是乎又失效了,我太难了
<img width="314" alt="image" src="https://user-images.githubusercontent.com/27286340/175551930-f298b46b-8c70-4767-b7c5-d340c1a8e20a.png">
