### ISSUE TITLE
关于稍后再看跳转的一点建议

### ISSUE THREAD

**Issue by freejool** [the1812/Bilibili-Evolved#340]
**关于哪一项功能**

稍后再看跳转
**期望的效果**
点击稍后再看列表中的视频时，b站默认会到一个可以自动播放下一个视频的链接，而用了脚本后跳转的界面是视频原始的链接。原来的那个好用啊

**脚本版本**

V1.10.0

**Comment by the1812** [comment]
在`工具`中关闭`稍后再看重定向`就不会跳原始链接了

**Comment by freejool** [comment]
哦哦感谢
