### ISSUE TITLE
升级到2.21插件加载不出来了

### ISSUE THREAD

**Issue by Cyiming** [the1812/Bilibili-Evolved#3406]
### 对应功能

上个版本正常 挂了梯子 不是讨论的被墙问题

### 问题描述

上一个版本正常 提示更新在线更新了下就再也没加载出来过

### 脚本版本

最新

### 浏览器版本

95

### 播放器版本

最新

### 播放策略

默认

### 错误信息

```shell
没有提示
```

**Comment by the1812** [comment]
试试看这些链接能加载吗:
- https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js
- https://cdn.jsdelivr.net/npm/@mdi/font@5.3.45/css/materialdesignicons.min.css
- https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/dist/bilibili-evolved.user.js

**Comment by AlbertWen-AW** [comment]
> 试试看这些链接能加载吗:
> 
> * https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js
> * https://cdn.jsdelivr.net/npm/@mdi/font@5.3.45/css/materialdesignicons.min.css
> * https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/dist/bilibili-evolved.user.js

我的和楼主的一样问题，安装了2.2.1后脚本加载不出来

这些网址里前两个无法加载，最后一个可以

**Comment by eatkid** [comment]
> 

俺也一样

**Comment by Cyiming** [comment]
> 



> > 试试看这些链接能加载吗:
> > 
> > * https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js
> > * https://cdn.jsdelivr.net/npm/@mdi/font@5.3.45/css/materialdesignicons.min.css
> > * https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/dist/bilibili-evolved.user.js
> 
> 我的和楼主的一样问题，安装了2.2.1后脚本加载不出来
> 
> 这些网址里前两个无法加载，最后一个可以

同

**Comment by the1812** [comment]
加载不出来去挂梯子, jsdelivr 需要额外配一下经过梯子

**Comment by the1812** [comment]
差不多吧, 除非浏览器缓存了

**Comment by xiaohuangsu** [comment]
挂梯子刷B站，刷出来就行

**Comment by Cyiming** [comment]
> 挂梯子刷B站，刷出来就行

我全局模式刷出来了 能看到设置 但插件完全不生效 有什么办法解决呢 要是全局模式刷b站有点过了吧 PAC添加什么网址呢

**Comment by eatkid** [comment]
需要额外配置代理规则,网址写jsdelivr.net就行,因为很多软件会视该域名在大陆而绕过代理试图直连,给这个单独配一条规则就行
