### ISSUE TITLE
扩展倍速有的视频刷不出来和快捷收藏问题

### ISSUE THREAD

**Issue by Cyiming** [the1812/Bilibili-Evolved#3408]
### 对应功能

1

### 问题描述

1、扩展倍速问题

av257295625 就显示
av642265901 不显示

2、快捷收藏

所有视频都不显示 

### 脚本版本

2.2.1

### 浏览器版本

95

### 播放器版本

2.78.5

### 播放策略

默认

### 错误信息

```shell
1
```

**Comment by noahhhi** [comment]
我也遇到了，hevc视频下很多功能会失效，暂时解决办法是右下设置切到av1或者avc

**Comment by Holiday2019** [comment]
> 我也遇到了，hevc视频下很多功能会失效，暂时解决办法是右下设置切到av1或者avc

你好，我设置了av1或avc之后，还是没有快速收藏功能。
![图片](https://user-images.githubusercontent.com/54856595/173163998-ee11245b-790a-4756-80b6-0b37b47a58c6.png)
![图片](https://user-images.githubusercontent.com/54856595/173164038-1fa2ae61-7979-463b-84c2-5e29fea2faad.png)

**Comment by Cyiming** [comment]
> > 我也遇到了，hevc视频下很多功能会失效，暂时解决办法是右下设置切到av1或者avc
> 
> 你好，我设置了av1或avc之后，还是没有快速收藏功能。 ![图片](https://user-images.githubusercontent.com/54856595/173163998-ee11245b-790a-4756-80b6-0b37b47a58c6.png) ![图片](https://user-images.githubusercontent.com/54856595/173164038-1fa2ae61-7979-463b-84c2-5e29fea2faad.png)

我也没有 单独提个bug吧

**Comment by Cyiming** [comment]
> > 我也遇到了，hevc视频下很多功能会失效，暂时解决办法是右下设置切到av1或者avc
> 
> 你好，我设置了av1或avc之后，还是没有快速收藏功能。 ![图片](https://user-images.githubusercontent.com/54856595/173163998-ee11245b-790a-4756-80b6-0b37b47a58c6.png) ![图片](https://user-images.githubusercontent.com/54856595/173164038-1fa2ae61-7979-463b-84c2-5e29fea2faad.png)

我屏蔽广告也失效
