### ISSUE TITLE
安装后无法显示设置按钮

### ISSUE THREAD

**Issue by Pretext-li** [the1812/Bilibili-Evolved#3414]
### 对应功能

设置

### 问题描述

安装后无法显示设置按钮，正式版和预览版都存在此问题
电脑系统是Windows 11专业工作站版 21H2

### 脚本版本

2.2.1

### 浏览器版本

chrome v102.0.5005.63

### 播放器版本

2.78.4

### 播放策略

HEVC

### 错误信息

```shell
Failed to load resource: net::ERR_TIMED_OUT
```

### 附加截图

![Snipaste_2022-06-08_10-04-40](https://user-images.githubusercontent.com/62142229/172516053-aa542d2d-e23a-4b26-b944-8981ad3569cf.png)

**Comment by Pretext-li** [comment]
魔法之后也是一样的

**Comment by the1812** [comment]
梯子要加 cdn.jsdelivr.net
默认是直连的
