### ISSUE TITLE
更新·后在左侧没有内两个按钮了重装卸载后重装都没用

### ISSUE THREAD

**Issue by wdy-bit** [the1812/Bilibili-Evolved#3417]
### 对应功能

没有两个按钮

### 问题描述

首页

### 脚本版本

应该是2.2.1

### 浏览器版本

102.0.1245.33 

### 播放器版本

2.78.6

### 播放策略

HEVC

### 错误信息

```shell
不知
```

### 附加截图

s

**Comment by DUXING130** [comment]
善用搜索#3331

**Comment by wdy-bit** [comment]
假期自动回复邮件。你好，我最近正在休习中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
