### ISSUE TITLE
#1003 加强版宽屏播放器样式错位

### ISSUE THREAD

**Issue by HookCode** [the1812/Bilibili-Evolved#3419]
### 对应功能

#1003 加强版宽屏失效了

### 问题描述

#1003 加强版宽屏失效了
https://github.com/the1812/Bilibili-Evolved/issues/1003

### 脚本版本

v2.2.1

### 浏览器版本

.

### 播放器版本

v2.78

### 播放策略

AVC

### 错误信息

```shell
....
```

### 附加截图

![image](https://user-images.githubusercontent.com/90203620/172764264-637526f3-f8f9-4112-9a20-0fb43d7d028c.png)

**Comment by HookCode** [comment]
新旧版播放器都错位

**Comment by SpoonerCake** [comment]
加一

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/173183381-9e6698e4-effa-447b-ae04-37aac641843e.png)

**Comment by SpoonerCake** [comment]
> 

新版旧版都有这个问题捏

**Comment by the1812** [comment]
```js
bilibiliEvolved.pluginApis.installStyle({name: 'widescreenPlus', style: `
.player-mode-widescreen #app {
    position: relative !important;
}
.player-mode-widescreen .v-wrap {
    max-width: unset !important;
} 
.player-mode-widescreen #playerWrap,
.player-mode-widescreen #bilibili-player {
    position: static !important;    
}
.player-mode-widescreen .bilibili-player {
    width: calc(100vw - 12px) !important;
    height: calc(100vh) !important;
    position: absolute !important;
    left: 6px !important;
    top: 0px !important;
}
.player-mode-widescreen #playerWrap {
    height: calc(100vh - 64px - 12px) !important;
}
.player-mode-widescreen #danmukuBox
{
    margin-top: 12px !important; 
    height: auto !important;
    order: 0 !important;
}
.player-mode-widescreen .up-info
{
    margin-top: calc(100vh - 64px + 12px) !important;
}
.player-mode-widescreen .custom-navbar,
.player-mode-widescreen .gui-settings-icon-panel,
.player-mode-widescreen .bilibili-player-video-bottom-area {
    display: none !important;
}
.player-mode-widescreen {
    scrollbar-width: none !important;   
}
.player-mode-widescreen::-webkit-scrollbar {
    height: 0 !important;
    width: 0 !important;
}`, displayName: '加强版宽屏', mode: 'important'})
```

**Comment by HookCode** [comment]
> ```js
> bilibiliEvolved.pluginApis.installStyle({name: 'widescreenPlus', style: `
> .player-mode-widescreen #app {
>     position: relative !important;
> }
> .player-mode-widescreen .v-wrap {
>     max-width: unset !important;
> } 
> .player-mode-widescreen #playerWrap,
> .player-mode-widescreen #bilibili-player {
>     position: static !important;    
> }
> .player-mode-widescreen .bilibili-player {
>     width: calc(100vw - 12px) !important;
>     height: calc(100vh) !important;
>     position: absolute !important;
>     left: 6px !important;
>     top: 0px !important;
> }
> .player-mode-widescreen #playerWrap {
>     height: calc(100vh - 64px - 12px) !important;
> }
> .player-mode-widescreen #danmukuBox
> {
>     margin-top: 12px !important; 
>     height: auto !important;
>     order: 0 !important;
> }
> .player-mode-widescreen .up-info
> {
>     margin-top: calc(100vh - 64px + 12px) !important;
> }
> .player-mode-widescreen .custom-navbar,
> .player-mode-widescreen .gui-settings-icon-panel,
> .player-mode-widescreen .bilibili-player-video-bottom-area {
>     display: none !important;
> }
> .player-mode-widescreen {
>     scrollbar-width: none !important;   
> }
> .player-mode-widescreen::-webkit-scrollbar {
>     height: 0 !important;
>     width: 0 !important;
> }`, displayName: '加强版宽屏', mode: 'important'})
> ```

![image](https://user-images.githubusercontent.com/90203620/173190446-bc0e3ebf-c9f6-479c-a98e-3611240a3ac1.png)
谢谢，新版做下会有这两个按钮，旧版就没有了

**Comment by SpoonerCake** [comment]
> 

这两个看着碍眼的话，可以用广告拦截软件abp，选拦截元素处理掉

**Comment by HookCode** [comment]
> > 
> 
> 这两个看着碍眼的话，可以用广告拦截软件abp，选拦截元素处理掉

现在“回到旧版”了

**Comment by nullnullnullnull0** [comment]
> ```js
> bilibiliEvolved.pluginApis.installStyle({name: 'widescreenPlus', style: `
> .player-mode-widescreen #app {
>     position: relative !important;
> }
> .player-mode-widescreen .v-wrap {
>     max-width: unset !important;
> } 
> .player-mode-widescreen #playerWrap,
> .player-mode-widescreen #bilibili-player {
>     position: static !important;    
> }
> .player-mode-widescreen .bilibili-player {
>     width: calc(100vw - 12px) !important;
>     height: calc(100vh) !important;
>     position: absolute !important;
>     left: 6px !important;
>     top: 0px !important;
> }
> .player-mode-widescreen #playerWrap {
>     height: calc(100vh - 64px - 12px) !important;
> }
> .player-mode-widescreen #danmukuBox
> {
>     margin-top: 12px !important; 
>     height: auto !important;
>     order: 0 !important;
> }
> .player-mode-widescreen .up-info
> {
>     margin-top: calc(100vh - 64px + 12px) !important;
> }
> .player-mode-widescreen .custom-navbar,
> .player-mode-widescreen .gui-settings-icon-panel,
> .player-mode-widescreen .bilibili-player-video-bottom-area {
>     display: none !important;
> }
> .player-mode-widescreen {
>     scrollbar-width: none !important;   
> }
> .player-mode-widescreen::-webkit-scrollbar {
>     height: 0 !important;
>     width: 0 !important;
> }`, displayName: '加强版宽屏', mode: 'important'})
> ```

现在又失效了

**Comment by HookCode** [comment]
> ```js
> bilibiliEvolved.pluginApis.installStyle({name: 'widescreenPlus', style: `
> .player-mode-widescreen #app {
>     position: relative !important;
> }
> .player-mode-widescreen .v-wrap {
>     max-width: unset !important;
> } 
> .player-mode-widescreen #playerWrap,
> .player-mode-widescreen #bilibili-player {
>     position: static !important;    
> }
> .player-mode-widescreen .bilibili-player {
>     width: calc(100vw - 12px) !important;
>     height: calc(100vh) !important;
>     position: absolute !important;
>     left: 6px !important;
>     top: 0px !important;
> }
> .player-mode-widescreen #playerWrap {
>     height: calc(100vh - 64px - 12px) !important;
> }
> .player-mode-widescreen #danmukuBox
> {
>     margin-top: 12px !important; 
>     height: auto !important;
>     order: 0 !important;
> }
> .player-mode-widescreen .up-info
> {
>     margin-top: calc(100vh - 64px + 12px) !important;
> }
> .player-mode-widescreen .custom-navbar,
> .player-mode-widescreen .gui-settings-icon-panel,
> .player-mode-widescreen .bilibili-player-video-bottom-area {
>     display: none !important;
> }
> .player-mode-widescreen {
>     scrollbar-width: none !important;   
> }
> .player-mode-widescreen::-webkit-scrollbar {
>     height: 0 !important;
>     width: 0 !important;
> }`, displayName: '加强版宽屏', mode: 'important'})
> ```

Viva浏览器新旧版播放器加强版宽屏样式失效无任何效果
Cent浏览器正常 

Cent Browser
版本 4.3.9.248（正式版本） （64 位） (Portable) (Chromium 86.0.4240.198)

Vivaldi | 5.3.2679.68 (Stable channel) （64 位）
修订版本 | ecfb656707bbec7aa16f80eb0ea2f4e98e14567b
操作系统 | Windows 11 Version 22H2 (Build 22621.169)
JavaScript | V8 10.2.154.13
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36
