### ISSUE TITLE
暗黑模式下收藏夹还是白色

### ISSUE THREAD

**Issue by Fpywyh** [the1812/Bilibili-Evolved#3422]
### 对应功能

暗黑模式

### 问题描述

开启暗黑模式之后，进入任一视频播放页，点击收藏按钮，发现收藏夹列表还是白色的，非常不方便阅读。

### 脚本版本

v2.2.1

### 浏览器版本

Chrome 102.0.5005.63（正式版本） （64 位）

### 播放器版本

网页版右键看不了版本号

### 播放策略

默认

### 错误信息

```shell
无错误报告
```

### 附加截图

![反馈](https://user-images.githubusercontent.com/84830072/172874290-1f8f0d65-ecd9-48a7-bd99-2c4a0e5fd62c.JPG)

**Comment by Geeyun-JY3** [comment]
看
置
顶
新版页面没适配：#2615

**Comment by Fpywyh** [comment]
好的，谢谢，我没注意看。

**Comment by Fpywyh** [comment]
> 



> 看 置 顶 新版视频页面没适配：#2615

好的，谢谢，我没注意看。
