### ISSUE TITLE
建议加一个类似B 站经验助手的功能

### ISSUE THREAD

**Issue by pongfcnkl** [the1812/Bilibili-Evolved#343]
**关于哪一项功能**

**期望的效果**
这种脚本，https://greasyfork.org/zh-CN/scripts/393096-bilibiliexp
可以自动投币视频、模拟移动端分享等获取经验

**脚本版本**

**Comment by the1812** [comment]
那直接装这个现成的不就行了

**Comment by pongfcnkl** [comment]
> 
> 
> 那直接装这个现成的不就行了

这个有bug

**Comment by Coulomb-G** [comment]
我这边安装后是兼容的,有bug的话应该去联系原作者修复,而不是来这找人重复造轮子
