### ISSUE TITLE
下载不了视频

### ISSUE THREAD

**Issue by wentlwr** [the1812/Bilibili-Evolved#3432]
### 对应功能

视频下载

### 问题描述

av54029771
下载视频点击开始的时候，网页左侧会跳出来  
错误
获取视频链接失败: code = -412, message = 请求被拦截

### 脚本版本

2.2.1

### 浏览器版本

edge浏览器 101.0.1210.53

### 播放器版本

2.79.0

### 播放策略

默认

### 错误信息

```shell
获取视频链接失败: code = -412, message = 请求被拦截
```

### 附加截图

![Snipaste_2022-06-12_20-24-41](https://user-images.githubusercontent.com/81084625/173233063-9fbbdb2b-0caf-4542-a5c6-cbd19b3e6e52.png)

**Comment by the1812** [comment]
下载太多了
