### ISSUE TITLE
首页向下滑动一点点，就会浮动显示分区栏（即便已屏蔽）

### ISSUE THREAD

**Issue by KDreamelf** [the1812/Bilibili-Evolved#3435]
### 对应功能

自定义顶栏：dd5e26569
简化首页（受影响）：simplifyHome

### 问题描述

主站首页，向下滚动一点点，会出现分区栏（无论是否已经屏蔽分区栏）
详见**正常情况下的图1**
这是页面位置没有超过分区栏的情况。看起来很正常
详见**异常情况下的图2**
但是一旦向下滚动一段，页面区域超过了分区栏，分区栏就会同标题一起锁定到页面顶部。
而由于插件的顶栏是半透明的，这会显得分区栏直接悬空在页面中，割裂感极强。

### 脚本版本

Bilibili Evolved v2.2.1-2-gdd5e26569 强大的哔哩哔哩增强脚本

### 浏览器版本

Microsoft Edge 版本 102.0.1245.39 (正式版本) (64 位)

### 播放器版本

与播放器无关

### 播放策略

AVC

### 错误信息

```shell
Bilibili Evolved (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}]0: {__ob__: Ae}1: {__ob__: Ae}2: {__ob__: Ae}3: {__ob__: Ae}4: {__ob__: Ae}5: {__ob__: Ae}6: {__ob__: Ae}length: 7[[Prototype]]: Array(0)
userscript.html?name=Bilibili%2520Evolved.user.js&id=f329bef9-10f2-4ea9-a17d-fbef8f404d8c:219 Bilibili Evolved reply 0 0
userscript.html?name=Bilibili%2520Evolved.user.js&id=f329bef9-10f2-4ea9-a17d-fbef8f404d8c:219 Bilibili Evolved at 0 0
userscript.html?name=Bilibili%2520Evolved.user.js&id=f329bef9-10f2-4ea9-a17d-fbef8f404d8c:219 Bilibili Evolved like 0 4
userscript.html?name=Bilibili%2520Evolved.user.js&id=f329bef9-10f2-4ea9-a17d-fbef8f404d8c:219 Bilibili Evolved sys_msg 0 0
userscript.html?name=Bilibili%2520Evolved.user.js&id=f329bef9-10f2-4ea9-a17d-fbef8f404d8c:219 Bilibili Evolved user_msg 0 62
```

### 附加截图

![正常情况下的图1](https://user-images.githubusercontent.com/49616714/173512321-0a0d861f-96fb-49d4-821c-978d4e469078.png)
↑正常情况下的图1
![异常情况下的图2](https://user-images.githubusercontent.com/49616714/173512591-7c0778dd-3a5b-460d-aee9-ddd8ffa2652e.png)
↑异常情况下的图2

**Comment by DUXING130** [comment]
你自定义顶栏是不是全局锁定了

**Comment by Geeyun-JY3** [comment]
可以复现，应该是新版首页（救命居然还在改），这个分区栏还可以展开，这种双重顶栏的设计还真是让我大开眼界：
![image](https://user-images.githubusercontent.com/49396421/181769895-cd7104c3-5816-47e9-af4b-b8a4ee35a536.png)
![image](https://user-images.githubusercontent.com/49396421/181769747-636889b4-6c26-48ba-bbcd-e46bfb14d120.png)

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved/commit/e285b5e185fa7c5dc33833b0640b0ce2850ce6a9 (#3585) 已经修了这 bug 了吧
