### ISSUE TITLE
动态页面展开某动态时若有几率长期显示某评论用户的头像且无法关闭

### ISSUE THREAD

**Issue by Ai-shuang** [the1812/Bilibili-Evolved#3436]
### 对应功能

无

### 问题描述

在主动态页面，展开任意动态时，若鼠标放置在评论用户头像时使显示头像详细信息小页面，但收起该动态时头像信息却仍存在，需要刷新整个页面才行。

### 脚本版本

v2.2.1

### 浏览器版本

chrome 102.0.5005.63

### 播放器版本

2.79.0

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

![` $8SB{BH_OG%} EMNOSIG8](https://user-images.githubusercontent.com/53259132/173754736-4f690f56-71ab-41fd-a43c-af1759d0211c.png)

**Comment by gaoqiaoqijie** [comment]
这个是b站自己的bug，我没装脚本的时候就有这个问题
