### ISSUE TITLE
网址追踪参数无法清理

### ISSUE THREAD

**Issue by hmgdd101** [the1812/Bilibili-Evolved#3437]
### 对应功能

网址参数清理功能失效

### 问题描述

在所有视频页面都出现，浏览器顶部地址栏中(https://www.bilibili.com/video/av*********)后加上了?vd_source=**********************一大段参数，一看就是追踪用户id的流氓参数，脚本无法清理这些参数，使用cleanurls这个插件也无法清除，在chrome、edge、Firefox中都是一样的

### 脚本版本

v2.2.1

### 浏览器版本

edge、Firefox、chrome最新版

### 播放器版本

2.79.2-rc.5416.0-1c66b65b

### 播放策略

HEVC

### 错误信息

```shell
Bilibili Evolved.user.js:218 Bilibili Evolved Array(7)
Bilibili Evolved.user.js:218 Bilibili Evolved reply 0 0
Bilibili Evolved.user.js:218 Bilibili Evolved at 0 0
Bilibili Evolved.user.js:218 Bilibili Evolved like 0 3
Bilibili Evolved.user.js:218 Bilibili Evolved sys_msg 0 0
Bilibili Evolved.user.js:218 Bilibili Evolved user_msg 0 76
Bilibili Evolved.user.js:218 Bilibili Evolved updated widgets Array(1)
Bilibili Evolved.user.js:218 Bilibili Evolved Array(2)0: {…}1: {…}length: 2__ob__: Ae {value: Array(2), dep: fe, vmCount: 0}[[Prototype]]: Array
Bilibili Evolved.user.js:218 Bilibili Evolved requestedPopup true
```

### 附加截图

![图片](https://user-images.githubusercontent.com/51875934/173853584-3d880b38-0f45-488f-a45e-c84432e7f949.png)

**Comment by imshixin** [comment]
https://github.com/the1812/Bilibili-Evolved/discussions/3424#discussioncomment-2918252
试试这个
