### ISSUE TITLE
在屏幕宽度1401~1614px下，自定义顶栏会造成Overflow

### ISSUE THREAD

**Issue by jiangming1399** [the1812/Bilibili-Evolved#345]
**关于哪一项功能**
自定义顶栏

**问题描述**
启用自定义顶栏后，网页右边出现白色Overflow区域。

**脚本版本**
1.10.5

**浏览器版本**
Firefox 73.0.1

**错误信息**
无

**附加截图**
![截图 2020-02-24 17 21 53](https://user-images.githubusercontent.com/6049028/75140756-85028800-572a-11ea-9b6d-95fcf35ee78f.png)

**Comment by sensty** [comment]
![image](https://user-images.githubusercontent.com/24983339/75151905-c1da7900-5742-11ea-8882-3ba192cc12af.png)
![image](https://user-images.githubusercontent.com/24983339/75151923-cc950e00-5742-11ea-8381-305bd7e83cdf.png)
不只是顶栏

**Comment by the1812** [comment]
请检查下是不是有些弹窗导致的, 比如那个`历史`打开来就很宽, 放在最右边就会移除, 如果是就需要减少顶栏里东西的数量, 可以在`顶栏布局`里隐藏掉
![image](https://user-images.githubusercontent.com/26504152/75315416-af288700-589d-11ea-9cda-b2a111beacc3.png)

我之后也会改一下默认的布局, 貌似历史面板更新后默认就会溢出

**Comment by sensty** [comment]
更改默认布局后也会溢出，这些是在不同大小下的截图
![image](https://user-images.githubusercontent.com/24983339/75318842-59a4a800-58a6-11ea-8b4e-efe97981e049.png)
![image](https://user-images.githubusercontent.com/24983339/75318878-6d500e80-58a6-11ea-839d-00524c260f30.png)
如果把首页布局里边的东西全关了也会有这种情况
![image](https://user-images.githubusercontent.com/24983339/75319187-2282c680-58a7-11ea-9619-dcbc0ab7b92e.png)

**Comment by jiangming1399** [comment]
将顶栏的元素删除掉一些之后，overflow的问题就解决了

**Comment by the1812** [comment]
@sensty 你那里不只是顶栏太长, 下面的内容也会溢出的, 这种接近竖屏的状态几乎所有页面都无法正常使用

**Comment by MaxwellXiao** [comment]
chrome8，也会出现这种情况，顶栏右边超出去一点，历史一栏溢出。缩放100，分辨率2560*1600。
