### ISSUE TITLE
插件对首页标签有用，但是在视频播放界面失效并提示「Invalid or unexpected token」

### ISSUE THREAD

**Issue by akarin-123** [the1812/Bilibili-Evolved#3451]
### 对应功能

这个找不到

### 问题描述

插件对首页标签有用，但是在视频播放界面失效并提示「Invalid or unexpected token」  
猜测会不是会因为啊B今天更新了播放器导致的失效？

### 脚本版本

v1.11.12

### 浏览器版本

版本号:13.1.6000.0I内核版本:86.0.4240.198

### 播放器版本

HTML5播放器 V3.12.5

### 播放策略

默认

### 错误信息

```shell
这个里面找不到
```

### 附加截图

![image](https://user-images.githubusercontent.com/79259342/175290740-9b94824a-bbac-4525-b5a8-ede2562b9a00.png)

**Comment by Geeyun-JY3** [comment]
V1 不维护啦
