### ISSUE TITLE
【bug】复制评论链接失效

### ISSUE THREAD

**Issue by Kal-tsit63** [the1812/Bilibili-Evolved#3453]
### 对应功能

![image](https://user-images.githubusercontent.com/85188780/175397918-81ecf4b6-cd7c-4a57-90c1-bb0d036fed4a.png)
Commit: dd5e26569

### 问题描述

所有视频页面评论都可复刻，评论菜单内无复制链接选项，返回旧版视频页也无法使用

### 脚本版本

2.2.1-2-gdd5e26569

### 浏览器版本

Microsoft Edge 版本 103.0.1264.37 (正式版本) (64 位)

### 播放器版本

3.10.1-b062bf58与2.80.4-049682e5

### 播放策略

AV1

### 错误信息

```shell
请见附加截图
```

### 附加截图

![image](https://user-images.githubusercontent.com/85188780/175401759-9117ba3b-cc33-48ce-8f75-d1a3e456089d.png)
3.10.1-b062bf58
![image](https://user-images.githubusercontent.com/85188780/175401877-35429176-9062-4fec-914d-568514ddcbc6.png)
2.80.4-049682e5

**Comment by Lark-diversity** [comment]
有任何需要我提供的评论就好，我会立刻收到邮箱提醒

**Comment by the1812** [comment]
#3425 提过了, 确实失效了

**Comment by Kal-tsit63** [comment]
> #3425 提过了， 确实失效了

 #3425     提到是在新版，那为何我返回了旧版还是失效呢？

**Comment by Tinhone** [comment]
> > #3425 提过了， 确实失效了
> 
> #3425 提到是在新版，那为何我返回了旧版还是失效呢？

emm...其实是忘了说了...旧版播放页也一样改版了
