### ISSUE TITLE
直播间标题栏未适配夜间模式

### ISSUE THREAD

**Issue by zbodo** [the1812/Bilibili-Evolved#3459]
### 对应功能

夜间模式

### 问题描述

在直播页面打开夜间模式后，标题栏仍为白色

### 脚本版本

v2.2.1-preview

### 浏览器版本

Microsoft Edge 版本 103.0.1264.37 (正式版本) (64 位)

### 播放器版本

Bilibili HTML5 Live Player 3.6.56

### 附加截图

![image](https://user-images.githubusercontent.com/39948021/175955950-410fe5f7-ee33-4ec6-b87f-6961096027f0.png)
![image](https://user-images.githubusercontent.com/39948021/175956054-321b6e58-ec4c-41d0-9fbf-573c671be04a.png)

**Comment by AzusaHana** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/2615#issuecomment-1135411573
