### ISSUE TITLE
Aria2 RPC下载视频时报console.table is not a function

### ISSUE THREAD

**Issue by coffee0818** [the1812/Bilibili-Evolved#3462]
### 对应功能

Aria2 RPC下载视频

### 问题描述

新安装的win11系统，之前的忘记备份Evolved的设置了，所以全新安装的浏览器以及Bilibili-Evolved插件。
网络正常。
当使用Aria2 RPC的方法下载视频时，左下角弹出“console.table is not a function”，但实际去Aria2服务器去查看时，文件清单确实接收到又下载成功了。

### 脚本版本

v2.2.2-7-g095ddcc03

### 浏览器版本

Chrome x64 103.0.5060.66

### 播放器版本

不知道

### 播放策略

默认

### 错误信息

```shell
如截图
```

### 附加截图

![Snipaste_2022-06-28_13-04-54](https://user-images.githubusercontent.com/37019962/176097328-7a69ad8c-143a-431c-aa99-1681345ce415.png)
![Snipaste_2022-06-28_13-05-25](https://user-images.githubusercontent.com/37019962/176097346-570ae659-2aea-452f-b6db-0bfed48f3d45.png)
![Snipaste_2022-06-28_13-08-57](https://user-images.githubusercontent.com/37019962/176097521-225792de-a052-4f99-bd6c-d9b466c683eb.png)

**Comment by DullJZ** [comment]
同样出现这个问题
