### ISSUE TITLE
动态页插件禁止动态跳转与固定动态侧栏问题

### ISSUE THREAD

**Issue by icateav** [the1812/Bilibili-Evolved#3465]
### 对应功能

禁止跳转动态详情 Commit: 095ddcc03
强制固定动态侧栏 Commit: 095ddcc03

### 问题描述

均在页面https://t.bilibili.com/中
开启**禁止跳转动态详情**后，动态中的展开按钮无法展开动态，
使用Dark Reader插件的黑暗模式（没有使用**夜间模式**组件），开启**强制固定动态侧栏**会额外出现一个蓝色的背景，影响正常使用

### 脚本版本

v2.2.2-7-g095ddcc03

### 浏览器版本

Microsoft Edge 版本 101.0.1210.53 (正式版本) (64 位)

### 播放器版本

无关

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

![Snipaste_2022-06-29_14-50-29](https://user-images.githubusercontent.com/103933830/176373337-0c3486eb-d787-4b4a-bf08-e9d8fd1c0f0a.png)
![Snipaste_2022-06-29_15-04-16](https://user-images.githubusercontent.com/103933830/176373358-bd5bc07c-2ec5-4ec8-a9c8-b9c9c15446cf.png)
![Snipaste_2022-06-29_15-04-41](https://user-images.githubusercontent.com/103933830/176373364-9710d6d9-7ddc-4bdc-88b4-7340233b91a7.png)

**Comment by the1812** [comment]
无法展开动态已确认.
第二条应该是 Dark Reader 的算法问题, 强制固定动态侧栏并不会更换背景图
