### ISSUE TITLE
自定义顶栏未隐藏登陆提示

### ISSUE THREAD

**Issue by Workear34** [the1812/Bilibili-Evolved#3469]
### 对应功能

自定义顶栏（Commit: 095ddcc03）

### 问题描述

启用自定义顶栏后，B站的未登陆提示会弹出，导致顶栏被遮挡

### 脚本版本

v2.2.2-7-g095ddcc03

### 浏览器版本

Microsoft Edge 版本 103.0.1264.37 (正式版本) (64 位)

### 播放器版本

HTML5播放器 V2.80.6

### 播放策略

默认

### 错误信息

```shell
none（没有任何错误）
```

### 附加截图

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/99064442/176460542-7419433d-463d-47d7-afaa-b9db0a2116d4.png">

**Comment by the1812** [comment]
那就登录啊
