### ISSUE TITLE
样式更改能否使用user styles？

### ISSUE THREAD

**Issue by WolfLee-red** [the1812/Bilibili-Evolved#347]
**关于哪一项功能**
样式：夜间模式和简化首页等

**期望的效果**
现在是用js改页面样式，由于脚本很大，每次界面都会延迟很长时间，有时候样式根本加载不出来。如果改成user styles用纯css就快多了。

**脚本版本**
正式版 1.10.5

**Comment by the1812** [comment]
夜间模式目前有点bug, 所以会出不来
如果觉得延迟可以试试离线版

**Comment by the1812** [comment]
现在可以试用user styles了
请先在浏览器控制台(<kbd>Ctrl+Shift+I</kbd>)运行这段代码打开user styles支持:
```js
bilibiliEvolved.settings.useDarkStyleAsUserStyle = true
```
然后给stylus安装这个样式: https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@preview/min/dark.user.css
