### ISSUE TITLE
新版2.2.2卡,而且console.table is not a function bug

### ISSUE THREAD

**Issue by michaellongge163** [the1812/Bilibili-Evolved#3477]
![QQ截图20220703040155](https://user-images.githubusercontent.com/66716069/177014780-33609f70-064a-4aaa-97cb-bc993b371fd7.png)
### 对应功能

整体

### 问题描述

版本v2.2.2-7-g095ddcc03

以前点开一个视频只要5秒就加载完了,现在视频上面那一条,主页推荐消息动态那行要30秒
卡的一比

还有aria2 RPC下载报错,console.table is not a function bug

但是有时候还是可以下载,报错也有

### 脚本版本

v2.2.2-7-g095ddcc03

### 浏览器版本

edge Version 103.0.1264.37 (Official build) (64-bit)

### 播放器版本

2.81.1-b3b1d923

### 播放策略

默认

### 错误信息

```shell
console.table is not a function bug
```

### 附加截图

![QQ截图20220703040155](https://user-images.githubusercontent.com/66716069/177014780-33609f70-064a-4aaa-97cb-bc993b371fd7.png)

**Comment by Geeyun-JY3** [comment]
你这是新版播放器界面啊：#2615
