### ISSUE TITLE
扩展倍速功能在传统分p下失效

### ISSUE THREAD

**Issue by fdndnuw** [the1812/Bilibili-Evolved#3478]
### 对应功能

![image](https://user-images.githubusercontent.com/97323048/177029422-a61480d7-d7d5-4aeb-8066-a8da51cf3ca5.png)

### 问题描述

Chrome 103.0.5060.66（正式版本） （64 位）下传统分p视频无法扩展倍速
firefox 102.0 (64 位）则可以

![image](https://user-images.githubusercontent.com/97323048/177029883-2258c605-9df6-48db-939d-1ac60d05fce0.png)

### 脚本版本

Bilibili Evolved v2.2.1

### 浏览器版本

Chrome 103.0.5060.66（正式版本） （64 位）

### 播放器版本

HTML5播放器 V2.81.1

### 播放策略

默认

### 错误信息

```shell
Error: video element not found!
    at T (eval at loadFeatureCode (BV1xv4y1P7pD:196:65540), <anonymous>:1:5147)
```

**Comment by fdndnuw** [comment]
![image](https://user-images.githubusercontent.com/97323048/177030105-1367cd75-03ab-498b-a4a0-2467799230cb.png)
新问题

**Comment by Geeyun-JY3** [comment]
新版播放界面：#2615
