### ISSUE TITLE
关于旧版动态支持问题

### ISSUE THREAD

**Issue by RainEffect** [the1812/Bilibili-Evolved#348]
**关于哪一项功能**
旧版动态支持

**问题描述**
旧版动态已被官方彻底关闭... (草) #79 

**附加截图**
![Image](https://user-images.githubusercontent.com/14258727/75232010-6e733400-57f1-11ea-89af-96c3fff60e40.png)

**Comment by SpoonerCake** [comment]
I have the same question....

**Comment by Coulomb-G** [comment]
那就用新版动态吧,可以搭配「动态过滤器」使用

**Comment by RainEffect** [comment]
旧版动态支持选项可以删除了
以及就是记得把功能关了，不然到时候选项没了还是跳转到旧版动态就搞笑了
