### ISSUE TITLE
从最新预览版导出得设置导入到最新正式版后，脚本无法正常使用

### ISSUE THREAD

**Issue by hugbio** [the1812/Bilibili-Evolved#3480]
### 对应功能

导入设置

### 问题描述

2.3.1-preview 预览版 导出设置后，安装2.2.2正式版后，导入设置。脚本无法正常使用

### 脚本版本

2.2.2

### 浏览器版本

 Edge 103.0.1264.44

### 播放器版本

3.10.1

### 播放策略

默认

### 错误信息

```shell
无
```

**Comment by the1812** [comment]
高版本的设置不能往低版本导的...

**Comment by hugbio** [comment]
谢谢，看来要等下个正式版才能切换了。不过就是预览版没有后悔药有点不方便了。如果导出得配置如果能兼容一定范围得旧版本会更方便点。
