### ISSUE TITLE
视频播放完毕后的“相关推荐”无法通过“传统连播模式”插件禁止连续播放。版本已更新为最新仍然无效。 

### ISSUE THREAD

**Issue by zzssww000** [the1812/Bilibili-Evolved#3481]
### 对应功能

传统连播模式

### 问题描述

视频播放完毕后的“相关推荐”无法通过“传统连播模式”插件禁止连续播放。版本已更新为最新仍然无效。 

### 脚本版本

v2.2.2-7-g095ddcc03

### 浏览器版本

Microsoft Edge 版本 103.0.1264.37 

### 播放器版本

HTML5播放器 V2.81.1

### 播放策略

默认

### 错误信息

```shell
视频播放完毕后的“相关推荐”无法通过“传统连播模式”插件禁止连续播放。版本已更新为最新仍然无效。
```

### 附加截图

视频播放完毕后的“相关推荐”无法通过“传统连播模式”插件禁止连续播放。版本已更新为最新仍然无效。

**Comment by the1812** [comment]
2.4.0 已修复
