### ISSUE TITLE
(0 , r.useScopedConsole) is not a function

### ISSUE THREAD

**Issue by aiguoli** [the1812/Bilibili-Evolved#3482]
### 对应功能

下载视频，批量手动输入av号

### 问题描述

弹窗提示`(0 , r.useScopedConsole) is not a function`

### 脚本版本

v2.0.8-13-g93accf2ac

### 浏览器版本

EDGE 103.0.1264.44 (正式版本) (64 位)

### 播放器版本

2.81.1-b3b1d923

### 播放策略

默认

### 错误信息

```shell
(0 , r.useScopedConsole) is not a function
```

**Comment by the1812** [comment]
你脚本太旧了
