### ISSUE TITLE
下载出现Getway504

### ISSUE THREAD

**Issue by Jasonandy** [the1812/Bilibili-Evolved#3492]
### 对应功能

504 Gateway Time-out

### 问题描述

# 下载出现Bad getway 504 504 Gateway Time-out

### 脚本版本

v2.2.2-7-g095ddcc03

### 浏览器版本

chrome

### 播放器版本

无

### 播放策略

HEVC

### 错误信息

```shell
504 Gateway Time-out
```

### 附加截图

![image](https://user-images.githubusercontent.com/12879147/178151340-e0b9374b-0dfd-4237-a059-8981c55a903e.png)

**Comment by the1812** [comment]
网络不稳定 过段时间再下
