### ISSUE TITLE
安装之后没有左侧插件显示

### ISSUE THREAD

**Issue by Hiikki** [the1812/Bilibili-Evolved#3494]
### 对应功能

无

### 问题描述

从github上安装脚本后，打开B站左侧没有对应插件模块弹出，一些首页信息也被隐藏了，想求助下是啥原因？

### 脚本版本

2.2.2

### 浏览器版本

103.0.1264.49 

### 播放器版本

2.81.9

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/45349715/178325040-bea5f5d6-e974-4d4d-b563-414e5f6a07cb.png)

**Comment by the1812** [comment]
看不出来, 之前有装过吗, 新安装的应该不会改动页面

**Comment by qingtianxiaojie** [comment]
我的也是，上个月开始我插件就用不了了，不管是重装系统还是什么，就是用不了，没有什么插件显示，但是插件却显示开启

**Comment by Hiikki** [comment]
> 看不出来, 之前有装过吗, 新安装的应该不会改动页面

现在是新电脑上第一次装，之前的老电脑倒是没有问题，一开始以为是AdGuard插件影响，后面关了再试也还是不行

**Comment by M1saka10010** [comment]
> 我的也是，上个月开始我插件就用不了了，不管是重装系统还是什么，就是用不了，没有什么插件显示，但是插件却显示开启

f12看看，之前的版本的话盲猜是因为jsdelivr被墙导致的，不过现在放出来了（2.2.2我也不用不了

**Comment by LollipopOuO** [comment]
2.2.1可以用，我暂时停在这个版本

**Comment by Hiikki** [comment]
![Snipaste_2022-07-13_15-10-17](https://user-images.githubusercontent.com/45349715/178673061-3541b939-1072-41c8-91cf-585ec12c6127.png)
![Snipaste_2022-07-13_15-10-44](https://user-images.githubusercontent.com/45349715/178673089-6c84e223-d741-4f66-bb90-009b9f5dc8c8.png)
预览版可以用欸，没有影响

**Comment by M1saka10010** [comment]
> ![Snipaste_2022-07-13_15-10-17](https://user-images.githubusercontent.com/45349715/178673061-3541b939-1072-41c8-91cf-585ec12c6127.png) ![Snipaste_2022-07-13_15-10-44](https://user-images.githubusercontent.com/45349715/178673089-6c84e223-d741-4f66-bb90-009b9f5dc8c8.png) 预览版可以用欸，没有影响

我台式机的预览版也没问题，但是稳定版寄了

**Comment by kid-oh** [comment]
一样 macbook的Safari不知道从哪个版本开始就不显示了
