### ISSUE TITLE
动态被视频播放器遮挡问题

### ISSUE THREAD

**Issue by Eri5Ch** [the1812/Bilibili-Evolved#350]
**关于哪一项功能**

**问题描述**
当脚本设置成，默认播放宽屏，自动关灯打开，此时鼠标滑动到顶部导航栏的动态时，动态列表会被视频播放器遮挡，每个导航栏的导航模块都会这样。

**脚本版本**
1.10.5

**浏览器版本**
Chrome 80.0.3987.122（正式版本） （64 位）

**错误信息**

**附加截图**

![2020-02-26 185937](https://user-images.githubusercontent.com/12391921/75339088-ccc01580-58ca-11ea-9112-569392588f44.jpg)
![2020-02-26 185642](https://user-images.githubusercontent.com/12391921/75339098-d184c980-58ca-11ea-8896-44c5e4b890ee.jpg)
![2020-02-26 185938](https://user-images.githubusercontent.com/12391921/75339682-f3cb1700-58cb-11ea-87be-697f847a8f32.jpg)

**Comment by the1812** [comment]
即便是原版(不使用脚本)也是这样
![image](https://user-images.githubusercontent.com/26504152/75945685-ea4a3c00-5ed5-11ea-81dc-60ebe7ec30e7.png)
如果能这挡住播放器的话, 开网页全屏模式播放器就挡不住顶栏了
所以这个我就不做改动了
