### ISSUE TITLE
关于画中画的功能

### ISSUE THREAD

**Issue by holoscy** [the1812/Bilibili-Evolved#351]
**关于哪一项功能**

直播画中画

**期望的效果**
直播间能支持 和视频一样支持启用画中画
大佬拜托了(●'◡'●)

**脚本版本**
1.10.5

**Comment by Coulomb-G** [comment]
chrome自带画中画功能`javascript:if(document.pictureInPictureElement===document.querySelector("video"))document.exitPictureInPicture(); else document.querySelector("video").requestPictureInPicture();`
打开书签管理器，添加书签，书签的网址填上面这段代码，保存。需要当前网页视频开启或退出画中画的时候，在书签栏点击这个书签就行了。

**Comment by holoscy** [comment]
> chrome自带画中画功能`javascript:if(document.pictureInPictureElement===document.querySelector("video"))document.exitPictureInPicture(); else document.querySelector("video").requestPictureInPicture();`
> 打开书签管理器，添加书签，书签的网址填上面这段代码，保存。需要当前网页视频开启或退出画中画的时候，在书签栏点击这个书签就行了。

谢谢提供方法，B站直播间h5下右键两次开不了画中画，而它的视频却支持

**Comment by fox010** [comment]
很多画中画扩展可以实现，比如[picture-in-picture](https://pictureknow.com/extension?id=ff0c4f68567141568aa51599a81e4b47)
（不过位置在扩展栏，有点远）
