### ISSUE TITLE
第一次设置完毕后组件按钮消失

### ISSUE THREAD

**Issue by tfqy** [the1812/Bilibili-Evolved#3518]
### 对应功能

组件设置

### 问题描述

无法打开组件

### 脚本版本

2.2.2

### 浏览器版本

Google Chrome  103.0.5060.134

### 播放器版本

V2.81.13

### 播放策略

默认

### 错误信息

```shell
已断开 DevServer 连接
```

### 附加截图

![image](https://user-images.githubusercontent.com/78732818/180639090-171c8d5c-8f46-4218-b940-320ccfd9ee10.png)
![image](https://user-images.githubusercontent.com/78732818/180639381-9abefff1-ec56-4b37-929c-4380e96c4990.png)

**Comment by the1812** [comment]
所以你的 "第一次设置" 做了啥? 怎么连 DevClient 都装上了

**Comment by tfqy** [comment]
> 所以你的 "第一次设置" 做了啥? 怎么连 DevClient 都装上了
我就只是在仓库里下载了组件，然后刷新页面就没了

**Comment by the1812** [comment]
是不是一股脑全下载了, 里面有个自动隐藏侧栏的, 装了后鼠标经过左侧中间才会显示按钮

**Comment by tfqy** [comment]
> 

应该是这个问题，那怎么解决呢，我重新下载没有用

**Comment by fnatictreo** [comment]
> 是不是一股脑全下载了, 里面有个自动隐藏侧栏的, 装了后鼠标经过左侧中间才会显示按钮

我启用了隐藏侧栏的功能，但是鼠标过去没反应，怎么办？

**Comment by fnatictreo** [comment]
> > 是不是一股脑全下载了, 里面有个自动隐藏侧栏的, 装了后鼠标经过左侧中间才会显示按钮
> 
> 我启用了隐藏侧栏的功能，但是鼠标过去没反应，怎么办？

找到问题了，原来是和浮图秀冲突

**Comment by Shlimax** [comment]
> > > 是不是一股脑全下载了, 里面有个自动隐藏侧栏的, 装了后鼠标经过左侧中间才会显示按钮
> > 
> > 
> > 我启用了隐藏侧栏的功能，但是鼠标过去没反应，怎么办？
> 
> 找到问题了，原来是和浮图秀冲突

感谢，我也是找不到了，也是浮图秀冲突，省事了
