### ISSUE TITLE
新功能-直播间记录弹幕失效

### ISSUE THREAD

**Issue by dongdongkeer** [the1812/Bilibili-Evolved#352]
经本人测试, 在多个直播间, chrome和firefox环境下均无法记录弹幕, 未开启广告拦截器

**Comment by Coulomb-G** [comment]
控制台有什么报错信息吗

**Comment by 31415926loli** [comment]
> 控制台有什么报错信息吗

无法记录，控制台报错
Access to XMLHttpRequest at 'https://api.live.bilibili.com/mobile/userOnlineHeart' from origin 'https://live.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by 31415926loli** [comment]
> 控制台有什么报错信息吗

Access to XMLHttpRequest at 'https://api.live.bilibili.com/User/userOnlineHeart' from origin 'https://live.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

这是我关了油猴上其他所有脚本，清空控制台，点击开始记录后出现的第一个报错，不知道是不是这个。我这同样也不能记录弹幕，测试过chrome和新edge。

**Comment by the1812** [comment]
这就奇怪了 我录弹幕没用到这个api啊

**Comment by dongdongkeer** [comment]
> > 控制台有什么报错信息吗
> 
> Access to XMLHttpRequest at 'https://api.live.bilibili.com/User/userOnlineHeart' from origin 'https://live.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 
> 这是我关了油猴上其他所有脚本，清空控制台，点击开始记录后出现的第一个报错，不知道是不是这个。我这同样也不能记录弹幕，测试过chrome和新edge。

这个是移动端心跳失效的报错, 什么不允许跨域请求的

**Comment by dongdongkeer** [comment]
> 控制台有什么报错信息吗

大佬, 弹幕记录功能突然好使了, 可能是我的卡巴斯基扩展捣乱

**Comment by 31415926loli** [comment]
> > 控制台有什么报错信息吗
> 
> 大佬, 弹幕记录功能突然好使了, 可能是我的卡巴斯基扩展捣乱

不对啊，我这关了所有扩展和杀软，还是无法记录啊

**Comment by the1812** [comment]
> 不对啊，我这关了所有扩展和杀软，还是无法记录啊

所有直播间都不行?

**Comment by 31415926loli** [comment]
> > 不对啊，我这关了所有扩展和杀软，还是无法记录啊
> 
> 所有直播间都不行?

我关注的都试过了，也随便从直播首页点了几个进去，都不行，一直显示0条记录。然后重新下的chrome，扩展只装了油猴，脚本只下了这个，也不行。杀软只有win自带的那玩意。

**Comment by the1812** [comment]
下个预览离线版试试, 我加了一些日志点, 看看报错信息有没有多什么?

**Comment by 31415926loli** [comment]
> 下个预览离线版试试, 我加了一些日志点, 看看报错信息有没有多什么?

Live Socket: close CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: "", type: "close", …}

Live Socket: unexpected disconnect, retry in 200ms

**Comment by 31415926loli** [comment]
> > 下个预览离线版试试, 我加了一些日志点, 看看报错信息有没有多什么?
> 
> Live Socket: close CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: "", type: "close", …}
> 
> Live Socket: unexpected disconnect, retry in 200ms

突然想到路由器开了防护，给关了，结果还是不行（悲

**Comment by the1812** [comment]
看来是服务器切掉了我的连接, 我得再研究研究

**Comment by qw1124sdo** [comment]
> 看来是服务器切掉了我的连接, 我得再研究研究

可能是锁ip之类的吧,我第一天用得好好的,第二天就用不了.
现在换热点又可以录弹幕了
