### ISSUE TITLE
关于播放器样式的建议

### ISSUE THREAD

**Issue by cwoesj** [the1812/Bilibili-Evolved#353]
你好  能否添加把视频标题和作者信息放到 播放器下方的功能 这样更容易定位播放窗口 调整起来也比较容易

**Comment by the1812** [comment]
是这样吗?
![image](https://user-images.githubusercontent.com/26504152/80085099-5bc77200-858a-11ea-9726-be8afadcb4a1.png)

**Comment by cwoesj** [comment]
看起来是图片这样的。 我的意思就是：把滚动条滚在最顶端的时候可以完整显示宽屏的播放器，就像YouTube的播放器那样，把视频标题和UP信息放下边感觉更简洁，宽屏下也不用费力地调整播放器的位置，直接滑倒最顶端就可以了 。感谢你的回复

发件人: Grant Howard
发送时间: 2020年4月23日 17:48
收件人: the1812/Bilibili-Evolved
抄送: Chen-cwoest; Author
主题: Re: [the1812/Bilibili-Evolved] 关于播放器样式的建议 (#353)

是这样吗?

**Comment by the1812** [comment]
好的 那我就按照这个图来了

**Comment by Littleweisheit** [comment]
我没找到怎么设置，不过这图片和油管也不一样。油管是

- 标题
- 频道名
- 简介
- 
![图片](https://github.com/user-attachments/assets/5434dc34-be81-43a6-b0b0-ad32e8e4e71b)

这样默认宽屏，不需要调整视频位置，确实方便。
