### ISSUE TITLE
希望下载视频的功能里能提供音画整合的格式

### ISSUE THREAD

**Issue by Astexia** [the1812/Bilibili-Evolved#3530]
### 对应功能

下载视频

### 问题描述

希望下载视频的功能里能提供音画整合的格式，现在除了flv外都是音画分离的，希望能增加整合版的格式，最好是mp4。

### 脚本版本

v2.2.2-7-g095ddcc03

### 浏览器版本

chrome 103.0.5060.134

### 播放器版本

不清楚

### 播放策略

默认

### 错误信息

```shell
希望下载视频的功能里能提供音画整合的格式，现在除了flv外都是音画分离的，希望能增加整合版的格式，最好是mp4。
```

**Comment by the1812** [comment]
因为 b 站就是分离的, 你得下载到本地合并
