### ISSUE TITLE
部分组件没有“检查更新”和“开启调试”按钮

### ISSUE THREAD

**Issue by timongh** [the1812/Bilibili-Evolved#3531]
### 对应功能

/

### 问题描述

部分组件没有“检查更新”和“开启调试”。如隐藏顶部横幅：
![image](https://user-images.githubusercontent.com/46739861/181228411-8a33b2ee-83f0-49d7-afac-988a95d5e29d.png)

有类似情况的还有：隐藏番剧点评、隐藏视频标题层等。具体有哪些不清楚。

### 脚本版本

v2.3.1-preview

### 浏览器版本

Microsoft Edge 版本 103.0.1264.62 (正式版本) (64 位)

### 播放器版本

/

### 播放策略

默认

### 错误信息

```shell
/
```

**Comment by the1812** [comment]
用在线仓库装一下覆盖掉试试

**Comment by timongh** [comment]
覆盖后没问题了
