### ISSUE TITLE
删除视频弹窗失效

### ISSUE THREAD

**Issue by Magic-glass** [the1812/Bilibili-Evolved#3545]
### 对应功能

删除视频弹窗

### 问题描述

视频内现在会出现三连的弹窗了
![图片](https://user-images.githubusercontent.com/49303407/181875300-7a2c9f9f-c2f3-4328-8f90-1ab343ae5a2c.png)

此外这个是不是影响了双击全屏功能？之前双击是不会自动全屏的，我搜到discussions有相关的话题，是在这一层上的吗？
https://github.com/the1812/Bilibili-Evolved/discussions/2131

### 脚本版本

v2.2.2-7-g095ddcc03 / 删除视频弹窗Commit: 095ddcc03 

### 浏览器版本

firefox 91.10.0esr

### 播放器版本

3.14.15/旧版页面

### 播放策略

默认

### 错误信息

```shell
并没有报错？
```

### 附加截图

![图片](https://user-images.githubusercontent.com/49303407/181875402-6cb3de10-79fd-4d20-8d1c-6717ca4ca711.png)

**Comment by Geeyun-JY3** [comment]
我猜还是 3.x 播放器没适配的问题：#3187

**Comment by xsdyd** [comment]
同 昨天开始无效的

**Comment by Magic-glass** [comment]
> 我猜还是 3.x 播放器没适配的问题：#3187

_(:зゝ∠)_啊不是吧。。。。。这也太淦了

**Comment by the1812** [comment]
这弹窗看起来是个新版的, 以前的不长这样

**Comment by cjf0523** [comment]
赶紧把这个修复一下，太难受了

**Comment by Admasy** [comment]
推荐一个方法，你们应该都安装了AdBlock，拦截这些弹窗就可以了

**Comment by People-11** [comment]
更新 2.2.4 后，弹窗依然未被去除
<img width="1142" alt="Snipaste_2022-08-27_18-43-17" src="https://user-images.githubusercontent.com/41558215/187026723-b1e4ca88-90ac-460a-97d7-7232b16397d2.png">

**Comment by the1812** [comment]
反馈时记得带上 Commit 以及视频的地址
<img width="500" src="https://user-images.githubusercontent.com/26504152/187053948-e00f306e-64a6-4513-b6ce-c438422ab9e6.png">

**Comment by ZetsuLAM** [comment]
![图片](https://user-images.githubusercontent.com/102503493/187338053-b3930f57-9d92-4a9d-9d52-5a363e0982f7.png)
https://www.bilibili.com/video/av730118661
