### ISSUE TITLE
【默认播放器模式】导致滚轮不能调节音量。

### ISSUE THREAD

**Issue by hcppxgit** [the1812/Bilibili-Evolved#3546]
### 对应功能

默认播放器模式
Commit: 095ddcc03
内部名称: defaultPlayerMode

### 问题描述

这个模式会导致全屏时鼠标滚轮无法调节音量。

复现步骤：开启【默认播放模式】，默认模式选择设为【宽屏】，刷新当前视频或者新开一个任意视频播放页面，将视频全屏，此时滚轮上下滚动调节音量的功能失效。

修复办法：在全屏和非全屏之间反复切换几次，或者alt+tab切换到其他窗口再切回去均可恢复正常，感觉就是先点别的地方使播放器失去顶层窗口焦点再恢复焦点即可。

刷新以后再开全屏又会失效。

### 脚本版本

Bilibili Evolved (Preview) v2.3.1-preview

### 浏览器版本

Chrome 已是最新版本 版本 103.0.5060.134（正式版本） （64 位）

### 播放器版本

测试不管新版旧版播放器都有此问题。

### 播放策略

AV1

### 错误信息

```shell
没有具体错误信息，见附件
```

### 附加截图

![2022-07-30-204755](https://user-images.githubusercontent.com/22807140/181915071-580c99e7-17a1-4f9f-a1d8-7f9de97348ba.png)

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/182055335-5e0e279f-701e-4cc6-9f01-17b6ac06674c.png)
