### ISSUE TITLE
倍速快捷键 shift ↑ 失效

### ISSUE THREAD

**Issue by AKIRAasf** [the1812/Bilibili-Evolved#3548]
### 对应功能

095ddcc03

### 问题描述

倍速快捷键 shift ↑ 失效

### 脚本版本

v2.2.2-7-g095ddcc03

### 浏览器版本

Microsoft Edge 版本 103.0.1264.77 (正式版本) (64 位)

### 播放器版本

V3.14.12

### 播放策略

默认

### 错误信息

```shell
倍速快捷键 shift ↑ 失效
```

**Comment by Geeyun-JY3** [comment]
#3187
