### ISSUE TITLE
能否支持批量下载外挂CC字幕功能（字幕，不是弹幕），目前好像只支持下载当前页面的字幕

### ISSUE THREAD

**Issue by Tonyzhang007** [the1812/Bilibili-Evolved#3549]
### 对应功能

批量下载字幕（不是弹幕）

### 问题描述

![image](https://user-images.githubusercontent.com/43006807/182011190-08e87d40-4939-4ce7-b3ae-b8f7e2c7741a.png)

### 脚本版本

v2.3.1-preview

### 浏览器版本

版本 103.0.5060.134（正式版本） （64 位）

### 播放器版本

2 3版本第一是一样的问题，只支持下载当前页面的字幕，不能批量下载

### 播放策略

默认

### 错误信息

```shell
只支持下载当前页面的字幕，不能批量下载字幕
```

**Comment by the1812** [comment]
装个下载视频, 在批量下载里把字幕下载打开
