### ISSUE TITLE
自定义顶栏和清爽首页冲突

### ISSUE THREAD

**Issue by VergilGao** [the1812/Bilibili-Evolved#3557]
### 对应功能

自定义顶栏会遮挡清爽首页最上面一行

### 问题描述

开启自定义顶栏和清爽首页

### 脚本版本

v2.2.2-7-g095ddcc03

### 浏览器版本

Microsoft Edge 版本 103.0.1264.77 (正式版本) (64 位)

### 播放器版本

2.81.14-7b7d8e11

### 播放策略

默认

### 错误信息

```shell
无报错
```

### 附加截图

![Snipaste_2022-08-02_12-13-02](https://user-images.githubusercontent.com/8655163/182291314-6652c110-46e5-4fd7-8aa1-92e5a3c59bdf.png)

**Comment by ZiYuanZiWan** [comment]
Have the same problem.

**Comment by luotianyiismywife** [comment]
![图片](https://user-images.githubusercontent.com/81459639/182392959-0ea9337e-66ae-4acd-8bad-7d056a589fe5.png)
加一。。。。。类似的问题。
![图片](https://user-images.githubusercontent.com/81459639/182393119-e0422dd0-6a2e-477d-95cc-8147f59f9850.png)
![图片](https://user-images.githubusercontent.com/81459639/182393232-ba19fd77-4dd9-455e-a7eb-53c286169595.png)
![图片](https://user-images.githubusercontent.com/81459639/182393348-9f571a5c-83c5-4fcb-8be0-08136cbc3619.png)

**Comment by Geeyun-JY3** [comment]
@luotianyiismywife 你说的问题是这个吧：#3435

**Comment by VergilGao** [comment]
> ![image](https://user-images.githubusercontent.com/97338781/182417875-1b36c106-acbc-4828-ade7-cbc95e574a0f.png)

就是这个问题，退出内测后问题解决。
