### ISSUE TITLE
倍速扩展失效

### ISSUE THREAD

**Issue by Kulahala** [the1812/Bilibili-Evolved#3566]
### 对应功能

倍速扩展Commit: 095ddcc03

### 问题描述

扩展的倍速消失，倍速扩展按钮消失

### 脚本版本

v2.2.2-7-g095ddcc03

### 浏览器版本

104.0.5112.81（正式版本） （64 位）

### 播放器版本

3.15.4-50c8e7e6

### 播放策略

AV1

### 错误信息

```shell
Bilibili Evolved Error: speed container element not found!
    at N (eval at loadFeatureCode (BV1yt4y1G76d:195:65615), <anonymous>:1:4470)
```

### 附加截图

![Snipaste_2022-08-04_20-39-24](https://user-images.githubusercontent.com/54696830/182849211-31e3f72a-a242-4070-bb5f-ac262feeae88.png)

**Comment by Geeyun-JY3** [comment]
#3187

**Comment by Kulahala** [comment]
preview正常
