### ISSUE TITLE
现在B站稍后再看里的视频已经不会被自动删除了，建议取消“稍后再看期限提醒”功能

### ISSUE THREAD

**Issue by ZCXLLOD** [the1812/Bilibili-Evolved#357]
**关于哪一项功能**
关于工具中的“稍后再看期限提醒”功能。

**期望的效果**
如题，现在B站稍后再看里的视频已经不会被自动删除了，所以建议取消“稍后再看期限提醒”功能。
[https://h.bilibili.com/58955964](url)
![Snipaste_2020-03-02_15-08-35](https://user-images.githubusercontent.com/19368077/75653132-d87b5580-5c97-11ea-9ac2-b0210b79943c.png)
https://h.bilibili.com/58117058
![Snipaste_2020-03-02_15-09-18](https://user-images.githubusercontent.com/19368077/75653163-eaf58f00-5c97-11ea-81fe-1617ff4851bf.png)

**脚本版本**
Bilibili Evolved 1.10.6、Bilibili Evolved (Preview) 1.10.6、Bilibili Evolved (Offline) 589.93和Bilibili Evolved (Preview Offline) 589.93

**Comment by the1812** [comment]
感谢提醒 下次更新将会删除此功能

**Comment by ZCXLLOD** [comment]
> 感谢提醒 下次更新将会删除此功能

嗯，不用谢～
