### ISSUE TITLE
赛事直播自定义顶栏失效 全屏无法隐藏

### ISSUE THREAD

**Issue by wyq977** [the1812/Bilibili-Evolved#3575]
### 对应功能

- 在Safari中，直播赛事无法自定义顶栏。
- 全屏播放顶栏仍然悬浮于直播视频之上。
- 插件在Macaque Manager中安装。

正常主页或视频：
![Screen Shot 2022-08-07 at 5 14 31 PM](https://user-images.githubusercontent.com/27303600/183298403-4b09706b-189a-48a0-9080-7eac3e364832.png)
赛事直播：
![Screen Shot 2022-08-07 at 5 25 55 PM](https://user-images.githubusercontent.com/27303600/183298405-35ee2105-1f0c-4765-82e4-36814ab01908.png)

安装的组件：
![Screen Shot 2022-08-07 at 5 14 56 PM](https://user-images.githubusercontent.com/27303600/183298411-f08afbd1-d60f-4392-a9af-7a36d58a9f85.png)

好像其他的特殊直播间样式如[直播1](https://live.bilibili.com/22625027)，也会无法自定义顶栏，但全屏播放不会出现顶栏。

直播1（自定义顶栏不行，全屏正常）
![Screen Shot 2022-08-07 at 5 29 28 PM](https://user-images.githubusercontent.com/27303600/183298613-38f4b0cb-e692-44f5-9130-d2222390ddae.png)
![Screen Shot 2022-08-07 at 5 30 02 PM](https://user-images.githubusercontent.com/27303600/183298627-a9da8775-64c7-47c0-b893-983a07916c30.png)

直播2（自定义顶栏不行，全屏正常）
![Screen Shot 2022-08-07 at 5 30 26 PM](https://user-images.githubusercontent.com/27303600/183298638-af6e729c-58ca-48ed-9f49-f66a2b2a4730.png)
![Screen Shot 2022-08-07 at 5 30 17 PM](https://user-images.githubusercontent.com/27303600/183298637-5a7fc28f-148a-49be-a2fe-598c3f3e8730.png)

LOL赛事直播（自定义顶栏不行，全屏不正常）
![Screen Shot 2022-08-07 at 5 32 45 PM](https://user-images.githubusercontent.com/27303600/183298722-59161fc7-983a-44d3-80bf-886db1a46fd4.png)
![Screen Shot 2022-08-07 at 5 29 51 PM](https://user-images.githubusercontent.com/27303600/183298616-e3e51e4d-71a1-4233-925c-dd489a0f19ca.png)

### 问题描述

https://live.bilibili.com/6

### 脚本版本

v2.2.2-7-g095ddcc03

### 浏览器版本

Safari Version 15.5 (17613.2.7.1.8)

### 播放器版本

HTML 5 Live Player 3.6.70

### 播放策略

默认

### 错误信息

```shell
[Error] Bilibili Evolved – "feedsCardsManager.startWatching() failed"
	(anonymous function) (Macaque-Bilibili-Evolved:29)
	asyncFunctionResume
	(anonymous function) (Macaque-Bilibili-Evolved:28)
	r (Macaque-Bilibili-Evolved:13:197)
	m (Macaque-Bilibili-Evolved:377:1767)
	(anonymous function) (Macaque-Bilibili-Evolved:354:6829)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Bilibili Evolved – "feedsCardsManager.startWatching() failed"
	(anonymous function) (sentry-5.2.1.min.js:2:42748)
	(anonymous function) (179.c1c7eca7f0eea0abd229.js:2:3029513)
	(anonymous function) (Macaque-Bilibili-Evolved:29)
	asyncFunctionResume
	(anonymous function) (Macaque-Bilibili-Evolved:28)
	r (Macaque-Bilibili-Evolved:13:197)
	m (Macaque-Bilibili-Evolved:377:1767)
	(anonymous function) (Macaque-Bilibili-Evolved:354:6829)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Log] [Macaque] Injecting Script: "Bilibili Evolved" Into "auto" (content.js, line 1)
```

### 附加截图

![Screen Shot 2022-08-07 at 5 23 23 PM](https://user-images.githubusercontent.com/27303600/183298278-17e1b047-1ca6-492c-a8be-8b95e03156ef.png)

**Comment by Geeyun-JY3** [comment]
`自定义顶栏` 这功能只替换主站的顶栏，直播页面没有是正常的，当前页面原本是什么顶栏就是什么顶栏：https://github.com/the1812/Bilibili-Evolved/blob/master/doc/features/features.md#自定义顶栏

至于直播赛事和特殊样式直播间，一直就没怎么适配，也有 [`返回原版直播间`](https://github.com/the1812/Bilibili-Evolved/blob/master/doc/features/features.md#返回原版直播间) 的功能。
全屏了还有个原版顶栏应该是其他功能的 bug，我这边不能复现，和 `自定义顶栏` 应该没什么关系。

**Comment by wyq977** [comment]
@Geeyun-JY3 谢谢快速回复！

不知道为何，「全屏了还有个原版顶栏」又没了，可能是mac/safari特有的bug，不去多想了。

`[返回原版直播间](https://github.com/the1812/Bilibili-Evolved/blob/master/doc/features/features.md#%E8%BF%94%E5%9B%9E%E5%8E%9F%E7%89%88%E7%9B%B4%E6%92%AD%E9%97%B4)` 好像无法把直播赛事和特殊样式直播间返回成原版、正常界面是吗？

**Comment by Geeyun-JY3** [comment]
[`返回原版直播间`](https://github.com/the1812/Bilibili-Evolved/blob/master/doc/features/features.md#返回原版直播间) 就是为把直播赛事和特殊样式直播间返回成原版、正常界面而生的，实测目前还能用。
