### ISSUE TITLE
关于网址参数清理的优化

### ISSUE THREAD

**Issue by NoePoppy** [the1812/Bilibili-Evolved#358]
启用网址参数清理的时候，
在视频推荐里打开新视频，会得到 https://www.bilibili.com/video/av123456/ 格式的链接；
在其他页面（如首页）点击的时候，会得到 https://www.bilibili.com/video/av123456 格式。

两者仅相差一个“/”，于是浏览器无法区分。

希望能够统一格式，这样在浏览器收藏的时候不会重复。

**Comment by Geeyun-JY3** [comment]
今日似乎又出现了一样的情况

**Comment by the1812** [comment]
这个统一`/`的功能已经取消了
因为会导致一些用相对路径的链接指向错误的地址
之前有不少issue 你可以找找看

**Comment by Geeyun-JY3** [comment]
> 这个统一`/`的功能已经取消了
> 因为会导致一些用相对路径的链接指向错误的地址
> 之前有不少issue 你可以找找看

指 [v1.10.20](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.10.20) 中对 #463 等的修复？但我记得最近两三个月的使用体验是清除参数后视频后方都不会有 `/` 的。

还是说是 b 站最近加上了 `/`？如果这个功能最近确实无更改，能否仅针对视频最近的这个情况把这个 `/` 清除掉？

（还想问问这种情况是应该先在这评论还是另开一个 issue（逃

**Comment by the1812** [comment]
有些地方就是不带`/`的, 比如动态页的视频
而视频页里的推荐视频就是带`/`的

而且开着`网址参数清理`和`网址AV号转换`, 也不会影响最后是否有`/`, 都是按照原来的

**Comment by Geeyun-JY3** [comment]
> 有些地方就是不带`/`的, 比如动态页的视频
> 而视频页里的推荐视频就是带`/`的
> 
> 而且开着`网址参数清理`和`网址AV号转换`, 也不会影响最后是否有`/`, 都是按照原来的

那可不可以专门针对推荐视频这种情况将最后的 `/` 清除（强迫症，像本条 issue 说的多了个 `/` 造成的不便）

**Comment by the1812** [comment]
嗯 或许可以仅在视频页里做这种`/`的处理

**Comment by Geeyun-JY3** [comment]
1. 从首页专栏分区打开的文章清除参数后的地址最后也有一个 `/`，从推荐文章中打开的清除参数后就没有 `/`（和视频刚好反过来可还行）
2. 从首页番剧／国创分区打开（非排行榜）的番剧的地址最后也有一个 `/`，即 `https://www.bilibili.com/bangumi/play/ss******/` 或 `https://www.bilibili.com/bangumi/play/ep*****/`
