### ISSUE TITLE
首页分区栏全局固定，不跟自定义顶栏走；删除广告不完全

### ISSUE THREAD

**Issue by Kodeshin** [the1812/Bilibili-Evolved#3585]
### 对应功能

自定义顶栏：095ddcc03
删除广告：095ddcc03 

### 问题描述

- 首页更新后，分区栏默认全局固定。关闭自定义顶栏的全局固定时，分区栏出现在不上不下的位置。
- 首页更新后，广告会混在视频推荐里，没有被删除。（但会被 uBlock Origin 移除，留下空白）

### 脚本版本

 v2.2.2-7-g095ddcc03

### 浏览器版本

Firefox 103.0.1 64bit

### 播放器版本

3.16.0

### 播放策略

默认

### 错误信息

```shell
无输出
```

### 附加截图

![图片](https://user-images.githubusercontent.com/95967481/183771650-aa688a17-3514-4e8a-9127-07884d73b9e2.png)

**Comment by Geeyun-JY3** [comment]
部分重复：#3435

**Comment by the1812** [comment]
新版这广告还真不好屏蔽
