### ISSUE TITLE
Adguard浏览器插件 会和 清爽首页 造成bug冲突造成 闪烁

### ISSUE THREAD

**Issue by th3weird0** [the1812/Bilibili-Evolved#3599]
### 对应功能

清爽首页 Commit: 67d61b5ef 内部名称: freshHome

### 问题描述

PC里使用了adguard过滤广告crx扩展【https://chrome.google.com/webstore/detail/adguard-browser-assistant/fbohpolgemkbfphodcfgnpjcmedcjhpn】
浏览器默认的adguard浏览器插件会启用 
如果同时启用了清爽首页功能会造成首页推荐栏和动态栏无限闪烁 disable掉插件过滤功能即可恢复
贴出这条issue主要是给其他的用户看一下 如果遇到我这种情况可以disable掉过滤 但具体怎么冲突的我也不知 可以协助调试

### 脚本版本

Bilibili Evolved v2.2.3-4-g67d61b5ef

### 浏览器版本

Chrome 版本 104.0.5112.81（正式版本） （64 位）

### 播放器版本

感觉不相关

### 播放策略

默认

### 错误信息

```shell
https://www.bilibili.com/video/BV1tW4y1h7e9/
复现视频在这里
```

### 附加截图

![image](https://user-images.githubusercontent.com/68617067/184701122-95cf39d4-d428-4d37-8bf0-63c6438fa48a.png)

**Comment by ITa-Sun** [comment]
我没遇到这个问题啊，我是adguard会员。开清爽桌面之后正常显示。
![image](https://user-images.githubusercontent.com/68020072/184763281-203683f4-f808-42ed-bded-abf10babbdd6.png)

**Comment by the1812** [comment]
#3128
