### ISSUE TITLE
使用过的各位有没有遇到乱投币问题

### ISSUE THREAD

**Issue by qingshujun** [the1812/Bilibili-Evolved#3603]
### 对应功能

最近帐号莫名其妙给一些没看过的视频投币，还大多是网易游戏宣传，或者什么鬼的[阳谋-心火余温]介绍游戏战队，京东健康什么鬼的。

### 问题描述

因为一个莫名其妙的视频，因为在浏览器打开b站后，有个莫名其妙的视频出现在我的收藏里，查看了下，居然三连了，再查看投币情况，大都是晚上10-凌晨1点（这段时间刚好在游戏，不开网页手机也不开），更夸张的有个是周一下午3点，上班搬砖啊，怎么投币三连？还有查了登录记录，却没有异常，所以就莫名其妙的。

### 脚本版本

v2.3.2

### 浏览器版本

chrome  104.0.5112.79

### 播放器版本

3.17.1-rc.7433.0 revision: 1216b385

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

<img width="407" alt="QQ20220817-023030@2x" src="https://user-images.githubusercontent.com/46417124/184952919-f1914fd9-5dd6-40c9-aba9-df6ae9224f87.png">

**Comment by Geeyun-JY3** [comment]
我用了至少两年多了，可以很明确地说从未遇到过。

**Comment by the1812** [comment]
改个密码吧
