### ISSUE TITLE
组件加载失败

### ISSUE THREAD

**Issue by Passerby1011** [the1812/Bilibili-Evolved#3604]
### 对应功能

组件加载

### 问题描述

总是显示组件加载失败，再重新安装后使用一会后依然会出现组件加载失败，并且网页会巨卡无比，甚至无法加载，而且就是一般使用时，网页加载时间也比以前长了好多，使用的是暴力猴

### 脚本版本

2.2.3

### 浏览器版本

yandex-22.7.4.907 beta

### 播放器版本

大于3

### 播放策略

AV1

### 错误信息

```shell
下图
```

### 附加截图

![image](https://user-images.githubusercontent.com/63802758/185029994-bd609cd8-3037-4bce-9ba6-1744dc6edcf4.png)
![image](https://user-images.githubusercontent.com/63802758/185030264-d219eec3-2e38-40d6-bf5d-29edcccc0745.png)

**Comment by Passerby1011** [comment]
多次重新安装的过程中，使用一段时间后总有1到2个组件加载失败

**Comment by the1812** [comment]
导出一份设置看看？

**Comment by Passerby1011** [comment]
[settings (1).txt](https://github.com/the1812/Bilibili-Evolved/files/9356165/settings.1.txt)
[settings.txt](https://github.com/the1812/Bilibili-Evolved/files/9356168/settings.txt)
因为类型限制所有后缀改成了txt，第一份设置是重新安装后设置的正常使用一段时间后报错，第二份是以前用了很长时间的配置，突然就报错了，配置是报错之后导出的，现在只要导入比报错

**Comment by the1812** [comment]
看了一下, 混入了很多这种异常数据, 你用的脚本管理器是啥?
![image](https://user-images.githubusercontent.com/26504152/185173878-758ca37a-cd69-43b7-8c52-120d9087adbd.png)

**Comment by Passerby1011** [comment]
用的暴力猴Violentmonkey

**Comment by Passerby1011** [comment]
我大致怀疑是我下载器的浏览器插件导致的，但具体是插件的问题还是Bilibili-Evolved问题我不是很清楚

**Comment by the1812** [comment]
我搜了下 filecxx, 是个下载器, 可能跟这个有关

**Comment by Passerby1011** [comment]
https://github.com/filecxx/FileCentipede这是那个下午器的github地址

**Comment by Passerby1011** [comment]
应该是插件更新至2.6版本后出现的这个问题

**Comment by Passerby1011** [comment]
应该是浏览器插件更新到最新版本导致的问题出现

**Comment by filecxx** [comment]
是我的错，filecxx扩展会分析所有js脚本内的潜在视频URL和加密KEY，在自动分析完object和array之后会自动清理临时值，但是似乎没有清理完全，导致了该脚本出现错误，该BUG下个版本会修复， 给你们带来的不便还请见谅。
