### ISSUE TITLE
删除视频弹窗功能失效

### ISSUE THREAD

**Issue by wy3210953202** [the1812/Bilibili-Evolved#3608]
### 对应功能

关闭视频弹窗功能失效，之前以为是没有更新的缘故，该插件启用后还是有弹窗，更新了最新的预览版后问题还是没有解决，关闭弹窗的功能启用后任然有弹窗显示

### 问题描述

删除视频弹窗功能失效，之前以为是没有更新的缘故，删除弹窗的插件启用后播放视频还是有弹窗，之后更新了最新的预览版后问题还是没有解决，删除弹窗的功能启用后仍然有弹窗显示。
比如播放视频BV1fN4y157Fj时，仍然会有弹窗显示

### 脚本版本

v2.3.1-preview

### 浏览器版本

Edge ：104.0.1293.47 (正式版本) (64 位)

### 播放器版本

HTML5播放器 V3.17.0

### 播放策略

默认

### 错误信息

```shell
Bilibili Evolved 网址参数清理 https://www.bilibili.com/video/BV1fN4y157Fj/?vd_source=6ee08280898c887e82a1289968657f04 https://www.bilibili.com/video/BV1fN4y157Fj/
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=c2a267e0-ff97-4108-9097-d1b092cf3197:216 Bilibili Evolved updated widgets Array(4)
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=c2a267e0-ff97-4108-9097-d1b092cf3197:216 
        
       Bilibili Evolved Error: speed container element not found!
    at O (eval at loadFeatureCode ((索引):193:65676), <anonymous>:1:3701)
m @ userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=c2a267e0-ff97-4108-9097-d1b092cf3197:216
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=c2a267e0-ff97-4108-9097-d1b092cf3197:216 Bilibili Evolved Array(2)
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=c2a267e0-ff97-4108-9097-d1b092cf3197:216 Bilibili Evolved [updateTestVideoInfo] Object
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=c2a267e0-ff97-4108-9097-d1b092cf3197:216 Bilibili Evolved [updateTestVideoInfo] Object
```

### 附加截图

![image](https://user-images.githubusercontent.com/88216706/185185017-c35961df-2557-46b5-9cc9-006c288d642e.png)
![image](https://user-images.githubusercontent.com/88216706/185185073-96357154-a9e0-4422-8047-8d7cd5e17a89.png)
![image](https://user-images.githubusercontent.com/88216706/185185087-586469b0-ddbf-4549-a89f-5eb9fa940f6f.png)
![image](https://user-images.githubusercontent.com/88216706/185188854-5b22e35f-3d0a-44c3-a7e0-c0abd0811504.png)

**Comment by the1812** [comment]
#3545
