### ISSUE TITLE
Bug 反馈

### ISSUE THREAD

**Issue by ERUJRF** [the1812/Bilibili-Evolved#3616]
### 对应功能

组件 "1659500174263_filecxx" 加载失败。

### 问题描述

插件 "1659500174263_filecxx" 加载失败
插件 "1659500174263_filecxx" 加载失败
组件 "1659500174263_filecxx" 加载失败。

### 脚本版本

v2.2.3-4-g67d61b5ef

### 浏览器版本

Microsoft Edge 版本 104.0.1293.54 (正式版本) (64 位)

### 播放器版本

640032

### 播放策略

 AV1

### 错误信息

```shell
组件 "1659500174263_filecxx" 加载失败。
插件 "1659500174263_filecxx" 加载失败
```

### 附加截图

![QQ截图20220819093331](https://user-images.githubusercontent.com/111472456/185523483-7fc099ad-fafb-44fb-a4fc-89da564535f2.png)
![QQ截图20220819092259](https://user-images.githubusercontent.com/111472456/185523516-aa693c18-7eca-44ad-bcd5-734c43008379.png)
![3](https://user-images.githubusercontent.com/111472456/185524623-5c30dd16-aa02-4982-83a6-8bd839f366b2.png)

**Comment by Geeyun-JY3** [comment]
请善用搜索：#3604
