### ISSUE TITLE
热门页隐藏顶部横幅无效

### ISSUE THREAD

**Issue by Alexius66** [the1812/Bilibili-Evolved#3618]
### 对应功能

夜间模式

### 问题描述

热门页上有一个占位条夜间模式无效

### 脚本版本

 v2.3.2-preview-7-g63e6ee0f7

### 浏览器版本

EDGE 104.0.1293.54

### 播放器版本

3.17.0

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/73510996/185644996-4937ad35-2d85-4ce3-919d-279ee7a2b99b.png)

**Comment by the1812** [comment]
这是 `隐藏顶部横幅` 有问题
