### ISSUE TITLE
组件“简化首页”的选项变少

### ISSUE THREAD

**Issue by LifeCoLTD** [the1812/Bilibili-Evolved#3619]
### 对应功能

“简化首页”
内部名称: simplifyHome
Commit: (页面没有显示此参数，也没有找到)

### 问题描述

组件“简化首页”的选项变少。之前的“简化首页”可以屏蔽所有页面元素，目前的“简化首页”只能屏蔽很有限的页面元素（见第一张截图）。不论是preview版本（v2.3.2-preview-7-g63e6ee0f7）还是稳定版本（v2.2.3-4-g67d61b5ef）都存在此问题。

### 脚本版本

v2.3.2-preview-7-g63e6ee0f7  &  v2.2.3-4-g67d61b5ef

### 浏览器版本

Google Chrome Version 104.0.5112.101 (Official Build) (arm64)

### 播放器版本

3.17.0-2bfb98a6

### 播放策略

默认

### 错误信息

```shell
详情见下面第二张到第四张的截图。
```

### 附加截图

<img width="616" alt="iShot2022-08-19 12 43 33" src="https://user-images.githubusercontent.com/18227727/185695516-119f88f8-fe4e-43ee-bcae-7b04088f9b92.png">
<img width="575" alt="iShot2022-08-19 12 50 02" src="https://user-images.githubusercontent.com/18227727/185696709-307458c4-6ff8-4bcf-b937-df9aa9bc6636.png">
<img width="575" alt="iShot2022-08-19 12 50 36" src="https://user-images.githubusercontent.com/18227727/185696721-9b889238-5022-4bb4-826d-b0b400d690d3.png">
<img width="582" alt="iShot2022-08-19 12 50 55" src="https://user-images.githubusercontent.com/18227727/185696737-2256f552-5839-4beb-80f2-9f1cf08cd7eb.png">

**Comment by the1812** [comment]
右下退出内测

**Comment by LifeCoLTD** [comment]
> 右下退出内测
<img width="620" alt="iShot2022-08-25 20 18 23" src="https://user-images.githubusercontent.com/18227727/186810732-872c1ea2-ae7b-470a-aa70-df7b41a6536d.png">
你好！右下角的选项中并无退出内测的选项

**Comment by the1812** [comment]
是整个 b 站的右下角，内测是 b 站在搞

**Comment by S6bb** [comment]
我退出内测后选项依然没有变多
