### ISSUE TITLE
自定义顶栏会把推荐的刷新按钮挡住一半

### ISSUE THREAD

**Issue by ccz97663** [the1812/Bilibili-Evolved#3623]
### 对应功能

自定义顶栏 以及 简化首页

### 问题描述

自定义顶栏会把推荐的刷新按钮挡住一半

### 脚本版本

Offline v1246.26

### 浏览器版本

Google Chrome 104.0.5112.82（正式版本） （64 位）

### 播放器版本

无

### 播放策略

默认

### 错误信息

```shell
自定义顶栏会把推荐的刷新按钮挡住一半
```

### 附加截图

![image](https://user-images.githubusercontent.com/70783191/185744827-8908c9f0-89b6-45f0-b6eb-25169aa512e5.png)

**Comment by Geeyun-JY3** [comment]
你这是 `清爽首页`。

请善用搜索：#3565

**Comment by zhiqiangme1** [comment]
油猴里关闭插件，刷新网页会变成原版B站网页，然后在右侧点退出内测，然后打开插件刷新网页就好了
