### ISSUE TITLE
插件【清爽首页】希望可以留一个顶栏开关设置，

### ISSUE THREAD

**Issue by Fatebro** [the1812/Bilibili-Evolved#3624]
### 对应功能

Commit: 67d61b5ef
![chrome_xmNJdlpBnV](https://user-images.githubusercontent.com/70732975/185772799-942d8ff5-d19f-4cd2-973f-f0c517a583bf.jpg)

### 问题描述

希望支持全局自定义顶栏

### 脚本版本

v2.3.2-preview-7-g63e6ee0f7

### 浏览器版本

Chrome version 104.0.5112.101 (Official Build) (64-bit)

### 播放器版本

3.17.0

### 播放策略

HEVC

### 错误信息

```shell
没有
```

**Comment by Geeyun-JY3** [comment]
啥意思，现在自定义顶栏不就是全局的吗？
