### ISSUE TITLE
热门视频获取失败

### ISSUE THREAD

**Issue by Alexius66** [the1812/Bilibili-Evolved#3625]
### 对应功能

清爽首页

### 问题描述

热门视频获取失败

### 脚本版本

v2.3.2-preview-7-g63e6ee0f7

### 浏览器版本

edge 104.0.1293.54 

### 播放器版本

3.17.0

### 播放策略

默认

### 错误信息

```shell
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

### 附加截图

![image](https://user-images.githubusercontent.com/73510996/185790105-0a398c17-0e9d-4fe7-bb53-307f74f03c22.png)

**Comment by liangzilixueha** [comment]
我也是

**Comment by xiajunkai** [comment]
我也是，显示被拦截
![image](https://user-images.githubusercontent.com/34534318/186198885-10ab29a3-2fed-4e16-a66a-f2e4182a69de.png)

**Comment by tfqy** [comment]
![image](https://user-images.githubusercontent.com/78732818/186335014-42e46522-059a-44e3-aefb-0e35e2cfd698.png)
我的也是

**Comment by xiajunkai** [comment]
现在恢复正常了
![image](https://user-images.githubusercontent.com/34534318/187154409-a6f6fc04-a57a-4f85-b147-1b50257d1340.png)
