### ISSUE TITLE
需要手机端下载功能适配

### ISSUE THREAD

**Issue by ifwlzs** [the1812/Bilibili-Evolved#3628]
### 对应功能

下载视频 - aria2 输出支持
downloadVideo.outputs.aria2

### 问题描述

平时电脑不怎么用，经常是手机 通过`下载视频 - aria2 输出支持`功能进行离线下载。但是由于移动端域名不同，导致安装的插件一个也没有。只能手机浏览器切到pc模式进行下载。希望能将下载功能适配到手机端

电脑上下载功能是正常的，b站域名是www.bilibili.com
>
>### 电脑Microsoft Edge查看：
> ![image](https://user-images.githubusercontent.com/49548316/186071236-45f621e8-d0f4-4604-9c4a-097f36549ff3.png)
>
>### 手机firefox nightly，桌面版网页模式查看：
> ![43f6fdb6648f9fdaae1aa2e60b33ede](https://user-images.githubusercontent.com/49548316/186072926-89eda822-6727-4a0b-9914-9bbf6cf43492.jpg)

移动端功能组件库为空，域名为m.bilibili.com
>
>### 电脑Microsoft Edge，手机模式查看：
> ![image](https://user-images.githubusercontent.com/49548316/186072119-2ffc2701-0af5-4454-b828-576669e38e73.png)
>
>### 手机firefox nightly查看：
> ![705d4b0f11643b9260708af4165e0f0](https://user-images.githubusercontent.com/49548316/186073049-05a8c8bb-a8d5-49ef-a42f-e8111284881f.jpg)

### 脚本版本

2.2.3正式版

### 浏览器版本

电脑：Microsoft Edge 104.0.1293.63手机：firefox nightly105.0a1

### 播放器版本

3.17.0-2bfb98a6

### 播放策略

默认

### 错误信息

```shell
Bilibili Evolved updated widgets Array(0)
```

### 附加截图

![image](https://user-images.githubusercontent.com/49548316/186073727-f8b731fe-6b9c-43af-a664-1ef8713f8015.png)

**Comment by Geeyun-JY3** [comment]
#102、#3306
