### ISSUE TITLE
控制栏着色失效，须打开夜间模式

### ISSUE THREAD

**Issue by avrilnoeme** [the1812/Bilibili-Evolved#363]
**关于哪一项功能**
控制栏着色功能

**问题描述**

直接打开着色功能，不会生效，必须在脚本里开启夜间模式才能生效
av93999290

**脚本版本**

1.10.6、1.10.8

**浏览器版本**
Chrome  80.0.3987.132

**错误信息**

<img width="1902" alt="Snipaste_2020-03-06_17-18-26" src="https://user-images.githubusercontent.com/9085763/76069866-86576e80-5fce-11ea-8267-4c6ee772051d.png">

**Comment by the1812** [comment]
失效是指没变化吗? 我试了下貌似没啥问题
![image](https://user-images.githubusercontent.com/26504152/76069953-b737a380-5fce-11ea-8894-31cccad3b8f7.png)
![image](https://user-images.githubusercontent.com/26504152/76069962-bf8fde80-5fce-11ea-89c3-7d8243b47ae2.png)

**Comment by avrilnoeme** [comment]
> 失效是指没变化吗? 我试了下貌似没啥问题
> ![image](https://user-images.githubusercontent.com/26504152/76069953-b737a380-5fce-11ea-8894-31cccad3b8f7.png)
> ![image](https://user-images.githubusercontent.com/26504152/76069962-bf8fde80-5fce-11ea-89c3-7d8243b47ae2.png)

我这边测试更换了主题颜色厚，不打开夜间模式用chrome和firefox都是不行，最顶部的导航栏颜色是会变的。

**Comment by the1812** [comment]
你是指进度条的颜色吗？ 那个是夜间模式特有的，会把很多蓝色粉色的东西改成主题颜色
控制栏着色只是加一层黑色背景，宽屏、网页全屏才看得出来

**Comment by avrilnoeme** [comment]
> 你是指进度条的颜色吗？ 那个是夜间模式特有的，会把很多蓝色粉色的东西改成主题颜色
> 控制栏着色只是加一层黑色背景，宽屏、网页全屏才看得出来

谢谢，确实是 进度条 颜色，可以关了～
