### ISSUE TITLE
请问为什么我不论下载什么格式都一律自动命名成了.m4s?

### ISSUE THREAD

**Issue by shimakotodo** [the1812/Bilibili-Evolved#3637]
### 对应功能

下载视频 Commit: 67d61b5ef
下载音频 Commit: 67d61b5ef

### 问题描述

请问我不管选择下载什么格式，比如dash（avc）或dash（仅音频），在左下角弹出的弹窗会正确命名，比如热门视频.mp4，热门视频.m4a，但是右键保存时，就会自动命名成30280.m4s这种格式。不论原来是mp4还是m4a都变成了m4s，要重新手动命名成热门视频.mp4。
多数时候都是变成m4s，反复点击多次后，原来的mp4和m4a又会自动命名成成30280.mp4这种格式，m4a也变成了.mp4。

我在issues里搜索了没有找到相关解决方案，不得已开了新issue。如果重复提问了望见谅。

### 脚本版本

v2.2.3-4-g67d61b5ef

### 浏览器版本

Microsoft Edge 版本 97.0.1072.76 (官方内部版本) (64 位) 在Chrome里也是同样问题。

### 播放器版本

3.17 但我觉得在这里单独发帖反馈下比较好

### 播放策略

默认

### 错误信息

```shell
我这个问题并非脚本直接报告错误
```

### 附加截图

![屏幕截图(283)](https://user-images.githubusercontent.com/64628237/186836002-7a0b9f1a-7c65-41eb-878e-03192388138b.png)
![屏幕截图(285)](https://user-images.githubusercontent.com/64628237/186836105-7dad4ba9-5117-492a-8442-60af2ece3f2b.png)

**Comment by the1812** [comment]
<img width="500" src="https://user-images.githubusercontent.com/26504152/186915158-e3861828-ac8e-4509-a139-f0d472f8896f.png">
