### ISSUE TITLE
简化首页功能在 Safari 中无法获取动态

### ISSUE THREAD

**Issue by PatZhuang** [the1812/Bilibili-Evolved#364]
**关于哪一项功能**
简化首页功能

**问题描述**

无论是清爽还是极简首页都无法在 Safari 中正确加载动态。

**脚本版本**

离线版 589.93（在同时发布的四个版本上测试过都可以复现）

**浏览器版本**

Safari 13.0.5

**错误信息**

左下角浮窗会报错 “加载组件 feedsApis” 失败。
log 里报的错误主要是

`Failed to apply feature "feedsApis": TypeError: function is not a constructor (evaluating 'super(...arguments)')`

报错的代码段是

```
applyComponent(key, text)
                    {
                        const func = typeof text === 'string' ? eval(text) : text
                        if (func) {
                            try {
                                const attribute = func(settings, this) || {}
                                this.attributes[key] = attribute
                            } catch (error) {
                                console.error(`Failed to apply feature "${key}": ${error}`)
                                const displayName = Resource.all[key].displayName
                                let toastMessage = `加载组件<span>${displayName || key}</span>失败`
                                if (settings.toastInternalError) {
                                    toastMessage += '\n' + error
                                }
                                Toast.error(toastMessage, '错误')
                            }
                        }
                    }
```

**附加截图**

**Comment by the1812** [comment]
似乎是`EventTarget`不兼容 Safari, 这样的话`直播弹幕记录器`同样会无法使用.
预计会在`v1.10.9`中修复.

**Comment by the1812** [comment]
请试试现在的预览离线版, 我做了一些修复

**Comment by PatZhuang** [comment]
> 请试试现在的预览离线版, 我做了一些修复

预览版 1.10.9 预览离线版 604.19 仍有此问题

**Comment by the1812** [comment]
还是报一样的错误吗

**Comment by PatZhuang** [comment]
> 还是报一样的错误吗

是的 控制台中报错的函数调用位置也和离线/正式是一样的

**Comment by the1812** [comment]
请再试试预览版(`v1.10.10`)

**Comment by PatZhuang** [comment]
> 请再试试预览版(`v1.10.10`)

现在可以正常获取动态 但是样式有一点问题

![QQ20200321-234608@2x.png](https://i.loli.net/2020/03/21/ShCdDGpBbrk6xEA.png)

鼠标 hover 到右下角的「直播」、「专题」、「小黑屋」的时候会恢复到正常的样式
但是再 hover 到任意一个动态的 card 上时就回变回上面这样

**Comment by the1812** [comment]
这个可就难办了...得以后找台mac试试才能修
