### ISSUE TITLE
组件'简化评论区' 导致表情框存在问题

### ISSUE THREAD

**Issue by Weidows** [the1812/Bilibili-Evolved#3641]
### 对应功能

简化评论区

### 问题描述

打开简化评论区后, 表情框位置会移到右边, 点开后会被推荐视频覆盖

### 脚本版本

2.2.4

### 浏览器版本

Edge 104.0.1293.70 (正式版本) (64 位)

### 播放器版本

3.18.2

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/61131704/187113140-ce86878d-14d9-454a-9147-c2c70710d6e2.png)

**Comment by the1812** [comment]
#2615
