### ISSUE TITLE
空空如也

### ISSUE THREAD

**Issue by chiaweilee** [the1812/Bilibili-Evolved#3643]
### 对应功能

所有功能

### 问题描述

空空如也

<img width="641" alt="Screenshot 2022-08-30 at 07 48 02" src="https://user-images.githubusercontent.com/29817353/187318300-e353e488-5d14-4f1a-b5ca-f7a8ebfb76c0.png">
<img width="474" alt="Screenshot 2022-08-30 at 07 49 31" src="https://user-images.githubusercontent.com/29817353/187318306-51c9f52c-b25f-4fe4-9196-221c53ce7b43.png">

返回旧版和退出内测后依然如此

### 脚本版本

2.2.4

### 浏览器版本

104.0.5112.101

### 播放器版本

3.17.2-c

### 播放策略

默认

### 错误信息

```shell
没有错误信息
```

**Comment by the1812** [comment]
你在期待什么(
![image](https://user-images.githubusercontent.com/26504152/187324481-fff5d167-cd81-4630-be81-c335f7631999.png)
