### ISSUE TITLE
窗体大部分消失，左侧浮球也不见

### ISSUE THREAD

**Issue by anyezhuguang** [the1812/Bilibili-Evolved#3645]
### 对应功能

如图
![image](https://user-images.githubusercontent.com/88629817/187816090-f096b2b6-9c09-4583-b849-bf06fadee64e.png)

### 问题描述

不知道如何出现的  目前动态和视频均消失大部分窗体

### 脚本版本

 Bilibili Evolved (Preview)2.3.3

### 浏览器版本

edge104.0.1293.70 (正式版本) (64 位)

### 播放器版本

旧版

### 播放策略

HEVC

### 错误信息

```shell
根本搜不到
```

### 附加截图

![image](https://user-images.githubusercontent.com/88629817/187817079-f08f3370-03f4-493d-8052-a7d10240a1a9.png)

**Comment by anyezhuguang** [comment]
播放策略我也忘了 总之  正常使用了几个月  最近突然就这样了

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/188251756-a0d758b0-ef2d-4e93-9368-e8db88ef79f1.png)
去掉 `bilibili evolved` 的筛选看看?

**Comment by EclipseHSP** [comment]
我更新2.4.0以后，我插件不能用了，左侧悬浮球消失，页面也是bilibili原版页面

**Comment by ddqlsep** [comment]
> 我更新2.4.0以后，我插件不能用了，左侧悬浮球消失，页面也是bilibili原版页面

一样没了，以后更新前还是得上来看看，别乱点。

**Comment by EclipseHSP** [comment]
> > 我更新2.4.0以后，我插件不能用了，左侧悬浮球消失，页面也是bilibili原版页面
> 
> 一样没了，以后更新前还是得上来看看，别乱点。

突然好了，提示我申请访问什么，我点了临时允许就正常用了

**Comment by stevencrave** [comment]
2.4更新不能用+1

**Comment by k244493511** [comment]
> > > 我更新2.4.0以后，我插件不能用了，左侧悬浮球消失，页面也是bilibili原版页面
> > 
> > 
> > 一样没了，以后更新前还是得上来看看，别乱点。
> 
> 突然好了，提示我申请访问什么，我点了临时允许就正常用了

啊这，怎么修复的，我也不行

**Comment by EclipseHSP** [comment]
> 

不是我有意修复的，是油猴自己弹出来的

**Comment by anthonyrabbit** [comment]
更新成功了，看最新的readme 需要挂梯子才能更新 那个链接不挂梯子访问不了

**Comment by 8ruecDon** [comment]
> 我更新2.4.0以后，我插件不能用了，左侧悬浮球消失，页面也是bilibili原版页面

插件跨源请求
选择总是允许此域名

**Comment by HopeKlaus** [comment]
@8ruecDon 在哪里设置

**Comment by VceUtaoki1** [comment]
> @8ruecDon 在哪里设置

用steam++加速github，然后进浏览器打开哔哩哔哩，就会弹出来域名访问请求了，你试试...

**Comment by mcthesw** [comment]
> 

回答非常有帮助

**Comment by BERT202206** [comment]
我也遇到问题，更新到2.4.0以后，我插件不能用了，左侧悬浮球消失，页面也是bilibili原版页面，各项功能都无法正常使用了！

**Comment by mcthesw** [comment]
> 我也遇到问题，更新到2.4.0以后，我插件不能用了，左侧悬浮球消失，页面也是bilibili原版页面，各项功能都无法正常使用了！

用Edge浏览器的话，点地址栏左侧的小锁，然后点“此网站的权限”，在新页面中开启“不安全的内容”即可

**Comment by CreamPizzaCrumbs** [comment]
> > @8ruecDon 在哪里设置
> 
> 用steam++加速github，然后进浏览器打开哔哩哔哩，就会弹出来域名访问请求了，你试试...

steam++加速了也弹不出来，有其他方法吗？浏览器用的Chrome。多谢了。

**Comment by the1812** [comment]
网络实在不行的可以看一下 #3655 进行回退

**Comment by CreamPizzaCrumbs** [comment]
> 网络实在不行的可以看一下 #3655 进行回退

刚刚试了一下，回退到2.2.4也不好用。之前点过一个“一个用户脚本试图访问跨源资源”的东西就好了，但是现在那个不自己弹出来了。挂梯子也不好使。不知道咋回事。。

**Comment by the1812** [comment]
[v2.4.1](https://github.com/the1812/Bilibili-Evolved/discussions/3685) 已恢复 jsDelivr 源

**Comment by EclipseHSP** [comment]
> 

你好，更新2.4.1后又出现插件无法正常启动的情况，b站首页界面回到原版界面
