### ISSUE TITLE
夜间模式相关问题

### ISSUE THREAD

**Issue by Alexius66** [the1812/Bilibili-Evolved#3656]
### 对应功能

夜间模式

### 问题描述

某些页面夜间模式不彻底或者失效

### 脚本版本

v2.4.0-preview

### 浏览器版本

EDGE 104.0.1293.70

### 播放器版本

3.18.6

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/73510996/188275744-2ed26ad1-9b7c-4689-bf54-141ee9f3d52c.png)
![image](https://user-images.githubusercontent.com/73510996/188275768-c9b03266-ac09-4c52-b072-1d0fa50aab94.png)

**Comment by anthonyrabbit** [comment]
重新更新 2.4版本需要翻墙更新

**Comment by the1812** [comment]
[v2.4.1](https://github.com/the1812/Bilibili-Evolved/discussions/3685) 已恢复 jsDelivr 源
