### ISSUE TITLE
githubusercontent 拥有与 jsdelivr 相似/更高的阻断与污染

### ISSUE THREAD

**Issue by wosk0x01** [the1812/Bilibili-Evolved#3657]
### 对应功能

更新URL

### 问题描述

新版本采用的githubusercontent在大陆地区污染比jsdelivr更加严重, 推荐以下jsdelivr其他子域名的加速源 (亦或者其他github加速,真的很多)
3 cdn.jsdelivr.net
8 fastly.jsdelivr.net
9 test1.jsdelivr.net
9 testingcf.jsdelivr.net
9 gcore.jsdelivr.net
10 originfastly.jsdelivr.net
via. moxids

### 脚本版本

v2.4.0

### 浏览器版本

ff 104.0.1

### 播放器版本

3.18.6

### 播放策略

默认

### 错误信息

```shell
None
```

### 附加截图

![Screenshot 2022-09-04 115732](https://user-images.githubusercontent.com/77735964/188296660-e046f10f-a26b-42b0-88a5-9026e09c1406.png)
![Screenshot 2022-09-04 115849](https://user-images.githubusercontent.com/77735964/188296681-cffa6630-66cc-4ef5-8ea7-b16ba302a49b.png)

**Comment by Workear34** [comment]
cdn.jsdelivr.net貌似已经恢复了，但因为是国外服务器还是比较慢

**Comment by the1812** [comment]
新版可以选择 fastly.jsdelivr.net 源了
