### ISSUE TITLE
下载视频的功能似乎出现问题

### ISSUE THREAD

**Issue by KJZH001** [the1812/Bilibili-Evolved#3658]
### 对应功能

下载视频

### 问题描述

在我的设备上，不论访问哪个视频页面，执行下载视频的功能时都会出现此问题

插件会正常给出带有下载链接的弹窗，console中没有相关报错（因此看起来不像是下载次数过多导致的）

但是在新标签页打开此链接后会发现无法加载，同时console中能发现服务器返回了403

在 #3187 中大致浏览了一下，发现应该没有和我遇到相同情况的bug，并且看到您说自己也已经得到了3.x的灰度，因此我打算单独发一个出来（另外一方面是回复没有直接提交issue容易排版）

ps.测试时暂停了ADG插件，已经排除了ADG反广告误伤误伤的可能

### 脚本版本

Bilibili Evolved v2.4.0-2-g124fff7f9

### 浏览器版本

 Google Chrome	104.0.5112.102 (正式版本) （64 位） (cohort: Stable) 

### 播放器版本

3.18.6

### 播放策略

默认

### 错误信息
视频页的Console没有报错信息，只有警告

下载页面中返回
```
Failed to load resource: the server responded with a status of 403 ()
44691031_da2-1-30280.m4s:1          Failed to load resource: the server responded with a status of 403 ()
```

### 附加截图

![image](https://user-images.githubusercontent.com/29683578/188297438-efa97201-021d-4c45-877a-23e50ecb6707.png)

**Comment by CloudyEagle** [comment]
upos的cdn大概率都能下载，这个地区cdn以及有些偏向乱码向开头的cdn下载链接貌似不让下载。
建议多点击几次开始按钮，用解析到upos开头的链接下载，若一直没有建议换网络运营商；
我在zjhzjd，用移动网络经常没有upos开头的下载链接，有的概率很少；
用电信网络时upos的开头的下载链接经常有，我同时也在用[脚本](https://greasyfork.org/scripts/415714)优化所给的链接。

**Comment by KJZH001** [comment]
> upos的cdn大概率都能下载，这个地区cdn以及有些偏向乱码向开头的cdn下载链接貌似不让下载。 建议多点击几次开始按钮，用解析到upos开头的链接下载，若一直没有建议换网络运营商； 我在zjhzjd，用移动网络经常没有upos开头的下载链接，有的概率很少； 用电信网络时upos的开头的下载链接经常有，我同时也在用[脚本](https://greasyfork.org/scripts/415714)优化所给的链接。

那么我感觉可以挂个全局的梯子试试能不能解决
不过更换网络运营商我感觉不是很现实，我们这边有些原因，反正换网是肯定没法说换就换的
然后你给出的脚本我也会去尝试一下，感谢你的答复
最后，我这边的网应该算是联通的，基本上刷出来的下载链接都是那种偏乱码的，尝试过很多次

**Comment by KJZH001** [comment]
> 换个别的输出方式, Toast 经常会这样, b 站可能随机给你个不行的 CDN

感谢回复，但是可以麻烦说下怎么修改输出方式吗

我似乎找不到下载视频这个插件的设置
[![QVxC.png](https://img.cdn.loliloli.net/images/2022/09/14/QVxC.png)](https://img.loliloli.moe/image/QVxC)

**Comment by the1812** [comment]
去在线仓库里搜下载视频
![image](https://user-images.githubusercontent.com/26504152/190915982-91df1de0-1693-445c-aa9c-19e098f85387.png)

**Comment by KJZH001** [comment]
> 去在线仓库里搜下载视频 ![image](https://user-images.githubusercontent.com/26504152/190915982-91df1de0-1693-445c-aa9c-19e098f85387.png)

经过测试，已经解决
更换为IDM下载视频后功能正常使用，感谢
