### ISSUE TITLE
直播间里更换勋章和头衔按钮消失

### ISSUE THREAD

**Issue by HYY-zh** [the1812/Bilibili-Evolved#366]
在直播主页里有更换勋章和头衔的按钮，如图
![直播主页](https://user-images.githubusercontent.com/61227595/76163799-3d491b00-6184-11ea-9b8e-7b1f762f5b72.png)
到了具体的直播间里这两个按钮就消失了，如图下所示
![直播间里](https://user-images.githubusercontent.com/61227595/76163811-5eaa0700-6184-11ea-875c-2eb0f200eba4.png)
这应该算bug？还是我的锅？

环境：
操作系统：Windows10专业版2004
浏览器：Google 版本 80.0.3987.116（正式版本） （64 位）
油猴版本：4.9
脚本版本：正式版1.10.6

**Comment by the1812** [comment]
去猫神直播间看了一下没啥问题, 请问你进直播间后网址是什么?
这个功能出现的条件是当前域名为`live.bilibili.com`

**Comment by HYY-zh** [comment]
> 去猫神直播间看了一下没啥问题, 请问你进直播间后网址是什么?
> 这个功能出现的条件是当前域名为`live.bilibili.com`

域名是对的，可是还是没有_(:3」∠)_
![1111](https://user-images.githubusercontent.com/61227595/76164108-12ac9180-6187-11ea-9f08-d7af8f4373d9.png)

**Comment by the1812** [comment]
那在控制台里(`Ctrl+Shift+I`)运行这个试试看会得到什么?
```js
document.domain
```

**Comment by HYY-zh** [comment]
> 那在控制台里(`Ctrl+Shift+I`)运行这个试试看会得到什么?
> 
> ```js
> document.domain
> ```

![`U5K8 Q9T3(IHIS4P3C`~DQ](https://user-images.githubusercontent.com/61227595/76164277-89965a00-6188-11ea-9b1b-5c48646e17c1.png)
是bilibili.com，不是live.bilibili.comΣ(ﾟдﾟ;)

**Comment by the1812** [comment]
是有别的什么插件改了吗? 改成`bilibili.com`确实能减少一些网络请求的限制

**Comment by HYY-zh** [comment]
> 是有别的什么插件改了吗? 改成`bilibili.com`确实能减少一些网络请求的限制

我去看了一下，的确是其他脚本改了_(:3」∠)_

**Comment by the1812** [comment]
好的 下次更新我会更换判断方法

**Comment by HYY-zh** [comment]
> 好的 下次更新我会更换判断方法

没事没事，我把其他脚本给改了，现在按钮能正常显示了，谢谢大佬的解惑😂

**Comment by the1812** [comment]
以防后患嘛 我想尽量多兼容一下其他脚本

**Comment by HYY-zh** [comment]
> 以防后患嘛 我想尽量多兼容一下其他脚本

大佬NB，期待更新呦👀
