### ISSUE TITLE
2.4 夜间模式首页文字是日间模式的颜色，导致完全看不见了。

### ISSUE THREAD

**Issue by ChaoSSSSSSSSSSS** [the1812/Bilibili-Evolved#3661]
### 对应功能

![image](https://user-images.githubusercontent.com/86147546/188318729-6d839772-c5e6-4d1a-a6f0-7ac0be378a7d.png)

### 问题描述

首页，标题因为颜色看不见文字。

### 脚本版本

2.4

### 浏览器版本

edge 104

### 播放器版本

与播放器无关

### 播放策略

默认

### 错误信息

```shell
不需要错误信息
```

### 附加截图

![image](https://user-images.githubusercontent.com/86147546/188318773-4ee3747f-6562-4c73-bcca-ae14da524075.png)

**Comment by moranwenfeng** [comment]
![image](https://user-images.githubusercontent.com/22976522/188574164-992f9738-278c-4a1c-8ec0-39a2a12e12b2.png)
新版有冲突，回到旧版就可以了
