### ISSUE TITLE
黑名单屏蔽人数过多的话会超出屏幕

### ISSUE THREAD

**Issue by RuoYear** [the1812/Bilibili-Evolved#3665]
### 对应功能

Commit: 124fff7f9
内部名称: blackList

### 问题描述

图1：
如题，并且在添加过多时上面的输入框会被顶到屏幕外，以及无法滚动列表，是否可以调整一下宽度和尺寸，或者屏蔽列表另外显示？

图2：
而且只有在首页才能添加黑名单，在个人空间和任意播放页均显示为空并且添加失败且有如图报错。播放器版本：3.18.6。

还有新版内测界面的列表里有一部分已列入黑名单的依旧有部分会被展示出来，播放器版本：3.19.2。

以及是否可以在页面里一键屏蔽指定UP？或者精确匹配可以加一个通过UID屏蔽？
例如在打开个人空间之后可以加一个按钮一键屏蔽。

### 脚本版本

v2.4.0-2-g124fff7f9

### 浏览器版本

Chromium 86.0.4240.198

### 播放器版本

首页

### 播放策略

默认

### 错误信息

```shell
首页：
Bilibili Evolved.user.js:216 Bilibili Evolved null

个人空间、播放页：图二
```

### 附加截图

![image](https://user-images.githubusercontent.com/11421144/188845277-8efaaa6b-97ee-4bd3-88ee-0f57be241438.png)

![image](https://user-images.githubusercontent.com/11421144/188850830-b42c72b6-c94a-46c7-add6-2d4d5d4ccab4.png)

**Comment by the1812** [comment]
@snowraincloud

**Comment by snowraincloud** [comment]
黑名单只支持首页，不包括新版内测，且不会进行版本更新支持了，只修复bug，因为当前的实现是监听dom树改动，效率较低，且不是实时变动，且用户自定义的功能较弱，后期有时间的话准备使用chrome.webRequest的功能进行重写，图一的bug，我这周会进行修复。

**Comment by RuoYear** [comment]
的确在内测界面是等一会才会屏蔽但能起效果，拦截的话我也在研究它是怎么渲染界面，暂时只能再搞个正则匹配去屏蔽掉；

而一键屏蔽的按钮有在油猴看到一个“b站首页黑名单”的功能挺不错，把按钮加在“稍后再看”的下面，通过UID屏蔽，但它只能屏蔽推荐的豆腐块（也让我看到B站的推荐机制真的是无语，8个豆腐块4个被屏蔽还一直推荐）

> 图一的bug，我这周会进行修复。 图二的，黑名单只支持首页，不包括新版内测，后面有时间的话准备使用直接修改请求的返回值的方式进行实现黑名单功能，所有不会进行版本更新支持了，只修复bug，因为当前的实现是监听dom树改动，效率较低，且不是实时变动，且用户自定义的功能较弱，一键添加屏蔽，短期内应该不会添加此功能。
