### ISSUE TITLE
近期出现加载缓慢的情况,以及the1812.github.io访问问题

### ISSUE THREAD

**Issue by Mixlining** [the1812/Bilibili-Evolved#3668]
### 对应功能

脚本加载

### 问题描述

脚本每次加载都会访问the1812.github.io,但是若不开启代理,访问十分缓慢(广东深圳移动),导致整个脚本加载很慢(表现为:网页一直在转圈圈,网页左边脚本的工具栏没有加载)
测试方法:
1.  将domain:the1812.github.io加入路由direct目录,加载缓慢
2.  将domain:the1812.github.io加入路由block目录,加载迅速
3.  将domain:the1812.github.io加入路由proxy目录,加载迅速

能否提供开关,关闭每次对the1812.github.io的连接

### 脚本版本

v2.4.0-2-g124fff7f9

### 浏览器版本

Edge 105.0.1343.27

### 播放器版本

3.19.4

### 播放策略

默认

### 错误信息

```shell
无
```

**Comment by the1812** [comment]
这个是访问图标库的域名, 加载缓慢的问题以后会提供更多 CDN 方案来解决的

**Comment by Mixlining** [comment]
但是block域名后是可以正常使用的,也就是说并不是必须连接,是否可以添加关闭连接功能,或者当延迟大于某个值时就停止连接

**Comment by DUXING130** [comment]
> 但是block域名后是可以正常使用的,也就是说并不是必须连接,是否可以添加关闭连接功能,或者当延迟大于某个值时就停止连接

你block还能加载是因为本地有了缓存，如果没有缓存你block就会形成方框

**Comment by ccjjxx99** [comment]
> > 但是block域名后是可以正常使用的,也就是说并不是必须连接,是否可以添加关闭连接功能,或者当延迟大于某个值时就停止连接
> 
> 你block还能加载是因为本地有了缓存，如果没有缓存你block就会形成方框

那可不可以先判断一下有没有缓存，如果没有缓存再去连接服务器呢，毕竟有时候不开梯子的时候，这个插件让整个哔哩哔哩都无法进入一直转圈，也太难受了

**Comment by the1812** [comment]
[v2.4.1](https://github.com/the1812/Bilibili-Evolved/discussions/3685) 已恢复 jsDelivr 源
