### ISSUE TITLE
「功能建议」希望可以批量下载CC字幕且转码SRT格式

### ISSUE THREAD

**Issue by gongyoyo** [the1812/Bilibili-Evolved#367]
**关于哪一项功能**
CC字幕下载

**期望的效果**
批量下载且能转码为srt格式

**脚本版本**
v1.10.5

**Comment by Coulomb-G** [comment]
ass你用不了吗?另外,批量下载是想怎样批量下载?

**Comment by the1812** [comment]
批量应该就是跟弹幕一样的待遇吧 出现在下载视频面板里
srt看了下功能貌似太简陋了, 覆盖不了b站字幕的各种变化

**Comment by gongyoyo** [comment]
> ass你用不了吗?另外,批量下载是想怎样批量下载?

是CC字幕，下载下来是json，批量下载就是本视频所有P全部打包一起下载，几百个慢慢下太慢

**Comment by the1812** [comment]
按shift点按钮是ass格式

**Comment by gongyoyo** [comment]
> 按shift点按钮是ass格式

感谢解答，不过真的希望出个批量下载字幕，类似于批量下载弹幕，所有分P一次性下载，要不然有些教程系列的，100多P，手动效率太低

**Comment by the1812** [comment]
会的会的

**Comment by endlesstravel** [comment]
@the1812 建议能给个下载字幕的格式选择框，不然都不知道按下shift可以下载ass格式字幕

**Comment by AllGetHub** [comment]
所以按住shift的，这样可以单独下载ass格式字幕，我差点就要求你单独上一个更新字幕的功能，
下载视频+弹幕的这个选项，下载的弹幕是当前显示的还是全部的弹幕，如果我在播放设置里屏蔽了滚动弹幕，是不是下载的时候就没有滚动弹幕？还是说不管我设置显示哪些弹幕，下载的是全部弹幕？

**Comment by the1812** [comment]
@AllGetHub 仅`ASS`格式会跟随你的屏蔽设置, `XML`不会
