### ISSUE TITLE
夜间模式视频播放列表显示异常

### ISSUE THREAD

**Issue by mavnp** [the1812/Bilibili-Evolved#3671]
### 对应功能

夜间模式

### 问题描述

视频链接为https://www.bilibili.com/video/BV1YW4y187mt
其播放列表显示为白色

### 脚本版本

v2.4.0-2-g124fff7f9

### 浏览器版本

Microsoft Edge 版本 105.0.1343.33 (正式版本) (64 位)

### 播放器版本

3.19.5-376a8dOf

### 播放策略

默认

### 错误信息

```shell
userscript.html?name…5b-00b6361b8bb7:217 Bilibili Evolved 网址参数清理 https://www.bilibili.com/video/BV1YW4y187mt?vd_source=55cbe82… https://www.bilibili.com/video/BV1YW4y187mt
userscript.html?name…5b-00b6361b8bb7:217 Bilibili Evolved updated widgets 
Array(6)
userscript.html?name…5b-00b6361b8bb7:217 Bilibili Evolved 
Array(2)
userscript.html?name…5b-00b6361b8bb7:217 Bilibili Evolved 
Array(2)
userscript.html?name…5b-00b6361b8bb7:217 Bilibili Evolved 
Array(2)
```

### 附加截图

![QQ截图20220912111409](https://user-images.githubusercontent.com/92003405/189568271-877ac87f-2978-4fae-81f5-7e27fdc44dad.png)
![QQ截图20220912111955](https://user-images.githubusercontent.com/92003405/189568295-8ee0e31e-c957-4de6-8d0b-cb16edcb8d15.png)

**Comment by Geeyun-JY3** [comment]
回旧版播放页：#2615
