### ISSUE TITLE
脚本自动更新至 2.4.0 后完全无法运行，侧边栏消失

### ISSUE THREAD

**Issue by guysxpf** [the1812/Bilibili-Evolved#3678]
### 对应功能

无

### 问题描述

脚本自动更新至 2.4.0 后完全无法运行，侧边栏消失。更新前使用正常

而且尝试了：
1，关闭其他所有脚本——无效
2、删除脚本重新安装——无效
3、尝试挂梯子加载代码——无效

浏览器 Edge 105.0.1343.27
油猴 4.16.1

### 脚本版本

2.4.0

### 浏览器版本

Edge 105.0.1343.27

### 播放器版本

3.19.4

### 播放策略

HEVC

### 错误信息

```shell
无
```

### 附加截图

无

**Comment by nj1067426682** [comment]
我也是，2.3版本就这样了，现在一直用2.2.3

**Comment by guysxpf** [comment]
> 我也是，2.3版本就这样了，现在一直用2.2.3
我想知道油猴里的脚本怎么禁用更新

**Comment by MirionQs** [comment]
可能是无法连接到cdn（

**Comment by the1812** [comment]
[v2.4.1](https://github.com/the1812/Bilibili-Evolved/discussions/3685) 已恢复 jsDelivr 源
