### ISSUE TITLE
更换头像后自定义顶栏加载头像错误

### ISSUE THREAD

**Issue by j1g5awi** [the1812/Bilibili-Evolved#3679]
### 对应功能

自定义顶栏 124fff7f9

### 问题描述

更换头像后刷新主页，F12 可见顶栏头像的链接开头为 httpss://，怀疑是错误地进行了两次替换。

### 脚本版本

v2.4.0-preview

### 浏览器版本

Chromium 版本 105.0.5195.102（正式版本）

### 播放器版本

3.19.10

### 播放策略

默认

### 错误信息

```shell
未发现错误信息
```

### 附加截图

![image](https://user-images.githubusercontent.com/50312681/190419686-e2c1f8ff-2db0-4c38-9e48-a73255cf97d1.png)

**Comment by the1812** [comment]
以前 b 站的图全部都是 http 的, 所以有个替换成 https 的操作, 不过现在看来新头像的图终于有 https 了

**Comment by pooneyy** [comment]
匹配了“http”替换，如果匹配的是“http://”应该就不会有这种问题了

**Comment by Rodney-aj** [comment]
我也有这个问题，有什么办法修复吗，还是等更新

**Comment by Demon-Lucifer** [comment]
我把浏览器都干一遍了，原来是src有问题

**Comment by GTVpigs** [comment]
我安装的正式版也有这个BUG，而预览版正常，是不是只修了预览版？
![image](https://user-images.githubusercontent.com/86565518/190894329-81f6e300-eefd-4ab2-9837-29d8ec16e433.png)

**Comment by the1812** [comment]
我修了, 还没发版, 这个头像时好时坏
到时候两个版本会一块发的
