### ISSUE TITLE
bilibili的用户牌子class发生改变

### ISSUE THREAD

**Issue by Smoke-N-Mirrors** [the1812/Bilibili-Evolved#368]
bilibili的用户牌子class发生改变, 由[class='dynamic-level']变为了[class='stick true-love'], 相应的简化评论区插入的css代码也应该发生改变 
还有请问github怎么为问题添加标签啊, 我想添加"bug"标签可是没找到选项

**Comment by the1812** [comment]
标签就在右边的Labels里 这个应该算`adaptation`(原本正常的功能需要适应b站的变化)
