### ISSUE TITLE
复制动态链接时报错 Uncaught ReferenceError: GM_setClipboard is not defined

### ISSUE THREAD

**Issue by woshiluo** [the1812/Bilibili-Evolved#3687]
### 对应功能

copyFeedsLink  

### 问题描述

在 https://t.bilibili.com/ 中复制链接会报错 `Uncaught ReferenceError: GM_setClipboard is not defined`。

### 脚本版本

v2.4.1-preview 

### 浏览器版本

Firefox 104.0.2 (64-bit)

### 播放器版本

3.19.11

### 播放策略

默认

### 错误信息

```shell
Uncaught ReferenceError: GM_setClipboard is not defined
```

### 附加截图

![image](https://user-images.githubusercontent.com/29979060/190937062-aca70b2f-4900-4f12-8a23-bd3e619b3760.png)

**Comment by woshiluo** [comment]
如果有需要的话，使用的是 Violentmonkey。

我注意到在文件中并没有`// @grant GM_setClipboard`，加上后就可以正常使用。

请问是 Bug 还是我操作不当？

**Comment by the1812** [comment]
应该是组件未更新, 新版本的 copyFeedsLink 换用浏览器原生的 `navigator.clipboard` 了, 所以脚本不需要 `@grant GM_setClipboard`

**Comment by woshiluo** [comment]
谢谢，卸载该组件后重新安装就好了。

（很奇怪，点了许多次更新组件但是似乎都没有起效）
