### ISSUE TITLE
Bilibili Evolved (Preview)	2.4.0 下载字幕缺少 Fontsize

### ISSUE THREAD

**Issue by wenruozhu** [the1812/Bilibili-Evolved#3688]
### 对应功能

<img width="185" alt="image" src="https://user-images.githubusercontent.com/25280349/190953026-7c59e22e-85af-47e6-95d3-8bda142073bf.png">

### 问题描述

查看以前的issue [#1377](https://github.com/the1812/Bilibili-Evolved/issues/1377) 1，1.11.9已解决，新版本又缺少 Fontsize

### 脚本版本

Bilibili Evolved (Preview)	2.4.0

### 浏览器版本

105.0.5195.125

### 播放器版本

3.19.11

### 播放策略

默认

### 错误信息

```shell
下载字幕缺少 Fontsize
```

### 附加截图

<img width="957" alt="image" src="https://user-images.githubusercontent.com/25280349/190952942-dc6a7383-6898-4757-a930-8ef4d794da5d.png">

**Comment by wenruozhu** [comment]
> 看了下是有的, 把 `下载字幕` 这个组件更新或者重新装下把
> 
> https://github.com/the1812/Bilibili-Evolved/blob/59c04ba07816fc5ab6aa55f6c54bd53c07136c35/registry/lib/components/video/danmaku/converter/ass-danmaku.ts#L74-L76

那个不是弹幕的吗？字幕的确实没有Fontsize，麻烦您确认下。

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/25280349/191390893-da74c44e-10be-41de-bf01-9637d736f9a9.png">

**Comment by the1812** [comment]
是我搞错了, 字幕的确实没有

**Comment by wenruozhu** [comment]
> 是我搞错了, 字幕的确实没有
好的，感谢提供的插件
