### ISSUE TITLE
自定义顶栏头像无法显示

### ISSUE THREAD

**Issue by auqhjjqdo** [the1812/Bilibili-Evolved#3689]
### 对应功能

自定义顶栏

### 问题描述

自定义顶栏的头像无法显示，控制台网络发现请求地址变成了httpss

### 脚本版本

2.4.1

### 浏览器版本

Chromium 102.0.5005.167

### 播放器版本

3.19.11

### 播放策略

默认

### 错误信息

```shell
net::ERR_UNKNOWN_URL_SCHEME
```

### 附加截图

![image](https://user-images.githubusercontent.com/56216884/190958969-2160b4ba-937d-42fe-aeda-c20454eab00a.png)
![image](https://user-images.githubusercontent.com/56216884/190959619-e955b957-7d79-4d46-9951-60d7227cdd68.png)

**Comment by Slicn** [comment]
我也是这个问题

**Comment by the1812** [comment]
更新一下 `自定义顶栏`, 已经修复了的
