### ISSUE TITLE
地区限定视频无法下载

### ISSUE THREAD

**Issue by wasabi-git** [the1812/Bilibili-Evolved#369]
虽然这个问题已经有人提过，但是我还发现一个衍生出来的问题。
正常网络环境下，地区限定的视频无法下载；如果使用海外IP观看平常可以看的番，对于这个IP，这些视频就成了地区限定，尽管使用“解除B站区域限制”这个脚本，进去以后也同样没有下载选项，问题就在这，已知这些视频本是可以下载的，但是用解除限制的脚本进入视频后，就不能下载了。
是不是说B站的视频只要对于这个账户来说是区域限定的，就无法下载？
还是说能反推出这些区域限定的视频还是能够有方法下载的？

**Comment by the1812** [comment]
这仅仅跟IP位置有关
国内IP只能下载国内番 海外IP只能下载海外番
国内不能下海外 海外也不能下国内

**Comment by Coulomb-G** [comment]
关于解除B站区域限制,并不是把你的IP改成海外,而是把非内地的BiliPlus的服务器上的资源给你,和b站关系不大
想下载区域限制的视频,直接找个相应的节点IP就可以下载

**Comment by wasabi-git** [comment]
知道了,感谢。
