### ISSUE TITLE
Aira2下载不支持https协议

### ISSUE THREAD

**Issue by Felix2yu** [the1812/Bilibili-Evolved#3691]
### 对应功能

Aria2 RPC下载视频

### 问题描述

当前aria2下载强制使用http协议，即使端口号填写443，也是请求`http://aria2:443/jsonrpc`，希望能加入一个选项以支持https协议的aria2 RPC

### 脚本版本

2.4.1

### 浏览器版本

Safari 16.1

### 播放器版本

3.9.12

### 播放策略

HEVC

### 错误信息

```shell
（索引）	param	success	message
0		false	"无法连接到RPC主机, error = TypeError: undefined is not an object (evaluating 'n.error')"
1		false	"无法连接到RPC主机, error = TypeError: undefined is not an object (evaluating 'n.error')"
```

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/191146027-31f454c6-e3d2-4e0f-b7e3-7a2d1e7a555a.png)

**Comment by Felix2yu** [comment]
确实可以，谢谢。
但默认值为`127.0.0.1`如果为`http://127.0.0.1`至少能让人意识到协议是能改的。
