### ISSUE TITLE
夜间模式和新等级标冲突

### ISSUE THREAD

**Issue by xx146542xx** [the1812/Bilibili-Evolved#3696]
### 对应功能

夜间模式

### 问题描述

突然改了等级标 加了个白色背景

### 脚本版本

2.4.0

### 浏览器版本

chrome105.0.5195.127（正式版本） （64 位）

### 播放器版本

HTML5播放器 V3.19.10

### 播放策略

默认

### 错误信息

```shell
-
```

### 附加截图

![image](https://user-images.githubusercontent.com/109429390/191200104-ba1a92a4-3ad8-4dd6-93bd-59971af54976.png)

**Comment by the1812** [comment]
你夜间模式没更新
