### ISSUE TITLE
“播放前显示封面”会导致视频暂停时 显示内容为封面，而不是视频暂停当前帧的画面

### ISSUE THREAD

**Issue by D-Jancy** [the1812/Bilibili-Evolved#3698]
### 对应功能

播放前显示封面

### 问题描述

如题

### 脚本版本

v2.4.1-10-gcd68678fc

### 浏览器版本

105.0.5195.127

### 播放器版本

V3.19.10

### 播放策略

AVC

### 错误信息

```shell
无
```

**Comment by gayhub-com** [comment]
同样的问题。。。。

**Comment by yangyangbuxiangyang** [comment]
一样的，但是只有一次，后面再暂停就不会了

**Comment by absentmemory** [comment]
+1

**Comment by GalaxySnail** [comment]
+1，其实很早就有这个问题但是只有偶尔才会触发，通常重新暂停一次就不会显示封面了，但是最近几天（大概两三天吧）总是稳定触发，每次暂停都会显示封面。不清楚是不是播放器升级做了哪些改动导致的。

脚本版本：`v2.4.1-preview`
浏览器版本：`chromium 105.0.5195.54 (1027018)` 以及 `chromium 106.0.5249.62 (1036826)`
播放器版本：`3.20.8-442d59f2`

**Comment by xcfj** [comment]
+1，稳定触发显示封面
脚本版本：v2.4.1-2-g1def12660
浏览器版本：chromium 86.0.4240.198（360极速）
播放器版本：3.20.8-442d59f2

**Comment by cjf0523** [comment]
顶一顶，很多时候都需要暂停看，太难受了，又不想舍弃封面

**Comment by definfo** [comment]
相同问题且稳定复现

脚本版本：`v2.4.1-preview`
浏览器版本：`Centbrowser 版本 5.0.1002.182（正式版本）（64 位） (Portable) (Chromium 102.0.5005.167)`
播放器版本：`3.20.8-442d59f2Chromium 102.0.5005.167`
