### ISSUE TITLE
9月24日下午脚本突然就不运行了

### ISSUE THREAD

**Issue by HumanMusicX** [the1812/Bilibili-Evolved#3704]
### 对应功能

脚本不运行

### 问题描述

B站所有页面都不运行

### 脚本版本

2.4.1

### 浏览器版本

Microsoft Edge 版本 105.0.1343.50 (正式版本) (64 位)

### 播放器版本

更新历史 3.20.4-a3f78d0f

### 播放策略

默认

### 错误信息

```shell
空
```

### 附加截图

![Snipaste_2022-09-24_17-49-08](https://user-images.githubusercontent.com/46023154/192091669-e560e8f9-d7d9-467e-8f52-9ab2af9334aa.png)

**Comment by lery666** [comment]
还是2.2.4最稳定

**Comment by HumanMusicX** [comment]
已经修复
