### ISSUE TITLE
希望能自由调节ASS弹幕透明度

### ISSUE THREAD

**Issue by fcevat** [the1812/Bilibili-Evolved#373]
我看到弹幕处理在1205行    onlineData["https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/min/download-danmaku.min.js"]   ...   {i={font:"微软雅黑",alpha:.6,duration:t=> ...
不确定这里的alpha:.6是不是指生成的ass字幕透明度是60%，我试着改成其他数值但是和视频一起下载的ass字幕透明度并没有发生变化。
能否给个提示如何调整ass透明度，能整合进脚本就更棒啦~
Thank you very much!

**Comment by the1812** [comment]
没出bug的话应该是等同于播放器里弹幕设置的透明度  60%只是默认值

**Comment by the1812** [comment]
刚才特地去看了下 虽然是取播放器的透明度 但数值上还有些偏差 得修一下

**Comment by 25041haha** [comment]
好的 十分感谢
