### ISSUE TITLE
开启“样式 - 使用自定义顶栏”后，头衔显示不正常

### ISSUE THREAD

**Issue by kKevin0001** [the1812/Bilibili-Evolved#3733]
### 对应功能

开启“样式 - 使用自定义顶栏”功能后，即可复现该问题

### 问题描述

开启“样式 - 使用自定义顶栏”功能后，即可复现该问题

### 脚本版本

Stable v1.12.22

### 浏览器版本

106.0.5249.103（正式版本） （64 位）

### 播放器版本

V3.20.10

### 播放策略

默认

### 错误信息

```shell
.
```

### 附加截图

![image](https://user-images.githubusercontent.com/37786366/195559105-0eadd114-b280-42cc-92b1-28c1c9306b53.png)

**Comment by the1812** [comment]
脚本版本太低了

**Comment by kKevin0001** [comment]
现在正常了，之前似乎更新源失效了
