### ISSUE TITLE
自定义顶栏头像加载失败

### ISSUE THREAD

**Issue by Fatebro** [the1812/Bilibili-Evolved#3734]
### 对应功能

![1](https://user-images.githubusercontent.com/70732975/195604141-a4079e0b-3565-49b4-8aca-98e577dd31ff.jpg)

### 问题描述

在任何界面都会出现这个问题

### 脚本版本

v2.4.1-2-g1def12660

### 浏览器版本

Chrome---Version 106.0.5249.119 (Official Build) (64-bit)

### 播放器版本

3.20.10-bdf5535c

### 播放策略

默认

### 错误信息

```shell
net::ERR_UNKNOWN_URL_SCHEME
```

### 附加截图

![image](https://user-images.githubusercontent.com/70732975/195605555-f73726a9-e865-4e4b-9a96-ef6dc3c402d2.png)

**Comment by the1812** [comment]
你的 `自定义顶栏` 是 21 年的版本...
<img width="400" src="https://user-images.githubusercontent.com/26504152/195611827-82f5e77f-2450-461e-971c-ec1eaa2859a7.png">
