### ISSUE TITLE
有关夜间模式

### ISSUE THREAD

**Issue by MasqueradeXY** [the1812/Bilibili-Evolved#374]
夜间模式下，小电视和联系客服按钮极度耀眼。
小电视可以通过开启删除广告功能解决，不知道联系客服按钮有救吗？似乎没有找到相关的屏蔽功能
如果是我没找到还请告知，十分感谢！
<img width="610" alt="微信截图_20200314122809" src="https://user-images.githubusercontent.com/62165728/76674934-7ef81c80-65ef-11ea-935c-3e1627bda386.png">

**Comment by the1812** [comment]
那个联系客服已经计划要修复了 你可以先开简化首页隐藏掉
