### ISSUE TITLE
使用此插件批量下载视频，导致IP被封

### ISSUE THREAD

**Issue by geekyouth** [the1812/Bilibili-Evolved#3746]
### 对应功能

整个 https://www.bilibili.com/ 无法访问

### 问题描述

整个 https://www.bilibili.com/ 无法访问

### 脚本版本

v2.4.1-2-g1def12660

### 浏览器版本

Cent Browser 版本 4.3.9.248（正式版本） （32 位） (Chromium 86.0.4240.198)

### 播放器版本

更新历史 3.20.10-bdf5535c

### 播放策略

默认

### 错误信息

```shell
代理直连打不开 https://www.bilibili.com/

代理全局使用美国 IP 可以打开b站

导致此故障的原因是，我之前使用本插件批量下载视频，然后整个B站都无法访问了，后来我意识到是IP被封了，于是我打开在家庭wifi 下的手机，打开bilibili APP，也是无法访问，然后我手机切换到数据流量就可以访问了。

同理，我电脑默认是ssr 科学上网走的 pac 代理模式，无法访问B站，然后我切换到全局，代理规则是绕过局域网，代理IP 选择美国，马上就可以访问B站了。

我用的电信500MB光纤，拥有公网IP。我尝试重启主路由重新拨号更换公IP，依然打不开B站。

请问我现在要怎么解封我的公网IP、IP 段？？？
```

### 附加截图

![image](https://user-images.githubusercontent.com/12899262/196340656-edcd95f2-7617-4ed3-9106-c1b785240187.png)

![image](https://user-images.githubusercontent.com/12899262/196340720-c9b31ef3-951f-4b60-9403-15155825109d.png)

**Comment by the1812** [comment]
只能等解封了, 你这是下了多少
