### ISSUE TITLE
下载FLV格式的视频时无法选择1080P以上的清晰度

### ISSUE THREAD

**Issue by starryxia** [the1812/Bilibili-Evolved#3748]
### 对应功能

下载视频

### 问题描述

选择FLV格式时只显示1080P和360P两个清晰度，当切换其他格式时可以正常选择所有清晰度
如：https://www.bilibili.com/video/BV1et4y1F7k7/

### 脚本版本

v2.4.1-10-gcd68678fc

### 浏览器版本

Microsoft Edge 106.0.1370.47 

### 播放器版本

V3.20.10

### 播放策略

默认

### 错误信息

```shell
昨天刷新几下页面还能正常显示所有清晰度，今天怎么刷新切换都只有1080P和360P了
```

### 附加截图

![微信截图_20221019205310](https://user-images.githubusercontent.com/116174090/196696317-59cff7cc-47b1-4eca-9574-93fc4a9599b9.png)
![微信截图_20221019205404](https://user-images.githubusercontent.com/116174090/196696428-9ec36f13-4854-4d87-88dd-dd2e09bacb71.png)

**Comment by non-one** [comment]
同样遭遇，而且下载FLV格式视频时，点击下载连接后会新建一个标签页，并没有开始下载操作
![QQ截图20221020145905](https://user-images.githubusercontent.com/32992657/196878346-0a1a0a21-425b-4df8-8596-fb6be66a22cb.png)

**Comment by df4d** [comment]
> 

在左下角那里右键另存为就好了，问题不大

**Comment by the1812** [comment]
正常, flv 一直都比 dash 清晰度少
