### ISSUE TITLE
我的课程图标找不到！

### ISSUE THREAD

**Issue by KANA108** [the1812/Bilibili-Evolved#375]
![Snipaste_2020-03-14_13-39-25](https://user-images.githubusercontent.com/55820158/76675901-507f3f00-65f9-11ea-987a-9f6026e971f7.png)
![Snipaste_2020-03-14_13-40-55](https://user-images.githubusercontent.com/55820158/76675917-77d60c00-65f9-11ea-86c3-21556863f9b2.png)

**Comment by the1812** [comment]
课程后来出的 还没加上...

**Comment by KANA108** [comment]
> 课程后来出的 还没加上...

等你加上，不是大问题，但是就是每次进课堂要关掉插件很麻烦

**Comment by KANA108** [comment]
OK
