### ISSUE TITLE
更新到2.5评论区不显示点赞、踩的图标

### ISSUE THREAD

**Issue by junyuwsda** [the1812/Bilibili-Evolved#3751]
### 对应功能

简化评论区

### 问题描述

更新到2.5评论区不显示点赞、踩的图标

### 脚本版本

v2.5.0-25-gdab6500b7

### 浏览器版本

edge106.0.1370.47

### 播放器版本

3.20.11-fb629aa9

### 播放策略

AVC

### 错误信息

```shell
按操作来，一片空白
```

### 附加截图

![image](https://user-images.githubusercontent.com/96709393/196888368-ca467bb2-ebf4-4a90-9fc4-a8154af08b02.png)

**Comment by 1405308186** [comment]
+1

**Comment by SnowMeteors** [comment]
更新到2.5，插件全没了，是啥情况
