### ISSUE TITLE
jsDelivr 源图标、在线仓库搜索、展开选集列表、展开选集标题、自定义顶栏“频道”按钮问题

### ISSUE THREAD

**Issue by MonicaWQY** [the1812/Bilibili-Evolved#3752]
### 对应功能

在线仓库、展开选集列表、展开选集标题、自定义顶栏

### 问题描述

1.看到你之前在#3331中回复jsDelivr 源可以不用梯子了，但是我这边用jsDelivr 源的还是会出现设置界面图标不显示的问题，目前已换回GitHub 源，但还是希望能不用梯子就正常使用；

2.在在线仓库界面搜索会出现灰条然后卡死，开梯子有能搜索的几率；

3.今天看到新增了“展开选集列表”功能，更新了2.5.0版本，我在在线仓库里没有看到有需要安装的“展开选集列表”功能，搜索的一下发现显示是已安装状态，但是在设置界面搜索却没有这个功能，随便点开一个有多个视频合集的页面也没生效，我在在线仓库界面重新安装这个功能之后确实生效了，但是“展开选集标题”功能失效了，重新安装“展开选集标题”功能的话，展开选集列表”功能又会失效；
多P视频链接：https://www.bilibili.com/video/BV19G411J7Yb
合集视频链接：https://www.bilibili.com/video/BV1qG4y1r71k

4.自定义顶栏“频道”按钮点击之后没有反应，这个问题在2.4.0版本就存在。

### 脚本版本

2.5.0

### 浏览器版本

Microsoft Edge 106.0.1370.47 (正式版本) (64 位)

### 播放器版本

/

### 播放策略

默认

### 错误信息

```shell
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved plugins block time: 2.1ms for 30 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved plugins resolve time: 15.4ms for 30 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved 网址参数清理 https://www.bilibili.com/video/BV1qG4y1r71k/?vd_source=1219be0ba6f4ee34ae321a13a9af3d71 https://www.bilibili.com/video/BV1qG4y1r71k/
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved Array(6) 814789962 false
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved videoChange 814789962 814789962
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved components block time: 4.3ms for 36 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved components resolve time: 1738ms for 36 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved Array(6) 814789962 false
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved init block time: 0.5ms for 6 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved init resolve time: 2831.6ms for 6 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved (6) [79212575, 201275480, 498220633, 56024433, 74964956, 80149248, __ob__: Ae] 814789962 false
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved updated widgets [__ob__: Ae]
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 
        
       Bilibili Evolved TypeError: Cannot read properties of undefined (reading 'key')
    at fi (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:188:34728)
    at userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:189:14218
    at C (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:189:14380)
    at userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:189:13905
    at C (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:189:14380)
    at o.__patch__ (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:189:15515)
    at e._update (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:188:27164)
    at o.i (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:189:22751)
    at wn.get (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:188:19517)
    at wn.run (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:188:20401)
    at vn (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:188:18509)
    at Array.<anonymous> (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:188:5108)
    at et (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:188:4507)
```

### 附加截图

1.
![1](https://user-images.githubusercontent.com/93992899/196912316-cfdbbd3d-bbc5-4047-bb9b-27531e311894.jpg)
2.
![2](https://user-images.githubusercontent.com/93992899/196912377-8b887990-fd80-449c-899d-a2ea9069b504.jpg)
3-1.
![3](https://user-images.githubusercontent.com/93992899/196912441-2c9c192c-b90f-4198-a516-c6904d5bc9c1.jpg)
3-2.
![4](https://user-images.githubusercontent.com/93992899/196912474-257e5ead-8c6a-4f04-9806-9339bc64e574.jpg)

**Comment by the1812** [comment]
频道我试了下正常的啊

**Comment by MonicaWQY** [comment]
> 频道我试了下正常的啊

我点频道的时候会出现以下错误信息：

userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved plugins block time: 3.4ms for 30 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved plugins resolve time: 30.5ms for 30 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved components block time: 5.1ms for 18 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved components resolve time: 1110.7ms for 18 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved init block time: 1.1ms for 6 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved init resolve time: 4709.3ms for 6 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved plugins block time: 3.2ms for 30 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved plugins resolve time: 22.4ms for 30 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved components block time: 1.7ms for 17 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved components resolve time: 60.3ms for 17 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved init block time: 1ms for 6 items
userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 Bilibili Evolved init resolve time: 676.4ms for 6 items
2userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:217 
        
       Bilibili Evolved TypeError: Cannot read properties of null (reading 'getAttribute')
    at bt.clickAction (eval at loadFeatureCode (www.bilibili.com/:194:66109), <anonymous>:1:2578)
    at click (eval at loadFeatureCode (www.bilibili.com/:194:66109), <anonymous>:28:8296)
    at We (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:188:4022)
    at HTMLDivElement.n (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:188:5813)
    at a._wrapper (userscript.html?name=Bilibili%2520Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:189:3001)
    at HTMLDivElement.sentryWrapped (sentry-5.15.0.min.js:2:53430)

**Comment by the1812** [comment]
好的, 那我知道是啥原因了

**Comment by MonicaWQY** [comment]
好的，期待修复，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 下午3:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] jsDelivr 源图标、在线仓库搜索、展开选集列表、展开选集标题、自定义顶栏“频道”按钮问题 (Issue #3752)





 
好的, 那我知道是啥原因了

**Comment by MonicaWQY** [comment]
我刚刚安装了2.5.1版本，卸载了“展开选集标题”功能，安装“选集区域优化”组件后，设置界面还是只有一个“展开选集标题”功能，没有“展开选集列表”功能，只有把脚本恢复到出厂状态，才能正确安装“选集区域优化”组件。

**Comment by MonicaWQY** [comment]
> 好的, 那我知道是啥原因了

我刚刚安装了2.5.1版本，卸载了“展开选集标题”功能，安装“选集区域优化”组件后，设置界面还是只有一个“展开选集标题”功能，没有“展开选集列表”功能，只有把脚本恢复到出厂状态，才能正确安装“选集区域优化”组件。
