### ISSUE TITLE
更新2.5后插件失效

### ISSUE THREAD

**Issue by samlee111** [the1812/Bilibili-Evolved#3760]
### 对应功能

无

### 问题描述

昨天升级后无法使用功能，侧边菜单消失，旧版/新版/内测版ui均不出现。退回2.4可以正常显示使用。

### 脚本版本

2.5

### 浏览器版本

Firefox 106.0.1 (64 位)

### 播放器版本

3.20.11

### 播放策略

AVC

### 错误信息

```shell
无
```

### 附加截图

![1](https://user-images.githubusercontent.com/32815796/197194644-76129674-06a6-4fdf-84bb-b3f367f48538.png)
![2](https://user-images.githubusercontent.com/32815796/197194657-9ece4f5a-78c0-4491-a7fe-81c70cc40ac4.png)
![3](https://user-images.githubusercontent.com/32815796/197194659-e68715f7-3a23-4bb1-9567-f8611b4cb08f.png)

2.4正常显示
![4](https://user-images.githubusercontent.com/32815796/197197947-c6172425-176d-448f-9a7b-b108cdaf3092.png)

**Comment by catomoufzt** [comment]
开魔法或者其他能加速安装源后重新安装

**Comment by KINNAKAIHOU** [comment]
同样的问题，挂梯子重新安装后还是有这个问题

**Comment by samlee111** [comment]
> 开魔法或者其他能加速安装源后重新安装

OK有了
![QQ截图20221022121217](https://user-images.githubusercontent.com/32815796/197318561-8fb50416-e065-466a-81d8-65a8e9e7720b.png)

**Comment by samlee111** [comment]
> 同样的问题，挂梯子重新安装后还是有这个问题

是不是梯子质量不好？我挂梯子安装就有了

**Comment by KINNAKAIHOU** [comment]
> 

好奇怪，我预览版是可以的，但是正式版不行，开正式版的话首页直接白屏

**Comment by the1812** [comment]
去首页换 jsDelivr 源
