### ISSUE TITLE
mdi图标404

### ISSUE THREAD

**Issue by Yun-Shan** [the1812/Bilibili-Evolved#3761]
### 对应功能

包括插件菜单图标和视频底下的稍后再看图标无法正常显示，未影响功能，但是比较影响使用体验

### 问题描述

https://github.com/the1812/Bilibili-Evolved/blob/b56d7b482af639ec27d1ddc6c9935281b5a77924/webpack/cdn/jsdelivr.ts#L16
访问这个cdn链接 `https://fastly.jsdelivr.net/gh/Templarian/MaterialDesign-Webfont@5.3.45/css/materialdesignicons.min.css` 返回的字体url是 `../fonts/materialdesignicons-webfont.woff2?v=5.3.45`

https://github.com/the1812/Bilibili-Evolved/blob/b56d7b482af639ec27d1ddc6c9935281b5a77924/src/ui/mdi/index.ts#L11
但是这里直接替换得到的是 `./materialdesignicons.min.woff2`，而这个文件并不存在导致404

断点强行替换成正确的链接后显示正常

### 脚本版本

v2.5.0-25-gdab6500b7

### 浏览器版本

Chrome 106.0.5249.103

### 播放器版本

3.20.11-fb629aa9

### 播放策略

默认

### 错误信息

```shell
Failed to load resource: the server responded with a status of 404 ()
```

**Comment by the1812** [comment]
之前设错地址了, v2.5.1 已修复
