### ISSUE TITLE
首页稍后再看按钮按了没反应

### ISSUE THREAD

**Issue by dmddjack** [the1812/Bilibili-Evolved#3762]
### 对应功能

[settings.zip](https://github.com/the1812/Bilibili-Evolved/files/9839926/settings.zip)

### 问题描述

开了简化首页，首页稍后再看按钮按了没反应

### 脚本版本

v2.5.0-25-gdab6500b7

### 浏览器版本

Chrome 106.0.5249.119 (正式版本) (64 位元)

### 播放器版本

3.20.11-fb629aa9

### 播放策略

默认

### 错误信息

```shell
没有错误信息
```

**Comment by q56535** [comment]
请问有类似的报错吗
![1 848_POS~CBZT7B26U3QJQ](https://user-images.githubusercontent.com/26663837/208287708-e37af023-f9ed-4c85-bd98-16b9bd9c6316.png)
![80SDT8Y_W%F% A7D4%R7DAS](https://user-images.githubusercontent.com/26663837/208287709-51cf14a8-fb8d-4b9d-b88e-870c66877f54.png)
如果有能否提供一下在使用什么扩展程序
