### ISSUE TITLE
（如果可以的话）动态右侧 正在直播 显示尽可能多的条目

### ISSUE THREAD

**Issue by teatube** [the1812/Bilibili-Evolved#377]
**关于哪一项功能**

动态相关

**期望的效果**
动态右侧 正在直播 显示尽可能多的人正在直播（而不用点 更多>）
(如果可以的话）

**脚本版本**
1.10.6

**Comment by the1812** [comment]
目前上限是多少个?

**Comment by teatube** [comment]
> 
> 
> 目前上限是多少个?

10个

**Comment by the1812** [comment]
可以扩到30个

**Comment by teatube** [comment]
> 
> 
> 可以扩到30个

那也很强了（好像手机上一次能看30个来着）
