### ISSUE TITLE
直播信息扩充界面开启会导致动态的正在直播界面仅显示6个直播间

### ISSUE THREAD

**Issue by grender12** [the1812/Bilibili-Evolved#3774]
### 对应功能

直播信息扩充界面开启会导致动态的正在直播界面仅显示6个直播间，关闭后会正常显示10个直播间

### 问题描述

直播信息扩充开启会导致动态的正在直播界面仅显示6个直播间，关闭后会正常显示10个直播间

### 脚本版本

v2.5.1-15-g3869a146c

### 浏览器版本

 106.0.1370.52 (正式版本) (64 位)

### 播放器版本

非视频播放相关问题

### 播放策略

默认

### 错误信息

```shell
直播信息扩充界面开启会导致动态的正在直播界面仅显示6个直播间，关闭后会正常显示10个直播间
```

### 附加截图

1

**Comment by the1812** [comment]
6个的时候可以滚动吗

**Comment by grender12** [comment]
> 6个的时候可以滚动吗

不能，
![image](https://user-images.githubusercontent.com/110667863/198614171-48cc009e-ade0-4732-a6b4-ddfe71809088.png)
就像这样，能注意到有一部分没有显示

**Comment by the1812** [comment]
屏幕分辨率和缩放是多少

**Comment by grender12** [comment]
> 屏幕分辨率和缩放是多少

1920*1080 110%

**Comment by the1812** [comment]
确定是系统缩放 (一般就在分辨率旁边) 吗, 不是浏览器缩放

**Comment by grender12** [comment]
> 确定是系统缩放 (一般就在分辨率旁边) 吗, 不是浏览器缩放
系统缩放125%，浏览器110%

**Comment by the1812** [comment]
模拟试了下没问题啊, 也可以正常滚动

<div>
<img width="300" src="https://user-images.githubusercontent.com/26504152/201339189-5ccc5e44-6515-4527-aeaa-36072e600dfa.png">
<img width="300" src="https://user-images.githubusercontent.com/26504152/201339217-bcdaa4fd-d946-4f80-9f3e-2df38d76c7c3.png">
</div>

**Comment by wcnpdcwxy** [comment]
类似的问题我也碰到了，我这边以前是可以全部信息滚轮查看的，目前固定只显示10个。而且我遇到这个问题有一阵子了，时不时更新或者其它原因就好了，时不时又出问题，一阵一阵的。
