### ISSUE TITLE
夜间模式清爽首页文字颜色

### ISSUE THREAD

**Issue by unlsycn** [the1812/Bilibili-Evolved#3786]
### 对应功能

- 夜间模式
- 清爽首页

### 问题描述

夜间模式的清爽首页下，分区标题颜色是黑色。

### 脚本版本

v2.5.1-preview

### 浏览器版本

Microsoft Edge 106.0.1370.52

### 播放器版本

3.21.7

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/31343548/198686515-e68d2687-f58a-48dd-8e6c-7456724098e0.png)

**Comment by Geeyun-JY3** [comment]
善用搜索：https://github.com/the1812/Bilibili-Evolved/discussions/3769#discussioncomment-3961578

**Comment by unlsycn** [comment]
组件版本commit: (preview)3c2cce86de3bf922598070b2086f5b04f5366888

**Comment by Geeyun-JY3** [comment]
怪了，我测试的 `清爽首页` 组件的 commit hash 也是 3c2cce86d

**Comment by fly10696** [comment]
我也是,都看不清字
![image](https://user-images.githubusercontent.com/117005380/198870426-696e76bd-57be-482d-bd0f-2b74ac95499f.png)

**Comment by Geeyun-JY3** [comment]
@fly10696 我们这说的是 `清爽首页` 这个组件，你这是破站的新版播放页，相关 issue 在这：#2615

**Comment by the1812** [comment]
可能是不同版本的 b 站首页, 退出清爽首页然后试试右下的内测/新版切换

**Comment by Geeyun-JY3** [comment]
> 可能是不同版本的 b 站首页, 退出清爽首页然后试试右下的内测/新版切换

确实是版本的问题，大概搞清楚了，可以复现。

现在 b 站首页原来有三个版本（至少，我能随意切换体验到的就有）：旧版、新版、内测

- 旧版里就会有本 issue 所说的夜间模式下分区视频标题是黑色的问题（另外分区的 `有新动态` 和 `最新发布` 中的视频的视频标题也不对，不知道提取到了什么信息）
- 新版里 `清爽首页` 组件好像直接失效了
- 内测里反而好像没什么问题

不是很懂破站这测试跨度拉这么长是干嘛，我还以为旧版早被干没了。

**Comment by unlsycn** [comment]
> > 可能是不同版本的 b 站首页, 退出清爽首页然后试试右下的内测/新版切换
> 
> 确实是版本的问题，大概搞清楚了，可以复现。
> 
> 现在 b 站首页原来有三个版本（至少，我能随意切换体验到的就有）：旧版、新版、内测
> 
> * 旧版里就会有本 issue 所说的夜间模式下分区视频标题是黑色的问题（另外分区的 `有新动态` 和 `最新发布` 中的视频的视频标题也不对，不知道提取到了什么信息）
> * 新版里 `清爽首页` 组件好像直接失效了
> * 内测里反而好像没什么问题
> 
> 不是很懂破站这测试跨度拉这么长是干嘛，我还以为旧版早被干没了。

的确，之前新版清爽首页失效之后我就切回旧版了。
谢谢。
