### ISSUE TITLE
点击播放后，视频却突然消失

### ISSUE THREAD

**Issue by 2222A** [the1812/Bilibili-Evolved#379]
**关于哪一项功能**
未发现是哪项功能引起的bug

**问题描述**

https://www.bilibili.com/video/av95270169
此视频下点击播放视频会消失，扬声器也没有声音。我试了下，其他的视频也有这样的问题，但是番剧却没受到影响。

**脚本版本**

1.10.6

**浏览器版本**

版本 80.0.3987.132（正式版本） （64 位）

**错误信息**

![Uploading image.png…]()

**附加截图**
![Snipaste_2020-03-15_13-31-57](https://user-images.githubusercontent.com/52919808/76696003-648e7380-66c1-11ea-998b-5a1df58cd58e.png)

**Comment by Coulomb-G** [comment]
先把其他插件脚本关了再试试?

**Comment by 2222A** [comment]
谢谢，问题已解决。把“為什麼你們就是不能加個空格呢？”这个脚本在B站禁掉问题就解决了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Coulomb-G"<notifications@github.com&gt;; 
发送时间: 2020年3月15日(星期天) 中午1:35
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "以德服人"<2361778223@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 点击播放后，视频却突然消失 (#379)





 
先把其他插件脚本关了再试试?

**Comment by the1812** [comment]
原来又是这个脚本啊。。 #254 曾经讨论过

**Comment by 2222A** [comment]
哦哦，抱歉我之前没有看closed issues。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Grant Howard"<notifications@github.com&gt;; 
发送时间: 2020年3月16日(星期一) 中午12:25
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "以德服人"<2361778223@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 点击播放后，视频却突然消失 (#379)





 
原来又是这个脚本啊。。 #254 曾经讨论过

**Comment by 2222A** [comment]
感谢您提供这么好的脚本。
