### ISSUE TITLE
扩展倍速功能正常,但是无法正常点击启用

### ISSUE THREAD

**Issue by aquawius** [the1812/Bilibili-Evolved#3790]
### 对应功能

> 插件功能定位: 扩展倍速
> Commit: 3869a146c
> 内部名称: extendVideoSpeed

![image](https://user-images.githubusercontent.com/70997816/198931306-f753414d-c50b-495d-ada3-494edf715951.png)

### 问题范围:
在所有页面上都有这个问题
已经测试在Edge和Chrome(都为最新版)(Tampermonkey版本)上都有此问题 Edge版本(107.0.1418.26)  Chrome版本(107.0.5304.88) 系统为Win10 22h2 x64版本

在其他脚本平台(比如脚本猫)上没有测试

### 问题描述:
在点击1.5倍速的时候,只能通过点击1.5x上下的小块进行触发,1.5倍速功能正常
点击1.5x文字无反应(有时会切换到3.0倍速)

![image](https://user-images.githubusercontent.com/70997816/198931019-313af0c8-2312-4a7c-ac54-0f4c93d8454a.png)
![image](https://user-images.githubusercontent.com/70997816/198931129-784a3953-bb69-425b-9d6f-0858209578d2.png)

### 脚本版本

v2.5.1-30-gb1ec760a3

### 浏览器版本

Edge版本(107.0.1418.26)

### 播放器版本

3.21.7-dd97bab4

### 播放策略

默认

### 错误信息

```shell
我觉得和这个没有关系,还是粘一个好了

![image](https://user-images.githubusercontent.com/70997816/198934154-9267b114-c534-4b99-963b-708346c63f52.png)
```

### 附加截图

![image](https://user-images.githubusercontent.com/70997816/198933559-ad014435-7878-4c6b-9bfb-bc09c11814f9.png)
只学过基础JS的我....看不懂

**Comment by LonelySteve** [comment]
#3539 

解决方案见：https://github.com/the1812/Bilibili-Evolved/issues/3539#issuecomment-1229362535
