### ISSUE TITLE
头像显示异常

### ISSUE THREAD

**Issue by Lu-del** [the1812/Bilibili-Evolved#3792]
### 对应功能

自定义顶栏

### 问题描述

头像请求路径多加个s（我看头像请求地址是这个开头：httpss）

### 脚本版本

1.12.22

### 浏览器版本

106.0.5249.62

### 播放器版本

 1

### 播放策略

默认

### 错误信息

```shell
1
```

**Comment by Geeyun-JY3** [comment]
v1 不维护啦
