### ISSUE TITLE
浏览器标签页转圈很久才加载完该插件

### ISSUE THREAD

**Issue by doglex** [the1812/Bilibili-Evolved#3793]
### 对应功能

并非特定功能

### 问题描述

浏览器标签页转圈很久才加载完该插件。以前不是的，最近才这样

### 脚本版本

2.5.1

### 浏览器版本

版本 107.0.5304.88（正式版本） （64 位）

### 播放器版本

3.21.7

### 播放策略

默认

### 错误信息

```shell
Bilibili Evolved 网址参数清理 https://www.bilibili.com/video/BV1iV411x7d9/?vd_source=6d88267edd65f32e71463812e33008f1 https://www.bilibili.com/video/BV1iV411x7d9/
Bilibili Evolved.user.js:216 Bilibili Evolved (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}]
Bilibili Evolved.user.js:216 Bilibili Evolved reply 0 0
Bilibili Evolved.user.js:216 Bilibili Evolved at 0 0
Bilibili Evolved.user.js:216 Bilibili Evolved like 0 0
Bilibili Evolved.user.js:216 Bilibili Evolved sys_msg 0 0
Bilibili Evolved.user.js:216 Bilibili Evolved user_msg 0 14
```

**Comment by doglex** [comment]
DevTools 无法加载来源映射：无法加载 https://s1.hdslb.com/bfs/static/jinkela/risk-captcha-sdk/CaptchaLoader.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载来源映射：无法加载 https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载来源映射：无法加载 https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/vue.min.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE


有种可能是bilibili自身的东西正在加载中，能否提前该插件的加载，因为该插件不加载，右上的功能就没了

**Comment by Ethkuil** [comment]
> 浏览器标签页转圈很久才加载完该插件。以前不是的，最近才这样
「很久」是大概几秒？

> 有种可能是bilibili自身的东西正在加载中，能否提前该插件的加载，因为该插件不加载，右上的功能就没了
「右上的功能」指？

没能完全理解，盲猜一下，通用设置里的「功能加载模式」、「样式加载模式」是否是你需要的东西？

（在我电脑上，B站页面大略显示后，还要等2秒，Bilibili-Evolved的2个按钮才能加载出来，同时B站加载完成。）

**Comment by the1812** [comment]
可以试试这样设置
![image](https://user-images.githubusercontent.com/26504152/200109883-a70619ef-e55f-4923-b873-8a76fc60da97.png)

**Comment by doglex** [comment]
> 可以试试这样设置 ![image](https://user-images.githubusercontent.com/26504152/200109883-a70619ef-e55f-4923-b873-8a76fc60da97.png)

我试试，感谢！

**Comment by doglex** [comment]
> > 浏览器标签页转圈很久才加载完该插件。以前不是的，最近才这样
> > 「很久」是大概几秒？
> 
> > 有种可能是bilibili自身的东西正在加载中，能否提前该插件的加载，因为该插件不加载，右上的功能就没了
> > 「右上的功能」指？
> 
> 没能完全理解，盲猜一下，通用设置里的「功能加载模式」、「样式加载模式」是否是你需要的东西？
> 
> （在我电脑上，B站页面大略显示后，还要等2秒，Bilibili-Evolved的2个按钮才能加载出来，同时B站加载完成。）

很久，大概要20秒。
右上角的功能是 订阅、消息、头像 等控件。
 我试试

**Comment by doglex** [comment]
> > 浏览器标签页转圈很久才加载完该插件。以前不是的，最近才这样
> > 「很久」是大概几秒？
> 
> > 有种可能是bilibili自身的东西正在加载中，能否提前该插件的加载，因为该插件不加载，右上的功能就没了
> > 「右上的功能」指？
> 
> 没能完全理解，盲猜一下，通用设置里的「功能加载模式」、「样式加载模式」是否是你需要的东西？
> 
> （在我电脑上，B站页面大略显示后，还要等2秒，Bilibili-Evolved的2个按钮才能加载出来，同时B站加载完成。）

有用

**Comment by doglex** [comment]
> 可以试试这样设置 ![image](https://user-images.githubusercontent.com/26504152/200109883-a70619ef-e55f-4923-b873-8a76fc60da97.png)

有用
