### ISSUE TITLE
能否增加默认旧版播放器的功能

### ISSUE THREAD

**Issue by RainSola** [the1812/Bilibili-Evolved#38]
RT，习惯使用旧版播放器，但是B站总是自动切成新版播放器，不知道是哪个插件导致还是B站自己的设定。
总之如果可能的话，希望能给一个设置默认旧版播放器或屏蔽新版播放器的功能，非常感谢！

**Comment by the1812** [comment]
我记得新版右侧有个返回旧版的按钮的(脚本没开的时候)
那个要是也不管用的话, 我可以加个切换播放器的功能. (可能要等到元旦了, 期末比较忙

**Comment by RainSola** [comment]
> 
> 
> 我记得新版右侧有个返回旧版的按钮的(脚本没开的时候)
> 那个要是也不管用的话, 我可以加个切换播放器的功能. (可能要等到元旦了, 期末比较忙

对的，我用右侧那个返回旧版，但是经常打开新视频页面时又会自动变成新版，然后又要手动返回旧版，如此反复，非常麻烦。
我试过直接把暴力猴直接关闭，也会遇到这种情况，所以可能不是插件导致而是B站本身的设计行为。
总之，希望能有一个设置默认旧版播放器或屏蔽新版播放器的功能，不急，有空再弄都可以，谢谢！

**Comment by RainSola** [comment]
> 
> 
> 新版本加了这个功能了, 不过我不太确定能不能稳定切换, 先用着试试吧

非常感谢，暂时使用没有问题，后续使用有问题会再来反馈的。
