### ISSUE TITLE
弹幕默认设置的一点小建议

### ISSUE THREAD

**Issue by LTHPKBTE** [the1812/Bilibili-Evolved#380]
**关于哪一项功能**
视频-使用默认弹幕设置-记住弹幕设置

**期望的效果**
1.默认的渲染选项是Canvas，但是我无论是在哪个机器上测试，这种渲染都比CSS3要慢很多，而且还会有卡顿现象。如果是bilibili默认这样设置的....也是改一下比较好。
2.如果可能的话能不能在登陆时候/开启记住设置时自动获取这个账号的弹幕设置？每次都调感觉有点麻烦。（好像bilibili本身会同步的来着....）
3.有时候自动记住不会记住按类型屏蔽的"顶部"和"底部"选项。

**脚本版本**
Bilibili Evolved (Preview)1.10.9 
插件管理器[tampermonkey]4.10.6105
浏览器FireFox74.0

**Comment by the1812** [comment]
1. Firefox上默认Canvas, Chrome上默认CSS3, 不知道为什么b站要这样设置, 但是修改过一次后b站就会保存的.
2. 账号有关联弹幕设置吗? 我不清楚, 换一个浏览器登录并没有同步过设置.
3. 记住弹幕设置仅限`防挡字幕`和`智能防挡弹幕`, 类型屏蔽是b站去记的, 刷新还有, 但关闭这个标签页就会失效.

**Comment by LTHPKBTE** [comment]
谢谢解答，如果不做修改渲染选项的话这个issue可以关了
