### ISSUE TITLE
插件【下载视频 - 手动输入】问题

### ISSUE THREAD

**Issue by Tinhone** [the1812/Bilibili-Evolved#3801]
### 对应功能

下载视频
Commit: 3c2cce86d

### 问题描述

安装插件：
下载视频 - 手动输入
downloadVideo.inputs.manual

进入番剧播放页面，打开功能栏，点击下载视频，在弹窗中打开[输入源]下拉框，会发现并没有[手动输入]选项
![图片](https://user-images.githubusercontent.com/81268244/200022617-5de3edd0-7266-4831-a848-3089bfe69c46.png)

---

在BV播放页面执行操作则不会出现这个问题
![图片](https://user-images.githubusercontent.com/81268244/200025470-03dd801b-34e6-4d7e-bbe1-b24c0bc24195.png)

### 脚本版本

v2.5.1-preview

### 浏览器版本

Firefox V88

### 播放器版本

番剧播放页面v3.20.11  BV播放页面v3.21.7

### 播放策略

AVC

### 错误信息

```shell
见下
```

### 附加截图

![图片](https://user-images.githubusercontent.com/81268244/200025313-e7b84d20-48ea-4820-af8a-35ac9cdefff8.png)

**Comment by the1812** [comment]
设定如此, 必须要在视频页面才能使用
