### ISSUE TITLE
动态页面经常莫名其妙的弹出报错

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#3802]
### 对应功能

也不知道是哪个功能报错,反正动态相关组件如图

### 问题描述

也不是每次进入动态就会报错,但频率还算比较高

### 脚本版本

2.5.1

### 浏览器版本

107

### 播放器版本

3.21

### 播放策略

AVC

### 错误信息

```shell
Bilibili Evolved Error
    at o.nextPage (eval at loadFeatureCode (t.bilibili.com/:193:66108), <anonymous>:17:2617)
    at async o.created (eval at loadFeatureCode (t.bilibili.com/:193:66108), <anonymous>:17:2331)
```

### 附加截图

![image](https://user-images.githubusercontent.com/14146754/200096707-b8f72243-d0b7-46e9-8fce-7f45816a074d.png)
![image](https://user-images.githubusercontent.com/14146754/200096822-0dc9bf2a-c324-4b17-8bd0-c0409721d35c.png)

**Comment by the1812** [comment]
看报错是顶栏的某个弹窗加载失败了

**Comment by u2shana** [comment]
> 看报错是顶栏的某个弹窗加载失败了
顶栏相关
![image](https://user-images.githubusercontent.com/14146754/200097067-7a7f298b-7d1f-449d-a636-78e463fa83e1.png)
![image](https://user-images.githubusercontent.com/14146754/200097094-ce5db110-3a38-4d40-9e95-03604872cecd.png)

**Comment by the1812** [comment]
重新从在线仓库装一下 `自定义顶栏`, 或者尝试重新登录再试试?

**Comment by u2shana** [comment]
找出问题了,是顶栏动态里面加载不出东西,鼠标滑过去就会报错,找了半天原因,停用各种插件都不行,然后重置下网站数据就恢复了
