### ISSUE TITLE
希望能控制小视频是否自动播放

### ISSUE THREAD

**Issue by jmlevol** [the1812/Bilibili-Evolved#381]
**关于哪一项功能**
设置—动态

**期望的效果**
动态流页面下拉时，一些小视频会自动静音播放，希望添加能禁止“小视频”自动播放的按钮

**脚本版本**
1.10.6

**Comment by Coulomb-G** [comment]
目前可通过「动态过滤器」直接屏蔽小视频,怕错过优秀的小视频的话,可以切换到小视频栏专门查看

**Comment by jmlevol** [comment]
> 目前可通过「动态过滤器」直接屏蔽小视频,怕错过优秀的小视频的话,可以切换到小视频栏专门查看

谢谢解答

**Comment by Geeyun-JY3** [comment]
现在是不是没有小视频这东西了

**Comment by the1812** [comment]
是的, 都会变成普通视频
