### ISSUE TITLE
自定义顶栏显示问题

### ISSUE THREAD

**Issue by LinkLee2020** [the1812/Bilibili-Evolved#3810]
### 对应功能

自定义顶栏

### 问题描述

开启后在新的顶栏覆盖下还显示“检测到您的页面展示可能受到浏览器插件影响，建议您将当前页面加入插件白名单，以保障您的浏览体验～”，因为顶栏被覆盖，所以无法点击关闭，非常影响观感，希望可以去除，提升体验

### 脚本版本

v2.5.1-15-g3869a146c

### 浏览器版本

safari v16.1

### 播放器版本

V3.22.1

### 播放策略

默认

### 错误信息

```shell
无
```

**Comment by Geeyun-JY3** [comment]
#3719

那就把自定义顶栏关掉后再去关掉这个横幅啊

**Comment by xiaochopin** [comment]
> ### 对应功能
> 自定义顶栏
> 
> ### 问题描述
> 开启后在新的顶栏覆盖下还显示“检测到您的页面展示可能受到浏览器插件影响，建议您将当前页面加入插件白名单，以保障您的浏览体验～”，因为顶栏被覆盖，所以无法点击关闭，非常影响观感，希望可以去除，提升体验
> 
> ### 脚本版本
> v2.5.1-15-g3869a146c
> 
> ### 浏览器版本
> safari v16.1
> 
> ### 播放器版本
> V3.22.1
> 
> ### 播放策略
> 默认
> 
> ### 错误信息
> ```shell
> 无
> ```
> 
> ### 附加截图
> _No response_

使用这个·
https://greasyfork.org/zh-CN/scripts/463096-%E8%87%AA%E5%8A%A8%E5%85%B3%E9%97%ADb%E7%AB%99%E6%A8%AA%E5%B9%85%E6%8F%90%E7%A4%BA
