### ISSUE TITLE
chrome组件自定义顶栏无法正常显示头像

### ISSUE THREAD

**Issue by Qianclear** [the1812/Bilibili-Evolved#3811]
### 对应功能

组件：自定义顶栏
Commit: 124fff7f9

### 问题描述

chrome无法正常显示头像，查看源代码发现是httpss
在chrome中：
![Snipaste_2022-11-10_20-58-39](https://user-images.githubusercontent.com/53326107/201097695-11fa788f-f6f9-41d2-955a-665ffd3db919.png)
在edge中：
![Snipaste_2022-11-10_21-00-05](https://user-images.githubusercontent.com/53326107/201098044-48a4afcd-3eba-4927-b5d1-036aceb99500.png)

### 脚本版本

2.5.1

### 浏览器版本

107.0.5304.107（正式版本） （64 位）

### 播放器版本

3.22.1-e4daf1b7

### 播放策略

AV1

### 错误信息

```shell
应该不是播放器的问题(猜的)
```

### 附加截图

![Snipaste_2022-11-10_21-03-18](https://user-images.githubusercontent.com/53326107/201099542-efbce348-e4b2-4031-9065-eb7547d9d93f.png)

**Comment by Qianclear** [comment]
tampermonkey版本是v4.14

**Comment by the1812** [comment]
自定义顶栏组件更新一下
