### ISSUE TITLE
点击首页直接白屏

### ISSUE THREAD

**Issue by KINNAKAIHOU** [the1812/Bilibili-Evolved#3816]
### 对应功能

无

### 问题描述

首页白屏，跳到视频网页也是没有按钮出现

### 脚本版本

2.5.1 正式版 (jsDelivr 源)

### 浏览器版本

版本 107.0.5304.107（正式版本） （64 位）

### 播放器版本

HTML5播放器 V3.22.1

### 播放策略

默认

### 错误信息

```shell
bilibili evolved没有出现任何消息
```
![image](https://user-images.githubusercontent.com/73224577/201831824-daf9f9f7-0faf-4fce-8790-a5a783882cd8.png)

**Comment by Ethkuil** [comment]
未能复现，也猜不出原因，因为从现有条件似乎看不出任何问题。暂有以下思路，可考虑进一步提供信息以便开发者找到问题所在：

1. 关闭 此脚本 后问题仍存在吗？
2. 若关闭此脚本后问题消失、而再启用后问题再次出现，可考虑完整复制下控制台信息（即使可能感觉无关）贴到回复。
3. 另外，此问题是何时开始发生的？比如有使用旧版本的话，旧版本是否有这个问题？

**Comment by MirionQs** [comment]
油猴管理器里重置存储项

**Comment by KINNAKAIHOU** [comment]
> components

![image](https://user-images.githubusercontent.com/73224577/204968489-663d6700-40af-49b6-a08c-b4ea97ec3a96.png)
你是说这里的存储的哪项，我没找到？
