### ISSUE TITLE
极简首页组件：“默认标签页”始终为“动态”，设置选项无法生效

### ISSUE THREAD

**Issue by Ethkuil** [the1812/Bilibili-Evolved#3817]
### 对应功能

内部名称：minimalHome，Commit: 3869a14 （为最新正式版）

### 问题描述

> 其中一项“默认标签页”选项无法生效，具体表现为：我设置了默认标签页为推荐，但首页还是显示动态，推荐在第二页。

https://github.com/the1812/Bilibili-Evolved/issues/3331#issuecomment-1314993964

### 脚本版本

v2.5.1-15-g3869a146c

### 浏览器版本

Version 107.0.5304.107 (Official Build) (64-bit)

### 播放器版本

3.22

### 播放策略

默认

### 错误信息

```shell
无报错信息
```

**Comment by Ethkuil** [comment]
另外吐槽一下不解之处，为何要把 “热门” 与 “个性化推荐” 挤在一个标签页里二选一呢，分别可选不也挺好吗？

**Comment by the1812** [comment]
不是所有人都喜欢看到个性化推荐

**Comment by Ethkuil** [comment]
我的意思是类似于这样：

动态             <选择是否开启>
热门            <选择是否开启>
个性化推荐  <选择是否开启>

**Comment by Ethkuil** [comment]
我今晚比较有空，如果你不打算马上改这两个地方的话，我可以试试分 2 个 commit 改完发个 PR。

**Comment by the1812** [comment]
可以的，我这周要修别的 bug

**Comment by the1812** [comment]
我今晚有空就先修了(
