### ISSUE TITLE
阿b直播间好像会自动跳默认画质，

### ISSUE THREAD

**Issue by aoi777** [the1812/Bilibili-Evolved#382]
**关于哪一项功能**

开始省钱了？.....反正就是低人气的是原画，高人气也是原画，万把人气不高不低那种会默认超清？
也没搞清是个什么设定
**期望的效果**
给整个自动跳回原画画质，不然看一些直播间会默认超清，有点糊。

**脚本版本**

**Comment by the1812** [comment]
同#286, 在做了在做了
