### ISSUE TITLE
开启""简化评论区""功能，导致画中画无法在评论区正常显示

### ISSUE THREAD

**Issue by 527570755** [the1812/Bilibili-Evolved#3822]
### 对应功能

简化评论区

### 问题描述

开启网页的画中画，视频无法完成显示，评论区区域范围的被遮挡

### 脚本版本

v2.5.1-15-g3869a146c

### 浏览器版本

Edge版本 107.0.1418.42 (正式版本) (64 位)

### 播放器版本

2.88.0-5a1f2816

### 播放策略

默认

### 错误信息

```shell
无
```

### 附加截图

![QQ截图20221119193638](https://user-images.githubusercontent.com/31041923/202849265-f04ada0a-51d8-450f-9e66-1d9c89b069e9.png)

**Comment by Geeyun-JY3** [comment]
你这截图里的是破站的迷你播放器吧

**Comment by 527570755** [comment]
> 你这截图里的是破站的迷你播放器吧
是的，就是网页直接往下滑，就会出现这个小窗，然后拖到评论区就会显示不全，被遮住了一样

**Comment by Geeyun-JY3** [comment]
画中画不是指这个……

另外我这边是无法复现的，建议提供更多信息如错误信息

**Comment by 527570755** [comment]
这问题一开始没有，中间出现了有半个月吧，今天好像又没这个问题了
