### ISSUE TITLE
首页账号头像无法正常显示

### ISSUE THREAD

**Issue by Char1esAce** [the1812/Bilibili-Evolved#3825]
### 对应功能

首页账号头像无法正常显示

### 问题描述

首页账号头像无法正常显示

### 脚本版本

Bilibili Evolved Offline v1246.26

### 浏览器版本

FireFox Offline v1246.26

### 播放器版本

HTML5播放器 V3.22.1

### 播放策略

默认

### 错误信息

```shell
Nothing
```

### 附加截图

![图片](https://user-images.githubusercontent.com/93077301/202860729-29d7510e-68d4-4389-8414-76edb9dc734f.png)

**Comment by the1812** [comment]
v1 不维护了
