### ISSUE TITLE
夜间模式评论区工作不正常

### ISSUE THREAD

**Issue by Asiimoviet** [the1812/Bilibili-Evolved#3826]
### 对应功能

对应功能：夜间模式
Commit：3869a146c

### 问题描述

![image](https://user-images.githubusercontent.com/66727875/202865377-323b495b-c36f-4cff-a8c1-73684b0d6037.png)

评论区背景颜色不正确

修改CSS：
`.comment-m-v1 .comment-container {
  background-color: #222222;
}`

### 脚本版本

v2.5.1-30-gb1ec760a3

### 浏览器版本

Microsoft Edge Search result match: Version 107.0.1418.52 (Official build) (64-bit)Version 107.0.1418.52 (Official build) (64-bit)

### 播放器版本

3.22.1

### 播放策略

默认

### 错误信息

```shell
没有啥错误
```

**Comment by Asiimoviet** [comment]
修改后
![image](https://user-images.githubusercontent.com/66727875/202865483-c56d1400-198b-402f-b407-2e7a371bb0f7.png)

**Comment by the1812** [comment]
该更新了
