### ISSUE TITLE
看视频浏览器卡死

### ISSUE THREAD

**Issue by dmddjack** [the1812/Bilibili-Evolved#3827]
### 对应功能

[settings.zip](https://github.com/the1812/Bilibili-Evolved/files/10048889/settings.zip)

### 问题描述

随便看什么视频，打开两三个视频页面，打开自动连播，播视频半个小时左右有时候退出全屏会卡死，有时候重新加载会卡死，有时候自动卡死，Chrome未响应。在我的两部电脑上都有复现。

### 脚本版本

v2.5.1-30-gb1ec760a3

### 浏览器版本

107.0.5304.107

### 播放器版本

3.22.2-rc.0075.0-8f54c8b9

### 播放策略

默认

### 错误信息

```shell
卡死了，F12打不开
```

**Comment by 7est** [comment]
同样的情况。
同环境同设置edge无影响

**Comment by the1812** [comment]
这应该是 Chrome 的问题吧

**Comment by 7est** [comment]
关闭高分辨率图片后正常，可以试试

**Comment by RushQ** [comment]
打开任意视频，进去不到1min直接卡死， 无法刷新，无响应，根据最后[7est](https://github.com/7est) 的建议，关闭高分辨率图片后正常，六呀。

**Comment by 7est** [comment]
> 打开任意视频，进去不到1min直接卡死， 无法刷新，无响应，根据最后[7est](https://github.com/7est) 的建议，关闭高分辨率图片后正常，六呀。

可能是B站js莫名其妙缓存了一个有问题的版本的锅，关闭高分辨率图片后播放页表情多数出错，最后的解决方案是网页右侧返回旧版再进入新版，完美解决问题

**Comment by Ken14777** [comment]
> 关闭高分辨率图片后正常，可以试试

感谢大佬，我还是跟作者反馈之后作者发了邮件给我转发了你这个评论，尝试之后果然直接好了
