### ISSUE TITLE
清爽首页-分区-番剧 部分字体在夜间模式下没有改为白色

### ISSUE THREAD

**Issue by whyjxz14** [the1812/Bilibili-Evolved#3828]
### 对应功能

清爽首页

### 问题描述

首页

### 脚本版本

v2.5.2-17-g89d37a1f2

### 浏览器版本

版本 105.0.5195.127（正式版本） （64 位）

### 播放器版本

3.22.1

### 播放策略

默认

### 错误信息

```shell
不用
```

### 附加截图

![image](https://user-images.githubusercontent.com/6323818/202903365-88703be0-4b24-422d-a120-bdc6852cdccd.png)
右边的
1.排行榜 2.第一部的标题 3.第二第三部的集数也没

**Comment by unlsycn** [comment]
见 #3786
