### ISSUE TITLE
自定义顶栏收藏夹问题

### ISSUE THREAD

**Issue by pbxs666** [the1812/Bilibili-Evolved#383]
问题：收藏夹不多时这个问题发现不了
![图片1](https://user-images.githubusercontent.com/47630168/77022488-b0446400-69c4-11ea-82ac-b24c14d66eeb.png)
一切正常
从图二到图三，鼠标滚动把下面的收藏滚动出来，就有问题了
![图片2](https://user-images.githubusercontent.com/47630168/77022579-f4cfff80-69c4-11ea-8793-d4765b2348be.png)
![图片3](https://user-images.githubusercontent.com/47630168/77022588-f8fc1d00-69c4-11ea-8f05-5dbed60c7aee.png)
![图片4](https://user-images.githubusercontent.com/47630168/77022623-14ffbe80-69c5-11ea-9905-25503b1aa216.png)
有大半截空白，而且上面隐藏的内容也滚动不回来，其他收藏夹也没法打开。

趁此机会还想提几点建议：
1.能不能给收藏栏和历史栏添加搜索框，虽然空间有点狭小，但没关系。
希望的效果：
![图片5](https://user-images.githubusercontent.com/47630168/77023522-17631800-69c7-11ea-9602-5503d8bdae04.png)
![图片6](https://user-images.githubusercontent.com/47630168/77023531-1c27cc00-69c7-11ea-8a27-43a941946740.png)

2.希望给自定义顶栏的搜索历史添加逐条删除按钮，就像这样
![图片7](https://user-images.githubusercontent.com/47630168/77023589-4083a880-69c7-11ea-9be5-86b4f937d2f6.png)
给原始搜索框的历史添加批量删除按钮，像这样
![图片8](https://user-images.githubusercontent.com/47630168/77023623-55603c00-69c7-11ea-85ab-7e77f257f1ec.png)

最后再唠叨几句，大佬的这个脚本很厉害，很喜欢用，要是能 3.自定义的搜索框能同步原始搜索框的历史，就更完美了。现在自定义的搜索历史是重新开始记录的，要是以前搜过很多历史，用上新的自定义搜索框历史同步不过来，岂不是要全部重搜一遍，很麻烦。

写的有点啰嗦，很感谢大佬能够耐心看完，谢谢！

版本：预览版1.10.10

**Comment by the1812** [comment]
感谢建议, 搜索历史目前可以用方向键选中, 按`Shift+Delete`删除

**Comment by the1812** [comment]
和原始搜索框似乎无法同步, b站把这个搜索历史放在`search.bilibili.com`的本地存储中, 在一般的`www.bilibili.com`中读取不到

**Comment by pbxs666** [comment]
嗯嗯，还是很感谢你。不知道上述的其他功能可以实现不

**Comment by the1812** [comment]
可以给`历史`添加搜索框, 而`收藏`这里的搜索有两种, 一种是对当前收藏夹显示出来的视频进行搜索, 非常快速, 另一种是对所有收藏夹以及没显示出来的视频进行搜索, 需要联网花一点时间搜索. 你想要哪一种?

搜索历史将会添加单个删除的按钮, 但对原版顶栏不做修改.

**Comment by pbxs666** [comment]
收藏搜索就我个人而言针对当前收藏夹来说使用一些，平时收藏时就分类清楚了，知道视频的大致位置。当然，其他用户可能分的不是很细，您可以在自定义顶栏中把两种都添加，通过左侧的设置面板选择性开启。（是不是有点贪心，嘿嘿）
历史的搜索框OK
原版顶栏不做修改也行，哈哈

谢谢您耐心的回复！
