### ISSUE TITLE
自定义顶栏导致番剧页顶部banner排版错乱。

### ISSUE THREAD

**Issue by hugbio** [the1812/Bilibili-Evolved#3833]
### 对应功能

自定义顶栏插件

### 问题描述

自定义顶栏导致番剧页顶部banner排版错乱。url：https://B站/anime/

### 脚本版本

v2.5.2-17-g89d37a1f2

### 浏览器版本

Microsoft Edge 版本 107.0.1418.52 (正式版本) (x86_64)

### 播放器版本

V3.22.11

### 播放策略

HEVC

### 错误信息

```shell
-
```

### 附加截图

![image](https://user-images.githubusercontent.com/4772219/203068908-38507452-fb02-41b8-a1bc-ef6ac245d72a.png)

**Comment by Tinhone** [comment]
问题貌似出在`registry/lib/components/style/custom-navbar/hide-original.scss`的34~37行，删掉后就没有这个问题了

**Comment by hugbio** [comment]
@the1812  请问什么时候可以推送更新？这个问题比较影响实用，谢谢

**Comment by the1812** [comment]
周末吧
