### ISSUE TITLE
2.5.2版本运行不了了，我浏览器版本小于100

### ISSUE THREAD

**Issue by Ice-Astro** [the1812/Bilibili-Evolved#3835]
### 对应功能

脚本显示不出来了

### 问题描述

2.5.2版本运行不了了，我浏览器版本小于100，怎么才能回退回2.5.1版本呢（我之前好像一直用的是2.4.几的版本）

### 脚本版本

2.5.2

### 浏览器版本

95.0.4638.69

### 播放器版本

V3.22.1

### 播放策略

AVC

### 错误信息

```shell
版本问题，没有错误信息
```

### 附加截图

![image](https://user-images.githubusercontent.com/73596744/203371392-dca9fae4-64d2-47a7-933d-7cdcf49c524b.png)

**Comment by the1812** [comment]
[bilibili-evolved.v2.5.1.user.zip](https://github.com/the1812/Bilibili-Evolved/files/10072094/bilibili-evolved.v2.5.1.user.zip)

**Comment by wk333** [comment]
我更新了也用不了，换了jsDelivr的就ok了
https://fastly.jsdelivr.net/gh/the1812/Bilibili-Evolved@master-cdn/dist/bilibili-evolved.user.js

**Comment by Tutu2233** [comment]
> 我更新了也用不了，换了jsDelivr的就ok了 https://fastly.jsdelivr.net/gh/the1812/Bilibili-Evolved@master-cdn/dist/bilibili-evolved.user.js
> 
> I can't use it even if I update it, but JSDELIVR is OK https://fastly.jsDelivr.net/gh/the1812/bilibili-evolved@master-cdn/dist/bilibili-evolved.user.js

我想起来了，以前有个版本关闭了一个什么接口，要访问那个网站才能用，然后要搭个梯子，油猴就自动跳出一个窗口，点始终允许才能用
用了你的链接确实可以能用了，就是安装的时候点jsDelivr吗？GitHub的我们用不了是吗？
然后就是更新了需内核>100，但是我95内核也能用，是不是一些功能不支持

**Comment by wk333** [comment]
> > 我更新了也用不了，换了jsDelivr的就ok了 https://fastly.jsdelivr.net/gh/the1812/Bilibili-Evolved@master-cdn/dist/bilibili-evolved.user.js
> > I can't use it even if I update it, but JSDELIVR is OK https://fastly.jsDelivr.net/gh/the1812/bilibili-evolved@master-cdn/dist/bilibili-evolved.user.js
> 
> 我想起来了，以前有个版本关闭了一个什么接口，要访问那个网站才能用，然后要搭个梯子，油猴就自动跳出一个窗口，点始终允许才能用 用了你的链接确实可以能用了，就是安装的时候点jsDelivr吗？GitHub的我们用不了是吗？ 然后就是更新了需内核>100，但是我95内核也能用，是不是一些功能不支持

是的，点jsdeliver就行，具体功能我也不清楚，我主用firefox

**Comment by the1812** [comment]
> 其实是不是可以找个地方写写怎样利用 Git 回退版本，新版本刚出来的一段时间总有人问怎么回退到旧版🤔

https://github.com/the1812/Bilibili-Evolved/blob/master/doc/rollback.md
