### ISSUE TITLE
关于自定义顶栏收藏夹

### ISSUE THREAD

**Issue by xiaole3349** [the1812/Bilibili-Evolved#384]
**关于哪一项功能**

**问题描述**

自定义栏收藏夹的视频收藏日期显示错误。

**脚本版本**

预览版

**浏览器版本**

Edge测试版

**错误信息**

**附加截图**
![L7F36W@92D$4@DX2Q4Z81RG](https://user-images.githubusercontent.com/40677760/77130456-01228e00-6a93-11ea-9c7b-215a60b4d89d.png)

**Comment by the1812** [comment]
加0的时候加反了...

**Comment by xiaole3349** [comment]
> 加0的时候加反了...

就挺生草的www
