### ISSUE TITLE
`选集区域优化`  相关问题：若同时开启了 `展开选集列表` 和 `展开选集标题`，临时收起选集列表时某些选集被遮挡

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#3841]
### 对应功能

选集区域优化
Commit: 14147f840
内部名称: fullEpisodeTitle

### 问题描述

打开 `展开选集列表` 时，若开启了 `展开选集标题`，在选集区域的标题上按住 <kbd>Alt</kbd> 键点击临时收起选集列表后，被排在最后的那些选集有可能会看不全。

只测试了合集类。

### 脚本版本

v2.5.2-preview-49-g14147f840

### 浏览器版本

Chrome 107.0.5304.107（正式版本） （64 位）

### 播放器版本

3.23.5-d83dd953

### 播放策略

AVC

### 错误信息

```shell
无
```

### 附加截图

开启 `展开选集标题` 前
![image](https://user-images.githubusercontent.com/49396421/203820718-a15a2d8d-c9f2-4401-9025-e6013b2c1aa3.png)

开启 `展开选集标题` 后
![image](https://user-images.githubusercontent.com/49396421/203816261-8ea2f0da-e96e-421b-89ee-01209d2719bc.png)

**Comment by Kal-tsit63** [comment]
如果只开启了展开选集标题, 也会有同样的问题.。
![image](https://user-images.githubusercontent.com/85188780/209344558-099592c8-1c54-4b99-a6ba-6e8d793e05b3.png)
