### ISSUE TITLE
存储项乱码导致首页白屏等问题

### ISSUE THREAD

**Issue by MirionQs** [the1812/Bilibili-Evolved#3849]
### 对应功能

N/A

### 问题描述

2.4.X某次更新后我遇到了首页白屏、视频页部分控件消失等问题，关闭插件后一切又都恢复了正常，翻找issue区发现一些人遇到了相同的问题但开发者似乎未能复现。

2.5.2这个问题依然存在，尝试手动解决后发现删除`脚本管理器`-`存储`-`components.settingsPanel.options.scriptLoadingMode`项便解决了问题，但是设置栏中出现了大量乱码。

![Snipaste_2022-11-30_22-21-35](https://user-images.githubusercontent.com/51433180/204820306-88eac6ad-21cc-4199-8903-5fbd00e42914.jpg)

可以看到存储项中有大量乱码，而重置（改成`{}`再在设置栏里重新配置）后再查看就不存在乱码了。
~~有没有可能是某次存储出现了编码问题导致下次读取时出现了各种错误最终造成了上述问题~~

### 脚本版本

2.5.2

### 浏览器版本

107.0.5304.122

### 播放器版本

3.23.9

### 播放策略

默认

### 错误信息

```shell
N/A
```

**Comment by the1812** [comment]
那就怪了, 我从来没转过啥编码

**Comment by MirionQs** [comment]
> 那就怪了, 我从来没转过啥编码

那或许是脚本管理器自己的问题（
