### ISSUE TITLE
FLV文件无效

### ISSUE THREAD

**Issue by ToneySun** [the1812/Bilibili-Evolved#3851]
### 对应功能

下载视频

### 问题描述

下载的视频是无效的

### 脚本版本

2.5.2

### 浏览器版本

108.0.5359.72

### 播放器版本

大于 3

### 播放策略

默认

### 错误信息

```shell
updated widgets Array(1)
userscript.html?name=Bilibili%2520Evolved.user.js&id=4a1a9d29-42b9-474b-9f63-bd2dd66c726e:218 Bilibili Evolved [updateTestVideoInfo] Object
userscript.html?name=Bilibili%2520Evolved.user.js&id=4a1a9d29-42b9-474b-9f63-bd2dd66c726e:218 Bilibili Evolved [updateTestVideoInfo] Object
userscript.html?name=Bilibili%2520Evolved.user.js&id=4a1a9d29-42b9-474b-9f63-bd2dd66c726e:218 Bilibili Evolved Object Object
userscript.html?name=Bilibili%2520Evolved.user.js&id=4a1a9d29-42b9-474b-9f63-bd2dd66c726e:218 Bilibili Evolved [downloadExtraAssets] Array(0)
```

### 附加截图

![image](https://user-images.githubusercontent.com/18101168/204885317-1203db1e-d64c-435a-a6ee-8a9fe3cfb762.png)

**Comment by neverp** [comment]
![image](https://user-images.githubusercontent.com/89000973/204937753-725bf020-be98-46fa-8355-4939dea6ef88.png)
我也遇到了这样的问题

**Comment by WinlorZZ** [comment]
> ![image](https://user-images.githubusercontent.com/89000973/204937753-725bf020-be98-46fa-8355-4939dea6ef88.png) 我也遇到了这样的问题

一样欸

**Comment by the1812** [comment]
#3765

**Comment by BingLianss** [comment]
我也是这样

**Comment by ToneySun** [comment]
> 我也是这样

这是因为B站把视频改了，通过解析可以发现，原先的.flv格式已经变成了.mp4格式。但是作者的脚本还是老一套，如果你是像我一样把视频下载到本地进行观看的，那么，你只需要将.flv改成.mp4即可。

**Comment by BingLianss** [comment]
知道了

ToneySun ***@***.***> 于2023年1月8日周日 15:12写道：

**Comment by BingLianss** [comment]
知道了

**Comment by BingLianss** [comment]
哈哈哈
