### ISSUE TITLE
删除视频弹窗功能失效

### ISSUE THREAD

**Issue by xx146542xx** [the1812/Bilibili-Evolved#3853]
### 对应功能

删除视频弹窗

### 问题描述

删除视频弹窗失效

### 脚本版本

2.5.2

### 浏览器版本

107.0.5304.123

### 播放器版本

3.23.5

### 播放策略

默认

### 错误信息

```shell
↓
```

### 附加截图

![image](https://user-images.githubusercontent.com/109429390/205373317-b19936d5-33bb-40d2-9eba-43515d855167.png)
![image](https://user-images.githubusercontent.com/109429390/205373333-86f87c88-40e5-454f-9b78-ec30dd64482e.png)

**Comment by cjf0523** [comment]
+1

**Comment by ITa-Sun** [comment]
我也
