### ISSUE TITLE
图标看不到了，必须挂梯子

### ISSUE THREAD

**Issue by xibaibai9527** [the1812/Bilibili-Evolved#3858]
### 对应功能

全部

### 问题描述

图标看不到了，除了插件中的图标，比较影响体验的有播放器的截图功能，“稍后在看”的删除按钮
必须挂梯子刷新一下b站才能看到，但第二天又会恢复原样

### 脚本版本

v2.5.2-17-g89d37a1f2

### 浏览器版本

360极速浏览器 95.0.4638.69

### 播放器版本

-

### 播放策略

默认

### 错误信息

```shell
-
```

### 附加截图

![截图03](https://user-images.githubusercontent.com/19858971/205927929-e36d28f2-135d-4a3c-9d86-16c056eaf243.jpg)

**Comment by xibaibai9527** [comment]
忘了说，移动网络

**Comment by the1812** [comment]
首页有 jsDelivr 版 不用梯子
