### ISSUE TITLE
在有分P或者合集的视频播放页面无法显示推荐列表中的视频投稿时间

### ISSUE THREAD

**Issue by MonicaWQY** [the1812/Bilibili-Evolved#3860]
### 对应功能

显示视频投稿时间

### 问题描述

Hi，12月好~我又来提交问题啦……
“显示视频投稿时间”这个功能在只有单P的视频播放页面可正常运行，但是在有分P或者合集的视频播放页面无法正常运行。
单P视频页例子：https://www.bilibili.com/video/BV1eg411H7B5/
多P视频页例子：https://www.bilibili.com/video/BV13R4y1C7eq/
合集视频页例子：https://www.bilibili.com/video/BV1wS4y1s7Ja/

### 脚本版本

v2.5.2-17-g89d37a1f2

### 浏览器版本

Microsoft Edge 108.0.1462.42 (正式版本) (64 位)

### 播放器版本

3.23.9-aa2cfd24

### 播放策略

默认

### 错误信息

```shell
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved plugins block time: 5.2ms for 30 items
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved plugins resolve time: 34.4ms for 30 items
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved 
[__ob__: Ae]
 348460721 false
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved videoChange 348460721 348460721
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved components block time: 10.3ms for 36 items
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved components resolve time: 36937.7ms for 36 items
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved plugins block time: 3.7ms for 30 items
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved plugins resolve time: 25.9ms for 30 items
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved components block time: 2.8ms for 17 items
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved components resolve time: 72.9ms for 17 items
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved 网址参数清理 https://www.bilibili.com/video/BV13R4y1C7eq/?vd_source=1219be0… https://www.bilibili.com/video/BV13R4y1C7eq/
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved 
(6) [79212575, 201275480, 498220633, 56024433, 74964956, 80149248, __ob__: Ae]
 348460721 false
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved init block time: 0.7ms for 6 items
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved init resolve time: 6644.9ms for 6 items
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved init block time: 1ms for 6 items
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved init resolve time: 420.4ms for 6 items
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved updated widgets 
[__ob__: Ae]
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved 
{…}
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved 
{…}
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved 
{code: 0, msg: '', message: '', data: {…}}
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved nextPage get 
(20) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
userscript.html?name…ae-931249c10a43:219 Bilibili Evolved 
(6) [79212575, 201275480, 498220633, 56024433, 74964956, 80149248, __ob__: Ae]
 348460721 false
```

### 附加截图

![单P视频页](https://user-images.githubusercontent.com/93992899/206126973-ae09e2bb-f7cd-43c2-ae63-a9c74eafb870.jpg)
![多P视频页](https://user-images.githubusercontent.com/93992899/206127001-f6ab4a6d-bc56-4beb-9ed4-96f0620528d7.jpg)

**Comment by Geeyun-JY3** [comment]
这功能应该是没适配新版播放页：#2615

**Comment by the1812** [comment]
@wisokey

**Comment by wisokey** [comment]
我在同样的多P视频页面中功能正常
附加截图
![image](https://user-images.githubusercontent.com/57711857/208000873-4d3f33f5-8ca2-408e-b4b4-30f6858ba852.png)

**Comment by MonicaWQY** [comment]
emmm如果你点了右下角前往新版还是正常显示的吗？我这边在我反复测试的时候只有一次我按住alt临时收起分P的时候正常显示过，但我刷新之后再多次测试却怎么也不显示了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月16日(周五) 上午9:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [the1812/Bilibili-Evolved] 在有分P或者合集的视频播放页面无法显示推荐列表中的视频投稿时间 (Issue #3860)




 
我在同样的多P视频页面中功能正常
 附加截图

**Comment by MonicaWQY** [comment]
> 我在同样的多P视频页面中功能正常 附加截图 ![image](https://user-images.githubusercontent.com/57711857/208000873-4d3f33f5-8ca2-408e-b4b4-30f6858ba852.png)

emmm如果你点了右下角前往新版还是正常显示的吗？我这边在我反复测试的时候只有一次我按住alt临时收起分P的时候正常显示过，但我刷新之后再多次测试却怎么也不显示了。

**Comment by MonicaWQY** [comment]
不小心点到关闭了_(:з」∠)_

**Comment by wisokey** [comment]
> > 我在同样的多P视频页面中功能正常 附加截图 ![image](https://user-images.githubusercontent.com/57711857/208000873-4d3f33f5-8ca2-408e-b4b4-30f6858ba852.png)
> 
> emmm如果你点了右下角前往新版还是正常显示的吗？我这边在我反复测试的时候只有一次我按住alt临时收起分P的时候正常显示过，但我刷新之后再多次测试却怎么也不显示了。
目前还没有为新版做适配，也没有做日志的打印
我周末试着写下

**Comment by MonicaWQY** [comment]
> > > 我在同类型的多P视频页面中功能正常 附加截图![图片](https://user-images.githubusercontent.com/57711857/208000873-4d3f33f5-8ca2-408e-b4b4-30f6858ba852.png)
> > 
> > 
> > emmm如果点右下角新版还是正常显示吗？我这边我我反复反复测试测试的的的的时候时候时候只有有一一次我我按住按住按住收起分收起分收起分怎么也不显示了。
> 
> 目前还有没有为新版做合适配，也没有做日志的打印 我周末试着写下

好哦，辛苦啦，比心~(●'◡'●)ﾉ♥

**Comment by wisokey** [comment]
@MonicaWQY 感谢您的使用，这个功能本身就是为我自己开发的，没想到真的会有人用

**Comment by egoistinr** [comment]
想裝「显示视频投稿时间」這個組件
但退到舊版也無法安裝是正常的嗎
不知道是不是同個問題，先發在這裡看看
**脚本版本**
v2.5.2-23-g273a607e5

**浏览器版本**
Chrome 目前是最新版本
版本 108.0.5359.125 (正式版本) (64 位元)
![image](https://user-images.githubusercontent.com/27774913/209457510-30892ca4-7273-490b-9f60-a1cbf9b541c8.png)
![](https://i.imgur.com/ve2DKUP.png)

**Comment by wisokey** [comment]
> 想裝「显示视频投稿时间」這個組件 但退到舊版也無法安裝是正常的嗎 不知道是不是同個問題，先發在這裡看看 **脚本版本** v2.5.2-23-g273a607e5
> 
> **浏览器版本** Chrome 目前是最新版本 版本 108.0.5359.125 (正式版本) (64 位元) ![image](https://user-images.githubusercontent.com/27774913/209457510-30892ca4-7273-490b-9f60-a1cbf9b541c8.png) ![](https://camo.githubusercontent.com/8bcf64441821536935d384f9e86b7f3f2f05fd63e60322a89eabcf9d2ff04036/68747470733a2f2f692e696d6775722e636f6d2f766532444b55502e706e67)

这个你可以试试用preview版本的显示视频投稿时间，我也很奇怪master为啥用不了

**Comment by egoistinr** [comment]
> 这个你可以试试用preview版本的显示视频投稿时间，我也很奇怪master为啥用不了

有了，感謝!!
順便問preview是開發中的beta版嗎?
之後新版的如果改好需要刪掉重裝master版還是不用?

**Comment by wisokey** [comment]
对于这个组件来说用preview和master没区别

**Comment by wisokey** [comment]
毕竟我自己也用

**Comment by MonicaWQY** [comment]
我这两天发现有时候有的多P视频在切到某一P的时候会生效，这个问题大概什么时候会修复呀~

**Comment by wisokey** [comment]
> 我这两天发现有时候有的多P视频在切到某一P的时候会生效，这个问题大概什么时候会修复呀~

这个有具体的bv号不，我得复现才能修复

**Comment by MonicaWQY** [comment]
> > 我这两天发现有时候有的多P视频在切到某一P的时候会生效，这个问题大概什么时候会修复呀~
> 
> 这个有具体的bv号不，我得复现才能修复

BV168411n7c9
我这边刚刚试了一下，每个多P视频都是一样的情况，刚打开视频，右边推荐视频是不显示投稿时间的，切分P才会显示。

**Comment by MonicaWQY** [comment]
https://user-images.githubusercontent.com/93992899/209458591-07823974-65f0-446f-aa58-f068c60b0dda.mp4

大概就是这样

**Comment by wisokey** [comment]
> > > 我这两天发现有时候有的多P视频在切到某一P的时候会生效，这个问题大概什么时候会修复呀~
> > 
> > 
> > 这个有具体的bv号不，我得复现才能修复
> 
> BV168411n7c9 我这边刚刚试了一下，每个多P视频都是一样的情况，刚打开视频，右边推荐视频是不显示投稿时间的，切分P才会显示。

我这边试了下目前的组件版本在旧版页面是正常的，在新版页面会出现你说的现象，不过我已经提交且合并了修复 #3880 ，在这个修复下新版和旧版功能均正常

**Comment by MonicaWQY** [comment]
> > > > 我这两天发现有时候有的多P视频在切到某一P的时候会生效，这个问题大概什么时候会修复呀~
> > > 
> > > 
> > > 这个有具体的bv号不，我得复现才能修复
> > 
> > 
> > BV168411n7c9 我这边刚刚试了一下，每个多P视频都是一样的情况，刚打开视频，右边推荐视频是不显示投稿时间的，切分P才会显示。
> 
> 我这边试了下目前的组件版本在旧版页面是正常的，在新版页面会出现你说的现象，不过我已经提交且合并了修复 #3880 ，在这个修复下新版和旧版功能均正常

那是要到下个版本才可以吗？

**Comment by wisokey** [comment]
目前我用的也是本地编译的版本，你可以自己尝试本地编译后使用

**Comment by MonicaWQY** [comment]
> 目前我用的也是本地编译的版本，你可以自己尝试本地编译后使用

我不会，我是个笨蛋！QAQ呜呜呜~~~我等更新吧，谢谢你！ღ( ´･ᴗ･` )比心！小火车呜呜呜~~~~~~~~~~~~~
