### ISSUE TITLE
BUG开启插件时直播界面自动会被识别为英文

### ISSUE THREAD

**Issue by DEabcdp** [the1812/Bilibili-Evolved#387]
**关于哪一项功能**

**问题描述**

开启插件时，任意直播页面都会被Edge chromium dev浏览器识别为英文页面。如（https://live.bilibili.com/5269）
插件设置里并没有开启页面翻译，我试过关掉插件重启浏览器就正常中文。一旦开启插件，浏览器就识别为英文页面从而自动翻译为乱码。应该是bug吧

**脚本版本**

正式版1.10.6

**浏览器版本**

Edge chromium内核 版本 82.0.457.0 (官方内部版本) canary (64 位)

**错误信息**

**附加截图**

**Comment by the1812** [comment]
编辑脚本, 到497行
```js
medalHelper: true,
about: true,
playerLayout: false,
```
把那个`about: true`改成`about: false`保存试试
```js
medalHelper: true,
about: false,
playerLayout: false,
```

**Comment by DEabcdp** [comment]
成功解决！感谢作者。不过我是在525行找到的medalHelper: true,526行直接是playerLayout: false,中间并没有about: true,。不知道是不是版本的问题，我的使正式版1.10.12.不过，我按你的办法在其中间加入about: false,后完美解决问题！再次感谢！！！
![image](https://user-images.githubusercontent.com/62452364/77482313-97263200-6e60-11ea-93fb-d116751ef7c7.png)

**Comment by DEabcdp** [comment]
成功解决！感谢作者。

不过我是在525行找到的medalHelper: true,526行直接是playerLayout: false,中间并没有about: true,

不知道是不是版本的问题，我的是正式版1.10.12.




不过，我按你的办法在其中间加入about: false,后完美解决问题！再次感谢！！！
















在 2020-03-23 10:41:56，"Grant Howard" <notifications@github.com> 写道：

编辑脚本, 到497行

medalHelper:true,

about:true,

playerLayout:false,

把那个about: true改成about: false保存试试

medalHelper:true,

about:false,

playerLayout:false,
