### ISSUE TITLE
自定义顶栏季节logo不对

### ISSUE THREAD

**Issue by uHioVK** [the1812/Bilibili-Evolved#3876]
### 对应功能

自定义顶栏
Commit: e5bb5742f
内部名称: customNavbar

### 问题描述

![c30c24d4-6330-4665-b453-fb96ecfee900](https://user-images.githubusercontent.com/84575318/207594953-062e3505-f2b7-4192-91a8-23645fa80415.png)
季节logo不对，现在是冬季
问题出现于首页/所有页面

### 脚本版本

v2.5.2-preview-56-ge5bb5742f

### 浏览器版本

Microsoft Edge 版本 108.0.1462.46 (正式版本) (64 位)

### 播放器版本

3.24.5

### 播放策略

默认

### 错误信息

```shell
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=aee43e0b-c877-4b23-9104-a1c23d9b6992:221 Bilibili Evolved 简化首页 isHome true
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=aee43e0b-c877-4b23-9104-a1c23d9b6992:221 Bilibili Evolved getContent 动画
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=aee43e0b-c877-4b23-9104-a1c23d9b6992:221 Bilibili Evolved Object
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=aee43e0b-c877-4b23-9104-a1c23d9b6992:221 Bilibili Evolved 简化首页 null
```

**Comment by the1812** [comment]
这是 b 站没更新, 现在应该是冬了
