### ISSUE TITLE
暴力猴安装失败，提示加载脚本依赖发生错误

### ISSUE THREAD

**Issue by Tungwerl** [the1812/Bilibili-Evolved#388]
<img width="403" alt="屏幕快照 2020-03-21 下午12 04 15" src="https://user-images.githubusercontent.com/32892836/77218970-1d462e00-6b6c-11ea-946f-232e4df01876.png">

安装其他脚本正常，截图所示

**Comment by the1812** [comment]
脚本的依赖如下, 请检查是哪个无法加载
https://code.jquery.com/jquery-3.4.0.min.js
https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js
https://cdn.bootcss.com/jszip/3.1.5/jszip.min.js
https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js
https://unpkg.com/vuex@3.1.2/dist/vuex.js

**Comment by Tungwerl** [comment]
> 脚本的依赖如下, 请检查是哪个无法加载
> https://code.jquery.com/jquery-3.4.0.min.js
> https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js
> https://cdn.bootcss.com/jszip/3.1.5/jszip.min.js
> https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js
> https://unpkg.com/vuex@3.1.2/dist/vuex.js

每个链接都能打开

**Comment by the1812** [comment]
重新安装试试看?(可以换几个不同的安装源试) 我测试了一下没有问题
![image](https://user-images.githubusercontent.com/26504152/77221666-a702f500-6b86-11ea-939c-45b337dcc6fc.png)

**Comment by mengxinme** [comment]
> > 脚本的依赖如下，请检查是无法加载
> > [https://code.jquery.com/jquery-3.4.0.min.js ](https://code.jquery.com/jquery-3.4.0.min.js)
> > [https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash。 min.js ](https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js)
> > [https://cdn.bootcss.com/jszip/3.1.5/jszip.min.js ](https://cdn.bootcss.com/jszip/3.1.5/jszip.min.js)
> > [https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js ](https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js)
> > [https：/ /unpkg.com/vuex@3.1.2/dist/vuex.js](https://unpkg.com/vuex@3.1.2/dist/vuex.js)
> 
> 每个链接完全打开

我无法加载https://code.jquery.com/jquery-3.4.0.min.js该怎么办

**Comment by the1812** [comment]
@mengxinme 
反正都得更新到新版的, 直接装新版就行了
https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@master/bilibili-evolved.user.js
