### ISSUE TITLE
urlInclude的逻辑是怎样的？

### ISSUE THREAD

**Issue by swhoro** [the1812/Bilibili-Evolved#3883]
### 对应功能

urlInclude未按预期执行

### 问题描述

假如我这么写：
```js
urlInclude: [/^https:\/\/space\.bilibili\.com\/\d*\/channel\/seriesdetail\?sid=\d*/],
```
那么脚本不会在以下页面运行：https://space.bilibili.com/1567748478/channel/seriesdetail?sid=358497
但是实际上进行正则检测会返回true：
```js
/^https:\/\/space\.bilibili\.com\/\d*\/channel\/seriesdetail\?sid=\d*/.test("https://space.bilibili.com/1567748478/channel/seriesdetail?sid=358497")
true
```

### 脚本版本

Bilibili Evolved (Local) v2.5.2-24-g19330b8cb

### 浏览器版本

edge 108.0.1462.54

### 播放器版本

无需

### 播放策略

默认

### 错误信息

```shell
见下图
```

### 附加截图

未正常运行，不打印信息：
![image](https://user-images.githubusercontent.com/34229589/208290148-da52bd71-f003-4e98-a733-e071754f235e.png)
去掉urlInclude，正常运行，打印相关信息：
![image](https://user-images.githubusercontent.com/34229589/208290218-1ed92b1d-a04d-4c05-b920-c942b4aa6028.png)

**Comment by the1812** [comment]
查询参数不算 (`?` 以及后面的)
