### ISSUE TITLE
在Chrome 4.18.1油猴打开bilibili evolved完全无法使用，b站首页搜索框都不见了，左侧的悬浮窗也没有

### ISSUE THREAD

**Issue by linmulinyy** [the1812/Bilibili-Evolved#3888]
### 对应功能

.

### 问题描述

无

### 脚本版本

2.5.2

### 浏览器版本

Chrome 版本 108.0.5359.125（正式版本） （64 位）

### 播放器版本

3.252

### 播放策略

AVC

### 错误信息

```shell
搜索bilibili evolved是啥都没有
```

### 附加截图

![image](https://user-images.githubusercontent.com/121184809/208955335-61325306-8436-47df-9d1a-01f03563d2a8.png)

**Comment by jyszzz** [comment]
一模一样。。。我的也是

**Comment by f59375543** [comment]
我也遇到了这个问题，Chrome102和Chrome108都遇到了，jsDelivr版加载半天加载不出来，必须不停刷新

**Comment by MirionQs** [comment]
你测试下fq后能否正常加载，确定是不是cdn的问题
再看眼脚本管理器的存储项，确定是否有乱码的问题

**Comment by f59375543** [comment]
> 你测试下fq后能否正常加载，确定是不是cdn的问题 再看眼脚本管理器的存储项，确定是否有乱码的问题

已全局代理，还是有加载卡顿的情况

**Comment by YiJun0706** [comment]
我也遇到类似问题，检查发现 the1812.github.io 下的样式无法加载，将其加入代理规则，解决了

**Comment by bacon8474** [comment]
遇到同样的情况，只能暂时用别的脚本顶着

**Comment by Talk1scheap** [comment]
> 我也遇到类似问题，检查发现 the1812.github.io 下的样式无法加载，将其加入代理规则，解决了

用你的方法解决了 感谢

**Comment by linmulinyy** [comment]
> 遇到相同的情况，只能暂时用别的脚本顶着

我换了其他版本油猴插件就可以用了

**Comment by actforjason** [comment]
> > 遇到相同的情况，只能暂时用别的脚本顶着
> 
> 我换了其他版本油猴插件就可以用了

不管用

**Comment by 9563067** [comment]
+1，我是用win10的时候，正常使用，但重装win11后，再在edge使用这脚本，很多东西都不显示，如图
![图片](https://github.com/user-attachments/assets/c26f29f2-d9e3-4e26-ba56-6d1269c4ffb1)

**Comment by xyh90675-png** [comment]
我是这样解决这个问题的, 要打开tamper monkey的开发者模式, edge上的打开位置如图所示

<img width="604" height="651" alt="Image" src="https://github.com/user-attachments/assets/66e0c0a6-e8dc-40fb-b81f-8880d0452e82" />

<img width="810" height="439" alt="Image" src="https://github.com/user-attachments/assets/24a413ba-c97b-4d6a-b7f4-290e810effe4" />

我使用的edge版本  Version 143.0.3650.80 (Official build) (arm64)

操作系统 macos 26

tamper monkey版本 5.4.0

bilibili-envolved版本 2.10.5
