### ISSUE TITLE
删除广告 功能会把活动视频的横幅也删了。。

### ISSUE THREAD

**Issue by HIMQ** [the1812/Bilibili-Evolved#389]
投票按钮也莫得了，这个应该不算广告吧，最好可以不屏蔽（或者给个开关
位置在标签跟评论区之间
![image](https://user-images.githubusercontent.com/35751763/77241915-1d116580-6c34-11ea-882e-9eaeec8aa83a.png)

**Comment by the1812** [comment]
这里成活动横幅了吗.. 以前是随机广告来着
