### ISSUE TITLE
高分辨率图片不起作用了

### ISSUE THREAD

**Issue by Smobniar** [the1812/Bilibili-Evolved#3894]
### 对应功能

![截屏2022-12-27 下午9 31 17](https://user-images.githubusercontent.com/48118937/209933671-204ccb55-a58a-431b-95bc-c34747d70db9.jpg)

### 问题描述

![截屏2022-12-27 下午9 29 17](https://user-images.githubusercontent.com/48118937/209933693-aa05b65b-68e1-4fd0-b8a6-bb50a74b3f06.jpg)

### 脚本版本

v2.5.2-preview-56-ge5bb5742f

### 浏览器版本

Safari 16.2

### 播放器版本

3.25.5-e3a5739f

### 播放策略

默认

### 错误信息

```shell
无
```

**Comment by the1812** [comment]
图没传上来

**Comment by the1812** [comment]
这是在哪个页面里的

**Comment by Smobniar** [comment]
> 这是在哪个页面里的

是个人主页的投稿页面，动态页面会比较清晰
