### ISSUE TITLE
番剧评论区无法正常显示

### ISSUE THREAD

**Issue by theblueandblackcrow** [the1812/Bilibili-Evolved#3901]
### 对应功能

不确定是哪一个脚本功能

### 问题描述

在打开任意一部番剧后，观看评论区无法正常显示
补充：电影也不行

### 脚本版本

v2.6.0

### 浏览器版本

浏览器版本108.0.5359.125

### 播放器版本

版本3.25.10

### 播放策略

HEVC

### 错误信息

```Shell
图里有错误样式，不知道其他人有没有和我同样的问题
```

### 附加截图

![image](https://user-images.githubusercontent.com/96634006/210177182-16251e88-44cc-4ec5-8d2d-005ca6d43e54.png)
![image](https://user-images.githubusercontent.com/96634006/210177404-53560e4f-5be2-4f3b-bc74-b771039dd5b4.png)

**Comment by Ethkuil** [comment]
我这边正常（也是v2.6.0）。Chrome Version 107.0.5304.107.

我安装的组件列表：

![image](https://user-images.githubusercontent.com/77615248/210186485-47b1fa2f-fe4b-439d-b8b7-7fe4250cb59d.png)
![image](https://user-images.githubusercontent.com/77615248/210186502-bd90c823-843b-4592-8125-cffb460aaac1.png)
![image](https://user-images.githubusercontent.com/77615248/210186514-3e9e7fab-60b3-4337-822c-a6ae2a2c8b0e.png)

可考虑试试控制变量，看看是哪个组件导致了问题？

**Comment by theblueandblackcrow** [comment]
> 我这边正常（也是v2.6.0）。Chrome Version 107.0.5304.107.
> 
> 我安装的组件列表（供排除法使用）：
> 
> ![image](https://user-images.githubusercontent.com/77615248/210186485-47b1fa2f-fe4b-439d-b8b7-7fe4250cb59d.png) ![image](https://user-images.githubusercontent.com/77615248/210186502-bd90c823-843b-4592-8125-cffb460aaac1.png) ![image](https://user-images.githubusercontent.com/77615248/210186514-3e9e7fab-60b3-4337-822c-a6ae2a2c8b0e.png)
> 
> 可考虑试试控制变量，看看是哪个组件导致了问题？

不显示评论的同时，还显示这个错误，显示3遍，挺奇怪的
utils.playerReady 失败

**Comment by theblueandblackcrow** [comment]
破案了，不是本脚本的问题
是其他脚本的问题
