### ISSUE TITLE
“网址参数清理”对直播网址不生效

### ISSUE THREAD

**Issue by AzusaHana** [the1812/Bilibili-Evolved#3905]
### 对应功能

网址参数清理

### 问题描述

通过用户空间点开的直播间会带参数
![image](https://user-images.githubusercontent.com/100906636/210231522-e31efcc0-5ba3-4794-bf8d-af5927a0a499.png)
网址参数清理不生效
https://live.bilibili.com/6?is_room_feed=1?spm_id_from=333.999.space_home.left_live.click

### 脚本版本

v2.6.0-preview-52-g3397e56dc

### 浏览器版本

Chrome 107.0.5304.107

### 播放器版本

无

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved 网址参数清理 https://live.bilibili.com/6?broadcast_type=0&is_room_feed=1?spm_id_from=333.999.space_home.left_live.click https://live.bilibili.com/6?is_room_feed=1?spm_id_from=333.999.space_home.left_live.click
```

**Comment by the1812** [comment]
这是 b 站的问题, 网址参数带了两个问号, 变成了 `is_room_feed` = `1?spm_id_from=333.999.space_home.left_live.click`
![image](https://user-images.githubusercontent.com/26504152/210233669-8051c28c-6e63-4718-9f47-2e20841136aa.png)
