### ISSUE TITLE
BV 号兼容问题集中反馈

### ISSUE THREAD

**Issue by ZeroAurora** [the1812/Bilibili-Evolved#391]
**关于哪一项功能**
Bilibili 近期开始推广最新的视频编号格式 bv
bv号前缀为BV/bv，后跟10位字符串，内含有随机生成大小写字母（敏感）和数字。
目前个人发现的影响范围是手动输入链接下载功能不可用。

**期望的效果**
当然是尽快兼容啊o(≧口≦)o

**脚本版本**
1.10.6 正式版

**Comment by the1812** [comment]
bv号这东西 影响范围现在还很难说
这楼就用作bv号相关问题集中反馈吧

**Comment by the1812** [comment]
- BV号页面下无效:
  - 下载视频 - 批量导出
  - 外置稍后再看
- 稍后再看重定向失效

**Comment by JimMoen** [comment]
关于av号和BV号的兼容
任意视频资源在浏览器打开视频页面，F12打开开发者工具。
Console中输入“aid”可以得到纯数字av号；输入“bvid”可以得到带有大写“BV”的BV号。
在目前未更新的情况下可以使用该方法临时获取av号和BV号。

**Comment by inuo2008** [comment]
贴吧出了bv转av 的小工具挺好用，

**Comment by the1812** [comment]
转换功能将会整合到搜索栏中
<img width="400" src="https://user-images.githubusercontent.com/26504152/77314268-49b2a380-6d40-11ea-88f5-2acc5a539c52.png">

**Comment by JimMoen** [comment]
BV号视频中，“外置稍后再看”仍然无效。（已从github源更新到1.10.12版本）

**Comment by the1812** [comment]
> BV号视频中，“外置稍后再看”仍然无效。（已从github源更新到1.10.12版本）

控制台(<kbd>Ctrl+Shift+I</kbd>)有报错吗? 没有的话看看运行这段代码得到什么
```js
bilibiliEvolved.Resource.all.outerWatchlater.text.toString()
```

**Comment by rennemaki** [comment]
"(t,i)=>{(async()=>{if(!document.URL.includes("//www.bilibili.com/video/av")){return}await SpinQuery.condition(()=>dq(".video-toolbar .ops .collect"),t=>{return t!==null&&t.innerText!=="--"});const t=dq(".video-toolbar .ops .collect");if(!t){return}t.insertAdjacentHTML("afterend",`\n<span title='稍后再看' class='watchlater' :class="{on: isInWatchlater}" @click="toggle()">\n<i class='mdi mdi-timetable'></i>\n      稍后再看\n<div class='tip' :class="{show: tipShowing}">{{tipText}}</div>\n</span>\n`);const i=dq(".ops .watchlater");const e=dq(".ops .watchlater .tip");if(!i||!e){return}const a=new Vue({el:i,store:store,data:{aid:unsafeWindow.aid,tipText:"",tipShowing:false,tipHandle:0},computed:{...Vuex.mapState(["watchlaterList"]),isInWatchlater(){return this.watchlaterList.includes(parseInt(this.aid))}},methods:{...Vuex.mapActions(["toggleWatchlater"]),showTip(t){this.tipText=t;this.tipShowing=true;if(this.tipHandle){clearTimeout(this.tipHandle)}this.tipHandle=setTimeout(()=>{this.tipShowing=false},2e3)},async toggle(){await this.toggleWatchlater(this.aid);this.showTip(this.isInWatchlater?"已添加至稍后再看":"已从稍后再看移除")}}});Observer.videoChange(()=>{a.aid=unsafeWindow.aid})})()}"

> > BV号视频中，“外置稍后再看”仍然无效。（已从github源更新到1.10.12版本）
> 
> 控制台(Ctrl+Shift+I)有报错吗? 没有的话看看运行这段代码得到什么
> 
> ```js
> bilibiliEvolved.Resource.all.outerWatchlater.text.toString()
> ```

**Comment by the1812** [comment]
应该是热更新的机制bug导致的, 更新包是jsDelivr那边的, 需要1天后更新
换离线版试试看?

**Comment by rennemaki** [comment]
> 应该是热更新的机制bug导致的, 更新包是jsDelivr那边的, 需要1天后更新
> 换离线版试试看?

经过多次尝试数个版本与数个下载点这个“外置稍后再看”的issue依然存在，如果您确定是热更新机制的bug也许可能大概需要检查一下是否更新错了文件

**Comment by the1812** [comment]
文件内容确认过没问题了, `www.bilibili.com/video/`那里后面没有限定`av`.
您确定是从GitHub源安装的`v1.10.12`(离线版版本大于等于`616.19`)吗? (另外两个安装源现在肯定还是`v1.10.6`的文件)
![image](https://user-images.githubusercontent.com/26504152/77334817-43ccba80-6d60-11ea-9d33-c139686b7401.png)

**Comment by rennemaki** [comment]
> 文件内容确认过没问题了, `www.bilibili.com/video/`那里后面没有限定`av`.
> 您确定是从GitHub源安装的`v1.10.12`(离线版版本大于等于`616.19`)吗? (另外两个安装源现在肯定还是`v1.10.6`的文件)
> ![image](https://user-images.githubusercontent.com/26504152/77334817-43ccba80-6d60-11ea-9d33-c139686b7401.png)

我想我找到问题了
我很确定我是点Github源进行安装的
然后这里赫然写着
// @version      615.78

**Comment by the1812** [comment]
那看来GitHub也不是所有文件同步更新的...

**Comment by rennemaki** [comment]
![image](https://user-images.githubusercontent.com/11786799/77336638-c5bde300-6d62-11ea-885b-26ee44450987.png)

![image](https://user-images.githubusercontent.com/11786799/77336970-3b29b380-6d63-11ea-9b41-365098b709d4.png)

呃我需要补充说明一下，或许您需要把您主页上的安装目录下的链接改成github源
很明显我应该是搞混了这个没进行标注来源的下载按钮
其实现在只有GitHub更新到了616.33而我之前在尝试不同源的时候错误的把下载目录下的那个误当成GitHub源了。

**Comment by JimMoen** [comment]
> > BV号视频中，“外置稍后再看”仍然无效。（已从github源更新到1.10.12版本）
> 
> 控制台(Ctrl+Shift+I)有报错吗? 没有的话看看运行这段代码得到什么
> 
> ```js
> bilibiliEvolved.Resource.all.outerWatchlater.text.toString()
> ```

- # ***修复：***

在“已安装脚本”页面中删除混乱的1.10.12版。然后点击该链接安装1.10.12版。
### 如图： ![screenshot1](https://user-images.githubusercontent.com/32241529/77336824-0cabd880-6d63-11ea-9d98-305cb819ad08.png)



如果发现你点开的安装链接为1.10.6版，不论现在安装的是什么版本，也请直接删除脚本并重新安装


- # ***以下为测试过程：***

安装过程：
已安装1.10.6版，直接点击项目主页中的**“备用安装源，Github正式版”**升级到1.10.12版。
### 如图： ![screenshot2](https://user-images.githubusercontent.com/32241529/77336824-0cabd880-6d63-11ea-9d98-305cb819ad08.png)
之后在查看项目时再次点击项目主页中的“安装”，发现为1.10.6版本后选择**取消**。
### 如图：![screenshot3](https://user-images.githubusercontent.com/32241529/77336918-26e5b680-6d63-11ea-8b7c-be9cff411907.png)

此时在“已安装脚本”页面查看版本为1.10.12

之后经过多次刷新，“外置稍后观看”仍然无效，浏览器清除cookie仍然无效。
但在“附加功能”中点击清除缓存，然后立刻刷新页面。按钮出现。再次刷新后按钮消失。（重启浏览器或打开新视频页面按钮也不出现，必须清除缓存才能出现）
**按钮失效时执行**
```js
bilibiliEvolved.Resource.all.outerWatchlater.text.toString()
```
结果含有如下内容
_startsWith("https://www.bilibili.com/video/av")_
**按钮有效时**输出含有内容为
_startsWith("https://www.bilibili.com/video/")_

**注：以上过程可多次复现，怀疑为Tempermonky插件的缓存机制导致**

**Comment by the1812** [comment]
@JimMoen 您这个就是上面所讨论的热更新bug, 清除缓存/首次安装时使用的是脚本内部的代码, 但是非离线版运行后会检查功能的热更新, 这里的更新包版本检查有问题, 于是直接把`v1.10.6`的包装上了, 然后`外置稍后再看`再次失效.

**Comment by JimMoen** [comment]
> @JimMoen 您这个就是上面所讨论的热更新bug, 清除缓存/首次安装时使用的是脚本内部的代码, 但是非离线版运行后会检查功能的热更新, 这里的更新包版本检查有问题, 于是直接把`v1.10.6`的包装上了, 然后`外置稍后再看`再次失效.

但是出现这个bug的时候是可以看到“附加功能”中的av号、BV号的。也就是说代码里是有1.10.12中的功能实现的。或许是热更新的安装的1.10.6代码把已有的1.10.12的代码覆盖了？
（我对Tempermonky的更新机制没有了解，只是猜测）
所以应该只是插件本身的bug，现在1.10.12的脚本没问题就好。

**Comment by the1812** [comment]
> > @JimMoen 您这个就是上面所讨论的热更新bug, 清除缓存/首次安装时使用的是脚本内部的代码, 但是非离线版运行后会检查功能的热更新, 这里的更新包版本检查有问题, 于是直接把`v1.10.6`的包装上了, 然后`外置稍后再看`再次失效.
> 
> 但是出现这个bug的时候是可以看到“附加功能”中的av号、BV号的。也就是说代码里是有1.10.12中的功能实现的。或许是热更新的安装的1.10.6代码把已有的1.10.12的代码覆盖了？
> （我对Tempermonky的更新机制没有了解，只是猜测）
> 所以应该只是插件本身的bug，现在1.10.12的脚本没问题就好。

跟Tempermonkey没关系, 这个更新也是我写的. 附加功能中的显示av/bv号和外置稍后再看是互相独立的功能, `v1.10.6`里没有前者所以不会覆盖

**Comment by the1812** [comment]
@rennemaki 那里曾经是Github源, 但毕竟是国外服务器, 经常会下载不完整/下载无响应, 包括我自己也无法用GitHub源更新, 所以换成了更新较慢但速度稳定的jsDelivr

**Comment by ZeroAurora** [comment]
总感觉跑题了2333333

**Comment by JimMoen** [comment]
> 总感觉跑题了2333333

毕竟谁也没有想到有一天video/av会变成video/BV
（狗头

**Comment by the1812** [comment]
> 总感觉跑题了2333333

为了兼容BV号而发布的更新里 发现了bug (强行扣题

**Comment by JimMoen** [comment]
> > 总感觉跑题了2333333
> 
> 为了兼容BV号而发布的更新里 发现了bug (强行扣题

热更新的bug感觉还是很迷，刚刚又想了一下。
已有1.10.6，更新到1.10.12会触发问题。
纯净安装的1.10.12却不会触发？
所以还是有版本信息存储在了Tempermonky中，（版本号？）更新后的脚本检查到TemperMonky提供的版本号和现有版本号不匹配然后执行了热更新？

**Comment by the1812** [comment]
@JimMoen  不匹配不会更新, 是一开始从GitHub取版本得到`1.10.12`, 与当前脚本一致, 然后从jsDelivr下载更新包`1.10.6`(更新包这里没检查), 直接就装上了
你发测试过程那会我已经又改了`1.10.12`的热更新bug, 与此同时jsDelivr的更新包也更新为`1.10.12`了, 于是就正常了

**Comment by JimMoen** [comment]
> @JimMoen 不匹配不会更新, 是一开始从GitHub取版本得到`1.10.12`, 与当前脚本一致, 然后从jsDelivr下载更新包`1.10.6`(更新包这里没检查), 直接就装上了
> 你发测试过程那会我已经又改了`1.10.12`的热更新bug, 与此同时jsDelivr的更新包也更新为`1.10.12`了, 于是就正常了

我两分钟前重新装了1.10.12，又给我热更新挂了。还是一样的问题。等明天各处同步吧233333

**Comment by u2shana** [comment]
现在通过顶栏稍后再看自动弹出的列表点进去的视频会提示找不到视频，此时url是watchlater/#/avXXXXX

如果点进去稍后再看在里面点开视频的话是watchlater/#/BVXXXXX，可以正常播放

**Comment by the1812** [comment]
哦豁 最先取消av的地方居然是这里

**Comment by the1812** [comment]
> > @JimMoen 不匹配不会更新, 是一开始从GitHub取版本得到`1.10.12`, 与当前脚本一致, 然后从jsDelivr下载更新包`1.10.6`(更新包这里没检查), 直接就装上了
> > 你发测试过程那会我已经又改了`1.10.12`的热更新bug, 与此同时jsDelivr的更新包也更新为`1.10.12`了, 于是就正常了
> 
> 我两分钟前重新装了1.10.12，又给我热更新挂了。还是一样的问题。等明天各处同步吧233333

昨晚又试了下发现Tempermonkey似乎是有缓存的, [更新包](https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@master/min/bundle.zip)在浏览器直接打开得到的是`1.10.12`的包, 但是脚本里用Tempermonkey的API去下得到的却还是之前的`1.10.6`

**Comment by Itzamana** [comment]
说起来既然以github为主了，那么从github安装的脚本也从github更新不也挺好嘛…

**Comment by the1812** [comment]
就是因为很难从Github更新啊, 在我换成jsDelivr之前, 经常有人出现脚本下载不完整的情况, 要反复重装刷出一个下载完整的文件. 我家里的WiFi, 4G热点去下载速度不到1KB/s, 只有校园网偶尔能下载下来.
其实现在GreasyFork那边还是这样的情况, 因为默认只能用GreasyFork的源, 那边三天两头就有下载不完整的来问为什么装了后b站没有任何变化
![image](https://user-images.githubusercontent.com/26504152/77384194-b620b780-6dbf-11ea-897d-fed6b80358f4.png)

**Comment by Itzamana** [comment]
> 就是因为很难从Github更新啊, 在我换成jsDelivr之前, 经常有人出现脚本下载不完整的情况, 要反复重装刷出一个下载完整的文件. 我家里的WiFi, 4G热点去下载速度不到1KB/s, 只有校园网偶尔能下载下来.
> 其实现在GreasyFork那边还是这样的情况, 因为默认只能用GreasyFork的源, 那边三天两头就有下载不完整的来问为什么装了后b站没有任何变化


感谢回复，不过我的意思是，从其他源安装的脚本还是从jsDelivr更新，但是从github安装的脚本能直接从github更新就好，毕竟主动选择从github安装脚本，基本意味着自己能解决这边的下载速度问题…

**Comment by the1812** [comment]
那倒也行, 我可以加个选项切换两个源

**Comment by JimMoen** [comment]
@the1812 目前BV号视频的“稍后再看按钮外置”功能已可以正常使用。

**Comment by oscarwty** [comment]
去除网址参数功能，目前对BV视频是无效的

**Comment by wangzhehan84** [comment]
用批量导出采取aria2 结果获取的都是分段视频

**Comment by ZeroAurora** [comment]
> 
> 
> 就是因为很难从Github更新啊, 在我换成jsDelivr之前, 经常有人出现脚本下载不完整的情况, 要反复重装刷出一个下载完整的文件. 我家里的WiFi, 4G热点去下载速度不到1KB/s, 只有校园网偶尔能下载下来.
> 其实现在GreasyFork那边还是这样的情况, 因为默认只能用GreasyFork的源, 那边三天两头就有下载不完整的来问为什么装了后b站没有任何变化
> ![image](https://user-images.githubusercontent.com/26504152/77384194-b620b780-6dbf-11ea-897d-fed6b80358f4.png)

（顺便一提今天 GitHub Pages 和 Girhub Raw 不是被中间人攻击了还是什么来着（（

**Comment by wanguano** [comment]
请问如何解决,稍后观看列表里面的视频链接是: javascript:;

**Comment by the1812** [comment]
> 请问如何解决,稍后观看列表里面的视频链接是: javascript:;

那个还没适配, 可以先开`稍后再看重定向`凑合下

**Comment by wanguano** [comment]
> > 请问如何解决,稍后观看列表里面的视频链接是: javascript:;
> 
> 那个还没适配, 可以先开`稍后再看重定向`凑合下

好的
