### ISSUE TITLE
弹幕空降功能失效了

### ISSUE THREAD

**Issue by FShH1997** [the1812/Bilibili-Evolved#3913]
### 对应功能

Commit: 5b8d9acf1
内部名称: danmakuAirborne

### 问题描述

视频链接：https://www.bilibili.com/video/BV1xR4y1U7Rw/?vd_source=c0f8ec9622685db9832957f7932185ae
时间：1：39
弹幕内容：“空降01:46”
弹幕样式：顶部、黄色、正常大小
问题描述：这条弹幕没有下划线，也无法点击

### 脚本版本

v2.6.0-18-g702d02d6c

### 浏览器版本

Microsoft Edge 版本 108.0.1462.54 (正式版本) (64 位)

### 播放器版本

3.25.5-e3a5739f

### 播放策略

默认

### 错误信息

```Shell
没有bilibili evolved相关的内容，准确说是几乎啥都没有

附加截图传不上来，总之就是只有两个bilibili的logo样式，下面没有别的消息了
```

**Comment by Geeyun-JY3** [comment]
#3187 有相关反馈：<https://github.com/the1812/Bilibili-Evolved/issues/3187#issuecomment-1090302039>、<https://github.com/the1812/Bilibili-Evolved/issues/3187#issuecomment-1218470293>
