### ISSUE TITLE
适配新版稍后再看页面

### ISSUE THREAD

**Issue by sky-279** [the1812/Bilibili-Evolved#3916]
### 对应功能

几乎所有功能失效

### 问题描述

问题界面包括但不限于稍后在看页面，播放收藏夹所有视频页面等包含新版视频列表的页面
症状是侧边功能选项卡空空如也，几乎所有功能失效
![image](https://user-images.githubusercontent.com/60536042/210762889-59e146de-f474-4323-805f-72257a1d7ed5.png)

### 脚本版本

v2.6.0-18-g702d02d6c

### 浏览器版本

Kernel: 109.0.5414.62（正式版本） （64 位）

### 播放器版本

3.25.11

### 播放策略

默认

### 错误信息

```Shell
DevTools 无法加载来源映射：无法加载 https://s1.hdslb.com/bfs/static/jinkela/risk-captcha-sdk/CaptchaLoader.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载来源映射：无法加载 https://s1.hdslb.com/bfs/static/jinkela/playlist-video/playlist-video.42f59f93e4c2f886b8fe83f21f20202703742b7b.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载来源映射：无法加载 https://s1.hdslb.com/bfs/static/jinkela/playlist-video/1.playlist-video.42f59f93e4c2f886b8fe83f21f20202703742b7b.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载来源映射：无法加载 https://s1.hdslb.com/bfs/static/jinkela/playlist-video/css/playlist-video.0.42f59f93e4c2f886b8fe83f21f20202703742b7b.css.map 的内容：HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载来源映射：无法加载 https://s1.hdslb.com/bfs/static/jinkela/playlist-video/css/playlist-video.1.42f59f93e4c2f886b8fe83f21f20202703742b7b.css.map 的内容：HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by the1812** [comment]
改成啥了, 我咋还是 medialist

**Comment by sky-279** [comment]
右上角可选顺序/倒序播放   列表循环/随机播放  这种  删除按钮从缩略图右下改到了标题尾部

**Comment by Geeyun-JY3** [comment]
> 改成啥了, 我咋还是 medialist

我这边收藏夹打开的 URL 都是 `list/ml*******` 了（稍后播放就是 `list/watchlater`）

收藏夹的 `播放全部视频` 按钮的 URL 倒好像都还没改

**Comment by zeroabc** [comment]
一样，稍后再看的播放推送了新版本。我最需要的是播放自动网页全屏和播放速率适用都没有生效了

**Comment by birthfromfire** [comment]
确实，最需要的记忆倍速没法用了  QAQ

**Comment by nyano** [comment]
改样式了好烦。。。大部分功能全不能用了

**Comment by nyano** [comment]
https://www.bilibili.com/medialist/play/watchlater/BV****** 被改为list/watchlater?oid=******&bvid=BV******&p=1 今天强制跳转。 明明列表循环 但是当前的播放完就是不跳转~页面中除了按钮还在，其他功能几乎全部失效了

**Comment by sky-279** [comment]
> https://www.bilibili.com/medialist/play/watchlater/BV****** 被改为list/watchlater?oid=******&bvid=BV******&p=1 今天强制跳转。 明明列表循环 但是当前的播放完就是不跳转~页面中除了按钮还在，其他功能几乎全部失效了

不跳转在更多播放中设置就行。但是对于多p视频有bug，点了删除还是会播放多p的2p不会播放列表的下一个视频。另外列表点了删除有概率没反应。

**Comment by nyano** [comment]
呜呜呜 今天极简首页也失效了。。另外一个建议。极简首页里的动态能不能加个视频上传时间 或者有个区分哪些是看过的。关注的太多了。。不知道从哪截止是看过的

**Comment by timongh** [comment]
B 站的播放列表现在似乎就两种（我已经发现的）：

- 列表
  - 没有返回旧版按钮
  - 网址是：`www.bilibili.com/list/...`
  - 有顺序播放和倒序播放按钮
  - 有视频缩略图
  - 稍后再看的播放全部、“UP主主页-投搞-播放全部”、“UP主主页-合集和列表-播放全部（不带‘合集·’字样)”打开的都是这种
  - 稍后再看的播放全部中有删除按钮
  - 例子：`https://www.bilibili.com/list/5260378`
- 合集
  - 有返回旧版按钮
  - 网址是：`www.bilibili.com/video/...`
  - 没有顺序播放和倒序播放按钮，不能将视频从播放列表中删除
  - 只有“UP主主页-合集和列表-播放全部（带‘合集·’字样)”打开的才是这种
  - 如果正在播放的视频属于某个合集，那么视频页面会以播放列表的形式自动展示该视频所属的合集
  - 合集又分两类
    - 无分组
      - 无视频缩略图
      - 例子：https://www.bilibili.com/video/BV18J411B7QA
    - 有分组
      - 有视频缩略图
      - 例子：https://www.bilibili.com/video/BV1JN4y1w7wY

附一个 Up 的“个人主页-合集和列表”，可以从这里同时找到“合集”和“列表”：https://space.bilibili.com/8047632/channel/series

**Comment by ddqlsep** [comment]
传统连播没了好伤啊
