### ISSUE TITLE
新版动态页下功能失效

### ISSUE THREAD

**Issue by sunfkny** [the1812/Bilibili-Evolved#3917]
### 对应功能

直播信息扩充
Commit: 5b8d9acf1
内部名称: extendFeedsLive

### 问题描述

切换到新版动态（绿色背景），打开"直播信息扩充"组件，点击扩充的直播间（10个之后的直播间），无法打开

问题在这

https://github.com/the1812/Bilibili-Evolved/blob/b9a1a89d88351f394f66ff8f973c3ba6f55464e0/registry/lib/components/feeds/extend-live/index.ts#L47-L51

旧版动态是 `.bili-dyn-live-users__item`
新版动态是 `.bili-dyn-live-users__container > .bili-dyn-live-users__item-container > .bili-dyn-live-users__item`
所以addEventListener没加上

### 脚本版本

Bilibili Evolved (Preview) b9a1a89 (2.6.0)

### 浏览器版本

Chrome 已是最新版本 版本 108.0.5359.125（正式版本） （64 位）

### 播放器版本

3.25.11-d04ab121

### 播放策略

默认

### 错误信息

```Shell
无
```

**Comment by the1812** [comment]
这也有新版? 在哪里切换的

**Comment by sunfkny** [comment]
是某天自动切换的，可以手动回旧版，切换时改了个cookie `go-back-dyn=1`
于是搜索`"go-back-dyn"` 找到了个参数，好像只需要访问 https://t.bilibili.com/?w=3 就能切换新版
```
handleBack: function() {
    j.set("go-back-dyn", "1");
    var t = location.href.replace("?w=3", "");
    location.href = t
},
```

**Comment by the1812** [comment]
哦豁, 那可不止这一个功能遭殃了

**Comment by Tinhone** [comment]
做都没做好啊，评论区甚至是上一个版本，离谱

**Comment by timongh** [comment]
我今天被灰度到了

小分辨率：
<img width="960" alt="little" src="https://user-images.githubusercontent.com/46739861/220607282-36c5d6b7-7dbe-45b3-93c7-265afa4964bd.png">

大分辨率
<img width="960" alt="big" src="https://user-images.githubusercontent.com/46739861/220607325-8861270a-092a-44b4-aab9-f5a47f289916.png">

**Comment by the1812** [comment]
其他一些失效的补充, 来自 #4041
![image](https://user-images.githubusercontent.com/26504152/222948194-12a71136-dd32-4ffc-9e54-1acfe7939e59.png)

**Comment by u2shana** [comment]
刚更新了2.7.1,新版动态,开启直播信息栏扩充后面板直接消失了
![image](https://user-images.githubusercontent.com/14146754/234203612-f2731cc6-8a3e-4cdd-a92c-0072c4ec58ea.png)

**Comment by the1812** [comment]
应该是支持的啊
![image](https://user-images.githubusercontent.com/26504152/234439525-5b3eca02-d55a-44e4-b912-1c2ed11011e5.png)

**Comment by u2shana** [comment]
> 应该是支持的啊 ![image](https://user-images.githubusercontent.com/26504152/234439525-5b3eca02-d55a-44e4-b912-1c2ed11011e5.png)

那就怪了,我试了很多次都有问题,装回master分支的插件又正常的

**Comment by the1812** [comment]
b 站这个新版的动态菜单, 连垂直居中都不会写...
<img width="200" src="https://github.com/the1812/Bilibili-Evolved/assets/26504152/651d8eaa-ff76-4bde-b0b8-c2e7b679d79c">
