### ISSUE TITLE
夜间模式反应慢

### ISSUE THREAD

**Issue by fengmingli107** [the1812/Bilibili-Evolved#3919]
### 对应功能

Commit: 3397e56dc

### 问题描述

打开夜间模式跟随系统设置下，首次进入bilibili页面，夜间模式不会立刻切换，而是等待约1分钟后自动切换，哪怕我在“通用设置”的“功能加载模式”中选择“同时”也不会自动切换。

### 脚本版本

v2.6.0-33-gb03cdc725

### 浏览器版本

Microsoft Edge 版本 108.0.1462.76 (正式版本) (64 位)

### 播放器版本

HTML5播放器 V3.25.5

### 播放策略

默认

### 错误信息

```Shell
截图在附件
```

### 附加截图

![image](https://user-images.githubusercontent.com/107227092/211128840-12b614df-1ea0-4560-bfae-76857768c338.png)
![Snipaste_2023-01-07_11-12-06](https://user-images.githubusercontent.com/107227092/211128852-35b90f53-3859-4689-8eab-1cc7ec8de485.png)
![image](https://user-images.githubusercontent.com/107227092/211128884-28324e87-54ea-41a1-be0c-bfabd510ea41.png)

**Comment by the1812** [comment]
可能是资源文件卡着了 (https://fastly.jsdelivr.net/gh/Templarian/MaterialDesign-Webfont@5.3.45/css/materialdesignicons.min.css), 检查下速度

**Comment by fengmingli107** [comment]
> 可能是资源文件卡着了 (https://fastly.jsdelivr.net/gh/Templarian/MaterialDesign-Webfont@5.3.45/css/materialdesignicons.min.css), 检查下速度

我尝试关闭了其他插件，问题依然存在，这个网址要怎么检查？我需要做什么呢？

**Comment by the1812** [comment]
检查下是不是打开得很慢

**Comment by lovelyCARDINAL** [comment]
jsdelivr访问速度的问题吧...换个（海外）网络环境
这个issue可以直接关闭吧
