### ISSUE TITLE
外置稍后再看无效没有按钮了

### ISSUE THREAD

**Issue by wsdd977** [the1812/Bilibili-Evolved#392]
**关于哪一项功能**
外置稍后再看无效没有按钮了

**问题描述**
外置稍后再看无效没有按钮了所有视频都没有

**脚本版本**

1.10.6

**浏览器版本**

chrome78

**错误信息**

**附加截图**

**Comment by the1812** [comment]
参见 #391, 按钮不会在BV号页面出现
