### ISSUE TITLE
插件导致bilibili网页卡死

### ISSUE THREAD

**Issue by Ken14777** [the1812/Bilibili-Evolved#3921]
### 对应功能

不确定是哪个功能引起的

### 问题描述

为啥开了这个插件之后，一点个一个视频网页就会卡死，几次不同的视频都遇到这个问题，之前好久都没遇到过这个问题 。关闭插件之后可以正常跳转 播放

### 脚本版本

23年1月1号更新的版本

### 浏览器版本

edge 108.0.1462.76 (正式版本) (64 位)

### 播放器版本

更新历史3.25.12-4c877a76

### 播放策略

默认

### 错误信息

```Shell
1
```

**Comment by MoeGod277** [comment]
把工具選項裏的自動更新和更新通知這兩項關了 經過排查是這兩個插件導致的

**Comment by Ken14777** [comment]
没想到您这么快就回复了哈哈哈哈，我立马根据您说的尝试了一下，但是好像并没有改善我所碰到的问题，还是出现打开一个视频就卡死的情况，甚至整个edge浏览器都卡死。附上我改设置之后的截图





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月10日(星期二) 晚上10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 插件导致bilibili网页卡死 (Issue #3921)





 
把工具選項裏的自動更新和更新通知這兩項關了 經過排查是這兩個插件導致的

**Comment by the1812** [comment]
可能是 #3827

**Comment by Ken14777** [comment]
我焯，真的是 高分辨率图片这个功能，关了就Ok啦，感谢~~！！！&nbsp;只是不知道为啥会突然有一天就因为这个之前一只开着的功能出现问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Grant ***@***.***&gt;; 
发送时间: 2023年1月10日(星期二) 晚上10:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 插件导致bilibili网页卡死 (Issue #3921)





 
可能是 #3827
