### ISSUE TITLE
长按健盘右箭头加速失效

### ISSUE THREAD

**Issue by Francis-xsc** [the1812/Bilibili-Evolved#3922]
### 对应功能

快捷键扩展

### 问题描述

不装插件，默认长按箭头右箭头倍速播放
安装插件后失效

### 脚本版本

2.6.0

### 浏览器版本

108.0.5359.125

### 播放器版本

3.25.12-rc.

### 播放策略

默认

### 错误信息

```Shell
1
```

**Comment by Geeyun-JY3** [comment]
这不是 bug，这就是 `快捷键扩展` 在正常工作，这是因为 `快捷键扩展` 的 `前进` 动作对应的默认按键是 <kbd>→</kbd>，会覆盖掉破站原来的快捷键。

如果想保留破站默认的长按 <kbd>→</kbd> 倍速播放，将 `前进` 的 `自定义按键` 一栏留空即可。
