### ISSUE TITLE
Bilibili-Evolved完全失效

### ISSUE THREAD

**Issue by xiaoyunta** [the1812/Bilibili-Evolved#3923]
### 对应功能

*****

### 问题描述

·使用环境：Chrome+油猴
·在视频播放页左侧完全不显示任何功能模块，就跟没安装这个脚本一样

### 脚本版本

2.6.0

### 浏览器版本

Chrome 109.0.5414.87

### 播放器版本

HTML5播放器 V3.25.5

### 播放策略

默认

### 错误信息

```Shell
*****
```

### 附加截图

![image](https://user-images.githubusercontent.com/80113853/211707675-3dd5d9aa-3780-4830-9a29-e520e9599085.png)
![image](https://user-images.githubusercontent.com/80113853/211707923-03516040-474c-444c-9943-50ba9eeb02ac.png)

**Comment by PAUSEMAD** [comment]
+1，我还以为其他插件干扰，都关了，还是不行

**Comment by yqf23333** [comment]
我这边用倒是还行，就是图标全部消失了，只剩文字

**Comment by PAUSEMAD** [comment]
兄弟们是我智商下线了，我自己没有开启油猴脚本功能，现在正常了

**Comment by theblueandblackcrow** [comment]
> 兄弟们是我智商下线了，我自己没有开启油猴脚本功能，现在正常了

😅……

**Comment by TL2298** [comment]
楼主解决了吗，我也有这个问题，反正安装正式版还是预览版左侧都没有功能栏。

**Comment by szlysms** [comment]
那你要自己把这个issue给close一下啊。。。
