### ISSUE TITLE
稍后再看重定向失效

### ISSUE THREAD

**Issue by hoiyuyiu** [the1812/Bilibili-Evolved#3925]
### 对应功能

稍后再看重定向
Commit: 3397e56dc

### 问题描述

稍后再看页面似乎变成了新版页面而且无法返回，感觉是叔叔强制弄的，其实我也不经常用重定向功能，只是更偏好于旧版页面小一点的字体，于是尝试使用重定向，结果发现也失效了。

稍后再看页面的播放器版本为：3.25.14-788698c7
普通页面为：325.13-cad397b3

### 脚本版本

v2.6.0-preview-52-g3397e56dc

### 浏览器版本

Google Chrome 版本 108.0.5359.72（正式版本） （64 位）

### 播放器版本

3.25.14-788698c7

### 播放策略

HEVC

### 错误信息

```Shell
下截图
```

### 附加截图

![image](https://user-images.githubusercontent.com/61400426/211977332-559efe4c-2f87-46c3-874c-87e5a0b45a4f.png)

稍后再看页面（明显感觉界面元素更大）
![image](https://user-images.githubusercontent.com/61400426/211977401-e871c3ce-1734-4470-a1f3-dbb7f004421f.png)

普通页面
![image](https://user-images.githubusercontent.com/61400426/211977609-49332503-3e17-4dcd-9322-bd3a0d904826.png)

**Comment by hoiyuyiu** [comment]
似乎已解决，重定向成功

**Comment by canbingzt** [comment]
2.7.6版本的稍后再看没有重定向了
