### ISSUE TITLE
弹幕空降功能失效

### ISSUE THREAD

**Issue by Maozai-Teng** [the1812/Bilibili-Evolved#3926]
### 对应功能

启用弹幕空降

### 问题描述

启用弹幕空降完全失效，带有时间的弹幕都没有下划线，也都不能跳转

### 脚本版本

v2.6.0-21-g5b8d9acf1

### 浏览器版本

360极速21.0.1180.0 内核版本95.0.4638.69

### 播放器版本

HTML5播放器 V3.25.5

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved 网址参数清理 https://www.bilibili.com/video/av78426409/?vd_source=a9f65be0651c787d91909982127414b0 https://www.bilibili.com/video/av78426409/
```

### 附加截图

![QQ截图20230113045456](https://user-images.githubusercontent.com/18625640/212180413-8f1a012d-7f59-48d7-a283-9c4a4fc4042b.jpg)

**Comment by Geeyun-JY3** [comment]
请善用搜索：#3913、#3187 有相关反馈：<https://github.com/the1812/Bilibili-Evolved/issues/3187#issuecomment-1090302039>、<https://github.com/the1812/Bilibili-Evolved/issues/3187#issuecomment-1218470293>

**Comment by Maozai-Teng** [comment]
> 

我知道啊，但一直以来就是没有修复，其他失效的我找别的插件补足了，但这个没办法，我单独把这个发出来，让作者注意到这个bug~
