### ISSUE TITLE
脚本与解除B站港澳限制的脚本同时使用，出现的bug

### ISSUE THREAD

**Issue by zangliu2077** [the1812/Bilibili-Evolved#3928]
### 对应功能

配合B站港澳台的脚本使用，会出现弹幕点赞无法使用，然后脚本失效的问题

### 问题描述

配合B站港澳台脚本使用的时候，脚本无法响应，点击左边的按钮，圈圈消失，不会弹出任何内容，最重要的问题是，这个时候无法使用弹幕点赞功能，希望能修复一下这个问题，如果港澳台界面实在无法使用，希望能修复让其不冲突，让弹幕恢复能正常点赞，禁用脚本以后，能正常弹幕点赞之类的操作

### 脚本版本

V2.6.0

### 浏览器版本

edge， chrome最新版本

### 播放器版本

2.49.2

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved Error: 啥都木有
    at pn.fetchInfo (userscript.html?name=Bilibili%2520Evolved.user.js&id=07100e1a-e430-4b04-8de9-0dfac88bed17:193:22578)
    at async eval (eval at loadFeatureCode (www.bilibili.com/:193:65820), <anonymous>:1:2006)
```

### 附加截图

![image](https://user-images.githubusercontent.com/92388155/212463329-f35435e6-e625-4c35-b19b-7e30d70022cc.png)

**Comment by zangliu2077** [comment]
如果无法修复不支持港澳台页面也没关系，希望能够解决冲突导致弹幕无法操作的bug

**Comment by Kal-tsit63** [comment]
和自定义顶栏也会有冲突

**Comment by MC-dusk** [comment]
老问题了，建议单独使用两个脚本，话说我记得这个脚本曾经主动排除了港澳台页面，就像直播页面自定义顶栏不生效一样？
