### ISSUE TITLE
在夜间模式下，首页的番剧区部分字体没自动反转显示的颜色（比如黑色背景下字体变成白色，而非还是相近的颜色）

### ISSUE THREAD

**Issue by stars-island** [the1812/Bilibili-Evolved#3930]
### 对应功能

夜间模式

### 问题描述

在夜间模式下，首页的番剧区部分字体没自动反转显示的颜色（比如黑色背景下字体变成白色，而非还是相近的颜色）

### 脚本版本

v2.6.0-18-g702d02d6c

### 浏览器版本

Google Chrome Version 109.0.5414.75 (Official Build) (64-bit)

### 播放器版本

3.25.13-cad397b3

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved getContent 番剧 userscript.html?name=Bilibili%2520Evolved.user.js&id=bdc28d57-e2d2-415c-9f55-5469ca4ba351
```

### 附加截图

![image](https://user-images.githubusercontent.com/66160777/212521268-c66e043b-f6e9-4af9-b76a-bcb4ce8554d3.png)

鼠标靠近想要点击的物件时,，例如《古物奇谭》
![image](https://user-images.githubusercontent.com/66160777/212521275-1e866332-df2e-42be-94e0-79224f047124.png)

**Comment by the1812** [comment]
切回原版首页, 右下体验新版, 再开简化首页
