### ISSUE TITLE
稍后再看页面播放视频部分快捷键功能失效

### ISSUE THREAD

**Issue by z78966789** [the1812/Bilibili-Evolved#3933]
### 对应功能

快捷键扩展
Commit: 3397e56dc
内部名称: keymap

启用逐帧调整
Commit: 3397e56dc
内部名称: seekByFrames

### 问题描述

将视频添加到稍后再看，在稍后再看list页面播放视频而非直接播放那个视频
逐帧调整直接就不能用，快捷键也无效
快捷键扩展的点赞投币收藏快捷键无效

### 脚本版本

v2.6.0-preview-52-g3397e56dc

### 浏览器版本

Chrome 版本 109.0.5414.75（正式版本） （64 位）

### 播放器版本

3.25.14

### 播放策略

默认

### 错误信息

```Shell
暂无
```

**Comment by Geeyun-JY3** [comment]
重复，请善用搜索：#3916
