### ISSUE TITLE
视频下载功能，只能下载地址错误的番剧

### ISSUE THREAD

**Issue by RuJingTingShan** [the1812/Bilibili-Evolved#3942]
### 对应功能

下载视频

### 问题描述

刚才打了一堆结果页面出错，我吐血……

正常从搜索页面点进去地址
https://www.bilibili.com/video/BV13r4y1Q7a8/
![截图555](https://user-images.githubusercontent.com/96676995/213920695-c679d040-b7a9-49d5-98fd-59e325879f03.jpg)

结果进去的是番剧页面
https://www.bilibili.com/bangumi/play/ep434471
![截图559](https://user-images.githubusercontent.com/96676995/213920701-1946fcd8-3231-43a8-ad76-35575e70441d.jpg)

我要看的视频变成了“特别企划”的一集
而视频下载功能只能下载番剧，下载不到当前页面播放的内容

### 脚本版本

-

### 浏览器版本

-

### 播放器版本

-

### 播放策略

默认

### 错误信息

```Shell
-
```

**Comment by Geeyun-JY3** [comment]
因为该视频被破站拿去引流了：#3850

**Comment by RuJingTingShan** [comment]
> 
谢谢，插件已安装，但视频下载功能和以前一样，没找到可用的按钮，麻烦能告知一下怎么找到吗？

**Comment by Geeyun-JY3** [comment]
找个正常视频页面就能在下拉菜单看到 `手动输入` 了：#3801

**Comment by RuJingTingShan** [comment]
谢谢，折腾了大半个月终于成功下载好了，感恩
