### ISSUE TITLE
IframePopup.vue 中使用了 item.src，而 CustomNavbarItem 类型里却没有 src 属性

### ISSUE THREAD

**Issue by timongh** [the1812/Bilibili-Evolved#3947]
### 问题描述

IframePopup.vue 里面声明了 item 这个 prop，这个 prop 是 CustomNavbarItem  类型，而这个类型里面没有 src 属性。另外还有 item.width, item.height 是同样的情况

https://github.com/the1812/Bilibili-Evolved/blob/80794de10dd8c337e10806d1195bc204b85c5a6e/registry/lib/components/style/custom-navbar/iframe/IframePopup.vue#L2

**Comment by the1812** [comment]
正确的 item 类型应该是 `CustomNavbarItemInit & NavbarIframeConfig`, 偷懒直接调了那个 mixin 了(

**Comment by timongh** [comment]
那看吧，如果你现在懒得改，我就在升 Vue3 的时候给顺手改了。
