### ISSUE TITLE
v-for 迭代不允许使用 of

### ISSUE THREAD

**Issue by timongh** [the1812/Bilibili-Evolved#3948]
### 问题描述

https://github.com/the1812/Bilibili-Evolved/blob/80794de10dd8c337e10806d1195bc204b85c5a6e/src/ui/TabControl.vue#L7

Vue 的 v-for 只能用 in 来迭代

see: https://v2.cn.vuejs.org/v2/api/index.html#v-for

![image](https://user-images.githubusercontent.com/46739861/215251496-e79d320c-f2d1-43c0-a041-130bf8beb2c4.png)

**Comment by timongh** [comment]
src/components/feeds/VideoCard.vue 也是

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/215328466-32db5ccd-4404-43f6-94d6-1507d12659e9.png)
