### ISSUE TITLE
<template> 上不能使用属性

### ISSUE THREAD

**Issue by timongh** [the1812/Bilibili-Evolved#3951]
### 问题描述

在 dev-client/Widget.vue 中的 `<template>` 中使用了一个 class 属性。这是无效行为。我没直接改的原因是：怕修改后影响原有运行效果，需要更多考虑和测试才能更改。

**Comment by the1812** [comment]
可以删掉, 这个应该是早期开发时留下的 (这块曾经是个 div)

**Comment by timongh** [comment]
你顺手删了吧，我提交没你方便

**Comment by the1812** [comment]
ok
