### ISSUE TITLE
扩展倍速组件在从稍后再看打开的视频页面中不生效

### ISSUE THREAD

**Issue by odlove** [the1812/Bilibili-Evolved#3962]
### 对应功能

扩展倍速组件

### 问题描述

如标题所述
可能是因为从稍后再看打开的网址与正常打开的网址不同

可能其它组件也有此问题

### 脚本版本

v2.6.0-18-g702d02d6c 

### 浏览器版本

firefox 109.0.1 64 位

### 播放器版本

HTML5播放器 V3.25.5

### 播放策略

AVC

### 错误信息

```Shell
莫得
```

**Comment by Geeyun-JY3** [comment]
善用搜索，看置顶：#3916
