### ISSUE TITLE
两个夜间模式适配问题

### ISSUE THREAD

**Issue by NightSharp** [the1812/Bilibili-Evolved#3963]
### 对应功能

夜间模式
Commit: 3397e56dc
内部名称: darkMode

### 问题描述

1. festival界面下的评论区背景
[示例页面](https://www.bilibili.com/festival/2023bnj?bvid=BV17G4y1X7t8)
![图片](https://user-images.githubusercontent.com/9748063/216492337-d3f384b7-5b60-4409-964c-ad72a48e94f5.png)
其样式中的`background`被设置为了`#fff`
```
.comment-wrapper .comment-m[data-v-1cbe4364] {
  padding: 20px 17px;
  background: #fff;
}
```
需要将其修改为 `#222`
```
.comment-wrapper .comment-m[data-v-1cbe4364] {
  padding: 20px 17px;
  background: #222;
}
```
效果如下
![图片](https://user-images.githubusercontent.com/9748063/216493111-ff7a55bf-110f-4fa5-a32f-cf280c64acba.png)

2. 普通单人投稿播放页的关注按钮文本(无论新版旧版播放页)(专栏也有此问题)
此问题出现在未关注投稿作者时
[示例专栏](https://www.bilibili.com/read/cv9787208)
[示例视频](https://www.bilibili.com/video/av302459376)
旧版播放页
![图片](https://user-images.githubusercontent.com/9748063/216494502-e78e1918-ece7-474b-934a-b106b8644ef6.png)
新版播放页
![图片](https://user-images.githubusercontent.com/9748063/216494808-7c5d61cd-a677-4148-897d-87799f6949c8.png)
其样式中的`--foreground-color`被设置成了`black`
```
html{
 --foreground-color:black
}
```
需要将其修改为`white`
```
html{
 --foreground-color:white
}
```
效果如下
旧版播放页
![图片](https://user-images.githubusercontent.com/9748063/216495390-d3bc9cf2-d078-47ec-b31f-74dab9fee891.png)
新版播放页
![图片](https://user-images.githubusercontent.com/9748063/216495461-e8d93889-4d4b-4e36-a98a-93ad4226ed55.png)

### 脚本版本

v2.6.0-preview-52-g3397e56dc

### 浏览器版本

Firefox 109.0.1 (64 位)

### 播放器版本

festival是3.21.8-59565b57，普通播放页是3.26.0-dc55d742

### 播放策略

AVC

### 错误信息

```Shell
样式问题，控制台无具体报错
```

**Comment by the1812** [comment]
关于第二条, 有问题的其实是这个
![image](https://user-images.githubusercontent.com/26504152/217687320-b5090467-81ca-4860-9932-efdf2ea63bf3.png)

`--foreground-color` 只需要在通用设置里把文本颜色改一下就行了

**Comment by NightSharp** [comment]
> 关于第二条, 有问题的其实是这个 ![image](https://user-images.githubusercontent.com/26504152/217687320-b5090467-81ca-4860-9932-efdf2ea63bf3.png)
> 
> `--foreground-color` 只需要在通用设置里把文本颜色改一下就行了

我用Stylus自己定制了一下，越改越发现要改的地方好多，感觉都可以当个独立辅助样式发布了233，不过着实不规范

**Comment by Geeyun-JY3** [comment]
第一条还是合并回 #2945 吧
