### ISSUE TITLE
建议:将样式加载进行独立开关,解决the1812.github.io加载缓慢的问题

### ISSUE THREAD

**Issue by Mixlining** [the1812/Bilibili-Evolved#3964]
### 对应功能

加载脚本时的问题,非独立功能模块问题

### 问题描述

每次加载脚本需要连接the1819.github.io,从之前的issue已知是访问图标库,但是我启用的功能(扩展倍数 快捷键扩展 网址参数清理)并不需要加载任何样式,使用的是b站默认的样式,但是每次进入b站加载脚本依然会连接the1819.github.io
在不连接the1819.github.io时(路由器block),扩展功能仍然可以正常使用(即该连接只与样式加载有关,与功能加载无关,所以只用功能模块时不需要连接the1819.github.io)
the1819.github.io在不同网络环境下连接情况不同,在移动网络(深圳移动)会出现很高的延迟,导致网页加载很慢,影响体验
毕竟有时候看b站时是不挂梯子的

### 脚本版本

2.6.0

### 浏览器版本

Edge 109.0.1518.78 

### 播放器版本

3.26.0

### 播放策略

默认

### 错误信息

```Shell
无
```

**Comment by the1812** [comment]
这个样式是所有功能依赖的图标, 我打算改回脚本内置的形式
