### ISSUE TITLE
希望增加失效收藏视频的信息显示

### ISSUE THREAD

**Issue by GoingTime** [the1812/Bilibili-Evolved#397]
**关于哪一项功能**
B站失效视频并未完全被移除，其大多数信息仍然被保留且可以被解析。希望增加失效收藏显示功能显示相关内容，例如简介、UP主等。得到标题和简介就可以比较方便的寻找其他资源

**期望的效果**
类似于这个脚本：https://greasyfork.org/zh-CN/scripts/383143-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9-b%E7%AB%99-bilibili-%E6%94%B6%E8%97%8F%E5%A4%B9fix

该脚本的部分功能已经失效且一直没有更新，目前可以勉强使用，无法查看标题，可以查看UP主名字和上传日期

**Comment by Coulomb-G** [comment]
这个脚本调用的是biliplus转存的信息,你似乎理解错了

**Comment by lianmengkexin** [comment]
看了下b站自身的api中https://api.bilibili.com/medialist/gateway/base/spaceDetail?media_id=" + media_id + "&pn=" + pn + "&ps=20&keyword=&order=mtime&type=0&tid=0&jsonp=jsonp  
保存有失效视频除了标题和封面两项外的基本信息，当然那两项其实是最重要的
GooglepPlay版Android端当前似乎有api能获取那最重要的两项，然后请求有sign加密，破解无能……
biliplus缓存的信息其实封面还是外链的B站的服务器，可见B站本身是没有清楚缓存的，至少封面没有。
可惜biliplus缓存也有疏漏，例如本人收藏总共三个失效视频，其中两个获取不到封面，一个完全没有缓存！

**Comment by Coulomb-G** [comment]
biliplus转存的规则是得在plus页面转存过,你直接在b站收藏是不会转存的,尤其是新视频和低人气视频,没有封面和标题的话,其他信息也挺鸡肋的

**Comment by the1812** [comment]
喜欢的视频直接下下来吧 恢复失效视频信息以前的方法出一个封一个
