### ISSUE TITLE
“播放前显示封面”会导致视频暂停时也总是显示封面

### ISSUE THREAD

**Issue by GalaxySnail** [the1812/Bilibili-Evolved#3974]
### 对应功能

播放前显示封面

### 问题描述

如题。因为刚发布了新版本脚本，我不确定是新版本导致的 #3698 的回归，还是B站播放器更新导致的新问题。

### 脚本版本

v2.6.1-preview

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

chromium 109.0.5414.75 (正式版本) （64 位） 

### 播放器版本

3.26.2-af11cc59

### 播放策略

AVC

### 错误信息

```Shell
没有 Bilibili Evolved 输出的日志
```

**Comment by Yun-Shan** [comment]
应该是这个commit导致的 ed8d16b
https://github.com/the1812/Bilibili-Evolved/blob/3dca1e16357a331a78afc06cbb40f343e962a76b/registry/lib/components/video/player/show-cover/index.ts#L43
添加封面变量的元素改成了documentElement，但是移除封面变量的元素漏改了还是body，导致实际上没有移除封面
https://github.com/the1812/Bilibili-Evolved/blob/3dca1e16357a331a78afc06cbb40f343e962a76b/registry/lib/components/video/player/show-cover/index.ts#L8

作为作者修复前的临时解决方案，可以进入油猴脚本管理页面，然后点击编辑脚本，选择"存储"tab，将里面的内容全部复制到文本编辑器，然后搜索`body.style.removeProperty(\"--cover-url\")`，将`body`改为`documentElement`，点击保存即可

**Comment by seiuneko** [comment]
暴力猴 v2.13.9 编辑后无法保存，这里是自行编译的组件：
[show-cover.js](https://github.com/the1812/Bilibili-Evolved/files/10697831/show-cover.js.txt)

**Comment by FrankHB** [comment]
前些天是第一次暂停会出现问题之后正常，过了几天又是每次会重现，现在看了下 v2.7.2-53-g97c6184e1 还是有这个问题，直接关了算了……

**Comment by HowieHz** [comment]
这毛病还是存在，只能关掉了

**Comment by Mr-EEEeee** [comment]
bug依旧存在

**Comment by GalaxySnail** [comment]
我这里自从2月修复以后就再没出现过，所以你们反馈的问题可能是另外一个问题导致的。在一个被关掉的 issue 里跟帖不容易被注意到，我建议可以重新开一个 issue，在其中附上你的系统环境信息以及报错信息（如果有报错的话）。
