### ISSUE TITLE
为什么新版找不到批量下载

### ISSUE THREAD

**Issue by xlc520** [the1812/Bilibili-Evolved#398]
为什么新版找不到批量下载，好像原来可以选择具体的某一集然后用Aria2批量下载？

**Comment by xlc520** [comment]
我知道了，要把地址栏的BV号改为av号

**Comment by the1812** [comment]
你更新了吗? `v1.10.12`之后才支持bv号

**Comment by xlc520** [comment]
今天晚上更新的，然后没有，我把地址改为av号又有了，不影响

**Comment by piliparon** [comment]
我也是这个问题，手动换成av号以后虽然可以批量下载，但是下载时候一个视频的文件被分割成好几个小的，这样字幕就不能对上了。
