### ISSUE TITLE
清爽首页好像失效了

### ISSUE THREAD

**Issue by KINNAKAIHOU** [the1812/Bilibili-Evolved#3981]
### 对应功能

清爽首页

### 问题描述

原本的界面是这样的，小方块
![image](https://user-images.githubusercontent.com/73224577/217844210-6640187d-fa8e-4f82-a182-2139b5c8735e.png)
但是突然变成这个大方块的，而且是向显示小方块的加载，然后强制跳转到大方块
![image](https://user-images.githubusercontent.com/73224577/217845012-297e9a90-c20b-417f-8578-3c0512cf2428.png)

### 脚本版本

v2.6.1-22-ge28b5088d

### 脚本管理器及版本

Tampermonkey BETA 4.19.6177

### 浏览器及版本

版本 107.0.5304.107

### 播放器版本

HTML5播放器 V3.26.2

### 播放策略

默认

### 错误信息

```Shell
如下
```

### 附加截图

![image](https://user-images.githubusercontent.com/73224577/217845992-b7b25b52-89e2-4c55-ab3d-e743650fa28e.png)

**Comment by RoyDust** [comment]
先正常加载，然后转跳到原来主页
![image](https://user-images.githubusercontent.com/50167909/217890428-e7c8ca48-136d-46ef-bc14-4c4ad2552d33.png)
![image](https://user-images.githubusercontent.com/50167909/217890553-53fe917e-dd58-4863-bbe2-c7a72f59d4d5.png)

**Comment by misaka12001** [comment]
原来的小方块跑到页面最下边了，把简化首页里的选项都删掉还是可以用的，只不过上方会有一大块空白

**Comment by misaka12001** [comment]
![屏幕截图(36)](https://user-images.githubusercontent.com/118743788/218008359-1c4331a3-0365-4f8c-b887-e95adbad0066.png)

**Comment by Geeyun-JY3** [comment]
清爽首页在旧版、新版、内测首页的可用程度应该还是这个样子：https://github.com/the1812/Bilibili-Evolved/issues/3786#issuecomment-1304385603

**Comment by Geeyun-JY3** [comment]
半年前就有跑到最下面的反馈了：<https://github.com/the1812/Bilibili-Evolved/issues/3639#issuecomment-1228409122>，说的应该就是新版首页。应该算重复了吧。

**Comment by a1623382** [comment]
现在的问题是我这里没有回到旧版的选项了；切换成内测网页会经常卡死，不好用

**Comment by Geeyun-JY3** [comment]
确实该适配一下现在的默认首页（即以前的新版首页）了，不过还是建议将本 issue 合并至 #3639。

**Comment by sumi-0811** [comment]
超级喜欢那个简化首页-清爽-允许横向滚动，今天突然又没了，整个页面都没有这样的了

**Comment by a1623382** [comment]
> 现在的问题是我这里没有回到旧版的选项了；切换成内测网页会经常卡死，不好用 注：开启横向滚动之后，页面 cpu 占用会超过 100% ![image](https://user-images.githubusercontent.com/34230652/237732958-e35bf4df-0805-481a-9598-74f806bce35b.png)

使用uBlock Orgin ban了www.bilibili.com##.bili-layout和www.bilibili.com##.bili-footer之后，新版主页适配正常了；
ps：关闭横向滚动后，内测主页还是会经常卡死，完全不能日用。
