### ISSUE TITLE
自定义顶栏开启后进入稍后再看的视频，记笔记按钮消失

### ISSUE THREAD

**Issue by TojoSeita** [the1812/Bilibili-Evolved#3982]
### 对应功能

自定义顶栏
Commit: e28b5088d
内部名称: customNavbar

展开视频简介
Commit: e28b5088d
内部名称: fullVideoDescription

### 问题描述

只有从稍后再看进入的视频，稿件投诉旁边记笔记按钮会消失并且视频简介也没有自动展开，其他例如首页推荐的视频点进去按钮就显示正常，简介也会自动展开
![image](https://user-images.githubusercontent.com/48561640/217849577-5cc4ee94-6688-428b-b05c-560a5e0687d9.png)

### 脚本版本

v2.6.2-24-g156c9ce2d

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Chrome 版本 110.0.5481.77（正式版本） （64 位）

### 播放器版本

HTML5播放器 V3.26.0

### 播放策略

默认

### 错误信息

```Shell
无
```

**Comment by the1812** [comment]
#3916
