### ISSUE TITLE
关于弹幕卡顿

### ISSUE THREAD

**Issue by sclszjx** [the1812/Bilibili-Evolved#399]
**关于哪一项功能**
实测开启脚本时，弹幕时不时会出现卡顿，希望能优化一下，谢谢
**期望的效果**
解决弹幕卡顿问题
**脚本版本**
1.10.12

**Comment by LTHPKBTE** [comment]
这个...查看一下自己的弹幕渲染模式(弹幕设置-更多设置)是不是改成Canvas了,目前实测全部平台全部浏览器都是用CSS3渲染比较好

**Comment by sclszjx** [comment]
嗯，换成CSS3好像不卡了，谢谢！

**Comment by LTHPKBTE** [comment]
#380
提到过这个问题。有更详细点的解答
