### ISSUE TITLE
动态栏双列显示失效了

### ISSUE THREAD

**Issue by i110077** [the1812/Bilibili-Evolved#3990]
### 对应功能

就是之前是启用了展开动态内容还是哪一项功能后有双列显示的效果了

### 问题描述

之前点击顶部动态按钮后弹出的下拉菜单是视频内容以双列卡片形式显示的，更新最新版后失效了，返回旧版也无法解决，不知道是失效了还是哪里需要设置一下呢？求教了，感谢

### 脚本版本

v2.6.2-39-gc96b1880c

### 脚本管理器及版本

tampermonkey 4.18.1

### 浏览器及版本

Firefox 109.0.1 (64 位)

### 播放器版本

HTML5播放器 V3.26.0

### 播放策略

默认

### 错误信息

```Shell
firefox 控制台里按图输入Bilibili Evolved之后没有内容
```

### 附加截图
![20230212204404](https://user-images.githubusercontent.com/83385874/218312008-f7e10da3-b945-4eb4-a8d8-19f6760561ab.jpg)

_No response_

**Comment by Geeyun-JY3** [comment]
给张截图吧，我怎么感觉你说的是 `自定义顶栏` 功能，和动态相关功能没什么关系。

**Comment by Geeyun-JY3** [comment]
翻到个 v1 时期的 issue：#2191
和它一样吗？

**Comment by JOE-YEYE** [comment]
> 翻到个 v1 时期的 issue： [#2191 ](https://github.com/the1812/Bilibili-Evolved/issues/2191) 和它一样吗？

![image](https://user-images.githubusercontent.com/57321118/218306188-ed7c7cff-f431-47ad-8cc1-8868d09a3ebd.png)
我的问题和他的一样，只有在b博的页面能够显示双行，其他页面均为左边缺失。
开始我以为是我清理电脑删除了什么关键的文件，但是用镜像恢复后还是不行，，才想起来反馈

**Comment by JOE-YEYE** [comment]
对了，脚本不知道什么时候开始，主页头像不能加载。
但是怪异的是：｛开代理不关闭脚本｝和｛关闭脚本不开代理｝都能加载
![image](https://user-images.githubusercontent.com/57321118/218306577-a7651110-5a22-4402-a540-f303f55c9b3b.png)

**Comment by Geeyun-JY3** [comment]
我觉得你应该先更新一下组件，很久之前修过一个头像 bug：#3910、#3736、#3679

**Comment by i110077** [comment]
上面补了张图，现在显示效果如图所示，是正常状态不？上一版本这个动态框是双列显示的，视频封面和视频标题同时双列显示，忘记是设置了哪个组件，更新后就没了

**Comment by Geeyun-JY3** [comment]
> 上面补了张图，现在显示效果如图所示，是正常状态不？上一版本这个动态框是双列显示的，视频封面和视频标题同时双列显示，忘记是设置了哪个组件，更新后就没了

你补的图里的是原版顶栏，没有 `自定义顶栏`

**Comment by JOE-YEYE** [comment]
> 我觉得你应该先更新一下组件，很久之前修过一个头像 bug： [#3910 ](https://github.com/the1812/Bilibili-Evolved/issues/3910)、 [#3811 ](https://github.com/the1812/Bilibili-Evolved/issues/3811)、 [#3736 ](https://github.com/the1812/Bilibili-Evolved/issues/3736)、 [#3689 ](https://github.com/the1812/Bilibili-Evolved/issues/3689)、 [#3679 ](https://github.com/the1812/Bilibili-Evolved/issues/3679)

谢谢，看了下，原来是更新大版本，之前是在脚本仓库下的。研究了会弄好了新版，确实焕然一新，所有组件模块化了，要什么安装什么。很方便。
谢谢各位的贡献

**Comment by i110077** [comment]
> > 上面补了张图，现在显示效果如图所示，是正常状态不？上一版本这个动态框是双列显示的，视频封面和视频标题同时双列显示，忘记是设置了哪个组件，更新后就没了
> 
> 你补的图里的是原版顶栏，没有 `自定义顶栏`。你确定你装了并开了 `自定义顶栏` 这个组件吗？

搞定了，就是没装自定义顶栏导致的，下了一堆组件就是死活没想到在这个里，完美解决，感谢！
