### ISSUE TITLE
自定义倍速功能在个人主页播放全部下无效

### ISSUE THREAD

**Issue by lxr760** [the1812/Bilibili-Evolved#3991]
### 对应功能

扩展倍速

### 问题描述

自定义倍速功能在个人主页播放全部下无效

### 脚本版本

v2.6.2-39-gc96b1880c

### 脚本管理器及版本

Tampermonkey 4.18.1

### 浏览器及版本

Chrome Version 112.0.5582.0 (Official Build) dev (64-bit)

### 播放器版本

3.26.2

### 播放策略

默认

### 错误信息

```Shell
已打开扩展倍速和记忆倍速功能，设置5倍速视频播放，在单一视频下有效。但是在个人主页中，点击“播放全部”情况下，没有扩展倍速选项
```

### 附加截图

![image](https://user-images.githubusercontent.com/8476457/218298059-030bceec-35a7-4d31-aeab-63c00a9cef3d.png)
![image](https://user-images.githubusercontent.com/8476457/218298070-12bf51db-9d25-482b-bfb9-6fc702c20295.png)
![image](https://user-images.githubusercontent.com/8476457/218298075-1d313d42-05b3-40a7-adc8-121bff1499d5.png)
![image](https://user-images.githubusercontent.com/8476457/218298081-39404d9d-d736-4cad-9a3b-e7886ce29e53.png)

**Comment by Geeyun-JY3** [comment]
重复。看置顶，这个就是播放列表：#3916
