### ISSUE TITLE
“隐藏直播推荐”功能失效

### ISSUE THREAD

**Issue by mikazukizero** [the1812/Bilibili-Evolved#3993]
### 对应功能

隐藏直播推荐

### 问题描述

“隐藏直播推荐”功能失效。

新版播放界面右侧“直播推荐”无法屏蔽。
![屏幕截图 2023-02-14 232508](https://user-images.githubusercontent.com/37569694/218782338-b536e616-5a3c-4c46-9fa3-f621b771a122.png)

### 脚本版本

v2.6.2-24-g156c9ce2d

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Microsoft Edge 版本 110.0.1587.41

### 播放器版本

3.26.2-af11cc59

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved bpx player not found
b	@	userscript.html?name…c5-0bbd1c01a1ef:225
eval	@	VM7468:9
E	@	userscript.html?name…c5-0bbd1c01a1ef:198
await in E(异步)		
entry	@	VM7468:9
await in entry(异步)		
a	@	userscript.html?name…c5-0bbd1c01a1ef:190
h	@	userscript.html?name…c5-0bbd1c01a1ef:190
await in h(异步)		
(匿名)	@	userscript.html?name…c5-0bbd1c01a1ef:190
Promise.then(异步)		
a	@	userscript.html?name…c5-0bbd1c01a1ef:190
(匿名)	@	userscript.html?name…c5-0bbd1c01a1ef:190
(匿名)	@	userscript.html?name…c5-0bbd1c01a1ef:198
load(异步)		
(匿名)	@	userscript.html?name…c5-0bbd1c01a1ef:198
a	@	userscript.html?name…c5-0bbd1c01a1ef:198
(匿名)	@	userscript.html?name…c5-0bbd1c01a1ef:190
v	@	userscript.html?name…c5-0bbd1c01a1ef:190
await in v(异步)		
(匿名)	@	userscript.html?name…c5-0bbd1c01a1ef:249
await in (匿名)(异步)		
r	@	userscript.html?name…c5-0bbd1c01a1ef:198
await in r(异步)		
(匿名)	@	userscript.html?name…c5-0bbd1c01a1ef:249
await in (匿名)(异步)		
(匿名)	@	userscript.html?name…c5-0bbd1c01a1ef:249
(匿名)	@	userscript.html?name…c5-0bbd1c01a1ef:249
(匿名)	@	userscript.html?name…c5-0bbd1c01a1ef:249
St	@	VM7420:9
(匿名)	@	userscript.html?name…9cc5-0bbd1c01a1ef:1
window.__f__le4n9b06.do	@	userscript.html?name…9cc5-0bbd1c01a1ef:1
St	@	VM7420:9
n	@	VM7420:71
(匿名)	@	VM7420:72
set	@	VM7420:80
(匿名)	@	userscript.html?name…9cc5-0bbd1c01a1ef:1
ho	@	VM7418 content.js:21
O	@	VM7418 content.js:39
(匿名)	@	VM7418 content.js:40
Mt	@	VM7418 content.js:8
t	@	VM7418 content.js:9
Io	@	VM7418 content.js:36
Vo	@	VM7418 content.js:51
(匿名)	@	VM7418 content.js:51
(匿名)	@	VM7418 content.js:15
Mt	@	VM7418 content.js:8
t	@	VM7418 content.js:9
(匿名)	@	VM7418 content.js:15
(匿名)	@	VM7418 content.js:48
```

**Comment by mikazukizero** [comment]
只有部分视频能够复现，且控制台无报错。
重启浏览器依旧存在此情况。
以下内容基于内地版安卓客户端7.16.0。
主站点击打开视频没有推荐；内地版客户端分享视频（[短链接，无BV号，https://b23.tv/[xxxxxx]）浏览器打开几乎都有直播推荐（数据量不够）；海外版短链接（有BV号，https://b23.tv/BV[xxxxxx]）分享没有这个问题。
从海外版、网页端打开的视频用内地版短链接分享无直播推荐，使用内地版客户端分享链接打开后其它的都有直播推荐。

以下是我这里打开有直播推荐的部分视频：
https://www.bilibili.com/video/BV1sG4y1K7HK
https://www.bilibili.com/video/BV1yR4y1a7ak
https://www.bilibili.com/video/BV1aY411d76H
https://www.bilibili.com/video/BV1uM4y1R7Dv
https://www.bilibili.com/video/BV1Q54y1A756
https://www.bilibili.com/video/BV1o3411X7qX
https://www.bilibili.com/video/BV1ji4y1L7Ay
https://www.bilibili.com/video/BV14h411C7bZ
https://www.bilibili.com/video/BV1vP4y1r7UE
https://www.bilibili.com/video/BV1UG411V7km

控制台：
跨源读取阻止(CORB)功能阻止了 MIME 类型为 application/json 的跨源响应https://live-trace.bilibili.com/xlive/data-interface/v1/index/log?sessionID=2bedeccce9fccbabaa9b833a68999e55_8ABE826D-9C04-4EA5-AA50-0BFBDC432A72&group_id=1000221&biz=live&event_id=live_card_show&rule_key=&special_id=0&roomid=4537719&parent_id=1&area_id=530&page=0&position=1&platform=web?jsonp=jsonp&callback=jsonCallback_bili_86086001395800630。有关详细信息，请参阅 https://www.chromestatus.com/feature/5629709824032768。

**Comment by anwen-anyi** [comment]
QAQ  最近我也出现这个了 我以为是哔哩哔哩新加的选项呢 哈哈...等大佬修复

**Comment by MerlinAmbr0sius** [comment]
同样的问题。

**Comment by Sayyiku** [comment]
same question

**Comment by KJZH001** [comment]
同样的问题，遇到的页面地址为[https://www.bilibili.com/video/av820639108/?p=3](https://www.bilibili.com/video/av820639108/?p=3)

已开启bv转av号，同时视频是从个人收藏进去的

以及，这是我的报错信息
```
content-script-start.js:2641 Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (content-script-start.js:2641:18)
```

版本 Bilibili Evolved
v2.6.2-24-g156c9ce2d

**Comment by unlsycn** [comment]
同样的问题。

**Comment by LumineYoimiya** [comment]
the same

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/219948516-193dccce-2f02-4de4-9b67-82b99f5cadee.png)
请勿复读, 下次发版会修复的
