### ISSUE TITLE
搜索结果界面中间列有几个空白

### ISSUE THREAD

**Issue by junyuwsda** [the1812/Bilibili-Evolved#3997]
### 对应功能

搜索界面

### 问题描述

如图所示，搜索结果界面中间列有几个空白，不知为何

### 脚本版本

v2.6.2-39-gc96b1880c

### 脚本管理器及版本

Tampermonkey 4.18.1

### 浏览器及版本

EDGE 110.0.1587.41 (正式版本) (64 位)

### 播放器版本

3.26.3-rc.165.0-603ad5f

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/96709393/219010962-e0071aa9-05d2-4d0f-b206-207b32f84780.png)

**Comment by the1812** [comment]
应该是广告

**Comment by Geeyun-JY3** [comment]
还是塞个 `🚫已屏蔽广告` 占位吧：https://github.com/the1812/Bilibili-Evolved/discussions/3862#discussioncomment-4390923

**Comment by Corgile** [comment]
@the1812 直接把占位元素整个删掉吧，省的开uBlock了。或者增加删除模式，删不删用户自己决定

**Comment by the1812** [comment]
啥时候火狐支持 `:has` 我就删
![image](https://user-images.githubusercontent.com/26504152/219662896-d3e6ae53-332b-4ede-bf5c-bb288310db49.png)

**Comment by junyuwsda** [comment]
刚才看了评论试了一下，是ublock拦截的广告，而且ublock的拦截优先级更高
如果开了ublock，那么空白位置就完全是空白；而只开脚本自带拦截广告，就只是不显示广告图案而已，点击仍会跳转广告的链接
因此建议能够直接删掉并不显示空白

**Comment by ZhangTianrong** [comment]
原来是因为火狐吗……那么目前 Chromium 浏览器用户应该可以通过 DarkReader 或者 Stylus 之类的插件 (感觉这俩比较普及) 简单添加一条样式自己屏蔽搜索结果中的广告卡，比如
```javascript
div:not(:has(.bili-video-card__info--date)):has(>.bili-video-card) {
    display: none;
}
```

**Comment by the1812** [comment]
Firefox 121 已支持 `:has`, 我将考虑改进一下这个空白问题了

https://blog.nightly.mozilla.org/2023/11/02/i-can-has-browser-improvements-these-weeks-in-firefox-issue-148/
