### ISSUE TITLE
扩展倍数在稍后再看页面中失效

### ISSUE THREAD

**Issue by HZR-share** [the1812/Bilibili-Evolved#4004]
### 对应功能

扩展倍数
Commit: 156c9ce2d

### 问题描述

所有稍后再看页面

### 脚本版本

v2.6.2-24-g156c9ce2d

### 脚本管理器及版本

油猴 4.18.1

### 浏览器及版本

edge

### 播放器版本

V3.26.3

### 播放策略

默认

### 错误信息

```Shell
无
```

**Comment by Geeyun-JY3** [comment]
请善用搜索，重复：#3916
