### ISSUE TITLE
隐藏直播推荐失效

### ISSUE THREAD

**Issue by As8011** [the1812/Bilibili-Evolved#4009]
### 对应功能

隐藏直播推荐失效

### 问题描述

隐藏直播推荐失效

### 脚本版本

隐藏直播推荐失效

### 脚本管理器及版本

隐藏直播推荐失效

### 浏览器及版本

隐藏直播推荐失效

### 播放器版本

隐藏直播推荐失效

### 播放策略

默认

### 错误信息

```Shell
隐藏直播推荐失效
```

### 附加截图

隐藏直播推荐失效

**Comment by the1812** [comment]
#3993
