### ISSUE TITLE
更新后无法正常使用的问题

### ISSUE THREAD

**Issue by AndyStrom** [the1812/Bilibili-Evolved#4018]
### 对应功能

其他

### 问题描述

油猴的Bilibili-Evolved版本更新后会自动下载js源，导致使用github源的更新后不可用，建议添加个js/gay（划掉）hub源的手动选择按钮

### 脚本版本

多个版本

### 脚本管理器及版本

Tampermonkey 4.18.1

### 浏览器及版本

火狐 多个版本

### 播放器版本

无关

### 播放策略

默认

### 错误信息

```Shell
无关
```

**Comment by the1812** [comment]
本体的更新源不会串的, 你装的 jsDelivr 源就更新 jsDelivr 源, 装的 GitHub 源就更新 GitHub 源.
功能的更新可以在通用设置里修改
![image](https://user-images.githubusercontent.com/26504152/220380677-1ced1156-7aa1-4f57-bef6-5be15deb97f6.png)
