### ISSUE TITLE
switch-options.ts 里的注释与代码行为不匹配

### ISSUE THREAD

**Issue by timongh** [the1812/Bilibili-Evolved#4022]
### 问题描述

在 commit 'Fix infinite call stack'（e4e8c7370e54e5d99463780c64358ecdd56eb7bc）中，修改了函数 `newSwitchOptionsMetadataExtender` 的行为。使得该函数不再修改 options 自身，而是返回新对象。

但在类型 `SwitchOptionsMetadataExtender` 的注释中写的仍然是修改自身。

当然，我个人是倾向于直接修改对象本身。而且 `SwitchComponentWrapper` 的行为也是修改传入组件本身。

**Comment by the1812** [comment]
我当时是想让这里整齐点, 就觉得没必要修改自身了
https://github.com/the1812/Bilibili-Evolved/blob/cb3e1fd3f3d3081bcc656905beda502fa97e65f7/src/components/switch-options.ts#L307-L315

**Comment by timongh** [comment]
我的想法主要是，一般被包装后不再需要原始的对象了。所以直接修改对象本身，如果用户需要保留原始对象就自己克隆。

不过你的说法也行。毕竟 `widget`, `entry` 都被直接换掉了。

按你的偏好来吧，只要注释和行为能对得上就行了。

**Comment by timongh** [comment]
PR #4021 我是没有改这处注释的。

**Comment by timongh** [comment]
另外类型 `SwitchComponentWrapper` 的注释里也提一下比较好。options 选项是被扩展还是被替换。
