### ISSUE TITLE
新版动态页面问题汇总(?)

### ISSUE THREAD

**Issue by RtYkk** [the1812/Bilibili-Evolved#4023]
### 对应功能

直播信息扩充 cbd812487

### 问题描述

左侧直播栏如果有超过十个直播，十个以后(>10)的就点击不了了 。关了功能之后发现排序 10 以后的直播都被折叠了。

### 脚本版本

v2.6.3-preview

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Chrome 110.0.5481.178

### 播放器版本

v 0.0

### 播放策略

默认

### 错误信息

```Shell
从下图可见明显分成了 Array 10 和 Array 3，目前正好是 13 个人同时开播
```

### 附加截图

![chrome_PEH4sugaC9](https://user-images.githubusercontent.com/45971730/220915815-03182ba3-a631-4b3b-934e-8b97c9e6c432.png)

**致遇到了相同问题准备回复的人**
**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>Spoiler warning</summary>
由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与[邮件列表](https://www.zhihu.com/question/23757640)类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其是，项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。

</details>

**Comment by lrs95** [comment]
> ### 对应功能
> 直播信息扩充 [cbd8124](https://github.com/the1812/Bilibili-Evolved/commit/cbd8124874bde2a965802ef9991953c7086c5d57)
> 
> ### 问题描述
> 左侧直播栏如果有超过十个直播，十个以后(>10)的就点击不了了 。关了功能之后发现排序 10 以后的直播都被折叠了。
> 
> ### 脚本版本
> v2.6.3-preview
> 
> ### 脚本管理器及版本
> Tampermonkey v4.18.1
> 
> ### 浏览器及版本
> Chrome 110.0.5481.178
> 
> ### 播放器版本
> v 0.0
> 
> ### 播放策略
> 默认
> 
> ### 错误信息
> ```shell
> 从下图可见明显分成了 Array 10 和 Array 3，目前正好是 13 个人同时开播
> ```
> 
> ### 附加截图
> ![chrome_PEH4sugaC9](https://user-images.githubusercontent.com/45971730/220915815-03182ba3-a631-4b3b-934e-8b97c9e6c432.png)

我也有这问题

**Comment by ssxwcz** [comment]
目前发现的样式问题如下：
1. 转发的动态背景色不对
2. 左侧直播栏鼠标悬浮上去背景色变为白色
3. 右侧话题栏鼠标悬浮上去背景色变为白色
4. 顶部关注栏左右切换按钮变成白色了
![image](https://user-images.githubusercontent.com/43665491/221890012-049fcd04-2685-4a7e-ac7d-e1d17d196f08.png)

**Comment by Geeyun-JY3** [comment]
算重复了吧：#3917（
