### ISSUE TITLE
隐藏番剧承包似乎失效

### ISSUE THREAD

**Issue by KJZH001** [the1812/Bilibili-Evolved#4028]
### 对应功能

隐藏番剧承包

Commit: 2bfc43d3a

内部名称: hideBangumiSponsors

### 问题描述

相关页面[https://www.bilibili.com/bangumi/play/ss5798](https://www.bilibili.com/bangumi/play/ss5798)

![image](https://user-images.githubusercontent.com/29683578/221392617-ad336531-e063-4369-b156-6a0620737cb2.png)

正常播放完即可重现，由于搜索issue似乎找不到已经提交过的类似问题，并且我无法确定是否应该归属到播放器相关问题，所以单独发一个出来

### 脚本版本

v2.6.3-29-gd5cae8ee7

### 脚本管理器及版本

4.18.1

### 浏览器及版本

Google Chrome	110.0.5481.177 (正式版本) （64 位） (cohort: M110_Stable_RampUp)

### 播放器版本

3.26.0-dc55d742

### 播放策略

默认

### 错误信息

```Shell
（1）Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (chrome-extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/pages/content-script-start.js:2641:18)

（3）Uncaught (in promise) Error: Cannot read properties of null (reading 'endsWith')
    at wrappedSendMessageCallback (chrome-extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/pages/content-script-start.js:2641:18)
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
看功能描述, 是 `隐藏番剧页面下方的承包榜, 以及右边的承包按钮.`, 并不是播放完后出现的这个
