### ISSUE TITLE
直播信息扩充 功能失效

### ISSUE THREAD

**Issue by yangyangbuxiangyang** [the1812/Bilibili-Evolved#4034]
### 对应功能

直播信息扩充

### 问题描述

rt

### 脚本版本

v2.6.3-26-gc23219d84

### 脚本管理器及版本

Tampermonkey 4.18.1

### 浏览器及版本

Microsoft Edge110.0.1587.57 和Chrome110.0.5481.178

### 播放器版本

3.27.1

### 播放策略

AVC

### 错误信息

```Shell
rt
```

### 附加截图

![image](https://user-images.githubusercontent.com/114185862/222137361-201382ea-dc43-427e-b5cd-71cfaf144606.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
请善用搜索，重复：#3917、#4023

**Comment by yangyangbuxiangyang** [comment]
> 请善用搜索，重复：#3917、#4023

我用的是旧版网页

**Comment by yangyangbuxiangyang** [comment]
还没修复呀怎么关闭了

**Comment by the1812** [comment]
新版本修了

**Comment by TerrenceLTX** [comment]
试了一下，确实还没修好。
![Screenshot 2023-03-26 230516](https://user-images.githubusercontent.com/104809983/227774587-b765edbb-e9c1-4463-9ee4-cce3ed1d3651.jpg)

**Comment by CrazyboyQCD** [comment]
确实没修好，只展示10个

**Comment by yangyangbuxiangyang** [comment]
> 新版本修了

修好了我就不会这么回复了

**Comment by Unburnt-Sky** [comment]
我这里更新到2.7后已恢复正常

**Comment by KazenoIro936** [comment]
我这里更新2.7.0后，旧版功能正常，新版b站页面还是只能显示10个，chrome控制台报错如图，版本111.0.5563.111
![屏幕截图 2023-03-26 084948](https://user-images.githubusercontent.com/96087259/227776860-19f6956e-652c-474c-b69f-6e32fa651b86.png)

**Comment by Feng-Li-123** [comment]
很神奇，我能显示30个...
扩充了 但没完全扩
