### ISSUE TITLE
课程无法双击全屏

### ISSUE THREAD

**Issue by Hatanezumi** [the1812/Bilibili-Evolved#4036]
### 对应功能

双击全屏

### 问题描述

在安装了双击全屏插件后，bilibili课程无法使用双击全屏
其他视频双击全屏可用

### 脚本版本

v2.6.3-34-g2bfc43d3a

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Microsoft Edge v110.0.1587.57

### 播放器版本

3.22.1

### 播放策略

默认

### 错误信息

```Shell
见截图
```

### 附加截图

![image](https://user-images.githubusercontent.com/49899349/222178074-7ecc66ea-c9af-4b79-9565-17b7234eeb64.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
关于 Bilibili-Evolved 会不会支持课程界面的播放器：#3199
所以 `双击全屏` 会不会支持……

**Comment by Hatanezumi** [comment]
那这样的话希望能有一个自动禁用的功能

**Comment by Geeyun-JY3** [comment]
> 那这样的话希望能有一个自动禁用的功能

直接在用户脚本管理器里排除课程页的域名啊
