### ISSUE TITLE
动态图片导出检测不到图片

### ISSUE THREAD

**Issue by 7654** [the1812/Bilibili-Evolved#4038]
### 对应功能

Commit: 2bfc43d3a
内部名称: imageExporter

### 问题描述
旧版动态出现问题，新版动态正常可用
在t.bilibili.com动态首页和动态详情页下载图片失败，提示 此条动态没有检测到任何图片. 
在Up的space.bilibili.com/UID/dynamic 可下载图片

### 脚本版本

v2.6.3-41-g93cdffde0

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Firefox 110.0.1

### 播放器版本

3.26.5

### 播放策略

默认

### 错误信息

```Shell
无输出
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
新版动态？

**Comment by 7654** [comment]
> 新版动态？

昨天出行的问题，并没有见到回到旧版的按钮，不确定是否新版动态

**Comment by the1812** [comment]
你看主页背景, 蓝色是旧版, 绿色是新版

**Comment by 7654** [comment]
>

**Comment by 7654** [comment]
> 你看主页背景, 蓝色是旧版, 绿色是新版

蓝色背景，另稍后再看https://www.bilibili.com/list/watchlater?bvid= 不能下载视频了

**Comment by 7654** [comment]
> 你看主页背景, 蓝色是旧版, 绿色是新版

今天B站给我推新版动态了，图片下载可用
