### ISSUE TITLE
找不到录像下载功能在哪

### ISSUE THREAD

**Issue by xproducer** [the1812/Bilibili-Evolved#404]
看到更新动态里有说新增了直播录像下载的功能，但我不管是在正在直播的直播间还是在轮播直播录像的直播间里都没找到下载录像的选项，我想问问这个功能在哪打开

**Comment by the1812** [comment]
录像页面才会出现, 网址形如`https://live.bilibili.com/record/XXXXXXX`

**Comment by xproducer** [comment]
> 录像页面才会在附加功能出现, 网址形如`https://live.bilibili.com/record/XXXXXXX`

大概懂了，就是这个不是录制直播内容或者下载轮播内容的，需要up主提供直播录像的网址才能进去下载录像，没有录像网址就下不了是吧。不好意思是我弄错了

**Comment by the1812** [comment]
是的, 可以参考#297
