### ISSUE TITLE
`展开选集列表` 相关 bug 和优化建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#4040]
接着 https://github.com/the1812/Bilibili-Evolved/discussions/3764#discussioncomment-4011316 继续反馈：

由于目前 `选集区域优化` 的 `展开选集列表` 会展开合集下的所有分组，但分组右上角展开 / 收起操作的按钮在未做任何操作的情况下仍是未展开的状态（即「v」状），这就导致首次折叠合集中非当前视频所在分组需要点按两次上述按钮。
![image](https://user-images.githubusercontent.com/49396421/222725614-6790ca94-5bd8-4fab-8713-e2cc914506f4.png)
![bilibili_collection](https://user-images.githubusercontent.com/49396421/222727261-39b7ba42-5606-4955-a70e-8d153d1e51b0.gif)

是否还能优化？如让按钮符合分组实际展开 / 收起状态（即让其他分组上述按钮在分组实际已展开时呈倒「v」状），或和破站默认逻辑一样[只强制展开合集中当前视频所在分组](https://github.com/the1812/Bilibili-Evolved/discussions/3764#discussioncomment-4061612)。

_Originally posted by @Geeyun-JY3 in https://github.com/the1812/Bilibili-Evolved/discussions/3899#discussioncomment-4578844_

**Comment by the1812** [comment]
可能得用 JS 去搞了, 纯 CSS 总是不太完美
