### ISSUE TITLE
"夜间模式" "复制动态链接" "图片批量导出" 在新版动态中无法工作不正常，"强制固定动态侧栏" 疑似无法工作

### ISSUE THREAD

**Issue by Misaka-L** [the1812/Bilibili-Evolved#4041]
### 对应功能

- 强制固定动态侧栏
- 夜间模式
- 复制动态链接
- 图片批量导出

### 问题描述

1. 进入新版动态页
2. 问题出现

### 夜间模式
未适配转发动态、 UP 主筛选、回到顶部和直播间信息
![image](https://user-images.githubusercontent.com/42287372/222869606-bbb1252b-3e23-4b10-adf1-4bae1e90544a.png)
![image](https://user-images.githubusercontent.com/42287372/222869624-ffa6d7e0-d5c2-479f-843a-0d0f1082131e.png)
![image](https://user-images.githubusercontent.com/42287372/222869734-f96604a4-9ae8-4eb3-ab26-59c62f16a76d.png)
![image](https://user-images.githubusercontent.com/42287372/222869752-5dda217d-7fc4-4f1d-8d85-e2c526cccffd.png)

### 复制动态链接 与 图片批量导出
在启用以上功能中任意一个功能之后，动态的上下文菜单无法正常工作。
![image](https://user-images.githubusercontent.com/42287372/222869890-b18c0b08-8ba3-466c-bafe-d7a3ff84006a.gif)

### 强制固定动态侧栏
具体问题表现为所有板块的间隔消失，但是貌似切换回旧版再切换回来就可以正常工作（？）

### 脚本版本

v2.6.3-29-gd5cae8ee7

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Microsoft Edge 110.0.1587.56 (正式版本) (64 位) 

### 播放器版本

3.27.1

### 播放策略

HEVC

### 错误信息

```Shell
见截图
```

### 附加截图

![image](https://user-images.githubusercontent.com/42287372/222869537-8bbe4863-0607-460f-a5e5-b0243229945f.png)
![image](https://user-images.githubusercontent.com/42287372/222869544-99d6b933-a141-4c9d-9dc8-7fad9c14dee4.png)
![image](https://user-images.githubusercontent.com/42287372/222869547-bb55f31e-0534-4cb4-922a-63ab68a41272.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
合并到 #3917
