### ISSUE TITLE
强制固定动态侧栏使得新版动态页面排版崩坏

### ISSUE THREAD

**Issue by Yanstory** [the1812/Bilibili-Evolved#4042]
### 对应功能

强制固定动态侧栏（Commit: cbd812487，内部名称: fixedFeedsSidebars）

### 问题描述

新版动态首页下，开启“强制固定动态侧栏”功能会导致动态页面排版崩坏，但仅在最大化窗口时会出现此种情况。
![image](https://user-images.githubusercontent.com/5153875/222882624-7219dc3b-3a1d-4a8c-9c93-348b42dc98ca.png)
在开启开发工具（F12）和非最大化窗口的情况下会正常显示；关闭该功能亦可，但会失去固定动态侧栏的能力。

此外昨日未发现异常。

### 脚本版本

v2.6.3-preview

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Chromium 102.0.5005.167

### 播放器版本

（与播放器无关）

### 播放策略

默认

### 错误信息

```Shell
见附加截图（应该是无异常）
```

### 附加截图

![image](https://user-images.githubusercontent.com/5153875/222882915-cd1b57bc-84e1-43ca-b001-d822e2b4dcc0.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
#4041
