### ISSUE TITLE
个别多P视频无法下载

### ISSUE THREAD

**Issue by AllanFLan** [the1812/Bilibili-Evolved#4044]
### 对应功能

下载视频
Commit: cbd812487
内部名称: downloadVideo

### 问题描述

BV1xP411g74E 和 BV1wo4y1r7y6 这个多P视频无法下载，而其它多P视频则可以下载

### 脚本版本

v2.6.3-29-gd5cae8ee7

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Microsoft Edge 110.0.1587.63 (正式版本) (64 位)

### 播放器版本

3.27.1-e85c9522

### 播放策略

默认

### 错误信息

```Shell
获取番剧数据失败: 无法解析 Season ID
```

### 附加截图

![image](https://user-images.githubusercontent.com/36136750/222932316-93826eb2-f86a-4e50-a74d-e1a83fc16133.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
#3850

**Comment by diannaojiang** [comment]
我这里所有多P视频都无法使用下载功能，包括番剧和任何有列表的视频，提示和上图一样“无法解析 Season ID”。播放器版本包括3.27.1和3.27.3

**Comment by the1812** [comment]
估计也是新版播放器的问题, 等我被灰度到再看看

**Comment by diannaojiang** [comment]
简单的调试了一下，[源码](https://github.com/the1812/Bilibili-Evolved/blob/900b6c1f6137d0a52c34afc5b63ea1a99efe5c29/registry/lib/components/video/download/inputs/bangumi/batch.ts)中的**metaUrl**现在解析到的内容是`<meta property="og:url" content="https://www.bilibili.com/bangumi/play/ep704473">`  所以正则确实从中无法匹配到`/play\/ss(\d+)/`

**Comment by yxtj** [comment]
最近一些番剧也遇到这个问题，但是过几天又会莫名其妙地回复正常，我查看了播放器版本都是3.27.1。比如我发现前几天是轻音少女第二季，这几天是间谍过家家。
https://www.bilibili.com/bangumi/play/ep700607

**Comment by Rossi9588** [comment]
https://www.bilibili.com/bangumi/play/ep737555   
 Running Man（僅限台灣地區） 
您好，這個也常常{获取番剧数据失败: 无法解析 Season ID}
之前都沒問題，最近常常不好使。有時候會正常，這幾天是完全不行了。
其他影片則是有些可以有些不行。謝謝

**Comment by the1812** [comment]
和地区没关系 只是 Season ID 的获取失效了

**Comment by Geeyun-JY3** [comment]
？艾特我干嘛

**Comment by HolmesZhao** [comment]
> 简单的调试了一下，[源码](https://github.com/the1812/Bilibili-Evolved/blob/900b6c1f6137d0a52c34afc5b63ea1a99efe5c29/registry/lib/components/video/download/inputs/bangumi/batch.ts)中的**metaUrl**现在解析到的内容是`<meta property="og:url" content="https://www.bilibili.com/bangumi/play/ep704473">` 所以正则确实从中无法匹配到`/play\/ss(\d+)/`

看了一下确实是这样的, 有没有大佬 fork 后打包一个?

**Comment by shimakotodo** [comment]
在下载街头霸王动画https://www.bilibili.com/bangumi/play/ep52546也发现了这个问题，期待新版更新解决。

**Comment by RadioNoiseE** [comment]
问题在于有两种url，一种是从首页等点击进入剧集时的`https://www.bilibili.com/bangumi/play/ss2592`，结尾是`ssxxxxx`，用这个可以被正则匹配到。

上面有人贴出来的`https://www.bilibili.com/bangumi/play/ep63870`url这样的自然匹配不到。

（不过是不是该在报错信息或者什么地方提一下？
