### ISSUE TITLE
自定义顶栏的动态问题

### ISSUE THREAD

**Issue by wjwkill** [the1812/Bilibili-Evolved#4049]
### 对应功能

![image](https://user-images.githubusercontent.com/49703448/223335039-b8c2d031-7bc5-42b3-aca2-c12d8fdd9bc5.png)

### 问题描述

动态首页的自定义顶栏，鼠标悬停在动态上时无内容，点击下方页签，左下角报错。

### 脚本版本

v2.6.3-41-g93cdffde0

### 脚本管理器及版本

Tampermonkey v4.11

### 浏览器及版本

Chrome 110.0.5481.178

### 播放器版本

3.27.2-d0bc6222

### 播放策略

默认

### 错误信息

```Shell
错误
```

### 附加截图

![image](https://user-images.githubusercontent.com/49703448/223336089-420c3048-64b7-4219-8c78-11f7402aff3a.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by wjwkill** [comment]
还有一个建议，自定义顶栏的稍后在看和收藏没有显示总视频数量，原版是有的，希望能够加上！
![image](https://user-images.githubusercontent.com/49703448/223337208-cd0796d7-5bcf-4a20-b4c4-9d9c8dcb7963.png)
![image](https://user-images.githubusercontent.com/49703448/223337273-56b90a79-6b91-40dc-ab8d-7998e3e6eb62.png)
![image](https://user-images.githubusercontent.com/49703448/223337303-4182be21-e5f2-4356-8f90-ab74152dbb2d.png)

**Comment by Geeyun-JY3** [comment]
是不是新版动态：#3917

**Comment by wjwkill** [comment]
> 是不是新版动态：#3917

不是，我还用的老版的

**Comment by the1812** [comment]
之前有类似的, 退出登录再重新登录就好了

**Comment by the1812** [comment]
功能建议记得去讨论区提

**Comment by wjwkill** [comment]
好的

**Comment by wjwkill** [comment]
退出登录再重新登录后还有此问题，强制刷新界面后，鼠标放上去会报错，看了下控制台估计是请求“视频”、“番剧”、“专栏”的接口返回200但是没有内容，前端拿不到数据进行展示报的错
![image](https://user-images.githubusercontent.com/49703448/225343563-336b67cc-1a85-433b-9359-d96fae94a69a.png)
![image](https://user-images.githubusercontent.com/49703448/225343598-7821d009-e885-452f-acd7-84396e66de80.png)
![image](https://user-images.githubusercontent.com/49703448/225343696-6d2625e8-d025-438b-9cb2-4f79041afadf.png)
![image](https://user-images.githubusercontent.com/49703448/225343731-c58dbf5c-9881-4d38-9600-bb3b80da8f19.png)

**Comment by the1812** [comment]
那我也不知道该怎么办了...

**Comment by wjwkill** [comment]
我提个建议，如果返回的data为空或者格式不对，就不显示呗，也没啥影响，把错误弹窗处理下让它不显示就行，主要是弹窗影响观感，其他功能不是那么重要

**Comment by the1812** [comment]
报错的是最后那个 `dynamic_new`, 不去打开动态弹窗也不会触发吧

**Comment by wjwkill** [comment]
是的，就它报错

**Comment by the1812** [comment]
那还是要报错的, 不然出错就显示个空更迷惑了
