### ISSUE TITLE
动态界面-黑暗模式-炸了

### ISSUE THREAD

**Issue by Malus-Mill** [the1812/Bilibili-Evolved#405]
**关于哪一项功能**
动态界面-黑暗模式
**问题描述**

背景覆盖不完全，字体颜色出错（直播、话题）

**脚本版本**

 (Offline) | 616.33

**浏览器版本**

Google Chrome 已是最新版本
版本 80.0.3987.149（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/53999738/77557216-760f2100-6ef4-11ea-85c8-5d8dc69983c1.png)

**Comment by chaylun** [comment]
哈哈哈跟我一样，这界面可太难受了
