### ISSUE TITLE
简化直播间 - 付费礼物支持直接隐藏左下角

### ISSUE THREAD

**Issue by wwzw27** [the1812/Bilibili-Evolved#4067]
### 对应功能

简化直播间
![image](https://user-images.githubusercontent.com/64151098/225214266-20a1e5a3-60db-4610-9afc-d36446b1521e.png)

### 问题描述

简化直播间功能简化不完全，任意直播间都会出现。应该是b站更新了礼物栏造成的。

### 脚本版本

v2.6.3-36-g9581897e4

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Chrome 111.0.5563.65

### 播放器版本

RoomPlayer version: 3.6.116

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/64151098/225212859-0be1fd64-6fac-44ff-addc-a6a43d56dfa7.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by TsubakiAwa** [comment]
我也是网页全屏和全屏也是是这样
![image](https://user-images.githubusercontent.com/53134066/225240111-2a6eb5e4-7ce1-4d0a-94de-3fee26c6c3a1.png)
![image](https://user-images.githubusercontent.com/53134066/225240417-73551dd8-9e09-4083-ae5d-f815abeb6318.png)
![image](https://user-images.githubusercontent.com/53134066/225240525-ae792e1b-91e6-46fe-b86a-4996653a5973.png)
![image](https://user-images.githubusercontent.com/53134066/225240667-e6b0c1b3-49f0-4de8-a5ed-59cb194bcad2.png)

**Comment by a546109781** [comment]
我也这样了

**Comment by Dizero1** [comment]
刷新后暂时不出现，等一会又出现了。
_先F12删元素（id=gift-control-vm，有两个)应付着，等更新。_

**Comment by A-Whisper** [comment]
![image](https://user-images.githubusercontent.com/60808770/225321704-c2e91bc7-ce4a-460d-b233-a58ffcc5fd6a.png)
点这里直接关掉

**Comment by fortandh** [comment]
补充一个救济的法子：https://github.com/fortandh/SimplifyLiveroomTemp

**Comment by pencilqaq** [comment]
补充bug 点击返回原版直播间后 上述问题依然存在（非全屏情况下）

**Comment by AsunaEmiria** [comment]
建议直接用Adguard，Adblock等浏览器扩展直接拦截元素

**Comment by Mon3t4r** [comment]
刚刚找ai写好了一个油猴脚本来屏蔽他,可以临时用用,测试有效
// ==UserScript==
// @name         Hide gift-control-vm element
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Hide gift-control-vm element
// @author       You
// @match        http://*/*
// @match        https://*/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    document.getElementById('gift-control-vm').style.display = 'none';
})();
