### ISSUE TITLE
希望能添加查询弹幕发送者功能

### ISSUE THREAD

**Issue by ChanJohann** [the1812/Bilibili-Evolved#407]
**关于哪一项功能**
弹幕

**期望的效果**
在弹幕列表中右键查询弹幕发送者

**脚本版本**
1.10.12

**Comment by Coulomb-G** [comment]
已经有人做过相关功能了,可以去谷歌商店找「pakku」

**Comment by ChanJohann** [comment]
> 已经有人做过相关功能了，可以去谷歌商店找「pakku」

谢谢，其实我就是从 pakku 来的，希望单独把这个功能添加到脚本中

**Comment by Coulomb-G** [comment]
弹幕相关的功能「pakku」已经做到极致了,且和该脚本兼容较好,没必要重复造轮子
