### ISSUE TITLE
夜间模式在新版动态页存在样式问题

### ISSUE THREAD

**Issue by 401U** [the1812/Bilibili-Evolved#4070]
### 对应功能

夜间模式

### 问题描述

新版动态页和动态详情页的夜间模式样式存在问题，已发现的问题包括

- 动态首页 https://t.bilibili.com/
    - 正在直播列表在选中时
    - 常用用户的边缘阴影
- 动态详情页 https://www.bilibili.com/opus/773305760884981792
    - 评论区的宽度 
   
详细信息见附加截图

### 脚本版本

v2.6.3-preview

### 脚本管理器及版本

violentmonkey 2.13.10

### 浏览器及版本

Microsoft Edge 111.0.1661.41

### 播放器版本

3.27.3-rc.689.0-07649083

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

动态首页：
![动态首页 夜间](https://user-images.githubusercontent.com/52659312/225387917-d246099f-dcaf-4a3f-ad4c-e4dbc7078e2b.png)
![动态首页 日间](https://user-images.githubusercontent.com/52659312/225388170-4de8c774-318e-4a5f-b94d-44ee047c98d3.png)

动态详情页：
![动态详情页 夜间](https://user-images.githubusercontent.com/52659312/225388667-889ae7ac-1799-41a5-91a0-feb54f9c7859.png)
![动态详情页 日间](https://user-images.githubusercontent.com/52659312/225388558-d480a23f-774f-4973-b40b-6cb77a667cfc.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
请善用搜索：#3917

**Comment by 401U** [comment]
> 请善用搜索：#3917

抱歉，我搜索的关键词是夜间模式，找到的相关问题都与动态页无关，所以发起此issue
