### ISSUE TITLE
顶栏和左侧插件快捷键均不显示

### ISSUE THREAD

**Issue by VwEl** [the1812/Bilibili-Evolved#4081]
### 对应功能

无入口

### 问题描述

edge 111.0.1661.44 +  Tampermonkey v4.18.1  首页和任意视频打开都不显示入口:
firefox 110.0.1 + Tampermonkey v4.18.1  正常生效，把firefox上的导出跑在edge上也不行

### 脚本版本

2.6.3

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

edge 111.0.1661.44 (正式版本) (64 位)

### 播放器版本

3.27.3

### 播放策略

默认

### 错误信息

```Shell
console 无关于此插件的错误显示
```

**Comment by Geeyun-JY3** [comment]
#3988、#3918、#3888

**Comment by cjf0523** [comment]
+1

**Comment by actforjason** [comment]
> #3988、#3918、#3888

不管用呀

**Comment by Geeyun-JY3** [comment]
> 不管用呀

我说的是重复，解决方案去关注还开着的 issue 后续。

**Comment by zzy0516alex** [comment]
破案了，到Microsoft插件商店下载Tampermonkey BETA最新版即可
https://microsoftedge.microsoft.com/addons/detail/tampermonkey-beta/fcmfnpggmnlmfebfghbfnillijihnkoh
旧版Tampermonkey 4.18似乎不支持
