### ISSUE TITLE
港澳台番剧无法下载

### ISSUE THREAD

**Issue by 1q2a3a** [the1812/Bilibili-Evolved#4082]
### 对应功能

下载视频 
Commit: fd37f297f

### 问题描述

挂梯子后下载港澳台番剧会报错，提示读取不到 Season ID，能正常观看，能读取封面，也可以下载弹幕。使用梯子为BitzNet

### 脚本版本

v2.6.3-36-g9581897e4

### 脚本管理器及版本

油猴V4.18.1

### 浏览器及版本

Edge 111.0.1661.44 

### 播放器版本

0.11.21-8C739D8A

### 播放策略

默认

### 错误信息

```Shell
获取番剧数据失败: 无法找到 Season ID
```

### 附加截图

![image](https://user-images.githubusercontent.com/128471527/226575929-aadfffde-0b16-40b2-bf57-633ff8dd4dc9.png)
![image](https://user-images.githubusercontent.com/128471527/226576083-6973cca3-8b18-46ff-b6ff-732ac6230238.png)
![image](https://user-images.githubusercontent.com/128471527/226576181-80d98579-7026-49ff-83ad-3f59e54284e6.png)
![image](https://user-images.githubusercontent.com/128471527/226576587-7e86057e-e8f2-4f66-aa4f-f21b29b703a8.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/4044#issuecomment-1476464386 有相似反馈
