### ISSUE TITLE
工具>删除广告  如果打开，视频有声音，整个网页是黑色的。

### ISSUE THREAD

**Issue by lxl217114** [the1812/Bilibili-Evolved#4086]
### 对应功能

工具>删除广告  如果打开，视频有声音，整个网页是黑色的。
![image](https://user-images.githubusercontent.com/54263659/227126575-98b0ba72-3f00-4606-a77d-f630754c7c76.png)

### 问题描述

工具>删除广告  如果打开，视频有声音，整个网页是黑色的。
![image](https://user-images.githubusercontent.com/54263659/227126575-98b0ba72-3f00-4606-a77d-f630754c7c76.png)

### 脚本版本

v2.6.3

### 脚本管理器及版本

v2.14.0

### 浏览器及版本

Microsoft Edge 版本 111.0.1661.44 (正式版本) (64 位)

### 播放器版本

version: 4.0.1-rc.850.0

### 播放策略

默认

### 错误信息

```Shell
F12控制台无法搜索到bilibili evolved
```

### 附加截图

![image](https://user-images.githubusercontent.com/54263659/227126575-98b0ba72-3f00-4606-a77d-f630754c7c76.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
4.0 播放器都出来了😯

**Comment by Geeyun-JY3** [comment]
没想到我这边也上了 4.0 播放器，播放器版本号为 4.0.1-rc.868.0-f93946da
但无法复现：
![image](https://user-images.githubusercontent.com/49396421/227770714-9bbedd61-f512-4a89-8237-79b180fabdee.png)

Tampermonkey v4.18.1
Bilibili Evolved v2.6.3-41-g93cdffde0

**Comment by pencilqaq** [comment]
4.0.4-cfc84eb8 未复现
