### ISSUE TITLE
更新2.7.0后与「解除B站区域限制」这个脚本冲突。

### ISSUE THREAD

**Issue by Sabiary** [the1812/Bilibili-Evolved#4099]
### 对应功能

所有

### 问题描述

更新2.7.0后与这个脚本同时开启，视频页面脚本不生效，其他页面均生效。
https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6

### 脚本版本

预览版及正式版 2.7.0

### 脚本管理器及版本

暴力猴: 2.14.0

### 浏览器及版本

Microsoft Edge  111.0.1661.54 

### 播放器版本

version: 4.0.1-rc.868.0

### 播放策略

默认

### 错误信息

```Shell
BALH detected, Bilibili Evolved is disabled.
```

**Comment by the1812** [comment]
这是新加的功能, 感觉得加个开关
![image](https://user-images.githubusercontent.com/26504152/227781706-7ba7453f-7358-4e95-866b-1bc2a154b778.png)

**Comment by the1812** [comment]
已添加开关
https://github.com/the1812/Bilibili-Evolved/discussions/4095#discussioncomment-5432331
