### ISSUE TITLE
拖动进度条跳转会图标和读条错位

### ISSUE THREAD

**Issue by the1812** [the1812/Bilibili-Evolved#41]
![image](https://user-images.githubusercontent.com/35068322/50479076-af19c680-0a0f-11e9-9ed5-7afa78a7ffab.png)

_Originally posted by @aliofwind in https://github.com/the1812/Bilibili-Evolved/issues/40#issuecomment-450135902_

**Comment by the1812** [comment]
@aliofwind `166.16`版做了调整, 你看下还错位不

**Comment by aliofwind** [comment]
试了一下，可以了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Grant Howard <notifications@github.com>
发送时间: Saturday, December 29, 2018 7:45:58 PM
收件人: the1812/Bilibili-Evolved
抄送: aliofwind; Mention
主题: Re: [the1812/Bilibili-Evolved] 拖动进度条跳转会图标和读条错位 (#41)


@aliofwind<https://github.com/aliofwind> 166.16版做了调整, 你看下还错位不

―
