### ISSUE TITLE
直播全屏包裹全屏下会失效，网页全屏下样式有问题

### ISSUE THREAD

**Issue by CrazyboyQCD** [the1812/Bilibili-Evolved#4105]
### 对应功能

直播全屏包裹

### 问题描述

在屏幕全屏下没有包裹按钮，网页全屏下存在但是是透明的，悬浮时才会显示（强迫症希望与其他按钮改到同一高度）

### 脚本版本

v2.7.0-39-gac29c0ec6

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Microsoft Edge 111.0.1661.54

### 播放器版本

不相关

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/53971641/228222894-5de82aa3-d3aa-44bf-b6e3-e6d58f195928.png)
![image](https://user-images.githubusercontent.com/53971641/228222895-dbcd1d6a-3b84-4a0a-93dd-803559c2ba7a.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by pencilqaq** [comment]
全屏的 class名变了 所以不显示 包裹 图里这个字体颜色我没有复现

**Comment by the1812** [comment]
从来就没有支持过全屏, 描述里写得很清楚了, 以前全屏的那个是 b 站自带的
![image](https://user-images.githubusercontent.com/26504152/229292287-d5c1093b-ef0e-4c61-8762-896bbc60e6b5.png)

**Comment by CrazyboyQCD** [comment]
> 全屏的 class名变了 所以不显示 包裹 图里这个字体颜色我没有复现
这是包裹按钮的字体颜色#18191c，应该改成#eee和其他一样就行了

**Comment by CrazyboyQCD** [comment]
> 从来就没有支持过全屏, 描述里写得很清楚了, 以前全屏的那个是 b 站自带的 !

之前没注意到，当功能增强吧

**Comment by pencilqaq** [comment]
> > 从来就没有支持过全屏, 描述里写得很清楚了, 以前全屏的那个是 b 站自带的 !
> 
> 之前没注意到，当功能增强吧

对不起QAQ

**Comment by CrazyboyQCD** [comment]
那我再提几个样式问题吧

![image](https://user-images.githubusercontent.com/53971641/229292905-7d1abcad-36d2-4a94-8c9d-a4c9b4009d2a.png)
![image](https://user-images.githubusercontent.com/53971641/229292914-433ea3a2-cbdb-442c-8641-3c7c81bde3f2.png)
![image](https://user-images.githubusercontent.com/53971641/229292922-9cefa44e-a849-440b-803c-8294370ff23a.png)

背景颜色，开关和文字高度都是有问题的

**Comment by the1812** [comment]
> > 从来就没有支持过全屏, 描述里写得很清楚了, 以前全屏的那个是 b 站自带的 !
> 
> 之前没注意到，当功能增强吧

嗯, 这次按更新后的直播间再一起调整下

**Comment by pencilqaq** [comment]
> 那我再提几个样式问题吧
> 
> ![image](https://user-images.githubusercontent.com/53971641/229292905-7d1abcad-36d2-4a94-8c9d-a4c9b4009d2a.png) ![image](https://user-images.githubusercontent.com/53971641/229292914-433ea3a2-cbdb-442c-8641-3c7c81bde3f2.png) ![image](https://user-images.githubusercontent.com/53971641/229292922-9cefa44e-a849-440b-803c-8294370ff23a.png)
> 
> 背景颜色，开关和文字高度都是有问题的

这是哪个组件的问题？

**Comment by CrazyboyQCD** [comment]
> 这是哪个组件的问题？

就是这个组件移动包裹按钮后出现的样式错误

**Comment by pencilqaq** [comment]
> 全屏 → 打开礼物栏 → 网页全屏 → 关闭礼物栏 → 全屏

哈哈哈 还真是 全屏 打开包裹是 用bottom 调高的 网页全屏关闭包裹是 修改z-index 这么刁钻的bug也能找到哈哈哈哈哈哈哈
