### ISSUE TITLE
简化直播间隐藏付费礼物不完全

### ISSUE THREAD

**Issue by Alexius66** [the1812/Bilibili-Evolved#4108]
### 对应功能

简化直播间

### 问题描述

RT

### 脚本版本

v2.7.0-42-gc2ba4a36a

### 脚本管理器及版本

Tampermonkey 4.18.1

### 浏览器及版本

EDGE 111.0.1661.54

### 播放器版本

Bilibili Live Player 3.6.121

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![image](https://user-images.githubusercontent.com/73510996/228436759-1d39edb5-5b75-44e9-95bc-539654ba9997.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by pencilqaq** [comment]
全屏（非网页全屏）模式下的class发生了改变 变成了fullscreen-fix 只要加一个与运算就行了 我克隆到本地进行了修改 发现后面还有监听全屏模式状态的函数 但是太菜看不懂 不过经过我的测试不修改监听函数 只增加与运算 就可修复全屏状态下没有包裹按钮的问题 测试可能不全面 就没提交pr 留下回复 希望对作者又所帮助

**Comment by Lohartte** [comment]
脚本版本
**v2.7.1-50**-gdd29a9806

脚本管理器及版本
Tampermonkey 4.18.1

浏览器及版本
EDGE **113.0.1774.57** (正式版本) (64 位)

播放器版本
Bilibili Live Player **3.6.127**

播放策略
默认

![包裹栏](https://github.com/the1812/Bilibili-Evolved/assets/91640363/60b76343-a110-4f72-9f79-cedb38179b39)

**Comment by pencilqaq** [comment]
> 这两天系统更新后，问题重新出现 脚本版本 **v2.7.1-50**-gdd29a9806
> 
> 脚本管理器及版本 Tampermonkey 4.18.1
> 
> 浏览器及版本 EDGE **113.0.1774.57** (正式版本) (64 位)
> 
> 播放器版本 Bilibili Live Player **3.6.127**
> 
> 播放策略 默认
> 
> ![包裹栏](https://user-images.githubusercontent.com/91640363/242883536-60b76343-a110-4f72-9f79-cedb38179b39.png)

请你新开一个issus，如果作者在20号之前没有修复，我会在月底修复这个bug
