### ISSUE TITLE
简化首页功能开启后，在首页点击视频后地址栏BV号会自动变成AV号，导致部分功能失效

### ISSUE THREAD

**Issue by SEVLT** [the1812/Bilibili-Evolved#411]
简化首页功能开启后（清爽、极简风格均出现此bug），在首页点击视频去播放，跳转后地址栏BV号会自动变成AV号，导致部分功能失效，例如自动宽屏、定位视频框位置等

补充一定：bug只发生在“在首页点击视频”，而在个人动态中点击视频地址栏是正常的BV号

**Comment by the1812** [comment]
bv号会自动变成av号? 可是简化首页生成的所有链接本来就都是av号啊?
<img height="300" src="https://user-images.githubusercontent.com/26504152/77742423-678a4c00-7051-11ea-8a07-a47da58374fd.png">

**Comment by SEVLT** [comment]
> bv号会自动变成av号? 可是简化首页生成的所有链接本来就都是av号啊?
> <img alt="" height="300" src="https://user-images.githubusercontent.com/26504152/77742423-678a4c00-7051-11ea-8a07-a47da58374fd.png">

呃..主要是因为简化首页生成的是AV不是BV，其他功能（例如自动宽屏、定位播放器位置）会失效（BV下生效，AV下生效），所以简化首页这里如果生成是BV才是完美的吧

**Comment by the1812** [comment]
这些功能究竟是没有运行还是出错了? 能否提供控制台(<kbd>Ctrl+Shift+I</kbd>)的报错信息呢

**Comment by SEVLT** [comment]
> 这些功能究竟是没有运行还是出错了? 能否提供控制台(Ctrl+Shift+I)的报错信息呢
<img width="960" alt="1" src="https://user-images.githubusercontent.com/49136035/77755730-d030f300-7068-11ea-8b28-fce9f36a7cb5.png">
你好，控制台图片如上，edge只打开这一个插件，应该可以排除其他插件的影响。

**Comment by Coulomb-G** [comment]
你把「播放时应用模式」关了再试试,关了才是自动应用,开着是播放时应用

**Comment by SEVLT** [comment]
好吧。。。细心对比了下，原来不是这个插件的问题，排查后插件一切正常..麻烦开发者了。。。.
