### ISSUE TITLE
退出全屏后会退出宽屏(导致默认播放器模式暂时失效)

### ISSUE THREAD

**Issue by xiao-mantou** [the1812/Bilibili-Evolved#412]
**关于哪一项功能**

默认播放器模式

**问题描述**

退出全屏后一定会退出宽屏模式(恢复为`常规`),官方的逻辑希望您可以帮他一下

设置 `默认播放器模式` 为 `宽屏`,进入全屏,退出全屏.

**脚本版本**

预览离线版 619.11

**浏览器版本**

Edge(Chromium) 82

**Comment by the1812** [comment]
这其实不属于`默认播放器模式`的功能范围了, `默认播放器模式`只关心刚进入视频时的模式, 并不关心后续切换为其他的模式.
如果希望退出来仍是宽屏的话, 可以用网页全屏代替全屏, 网页全屏状态再点宽屏是可以退出网页全屏进入宽屏的.

**Comment by xiao-mantou** [comment]
当作建议的话怎么样?
我刚看了一下youtube,退出全屏是保留宽屏的,新视频不打开新标签页所以宽屏模式是可以保留的,新开视频也会使用上次的模式,点击任意位置就可以直接键盘快进,这些貌似都是"新"添加的,哇这youtube现在怎么看怎么舒服,bilibili还有播放器定位这种小问题,真的头疼.这些功能要是都能实现就好了.

**Comment by the1812** [comment]
退出全屏保留宽屏吗 就算能做出来我觉得也会怪怪的 所看到的会是先变成普通状态然后再跳到宽屏状态 不会像youtube那么流畅的
你实在需要我可以单独写个脚本 就不作为功能发布了

**Comment by xiao-mantou** [comment]
我以为可以像网页全屏退出到宽屏一样流畅,到就不麻烦您了,谢谢^^
