### ISSUE TITLE
特定情况下插件无法正常显示

### ISSUE THREAD

**Issue by Seukieee** [the1812/Bilibili-Evolved#4121]
### 对应功能

特定情况下插件无法正常显示，页面左侧没有按钮

### 问题描述

使用插件版本为V2.7.0 Preview版本+浏览器Edge Canary 113.0.1773.0时，左侧不显示组件，将插件或浏览器更换为正式版均能显示，详见PDF
[问题反馈.pdf](https://github.com/the1812/Bilibili-Evolved/files/11131324/default.pdf)

### 脚本版本

V2.7.0 Preview版本

### 脚本管理器及版本

Tampermonkey 4.18.1

### 浏览器及版本

Edge Canary 113.0.1773.0

### 播放器版本

4.0.4-cfc84eb8

### 播放策略

默认

### 错误信息

```Shell
无
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
看起来只是没翻墙的问题?
使用 Edge Canary 115.0.1866.0 / Tampermonkey 4.18.1 / Bilibili Evolved (Preview) 2.7.1 测试
![image](https://github.com/the1812/Bilibili-Evolved/assets/26504152/cf73ec54-c51d-429d-a7cd-5318e78e60c6)

----

打开梯子后
![image](https://github.com/the1812/Bilibili-Evolved/assets/26504152/45a59ec0-984b-4534-b6d7-c0563851d9ff)

**Comment by Seukieee** [comment]
![image](https://github.com/the1812/Bilibili-Evolved/assets/76165686/0ec57f17-ce41-4a32-80c9-325f44c1538a)
打开梯子后界面左侧依然不显示插件

**Comment by the1812** [comment]
看你的图里有用规则, 试下开全代理, 或者把 `githubusercontent.com` 设置为使用代理?

**Comment by Seukieee** [comment]
![image](https://github.com/the1812/Bilibili-Evolved/assets/76165686/8a54a187-f734-4100-b5cb-caed89ebbc53)
全代理似乎也没用。。。
对这方面也不是很了解，懒得捣鼓了，姑且先用正式版吧😂
