### ISSUE TITLE
视频传统连播功能有bug会导致自动点赞视频并且弹出投币界面

### ISSUE THREAD

**Issue by Ymr-zyh** [the1812/Bilibili-Evolved#4127]
### 对应功能

Commit: c2ba4a36a

### 问题描述

开启传统连播功能后打开视频会自动点赞当前视频 并且随后弹出投币界面  影响使用

### 脚本版本

v2.7.0-42-gc2ba4a36a

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

edge和chrome都试过

### 播放器版本

4.0.4

### 播放策略

默认

### 错误信息

```Shell
无
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by pencilqaq** [comment]
2.7 preview未复现

**Comment by Ymr-zyh** [comment]
> 2.7 preview未复现

麻了 但是确实是这个功能导致的  我挨个挨个关闭功能发现这个关了就好了

**Comment by pencilqaq** [comment]
> > 2.7 preview未复现
> 
> 麻了 但是确实是这个功能导致的 我挨个挨个关闭功能发现这个关了就好了

用预览版吧

**Comment by Ymr-zyh** [comment]
> 是不是按到键盘 `L` / `C` 了

不是呀  键盘正常 没有按键情况下都会   这段时间一直没开这个功能就是正常的

**Comment by the1812** [comment]
那就不知道咋回事了, 目前正式版只有这俩按键 + 快捷键扩展能触发点赞视频和投币

**Comment by Ymr-zyh** [comment]
> 那就不知道咋回事了, 目前正式版只有这俩按键 + 快捷键扩展能触发点赞视频和投币

问题不大 只要把这个功能关了就好  不太影响使用

**Comment by Ymr-zyh** [comment]
> 那就不知道咋回事了, 目前正式版只有这俩按键 + 快捷键扩展能触发点赞视频和投币

![image](https://user-images.githubusercontent.com/59598094/234333550-a13dfd18-8eb0-4db0-8388-36276963ccf4.png)
这是我刚刚测试的打开这个功能就能看到打开视频就回弹出这个   但是具体你们不能复现我也没有办法

**Comment by Ymr-zyh** [comment]
![image](https://user-images.githubusercontent.com/59598094/234333745-978ec793-8784-4cca-ab2b-ad5e46295cc0.png)

**Comment by GalaxySnail** [comment]
有没有可能和其它浏览器拓展或者脚本冲突了，关掉所有在B站生效的浏览器拓展和油猴脚本然后试试？

**Comment by linyinian** [comment]
> ![image](https://user-images.githubusercontent.com/59598094/234333745-978ec793-8784-4cca-ab2b-ad5e46295cc0.png)

一直想去掉这个弹窗，目前是没有这个功能吗 @the1812

**Comment by the1812** [comment]
> > ![image](https://user-images.githubusercontent.com/59598094/234333745-978ec793-8784-4cca-ab2b-ad5e46295cc0.png)
> 
> 一直想去掉这个弹窗，目前是没有这个功能吗 [@the1812](https://github.com/the1812)

没有
