### ISSUE TITLE
首页运行正常，视频播放页失效

### ISSUE THREAD

**Issue by Little-YangQi** [the1812/Bilibili-Evolved#4133]
### 对应功能

/

### 问题描述

插件首页运行正常，打开视频播放页后失效，与未安装时相同

### 脚本版本

v2.7.0-46-g91e80d9c5

### 脚本管理器及版本

 Tampermonkey v4.18.1

### 浏览器及版本

Microsoft Edge 112.0.1722.34 (正式版本) (64 位)

### 播放器版本

4.0.4-cfc84eb8

### 播放策略

默认

### 错误信息

```Shell
userscript.html?name=Bilibili%2520Evolved.user.js&id=f1209cb7-b177-4e10-af61-e30d182ae236:248 BALH detected, Bilibili Evolved is disabled.
```

### 附加截图

![p1](https://user-images.githubusercontent.com/130209769/230708952-6e12b65b-a731-4d8e-aeaa-6b6338d4b7cf.png)
![p2](https://user-images.githubusercontent.com/130209769/230708953-23cf1d7f-980a-4c38-afa8-60eb6f1d2876.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by thouser8** [comment]
你是不是同时使用了解除港澳台限制的脚本？目前我也发现了此问题，关闭解除限制脚本即可恢复这个脚本在视频页的使用。

**Comment by Little-YangQi** [comment]
> 你是不是同时使用了解除港澳台限制的脚本？目前我也发现了此问题，关闭解除限制脚本即可恢复这个脚本在视频页的使用。

还真是，刚把解除区域限制关了就能用了，但我两个月前用的时候两个插件是不冲突的。。。

**Comment by Geeyun-JY3** [comment]
看更新日志：https://github.com/the1812/Bilibili-Evolved/discussions/4095#discussioncomment-5432331
