### ISSUE TITLE
直播经常不加载弹幕，右侧评论也完全不更新

### ISSUE THREAD

**Issue by blackacrow** [the1812/Bilibili-Evolved#4146]
### 对应功能

直播经常不加载弹幕，右侧评论也完全不更新

### 问题描述

点进直播很大概率完全不更新弹幕，当时看还以为压根没人发弹幕呢，结果一刷新右侧发言栏是全新的言论，而且是大概率出现，如果想看弹幕，就只能不断刷新，直到刷新出会滚动的界面。
我测试过，关了这个脚本，变成B站原生直播间是能看到有人发弹幕的。所以应该是脚本问题

### 脚本版本

v2.7.0-46-g91e80d9c5 

### 脚本管理器及版本

4.18.1

### 浏览器及版本

火狐v2.7.0-46-g91e80d9c5 

### 播放器版本

4.0.9

### 播放策略

默认

### 错误信息

```Shell
无
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by blackacrow** [comment]
![图片](https://user-images.githubusercontent.com/43438263/232786759-52b0a46d-ddbd-45d1-9d6d-0e13314acfdc.png)

**Comment by lovelyCARDINAL** [comment]
B站原生直播间也可能出现这种情况

**Comment by plokid** [comment]
@blackacrow @lovelyCARDINAL  我也遇到一样的问题，请问有解决方法吗？

**Comment by hafeoz** [comment]
如果还有人有类似的问题，可以按照下面的思路排查：

1. 右键播放器查看日志信息，如果有websocket相关的问题那应该是网络问题。如果没有那可能是弹幕过滤的问题。
2. 网络问题：确认uBlock或者其他拦截器是不是拦截了`chat.bilibili.com`。这个域名被B站用来收集数据，因此很多非国内的拦截名单都会拉黑这个域名，导致直播弹幕加载不出来。可以使用`@@||*.chat.bilibili.com/sub$websocket,domain=live.bilibili.com`来针对`/sub`弹幕路径白名单过滤。
3. 弹幕过滤问题：弹幕发送框上面有个全局过滤选项，确认是不是拉到了最大。
