### ISSUE TITLE
通用 - 主题颜色 - 部分区域无法显示自定义主题颜色

### ISSUE THREAD

**Issue by MafiaLee** [the1812/Bilibili-Evolved#4148]
### 对应功能

通用-主题颜色
Commit: ac29c0ec6
内部名称: settingsPanel
![Screenshot 2023-04-19 142315](https://user-images.githubusercontent.com/22052560/232984517-81e93f7f-8ad0-418d-9742-17d23f0d396b.png)

### 问题描述

任一视频页面；
夜间模式开启时自定义颜色（我的为红色）显示正常；但当夜间模式关闭时，页面中，一部分主题颜色（如播放进度条、页面按钮）无法显示自定义颜色（仍保持b站蓝色），如图2。
![Screenshot 2023-04-19 140326](https://user-images.githubusercontent.com/22052560/232981269-3e402875-b1b0-4afa-a4f6-e5fad3d337e5.png)
![Screenshot 2023-04-19 140719](https://user-images.githubusercontent.com/22052560/232982003-56b70cbb-debf-4c73-b126-6beb86f4ba1a.png)

### 脚本版本

v2.7.0-39-gac29c0ec6

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Microsoft Edge Version 112.0.1722.48 (Official build) (64-bit)

### 播放器版本

4.0.9-78070b4b

### 播放策略

默认

### 错误信息

```Shell
如图
```

### 附加截图

![Screenshot 2023-04-19 135745](https://user-images.githubusercontent.com/22052560/232980341-dd2cc47d-476f-48e4-8086-bcc664d5598f.png)
![Screenshot 2023-04-19 135800](https://user-images.githubusercontent.com/22052560/232980357-6f5e03f7-d7cf-4f99-907f-4a4d0e4e8f26.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
这个就是夜间模式的特性 没开的话只有脚本提供的界面里会使用主题颜色

**Comment by MafiaLee** [comment]
好的，感谢解答。
