### ISSUE TITLE
动态过滤插件【按类型筛选】的功能在某些情况下失效

### ISSUE THREAD

**Issue by qaqz111** [the1812/Bilibili-Evolved#4149]
### 对应功能

动态过滤

### 问题描述

当前版本必须在动态首页【全部动态 - 全部】的状态下切换至单个UP动态才能针对单个UP正常使用【按类型筛选】的功能。
在【全部动态 - 视频投稿/追番追剧/专栏】状态下切换至单个UP，则【按类型筛选】功能会保持屏蔽状态且按类型筛选功能无效。

【动态筛选】插件对形如【 https://t.bilibili.com/?tab=(video|pgc|article) 】的 url（直接地址栏键入转到）不会启用【按类型筛选】的功能。
另外，在切换过一次单个UP动态列表后，【按类型筛选】功能的启用状态就不会再发生改变（不按F5刷新页面的情况下，【切换至单个UP动态列表之前】【按类型筛选】功能没启用就一直不会启用，否则就会一直保持可用）。

重现步骤：

1. 进入【动态】首页【 https://t.bilibili.com/ 】

2. 此时在中栏圆形头像UP列表里应默认选中【全部动态】，下一行的分类标签应是默认选中【全部】。
点击分类标签的【视频投稿】，浏览器地址栏 url 变更为【 https://t.bilibili.com/?tab=video 】。
此时【动态筛选】插件中【按类型筛选】的部分消失。

3. 点击中栏圆形头像UP列表里任意一个UP头像，【动态筛选】插件中【按类型筛选】的部分仍然不会出现，
且动态列表会显示该UP的所有类型动态，此时浏览器地址栏 url 仍然为【 https://t.bilibili.com/?tab=video 】。

B站动态的官方设计并没有提供针对单个UP按内容筛选的功能，因此【动态筛选】插件在此处特别有用。
但是该插件在按上述操作流程切换到单个UP动态的时候没有将【按类型筛选】的功能打开，疑似 Bug。

### 脚本版本

v2.7.0-46-g91e80d9c5

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Microsoft Edge 版本 112.0.1722.48 (正式版本) (64 位)

### 播放器版本

4.0.9-78070b4b

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved updated widgets Array(0)
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
#3917

**Comment by the1812** [comment]
> #3917

跟新版动态没关系, 旧版也有

**Comment by qaqz111** [comment]
是的新旧两版页面都有这个问题，但也不算是太严重的bug，解决办法很简单，手动去掉 url 后面的 ?tab=XXX，或者切换到【全部动态-全部】之后 F5 刷新一下就可以了。
