### ISSUE TITLE
建议增加下载视频为mp3

### ISSUE THREAD

**Issue by MrTC1277** [the1812/Bilibili-Evolved#415]
就只下载视频中的声音
下载了在转换有点麻烦
_(:з」∠)_

**Comment by the1812** [comment]
下DASH格式就行了, `.m4a`后缀的就是音频

**Comment by fox010** [comment]
还是有一丢丢麻烦，因为可能这次临时下音频，下次还是下视频，要再选回来

**Comment by Coulomb-G** [comment]
dash是包含音频,不是只有音频

**Comment by the1812** [comment]
那要是有mp3格式 下次下视频还不是得选回来?
