### ISSUE TITLE
自定义顶栏插件导致B站顶栏显示异常

### ISSUE THREAD

**Issue by abcofabc** [the1812/Bilibili-Evolved#4156]
### 对应功能

自定义顶栏 
Commit: 1b524b518

### 问题描述

启用自定义顶栏会导致大部分页面的顶栏的右侧功能全部消失，只剩下未登录按钮与投稿按钮，但是并没有掉登录，关闭该功能即正常

![image](https://user-images.githubusercontent.com/30181838/234047237-1fc3454c-0c65-4da8-9cd3-25b6a12cb349.png)

![image](https://user-images.githubusercontent.com/30181838/234047275-f711ce79-a63c-47b8-938a-3dc5f2f0f076.png)

### 脚本版本

v2.6.0-21-g5b8d9acf1

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Microsoft Edge 版本 112.0.1722.58 (正式版本) (64 位)

### 播放器版本

4.0.9-78070b4b

### 播放策略

默认

### 错误信息

```Shell
在下面
```

### 附加截图

![image](https://user-images.githubusercontent.com/30181838/234048450-9914eb4e-fb1f-4466-9001-7b5e06d64fc9.png)
![image](https://user-images.githubusercontent.com/30181838/234048482-9fc36fe4-7142-451d-8cef-cb20906b86ac.png)

错误信息
![image](https://user-images.githubusercontent.com/30181838/234049125-8d292c03-4587-439f-827d-3beb84c449c4.png)
![image](https://user-images.githubusercontent.com/30181838/234049240-a9452595-d85b-433d-b664-c6768a5671ea.png)
![image](https://user-images.githubusercontent.com/30181838/234049290-735f0d0f-7a34-4927-8880-d52e961b01cc.png)
![image](https://user-images.githubusercontent.com/30181838/234049344-6b8aaf04-4148-409a-b579-ae08431a06f1.png)
![image](https://user-images.githubusercontent.com/30181838/234049401-0256e98e-22e1-4aa5-88fb-706a60052311.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
建议你先将脚本本体和`自定义顶栏`组件更新至最新版，2.6.0 已经是四个月前的版本了。

**Comment by the1812** [comment]
开原版, 退出登录, 重新登录, 再开自定义顶栏

**Comment by abcofabc** [comment]
> 开原版, 退出登录, 重新登录, 再开自定义顶栏

感谢开发大佬的协助，重置浏览器设置后恢复正常
