### ISSUE TITLE
拜托大佬加入透明度设置惹...

### ISSUE THREAD

**Issue by Noah1995** [the1812/Bilibili-Evolved#416]
拜托大佬加入透明度自定义设置惹...
最好是磨砂透明..
还有最好可以把个人资料丶直播丶公告栏和话题
放在同一边垂直排列...
让用户选择居左和局右...
内容可以稍微设置宽屏一点...
下面是效果图
还有建一个qq群鸭...
![【2020-03-29】【16∶25∶26】](https://user-images.githubusercontent.com/25548230/77844513-0477f100-71da-11ea-9c29-7c4aaff8ceef.jpg)

**Comment by the1812** [comment]
磨砂透明浏览器不支持

**Comment by Noah1995** [comment]
backdrop-filter:blur
好像叫毛玻璃

**Comment by the1812** [comment]
这东西Chrome掉帧, Firefox不支持, Safari未知  目前是完全没法用
你可以自己装个Stylus写点backdrop-filter玩玩

**Comment by Noah1995** [comment]
![9V(}1B@9X2%KO6MO4Y_VC9T](https://user-images.githubusercontent.com/25548230/77850260-d60f0b80-7203-11ea-9424-ffb01367bb03.gif)
嘤嘤嘤...
只能忍痛接受...
