### ISSUE TITLE
视频播放器玄学收缩！

### ISSUE THREAD

**Issue by ToneySun** [the1812/Bilibili-Evolved#417]
**问题描述**
有些页面会播放器会自动收缩关闭！我关闭脚本就正常了，开启脚本有一些页面就会玄学收缩！例如：https://www.bilibili.com/video/BV1hE41147jk

**脚本版本**
1.10.12

**浏览器版本**
版本 71.0.3578.80（正式版本） （64 位）

**错误信息**
没有错误信息！！！

**附加截图**

![bilibug](https://user-images.githubusercontent.com/18101168/77852736-d531a600-7212-11ea-86ec-89d01a998eaa.jpg)

**Comment by Coulomb-G** [comment]
先把其他插件关了再看看?

**Comment by the1812** [comment]
见#379和#254

**Comment by ToneySun** [comment]
感谢！最后找到问题了，是另一款关闭b站的脚本开着，两个脚本可能起了冲突。把另外一款关闭，就好了，感谢作者写这么奶思的脚本，感谢！
