### ISSUE TITLE
直播间粉丝勋章更换功能bug

### ISSUE THREAD

**Issue by regentropfen2013** [the1812/Bilibili-Evolved#4181]
### 对应功能

Commit: dd29a9806

### 问题描述

粉丝勋章超过169个时，UI显示会过于靠上，显示不全

左图是正常显示不全的情况
右图是网页35%缩放的情况
![屏幕截图 2023-05-05 004817](https://user-images.githubusercontent.com/62187507/236273192-d42dc5fb-22d9-4c84-98c1-65418f8aed85.png)

### 脚本版本

v2.7.1-45-ga98c3b36d

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Microsoft Edge 版本 112.0.1722.68 (正式版本) (64 位)

### 播放器版本

3.6.123

### 播放策略

AVC

### 错误信息

```Shell
无
```

### 附加截图

![屏幕截图 2023-05-05 004817](https://user-images.githubusercontent.com/62187507/236274729-8ec9de99-6ad1-4579-8984-837bfd23b860.png)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by ZiuChen** [comment]
模拟了一下超过169个牌子的情况，牌子展示时似乎都是纵向排列的？

`Chrome 113`和`Edge 113`都是一样的结果

是不是有其他因素影响到了布局？比如其他组件或者其他拓展插件

> <img width="100%" src="https://github.com/the1812/Bilibili-Evolved/assets/64892985/b54723f5-f655-4ac8-8d49-f5239ba684e3" />

**Comment by regentropfen2013** [comment]
> 模拟了256个牌子的情况，在不同屏幕尺寸下都没有出现越界的情况：
> 
> > ![image1](https://user-images.githubusercontent.com/64892985/238113978-5b040ea1-598c-4084-8684-9d24a2567a7c.png)
> > ![image2](https://user-images.githubusercontent.com/64892985/238114127-8f852ffe-513c-4cb5-a27b-debc41b57f4c.png)
> 
> 弹出框始终与屏幕上下界保持了一定的距离，`Chrome 113`和`Edge 113`都是一样的结果
> 
> 考虑检查一下是不是有其他影响样式的因素，比如其他组件或拓展插件？

试了下，关掉了所有的其他插件和脚本，仍然是是超出的；但是同样的Bilibili-Evolved设置导出到Firefox，那边的显示又是正常的

**Comment by ZiuChen** [comment]
有没有在Chrome浏览器上测试一下呢？

**Comment by regentropfen2013** [comment]
> 

找到原因了，功能页面的功能越多，这个显示就越不全；整个牌子的展开框是跟着【更换勋章】定位的，其他【更换头衔】【简化直播间】【瓜子换硬币】【直播间签到】【返回原版直播间】【替换更新链接】等功能都是在【更换勋章】下方，会把【更换勋章】连着牌子的展开框往上顶，然后会显示不全。

**Comment by the1812** [comment]
目前最大列数设置为 6 了, 以最小支持分辨率的宽度 1440 来看, 最多可以扩充到 15 列, 应该能解决这个问题
