### ISSUE TITLE
直播间的金宝箱打不开了

### ISSUE THREAD

**Issue by HYY-zh** [the1812/Bilibili-Evolved#420]
直播间左下角的金宝箱打开后只有“本轮奖品”4个字，内容都没了，只有把脚本关了之后才出现，估计是脚本给弄没的("▔□▔)/

**脚本版本**
正式版1.10.12

**浏览器版本**
80.0.3987.149（正式版本） （64 位）

**附加截图**
开启脚本：
![只开启脚本](https://user-images.githubusercontent.com/61227595/77909126-5a729480-72bf-11ea-9684-1e5838280419.png)
关闭脚本：
![关闭了脚本](https://user-images.githubusercontent.com/61227595/77909171-75450900-72bf-11ea-8320-f61950c97b4e.png)

**Comment by the1812** [comment]
能不能确认到某个功能上呢? 整个脚本范围太大了我也不知道是哪里的问题

**Comment by HYY-zh** [comment]
等我看看哪里有金宝箱我再试试看

**Comment by HYY-zh** [comment]
刚刚试了一下，在我的设置下，关闭了网址参数清理，金宝箱内容就能正常显示了
打开了网址参数清理：
![打开了网址参数清理](https://user-images.githubusercontent.com/61227595/79300317-e8ce5380-7f18-11ea-8567-b0440233e28d.png)
关闭了网址参数清理：
![关闭了网址参数清理](https://user-images.githubusercontent.com/61227595/79300342-fd125080-7f18-11ea-9ed3-07f9a39acc63.png)
我的配置文件：
[bilibili-evolved-settings.zip](https://github.com/the1812/Bilibili-Evolved/files/4479198/bilibili-evolved-settings.zip)

**Comment by the1812** [comment]
明白了  下次更新将会修复

**Comment by HYY-zh** [comment]
大佬要不要亲自试试，我怕是我其他设置的问题_(:3」∠)_

**Comment by the1812** [comment]
试过了 确实是因为这个
