### ISSUE TITLE
清爽首页下b站首页错位

### ISSUE THREAD

**Issue by amlkiller** [the1812/Bilibili-Evolved#4209]
### 对应功能

清爽首页
Commit: f64801060
内部名称: freshHome

### 问题描述

首页 推荐/热门和动态的位置下移，并且左右切换消失，出现在网页右侧。
![image_159](https://github.com/the1812/Bilibili-Evolved/assets/62412330/f2aed384-b317-4ba0-9a0d-236c21fa6c09)
![image_160](https://github.com/the1812/Bilibili-Evolved/assets/62412330/646004ed-dd62-47c1-bebc-fe9c6c707223)
![image_161](https://github.com/the1812/Bilibili-Evolved/assets/62412330/b7282bf3-ae24-4292-b142-95e80ea6cfff)

### 脚本版本

 v2.7.1-preview-73-gf64801060

### 脚本管理器及版本

Tampermonkey v4.19.6183

### 浏览器及版本

Google Chrome 115.0.5773.4

### 播放器版本

V4.0.3

### 播放策略

AV1

### 错误信息

```Shell
附加截图
```

### 附加截图

![image_158](https://github.com/the1812/Bilibili-Evolved/assets/62412330/0093b70e-0761-4150-bad7-ba0d23fe65f5)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Alexius66** [comment]
使用edge dev 115.0.1866.1版本也有此问题，但是使用edge 113.0.1774.50就可以正常使用

**Comment by Whale-Dolphin** [comment]
更新到edge-dev版本 115.0.1880.1 (正式版本) dev (64 位)后该问题解决

**Comment by amlkiller** [comment]
> 更新到edge-dev版本 115.0.1880.1 (正式版本) dev (64 位)后该问题解决

应该是回退吧？

**Comment by amlkiller** [comment]
Chrome 116.0.5803.2 后问题解决。

**Comment by Whale-Dolphin** [comment]
> Chrome 116.0.5803.2 后问题解决。

你这么说看版本号确实，但我确实是更新以后是这个版本号的emmm
