### ISSUE TITLE
DASH api failed

### ISSUE THREAD

**Issue by chenyinchao** [the1812/Bilibili-Evolved#421]
环境：
下载格式为：flv

点击aria2 RPC后，弹出错误弹窗“DASH api failed”，这个是什么回事

**Comment by the1812** [comment]
哪个视频

**Comment by geekqiao** [comment]
> 哪个视频

https://www.bilibili.com/video/av14426931

错误
DASH api failed
o@eval line 2 > eval line 15978 > eval:1:627

**Comment by the1812** [comment]
老视频那个年代没有dash格式的 当然会失败
