### ISSUE TITLE
简化直播间-标题栏活动 显示异常

### ISSUE THREAD

**Issue by pinaZC** [the1812/Bilibili-Evolved#4215]
### 对应功能

简化直播间
Commit: f64801060
内部名称: simplifyLiveroom

### 问题描述

屏蔽【标题栏活动】后
1.看过、点赞、举报、分享 位置错误，超出标题栏
2.点击 粉丝团-助力打榜，弹出页面在页面最左侧，并且显示不全，无法关闭
![image](https://github.com/the1812/Bilibili-Evolved/assets/72682556/6a504734-9218-4132-8def-0c60f484829a)

### 脚本版本

v2.7.1-49-g261f1b61a

### 脚本管理器及版本

Tampermonkey 4.18.1

### 浏览器及版本

Microsoft Edge 版本 113.0.1774.50 (正式版本) (64 位)

### 播放器版本

RoomPlayer version: 3.6.126

### 播放策略

默认

### 错误信息

```Shell
无
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by pencilqaq** [comment]
> ### 对应功能
> 简化直播间 Commit: [f648010](https://github.com/the1812/Bilibili-Evolved/commit/f64801060d2d83daeba6eebb3462941893da548d) 内部名称: simplifyLiveroom
> 
> ### 问题描述
> 屏蔽【标题栏活动】后 1.看过、点赞、举报、分享 位置错误，超出标题栏 2.点击 粉丝团-助力打榜，弹出页面在页面最左侧，并且显示不全，无法关闭 ![image](https://user-images.githubusercontent.com/72682556/240300311-6a504734-9218-4132-8def-0c60f484829a.png)
> 
> ### 脚本版本
> v2.7.1-49-g261f1b61a
> 
> ### 脚本管理器及版本
> Tampermonkey 4.18.1
> 
> ### 浏览器及版本
> Microsoft Edge 版本 113.0.1774.50 (正式版本) (64 位)
> 
> ### 播放器版本
> RoomPlayer version: 3.6.126
> 
> ### 播放策略
> 默认
> 
> ### 错误信息
> ```shell
> 无
> ```
> 
> ### 附加截图
> _No response_
> 
> ### 致遇到了相同问题准备回复的人
> **太长不看**： 1、遇到了相同的问题：**请用左下角的 reaction 点赞** 2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。 **_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
> 
> 完整版

官方原版 就没有助理打榜的关闭功能 点左上角返回然后可以关闭  所以我不会添加关闭红能
 但我会修复错位问题

**Comment by the1812** [comment]
我重开是打算看看打榜，错位已经修掉了
