### ISSUE TITLE
顶栏->动态，看过的视频/番剧/专栏仍显示为New

### ISSUE THREAD

**Issue by youngerstar** [the1812/Bilibili-Evolved#422]
**关于哪一项功能**
顶栏->动态的内容

**问题描述**

在顶栏->动态里，看过的视频/番剧/专栏仍显示New角标

**脚本版本**

1.10.12

**浏览器版本**

Firefox Beta 75.0b11

**错误信息**

**附加截图**
![图片](https://user-images.githubusercontent.com/46211595/78022541-b143a100-7387-11ea-85d5-6e355427e59e.png)
![图片](https://user-images.githubusercontent.com/46211595/78022564-bdc7f980-7387-11ea-9868-95a710793358.png)

**Comment by the1812** [comment]
cookie可能乱了 清一下cookie重新登录试试

**Comment by youngerstar** [comment]
> cookie可能乱了 清一下cookie重新登录试试

登录后刷新页面后正常了
