### ISSUE TITLE
建议在动态页面也能在鼠标移动到自定义顶栏的动态按钮后显示视频等更新页面

### ISSUE THREAD

**Issue by LiamSho** [the1812/Bilibili-Evolved#423]
**关于哪一项功能**
自定义顶栏->动态按钮

**期望的效果**
在动态页面将鼠标放到动态按钮后也能显示这样的窗口，现在在动态页面将鼠标放在动态按钮后不会显示，原版的网页是可以的，这样查看视频更新信息要方便不少
![image](https://user-images.githubusercontent.com/28832398/78096997-ab909e80-740d-11ea-8e11-5373f647a889.png)
在动态页不会有显示：
![image](https://user-images.githubusercontent.com/28832398/78097249-6325b080-740e-11ea-9e58-606c3c7771c4.png)

**脚本版本**
正式版1.10.12

**其他东西的版本**
Google Chrome 80.0.3987.149
Tampermonkey v4.9

**Comment by the1812** [comment]
动态页面里的内容就是和弹窗里一样的啊, 何必再去看那个弹窗?

**Comment by LiamSho** [comment]
弹窗里显示的视频的更新，这样不必在动态网页的“全部”和“投稿视频”两栏里切换， 信息密集度也高
