### ISSUE TITLE
能切换成中文吗？我的安装默认是英文状态！

### ISSUE THREAD

**Issue by fansuregrin** [the1812/Bilibili-Evolved#424]
请问能切换成中文吗？我的安装默认是英文状态，看了chrome的设置，默认的语言是简体中文，在脚本设置中找了半天，发现没有切换语言的按钮，只有一个UI 翻译，翻译English和日本语。请求指导？谢谢！

**Comment by fansuregrin** [comment]
谢谢！关掉就可以了！

**Comment by ground0start** [comment]
哇，找了半天没找到，请问是在tampermonkey的设置还是这个脚本的设置里面哇？

**Comment by the1812** [comment]
脚本设置里`UI Translation`

**Comment by fansuregrin** [comment]
UI Translation前面的按钮关闭即可

**Comment by ground0start** [comment]
大佬原来github都是秒回的嘛 哭了

**Comment by ground0start** [comment]
![image](https://user-images.githubusercontent.com/38744485/78116779-ca257400-73d2-11ea-8854-216641b9df32.png)

![image](https://user-images.githubusercontent.com/38744485/78116817-d6113600-73d2-11ea-9a3d-dbca581e00ed.png)

我是这样的...麻烦了

**Comment by fansuregrin** [comment]
哔哩哔哩界面，点开齿轮按钮，在里面找

**Comment by ground0start** [comment]
对不起 我没去看README 打扰了

**Comment by fansuregrin** [comment]
![Snipaste_2020-04-01_16-41-52](https://s1.ax1x.com/2020/04/01/G3Ng7d.png)

**Comment by ground0start** [comment]
找到了！

**Comment by ground0start** [comment]
我从一开始就没看到左边边上的两个小的UI 就是从greasyfork下下来之后根本没懂怎么用(也算是个用户反馈吧）（我瞎

**Comment by the1812** [comment]
能来GitHub就好, 你要是发在GreasyFork反馈估计两三天都没人理你(

**Comment by ground0start** [comment]
阿里嘎多！开发赛高！

**Comment by fansuregrin** [comment]
咦，作者大大，为什么那个翻译功能默认是开启的呀~一上来就是英文界面，我一个小白实在懵了😆这个脚本蛮好的，谢谢开发！

**Comment by the1812** [comment]
首次运行会匹配浏览器语言

**Comment by fansuregrin** [comment]
哦哦 懂了😊
