### ISSUE TITLE
最近下載畫質沒有1080P選項

### ISSUE THREAD

**Issue by YheonYeung** [the1812/Bilibili-Evolved#4241]
### 对应功能

下載視頻

### 问题描述

習慣下載影片再看，最近2.7.1及2.7.2想下載1080P都沒這個畫質。
上個禮拜0528的雖然未看，但那時能下載1080P，見potplayer擷圖。
https://www.bilibili.com/video/BV1eW4y1R7fy/

### 脚本版本

2.7.2

### 脚本管理器及版本

Tampermonkey 4.19.0

### 浏览器及版本

Chrome 114.0.5735.91 (正式版本) (64 位元)

### 播放器版本

4.1.17-d9e7a49b

### 播放策略

AVC

### 错误信息

```Shell
Bilibili Evolved updated widgets Array(3)
userscript.html?name=Bilibili-Evolved.user.js&id=f8607aef-1633-470d-88f9-191aeac7a05d:226 Bilibili Evolved Object Object
userscript.html?name=Bilibili-Evolved.user.js&id=f8607aef-1633-470d-88f9-191aeac7a05d:226 Bilibili Evolved [updateTestVideoInfo] Object
userscript.html?name=Bilibili-Evolved.user.js&id=f8607aef-1633-470d-88f9-191aeac7a05d:226 Bilibili Evolved [updateTestVideoInfo] Object
userscript.html?name=Bilibili-Evolved.user.js&id=f8607aef-1633-470d-88f9-191aeac7a05d:226 Bilibili Evolved ScrollTrigger Intersection Observer trigger
```

### 附加截图

![image](https://i.imgur.com/EQDAxxE.png)
![image](https://github.com/the1812/Bilibili-Evolved/assets/63342274/89967e6d-e6d1-428d-917a-46019974f08b)

**Comment by the1812** [comment]
flv 格式早就被 b 站砍画质了, 早点习惯 dash 吧
