### ISSUE TITLE
夜间模式下首页“推广”处视频题目不显示

### ISSUE THREAD

**Issue by wangqs97** [the1812/Bilibili-Evolved#425]
**关于哪一项功能**
夜间模式

**问题描述**
夜间模式下首页“推广”处视频题目不显示，光标移上去后才显示。

**脚本版本**
正式版1.10.12

**浏览器版本**
MAC端Safari13.0.5 (15608.5.11)，即最新版

**附加截图**
<img width="1120" alt="iShot2020-04-01下午10 36 22" src="https://user-images.githubusercontent.com/55077238/78149990-3fdc1f00-7469-11ea-927b-cf381e411eff.png">

**Comment by the1812** [comment]
夜间模式目前还没有覆盖到广告类的区域, 可以先打开`删除广告`隐藏掉这一块

**Comment by wangqs97** [comment]
了解，感谢回复
