### ISSUE TITLE
清爽首页错位

### ISSUE THREAD

**Issue by LockRim** [the1812/Bilibili-Evolved#4258]
### 对应功能

清爽首页
Commit: 65362f05f
内部名称: freshHome

### 问题描述

![image](https://github.com/the1812/Bilibili-Evolved/assets/52944370/e39f991f-fd92-48db-860e-d98e70a65ebc)
推荐 动态 分区的长度特别长

### 脚本版本

v2.8.0-preview-77-g7e99bde31

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

116.0.5829.0-dev （64 位）

### 播放器版本

4.1.18-e5c66460

### 播放策略

AV1

### 错误信息

```Shell
如图
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/52944370/6558185f-4a6a-4851-a442-5ef6498815f5)
![image](https://github.com/the1812/Bilibili-Evolved/assets/52944370/1f0bd45c-ab91-44d3-bf73-598fe509c9f2)

**Comment by the1812** [comment]
#4258?

**Comment by LockRim** [comment]
是的，回退到116.0.5817.0-dev版本后修复
