### ISSUE TITLE
开启清爽首页后，主界面的“推荐”栏宽度异常

### ISSUE THREAD

**Issue by 408723679** [the1812/Bilibili-Evolved#4261]
### 对应功能

Commit: 81aba0ace

### 问题描述

打开清爽首页并查看极简首页为关闭状态，首页的“推荐”栏显示宽度异常

### 脚本版本

v2.8.0-preview-77-g7e99bde31

### 脚本管理器及版本

篡改猴 4.19.0

### 浏览器及版本

Chrome版本 114.0.5735.134（正式版本） （64 位）

### 播放器版本

4.1.19-rc.1660.0

### 播放策略

默认

### 错误信息

```Shell
已附截图
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/36323933/38885a62-a836-4167-b721-f6742ace5980)
![image](https://github.com/the1812/Bilibili-Evolved/assets/36323933/73e61567-288e-4305-8718-ea0e44240274)

**Comment by the1812** [comment]
#4236

**Comment by 408723679** [comment]
> #4236

感谢，确实出现了更新后并未替换版本的情况，也是卸载后重新安装后解决
