### ISSUE TITLE
[Bug]清爽主页样式丢失

### ISSUE THREAD

**Issue by misaka10843** [the1812/Bilibili-Evolved#4266]
### 对应功能

![image](https://github.com/the1812/Bilibili-Evolved/assets/69132853/0903be95-99d3-49af-8b65-c27cf1e2b188)

### 问题描述

在首页中，启动清爽主页会导致部分样式无法被渲染，在将Tampermonkey中其他脚本禁用后也还是会出现此情况

![image](https://github.com/the1812/Bilibili-Evolved/assets/69132853/d8185ef5-a940-41e5-bc69-aa10719b6848)

但是在加载b站的内容之前，可以正常渲染（可以查看附加截图中的Lighthouse测试截图）

Bilibili-Evolved尝试过正式版以及测试版都无果，将其他组件全部禁用后也无果

### 脚本版本

v2.7.2-57-g3b6d87c8a

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

Chrome 116.0.5829.0 dev

### 播放器版本

4.1.19-rc.1660.0-897184dc

### 播放策略

AVC

### 错误信息

```Shell
userscript.html?name=Bilibili-Evolved.user.js&id=3f71be0f-26dc-47da-98f2-b78e3bb440ea:227 Bilibili Evolved 简化首页 isHome true
userscript.html?name=Bilibili-Evolved.user.js&id=3f71be0f-26dc-47da-98f2-b78e3bb440ea:227 Bilibili Evolved getContent 动画
userscript.html?name=Bilibili-Evolved.user.js&id=3f71be0f-26dc-47da-98f2-b78e3bb440ea:227 Bilibili Evolved {…}
userscript.html?name=Bilibili-Evolved.user.js&id=3f71be0f-26dc-47da-98f2-b78e3bb440ea:227 Bilibili Evolved (2) [{…}, {…}]
userscript.html?name=Bilibili-Evolved.user.js&id=3f71be0f-26dc-47da-98f2-b78e3bb440ea:227 Bilibili Evolved (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}]
userscript.html?name=Bilibili-Evolved.user.js&id=3f71be0f-26dc-47da-98f2-b78e3bb440ea:227 Bilibili Evolved reply 0 0
userscript.html?name=Bilibili-Evolved.user.js&id=3f71be0f-26dc-47da-98f2-b78e3bb440ea:227 Bilibili Evolved at 0 0
userscript.html?name=Bilibili-Evolved.user.js&id=3f71be0f-26dc-47da-98f2-b78e3bb440ea:227 Bilibili Evolved like 0 2
userscript.html?name=Bilibili-Evolved.user.js&id=3f71be0f-26dc-47da-98f2-b78e3bb440ea:227 Bilibili Evolved sys_msg 0 0
userscript.html?name=Bilibili-Evolved.user.js&id=3f71be0f-26dc-47da-98f2-b78e3bb440ea:227 Bilibili Evolved user_msg 0 5
```

### 附加截图

**Lighthouse测试截图**
![image](https://github.com/the1812/Bilibili-Evolved/assets/69132853/e303eb61-d08c-403b-b41a-764ead787334)
![image](https://github.com/the1812/Bilibili-Evolved/assets/69132853/43afa6b4-0c6e-42d2-9350-d7ba7fbd5ec6)

**控制台截图**
![image](https://github.com/the1812/Bilibili-Evolved/assets/69132853/c578187e-e50f-499d-97e2-7ab644370fbe)

**Comment by misaka10843** [comment]
在我重新安装并升级chrome后问题消失，虽然现在暂时消失了，但是之前就有过突然某天又出现这个问题（怪得很）
所以我认为还是把issue打开比较好？（虽然也可以直接关闭到再次出现问题时打开）

**Comment by the1812** [comment]
#4209
