### ISSUE TITLE
b站系统检测账号使用插件无法观看直播

### ISSUE THREAD

**Issue by amarazshi** [the1812/Bilibili-Evolved#427]
**问题描述**

如题，b站系统检测账号使用插件，直播就没法看了，估计b站直接就锁了ip，不论换不换浏览器，开不开插件都没用了，我基本看一次直播就和客服斗智斗勇一次（；´д｀）ゞ，客服给你解了只要还用过一天左右又被封了。。。大佬有没有方法解决？ヾ(•ω•`)o感谢大佬

**脚本版本**

正式版1.10.12

**浏览器版本**

 Chrome 83.0.4087.0（正式版本）canary （64 位）

**附加截图**
图就不上了，反正就是直播黑屏转圈圈/_ \

**Comment by Coulomb-G** [comment]
你老实回答...用了哪些自动薅羊毛的插件,和这个脚本有关系?

**Comment by amarazshi** [comment]
我老实回答，没啊，有关于b站的脚本就只有这个和b站港澳台。。。这个插件里的直播间自动领奖没关，是不是和这个有关系？（我不知道请别喷）

![批注 2020-04-04 172244](https://user-images.githubusercontent.com/62531410/78423456-fbcf6100-7698-11ea-866d-1f63acb2eb5f.jpg)

**Comment by Coulomb-G** [comment]
这两个脚本我也都安装着,自动领奖很收敛,是正常速度领取,我至今也没出现过这种情况,客服的解释能具体看一下是什么样的么?

**Comment by amarazshi** [comment]
基本上就是重复这几句话。。。
![批注 2020-04-05 135325](https://user-images.githubusercontent.com/62531410/78468006-a1400e80-7745-11ea-9dd8-6085670628cc.jpg)

**Comment by the1812** [comment]
那么你一天大致领多少直播间的那些抽奖?

**Comment by Coulomb-G** [comment]
你是否有过共享账号之类的行为?或者ip大幅度变化
https://account.bilibili.com/account/record

**Comment by amarazshi** [comment]
两个一起回答吧。。。我基本是只看一个直播间，所以应该不存在领的太频繁封了的问题。。。没共享过账号，查了一下只有之前小飞机全局忘关的国外ip，其他的是我的手机电脑，总共就3个。所以我才郁闷到底怎么回事。。。

**Comment by the1812** [comment]
那应该就是国外ip导致的吧

**Comment by HYY-zh** [comment]
挂代理会被封，我之前挂代理（阿里云的；国外的），第二天就黑(´；ω；`)

**Comment by amarazshi** [comment]
换火狐了，现在没问题。最近都没挂代理，所以没事了？（@-@）不懂。。。总之谢谢各位。
