### ISSUE TITLE
番剧播放页 https://www.bilibili.com/bangumi/play/ep 夜间模式，很多地方失效了

### ISSUE THREAD

**Issue by orisgh** [the1812/Bilibili-Evolved#4272]
### 对应功能

番剧播放页 https://www.bilibili.com/bangumi/play/ep 夜间模式，很多地方失效了

### 问题描述

番剧播放页 https://www.bilibili.com/bangumi/play/ep 夜间模式，很多地方失效了

### 脚本版本

最新版

### 脚本管理器及版本

最新版篡改猴

### 浏览器及版本

最新版Chrome

### 播放器版本

最新版吧

### 播放策略

默认

### 错误信息

```Shell
番剧播放页 https://www.bilibili.com/bangumi/play/ep 夜间模式，很多地方失效了
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/44023550/a4ba6766-613d-4a3e-8ad8-ee328d16f494)

**Comment by Geeyun-JY3** [comment]
新版番剧播放页没适配是已知的：#4186、https://github.com/users/the1812/projects/1/views/3?pane=issue&itemId=30092837
