### ISSUE TITLE
动态里的番剧内容不更新了

### ISSUE THREAD

**Issue by MarkDanDing** [the1812/Bilibili-Evolved#4279]
### 对应功能

动态里的番剧内容不更新了

### 问题描述

动态里的番剧内容不更新了

### 脚本版本

2.7.2

### 脚本管理器及版本

4.19.0

### 浏览器及版本

 Edge114.0.1823.67

### 播放器版本

4.1.20-7187a7c9

### 播放策略

默认

### 错误信息

```Shell
动态里的番剧内容不更新了
```

### 附加截图

动态里的番剧内容不更新了

**Comment by Geeyun-JY3** [comment]
你说的是哪里的动态？

**Comment by MarkDanDing** [comment]
![image](https://github.com/the1812/Bilibili-Evolved/assets/60662448/f2a54df8-46f0-4d2f-8ebd-8a0bf8783eab)
顶部的动态

**Comment by the1812** [comment]
见 #4305
