### ISSUE TITLE
不离开页面换P无法显示弹幕

### ISSUE THREAD

**Issue by ccicnce113424** [the1812/Bilibili-Evolved#428]
**关于哪一项功能**

**问题描述**

安装脚本后，打开视频网页，不离开页面换P的时候无法显示弹幕。互动视频也有问题。卸载脚本后问题仍存在，重置浏览器后才恢复。

**脚本版本**

5天前装的离线版（GitHub）

**浏览器版本**

user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

**错误信息**

未知

**附加截图**

**Comment by Coulomb-G** [comment]
是否还安装了其他插件/脚本?

**Comment by ccicnce113424** [comment]
没有，这个问题有时候出现

**Comment by ccicnce113424** [comment]
可能是我这个浏览器没配置好，不好用。这个问题有时出现。
