### ISSUE TITLE
收起评论按钮超出了评论区的边框

### ISSUE THREAD

**Issue by yokinanya** [the1812/Bilibili-Evolved#4282]
### 对应功能

功能名：快速收起评论
Commit: 65362f05f
内部名称: foldComments

### 问题描述

在动态页面展开评论后出现的收起评论按钮长度超出了B站动态的长度
尝试手动修改css中的 `width: calc(100% + 48px);` 和 `transform: translateX(-24px);` 为 `width: calc(100%);` 和 `transform: translateX(0px);` 后可正常显示

### 脚本版本

v2.8.0-preview-77-g7e99bde31

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

Chrome 114.0.5735.199

### 播放器版本

与播放器无关

### 播放策略

默认

### 错误信息

```Shell
不存在错误信息
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/30362789/d0160832-ba2a-44b7-80ac-a2a0b0439405)

**Comment by Geeyun-JY3** [comment]
目前似乎有让新版动态首页中间部分过窄的 bug
