### ISSUE TITLE
查看封面失效 (Cannot read properties of null (reading 'list'))

### ISSUE THREAD

**Issue by Fiz-Victor** [the1812/Bilibili-Evolved#4291]
### 对应功能

查看封面

### 问题描述

查看封面按钮为灰色

### 脚本版本

v2.8.0-preview-77-g7e99bde31

### 脚本管理器及版本

Violentmonkey 2.14.0

### 浏览器及版本

Microsoft Edge 114.0.1823.67 

### 播放器版本

4.1.20-7187a7c9

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved TypeError: Cannot read properties of null (reading 'list')
    at hn.fetchInfo (chrome-extension://eeagobfjdenkkddmbclomhiblgggliao/Bilibili%20Evolved%20.user.js#1:195:25501)
    at async eval (eval at <anonymous> (eval at <anonymous> (www.bilibili.com/:197:38782)), <anonymous>:1:2006)
b @ Bilibili Evolved (Preview).user.js:226
```

### 致遇到了相同问题准备回复的人
**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by starxjys** [comment]
同报错，字幕下载不了

**Comment by TangCH-02** [comment]
同问题。查看封面无法点击

**Comment by Tinhone** [comment]
咦，原来的“致遇到了相同问题准备回复的人”去哪了？

**Comment by the1812** [comment]
糟了 之前合码搞没了

**Comment by the1812** [comment]
这个报错看起来是 b 站修改了 API 的返回字段

**Comment by Tinhone** [comment]
将光标置于下图所示元素时会报错，不知道和这个 issue 有没有关联
![图片](https://github.com/the1812/Bilibili-Evolved/assets/81268244/a21fc6b9-b7da-4111-9766-f8f75608f60f)
![图片](https://github.com/the1812/Bilibili-Evolved/assets/81268244/f83eeed6-07e2-4407-a1f5-3b5632814f7c)

**Comment by JackASil** [comment]
火狐108同问题[evolved log.txt](https://github.com/the1812/Bilibili-Evolved/files/12030535/evolved.log.txt)

**Comment by Yanstory** [comment]
下载功能尝试显示封面也会出现此问题，原封面位置会留空

可能所有能显示封面的位置都可以触发此错误

**Comment by the1812** [comment]
已修复, 更新最新版脚本就行

**Comment by Marx48** [comment]
![image](https://github.com/the1812/Bilibili-Evolved/assets/24847949/e704302e-7d7d-46a1-a45a-be7197d7cf62)
我的版本是这个，但在下载字幕时仍然出现错误

**Comment by SetoKaiba** [comment]
@the1812 下载字幕错误是在这个issue里回还是另起一个，我和楼上的一样。但是我看大家都是在这个查看封面失效的issue里回了，最新预览版还是不行。

**Comment by Marx48** [comment]
据您所描述，今天似乎什么都不正常工作，无论是2.7.3版本还是preview2.8.1版本。
![image](https://github.com/the1812/Bilibili-Evolved/assets/24847949/75b3ffa1-584d-4f8c-a8e7-f70a9ce172fa)

**Comment by Marx48** [comment]
> @the1812 下载字幕错误是在这个issue里回还是另起一个，我和楼上的一样。但是我看大家都是在这个查看封面失效的issue里回了，最新预览版还是不行。 https://www.bilibili.com/video/BV1WW4y197dE/ 比如这个视频点击下载字幕，然后报错Cannot read properties of null (reading 'body')

附加的链接已下线

**Comment by SetoKaiba** [comment]
> > @the1812 下载字幕错误是在这个issue里回还是另起一个，我和楼上的一样。但是我看大家都是在这个查看封面失效的issue里回了，最新预览版还是不行。 https://www.bilibili.com/video/BV1WW4y197dE/ 比如这个视频点击下载字幕，然后报错Cannot read properties of null (reading 'body')
> 
> 附加的链接已下线

没有下线的，好像是github的bug，点开后，在地址栏再重新按一下回车就好了。

**Comment by Marx48** [comment]
> > > @the1812 下载字幕错误是在这个issue里回还是另起一个，我和楼上的一样。但是我看大家都是在这个查看封面失效的issue里回了，最新预览版还是不行。 https://www.bilibili.com/video/BV1WW4y197dE/ 比如这个视频点击下载字幕，然后报错Cannot read properties of null (reading 'body')
> > 
> > 
> > 附加的链接已下线
> 
> 没有下线的，好像是github的bug，点开后，在地址栏再重新按一下回车就好了。

好的，谢谢。我已经成功打开了视频。问题确实还存在: Cannot read properties of null (reading 'body')

**Comment by the1812** [comment]
下载字幕的在 #4319
