### ISSUE TITLE
切换分p会弹出提示 Cannot read properties of null (reading 'list')

### ISSUE THREAD

**Issue by GaryOldMen** [the1812/Bilibili-Evolved#4292]
### 对应功能

![image](https://github.com/the1812/Bilibili-Evolved/assets/45043650/af3856c7-ee90-481b-804d-c2354b269d51)

### 问题描述

切换分p会弹出提示 Cannot read properties of null (reading 'list')

### 脚本版本

v2.7.2-53-g81aba0ace

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

 版本 114.0.5735.199（正式版本） （64 位）

### 播放器版本

4.1.20—7187a7c9

### 播放策略

默认

### 错误信息

```Shell
报错
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/45043650/6d842d4a-3b1b-43b1-b0cf-ab72c634b46f)

**Comment by TangCH-02** [comment]
遇到了同样的问题。即使是单p的视频同样会弹出提示

**Comment by the1812** [comment]
合并至 #4291
