### ISSUE TITLE
顶栏-动态-番剧 错误

### ISSUE THREAD

**Issue by EarOfWheat** [the1812/Bilibili-Evolved#4305]
### 对应功能

顶栏-动态-番剧 

### 问题描述

顶栏-动态-番剧 
![image](https://github.com/the1812/Bilibili-Evolved/assets/74401501/5a49e7c1-1526-4cb2-aede-84602d5f921c)
![image](https://github.com/the1812/Bilibili-Evolved/assets/74401501/628adfe7-968d-404e-a179-1780ce263f14)

### 脚本版本

2.7.3

### 脚本管理器及版本

4.19.0

### 浏览器及版本

Microsoft Edge 版本 114.0.1823.82

### 播放器版本

无关

### 播放策略

默认

### 错误信息

```Shell
Error
    at a.nextPage (eval at 
 (eval at  (:1:1)), :19:2331)
    at async a.created (eval at  (eval at  (:1:1)), :19:2084)
```

### 附加截图

<img width="392" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/74401501/f800dd67-4194-4892-9e03-f1583ac0dc60">

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
#3802?

**Comment by Tinhone** [comment]
![图片](https://github.com/the1812/Bilibili-Evolved/assets/81268244/5aea3455-fa93-4225-a985-a264b7563197)
我这里的错误弹窗是另一种样子

**Comment by EarOfWheat** [comment]
> #3802?

我也试了更新脚本至[预览] v2.8.1、停用其他脚本、清除cookie。错误仍存在，不过变成了楼上一样错误内容为空。

**Comment by XianYuDaXian** [comment]
一样的错误，清除cookie和重装脚本也是一样。

**Comment by theblueandblackcrow** [comment]
在清爽主页和右上角动态里的番剧均无法成功刷新，显示空空如也
可能是b站这边对番剧部分做出了限制（不确定）

**Comment by HashLiver** [comment]
是因为`api.vc.bilibili.com`这个**过时**API的原因，当点击「番剧」这个选项卡时，
请求：
`https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_new?uid=*******&type_list=512`
回复：
`{"code":500122,"msg":"","message":"","data":{}}`

我建议把顶栏的所有包含`api.vc.bilibili.com`过时API全部更换为现在新的网页API，比如现在的番剧动态API是：
`https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/all?timezone_offset=-480&type=pgc&page=1`

**Comment by pinaZC** [comment]
> ![图片](https://user-images.githubusercontent.com/81268244/253705797-5aea3455-fa93-4225-a985-a264b7563197.png) 我这里的错误弹窗是另一种样子

顶一下这个，我的现象跟这个一样的，作者是无法复现这个吗？
每天点动态-番剧都显示错误，每天都被这个至少错误一次，至少一个多月了，让人挺烦躁的，能不能加急修复下
顺便插件什么时候更新啊，看issue里不少东西也修复/适配了

**Comment by HashLiver** [comment]
早说过是API的问题，结果我的评论被几个F12都不会按的傻逼狂踩，还有什么好说的呢
