### ISSUE TITLE
目前部分各功能突然失效 已知有查看封面 快速收藏 外置稍后再看

### ISSUE THREAD

**Issue by 1213mmm** [the1812/Bilibili-Evolved#4309]
### 对应功能

查看封面（Commit: cd5e421d8 内部名称: viewCover）/启用快速收藏（Commit: cd5e421d8 内部名称: quickFavorite）/外置稍后再看（Commit: cd5e421d8 内部名称: outerWatchlater）

### 问题描述

假设一个时间点 14点之前打开的视频功能都正常 之后再打开的视频部分功能就失效了 目前我就知道这3个失效其他不清楚

### 脚本版本

v2.7.3

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

Google Chrome/114.0.5735.199（正式版本） （64 位）

### 播放器版本

4.2.0-da9c873d

### 播放策略

默认

### 错误信息

```Shell
userscript.html?name=Bilibili-Evolved.user.js&id=d2dde195-9e9b-468e-919b-9f2326bfd1ab:226 Bilibili Evolved [__ob__: Be]length: 0__ob__: Be {value: Array(0), dep: ue, vmCount: 0}dep: ue {id: 38, subs: Array(4)}value: [__ob__: Be]vmCount: 0[[Prototype]]: Object[[Prototype]]: Arraypop: ƒ ()push: ƒ ()reverse: ƒ ()shift: ƒ ()sort: ƒ ()splice: ƒ ()unshift: ƒ ()[[Prototype]]: Array(0) undefined false
userscript.html?name=Bilibili-Evolved.user.js&id=d2dde195-9e9b-468e-919b-9f2326bfd1ab:226 Bilibili Evolved 网址参数清理 直接清理 https://www.bilibili.com/video/BV1zk4y1V7Hf/?vd_source=3ae47c8034c5c0519fbdb99997c945e7 https://www.bilibili.com/video/BV1zk4y1V7Hf/
userscript.html?name=Bilibili-Evolved.user.js&id=d2dde195-9e9b-468e-919b-9f2326bfd1ab:226 Bilibili Evolved updated widgets [__ob__: Be]
userscript.html?name=Bilibili-Evolved.user.js&id=d2dde195-9e9b-468e-919b-9f2326bfd1ab:226 Bilibili Evolved (2) [{…}, {…}, __ob__: Be]0: {…}1: {…}length: 2__ob__: Be {value: Array(2), dep: ue, vmCount: 0}[[Prototype]]: Array
userscript.html?name=Bilibili-Evolved.user.js&id=d2dde195-9e9b-468e-919b-9f2326bfd1ab:226 Bilibili Evolved (2) [{…}, {…}, __ob__: Be]0: {…}1: {…}length: 2__ob__: Be {value: Array(2), dep: ue, vmCount: 0}[[Prototype]]: Array
userscript.html?name=Bilibili-Evolved.user.js&id=d2dde195-9e9b-468e-919b-9f2326bfd1ab:226 Bilibili Evolved (2) [{…}, {…}, __ob__: Be]0: {…}1: {…}length: 2__ob__: Be {value: Array(2), dep: ue, vmCount: 0}[[Prototype]]: Array
userscript.html?name=Bilibili-Evolved.user.js&id=d2dde195-9e9b-468e-919b-9f2326bfd1ab:226 Bilibili Evolved updated widgets (2) [{…}, {…}, __ob__: Be]
userscript.html?name=Bilibili-Evolved.user.js&id=d2dde195-9e9b-468e-919b-9f2326bfd1ab:226 Bilibili Evolved (2) [{…}, {…}, __ob__: Be]0: {…}1: {…}length: 2__ob__: Be {value: Array(2), dep: ue, vmCount: 0}[[Prototype]]: Array
userscript.html?name=Bilibili-Evolved.user.js&id=d2dde195-9e9b-468e-919b-9f2326bfd1ab:226 Bilibili Evolved updated widgets (3) [{…}, {…}, {…}, __ob__: Be]
userscript.html?name=Bilibili-Evolved.user.js&id=d2dde195-9e9b-468e-919b-9f2326bfd1ab:226 Bilibili Evolved (2) [{…}, {…}, __ob__: Be]0: {…}1: {…}length: 2__ob__: Be {value: Array(2), dep: ue, vmCount: 0}[[Prototype]]: Arraypop: ƒ ()push: ƒ ()reverse: ƒ ()shift: ƒ ()sort: ƒ ()splice: ƒ ()unshift: ƒ ()[[Prototype]]: Array(0)
userscript.html?name=Bilibili-Evolved.user.js&id=d2dde195-9e9b-468e-919b-9f2326bfd1ab:226 Bilibili Evolved (2) [{…}, {…}, __ob__: Be]0: {…}1: {…}length: 2__ob__: Be {value: Array(2), dep: ue, vmCount: 0}[[Prototype]]: Array
userscript.html?name=Bilibili-Evolved.user.js&id=d2dde195-9e9b-468e-919b-9f2326bfd1ab:226 Bilibili Evolved [__ob__: Be]length: 0__ob__: Be {value: Array(0), dep: ue, vmCount: 0}[[Prototype]]: Array undefined false
```

### 附加截图

![QQ截图20230714152952](https://github.com/the1812/Bilibili-Evolved/assets/127377356/bc102192-697b-4112-81c7-cfed70cc7908)
![QQ截图20230714151718](https://github.com/the1812/Bilibili-Evolved/assets/127377356/ea5c8f9d-f03c-47cc-ac8f-ce66e3336f7b)
![QQ截图20230714151708](https://github.com/the1812/Bilibili-Evolved/assets/127377356/e3755a3f-0d1d-4dac-ada2-989d5e099eaa)

关闭再启动组件的
![QQ截图20230714153122](https://github.com/the1812/Bilibili-Evolved/assets/127377356/ad2e5baf-13bf-4507-ade4-38981f227d3b)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by cancundeyingzi** [comment]
下载,自动宽屏/全屏都没了

**Comment by 1213mmm** [comment]
> 下载,自动宽屏/全屏都没了

估计是一批一批的失效的 其他我都不清楚我主要用快速收藏 我1点多开始看B站快速收藏还是在的 然后过段时间我再打开新视频 快速收藏没了 看了看另外2个经常用的也寄了 目前我看快捷键简化评论区倒是没事

**Comment by guoyaoyang0522** [comment]
我也遇到这个问题

**Comment by guoyaoyang0522** [comment]
2.7.3各功能失效

**Comment by guoyaoyang0522** [comment]
![image](https://github.com/the1812/Bilibili-Evolved/assets/109347164/c0955e22-d14c-484c-b92d-2aa2c97fc7c9)

**Comment by megaslx** [comment]
播放速度设置以及记忆功能同样也失效了

**Comment by EarOfWheat** [comment]
空降也失效了

**Comment by nosorame** [comment]
大部分功能已失效

**Comment by Poqiu4396** [comment]
视频内显示时间，启用快速收藏，网址AV号转换功能也已失效

**Comment by HuaZzZzZz** [comment]
传统连播也失效了

**Comment by Linnest2020** [comment]
插件v2.8.1-preview，Tampermonkey4.19.0，浏览器平台Firefox115.0.2。且在Chrome平台进行过测试。下载，拓展倍速，均失效

**Comment by nutari** [comment]
传统连播失效，2.8.1和2.7.3下都无效了。

**Comment by 1213mmm** [comment]
部分快捷键我看好像也失效了比如点赞收藏投币的  例如网页全屏的就没事

**Comment by Tinhone** [comment]
启用视频截图 videoScreenshot
启用逐帧调整 seekByFrames
也已失效

**Comment by the1812** [comment]
#4303
