### ISSUE TITLE
在2560×1440分辨率屏幕下无法使用

### ISSUE THREAD

**Issue by homo11451419** [the1812/Bilibili-Evolved#4315]
### 对应功能

在原来的分辨率较低的笔记本上可正常使用。
新笔记本分辨率为2560×1440
Chrome:
<img width="1280" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/127638251/5bf5716f-f95f-47b4-b609-ed5912899c84">（最新版本）
B站：
<img width="1320" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/127638251/48b88e08-1a7e-4168-8843-95d7457d77cb">（两个源都试过了，都一样）
AdGuard广告拦截器已关闭：
<img width="1280" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/127638251/a23f15e3-0e93-4f40-9be1-12a85bb30362">
望解决（我真的很喜欢这个项目）

### 问题描述

所有界面/分辨率2560×1440/Google Chrome114.0.5735.199

### 脚本版本

最新（面板都没了开什么玩笑）

### 脚本管理器及版本

篡改猴 v.4.19.0

### 浏览器及版本

Google Chrome114.0.5735.199

### 播放器版本

4.2.0-da9c873d

### 播放策略

默认

### 错误信息

```Shell
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at MutationObserver.<anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili-Evolved.user.js&id=c9af6c10-c8c1-4bf6-9313-8dbb14b6ae6a:189:36309)
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
这跟分辨率没啥关系吧, 删掉重新装个新的试试?

**Comment by homo11451419** [comment]
安装预览版，问题没了
