### ISSUE TITLE
下载字幕失败

### ISSUE THREAD

**Issue by yufangjie1643** [the1812/Bilibili-Evolved#4319]
### 对应功能

下载字幕：
启用下载字幕支持, 在视频页面中可从功能面板里下载字幕.

Commit: cd5e421d8
内部名称: downloadSubtitle

### 问题描述

下载视频字幕时弹出报错信息：“Cannot read properties of null (reading 'body')”
相关示例视频：https://www.bilibili.com/bangumi/play/ep761165

### 脚本版本

Bilibili Evolved v2.7.3

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

Microsoft Edge 版本 114.0.1823.79 (正式版本) (64 位)

### 播放器版本

version: 4.1.19-rc.1663.0

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved TypeError: Cannot read properties of null (reading 'body')
    at l (eval at <anonymous> (eval at <anonymous> (ep761165:1:1)), <anonymous>:1:1950)
    at async a.download (eval at <anonymous> (eval at <anonymous> (ep761165:1:1)), <anonymous>:12:3699)
```

### 附加截图

<img width="1280" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/72263454/11f07115-d9d9-41bd-aa19-510975bbbf2b">
<img width="816" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/72263454/6d95f4f0-6ef8-4222-b958-f4247643376b">

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
b 站接口现在不返回字幕的下载地址了, 得找另外的方法

**Comment by Marx48** [comment]
> b 站接口现在不返回字幕的下载地址了, 得找另外的方法

你知道还有其他选择吗？

**Comment by SetoKaiba** [comment]
@the1812 
https://api.bilibili.com/x/player/wbi/v2?aid=xxx&cid=xxx
这个接口应该能返回字幕吧？B站播放器应该是用这个接口拿的字幕呀。

**Comment by Marx48** [comment]
![image](https://github.com/the1812/Bilibili-Evolved/assets/24847949/aad26a3b-0a9d-485f-a91f-122a8194aac0)


> @the1812 https://api.bilibili.com/x/player/wbi/v2?aid=xxx&cid=xxx 这个接口应该能返回字幕吧？B站播放器应该是用这个接口拿的字幕呀。
![image](https://github.com/the1812/Bilibili-Evolved/assets/24847949/3d15efb8-f722-4557-90d1-a8bc8de36318)

这是出现的消息。

**Comment by SetoKaiba** [comment]
@Marx48 这是接口，不是直接点开的，要传正确的aid和cid才能获得字幕的地址。

**Comment by the1812** [comment]
> 这个接口应该能返回字幕吧？B站播放器应该是用这个接口拿的字幕呀。

可以的

**Comment by SetoKaiba** [comment]
@the1812 为什么AI生成的不能下载呀？以前都可以下载的呀，而且这个接口返回的里面有AI的呀

**Comment by SetoKaiba** [comment]
以前可以下载是因为subtitles[0]吗？因为只有一个字幕，所以自动下载AI的了吗？

**Comment by the1812** [comment]
b 站选择 AI 字幕不会更新到 localStorage 中存储的字幕语言，脚本匹配到的仍然是非 AI 字幕
不过我还没试过那种只有 AI 字幕的视频，说不定能下载

**Comment by SetoKaiba** [comment]
什么时候会发布到预览版呀？

**Comment by Holiday2019** [comment]
这个东西有无可能实现？
