### ISSUE TITLE
1.10.14版本不会覆盖更新

### ISSUE THREAD

**Issue by YuhangSco** [the1812/Bilibili-Evolved#432]
我更新1.10.14之后还存在1.10.12导致旧版本一直弹窗更新。后来我才发现没有新版没有覆盖旧版
还有就是更新之后设置项重置了，有个全屏保留进度条的功能我找不到了。
![屏幕截图(203)](https://user-images.githubusercontent.com/56777685/78421979-a4c48e80-768e-11ea-8ee0-cb575df00b62.png)

**Comment by the1812** [comment]
你上哪更的1.10.14? 目前正式版还是1.10.12
设置重置说明安装的还是1.10.12, 相同版本安装的话Tampermonkey会重置设置
保留进度条是触摸播放器的功能

**Comment by the1812** [comment]
重新传了一下1.10.14版的 请1天后再检查更新试试

**Comment by zaqw6414** [comment]
确实不会覆盖新版，而是另装一个，导致我每次开都要我更新，而且设置用的是预设的，强刷了半天才发现装了俩个版本

**Comment by ctc1991** [comment]
bug依旧在

**Comment by ctc1991** [comment]
不修复的话，原先的自定义设置就没用了把

**Comment by YuhangSco** [comment]
> 你上哪更的1.10.14? 目前正式版还是1.10.12
> 设置重置说明安装的还是1.10.12, 相同版本安装的话Tampermonkey会重置设置
> 保留进度条是触摸播放器的功能

我的插件是在greasyfork下的，昨天下午提示我更新

**Comment by zaqw6414** [comment]
https://greasyfork.org/scripts/373563-bilibili-evolved/code/Bilibili%20Evolved.user.js
https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@master/bilibili-evolved.user.js

**Comment by zaqw6414** [comment]
> 不修复的话，原先的自定义设置就没用了把

我先把新版关了继续用着旧版……懒得重新调一次设定了

**Comment by the1812** [comment]
明白了 今天已经传了修复后的 网络好的可以直接到主页用[GitHub源](https://github.com/the1812/Bilibili-Evolved/raw/master/bilibili-evolved.user.js)安装更新 连不上GitHub源需要等明天[jsDelivr更新](https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@master/bilibili-evolved.user.js)

目前暂时的解决方法有:
**1. 关掉`1.10.12`的检查更新并继续使用**
编辑脚本, 找到约532行的位置, 把`notifyNewVersion`后面的`true`改为`false`保存
```js
notifyNewVersion: false,
```
**2. 使用那个有问题的`1.10.14`版**
在`1.10.12`里导出设置, 再开`1.10.14`导入进去即可.
<img width="400" src="https://user-images.githubusercontent.com/26504152/78465421-13095f80-7728-11ea-95ee-077f3dda49fa.png">

**Comment by the1812** [comment]
现在应该恢复正常了, 可以把原先的`1.10.12`更新到`1.10.14`, 并删除那个多出来的`1.10.14`版
(多出来的那个可以看编辑脚本里第3行是`// @namespace   Bilibili-Evovled`)
