### ISSUE TITLE
顶栏 - 动态 - 番剧功能不显示（报错）

### ISSUE THREAD

**Issue by KB3146706** [the1812/Bilibili-Evolved#4324]
### 对应功能

自定义顶栏
cd5e421d8

### 问题描述

鼠标点击顶栏动态中的番剧分类

### 脚本版本

2.7.4-50-g1965b5590

### 脚本管理器及版本

Tampermonkey 4.19.0

### 浏览器及版本

猫眼浏览器 3.7.2（Kernel 115.0.5790.82）

### 播放器版本

4.2.0-da9c873d

### 播放策略

HEVC

### 错误信息

```Shell
Bilibili Evolved Error
    at a.nextPage (eval at <anonymous> (eval at <anonymous> (www.bilibili.com/:1:1)), <anonymous>:19:2331)
    at async a.created (eval at <anonymous> (eval at <anonymous> (www.bilibili.com/:1:1)), <anonymous>:19:2084)
b @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:229
a @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:229
nextPage @ VM1843:19
await in nextPage（异步）
created @ VM1843:19
Qe @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
sn @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
e._init @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
a @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
（匿名） @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
init @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
（匿名） @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:254
m @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:254
_i.nodeOps @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:254
e._update @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
o @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:254
wn.get @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
wn.run @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
vn @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
（匿名） @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
et @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
Promise.then（异步）
Xe @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
rt @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
（匿名） @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
wn.update @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
ue.notify @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:250
set @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
yn.set @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
selectTab @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:229
click @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:229
Qe @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
n @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:253
r._wrapper @ userscript.html?name=Bilibili-Evolved.user.js&id=c5aca8f4-f0ff-4b2a-ba14-3c272ecc389f:254
```

### 附加截图

![Snipaste_2023-07-16_16-57-43](https://github.com/the1812/Bilibili-Evolved/assets/57534077/60e1c0d5-f6f7-4021-ac5d-7f6d5bc10903)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
重复，请善用搜索：#4305

**Comment by KB3146706** [comment]
> 重复，请善用搜索：#4305

非重复，现象与 https://github.com/the1812/Bilibili-Evolved/issues/4305#issuecomment-1636607352 相同（错误弹窗仅有“错误”二字）但与 #4305 不同，我补充了新情况的具体报错信息

**Comment by zhi0328** [comment]
补充：想使用添加组件的在线仓库功能也会有同样的错误
![QQ图片20230723000032](https://github.com/the1812/Bilibili-Evolved/assets/140264404/b488a1c0-e083-41f3-9684-470818304d30)
![QQ图片20230723000025](https://github.com/the1812/Bilibili-Evolved/assets/140264404/ffecbc1a-b827-46e6-82bc-e00ae3fad42f)

**Comment by Geeyun-JY3** [comment]
> 补充：想使用添加组件的在线仓库功能也会有同样的错误 
![QQ图片20230723000032](https://user-images.githubusercontent.com/140264404/255339124-b488a1c0-e083-41f3-9684-470818304d30.png) 
![QQ图片20230723000025](https://user-images.githubusercontent.com/140264404/255339138-ffecbc1a-b827-46e6-82bc-e00ae3fad42f.png)

你这是更新源选了 GitHub 却没有相应的网络环境吧，根本就不是一回事。

**Comment by Geeyun-JY3** [comment]
> 补充：想使用添加组件的在线仓库功能也会有同样的错误 
![QQ图片20230723000032](https://user-images.githubusercontent.com/140264404/255339124-b488a1c0-e083-41f3-9684-470818304d30.png) 
![QQ图片20230723000025](https://user-images.githubusercontent.com/140264404/255339138-ffecbc1a-b827-46e6-82bc-e00ae3fad42f.png)

你这是更新源选了 GitHub 却没有相应的网络环境吧，根本就不是一回事。
