### ISSUE TITLE
自定义顶栏在 Firefox 中搜索栏和个人信息栏显示有问题

### ISSUE THREAD

**Issue by LTHPKBTE** [the1812/Bilibili-Evolved#4326]
### 对应功能

自定义顶栏

### 问题描述

开启自定义顶栏后所有页面都会有同样的显示问题，看起来像是本来应该在顶栏外的元素被限制在了顶栏内。
未测试其他浏览器是否有问题。

### 脚本版本

v2.8.2-preview 自定义顶栏版本为ab972fd7e

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

Firefox ESR 102.0

### 播放器版本

4.1.20

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved 
Array []
 870189797 false Bilibili-Evolved-Preview.user.js:228:2040
Bilibili Evolved [Runtime Library] Start download from https://raw.githubusercontent.com/protobufjs/protobuf.js/v6.10.1/dist/light/protobuf.min.js Bilibili-Evolved-Preview.user.js:228:2040
Bilibili Evolved 网址参数清理 History API 拦截 /video/BV1hV4y1y71z/?vd_source=53c5daf1eb288f71992369d231080513 https://www.bilibili.com/video/BV1hV4y1y71z/ 2 Bilibili-Evolved-Preview.user.js:228:2040
Bilibili Evolved [Runtime Library] Downloaded from https://raw.githubusercontent.com/protobufjs/protobuf.js/v6.10.1/dist/light/protobuf.min.js , length = 63465 Bilibili-Evolved-Preview.user.js:228:2040
Bilibili Evolved 展开弹幕列表 当前弹幕量: 2 Bilibili-Evolved-Preview.user.js:228:2040
Bilibili Evolved videoChange 870189797 870189797 Bilibili-Evolved-Preview.user.js:228:2040
Bilibili Evolved 
Array(61) [ 913455919, 658495006, 956013569, 83502924, 949532001, 658276020, 403499716, 983669163, 615879834, 693328082, … ]
 870189797 false Bilibili-Evolved-Preview.user.js:228:2040
```

### 附加截图

![图片](https://github.com/the1812/Bilibili-Evolved/assets/53574505/c38ba6e4-2865-49cb-aa83-dcdcf8860036)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
![Snipaste_2023-07-19_08-13-11](https://github.com/the1812/Bilibili-Evolved/assets/26504152/cd7e8ced-a537-40e0-819e-51ccf15eae54)

Firefox 117 未能复现, 你的浏览器版本已经低于推荐配置了

**Comment by Tinhone** [comment]
Firefox 88 未能复现，或许可以尝试关闭其他浏览器插件&脚本以排查问题

**Comment by LTHPKBTE** [comment]
已确认空白的配置文件中没有该问题，正在排查，抱歉
