### ISSUE TITLE
动态首页的搜索框背景颜色

### ISSUE THREAD

**Issue by fox010** [the1812/Bilibili-Evolved#434]
**关于哪一项功能**
[动态首页](https://t.bilibili.com/) 的搜索框背景在夜间模式下，一直是亮的
而普通视频的搜索框背景会变暗

![image](https://user-images.githubusercontent.com/23356274/78471736-2509f300-7766-11ea-9153-85dce1c13111.png)

**期望的效果**
希望进行暗色处理

**脚本版本**
1.10.14

**Comment by 3301152539** [comment]
可以开自定义顶栏👀

**Comment by fox010** [comment]
设定自定义顶栏颜色 #444444，会让 Bilibili Evolved 的选项也都变灰色，分不清哪些按钮开启了

**Comment by the1812** [comment]
希望`自定义顶栏`暗色把就`主题色填充`关了吧, 不要把主题颜色设成灰色

**Comment by fox010** [comment]
发现不知道什么时候已经好了
