### ISSUE TITLE
适配新版搜索页面

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#4354]
### 对应功能

自定义顶栏
（不知道还有没有其他）

### 问题描述

我发现的有：
- `自定义顶栏`开启后仍能看见原版顶栏
- 在搜索页面中，`自定义顶栏`的搜索框不会自动填入当前搜索词

（顺便捞一下 #1847）

### 脚本版本

v2.8.0-preview-77-g7e99bde31

### 脚本管理器及版本

Tampermonkey v4.19.6183

### 浏览器及版本

Chrome 115.0.5790.110 （正式版本） （64 位）

### 播放器版本

不相关

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/81533bd9-fcfd-4950-83a1-f3db27af0ed7)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
顺便提一下含相关活动卡片的新版搜索结果页的夜间模式吧，卡片的按钮主题色和卡片主体背景都有些小问题：
https://search.bilibili.com/all?keyword=%E5%8E%9F%E7%A5%9E
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/8087778e-1d9e-4a1a-9239-318b5b5d389a)
https://search.bilibili.com/all?keyword=%E6%98%8E%E6%97%A5%E6%96%B9%E8%88%9F
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/49d3ed9f-74fb-43c4-bc35-09dacd127073)

**Comment by the1812** [comment]
![Snipaste_2024-03-07_22-34-06](https://github.com/the1812/Bilibili-Evolved/assets/26504152/2e0cbffb-4d90-4af6-8644-0330d8b83a1e)
现在好像没右边那个了?

**Comment by Geeyun-JY3** [comment]
> ![Snipaste_2024-03-07_22-34-06](https://github.com/the1812/Bilibili-Evolved/assets/26504152/2e0cbffb-4d90-4af6-8644-0330d8b83a1e)
> 现在好像没右边那个了?

不好说，我觉得应该是有时效性的广告位，我有空再找找（或者你也看看近期有什么有激励计划的二游版更，说不定也有。）

**Comment by Geeyun-JY3** [comment]
额今天就有了：
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/e250d07d-618e-4e44-9038-aeef10bb1711)
原神的也有。
