### ISSUE TITLE
”手动输入“时[ep]会获取到单p视频的EP名，”下载视频“则不会

### ISSUE THREAD

**Issue by fireattack** [the1812/Bilibili-Evolved#436]
**关于哪一项功能**

下载文件重命名

**问题描述**

对于任何单p视频，如果使用“下载视频”则`EP`不会转换为EP名（其实就是上传的文件名，比如av85736039的EP名就是“bokuhaka”），批量下载则会。

我理解这可能是故意这么设置的，但是希望能有一种方式在用”下载视频“时，也获取到这个EP名在重命名时能用。

**Comment by the1812** [comment]
放进`手动输入`里下载就会带`ep`

**Comment by fireattack** [comment]
> 放进`手动输入`里下载就会带`ep`

是的，可能我没说清楚，我就是觉得”下载视频“和”手动输入“时，文件名替换规则应该一致，这样保证无论用哪种方式都能下出一样的文件名。

现在除了上面说的下载视频无法获取到文件名的问题以外，反过来用手动输入批量下载时如果包括`EP`也会获取到单P视频的对大部分用户来说没啥用的文件名。

我觉得可以保持EP使用“下载视频“的方式（不输出如果是单P，输出分P名如果是多P），额外增加文件名之类的字段便于获取单P的文件名。

**Comment by the1812** [comment]
那就批量的时候, 单P的`ep`输出空吧
