### ISSUE TITLE
简化直播间：请求添加隐藏“荣耀等级勋章”功能

### ISSUE THREAD

**Issue by miachannel1** [the1812/Bilibili-Evolved#4363]
### **`Commit: 997218e88`**

![image](https://github.com/the1812/Bilibili-Evolved/assets/87613038/f7941b70-f88e-4a6b-8a45-5841130de0e5)

### 问题描述

请求添加隐藏“荣耀等级勋章”功能
该元素的类名：
class="wealth-medal-ctnr fans-medal-item-target dp-i-block p-relative v-middle"

![image](https://github.com/the1812/Bilibili-Evolved/assets/87613038/4f7e0c10-11d7-4229-be81-d2ee432c75f2)

### 脚本版本

Bilibili Evolved v2.7.4

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

Cent Browser (Chromium 102.0.5005.167)

### 播放器版本

Bilibili HTML5 Live Player 3.6.128

### 播放策略

默认

### 错误信息

```Shell
无报错
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Fiz-Victor** [comment]
用预览版，预览版已经加了这个功能

**Comment by CrunchyShark944** [comment]
哈哈我做好了

**Comment by the1812** [comment]
只是做好了, 我还没来得及发版

**Comment by Admasy** [comment]
@the1812 请问可以修复一下 简化评论区的功能吗 目前在新版播放页全部失效。
脚本版本: 简化评论区 Commit: 73fa9af28
Evolved:  v2.7.4
Google Chrome 115.0.5790.171
 Tampermonkey 4.19.0
