### ISSUE TITLE
“强制固定顶栏与侧栏”启用时左侧“正在直播”添加滚动条

### ISSUE THREAD

**Issue by 1818yu** [the1812/Bilibili-Evolved#437]
**关于哪一项功能**
设置→动态→强制固定顶栏与侧栏
**期望的效果**
在滚动动态时，左侧正在直播添加单独的滚动条如图所示
![2020-04-06_21-26-54](https://user-images.githubusercontent.com/56754498/78563367-6e813d80-784d-11ea-8a9d-0695c0610f95.gif)
**脚本版本**
1.10.14

**Comment by the1812** [comment]
只有一点需要注意一下:
加了滚动条的话 鼠标放在头像上出现的资料卡弹窗就无法超出`正在直播`的区域
所以这个资料卡弹窗我会屏蔽掉
![image](https://user-images.githubusercontent.com/26504152/80072743-3c741900-8579-11ea-8957-89d1a79a1888.png)
