### ISSUE TITLE
两个夜间模式下的字体颜色问题

### ISSUE THREAD

**Issue by GristTheHungerTide** [the1812/Bilibili-Evolved#4376]
### 对应功能

夜间模式
Commit: 997218e88

### 问题描述

1.对方私信的字颜色太深看不清楚，自己这边却没有问题，似乎和原本两边对话框颜色不同有关。
2.视频页下的"充电"两字会变成主题色但边框不会，感觉怪怪的；评论的点赞也是，数字会变但图标不变。

### 脚本版本

v2.7.4

### 脚本管理器及版本

Tampermonkey (Beta) v4.20.6186

### 浏览器及版本

Firefox Developer Edition 117.0 Beta 7 (20230813180142)

### 播放器版本

HTML5播放器 V4.3.3

### 播放策略

默认

### 附加截图

<img width="348" alt="屏幕截图 2023-08-16 003353" src="https://github.com/the1812/Bilibili-Evolved/assets/47290740/4c404b93-58cf-4260-91c1-25dc3c99ea2c">
<img width="358" alt="屏幕截图 2023-08-16 003404" src="https://github.com/the1812/Bilibili-Evolved/assets/47290740/562d8b5d-d029-4a05-bcfd-ea390b92ae09">
<img width="89" alt="屏幕截图 2023-08-16 005208" src="https://github.com/the1812/Bilibili-Evolved/assets/47290740/b68ed450-fbe9-42d4-bf5e-8febd0dec670">
<img width="30" alt="屏幕截图 2023-08-16 020715" src="https://github.com/the1812/Bilibili-Evolved/assets/47290740/f2323045-5541-4f7e-a0a1-3725c421c6d9">

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Dimir-Mastermind** [comment]
<img width="30" alt="屏幕截图 2023-08-16 020715" src="https://github.com/the1812/Bilibili-Evolved/assets/47290740/f2323045-5541-4f7e-a0a1-3725c421c6d9">
还有这个

**Comment by Dimir-Mastermind** [comment]
今天又发现一处
![Screenshot 2023-08-19 at 14-06-11 动态首页-哔哩哔哩](https://github.com/the1812/Bilibili-Evolved/assets/47290740/a0afdfaa-df7e-46c7-b640-6ffc0d66cc5f)

**Comment by pencilqaq** [comment]
如果你现在能找到有开预约的up主 发给我 我可以把预约也修复了

**Comment by Geeyun-JY3** [comment]
其实已过期的预约一样有问题：https://t.bilibili.com/924636085808529540dd
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/a7931a3f-c707-4124-bcab-326f65325d7d)
还没过期的预约：https://t.bilibili.com/935026470729809957

***

要做的话感觉可以顺便把以下这些动态相关的也做了：

- 相关游戏，实例：https://space.bilibili.com/3493265644980448/dynamic
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/233929d3-3fbf-40e7-8b08-ad1366326e8a)
- 投票，实例：https://t.bilibili.com/908326312582578199
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/902b9259-cf35-4a50-be16-45cdc46674b2)
- UP主的推荐（会员购），实例：https://t.bilibili.com/791756309077688325
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/bcf86c91-7bf2-4fe8-ad7d-76d306667680)
  其实还有一个 `UP主的推荐 · 来自淘宝`的实例：https://github.com/the1812/Bilibili-Evolved/issues/2136#issuecomment-1290663655

**Comment by pencilqaq** [comment]
> 其实已过期的预约一样有问题：https://t.bilibili.com/924636085808529540dd ![image](https://private-user-images.githubusercontent.com/49396421/333877115-a7931a3f-c707-4124-bcab-326f65325d7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Nzk4ODYsIm5iZiI6MTcxNjc3OTU4NiwicGF0aCI6Ii80OTM5NjQyMS8zMzM4NzcxMTUtYTc5MzFhM2YtYzcwNy00MTI0LWJjYWItMzI2ZjY1MzI1ZDdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAzMTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MGIxMjZlOThmYWY3ZGU5YmEwOWM2MWMxYzBjNGViMGE1MmYxZDI4MmNkMThkMGE3OWM1ZjkzZjVkNzk1YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A8qx2o99djtNYgu-Px6nWx7566Uo_D12oFsqrj7zky0) 还没过期的预约：https://t.bilibili.com/935026470729809957
> 
> 要做的话感觉可以顺便把以下这些动态相关的也做了：
> 
> * 相关游戏，实例：https://space.bilibili.com/3493265644980448/dynamic
>   ![image](https://private-user-images.githubusercontent.com/49396421/333877228-233929d3-3fbf-40e7-8b08-ad1366326e8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Nzk4ODYsIm5iZiI6MTcxNjc3OTU4NiwicGF0aCI6Ii80OTM5NjQyMS8zMzM4NzcyMjgtMjMzOTI5ZDMtM2ZiZi00MGU3LThiMDgtYWQxMzY2MzI2ZThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAzMTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYTdjODI1MDVlMWIxNjNhOWQ3ODQzYWMyOGEwM2JjYzAxZDA0NzA0ZDc1MmZhNGRkOWQyNzcxOTk1NzVmYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hjzIIHhk5hICT1h5lg9RXMo1JcxKPNm_tEG6Z_GIMig)
> * 投票，实例：https://t.bilibili.com/908326312582578199
>   ![image](https://private-user-images.githubusercontent.com/49396421/333877335-902b9259-cf35-4a50-be16-45cdc46674b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Nzk4ODYsIm5iZiI6MTcxNjc3OTU4NiwicGF0aCI6Ii80OTM5NjQyMS8zMzM4NzczMzUtOTAyYjkyNTktY2YzNS00YTUwLWJlMTYtNDVjZGM0NjY3NGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAzMTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYmNkMTFmZGY3M2U0NTBiNjQ1MWQyNWI5YjM1MjVlODQ2NjY2NmZjYjA1NzY1ZjgyOWZlZTg2ZGZlMGRjNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L8YbvjULE7_7c74nP2safqWvYZX1_2FtrLst-0V9HrI)
> * UP主的推荐（会员购），实例：https://t.bilibili.com/791756309077688325
>   ![image](https://private-user-images.githubusercontent.com/49396421/333877363-bcf86c91-7bf2-4fe8-ad7d-76d306667680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Nzk4ODYsIm5iZiI6MTcxNjc3OTU4NiwicGF0aCI6Ii80OTM5NjQyMS8zMzM4NzczNjMtYmNmODZjOTEtN2JmMi00ZmU4LWFkN2QtNzZkMzA2NjY3NjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAzMTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZjFmNWIwMjBhZGIyMGFlZDk5N2EyYzYxNjA1NDA1ZjJlOTIzYWVmNWQ5MDhhMzRmZjcwMWYxN2M3MWI5NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6UsdLoYdru6ULe-aYp7ysd6hgQ2EdTP7EDsquvS5ksg)
>   其实还有一个 `UP主的推荐 · 来自淘宝`的实例：[夜间模式未完全适配仍在继续集中反馈 #2136 (comment)](https://github.com/the1812/Bilibili-Evolved/issues/2136#issuecomment-1290663655)

像这种卡片 用的是什么样式
