### ISSUE TITLE
CPU全线程占用过高

### ISSUE THREAD

**Issue by chuyueye** [the1812/Bilibili-Evolved#4379]
### 对应功能

所有功能

### 问题描述

打开新网页的时候全线程cpu占用100%

### 脚本版本

2.7.4

### 脚本管理器及版本

Tampermonkey v4.19.6176

### 浏览器及版本

chrome105

### 播放器版本

4.3.3

### 播放策略

默认

### 错误信息

```Shell
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM65 index.js:1 [reporter-pb]: request error TypeError: Failed to fetch
    at index.js:1:33017
    at p (index.js:1:26029)
    at Generator.<anonymous> (index.js:1:27384)
    at Generator.next (index.js:1:26392)
    at u (index.js:1:32037)
    at a (index.js:1:32240)
    at index.js:1:32299
    at new Promise (<anonymous>)
    at index.js:1:32180
    at index.js:1:33289
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
你确定不是别的什么东西占用了? 我这笔记本开 b 站瞬时最高占用也就到 43%
![Snipaste_2023-08-21_20-23-53](https://github.com/the1812/Bilibili-Evolved/assets/26504152/5db691cd-4641-4176-8351-8e6dea1affbc)

**Comment by xxldm** [comment]
CPU：12700f
浏览器：chrome 版本 120.0.6099.109（正式版本） （64 位）
脚本：v2.8.7-preview-109-g04685315d

使用Ctrl+鼠标左键（也就是在新标签页中后台打开）依次打开3个视频，CPU会短暂（1-2秒）达到100%
不开脚本，使用以上方法打开24个视频，CPU会短暂（1-2秒）达到100%
![不开插件](https://github.com/the1812/Bilibili-Evolved/assets/38677850/48f08199-4bd2-4721-8c64-f6aa1a1f4721)
开脚本，使用以上方法打开24个视频，CPU一直持续在100%，直到停止打开视频，并等待大约10秒
![开插件](https://github.com/the1812/Bilibili-Evolved/assets/38677850/7d22a082-e5fa-4981-82fa-ef6eb3cfff61)

**Comment by the1812** [comment]
v2.8.7-preview, 装有 97 个组件, Chrome 120.0.6099.71
连开 24 个视频, 仅 1 个核持续满载, 总体占用率 70% 左右

![Snipaste_2023-12-17_17-09-12](https://github.com/the1812/Bilibili-Evolved/assets/26504152/729387d6-0b75-4105-b15f-abb40faa8d1f)

脚本对性能影响一定是有的, 首页说明里也明确说了, 不能接受就卸了吧. (虽然我不知道为啥 12700F 表现还不如 11800H)

**Comment by RingingVolcano** [comment]
可以检查下后台其他程序或者浏览器本身，你的chrome版本是105 可以更到最新看一下
还有是不是系统大小核调度的问题 12代如果强行装win10也可能会这样
我的电脑是R7 6800H 大概相当于13代i5 13500H 装了一堆组件也基本上是秒开的

**Comment by RingingVolcano** [comment]
> CPU：12700f 浏览器：chrome 版本 120.0.6099.109（正式版本） （64 位） 脚本：v2.8.7-preview-109-g04685315d
> 
> 使用Ctrl+鼠标左键（也就是在新标签页中后台打开）依次打开3个视频，CPU会短暂（1-2秒）达到100% 不开脚本，使用以上方法打开24个视频，CPU会短暂（1-2秒）达到100% ![不开插件](https://private-user-images.githubusercontent.com/38677850/291051106-48f08199-4bd2-4721-8c64-f6aa1a1f4721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjM3NTIsIm5iZiI6MTcwMjgyMzQ1MiwicGF0aCI6Ii8zODY3Nzg1MC8yOTEwNTExMDYtNDhmMDgxOTktNGJkMi00NzIxLThjNjQtZjZhYTFhMWY0NzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE0MzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMzgzMTUxZDBiOWU2YzFiNTdkMTEwMTI1ZTAxY2ZlM2RjM2EyOGFlNDE4MDAwNzM3YTNmNWYyMTY4NTRiMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h8gDTiYhFKFna9QO9C9wniXa8TQ4C2ya6lRam4ae9W4) 开脚本，使用以上方法打开24个视频，CPU一直持续在100%，直到停止打开视频，并等待大约10秒 ![开插件](https://private-user-images.githubusercontent.com/38677850/291051180-7d22a082-e5fa-4981-82fa-ef6eb3cfff61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjM3NTIsIm5iZiI6MTcwMjgyMzQ1MiwicGF0aCI6Ii8zODY3Nzg1MC8yOTEwNTExODAtN2QyMmEwODItZTVmYS00OTgxLTgyZmEtZWY2ZWIzY2ZmZjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE0MzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNjk3OGQyMDQ0OGI2YzJkNTdkOTE1OWRkZWJjZGYxNDU2YjJiM2MwYWVmZDljZjZjMDJhY2Y5OTU3Mzg1YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ElGIJqBgpulXFVTyYoAaR07qFWURLF0OOXugAqParw0)

脚本在页面刚打开时加载确实会占用一定资源，建议不要同时开这么多页面
