### ISSUE TITLE
批量下载的视频播放器导入音轨没有声音

### ISSUE THREAD

**Issue by miku-jia** [the1812/Bilibili-Evolved#438]
**关于哪一项功能**
批量下载

**问题描述**

部分批量下载的视频，播放器导入音轨没有声音，单独下载同样的视频不会出现这样的问题，用的播放器是PotPlayer，出现问题的有《轻音少女 第一季》AV52307583、《轻音少女 第二季》、《CLANNAD 》AV29801945等，下载时选项：格式DASH；清晰度：高清 1080P；弹幕：ASS；首选编码：HEVC/H.265

**脚本版本**

1.10.14

**浏览器版本**

80.0.3987.149（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by the1812** [comment]
导入的音频文件本身播放就没有声音吗?

**Comment by miku-jia** [comment]
有声音的，我的解决方法就是把视频和音频都分别打开来看，但是很不方便




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Grant Howard"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上9:41
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "jia_zeng"<2460235502@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 批量下载的视频播放器导入音轨没有声音 (#438)





 
导入的音频文件本身播放就没有声音吗?
 
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by the1812** [comment]
那还是用ffmpeg合并一下吧

**Comment by miku-jia** [comment]
好的，谢谢，刚搞懂怎么用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Grant Howard"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上10:47
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "jia_zeng"<2460235502@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 批量下载的视频播放器导入音轨没有声音 (#438)





 
那还是用ffmpeg合并一下吧
 
&mdash;
