### ISSUE TITLE
直播间侧边栏自适应异常

### ISSUE THREAD

**Issue by xuedingeHutao** [the1812/Bilibili-Evolved#4387]
### 对应功能

直播间网页全屏自适应

### 问题描述

开启侧边栏自适应后 视频区域显示异常

### 脚本版本

v2.8.3-preview-83-g164c3a1e6

### 脚本管理器及版本

Tampermonkey 4.19.0

### 浏览器及版本

Edge 117.0.2045.1 (正式版本) dev

### 播放器版本

Bilibili HTML5 Live Player 3.6.134

### 播放策略

默认

### 错误信息

```Shell
侧边栏的宽度没问题，但是视频区域的显示异常
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/45312898/f3935a67-3ce8-4146-967e-a3061e7a339f)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
![Snipaste_2023-08-26_14-46-13](https://github.com/the1812/Bilibili-Evolved/assets/26504152/02b711a3-5862-47af-be04-27ff2a385eb7)
检查元素搜一下这个 `player-section` 看看, 可能是我的样式没盖过原本的

**Comment by xuedingeHutao** [comment]
![image](https://github.com/the1812/Bilibili-Evolved/assets/45312898/ef63c68b-7864-4a75-b7c3-1e8e1808efda)
样式是这样的

**Comment by xuedingeHutao** [comment]
> ![Snipaste_2023-08-26_14-46-13](https://user-images.githubusercontent.com/26504152/263446452-02b711a3-5862-47af-be04-27ff2a385eb7.png) 检查元素搜一下这个 `player-section` 看看, 可能是我的样式没盖过原本的

样式是这样的
![image](https://github.com/the1812/Bilibili-Evolved/assets/45312898/6b2cec1a-34ec-4046-8d4a-0a34a27340d9)

**Comment by the1812** [comment]
确实没盖过, 我改改

**Comment by u2shana** [comment]
4ee0fe551这是最新的么，今天早上preview合了代码后，我也出现了这个情况，

**Comment by the1812** [comment]
是最新的, 你看下元素, 按理说应该优先级更高了
![Snipaste_2023-08-30_22-17-35](https://github.com/the1812/Bilibili-Evolved/assets/26504152/b8673e33-26b2-4100-8af3-31d2e3b8914f)

**Comment by u2shana** [comment]
![image](https://github.com/the1812/Bilibili-Evolved/assets/14146754/be5a689c-6fb0-4ceb-a4d5-b4418fa6de68)
我看上面的情况是开启侧边聊天框后聊天框不显示。我现在的情况是收起聊天框后没有变成网页全屏，右边聊天框部分空了

**Comment by xuedingeHutao** [comment]
@the1812 现在收起聊天框后留空了
![image](https://github.com/the1812/Bilibili-Evolved/assets/45312898/86fdd075-ee49-4ece-ab6b-14f752a86a88)

**Comment by the1812** [comment]
可以更新至 `e0d033728`
