### ISSUE TITLE
下载视频功能无法选择1080p以上

### ISSUE THREAD

**Issue by Umbra12** [the1812/Bilibili-Evolved#4389]
### 对应功能

b

### 问题描述

大部分视频最高只能下载720p分辨率，比如下图中黑神话官方试玩视频，播放选项中有1080p清晰度可选。

【《黑神话：悟空》首次线下试玩现场直播回放】 https://www.bilibili.com/video/BV19p4y1J7AH/?share_source=copy_web&vd_source=11b54157c9545510d39edb7712bf320e

最后感谢大佬制作的工具，从老版本开始用就非常喜欢，感谢大佬的辛苦付出

### 脚本版本

2.75

### 脚本管理器及版本

v4.19

### 浏览器及版本

chrome版本 116.0.5845.111（正式版本

### 播放器版本

4.4.2

### 播放策略

默认

### 错误信息

```Shell
发
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/63956712/4c1895b5-0243-40fe-9b98-84e6e24b8dec)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
原因不就写在上面了?
![Snipaste_2023-08-29_21-15-36](https://github.com/the1812/Bilibili-Evolved/assets/26504152/5d21ba10-d96c-4669-a0ce-6db77554dd0f)
