### ISSUE TITLE
非常希望加入首页大搜索框大logo的功能

### ISSUE THREAD

**Issue by once-bastion** [the1812/Bilibili-Evolved#439]
**关于哪一项功能**
![QQ图片20200407124635](https://user-images.githubusercontent.com/63277682/78631055-d7a89580-78cd-11ea-9afb-726acfd78b19.png)
非常感谢

**期望的效果**

**脚本版本**

**Comment by the1812** [comment]
之前有人提过了 在#270

**Comment by once-bastion** [comment]
加油吧，up。不过我之前试过stytlus和你的程序会冲突。如果自定义一个【可以顶部导航调用的开关】按钮，是不是就可以不冲突，毕竟我们只是馋这个大搜索框【狗头】

**Comment by once-bastion** [comment]
如果自定义一个【可以顶部导航调用的开关】按钮，是不是就可以不冲突，毕竟我们只是馋这个大搜索框【狗头】

**Comment by once-bastion** [comment]
可以evolved和stylus一起用
