### ISSUE TITLE
Edge更新到116.0.1938.62的新版UI以后，脚本所有功能失效

### ISSUE THREAD

**Issue by zishu-gao** [the1812/Bilibili-Evolved#4393]
### 对应功能

全部功能

### 问题描述

Edge更新到116.0.1938.62的新版UI以后，脚本所有功能失效

### 脚本版本

2.7.5

### 脚本管理器及版本

油猴 4.19.0

### 浏览器及版本

Edge 116.0.1938.62

### 播放器版本

4.4.2-9aef5ecf

### 播放策略

HEVC

### 错误信息

```Shell
没有找到“bilibili evolved”相关字段，脚本似乎未正常加载
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Fiz-Victor** [comment]
相同edge版本，开启新版ui，用的暴力猴，版本v2.8.2-preview，其余参数相同，并未遇到脚本加载失败问题

**Comment by the1812** [comment]
![Snipaste_2023-08-27_17-15-45](https://github.com/the1812/Bilibili-Evolved/assets/26504152/532d495d-5f6b-481d-845f-93f50aa676e8)

**Comment by HeavenTheWind** [comment]
重新安装就解决了

**Comment by YeabutY** [comment]
我也是，浏览器版本、油猴版本、脚本版本和楼主一样，b站页面没有evolved的选项了

**Comment by Yuki020812** [comment]
更新了之后需要开下梯子什么的,我刚刚试过了

**Comment by zishu-gao** [comment]
更新到新版UI以后，打开VPN的情况下进入一次bilibili.com即可解决此问题。

**Comment by Tinhone** [comment]
这个问题可能是脚本更新后需要从 raw.githubusercontent.com 加载 lodash 库导致的

**Comment by the1812** [comment]
jsDelivr 源应该是从 https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js 下载, 不应该加载不出来吧

**Comment by Tinhone** [comment]
> jsDelivr 源应该是从 https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js 下载, 不应该加载不出来吧

原来如此... 我用的预览版，写回复的时候忘记这件事了
