### ISSUE TITLE
无法下载bilibili的番剧 一些无版权的旧番没问题 

### ISSUE THREAD

**Issue by assassincreedv** [the1812/Bilibili-Evolved#440]
#下载功能

**问题描述**

今天Windows笔记本上突然无法下载番剧（昨天仍可以下载），所有有版权的番剧都不可以下载（甚至连下载的button都没了），但旧番和视频下载正常。
例如： 猫眼三姐妹这种旧番可以下载 https://www.bilibili.com/bangumi/play/ss2876
但新一点有版权的番剧 例如实教 不可以下载 https://www.bilibili.com/bangumi/play/ss6339
人在美西，同时使用了解除B站地区限制
我在windows之前使用aria2批量下载到NAS上，又尝试了在mac上安装插件可以正常下载（mac上同样使用了解除B站区域限制的插件）

插件正式版本1.10.14

Windows浏览器 Chrome 80.0.3987.163
mac浏览器Chrome 80.0.3987.149

**错误信息**
无明显错误信息

**附加截图**
![image](https://user-images.githubusercontent.com/26586540/78638560-53202d80-7861-11ea-8b70-76b130faf5ca.png)

**Comment by Coulomb-G** [comment]
解除B站区域限制用的plus的服务器,和b站关系不大,你在国内想下载港澳台番剧的话,请使用港澳台节点的梯子,在海外想下载大陆番剧的话,请使用大陆节点的梯子

**Comment by assassincreedv** [comment]
可是我之前并没用梯子，所以其实我之前相当于是从解除B站区域限制的服务器上下载下来的对么？

**Comment by Coulomb-G** [comment]
那个脚本不是有设置界面么,你可以去看看你是如何设置的代理服务器,"更新"之类的情况也可能修改了默认设置

**Comment by assassincreedv** [comment]
感觉并没有什么特别可以设置的额
![image](https://user-images.githubusercontent.com/26586540/78640657-fa529400-7864-11ea-9b6f-855c4871d6d1.png)

而且 我在mbp上一样的设置 可以下载大陆地区的资源 而且有下载的button 现在Windows上连查看封面的button都没有了 我觉得有些奇怪

**Comment by assassincreedv** [comment]
![image](https://user-images.githubusercontent.com/26586540/78641471-24588600-7866-11ea-9f69-0f78adad2099.png)
附一张console

**Comment by Coulomb-G** [comment]
具体问题你可能得找解除B站区域限制那边的作者,或者直接去plus那边下载吧

**Comment by assassincreedv** [comment]
OKOK  感谢大佬 抽空回答 跪谢
