### ISSUE TITLE
直播信息扩充 报错 侧边栏组件消失

### ISSUE THREAD

**Issue by oxygenkun** [the1812/Bilibili-Evolved#4408]
### 对应功能

直播信息扩充 
Commit: 2daca2959
内部名称: extendFeedsLive

### 问题描述

在新版（也退不回老版本）动态页面，直播栏会被隐藏。
<img width="204" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/24502572/81975b76-0dc1-4867-acf7-abdd9be055fd">

建议对这种可破坏Dom的操作有回退机制，即就算网页改版脚本没对应上，能够不修改原DOM保证正常使用。

### 脚本版本

v2.8.3-preview-83-g164c3a1e6

### 脚本管理器及版本

tampermonkey v4.19.0

### 浏览器及版本

Chrome  116.0.5845.141

### 播放器版本

Null

### 播放策略

默认

### 错误信息

```Shell
extendFeedsLive aside not found
```

### 附加截图

<img width="892" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/24502572/42df6b22-24ef-4b33-92df-478cef5a74b1">

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
新版应该是绿色背景的吧, 我试了下新旧版都没问题啊

**Comment by oxygenkun** [comment]
确实不是新版。我这个版本好像也不是旧版。我在另一个浏览器登陆就没有问题。

对比了两个页面的风格，感觉我出问题的版本像更老的一个版本。

<img width="573" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/24502572/1c6da8b1-f3b9-4476-8830-8ece665acba8">
用另一个浏览器没问题的版本，搜索栏是圆角风格。

<img width="623" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/24502572/35d8126d-b5e1-407f-b85d-7986eb96009f">
我有问题的版本。而且页面也没有变成新版的选择按钮。

估计是B站AB test的问题？
