### ISSUE TITLE
使用默认弹幕设置 不起作用 打开开启弹幕切换视频后弹幕还是默认关闭的

### ISSUE THREAD

**Issue by meihus** [the1812/Bilibili-Evolved#441]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
「开启弹幕」你没开吗?

**Comment by meihus** [comment]
我开了&nbsp; 刷新之后弹幕不会开 但是弹幕设置会弹出来一下然后弹幕设置正常 弹幕不开启

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Coulomb-G"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 下午4:50
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"许元康"<1796414602@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 使用默认弹幕设置 不起作用 打开开启弹幕切换视频后弹幕还是默认关闭的 (#441)





 
「开启弹幕」你没开吗?

**Comment by Coulomb-G** [comment]
是否还安装了其他b站相关的插件?

**Comment by meihus** [comment]
以前下载过什么大会员那个&nbsp; 不会用然后删了 现在B站页面就这些了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Coulomb-G"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 下午4:54
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"许元康"<1796414602@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 使用默认弹幕设置 不起作用 打开开启弹幕切换视频后弹幕还是默认关闭的 (#441)





 
是否还安装了其他b站相关的插件?

**Comment by the1812** [comment]
是原本就不开 还是刚进去的时候开着然后看着它关上?

**Comment by meihus** [comment]
我开启设置，打开视频，弹幕没开
我手动打开弹幕后，看完视频，切换视频，弹幕还是没打开。还需要手动开启。
等于自动打开弹幕设置没起作用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Grant Howard"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 晚上9:44
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"许元康"<1796414602@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 使用默认弹幕设置 不起作用 打开开启弹幕切换视频后弹幕还是默认关闭的 (#441)





 
是原本就不开 还是刚进去的时候开着然后看着它关上?

**Comment by the1812** [comment]
我的意思是弹幕原本是关着的吗?(不开脚本)

**Comment by meihus** [comment]
听了你的不开脚本弹幕是开着的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Grant Howard"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 晚上9:53
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"许元康"<1796414602@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 使用默认弹幕设置 不起作用 打开开启弹幕切换视频后弹幕还是默认关闭的 (#441)





 
我的意思是弹幕原本是关着的吗?(不开脚本)

**Comment by meihus** [comment]
我把所有插件都关了 单独留下就正常了， 试出来这个开着就会有冲突 我该把这个插件删了吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Grant Howard"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 晚上9:53
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"许元康"<1796414602@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 使用默认弹幕设置 不起作用 打开开启弹幕切换视频后弹幕还是默认关闭的 (#441)





 
我的意思是弹幕原本是关着的吗?(不开脚本)

**Comment by the1812** [comment]
哪个插件 你图貌似没发出来

**Comment by meihus** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Grant Howard"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上9:59
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "许元康"<1796414602@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 使用默认弹幕设置 不起作用 打开开启弹幕切换视频后弹幕还是默认关闭的 (#441)





 
哪个插件 你图貌似没发出来
 
&mdash;

**Comment by meihus** [comment]
有群吗 邮件不方便




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Grant Howard"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上9:59
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "许元康"<1796414602@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 使用默认弹幕设置 不起作用 打开开启弹幕切换视频后弹幕还是默认关闭的 (#441)





 
哪个插件 你图貌似没发出来
 
&mdash;

**Comment by the1812** [comment]
直接来Github发啊 邮件带不了图

**Comment by meihus** [comment]
啊 我不知道 截图原来看不到啊 github英文不太会&nbsp; &nbsp;视频网HTML5播放小工具







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Grant Howard"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上10:02
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "许元康"<1796414602@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 使用默认弹幕设置 不起作用 打开开启弹幕切换视频后弹幕还是默认关闭的 (#441)





 
直接来Github发啊 邮件带不了图
 
&mdash;

**Comment by the1812** [comment]
那就删掉吧 b站不缺它这些功能

**Comment by meihus** [comment]
我也不知道这个插件到底怎么用 看到很多人下我就下了 那我删了吧
谢谢作者大大了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Grant Howard"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上10:11
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "许元康"<1796414602@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 使用默认弹幕设置 不起作用 打开开启弹幕切换视频后弹幕还是默认关闭的 (#441)





 
那就删掉吧 b站不缺它这些功能
 
&mdash;
