### ISSUE TITLE
疑似自定义顶栏导致动态空白，且脚本会报错

### ISSUE THREAD

**Issue by Adiwon** [the1812/Bilibili-Evolved#4416]
### 对应功能

自定义顶栏

### 问题描述

开启自定义顶栏时，鼠标移到“动态”之后弹出的下拉菜单空白，且左下角报错
` (0 , a.descendingBiglntSort) is not a function`

### 脚本版本

v2.7.5-58-g77b42bc3b

### 脚本管理器及版本

Tampermonkey  v4.19.0

### 浏览器及版本

（64 位） (Portable) (Chromium 102.0.5005.167)

### 播放器版本

4.4.10-e317216a

### 播放策略

AVC

### 错误信息

```Shell
直接报错：  (0 , a.descendingBiglntSort) is not a function
```

### 附加截图

<img width="905" alt="屏幕截图 2023-09-08 112215" src="https://github.com/the1812/Bilibili-Evolved/assets/16150302/88f0f1b8-07a2-49a3-8155-fc5f5af91cf1">
<img width="945" alt="屏幕截图 2023-09-08 113145" src="https://github.com/the1812/Bilibili-Evolved/assets/16150302/38f19c51-1ce9-4b0d-a812-03f9aee03d0d">
<img width="934" alt="屏幕截图 2023-09-08 113157" src="https://github.com/the1812/Bilibili-Evolved/assets/16150302/b607cfd5-552f-437d-8bdc-c1512b205b99">

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
更新下脚本

**Comment by Adiwon** [comment]
> 更新下脚本

更新后解决了

**Comment by LLdaa** [comment]
v2.7.6-9-g881ccf2f0  动态还是空白  脚本没报错

**Comment by hen0920** [comment]
v2.7.6-9-g881ccf2f0  更新后还是空白 控制台无报错

Bilibili Evolved {code: 0, message: '0', ttl: 1, data: {…}}
Bilibili Evolved nextPage get []

**Comment by bayunhuiye** [comment]
v2.7.6动态依旧空白，且左下角报错(0 , i.descendingBigIntSort) is not a function
浏览器：360极速浏览X

**Comment by esummr** [comment]
版本chorme 116.0.5845.180（正式版本） （64 位）
v2.7.6-9-g881ccf2f0
动态除直播外，视频、动画、专栏三项均无法显示，无报错

**Comment by yan624** [comment]
最新版依旧空白。动态接口返回数据正常。

**Comment by 840119580** [comment]
版本2.8.4 preview预览版
动态除直播外，
视频、动画、专栏三项均无法显示
自定义顶栏导致 关闭顶栏恢复

**Comment by yan624** [comment]
> 最新版依旧空白。动态接口返回数据正常。

解決了。左边侧边栏，点击更新所选组件就行了。

**Comment by LVincent555** [comment]
![image](https://github.com/the1812/Bilibili-Evolved/assets/22406963/36b1cb3f-15f6-401e-8195-67349bd9d751)
版本 v2.7.6-59-g3d43a4e0c
视频、动画、专栏三项均无法显示
自定义顶栏导致 关闭顶栏恢复
后台能拿到数据
![image](https://github.com/the1812/Bilibili-Evolved/assets/22406963/4394142d-e645-44f3-9d74-75550b12bf35)

**Comment by Kamisato100** [comment]
v2.7.6版本最近重新出现此问题，所有插件都已经更新到自动检测的最新。浏览器Google Chrome版本 116.0.5845.111
动态下拉框中视频一栏无法加载出内容。此前遇到过但更新之后解决，不知为何今天再次发生这个问题。
左下角弹框报错内容为：(0 , i.parseCount) is not a function

**Comment by Lin-XCC** [comment]
> v2.7.6版本最近重新出现此问题，所有插件都已经更新到自动检测的最新。浏览器Google Chrome版本 116.0.5845.111 动态下拉框中视频一栏无法加载出内容。此前遇到过但更新之后解决，不知为何今天再次发生这个问题。 左下角弹框报错内容为：(0 , i.parseCount) is not a function

确实 我也出现了。

**Comment by LynxCatTheThird** [comment]
Google Chrome 版本 117.0.5938.132（Arch 系统）
Bilibili Evolved (Preview) 版本 v2.8.4-preview-103-g6049a6149
已检查所有更新，现象为动态下拉框中视频一栏无法加载出内容，左下角弹框报错`(0 , i.parseCount) is not a function`

**Comment by Geeyun-JY3** [comment]
@LynxCatTheThird 正式版和预览版最新版都是 2.8.5
