### ISSUE TITLE
顶栏动态总是有数字（即使没有新动态）

### ISSUE THREAD

**Issue by Cleansweep7** [the1812/Bilibili-Evolved#4427]
### 对应功能

自定义顶栏

### 问题描述

顶栏上的动态按钮总是有数字，即使已经没有新动态。今天一开始是1，晚上变成了2

### 脚本版本

2.7.6

### 脚本管理器及版本

Tampermonkey v4.19

### 浏览器及版本

edge 115.0.1901.203 和 360极速浏览x 21.0.1206

### 播放器版本

4.4.10

### 播放策略

AVC

### 错误信息

```Shell
Bilibili Evolved Array(44)0: 9580583351: 8303274732: 3909882833: 3205509324: 5925847465: 2754134036: 4906026337: 6151858228: 5754240499: 87309134510: 78787190911: 93300392412: 61705560813: 2844071614: 79722141815: 22158579616: 29213798217: 31616857018: 57369938719: 82810849320: 31559713421: 25153764022: 40189332623: 31546891224: 31510704825: 40260916426: 82749934727: 27230166528: 69911161529: 93190833430: 8524644031: 69925658232: 48683219833: 52936920234: 98183140335: 30320127136: 99491688937: 82656833038: 39823128639: 59661522440: 95370849741: 40089024042: 52835681343: 498545781length: 44__ob__: De {value: Array(44), shallow: false, mock: false, dep: ge, vmCount: 0}[[Prototype]]: Array undefined false
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=b3c4f19e-8bea-4faf-a9a1-c40f0696ea2a:253 Bilibili Evolved Array(44) undefined false
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=b3c4f19e-8bea-4faf-a9a1-c40f0696ea2a:253 Bilibili Evolved Object
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=b3c4f19e-8bea-4faf-a9a1-c40f0696ea2a:253 Bilibili Evolved Object
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=b3c4f19e-8bea-4faf-a9a1-c40f0696ea2a:253 Bilibili Evolved Object
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=b3c4f19e-8bea-4faf-a9a1-c40f0696ea2a:253 Bilibili Evolved nextPage get Array(16)
2userscript.html?name=Bilibili-Evolved-Preview.user.js&id=b3c4f19e-8bea-4faf-a9a1-c40f0696ea2a:253 Bilibili Evolved 网址参数清理 History API 拦截 /video/BV1e541137Tc/?vd_source=9189c1617eade4583af208233abcdf24 https://www.bilibili.com/video/BV1e541137Tc/
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=b3c4f19e-8bea-4faf-a9a1-c40f0696ea2a:253 Bilibili Evolved videoChange 460541448 460541448
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=b3c4f19e-8bea-4faf-a9a1-c40f0696ea2a:253 Bilibili Evolved (44) [958058335, 830327473, 390988283, 320550932, 592584746, 275413403, 490602633, 615185822, 575424049, 873091345, 787871909, 933003924, 617055608, 28440716, 797221418, 221585796, 292137982, 316168570, 573699387, 828108493, 315597134, 251537640, 401893326, 315468912, 315107048, 402609164, 827499347, 272301665, 699111615, 931908334, 85246440, 699256582, 486832198, 529369202, 981831403, 303201271, 994916889, 826568330, 398231286, 596615224, 953708497, 400890240, 528356813, 498545781, __ob__: De] 460541448 false
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/59435862/f139ef28-8072-4bb9-9f9a-870c7400b03e)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Cleansweep7** [comment]
暂时没出现了

**Comment by BillGoldenWater** [comment]
猜想: 
https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/all/update 返回的应该是所有类型的动态的未读数, 而顶栏动态只能读到视频的动态, 所以会有消不掉的未读数, 点进[动态页面](https://t.bilibili.com/)后这消不掉的未读数确实消失了

建议的解决方法, 使用 https://api.bilibili.com/x/web-interface/dynamic/entrance 里的 `update_info.item.count` 来获取顶栏动态的未读数

建议 Reopen 该 Issue

**Comment by animationplayer** [comment]
v2.8.4-preview-103-g6049a6149
目前也有一样的问题
