### ISSUE TITLE
首页滚动栏广告屏蔽失效

### ISSUE THREAD

**Issue by dskaowu** [the1812/Bilibili-Evolved#444]
**关于哪一项功能**
广告屏蔽

**问题描述**

首页广告屏蔽失效（滚动栏）

**脚本版本**
正式版1.10.14

**浏览器版本**
Chrome 80

**错误信息**

**附加截图**
![N %)$Q3()CQE~OFU1LI9D0V](https://user-images.githubusercontent.com/34599430/78757974-f67f5880-79af-11ea-9a80-47b4abadaf74.png)

**Comment by the1812** [comment]
同#442

**Comment by dskaowu** [comment]
> 同#442

指公主链接那个，滚动栏位置的广告

**Comment by the1812** [comment]
好的
