### ISSUE TITLE
啓動腳本後，Ｂ站營運的ＦＧＯ的下級網頁打不開

### ISSUE THREAD

**Issue by YheonYeung** [the1812/Bilibili-Evolved#445]
**关于哪一项功能**

**问题描述**

已試過停用所有擴充功能及腳本，發現是該腳本引致。
https://game.bilibili.com/fgo
首頁是正常的，譬如當點開公告內容，就會顯示圖中內容。
在greasyfork.org那邊開帖沒見回覆，來這邊問了。

**脚本版本**

1.10.12、1.10.14

**浏览器版本**

Cent Browser 版本 4.2.7.128 (正式版本) (32 位元) (Chromium 80.0.3987.149)

**错误信息**

The requested URL was not found on this server. Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!

URL:	http://game.bilibili.com/news.html
Server:	tgameops-static-slb-app-1
Date:	2020/04/08 17:06:16
Powered by Tengine

**附加截图**
![image](https://user-images.githubusercontent.com/63342274/78766556-fc7b3680-79bb-11ea-9180-09d9b74a8498.png)

**Comment by Coulomb-G** [comment]
是「网址参数清理」的误伤,之前忘了回复,我的锅

**Comment by YheonYeung** [comment]
> 是「網址參數清理」的誤傷，之前忘了回复，我的鍋，正式版沒更新前可以先暫時把這個功能關了

感謝回覆，期待修復。

> 是「网址参数清理」的误伤,之前忘了回复,我的锅,正式版没更新前可以先暂时把这个功能关了

感謝回覆。我不懂編碼……能請教下怎麼操作嗎？

**Comment by Coulomb-G** [comment]
打开左侧「设置」的「工具」栏,点击关闭「网址参数清理」,下次更新会修复的
