### ISSUE TITLE
部分动态相关功能在个人空间搜索结果页中失效及相关 bug

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#4458]
### 对应功能

- 快速收起评论
  Commit: 35578ac47
  内部名称: foldComments
- 禁止跳转动态详情
  Commit: 35578ac47
  内部名称: disableFeedsDetails
- 复制动态链接
  Commit: 35578ac47
  内部名称: copyFeedsLink
- 图片批量导出
  Commit: 35578ac47
  内部名称: imageExporter
- 动态看图自动回顶
  Commit: 35578ac47
  内部名称: imageAutoBackToTop

（写这些是因为只测了这些，不确定有没有遗漏）

### 问题描述

（和 #2137 大差不差。其实印象中已经失效挺久了，之前一直懒得报，以为说不定哪天就给修了）

`快速收起评论`、`禁止跳转动态详情`、`复制动态链接`、`图片批量导出`、`动态看图自动回顶`组件在个人空间搜索结果页中的动态均已失效。
也就只有`展开动态内容`还生效。

这似乎同时导致了：若从个人空间搜索结果页切换至同一用户的动态 tab，上述动态相关功能失效。

碎碎念：

- 有点难绷的是，实测个人空间搜索结果页原生好像是能做到退出查看图片模式时自动将动态移入视图内的（即`动态看图自动回顶`组件的一部分功能）
- 令人感叹的是，时隔两年，这个搜索页面的圆角和边框还是 https://github.com/the1812/Bilibili-Evolved/issues/2137#issuecomment-898859320 图里的鬼样（见下附加截图 1）。
- 而且这个人空间搜索结果页好像还有 bug：若结果包含的被转发动态所属 UP 注册时间较晚，uid 较长（今天发现的例子是 16 位），在这个搜索结果页鼠标悬停这个所属 UP 名字显示的 URL 是没转换过（？）的（今天发现的例子为 10 位 uid），直接导致此 URL 是无效的，无法直接点击进入这个所属 UP 的个人空间。

### 脚本版本

v2.8.5-preview-103-g35578ac47

### 脚本管理器及版本

Tampermonkey v4.20.6185

### 浏览器及版本

Chrome 116.0.5845.188  （正式版本） （64 位）

### 播放器版本

不相关

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

`禁止跳转动态详情`、`复制动态链接`、`图片批量导出`：
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/15d3362d-be16-4ade-a47f-d7ccecc7951b)
`快速收起评论`：
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/e3cc17dc-a14e-43f2-8e17-f77bb29c74e0)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
其实这类你可以统称为 Feeds API 没适配, 适配的话那一堆动态相关功能自然都会生效的

**Comment by the1812** [comment]
这还不太好做适配, Feeds API 是根据不同页面去适配的, 空间这里直接看动态是 v2 的动态, 搜索又是 v1 的动态, 目前直接判定成 v2 的所以解析不了 v1 的了.
我先把搜索时判断为没有动态, 至少不会影响到直接看的时候, 等阿 b 什么时候把搜索改成 v2 的再加回来. 目前搜索出来的动态点开详情还是可以正常使用相关功能的.

**Comment by Geeyun-JY3** [comment]
只能说真的很难绷，动态详情页、动态首页和个人空间`动态` tab 都改成什么样了（印象中是改了又改），甚至连个人空间`投稿` tab 下的专栏都已经改成图文了，[两年半前提过的个人空间搜索页面的边框和圆角](https://github.com/the1812/Bilibili-Evolved/issues/2137#issuecomment-898859320)仍然是没做的。
估计这功能做出来后就没怎么管过，协同更新什么的优先级并不高。
