### ISSUE TITLE
下载1080p+的视频，下载后观看帧率还是24帧，并没有60帧

### ISSUE THREAD

**Issue by liao666brant** [the1812/Bilibili-Evolved#446]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
原视频是60帧?

**Comment by liao666brant** [comment]
哦哦，原来如此，我理解错了。

**Comment by liao666brant** [comment]
> 原视频是60帧?1080P+是高码率,并不是高帧

哦哦，原来如此，我理解错了。
