### ISSUE TITLE
正式版 (jsDelivr 源)无法安装，还有其他的源吗？

### ISSUE THREAD

**Issue by ToKingl** [the1812/Bilibili-Evolved#4460]
### 对应功能

无

### 问题描述

如题，正式版 (jsDelivr 源)点击安装链接后，打开的界面是一片空白，复制安装链接在油猴管理面板的【实用工具-从 URL 安装】内也无法安装，提示的是：“无法从该 URL 加载脚本: https://fastly.jsdelivr.net/gh/the1812/Bilibili-Evolved@master-cdn/dist/bilibili-evolved.user.js ”，还有其他可用的源吗，希望能再增加一个在国内可用的源。

### 脚本版本

无

### 脚本管理器及版本

Tampermonkey v4.20.6187

### 浏览器及版本

Firefox 118.0(64位)

### 播放器版本

无

### 播放策略

默认

### 错误信息

```Shell
无
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by DUXING130** [comment]
> ### 对应功能
> 无
> 
> ### 问题描述
> 如题，正式版 (jsDelivr 源)点击安装链接后，打开的界面是一片空白，复制安装链接在油猴管理面板的【实用工具-从 URL 安装】内也无法安装，提示的是：“无法从该 URL 加载脚本: https://fastly.jsdelivr.net/gh/the1812/Bilibili-Evolved@master-cdn/dist/bilibili-evolved.user.js ”，还有其他可用的源吗，希望能再增加一个在国内可用的源。
> 
> ### 脚本版本
> 无
> 
> ### 脚本管理器及版本
> Tampermonkey v4.20.6187
> 
> ### 浏览器及版本
> Firefox 118.0(64位)
> 
> ### 播放器版本
> 无
> 
> ### 播放策略
> 默认
> 
> ### 错误信息
> ```shell
> 无
> ```
> 
> ### 附加截图
> _No response_
> 
> ### 致遇到了相同问题准备回复的人
> **太长不看**： 1、遇到了相同的问题：**请用左下角的 reaction 点赞** 2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。 **_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
> 
> 完整版
国内没有免费CDN

**Comment by ToKingl** [comment]
> > ### 对应功能
> > 无
> > ### 问题描述
> > 如题，正式版 (jsDelivr 源)点击安装链接后，打开的界面是一片空白，复制安装链接在油猴管理面板的【实用工具-从 URL 安装】内也无法安装，提示的是：“无法从该 URL 加载脚本: https://fastly.jsdelivr.net/gh/the1812/Bilibili-Evolved@master-cdn/dist/bilibili-evolved.user.js ”，还有其他可用的源吗，希望能再增加一个在国内可用的源。
> > ### 脚本版本
> > 无
> > ### 脚本管理器及版本
> > Tampermonkey v4.20.6187
> > ### 浏览器及版本
> > Firefox 118.0(64位)
> > ### 播放器版本
> > 无
> > ### 播放策略
> > 默认
> > ### 错误信息
> > ```shell
> > 无
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 附加截图
> > _No response_
> > ### 致遇到了相同问题准备回复的人
> > **太长不看**： 1、遇到了相同的问题：**请用左下角的 reaction 点赞** 2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。 **_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
> > 完整版
> > 国内没有免费CDN

找到办法了，把由 Fastly 提供的fastly.jsdelivr.net替换成G-Core 提供的gcore.jsdelivr.net就能正常访问并安装了

**Comment by the1812** [comment]
README 忘更新了...
现在的 jsDelivr 源链接应该是 https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@master-cdn/dist/bilibili-evolved.user.js

**Comment by Geeyun-JY3** [comment]
巧了，最近也有人在问：#4457

**Comment by lisonge** [comment]
可以将脚本发布到 npm 上，然后通过类似如下的镜像加速链接安装

<https://registry.npmmirror.com/vue/latest/files/dist/vue.global.js>

此外 require 的链接也可以全部换成 npmmirror 的
