### ISSUE TITLE
进入视频右上角的up个人空间会一片空白

### ISSUE THREAD

**Issue by shimakotodo** [the1812/Bilibili-Evolved#4466]
### 对应功能

v2.8.5-71-g10300c16b

### 问题描述

最近由于顶栏自定义报错问题，更新了2.85版，就出现了这个空白问题，就是点击视频右上角的up名字，进入他的个人空间，经常会一片空白，要反复刷新几次才会出现内容。关闭Bilibili Evolved后，则一切正常。
从收藏夹里直接进入up的个人空间页面，也同样会一片空白，要多刷新，或者关闭Evolved才能正常。

### 脚本版本

v2.8.5-71-g10300c16b

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

Microsoft Edge 版本 117.0.2045.43 (正式版本) (64 位)

### 播放器版本

4.5.7

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![Uploading 屏幕截图(79).png…]()
![Uploading 屏幕截图(80).png…]()

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Fiz-Victor** [comment]
@shimakotodo 图片上传失败了？报错应该不会没有吧

**Comment by shimakotodo** [comment]
![屏幕截图(79)](https://github.com/the1812/Bilibili-Evolved/assets/64628237/06336f1a-41aa-426c-a84e-2fbeb77c2208)
![屏幕截图(80)](https://github.com/the1812/Bilibili-Evolved/assets/64628237/2742bd01-32af-44a9-9c44-19ac117042c3)

刚才图片没传成功，不是某个功能报错，而是整个页面空白。

**Comment by Fiz-Victor** [comment]
v2.8.5-preview-103-g35578ac47
无法复现，尝试更新到最新版

**Comment by shimakotodo** [comment]
又反复实验，当前的v2.8.5-71-g10300c16b，从收藏夹里直接打开收藏的多个up个人空间页面，的确还是那样，有部分是正常的，另一部分则是空白，要反复刷新才出现。
如果别人没有这个问题，可能是我自己的电脑问题。虽然不知道怎么解决，姑且凑合着用吧。

**Comment by Tinhone** [comment]
关于个人空间页面空白问题，我很久之前就开始遇到了，但次数很少，下次遇到的时候我往这里补点信息来。

没想到这个问题不是只在我这里出现的，不知道是 B 站的问题还是脚本的问题...

**Comment by kamikaze211** [comment]
点击用户的空间里的投稿页面，没反应，新窗口打开发现自动跳转到了https://space.bilibili.com/
