### ISSUE TITLE
chrome版edge 顶部栏搜索框的右侧只能显示用户和投稿，其他显示不出

### ISSUE THREAD

**Issue by ax-prayer** [the1812/Bilibili-Evolved#447]
[试了几个版本都出现这种情况。顶部右侧的收藏、动态等在勾选显示的情况下无法显示出来。
不知道该如何在这里添加图片。。。。。edge是刚在官网下载的最新版
![批注 2020-04-09 001038](https://user-images.githubusercontent.com/15603867/78807388-919b2100-79f6-11ea-9446-deaef359f70f.png)

**Comment by Coulomb-G** [comment]
你登录了吗?

**Comment by ax-prayer** [comment]
> 你登录了吗?

......原来要登录后显示，谢谢啦
