### ISSUE TITLE
视频不见了

### ISSUE THREAD

**Issue by NAN123d** [the1812/Bilibili-Evolved#448]
**关于哪一项功能**

**问题描述**

视频直接消失，页面加载时候 视频区域加载一下就直接消失掉了。动态里的视频和首页推送的视频都是这种问题，投稿视频全都看不了，但番剧和直播是可以正常使用的。更新之前没有这种问题。昨晚好了一会，但今天又出现了这种情况。

**脚本版本**

 脚本1.10.14

**浏览器版本**

Chrome 版本 80.0.3987.122（正式版本） （64 位）

**错误信息**

console截图
![错误](https://user-images.githubusercontent.com/63349503/78855505-a7d8c980-7a56-11ea-91a5-d2bcfa8fc077.png)

**附加截图**
视频界面
![界面](https://user-images.githubusercontent.com/63349503/78855543-c0e17a80-7a56-11ea-802d-f14fb10ae2b3.png)

**Comment by the1812** [comment]
参考#254 / #379

**Comment by NAN123d** [comment]
> 参考#254 / #379

懂了，感谢！
