### ISSUE TITLE
动态横幅左边 bilibili logo 被拉伸

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#4480]
### 对应功能

不知道

### 问题描述

这应该算是旧版原版顶栏的相关 bug，我现在首页就是旧版首页，就还是旧版原版顶栏，也能复现。

新版原版顶栏就没这问题。顺便一提，新版自定义顶栏也不会有 #1247 提到的隐藏左边 bilibili logo 和鼠标悬停横幅出现的提示的情况了。

（其实原本想顺便捞一下 #4447，就是不知道为啥 issue 主自己关了

### 脚本版本

v2.8.5-preview-103-g35578ac47

### 脚本管理器及版本

Tampermonkey v4.19.6185

### 浏览器及版本

Chrome 117.0.5938.150 （正式版本） （64 位）

### 播放器版本

不相关

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/64f3f614-a7ee-49f8-80d1-c3290ee4bf50)
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/251153b3-de5b-4e41-b836-a23af3169d73)
正常的样子：
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/6d944301-e359-4da5-9f76-e6dfe9b3312f)
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/fcc97790-77a3-430d-bb64-8701af8f5f61)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
看起来像是 `高分辨率图片` 导致的, 这个 Logo 的容器只限制了高度导致增加分辨率后只有宽度变了

**Comment by Geeyun-JY3** [comment]
还真是`高分辨率图片`导致的。

**Comment by Geeyun-JY3** [comment]
还真是`高分辨率图片`导致的。

**Comment by Geeyun-JY3** [comment]
bug 似乎还在：
![image](https://github.com/the1812/Bilibili-Evolved/assets/49396421/2155f445-4b14-4584-a57d-9e4e4e8baddc)

**Comment by the1812** [comment]
未能复现, 难道你那的 `class` 变了?
![Snipaste_2024-05-01_11-07-39](https://github.com/the1812/Bilibili-Evolved/assets/26504152/6cfd21c8-bfbc-4188-a2cf-bb876861a57a)

![Snipaste_2024-05-01_11-07-02](https://github.com/the1812/Bilibili-Evolved/assets/26504152/d5fd4aa7-025d-4ae4-89a3-0cee1345282a)
