### ISSUE TITLE
建议下视频时可以选择将封面一同下下来

### ISSUE THREAD

**Issue by wzxyisme** [the1812/Bilibili-Evolved#449]
**关于哪一项功能**
关于下载视频
**期望的效果**
建议下视频时可以选择是否将封面下到同一个压缩包😋

**脚本版本**

**Comment by the1812** [comment]
封面直接右键保存啊

**Comment by wzxyisme** [comment]
想要封面下载和弹幕一样加入下载选项，在下视频时一起下载并压缩在同一个包里

**Comment by wzxyisme** [comment]
> 封面直接右键保存啊

希望封面下载和弹幕一样加入下载选项，在下视频时一起下载并压缩在同一个包里

**Comment by the1812** [comment]
为什么要纠结于在一个压缩包里? 保存一张图片并不费事
