### ISSUE TITLE
视频播放中暂停显示封面

### ISSUE THREAD

**Issue by Mr-EEEeee** [the1812/Bilibili-Evolved#4491]
### 对应功能

![image](https://github.com/the1812/Bilibili-Evolved/assets/82107297/2325d05d-4d00-4513-8ee9-9d02fd1c0e37)

### 问题描述

这个问题从很早就有，但是中间有段时间好像修复了，后来又出现到现在一直这样，之前的问题close了
![image](https://github.com/the1812/Bilibili-Evolved/assets/82107297/af09ba8c-0df3-430b-8217-cdf3a561f0cd)

### 脚本版本

v2.8.5-24-g3d78bf7c9

### 脚本管理器及版本

4.19.0

### 浏览器及版本

Microsoft Edge 版本 117.0.2045.60 (正式版本) (64 位)

### 播放器版本

4.6.0-199a5709

### 播放策略

默认

### 错误信息

```Shell
截图
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/82107297/154f41b3-b8d9-4e1f-87ea-98c13a5aae00)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by YaeSakuraQvQ** [comment]
chrome`118`播放器`4.6.1-7e0f99fb`搭配tampermonkey`4.19.0`脚本`v2.8.5-preview-103-g35578ac47`复现相同问题
关闭"播放前显示封面"则不出现该bug

**Comment by MikuApp** [comment]
Chrome 119.0.6045.106，播放器 4.7.2-ffdcbfca，油猴 4.19.0，脚本 2.8.5 复现相同问题
补充条件：只有每次打开视频后的第一次暂停会出现此情况，之后的暂停正常

**Comment by YaeSakuraQvQ** [comment]
尝试在分p视频中的p2及以后进行复现，这样复现概率大
不过是偶发问题，我现在又不出现了。如果还是不能复现，就先放着吧，我下次再出这个bug了抓点日志给大佬看看

**Comment by MikuApp** [comment]
> 尝试在分p视频中的p2及以后进行复现，这样复现概率大 不过是偶发问题，我现在又不出现了。如果还是不能复现，就先放着吧，我下次再出这个bug了抓点日志给大佬看看

我这边复现概率很高，但是不清楚如何抓取日志

是打开开发者模式之后看F12控制台吗？

**Comment by the1812** [comment]
1. 看根元素上有没有 `--cover-url`
![Snipaste_2023-11-08_08-00-18](https://github.com/the1812/Bilibili-Evolved/assets/26504152/9c225993-bcfd-4411-8914-940e5bbaaeb5)
2. 看控制台是否有以下几条报错
![Snipaste_2023-11-08_08-00-56](https://github.com/the1812/Bilibili-Evolved/assets/26504152/8273ca2d-0511-47ec-8555-451f1bf07e4b)

**Comment by MikuApp** [comment]
> 1. --cover-url

根元素上有`--cover-url`，控制台没有这几条相关的输出

发现了一个可以稳定触发的方式：关闭自动开播，打开一个视频，在视频加载出画面后立即点播放（此时封面还没有出现），播放一段时间后再暂停，封面就会出现
