### ISSUE TITLE
首页的旧版本回退指南,点击显示Not Found

### ISSUE THREAD

**Issue by 1213822** [the1812/Bilibili-Evolved#4495]
### 对应功能

首页的更新功能

### 问题描述

首页的[旧版本回退指南](https://github.com/the1812/doc/rollback.md) Not Found
应该改为 https://github.com/the1812/Bilibili-Evolved/blob/master/doc/rollback.md

### 脚本版本

2.85

### 脚本管理器及版本

Tampermonkey v4.19.6176

### 浏览器及版本

谷歌

### 播放器版本

1

### 播放策略

AV1

### 错误信息

```Shell
首页的[旧版本回退指南](https://github.com/the1812/doc/rollback.md) Not Found
应该改为 https://github.com/the1812/Bilibili-Evolved/blob/master/doc/rollback.md
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
是怎么点成那个链接的? 我在首页是正常的链接啊

![Snipaste_2023-11-03_09-22-28](https://github.com/the1812/Bilibili-Evolved/assets/26504152/896159c4-3ec8-42e9-9aab-36bd28189894)

**Comment by Geeyun-JY3** [comment]
这 issue 刚发出来的时候我好像复现过，忘记截图存档了，不会是 GitHub 当时的 bug 吧？
