### ISSUE TITLE
怎么样使用批量下载

### ISSUE THREAD

**Issue by du-muqiao** [the1812/Bilibili-Evolved#451]
如题

**Comment by Coulomb-G** [comment]
aria2或aria2 RPC

**Comment by du-muqiao** [comment]
感谢

**Comment by CuiEnPeng** [comment]
aria2 和 aria2PRC下载下来的而不是 xml 文件就是 txt 文件，怎么解决啊？

**Comment by Coulomb-G** [comment]
> aria2 和 aria2PRC下载下来的而不是 xml 文件就是 txt 文件，怎么解决啊？

txt文件说明是正常情况,请参考https://github.com/the1812/Bilibili-Evolved/blob/master/aria2-notice.md
