### ISSUE TITLE
插件-[直播首页静音] bug反馈

### ISSUE THREAD

**Issue by Qm-jmz** [the1812/Bilibili-Evolved#4511]
### 对应功能

出现问题的功能：直播首页静音
Commit:3d78bf7c9
内部名称: liveHomeMute

### 问题描述

问题：打开直播间首页静音与隐藏首页直播板块选项后，在刚打开直播首页时仍有3s左右的直播声音，后消失；同时保持网页开启一段时间后（时长不确定），首页直播声音再次出现，并不会消失。
重现过程：
1. 关闭除油猴外的其他浏览器插件
2. 只打开直播首页静音（并不必须但我为了避免插件间干扰所以关掉了其他插件）同时打开隐藏首页直播板块选项，脚本设置截图如下
![image](https://github.com/the1812/Bilibili-Evolved/assets/50917637/1d203898-2098-4ec9-8ca3-6db95e7fafd7)
3. 打开直播首页，此时问题出现，浏览器截图如下
![image](https://github.com/the1812/Bilibili-Evolved/assets/50917637/890502dc-e0eb-4c99-9224-efa485d40168)
如画面显示，首页直播板块成功隐藏，但有声音，证据为截图中窗口标题的小喇叭图标
4. 放置一段时间后，声音再次出现，并保持（暂无截图）

### 脚本版本

v2.8.5-24-g3d78bf7c9

### 脚本管理器及版本

篡改猴测试版 5.0.6189

### 浏览器及版本

Chrome 118.0.5993.118

### 播放器版本

Bilibili HTML5 Live Player 3.7.13

### 播放策略

默认

### 错误信息

```Shell
无报错
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
[#4459](https://github.com/the1812/Bilibili-Evolved/issues/4459#issuecomment-1751978694)
