### ISSUE TITLE
在Aria2无法下载视频，提示403或405错误

### ISSUE THREAD

**Issue by Craftsman98** [the1812/Bilibili-Evolved#452]
**关于哪一项功能**
下载视频

**问题描述**

导出下载链接后使用Aria2下载提示403或405错误

**脚本版本**

1.10.14

**浏览器版本**

Microsoft Edge 版本 81.0.416.45 (官方内部版本) beta (64 位)

**错误信息**

**附加截图**

<img width="878" alt="批注 2020-04-10 194803" src="https://user-images.githubusercontent.com/38043100/78988865-a72e5900-7b64-11ea-9515-823a5d7731dc.png">
<img width="890" alt="批注 2020-04-10 194824" src="https://user-images.githubusercontent.com/38043100/78988869-a8f81c80-7b64-11ea-898b-5315d583d65c.png">

**Comment by the1812** [comment]
请检查下对aria2的配置, 从图中来看不只是无法下载, 文件名之类的信息也没有

**Comment by Craftsman98** [comment]
使用aria2 RPC可以下载。之前应该是我设置的问题，sry

> 请检查下对aria2的配置, 从图中来看不只是无法下载, 文件名之类的信息也没有

**Comment by strive-kun** [comment]
你好，你是怎样解决的

**Comment by fgr178707** [comment]
你好，你是怎样解决的
