### ISSUE TITLE
不是bug，希望给拓展倍速加一个一键改变（原倍速/记忆倍速状态）的按键

### ISSUE THREAD

**Issue by Clov3rBug** [the1812/Bilibili-Evolved#4524]
### 对应功能

[@JLoeve](https://github.com/LonelySteve)

### 问题描述

就是平时使用记忆倍速的功能比较多，经常需要更改（记忆倍速/原倍速）默认的鼠标停留再选择效率有点低，可以像是youtube一样，直接点一下倍速键就可以更改这两种状态吗（记忆倍速/原倍速），如果有开记忆倍速插件的就默认记忆倍速和原倍速切换，没有开这个插件的就默认2倍速或者1.5倍速什么的

### 脚本版本

v2.8.5-24-g3d78bf7c9

### 脚本管理器及版本

Tampermonkey v4.19.6176 

### 浏览器及版本

版本 119.0.6045.124（正式版本） （64 位）

### 播放器版本

HTML5播放器 V4.5.5

### 播放策略

HEVC

### 错误信息

```Shell
无错误
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
不是 bug 你就应该去开 discussion。

***

你说的「原倍速」是指最近一个视频所使用的倍速还是 1.0x？
YouTube 原生有你说的「直接点一下倍速键就可以更改这两种状态」这种功能吗？

装了[`快捷键扩展 - 视频倍速`](https://github.com/the1812/Bilibili-Evolved/blob/master/doc/features/features.md#快捷键扩展---视频倍速)这个插件后，`快捷键扩展`中的`切换倍速`目前就能做到在有开`记忆倍速`时在`全局记忆倍速值`所设倍速值和 1.0x 间切换（还需在`记忆倍速`中开启`固定全局倍速值`），在没开`记忆倍速`时在 1.0x 和在当前视频最近使用的倍速值间切换。

**Comment by Clov3rBug** [comment]
> 不是 bug 你就应该去开 discussion。
> 
> 你说的「原倍速」是指最近一个视频所使用的倍速还是 1.0x？ YouTube 原生有你说的「直接点一下倍速键就可以更改这两种状态」这种功能吗？
> 
> 装了[`快捷键扩展 - 视频倍速`](https://github.com/the1812/Bilibili-Evolved/blob/master/doc/features/features.md#%E5%BF%AB%E6%8D%B7%E9%94%AE%E6%89%A9%E5%B1%95---%E8%A7%86%E9%A2%91%E5%80%8D%E9%80%9F)这个插件后，`快捷键扩展`中的`切换倍速`目前就能做到在有开`记忆倍速`时在`全局记忆倍速值`所设倍速值和 1.0x 间切换（还需在`记忆倍速`中开启`固定全局倍速值`），在没开`记忆倍速`时在 1.0x 和在当前视频最近使用的倍速值间切换。

哦哦，那我等会再去发个discussion，不太会用哈哈哈。
记忆倍速是开了记忆倍速以后自己设置的默认全局倍速，原倍速是1.0x
想了下，好像不是youtube，抱歉，应该是twitter还是telegram来着。

那个插件我也有装，不过那个是shift+/ 快速切换，我平时也一直在用，但是如果在加上这个功能的话就可以不用到键盘直接切换了
