### ISSUE TITLE
首页最顶部丢失，没有搜索栏，设置里面各项点开无效，一直显示更新

### ISSUE THREAD

**Issue by thghxf123** [the1812/Bilibili-Evolved#453]
显示更新后无效

![image](https://user-images.githubusercontent.com/53709810/79058886-f62fd780-7ca5-11ea-8ad5-e2b4bfbacf34.png)

顶部搜索栏不出现
![image](https://user-images.githubusercontent.com/53709810/79058868-b7018680-7ca5-11ea-99b5-65f7d71b4347.png)

**Comment by the1812** [comment]
参考#432 检查下是不是装了两个

**Comment by thghxf123** [comment]
> 参考[＃432](https://github.com/the1812/Bilibili-Evolved/issues/432)检查下是不是装了两个

好像是装了两个，但是不知道具体怎么删除这个脚本，设置各选项都点不动

**Comment by Coulomb-G** [comment]
暴力猴的话,打开控制台「已安装的脚本」,就可以删除了

**Comment by thghxf123** [comment]
> 暴力猴的话,打开控制台「已安装的脚本」,就可以删除了

感谢，就是冲突的原因，删除旧的已经恢复了
