### ISSUE TITLE
动态过滤功能似乎对视频标题无效

### ISSUE THREAD

**Issue by lidoworld** [the1812/Bilibili-Evolved#454]
**关于哪一项功能**
动态过滤

**问题描述**

![QQ截图20200412113739](https://user-images.githubusercontent.com/24887103/79059899-0c439500-7cb2-11ea-8cb1-638b76536ca0.png)
如图 设置后依旧无法过滤

**脚本版本**

1.10.14

**浏览器版本**

80

**错误信息**

**附加截图**

**Comment by the1812** [comment]
目前只会过滤他们发的文字, 不包含任何标题
