### ISSUE TITLE
[feature request or help wanted]自动关闭弹幕

### ISSUE THREAD

**Issue by peetteerr** [the1812/Bilibili-Evolved#455]
脚本版本：1.10.14

-----
- 关于哪一项功能
现在可以手动用快捷键(d)把弹幕关闭，但我没有找到是否有直接自动关闭弹幕的设置
如果有方法自动关闭的话，请问如何做；如果没有的话，能否加入此项功能
- 期望的效果
**弹幕自动关闭**

**Comment by the1812** [comment]
打开`使用默认弹幕设置`, 关闭里面的`开启弹幕`
