### ISSUE TITLE
双击全屏在番剧页面失效

### ISSUE THREAD

**Issue by Temp314159** [the1812/Bilibili-Evolved#4554]
### 对应功能

双击全屏
Commit: 8dcba987d
内部名称: doubleClickFullscreen

### 问题描述

在番剧页面对播放器双击无法全屏（例如：https://www.bilibili.com/bangumi/play/ep787484）
其它视频页面均能正确生效

### 脚本版本

v2.8.7-67-g888d62c6c

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

Chrome 119.0.6045.160

### 播放器版本

4.7.6-rc.3969.0-b1e4d051

### 播放策略

默认

### 错误信息

```Shell
无
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Temp314159** [comment]
补充说明：
这似乎是一个通用问题？我仔细看了下，与播放器相关的很多组件都不适配现有的番剧页面，例如“扩展倍速”、“视频截图”等，在番剧页面也都是无效的。
不过不同的是，相比于上述新增的扩展功能，双击全屏是B站的原生功能，不知为何在安装Bilibili-Evolved后（未安装任何组件）双击全屏就会失效…因为已经习惯了双击全屏，一时用不了还挺别扭的…

**Comment by Geeyun-JY3** [comment]
> 相比于上述新增的扩展功能，双击全屏是B站的原生功能，不知为何在安装Bilibili-Evolved后（未安装任何组件）双击全屏就会失效…

README 不是写得很清楚吗：https://github.com/the1812/Bilibili-Evolved/blob/master/README.md#%E5%AE%89%E8%A3%85
> ……
> - 默认屏蔽双击全屏, 如有需要可以安装 双击全屏 组件来恢复.

**Comment by the1812** [comment]
合并至 #4571
