### ISSUE TITLE
希望增加自定义播放速度

### ISSUE THREAD

**Issue by y4kumo** [the1812/Bilibili-Evolved#456]
**关于哪一项功能**

**期望的效果**
希望增加自定义播放速度，例如自定义1.35, 1.85

**脚本版本**
1.10.14

**Comment by Coulomb-G** [comment]
不是有1.25和1.75么?差别很大吗

**Comment by y4kumo** [comment]
差别很大。

**Comment by the1812** [comment]
直接在浏览器控制台(<kbd>Ctrl+Shift+I</kbd>)执行这个来改吧
```js
document.querySelector('video').playbackRate = 1.35
```

**Comment by y4kumo** [comment]
学习了。原来是html的属性啊。
谢谢大佬。

**Comment by y4kumo** [comment]
问题解决，可以删除这个issue了。谢谢啦。
