### ISSUE TITLE
快捷键扩展某些功能失效

### ISSUE THREAD

**Issue by adfnkjasd** [the1812/Bilibili-Evolved#4561]
### 对应功能

快捷键扩展

### 问题描述

自定义按键或禁用按键失效，番剧页面默认w投币，设置w网页全屏后依然是w投币
![QQ图片20231204113222](https://github.com/the1812/Bilibili-Evolved/assets/39746646/ab03b4c3-a852-434c-8be0-aa0156d23e8b)
![QQ截图20231204112939](https://github.com/the1812/Bilibili-Evolved/assets/39746646/c7371f9c-b4e4-40dd-84c0-ac3ba9fa7304)

### 脚本版本

v2.8.7-preview-109-g04685315d

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

Chrome 版本 119.0.6045.200（正式版本） （64 位）

### 播放器版本

4.7.6-rc.3969.0-b1e4d051

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved 网址参数清理 History API 拦截 https://www.bilibili.com/bangumi/play/ep66645 https://www.bilibili.com/bangumi/play/ep66645
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved Array(7)
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved reply 0 0
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved at 0 0
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved like 0 2
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved sys_msg 0 0
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved user_msg 0 7
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved updated widgets Array(2)
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved Array(2)
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved Object Object Default Proxy(Object)
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved [bpx player polyfill] pbp not found
b @ userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved Array(2)
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved Object
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved Object
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved Object
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved nextPage get Array(20)
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=199ed4e6-afa3-46df-a934-1f6907fe9b83:250 Bilibili Evolved Array(2)
```

### 附加截图

![QQ截图20231204114538](https://github.com/the1812/Bilibili-Evolved/assets/39746646/dec4a5e9-1856-4db0-baa8-a0c8af3e7b4d)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
合并至 #4571
