### ISSUE TITLE
稍后再看重定向失败

### ISSUE THREAD

**Issue by MrV-art** [the1812/Bilibili-Evolved#457]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
版本号是多少?报错信息截图呢?

**Comment by MrV-art** [comment]
又好了，不知道怎么回事，可能是360浏览器的问题，不好意思打扰了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Coulomb-G"<notifications@github.com&gt;; 
发送时间: 2020年4月14日(星期二) 晚上10:35
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "Mr.V"<1643721460@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 稍后再看重定向失败 (#457)





 
版本号是多少?报错信息截图呢?
