### ISSUE TITLE
Bilibili Evolved在番剧视频下载不了任何东西，但在其他普通页面却可以正常下载

### ISSUE THREAD

**Issue by YaeSakur** [the1812/Bilibili-Evolved#4570]
### 对应功能

弹幕下载，视频下载，音频下载

### 问题描述

在任何的番剧页面都会显示不出功能来，而普通的视频却可以正常下载，

### 脚本版本

v2.8.7-20-g8dcba987d

### 脚本管理器及版本

Tampermonkey v.4.19.0

### 浏览器及版本

edge 120.0.2210.61

### 播放器版本

4.7.6-rc.3969.0

### 播放策略

默认

### 错误信息

```Shell
userscript.html?name=Bilibili-Evolved.user.js&id=b331b234-9540-4729-88b1-acbf12ac6bc4:253 Bilibili Evolved updated widgets Array(0)
userscript.html?name=Bilibili-Evolved.user.js&id=b331b234-9540-4729-88b1-acbf12ac6bc4:253  Bilibili Evolved [bpx player polyfill] pbp not found
b @ userscript.html?name=Bilibili-Evolved.user.js&id=b331b234-9540-4729-88b1-acbf12ac6bc4:253
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/79316513/13bef128-ba0c-4e86-894c-b0a86e76c9e3)
![image](https://github.com/the1812/Bilibili-Evolved/assets/79316513/2251ffa4-a822-46af-9b14-b034cc4b8744)
![image](https://github.com/the1812/Bilibili-Evolved/assets/79316513/c5ca0cc1-aada-4e77-a1b7-5a7f724ac750)
![image](https://github.com/the1812/Bilibili-Evolved/assets/79316513/8b380f51-91f5-4019-b540-83ae84ae96e5)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
感觉有必要给这一个新版番剧页整个集中反馈 issue 了：#4556、#4554、#4568、#4561。
现在好像已经回不去旧版了。

**Comment by the1812** [comment]
番剧播放器最近又改 class 了, 应该挂了不少功能

**Comment by the1812** [comment]
合并至 #4571
