### ISSUE TITLE
番剧区功能失效集中跟进

### ISSUE THREAD

**Issue by the1812** [the1812/Bilibili-Evolved#4571]
### 对应功能

b 站最近番剧播放器叕把 class 改了, 汇总一下之前反馈过的相关问题, 当然再出现别的什么功能在番剧区失效了也很正常

### 问题描述

https://github.com/the1812/Bilibili-Evolved/discussions/4556
https://github.com/the1812/Bilibili-Evolved/issues/4561
https://github.com/the1812/Bilibili-Evolved/issues/4570
https://github.com/the1812/Bilibili-Evolved/issues/4554

### 脚本版本

v2.8.7-preview

### 脚本管理器及版本

Tampermonkey v5.0.6191

### 浏览器及版本

Chrome 120.0.6099.71

### 播放器版本

4.7.6-rc3969.0-b1e4d051

### 播放策略

AV1

### 错误信息

```Shell
\
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by LonelyMarch** [comment]
一样的问题，番剧界面所有功能失效，

**Comment by LonelyMarch** [comment]
@the1812
目前一个可供替代的解决方案：
Github:  github.com/yutto-dev/bilili
Website:  bilili.nyakku.moe

**Comment by pecliu** [comment]
这里还没有解决吗

**Comment by the1812** [comment]
还没呢 年底积的事情太多了忙不过来
这个月内应该能更个新

**Comment by the1812** [comment]
遇到个怪事, 番剧那个点赞的事件是哪处理的, 里面元素都没有绑 click 事件, 而且用右键点也能触发.
快捷键扩展单纯给它发送个 click 事件并没有什么作用.

**Comment by WakelessSloth56** [comment]
> 遇到个怪事, 番剧那个点赞的事件是哪处理的, 里面元素都没有绑 click 事件, 而且用右键点也能触发. 快捷键扩展单纯给它发送个 click 事件并没有什么作用.

事件好像是在 `div#__next` 上，而且在这个 `framework-63157d71ad419e09.js` 处理了页面上所有的事件……
![1](https://github.com/the1812/Bilibili-Evolved/assets/43951496/0c29e6a1-06d2-483a-b506-34fb58fbc615)
![2](https://github.com/the1812/Bilibili-Evolved/assets/43951496/4429e95e-6cb5-47b4-b695-546bebb9e77c)

**Comment by NightSharp** [comment]
播放倍率也是失效状态

**Comment by CatAlan1028** [comment]
会员区番剧似乎只有成为会员才能下载完整版

**Comment by CatAlan1028** [comment]
不知道可不可以弄一下

**Comment by Waitung** [comment]
火狐浏览器 + Violentmonkey 番剧页面失效，只有侧边显示两个按钮，点击闪一下没有效果，其他页面没有发现问题。
测试了火狐浏览器 + Tampermonkey 是正常的，edge + Violentmonkey 也是正常的，只有火狐浏览器 + Violentmonkey 有这个问题。
系统 win11 , 以及浏览器 插件 脚本 都是最新正式版。

**Comment by the1812** [comment]
> 火狐浏览器 + Violentmonkey 番剧页面失效，只有侧边显示两个按钮，点击闪一下没有效果，其他页面没有发现问题。 测试了火狐浏览器 + Tampermonkey 是正常的，edge + Violentmonkey 也是正常的，只有火狐浏览器 + Violentmonkey 有这个问题。 系统 win11 , 以及浏览器 插件 脚本 都是最新正式版。

@Waitung 看描述这是 #4250 的问题

**Comment by Waitung** [comment]
> > 火狐浏览器 + Violentmonkey 番剧页面失效，只有侧边显示两个按钮，点击闪一下没有效果，其他页面没有发现问题。 测试了火狐浏览器 + Tampermonkey 是正常的，edge + Violentmonkey 也是正常的，只有火狐浏览器 + Violentmonkey 有这个问题。 系统 win11 , 以及浏览器 插件 脚本 都是最新正式版。
> 
> @Waitung 看描述这是 #4250 的问题

确实，改成 document-idle 可以了。当时看 issues 看到描述是自定义顶栏的问题，给略过了，没认真看这个。
