### ISSUE TITLE
工具 `评论区IP属地显示` 导致小黑屋评论无法显示

### ISSUE THREAD

**Issue by nuclear06** [the1812/Bilibili-Evolved#4572]
### 对应功能

相关信息:
> Commit: 8dcba987d
> 内部名称: ipShow
> 作者: @LightQuanta 

![image](https://github.com/the1812/Bilibili-Evolved/assets/91713418/6221c475-718c-4e42-af7f-90042b6b476e)

### 问题描述

在安装 `评论区IP属地显示` 插件后，**无论是开启还是关闭**该插件，访问[小黑屋](https://www.bilibili.com/blackroom/ban/3207785)中任意动态均无法显示评论，[例如](https://www.bilibili.com/blackroom/ban/3207785)，卸载插件后正常显示。通过抓包已排除数据请求问题，对评论的网络请求正常。

为确保问题确实为该插件的问题，已重新安装`Bilibili-Evolved`脚本，并仅安装 `评论区IP属地显示`插件，依旧无法显示。
实际问题效果图见下:
![效果图](https://github.com/the1812/Bilibili-Evolved/assets/91713418/89b1e2d9-d82f-4db8-9580-d55ff296251c)

### 脚本版本

v2.8.7-20-g8dcba987d

### 脚本管理器及版本

Tampermonkey v5.0.0

### 浏览器及版本

Google Chrome 版本 120.0.6099.109（正式版本） （64 位）

### 播放器版本

与播放器无关

### 播放策略

默认

### 错误信息

```Shell
见下
```

### 附加截图
![image](https://github.com/the1812/Bilibili-Evolved/assets/91713418/4738d179-4524-451f-9090-4725685192b9)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by LightQuanta** [comment]
收到，经测试是因为小黑屋这边用的旧版评论区脚本和主站的旧版评论区脚本代码不同导致的，正在修复

**Comment by nuclear06** [comment]
This is an auto-reply email and doesn't require a reply.
    Your email has been received, thank you.

**Comment by LightQuanta** [comment]
#4573
