### ISSUE TITLE
下载视频中选择同时下载字幕和弹幕时，仅下载了弹幕文件

### ISSUE THREAD

**Issue by ZzzzRyan** [the1812/Bilibili-Evolved#4576]
### 对应功能

下载视频
Commit: 8dcba987d
内部名称: downloadVideo

### 问题描述

通用设置-文件下载模式为“**打包下载**”。
但下载视频时，选择同时下载**字幕ASS**和**弹幕ASS**，下载的压缩包中却仅有一个ASS文件，经查看是**弹幕ASS文件**。

![示意图](https://github.com/the1812/Bilibili-Evolved/assets/107601663/84750355-a814-42dc-9b5d-17092af77b8d)

当通用设置-文件下载模式为“单独下载”时，字幕和弹幕都可以正常下载。

### 脚本版本

v2.8.7-20-g8dcba987d

### 脚本管理器及版本

Tampermonkey v5.0.0

### 浏览器及版本

Microsoft Edge 版本 120.0.2210.77 (正式版本) (64 位)

### 播放器版本

4.7.9-68212f72

### 播放策略

默认

### 错误信息

```Shell
见截图
```

### 附加截图

<details> <summary>  Console截图 </summary>
<img src=https://github.com/the1812/Bilibili-Evolved/assets/107601663/eb60943f-1665-44d5-a856-0657e102b489 width=80% />
</details>

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
这个是由于文件名冲突引起的, 没想到啥比较好的处理方式, 只能把后来的那个自动重命名了.
但是改过名后播放器估计自动识别不了, 得手动载入一下
