### ISSUE TITLE
打开自定义顶栏，顶栏消失

### ISSUE THREAD

**Issue by MosaicAccount** [the1812/Bilibili-Evolved#4580]
### 对应功能

自定义顶栏
<img width="354" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/66773914/875980fb-e1ba-464c-ab2d-a23f2e5d36d3">

### 问题描述

在safari浏览器中，打开自定义顶栏后顶栏消失，关闭自定义顶栏后顶栏出现。
<img width="1426" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/66773914/ead1b0bf-c238-460a-ba1c-9ec224478247">
<img width="1414" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/66773914/38bc41b0-bca2-4df6-bc3e-12655c149c8f">

### 脚本版本

v2.8.7-20-g8dcba987d

### 脚本管理器及版本

stay 2.5.6(120)

### 浏览器及版本

safari 16.5 (17615.2.9.11.6, 17615)

### 播放器版本

479-68212f72

### 播放策略

默认

### 错误信息

```Shell
错误信息在附加截图中
```

### 附加截图

<img width="1449" alt="image" src="https://github.com/the1812/Bilibili-Evolved/assets/66773914/834c2702-cc0e-4773-8c60-6b164898278a">

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
你使用的脚本管理器可能有问题，报错显示存储的数据没有正确读取出来

**Comment by freedomspiritJohn** [comment]
> 你使用的脚本管理器可能有问题，报错显示存储的数据没有正确读取出来

用的暴力猴，一样问题
![image](https://github.com/the1812/Bilibili-Evolved/assets/129288685/5a960228-5c38-4f81-b13b-4f0b7cc929fb)
![image](https://github.com/the1812/Bilibili-Evolved/assets/129288685/b7e320e2-294e-43bd-a455-5fa0001f6d95)

**Comment by YamatoRyou** [comment]
> 你使用的脚本管理器可能有问题，报错显示存储的数据没有正确读取出来

有同样的问题, 甚至连左侧常驻的按钮也消失导致无法打开脚本的任何设置. 已经试过重装脚本甚至扩展, 都没有用.
Tampermonkey 5.0.1
Catsxp 4.1.3 (x64, Chromium 121.0.6167.47)
![{C3986061-C60D-C42A-C349-B2B663E4B963}](https://github.com/the1812/Bilibili-Evolved/assets/48104960/65d3237a-3cb1-427e-b93a-dfaf28bbef54)

**Comment by the1812** [comment]
Tampermonkey 的别搁这同样了, 这里是题主用 Stay 的不兼容问题
