### ISSUE TITLE
希望增加直播结束后不自动轮播的功能

### ISSUE THREAD

**Issue by NatralMicsear** [the1812/Bilibili-Evolved#459]
比如不直播时停用播放器之类的，有方法可以实现吗

**Comment by Coulomb-G** [comment]
轮播不是主播设置的吗

**Comment by NatralMicsear** [comment]
> 轮播不是主播设置的吗

是这样的，但绝大多数主播都开了轮播，实际上挂到后台听直播结束时突然切到轮播会被吓一跳

**Comment by the1812** [comment]
中间不是有30秒时间吗(画面有个`xx秒后, 主播的轮播视频将开始播放`之类的), 然后才会变成轮播

**Comment by NatralMicsear** [comment]
> 中间不是有30秒时间吗(画面有个`xx秒后, 主播的轮播视频将开始播放`之类的), 然后才会变成轮播

是的，只是因为有时候放在后台听或者听着听着睡着了注意不到直播结束了结果自动开始轮播后被吵醒这样。
也许只是我个人遇到的问题，需求不大的话就忽略这条吧

**Comment by dskaowu** [comment]
> > 中间不是有30秒时间吗(画面有个`xx秒后, 主播的轮播视频将开始播放`之类的), 然后才会变成轮播
> 
> 是的，只是因为有时候放在后台听或者听着听着睡着了注意不到直播结束了结果自动开始轮播后被吵醒这样。
> 也许只是我个人遇到的问题，需求不大的话就忽略这条吧

感觉可以有，做成个挂机模式的开关之类的，挺酷的
