### ISSUE TITLE
观看番剧、电影时进度调整、音量调节、暂停等按键无法使用

### ISSUE THREAD

**Issue by Limgmk** [the1812/Bilibili-Evolved#460]
**问题描述**
观看番剧、电影时，进度调整、音量调节、暂停等按键无法使用，禁用脚本之后就正常了。观看普通视频没有这个问题

**脚本版本**
1.10.14

**浏览器版本**
80.0.3987.163（正式版本） （64 位）

**Comment by Coulomb-G** [comment]
我这边试了下按键是正常的,截图看看报错信息

**Comment by Limgmk** [comment]
> 我这边试了下按键是正常的,是否还开着其他b站相关的插件//脚本,截图看看报错信息

好奇怪，突然好了，之前好几天都是这个问题，就刚刚就突然好了。没有其他脚本。可能是我自己电脑的问题吧，打扰了。
