### ISSUE TITLE
`自定义顶栏`导致的番剧、国创、虚拟UP主区、公开课页面错位以及与`隐藏顶部横幅`兼容问题，首页`删除广告`空白占位，安装`视频内显示时间`报错，偶发性视频跳转卡住

### ISSUE THREAD

**Issue by MonicaWQY** [the1812/Bilibili-Evolved#4610]
### 对应功能

1.`自定义顶栏`
2.`隐藏顶部横幅`
3.`删除广告`
4.`视频内显示时间`

### 问题描述

1.开启`自定义顶栏`后，番剧、国创、虚拟UP主区、公开课页面有部分信息被遮挡、错位重叠

番剧：https://www.bilibili.com/v/anime/finish/#/
原版：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/5475dd89-60fb-443e-8763-9216aee66729)
开启`自定义顶栏`：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/fe9373b1-f323-4299-beea-3aa15180336d)
开启`自定义顶栏`和`隐藏顶部横幅`：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/32c25b16-7d11-4b90-be57-f2dd5862edcd)

国创：https://www.bilibili.com/v/guochuang/chinese/#/
原版：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/1f403031-5624-4cbe-826b-67388dec4cdd)
开启`自定义顶栏`：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/c6a4f865-1fd8-4b78-ba25-27d0d9393b46)
开启`自定义顶栏`和`隐藏顶部横幅`：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/ea46501c-c657-4512-84eb-7c5c99145384)

虚拟UP主区：https://www.bilibili.com/v/virtual/
原版：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/7b291eb5-92f9-4f26-b693-b766feaa95cb)
开启`自定义顶栏`：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/d5e9a032-6084-4210-907a-740f49a442e8)
开启`自定义顶栏`和`隐藏顶部横幅`：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/0d2f0212-5f0e-4198-b6cd-73d84362ef80)

公开课：https://www.bilibili.com/mooc/
原版：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/eb0f2ebe-6f9b-41ef-b999-95661d3decda)
开启`自定义顶栏`：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/3c2e363f-e35a-448b-8a22-85c8284354d7)
开启`自定义顶栏`和`隐藏顶部横幅`：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/81693ed4-cfca-4579-9ca5-0e5737f131d9)

**番剧、国创和虚拟UP主区页面**在同时开了`自定义顶栏`和`隐藏顶部横幅`后可以解决错位重叠遮挡的问题，但是会出现第一排分区菜单的**鼠标悬停菜单被遮挡**的情况，这个遮挡问题在**主页和所有有分区菜单的页面**都会发生；**公开课页面**是只要开了`自定义顶栏`就被出现重叠遮挡的问题，且`自定义顶栏-透明填充`不生效，往下滑还会有**原生顶栏**出现，开`隐藏顶部横幅`后无法解决重叠遮挡问题，且`隐藏顶部横幅`功能在页面**刷新后会失效**。

设想：有没有方法能让第一排分区菜单的鼠标悬停菜单像第二排一样显示在分区按钮下方？

2.开启`删除广告`后，首页依然有空白占位区域，没有开`删除广告-占位文本`

只开Bilibili-Evolved：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/661fff7b-992e-49f7-aae2-06deedfdd2b3)
开了Bilibili-Evolved和AdGuard：
![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/6bb5bce2-74f4-46bc-b49c-88c3f8c09c41)

不管开不开其他扩展和脚本，都会有空白占位区域。

3.安装`视频内显示时间`组件会报错，无法安装

![image](https://github.com/the1812/Bilibili-Evolved/assets/93992899/d64f2660-5722-451f-8b54-06df2312d2da)

### 脚本版本

v2.8.8-27-g3981ed7b6

### 脚本管理器及版本

Tampermonkey v5.0.0

### 浏览器及版本

Microsoft Edge 120.0.2210.144 (正式版本) (64 位)

### 播放器版本

4.7.16-fa4a55f8

### 播放策略

默认

### 错误信息

```Shell
userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252  Bilibili Evolved [FeedsCardsManager] No adaptor found (5) [{…}, {…}, {…}, {…}, {…}]
b @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252
startWatching @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:219
Je @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:219
setup @ VM877:1
await in setup(异步)
e.setup @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:223
m @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252
await in m(异步)
f @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252
await in f(异步)
a @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:212
(anonymous) @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:212
(anonymous) @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:223
userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252  Bilibili Evolved feedsCardsManager.startWatching() failed
b @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252
Je @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:219
await in Je(异步)
setup @ VM877:1
await in setup(异步)
e.setup @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:223
m @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252
await in m(异步)
f @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252
await in f(异步)
a @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:212
(anonymous) @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:212
(anonymous) @ userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:223
userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252 Bilibili Evolved plugins block time: 5.2ms for 45 items
userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252 Bilibili Evolved plugins resolve time: 59.2ms for 45 items
userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252 Bilibili Evolved components block time: 4.3ms for 19 items
userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252 Bilibili Evolved components resolve time: 792.7ms for 19 items
userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252 Bilibili Evolved init block time: 0.8ms for 6 items
userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:252 Bilibili Evolved init resolve time: 774.7ms for 6 items
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by SteveXu9102** [comment]
似乎与 #4614 相关？

**Comment by the1812** [comment]
1. 这个菜单弹出的位置只能由 b 站控制, 我只能解决一下错位的问题
![image](https://github.com/the1812/Bilibili-Evolved/assets/26504152/805df8b4-d2fe-47f9-9bc8-40d0d8940a74)

2. 公开课页面的布局实现比较特殊 (和其他分区都不一样), `自定义顶栏` 将对这个页面关闭, 优先保证可用性

3. `视频内显示时间` 现在应该好了

**Comment by the1812** [comment]
空白占位可以解决
视频跳转卡住是来自网址参数清理, 但还不知道咋解决
