### ISSUE TITLE
一直提示：undefined: code = -404, message = 啥都木有

### ISSUE THREAD

**Issue by billowssun** [the1812/Bilibili-Evolved#4616]
### 对应功能

左下角

### 问题描述

一直提示：undefined: code = -404, message = 啥都木有

### 脚本版本

最新版

### 脚本管理器及版本

最新版本

### 浏览器及版本

最新版

### 播放器版本

最新版

### 播放策略

默认

### 错误信息

```Shell
1
```

### 附加截图

1

### 致遇到了相同问题准备回复的人

11

**Comment by 15Shell** [comment]
一样的情况
![image](https://github.com/the1812/Bilibili-Evolved/assets/111548938/726e6ac3-df52-455e-9d47-64db0bd3dc1d)

**Comment by the1812** [comment]
#4614
