### ISSUE TITLE
脚本冲突？

### ISSUE THREAD

**Issue by wulifuji** [the1812/Bilibili-Evolved#462]
**浏览器版本**
Chrome/80.0.3987.163 

**错误信息**
与[解除B站区域限制](https://github.com/ipcjs/bilibili-helper/blob/user.js/bilibili_bangumi_area_limit_hack.md)冲突
具体冲突为：
![image](https://user-images.githubusercontent.com/61496038/79438166-c5cd9d80-8005-11ea-9250-8230f95dc6fc.png)
                                                                                 ===图中小地球无法显示

**附加文件**
[我的配置文件](https://raw.githubusercontent.com/wulifuji/bilibili/master/bilibili-evolved-settings.json)

**Comment by Coulomb-G** [comment]
确实冲突,可以去番剧详情页找到该小地球

**Comment by wulifuji** [comment]
更新的是预览版嘛？我试了没效果呀QAQ

**Comment by Coulomb-G** [comment]
我说的是你在用的「解除b站区域限制」,我的版本是7.9.3

**Comment by wulifuji** [comment]
还是没效果 **7.9.3** 「解除b站区域限制」，这个插件我刚更新了，还是没有的

**Comment by wulifuji** [comment]
[要不私聊？](https://t.me/spring_commander)

**Comment by Coulomb-G** [comment]
页面下拉之后,也没有小地球?控制台报错信息可以截图看看吗?可能得找那个脚本的原作者报错

**Comment by wulifuji** [comment]
重启治一切，我重启了下，好👌了，你说淦不淦？

**Comment by wulifuji** [comment]
[私聊](https://t.me/spring_commander)

**Comment by wulifuji** [comment]
时好时不好，没有报错，我太难了，您直接跟作者对接吧

**Comment by Coulomb-G** [comment]
我这边没出错啊,甚至报错信息都看不见,小地球得在播放页下拉才会显示,这真的只能你去找原作者

**Comment by wulifuji** [comment]
`Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first
