### ISSUE TITLE
抽奖宝箱点击后加载不完全

### ISSUE THREAD

**Issue by EuropeanWithSSR** [the1812/Bilibili-Evolved#463]
**关于哪一项功能**
网址参数清理

**问题描述**
https://live.bilibili.com/28576 直播间实物抽奖，点击左下角抽奖宝箱，弹出的抽奖页面加载不全，关闭“网址参数清理”功能后正常。

**脚本版本**
正式版 1.10.14

**浏览器版本**
Cent Browser
版本 4.1.7.182（正式版本） （32 位） (Chromium 78.0.3904.108)

**错误信息**
点击抽奖宝箱后，console新增信息如下：
`[URL params clean] https://live.bilibili.com/p/html/live-room-treasurebox/index.html?aid=529#/ https://live.bilibili.com/p/html/live-room-treasurebox/index.html#?aid=529
userscript.html?id=4c445978-c243-46a5-b743-388baa3818ae:15920 scheduled bundle update
script_injector.js:12 pakku ajax: injecting hook
xhr_hook.js:17 pakku: [to developers] Web Worker is disabled for compatibility reasons
(anonymous) @ xhr_hook.js:17
(anonymous) @ xhr_hook.js:71
xhr_hook.js:70 pakku ajax: hook set
userscript.html?id=4c445978-c243-46a5-b743-388baa3818ae:15922 downloading bundle
userscript.html?id=4c445978-c243-46a5-b743-388baa3818ae:16035 zip version = 1.10.15
userscript.html?id=4c445978-c243-46a5-b743-388baa3818ae:16042 bundle version not match. current = 1.10.14, latest = 1.10.15`

**附加截图**
![image](https://user-images.githubusercontent.com/39738950/79445413-3927dd00-800f-11ea-80e8-a4f7775561af.png)

**Comment by aliofwind** [comment]
和网址参数清理功能冲突了，抽奖框是iframe里打开了https://live.bilibili.com/p/html/live-room-treasurebox/index.html?aid=529#/ 这个地址，会被清理功能把后面的aid清理掉

**Comment by the1812** [comment]
同#420 / #445, 预计会在v1.10.16版中修复
网址参数清理修改了末尾的斜杠, 导致相对路径的链接失效了
