### ISSUE TITLE
评论区IP属地显示在一般样式的视频中失效

### ISSUE THREAD

**Issue by miaonai** [the1812/Bilibili-Evolved#4643]
### 对应功能

评论区IP属地显示
工具
by [@Light_Quanta](https://github.com/LightQuanta)

在评论区显示评论的IP属地信息

Commit: c839f80bc
内部名称: ipShow

![image](https://github.com/the1812/Bilibili-Evolved/assets/67116517/40e26c4a-0e8b-4885-bc77-794832617947)

### 问题描述

评论区IP属地显示在一般样式的视频中失效
测试了多个视频如 BV1mJ4m147PG  BV1Ug411j766等
![image](https://github.com/the1812/Bilibili-Evolved/assets/67116517/ec3c28f0-56f5-4577-8403-4c5153fc9057)

但在春节样式中的视频是正常的如 BV1iU421d7aG 
![image](https://github.com/the1812/Bilibili-Evolved/assets/67116517/55f34c9d-ae53-4529-9719-8638fd3e0008)

### 脚本版本

Bilibili Evolved v2.8.8-27-g3981ed7b6

### 脚本管理器及版本

tampermonkey v5.0.1

### 浏览器及版本

Microsoft Edge 版本 121.0.2277.128 (正式版本) (64 位)

### 播放器版本

4.7.15-06907113

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved 
[FeedsCardsManager] No adaptor found (5) [{…}, {…}, {…}, {…}, {…}]
0: {name: 'live', match: Array(1), watchCardsList: ƒ}
1: {name: 'space', match: Array(1), watchCardsList: ƒ}
2: {name: 'topic', match: Array(1), watchCardsList: ƒ}
3: {name: 'opus-detail', match: Array(1), watchCardsList: ƒ}
4: {name: 'default', match: Array(1), watchCardsList: ƒ}length: 
5[[Prototype]]: Array(0)
b @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:252
startWatching @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:219
Je @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:219
setup @ VM1387:1
await in setup(异步)
m @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:252
await in m(异步)
f @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:252
await in f(异步)
a @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:212
(匿名) @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:212
(匿名) @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:223

userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:252  
Bilibili Evolved feedsCardsManager.startWatching() failed
b @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:252
Je @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:219
await in Je(异步)
setup @ VM1387:1
await in setup(异步)
m @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:252
await in m(异步)
f @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:252
await in f(异步)
a @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:212
(匿名) @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:212
(匿名) @ userscript.html?name=Bilibili-Evolved.user.js&id=9c1721cb-0242-40a0-aa19-1a077bb8ad43:223
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/67116517/177d0d02-930d-4d3f-8023-f3bf66f99e47)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by ChaXxl** [comment]
烦，确实用不了了，连那个油猴脚本也用不了

**Comment by adfnkjasd** [comment]
同样问题，已reaction

**Comment by kingdomsqedf** [comment]
同样问题

**Comment by EarOfWheat** [comment]
> 烦，确实用不了了，连那个油猴脚本也用不了

哎，现在另外那个暂时修复了，但样式和这个脚本变得有冲突了

**Comment by xiaohuangsu** [comment]
gf那边有脚本解决了，啊b更改了评论区代码导致原来的脚本失效，我现在还看不了评论区的图片了呢，还有简化头像框也没简化掉

**Comment by kiriYui0** [comment]
看了下接口里还是会返回属地信息的，估计是数据结构变了吧

**Comment by lxr760** [comment]
2.8.9修复这个bug了吗？好像还是不能显示IP属地

**Comment by the1812** [comment]
没说修过哦

**Comment by himetuki** [comment]
我是B站新版界面无法显示，旧版界面可以

**Comment by LightQuanta** [comment]
经测试是b站的评论区相关代码更改导致的，无法获取评论元素之前使用的`__vueParentComponent`属性（参考 #4690 ），导致[comment-apis.ts](https://github.com/the1812/Bilibili-Evolved/blob/8a4e422612a7bd0b42da9aa50c21c7bf3ea401b8/src/components/utils/comment-apis.ts)里的代码失效（IP属地显示依赖此文件），并不是由于B站API接口数据结构变化导致的

使用新的获取方法可以重新获取评论相关数据，等更新吧

**Comment by 1106458351** [comment]
> gf那边有脚本解决了，啊b更改了评论区代码导致原来的脚本失效，我现在还看不了评论区的图片了呢，还有简化头像框也没简化掉

能发个链接吗

**Comment by MisakaMikoto9982** [comment]
> > gf那边有脚本解决了，啊b更改了评论区代码导致原来的脚本失效，我现在还看不了评论区的图片了呢，还有简化头像框也没简化掉
> 
> 能发个链接吗

在greasyfork简单搜索一下就有了
https://greasyfork.org/zh-CN/scripts/448434

**Comment by the1812** [comment]
现在修了

**Comment by KusanagiKW** [comment]
还是不行啊，版本2.8.11

**Comment by KusanagiKW** [comment]
> 现在修了
还是不行啊，版本2.8.11

**Comment by KusanagiKW** [comment]
> > > 现在修了
> > > 还是不行啊，版本2.8.11
> 
> 我这边可以了，版本2.8.11

我换了个新的浏览器，便携版chrome最新版，新安装temparmonkey，新安装脚本，只安装ip显示的情况下都不起作用

**Comment by KusanagiKW** [comment]
> 能用是能用了，但所有楼中楼评论的IP和楼主都是一样的

还真是，我说看起来怎么怪怪的

**Comment by the1812** [comment]
> 能用是能用了，但所有楼中楼评论的IP和楼主都是一样的

修了, 再更新下

**Comment by absentmemory** [comment]
好像又失效了，动态页里可以看到IP地址，但是视频页就看不到

**Comment by Tinhone** [comment]
> 好像又失效了，动态页里可以看到IP地址，但是视频页就看不到

参见 #4812 #4804
