### ISSUE TITLE
采用WASM下载视频时有时候要重新下载一次ffmpeg wasm

### ISSUE THREAD

**Issue by long45343** [the1812/Bilibili-Evolved#4648]
### 对应功能

Commit: c5852f8b9
内部名称: downloadVideo
![image](https://github.com/the1812/Bilibili-Evolved/assets/51872789/beb455a9-ab7b-4de7-87f2-28e91f9c4a18)

### 问题描述

只要切换一下页面彻底关闭或者b站的标签页再次打开进行WASM下载时就要重新下载一次WASM
重现方法:安装下载视频以及WASM输出组件后先随意下载一个视频，此时提示需要下载WASM，下载完成后也可以正常使用。
但是稍等一段时间后再重复如上操作，即使没有清理缓存也要重新下载WASM
如果有什么log需要提供，我会尽力配合，谢谢！

### 脚本版本

v2.8.8-74-g9f446110e

### 脚本管理器及版本

Tampermonkey v5.0.6192

### 浏览器及版本

Microsoft Edge 版本 121.0.2277.128 (正式版本) (64 位）

### 播放器版本

4.8.0-6303bf16

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved updated widgets [__ob__: Ee]
userscript.html?name=Bilibili-Evolved.user.js&id=4264cda6-2c1a-4b02-86a2-192e07a4cef9:253 Bilibili Evolved [updateTestVideoInfo] {aid: '1600969659', cid: '1448442457', title: '三年升三级？最后两轮出现爆炸剧情！比赛跌宕起伏精彩刺激！FC24都柏林大学经理模式第九集【粤语中字】…年升三级？最后两轮出现爆炸剧情！比赛跌宕起伏精彩刺激！FC24都柏林大学经理模式第九集【粤语中字】'}
userscript.html?name=Bilibili-Evolved.user.js&id=4264cda6-2c1a-4b02-86a2-192e07a4cef9:253 Bilibili Evolved [updateTestVideoInfo] {aid: '1600969659', cid: '1448442457', title: '三年升三级？最后两轮出现爆炸剧情！比赛跌宕起伏精彩刺激！FC24都柏林大学经理模式第九集【粤语中字】…年升三级？最后两轮出现爆炸剧情！比赛跌宕起伏精彩刺激！FC24都柏林大学经理模式第九集【粤语中字】'}
userscript.html?name=Bilibili-Evolved.user.js&id=4264cda6-2c1a-4b02-86a2-192e07a4cef9:253 Bilibili Evolved [downloadExtraAssets] []
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
@WakelessSloth56

**Comment by WakelessSloth56** [comment]
这个应该是浏览器缓存机制的问题吧，我在代码里仅仅只是 fetch 下来了，缓存全在于浏览器。
除非是手动在某个地方缓存一下，大概没什么好办法？

---

我最近没什么时间，3月应该能有点时间，我做一下基于 WebCodecs 的插件（#4615）。
