### ISSUE TITLE
预览版手动更新后报错

### ISSUE THREAD

**Issue by LTHPKBTE** [the1812/Bilibili-Evolved#465]
原来是1.10.15预览版本，通过github的预览版连接更新了1.10.16，打开一个页面就报错一次
Attempt to get style which is not downloaded.
网络通畅，等了很久也有这个报错，不知道是什么问题

我的代替广告的功能好像错位了，不知道是不是样式未下载导致的问题
![图片](https://user-images.githubusercontent.com/53574505/79703871-0a488a00-82e1-11ea-80d1-8fb5afd460d5.png)

**Comment by the1812** [comment]
是我尝试统一滚动条样式弄出的问题, 已在`1.10.17`版中修复
广告那个是首页的尺寸变了, 我之前还没适配, 现在也改好了

**Comment by LTHPKBTE** [comment]
更新后已修复，谢谢回答
