### ISSUE TITLE
开启网址参数清理后搜索页奇怪表现

### ISSUE THREAD

**Issue by YuuUehara** [the1812/Bilibili-Evolved#4656]
### 对应功能

网址参数清理
Commit: c5852f8b9

### 问题描述

随意在bilibili进行搜索，搜索后保持搜索页面未关闭，刷新可见地址栏先跳转至/undefined然后再跳转回正确搜索界面；关闭浏览器，重新打开刚刚保持的搜索页面，跳转至/undefined并且不会跳转回正确搜索界面。
关闭网址参数清理功能后不再出现此问题。

### 脚本版本

2.8.8

### 脚本管理器及版本

Tampermonkey 5.0.1

### 浏览器及版本

Edge 122.0.2365.52 Firefox 123.0 上均观察到此问题

### 播放器版本

不适用

### 播放策略

AV1

### 错误信息

```Shell
见截图。
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/45460331/82edb6bb-fb9c-4da1-92c3-0c1e3ceeb677)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Tinhone** [comment]
### 对应功能

网址参数清理
Commit: c839f80bc

### 补充

我使用了 Firefox 附加组件：找回已关闭的标签页，在关闭搜索页后使用此附加组件功能复原时，会发现网址变为 `https://search.bilibili.com/undefined`。

而其他哔哩哔哩页面不会有这个问题，关闭网址参数清理组件后也不会出现这个问题，非常奇怪。

### 脚本版本

v2.8.8-preview-116-g3e4fdda59

### 脚本管理器及版本

Tampermonkey v4.18.1

### 浏览器及版本

Firefox v88.0

**Comment by Geeyun-JY3** [comment]
实话实说我已经被这个问题困扰了至少半年了，原来是`网址参数清理`这个组件的锅，我还一直以为是破站的 bug……先感谢 issue 主。

@Tinhone 其实就是只要离开破站的搜索页面再返回/恢复该搜索页就能复现，我遇到过的就有：

- 关闭标签页后通过某种方式恢复标签页（包括但不限于浏览器窗口菜单的`重新打开关闭的标签页`〔其实就是按 <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd>〕、工具栏汉堡菜单里的历史记录里找回）（我个人就是在用百分浏览器时开了`显示恢复关闭标签按钮`，恢复标签页的操作非常高频，此 bug 令我苦不堪言）
- 通过 [searchEngineJump 搜索引擎快捷跳转](https://github.com/qxinGitHub/searchEngineJump) 此类脚本跳转到其他搜索页面再返回该搜索页
