### ISSUE TITLE
自定义顶栏插件开启后在稍后再看界面顶部出现异常

### ISSUE THREAD

**Issue by passerbyjia0** [the1812/Bilibili-Evolved#4668]
### 对应功能

自定义顶栏插件开启后在稍后再看界面顶部出现异常

### 问题描述

自定义顶栏插件开启后在稍后再看界面顶部出现异常

### 脚本版本

v2.8.8-27-g3981ed7b6

### 脚本管理器及版本

Tampermonkey v5.0.0

### 浏览器及版本

Chrome  版本 122.0.6261.112（正式版本） （64 位）

### 播放器版本

4.7.16-fa4a55f8

### 播放策略

默认

### 错误信息

```Shell
在截图中
```

### 附加截图

![捕获](https://github.com/the1812/Bilibili-Evolved/assets/104680428/b4ba6264-9b9c-4796-bc9e-9a07f8ab78d1)

![捕获](https://github.com/the1812/Bilibili-Evolved/assets/104680428/7d409ec8-46af-4d4a-8e69-6afd26ddbcc2)
![捕获](https://github.com/the1812/Bilibili-Evolved/assets/104680428/2cd6c30d-66f0-40e4-8c77-f68ee65e36d3)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by TAIY2020** [comment]
加一，我也遇到相同问题，在改变页面长度后可以恢复

**Comment by lh-java** [comment]
遇到了相同的问题,但目前没有好的解决办法。开启隐藏顶部横幅和自定义顶栏的同时,需要保留那一行没用的分类菜单才不会出问题

**Comment by lh-java** [comment]
自己瞎搞的脚本 把长度改短了好多了

// @match        https://www.bilibili.com/watchlater/*
(function() {
    // 等待网页完成加载
    window.addEventListener('load', function() {
        // 加载完成后执行的代码
        var div = $(".z-top-container").css("min-height","70px");
    }, false);
})();

**Comment by refrigerator777** [comment]
> 自己瞎搞的脚本 把长度改短了好多了
> 
> // @match https://www.bilibili.com/watchlater/* (function() { // 等待网页完成加载 window.addEventListener('load', function() { // 加载完成后执行的代码 var div = $(".z-top-container").css("min-height","70px"); }, false); })();

这个是怎么自己修改呀，在哪改 问问

**Comment by lh-java** [comment]
> > 自己瞎搞的脚本 把长度改短了好多了
> > // @match https://www.bilibili.com/watchlater/* (function() { // 等待网页完成加载 window.addEventListener('load', function() { // 加载完成后执行的代码 var div = $(".z-top-container").css("min-height","70px"); }, false); })();
> 
> 这个是怎么自己修改呀，在哪改 问问

1. 首先,用完Bilibili Evolved优化是这样的,
![PixPin_2024-04-04_11-22-44](https://github.com/the1812/Bilibili-Evolved/assets/72517658/39b9d15b-850f-4cd0-bbbc-f79ae17ddc91)

2. 然后先点击油猴,新建脚本,全部代码我给你复制出来了,在下面

// ==UserScript==
// @name         [Bilibili] 稍后再看去除空白区域
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  try to take over the world!
// @author       You
// @match        https://www.bilibili.com/watchlater/*
// @icon         https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@preview/images/logo-small.png
// @grant        none
// ==/UserScript==
(function() {
    // 等待网页完成加载
    window.addEventListener('load', function() {
        // 加载完成后执行的代码
        var div = $(".z-top-container").css("min-height","70px");
    }, false);
})();

3.效果这样
![PixPin_2024-04-04_11-24-24](https://github.com/the1812/Bilibili-Evolved/assets/72517658/fd60f0d6-e90b-450d-80bc-6cd30f6c77f9)
![PixPin_2024-04-04_11-24-40](https://github.com/the1812/Bilibili-Evolved/assets/72517658/e1c630bc-e51f-45db-a85e-3df3fb3210ff)
4.用AdGuard拦截上面那个分类栏和下面的没用的信息
![微信图片_20240404112803](https://github.com/the1812/Bilibili-Evolved/assets/72517658/e4dfb003-f963-41a2-a07b-36da3f0bc866)
![PixPin_2024-04-04_11-28-57](https://github.com/the1812/Bilibili-Evolved/assets/72517658/3b31123a-e1c6-405a-b072-a06c9576f896)
5.最终效果
![PixPin_2024-04-04_11-29-47](https://github.com/the1812/Bilibili-Evolved/assets/72517658/71be6c15-1dd7-47cd-b9b7-1158eec03d3d)

还是等集成这个功能好 这个只是暂时解决了
