### ISSUE TITLE
希望顶栏动态能刷新更多动态

### ISSUE THREAD

**Issue by wwzw27** [the1812/Bilibili-Evolved#467]
现在的顶栏动态中只能刷新一页的动态内容。原版网页可以在刷新第一页内容后继续往后刷新出第二页第三页，而自定义顶栏只能加载一页，就需要点击全部动态去看了。
脚本版本正式版1.10.14
![1](https://user-images.githubusercontent.com/64151098/79998215-fffadb80-84ec-11ea-8921-82c07e8e043d.png)
![2](https://user-images.githubusercontent.com/64151098/79998236-04bf8f80-84ed-11ea-9e10-a20d9d54b750.png)
![3](https://user-images.githubusercontent.com/64151098/79998241-05f0bc80-84ed-11ea-8ddd-9ba9679b15f0.png)

**Comment by wwzw27** [comment]
还有一个原版显示视频更新的时间的内容能否加到自定义顶栏中

**Comment by yongdianxiin** [comment]
附议

**Comment by 840119580** [comment]
附议，版本离线预览693.34，同希望能够多加入动态，因为关注的人比较多，视频动态刷新不全，每次都要到动态页面去查看，很麻烦，原版网页可以直接向下滚动就可以载入后面的动态，希望能够刷新更多动态qwq
