### ISSUE TITLE
使用谷歌浏览器打开Bilibili Evolved完全失效。

### ISSUE THREAD

**Issue by Yukihana-Lamy** [the1812/Bilibili-Evolved#4676]
### 对应功能

【功能】&【设置】

### 问题描述

1.使用Google浏览器打开Bilibili网页版首页和任意视频网页，在篡改猴开启Bilibili Evolved的情况下，Bilibili Evolved的【功能】&【设置】按钮完全不显示。导致无法使用Bilibili Evolved。

2.打开Tampermonkey的Bilibili Evolved菜单栏，同样也没看到【功能】&【选项】。

希望Bilibili Evolved的作者尽快修复这个问题。

### 脚本版本

V2.8.9

### 脚本管理器及版本

Tampermonkey V5.0.1

### 浏览器及版本

Google浏览器 V122.0.6261.112（正式版本） （64 位）

### 播放器版本

无

### 播放策略

默认

### 错误信息

```Shell
见附加截图
```

### 附加截图

![Bilibili Evolved的bug1](https://github.com/the1812/Bilibili-Evolved/assets/103800975/c4f67152-24ae-497c-a3cf-dc32a952b5f2)
![Bilibili Evolved的bug2](https://github.com/the1812/Bilibili-Evolved/assets/103800975/57c719af-7e8c-4e15-9bec-f834139de9ab)
![Bilibili Evolved的bug3](https://github.com/the1812/Bilibili-Evolved/assets/103800975/c567e714-f683-4a0c-9c26-dd2841d5b575)
![Bilibili Evolved的bug4](https://github.com/the1812/Bilibili-Evolved/assets/103800975/4a21f4ac-2e7c-4f78-9192-4f51c4a83e19)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
这里菜单有不
![Snipaste_2024-03-11_21-36-45](https://github.com/the1812/Bilibili-Evolved/assets/26504152/1e9cd13b-4324-4235-85e5-de1fc07bd294)

**Comment by Yukihana-Lamy** [comment]
> 这里菜单有不 ![Snipaste_2024-03-11_21-36-45](https://private-user-images.githubusercontent.com/26504152/311722775-1e9cd13b-4324-4235-85e5-de1fc07bd294.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTIzNDcsIm5iZiI6MTcxMDIxMjA0NywicGF0aCI6Ii8yNjUwNDE1Mi8zMTE3MjI3NzUtMWU5Y2QxM2ItNDMyNC00MjM1LTg1ZTUtZGUxZmMwN2JkMjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDAyNTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NWMwYThiMmJkOTQzN2M3MjQ1NTI5MzdjODI2YTY0MTc4MjBiMGY2ODA4ODIwNDg2MGI5NGY4YjhhZTgzNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hio-G_U0FwfwMzd-AFagJbl0AP8AXKZ_v_sQfBLiyeU)

当然有啦

![Bilibili Evolved的bug5](https://github.com/the1812/Bilibili-Evolved/assets/103800975/e25c37cc-ec62-44c0-9916-185014b48996)

**Comment by Yukihana-Lamy** [comment]
> 这里菜单有不 ![Snipaste_2024-03-11_21-36-45](https://private-user-images.githubusercontent.com/26504152/311722775-1e9cd13b-4324-4235-85e5-de1fc07bd294.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTI4MzYsIm5iZiI6MTcxMDIxMjUzNiwicGF0aCI6Ii8yNjUwNDE1Mi8zMTE3MjI3NzUtMWU5Y2QxM2ItNDMyNC00MjM1LTg1ZTUtZGUxZmMwN2JkMjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDAzMDIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MzY4YjFhNDIwNThjYWQ1MDNhMWYyMTgwMGFmZDU2YTRhZDJmNjUwYzRjOWVhMzNiZTg4N2M1MjFhOWViNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u5bCfiOsCU8_mw2OyQ65k30eWbVIVBp0fqcNq94lWf4)

菜单里好像没看见【功能】&【设置】

![Bilibili Evolved的bug5](https://github.com/the1812/Bilibili-Evolved/assets/103800975/580cda8f-2870-4bd8-922c-4e470d159d9b)

![Bilibili Evolved的bug6](https://github.com/the1812/Bilibili-Evolved/assets/103800975/0e5390b5-d7d2-4fa1-aa5e-57609d3cee50)

**Comment by the1812** [comment]
梯子开全局重新进b站

**Comment by Yukihana-Lamy** [comment]
> 梯子开全局重新进b站

我使用了Clash，开全局重新进入B站，还是这个样子，没用。

**Comment by Yukihana-Lamy** [comment]
> 梯子开全局重新进b站

之前，单击Tampermonkey的Bilibili Evolved，会出现【功能】&【设置】，现在单击了没反应。

**Comment by the1812** [comment]
那就不清楚了, 可能和别的脚本冲突了

**Comment by Casuwin** [comment]
我这不止失效，而且会导致顶栏整个消失。
![image](https://github.com/the1812/Bilibili-Evolved/assets/28701378/3fbe7dd7-92ca-4549-8585-71a9b19cea88)

**Comment by wch352136** [comment]
提供个额外信息，我是下载了预览版可以，正式版也是同样的问题，顶栏消失，没有设置和功能按钮（菜单里也没有）
![image](https://github.com/the1812/Bilibili-Evolved/assets/17609338/d45113bf-3e8d-4277-8b6a-688ce4a0a578)

**Comment by lxr760** [comment]
同样问题+1

在chrome dev 124.0.6356.6上脚本失效  左侧无2个图标，Tampermonkey也看不到脚本设置

但是旧版的比如beta123.0.6312.46 或者正式版122.0.6261.129脚本都能正常工作

**Comment by the1812** [comment]
合并至 #4476

**Comment by hahaVVV402** [comment]
找到解决Bilibili Evolved不运行的解决方法 
在chrome://extensions/ 中找到篡改猴
点击详情将<允许运行用户脚本>选项打开

<img width="1039" height="977" alt="Image" src="https://github.com/user-attachments/assets/4ad3a6c7-cbf8-4197-8d73-70fac034561e" />
