### ISSUE TITLE
多个浏览器打开Bilibili网页版页面和B站具体视频页面，BIlibili Evolved完全失效。。。

### ISSUE THREAD

**Issue by Yukihana-Lamy** [the1812/Bilibili-Evolved#4678]
### 对应功能

Bilibili网页版首页和任意视频页面Bilibili Evolved的【功能】&【设置】、篡改猴菜单栏Bilibili Evolved的【功能】&【设置】

### 问题描述

1.我最近更新了Bilibili Evolved到V2.8.9版本，但是我试了Google浏览器、华为浏览器PC版、123浏览器，打开Bilibili网页版首页和任意视频页面Bilibili Evolved都未出现【功能】&【设置】按钮，Bilibili Evolved完全失效，导致我无法使用Bilibili Evolved。

2.单击这些浏览器的篡改猴菜单栏Bilibili Evolved没反应，都没看见像之前那样，看见【功能】&【设置】。

不知相关页面的【功能】&【设置】不显示，是不是与我刚才提到的第2点有关系，希望Bilibili Evolved的作者尽快修复这些问题。

### 脚本版本

V2.8.9

### 脚本管理器及版本

Tampermonkey V5.0.1

### 浏览器及版本

Google浏览器 V122.0.6261.112（正式版本） （64 位）、华为浏览器 V12.1.3.306 | 内核版本: Chromium 99.0.4844.84、123浏览器 V2.2.29.4 [Chromium 117.0.5938.152]（正式版本） （64 位）

### 播放器版本

无

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Yukihana-Lamy** [comment]
截图

![Tampermonkey1](https://github.com/the1812/Bilibili-Evolved/assets/103800975/b261d06c-7f1d-4db2-9d84-abc3861e4f67)

![Tampermonkey2](https://github.com/the1812/Bilibili-Evolved/assets/103800975/00db4e49-fd6f-4701-a148-6871eee1be4e)

**Comment by the1812** [comment]
#4676

**Comment by 91hxs** [comment]
刚开始以为是缓存问题，不断的卸载，后面在edge自带的扩展商店重新安装篡改猴后发现可以使用了。
