### ISSUE TITLE
我在篡改猴里开启了Bilibili Evolved正式版，浏览B站网页版，发现B站网页版顶栏被清空了。

### ISSUE THREAD

**Issue by Yukihana-Lamy** [the1812/Bilibili-Evolved#4685]
### 对应功能

仅仅是在篡改猴里开启了Bilibili Evolved，还未打开具体功能

### 问题描述

我在篡改猴里开启了Bilibili Evolved正式版，浏览B站网页版，发现B站网页版顶栏被完全清空了。之前我就注意到这里已经有一些Bilibili Evolved的用户发帖反映了这个问题，说明我遇到这个问题的绝不是个例。

PS：虽然我这次帖子里反馈的是Bilibili Evolved正式版出现了这个情况，但是Bilibili Evolved预览版有时也会出现这种问题，所以我希望Bilibili Evolved在检测的的时候对2个版本全都进行检测，若是发现这个问题，能尽快修复和解决这个问题。

系统：Win10专业版

Version：22H2

### 脚本版本

V2.8.9

### 脚本管理器及版本

Tampermonkey V5.0.1

### 浏览器及版本

Google浏览器 V122.0.6261.112（正式版本） （64 位）、华为浏览器 V12.1.3.306 | 内核版本: Chromium 99.0.4844.84、123浏览器 V2.2.29.4 [Chromium 117.0.5938.152]（正式版本） （64 位）

### 播放器版本

无关播放器

### 播放策略

默认

### 错误信息

```Shell
见附加截图
```

### 附加截图

开启Bilibili Evolved正式版，出现问题的B站页面：

![Bilibili Evolved顶栏消失](https://github.com/the1812/Bilibili-Evolved/assets/103800975/fc60edcc-20a5-4eeb-b8a5-52d053deb7d1)

开启Bilibili Evolved正式版，正常的B站页面：

![Bilibili Evolved顶栏消失1](https://github.com/the1812/Bilibili-Evolved/assets/103800975/d8c2e34b-3e23-4327-a946-3aca7a0a98cd)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
#4476
