### ISSUE TITLE
在评论区出现随机的黑白相间方格

### ISSUE THREAD

**Issue by Casuwin** [the1812/Bilibili-Evolved#4688]
### 对应功能

还未找到具体哪个功能导致，猜测与简化评论区功能相关。

### 问题描述

在评论区滑动时出现类似PNG透明背景似的黑白相间格子（图片1），位置随机，大小随机，出现时间也随机，由于闪烁速度太快，哪怕通过录屏视频截图，0.2倍速度下播放也是快速闪过，但是肉眼能明显观察到，控制台有报错。

### 脚本版本

v2.8.9-30-gd2a3aa287

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

版本 119.0.6045.159（Official Build, ungoogled-chromium） （64 位）

### 播放器版本

4.8.10-a7eaf219

### 播放策略

默认

### 错误信息

```Shell
图片2
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/28701378/8f00e0b0-6022-40e2-86c5-d6f59247b1af)
![image](https://github.com/the1812/Bilibili-Evolved/assets/28701378/0570140e-f8f6-4b78-9d72-dd54b7d16677)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
这看着像你显卡出问题了。。。

**Comment by Casuwin** [comment]
虽然看起来确实像，但同一个窗口下的其他标签页没问题，而且我另一个屏幕没问题。

**Comment by Zorrok-k** [comment]
> 虽然看起来确实像，但同一个窗口下的其他标签页没问题，而且我另一个屏幕没问题。

这个问题存在很久了，不是脚本的问题是Chrome浏览器的问题。你把硬件加速关闭就不会有这个问题了，或者把gpu的调用改d3d9也能解决。很好奇你为啥不是先去百度和B站搜索而是第一怀疑脚本……

**Comment by Casuwin** [comment]
因为这事我是第一次看见，其他标签页面没出现，双屏中另一个屏的chrome页面也没出现，然后最近才换到预览版，因为正式版没法用，所以才来问问，其他脚本也不在B站启用。

**Comment by Casuwin** [comment]
哦，这台用的不是预览版，另一台才是预览版。

**Comment by Jack911521** [comment]
希望下个版本能解禁这个问题

**Comment by the1812** [comment]
更新显卡驱动吧, 脚本可没法解决这种问题
