### ISSUE TITLE
截图功能截图后无法复制粘贴

### ISSUE THREAD

**Issue by Casuwin** [the1812/Bilibili-Evolved#4691]
### 对应功能

启用视频截图
Commit: 29059634f

### 问题描述

在付费视频中截图，右上角能正常显示截图并保存到电脑，但无法直接复制进剪贴板粘贴，在word中粘贴会粘贴一个空白透明图片，在typora中粘贴则是一串链接。
而普通视频截图能传入剪贴板，但仍然无法粘贴。

### 脚本版本

v2.8.9-preview-131-gd0093bf65

### 脚本管理器及版本

Tampermonkey v4.19.0

### 浏览器及版本

版本 119.0.6045.159（Official Build, ungoogled-chromium） （64 位）

### 播放器版本

4.8.8-740859de

### 播放策略

默认

### 错误信息

```Shell
不知道哪个是有用报错。
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/28701378/db241238-2c26-4fcf-bf62-9c0b41bc27a2)
![image](https://github.com/the1812/Bilibili-Evolved/assets/28701378/c12521a4-e759-4393-ba4f-58ac2e290ccb)
![image](https://github.com/the1812/Bilibili-Evolved/assets/28701378/04b094b8-bf85-4f1e-88af-cb6d729c5d0d)
![image](https://github.com/the1812/Bilibili-Evolved/assets/28701378/03ca2b54-ca65-4b23-be0f-e50dd958c87b)
![image](https://github.com/the1812/Bilibili-Evolved/assets/28701378/f5397fb3-43d6-4b8c-89ff-776865dd4d74)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
因为截出来的图并不存在于 b 站服务器
浏览器复制时同时复制了地址和图片内容, 如果粘贴的程序优先从地址读取, 就无法下载了.
![Snipaste_2024-03-27_19-35-13](https://github.com/the1812/Bilibili-Evolved/assets/26504152/2c1e3e72-696e-4c70-948e-2fb6f2f01540)

像图像处理软件或者 Windows 剪贴板就会优先使用图片内容, 可以正确粘贴.
Word 这类软件可以调整粘贴格式, 选择粘贴图片即可.
![Snipaste_2024-03-27_19-36-49](https://github.com/the1812/Bilibili-Evolved/assets/26504152/db0fbc2a-c1b7-4b19-8d4d-dab6fa233977)
