### ISSUE TITLE
个人空间页举报弹窗中的举报内容字体颜色错误，融于背景色中

### ISSUE THREAD

**Issue by shugen002** [the1812/Bilibili-Evolved#47]
**关于哪一项功能**

夜间模式

**问题描述**

个人空间页举报弹窗中的举报内容字体颜色错误，融于背景色中

**脚本版本**
Bilibili Evolved (Preview) | 1.6.30

**浏览器版本**
Chrome 71

**附加截图**
![image](https://user-images.githubusercontent.com/10257291/50822371-947b1200-136c-11e9-9ee4-033ce3cea2f6.png)

**Comment by shugen002** [comment]
补充：
移除粉丝确认弹窗 提示信息字体颜色
![image](https://user-images.githubusercontent.com/10257291/50851299-64a52c00-13b7-11e9-968f-01a64a696b9b.png)
充电弹窗时覆盖层颜色过深（似乎有两层？）
![image](https://user-images.githubusercontent.com/10257291/50851353-91594380-13b7-11e9-8565-c380466d6f01.png)

**Comment by the1812** [comment]
充电那个是因为它又开了一层页面, 而夜间模式下每个页面的背景是设成深灰色的, 所以后面的就直接挡住了, 加个覆盖层看起来就很黑. 其他两个地方稍后会更新

**Comment by shugen002** [comment]
你们有没有觉得B站的前端代码很乱？。。。顺带，直播房间页的关注后的选择分组弹窗的覆盖层也是。。。

**Comment by the1812** [comment]
是啊, 一样的顶栏在不同页面可能有五六种实现(仅仅在一些过渡动画里有差别), 夜间只做了最常见的两种. 有的页面还是开发模式部署的...
