### ISSUE TITLE
能不能加兼容下Arc浏览器？发现在Arc浏览器上无法使用

### ISSUE THREAD

**Issue by hugbio** [the1812/Bilibili-Evolved#4704]
### 对应功能

~

### 问题描述

Arc浏览器上使用，开启后，顶栏不见了，而且网站侧边没有功能按钮，无法正常使用，能否兼容下Arc浏览器？

### 脚本版本

2.8.9

### 脚本管理器及版本

Tampermonkey v5.1.0

### 浏览器及版本

Arc浏览器版本1.37.0 (48361) Chromium Engine Version 123.0.6312.106

### 播放器版本

~

### 播放策略

默认

### 错误信息

```Shell
~
```

### 附加截图

~

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Tinhone** [comment]
这应该和 #4476 的问题相同

**Comment by hugbio** [comment]
@Tinhone  我也怀疑过是不是网络问题，把github源换成jsdelivr的，也还是不行，挂了梯子后，试了两个源，也还是不行。因为我是刚从edge浏览器试着转到arc浏览器。所以同时有两个浏览器，目前相同网络相同电脑相同系统，edge浏览器使用正常。arc浏览器不正常。所以我才会怀疑是不是浏览器不支持？

**Comment by Geeyun-JY3** [comment]
README 其实写得很清楚了：https://github.com/the1812/Bilibili-Evolved#%E6%B5%8F%E8%A7%88%E5%99%A8
> 支持最新版 Chrome, Edge (Chromium 内核), Firefox, 不保证脚本能在"套壳类浏览器"或者较长时间没更新的浏览器中完美运行.

无论是否和 #4476 一样，作者都是不会专门适配这个浏览器的。你这 issue 可以关了。
