### ISSUE TITLE
关于创作中心

### ISSUE THREAD

**Issue by xiaole3349** [the1812/Bilibili-Evolved#471]
**关于哪一项功能**
创作中心的夜间模式没有去除干净。

**问题描述**

如图：
![N$WG0S%C)SM 2UN5DVRDYHK](https://user-images.githubusercontent.com/40677760/80233024-6bc57b80-8688-11ea-8c13-6b014ac15d6a.png)

**脚本版本**

预览版

**浏览器版本**

Edge测试版。

**错误信息**

**附加截图**

**Comment by the1812** [comment]
这里和其他页面的消息弹窗是共用的(如果没开自定义顶栏的话)
如果取消它的夜间 其他页面里这个会是亮色

**Comment by xiaole3349** [comment]
> 这里和其他页面的消息弹窗是共用的(如果没开自定义顶栏的话)
> 如果取消它的夜间 其他页面里这个会是亮色
在这个页面用js单独给它个id控制它？

**Comment by xiaole3349** [comment]
> 这里和其他页面的消息弹窗是共用的(如果没开自定义顶栏的话)
> 如果取消它的夜间 其他页面里这个会是亮色

在这个页面用js单独给它个id控制它？

**Comment by the1812** [comment]
我之后试试吧

**Comment by the1812** [comment]
不太好搞 消息弹窗获取不了父页面的信息 也不知道被加了什么id 将就用着吧
