### ISSUE TITLE
夜间模式不适配chrome新版滚动条

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [the1812/Bilibili-Evolved#4717]
### 对应功能

夜间模式 Commit: 29059634f

### 问题描述

夜间模式未能被浏览器正确识别，导致不会发生切换，以下有图片示例
![image](https://github.com/the1812/Bilibili-Evolved/assets/87939280/7ca7f771-d4ac-41f7-a972-7150693346fd)
（这里使用GitHub页面作为正确工作时的示例，其他支持深浅切换的网站也可正常工作）

如果该滚动条样式未默认开启，可在 [chrome://flags/#fluent-overlay-scrollbars](chrome://flags/#fluent-overlay-scrollbars) 开启

### 脚本版本

v2.8.9-preview-120-g6de19e68bB

### 脚本管理器及版本

 Tampermonkey v5.1.0

### 浏览器及版本

Chrome 124.0.6367.61

### 播放器版本

null

### 播放策略

默认

### 错误信息

```Shell
null
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by zx-ma** [comment]
遇到了类似的问题， 一个可供参考的解决方式是直接用dark reader extension启用夜间模式，如还有问题可以查看此链接：[不覆盖default scrollbar](https://github.com/darkreader/darkreader/issues/12438#issuecomment-1991050313)

**Comment by YaeSakuraQvQ** [comment]
已解决，感谢大佬~
