### ISSUE TITLE
BV 号转换 复制链接时带上标题 会复制原标题和合集中的标题导致重复

### ISSUE THREAD

**Issue by pinaZC** [the1812/Bilibili-Evolved#4718]
### 对应功能

BV 号转换 Commit: d0093bf65

### 问题描述

如题 复制后粘贴效果如下
【星露谷物语1.6】新的物品翻译来了！ - 新的物品翻译来了！ https://www.bilibili.com/video/BV1Br42137Cs
（已验证 分p视频和没有合集的视频不会标题重复）

### 脚本版本

v2.8.9-preview-131-gd0093bf65

### 脚本管理器及版本

Tampermonkey v5.1.0

### 浏览器及版本

chrome 123.0.6312.124

### 播放器版本

4.8.17-806fa473

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![image](https://github.com/the1812/Bilibili-Evolved/assets/72682556/bd6066e4-e60e-452a-9256-ff93bd2e9f10)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
这是由通用设置里的文件命名格式决定的, 改成 `[title]` 就行了
![Snipaste_2024-05-01_10-52-03](https://github.com/the1812/Bilibili-Evolved/assets/26504152/ea4a1d83-f0f9-4af0-a74b-27aecc7691b9)
