### ISSUE TITLE
`自定义顶栏`搜索框的搜索历史删除相关小 bug

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#4732]
### 对应功能

自定义顶栏
Commit: 09b014c4f
内部名称: customNavbar

### 问题描述

删除搜索历史项时存在一个有点影响体验的 bug：将搜索框的搜索历史下拉菜单展示的搜索历史项依次记为历史项 1、历史项 2、历史项 3……（从上往下以此类推），通过点击搜索历史项右边的`×`（删除此项）按钮删除搜索历史项时，删除除历史项 1 外的任一搜索历史项后均会使搜索框的搜索历史下拉菜单收起。
因为删除历史项 1 时不会有这种情况，所以这应该不是故意的，于是我就来开 issue 了。

### 脚本版本

v2.8.10-preview-130-g09b014c4f

### 脚本管理器及版本

Tampermonkey v5.1.6194

### 浏览器及版本

Chrome 124.0.6367.91 （正式版本） （64 位）

### 播放器版本

不相关

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![bilibili_evolved_customNavbar_delete_history_entry_bug](https://github.com/the1812/Bilibili-Evolved/assets/49396421/ab858668-5254-47d1-9a28-d866ad0c749e)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
如 #4949 第 4 点所述，现在删除`自定义顶栏`搜索框的任一搜索历史项时都会收起下拉菜单，这应该不是预期效果。

**Comment by JiaoZhu1784** [comment]
经过修理，现在删除历史项 1 时也会遇到这个bug了

**Comment by Geeyun-JY3** [comment]
（既然重开了把这条评论也搬过来：<https://github.com/the1812/Bilibili-Evolved/discussions/4949#discussioncomment-11204384>）
通过 <kbd>/</kbd> 唤起的搜索栏也有一样的毛病
