### ISSUE TITLE
如果不用脚本的自动播放用播放器自带的话，那就不能使用播放时应用模式了

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#475]
所以暂时别删这个功能吧

**Comment by the1812** [comment]
`播放时应用模式`会去检测播放器的设置的, 没有什么影响

**Comment by u2shana** [comment]
> `播放时应用模式`会去检测播放器的设置的, 没有什么影响

原来是jsdelivr的源没更新新版的原因，换成GitHub源更新新版后能检测播放器状态了
