### ISSUE TITLE
“自定义顶栏—稍后再看“视频数字不符。

### ISSUE THREAD

**Issue by kethoven** [the1812/Bilibili-Evolved#4754]
“自定义顶栏—稍后再看“视频数字不符。
例如 我实际有998个视频，当时顶栏上只显示958.
这个问题，出现有两三个版本。以前的版本没有问题
希望能够修复一下

现在的顶栏稍后再看数字，跟稍后再看管理页面的一致，应该算是有效视频数量。但是这个数字没有播放页面的数字有意义。我们一般不关注管理页面，反而更关注播放页面。因为可添加的数量，也更加的真实。符合习惯直觉。

_Originally posted by @kethoven in https://github.com/the1812/Bilibili-Evolved/discussions/4740#discussioncomment-9443577_

**Comment by Geeyun-JY3** [comment]
？怎么关了

**Comment by kethoven** [comment]
因为b站统一了  ，无效视频被清除了

**Comment by Geeyun-JY3** [comment]
还真是，原本还想有空截个图留存一下证据的，现在看来是没机会了。

**Comment by Geeyun-JY3** [comment]
对，所以https://github.com/the1812/Bilibili-Evolved/discussions/4740#discussioncomment-9443577 所述的这种不统一的状况也没持续太长时间。
