### ISSUE TITLE
可不可以添加以下这两个exclude

### ISSUE THREAD

**Issue by Smoke-N-Mirrors** [the1812/Bilibili-Evolved#476]
可不可以添加一下
// @exclude      *://api.bilibili.com/*
// @exclude      *://*.bilibili.com/api/*
因为查看get的json响应时, 脚本的侧边栏代码会使得绝大部分json格式化插件失效, 每次更新都要手动把代码加上qwq, 作者大佬们意下如何

**Comment by the1812** [comment]
当然可以
顺便一提我用的 JSON Formatter, 不会失效
