### ISSUE TITLE
视频评论区的举报按钮无法点击

### ISSUE THREAD

**Issue by youngerstar** [the1812/Bilibili-Evolved#477]
**关于哪一项功能**
评论区的举报按钮

**问题描述**

av455467367
点击评论右侧三点按钮展开菜单后，截图中位置再往下移，菜单就会消失，无法点击举报按钮。关闭此脚本后正常。

**脚本版本**

正式版1.10.14

**浏览器版本**

Edge Dev 84.0.488.1

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/46211595/80329697-b9eba200-8875-11ea-9bf0-35f21232d8e9.png)

**Comment by Coulomb-G** [comment]
是否还开着其他插件脚本?

**Comment by the1812** [comment]
应该是简化评论区的问题

**Comment by youngerstar** [comment]
> 应该是简化评论区的问题

对的，关闭“简化评论区”后正常
