### ISSUE TITLE
左侧功能和设置面板点不进去

### ISSUE THREAD

**Issue by SunJunge08** [the1812/Bilibili-Evolved#4771]
### 对应功能

功能和设置面板

### 问题描述

所有页面都点不进去

### 脚本版本

2.8.12

### 脚本管理器及版本

暴力猴v2.18.0

### 浏览器及版本

Microsoft Edge 版本 126.0.2592.24 (正式版本) beta (64 位)

### 播放器版本

4.8.26-997702c5

### 播放策略

默认

### 错误信息

```Shell
Bilibili Evolved getContent 动画
Bilibili Evolved.user.js:226 Bilibili Evolved {…}code: (...)icon: (...)link: (...)route: (...)subCategories: (...)__ob__: Ee {value: {…}, shallow: false, mock: false, dep: be, vmCount: 0}get code: ƒ ()set code: ƒ (t)get icon: ƒ ()set icon: ƒ (t)length: 1name: "set"prototype: {}arguments: (...)caller: (...)[[FunctionLocation]]: Bilibili Evolved.user.js:246[[Prototype]]: ƒ ()[[Scopes]]: Scopes[9]get link: ƒ ()set link: ƒ (t)get route: ƒ ()set route: ƒ (t)get subCategories: ƒ ()set subCategories: ƒ (t)[[Prototype]]: Object
Bilibili Evolved.user.js:226 Bilibili Evolved updated widgets [__ob__: Ee]0: {__ob__: Ee}component: (...)name: (...)options: (...)urlInclude: (...)__ob__: Ee {value: {…}, shallow: false, mock: false, dep: be, vmCount: 0}get component: ƒ ()set component: ƒ (t)get name: ƒ ()set name: ƒ (t)get options: ƒ ()set options: ƒ (t)get urlInclude: ƒ ()set urlInclude: ƒ (t)[[Prototype]]: Object1: {__ob__: Ee}2: {__ob__: Ee}length: 3__ob__: Ee {value: Array(3), shallow: false, mock: false, dep: be, vmCount: 0}[[Prototype]]: Array
Bilibili Evolved.user.js:226 Bilibili Evolved null
Bilibili Evolved.user.js:226 Bilibili Evolved requestedPopup false
4Bilibili Evolved.user.js:226 Bilibili Evolved ScrollTrigger Intersection Observer trigger
2Bilibili Evolved.user.js:226 Bilibili Evolved requestedPopup true
2Bilibili Evolved.user.js:226 Bilibili Evolved requestedPopup false
Bilibili Evolved.user.js:226 Bilibili Evolved {…}
Bilibili Evolved.user.js:226 Bilibili Evolved {…}
Bilibili Evolved.user.js:226 Bilibili Evolved {code: 0, message: '0', ttl: 1, data: {…}}
Bilibili Evolved.user.js:226 Bilibili Evolved nextPage get []
2Bilibili Evolved.user.js:226 Bilibili Evolved requestedPopup false
3Bilibili Evolved.user.js:226 Bilibili Evolved requestedPopup true
Bilibili Evolved.user.js:226 Bilibili Evolved requestedPopup false
Bilibili Evolved.user.js:226 Bilibili Evolved requestedPopup true
11Bilibili Evolved.user.js:226 Bilibili Evolved requestedPopup false
Bilibili Evolved.user.js:226 Bilibili Evolved requestedPopup true
20Bilibili Evolved.user.js:226 Bilibili Evolved requestedPopup false
```

### 附加截图

[![pk8cBX8.png](https://s21.ax1x.com/2024/05/31/pk8cBX8.png)](https://imgse.com/i/pk8cBX8)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
![Snipaste_2024-06-03_23-01-40](https://github.com/the1812/Bilibili-Evolved/assets/26504152/e985e3a7-0a89-4b89-879d-0261d68e23ed)
点这里呢

**Comment by SunJunge08** [comment]
> ![Snipaste_2024-06-03_23-01-40](https://private-user-images.githubusercontent.com/26504152/336124268-e985e3a7-0a89-4b89-879d-0261d68e23ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDA3MzIsIm5iZiI6MTcxNzUwMDQzMiwicGF0aCI6Ii8yNjUwNDE1Mi8zMzYxMjQyNjgtZTk4NWUzYTctMGE4OS00Yjg5LTg3OWQtMDI2MWQ2OGUyM2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDExMjcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZTg3YTNlMjllNmNiMGFlYjc0YTgxZDUwMTEyYjVhZGIxY2VhNjIzYzFlOTI1NTg3ZDcyZjE1NWE1YTE1ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pXhQ9jM6JhUUzXzOfHrtkCX6lmx3SD878kocbNiM8sY) 点这里呢

突然就好了，这bug一惊一乍的。。。

（之前点这里也没用）
