### ISSUE TITLE
对于火狐的浮窗的文字等样式问题

### ISSUE THREAD

**Issue by hanfei831** [the1812/Bilibili-Evolved#4774]
### 对应功能

已关闭所有插件、组件，以及所有其他浏览器插件、拓展，也回退过错误出现前一版本仍稳定复现问题，但是换到Edge就怎么都行了，面向火狐的兼容出了问题？

### 问题描述

在所有界面的浮窗均有文字、样式问题
![firefox_qej5nIhz3r](https://github.com/the1812/Bilibili-Evolved/assets/87600710/0b449c2e-3d39-41af-a093-0a6785d8fe4d)
![firefox_fkUEo8JYI2](https://github.com/the1812/Bilibili-Evolved/assets/87600710/a59d2853-05c9-438e-a164-d0810c9e9e01)
![firefox_jEGPhsfvsv](https://github.com/the1812/Bilibili-Evolved/assets/87600710/ac8f507e-5131-4309-87f3-70b9360a0255)
![firefox_rKYQFXfyku](https://github.com/the1812/Bilibili-Evolved/assets/87600710/f64a4e7b-b14e-46ea-b9a9-df8d11a1aa1d)
![firefox_Pzi5NiUzDe](https://github.com/the1812/Bilibili-Evolved/assets/87600710/3c64fe7d-2302-476c-9a69-1f221f6e06c4)

### 脚本版本

v2.8.12-80-g513b71b49

### 脚本管理器及版本

Tampermonkey v5.11

### 浏览器及版本

Firefox 126.0.1

### 播放器版本

v4.8.5-722b238d

### 播放策略

AV1

### 错误信息

```Shell
见附图
```

### 附加截图

![lhuAoJdPrv](https://github.com/the1812/Bilibili-Evolved/assets/87600710/4b0342da-d44b-43a7-9f11-a7fc8d1cd8c0)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Tinhone** [comment]
Firefox v88.0 显示正常，没有复现，怪

**Comment by hanfei831** [comment]
确实怪了，这个BUG还在我电脑上呆了好几天了，我尽量排查以避免是我的个人问题，但是今天早上完全恢复了，我唯一多的操作是更新了核显驱动，只能说确实没怀疑到它头上去。
