### ISSUE TITLE
老是有弹窗错误

### ISSUE THREAD

**Issue by 258599** [the1812/Bilibili-Evolved#4781]
### 对应功能

1

### 问题描述

打开视频时老是会提示这个错误，不知道是不是哪个功能引起的，求助

视频例子：https://www.bilibili.com/bangumi/play/ss40104?t=2101&spm_id_from=..top_right_bar_window_history.content.click

![快照2](https://github.com/the1812/Bilibili-Evolved/assets/119504787/e083b8dd-5dfb-453a-aa48-68159cfd3648)
![快照3](https://github.com/the1812/Bilibili-Evolved/assets/119504787/c2bfc46a-e018-4ba5-a0ec-7a1d808d65d2)

### 脚本版本

v2.8.12-36-gf53902062

### 脚本管理器及版本

Tampermonkey 5.1.0

### 浏览器及版本

Supermium 122.0.6261.85

### 播放器版本

4.8.22

### 播放策略

默认

### 错误信息

```Shell
1
```

### 附加截图

1

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
你把其他脚本扩展关掉后还会有这个弹窗吗？

**Comment by 258599** [comment]
> 你把其他脚本扩展关掉后还会有这个错误弹窗吗？

不好意思，原来没有仔细测试，我关闭了Bilibili Evolved脚本就没有这个弹窗，

刚才仔细看了下，开着Bilibili Evolved站脚本，关闭uBlock Origin也不会有错误弹窗，看来是冲突了，不知道和那条 规则有冲突，请大佬修复

**Comment by 258599** [comment]
> 你把其他脚本扩展关掉后还会有这个错误弹窗吗？

找到冲突的地方了，我的uBlock Origin原来添加了大佬们的一些静态规则，去掉就没有提示(*⌒_⌒*)，

!B站 https://www.bilibili.com
||hdslb.com/bfs/static/jinkela/long/js/sentry/$script,domain=~space.bilibili.com
||hdslb.com/bfs/seed/jinkela/short/mini-login/$script
! 去部分顶栏
||hdslb.com/bfs/seed/laputa-header/bili-header.umd.js$script
