### ISSUE TITLE
启用弹幕空降与 pakku 中 点击展开弹幕信息 冲突

### ISSUE THREAD

**Issue by WilliamK7** [the1812/Bilibili-Evolved#4786]
### 对应功能

启用弹幕空降
Commit: f53902062
内部名称: danmakuAirborne
by [@kdxcxs](https://github.com/kdxcxs)

### 问题描述

在开启 [pakku](https://github.com/xmcp/pakku.js) 的 点击展开弹幕信息 后，点击含有空降信息的弹幕会直接展开详细信息，不需要按住 Ctrl 键，且空降功能失效

### 脚本版本

v2.8.12-36-gf53902062

### 脚本管理器及版本

Tampermonkey v5.2.0

### 浏览器及版本

Chrome 125.0.6422.61

### 播放器版本

4.8.27-8beb90e8

### 播放策略

HEVC

### 错误信息

```Shell
见截图
```

### 附加截图

Bilibili-Evolved 截图
![image](https://github.com/the1812/Bilibili-Evolved/assets/82304956/2ddc644d-4b61-4fde-8857-2ea0c4cccbcc)
pakku 截图
![image](https://github.com/the1812/Bilibili-Evolved/assets/82304956/29e397fd-d211-4828-a897-fbcc1f3e2d13)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by WilliamK7** [comment]
https://github.com/xmcp/pakku.js/issues/286

**Comment by xmcp** [comment]
pakku 的相关逻辑在 https://github.com/xmcp/pakku.js/blob/master/pakkujs/injected/panel.ts#L290-L297 ，它监听了 `.bpx-player-row-dm-wrap` 的点击事件然后 stopPropagation 了，大概是导致 bilibili-evolved 没有工作的原因。

那就 pakku 下个版本改成只有按住 ctrl 的状态才调用这块的逻辑，应该就没问题了。bilibili-evolved 这边如果想主动适配的话，可以把 event listener 挂到 capturing phase。

**Comment by xmcp** [comment]
pakku v2024.6.3已修复此问题
