### ISSUE TITLE
宽屏模式自动定位

### ISSUE THREAD

**Issue by MrV-art** [the1812/Bilibili-Evolved#479]
**期望的效果**
打开宽屏模式自动定位到播放器

**脚本版本**
649.29

**Comment by Coulomb-G** [comment]
「自动定位到播放器」这个功能不是已经有了吗?

**Comment by MrV-art** [comment]
但打开“播放时应用模式就不行”



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Coulomb-G"<notifications@github.com&gt;; 
发送时间: 2020年4月28日(星期二) 中午1:32
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "Mr.V"<1643721460@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 宽屏模式自动定位 (#479)





 
「自动定位到播放器」这个功能不是已经有了吗?

**Comment by the1812** [comment]
(本质同#483)
