### ISSUE TITLE
弹幕精简有木有，像手机端的屏蔽等级一样

### ISSUE THREAD

**Issue by holore** [the1812/Bilibili-Evolved#480]

**Comment by Coulomb-G** [comment]
目前没有屏蔽等级,有需求的话可以去安装「pakku」插件,和evolved脚本完全兼容

**Comment by holore** [comment]
> 目前没有屏蔽等级,有需求的话可以去安装「pakku」插件,和evolved脚本完全兼容
pakku这个插件不错啊，多谢了
