### ISSUE TITLE
屏蔽黑名单up主 添加过多之后 窗口太高 看不见添加了

### ISSUE THREAD

**Issue by gdf159159** [the1812/Bilibili-Evolved#4809]
### 对应功能

我也不知道是不是应该在这里反馈

### 问题描述

屏蔽黑名单up主 添加过多之后 窗口太高 看不见添加了
![微信截图_20240630192334](https://github.com/the1812/Bilibili-Evolved/assets/8487256/3fd90840-9e5e-47d4-9f90-f98eda17071d)

### 脚本版本

v2.8.12-36-gf53902062

### 脚本管理器及版本

5.1.6194

### 浏览器及版本

Edge	114.0.1823.106 

### 播放器版本

000

### 播放策略

默认

### 错误信息

```Shell
000
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
请善用搜索，已经修了，等版本更新：#4749

**Comment by gdf159159** [comment]
> 请善用搜索，已经修了，等更新：#4749

请以事实回答问题 已经修了 什么时候能更新 什么时候能用  

代码修好了  Bilibili-Evolved 上还不能用  你说那有用吗?

**Comment by Tinhone** [comment]
> > 请善用搜索，已经修了，等更新：#4749
> 
> 请以事实回答问题 已经修了 什么时候能更新 什么时候能用
> 
> 代码修好了 Bilibili-Evolved 上还不能用 你说那有用吗?

呃，更新时间取决于作者，在这之前只能等，这就是事实了。所以楼上完全没说错什么，请你不要以质问的语气问楼上。开重复的 Issue 只会产生困扰，产生不必要的戾气还会更混乱。如果只是想问什么时候更新，你可以选择在讨论区开一个求助帖询问

不过我记得如果是预览版，也许大概貌似可能只要 PR 合了，手动给组件检查更新就可以更新到最新版组件，不需要等本体版本更新，你可以试一试

**Comment by the1812** [comment]
> 什么时候能更新 什么时候能用

~~等鸡吃完米，狗舔完面，火烧断锁~~
这个月应该会更新下
