### ISSUE TITLE
夜间模式下部分元素颜色异常

### ISSUE THREAD

**Issue by SakuraI-Nagakaze** [the1812/Bilibili-Evolved#4817]
### 对应功能

样式-夜间模式，Commit: de14b6fff

### 问题描述

如图一，“up主觉得很赞”依然显示为白色，并且文本输入框变成全黑（鼠标悬浮在文本框上后会变回正常的灰色，见图二）

似乎b站又闲着没事开始改网页样式了

**图一**白色元素和纯黑输入框
![屏幕截图 2024-07-10 144241](https://github.com/the1812/Bilibili-Evolved/assets/91313612/953f0d8c-af59-4efe-b8e1-b3a31bea9319)

**图二**正常状态
![屏幕截图 2024-07-10 150001](https://github.com/the1812/Bilibili-Evolved/assets/91313612/542b0f41-d6dd-44ab-b4a2-49a00743e094)

### 脚本版本

v2.8.12-preview-129-gde14b6fff

### 脚本管理器及版本

Tampermonkey  v5.1.1

### 浏览器及版本

Microsoft Edge 版本 126.0.2592.87 (正式版本) (64 位)

### 播放器版本

4.8.33-460db19e

### 播放策略

AV1

### 错误信息

```Shell
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=75a13ce9-1426-4583-991b-991de1f7789f:226  Bilibili Evolved TypeError: Cannot read properties of null (reading 'code')
    at k (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili-Evolved-Preview.user.js&id=75a13ce9-1426-4583-991b-991de1f7789f:195:4070)
    at async a.created (eval at <anonymous> (eval at <anonymous> (:1:1)), <anonymous>:1:1352)
b @ userscript.html?name=Bilibili-Evolved-Preview.user.js&id=75a13ce9-1426-4583-991b-991de1f7789f:226
```

### 附加截图

![屏幕截图 2024-07-10 145752](https://github.com/the1812/Bilibili-Evolved/assets/91313612/aae53487-efc5-4f98-b51c-5617bab2ef37)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by SakuraI-Nagakaze** [comment]
补充：展开评论楼中楼时会出现一个白色的加载中的蒙版
b战一定是又改网页了

![屏幕截图 2024-07-10 223357](https://github.com/the1812/Bilibili-Evolved/assets/91313612/bf1f5f56-bc59-42e9-ba02-9fac41c36ef8)

**Comment by xx146542xx** [comment]
https://github.com/the1812/Bilibili-Evolved/discussions/4804#discussioncomment-9979617 改下那个ELEMENTS就能暂时回到旧版

**Comment by the1812** [comment]
合并至 #4843
