### ISSUE TITLE
去除【宽屏模式】自动调节网页位置的问题

### ISSUE THREAD

**Issue by lidoworld** [the1812/Bilibili-Evolved#483]
由于b站设定，在点击宽屏模式按钮后，有个B站自己的定位到播放器功能，会自动滚动网页让播放器顶端在可视范围的最上方。
对我们习惯用宽屏模式的人来说，这样会导致Evolved的【自动定位到播放器】实质失效。
并且新功能【播放器置顶】也是一样，开启这个功能同样会受自动滚动网页的影响，让播放窗口超出可视范围。
![QQ截图20200429161323](https://user-images.githubusercontent.com/24887103/80574549-a0448900-8a34-11ea-8aea-24a76262f582.png)

我觉得以上两种情况都可以通过去除B站自己的自动定位功能解决。

1.10.20

**Comment by SpoonerCake** [comment]
差不多吧，我发现从动态打开新视频页后，播放器置顶选项开启会定位失效，而关闭后和原来一样精准二次定位
PS:楼上同学，这个插件可以设置默认播放器模式是宽屏的，不用再去自己点击

**Comment by the1812** [comment]
对 我也想屏蔽掉B站宽屏时的定位效果 不过暂时没啥好办法

**Comment by 2220209876** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/492#issuecomment-622670891
加强版宽屏值得拥有

**Comment by CKylinMC** [comment]
> 对 我也想屏蔽掉B站宽屏时的定位效果 不过暂时没啥好办法

试一下这个

<details>

<summary>在播放器加载后覆盖一个对象</summary>

```javascript
window.PlayerAgent = {
    player_widewin: function() {
        //window.scrollTo(0, 55),
        window.isWide = !0,
        setSize()
    },
    player_fullwin: function(e) {
        window.scrollTo(0, 0),
        window.isWide = !1,
        setSize()
    },
    toggleBlackSide: function(e) {
        window.hasBlackSide = e,
        setSize()
    }
}
```
注释掉了scrollTo行
![image](https://user-images.githubusercontent.com/11648014/107186885-0af10f00-6a20-11eb-8873-d58e41c12d0e.png)

</details>

[做成油猴可以试一下，我这里能行](https://greasyfork.org/zh-CN/scripts/421421)

**Comment by Geeyun-JY3** [comment]
既然正式版没实装，这个 issue 得重开吧

**Comment by the1812** [comment]
噢 被 commit 自动关了

**Comment by sino1641** [comment]
该问题在`1.12.19`和已发布的v2预览版中依然存在。
尝试使用v2组件库的播放器定位功能修改偏移量无果，其中加载模式已经设置为同时。

**Comment by the1812** [comment]
那当然了 因为从来就没修复过

**Comment by sino1641** [comment]
> 那当然了 因为从来就没修复过

噗 所以只能说是历史遗留问题了吗

**Comment by MASA-OMI** [comment]
建议添加一个区分视频和番剧的自动宽屏功能。因为我在观看番剧的时候希望自动宽屏，但是浏览up主视频的时候希望用常规的界面。期待您的答复！

**Comment by Faxmell** [comment]
默认播放器模式这个插件是有bug吗？我设置宽屏后，有的视频就默认打开宽屏，有的还是原来的样子。

**Comment by the1812** [comment]
默认播放器模式 [v2.1.6](https://github.com/the1812/Bilibili-Evolved/releases/tag/v2.1.6) 之后已经不维护了

另外这个问题本身倒是已经解决了, 脚本已经支持了 `disableWindowScroll` API

**Comment by chengli9464** [comment]
自动宽屏会出现进视频，视频打不开的状况，网页黑屏，需要多次刷新

**Comment by Poraris** [comment]
自动宽屏是失效了吗？今天突然就不起作用了。

**Comment by MaxNirvana** [comment]
自动宽屏失效了
