### ISSUE TITLE
更新新版之后b站窗口花右侧上下滚动条和下侧左右滚动条过小

### ISSUE THREAD

**Issue by tutu-tutu** [the1812/Bilibili-Evolved#484]
有没有解决方法？设置里面没有能改的选项

**Comment by the1812** [comment]
打开浏览器控制台(<kbd>Ctrl+Shift+I</kbd>), 运行这个代码, 可以扩宽到`8px`, 觉得还不够宽可以把里面的数字再改大一些
```js
bilibiliEvolved.installStyle({ name: 'wideScrollBar', style: `::-webkit-scrollbar { border-radius: 4px !important; height: 8px !important; width: 8px !important; }`, displayName: '滚动条加宽', mode: 'important'})
```

**Comment by WatcherOfTheWorld** [comment]
可以给这个功能加一个关闭按钮吗
在支持overlay scrollbar的浏览器上看着很怪

**Comment by shimakotodo** [comment]
> 打开浏览器控制台(Ctrl+Shift+I), 运行这个代码, 可以扩宽到`8px`, 觉得还不够宽可以把里面的数字再改大一些
> 
> ```js
> bilibiliEvolved.installStyle({ name: 'wideScrollBar', style: `::-webkit-scrollbar { border-radius: 4px !important; height: 8px !important; width: 8px !important; }`, displayName: '滚动条加宽', mode: 'important'})
> ```

解决了大问题，改到15感觉很好。

**Comment by pbxs666** [comment]
那新样式怎么卸载呢？
我这边是先加载浏览器原本的宽滚动条，再加载脚本的细滚动条，最后加载新样式，屏幕右边闪三下，很难受，想暂时先卸载新样式，求方法！

**Comment by the1812** [comment]
```js
bilibiliEvolved.uninstallStyle('wideScrollBar')
```

**Comment by pbxs666** [comment]
好的谢谢
把bilibiliEvolved.uninstallStyle，bilibiliEvolveddelStyle,bilibiliEvolved.deleteStyle都试了，就是忘了加样式名称😂

**Comment by the1812** [comment]
或者你可以试试把安装那里的`mode: 'important'`改成`mode: 'instant'`(尽早注入模式)

**Comment by pbxs666** [comment]
刚刚试了下，总结如下：
1.mode: 'important' 在视频播放界面滚动条会加载3下，其他界面会加载预期的2下；
2.mode: 'instant' 不管在哪个界面，滚动条都只加载2下.
3.用mode: 'instant'就可以完美的加载宽滚动条了
