### ISSUE TITLE
评论区相关功能 / 播放器相关功能失效汇总

### ISSUE THREAD

**Issue by the1812** [the1812/Bilibili-Evolved#4843]
### 对应功能

评论区 & 视频播放器

### 问题描述

- 由于 b 站使用新版基于 Shadow DOM 的评论区, 评论区相关的功能都会失效, 详情可看 #4804
- 播放器更新导致部分 class 变化, 包括删除视频弹窗和禁用特殊弹幕样式等功能都会失效 (PR #4839)

### 脚本版本

v2.9.0-preview

### 脚本管理器及版本

v5.3.6204

### 浏览器及版本

Chrome 127.0.6533.72

### 播放器版本

4.8.36-511a5548

### 播放策略

默认

### 错误信息

```Shell
\
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by InsaneDream233** [comment]
在预览界面鼠标移到的视频进度，点开就从那个进度开始播放了

**Comment by KuiPer-LTW** [comment]
请问何时更新？今天发现更多的功能失效了，太恶心

**Comment by the1812** [comment]
立个 flag, 黑神话发售前更新

**Comment by KuiPer-LTW** [comment]
> 立个 flag, 黑神话发售前更新

时间差不多咯~

**Comment by the1812** [comment]
> > 立个 flag, 黑神话发售前更新
> 
> 
> 
> 时间差不多咯~

这不是已经更了吗（虽然还剩了点难搞的

**Comment by KuiPer-LTW** [comment]
> > > 立个 flag, 黑神话发售前更新
> > 
> > 
> > 时间差不多咯~
> 
> 这不是已经更了吗（虽然还剩了点难搞的

评论区相关功能基本还是失效状态，sad

**Comment by xx146542xx** [comment]
寄 强制回退老版评论区的脚本也失效了

**Comment by MiuraUnnchi** [comment]
评论区ip显示在新版动态界面和播放界面里还是失效的，旧版动态界面能用了

**Comment by KB3146706** [comment]
更新到2.9.2后视频播放评论区显示IP与禁用搜索词还是失效

Commit: 7e9a93368
内部名称: ipShow

Commit: 99743eecf
内部名称: disableCommentsSearchLink

**Comment by Crystal-RainSlide** [comment]
简化评论区相关代码出现报错

控制台报错：
```
Bilibili Evolved TypeError: l is not a function
```

调试器确定是简化评论区的代码出错，应该是函数的 `l` 变成了 `undefined`：
![图片](https://github.com/user-attachments/assets/dd2bf588-b798-49f5-9971-37f50ebc1ac2)

定位到对应代码：
https://github.com/the1812/Bilibili-Evolved/blob/cb55fc2669e74da2953f14343663e00a8a337478/registry/lib/components/style/simplify/comments/index.ts#L57

发现此函数只能运行一次：
https://github.com/the1812/Bilibili-Evolved/blob/cb55fc2669e74da2953f14343663e00a8a337478/src/core/container-query.ts#L10

怀疑是运行了不止一次。建议储存此函数的运行结果，或者把 `lodash.once()` 去掉。

**Comment by lxw726** [comment]
IDM下载调用不了了？你们有这种情况吗？

**Comment by lxw726** [comment]
IDM下载调用不了了？你们有这种情况吗？

**Comment by zjns** [comment]
v2.9.2-45-g99743eecf 版本禁用评论区搜索词不生效，但是播放页就绪后手动开关一次开关又生效了，可能是时机不对？

**Comment by mkh10086** [comment]
隐藏视频推荐失效了

**Comment by limbia** [comment]
双击全屏失效是内部哪个插件的问题？

**Comment by 9k001** [comment]
隐藏直播推荐失效

**Comment by lkfun** [comment]
评论区替换功能，评论本体可替换，楼中楼中的评论失效

替换前
![Image](https://github.com/user-attachments/assets/298a5ec7-7059-4391-ac4b-4a7ddd202b78)
替换配置
![Image](https://github.com/user-attachments/assets/7fa6cd21-0cd8-43d2-b858-a3b1fff5a5c6)
替换后
![Image](https://github.com/user-attachments/assets/fbef3807-755d-45ee-b8b2-affa2ef0edec)

**Comment by pros2021** [comment]
希望能增加这个评论区一键展开功能？

**Comment by bixudamajiang** [comment]
评论区内容替换功能在firefox上完全失效，firefox版本135.0
