### ISSUE TITLE
2024-07-30 禁用大会员弹幕失效

### ISSUE THREAD

**Issue by GalaxySnail** [the1812/Bilibili-Evolved#4847]
### 对应功能

禁用特殊弹幕样式-禁用大会员弹幕

### 问题描述

今天（7月30日）起发现禁用大会员弹幕失效了。疑似是B站改变了大会员弹幕使用的 class。示例如下：

正常的普通弹幕：

```html
<div aria-live="polite" role="comment" class="bili-danmaku-x-dm" style="--opacity: 0.95; --fontSize: 28.749999403953552px; --fontFamily: SimHei, 'Microsoft JhengHei', Arial, Helvetica, sans-serif; --fontWeight: normal; --color: #ffffff; --textShadow: 1px 0 1px #000000,0 1px 1px #000000,0 -1px 1px #000000,-1px 0 1px #000000; --offset: 1523px; --translateX: -1679px; --duration: 8.41s; --top: 4px;">飞起来了！</div>
```

大会员弹幕：

```html
<div aria-live="polite" role="comment" class="bili-danmaku-x-dm bili-danmaku-x-roll bili-danmaku-x-show" style="--opacity: 0.95; --fontSize: 28.749999403953552px; --fontFamily: SimHei, 'Microsoft JhengHei', Arial, Helvetica, sans-serif; --fontWeight: normal; --color: #ffffff; --offset: 1469px; --translateX: -1625px; --duration: 8.14s; --top: 71.34091186523438px;">
  <div style="background-image: url(http://i0.hdslb.com/bfs/dm/716a749b2461e02df0b4dafb59bbaf0ceab79da9.png);background-size: cover;text-shadow:none;background-clip:text;text-fill-color: #FFFFF;text-stroke: 2px transparent;-webkit-background-clip:text;-webkit-text-fill-color: #FFFFF;-webkit-text-stroke: 2px transparent;-moz-background-clip:text;-moz-text-fill-color: #FFFFF;-moz-text-stroke: 2px transparent;-ms-background-clip:text;-ms-text-fill-color: #FFFFF;-ms-text-stroke: 2px transparent;" class="bili-danmaku-x-dm-vip">文学的开端</div>
</div>
```

### 脚本版本

v2.9.0-preview-132-g9920134d9

### 脚本管理器及版本

Tampermonkey v5.1.1

### 浏览器及版本

chromium 125.0.6422.142

### 播放器版本

4.8.37-286d821a

### 播放策略

HEVC

### 错误信息

```Shell
没有与此有关的报错
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
#4843

**Comment by GalaxySnail** [comment]
emmmmm 原来是同一个问题啊。不是同时开始发生的我还以为是不同的问题（

**Comment by the1812** [comment]
都是灰度推送的，大会员这个我上周就遇到了
