### ISSUE TITLE
首页滚动条幅第二三张总是容易白

### ISSUE THREAD

**Issue by Edelweissor** [the1812/Bilibili-Evolved#485]
**脚本版本**
正式版1.10.20

**浏览器版本**
最新版edge

**附加截图**
![1](https://user-images.githubusercontent.com/46107675/80585497-038ae700-8a46-11ea-9639-e020770ce80f.png)

**Comment by the1812** [comment]
那是广告被删掉了 可以开一下`显示占位文本`

**Comment by Edelweissor** [comment]
好的谢谢
