### ISSUE TITLE
启用自定义顶栏的搜索框，隐藏热搜会失效

### ISSUE THREAD

**Issue by Unbengabled** [the1812/Bilibili-Evolved#4855]
### 对应功能

自定义顶栏，隐藏热搜

### 问题描述

打开“自定义顶栏”后，搜索框仍然会显示推荐的关键词，但是如果关闭了自定义顶栏，打开了隐藏热搜，推荐关键词就能隐藏

### 脚本版本

2.9.0 preview

### 脚本管理器及版本

tampermonkey v5.1.1

### 浏览器及版本

edge 127.0.2651.86 

### 播放器版本

与播放器无关

### 播放策略

默认

### 错误信息

```Shell
见下面第一张图
```

### 附加截图

![屏幕截图 2024-08-02 231627](https://github.com/user-attachments/assets/a4975b1a-dd5e-4b04-8128-63a93502a04d)
![屏幕截图 2024-08-02 230934](https://github.com/user-attachments/assets/5c15ddbe-d0a9-4d77-9bb0-fadd7e18a4ec)
![屏幕截图 2024-08-02 230452](https://github.com/user-attachments/assets/06d56a9d-c64d-4f87-8987-63f82af0fc72)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Tinhone** [comment]
`自定义顶栏`默认不带热搜显示功能，可以看一下是不是安装了插件`搜索栏 - 搜索推荐`

**Comment by Unbengabled** [comment]
> `自定义顶栏`默认不带热搜显示功能，可以看一下是不是安装了插件`搜索栏 - 搜索推荐`

还真是这个，我都注意不到还有个插件功能
