### ISSUE TITLE
脚本未运行

### ISSUE THREAD

**Issue by 17JK-hash** [the1812/Bilibili-Evolved#4879]
### 对应功能

无法运行脚本

### 问题描述

在b站视频页面油猴显示没有运行中的脚本，尝试卸载重装以及使用预览版仍然如此
![image](https://github.com/user-attachments/assets/38f77185-11f1-47c8-aaf8-554bdd15249f)

### 脚本版本

2.9.0

### 脚本管理器及版本

Tampermonkey5.1.0

### 浏览器及版本

Chrome 127.0.6533.120

### 播放器版本

4.8.40-dd52a801

### 播放策略

默认

### 错误信息

```Shell
https://drive.google.com/file/d/1IbYRolgzV5DvTB5SfQ3R51hxfv2X_rza/view?usp=sharing
```

### 附加截图

![image](https://github.com/user-attachments/assets/78a90c50-2094-4ee7-a36a-891e1ce20041)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Luosuu** [comment]
发现对Chrome不同Profile有影响，我有两个profile，一个没有问题另外一个会有这个问题

**Comment by the1812** [comment]
最近 Tempermonkey 支持 Manifest v3 了, 需要[打开扩展的开发者模式](https://www.tampermonkey.net/faq.php#Q209)才能用, 我补充到[常见问题](https://github.com/the1812/Bilibili-Evolved/discussions/1301)中了
