### ISSUE TITLE
动态过滤的生效tab范围建议

### ISSUE THREAD

**Issue by XZL16** [the1812/Bilibili-Evolved#488]
刚刚担心是不是自己少设置了什么，一看到动态过滤器的悬浮说明，实在不好意思，打扰了......

---

**动态过滤**

**期望的效果**
目前动态过滤器过滤的侧边栏只会在“全部"的tab里生效，希望能在”投稿视频"、“追番追剧”、“专栏”里也生效，或者说生效范围覆盖整个动态页面，即使B站后续出了其他tab也会一并生效

![typora](https://i0.hdslb.com/bfs/album/d89dae659c0e903ebff078e41bb4063be12e12a0.png@518w_1e_1c.png)	

**脚本版本**
// @version      1.10.20

**Comment by the1812** [comment]
行  不过`按类型屏蔽`这一块还是不让它生效的 不然像开着屏蔽专栏切到专栏就直接空了
