### ISSUE TITLE
在不挂代理的情况下，使用StreamSaver输出方式下载视频会显示报错，挂代理刷新后正常

### ISSUE THREAD

**Issue by meowx25** [the1812/Bilibili-Evolved#4882]
### 对应功能

Commit: 0f6a1fd31
内部名称: downloadVideo

### 问题描述

如题

### 脚本版本

v2.9.1-preview-135-g49dab167c

### 脚本管理器及版本

Tampermonkey v.5.1.1

### 浏览器及版本

Microsoft Edge 版本 127.0.2651.105

### 播放器版本

HTML5播放器 v4.8.42-c1e72bb6

### 播放策略

AV1

### 错误信息

```Shell
biliMirror.umd.mini.js:1 
 bili-mirror: unhandRejection-Error parsing failed: 
Error: Cannot parse given Error object
    at Object.parse (biliMirror.umd.mini.js:1:42900)
    at biliMirror.umd.mini.js:1:48107
    at Object.<anonymous> (biliMirror.umd.mini.js:1:48506)
    at Generator.next (<anonymous>)
    at biliMirror.umd.mini.js:1:525
    at new Promise (<anonymous>)
    at t (biliMirror.umd.mini.js:1:270)
    at Object.unhandRejection (biliMirror.umd.mini.js:1:47913)
    at biliMirror.umd.mini.js:1:52835
(匿名)	@	biliMirror.umd.mini.js:1
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by meowx25** [comment]
![【绝区零】每次出警都有你！_哔哩哔哩_bilibili 和另外 6 个页面 - 个人 - Microsoft​ Edge 2024_8_20 1_22_44](https://github.com/user-attachments/assets/59eb1d08-116d-4808-8a62-696c84e78a21)
补张截图

**Comment by meowx25** [comment]
![【绝区零】每次出警都有你！_哔哩哔哩_bilibili 和另外 6 个页面 - 个人 - Microsoft​ Edge 2024_8_20 1_26_20](https://github.com/user-attachments/assets/89a89d16-a252-4c5b-bcaa-54edc2c2da23)
补张截图

**Comment by the1812** [comment]
因为你装的是 GitHub 源, 改一下分流规则, 或者换 jsDelivr 源不用挂代理
