### ISSUE TITLE
有关直播弹幕的建议

### ISSUE THREAD

**Issue by MI55-845** [the1812/Bilibili-Evolved#489]
**关于哪一项功能**
记住直播弹幕设置。

**期望的效果**
希望可以在直播功能中增加视频功能中记住弹幕设置的功能。

![1](https://user-images.githubusercontent.com/44739100/80703390-44056600-8b15-11ea-8d82-8f983e103c95.png)

**脚本版本**
正式版 1.10.20

**Comment by the1812** [comment]
貌似除了隐藏弹幕 其他的设置都是可以记住的

**Comment by MI55-845** [comment]
> 貌似除了隐藏弹幕 其他的设置都是可以记住的

**实在不好意思，我当时没有认真测试，也记错了视频弹幕设置的同步方式，请关闭这个问题吧。**
当时是同时打开了多个直播间，只在一个直播间设置了弹幕，其他直播间没有跟着变，想起来视频的弹幕设置，就想着来提一个建议。
测试了一下，视频的弹幕设置也不能在多个视频同时开启的情况下，进行同步变动。
