### ISSUE TITLE
升级到最新版本后出现了这样的问题

### ISSUE THREAD

**Issue by yellowkangaroo** [the1812/Bilibili-Evolved#4893]
### 对应功能

下载视频时报错

### 问题描述

下载视频时报错
所有可下载的视频页面都报错

### 脚本版本

v2.9.1-87-gd113a6712

### 脚本管理器及版本

Tampermonkey v5.1.1

### 浏览器及版本

Microsoft Edge 版本 128.0.2739.54 (正式版本) (64 位)

### 播放器版本

4.8.44

### 播放策略

HEVC

### 错误信息

```Shell
见截图
```

### 附加截图

![剪贴板_09-03-2024_01](https://github.com/user-attachments/assets/25e50ed1-1cad-4302-ad75-16559e03d3f4)
![剪贴板_09-03-2024_01](https://github.com/user-attachments/assets/fa75d99b-cb0b-4f53-b2fa-304d5705c77f)
![剪贴板_09-03-2024_02](https://github.com/user-attachments/assets/51ceefa8-48e8-4064-8fe6-8c540eba77b1)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
看看控制台?
![Snipaste_2024-09-05_22-34-52](https://github.com/user-attachments/assets/c28b793e-064f-4bdf-bd5a-f6cb49de9259)

**Comment by wildhorse666** [comment]
Bilibili Evolved [downloadExtraAssets] []
userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:226  Bilibili Evolved {readyState: 4, responseHeaders: '', finalUrl: 'https://raw.githubusercontent.com/jimmywarting/StreamSaver.js/2.0.6/StreamSaver.js', status: 0, statusText: '', …}
b @ userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:226
a @ userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:226
startDownload @ VM24:12
await in startDownload
click @ VM24:12
Tt @ userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:246
n @ userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:246
n._wrapper @ userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:246
biliMirror.umd.mini.js:2  bili-mirror: unhandRejection-Error parsing failed: Error: Cannot parse given Error object
    at Object.parse (biliMirror.umd.mini.js:2:17463)
    at biliMirror.umd.mini.js:2:22670
    at Object.<anonymous> (biliMirror.umd.mini.js:2:23069)
    at Generator.next (<anonymous>)
    at biliMirror.umd.mini.js:1:525
    at new Promise (<anonymous>)
    at t (biliMirror.umd.mini.js:1:270)
    at Object.unhandRejection (biliMirror.umd.mini.js:2:22476)
    at biliMirror.umd.mini.js:2:27398
(匿名) @ biliMirror.umd.mini.js:2
(匿名) @ biliMirror.umd.mini.js:1
t @ biliMirror.umd.mini.js:1
unhandRejection @ biliMirror.umd.mini.js:2
(匿名) @ biliMirror.umd.mini.js:2
userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:199  Uncaught (in promise) {readyState: 4, responseHeaders: '', finalUrl: 'https://raw.githubusercontent.com/jimmywarting/StreamSaver.js/2.0.6/StreamSaver.js', status: 0, statusText: '', …}
then @ userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:199
load
(匿名) @ userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:195
i @ userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:195
b @ userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:195
eval @ VM24:12
downloadVideoInfo @ VM24:12
eval @ VM24:12
startDownload @ VM24:12
await in startDownload
click @ VM24:12
Tt @ userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:246
n @ userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:246
n._wrapper @ userscript.html?name=Bilibili-Evolved.user.js&id=463967b3-b83b-4317-b729-def43ffdfb47:246

**Comment by wildhorse666** [comment]
<img width="834" alt="屏幕截图 2024-09-06 182214" src="https://github.com/user-attachments/assets/e97bb80e-4f37-4b46-8652-85c40d470bc3">

同样报错，重装应用会好一阵子

**Comment by SoraotoJZhao** [comment]
同样是下载报错，使用Aria RPC方式下载就会出现这种情况
![01](https://github.com/user-attachments/assets/7b3e2688-7940-4fcd-bf46-2de35e49083e)
![02](https://github.com/user-attachments/assets/a0a683b1-4091-4ea5-8c43-8211838e3b8b)

**Comment by Crystal-RainSlide** [comment]
@wildhorse666 建议给标题加上“下载错误”；你可能要开代理下载一下所需的依赖

@SoraotoJZhao 你的错误不一样，有应该是数组的东西变得不是数组了。
但代码里有不止一个应该是数组的变量，不好说具体是哪个：

https://github.com/the1812/Bilibili-Evolved/blob/cb55fc2669e74da2953f14343663e00a8a337478/registry/lib/components/video/download/DownloadVideo.vue#L345

https://github.com/the1812/Bilibili-Evolved/blob/cb55fc2669e74da2953f14343663e00a8a337478/registry/lib/plugins/video/download/aria2-output/aria2-input.ts#L10

**Comment by the1812** [comment]
@SoraotoJZhao 用的预览版还是正式版, 报错的地方是预览版的新功能

**Comment by SoraotoJZhao** [comment]
> @SoraotoJZhao 用的预览版还是正式版, 报错的地方是预览版的新功能

我用的是正式版Bilibili Evolved v2.9.2-45-g99743eecf

**Comment by the1812** [comment]
> > @SoraotoJZhao 用的预览版还是正式版, 报错的地方是预览版的新功能
> 
> 我用的是正式版Bilibili Evolved v2.9.2-45-g99743eecf

aria2 RPC 插件在正式版仓库重装一下吧

**Comment by oxygenkun** [comment]
> 同样是下载报错，使用Aria RPC方式下载就会出现这种情况 

无法复现，油猴更新`Bilibili-Evolved`后，手动`检查所有更新`，把插件也更新一下应该就没问题了。

![image](https://github.com/user-attachments/assets/7bfc0d95-9b4b-4a39-9ad2-516f1a6709c4)
