### ISSUE TITLE
下载视频音频失败

### ISSUE THREAD

**Issue by sdadafdf666** [the1812/Bilibili-Evolved#4913]
### 对应功能

![image](https://github.com/user-attachments/assets/c146b99e-7041-47e5-ad00-e725b2961768)

### 问题描述

所有视频都无法下载

### 脚本版本

2.9.3

### 脚本管理器及版本

tampermonkey v5.1.1

### 浏览器及版本

 128.0.2739.79 (正式版本) (64 位)

### 播放器版本

没找到抱歉

### 播放策略

HEVC

### 错误信息

```Shell
看截图吧
```

### 附加截图

![image](https://github.com/user-attachments/assets/018572ce-4a96-4caf-9f44-6fcd12ba120b)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by sdadafdf666** [comment]
求修复嘻嘻

**Comment by sdadafdf666** [comment]
我也用了其他版本，上个版本很稳定，但是我下载了还不行，不知道什么情况。然后我也试了八月十五号那个版本，也会出现错误，我再去试试上个版本，一会回

**Comment by sdadafdf666** [comment]
上个版本，挂梯子能下，不挂梯子下不了，是不是和这个网有关系。但是在学校不挂梯子也能下

**Comment by sdadafdf666** [comment]
挂梯子能下，点第一下下不了，双击才行，之前我记得点一次就行的啊

**Comment by Geeyun-JY3** [comment]
播放器区域内右键点击即可看见播放器版本。

**Comment by CATBRO-HUI** [comment]
我也遇到这个问题

**Comment by sdadafdf666** [comment]
我怎么修复呢，你发的这个

**Comment by sdadafdf666** [comment]
还是不行啊，我又更新了最新版还是不行

**Comment by sdadafdf666** [comment]
![image](https://github.com/user-attachments/assets/986ecd70-1100-46ce-9d9c-f60c3a817777)
是这个吗，播放器版本

**Comment by sdadafdf666** [comment]
我右键能看到的还有这个
![image](https://github.com/user-attachments/assets/92441d92-fc16-48a7-84bf-05bd59609e97)

**Comment by the1812** [comment]
还没更新呢 可以挂梯子装 GitHub 源的版本 这个问题只有 jsDelivr 源有

**Comment by sdadafdf666** [comment]
好的感谢，我先用老版本了，老版本还是可以用的

**Comment by Puxirepublic** [comment]
不能下载视频我这里出现很久了，重新下了 github 源，包括 github 预览源，还是无法下载，我这里是 firefox 130.0.1，脚本管理器是 violentmonkey，

![Annotation 2024-09-20 103448](https://github.com/user-attachments/assets/10e0e14c-0db3-49ef-b958-cc58744b95fc)

**Comment by sdadafdf666** [comment]
> 不能下载视频我这里出现很久了，重新下了 github 源，包括 github 预览源，还是无法下载，我这里是 firefox 130.0.1，脚本管理器是 violentmonkey，
> 
> ![Annotation 2024-09-20 103448](https://private-user-images.githubusercontent.com/5261049/369240935-10e0e14c-0db3-49ef-b958-cc58744b95fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjkyOTksIm5iZiI6MTcyNjgyODk5OSwicGF0aCI6Ii81MjYxMDQ5LzM2OTI0MDkzNS0xMGUwZTE0Yy0wZGIzLTQ5ZWYtYjk1OC1jYzU4NzQ0Yjk1ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjBUMTA0MzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMyMDBmOTQ4ZWI0ZTE4OTNmNjZkY2VlYmRkNTQwMjNjY2Q4ZmUzNmQ0OWFiODhiY2ZhZjViODAwMzQ4NTZiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gcGcPZ755bSDfTSKeRlaXh16S7BmAaBHLGtFnfncDLM)



> 不能下载视频我这里出现很久了，重新下了 github 源，包括 github 预览源，还是无法下载，我这里是 firefox 130.0.1，脚本管理器是 violentmonkey，
> 
> ![Annotation 2024-09-20 103448](https://private-user-images.githubusercontent.com/5261049/369240935-10e0e14c-0db3-49ef-b958-cc58744b95fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjkyOTksIm5iZiI6MTcyNjgyODk5OSwicGF0aCI6Ii81MjYxMDQ5LzM2OTI0MDkzNS0xMGUwZTE0Yy0wZGIzLTQ5ZWYtYjk1OC1jYzU4NzQ0Yjk1ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjBUMTA0MzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMyMDBmOTQ4ZWI0ZTE4OTNmNjZkY2VlYmRkNTQwMjNjY2Q4ZmUzNmQ0OWFiODhiY2ZhZjViODAwMzQ4NTZiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gcGcPZ755bSDfTSKeRlaXh16S7BmAaBHLGtFnfncDLM)

用上个版本，挂个vpn可以下很离谱

**Comment by sdadafdf666** [comment]
github我这里他也下不了，这个bug有点

**Comment by cpuopt** [comment]
https://github.com/the1812/Bilibili-Evolved/commit/a29af2e27b85169bf0e30cc3dbfad4a26a2dea58#diff-270577853b591fe63696b5b1ed718c67219e38fb7e8d636d87cf4f17245c52f2R30
看到这个应该是修复的尝试，但是这个hash又变成`428d5b3338ed0e6dde7f2e7b584f3ae2a5e7a81f01b20b7a3034f0da1f6c3cf9`了
自己改一下就能用，不知道streamsaver在搞什么幺蛾子

**Comment by Puxirepublic** [comment]
> [a29af2e#diff-270577853b591fe63696b5b1ed718c67219e38fb7e8d636d87cf4f17245c52f2R30](https://github.com/the1812/Bilibili-Evolved/commit/a29af2e27b85169bf0e30cc3dbfad4a26a2dea58#diff-270577853b591fe63696b5b1ed718c67219e38fb7e8d636d87cf4f17245c52f2R30) 看到这个应该是修复的尝试，但是这个hash又变成`428d5b3338ed0e6dde7f2e7b584f3ae2a5e7a81f01b20b7a3034f0da1f6c3cf9`了 自己改一下就能用，不知道streamsaver在搞什么幺蛾子

原来如此。
但是我改了后，点下载视频直接 log 弹窗报 hash 值错误，给了我另一个正确的 hash 值，我再改成 log 给的 hash 值，不报错了，又回到原来问题了。

**Comment by the1812** [comment]
> [a29af2e#diff-270577853b591fe63696b5b1ed718c67219e38fb7e8d636d87cf4f17245c52f2R30](https://github.com/the1812/Bilibili-Evolved/commit/a29af2e27b85169bf0e30cc3dbfad4a26a2dea58#diff-270577853b591fe63696b5b1ed718c67219e38fb7e8d636d87cf4f17245c52f2R30) 看到这个应该是修复的尝试，但是这个hash又变成`428d5b3338ed0e6dde7f2e7b584f3ae2a5e7a81f01b20b7a3034f0da1f6c3cf9`了 自己改一下就能用，不知道streamsaver在搞什么幺蛾子

跟 StreamSaver 没关系, 是因为 jsDelivr 源的链接使用了其提供的代码压缩服务 (加上 `.min.js` 后缀), 脚本新版本加了 SRI 功能后校验会出问题, 修复的方式是换回不压缩的链接并更换 hash

![Snipaste_2024-09-25_19-56-06](https://github.com/user-attachments/assets/187ff052-799f-447e-aafb-7323d0dc6f35)

**Comment by sdadafdf666** [comment]
大佬们加油，慢慢搞

**Comment by dragonish** [comment]
jsDelivr 的问题，对于同一个文件 `https://cdn.jsdelivr.net/npm/streamsaver@2.0.6/StreamSaver.min.js`，会得到两种由不同 Terser 版本压缩后的文件，压缩结果相同，但附加的文件头内容不同，所以校验出来的结果不一致。

1. `Minified by jsDelivr using Terser v5.19.2.`，文件头内容：

```js
/**
 * Minified by jsDelivr using Terser v5.19.2.
 * Original file: /npm/streamsaver@2.0.6/StreamSaver.js
 *
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
```

校验结果为：`64f465e51e5992be894c5d42330b781544eda5462069fe6be4c7421f02d28c92`，即脚本目前所验证的值。

2. `Minified by jsDelivr using Terser v5.10.0.`，文件头内容：

```js
/**
 * Minified by jsDelivr using Terser v5.10.0.
 * Original file: /npm/streamsaver@2.0.6/StreamSaver.js
 *
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
```

校验结果为：`428d5b3338ed0e6dde7f2e7b584f3ae2a5e7a81f01b20b7a3034f0da1f6c3cf9`。

**Comment by sdadafdf666** [comment]
怎么样了大佬们

**Comment by dragonish** [comment]
> 怎么样了大佬们

大佬之前就预览分支上处理了(a29af2e27b85169bf0e30cc3dbfad4a26a2dea58)，后面更新发布应该就合进来了；或者你可以对照着先自己改着用。

**Comment by the1812** [comment]
在发布更新之前, 可以临时编辑一下脚本来绕过这个问题:

1. 搜索 `StreamSaver.min.js`
![Snipaste_2024-10-01_23-09-17](https://github.com/user-attachments/assets/852c6e92-1cf0-4f8c-8291-7c12c9d2baa0)

2. 把 `.min` 去掉, 留下 `StreamSaver.js`, 后面的 sha256 里那一串 hash 换成 `a110f78e0b092481dc372901c4d57ae50681d773bc9d55e62356f9a22f17e24b`
![Snipaste_2024-10-01_23-11-10](https://github.com/user-attachments/assets/fd02c971-a55d-4169-98db-f670d93dda78)

3. 保存后应该就可以了

**Comment by gtxy54** [comment]
谢谢大佬，有用啦awa

**Comment by popplee** [comment]
感谢可以下了

**Comment by sdadafdf666** [comment]
搞定了

**Comment by Ifover** [comment]
用WASM混流输出也类似的问题，参考了一下方法
把actual的值替换掉脚本里的sha256 
这个方便，之前下载后还要手动合并音频和视频

**Comment by sdadafdf666** [comment]
我这个又不行了，直接显示错误，然后挂vpn就可以正常下了，什么情况

**Comment by sdadafdf666** [comment]
![image](https://github.com/user-attachments/assets/bd49915c-e981-4965-8958-0e7d4fd31bd0)
如图大佬，这个是改过之后的，但还是不行，然后挂个梯子就行了，很奇怪，是不是哪里又出问题了

**Comment by sdadafdf666** [comment]
> 你用的 github 源装的就得梯子

没有用github，难道说，那个代码改的就是变成github了吗

**Comment by the1812** [comment]
> 没有用github，难道说，那个代码改的就是变成github了吗

那应该是 StreamSaver 本身需要连接到 jimmywarting.github.io 的原因
