### ISSUE TITLE
[功能建议]能否指定播放器大小？

### ISSUE THREAD

**Issue by 2220209876** [the1812/Bilibili-Evolved#492]
能否增加 像 https://greasyfork.org/zh-CN/scripts/371672-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9-bilibili-com-%E6%92%AD%E6%94%BE%E5%99%A8%E8%B0%83%E6%95%B4r-ver-stardust
播放器调整R这类的调整播放器大小的功能？

指定播放器大小后可以滚动鼠标查看简介评论等（因为如果用网页全屏鼠标会不能滚动）
![image](https://user-images.githubusercontent.com/7346652/80780157-832cc900-8ba0-11ea-960f-dbb198013de3.png)
![image](https://user-images.githubusercontent.com/7346652/80780213-be2efc80-8ba0-11ea-967d-3c9e19caa7c5.png)

**Comment by the1812** [comment]
开宽屏不行吗

**Comment by 2220209876** [comment]
> 开宽屏不行吗

宽屏太小了，不能填满网页窗口。

**Comment by the1812** [comment]
那么播放器调整R能和我的脚本一起用吗

**Comment by 2220209876** [comment]
> 那么播放器调整R能和我的脚本一起用吗

播放器调整R在B站新版播放器界面有问题所以。。。

**Comment by the1812** [comment]
试试这个应该够宽了吧
开控制台(<kbd>Ctrl+Shift+I</kbd>)粘贴进去运行
```js
bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `.player-mode-widescreen #app {
    position: relative !important;
}
.player-mode-widescreen #bofqi {
    width: 98vw !important;
    height: calc(100vh - 50px - 40px) !important;
    position: absolute !important;
    left: 1vw !important;
}
.player-mode-widescreen .player-wrap,
.player-mode-widescreen .danmaku-box {
    height: calc(100vh - 50px - 40px + 12px) !important;
}`, displayName: '加强版宽屏', mode: 'important'})
```
![image](https://user-images.githubusercontent.com/26504152/80785878-600c1480-8bb4-11ea-96df-be5bfe8aa000.png)

**Comment by 2220209876** [comment]
> 试试这个应该够宽了吧
> 开控制台(Ctrl+Shift+I)粘贴进去运行
> 
> ```js
> bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `.player-mode-widescreen #app {
>     position: relative !important;
> }
> .player-mode-widescreen #bofqi {
>     width: 98vw !important;
>     height: calc(100vh - 50px - 40px) !important;
>     position: absolute !important;
>     left: 1vw !important;
> }
> .player-mode-widescreen .player-wrap,
> .player-mode-widescreen .danmaku-box {
>     height: calc(100vh - 50px - 40px) !important;
> }`, displayName: '加强版宽屏', mode: 'important'})
> ```
> 
> ![image](https://user-images.githubusercontent.com/26504152/80785878-600c1480-8bb4-11ea-96df-be5bfe8aa000.png)

谢谢谢谢，厉害厉害

![image](https://user-images.githubusercontent.com/7346652/80854435-e3883d00-8c6a-11ea-8f28-c2070f82d8ff.png)
可以增加高度吗？红框区域

**Comment by 2220209876** [comment]
可以像这个脚本这样的效果吗 https://github.com/Zren/ResizeYoutubePlayerToWindowSize/

顶栏移动到视频底部从而实现播放器填充网页

**Comment by the1812** [comment]
那个脚本效果长什么样? 我上不了youtube
高度你可以自己调 代码里那两段`height: calc(100vh - 50px - 40px)` 把减去的数值改小一点 重新再运行一次

**Comment by 2220209876** [comment]
> 那个脚本效果长什么样？我上不了youtube
> 高度你可以自己调代码里那两段`height: calc(100vh - 50px - 40px)`把反相的数值改小一点重新再运行一次

![image](https://user-images.githubusercontent.com/7346652/80855446-e2a7d900-8c73-11ea-9d6c-e619ecaa0036.png)
这样的，第一屏是视频填充网页，滑动鼠标出现搜索栏（顶栏）等

**Comment by 2220209876** [comment]
> 那个脚本效果长什么样? 我上不了youtube
> 高度你可以自己调 代码里那两段`height: calc(100vh - 50px - 40px)` 把减去的数值改小一点 重新再运行一次
100vh - 50px - 40px 
改为100 0 0

![image](https://user-images.githubusercontent.com/7346652/80855820-d8d3a500-8c76-11ea-8f69-e5852e3c7b66.png)

![_2020-05-02_13-13-11](https://user-images.githubusercontent.com/7346652/80855808-b477c880-8c76-11ea-9617-a998c96ba34d.png)
红框里是第一屏效果
如果增加自动隐藏弹幕栏就不用装两个脚本了😄

**Comment by 2220209876** [comment]
稍后再看页面错位(┬＿┬)
![image](https://user-images.githubusercontent.com/7346652/80856849-125cde00-8c80-11ea-87e1-797b6c8daa14.png)

**Comment by Coulomb-G** [comment]
错位的话,请开启「稍后再看重定向」

**Comment by 2220209876** [comment]
> 错位的话,请开启「稍后再看重定向」

😄 这个功能怎么说呢。。。如果稍后观看里有一个视频还行，用稍后观看的时候大部分情况下都是有很多视频，重定向后的稍后观看需要手动播放下一个，所以超级麻烦

**Comment by Coulomb-G** [comment]
那你得找b站去做个新版稍后再看,旧版稍后再看这边不会再做适配

**Comment by the1812** [comment]
那就赶快催一下b站把稍后再看整个换新版吧
总是以youtube的思维逛b站肯定会觉得到处麻烦的

**Comment by 2220209876** [comment]
> 那就赶快催一下b站把稍后再看整个换新版吧
已经联系了
> 总是以youtube的思维逛b站肯定会觉得到处麻烦的
以youtube的思维逛b站？
YouTube搜索栏也是在顶部的

**Comment by the1812** [comment]
我是指youtube的设计跟b站不一样 强求把youtube的设计搬到b站总是会不完美的
点赞的位置 宽屏的大小 还有标题/up主的位置(或者说是首屏的呈现)等等
建议尽量去适应b站, 而不是把b站变得更像youtube

**Comment by 2220209876** [comment]
> 我是指youtube的设计跟b站不一样 强求把youtube的设计搬到b站总是会不完美的
> 点赞的位置 宽屏的大小 还有标题/up主的位置(或者说是首屏的呈现)等等
> 建议尽量去适应b站, 而不是把b站变得更像youtube

本来问题是搜索顶栏位置能不能移动到下方，怎么和YouTube与B站扯上关系了？
你直接写明B站的顶栏因技术原因不能移动位置不就好了

**Comment by the1812** [comment]
那个说的是稍后再看跟宽屏的问题
顶栏我确实也移不下去

**Comment by 2220209876** [comment]
> 那个说的是后来再看跟宽屏的问题
> 顶栏我确实也移不下去

稍后观看就是B站问题了，等B站用新版播放器应该就可以了

**Comment by SpoonerCake** [comment]
如果想去掉顶栏的话可以在AdblockPlus插件里面添加过滤规则：www.bilibili.com##.mini-header.m-header.mini-type
因为我是把动态页t.bilibili.com放到收藏夹的，这个规则是在播放页面屏蔽顶栏，效果如下，而我想搜索时，就会打开收藏的动态页
![QQ截图20200503184706](https://user-images.githubusercontent.com/49234232/80912357-fc7a1680-8d6e-11ea-8dae-3e3fee87071a.png)
效果感觉还不错

**Comment by the1812** [comment]
稍后再看那个得等b站了
顶栏我又有些想法了 说不定真能移下去

**Comment by the1812** [comment]
```js
bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `.player-mode-widescreen #app {
    position: relative !important;
}
.player-mode-widescreen #bofqi {
    width: 100vw !important;
    height: calc(100vh) !important;
    position: absolute !important;
    left: 0 !important;
}
.player-mode-widescreen .player-wrap,
.player-mode-widescreen .danmaku-box {
    height: calc(100vh + 50px) !important;
}
.player-mode-widescreen .custom-navbar {
    transform: translateY(100vh);
}
.player-mode-widescreen {
    scrollbar-width: none !important;   
}
.player-mode-widescreen #app {
    transform: translateY(-70px);
}
.player-mode-widescreen::-webkit-scrollbar {
    height: 0 !important;
    width: 0 !important;
}`, displayName: '加强版宽屏', mode: 'important'})
```

**Comment by 2220209876** [comment]
> 如果想去掉顶栏的话可以在AdblockPlus插件里面添加过滤规则：www.bilibili.com ##。mini-header.m-header.mini-type
> 因为我是把动态页t.bilibili.com放到收藏夹的，这个规则是在播放页面屏蔽顶栏，效果如下，而我想搜索时，就会打开收藏的动态页面 效果感觉还不错
> ![QQ截图20200503184706](https://user-images.githubusercontent.com/49234232/80912357-fc7a1680-8d6e-11ea-8dae-3e3fee87071a.png)
o(∩_∩)o 不错的方式

**Comment by 2220209876** [comment]
> 顶栏下移版
> 
> ```js
> bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `.player-mode-widescreen #app {
>     position: relative !important;
> }
> .player-mode-widescreen #bofqi {
>     width: 100vw !important;
>     height: calc(100vh) !important;
>     position: absolute !important;
>     left: 0 !important;
> }
> .player-mode-widescreen .player-wrap,
> .player-mode-widescreen .danmaku-box {
>     height: calc(100vh + 50px) !important;
> }
> .player-mode-widescreen .custom-navbar {
>     transform: translateY(100vh);
> }
> .player-mode-widescreen {
>     scrollbar-width: none !important;   
> }
> .player-mode-widescreen #app {
>     transform: translateY(-70px);
> }
> .player-mode-widescreen::-webkit-scrollbar {
>     height: 0 !important;
>     width: 0 !important;
> }`, displayName: '加强版宽屏', mode: 'important'})
> ```

![image](https://user-images.githubusercontent.com/7346652/80914995-d6aa3d00-8d81-11ea-888b-61828e3e8e58.png)
666真的可以

**Comment by 2220209876** [comment]
> 如果想去掉顶栏的话可以在AdblockPlus插件里面添加过滤规则：www.bilibili.com##.mini-header.m-header.mini-type
> 因为我是把动态页t.bilibili.com放到收藏夹的，这个规则是在播放页面屏蔽顶栏，效果如下，而我想搜索时，就会打开收藏的动态页
> ![QQ截图20200503184706](https://user-images.githubusercontent.com/49234232/80912357-fc7a1680-8d6e-11ea-8dae-3e3fee87071a.png)
> 效果感觉还不错

弹幕栏怎么隐藏的？

**Comment by the1812** [comment]
弹幕栏隐藏加一段:
```css
.player-mode-widescreen .bilibili-player-video-bottom-area {
    display: none !important;
}
```

**Comment by 2220209876** [comment]
> 弹幕栏隐藏加一段:
> 
> ```css
> .player-mode-widescreen .bilibili-player-video-bottom-area {
>     display: none !important;
> }
> ```

弹幕栏可以自动隐藏吗？就想全屏模式那样移动到下面会自动出来

**Comment by 2220209876** [comment]
![image](https://user-images.githubusercontent.com/7346652/80915263-b11e3300-8d83-11ea-9cec-77e227f0af3c.png)
自动定位播放器-1040就是完美版第一屏视频了，如果关闭自动定位播放器播放器会往下移动30像素左右。

**Comment by the1812** [comment]
顶多是做成页面往下移动看到弹幕栏这样子 给高度加上46px(弹幕栏的高度)
```css
height: calc(100vh + 46px) !important;
```

**Comment by 2220209876** [comment]
bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `.player-mode-widescreen #app {
    position: relative !important;
}
.player-mode-widescreen #bofqi {
    width: 100vw !important;
    height: calc(100vh) !important;
    position: absolute !important;
    left: 0 !important;
}
.player-mode-widescreen .player-wrap,
.player-mode-widescreen .danmaku-box {
    height: calc(100vh + 50px) !important;
}
.player-mode-widescreen .custom-navbar {
    transform: translateY(100vh);
}
.player-mode-widescreen {
    scrollbar-width: none !important;   
}
.player-mode-widescreen #app {
    transform: translateY(-70px);
}
.player-mode-widescreen::-webkit-scrollbar {
    height: 0 !important;
    width: 0 !important;
    }
    .player-mode-widescreen .bilibili-player-video-bottom-area {
     display: none !important;
}
}`, displayName: '加强版宽屏', mode: 'important'})


现在用的这个代码不能投币（会有遮罩）

.player-mode-widescreen #app {
    transform: translateY(-70px);
}去掉这一行代码能投币（但是会错位）

**Comment by 2220209876** [comment]
> 顶多是做成页面往下移动看到弹幕栏这样子 给高度加上46px(弹幕栏的高度)
> 
> ```css
> height: calc(100vh + 46px) !important;
> ```

不知道加在哪(┬＿┬)，
另外用了宽屏代码后不能投币（好像有遮罩）

**Comment by the1812** [comment]
就是把里面`height: xxxx`的换成这段

**Comment by 2220209876** [comment]
bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `.player-mode-widescreen #app {
    position: relative !important;
}
.player-mode-widescreen #bofqi {
    width: 100vw !important;
    height: calc(100vh + 46px) !important;
    position: absolute !important;
    left: 0 !important;
}
.player-mode-widescreen .player-wrap,
.player-mode-widescreen .danmaku-box {
    height: calc(100vh + 50px) !important;
}
.player-mode-widescreen .custom-navbar {
    transform: translateY(100vh);
}
.player-mode-widescreen {
    scrollbar-width: none !important;   
}
.player-mode-widescreen #app {
    transform: translateY(-70px);
}
.player-mode-widescreen::-webkit-scrollbar {
    height: 0 !important;
    width: 0 !important;
}`, displayName: '加强版宽屏', mode: 'important'})


这样操作没效果。。。

**Comment by the1812** [comment]
```js
bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `
.player-mode-widescreen #app {
    position: relative !important;
}
.player-mode-widescreen #bofqi {
    width: 100vw !important;
    height: calc(100vh + 46px) !important;
    position: absolute !important;
    left: 0 !important;
}
.player-mode-widescreen .player-wrap,
.player-mode-widescreen .danmaku-box {
    height: calc(100vh + 50px + 46px) !important;
}
.player-mode-widescreen .custom-navbar {
    transform: translateY(calc(100vh + 46px));
}
.player-mode-widescreen {
    scrollbar-width: none !important;   
}
.player-mode-widescreen #app {
    transform: translateY(-70px);
}
.player-mode-widescreen::-webkit-scrollbar {
    height: 0 !important;
    width: 0 !important;
}`, displayName: '加强版宽屏', mode: 'important'})
```

**Comment by 2220209876** [comment]
> ```js
> bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `
> .player-mode-widescreen #app {
>     position: relative !important;
> }
> .player-mode-widescreen #bofqi {
>     width: 100vw !important;
>     height: calc(100vh + 46px) !important;
>     position: absolute !important;
>     left: 0 !important;
> }
> .player-mode-widescreen .player-wrap,
> .player-mode-widescreen .danmaku-box {
>     height: calc(100vh + 50px + 46px) !important;
> }
> .player-mode-widescreen .custom-navbar {
>     transform: translateY(calc(100vh + 46px));
> }
> .player-mode-widescreen {
>     scrollbar-width: none !important;   
> }
> .player-mode-widescreen #app {
>     transform: translateY(-70px);
> }
> .player-mode-widescreen::-webkit-scrollbar {
>     height: 0 !important;
>     width: 0 !important;
> }`, displayName: '加强版宽屏', mode: 'important'})
> ```

可以了谢谢，不能投币是什么原因？

**Comment by the1812** [comment]
投币点了得再往下一些

**Comment by 2220209876** [comment]
> 投币点了得再往下一些

![image](https://user-images.githubusercontent.com/7346652/81764700-b3f7f100-9504-11ea-99ae-9d4cdce0e5d2.png)
  😀看到了，在第三屏

**Comment by 2220209876** [comment]
大佬又来麻烦你了😃
1、用了加强版宽屏最近播放页的up主信息和推荐视频的位置会空出好多位置怎么办
2、投币会显示在第三屏有办法修一下吗
> ```js
> bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `
> .player-mode-widescreen #app {
>     position: relative !important;
> }
> .player-mode-widescreen #bofqi {
>     width: 100vw !important;
>     height: calc(100vh + 46px) !important;
>     position: absolute !important;
>     left: 0 !important;
> }
> .player-mode-widescreen .player-wrap,
> .player-mode-widescreen .danmaku-box {
>     height: calc(100vh + 50px + 46px) !important;
> }
> .player-mode-widescreen .custom-navbar {
>     transform: translateY(calc(100vh + 46px));
> }
> .player-mode-widescreen {
>     scrollbar-width: none !important;   
> }
> .player-mode-widescreen #app {
>     transform: translateY(-70px);
> }
> .player-mode-widescreen::-webkit-scrollbar {
>     height: 0 !important;
>     width: 0 !important;
> }`, displayName: '加强版宽屏', mode: 'important'})
> ```
![image](https://user-images.githubusercontent.com/7346652/89252259-d43ed400-d64b-11ea-9054-6d69be246b6a.png)

![image](https://user-images.githubusercontent.com/7346652/89252165-8924c100-d64b-11ea-98ad-4d9da44d3d10.png)
