### ISSUE TITLE
希望能够将 夜间模式 放到 自定义顶栏上。或者将夜间模式的图标摆放到 设置、附加功能图标的下方。

### ISSUE THREAD

**Issue by kethoven** [the1812/Bilibili-Evolved#493]
**关于哪一项功能**

将“样式”——“夜间模式‘’设置图标摆放到顶栏里面。
**期望的效果**
现在的夜间模式挺好用的，就是想要随机打开夜间模式的时候，操作有点繁琐。
希望将夜间模式的图标摆放到页面上，能够一次操作就能够打开夜间模式。

**脚本版本**
1.10.20

**Comment by the1812** [comment]
我可以考虑下放在顶栏上

**Comment by kethoven** [comment]
> 我可以考虑下放在顶栏上
那太好了！这个夜间模式是适配得最好的夜间模式。
