### ISSUE TITLE
开启直播信息扩充后，鼠标放在直播up头像弹出来的个人信息面板会被掩盖

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#494]
![QQ截图20200502230810](https://user-images.githubusercontent.com/14146754/80867978-17467f80-8cca-11ea-8b95-ec2a933ab56f.jpg)
像这样

**Comment by Coulomb-G** [comment]
请参考[#437](urlhttps://github.com/the1812/Bilibili-Evolved/issues/437)

**Comment by the1812** [comment]
貌似写漏了 没开固定也应该屏蔽一下这个弹窗

**Comment by shugen002** [comment]
我直接自己叠了个样式，干掉了滚动，反正我的关注少
`
.live-up-list{
    max-height:unset!important;
    overflow:unset!important;
}
`
