### ISSUE TITLE
脚本完全不工作（音频下载）

### ISSUE THREAD

**Issue by abdd22** [the1812/Bilibili-Evolved#4941]
### 对应功能

音频下载功能

### 问题描述

先补充其他几个信息：Thinkpad笔记本，系统 win11 23H2 9月最新版（有9月累计补丁+.net累计补丁 出厂默认，OEM中文家庭版）

ISP 江苏电信。普通用户，非码农。

1.根据教程 https://www.bilibili.com/read/cv35964049/ 设置好，（文中所有软件/插件本就是我个人的自用品，我只需要更改一下 User-Agent Switcher and Manager插件的设置而已）

2.视频本体 https://www.bilibili.com/video/BV1bLpveFEtE/，

edge回放当然没有任何问题，杜比已经正常开启，此时打开脚本选择下载仅音频（dash），没有任何反应，什么事也没有发生（没有任何下载链接弹出!!!!! 根本没到点击链接下载这一步），反复试了几次都一样。

3.切回默认的user agent，完全一切正常。结束。

个人的几点思考（因为不确定原因，所以只能上来提交issue了）

1.我不确定此问题是否与User-Agent Switcher and Manager插件 更改了user agent有关，这是最大的疑问。

2.怀疑的重点，当然是StreamSaver，但是并非与第三方cookies有关...（否则就是与软件不兼容了，要指定浏览器版本这事有点过分了。大家都知道 Brave自带过滤，我当然是默认，而扩展方面，很常见的UBO 1.6.0，或者是adguard(5.0.4 已经是MV3 beta了)也很常见）

3.更有可能（无法彻底排除）是 jimmywarting.github.io (StreamSaver 的网站) ，也就是github.io，电信出国就这垃圾状况啊。也就是与伟大的防火墙有关了，谁会上阿B同时开着全局代理啊，全部走直链才是正常情况吧。

### 脚本版本

2.9.3（最新）

### 脚本管理器及版本

Tampermonkey v5.3.0（MV3，官网正式版）

### 浏览器及版本

Edge 129/Brave 1.68（内核127）

### 播放器版本

HTML5播放器 v4.8.48（2024.9.29 最新）

### 播放策略

默认

### 错误信息

```Shell
none
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by fakepheonix** [comment]
我的错误信息
`[RuntimeLibrary] Check integrity failed from https://cdn.jsdelivr.net/npm/streamsaver@2.0.6/StreamSaver.min.js, expected = 64f465e51e5992be894c5d42330b781544eda5462069fe6be4c7421f02d28c92, actual = 428d5b3338ed0e6dde7f2e7b584f3ae2a5e7a81f01b20b7a3034f0da1f6c3cf9`

测试下来使用dash下载视频与音频均有该报错，且与User-Agent Switcher and Manager无关

**Comment by Geeyun-JY3** [comment]
或者可以参考 #4913

**Comment by abdd22** [comment]
> 或许可以参考 #4913

看了4913，难道想说是github源的问题吗？（我好像也是？不确定）

**Comment by the1812** [comment]
我觉得你可以先验证下第3点，梯子都是可以分流的，不是非得全代理或全直连

**Comment by alexfan07** [comment]
刚刚测试，2.9.1配梯子可以下载

**Comment by KappaFish0914** [comment]
我把版本回退到 2.8.13 版本可以正常下载B站视频了
