### ISSUE TITLE
动态/评论抽奖

### ISSUE THREAD

**Issue by yaronzz** [the1812/Bilibili-Evolved#495]
**关于哪一项功能**
提供给小UP的抽奖功能，因为B站需要“磁力”到达一定的分数才有这功能

**期望的效果**
在动态页面和视频页面提供抽奖功能：
- 转发 + 关注
- 评论 + 关注
- 选择中奖人数
功能按钮可以放在截图中箭头指向的地方，谢谢，如果能做到的话。
![动态页面](https://user-images.githubusercontent.com/15530958/80868341-891fc880-8ccc-11ea-9060-6d5371f7b0e4.png)
![视频页面](https://user-images.githubusercontent.com/15530958/80868343-8b822280-8ccc-11ea-8fcf-ae3295f9a929.png)

**脚本版本**
v1.10.20

**Comment by Coulomb-G** [comment]
我电磁力不够,无法测试该功能,另外你的要求是做出一个抽奖设置界面还是快速关注并转发功能?

**Comment by yaronzz** [comment]
> 我电磁力不够,无法测试该功能,另外你的要求是做出一个抽奖设置界面还是快速关注并转发功能?

是一个“抽奖设置界面”，这个功能是给UP主用的，比如我这种没有抽奖功能（磁力不够），又想给粉丝抽奖的人。

想要在动态界面有一个抽奖按钮，点击之后能显示一个界面，如下：
![4](https://user-images.githubusercontent.com/15530958/80869016-80c98c80-8cd0-11ea-89f4-6785b5f601a3.png)

点击确定之后，弹出一个抽奖结果的界面，列出抽中的用户ID

**Comment by Coulomb-G** [comment]
b站之所以设置电磁力门槛,就是为了不让up主靠抽奖在短时间内持续吸粉,你的初心是为了反馈粉丝是好的,但这个功能一旦做出来是会有其他人用来造营销号的,和官方意愿相悖,我只能建议你先成为大UP

**Comment by yaronzz** [comment]
你这么一说好像也是，那好吧

**Comment by the1812** [comment]
我记得有个btools有这功能

**Comment by yaronzz** [comment]
> 我记得有个btools有这功能

噢，谢谢，我去找找看
