### ISSUE TITLE
隐藏视频推荐 失效

### ISSUE THREAD

**Issue by NickerGrylls** [the1812/Bilibili-Evolved#4957]
### 对应功能

隐藏视频推荐
Commit: 9e5159f7d
内部名称: hideRelatedVideos

### 问题描述

如题，在绝大部分视频页面都失效，唯独对于稍后再看的视频能够正常屏蔽

### 脚本版本

v2.9.3-46-g9e5159f7d

### 脚本管理器及版本

Tampermonkey v5.1.1

### 浏览器及版本

Microsoft Edge 版本 129.0.2792.79 (正式版本) (64 位)

### 播放器版本

4.8.48-86c1d4e8

### 播放策略

AV1

### 错误信息

```Shell
0: {__ob__: Ae}1: {__ob__: Ae}2: {__ob__: Ae}3: {__ob__: Ae}4: {__ob__: Ae}5: {__ob__: Ae}6: {__ob__: Ae}length: 7[[Prototype]]: Array(0)
userscript.html?name=Bilibili-Evolved.user.js&id=d47ca7e9-1351-469b-bfca-a27a9d0bc551:228 Bilibili Evolved reply 0 0
userscript.html?name=Bilibili-Evolved.user.js&id=d47ca7e9-1351-469b-bfca-a27a9d0bc551:228 Bilibili Evolved at 0 0
userscript.html?name=Bilibili-Evolved.user.js&id=d47ca7e9-1351-469b-bfca-a27a9d0bc551:228 Bilibili Evolved like 0 3
userscript.html?name=Bilibili-Evolved.user.js&id=d47ca7e9-1351-469b-bfca-a27a9d0bc551:228 Bilibili Evolved sys_msg 0 0
userscript.html?name=Bilibili-Evolved.user.js&id=d47ca7e9-1351-469b-bfca-a27a9d0bc551:228 Bilibili Evolved user_msg 0 0
2userscript.html?name=Bilibili-Evolved.user.js&id=d47ca7e9-1351-469b-bfca-a27a9d0bc551:228 Bilibili Evolved 网址参数清理 History API 拦截
```

### 附加截图

![image](https://github.com/user-attachments/assets/a944b7ff-8df4-4dea-9e40-f429daa4d2ea)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by liehuo0423** [comment]
![图片](https://github.com/user-attachments/assets/ca5a86b2-fea9-443c-a947-1c1d66785234)
![图片](https://github.com/user-attachments/assets/0c07e217-e15e-4a6e-8cd0-9912c79378c0)
如果着急想隐藏视频推荐的话，可以用**uBlock Origin**插件添加静态元素移除规则，等开发者bug修复好后可以把原先添加的规则删除

**Comment by MisakaMikoto9982** [comment]
确实诶，前两天还好好的，突然就失效了，还好有人反馈，感谢你为大伙发声

**Comment by sakurayoumeng** [comment]
同，不知是bug还是B站更新了

**Comment by CloudyEagle** [comment]
我之前是一个账号出这个问题，以为是睿B灰测，现在所有账号都这样了。

**Comment by CloudyEagle** [comment]
#4933

**Comment by CloudyEagle** [comment]
#4959

**Comment by AugustTuan** [comment]
我的也失效，我还以为是我电脑问题

**Comment by FallingSakura** [comment]
关注这个问题一周了，依然没有修复，插个眼

**Comment by myuv14** [comment]
我也碰到了这个问题，但我是用的油猴5.3.1版本和火狐浏览器

**Comment by QCM0220** [comment]
版本v2.9.4-52-g7c8d2d25a（10月24日18:00）仍存在此问题，望尽快修复。
