### ISSUE TITLE
显示网站当前在线人数

### ISSUE THREAD

**Issue by yaronzz** [the1812/Bilibili-Evolved#496]
**关于哪一项功能**
主页显示当前网站在线人数

**期望的效果**
将原本的“在线列表”按钮文本改成：在线列表 （当前在线人数：100000人）
![3](https://user-images.githubusercontent.com/15530958/80868445-2d097400-8ccd-11ea-8869-2f59b4383263.png)  
方法：
1. 接口 https://api.bilibili.com/x/web-interface/online
2. 获取json参数web_online

**脚本版本**
v1.10.20

**Comment by Coulomb-G** [comment]
请开启「简化首页」中的清爽模式

**Comment by yaronzz** [comment]
噢，原来已经做好了，不好意思打扰了
