### ISSUE TITLE
`自定义顶栏`的`历史`弹窗过滤器选项按钮 tooltip 与实际不符

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#4962]
### 对应功能

自定义顶栏
Commit: 9e5159f7d
内部名称: customNavbar

### 问题描述

[v2.6.0](https://github.com/the1812/Bilibili-Evolved/releases/tag/v2.6.0) 采纳了 #2729 的建议，`自定义顶栏`的`历史`弹窗过滤器改为只能选择`全部`或者单一类型，但过滤器选项的 tooltip 没跟着改，导致选中`全部`和某一类型时选项按钮 tooltip 仍为`不显示xx`，未被选中时仍为`显示xx`。
https://github.com/the1812/Bilibili-Evolved/blob/77ada2305f3a4fba1c63dbe19cf08914cc787f38/registry/lib/components/style/custom-navbar/history/NavbarHistory.vue#L29

建议某一类型（除`全部`外）选项按钮选中和未被选中时 tooltip 都改为`只显示xx`，`全部`选项按钮的 tooltip 就一直是`显示全部`。

### 脚本版本

v2.9.3-90-g527e4f69d

### 脚本管理器及版本

暴力猴 v2.26.0

### 浏览器及版本

Microsoft Edge 版本 129.0.2792.89 (正式版本) (64 位)

### 播放器版本

不相关

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![image](https://github.com/user-attachments/assets/0d1b9cc8-3d2d-474e-b487-1db2e3b7fee3)
![image](https://github.com/user-attachments/assets/5de62941-fc95-42f3-ae3a-6e9b223a9355)
![image](https://github.com/user-attachments/assets/2d4512eb-323d-44a4-801f-bbf613bfc123)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
改成 Radio 的形态后, 其实这个 title 没有什么用了

**Comment by Geeyun-JY3** [comment]
删除也行，省事。
