### ISSUE TITLE
“简化直播间”部分失效

### ISSUE THREAD

**Issue by KuiPer-LTW** [the1812/Bilibili-Evolved#4974]
### 对应功能

如图，礼物栏
![1](https://github.com/user-attachments/assets/08a6ddb3-e96d-4e6a-a9a6-b265f97d69a2)

### 问题描述

最新版的油猴没问题，我浏览器最高只能装V4.20
之前一直没事的，猜测又双叒叕是因为灰测

### 脚本版本

v2.9.3-46-g9e5159f7d

### 脚本管理器及版本

Tampermonkey beta v4.20.6187

### 浏览器及版本

QQ浏览器11.9

### 播放器版本

4.8.48-86c1d4e8

### 播放策略

默认

### 错误信息

```Shell
截图
```

### 附加截图

![2](https://github.com/user-attachments/assets/de172806-d07a-4d72-aaee-bf8c302413f7)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by KuiPer-LTW** [comment]
补充，有时会出现礼物栏和排行榜一起消失的情况
这俩块区域似乎被绑定了
![1](https://github.com/user-attachments/assets/d445ff56-7ca2-4a51-948f-a338ab6ea86c)

**Comment by the1812** [comment]
#4968
