### ISSUE TITLE
动态卡片的菜单项中没有已经安装的动态图片导出功能选项

### ISSUE THREAD

**Issue by AyanamiSho** [the1812/Bilibili-Evolved#4976]
### 对应功能

已经安装了动态图片导出插件 但是点击动态右侧的三个点 弹出的框里没有动态图片导出按钮

![image](https://github.com/user-attachments/assets/86ee2934-a83f-401b-bc1d-a07ca3932463)

### 问题描述

发现问题后查看控制台报错如下
![image](https://github.com/user-attachments/assets/50276d92-3a62-40f6-8fce-5ec39eb93a4f)

排查后发现是因为今天b站又把动态又更新了 之前的 bili-dyn-more__menu 完全没了 改成了
![image](https://github.com/user-attachments/assets/56b6838b-9bd3-4ad5-8c8f-6fa5991cda1c)

导致 src/components/feeds/api/index.ts文件中的 addMenuItem 这个函数因为 '.more-panel, .bili-dyn-more__menu, .opus-more__menu', 都找不到了 直接报错 more panel not found  导致动态图片导出这个功能没能添加进菜单里 

看插件更新日志今天正式版本才解决之前提的图片导出功能问题，结果b站这动态马上又改，实在是有点离谱。。。

### 脚本版本

v2.9.4-52-g7c8d2d25a

### 脚本管理器及版本

Tampermonkey  v5.1.1

### 浏览器及版本

chrome 126.0.6478.127

### 播放器版本

4.8.49

### 播放策略

默认

### 错误信息

```Shell
如下图
```

### 附加截图

![image](https://github.com/user-attachments/assets/ed14e65d-ab49-47b3-b05c-3a78964ce70d)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by yjt123789** [comment]
+1
