### ISSUE TITLE
能不能修复一下在Microsoft edge上打开乱码的情况？

### ISSUE THREAD

**Issue by SKDDJ** [the1812/Bilibili-Evolved#498]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
请使用前先阅读readme,其中有兼容性说明
支持最新版 Chrome, Edge (Chromium 内核), Firefox, Safari, 不保证脚本能在"套壳类浏览器"或者较长时间没更新的浏览器中完美运行.
UWP 版 Edge 已经不再支持了(就是 Windows 10 自带的那个), 请使用以上列出的浏览器, 或换用 Chromium 内核的 Edge.

**Comment by SKDDJ** [comment]
ok
