### ISSUE TITLE
Win11专业版，开启Bilibili Evolved以后，Bilibili Evolved完全失效。。。

### ISSUE THREAD

**Issue by Meloetta-Nahida** [the1812/Bilibili-Evolved#4985]
### 对应功能

Bilibili开启以后，完全失效，进入B站网页版，【功能】&【设置】小图标完全不显示

### 问题描述

我在篡改猴里安装了、开启了Bilibili Evolved最新版，使用Edge浏览器浏览Bilibili网页版，左侧的Bilibili Evolved【功能】&【设置】小图标就是不显示（正式版+preview版），导致我无法使用Bilibili Evolved。我尝试使用谷歌浏览器重复这个操作进行测试，还是如此，希望Bilibili Evolved的作者尽快解决这个bug。。。

PS：我的系统是Win11(专业版）X64bit

### 脚本版本

V2.9.4

### 脚本管理器及版本

Tampermonkey V5.3.2

### 浏览器及版本

Edge 130.0.2849.56 (正式版本) (64 位)+谷歌浏览器 130.0.6723.70（正式版本）（64 位）

### 播放器版本

无关播放器

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![Bilibili Evolved2](https://github.com/user-attachments/assets/53182590-236e-4ce4-a4d9-ae7e6cb12415)

![Bilibili Evolved1](https://github.com/user-attachments/assets/7c5a8013-0d30-4f59-bfb0-38d3684c8c84)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by AyanamiSho** [comment]
把chrome插件管理的开发者模式打开试试

**Comment by Louis-Has** [comment]
我也是，只能临时退回V2.9.3

**Comment by Meloetta-Nahida** [comment]
> 你不是第一个，也不会是最后一个：#4476 而且这大概率和你的 Windows 版本也没什么关系。
> 
> 还是先排查一下其他脚本和扩展吧，比如你截图中首页左下角的齿轮图标是什么脚本或扩展的？

我在帖子里忘了说了，我之前就把我油猴扩展里的脚本都关了，只开启了Bilibili Evolved，结果，访问B站网页版，【功能】&【设置】还是不见踪影，那应该可以排查掉是油猴脚本冲突的原因了。。。

**Comment by Geeyun-JY3** [comment]
一样的，在 #4476 及相关 issue 你能看到有的是人也是这样加载不出来。
没必要开新 issue，集中到那边讨论就行了。

**Comment by Malus-Mill** [comment]
表示用预览版可以使用

**Comment by apricotoil** [comment]
win11专业工作站版，出现了同样情况。参考部分回答的建议，打开了chrome的扩展开发者模式，重新安装了预览版，就可以正常使用了

**Comment by rikukiix** [comment]
https://www.tampermonkey.net/faq.php#Q209

**Comment by Meloetta-Nahida** [comment]
> 表示用预览版可以使用

Bilibili预览版，我打开了Edge扩展的开发人员模式，重装了Bilibili EvolveV2.9.4预览版。可是，开启Bilibili Evolved后，打开B站网页版，还是老样子，而且B站网页版的顶部也不正常了。。。

![Bilibili Evolved3](https://github.com/user-attachments/assets/bf2b87a5-fd83-42a3-95cc-b860e409bd3d)

**Comment by Meloetta-Nahida** [comment]
实在不行的话，我就只有选择删除Bilibili EvolvedV2.9.4这个脚本了。。。

**Comment by AyanamiSho** [comment]
建议离线安装篡改猴老版本，比如这个 然后开启chrome扩展开发模式。之后不管是预览版还是稳定版的脚本应该都能正常工作。最新版的篡改猴和这个脚本的兼容性不太好 经常出问题

**Comment by Meloetta-Nahida** [comment]
> 你不是第一个，也不会是最后一个：#4476 而且这大概率和你的 Windows 版本也没什么关系。
> 
> 还是先排查一下其他脚本和扩展吧，比如你截图中首页左下角的齿轮图标是什么脚本或扩展的？

但是，使我感到很奇怪的是，Edge浏览器和谷歌浏览器，安装和开启了BilibiliEvolvedV2.9.4，访问B站网页版，【功能】&【设置】
不见踪影。但是我尝试使用123浏览器，安装和开启了BilibiliEvolvedV2.9.4，访问B站网页版，就一切正常。。。

![123浏览器 Bilibili Evolved](https://github.com/user-attachments/assets/c05ae3e0-9d8a-4904-842f-2b1f7ecb4804)

**Comment by zffon** [comment]
> 把chrome插件管理的开发者模式打开试试

It works！很神奇，以前从来没打开过，但现在不知道为什么不打开就不可用了

**Comment by Meloetta-Nahida** [comment]
> 把chrome插件管理的开发者模式打开试试

我Edge浏览器和Chrome浏览器的扩展开发人员模式一直是打开的状态。。。

**Comment by DUXING130** [comment]
大概率是Manifest V3造成的扩展无法加载

**Comment by Meloetta-Nahida** [comment]
> 大概率是Manifest V3造成的扩展无法加载



> 你不是第一个，也不会是最后一个：#4476 而且这大概率和你的 Windows 版本也没什么关系。
> 
> 还是先排查一下其他脚本和扩展吧，比如你截图中首页左下角的齿轮图标是什么脚本或扩展的？

我将篡改猴从Edge浏览器里删除，重装篡改猴最新版本，然后只装了Bilibili Evolved最新版本，访问B站网页版进行测试，这种情况下，Bilibili Evolved竟然出现了【功能】&【设置】小图标。。。

**Comment by Meloetta-Nahida** [comment]
> 你不是第一个，也不会是最后一个：#4476 而且这大概率和你的 Windows 版本也没什么关系。
> 
> 还是先排查一下其他脚本和扩展吧，比如你截图中首页左下角的齿轮图标是什么脚本或扩展的？

我将篡改猴从Edge浏览器里删除，重装篡改猴最新版本，然后只装了Bilibili Evolved最新版本，访问B站网页版进行测试，这种情况下，Bilibili Evolved【功能】&【设置】小图标竟然申请的出现了。。。

![Bilibili Evolved4](https://github.com/user-attachments/assets/79a19018-83b6-4d22-997e-9b361d1e7270)

**Comment by Meloetta-Nahida** [comment]
> 你不是第一个，也不会是最后一个：#4476 而且这大概率和你的 Windows 版本也没什么关系。
> 
> 还是先排查一下其他脚本和扩展吧，比如你截图中首页左下角的齿轮图标是什么脚本或扩展的？

我这次将篡改猴扩展从Edge浏览器、Chrome浏览器、123浏览器里删除，然后重装篡改猴扩展。之后，我率先安装了Bilibili EvolvedV2.9.4正式版和预览版，然后再将我的其他篡改猴脚本一键导入篡改猴扩展，访问B站网页版。Bilibili Evolved 的【功能】&【设置】小图标神奇的出现在了B站网页版左侧！！！

Edge浏览器访问B站网页版的截图：

![Bilibili Evolved4](https://github.com/user-attachments/assets/c3c0667f-e2ae-4c21-a2fb-4f9d5a257345)

Chrome浏览器访问B站网页版的截图：

![Bilibili Evolved5](https://github.com/user-attachments/assets/362d405b-972b-48a1-9e38-5f25c6c28aea)

123浏览器访问B站网页版的截图：

![Bilibili Evolved6](https://github.com/user-attachments/assets/d706e634-ca11-45ad-aef5-cfe4beff3aec)

**Comment by Meloetta-Nahida** [comment]
> 你不是第一个，也不会是最后一个：#4476 而且这大概率和你的 Windows 版本也没什么关系。
> 
> 还是先排查一下其他脚本和扩展吧，比如你截图中首页左下角的齿轮图标是什么脚本或扩展的？

我那张截图里左下角的齿轮，是这个篡改猴脚本（具体见截图）

![Bilibili Evolved7](https://github.com/user-attachments/assets/33fbeb5d-bb26-4747-8872-67d3d7d25a38)

**Comment by h3nrywuuuu** [comment]
在edges拓展里启用开发者模式，刷新之后重新打开b站，亲测可解决！

**Comment by re-shi** [comment]
可以换个插件试试，我用篡改猴也不行，用暴力猴就可以了
