### ISSUE TITLE
关于加强版宽屏的一个我没解决的小问题

### ISSUE THREAD

**Issue by SpoonerCake** [the1812/Bilibili-Evolved#499]
看到大佬发了代码后，自己折腾折腾，用abp把顶栏和弹幕发送栏都屏蔽掉了，滚动栏也调没，然后把参数改成了如下这样，但是还是有一小部分空白区域，我的浏览器缩放是125%，调到100时也是有这样一小块，请问如何调参数能占满全屏幕呢
bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `.player-mode-widescreen #app {
    position: relative !important;
}
.player-mode-widescreen #bofqi {
    width: 100vw !important;
    height: calc(100vh - 10px - 10px) !important;
    position: absolute !important;
    left: 0vw !important;
}
.player-mode-widescreen .player-wrap,
.player-mode-widescreen .danmaku-box {
    height: calc(100vh - 10px - 10px) !important;
}`, displayName: '加强版宽屏', mode: 'important'})
![QQ图片20200503193529](https://user-images.githubusercontent.com/49234232/80913250-d4da7c80-8d75-11ea-9544-11a50dcea6ee.png)

**Comment by the1812** [comment]
上面那段我是把整个往上移一点盖住, 这段也包括了隐藏弹幕发送栏和顶栏(`display: none !important;`的部分)
```js
bilibiliEvolved.installStyle({name: 'widescreenPlus', style: `.player-mode-widescreen #app {
    position: relative !important;
}
.player-mode-widescreen #bofqi {
    width: 100vw !important;
    height: calc(100vh) !important;
    position: absolute !important;
    left: 0 !important;
}
.player-mode-widescreen .player-wrap,
.player-mode-widescreen .danmaku-box {
    height: calc(100vh) !important;
}
.player-mode-widescreen .custom-navbar,
.player-mode-widescreen .bilibili-player-video-bottom-area {
    display: none !important;
}
.player-mode-widescreen {
    scrollbar-width: none !important;   
}
.player-mode-widescreen #app {
    transform: translateY(-70px) !important;
}
.player-mode-widescreen::-webkit-scrollbar {
    height: 0 !important;
    width: 0 !important;
}`, displayName: '加强版宽屏', mode: 'important'})
```
