### ISSUE TITLE
在线仓库对话框中组件 / 插件的提示气泡中的子级标题文本的颜色应总是白的

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#4995]
猛地发现在线仓库对话框中组件 / 插件的提示气泡中的子级标题文本的颜色在非夜间模式是黑的，应该和其他正文文本一样一直是白的吧。
![image](https://user-images.githubusercontent.com/49396421/204069411-27e630a3-7a50-4257-937e-02f17f096065.png)

_Originally posted by @Geeyun-JY3 in https://github.com/the1812/Bilibili-Evolved/issues/3759#issuecomment-1327965909_

2024-10-31 编辑：今天发现和夜间模式无关，现状是子级标题文本的颜色总是黑的。

**Comment by the1812** [comment]
是在哪个页面, 应该是样式被那个页面的给覆盖了

**Comment by Geeyun-JY3** [comment]
没测太多页面，目前实测视频播放页、个人空间页有这问题。
另外补充一点，设置面板的组件详情页的描述和也有一样的问题。
