### ISSUE TITLE
旧版播放器设置失效

### ISSUE THREAD

**Issue by RainSola** [the1812/Bilibili-Evolved#50]
设置里面选择旧版播放器无效，仍旧是新版，暂时只能禁用插件了，等待修复。
另外建议给播放器设置加一个开关功能吧，以免像这次一样要用旧版只能禁用插件。
总之，等你有空再完善，先谢谢了！

**Comment by the1812** [comment]
抱歉拖了这么久, [1.7.0](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.7.0)中已经更新可以切换了

**Comment by RainSola** [comment]
> 
> 
> 抱歉拖了这么久, [1.7.0](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.7.0)中已经更新可以切换了

测试OK，感谢！

**Comment by RainSola** [comment]
> 
> 
> 抱歉拖了这么久, [1.7.0](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.7.0)中已经更新可以切换了

测试OK，感谢！

> 
> 
> 抱歉拖了这么久, [1.7.0](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.7.0)中已经更新可以切换了

wait,我刚刚随便打开一个视频测试，旧版是旧版，但是播放等数据还有分P等列表都读不出，关了插件就可以。同样，用这插件换成新版也没事，就是旧版读不出。

**Comment by the1812** [comment]
刚才试了一下, 是搜索栏置顶导致的, 你先关了吧
