### ISSUE TITLE
B站又加了新的广告种类

### ISSUE THREAD

**Issue by DUXING130** [the1812/Bilibili-Evolved#5001]
### 对应功能

删除广告7c8d2d25a

### 问题描述

主界面右下角会出现遮盖横幅

### 脚本版本

2.9.4

### 脚本管理器及版本

Tampermonkey5.1.1

### 浏览器及版本

Edge 130

### 播放器版本

4.92

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![image](https://github.com/user-attachments/assets/5ae0bf5e-f68e-44f6-8850-b48a4e66fffd)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by DUXING130** [comment]
<div data-v-2ce37bb8="" class="palette-button-adcard is-bottom" style="left: 832px;"><picture data-v-2ce37bb8="" class="v-img ad-img"><source srcset="//i0.hdslb.com/bfs/activity-plat/static/20241104/8298d6b0f8f547347b097f0ce035e59c/zaL6eO4fW0.jpg@800w_512h.avif" type="image/avif"><source srcset="//i0.hdslb.com/bfs/activity-plat/static/20241104/8298d6b0f8f547347b097f0ce035e59c/zaL6eO4fW0.jpg@800w_512h.webp" type="image/webp"><img src="//i0.hdslb.com/bfs/activity-plat/static/20241104/8298d6b0f8f547347b097f0ce035e59c/zaL6eO4fW0.jpg@800w_512h" alt="三国谋定天下" loading="eager" onload="" onerror="typeof window.imgOnError === 'function' &amp;&amp; window.imgOnError(this)"></picture><svg data-v-2ce37bb8="" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24" width="24" height="24" class="exit-icon" fill="currentColor"><path d="M4.75075 4.75352C5.14127 4.36299 5.77444 4.36299 6.16496 4.75352L11.9984 10.587L17.8335 4.75188C18.224 4.36135 18.8572 4.36135 19.2477 4.75188C19.6383 5.1424 19.6383 5.77557 19.2477 6.16609L13.4126 12.0012L19.2464 17.835C19.637 18.2255 19.637 18.8587 19.2464 19.2492C18.8559 19.6397 18.2227 19.6397 17.8322 19.2492L11.9984 13.4154L6.16626 19.2476C5.77573 19.6381 5.14257 19.6381 4.75204 19.2476C4.36152 18.857 4.36152 18.2239 4.75204 17.8334L10.5842 12.0012L4.75075 6.16773C4.36022 5.77721 4.36022 5.14404 4.75075 4.75352z" fill="currentColor"></path></svg><div data-v-2ce37bb8="" class="detail-button"> 查看详情 </div></div>
![image](https://github.com/user-attachments/assets/9137753b-f3ef-4f8f-ab53-8c4feedf9edb)

**Comment by nostphi** [comment]
这个正方形图标还去除不了吗暂时
