### ISSUE TITLE
'简化首页'后顶栏按钮缺失

### ISSUE THREAD

**Issue by yaronzz** [the1812/Bilibili-Evolved#501]
**关于哪一项功能**
'简化首页'

**问题描述**
页面：主页面
重现步骤：勾上‘简化首页’-清爽模式，不使用自定义顶栏，设置图片如下。
问题：右上方的除了投稿之外，其他按钮不见了，网页多刷新几遍就出来了，图片如下。

**脚本版本**
v1.10.20

**浏览器版本**
Chrome 81

**错误信息**
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/international-home/css/international-home.1.28c1a657ae7aba12fe3218f210a1362ab232c7f6.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/international-home/css/international-home.0.28c1a657ae7aba12fe3218f210a1362ab232c7f6.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**附加截图**
![1](https://user-images.githubusercontent.com/15530958/80940053-1c621680-8e11-11ea-86d9-debf18764b36.png)
![2](https://user-images.githubusercontent.com/15530958/80940562-c0988d00-8e12-11ea-8bfd-2bbfe7b253b8.png)

**Comment by the1812** [comment]
简化首页会尝试阻止b站原有脚本的运行以提高速度, 顶栏那一块消失就是因为这样
可以开自定义顶栏, 或者等我下次修一下这个问题
