### ISSUE TITLE
视频播放时熄灯功能，暂停视频后没有自动解除熄灯

### ISSUE THREAD

**Issue by BAIDI-coder** [the1812/Bilibili-Evolved#502]
**关于哪一项功能**
视频播放时熄灯的功能

**问题描述**

第一次播放视频后自动熄灯，但是暂停播放后熄灯没有自动解除导致其他地方不能点，影响使用。

**脚本版本**

1.10.20版

**浏览器版本**

chrome 80

**错误信息**

**附加截图**

**Comment by AllGetHub** [comment]
挺实用的功能，不知道什么时候能出来
