### ISSUE TITLE
Crashes with OneKeyVip Script

### ISSUE THREAD

**Issue by wadawada** [the1812/Bilibili-Evolved#503]
**关于哪一项功能**
Player not shown correctly/hidden

**问题描述**
Bilibili-Evolved/OneKeyVip crashes when both script are installed and running on the same page
https://github.com/maxzhang666/OneKeyVip
https://www.bilibili.com/video/BV1r7411e73T
Player will be hidden when both scripts are loaded

**脚本版本**
1.10.20

**浏览器版本**
Version 84.0.4129.0 (Official Build) canary (64-bit)

**Comment by the1812** [comment]
**If any content inside player changed before player fully loaded, the player will be hidden. (A protective behavior of Vue.js)**

I'm sure all features of my script follow this rule.
But my script contains so many features that will slow down page loading. When OneKeyVip modified some content, the player is not fully loaded and will cause this problem.
Please contact OneKeyVip to fix this problem.

Related issues (same problem, different scripts): #379, #254
