### ISSUE TITLE
自定义顶栏可否增加单独的国创入口？

### ISSUE THREAD

**Issue by MonicaWQY** [the1812/Bilibili-Evolved#5045]
### 对应功能

`自定义顶栏`、`直播间首页静音`Commit: 7e5167c8b

### 问题描述

1.`自定义顶栏`可否增加单独的国创入口？就像`番剧`入口一样。
![image](https://github.com/user-attachments/assets/559ae9f7-1d96-48bc-bd4c-e937e28d80b4)

2.`直播间首页静音` 组件安装了不开启也会生效，这个问题我之前提过#4459，当时没大明白你的意思，也没明白为什么你那边会跟我的不一样，抱歉，这次我录了视频(￣▽￣") 
视频附件画质被压缩了，怕你看不清，我描述一下，具体就是我Tempermonkey里面只启用了只启用了Bilibili-Evolved ，安装了`直播间首页静音` 组件，但是未开启，进直播间首页也会被静音，手动打开声音再刷新网页还是会被静音，我把Tempermonkey禁用之后再刷新网页，就不会被静音了。
你在#4459里提到“会记住上次的选择, 如果有声音就静音以下, 再刷新就都静音了”，我这边试了很多次结果是没有记住，我静音之后再刷新也还是会有声音。因为附件限制10M以内，所以我没录进去。
总结一下就是只要安装了`直播间首页静音` 组件，不启用，进直播间首页也会被静音，禁用了Bilibili-Evolved之后，不论是否手动选择静音，每次进直播间首页就都是有声音的。
https://github.com/user-attachments/assets/0a84614f-7787-4da3-9325-dd7bd9da6aa2

3.另外#4459里提到的`禁止滚轮调音量`一直不生效的问题，我发现是和扩展浮图秀有冲突，启用浮图秀就会导致`禁止滚轮调音量`组件失效。

### 脚本版本

v2.9.5-61-g048e26a46

### 脚本管理器及版本

Tampermonkey v5.3.2

### 浏览器及版本

Edge131.0.2903.63 (正式版本)

### 播放器版本

4.9.6-410dbc94

### 播放策略

默认

### 错误信息

```Shell
直播间首页没有错误信息，视频播放页倒是有，不知道是不是跟`禁止滚轮调音量`有关。

userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:228  Bilibili Evolved TypeError: Cannot read properties of null (reading 'code')
    at k (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili-Evolved.user.js&id=a42cfc43-e568-46e0-9eae-931249c10a43:195:4070)
    at async a.created (eval at <anonymous> (eval at <anonymous> (:199:41061)), <anonymous>:1:1352)
```

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
1. 可以
2. 了解了, 确实存在未开启也执行的问题
3. 这应该是浮图秀的问题, 可以向浮图秀反馈

**Comment by Geeyun-JY3** [comment]
如果要加入单独的国创入口，要不干脆把所有版权内容的独立主页都加了吧：[电影](https://www.bilibili.com/movie/)、[电视剧](https://www.bilibili.com/tv/)、[综艺](https://www.bilibili.com/variety/)、[纪录片](https://www.bilibili.com/documentary/)
哦顺便一提还有一个全身上下都是就设计的[放映厅](https://www.bilibili.com/cinema/)，就是不知道有没有必要，还有也不知道破站以后会不会在上述版权内容已有了各自的独立主页后把这个老东西给砍了。
