### ISSUE TITLE
`自定义顶栏` 开启时，个人空间页面原版顶栏未完全隐藏 again

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#5050]
### 对应功能

自定义顶栏
Commit: 7e5167c8b
内部名称: customNavbar

### 问题描述

`自定义顶栏`开启时，个人空间页面原版顶栏未完全隐藏。

不确定 #4079 没修好还是修好了破站那边又改了，就另开 issue 了。

### 脚本版本

v2.9.5-104-g576fd06d4

### 脚本管理器及版本

暴力猴 v2.28.0

### 浏览器及版本

Firefox 132.0.2 (64 位)
Microsoft Edge 131.0.2903.63 (正式版本) (64 位)

### 播放器版本

不相关

### 播放策略

默认

### 错误信息

```Shell
无
```

### 附加截图

![image](https://github.com/user-attachments/assets/74c9943e-4135-4ebe-9292-f1830f56f2f9)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
> 所以这算不算是 https://github.com/the1812/Bilibili-Evolved/discussions/3036 在个人空间的体现？

算是吧

**Comment by the1812** [comment]
新版空间应该没有这种问题了

**Comment by Geeyun-JY3** [comment]
可是我还的常用账号没被灰度到新版空间，而且我感觉新版空间还要测试蛮久的_(:з」∠)_

**Comment by the1812** [comment]
清空 cookie 重新登录试试, 我是这样进入新版空间的

**Comment by tansongqi22** [comment]
你好，请问现在的自定义顶栏还有元素隐藏的功能吗

**Comment by tansongqi22** [comment]
我知道了，没有登录是没有这个功能的，只有边缘间距，登录后才有元素呈现，也就是可以调节顶栏中漫画，番剧等等之间的位置以及存在与否的功能，不过登录上就能出现，也没必要新开个issue处理这个问题了

Geeyun-JY3 ***@***.***> 於 2025年8月23日週六 下午10:48寫道：
