### ISSUE TITLE
夜间模式，未适配视频下方的Ai小助手，字体灰色，显示效果不佳。

### ISSUE THREAD

**Issue by Den-ze** [the1812/Bilibili-Evolved#5058]
### 对应功能

Commit: 7e5167c8b
内部名称: darkMode

### 问题描述

如标题所写的一样
开启夜间模式之后，与视频下方的Ai小助手有bug，字体灰色，显示效果不佳。

### 脚本版本

v2.9.5-104-g576fd06d4

### 脚本管理器及版本

v5.3.6216

### 浏览器及版本

Microsoft Edge 版本 131.0.2903.70 (正式版本) (64 位)

### 播放器版本

4.9.7-22f1ee4a

### 播放策略

默认

### 错误信息

```Shell
在下不太懂，应该不算是错误信息吧
```

### 附加截图

如下图（不知能否显示）我把广告内容马了。
![image](https://github.com/user-attachments/assets/6c01df69-4d9a-4c13-a7c9-77f985606e0b)
![image](https://github.com/user-attachments/assets/88be2aac-2809-44ed-bc31-a66795e5f83f)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
我觉得可以合并至 #4482，你也在那边评论了，反正也还没关（

（图有什么好怕显示不出来的）

**Comment by Den-ze** [comment]
哈哈，小白初次提交issue，麻烦合并！那边有我拙劣调整的css

**Comment by Geeyun-JY3** [comment]
你可以自己关闭，让作者来关最多也就是打个 label。
