### ISSUE TITLE
在使用“下载视频 - IDM 输出支持”插件时输出音频文件名不正确

### ISSUE THREAD

**Issue by Seameee** [the1812/Bilibili-Evolved#5062]
### 对应功能

下载视频 - IDM 输出支持(downloadVideo.outputs.idm)

### 问题描述

在使用“下载视频 - IDM 输出支持”插件批量下载多p视频时，输出音频文件名被修改为类似`1222980447-1-30280.mp4`的格式，下载参数如下：
![image](https://github.com/user-attachments/assets/5ec22215-b6ae-40dc-a5df-d8b8d16df7b4)
被修改后的效果：
![image](https://github.com/user-attachments/assets/228803fc-5d09-498d-aefb-3f052e866b1d)

### 脚本版本

Bilibili Evolved (Preview) v2.9.5-preview-156-g54b44b92d

### 脚本管理器及版本

Tampermonkey v5.3.2

### 浏览器及版本

Microsoft Edge 版本 132.0.2957.11 (正式版本) dev (64 位)

### 播放器版本

4.9.8-2a5fba08

### 播放策略

默认

### 错误信息

```Shell
见下方log文件
```

### 附加截图

[www.bilibili.com-1733288275380.log](https://github.com/user-attachments/files/18002794/www.bilibili.com-1733288275380.log)
[附带ef2文件](https://github.com/user-attachments/files/18002808/Pi.mc.p0.23.ef2.txt)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by the1812** [comment]
IDM 原生不支持保留文件名, 可以考虑配合其他工具, 例如 https://github.com/MotooriKashin/ef2

**Comment by Seameee** [comment]
> IDM 原生不支持保留文件名, 可以考虑配合其他工具, 例如 https://github.com/MotooriKashin/ef2
已经是使用ef2工具导入的了，但依然在下载时会被重命名为类似的格式，这个是idm的问题么，如果是那我就先关issue了

**Comment by the1812** [comment]
可能是工具没适配音频文件, 可以尝试用 aria2 之类的方式

**Comment by Seameee** [comment]
> 可能是工具没适配音频文件, 可以尝试用 aria2 之类的方式

好的感谢
