### ISSUE TITLE
关于顶栏布局设置中的"稍后再看","个人信息"以及视频播放页的分辨率问题

### ISSUE THREAD

**Issue by Pangu0210** [the1812/Bilibili-Evolved#5084]
### 对应功能

无

### 问题描述

顶栏设置中的"稍后再看"消失了,"个人信息"的话,已经登录账号了却显示没有登录的状态以及视频播放页的视频分辨率都是自动,设置1080P完了之后再打开其他视频,分辨率还是自动

### 脚本版本

v2.9.5-preview-156-g54b44b92d

### 脚本管理器及版本

Tampermonkey v5.3.3

### 浏览器及版本

Edge 131.0.2903.112

### 播放器版本

4.9.12-a7503831

### 播放策略

默认

### 错误信息

```Shell
userscript.html?name=Bilibili-Evolved-Preview.user.js&id=dfbb3245-6b64-4909-bc93-99cdec00ea0f:228  Bilibili Evolved TypeError: Cannot read properties of null (reading 'code')
    at k (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili-Evolved-Preview.user.js&id=dfbb3245-6b64-4909-bc93-99cdec00ea0f:195:4070)
    at async a.created (eval at <anonymous> (eval at <anonymous> (:199:41058)), <anonymous>:1:1352)
```

### 附加截图

![PixPin_2024-12-26_12-59-49](https://github.com/user-attachments/assets/78d16789-bbb8-4525-9712-acd7d74afa23)
![PixPin_2024-12-26_13-03-03](https://github.com/user-attachments/assets/59a6ef37-b19d-41eb-82ce-a32b32dae6cb)

### 致遇到了相同问题准备回复的人

**太长不看**：
1、遇到了相同的问题：**请用左下角的 reaction 点赞**
2、实时关注该 Issue 的后续进展：**请用 Issue 页上的 Subscribe 功能**（在 PC 端按钮通常位于页面右侧）。
**_请您回复前务必确认您有在本 Issue 之外补充了其它相关信息（比如 Log）再行回复以免对他人造成不必要的困扰_**
<details>
  <summary>完整版</summary>
    由于每个 Issue 甚至整个项目都是可以订阅通知的, 对于已经有人汇报过的 Bug, 如果您也遇到了并且没有其他信息要补充, 可以直接在左下点个赞表示 +1, 不要再去新增评论。想关注后续的可以用 Subscribe，Subscribe 之后该 Issue 如果有变动都可以收到通知，如果不想被回复打扰可以使用更加进阶的 Customize 功能，勾选 "Closed" & "Reopened"。Closed 通常代表该 Issue 已被解决，极少数情况下的 Reopened 代表该 Issue 的问题重新出现。如果您新增了无意义评论，因为 Issue 这个 bug tracker 与<a href="https://www.zhihu.com/question/23757640">邮件列表</a>类似，订阅某个 Issue 的用户会在每次这个 Issue 有新的动态时收到一封新的提醒邮件。也就是说，在 Issue 中的一个不能提供新的信息的评论，相当于给所有订阅这个 Issue 的用户发了一封垃圾邮件（spam）。尤其项目的维护者也是订阅者中的一员，太多垃圾邮件会对维护者带来很多不必要的困扰。发送垃圾邮件在开源社区通常是不那么受欢迎的行为。
</details>

**Comment by Geeyun-JY3** [comment]
自定义顶栏的问题或许可参考 #3866

视频分辨率是 b 站记忆的，Bilibili Evolved 没有相关功能。
