### ISSUE TITLE
视频下载地址无法用于potplayer添加链接播放

### ISSUE THREAD

**Issue by Tifa-i** [the1812/Bilibili-Evolved#509]
您好！我发现视频下载地址不能用于potplayer添加链接播放，请求您能加入获取视频真实播放地址功能，非常感谢！
![QQ截图20200507120346](https://user-images.githubusercontent.com/64943672/81253428-25462880-905b-11ea-845d-e36959b1939b.png)

**Comment by the1812** [comment]
没有什么真实地址的 请先下载完了再播放

**Comment by Tifa-i** [comment]
> 没有什么真实地址的请先下载完了再播放

我也不太懂额。。大佬您看看这个网站吧https://www.bilibili.com/video/av455707099，它解析后生产的MP4地址，可以用于添加到本地播放器播放，我发现这个网站解析出来的地址和您的脚本解析出来的总是不一样

**Comment by Tifa-i** [comment]
> 没有什么真实地址的请先下载完了再播放

我也不太懂额。。大佬您看看这个网站吧 https://www.xbeibeix.com/bilibili/ ，它解析b站视频后生产的MP4地址，是可以用于添加到本地播放器播放的，不用下载，而且我发现这个网站解析出来的地址和您的脚本解析出来的总是不一样

**Comment by the1812** [comment]
那个网站解析的是MP4地址
我的脚本只支持FLV和DASH格式
需要在PotPlayer中播放的话请用那个网站吧
