### ISSUE TITLE
下载下来的视频花屏

### ISSUE THREAD

**Issue by cottonty** [the1812/Bilibili-Evolved#51]
下载

下载会员的1080+清晰度视频花屏。其他清晰度没试过
https://www.bilibili.com/video/av33373296/?p=1

正式版1.6.25和预览版1.6.31都一样的问题

Chrome 71.0.3578.98

**Comment by the1812** [comment]
我下载下来播放是正常的, 花屏可能是因为播放器/解码器的问题, 你换个播放器试试吧
