### ISSUE TITLE
主页简化（清爽）功能建议

### ISSUE THREAD

**Issue by kulocora** [the1812/Bilibili-Evolved#512]
**关于哪一项功能**
主页简化 > 清爽

**期望的效果**
1. 右上角热门显示 8 个视频

2. 「活动」这个设计不太好，图片没有和上面的字对齐，有点怪
![图片](https://user-images.githubusercontent.com/12947678/81494776-f7bce180-92dd-11ea-9ff4-824c8cee5823.png)
改成这样可以吗...
![图片](https://user-images.githubusercontent.com/12947678/81494988-78301200-92df-11ea-8834-db9cd5cfd3a0.png)

**脚本版本**
652.04 Offline

**Comment by the1812** [comment]
热门可以触摸版/触摸屏横向滚动, 鼠标按住shift滚动

**Comment by FeiLZX3Km** [comment]
希望此【活动】卡片能够支持直接关闭/删除。因为感觉内容与自己想要了解的内容关系不大。
[截图](https://user-images.githubusercontent.com/12947678/81494776-f7bce180-92dd-11ea-9ff4-824c8cee5823.png)

因为议题相同，所以在此建议下回复以提出新的需求，不过不知道开发者能否收到相关信息？收不到过两天再看看另开新的issue。

**Comment by the1812** [comment]
预览版中做了支持的, 等发布就行
