### ISSUE TITLE
"自动隐藏侧栏"不方便操作

### ISSUE THREAD

**Issue by liquidhelium** [the1812/Bilibili-Evolved#513]
**关于哪一项功能**
新添加的"自动隐藏侧栏"功能

**期望的效果**
只要将鼠标放置在侧边周围即可显示侧栏(增加检测范围,比如将高度扩展到100%或50%或其他而不是"auto";现在的元素太小,经常找不到准确位置)

**脚本版本**
1.10.20

**Comment by the1812** [comment]
可以加个边缘检测, 鼠标移到边缘时也能显示侧栏, 不然扩到100%有时候会挡住别的东西
