### ISSUE TITLE
关于使用该脚本后出现视频暂停后再点开会出现一直转圈圈的情况

### ISSUE THREAD

**Issue by Newbie595** [the1812/Bilibili-Evolved#516]
前辈，我录有这个情况的视频，更新后会出现这样的情况em，不知道是脚本问题 还是浏览器问题，如果你们不会出现这种情况的话，记得说一下，那我就去重装谷歌浏览器了哈哈

**Comment by Coulomb-G** [comment]
请按照issue模板,提供详细的报错信息以及脚本和浏览器版本

**Comment by the1812** [comment]
视频看一半暂停 然后过很久再播放是会转圈的 它要整个重新连接一次来继续播放
但是也仅仅是暂停了很久才会这样 一般没有这种情况

**Comment by Newbie595** [comment]
Google Chrome 已是最新版本
版本 81.0.4044.138（正式版本） （64 位）
我这边的有点玄幻，视频开启后，暂停时间大概二三十秒吧 然后取消暂停就一直转圈啦，有时候是暂停后立即点开 他也会出现转圈问题
