### ISSUE TITLE
aria下载功能对部分视频无法使用

### ISSUE THREAD

**Issue by lidh15** [the1812/Bilibili-Evolved#519]
使用aria下载时报403错误，信息如下：
05/11 13:33:50 [ERROR] CUID#130 - Download aborted. URI=http://upos-hz-mirrorakam.akamaized.net/upgcxcode/88/87/32758788/32758788-7-15.flv?e=ig8euxZM2rNcNbNj7zUVhoMg7buBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1589199535&gen=playurl&os=akam&oi=93809152&trid=43daeb24dd2745ec922d495058b7d644u&platform=pc&upsig=a3c8a6cce3e599cf88772abaee42c8fe&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1589199535~hmac=701ef4947fbbdd39ba0a80bd28d57e679f4d1b3d3860456d6aace244af4e37f5&mid=186841978&logo=80000000
Exception: [AbstractCommand.cc:351] errorCode=22 URI=http://upos-hz-mirrorakam.akamaized.net/upgcxcode/88/87/32758788/32758788-7-15.flv?e=ig8euxZM2rNcNbNj7zUVhoMg7buBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1589199535&gen=playurl&os=akam&oi=93809152&trid=43daeb24dd2745ec922d495058b7d644u&platform=pc&upsig=a3c8a6cce3e599cf88772abaee42c8fe&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1589199535~hmac=701ef4947fbbdd39ba0a80bd28d57e679f4d1b3d3860456d6aace244af4e37f5&mid=186841978&logo=80000000
  -> [HttpSkipResponseCommand.cc:240] errorCode=22 The response status is not successful. status=403
一共有三百个左右flv文件其中119个报错。

**Comment by the1812** [comment]
你下载花了多长时间?

**Comment by the1812** [comment]
每条链接都有时间限制的 超时了就403
今天获取的链接 明天下载肯定不行

**Comment by lidh15** [comment]
好的，我可以分P每次少下点，但是其实这个错误是我下载中一些部分没下载下来，然后又重来的时候报的错，一开始的错误是服务器EOF：
05/11 15:20:26 [ERROR] CUID#196 - Download aborted. URI=http://upos-hz-mirrorakam.akamaized.net/upgcxcode/40/55/32995540/32995540-6-15.flv?e=ig8euxZM2rNcNbNg7zUVhoMghbuBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1589213761&gen=playurl&os=akam&oi=93809152&trid=f75eb82bcdb545bfb5aefc014a045161u&platform=pc&upsig=d23d6123e55df0235fc197c1e2448d2b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1589213761~hmac=1f3087565e5bdbae967a36f547d30b95e951e38f9e515839b66ee57d8643f1bd&mid=186841978&logo=80000000
Exception: [DownloadCommand.cc:234] errorCode=1 Got EOF from the server.
这种错误是什么情况

**Comment by the1812** [comment]
EOF是被服务器切了  重新导出一次就行了  aria2会从中断处继续的

**Comment by lidh15** [comment]
重新导出之后重新下载基本上DL为0，没办法了
