### ISSUE TITLE
添加抓取视频真实地址的功能

### ISSUE THREAD

**Issue by Tifa-i** [the1812/Bilibili-Evolved#524]
抓取视频真实地址的功能
能够利用potplayer添加链接，进行本地播放

**Comment by the1812** [comment]
这和 #509 是一样的吧

**Comment by Tifa-i** [comment]
> 这和[＃509](https://github.com/the1812/Bilibili-Evolved/issues/509)是一样的吧

大佬您看看这个网站吧https://www.xbeibeix.com/bilibili/，它解析b站视频后生产的MP4地址，是可以用来添加到本地播放器播放的，不用下载，而且我发现这个网站解析出来的地址和您的脚本解析出来的总是不一样

**Comment by Tifa-i** [comment]
> 这和[＃509](https://github.com/the1812/Bilibili-Evolved/issues/509)是一样的吧

大佬您看看这个网站吧 https://www.xbeibeix.com/bilibili/ ，它解析b站视频后生产的MP4地址，是可以用来添加到本地播放器播放的，不用下载，而且我发现这个网站解析出来的地址和您的脚本解析出来的总是不一样

**Comment by the1812** [comment]
那就用这个网站吧
我没有生成MP4地址的办法
