### ISSUE TITLE
弹幕上限更改功能

### ISSUE THREAD

**Issue by SteveQian** [the1812/Bilibili-Evolved#525]
**关于弹幕上限更改功能的建议**

**期望的效果**
希望能增加弹幕池上限更改功能。
一部几个小时的电影只有最多8000左右的弹幕，感觉太少了。
我觉得可以加载历史弹幕，来增加弹幕池数量
另外就是在b站弹幕屏蔽设置生效之后，弹幕就剩下一丁点了。
也希望出个自动补全弹幕池的功能

**1.10.20**

**Comment by the1812** [comment]
除非b站开放这个 否则我加不了弹幕
