### ISSUE TITLE
视频下载里，单视频下载是否能支持4K

### ISSUE THREAD

**Issue by GraphaX** [the1812/Bilibili-Evolved#528]
**关于哪一项功能**
在视频下载功能里，对单视频下载希望能提供4K清晰度的选项或者下载链接

**期望的效果**
现在B站逐步开放了一些4K视频的资源上传，希望能适配4K清晰度的下载

**脚本版本**
1.10.20

**Comment by the1812** [comment]
不是本来就能4K吗

**Comment by GraphaX** [comment]
> 不是本来就能4K吗

感谢回复，单视频下载最高只支持到1080+ ,手动输入才可以选择4K
![image](https://user-images.githubusercontent.com/48665204/81762852-421da880-9500-11ea-8c21-2d615a16019a.png)

**Comment by the1812** [comment]
4K是DASH格式独有的 FLV没有4K

**Comment by GraphaX** [comment]
> 4K是DASH格式独有的FLV没有4K

原来是这样啊 受教了，谢谢开发大大！
