### ISSUE TITLE
Firefox 开启脚本后页面无法加载

### ISSUE THREAD

**Issue by kulocora** [the1812/Bilibili-Evolved#529]
**关于哪一项功能**
Firefox 77 有时无法加载页面，一片空白

**问题描述**

只有 Firefox 有这个问题，Chromium 内核无事，关闭脚本后页面正常加载。
已尝试各种运行时期，均不能解决。

**脚本版本**

离线版、离线预览版都能复现

**浏览器版本**

Firefox 77

**错误信息**

![图片](https://user-images.githubusercontent.com/12947678/81959761-8a44e400-9642-11ea-85da-3ac571db0953.png)

**附加截图**
![图片](https://user-images.githubusercontent.com/12947678/81958301-608abd80-9640-11ea-902d-014d2d3692e3.png)

**Comment by the1812** [comment]
是所有页面都不行吗? 还是某几个页面

**Comment by kulocora** [comment]
> 
> 
> 是所有页面都不行吗? 还是某几个页面

好像是 TamperMonkey 的问题，我把注入模式改成「即时」就不复现了
