### ISSUE TITLE
非大会员用户下载自己上传的高帧率视频

### ISSUE THREAD

**Issue by imThree** [the1812/Bilibili-Evolved#530]
**关于哪一项功能**
视频下载

**期望的效果**
下载**自己上传**到B站的视频，能不能提供1080P60帧，1080P+等选项？
我很久没有开大会员了，虽然不能看别人上传的高帧率视频，但是自己上传过的高帧率视频播放是没有问题的。
为了下载高帧率视频改用其他的插件还是比较麻烦的。
![TIM截图20200516175151](https://user-images.githubusercontent.com/4982919/82117470-a8295a80-97a2-11ea-8c29-501485e3f4c3.png)
不知道大会员下载别人传的视频有没有60P的选项，下载自己传的视频不应该没有。

大哥大姐（们）不妨可以考虑一下。

**脚本版本**
1.10.20

![滑稽](https://user-images.githubusercontent.com/4982919/82117521-09e9c480-97a3-11ea-95b2-3dd65658ea53.png)

**Comment by the1812** [comment]
这应该算个bug了
以前清晰度全部都是开放的, 只要你能播放, 就能下载. 但是总有非大会员想下载**别人传的**高帧视频, 报错了又觉得我脚本有问题, 于是我就直接把非大会员下清晰度的选项给削了
所以就没考虑到自身上传视频的情况, 或许还是开放所有清晰度比较好吧, 我改改错误提示就行了

**Comment by imThree** [comment]
回复的效率很高啊
看来从来少不了白嫖怪~
不知道能不能判断登录账号与发布视频UP主的UID是否一致，然后再给出下载选项。我不是程序员，详细的我也不是很懂。

**Comment by the1812** [comment]
我直接开放全部清晰度了, 白嫖的会报错
你可以用预览离线版提前试一下

**Comment by imThree** [comment]
刚才更新了正式版，可以正常下载，感谢。
![截图](https://user-images.githubusercontent.com/4982919/82752702-7c395500-9df2-11ea-99d1-4ac2861b271d.png)
