### ISSUE TITLE
关于同时打开数量很多个b站视频网页后，有一部分后打开的无法使用默认播放速度

### ISSUE THREAD

**Issue by flyingnight** [the1812/Bilibili-Evolved#531]
同时打开多个b站视频网页后（数量有几十个网页），再一个一个从第一个视频开始看，有一部分后开的网页中插件的默认网页全屏能生效，但是设定的播放速度失效了（我设定的速度是x1.25），每次开启都只默认网页全屏，但是速度是正常速度

**脚本版本**
正式版1.10.20 

**浏览器版本**
Microsoft Edge beta 版本 83.0.478.28 (官方内部版本) beta (64 位)

**Comment by the1812** [comment]
少开点 这些功能是限时的

**Comment by flyingnight** [comment]
> 少开点 这些功能是限时的

但是关注的up多了，每天刷动态很多了，那能不能在动态页面每个视频边上增加一个添加稍后再看的选项？这样就不用打开每个视频页面再去点稍后再看了

**Comment by the1812** [comment]
封面右下角
![image](https://user-images.githubusercontent.com/26504152/82143113-04a87a80-9874-11ea-924d-316c647b232c.png)

**Comment by flyingnight** [comment]
> 封面右下角
> ![image](https://user-images.githubusercontent.com/26504152/82143113-04a87a80-9874-11ea-924d-316c647b232c.png)

谢谢，才发现这个
