### ISSUE TITLE
快捷键扩展功能建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#534]
**关于哪一项功能**

快捷键扩展

**期望的效果**
1. 现有扩展快捷键会与全景视频内用 WASD 键移动调节视角冲突（已经撞了三个：<kbd>w</kbd>、<kbd>s</kbd> 、 <kbd>d</kbd> ），希望可以针对全景视频进行优化（或参考第 2 条）；
2. 希望能够自定义快捷键，我知道这个之前提过（#414），但还是希望可以考虑下，实现效果可以参考 [哔哩哔哩（bilibili.com）播放器调整R（ver.stardust）](https://greasyfork.org/scripts/371672)。主要还是因为会和一些自用的视频播放器增强脚本冲突（如 [视频网HTML5播放小工具](https://greasyfork.org/scripts/30545)、[HTML5视频播放器增强脚本](https://greasyfork.org/scripts/381682)，这两个脚本的快捷键列表就都参考了 PotPlayer，不能和本脚本共存）。如果还是不考虑就无视本条建议吧，第 1 条是重点。

**脚本版本**
1.10.20

**Comment by the1812** [comment]
全景会优化的
自定义快捷键不考虑, 但可以考虑提供几套键位配置供你们切换

**Comment by Geeyun-JY3** [comment]
> 全景会优化的
> 自定义快捷键不考虑, 但可以考虑提供几套键位配置供你们切换

那就好

**Comment by the1812** [comment]
自定义快捷键这个很快就要支持了, 可以先整理几套快捷键预设?
![image](https://user-images.githubusercontent.com/26504152/102950834-66b21800-4506-11eb-8c7a-1fe3f29bc66b.png)

**Comment by Geeyun-JY3** [comment]
> 自定义快捷键这个很快就要支持了, 可以先整理几套快捷键预设?

我可以做些啥么😶😳

**Comment by the1812** [comment]
> 这两个脚本的快捷键列表就都参考了 PotPlayer，不能和本脚本共存

比如能够和其他脚本兼容的预设, 或者是照搬 PotPlayer 做一个预设

**Comment by Geeyun-JY3** [comment]
到底是只给几套预设还是每一个键都可以自定义啊（

老实说我没什么思路，或者说牵涉的脚本有些多（[哔哩哔哩（bilibili.com）播放器调整R（ver.stardust）](https://github.com/kkren/bilibili_adjustPlayer) 都已经说不更新让用户过来这边了🌚），要考虑的情况不少，最近事也有些多（

或者可以置顶这个 issue 或者开个 discussion 来讨论一下？

**Comment by Geeyun-JY3** [comment]
另外现在全景视频里 <kbd>w</kbd>、<kbd>d</kbd> 好像会同时执行脚本 `快捷键扩展` 的功能和切换视角。

**Comment by the1812** [comment]
每一个键都可以自定义, 预设只是快捷键定义的一个合集, 代码大概会长这样
```JavaScript
// 把投币换成 B 键
bilibiliEvolved.settings.customKeyBindings = { coin: 'b' }
// 更改多个功能的快捷键
bilibiliEvolved.settings.customKeyBindings = { 
  fullscreen: 'shift f',
  webFullscreen: 'shift w',
  wideScreen: 'shift t',
  mute: 'shift m',
}
```

如果你有些好的预设, 我是计划放到 discussion 的常见问题里的, 没有的话也没关系

**Comment by Geeyun-JY3** [comment]
> 如果你有些好的预设, 我是计划放到 discussion 的常见问题里的, 没有的话也没关系

到时如果有空的话我提供一些我的拙见吧（

**Comment by Geeyun-JY3** [comment]
除了目前已有的快捷键，还考虑增加其他快捷键吗（包括B站原生功能和脚本增加的功能）？

**Comment by the1812** [comment]
原生的可能就方向键加一下, 脚本功能会有截图和逐帧调整的

**Comment by Geeyun-JY3** [comment]
快捷键都在这了吗：
https://github.com/the1812/Bilibili-Evolved/blob/965d3b11309993cf9c49abcaf560ec284babe7bd/src/video/keymap/keymap.ts#L240-L264
#1411 提的两个会做吗？

**Comment by the1812** [comment]
回开头的见 PR #1414
另一个可以直接配出来，大跳的85秒有隐藏选项可以改，然后快捷键换一下就行了

**Comment by Geeyun-JY3** [comment]
> 另一个可以直接配出来，大跳的85秒有隐藏选项可以改，然后快捷键换一下就行了

就是有个隐藏选项可以自定义大跳多少秒？

**Comment by Geeyun-JY3** [comment]
还有就是循环播放的快捷键现在是不考虑实现还是暂时没时间搞了？

**Comment by the1812** [comment]
> 就是有个隐藏选项可以自定义大跳多少秒
`bilibiliEvolved.settings.keymapJumpSeconds = 85`

> 还有就是循环播放的快捷键现在是不考虑（没办法）实现还是暂时没时间搞了？
不好搞, 它那个循环按钮移到里面去了, 默认情况下点不到, `unsafeWindow.player`上也没找到像是跟循环有关的开关

**Comment by Geeyun-JY3** [comment]
先整理了一个快捷键对比表，说不定能给预设一些灵感。

[视频网HTML5播放小工具](https://greasyfork.org/scripts/30545) 基本上就是 [HTML5视频播放器增强脚本](https://github.com/xxxily/h5player) 的子集，一些小地方就是大同小异下表就只列出 [视频网HTML5播放小工具](https://greasyfork.org/scripts/30545)。
[视频网HTML5播放小工具](https://greasyfork.org/scripts/30545) 能看出来参考了 PotPlayer，但考虑到有些地方不一样还是都列出来了。

| 播放器相关功能 | YouTube  | [HTML5视频播放器增强脚本](https://github.com/xxxily/h5player) | PotPlayer | 本脚本／B站（截至2021-01-09） |
| --- | --- | --- | --- | --- |
| 播放／暂停视频 | <kbd>k</kbd>/<kbd>Space</kbd> | <kbd>Space</kbd> | <kbd>Space</kbd> | <kbd>Space</kbd> |
| 长快退 | <kbd>j</kbd>(10 秒) | <kbd>Ctrl</kbd>+<kbd>←</kbd>(30s) | <kbd>Ctrl</kbd>+<kbd>←</kbd>(30s)<br /><kbd>Shift</kbd>+<kbd>←</kbd>(1min)<br /><kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>←</kbd>(5min) | <kbd>j</kbd>(85s) |
| 长快进 | <kbd>l</kbd>(10 秒) | <kbd>Ctrl</kbd>+<kbd>→</kbd>(30s) | <kbd>Ctrl</kbd>+<kbd>→</kbd>(30s)<br /><kbd>Shift</kbd>+<kbd>→</kbd>(1min)<br /><kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>→</kbd>(5min) | <kbd>Shift</kbd>+<kbd>j</kbd>(85s) |
| 快进／快退 5 秒钟 | <kbd>←</kbd>/<kbd>→</kbd>   | <kbd>←</kbd>/<kbd>→</kbd> | <kbd>←</kbd>/<kbd>→</kbd> | <kbd>←</kbd>/<kbd>→</kbd> |
| 上一帧 | <kbd>.</kbd> | <kbd>d</kbd> | <kbd>d</kbd> | <kbd>Shift</kbd>+<kbd>←</kbd> |
| 下一帧 | <kbd>,</kbd> | <kbd>f</kbd> | <kbd>f</kbd> | <kbd>Shift</kbd>+<kbd>→</kbd> |
| 加速播放 | <kbd>></kbd>（原生设定倍速） | <kbd>c</kbd>(+0.1) | <kbd>c</kbd>(+0.2) | <kbd>Shift</kbd>+<kbd>↑</kbd>或<kbd>Shift</kbd>+<kbd>.</kbd>（原生设定倍速） |
| 减速播放 | <kbd><</kbd>（原生设定倍速） | <kbd>x</kbd>(-0.1) | <kbd>x</kbd>(+0.2) | <kbd>Shift</kbd>+<kbd>↓</kbd>或<kbd>Shift</kbd>+<kbd>,</kbd>（原生设定倍速） |
| 重置播放速度 | - | <kbd>z</kbd> | <kbd>z</kbd> | <kbd>Shift</kbd>+<kbd>/</kbd> |
| 将音量增大／减小  | <kbd>↑</kbd>/<kbd>↓</kbd>(5%) | <kbd>↑</kbd>/<kbd>↓</kbd>(10%)<br /><kbd>Ctrl</kbd>+<kbd>↑</kbd>/<kbd>Ctrl</kbd>+<kbd>↓</kbd>(20%) | <kbd>↑</kbd>/<kbd>↓</kbd>(5%) | <kbd>↑</kbd>/<kbd>↓</kbd>(10%) |
| 静音／取消静音 | <kbd>m</kbd> | - | <kbd>m</kbd> | <kbd>m</kbd> |
| 跳至视频进度的 10% 到 90% | 键盘主键区中的数字 1 到 9 | - | - | - |
| 跳至视频的开头 | 键盘主键区中的数字 0 | - | <kbd>Backspace</kbd> | #1414 |
| 跳至视频的开头或结尾 | <kbd>Home</kbd>/<kbd>End</kbd> | - | - | - |
| 进入／退出全屏模式 | <kbd>f</kbd> | <kbd>Enter</kbd> | <kbd>Enter</kbd> | <kbd>f</kbd> |
| 进入／退出网页全屏 | - | <kbd>Shift</kbd>+<kbd>Enter</kbd> | 键盘主键区中的数字 6（最大化） | <kbd>w</kbd> |
| 进入／退出影院模式（宽屏） | <kbd>t</kbd> | - | - | <kbd>t</kbd> |
| 画中画 | - | <kbd>Shift</kbd>+<kbd>p</kbd> | - | <kbd>p</kbd> |
| 上一个视频 | <kbd>Shift</kbd>+<kbd>p</kbd> | - | PgUp | <kbd>[</kbd> |
| 下一个视频 | <kbd>Shift</kbd>+<kbd>n</kbd> | <kbd>n</kbd> | PgDn | <kbd>]</kbd> |
| 开启／隐藏字幕（如果有） | <kbd>c</kbd> | - | <kbd>Alt</kbd>+<kbd>h</kbd> | - |

| 特色功能 | YouTube  | [HTML5视频播放器增强脚本](https://github.com/xxxily/h5player) | PotPlayer | 本脚本／B站（截至2021-01-09） |
| --- | --- | --- | --- | --- |
| 打开迷你播放器 | <kbd>i</kbd> | - | <kbd>`</kbd>(迷你尺寸) | - |
| 关闭迷你播放器或当前对话框 | <kbd>Esc</kbd> | - | <kbd>`</kbd>(迷你尺寸) | - |
| 搜索  | <kbd>/</kbd> | - | - | #1197 |
| 截图 | - | <kbd>Shift</kbd>+<kbd>s</kbd> | <kbd>Ctrl</kbd>+<kbd>c</kbd>（复制当前源画面）<br /><kbd>Ctrl</kbd>+<kbd>e</kbd>（截存当前源画面）<br /><kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>c</kbd>（复制当前实画面）<br /><kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>e</kbd>（截存当前实画面） | <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>c</kbd>（不带弹幕）<br /><kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>c</kbd>（带弹幕） |
| 发弹幕 | - | - | - | <kbd>Enter</kbd> |
| 弹幕开关 | - | - | - | <kbd>d</kbd> |
| 打开播放器菜单 | - | - | - |<kbd>`</kbd> |
| 点赞 | - | - | - | <kbd>l</kbd> |
| 投币 | - | - | - | <kbd>c</kbd> |
| 收藏 | - | - | - | <kbd>s</kbd> |
| 稍后再看 | - | - | - | <kbd>Shift</kbd>+<kbd>w</kbd> |
| 快速收藏 | - | - | - | <kbd>Shift</kbd>+<kbd>s</kbd> |

目前没有我觉得可以加的：关灯、循环（好的看见 https://github.com/the1812/Bilibili-Evolved/issues/534#issuecomment-757089739 了）

另外我个人不是很建议用 <kbd>Shift</kbd>+<kbd>/</kbd> 作为重置倍速的快捷键，这个组合经常被用于弹出快捷键帮助的快捷键。

**Comment by Geeyun-JY3** [comment]
现在全景视频是不是又有本 issue 一开始提的第一条的问题🌚
