### ISSUE TITLE
更新1.6.31后加载组件失败

### ISSUE THREAD

**Issue by 22332333** [the1812/Bilibili-Evolved#54]
**关于哪一项功能**

**问题描述**

插件无法使用 设置也打不开

**脚本版本**

正式版

**浏览器版本**

**错误信息**

- 

- 

- [ ] 

- [ ] 

**附加截图**

**Comment by 22332333** [comment]
![Uploading QQ截图20190119231222.png…]()
![Uploading QQ截图20190119231241.png…]()
![Uploading QQ截图20190119231501.png…]()

**Comment by 22332333** [comment]
![qq 20190119231222](https://user-images.githubusercontent.com/37445278/51428639-da738800-1c40-11e9-8a9d-bb88e7ad4cb5.png)
![qq 20190119231241](https://user-images.githubusercontent.com/37445278/51428640-db0c1e80-1c40-11e9-9b6c-f17708b5b323.png)
![qq 20190119231501](https://user-images.githubusercontent.com/37445278/51428641-dba4b500-1c40-11e9-869b-06ddc9c9d6db.png)

**Comment by the1812** [comment]
我这边测试没有问题啊, 试试清除缓存, 然后强制刷新(`Ctrl+Shift+R`); 或者重新把脚本安装一下吧.

**Comment by 22332333** [comment]
> 我这边测试没有问题啊, 试试清除缓存, 然后强制刷新(`Ctrl+Shift+R`); 或者重新把脚本安装一下吧.

清楚缓存是指清楚浏览器缓存吗 包括cookies那些吗...由于我的浏览器保留了很多密码我不太想....
我刚刚卸载了重新安装了这个版本还是加载失败...
![qq 20190120000825](https://user-images.githubusercontent.com/37445278/51429258-e1ea5f80-1c47-11e9-9852-b94aea3e895e.png)
![qq 20190120000859](https://user-images.githubusercontent.com/37445278/51429259-e3b42300-1c47-11e9-8a10-598e6eccead7.png)

**Comment by the1812** [comment]
随便进一个视频看看, 是不是`下载弹幕`也会加载失败?
清除缓存应该有让选的吧, 只清除缓存文件, 不删cookie和密码

**Comment by 22332333** [comment]
> 随便进一个视频看看, 是不是`下载弹幕`也会加载失败?
> 清除缓存应该有让选的吧, 只清除缓存文件, 不删cookie和密码

刚才是删除的这些选项后重新安装的 左边的功能键和设置键都打不开
![qq 20190120004901](https://user-images.githubusercontent.com/37445278/51429812-ace10b80-1c4d-11e9-8d2b-fca4eb0f220c.png)
![qq 20190120005116](https://user-images.githubusercontent.com/37445278/51429813-ace10b80-1c4d-11e9-890a-627ee675a045.png)

**Comment by the1812** [comment]
好的, 辛苦你了. 之后我会做一些修复, 离线版如果能用的话可以先用着了.

**Comment by the1812** [comment]
`1.6.32`版已修复此问题

**Comment by 22332333** [comment]
> `1.6.32`版已修复此问题
的确好了~
