### ISSUE TITLE
请问为什么新版本没有自动播放视频了

### ISSUE THREAD

**Issue by RuiPlus** [the1812/Bilibili-Evolved#542]
请问为什么新版本没有自动播放视频了，
还有自动切换清晰度，可以添加其他网站吗，比如虎牙，斗鱼

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/82343576-9efbf000-9a25-11ea-90fd-0224c473e135.png)

本脚本不会考虑任何b站以外的网站.

**Comment by sadkmoon** [comment]
谢谢
