### ISSUE TITLE
动态-强制固定顶栏与侧栏反馈

### ISSUE THREAD

**Issue by Kaneki521** [the1812/Bilibili-Evolved#545]
已经测试，预览版离线版（673.91）、预览版（1.10.23）、正式版（1.10.20）都有相同问题

**关于哪一项功能**

动态-强制固定顶栏与侧栏

**问题描述**

开启"动态-强制固定顶栏与侧栏"后，在动态页面，滚动鼠标滚轮会出现侧边栏上下跳动问题（具体可以看gif），关闭，则没有问题（不知道这算不算BUG，还是本身设计就是如此）

**脚本版本**

预览版离线版（673.91）、预览版（1.10.23）、正式版（1.10.20）都有相同问题

**浏览器版本**

Chrome    83.0.4103.61（正式版本）

**错误信息**

无

**附加截图**
![2](https://user-images.githubusercontent.com/50744308/82516776-378d8f80-9b4e-11ea-8f9b-dd5c10500a9c.gif)

**Comment by the1812** [comment]
动态过滤器有开吗?

**Comment by Kaneki521** [comment]
> 动态过滤器有开吗?

没有

**Comment by the1812** [comment]
我试不出来.. 能否导出整个设置给我?

**Comment by Kaneki521** [comment]
好的，感谢开发者大大

[bilibili-evolved-settings.zip](https://github.com/the1812/Bilibili-Evolved/files/4671686/bilibili-evolved-settings.zip)

**Comment by the1812** [comment]
ok 试出来了 下次更新会修复

**Comment by Kaneki521** [comment]
> ok 试出来了 下次更新会修复
辛苦了，感谢开发者大大
