### ISSUE TITLE
转换蓝链里的视频、专栏号为对应视频、专栏的信息

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#555]
**关于哪一项功能**

希望可以自动替换Bilibili评论区和动态里已经蓝了的视频、专栏链接显示文字为视频、专栏的名字，甚至显示更多的信息。
**期望的效果**
我自己之前弄过一个脚本([BilibiliLinksInfos](https://greasyfork.org/zh-CN/scripts/398500))但是做的不怎么好而且有时候转换不了...

**脚本版本**
v1.10.24

**Comment by Geeyun-JY3** [comment]
万万没想到，B 站官方居然率先实现了这个需求……视频专栏都实现了，还支持 `b23.tv/*` 短网址格式的视频和专栏（不过 cv 号好像还有些 bug，有些短网址格式的视频也还不行，应该还没做完）（目前我只在视频、专栏评论区测试过）

![image](https://user-images.githubusercontent.com/49396421/99647397-ad869b00-2a8c-11eb-9d52-5328c2d9e8d9.png)
![image](https://user-images.githubusercontent.com/49396421/99651502-a1e9a300-2a91-11eb-8292-a732e016d017.png)

**Comment by the1812** [comment]
鸽到官方实现也是一种不鸽(

**Comment by Geeyun-JY3** [comment]
那是不是该做一个把视频专栏标题转换回去的功能
![](https://camo.githubusercontent.com/e67fae24a8f8f413dc9aa490ed575029c8b3a8440bce4ade92f820c78365d602/68747470733a2f2f69302e6864736c622e636f6d2f6266732f656d6f74652f626261376331326161353166656430313939633234313436353536306466633237313463353933652e706e67)

**Comment by the1812** [comment]
> 那是不是该做一个把视频专栏标题转换回去的功能

右键 复制链接

**Comment by Geeyun-JY3** [comment]
> 右键 复制链接

指单纯的 av BV cv 号（不过如果完整链接还是av BV cv 号在 b 站都是这样的效果好像也没什么必要了）

**Comment by CKylinMC** [comment]
怕不是这里有官方的内鬼23333

**Comment by CKylinMC** [comment]
> 那是不是该做一个把视频专栏标题转换回去的功能
> ![](https://camo.githubusercontent.com/e67fae24a8f8f413dc9aa490ed575029c8b3a8440bce4ade92f820c78365d602/68747470733a2f2f69302e6864736c622e636f6d2f6266732f656d6f74652f626261376331326161353166656430313939633234313436353536306466633237313463353933652e706e67)

有道理啊~~~23333

**Comment by Geeyun-JY3** [comment]
那 https://github.com/the1812/Bilibili-Evolved/issues/688#issuecomment-652783687 说的弹出小窗是不是就不做了

**Comment by the1812** [comment]
是的
