### ISSUE TITLE
黑暗模式下，直播间勋章文字颜色有误

### ISSUE THREAD

**Issue by Wcraft233** [the1812/Bilibili-Evolved#557]
**关于哪一项功能**
黑暗模式

**问题描述**

直播间B站自带的选择勋章界面，勋章内颜色有误

**脚本版本**

预览版 1.10.24
**浏览器版本**

chrome83

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/30252123/82809234-39dd4a00-9ebe-11ea-8ae8-8c0e48d009b9.png)

**Comment by the1812** [comment]
我们没有类似的勋章可供参考, 可否抓取一下这个弹窗的结构? 虽然步骤可能有点繁琐:
- <kbd>F12</kbd>打开DevTools
- 点开这个`当前佩戴勋章`
- 按住<kbd>Shift</kbd>点附加功能
- DevTools会弹出, 整个页面冻结
- 点击使用左上角的探测节点工具, 然后点当前佩戴弹窗里的任意位置, DevTools会定位到这个弹窗
![image](https://user-images.githubusercontent.com/26504152/82815655-2933d080-9ecc-11ea-9ead-72475ed0a56c.png)

- 稍微向上找到含有`dialog-ctnr`的节点, 右键递归展开(Expand recursively), 然后把展现的结构截图给我
![image](https://user-images.githubusercontent.com/26504152/82815852-98112980-9ecc-11ea-95f0-40929ad2e244.png)

**Comment by Wcraft233** [comment]
不知道方法对不对，大概是这个？
![image](https://user-images.githubusercontent.com/30252123/82821132-1aeab200-9ed6-11ea-89fd-c428221bd113.png)

**Comment by the1812** [comment]
是的, 非常感谢
明晚应该就能收到修复后的更新包
