### ISSUE TITLE
请问取消细滚动条后就看不见滚动条了？

### ISSUE THREAD

**Issue by shimakotodo** [the1812/Bilibili-Evolved#558]
自动更新到了v1.10.24，新增取消细滚动条的选项。但是关闭这个选项后，滚动条的部位变成了一段空白，下面的横向滚动条是空白也还没事，可以正常拖动。但是右侧上下滚动条的位置变成空白，就无法正常拖动了，拖动时会乱跑到页面下面。请问是我这边自己的问题还是都是这样呢？怎样解决？谢谢。

附上两张前后对比截图，方便您看懂我的问题。
![1](https://user-images.githubusercontent.com/64628237/82875453-fcce9180-9f69-11ea-861d-60deb725dd7e.png)

第二张是取消细滚动条之后。
![2](https://user-images.githubusercontent.com/64628237/82875500-0c4dda80-9f6a-11ea-9f8c-eaaed5598981.png)

背景绿色是用了保护眼睛扩展，但是把这个扩展关闭了也还是一样，所以不是颜色扩展原因。

**Comment by the1812** [comment]
请问浏览器是?

**Comment by shimakotodo** [comment]
> 请问浏览器是?

chrome最新的版本 83.0.4103.61（正式版本） （64 位）

**Comment by the1812** [comment]
我试不出来, 能否导出您的设置提供给我?

**Comment by shimakotodo** [comment]
这个问题现在已经解决了。

当发现自动更新到v10.26，滚动条仍然没有出现，一怒之下删除重装...一切正常了。放弃用原来的设置导入，全部重新设置后，现在滚动条完全正常。

之前还认真的研究了很久Chrome的滚动条透明和美化之类，想找出冲突所在，就没想到删了重装这种原始解决方法。

这个问题可以关闭了。再次感谢制作这个脚本！

**Comment by the1812** [comment]
虽然不清楚原因, 但能解决就好
