### ISSUE TITLE
评论区相对时间戳转换为绝对时间戳

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#566]
**关于哪一项功能**
评论区增强（加到简化评论区里感觉不太合适）

**期望的效果**
希望能将评论区中的今天内的评论的相对时间戳显示成绝对时间戳。
（顺便提醒一下，视频底下的部分标签变成和手机一样的频道了）

**脚本版本**
正式版 v1.0.24

**Comment by the1812** [comment]
(标签在弄了

**Comment by Geeyun-JY3** [comment]
这个时间戳的转换我觉得可以参考 BiliPlus 的实现方式，这样也可以两全。
截图 GIF：
![biliplus时间戳](https://user-images.githubusercontent.com/49396421/84981475-3492b880-b167-11ea-887f-1031e3c3b0b3.gif)
