### ISSUE TITLE
粉丝勋章页面

### ISSUE THREAD

**Issue by YuhaoTang** [the1812/Bilibili-Evolved#567]
**关于哪一项功能**
粉丝勋章页面

**期望的效果**
https://link.bilibili.com/p/center/index#/user-center/wearing-center/my-medal
粉丝勋章页面能不能一次头加载所有25个勋章，并且按照等级倒序排列？

**脚本版本**
1.10.24

**Comment by the1812** [comment]
排个序挺好的
`能不能一次头加载所有25个勋章`这个是指什么?

**Comment by YuhaoTang** [comment]
当前那个网页每页只会显示10个勋章，而勋章这东西最多也只能有25个，所以一页显示全多好

**Comment by the1812** [comment]
勋章的话在直播间里的附加功能里可以看到所有的勋章, 可以切换佩戴状态
如果需要查看更多的信息, 我可以试试在鼠标悬浮的提示里加上

**Comment by YuhaoTang** [comment]
我的意思是不希望这里翻页，希望一页显示全
![image](https://user-images.githubusercontent.com/15133354/83040134-82893480-a071-11ea-97e9-61918f89e917.png)

**Comment by the1812** [comment]
那么我加一个附加功能如何? 点击立即查看所有勋章的亲密度上限等, 这样在任何直播间都能看, 不用再去那个页面
因为改它原本的界面还不如自己整一个方便

**Comment by YuhaoTang** [comment]
如果更方便那当然可以，我需求就是那个

**Comment by YuhaoTang** [comment]
但是我寻思，它有个这个请求

**Comment by the1812** [comment]
改请求的话 我得开个新脚本了
Evolved的代码执行顺序是赶不上页面的第一波请求的, 加了修改器也还是要切到第二页再切回来才起效

**Comment by YuhaoTang** [comment]
那如果把page=2 size=15 apped进去呢，就不排序了，这样做麻烦吗

**Comment by the1812** [comment]
你可以直接装上试试效果, 脚本需要打开`Ajax Hook API`选项, 点第二页会出25个勋章, 不带排序.
```js
// ==UserScript==
// @name          25个勋章
// @version       1.0.0
// @author        Grant Howard
// @match         https://link.bilibili.com/p/center/index*
// @grant         unsafeWindow
// ==/UserScript==

(() => {
  if (unsafeWindow.bilibiliEvolved === undefined) {
    unsafeWindow.bilibiliEvolved = { addons: [] }
  }
  const evolved = unsafeWindow.bilibiliEvolved
  evolved.addons.push({
    success: () => {
      evolved.Ajax.addEventListener('afterOpen', function (_, url) {
        console.log(url)
        if (url.startsWith('//api.live.bilibili.com/i/api/medal?page=') && url.endsWith('10')) {
          this.open('GET', '//api.live.bilibili.com/i/api/medal?page=1&pageSize=25')
        }
      })
    },
  })
})()
```

**Comment by YuhaoTang** [comment]
没找到打开Ajax Hook API选项在哪诶……

**Comment by the1812** [comment]
在`其他`那里, 最底下

**Comment by YuhaoTang** [comment]
是的可以生效

**Comment by the1812** [comment]
那么这个小脚本是否满意? 还是说仍要等我做出附加功能来?

**Comment by YuhaoTang** [comment]
满意啦，我需求其实已经够了
