### ISSUE TITLE
下载视频时能否设置非大会员的默认清晰度？

### ISSUE THREAD

**Issue by shimakotodo** [the1812/Bilibili-Evolved#568]
**关于哪一项功能**

**期望的效果**

**脚本版本**
v1.10.24，以前好像不是这样的，现在下载视频，默认一律按最高清晰度，比如说如果有1080p+（大会员专享），就默认下载这个。但是非大会员不能看1080P+，就会发生无法识别不能下载。要手动调成1080p才能下载。

虽然手动调一下也不麻烦，但是不知道的人可能就无法下载。如果能够的话，希望能增加一个下载的指定首选清晰度的选项，比如指定默认优先下载1080p，没有的话就自动降到720P。这样就能避免非大会员不能下载1080P+。

谢谢。

**Comment by the1812** [comment]
因为有非大会员up主需要下载自己的视频, 自己传的视频可以任意清晰度下载, 所以开放了所有清晰度.
不过清晰度的选择应该是有记忆的才对啊, 选过一次1080P, 下次就算有4K的视频, 默认清晰度也会选中1080P

**Comment by the1812** [comment]
不能记忆的话, 手动设置一下吧, 浏览器控制台(<kbd>Ctrl + Shift + I</kbd>)里:
- `bilibiliEvolved.settings.downloadVideoQuality` 查看当前记忆值
- `bilibiliEvolved.settings.downloadVideoQuality = 80` 设成默认1080P

![image](https://user-images.githubusercontent.com/26504152/83038017-13aadc00-a06f-11ea-904b-a393c6a3d768.png)

**Comment by shimakotodo** [comment]
> 不能记忆的话, 手动设置一下吧, 浏览器控制台(Ctrl + Shift + I)里:
> 
> * `bilibiliEvolved.settings.downloadVideoQuality` 查看当前记忆值
> * `bilibiliEvolved.settings.downloadVideoQuality = 80` 设成默认1080P
> 
> ![](https://user-images.githubusercontent.com/26504152/83038017-13aadc00-a06f-11ea-904b-a393c6a3d768.png)

感谢回复，成功解决了。在手动调成1080P下载后，默认的还是原来的120，改成80就好了。

能顺便问一句吗，我不翻墙就无法看到GitHub的附件图片，要翻墙才能看到。我按CSDN里给出的改host还是不行，不知你是怎么看附件图片的，有解决方法吗？

**Comment by the1812** [comment]
我随缘看的... 有时候能看有时候不能
看不到就挂到aria2那慢慢下载到本地再看
