### ISSUE TITLE
希望自定义顶栏支持在新标签页中打开链接

### ISSUE THREAD

**Issue by datou1996** [the1812/Bilibili-Evolved#570]
**关于哪一项功能**
自定义顶栏

**期望的效果**
希望添加一个“在新标签页打开链接”的功能

**脚本版本**
V1.10.24

**Comment by Coulomb-G** [comment]
鼠标右键不就有吗?

**Comment by datou1996** [comment]
emmm我是说添加一个默认所有链接都在新标签页打开的功能，每次都用右键稍微有些繁琐
