### ISSUE TITLE
反馈论坛界面，自定义顶栏刷不出来

### ISSUE THREAD

**Issue by peace-max** [the1812/Bilibili-Evolved#571]
**关于哪一项功能**
用户反馈论坛界面，自定义顶栏刷不出来，自定义顶栏刷不出来
https://www.bilibili.com/blackboard/activity-GBnHKZEX.html
**问题描述**

用户反馈论坛界面，自定义顶栏刷不出来，自定义顶栏刷不出来
https://www.bilibili.com/blackboard/activity-GBnHKZEX.html

**脚本版本**

1.10.24

**浏览器版本**

**错误信息**

**附加截图**

**Comment by pbxs666** [comment]
我也反馈一个，wiki界面也不行，连侧边栏都没有，脚本形同虚设。
但不卡，而反馈论坛的界面有点卡，油猴上显示脚本调用次数快速从1变到10。没刷新网页，第一次打开就这样。

wiki网址：https://wiki.biligame.com/wiki/%E9%A6%96%E9%A1%B5

**Comment by the1812** [comment]
wiki是biligame.com了 不属于脚本的运行范围bilibili.com
反馈论坛就离谱了, 里面用了5个iframe, 网页每使用一个iframe都要整个重新加载, 加载时间会成倍增长, 如果b站不减少iframe的使用, 我可能会关闭对反馈论坛的脚本加载

**Comment by pbxs666** [comment]
刚才也看了，确实不在脚本运行范围内。但不知为什么，脚本就是激活了。上图
![图片1](https://user-images.githubusercontent.com/47630168/83733832-b1f6fd00-a680-11ea-9613-71c76aa4686b.png)
![图片2](https://user-images.githubusercontent.com/47630168/83733841-b58a8400-a680-11ea-8056-49d82ca259a1.png)
顶栏还是原来的。

**Comment by the1812** [comment]
顶栏的`消息`也是使用了iframe, 导致了脚本运行
如果平时使用自定义顶栏的话, 可以在反广告插件里禁掉这个iframe, 能提高很多页面的加载速度

**Comment by the1812** [comment]
补充下可以禁掉的网址:
```
https://message.bilibili.com/pages/nav/index_new_pc_sync
https://message.bilibili.com/pages/nav/index_new_sync
https://t.bilibili.com/h5/dynamic/specification
```
