### ISSUE TITLE
视频链接 BV 号开头为小写「bv」时 BV 号不转换

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#573]
**关于哪一项功能**
网址 AV 号转换

**问题描述**
视频链接 BV 号开头为小写「bv」时 BV 号不会转换成 AV 号，动态、评论、私信中的 BV 号高亮跳转的似乎都是开头为小写「bv」的链接。

**脚本版本**
正式版 v1.10.24
预览离线版

**浏览器版本**
Chrome 83.0.4103.61（正式版本） （64 位）
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)

**错误信息**

**附加截图**

**Comment by the1812** [comment]
啊...刚出BV号那会还只认大写来着的

**Comment by Geeyun-JY3** [comment]
突然发现高亮跳转的链接又变成了大写「BV」……估计是近期又改了……

**Comment by the1812** [comment]
没事 已经加了小写bv的支持了
