### ISSUE TITLE
希望在视频缩略图上加一个直接弹出播放的图标

### ISSUE THREAD

**Issue by 921j** [the1812/Bilibili-Evolved#575]
**关于哪一项功能**

谢谢作者大大的好脚本，一直在使用：）
我用的是百分浏览器最新版便携64位版，习惯一边弹出视频在右下角播放一边做其他事，现在每一次都要先点开视频播放页面，然后在视频右上角点弹出播放的按钮。

**期望的效果**
不知道能否直接在视频缩略图上加一个类似“稍后收看”那样的图标，点击后能直接弹出视频播放，跳过打开播放页面的步骤。

**脚本版本**

**Comment by the1812** [comment]
不能 那种画中画弹窗必须先打开视频页面

**Comment by 921j** [comment]
> 不能 那种画中画弹窗必须先打开视频页面

好的，我试试其他方法，比如ahk或iMacros之类的，谢谢：）
