### ISSUE TITLE
视频下载失败

### ISSUE THREAD

**Issue by RenZihou** [the1812/Bilibili-Evolved#578]
**关于哪一项功能**
视频下载  
补充一下 #564 的相关说明

**问题描述**

下载视频时，下载进度条正常推进，但到达 100% 后没有保存视频，而是报错

尝试了多个视频、不同分辨率，均出现此问题

改用`aria2`下载，仍会出现此问题

**脚本版本**

正式版`1.10.24`

**浏览器版本**

`Version 81.0.4044.138 (Official Build) (64-bit)`

**错误信息**

直接下载时：
> Cannot read property 'url' of undefined
> TypeError: Cannot read property 'url' of undefined
>     at f.downloadSubtitle (eval at applyComponent (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=a37d583d-9bfa-45a5-bae2-a635e4c934da), :1:8985)
>     at async f.download (eval at applyComponent (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=a37d583d-9bfa-45a5-bae2-a635e4c934da), :1:9828)
>     at async Vue.startDownload (eval at applyComponent (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=a37d583d-9bfa-45a5-bae2-a635e4c934da), :1:21112)

使用`aria2`下载时：

> chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=a37d583d-9bfa-45a5-bae2-a635e4c934da:13290 TypeError: Cannot read property 'url' of undefined
>     at f.downloadSubtitle (eval at applyComponent (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=a37d583d-9bfa-45a5-bae2-a635e4c934da), <anonymous>:1:8985)
>     at async f.exportAria2 (eval at applyComponent (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=a37d583d-9bfa-45a5-bae2-a635e4c934da), <anonymous>:1:8035)
>     at async Vue.exportData (eval at applyComponent (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=a37d583d-9bfa-45a5-bae2-a635e4c934da), <anonymous>:1:14741)

**附加截图**
![Snap1](https://user-images.githubusercontent.com/45473641/83265417-12ef8280-a1f4-11ea-8b96-b511d0cc0304.png)
![Snap2](https://user-images.githubusercontent.com/45473641/83265730-7e395480-a1f4-11ea-96d1-7b62cf1a4b42.png)

**Comment by the1812** [comment]
是字幕的问题 之前如果下过字幕会导致bug
可以找一个有字幕的视频 把字幕选项设回无应该就正常了

**Comment by DEabcdp** [comment]
同样的下载错误，楼上说的不下载字幕同样报错，没有解决问题！直接下载提示Cannot read property 'url' of undefined。

**Comment by DEabcdp** [comment]
在有字幕的视频里把字幕设为“无”，刷新后可正常下载。但是新【BUG】是如果一个视频既有字幕也有弹幕，同时下载（均ass格式）时，发现下载下来的文件里只有字幕，没有弹幕。
