### ISSUE TITLE
哔哩哔哩客户端下载展示页适配问题

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#581]
**关于哪一项功能**
https://app.bilibili.com/ 页面适配问题

**问题描述**
已知的问题有看不到除「安卓版」外所有 tab 下的更新日志、夜间（暗色）模式没适配

**脚本版本**
正式版 v1.10.24
预览离线版

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 83.0.4103.61（正式版本） （64 位）

**错误信息**
以下是在 Chrome 83.0.4103.61（正式版本） （64 位）中使用预览离线版报告的错误信息：
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
sentry-5.2.1.min.js:2 Sentry Logger [Error]: This event has been sampled, will not send event.
(anonymous) @ sentry-5.2.1.min.js:2
vendors.435ea2524aed8f7e2af9.js:7 Uncaught (in promise) Error: Could not load URL at //s1.hdslb.com/bfs/seed/blive/blfe-link-shortassets/dist/component.statistics/log-reporter.js
    at HTMLScriptElement.i.onerror (vendors.435ea2524aed8f7e2af9.js:7)
```
```
[Report Only] Refused to load the stylesheet 'https://at.alicdn.com/t/font_1195811_3ymwb3fsnmj.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' *.hdslb.com static.geetest.com". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
```

**附加截图**
![image](https://user-images.githubusercontent.com/49396421/83272790-33bcd580-a1fe-11ea-9d7d-f3c88e95216b.png)
![image](https://user-images.githubusercontent.com/49396421/83272905-5cdd6600-a1fe-11ea-8185-46da6af44696.png)

**Comment by the1812** [comment]
夜间已适配
切tab的问题我也不知道咋回事 干脆就不管了吧 反正是手机端的信息

**Comment by Geeyun-JY3** [comment]
其实有个 TV 版和 UWP 版（虽然 UWP 版更新日志很久没更新了

**Comment by the1812** [comment]
反正各个平台的应用商店里肯定能找到日志的 (新不新就不一定了
