### ISSUE TITLE
查看封面无法完整预览图片 , 按钮超出整个版面

### ISSUE THREAD

**Issue by yoyosnart** [the1812/Bilibili-Evolved#582]
**关于哪一项功能**
查看封面

**问题描述**
查看封面无法完整预览图片 , 按钮超出整个版面

**脚本版本**
正式版 1.10.24

**浏览器版本**
Google Chrome 版本 83.0.4103.61 (正式版本) (64 位元)

**错误信息**
出错的影片：https://www.bilibili.com/video/BV1mt4y1C7dB/

**附加截图**
![2020-05-30_003814](https://user-images.githubusercontent.com/16216839/83284066-c5ccda00-a20e-11ea-997d-0cb7586a5768.png)

**Comment by Coulomb-G** [comment]
你的分辨率是多少?

**Comment by yoyosnart** [comment]
> 你的分辨率是多少?

屏幕的吗? 1920*1080

**Comment by yoyosnart** [comment]
貌似跟封面图的尺寸也有关系的 , 尺寸没那么大的封面图都可以正常显示

![2020-05-30_191901](https://user-images.githubusercontent.com/16216839/83326931-6fad7480-a2aa-11ea-84ce-0a30b63d9b90.png)

**Comment by sunfkny** [comment]
补充一下，`body > div.image-viewer-container.opened > div > img` 这个img超出父级div了，父级div高度正常
![20200530192135](https://user-images.githubusercontent.com/30853461/83326959-d92d8300-a2aa-11ea-8bd4-5bab087c71b5.png)
