### ISSUE TITLE
直播信息扩充导致直播间重复显示

### ISSUE THREAD

**Issue by XZL16** [the1812/Bilibili-Evolved#583]
**关于哪一项功能**
直播信息扩充

**问题描述**

开启直播信息扩充后，会重复显示该主播的直播间，都可以点击进入直播间，这个问题似乎在1.10.20就出现了，且仅有该主播出现过这种情况，无论我的关注列表是只有她一人直播时或是有多人直播时都是如此，而且我也没将她设为特别关注，先取消关注再进行关注后也是如此，实在搞不懂了所以来提交反馈。

主播直播间：https://live.bilibili.com/14917277

**脚本版本**

正式版1.10.24

**浏览器版本**

360极速浏览器
版本号：12.0.1322.0
内核版本：78.0.3904.108

**错误信息**

**附加截图**
![typora](https://i0.hdslb.com/bfs/album/00238f959fd62a542528787e32f0be3b39fb1d97.png)

**Comment by the1812** [comment]
可以查看下控制台(<kbd>Ctrl+Shift+I</kbd>)的输出吗?
扩充后会输出两个数组, 第一个是在原有的直播间上加标题的记录, 第二个是添加新的直播间的记录 (展开后能看到主播名称)

类似这样
![image](https://user-images.githubusercontent.com/26504152/85257810-00860300-b499-11ea-8b9e-2e864ed4e646.png)

**Comment by XZL16** [comment]
![typora](https://i0.hdslb.com/bfs/album/4f3cc0e0d81cffe1f8aa17b6ac8cd71166dfc594.png@518w_1e_1c.png)
![typora](https://i0.hdslb.com/bfs/album/9945fdf4de77bdc60f595c73b744a4306d3d9378.png@518w_1e_1c.png)


只有这个主播提示live title not found
要是这是不可重现的错误的话我估计可能是我自己之前弄过什么脚本导致的，认栽了_(:з」∠)_
