### ISSUE TITLE
any offcial telegram group is provided?

### ISSUE THREAD

**Issue by EA-DICE** [the1812/Bilibili-Evolved#588]

**Comment by the1812** [comment]
Sorry, we don't use telegram.

**Comment by EA-DICE** [comment]
any official group?if there is any bugs, i can report immediately

**Comment by the1812** [comment]
Please report to GitHub issues, we can immediately get the e-mail notifications.

**Comment by EA-DICE** [comment]
that will be negative, thanks

**Comment by EA-DICE** [comment]
great, thanks
