### ISSUE TITLE
希望可以在新标签页打开 BiliPlus 的对应页面

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#593]
**关于哪一项功能**
BiliPlus 跳转支持

**期望的效果**
希望可以给个在新标签页打开目前仍存活视频／番剧／个人（空间） BiliPlus 上对应页面的选项，已 404 页面则仍在本标签页跳转。
（顺便提醒又一轮的 [分区调整](https://www.bilibili.com/read/cv6289732)）

**脚本版本**
正式版 v1.10.24

**Comment by the1812** [comment]
做成支持右键菜单开新标签页如何?

**Comment by Geeyun-JY3** [comment]
> 做成支持右键菜单开新标签页如何?

也行
