### ISSUE TITLE
夜间模式下视频控制栏「选集」二字颜色偏暗

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#595]
**关于哪一项功能**
夜间模式

**问题描述**
扣个小细节，夜间模式下多 P 稿件的视频控制栏的「选集」二字与旁边的清晰度文字相比颜色偏暗，是 bug 还是忘了做🌚？

**脚本版本**
正式版 v1.10.24
预览离线版

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 83.0.4103.61（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/49396421/83647265-4b71d080-a5e7-11ea-83ab-878994b879a5.png)

**Comment by the1812** [comment]
因为我们平时开着触摸模式, 替换成图标了...
![image](https://user-images.githubusercontent.com/26504152/83705473-9f140680-a647-11ea-9e16-f6c4b0cafe58.png)

**Comment by Geeyun-JY3** [comment]
> 因为我们平时开着触摸模式, 替换成图标了...
> ![image](https://user-images.githubusercontent.com/26504152/83705473-9f140680-a647-11ea-9e16-f6c4b0cafe58.png)

那干脆直接也替换成图标😂？

**Comment by the1812** [comment]
改回正常的白色就行了 懒得再开个功能了(
