### ISSUE TITLE
大佬 关于4K下载音频合成问题

### ISSUE THREAD

**Issue by Love-Hong** [the1812/Bilibili-Evolved#598]
大佬 能不能把下载4K视频 直接音频合成好呢？现在下载4K 是一个ZIP压缩包 里面包含4K视频文件与音频文件 得自己把音轨拉进去才行 感觉有点麻烦 要是可以和1080P视频那样 直接给合成好就棒了 望加入此功能 谢谢！--您的 Bilibili-Evolved老用户！
![20200604213151](https://user-images.githubusercontent.com/35194212/83763329-2777c300-a6ab-11ea-869d-9d3a48f79d6d.png)

**Comment by the1812** [comment]
常见问题里有说的, 合并我无法在浏览器中完成, 需要您手动合并.
> 下载时选择`DASH`格式(注意只有新一点的视频才支持, 老视频只有`FLV`), 得到视频和音频文件后用 [ffmpeg](https://ffmpeg.org/) 合并, 合并方法见[#183](https://github.com/the1812/Bilibili-Evolved/issues/183).

**Comment by DEabcdp** [comment]
使用potplayer直接双击视频就能自动加载视频+音频+字幕，不用合并。

**Comment by PlexPt** [comment]
可以检查path里如果有ffmpeg的话， 就合并
