### ISSUE TITLE
很多图片加载失败

### ISSUE THREAD

**Issue by f59375543** [the1812/Bilibili-Evolved#599]
无论是看视频时的小图，还是专栏里的大图，都显示裂了，必须刷新多次才能出现

![image](https://user-images.githubusercontent.com/43315911/83825345-adc3f180-a70b-11ea-9dcb-a18e8be33fc4.png)
![image](https://user-images.githubusercontent.com/43315911/83825351-b1f00f00-a70b-11ea-821d-c23a064d0805.png)

脚本版本
正式版 v1.10.24

**Comment by the1812** [comment]
一直都这样? 还是偶尔?

**Comment by f59375543** [comment]
> 一直都这样吗？还是偶尔？

昨天升级到v1.10.26暂时没出现了，原本是一直都有

**Comment by nydusz** [comment]
可能是连b站图床不稳定 可以试试改host 先看可能是哪个节点有问题 然后打开C:\Windows\System32\drivers\etc\hosts
在末尾加上
113.96.181.216 s1.hdslb.com
113.96.181.215 s2.hdslb.com
183.232.215.136 i0.hdslb.com
113.96.140.113 i1.hdslb.com
183.236.60.130 i2.hdslb.com
14.215.83.243 static.hdslb.com
具体改host按自己需求改 不一定要按这个
