### ISSUE TITLE
简化首页中热门似乎没有刷新

### ISSUE THREAD

**Issue by killer45690** [the1812/Bilibili-Evolved#600]
**关于哪一项功能**
关于 简化首页 清爽 中

**问题描述**

热门视频似乎没有刷新，内容均为6月2号的热门视频，与原网页不符

**脚本版本**

preview v1.10.27

**浏览器版本**
Chrome 83.0.4103.61

**附加截图**
![image](https://user-images.githubusercontent.com/42988826/83895668-99243f80-a785-11ea-833f-63bccdb25f38.png)

**Comment by the1812** [comment]
热门那块似乎改了 原有的方法拿到的数据不更新了
而改版后的数据不再区分`今日`,`三日`,`一周`, 几乎全部都是近几日
