### ISSUE TITLE
顶栏动态选项下的直播分栏缺少一部分直播，关闭脚本后可见

### ISSUE THREAD

**Issue by North-glory** [the1812/Bilibili-Evolved#603]
**关于哪一项功能**
顶栏下的直播分栏缺少直播。

**问题描述**

**脚本版本**

**浏览器版本**
Chrome版本 77.0.3865.90

**附加截图**
![image](https://user-images.githubusercontent.com/58940498/83970297-981b1b80-a907-11ea-9c8a-d1724a1bab1d.png)

**Comment by the1812** [comment]
缺少是指什么? 少了某个主播?

**Comment by North-glory** [comment]
对，缺少一部分主播。大概十几位

**Comment by the1812** [comment]
总数量是不是超过24个了?

**Comment by North-glory** [comment]
对， 超过了

**Comment by the1812** [comment]
因为我只加载了前24个
那我改成全部加载吧

**Comment by North-glory** [comment]
幸苦了。
