### ISSUE TITLE
【BUG】预览版的视频下载IDM导出的ef2文件，导入IDM时显示“该文件不包含任何网络链接”，无法下载

### ISSUE THREAD

**Issue by DEabcdp** [the1812/Bilibili-Evolved#605]
**问题描述**
<【BUG】预览版的视频下载IDM导出的ef2文件，导入IDM时显示“该文件不包含任何网络链接”，无法下载。IDM版本为6.36>

**脚本版本**
<预览版1.10.28>

**浏览器版本**
<Edge Chromium 85.0.538.0>

**附加截图**
![image](https://user-images.githubusercontent.com/62452364/83982927-03dba380-a95d-11ea-8ccc-e30c7941feeb.png)

**Comment by the1812** [comment]
这个可以去 #540 看看, 大概晚上就能收到更新

**Comment by DEabcdp** [comment]
好的，感谢！
