### ISSUE TITLE
港澳台番剧打开失败（已安装解除区域限制脚本）

### ISSUE THREAD

**Issue by txy1212** [the1812/Bilibili-Evolved#609]
浏览器：chrome
脚本版本：均最新版本
![TIM截图20200610111651](https://user-images.githubusercontent.com/65844181/84223176-ee58ac00-ab0b-11ea-86fa-ddb290e93416.png)
![TIM截图20200610111417](https://user-images.githubusercontent.com/65844181/84223182-f0226f80-ab0b-11ea-9205-cecb251ab075.png)
![TIM截图20200610111338](https://user-images.githubusercontent.com/65844181/84223183-f0bb0600-ab0b-11ea-81be-835170a0d38e.png)

**Comment by the1812** [comment]
只剩下本脚本和解除区域限制脚本试试 其他的扩展关掉

**Comment by txy1212** [comment]
只用脚本能正常打开，那就是插件冲突?B站相关有：哔哩哔哩助手和pakku

Grant Howard <notifications@github.com> 于2020年6月10日周三 上午11:32写道：

**Comment by txy1212** [comment]
又看了一下是动态中的港澳台打不开...而番剧时间表中的港澳台番剧可以打开

HY T <u14334@gmail.com> 于2020年6月10日周三 上午11:46写道：

**Comment by Coulomb-G** [comment]
哔哩哔哩助手也有解除区域相关的功能,另外港澳台插件的不稳定应该和本脚本无关

**Comment by txy1212** [comment]
当季港澳台番能正常打开，后续上新的旧番，图片中为银魂，使用脚本，打开失败，关闭后正常。
关闭脚本后：[image: TIM截图20200610120927.png]
[image: TIM截图20200610120754.png]
[image: TIM截图20200610120722.png]

Coulomb-G <notifications@github.com> 于2020年6月10日周三 下午12:03写道：

**Comment by the1812** [comment]
请不要用邮件发图 我们看不见的

**Comment by txy1212** [comment]
关闭脚本![TIM截图20200610120927](https://user-images.githubusercontent.com/65844181/84363666-a74ce280-ac01-11ea-98b1-09d8ee272e4a.png)

打开脚本![TIM截图20200610120754](https://user-images.githubusercontent.com/65844181/84363673-a9af3c80-ac01-11ea-89ed-fb64f3cf68ab.png)
![TIM截图20200610120722](https://user-images.githubusercontent.com/65844181/84363675-aae06980-ac01-11ea-811e-b978b8a3d377.png)

**Comment by the1812** [comment]
![TIM截图20200610120927](https://user-images.githubusercontent.com/65844181/84363666-a74ce280-ac01-11ea-98b1-09d8ee272e4a.png)
![TIM截图20200610120722](https://user-images.githubusercontent.com/65844181/84363675-aae06980-ac01-11ea-811e-b978b8a3d377.png)

这两个打开后的网址是一样的吗?

**Comment by txy1212** [comment]
一样的界面   成功就到播放界面  失败的话就是我最先反馈的那样

Grant Howard <notifications@github.com> 于2020年6月12日周五 上午10:35写道：

**Comment by the1812** [comment]
不是问你界面 我问的网址

**Comment by txy1212** [comment]
一样

Grant Howard <notifications@github.com> 于2020年6月13日周六 下午4:38写道：

**Comment by Coulomb-G** [comment]
去找港澳台脚本的作者反馈吧,我这边都是正常打开,旧番也一样打得开
