### ISSUE TITLE
播放器置顶打开后自动定位 位置错误

### ISSUE THREAD

**Issue by lyineee** [the1812/Bilibili-Evolved#611]
**关于哪一项功能**
播放器置顶

**问题描述**

同时打开播放器置顶和自动定位到播放器以后，网页会定位到视频标题那里
**脚本版本**

预览离线版 v694.24

**浏览器版本**

Chrome 83.0.4103.97

**附加截图**
![nZ7QSafyyY](https://user-images.githubusercontent.com/19832762/84253800-f3851d80-ab42-11ea-90ab-05f53715bbd1.gif)

**Comment by the1812** [comment]
都置顶了还需要定位吗?  而且你可以修改定位偏移量

**Comment by lyineee** [comment]
也是ヾ(≧▽≦*)o，主要我一直没意识到是这个是定位播放器的锅，感觉这个坑别人也会踩。那我先关了这个issue吧。
