### ISSUE TITLE
【请添加】相关动态...自动展开选项

### ISSUE THREAD

**Issue by Noah1995** [the1812/Bilibili-Evolved#615]
1丶请添加【相关动态】自动展开选项
![【2020-06-11】【23∶33∶37】](https://user-images.githubusercontent.com/25548230/84406473-2a8b2a00-ac3c-11ea-8b95-4b347a36ad78.jpg)

2丶能否让全部动态都显示?
只有显示一行好麻烦...
鼠标移到元素上自动全部展开伸缩这样...
![【2020-06-11】【23∶36∶36】](https://user-images.githubusercontent.com/25548230/84406773-9372a200-ac3c-11ea-8abc-4116532f64b0.jpg)

**Comment by Geeyun-JY3** [comment]
#
