### ISSUE TITLE
4K视频下载bug

### ISSUE THREAD

**Issue by EA-DICE** [the1812/Bilibili-Evolved#619]
**关于哪一项功能**
关于4K视频的下载

**问题描述**

BV1kT4y1E75u
**脚本版本**

在线预览版1.10.28

**浏览器版本**

chrome83

**错误信息**

仅可以下载1080p+清晰度
**附加截图**
![image](https://user-images.githubusercontent.com/42771283/84559831-b9995e80-ad70-11ea-99cd-7dbe5876f220.png)
![image](https://user-images.githubusercontent.com/42771283/84559838-c0c06c80-ad70-11ea-93d9-4c6e259e58b6.png)

**Comment by the1812** [comment]
FLV没有4K

**Comment by EA-DICE** [comment]
已知悉，感谢回复
