### ISSUE TITLE
关于视频下载格式的问题

### ISSUE THREAD

**Issue by Eternal-Br** [the1812/Bilibili-Evolved#62]
**视频下载下来是.flv格式的**

**期望能直接下载为.mp4或者.avi等主流格式**

**脚本版本：正式版**

**Comment by the1812** [comment]
b站只开放了flv格式的下载, 要mp4只能转格式了. (准确的说是高清只有flv, mp4的资源只有240P)
如果在浏览器里用脚本做这个转换, 那个转换器(videoconverter.js)加载一下要一两分钟, 一个360P 30秒的视频要转换将近两分钟(下载只要2秒), 效率非常低.
所以可以用其他本地软件(HandBrake, FFmpeg之类的)把flv转换为mp4, 速度会快很多.

**Comment by Eternal-Br** [comment]
了解，感谢！
