### ISSUE TITLE
希望添加“下载MP4视频“功能”

### ISSUE THREAD

**Issue by RuikangSun** [the1812/Bilibili-Evolved#624]
**关于哪一项功能**
下载视频

**期望的效果**
希望能添加 将下载到的DASH文件中的 “mp4视频+m4a音频” 自动合并为 具有音频的mp4文件。
个人认为 基于ffmpeg等库 不难实现，但 添加该功能 对于普通用户来说 会方便不少。

**脚本版本**
20200614船新版本

**Comment by Coulomb-G** [comment]
那你有实现自动合并的方法吗?

**Comment by RuikangSun** [comment]
> 
> 
> 那你有实现自动合并的方法吗?

ffmpeg应该可以把视频流与音频流合并的

**Comment by the1812** [comment]
浏览器里跑ffmpeg可不好弄
今年内应该不会做出来

**Comment by RuikangSun** [comment]
> 
> 
> 浏览器里跑ffmpeg可不好弄
> 今年内应该不会做出来

也是哈，那样的话我觉得可以另行开发一个视频合并的小工具，应该挺简单的

**Comment by the1812** [comment]
合并交给本地的ffmpeg就行了

**Comment by RuikangSun** [comment]
> 
> 
> 合并交给本地的ffmpeg就行了

有没有现成的带用户界面的本地工具呢？

**Comment by Coulomb-G** [comment]
直接在GitHub搜ffmpeg GUI,至于哪个好用,我这边没界面需求也没研究过

**Comment by Cansll** [comment]
> 浏览器里跑ffmpeg可不好弄

仅仅是关于浏览器跑ffmpeg来合并视频，我看到的另一个脚本做到了这一点，也许有参考意义
[本地 YouTube 下载器](https://greasyfork.org/scripts/369400)

**Comment by RuikangSun** [comment]
> 
> 
> > 浏览器里跑ffmpeg可不好弄
> 
> 仅仅是关于浏览器跑ffmpeg来合并视频，我看到的另一个脚本做到了这一点，也许有参考意义
> [本地 YouTube 下载器](https://greasyfork.org/scripts/369400)

Y2B下载器的逻辑好像是网页插件+本地软件自动解决格式问题

**Comment by the1812** [comment]
那个下载器我看了一下, 应该可以在浏览器里合并x264编码的视频, 未来的版本可能会考虑加入
但是还是会有些问题:
- 浏览器内合并可能要占两倍的内存(输入文件和输出文件), Chrome一个标签页最多1G左右, 再多会崩. 而本地跑ffmpeg基本不占内存.
- b站这两年的视频都是支持x265的编码, 通常也是我下载时的首选(因为体积小), 但这个ffmpeg库似乎不支持.

所以还是本地的好用(

**Comment by Cansll** [comment]
确实很占内存 而且最近用那个去下油管视频经常失败，不知道是不是我这边的问题，我觉得不够稳定

对格式有要求其实到本地转码就好了，好多软件都可以批量合并的，确实是本地好用

只是提供一个参考，哈哈
