### ISSUE TITLE
一些无关紧要的细节问题

### ISSUE THREAD

**Issue by shenzhiming88** [the1812/Bilibili-Evolved#626]
**关于哪一项功能**

①“设置”
②“逐帧调整”的按钮备注

**实际的效果**
当然这两个问题一点儿都不影响脚本的效果，只是希望追求完美而已

①
希望可以一次只能选择一个下拉一个选择框，不然会出现如图所示的情况，影响美观
![image](https://user-images.githubusercontent.com/66902050/84589304-26d7ed00-ae60-11ea-9206-0e7ce12affdc.png)

②注意观察原生的按钮显示的备注与该脚本添加的按钮显示的备注：
![image](https://user-images.githubusercontent.com/66902050/84589434-0e1c0700-ae61-11ea-9774-8122b7798c48.png)
![image](https://user-images.githubusercontent.com/66902050/84589465-3277e380-ae61-11ea-90d5-62ebeca894b8.png)

希望该脚本添加的按钮显示的备注可以与原生的按钮一样

☆⌒(*＾-゜)v THX!!

**脚本版本**
1.10.26

**Comment by Geeyun-JY3** [comment]
懒得再开 issue 了，反正也是属于设置项的细节问题，所以就发这了。

希望在打开 样式 > 主题颜色 的颜色选择面板后，点击面板外围区域能先收起面板
![image](https://user-images.githubusercontent.com/49396421/99739637-2d9e1680-2b08-11eb-824d-cb1ff04959c7.png)

**Comment by Geeyun-JY3** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/626#issuecomment-730717345 的这个修复有些问题啊，点外围区域的同时还会关掉开关，容易误操作。

**Comment by the1812** [comment]
确实 还要加个透明图层挡住后面的开关?

**Comment by Geeyun-JY3** [comment]
嗯
