### ISSUE TITLE
希望“顶栏-动态-视频”能够增加上传时间显示。

### ISSUE THREAD

**Issue by peace-max** [the1812/Bilibili-Evolved#628]
**关于哪一项功能**

希望“顶栏-动态-视频”能够增加上传时间显示。
**期望的效果**
最新版增加无限刷新动态之后，感觉更加好用。连去动态页面都可以省了。
但是没有时间显示的话，还是稍微有点不太方便。

**脚本版本**
1.10.28

**Comment by kethoven** [comment]
@the1812 感觉上传时间可以简化一下。直接用24小时制。具体到分就可以。上午和下午也不用标出来。年份也可以不标出。
就像2021年2月8日  凌晨0:10:10  
目前脚本显示的是：2021/2/8 上午12:10:10
感觉可以简化为：2/8  0:10

**Comment by the1812** [comment]
那个就是鼠标放上去的时候显示的精细时间, 简化的就是鼠标没放上去时的`xxx小时前`

**Comment by kethoven** [comment]
> 
> 
> 那个就是鼠标放上去的时候显示的精细时间, 简化的就是鼠标没放上去时的`xxx小时前`

目前就是凌晨12点以后，会显示上午12点。感觉挺混淆的。直接24小时制可能更直观。

**Comment by kethoven** [comment]
> 
> 
> > 那个就是鼠标放上去的时候显示的精细时间, 简化的就是鼠标没放上去时的`xxx小时前`
> 
> 目前就是凌晨12点以后，会显示上午12点。感觉挺混淆的。直接24小时制可能更直观。没必要标注上午下午。

**Comment by the1812** [comment]
好吧 我再改一下 (其实12小时制是因为偷懒直接调用浏览器的日期显示
