### ISSUE TITLE
附加功能提供扩展接口或更进一步提供接口作为其他脚本框架

### ISSUE THREAD

**Issue by shugen002** [the1812/Bilibili-Evolved#63]
**关于哪一项功能**

可以提供个接口供其他脚本在附加功能处注册添加按钮作为功能入口或设置入口
或者
提供一些接口，例如生成个弹窗之类的
这样可以有更多人来增加附加功能

不要求短期提供大量接口，可以先从提供功能入口开始。

PS: 不是很喜欢现在的构建方式

**期望的效果**

**脚本版本**
预览版

**Comment by the1812** [comment]
可以啊, 等我性能调优做完了会慢慢加的.
(目前也有一些开放的API在`window.bilibiliEvolved`对象里)

**Comment by the1812** [comment]
最近总算找时间把API文档摸完了...
- [附加功能](https://github.com/the1812/Bilibili-Evolved/wiki/%E9%99%84%E5%8A%A0%E6%96%B0%E5%8A%9F%E8%83%BD)
- [API文档](https://github.com/the1812/Bilibili-Evolved/wiki/API%E5%8F%82%E8%80%83%E6%96%87%E6%A1%A3)

虽然开放的接口并不算多, 还是希望能帮到你.
