### ISSUE TITLE
脚本在动态首页失效

### ISSUE THREAD

**Issue by kethoven** [the1812/Bilibili-Evolved#634]
**关于哪一项功能**
脚本在动态首页失效

**问题描述**

脚本在动态首页失效，在其他页面目前倒是没有什么问题。
我自己在动态页面安装的两个脚本，另一个动态分组的脚本“b站时间线筛选”，都在今天失效了，感觉应该是B站，动态页面改动过。

**脚本版本**

预览版本最新版

**浏览器版本**

360极速浏览器12.0

**错误信息**

**附加截图**
![360截图20200617134326068](https://user-images.githubusercontent.com/64629623/84860124-0ea2e080-b0a1-11ea-900e-040f44fbdfc4.jpg)
希望截图是对的。

**Comment by Coulomb-G** [comment]
你把另一个脚本关了再看看？

**Comment by kethoven** [comment]
> 你把另一个脚本关了再看看？

确实是两个脚本冲突了。关掉另外一个，B-E确实正常工作了。
