### ISSUE TITLE
按钮位置改变

### ISSUE THREAD

**Issue by H-Tung** [the1812/Bilibili-Evolved#637]
我的习惯是任务栏左侧隐藏，所以去点按钮经常不小心呼出任务栏，我觉着也没必要麻烦大佬专门加一个移动位置的功能，能告知一下怎么改就很感谢了❤❤

**Comment by the1812** [comment]
设置里可以改成放右边

**Comment by Coulomb-G** [comment]
使用前请阅读「README」部分的相关说明
设置面板中的「其他」类型中有「设置面板停靠位置」以及「侧栏垂直偏移量」

**Comment by H-Tung** [comment]
哦哦好的，之前没注意到
