### ISSUE TITLE
全屏画质模糊

### ISSUE THREAD

**Issue by StevenLxQAQ** [the1812/Bilibili-Evolved#638]
**关于哪一项功能**

**问题描述**

b站内视频全屏会变为网页全屏且画质模糊，分辨率非常低，甚至能看到像素级画质，刷新一下又会变好。经过排除法发现的确是此脚本的问题。不知其他人有无同样的问题

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by the1812** [comment]
你是不是开了默认全屏

**Comment by StevenLxQAQ** [comment]
> 你是不是开了默认全屏

没有

**Comment by StevenLxQAQ** [comment]
https://sm.ms/image/mOjGJnt2oDCypxX
这是我截的图

**Comment by the1812** [comment]
那我就不清楚了

**Comment by StevenLxQAQ** [comment]
> 那我就不清楚了

仔细了看了readme.md 可能是因为我同时开了”解除b站区域限制“的问题
thx~
