### ISSUE TITLE
4k视频下载

### ISSUE THREAD

**Issue by jhc2414169248** [the1812/Bilibili-Evolved#640]
**关于哪一项功能**
4k视频下载出现了问题

**问题描述**
只要在av925936557用dash下的h.264下载4k视频，就会报错，错误代码416

**脚本版本**
正式版1.10.26

**浏览器版本**
chrome 83.0.4103.106

**错误信息**
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/seed/jinkela/header-v2/header.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**附加截图**

![无标题](https://user-images.githubusercontent.com/21095721/84988541-c523c580-b174-11ea-887d-4f81baae837a.png)

**Comment by jhc2414169248** [comment]
更新：目前看来是所有的4k视频都不能正常下载
![image](https://user-images.githubusercontent.com/21095721/84988866-51ce8380-b175-11ea-9c7f-85c16510c785.png)

**Comment by the1812** [comment]
4K请不要用`直接下载`, 用下面的导出

**Comment by jhc2414169248** [comment]
> 4K请不要用`直接下载`, 用下面的导出

好的，本地配置aria2c后成功下载完成，感谢
![image](https://user-images.githubusercontent.com/21095721/84991087-9f98bb00-b178-11ea-87a3-50feb4ea1636.png)
