### ISSUE TITLE
反馈一个BUG！！！

### ISSUE THREAD

**Issue by 2498966969** [the1812/Bilibili-Evolved#647]
主页加载不出“活动
![QQ图片20200621105753](https://user-images.githubusercontent.com/57282666/85215629-208cc800-b3ae-11ea-9b7c-54070b6c6b39.png)
”

**Comment by the1812** [comment]
看看是不是和 #330 一样?

**Comment by the1812** [comment]
以及是否跟AdGuard有关

**Comment by 2498966969** [comment]
问题已经解决，就是AdGuard的问题，谢谢!！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Grant Howard"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月21日(星期天) 中午11:01
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;" "<2498966969@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 反馈一个BUG！！！ (#647)





 
以及是否跟AdGuard有关
