### ISSUE TITLE
关于简化首页-极简模式下，自定义视频数量的建议

### ISSUE THREAD

**Issue by abc1044** [the1812/Bilibili-Evolved#648]
**关于哪一项功能**

简化首页-极简

**期望的效果**
新增自定义显示视频数量
（点击[查看更多]就会跳转动态页面，但是我觉得[简化首页-极简]模式很好看...是否可以直接在这个模式下自定义加载的视频数量，或者直接瀑布式加载更多视频）

**脚本版本**
stable v1.10.26

**Comment by the1812** [comment]
可以瀑布式 最近刚在动态弹窗那边实验过
