### ISSUE TITLE
针对 `https://www.bilibili.com/s/video/xxxx` 页的若干功能适配

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#649]
**关于哪一项功能**
夜间模式、网址 AV 号转换、BiliPlus 跳转支持等；
增加清除此类网址 `/s` 参数功能

**期望的效果**
请求适配格式为 `https://www.bilibili.com/s/video/xxxxxxxx` 的 [据说](https://t.bilibili.com/383325431737263645) 的 SEO page，在可实现的前提下功能尽量与常规视频页保持一致，如夜间模式、网址 AV 号转换、BiliPlus 跳转支持、附加功能中会显示当前视频的 AV 号和 BV 号等；
现在 Google 的搜索结果越来越多是这种格式，所以希望还能增加清除此类网址 `/s` 参数功能（即跳转至格式为 `https://www.bilibili.com/video/xxxxxxxx` 的常规视频页）

**脚本版本**
正式版 v1.10.26
预览离线版

**Comment by the1812** [comment]
我能直接跳回普通视频页吗 (这样就不用搬运那些功能了

**Comment by Geeyun-JY3** [comment]
> 我能直接跳回普通视频页吗 (这样就不用搬运那些功能了

我能说那些功能不如有空的时候一点一点搬吗🙊（bushi
（我稍微比较 care 的是夜间模式的适配，脚本现在的版本有部分元素是生效了的，但白色一块一块还是的不少，从 Google 搜索结果进入再跳转的过程怕被闪瞎🙈

**Comment by the1812** [comment]
夜间写起来累人啊
不如把google搜索结果换成普通视频页吧

**Comment by Geeyun-JY3** [comment]
> 夜间写起来累人啊
> 不如把google搜索结果换成普通视频页吧

一开始我就希望提供一个跳转至普通视频页的选项鸭
（其他功能要是一时半会做不来以后做不做就看心情吧，辛苦了
