### ISSUE TITLE
视频调整位置不准

### ISSUE THREAD

**Issue by Caelestrasz** [the1812/Bilibili-Evolved#65]
**关于哪一项功能**
打开视频自动调节位置（明明像实现的功能？？）

**问题描述**
1、番剧的调节位置没有包括发弹幕的框，不完整（截图1）
2、如果一直看视频调节位置正常（截图2），看了番剧之后视频调节位置向上偏移，视频不完整（截图三），清理缓存之后恢复正常，但一看番剧就出问题
3、两者选择的都是新版

**脚本版本**
<正式版1.7.0>

**浏览器版本**
Chrome 72.0.3626.96

**附加截图**
截图1
![image](https://user-images.githubusercontent.com/25895906/52414761-25860a00-2b20-11e9-800b-a0800627bf51.png)
截图2
![image](https://user-images.githubusercontent.com/25895906/52414849-5e25e380-2b20-11e9-9073-0bffc51484f6.png)
截图3
![image](https://user-images.githubusercontent.com/25895906/52414901-844b8380-2b20-11e9-9a69-27bff5b597ca.png)

**Comment by the1812** [comment]
哪个功能会调节位置了? 如果是指默认播放器模式设定宽屏时视频位置不居中, 那位置也不是脚本调的, 脚本只是自动点了一下那个宽屏按钮.
你可以试试手动点宽屏按钮, 视频的会调位置, 番剧的不会, 这可以解释问题1.
但是这个调位置为什么一看番剧后视频就会调错, 我也不是很清楚, 位置确实变化了, 但是这个位置正好包括了标题和up那行. 我能想到有些关系的, 就是2018年的时候新版播放器界面标题和up是在视频下面的, 调成那个位置就刚好是视频.
总之, 如果你很在意这个位置, 我可以加个调位置的功能.

**Comment by jackychao0226** [comment]
确实是正好包括了标题和up。但我关了脚本，退出宽屏清除缓存后试了一下，如果自己手动点击宽屏按钮不论视频和番剧都能对到正确的位置哎，不知道自动点击为什么会去到错误的位置。如果能自动调整到位置那就好了，谢谢。

**Comment by the1812** [comment]
现在选宽屏后脚本会让播放器居于页面中央, 你觉得这样可以吗?

**Comment by Caelestrasz** [comment]
我清除缓存升级到1.7.4还是老样子啊，播放器没有对到中央，你那边可以了？

**Comment by the1812** [comment]
我那边可以了啊, 你用离线版试试(排除浏览器仍有缓存的可能)

**Comment by Caelestrasz** [comment]
不行，番剧第一次有时能成功调到正确位置，看视频完全对不到，第二次刷新全都对不到正确位置。而且我上次没发现再选常规模式刷新网页，还是回到宽屏的错误位置，也就是选择播放器模式最多使用一次之后就失效了，感觉点不到正确位置。。。离线preview版和正式版都试过都是一样。

**Comment by the1812** [comment]
选常规的话就什么都不做了, 不点按钮也不调位置, 即使这样位置还会变的话, 难道是有别的东西影响了位置?

**Comment by Caelestrasz** [comment]
什么都不做对吗？我这里就算把所有扩展关掉，bilibili也是能记住上次选了宽屏还是常规的。。。就是我这次如果变成宽屏了，打开其他番剧和视频都是宽屏的，只有我手动再点成常规然后所有视频才恢复常规的

**Comment by the1812** [comment]
Σ( ￣□￣||) 我关掉所有扩展, b站是不会记住播放器的模式的, 每次打开都会是常规的...
你那的控制台有报什么错吗 (`F12`或`Ctrl+Shift+I`打开开发者工具, 里面的`Console`)

**Comment by Caelestrasz** [comment]
清除了网页cookies之后终于好了。。。后来不知道按了哪个功能又出现了一次（没试出来）然后又清了一次cookies。不好意思，这个暂时应该没问题了。
还有一个问题每次弹幕设置会弹出来是为了点击记住的设置吗？记住防挡字幕是不是还没实现？

**Comment by the1812** [comment]
是的, 我有计划在那时候暂时隐藏一下弹幕设置, 每次弹出来也不太好.
目前只有上面那5种弹幕类型可以记住, 防档字幕还没加, 需要的话也可以下次加上.

**Comment by the1812** [comment]
防挡字幕现在可以记住了
