### ISSUE TITLE
清爽主页   平滑滚动

### ISSUE THREAD

**Issue by SouLXH** [the1812/Bilibili-Evolved#650]
**关于哪一项功能**

**问题描述**

清爽和精简主页不能平滑滚动
可以滚动，但是阻尼感太强，并且是分段式的滚动，   

**脚本版本**

最新版
1.10.26

**浏览器版本**

版本 83.0.4103.97（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/44329481/85357209-616a1580-b543-11ea-90fd-c23472f87000.png)

**Comment by SouLXH** [comment]
![image](https://user-images.githubusercontent.com/44329481/85357328-a2fac080-b543-11ea-8e14-dba82d7645f4.png)

**Comment by the1812** [comment]
平滑滚动指什么? 我觉得用起来就是正常的滚动感觉啊, 没什么区别
