### ISSUE TITLE
希望直播功能的一个改进

### ISSUE THREAD

**Issue by freejool** [the1812/Bilibili-Evolved#652]
关于哪一项功能
这几天b站有些主播开启了PK功能很是碍眼，不过好像是嵌入播放器的，不知道大佬能否移除这个框
类似这个：![image](https://user-images.githubusercontent.com/39995589/85411102-82118a00-b59a-11ea-8659-b5832b2d0182.png)

脚本版本
1.10.26

**Comment by 31415926loli** [comment]
目前查到一个办法，手动在控制台输入
document.getElementById('chaos-pk-vm').style.opacity=0
