### ISSUE TITLE
关于自定义顶栏的「主站」组件建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#657]
**关于哪一项功能**
自定义顶栏

**期望的效果**
自定义顶栏的「主站」组件添加「课堂」入口；
（这个组件是和官方视频页下的「主站」组件保持一致的吗？如果是现在只是没跟进调整当我上面没说。不过我觉得现在的专题入口可以保留，也不必和官方完全一致）

最近的发现的一些子分区调整：娱乐区的「Korea相关」子分区没了（没问客服是不是在升级维护），音乐区多了一个「说唱」子分区，生活区的「搞笑」子分区问了客服说是在升级维护所以暂时不可见。

顺便想问一下在「主站」组件下鼠标悬停在分区上展开的子分区显示不全怎么破？这是我屏幕分辨率的问题，脚本也无能为力，还是说脚本可以解决？
附我的使用效果（游戏区的最后一个子分区也是没显示全的，但还能点击到所以我就懒得截图了）：
![生活](https://user-images.githubusercontent.com/49396421/85650717-b0957f00-b6d8-11ea-9955-a9a42bfaf7e0.png)
![时尚](https://user-images.githubusercontent.com/49396421/85650745-be4b0480-b6d8-11ea-8287-26b8c44573aa.png)

或者像官方一样减少每列的分区数量以减少这个组件展开后的高度，增加宽度（每个分区的间隔倒不必像官方那么大，分多一列或者别让第一列排太多分区就行了）会不会好一点？这样鼠标也不用下移太多距离。
附官方效果：
![image](https://user-images.githubusercontent.com/49396421/85650550-5dbbc780-b6d8-11ea-82f0-f90a247bbc87.png)

**脚本版本**
正式版 v1.10.26
预览离线版

**Comment by the1812** [comment]
是没跟进调整, Koera相关那个就是最近的一次分区调整去掉的
子分区的话是你屏幕高度太小, 加上固定了顶栏没法往下滚动造成的, 也许我可以试试把子分区分成两列

**Comment by Geeyun-JY3** [comment]
> 是没跟进调整, Koera相关那个就是最近的一次分区调整去掉的
> 子分区的话是你屏幕高度太小, 加上固定了顶栏没法往下滚动造成的, 也许我可以试试把子分区分成两列

固定顶栏还是我提的🤦‍♂️（某种意义上的自作自受🤦‍♂️）
我个人还是更倾向于减少每列的分区数量以减少每一列的高度，子分区分成两列移动鼠标的时候会不会因为宽度太大而容易触发到别的分区？

**Comment by the1812** [comment]
减少列高就会增大宽度, 又会导致有一部分超出屏幕外的
子分区有防抖一般不会误触别的分区

**Comment by Geeyun-JY3** [comment]
> 减少列高就会增大宽度, 又会导致有一部分超出屏幕外的
> 子分区有防抖一般不会误触别的分区

那好吧

**Comment by Geeyun-JY3** [comment]
顺便提一下今天发现个挺奇怪的活动页：[哔哩哔哩有求必应屋](https://www.bilibili.com/blackboard/act_fashion.html)（在用 UWP 客户端发现的，客户端内打不开所以用浏览器打开，应该是为手机适配的）
自定义顶栏的主站、用户信息、消息、订阅、稍后再看、收藏、历史、投稿组件鼠标悬浮展示的菜单背景都会变透明，侧栏设置菜单显示也很奇怪，不知道觉得这有没必要适配。
附个侧栏设置菜单的异常截图：
![image](https://user-images.githubusercontent.com/49396421/85919318-b6d45880-b89c-11ea-877a-5cef7af9c491.png)

**Comment by Coulomb-G** [comment]
手机页面请用手机打开,网页端b站自己都不做适配

**Comment by Geeyun-JY3** [comment]
> 手机页面请用手机打开,网页端b站自己都不做适配

好的吧

**Comment by Geeyun-JY3** [comment]
提醒一下，记得跟进本 issue 提到的子分区调整

**Comment by Geeyun-JY3** [comment]
啊忘问了这里提到的固定自定义顶栏后子分区显示不全的问题还考虑解决吗？
