### ISSUE TITLE
希望增加 发弹幕的快捷键

### ISSUE THREAD

**Issue by kethoven** [the1812/Bilibili-Evolved#659]
**关于哪一项功能**

希望增加 发弹幕的快捷键

**期望的效果**
目前发弹幕，需要首先移动鼠标到弹幕栏，点击鼠标。然后再双手放到键盘上，打字。
希望能够直接增加快捷键，直接用键盘操作完成。能够带来挺大的方便。

**脚本版本**
最新版本

**Comment by Coulomb-G** [comment]
enter就是发弹幕的快捷键
