### ISSUE TITLE
开启"播放前显示封面"、番剧自动播放下一集时，播放器中封面不会消失

### ISSUE THREAD

**Issue by Cirn09** [the1812/Bilibili-Evolved#661]
**关于哪一项功能**
播放前显示封面

**问题描述**
开启"播放前显示封面"，番剧自动播放下一集、且下一集没有播放过的情况下，播放器中会一直显示封面，手动暂停-播放可以恢复正常。
已经播放过的就不会显示封面，普通视频自动播放下一P没问题，播放列表自动播放下一视频也没问题。

**脚本版本**
1.10.29

**浏览器版本**
Edge 83

**错误信息**
无

**附加截图**

**Comment by the1812** [comment]
早上修复了一下
可以重新装一遍1.10.29看看 (记得备份设置)
或者等之后热更新推送

**Comment by Cirn09** [comment]
OK，正常了
