### ISSUE TITLE
“播放前显示封面”存在bug

### ISSUE THREAD

**Issue by sunfkny** [the1812/Bilibili-Evolved#662]
**关于哪一项功能**
播放前显示封面

**问题描述**

打开任意[番剧](https://www.bilibili.com/anime/)/[电视剧](https://www.bilibili.com/tv/)/[纪录片](https://www.bilibili.com/documentary/)
1. 不播放的情况下手动切换分P，封面不能在播放后自动消失，普通视频也有这个bug，自动切P无此bug
2. 播放后手动切换分P，此时并没有开始播放，可以显示封面但不显示封面

https://github.com/the1812/Bilibili-Evolved/issues/661#issuecomment-649941807 看到了，已经重装，问题依旧存在

**脚本版本**

正式版1.10.29

**浏览器版本**

Google Chrome 已是最新版本
版本 83.0.4103.116（正式版本） （64 位）

**Comment by the1812** [comment]
已修复 可以再重装试试
https://lunatic-kingdom.imfast.io/bilibili-evolved.user.js

**Comment by sunfkny** [comment]
番剧/电视剧/纪录片好了，普通多P视频不播放时切换分P，封面不消失bug依旧存在

**Comment by the1812** [comment]
我又换了种检测方法 (但愿能行\_(:3」∠)\_
