### ISSUE TITLE
高画质视频下载后网页崩溃没有方法解决吗

### ISSUE THREAD

**Issue by kdvslj** [the1812/Bilibili-Evolved#665]

**Comment by the1812** [comment]
<img src="https://user-images.githubusercontent.com/26504152/85918180-f433e880-b892-11ea-9441-433eb9c75b20.png" height="400">

**Comment by kdvslj** [comment]
请问我点击导出到了aria2之后是一个txt文件，
![image](https://user-images.githubusercontent.com/34133424/85919241-357cc600-b89c-11ea-9e75-019a9940a733.png)
我应该复制哪些内容到aria2下载

**Comment by the1812** [comment]
这有说明
https://github.com/the1812/Bilibili-Evolved/blob/master/aria2-notice.md
