### ISSUE TITLE
为什么可以看“当前在线”的功能没有了

### ISSUE THREAD

**Issue by converk** [the1812/Bilibili-Evolved#667]
之前在"动态"那一行可以看目前在线人数，这两天看不到了

**Comment by Geeyun-JY3** [comment]
[更新日志](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.10.29)有写：
![image](https://user-images.githubusercontent.com/49396421/85924939-0c722a80-b8c8-11ea-81c4-d48f9018e2d5.png)
