### ISSUE TITLE
首页顶栏 收藏窗口弹出异常

### ISSUE THREAD

**Issue by LeoneKuma** [the1812/Bilibili-Evolved#669]
**关于哪一项功能**

首页顶栏 收藏窗口弹出异常

**问题描述**

收藏窗口弹出过一次后，鼠标指针移动到首页推荐视频的封面上，收藏窗口会弹出。

- 复现方式：鼠标指针移动到顶栏收藏后，弹出收藏窗口，鼠标移开后收藏窗口收起。
随后鼠标指针移动到收藏窗口之前弹出的区域上（也就是首页视频推荐的封面区域），会直接弹出收藏窗口。

**脚本版本**

正式版 1.10.29

**浏览器版本**

Safari 13.1.1

**附加截图**

如图，我鼠标指针是位于右下角视频的封面上的，收藏窗口直接弹出了，很影响正常使用。
<img width="813" alt="截屏2020-06-27 下午10 30 10" src="https://user-images.githubusercontent.com/47859528/85924621-054a1d00-b8c6-11ea-986b-499682087d14.png">

**Comment by the1812** [comment]
只有收藏是这样吗 挺奇怪的 顶栏每个窗口都是一样的方式弹出收起的
不过我没有Mac 也没法在Safari里试试

**Comment by LeoneKuma** [comment]
> 只有收藏是这样吗 挺奇怪的 顶栏每个窗口都是一样的方式弹出收起的
> 不过我没有Mac 也没法在Safari里试试

其他窗口没问题，只有收藏窗口有问题。
我拿chrome也测了下，chrome下没问题，就很奇怪，油猴其他插件也关了。

**Comment by LeoneKuma** [comment]
mac系统升级到11.0.1 Big Sur，safari浏览器版本升级到14.0.1后问题消失。
脚本版本Stable v1.11.0。
之前可能是浏览器的bug吧。
