### ISSUE TITLE
关于番剧自动从历史记录点播放的bug

### ISSUE THREAD

**Issue by 11111111111ge1** [the1812/Bilibili-Evolved#67]
例如说，我在五等分的第四集看到了22分，当我点击第五集的连接后，会识别为我在第五集看了22分钟，并自动跳转至第五集的二十二分
**脚本版本**
1.7.4
**浏览器版本**
 71.0.3578.98（正式版本） （64 位）

**Comment by the1812** [comment]
这个我也很头疼, b站的这个历史记录点光记时间不记集数, 脚本只是看到有跳转播放就点一下.
建议跟官方反馈一下这个不记集数的问题吧, 我这里就算再改动也是治标不治本.

**Comment by ZCXLLOD** [comment]
@the1812 
应该是脚本的问题，正常没有使用脚本时看到第一集，新打开其他集时有提示上次看到第几集的哪个时间点，点击即可跳转到相应集数的相应时间点，而开启并使用脚本的“自动从历史记录点播放”功能后只能跳转到当前视频的相应时间点，无法跳转到相应的集数。
使用脚本前：
![360 20190209144634880](https://user-images.githubusercontent.com/19368077/52517745-d30d3080-2c7a-11e9-9546-7e50bc050ed7.jpg)

使用脚本的相关功能后：
![360 20190209145524731](https://user-images.githubusercontent.com/19368077/52517746-d3a5c700-2c7a-11e9-9010-e7af8fd4d701.jpg)

**Comment by the1812** [comment]
好吧 是我瞎了23333

**Comment by ZCXLLOD** [comment]
。。。

**Comment by the1812** [comment]
修复了, 不过这种跨集跳转刷新了播放器, 跳完就没有那个从头开始的提示了, 不介意吧?

**Comment by ZCXLLOD** [comment]
@the1812 
看到了，离线和预览离线版有更新，确实跳转正常了，但我这边跳转过去后视频处于播放状态但画面不动，声音没有，弹幕没有，需暂停再播放才行，不使用脚本手动点击跳转过去是可以正常自动播放的。。。

并不介意，使用自动跳转功能就是为了省事，从头播放点进度条和之前点按钮没有什么区别。

**Comment by the1812** [comment]
我没试出来你那种情况...我跳过去就正常播放了, 有报什么[错误](https://github.com/the1812/Bilibili-Evolved/wiki/%E6%9F%A5%E7%9C%8B%E6%B5%8F%E8%A7%88%E5%99%A8%E8%BE%93%E5%87%BA%E7%9A%84%E4%BF%A1%E6%81%AF)吗?

**Comment by ZCXLLOD** [comment]
@the1812 
今天又看了一下，发现是我这边谷歌浏览器的问题，不知道为什么，脚本正式版 1.7.4，谷歌浏览器 72.0.3626.96（正式版本） （64 位）跳转过去就卡住了，360安全浏览器 10.0.1634.0（chrome内核 63.0.3239.132）极速模式跳转过去就是正常自动播放。
谷歌浏览器旧版播放器无痕浏览
![360 20190210142848235](https://user-images.githubusercontent.com/19368077/52530435-c2bf8900-2d40-11e9-8aa5-86930b4da773.jpg)
![360 20190210142908677](https://user-images.githubusercontent.com/19368077/52530436-c3581f80-2d40-11e9-861f-dd5d38948cd8.jpg)

谷歌浏览器旧版播放器使用脚本
![360 20190210143707323](https://user-images.githubusercontent.com/19368077/52530494-a3752b80-2d41-11e9-9fec-2d053ec7f31b.jpg)

谷歌浏览器新版播放器无痕浏览
![360 20190210143822141](https://user-images.githubusercontent.com/19368077/52530495-a4a65880-2d41-11e9-8765-08ac2da58b63.jpg)

谷歌浏览器新版播放器使用脚本（跳转后不会自动播放，视频处于暂停状态，正常来说是会自动播放的）
![360 20190210143840851](https://user-images.githubusercontent.com/19368077/52530544-9b69bb80-2d42-11e9-8e5d-50dff5f10a2f.jpg)

360安全浏览器旧版播放器无痕浏览
![360 20190210144223610](https://user-images.githubusercontent.com/19368077/52530552-b9cfb700-2d42-11e9-894a-f92c19c96bd8.jpg)

360安全浏览器旧版播放器使用脚本
![360 20190210144310694](https://user-images.githubusercontent.com/19368077/52530553-b9cfb700-2d42-11e9-91da-07c5291c44e0.jpg)

**Comment by the1812** [comment]
辛苦了, Console里倒没发现什么来自脚本的异常消息, 我之后加个跳转完再自动点播放吧

**Comment by ZCXLLOD** [comment]
。。又看了一下，开启自动播放视频功能，在谷歌浏览器中旧版和新版播放器只有在第一次打开的时候会自动播放，再刷新网页后就不会了，而且跳转后也不会自动播放，但360安全浏览器正常，使用脚本的时候也没有使用其他浏览器扩展和脚本，是不是我谷歌浏览器版本太高的原因？之前有听说高版本的谷歌浏览器改了一些接口。
谷歌浏览器无痕浏览
![360 20190211114922574](https://user-images.githubusercontent.com/19368077/52547416-85bbcb00-2e02-11e9-8844-3c550bdd5580.jpg)
谷歌浏览器使用脚本跳转
![360 20190211114931155](https://user-images.githubusercontent.com/19368077/52547418-86546180-2e02-11e9-9f61-e505d7f7b8e3.jpg)
谷歌浏览器使用脚本第一次打开
![360 20190211124503967](https://user-images.githubusercontent.com/19368077/52547419-86546180-2e02-11e9-9af4-b5c3aa9ccb5d.jpg)
谷歌浏览器使用脚本第一次打开后再刷新网页
![360 20190211124515745](https://user-images.githubusercontent.com/19368077/52547420-86ecf800-2e02-11e9-91ce-8dcf21a04c0a.jpg)

**Comment by the1812** [comment]
高版本也没改什么接口啊, 我用的就是Chrome 72, 输出里那个`Uncaught (in promise) DOMException`能展开看看吗?
(记录点跳转后播放我还没加呢...

**Comment by ZCXLLOD** [comment]
。。。
![360 20190211155828974](https://user-images.githubusercontent.com/19368077/52551070-f28c9080-2e15-11e9-8fa7-ffc82a597802.jpg)
![360 20190211155834538](https://user-images.githubusercontent.com/19368077/52551071-f28c9080-2e15-11e9-95ae-74eae788ff2c.jpg)

**Comment by the1812** [comment]
这个错误确实是来自脚本的, 但是我还是无法确定原因... 预览离线版也会报这个错吗?

**Comment by ZCXLLOD** [comment]
是的，预览离线版也同样。。

**Comment by the1812** [comment]
展开来也完全一样吗, 我还指望能从离线版得到具体点的错误信息, 完全一样的话我暂时想不出办法了...

**Comment by ZCXLLOD** [comment]
看了一下，正式版和预览离线版的错误有些不一样。
正式版
![360 20190213220146610](https://user-images.githubusercontent.com/19368077/52716988-ffa6ac80-2fda-11e9-9fbd-87a2ba45954f.jpg)
![360 20190213220155440](https://user-images.githubusercontent.com/19368077/52716989-ffa6ac80-2fda-11e9-84b5-17c18b518424.jpg)
预览离线版
![360 20190213220213347](https://user-images.githubusercontent.com/19368077/52717002-07fee780-2fdb-11e9-9130-192809c9baf3.jpg)

**Comment by the1812** [comment]
我还是没法找到错因, 根据之前的描述来看应该跟cookies有关(只有第一次进正常). 这个问题就暂时先挂着吧

**Comment by ZCXLLOD** [comment]
@the1812 
今天想起来这个问题又看了一下，发现这个问题我这边已经没有了，跳转过后视频有时候会有短暂（几秒）加载，但不会一直卡住。
-----
脚本：预览离线版（465.23）
浏览器：谷歌浏览器 78.0.3904.70（正式版本） （64 位）
播放器：B站旧版和新版播放器。

**Comment by ZCXLLOD** [comment]
。。。为啥字会这么大。

**Comment by the1812** [comment]
感谢测试 那我就当这个问题解决了
