### ISSUE TITLE
关于高分屏下简化首页-极简的两栏/三栏状态下的布局bug

### ISSUE THREAD

**Issue by abc1044** [the1812/Bilibili-Evolved#670]
**关于哪一项功能**
关于简化首页-极简的三栏状态下的布局bug
样式-简化首页-极简

**问题描述**

极简风格下，动态显示为两栏/三栏的情况下，网页高度较大的时候，视频和底部按钮中间会有一段bug空位。
（win10，2k屏，100%缩放，在页面高度较大的时候会出现，把页面高度调小后恢复正常。）

**脚本版本**

正式版 v1.10.29

**浏览器版本**

chrome83 64位

**错误信息**

**附加截图**
（网络不好，稍后上传）

**Comment by abc1044** [comment]
![bug1](https://user-images.githubusercontent.com/18114052/85941691-da5bd980-b956-11ea-9475-925121e90902.png)
![bug2](https://user-images.githubusercontent.com/18114052/85941694-e21b7e00-b956-11ea-9c5a-5fcc4328dfbc.png)
![bug3](https://user-images.githubusercontent.com/18114052/85941701-ea73b900-b956-11ea-86ee-14d138b7f450.png)
![bug4](https://user-images.githubusercontent.com/18114052/85941702-ec3d7c80-b956-11ea-8406-aadb586e17ea.png)

**Comment by the1812** [comment]
这里之后会改为无限滚动的 也就不会有这个问题了
