### ISSUE TITLE
删除动态卡片、动态相关页图标换用 MD 图标

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#671]
**关于哪一项功能**
删除动态卡片
动态相关页位图图标全部换用 MD 图标

**期望的效果**
删除动态页和个人空间「动态」tab 下（顺便也把动态详情页带上？）用户右上角的动态卡片装扮
![动态页](https://user-images.githubusercontent.com/49396421/85937555-30208980-b937-11ea-99b5-6a23b647bb93.png)
![个人空间「动态」tab](https://user-images.githubusercontent.com/49396421/85937530-ef287500-b936-11ea-9941-745971838df0.png)

动态页、个人空间「动态」tab 下和动态详情页下动态的三个图标（转发、评论、点赞）像简化评论区功能那样全部换用 MD 图标

**脚本版本**
正式版 v1.10.29
预览离线版

**Comment by the1812** [comment]
那三个不就是矢量的吗

**Comment by Geeyun-JY3** [comment]
> 那三个不就是矢量的吗

哦哦我不知道那三个就是矢量图标（尴尬
那能不能三个图标替换成 MD 图标，和简化评论区的图标统一

**Comment by the1812** [comment]
MD里这三个我觉得还不如b站的好看
![image](https://user-images.githubusercontent.com/26504152/85937867-16cd0c80-b93a-11ea-83ab-2cff7dff3338.png)

**Comment by Geeyun-JY3** [comment]
> MD里这三个我觉得还不如b站的好看
> ![image](https://user-images.githubusercontent.com/26504152/85937867-16cd0c80-b93a-11ea-83ab-2cff7dff3338.png)

emmm我主要是想着统一风格……
随你吧，我只是写着这个动态卡片突然有这么个想法就顺便也写下来了

**Comment by Geeyun-JY3** [comment]
啊这个动态卡片去除也不考虑做吗（悲

**Comment by the1812** [comment]
啊 光看到MD图标了
晚上回家再改一下

**Comment by Geeyun-JY3** [comment]
这个动态卡片是不是又忘了🌚

**Comment by the1812** [comment]
好像是的
