### ISSUE TITLE
未登录状态下动态相关页面夜间模式、主题颜色适配不完全

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#672]
**关于哪一项功能**
主题颜色和夜间模式

**问题描述**
未登录状态下动态相关页面夜间模式、主题颜色适配不完全，包括 [动态首页](https://t.bilibili.com)、动态详情页、个人空间「动态」tab 下

**脚本版本**
正式版 v1.10.29
预览离线版

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 83.0.4103.116（正式版本） （64 位）

**错误信息**

**附加截图**
以下均为未登录状态下的截图：
1. 动态详情页、个人空间「动态」tab 下展开评论区（普通视频页下方评论区就没这个问题，区别也不只是我框住的地方，应该是忘做了吧）：![动态详情页、个人空间「动态」tab 下](https://user-images.githubusercontent.com/49396421/85937869-22203800-b93a-11ea-8fd6-551b8d5529da.png)

2. 点击 [动态页](https://t.bilibili.com) 转发／评论／点赞／关注／举报等弹出的登录窗口（顺便一提在普通视频播放页点击弹幕栏处的登录弹出的也是这个）：![动态页](https://user-images.githubusercontent.com/49396421/85937848-e2595080-b939-11ea-9266-919b284bc780.png)

3. 动态详情页弹出的登录窗口（顺便一提在普通视频页下方评论区（即在 1.  提到的，表面上看和 1. 中截图是一样的）点击登录弹出的也是这个）：
![动态详情登录窗口](https://user-images.githubusercontent.com/49396421/85938153-09fde800-b93d-11ea-96f1-4f8cbc91de5e.gif)

**Comment by Coulomb-G** [comment]
这个脚本的使用前提就是已登录b站账号,所以未登录页面都属于不常用页面.同时短期内也没空写夜间

**Comment by Geeyun-JY3** [comment]
> 这个脚本的使用前提就是已登录b站账号,所以未登录页面都属于不常用页面.同时短期内也没空写夜间

嗯可以理解，提出来纯属强迫症，不着急。
