### ISSUE TITLE
视频选集和相关推荐都是灰色的

### ISSUE THREAD

**Issue by 1353604736** [the1812/Bilibili-Evolved#673]
**关于哪一项功能**

**问题描述**

视频选集和相关推荐都是灰色的
bilibili.com/video/BV1PE411W7mN?p=193

**脚本版本**
1.10.29

**浏览器版本**
百分浏览器 版本 4.2.10.171（正式版本） （64 位） (portable) (Chromium 80.0.3987.163)

**错误信息**

**附加截图**
![2020-6-28 23-37-11](https://user-images.githubusercontent.com/12869582/86129123-c78f0380-bb14-11ea-9d23-a42fc027a455.png)

**Comment by the1812** [comment]
可能是网络不好?
![image](https://user-images.githubusercontent.com/26504152/86308161-0a52f780-bc4b-11ea-8468-91d22af9bc9f.png)

**Comment by 1353604736** [comment]
> 可能是网络不好？
> ![图片](https://user-images.githubusercontent.com/26504152/86308161-0a52f780-bc4b-11ea-8468-91d22af9bc9f.png)

已解决，原来是自定义ublock规则问题
