### ISSUE TITLE
清爽主页界面手机视频动态栏显示BUG

### ISSUE THREAD

**Issue by Kamikamiku** [the1812/Bilibili-Evolved#674]
**关于哪一项功能**
简化首页的清爽主题风格

**问题描述**
如图所示，动态中有手机分辨率的视频发布，动态栏中显示不全

**脚本版本**
正式版1.10.29

**浏览器版本**
 Chromium 63.0.3239.132

**错误信息**

**附加截图**
![TIM截图20200629123124](https://user-images.githubusercontent.com/67572116/85973731-552ffd80-ba06-11ea-9cfe-c0ee8189a9b8.png)

**Comment by the1812** [comment]
可以提供下这张封面的地址吗

**Comment by Kamikamiku** [comment]
我谷歌升级过后显示正常了
