### ISSUE TITLE
顶部栏移除稍后再看中的视频

### ISSUE THREAD

**Issue by lamcodes** [the1812/Bilibili-Evolved#676]
**关于哪一项功能**
稍后再看中移除视频

**问题描述**

点击移除，实质已经移除，但是稍后再看的列表没有刷新。被移除的视频仍然存在。第二次点击才刷新成功。

**脚本版本**

正式版1.10.29

**浏览器版本**

Microsoft Edge83.0.478.56 

**错误信息**

**附加截图**

**Comment by u2shana** [comment]
这bug很久了，经常点X删除然后又弹出来又点X又弹出来这样，要重复好几次才删掉，有时候删没了进去页面一看还待在稍后再看里面
