### ISSUE TITLE
`自定义顶栏` 搜索栏支持专栏 cv 号、视频 av 号、直播间号等跳转相关优化

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#677]
**关于哪一项功能**
自定义顶栏

**期望的效果**
- [x] 1. 搜索栏支持 cv 号跳转专栏；
- [ ] 2. 以下是突发联想：在搜索栏只输入了数字的情况下，希望联想结果可以像手机客户端一样，前三项分别是：跳转视频、跳转专栏和以该串数字为关键词搜索，按回车直接跳转至视频的功能也不用变。
  ***
  2023-04-26 编辑：官方手机客户端的联想结果的前三项分别是：跳转视频、跳转专栏和跳转直播间，没有以该串数字为关键词搜索的入口。
  <img src="https://user-images.githubusercontent.com/49396421/234219732-47c39f2c-5a90-4fde-80b0-401f1552ce13.png" width="50%" height="50%">
  所以需求的准确表述应该是：希望联想结果的前四项分别是：跳转视频、跳转专栏、跳转直播间和以该串数字为关键词搜索。
  ***
- [x] 3. 如果有需要的话音频（au 号）和歌单（am 号）我觉得也可以一起做了（这两倒不用只输数字也会联想，在输入 `au*****` 和 `am****` 的情况下给个联想结果就行）（不过我是没这需求，估计用的人也不多）
***
顺便提醒一下 [功能列表](https://github.com/the1812/Bilibili-Evolved/blob/master/features.md) 和脚本设置里的简短说明缺少了<kbd>`</kbd>键和<kbd>p</kbd>键的说明。

**脚本版本**
正式版 v1.10.29
预览离线版

**Comment by Geeyun-JY3** [comment]
要不也给文集加上？就像上面提到的音频和歌单一样，输入文集号（如：rl32746）才给个跳转联想结果

**Comment by Geeyun-JY3** [comment]
要不再加个直播间（灵感同样来自 App，平时用的 Play 版忘了）？

**Comment by the1812** [comment]
加 都可以加(

**Comment by Geeyun-JY3** [comment]
艹
`long-term` tag 制裁

**Comment by Geeyun-JY3** [comment]
要是有人嫌这联想太多太麻烦了了，想要个开关关掉，就把这功能叫作 `过度联想`<img src="https://i0.hdslb.com/bfs/emote/bba7c12aa51fed0199c241465560dfc2714c593e.png" width="20" height="20" alt="doge">

**Comment by the1812** [comment]
其实这个打 long-term 是想扔进 2.0 里做, 2.0 里的设计可以直接卸掉某种类型的联想

**Comment by Geeyun-JY3** [comment]
6. 要不再加个用户 UID？

**Comment by Geeyun-JY3** [comment]
7. 既然 v2 的搜索栏都能执行命令了，感觉 v2 搜索栏挺适合做成一个快速跳转入口，毕竟破站各种类型的页面的 URL 里都有各自的特征字母（像 av 号的 `av`、BV 号的 `BV`、专栏文章的 `cv` 啥的），除了上面提到的几种外，今天又想到可以加番剧影视类的 ss、ep、md 号。~~这也挺符合 v2 箭头图标的寓意的。~~

**Comment by Geeyun-JY3** [comment]
8. 如果可以利用 API 啥的获取到更多相关信息，感觉直接在下拉菜单中的相应的跳转项中显示出更多相关信息能让搜索栏这功能强大不少，通用的各种类型都能显示的如标题，像 av、BV、cv 还可以显示 UP 主，ss 可以显示本番剧影视类型（番剧、电视剧、电影、综艺、纪录片等）、简介、总共有几集（不过对于一些集数较多的可能还不能就简单地全部铺开），ep 可以显示其为第几集等等。

**Comment by the1812** [comment]
第 8 点的相关信息塞不下这么多, 暂且放个标题了

![image](https://user-images.githubusercontent.com/26504152/226165860-664ee663-ebae-4781-a08a-5bcba7ebeeab.png)

**Comment by Geeyun-JY3** [comment]
我在 https://github.com/the1812/Bilibili-Evolved/issues/677#issuecomment-755887397 说的应该是破站官方手机客户端的搜索栏数字联想结果还有一个直播间：
<img src="https://user-images.githubusercontent.com/49396421/234219732-47c39f2c-5a90-4fde-80b0-401f1552ce13.png" width="50%" height="50%">
要不把这个也做进`搜索栏 - 数字联想`？

另外我个人[当初](https://github.com/the1812/Bilibili-Evolved/issues/677#issuecomment-1113878007)是希望 UID 也能做进`搜索栏 - 数字联想`的，毕竟我感觉纯手打逐个数字输入搜用户的频率是比搜视频专栏高的，尽管官方客户端没有做这功能（

**Comment by Geeyun-JY3** [comment]
直播间的标题我倒是无所谓，有个跳转入口就行
