### ISSUE TITLE
多集番剧／影视（非同一 av 号分 p 类型）切换分集后附加功能中的 AV 号和 BV 号无变化

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#678]
**关于哪一项功能**
附加功能 AV 号和 BV 号显示、BiliPlus 跳转支持

**问题描述**
多集番剧／影视（非同一 av 号分 p 类型）切换分集后附加功能中的 AV 号和 BV 号无变化，进而也影响到 BiliPlus 跳转支持 功能

**脚本版本**
正式版 v1.10.29
预览离线版

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 83.0.4103.116（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by the1812** [comment]
以前的番剧都是一个av号的, 不知道现在改成多个av号会有多少功能出问题, 感觉不止这两个

**Comment by Geeyun-JY3** [comment]
> 以前的番剧都是一个av号的, 不知道现在改成多个av号会有多少功能出问题, 感觉不止这两个

现存的番剧一部分还是共用一个 av 号，一部分是一集一个 av 号
