### ISSUE TITLE
动态页直播栏up重复显示

### ISSUE THREAD

**Issue by Bel-Air** [the1812/Bilibili-Evolved#679]
**关于哪一项功能**

> 动态 >> 直播信息扩充

**问题描述**

> 在动态那个页面,左边直播栏出现了滚动到下半部分全是上面重复的up,而少了一部分其他正在直播的,只能去[更多](https://link.bilibili.com/p/center/index#/user-center/follow/1),原版那里找所有人的直播间,不知是不是和我关注了700个up有关,同时直播的很多,一般都是50个起步

**脚本版本**

>正式版  `1.10.29`

**浏览器版本**

> opera  `69.0.3686.36`

**错误信息**

> `null`

**附加截图**
![Honeycam 2020-06-30 23-29-50](https://user-images.githubusercontent.com/67642802/86145625-bbfa0780-bb29-11ea-9807-3366745d4960.gif)

**Comment by the1812** [comment]
那顶栏动态里的直播会不会重复显示?

**Comment by Bel-Air** [comment]
> 那顶栏动态里的直播会不会重复显示?

也是重复的
