### ISSUE TITLE
播放前显示视频封面和互动视频会冲突

### ISSUE THREAD

**Issue by Cansll** [the1812/Bilibili-Evolved#680]
**关于哪一项功能**
播放前显示视频封面

**问题描述**

（出问题时的视频:[av796126487](https://www.bilibili.com/video/av796126487/)）
在进行一次选择后视频会始终显示封面，把视频遮住。

**脚本版本**

Stable v1.10.29

**浏览器版本**

Chrome 83

**错误信息**

无红字

**附加截图**
![屏幕截图(742)](https://user-images.githubusercontent.com/11648014/86147719-4f343c80-bb2c-11ea-9d92-94877fa3dc99.png)
![屏幕截图(743)](https://user-images.githubusercontent.com/11648014/86147729-51969680-bb2c-11ea-8d2a-186a0cdc54f8.png)

**Comment by Cansll** [comment]
补充：如果出问题后关闭播放前显示视频封面不刷新那么每次选择后封面也都会继续遮住视频，除非重新开关一次

**Comment by the1812** [comment]
有试试 #662 里的方法吗, 我传了个改过的版本
也试了下你发的视频 应该没有问题

**Comment by Cansll** [comment]
抱歉之前虽然看见了那个issue但是没有去看解决方案

重装之后是没问题的，选项点完了虽然依然会显示封面，但是开始播放后可以正确播放视频。问题算是解决了 :D
不过是否可以在互动视频的时候只在第一次打开（没做选择时）显示封面，做了选择后就不显示封面了呢？(这个只是一个小想法)

**Comment by the1812** [comment]
互动视频选了之后下一个视频不是自动播放的吗

**Comment by Cansll** [comment]
修正一下 是还是会显示封面遮挡住正在播放的视频 但是暂停重新播放之后正常，还是有点问题
确实是自动播放的
刚刚没看到细节 抱歉

**Comment by Cansll** [comment]
![image](https://user-images.githubusercontent.com/11648014/86203116-bd154e00-bb96-11ea-93c0-0b1ba6292277.png)

**Comment by the1812** [comment]
好的 我之后再研究下
