### ISSUE TITLE
开启"播放时自动关灯"功能,B站原生自动小窗功能失效

### ISSUE THREAD

**Issue by Bel-Air** [the1812/Bilibili-Evolved#681]
**关于哪一项功能**

> 视频 >> `播放时自动关灯`

**问题描述**

> 开灯状态下,B站自带的自动小窗(滚动到原播放器外会把原播放器连带弹幕缩小成随滚动固定的悬浮窗)会失效,目前推测那个小窗在原播放器的右下角不随滚动固定,关灯播放时,快速从下滚动到上,会瞥见小窗从右上角恢复到原播放器

**脚本版本**

> 正式版 `1.10.29`

**浏览器版本**

> opera `69.0.3686.36`

**错误信息**

> `null`

**附加截图**

**Comment by the1812** [comment]
这是b站的问题 你可以关掉脚本手动关灯试试 还是一样的
