### ISSUE TITLE
随机出现播放器定位错误

### ISSUE THREAD

**Issue by Bel-Air** [the1812/Bilibili-Evolved#682]
**关于哪一项功能**

> 视频 >> 默认播放器模式 >> `宽屏`

**问题描述**

> 每次打开一个视频时,所有功能加载完毕后,会出现自动定位到播放器位置出错,体现为上一半在视野外,好像打开"打开过的视频"出现此问题概率更高?手动调节宽屏时发现可能是由默认的宽屏这个功能造成,或许调整功能开启顺序先宽屏后自动定位?
(未开启`自动定位到播放器`功能,默认宽屏自带自动定位?)

**脚本版本**

> 正式版 `1.10.29`

**浏览器版本**

> opera `69.0.3686.36`

**错误信息**

> `null`

**附加截图**
[bilibili-evolved-settings.zip](https://github.com/the1812/Bilibili-Evolved/files/4855336/bilibili-evolved-settings.zip)

**Comment by the1812** [comment]
宽屏这个是老毛病了 见#483
