### ISSUE TITLE
轮播图的去广告处理

### ISSUE THREAD

**Issue by hcfw007** [the1812/Bilibili-Evolved#685]
**关于哪一项功能**

在目前的去广告功能中，对于轮播图的处理是直接删除图片，这样播到这一张时会留下灰色的一块，不太好看。

**期望的效果**
建议最好改为能直接删除该节点，即不会播到空白图，或者使用一张比较好看的图替代。

**脚本版本**
1.10.29

**Comment by the1812** [comment]
删掉就变成下一张图了
图片和文字就错位了

**Comment by hcfw007** [comment]
我刚刚看了一下首页轮播图的dom结构
![image](https://user-images.githubusercontent.com/13669999/86275250-90e4e600-bc05-11ea-9239-8c9bf8c9809a.png)
只要把广告所在的div.item删除，同时再删除下面div.trigger里面的span，就可以实现删除广告且不留白的效果。span对位置不敏感，只要删除和广告数量相同数量的span即可。

**Comment by the1812** [comment]
好的 我之后试试

**Comment by the1812** [comment]
貌似删了之后这个轮播图的行为变得不正确了
`.trigger span`有时候会变成没有任何一个点亮的状态, 且点击最后一个不会跳转图片

**Comment by hcfw007** [comment]
如果刚好把处于on状态的span删了就会成为没有任何一个点亮的状态，但此时随意点击一个就能恢复正常。点击最后一个不会跳转我目前还没遇到过这种情况。

**Comment by the1812** [comment]
无论删掉的是不是带`on`的, 播到那个位置都会变成没有任何点亮
感觉轮播图的代码里是存了对这些`span`的引用的

**Comment by hcfw007** [comment]
那如果按照原广告图所在的位置删除相对应的span能避免这一现象发生嘛？

**Comment by the1812** [comment]
试了下 并不能避免
