### ISSUE TITLE
被风控视频报错页验证码输入框夜间模式适配不完全

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#686]
**关于哪一项功能**
夜间模式

**问题描述**
可能比较难复现，这也是昨天偶然发现的（[传送门](https://www.bilibili.com/video/av753740147?t=1552&p=4)）：视频触发哔哩哔哩安全风控策略，该次访问请求被拒绝时，验证码输入框夜间模式未适配完全（原谅我的强迫症）

**脚本版本**
正式版 v1.10.29
预览离线版

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 83.0.4103.116（正式版本） （64 位）

**错误信息**

```
Failed to load resource: the server responded with a status of 412 ()
```
（目测应该没什么用

**附加截图**
![image](https://user-images.githubusercontent.com/49396421/86230208-5b1f0d80-bbc3-11ea-8c10-b6af532d3909.png)

**Comment by the1812** [comment]
我进去是正常的 复现不了

**Comment by Geeyun-JY3** [comment]
> 我进去是正常的 复现不了

我发这条 issue 的时候进去也已经没问题了，当时是在未登录的情况下出现这种情况的……

**Comment by Geeyun-JY3** [comment]
今天发现了个视频撞车跳转提示页，想提醒一下，懒得再开一个 issue 就发在这了：

目前点击这个视频 [BV1wp4y1q75i](https://www.bilibili.com/video/bv1wp4y1q75i) 会出现该页面，没开夜间模式看上去没什么问题，开了夜间模式后发现「3 秒后自动跳转」的「转」字在按钮外，不知道是不是 b 站自己还在测试。

未开夜间模式：
![image](https://user-images.githubusercontent.com/49396421/90645260-52b08e00-e268-11ea-8f15-175610470bf8.png)
开启夜间模式：
![image](https://user-images.githubusercontent.com/49396421/90644735-ab335b80-e267-11ea-8490-385c7e1f76a5.png)

**Comment by the1812** [comment]
这原本就是在外边的吧 跟夜间没啥关系

**Comment by Geeyun-JY3** [comment]
> 这原本就是在外边的吧 跟夜间没啥关系

纯粹提醒一下，目前脚本的适配没什么问题，我更倾向于这是 b 站自己的问题。
