### ISSUE TITLE
动态页直播栏直播标题重复显示

### ISSUE THREAD

**Issue by LonelySteve** [the1812/Bilibili-Evolved#687]
**关于哪一项功能**

**问题描述**

> 在动态页面，左边直播栏里的标题信息会出现两次，在页面刷新之后的短暂时间内，渲染的结果是正确的，但之后标题就会占据原先显示 UP 主名字的位置，而 UP 主的名字则被挤了下去。

**脚本版本**

Stable v1.10.29

**浏览器版本**

Chrome 83.0.4103.116

**错误信息**

![image](https://user-images.githubusercontent.com/34429322/86256210-9ed93d80-bbea-11ea-8e8f-1bb6711c9407.png)

![image](https://user-images.githubusercontent.com/34429322/86256392-dcd66180-bbea-11ea-9696-6dc377c6639d.png)

![image](https://user-images.githubusercontent.com/34429322/86256467-f11a5e80-bbea-11ea-9b4c-11aebddf9dbb.png)

**Comment by the1812** [comment]
原本没标题的, 今天b站加上了
可以先关掉这个功能

**Comment by Cansll** [comment]
跟这个类似的问题，其实之前就有这个问题了，鼠标悬停时，靠后的几个直播间悬停提示时错误的，是第一个视频的
![image](https://user-images.githubusercontent.com/11648014/86306648-69af0880-bc47-11ea-8e5a-a16e4f86bf1e.png)

其实是第一个的提示

![image](https://user-images.githubusercontent.com/11648014/86306722-9105d580-bc47-11ea-91fd-9b30fe5b8eef.png)
