### ISSUE TITLE
搜索自定义顶栏搜索历史后无法单独删除

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#689]
不知道这是不是 bug 所以用提问的形式了。

搜索自定义顶栏搜索栏里的某条搜索历史后，无法单独删除任意一条搜索历史（用快捷键 <kbd>Shift</kbd>+ <kbd>Delete</kbd> 也不行），但可以清除全部搜索历史。
（讲得比较绕，具体看下方 GIF）
![搜索历史](https://user-images.githubusercontent.com/49396421/86332148-b3661600-bc7c-11ea-8419-b57cd963c58a.gif)

**Comment by Coulomb-G** [comment]
请提交一份「导出设置」看看，我这边暂时无法复现

**Comment by Geeyun-JY3** [comment]
这份是最新预览离线版导出的：[bilibili-evolved-settings.zip](https://github.com/the1812/Bilibili-Evolved/files/4863290/bilibili-evolved-settings.zip)

**Comment by Geeyun-JY3** [comment]
预览离线版默认的配置即可复现。

而且发现了一个之前没留意的细节：搜索自定义顶栏搜索栏里的某条搜索历史后，搜索栏中会自动填充刚刚点击的那条搜索历史。本 issue 会不会和这个细节有关？
