### ISSUE TITLE
Maximize Volume by Default

### ISSUE THREAD

**Issue by Riajyuu** [the1812/Bilibili-Evolved#69]
I don't really see why the default volume is 66.

**Comment by the1812** [comment]
bilibili will remember your volume by itself unless you are using touch gestures to adjust the volume.
To maximize volume by default, just hit up arrow key to increase volume to 100%. Then every video will starts with 100% volume.

**Comment by Riajyuu** [comment]
@the1812 
> bilibili will remember your volume by itself

Really? Am I missing anything?

**Comment by the1812** [comment]
Have you enabled cookies? The volume is stored via local storage, which is controlled by cookies settings. If it's already enabled, try to clear cookies of `bilibili.com`.
As the screenshot shows, if I set volume to 86%, `bilibili_player_settings.video_status.volume` will be set to `0.86`. Next video will read this value as default volume.
![local-storage](https://user-images.githubusercontent.com/26504152/52713429-388e5380-2fd2-11e9-9583-957011308c98.png)

**Comment by the1812** [comment]
Closed due to inactivity.
