### ISSUE TITLE
生成指定评论的定位链接

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#690]
**关于哪一项功能**
生成指定评论的定位链接

**期望的效果**
通过某种方式生成指定评论（包括楼中楼）的定位链接，即格式为 `http://www.bilibili.com/*****/*******/#reply[评论id]`（包括普通视频、番剧／影视、专栏）的评论定位链接
（不知道这有没有可行性，反正想到干脆就一并提了）

**脚本版本**
正式版 v1.10.29
预览离线版

**Comment by Coulomb-G** [comment]
这是跳转回复评论的地址,消息中心直接跳转过去就有啊

**Comment by Geeyun-JY3** [comment]
> 这是跳转回复评论的地址,消息中心直接跳转过去就有啊

也能起定位作用鸭，而且消息中心也只能跳转至和自己互动过的评论啊，不知道任意评论可能做到吗？

**Comment by Cansll** [comment]
我看到评论区的每一个div都有一个属性叫`data-id`，只要在地址后面加上`#reply`+`data-id`就可以在加载页面完成后自动跳转过去，动态详情页和视频页是这个规则。

**Comment by Geeyun-JY3** [comment]
找到一个实现了该功能的脚本：[哔哩哔哩-显示评论链接](https://greasyfork.org/zh-CN/scripts/406386)，具体效果是会弹出个对话框再手动复制。我个人更倾向于不弹出对话框直接复制链接到剪贴板的效果。

**Comment by Cansll** [comment]
> 找到一个实现了该功能的脚本：[哔哩哔哩-显示评论链接](https://greasyfork.org/zh-CN/scripts/406386)，具体效果是会弹出个对话框再手动复制。

这是我写的...我看见这个issue之后想试试就写了这么一个，但是在动态首页什么的地方直接加reply那个感觉没有意义，所以也没有继续完善下去...

**Comment by the1812** [comment]
<img src="https://user-images.githubusercontent.com/26504152/86886044-d8e59a80-c128-11ea-9239-fafa05f995bb.png" height="24">

**Comment by Geeyun-JY3** [comment]
> > 找到一个实现了该功能的脚本：[哔哩哔哩-显示评论链接](https://greasyfork.org/zh-CN/scripts/406386)，具体效果是会弹出个对话框再手动复制。
> 
> 这是我写的...我看见这个issue之后想试试就写了这么一个，但是在动态首页什么的地方直接加reply那个感觉没有意义，所以也没有继续完善下去...
> 
> 功能很简单，就是给所有的评论加一个按钮，按钮显示一个弹窗来方便复制 当前页面地址+ `#reply评论ID`

可以，整挺好

**Comment by Geeyun-JY3** [comment]
v1.10.34 发现的一些小问题：
1. 专栏下的评论好像复制了个寂寞；
2. 复制的歌单和歌曲下的评论链接似乎不能跳转定位至相应评论（虽然都有个 `data-id`），是 b 站官方没搞这个还是格式与视频、专栏下的不一样？
2. 链接套娃，在`http://www.bilibili.com/*****/*******/#reply[评论id]`下复制的评论链接会是 `http://www.bilibili.com/*****/*******/#reply[评论id]#reply[评论id]`，虽然还是能正常跳转并正确定位。
这是偷懒了吗（滑稽）？

**Comment by the1812** [comment]
当时随便整的 没测多少个页面(

**Comment by the1812** [comment]
专栏不知道为啥调用油猴的`GM_setClipboard`没有任何变化, 链接是已经获取到了的
音频歌单那边疑似是b站不支持
套娃会修复

**Comment by Geeyun-JY3** [comment]
> 音频歌单那边疑似是b站不支持

音频歌单尝试过互相回复，然后从消息中心跳转吗？

**Comment by the1812** [comment]
还没

**Comment by Geeyun-JY3** [comment]
更多菜单在英语界面下有些小问题
![image](https://user-images.githubusercontent.com/49396421/92304896-cebf0b80-efb4-11ea-946e-0f483f333a8f.png)
