### ISSUE TITLE
期望可以实现更具体的简化首页

### ISSUE THREAD

**Issue by TroyLin0218** [the1812/Bilibili-Evolved#693]
**关于哪一项功能**

简化首页

**期望的效果**
可以自行选择不显示哪些分类的内容
害，实际上是想使用另一个脚本【bilibili网页端添加APP首页推荐】，但是开了简化首页之后推荐就无法展示了，故想出一个折中方案。

**脚本版本**
1.10.29

**Comment by the1812** [comment]
是想把原来的首页也简化下吗

**Comment by TroyLin0218** [comment]
> 是想把原来的首页也简化下吗

抱歉一直没看Github，就是可以自行选择不展示主页的哪些分类推荐视频，比如什么舞蹈区什么的（实质上还是因为那个首页推荐在当前版本的简介首页下不能显示的问题）实际上用习惯了移动端，使用web端的时候就不再看各个分类推荐的视频了

**Comment by the1812** [comment]
那应该就是可以筛选下首页的分区这样的功能

**Comment by TroyLin0218** [comment]
> 那应该就是可以筛选下首页的分区这样的功能

对的对的
