### ISSUE TITLE
顶栏的弹出页面 视频时长 可以设置为 一直显示吗？

### ISSUE THREAD

**Issue by kethoven** [the1812/Bilibili-Evolved#696]
**关于哪一项功能**

顶栏的弹出页面 视频时长 可以设置为 一直显示吗？

**期望的效果**
仅仅就我个人而言，在刷动态的时候，希望能够一直显示视频时长。
我自己刷动态的方式就是一眼看过去，视频截图基本了解是什么。时长可以预测大体的内容，是简单的剪辑，还是完整的。之后再认真看标题，上传者。像很多上传者头像不是容易辨认的，看到时长一个多小时，立马就意识到应该是一部电影，节目。
我自己觉得视频时长是一个非常重要的参数，所以就希望能够一直显示时长。

**脚本版本**

**Comment by GrayDeprave** [comment]
@the1812 这个隐藏选项加在了哪里。

**Comment by the1812** [comment]
```js
bilibiliEvolved.settings.alwaysShowDuration = true
```

**Comment by GrayDeprave** [comment]
> ```js
> bilibiliEvolved.settings.alwaysShowDuration = true
> ```

这东西应该在哪用，油猴这个脚本是一个横排的。直接搜索也搜索不到。

**Comment by the1812** [comment]
开浏览器控制台 `Ctrl+Shift+I`
粘贴进去运行就行了

**Comment by GrayDeprave** [comment]
> 开浏览器控制台 `Ctrl+Shift+I`
> 粘贴进去运行就行了

运行之后貌似没有效果。

**Comment by GrayDeprave** [comment]
![image](https://user-images.githubusercontent.com/51424205/103974157-46dc4e80-51ac-11eb-9549-8a47448a43a5.png)

**Comment by the1812** [comment]
我看图里已经运行了  顶栏的动态 收藏之类的弹窗里视频时长应该会变为持续显示

**Comment by GrayDeprave** [comment]
> 我看图里已经运行了 顶栏的动态 收藏之类的弹窗里视频时长应该会变为持续显示

哦，是顶栏的动态，那个我看已经运行了。我还以为是页面的那个。

**Comment by fanjunfate** [comment]
为啥不直接做进脚本里呢，这个功能很好呀

**Comment by the1812** [comment]
之后的预览版会开放选项

**Comment by Geeyun-JY3** [comment]
这不在 Release note 里提一下？

**Comment by the1812** [comment]
打算放在下个预览版的 release note
