### ISSUE TITLE
顶栏背景模糊无效

### ISSUE THREAD

**Issue by Yuuki-Sakura** [the1812/Bilibili-Evolved#701]
**问题描述**

顶栏背景模糊无效
![image](https://user-images.githubusercontent.com/54829481/86525995-d123bd00-bec0-11ea-80ac-6190438ee96a.png)
![image](https://user-images.githubusercontent.com/54829481/86526040-7343a500-bec1-11ea-8d72-968049990c3b.png)

**脚本版本**

预览离线版 719.02
![image](https://user-images.githubusercontent.com/54829481/86526013-21028400-bec1-11ea-987e-36957fb78a17.png)

**浏览器版本**

Edge 84.0.522.28 (Beta)

**错误信息**

无

**附加截图**

**Comment by the1812** [comment]
因为这不是真正的背景模糊, 而且不能打开`透明填充`.
这只是在首页那个横幅那里弄个看起来像背景模糊的效果, 其他页面是没有的.
