### ISSUE TITLE
隐藏动态页的左右边栏

### ISSUE THREAD

**Issue by exyam** [the1812/Bilibili-Evolved#703]
动态页左右边栏的个人信息、公告栏和话题感觉都不是很有用，希望可以添加一个隐藏的选项。这样对竖屏浏览也友好些。
正在直播稍微有用些 ，也许可以移到中间？

**Comment by Coulomb-G** [comment]
提issue前可以先阅读readme,有各个功能的说明,其中就有「动态过滤器」
