### ISSUE TITLE
感觉我用上后打开bilibili超级卡

### ISSUE THREAD

**Issue by leafmoes** [the1812/Bilibili-Evolved#705]

**Comment by Coulomb-G** [comment]
可以说一下配置吗，或许可以试试离线版

**Comment by Wxt1314521** [comment]
貌似是简化主页这个功能引起的，希望css什么的可以弄本地加载，快一点

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/blob/master/src/style/simplify-home/simplify-home.md

**Comment by the1812** [comment]
开简化首页不配反广告插件会很慢的, 浏览器会把原版主页里所有分区都加载一遍才加载我的脚本

**Comment by Wxt1314521** [comment]
ok,谢谢了

**Comment by Wxt1314521** [comment]
貌似是简化主页这个功能引起的，希望css什么的可以弄本地加载，快一点



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Coulomb-G"<notifications@github.com&gt;; 
发送时间: 2020年7月6日(星期一) 晚上10:08
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "2111800583"<2111800583@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 感觉我用上后打开bilibili超级卡 (#705)





 
可以说一下配置吗，或许可以试试离线版
