### ISSUE TITLE
Tooltip 在移出又移入的时候动画没有做完

### ISSUE THREAD

**Issue by XGHeaven** [the1812/Bilibili-Evolved#708]
**关于哪一项功能**
Tooltip

**问题描述**

首先显示 Tooltip，然后鼠标移动开，当开始做消失动画的时候，但是还没有消失完全的时候鼠标再移动回来。
此时会发现 Tooltip 的背景颜色没有显示正确的颜色

**脚本版本**

正式版 `1.10.29`

**浏览器版本**

Chrome 83

**附加截图**

![Kapture 2020-07-08 at 15 43 47](https://user-images.githubusercontent.com/9291212/86892158-75f90100-c132-11ea-80f2-e4c164c9e7ea.gif)

**Comment by the1812** [comment]
只是动画暂时停住了, 等鼠标停在某个功能上0.8s后会再亮起来

**Comment by XGHeaven** [comment]
@the1812 是的。换用 transition 就不会遇到这种问题了。另外显示隐藏的时间感觉不只 0.8s，感觉有 3s

**Comment by the1812** [comment]
就是`transition`啊 我设的`transition-delay: 0.8s` 功能之间来回移动是不算的, 停留0.8s才会开始
