### ISSUE TITLE
脚本新版本失效

### ISSUE THREAD

**Issue by wsdd977** [the1812/Bilibili-Evolved#71]
**关于哪一项功能**

**问题描述**

脚本好像失效根本没有显示也没有任何作用之前旧版本能工作

**脚本版本**

1.7.9
1.7.4能正常工作

**浏览器版本**

 72.0.3626.119（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by the1812** [comment]
有什么[错误信息](https://github.com/the1812/Bilibili-Evolved/wiki/%E6%9F%A5%E7%9C%8B%E6%B5%8F%E8%A7%88%E5%99%A8%E8%BE%93%E5%87%BA%E7%9A%84%E4%BF%A1%E6%81%AF)吗? 离线版能不能正常工作?

**Comment by wsdd977** [comment]
离线版不行没反应旧版174正常

**Comment by wsdd977** [comment]
错误信息没见到有

**Comment by Felix2yu** [comment]
从178开始就失效了，预览、正式、离线都一样，表现为打开B站和没装一样，装回旧版会提示组件加载错误，但是之前设置的自动宽屏等设置还是生效的。
火狐66

**Comment by the1812** [comment]
现在还是没啥头绪...
失效的话就先降级吧, 用[旧的离线版](https://github.com/the1812/Bilibili-Evolved/raw/3e2a9f1c42f5bc30e5e3082a4b2609075b2bf210/bilibili-evolved.offline.user.js), 装了之后把11, 12行的代码删掉保存后就不会更新了.
![image](https://user-images.githubusercontent.com/26504152/53284346-ea294380-378d-11e9-8e23-53704c485442.png)

**Comment by Shlimax** [comment]
新版更新后还是不显示设置按钮，旧的设置依然生效，但无法修改

**Comment by the1812** [comment]
所以真的一点错误都没有吗? 没有错误信息我只能随缘修复了...
> 输出信息位于开发者工具的`控制台`或`Console`中. 开发者工具可以用快捷键`F12`或`Ctrl+Shift+I`打开.

**Comment by wsdd977** [comment]
[www.bilibili.com-1551529273522.log](https://github.com/the1812/Bilibili-Evolved/files/2922069/www.bilibili.com-1551529273522.log)

**Comment by Felix2yu** [comment]
火狐 66
暴力猴 2.10.1
```
ReferenceError: "GM_addValueChangeListener is not defined"
    <anonymous> https://www.bilibili.com/ line 1 > scriptElement:1934
    <anonymous> https://www.bilibili.com/ line 1 > scriptElement:24
    <anonymous> https://www.bilibili.com/ line 1 > scriptElement:1
    value https://www.bilibili.com/ line 1 > scriptElement:1
    j https://www.bilibili.com/:1
    j https://www.bilibili.com/:1
    value https://www.bilibili.com/:1
    <anonymous> https://www.bilibili.com/ line 1 > scriptElement:1
    <anonymous> https://www.bilibili.com/ line 1 > scriptElement:1
    i https://www.bilibili.com/:1
    i https://www.bilibili.com/:1
    j https://www.bilibili.com/:1
    O https://www.bilibili.com/:1
    LoadScripts https://www.bilibili.com/:1
    y https://www.bilibili.com/:1
    i https://www.bilibili.com/:1
line 1 > scriptElement:129:5
    logError https://www.bilibili.com/ line 1 > scriptElement:129
    <anonymous> https://www.bilibili.com/ line 1 > scriptElement:1968
    <anonymous> https://www.bilibili.com/ line 1 > scriptElement:24
    <anonymous> https://www.bilibili.com/ line 1 > scriptElement:1
    value https://www.bilibili.com/ line 1 > scriptElement:1
    j https://www.bilibili.com/:1
    j https://www.bilibili.com/:1
    value https://www.bilibili.com/:1
    <anonymous> https://www.bilibili.com/ line 1 > scriptElement:1
    <anonymous> https://www.bilibili.com/ line 1 > scriptElement:1
    i https://www.bilibili.com/:1
    i https://www.bilibili.com/:1
    j https://www.bilibili.com/:1
    O https://www.bilibili.com/:1
    LoadScripts https://www.bilibili.com/:1
    y https://www.bilibili.com/:1
    i https://www.bilibili.com/:1

```

**Comment by the1812** [comment]
明白了, 有些新功能不兼容暴力猴. 试试看`v1.7.11`版还有没有报错?

**Comment by Felix2yu** [comment]
可以正常使用了，谢谢。

**Comment by wsdd977** [comment]
没见到更新阿.....

**Comment by the1812** [comment]
辛苦你们了, 我发布前应该先在暴力猴上测试下的

**Comment by the1812** [comment]
@wsdd977 目前只在预览版中修复了

**Comment by wsdd977** [comment]
预览版还是十天前的更新阿

**Comment by the1812** [comment]
@wsdd977 [https://github.com/the1812/Bilibili-Evolved/tree/v1.7.11-preview](https://github.com/the1812/Bilibili-Evolved/tree/v1.7.11-preview)
或者直接用[安装链接](https://github.com/the1812/Bilibili-Evolved/raw/preview/bilibili-evolved.preview.user.js)

**Comment by wsdd977** [comment]
奇怪了 github 预览版分支被隐藏了吗 用你给的链接才看见新版本
