### ISSUE TITLE
夜间模式在 消息中心-我的消息 下适配不完全。

### ISSUE THREAD

**Issue by kethoven** [the1812/Bilibili-Evolved#710]
**关于哪一项功能**
夜间模式在消息中心-我的消息下适配不完全。
名字昵称不太清晰。

**问题描述**

**脚本版本**

**浏览器版本**

火狐78

**错误信息**

**附加截图**
本来想放截图的，但是图片上传失败了很多次。

**Comment by the1812** [comment]
是变白了吗 最近那边更新了
