### ISSUE TITLE
增加评论搜索功能

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#711]
**关于哪一项功能**
评论搜索

**期望的效果**
增加评论搜索功能（甚至更进一步的筛选过滤）
（ 知道 [Btools](https://chrome.google.com/webstore/detail/btools/codgofkgobbmgglciccjabipdlgefnch) 有这个功能，希望可以更进一步，打个 `long-term` 标签也是可以的）

**脚本版本**
正式版 v1.10.29
预览离线版

**Comment by the1812** [comment]
评论难道是一页页去搜的吗 感觉耗时会很长

**Comment by Geeyun-JY3** [comment]
> 评论难道是一页页去搜的吗 感觉耗时会很长

[Btools](https://chrome.google.com/webstore/detail/btools/codgofkgobbmgglciccjabipdlgefnch) 的加载时间确实挺久的
