### ISSUE TITLE
部分视频无限重开

### ISSUE THREAD

**Issue by fzqiao** [the1812/Bilibili-Evolved#712]
https://www.bilibili.com/video/BV1v5411Y7Pr/?spm_id_from=333.788.videocard_series
表现为不断地刷新进入，关闭脚本后正常

[bilibili-evolved-settings.zip](https://github.com/the1812/Bilibili-Evolved/files/4896172/bilibili-evolved-settings.zip)
这是设置，错误记录不太会用

**Comment by fantuyuan** [comment]
我是把自动转换AV号关掉就好了 你试试
