### ISSUE TITLE
影视内容的花絮区域无法批量导出下载链接

### ISSUE THREAD

**Issue by lidoworld** [the1812/Bilibili-Evolved#717]
**关于哪一项功能**
视频下载

**问题描述**

影视内容的花絮区域无法批量导出下载链接。
下图中的情况则是，官方把第一天的内容放在了正片选集的地方，第二天的内容放在花絮的这一栏。
这一栏是无法批量下载的。

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**
![QQ截图20200710213132](https://user-images.githubusercontent.com/24887103/87160098-fff0c780-c2f4-11ea-9bf4-0fbd2ae60ac0.png)

**Comment by the1812** [comment]
批量下载只能下载正片(或者说是那几个区域的第一个), 其他区域需要麻烦你一个个下载
