### ISSUE TITLE
增加 `界面翻译` 跟随浏览器界面语言切换选项

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#719]
**关于哪一项功能**

界面翻译

**期望的效果**
增加 `界面翻译` 跟随浏览器界面语言切换选项

**脚本版本**
正式版 v1.10.31
预览离线版

**Comment by the1812** [comment]
首次载入脚本后会跟随的, 之后都以手动设定的语言为准

**Comment by Geeyun-JY3** [comment]
> 首次载入脚本后会跟随的, 之后都以手动设定的语言为准

是需要安装脚本后首次打开b站语言为目标语言吗？但这个选项脚本默认是关闭的首次打开也不会跟随啊（还是说我有哪个步骤错了🤦‍♂️）

**Comment by the1812** [comment]
比如浏览器是英语的话, 首次安装脚本, 进入b站就会自动打开那个界面翻译并切到English

**Comment by Geeyun-JY3** [comment]
> 比如浏览器是英语的话, 首次安装脚本, 进入b站就会自动打开那个界面翻译并切到English

我这边登录非登录状态都测试了几次，好像 `界面翻译` 设置项都不会自动打开，不知道之前语言一直是中文会不会有影响🤦‍♂️要不也测试下？

**Comment by the1812** [comment]
跟登录没关系的 就是脚本初次安装的时候(脚本设置为空)才会检测语言

**Comment by Geeyun-JY3** [comment]
> 跟登录没关系的 就是脚本初次安装的时候(脚本设置为空)才会检测语言

我这边测试了好几次都不行🤦‍♂️要不算了

**Comment by the1812** [comment]
那就算了
