### ISSUE TITLE
下载视频进度条溢出

### ISSUE THREAD

**Issue by doio** [the1812/Bilibili-Evolved#72]
**关于哪一项功能**

下载视频

**问题描述**

下载 1080p60 视频，然后刚开始就切换到别的标签页去了
结果点回来看到进度条溢出了

**脚本版本**

Bilibili Evolved (Offline)
version 220.25

**浏览器版本**

Firefox 66.0b11

**附加截图**
![2019-02-27_16-43-42](https://user-images.githubusercontent.com/4461202/53477290-561deb80-3aaf-11e9-94a6-a76fcc3c8dbd.png)

**Comment by the1812** [comment]
是每次下视频都这样吗? 还是某个特殊的视频?
我重新写了进度条的代码, 看看还会不会溢出吧

**Comment by doio** [comment]
偶尔出现一次，也就看到一次实际上，_(:з」∠)_

**Comment by the1812** [comment]
下视频的时候服务器偶尔会抽的, 以前直接就算下载失败了, 最近改成失败的部分自动重试, 我觉得是(但愿是吧)重试的时候进度溢出了...
