### ISSUE TITLE
重定向稍后再看页点击跳转空页

### ISSUE THREAD

**Issue by fantuyuan** [the1812/Bilibili-Evolved#722]
**重定向稍后再看**

**问题描述**
打开【重定向稍后再看页面】开关，在【稍后再看页面】点击任意【稍后再看内容】，跳转到空页。

**脚本版本**
 正式版1.10.31 

**浏览器版本**
 Chrome  83.0.4103.116（正式版本） （64 位） 

**错误信息**

**附加截图**

**Comment by the1812** [comment]
稍后再看改版了, 见#723
