### ISSUE TITLE
稍后再看页面的视频url改动了,求适配

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#723]
在稍后再看页面里点进去的视频url是这个,而且也不也直接显示BV地址了,真的麻烦https://www.bilibili.com/medialist/play/watchlater/p1

不过目前旧版url也还能通过这个进去,就是不知道什么时候给删掉
https://www.bilibili.com/watchlater/p1

**Comment by the1812** [comment]
看来是稍后再看套了收藏夹列表的皮
我这的设置就只能控制到顶栏了

**Comment by the1812** [comment]
不过起码不是以前那个硬塞新版播放器的变扭页面了

**Comment by u2shana** [comment]
> 不过起码不是以前那个硬塞新版播放器的变扭页面了

这个新界面连视频简介都阉割掉，越来越怀疑产品经理的能力了

**Comment by fantuyuan** [comment]
> > 不过起码不是以前那个硬塞新版播放器的变扭页面了
> 
> 这个新界面连视频简介都阉割掉，越来越怀疑产品经理的能力了

list里的删除按钮也没了。
视频推荐也没了。

**Comment by fantuyuan** [comment]
没有视频推荐，又没有BV号，太难受了！

**Comment by fantuyuan** [comment]
顶栏的【稍后再看】还是跳转到【视频原地址】的！

**Comment by fantuyuan** [comment]
@the1812 顺便发现，只要使用插件，不管【外置稍后再看】的开关是否打开，【稍后再看】都被外置了？

**Comment by the1812** [comment]
> 这个新界面连视频简介都阉割掉，越来越怀疑产品经理的能力了
其实是收藏夹播放刚出那会瞎整的播放器, 后来就再也没更新过(

**Comment by rennemaki** [comment]
那个什么，请问这个功能还会修吗？

**Comment by the1812** [comment]
大概会再想办法给稍后再看页弄一下重定向

**Comment by MC-dusk** [comment]
现在的状态是：暂时关闭了“稍后再看页面重定向”功能吗？我这里是灰色的不能开启这个按钮

**Comment by the1812** [comment]
对 弄好之前不允许打开

**Comment by fantuyuan** [comment]
终于好了！🎉🎉🎉
