### ISSUE TITLE
【黑暗模式没完善】黑暗模式在这个地址下看的很尴尬，求修复！

### ISSUE THREAD

**Issue by Anurici** [the1812/Bilibili-Evolved#724]
**关于哪一项功能**

黑暗模式

**问题描述**

出现问题的地址
https://www.bilibili.com/s/video/BV1yf4y127t2

**脚本版本**

最新稳定版1.10.31

**浏览器版本**

Edge Dev 85（谷歌内核）
测试了Chrome，出现同样问题

**错误信息**

![image](https://user-images.githubusercontent.com/66464532/87410967-97a62c80-c5f9-11ea-9031-595917cc826e.png)

**附加截图**

![image](https://user-images.githubusercontent.com/66464532/87411062-befcf980-c5f9-11ea-90dd-52f630bfc3be.png)

**Comment by Coulomb-G** [comment]
请删去'/s'跳转到正常页面,这个页面一般是没有入口的

**Comment by Anurici** [comment]
> 请删去'/s'跳转到正常页面,这个页面一般是没有入口的
> 或者我过两天修一下吧,这两天有点事

![image](https://user-images.githubusercontent.com/66464532/87411757-bc4ed400-c5fa-11ea-8873-c267251abbe2.png)
有这个入口呀，这是我从搜索引擎搜索到的截图

**Comment by Anurici** [comment]
> 请删去'/s'跳转到正常页面,这个页面一般是没有入口的
> 或者我过两天修一下吧,这两天有点事

好的，谢谢大佬~

**Comment by Geeyun-JY3** [comment]
参见 #649

**Comment by Anurici** [comment]
> 见 #649 下的讨论

嗯嗯，看到了，但是我用的不是谷歌，用的是多吉搜索，别的搜索引擎是否也支持转换成普通视频地址？那这样的话，是不是很多搜索引擎也要适配？感觉还是单独适配/s/这个页面比较好，大佬们有时间适配一下咯，辛苦了~~

**Comment by Anurici** [comment]
> > 见 #649 下的讨论
> 
> 嗯嗯，看到了，但是我用的不是谷歌，用的是多吉搜索，别的搜索引擎是否也支持转换成普通视频地址？那这样的话，是不是很多搜索引擎也要适配？感觉还是单独适配/s/这个页面比较好，大佬们有时间适配一下咯，辛苦了~~

https://www.dogedoge.com/results?q=%E7%BA%A2%E7%B1%B3ac2100%E5%AE%98%E6%96%B9%E5%9B%BA%E4%BB%B6%E5%92%8C%E7%AC%AC%E4%B8%89%E6%96%B9%E5%9B%BA%E4%BB%B6%E8%AF%84%E6%B5%8B

**Comment by Geeyun-JY3** [comment]
> > 见 #649 下的讨论
> 
> 嗯嗯，看到了，但是我用的不是谷歌，用的是多吉搜索，别的搜索引擎是否也支持转换成普通视频地址？那这样的话，是不是很多搜索引擎也要适配？感觉还是单独适配/s/这个页面比较好，大佬们有时间适配一下咯，辛苦了~~

用哪个搜索引擎都没区别，这就是为了 SEO 做的页面，转换也只会是针对 b 站这种格式的视频播放页。
至于适不适配这个页面，我觉得仓库作者已经在 #649 中说得很清楚了。
