### ISSUE TITLE
能否修改一下“显示占位文本”的类的名称

### ISSUE THREAD

**Issue by shenzhiming88** [the1812/Bilibili-Evolved#725]
**关于哪一项功能**

显示占位文本

**原因**
与EasyList广告过滤规则冲突，反馈结果建议修改这个类的名称
地址如下：https://github.com/easylist/easylist/issues/5618

**脚本版本**
1.10.31

**Comment by the1812** [comment]
换成`blocked`行吗?

**Comment by shenzhiming88** [comment]
> 换成`blocked`行吗?

应该可以，目前在该过滤规则中没有看到这一条
