### ISSUE TITLE
部分番剧未能显示在动态>番剧中

### ISSUE THREAD

**Issue by Wcraft233** [the1812/Bilibili-Evolved#726]
**关于哪一项功能**

**问题描述**

测试了几个番剧
我的青春恋爱物语果然有问题。完 能显示
Re：从零开始的异世界生活 第二季 不能显示 但是pv能显示
宇崎学妹想要玩！能显示
刀剑神域 爱丽丝篇 异界战争 -终章- 能显示

**脚本版本**

预览版 1.10.31

**浏览器版本**

chrome83

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
你是不是给从零开始的异世界生活设置成「想看」了？

**Comment by Wcraft233** [comment]
是“在看”状态
________________________________
发件人: Coulomb-G <notifications@github.com>
发送时间: 2020年7月15日 12:24
收件人: the1812/Bilibili-Evolved <Bilibili-Evolved@noreply.github.com>
抄送: WCRAFT <897431@outlook.com>; Author <author@noreply.github.com>
主题: Re: [the1812/Bilibili-Evolved] 部分番剧未能显示在动态>番剧中 (#726)


你是不是给从零开始的异世界生活设置成「想看」了？

―

**Comment by Coulomb-G** [comment]
https://t.bilibili.com/?tab=512,4097,4098,4099,4100,4101
这个页面是否和你说的情况一样？是的话得去找b站反馈了

**Comment by the1812** [comment]
直观点说是动态首页里选番剧一栏是否有少番剧

**Comment by Wcraft233** [comment]
> 直观点说是动态首页里选番剧一栏是否有少番剧

是能显示的，而且最迷的是我打开这个界面后动态里也能显示了。但是在之前是确实不能显示的。也许是第二话更新这个bug被修复了？

**Comment by Wcraft233** [comment]
是B站的bug
