### ISSUE TITLE
稍后再看重定向功能

### ISSUE THREAD

**Issue by kly402023688** [the1812/Bilibili-Evolved#727]
**关于哪一项功能**
稍后再看重定向功能

**问题描述**

打开稍后再看重定向 a标签链接会被替换成javascript:;导致跳转到空白页

**脚本版本**

1.10.31

**浏览器版本**

 83.0.4103.116

**错误信息**

**附加截图**
![截屏2020-07-15 下午8 23 30](https://user-images.githubusercontent.com/20452880/87544543-36ee2100-c6d9-11ea-8264-e950e780fda1.png)
![截屏2020-07-15 下午8 21 18](https://user-images.githubusercontent.com/20452880/87544550-39e91180-c6d9-11ea-890f-ea6bd381a7e4.png)

**Comment by the1812** [comment]
#723

**Comment by Coulomb-G** [comment]
你可以先看看已经有人提过相同的issue了

**Comment by TonyShitDark** [comment]
额 所以说什么时候能修好

**Comment by the1812** [comment]
会取消 只能通过顶栏进入原链接
