### ISSUE TITLE
强制给我推荐https://www.bilibili.com/video/BV1Hf4y1R7GR/这个视频

### ISSUE THREAD

**Issue by ziping46** [the1812/Bilibili-Evolved#728]
相关推荐里面一直有这个
我怀疑有没有py
![image](https://user-images.githubusercontent.com/38586831/87552256-052e8780-c6e4-11ea-82de-0e6daa346d88.png)

**Comment by Coulomb-G** [comment]
那和这个脚本有什么关系?

**Comment by ziping46** [comment]
> 那和这个脚本有什么关系?

一开始我也觉得可能就是这个视频比较火，多次推荐也没什么的，我点了很多视频发现都是位于推荐视频第一个，位置一直是第一个，我觉得有点邪门。我试着在油猴关闭这个脚本，刷新后，神奇的是这个视频消失了，其他推荐视频照旧，顺序不变。然后我又复制当前链接到其他未安装油猴未安装其他拓展的ie浏览器，也是出现这种情况，并未给我推荐这个视频，其他推荐视频照旧，顺序不变。为什么安装该脚本后就会出现一个莫名其妙的视频长期存在于多个视频的推荐列表首位？

**Comment by the1812** [comment]
你要不重装下脚本试试
我所有的代码都是公开可查的, 不会搞什么视频推广

**Comment by ziping46** [comment]
> 你要不重装下脚本试试
> 我所有的代码都是公开可查的, 不会搞什么视频推广

我怀疑可能是‘相关推荐’列表抓取异常

**Comment by the1812** [comment]
相关推荐也是由b站抓取的
