### ISSUE TITLE
增加 `复制动态链接` 功能

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#729]
**关于哪一项功能**
复制动态链接

**期望的效果**
在动态首页、个人空间中每条动态右上角汉堡菜单和动态详情页汉堡菜单（更多菜单）中加入复制链接功能（不带 `?tab=2` 之类的参数），如下图位置，和 `举报` 并列：
动态页：
![image](https://user-images.githubusercontent.com/49396421/87562402-91df4280-c6f0-11ea-9371-36d536f4498d.png)
个人空间页：
![image](https://user-images.githubusercontent.com/49396421/87561254-fa2d2480-c6ee-11ea-8844-9dc3a3e719dd.png)

**脚本版本**
正式版 v1.10.31
预览离线版

**Comment by Geeyun-JY3** [comment]
有个相关的问题：除在动态页点击up主下方日期，如何获取某个视频对应的动态链接？
如果官方目前没有留入口，能否加个复制视频对应动态链接的功能（也算是符合本 issue 标题的功能吧（逃）？

**Comment by the1812** [comment]
貌似没留 我也做不了

**Comment by Geeyun-JY3** [comment]
> 貌似没留 我也做不了

好的吧
