### ISSUE TITLE
查看封面图直接打开大图的网页图片而不是 "blob://"？

### ISSUE THREAD

**Issue by doio** [the1812/Bilibili-Evolved#73]
**关于哪一项功能**

查看封面

**期望的效果**
blob:// 的形式不便于保存，而且保存图片的时候文件名直接是 `index.jpg` ，不方便归类而且还要重新命名
不知道能不能考虑一下用 b 站自己的封面图片链接打开新标签页的方式，或者/然后 根据视频 AV 号、标题重命名一下？

**脚本版本**

Bilibili Evolved (Preview Offline) v.227.03

**Comment by the1812** [comment]
你是右键另存为还是点了右下角的下载按钮?

**Comment by doio** [comment]
直接右键保存的时候（如果能在新标签页打开的话，借助浏览器的一些插件可以迅速把多个视频的封面都立刻保存，而不用一个一个点击？）

**Comment by the1812** [comment]
右键保存的话我无法控制它的文件名(新标签页也是), 所以才弄了blob和特别的下载按钮, 点那个下载按钮来保存是会根据当前视频来命名的.
新标签页打开可以加上, 只是打开后文件名就是乱的了, 不知道能不能帮到你.

**Comment by the1812** [comment]
加了`复制原链接`和`新标签页打开`了.
另外, 晚上闲着没事写了段批量下载封面的代码, 你可以新建个脚本粘贴进去玩玩. [附加功能: 批量下载封面](https://github.com/the1812/Bilibili-Evolved/wiki/%E9%99%84%E5%8A%A0%E6%96%B0%E5%8A%9F%E8%83%BD#%E6%89%B9%E9%87%8F%E4%B8%8B%E8%BD%BD%E5%B0%81%E9%9D%A2)
