### ISSUE TITLE
aria2批量下载问题

### ISSUE THREAD

**Issue by kingzleshe** [the1812/Bilibili-Evolved#730]
**关于哪一项功能**
下载视频--批量导出--aria2 RPC

**问题描述**
下载多个视频的时候会导致随机出现任务中断，看aria2的日志信息提示貌似是因为当某个任务在一定时间内没有足够的下载速度的时候就被中断了，因为其他任务把带宽占用满了。
目前IDM批量下载没这个问题，但是IDM没aria2方便（IDM多一个导入操作），而且文件名无法使用视频本身的文件名，都是一堆数字。

**脚本版本**
1.10.32

**浏览器版本**
Chrome 84

**aria2错误信息**
2020-07-16 12:20:44.936436 [ERROR] [AbstractCommand.cc:351] CUID#209 - Download aborted. URI=http://upos-sz-mirrorhw.bilivideo.com/upgcxcode/90/26/212202690/212202690_nb2-1-80.flv?e=ig8euxZM2rNcNbuM7WdVhoMa7wUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1594880163&gen=playurl&os=hwbv&oi=1867261987&trid=9933dff685f144848863026f23244315u&platform=pc&upsig=cf7849342832e966abafe61b939a7da8&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=279814730&orderid=0,3&logo=80000000
Exception: [AbstractCommand.cc:351] errorCode=5 URI=http://upos-sz-mirrorhw.bilivideo.com/upgcxcode/90/26/212202690/212202690_nb2-1-80.flv?e=ig8euxZM2rNcNbuM7WdVhoMa7wUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1594880163&gen=playurl&os=hwbv&oi=1867261987&trid=9933dff685f144848863026f23244315u&platform=pc&upsig=cf7849342832e966abafe61b939a7da8&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=279814730&orderid=0,3&logo=80000000
  -> [DownloadCommand.cc:312] errorCode=5 Too slow Downloading speed: 0 <= 1024(B/s), host:upos-sz-mirrorhw.bilivideo.com

**aria2配置信息**
### Basic Options ###
dir=E:\
save-session-interval=1
save-session=D:\aria2\aria2.session
input-file=D:\aria2\aria2.session
log-level=warn
log=D:\aria2\aria2.log
force-save=false
continue=true
max-concurrent-downloads=10
async-dns=false

### Advanced Options ###
auto-save-interval=60
disk-cache=512M
daemon=true
disable-ipv6=true
enable-mmap=true
file-allocation=prealloc
force-sequential=true
max-download-result=120
no-file-allocation-limit=32M
parameterized-uri=true
on-download-complete="rm -f "$3.aria2"
on-bt-download-complete="rm -f "$3.aria2"

### Proxy Setting ###
#all-proxy=http://127.0.0.1:8118 -d
#proxy-method=tunnel

### Http/FTP options ###
check-certificate=false
connect-timeout=120
http-no-cache=true
lowest-speed-limit=1k
max-file-not-found=2
max-tries=5
min-split-size=1M
split=16

### BT/PT Setting ###
max-connection-per-server=16
max-overall-download-limit=0
max-overall-upload-limit=150k
max-upload-limit=150
bt-save-metadata=false
bt-load-saved-metadata=true
enable-dht=true
enable-dht6=true
enable-peer-exchange=true
bt-enable-lpd=true
bt-hash-check-seed=true
bt-seed-unverified=true
#bt-force-encryption=true
#bt-require-crypto=true
bt-min-crypto-level=plain
bt-max-peers=0
bt-request-peer-speed-limit=50K
listen-port=6900
dht-listen-port=6900
seed-ratio=1.0
seed-time=0

**附加截图**
![微信图片_20200716122839](https://user-images.githubusercontent.com/20214409/87627127-9c392500-c760-11ea-8b7f-6292746e01ec.png)

**Comment by the1812** [comment]
这批任务大概下载了多长时间出现这个问题?

**Comment by kingzleshe** [comment]
> 这批任务大概下载了多长时间出现这个问题?

短则几十秒就会出现，长的话就1-2分钟左右。

打个比方：
如果同时下载10个任务，比如总共10G，一共需要下载10分钟
可能第一分钟的时候会出现一个任务失败，后面的几分钟的时候又会陆续增加若干个任务失败。

**Comment by the1812** [comment]
也许可以试试关闭低速限制?
删除这行
```
lowest-speed-limit=1k
```

**Comment by kingzleshe** [comment]
像是这个问题导致的，我测试下看看

**Comment by kingzleshe** [comment]
> 也许可以试试关闭低速限制?
> 删除这行
> 
> ```
> lowest-speed-limit=1k
> ```

lowest-speed-limit=0

修改成0后问题解决了，谢谢大佬。
