### ISSUE TITLE
bilibili新版徽章夜间模式下显示有误

### ISSUE THREAD

**Issue by Wcraft233** [the1812/Bilibili-Evolved#732]
**关于哪一项功能**
夜间模式

**问题描述**

如图，在不需要暗色模式的地方错误的暗色了

**脚本版本**

1.10.32

**浏览器版本**

chrome83

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/30252123/87672562-c2cd7f00-c7a5-11ea-869b-15a2b9dc1f02.png)

**Comment by the1812** [comment]
在做了在做了
