### ISSUE TITLE
黑暗模式视频评论区“up主觉得很赞”是白色的

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#733]
**关于哪一项功能**
黑暗模式

**问题描述**

[av77619407](https://www.bilibili.com/video/av77619407)

**脚本版本**

1.10.31 stable

**浏览器版本**

chrome 84

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/87687588-7d667d00-c7b8-11ea-9a56-91f1d61bd1be.png)

**Comment by naive12138** [comment]
我也遇到了这个问题。不仅是白色，很大，而且会对文字的显示有BUG，会把一条评论分割开来。

**Comment by Geeyun-JY3** [comment]
网页版的「up主觉得很赞」才刚出来不久……

**Comment by the1812** [comment]
大概会改成这样
![image](https://user-images.githubusercontent.com/26504152/87866242-de0cda00-c9b1-11ea-9845-847ea3701bb1.png)

**Comment by Geeyun-JY3** [comment]
@the1812 其实还有一个 `精选评论` 的标识，懒得再开一个 issue 了。应该是和官方搞的那个「一周B站热评」有关（印象中去年下半年开始用手机客户端在一些热门视频评论区能看到该标识），单独出现时（测试网址：https://www.bilibili.com/video/av60889308 ）夜间模式、简化评论区都和 `UP主觉得很赞` 一样，没什么问题，但一起同时出现会这两标识会叠起来，下图是预览离线版 736.21 中 `UP主觉得很赞` 和 `精选评论` 同时存在的效果，测试网址：https://www.bilibili.com/video/av71342767
![image](https://user-images.githubusercontent.com/49396421/88515557-77756500-d01e-11ea-9e1e-23b73c447bf8.png)
