### ISSUE TITLE
首页隐藏推荐直播板块似乎失效

### ISSUE THREAD

**Issue by Hellobaka** [the1812/Bilibili-Evolved#737]
**关于哪一项功能**
首页隐藏推荐直播板块似乎失效

**问题描述**
在打开 直播->禁止直播首页自动播放->隐藏首页推荐直播 之后,首页直播推荐板块仍旧存在

**脚本版本**
stable v1.10.31

**浏览器版本**
360安全浏览器12.3 Chrome内核 78.0

**附加截图**

![bug](https://user-images.githubusercontent.com/50934714/87839563-ebe92f00-c8cd-11ea-89c3-c6d7ba9a454a.png)

**Comment by the1812** [comment]
隐藏的是直播首页那个直播间
https://live.bilibili.com

**Comment by Hellobaka** [comment]
总感觉今天一上线多了这个版块，可能是我记错了吧
