### ISSUE TITLE
选择了FLV下载, 但是每次尝试都显示"此视频没有DASH格式, 请改用FLV格式"

### ISSUE THREAD

**Issue by iamjohnhihi** [the1812/Bilibili-Evolved#738]
**关于哪一项功能**
下载视频 - 批量导出 - 选择了flv和720p - 导出IDM

**问题描述**

但是每次按IDM都出现信息"此视频没有DASH格式, 请改用FLV格式", 按aria2也出现相同信息, 导致导出失败
av号为: av75631089
然而我刚刚试过单个视频能够下载一个一个的视频, 就是批量导出不行

**脚本版本**

1.10.31

**浏览器版本**

Version 83.0.4103.116 (Official Build) (64-bit)

**错误信息**

"此视频没有DASH格式, 请改用FLV格式"
 

**附加截图**
![image](https://user-images.githubusercontent.com/20634385/87852492-f5f24880-c934-11ea-9566-4ae765fbcd15.png)

**Comment by the1812** [comment]
如果是只选中一部分分集呢

**Comment by synodriver** [comment]
实测只选择一部分可以，全选不行，BV1SK4y147qU

**Comment by synodriver** [comment]
> 如果是只选中一部分分集呢 比如前面一两集
实测只选择一部分可以，全选不行，BV1SK4y147qU
