### ISSUE TITLE
关于快捷键扩展：合并快捷键扩展的悬浮提示至播放页右键菜单中的"快捷键说明"中

### ISSUE THREAD

**Issue by Quackgrass** [the1812/Bilibili-Evolved#739]
**关于哪一项功能**

快捷键扩展

**期望的效果**

将快捷键扩展的悬浮提示中的快捷键说明，添加至播放页右键菜单中的"快捷键说明"中。期望是加载官方默认的右侧，并有标题说明。

一般是不会一次性全部记下的，都是用什么功能再记相应快捷键的。当前查看方式不是很方便。

**脚本版本**

offline v724.22

**Comment by the1812** [comment]
多用用就记住了 每个键基本都是其功能的英语首字母或拼音首字母
