### ISSUE TITLE
Chat list's background of Bilibili Live isn't darkened correctly in Night mode

### ISSUE THREAD

**Issue by kator-278** [the1812/Bilibili-Evolved#74]
**关于哪一项功能**
Night mode

**问题描述**
The background of live's chat list remains light, while the font color is light as well and unable to read. Or did I miss some settings to make it work correctly?

**脚本版本**
Released ver 1.7.19

**浏览器版本**
Chrome 72, Firefox 65

**附加截图**
![tim20190301154425](https://user-images.githubusercontent.com/8875998/53623985-a4f78c80-3c39-11e9-9bf3-951c5ff7905a.png)

**Comment by the1812** [comment]
The bilibili live room has changed after v1.7.9 release. It was fixed in the preview versions, you can install a preview version or wait for the next update.

**Comment by kator-278** [comment]
Oh, I should have tried the preview version before posting the issue. :(

Yeah it works fine now with preview ver. Thanks for the reply. Sorry for the inconvenience.

**Comment by the1812** [comment]
My pleasure :)
