### ISSUE TITLE
稍后再看重定向问题

### ISSUE THREAD

**Issue by heyechuanmei** [the1812/Bilibili-Evolved#740]
**关于哪一项功能**
稍后再看重定向

**问题描述**

稍后再看重定向失效，点击后一律跳转about:blank

**脚本版本**

正式版

1.10.31
--

**浏览器版本**

Google Chrome 版本 84.0.4147.89（正式版本） （64 位）

**错误信息**

未出现报错

**附加截图**
![Snipaste_2020-07-18_23-31-38](https://user-images.githubusercontent.com/42758394/87856074-fef01380-c94e-11ea-86da-d1cf11ff5105.png)

**Comment by heyechuanmei** [comment]
<a href="https://sm.ms/image/QZTdla21GPzK7ps" target="_blank"><img src="https://i.loli.net/2020/07/18/QZTdla21GPzK7ps.png" ></a>

**Comment by Coulomb-G** [comment]
提issue前可以先搜索关键词,已经有人提过了

**Comment by heyechuanmei** [comment]
> 提issue前可以先搜索关键字，已经有人提过了

抱歉，当时没注意到已经有人反馈了。
