### ISSUE TITLE
关于快速收藏出现的bug

### ISSUE THREAD

**Issue by q56535** [the1812/Bilibili-Evolved#741]
**关于哪一项功能**
快速收藏

**问题描述**

当开启快速收藏功能时，打开任意一个视频都会出现两个报错框，内容为错误信息里的内容；关闭快速收藏后不出现报错

**脚本版本**

正式版`1.10.31`

**浏览器版本**

Chrome 83

**错误信息**

Cannot read property 'fav_state' of undefined
TypeError: Cannot read property 'fav_state' of undefined
    at Vue.syncFavoriteState (eval at applyComponent (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/userscript.html?name=Bilibili%2520Evolved.user.js&id=02db97bb-10b8-4d19-a33b-18b25c7d7cf3), 
:1:2709)

**附加截图**
![QQ图片20200719095423](https://user-images.githubusercontent.com/26663837/87865364-0d6a1980-c9a7-11ea-8203-b713ee7ac978.png)

**Comment by the1812** [comment]
重置下快速收藏试试, 浏览器控制台(<kbd>Ctrl+Shift+I</kbd>)里运行
```js
bilibiliEvolved.settings.quickFavoriteID = 0
```

**Comment by q56535** [comment]
重置后不再出现该问题
