### ISSUE TITLE
开启插件之后无法正常使用稍后再看

### ISSUE THREAD

**Issue by TsuiEnPeng** [the1812/Bilibili-Evolved#742]
**关于哪一项功能**

**问题描述**

**脚本版本**

版本：1.10.31

**浏览器版本**

版本 84.0.4147.89（正式版本）
**错误信息**

没有错误信息，当这个插件开启使用的时候，稍后再看里的视频点击后就跳转到这个空白页（about:blank#blocked），关闭插件后才能正常使用
**附加截图**

**Comment by the1812** [comment]
#722
