### ISSUE TITLE
此视频没有DASH格式, 请改用FLV格式

### ISSUE THREAD

**Issue by ToneySun** [the1812/Bilibili-Evolved#743]
**关于哪一项功能**
视频下载，Aria RPC，批量下载

**问题描述**
我批量下载Aria RPC一发送，就“此视频没有DASH格式, 请改用FLV格式”，**我试过issue中的一个问题的解答，就是把视频，一个一个的下载，确实没有报这个错误，但是！我要下载的视频有685P，如果每次手点的话，就会人傻掉的。**

**脚本版本**
1.10.31 

我希望修复这个“我明明选得是FLV但提示我DASH格式的bug”，或者说新增一个“Aria2 RPC自定义请求的功能”：意思就是假设我要下的视频有685P，那么按下按钮，脚本就会批量发送685个Aria2 RPC的请求

**Comment by the1812** [comment]
那每次导出100个呢

**Comment by ToneySun** [comment]
每次导出100，有时候可以，有时候还是会提示“此视频没有DASH格式，请改用FLV格式”




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月20日(星期一) 中午1:55
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"追风"<snowion@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 此视频没有DASH格式, 请改用FLV格式 (#743)





 
那每次导出100个呢
