### ISSUE TITLE
高能进度条未能适配主题颜色

### ISSUE THREAD

**Issue by LonelySteve** [the1812/Bilibili-Evolved#744]
**关于哪一项功能**

高能进度条

**问题描述**

随便打开一个有高能进度条的视频，比如 [BV1jK411J7Xx](https://www.bilibili.com/video/BV1jK411J7Xx)

1. 无论是正式版还是预览版，设置主题颜色都不会影响到高能进度条原有的背景颜色，显然，当设置的主题颜色不为蓝色，那么蓝色的高能进度条和自定义的主题颜色的进度条搭配在一起就有很强的违和感（图一、图二）
2. 在预览版本的夜间模式下的高能进度条会呈现与当前设置的主题颜色反色的效果（图三）

**脚本版本**

Stable v1.10.31, Preview v1.10.32

**浏览器版本**

Chrome  83.0.4103.116

**附加截图**

## 图一

![image](https://user-images.githubusercontent.com/34429322/87903080-c30f9800-ca8d-11ea-9144-b81136af9333.png)

## 图二

![image](https://user-images.githubusercontent.com/34429322/87902149-74f99500-ca8b-11ea-8319-6a8be9eebbff.png)

## 图三

![image](https://user-images.githubusercontent.com/34429322/87902782-159c8480-ca8d-11ea-8c33-1867082587bb.png)

**Comment by Geeyun-JY3** [comment]
既然说到高能进度条了，我想顺便问问：b 站现在是把高能进度条的设置项隐藏了吗？在我目前的使用过程中高能进度条还是会按照先前设置的选项运行，但似乎不会跟随帐号走（换个浏览器就重置了）。

（如果是隐藏了）或者能不能先通过脚本把这个隐藏设置项给调出来？

**Comment by the1812** [comment]
糟糕 他现在不给修改的选项 我也不知道这颜色到底存在哪了

**Comment by LonelySteve** [comment]
> 糟糕 他现在不给修改的选项 我也不知道这颜色到底存在哪了

这颜色应该是通过 fill 属性直接写在了 rect 元素上（Attributes Style）：

![image](https://user-images.githubusercontent.com/34429322/90215565-8b96d000-de2e-11ea-8d53-e1434287a97d.png)

**Comment by the1812** [comment]
我是说储存颜色值的地方, 不是最后被应用到的元素位置
因为我想适配后把所有人的这个颜色改回默认的, 不然像我这种以前就用过高能进度条且改过颜色的人最后颜色还是不对

**Comment by LonelySteve** [comment]
> 我是说储存颜色值的地方, 不是最后被应用到的元素位置
> 因为我想适配后把所有人的这个颜色改回默认的, 不然像我这种以前就用过高能进度条且改过颜色的人最后颜色还是不对

我不清楚以前这个值是怎么被存储的，但现在来看这个值应该没有被放在 localStorage 或者 Cookie 中，我在一个名称为 pbp 的 js 中找到了这个颜色值的声明位置，以及它被应用到 rect 元素上的代码：

![image](https://user-images.githubusercontent.com/34429322/90245110-9d936580-de64-11ea-84ad-d436550f0d76.png)

![image](https://user-images.githubusercontent.com/34429322/90244998-66bd4f80-de64-11ea-9ffc-8fa2f0f13c86.png)

**Comment by LonelySteve** [comment]
<details> 
<summary><em>这里面写这么多肯定没人看（</em></summary>
闲着又看了一下 pbp 这块的代码，发现这个高能进度条的主题颜色主要是通过以下代码来控制的：

```javascript
    function s(e, t) {
        var i = localStorage.getItem(e);
        return null == i && p(e, t),
        i || t
    }
    var p = function(e, t) {
        localStorage.setItem(e, t)
    }
// ...
 y = {
        b: {
            fillColor: "255,255,255",
            playedColor: "35,173,229"
        },
        p: {
            fillColor: "255,255,255",
            playedColor: "251,114,153"
        },
        r: {
            fillColor: "255,255,255",
            playedColor: "178,45,67"
        },
        g: {
            fillColor: "255,255,255",
            playedColor: "11,163,150"
        }
    };
// ...
            key: "_updatePbpConfig",
            value: function() {
                var e = s("pbp_theme_v4", "b")
                  , e = y[e] ? y[e] : y.b
                  , t = s("pbp_opacity_v3", "m")
                  , t = w[t] ? w[t] : w.m;
                this.st.opacity = t,
                this.st.fillColor = "rgb(".concat(e.fillColor, ")"),
                this.st.playedColor = "rgb(".concat(e.playedColor, ")"),
                this._setThemeStyle(e.playedColor)
            }
```

不难看出，其实 `s("pbp_theme_v4", "b")` 就是通过 'b' 这个键来选定一个主题色，而这个设定会被存在 localStorage 中，相应的键名就是 "pbp_theme_v4"，除了 'b' 作为主题色之外，还有 'p', 'r', 'g' 可用：

![image](https://user-images.githubusercontent.com/34429322/97013134-448a3100-157b-11eb-8f1a-6cb957c8670b.png)

虽然似乎没办法随意控制这个 playedColor，但通过修改 localStorage 中这个 "pbp_theme_v4" 的值，在一定程度上可以勉强适配一些人选择的主题色（~~比如我选的猛男粉~~）

![image](https://user-images.githubusercontent.com/34429322/97013300-79968380-157b-11eb-89ce-442153fed801.png)

</details>

在这个 issue 还没有更好的解决方案之前，对于主题色为「蓝色」、「粉色」、「红色」和「绿色」的用户来说，可以按 `F12` 打开开发者工具，在控制台下执行以下对应的语句来设置高能进度条的 playedColor：

- 蓝色：`localStorage.setItem("pbp_theme_v4", "b")`
- 粉色：`localStorage.setItem("pbp_theme_v4", "p")`
- 红色：`localStorage.setItem("pbp_theme_v4", "r")`
- 绿色：`localStorage.setItem("pbp_theme_v4", "g")`

执行后刷新页面即可生效。

**Comment by the1812** [comment]
破案了 我以前选着粉色的时候写下了夜间 所以设成`p`才是适配主题色
那么之后就夜间改回`蓝转主题色`滤镜, 然后所有人高能进度条设置重置为蓝色

**Comment by LonelySteve** [comment]
> 破案了 我以前选着粉色的时候写下了夜间 所以设成`p`才是适配主题色
> 那么之后就夜间改回`蓝转主题色`滤镜, 然后所有人高能进度条设置重置为蓝色

我应该在哪儿把高能进度条颜色重设？🤔

目前 3ee005aded068b3328b50f18227e497c094f650f 只是把滤镜改了。

**Comment by the1812** [comment]
`src/style/dark/dark-styles.js#30` 里加一下就行了

**Comment by LonelySteve** [comment]
> `src/style/dark/dark-styles.js#30` 里加一下就行了

这个编译器是不是有 BUG？有个奇怪的现象是，如果不使用「监视模式」，修改完了之后直接编译得到的仍然是以前的代码

如果清理 `build.cache`，重新编译，得到的仍然是以前的代码，但是会生成压缩后的 js，再编译一遍，才能得到预期的编译结果🤔

**Comment by the1812** [comment]
是的, 很有问题
最近在弄编译速度优化, 顺便看看能不能找到原因
