### ISSUE TITLE
启用 `禁止跳转动态详情` 功能后在动态下方增加详情跳转按钮

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#745]
**关于哪一项功能**
禁止跳转动态详情

**期望的效果**
> 本 issue 纯属强迫症闲得蛋疼的突发奇想

在启用 `禁止跳转动态详情` 功能后，希望可以在动态（任意类型）下方增加一个 `详情 >` 按钮允许用户跳转至用户详情，具体样式可以参考被转发动态最下方的 `详情 >`（知道可以通过 `查看更多评论` 进入，但希望可以点少几下，遇到大 up 的动态也不用翻一会评论区（对就是懒🙈），唯一想到可能有点用的是能打开视频对应的动态页（？认真想想好像也挺没用的？））

转发动态：
![image](https://user-images.githubusercontent.com/49396421/87920141-602cf980-caab-11ea-8a8d-c4cac35dd918.png)

纯动态：
![image](https://user-images.githubusercontent.com/49396421/87918205-adf43280-caa8-11ea-9eca-c73e30399b33.png)

**脚本版本**
正式版 v1.10.31
预览离线版

**Comment by the1812** [comment]
点up主名字下面那个日期就能进详情

**Comment by Geeyun-JY3** [comment]
> 点up主名字下面那个日期就能进详情

是我火星了
