### ISSUE TITLE
无法保存设置

### ISSUE THREAD

**Issue by h5mcbox** [the1812/Bilibili-Evolved#746]
**关于哪一项功能**

**问题描述**

无法保存设置,刷新就还原

**脚本版本**

Stable v1.10.31
Offline Preview v733.23
Preview v1.10.32

**浏览器版本**

Chrome 84.0.4147.89

**错误信息**

无错误

**附加截图**

**Comment by the1812** [comment]
用的是Tampermonkey吗

**Comment by h5mcbox** [comment]
是

**Comment by the1812** [comment]
检查下Tampermonkey里的存储?
![image](https://user-images.githubusercontent.com/26504152/87943462-a6e11a80-cad0-11ea-8a04-599ea2cf3d20.png)

**Comment by h5mcbox** [comment]
并没有储存选项卡
可选localStorage

**Comment by h5mcbox** [comment]
补图
![image](https://user-images.githubusercontent.com/33593244/87990891-82f4f780-cb17-11ea-8f93-82fd18edecea.png)

**Comment by the1812** [comment]
没遇到过这种情况, 重装下Tampermonkey试试?

**Comment by h5mcbox** [comment]
重装了 没用

**Comment by the1812** [comment]
那换个浏览器呢? 再不行的话我也没办法了

**Comment by h5mcbox** [comment]
我只用chrome close #7462

**Comment by h5mcbox** [comment]
我只用Chrome
