### ISSUE TITLE
视频下载不完，卡90%

### ISSUE THREAD

**Issue by q33ns** [the1812/Bilibili-Evolved#750]
**关于哪一项功能**
视频下载

**问题描述**

视频下载进度条走到一定位置卡死
av711423840
BV1KD4y1D7vW

**脚本版本**

1.10.31 stable

**浏览器版本**

chrome  84.0.4147.89

**错误信息**

DevTools failed to load SourceMap: Could not load content for chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
BV1KD4y1D7vW?p=1:1 Access to manifest at 'https://s1.hdslb.com/bfs/static/jinkela/video/manifest.9a6de76fdf229e69becbb74e09a2cea3a6b31347.json' from origin 'https://www.bilibili.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
s1.hdslb.com/bfs/static/jinkela/video/manifest.9a6de76fdf229e69becbb74e09a2cea3a6b31347.json:1 GET https://s1.hdslb.com/bfs/static/jinkela/video/manifest.9a6de76fdf229e69becbb74e09a2cea3a6b31347.json net::ERR_FAILED
BV1KD4y1D7vW?p=1:1 A cookie associated with a cross-site resource at http://apm-misaka.biliapi.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/seed/jinkela/header-v2/header.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
VM19260:1 GET https://cn-sdbz-cu-v-05.bilivideo.com/upgcxcode/64/95/215779564/215779564-1-30120.m4s?expires=1595519729&platform=pc&ssig=4ZVtB75CuxkU73Mz4iLNAQ&oi=2070953825&trid=6fb804f8f207455daf7c6248c12b481au&nfc=1&nfb=maPYqpoel5MI3qOUX6YpRA==&cdnid=9454&mid=262112032&cip=222.134.1.70&orderid=0,3&logo=80000000 416 (Requested Range Not Satisfiable)
eval @ VM19260:1
downloadFragment @ VM19260:1
download @ VM19260:1
startDownload @ VM19260:1
async function (async)
startDownload @ VM19260:1
click @ VM19491:3
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=a536cbe9-3563-43b0-af64-763f46d41824:2019
invoker @ userscript.html?name=Bilibili%20Evolved.user.js&id=a536cbe9-3563-43b0-af64-763f46d41824:2344
original._wrapper @ userscript.html?name=Bilibili%20Evolved.user.js&id=a536cbe9-3563-43b0-af64-763f46d41824:7697
userscript.html?name=Bilibili%20Evolved.user.js&id=a536cbe9-3563-43b0-af64-763f46d41824:13286 视频片段51请求失败, response = 416
logError @ userscript.html?name=Bilibili%20Evolved.user.js&id=a536cbe9-3563-43b0-af64-763f46d41824:13286
startDownload @ VM19260:1
async function (async)
startDownload @ VM19260:1
click @ VM19491:3
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=a536cbe9-3563-43b0-af64-763f46d41824:2019
invoker @ userscript.html?name=Bilibili%20Evolved.user.js&id=a536cbe9-3563-43b0-af64-763f46d41824:2344
original._wrapper @ userscript.html?name=Bilibili%20Evolved.user.js&id=a536cbe9-3563-43b0-af64-763f46d41824:7697
3VM19260:1 GET https://cn-sdbz-cu-v-05.bilivideo.com/upgcxcode/64/95/215779564/215779564-1-30120.m4s?expires=1595519729&platform=pc&ssig=4ZVtB75CuxkU73Mz4iLNAQ&oi=2070953825&trid=6fb804f8f207455daf7c6248c12b481au&nfc=1&nfb=maPYqpoel5MI3qOUX6YpRA==&cdnid=9454&mid=262112032&cip=222.134.1.70&orderid=0,3&logo=80000000 416 (Requested Range Not Satisfiable)
eval @ VM19260:1
downloadFragment @ VM19260:1
download @ VM19260:1
startDownload @ VM19260:1
async function (async)
startDownload @ VM19260:1
click @ VM19491:3
invokeWithErrorHandling @ userscript.html?name=Bilibili%20Evolved.user.js&id=a536cbe9-3563-43b0-af64-763f46d41824:2019
invoker @ userscript.html?name=Bilibili%20Evolved.user.js&id=a536cbe9-3563-43b0-af64-763f46d41824:2344
original._wrapper @ userscript.html?name=Bilibili%20Evolved.user.js&id=a536cbe9-3563-43b0-af64-763f46d41824:7697

**附加截图**

![捕获](https://user-images.githubusercontent.com/51525965/88295351-e35e8180-cd2f-11ea-9e23-90093644d9da.PNG)

**Comment by the1812** [comment]
4K吗, 4K不能直接下载, 只能用下面的导出

**Comment by q33ns** [comment]
> 4K吗, 4K不能直接下载, 只能用下面的导出

是的。。不过之前下载大部分视频4k是可以的  囧
