### ISSUE TITLE
有办法屏幕某种颜色的弹幕么

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#754]
不用说都知道是什么颜色了

屏蔽全部彩色弹幕又感觉太一刀切

理论上来说屏蔽掉调色板默认提供那三款同类的颜色就差不多了

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/88799041-75ef9c80-d1d8-11ea-830d-9469cb5dddf4.png)
这三个?

**Comment by u2shana** [comment]
没错,应该还得把那两个绿色系的给屏蔽掉,开车弹幕还有牛头人弹幕太烦了

**Comment by the1812** [comment]
控制台(<kbd>Ctrl + Shift + I</kbd>)里运行这段代码:
```js
bilibiliEvolved.installStyle({
  name: 'danmakuColorBlock',
  displayName: '屏蔽颜色弹幕',
  style: `
.b-danmaku[style*='color: rgb(255, 255, 0)'],
.b-danmaku[style*='color: rgb(255, 211, 2)'],
.b-danmaku[style*='color: rgb(255, 170, 2)'] {
  display: none !important;
}
  `
})
```
只能拿rgb值匹配下了, 有其他颜色需要屏蔽的话, 你可以直接仿照里面加一行, 再运行一次就可以

**Comment by Decwar** [comment]
如果是将某种颜色弹幕还原成白色的话代码要怎么改，还有这个代码直播间支持么
谢谢

**Comment by the1812** [comment]
`display: none !important;`换成`color: #fff !important;`

**Comment by Decwar** [comment]
谢谢，
另外如果有人需要屏蔽直播间的弹幕的话 `b-danmaku` 改成 `bilibili-danmaku`
