### ISSUE TITLE
专栏界面翻译英语翻译跟进

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#759]
**关于哪一项功能**
界面翻译

**问题描述**
专栏界面翻译英语翻译跟进（见下附加截图）
（创作中心其实也有不少）
（如果只是暂时没时间跟进翻译可以无视本 issue）

**脚本版本**
正式版 v1.10.31
预览离线版

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 84.0.4147.89（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/49396421/88529929-3c316100-d033-11ea-959b-dca6981aca1b.png)

已登录情况：
![image](https://user-images.githubusercontent.com/49396421/88529881-2cb21800-d033-11ea-89bd-b8d800ff249e.png)
未登录情况（仅标注出有区别部分）：
![image](https://user-images.githubusercontent.com/49396421/88529829-199f4800-d033-11ea-9dd7-53d8446811f8.png)

**Comment by the1812** [comment]
创作中心就不弄了  量太大而且老是改来改去的  夜间都放弃那里了

**Comment by Geeyun-JY3** [comment]
> 创作中心就不弄了 量太大而且老是改来改去的 夜间都放弃那里了

OK

**Comment by Coulomb-G** [comment]
翻译主要是给海外友人给予适当的便利,所以一般都是翻译常用界面,而不是全站翻译
