### ISSUE TITLE
biliplus的跳转支持

### ISSUE THREAD

**Issue by RainEffect** [the1812/Bilibili-Evolved#76]
希望在附加功能中加入biliplus的额外支持，
方式仅仅是读取 **"window.location.host"** 后，
将 **"www.bilibili.com"** 改为 **"www.biliplus.com"** 而已，希望可以加入一下。

很简单的小功能。

**Comment by the1812** [comment]
是希望在视频/番剧页面跳转吗? 其他页面跳转貌似没什么意义.

**Comment by RainEffect** [comment]
的确，仅仅只是这两个页面跳转即可
(实际是我朋友懒癌犯了，之前跳转我都是用收藏夹JS搞定的，但是我朋友不会，又希望你的插件可以有该功能，我就来了。)

**Comment by RainEffect** [comment]
但如果该功能可以全面发展增加跳转的话，其实我感觉会更好一点吧。
个人空间页: **"space.bilibili.com/xxx/"** 跳转为 **"www.biliplus.com/space/xxx/"**
番剧详情页暂时未找到规律: **"www.bilibili.com/bangumi/media/mdxxx/"** 与 **"www.biliplus.com/bangumi/i/xxx"**

**Comment by the1812** [comment]
按你说的一共4个吧, 我不知道有多少地方能跳转, biliplus用的不多\_(:з」∠)\_

**Comment by RainEffect** [comment]
麻烦了，后面我也会提供更多的建议的~(以及协助测试一下#14号issue的解决方案)
