### ISSUE TITLE
播放页面无限刷新

### ISSUE THREAD

**Issue by Wcraft233** [the1812/Bilibili-Evolved#760]
**关于哪一项功能**
未知-视频播放页

**问题描述**

https://www.bilibili.com/video/av841379951
这个视频，打开就会无限刷新，无法正常播放

**脚本版本**

预览版1.10.32

**浏览器版本**

chrome83
**错误信息**

**附加截图**

**Comment by the1812** [comment]
可以导出份设置吗 我这可以正常播放的

**Comment by Wcraft233** [comment]
> 可以导出份设置吗我这可以正常播放的


[bilibili-evolved-settings.json.txt](https://github.com/the1812/Bilibili-Evolved/files/4994918/bilibili-evolved-settings.json.txt)

**Comment by the1812** [comment]
还是试不出来 关闭其他插件/脚本试试?

**Comment by Wcraft233** [comment]
> 还是试不出来关闭其他插件/脚本试试？

我测试了下，关闭其他脚本没有改变，但是关闭增强就正常播放了.
有一个额外的信息：似乎每次刷新时都会尝试访问 
[](https://www.bilibili.com/video/BV1e54y1q75P/?spm_id_from=333.788.videocard_series)

然后会被转换为av号

**Comment by Wcraft233** [comment]
刚才又测试了一下，似乎在脚本的运行时期是document-start时会出现问题。

**Comment by the1812** [comment]
如果关闭av号转换呢

**Comment by Wcraft233** [comment]
> 如果关闭av号转换呢

关闭转换可以正常播

**Comment by the1812** [comment]
我之后改改看吧 不知道能不能解决
