### ISSUE TITLE
显示完整视频标题

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#761]
**关于哪一项功能**
显示完整视频标题

**期望的效果**
和 `展开选集列表` 部分功能类似，当标题过长时另起一行以显示完整视频标题
如：https://www.bilibili.com/video/av73280139 、https://www.bilibili.com/video/av67772590

**脚本版本**
正式版 v1.10.31
预览离线版

**Comment by Geeyun-JY3** [comment]
想知道为啥不做呢🤔

**Comment by the1812** [comment]
鼠标放上去就可以看到完整的 而且这种场景也很少见

**Comment by Geeyun-JY3** [comment]
> 鼠标放上去就可以看到完整的 而且这种场景也很少见

我提这个主要的需求是复制标题……🤦‍♂️
