### ISSUE TITLE
首页资讯区排版略有问题

### ISSUE THREAD

**Issue by dskaowu** [the1812/Bilibili-Evolved#763]
**关于哪一项功能**
首页排版

**问题描述**

**脚本版本**

1.10.31
--

**浏览器版本**
Chrome 80

**错误信息**

如截图

**附加截图**
![TIM截图20200729165323](https://user-images.githubusercontent.com/34599430/88779452-606c7980-d1bc-11ea-951a-b9888baab4df.png)

**Comment by Coulomb-G** [comment]
可否导出设置发一下看看?

**Comment by dskaowu** [comment]
> 可否导出设置发一下看看?

{"useDarkStyle":false,"hideBanner":false,"expandDanmakuList":false,"expandDescription":true,"watchLaterRedirect":true,"touchNavBar":false,"touchVideoPlayer":false,"customControlBackgroundOpacity":0.64,"customControlBackground":false,"darkScheduleStart":"18:00","darkScheduleEnd":"6:00","darkSchedule":false,"toast":true,"fullTweetsTitle":true,"fullPageTitle":false,"removeVideoTopMask":false,"removeLiveWatermark":true,"harunaScale":true,"removeAds":true,"showBlockedAdsTip":true,"hideTopSearch":false,"touchVideoPlayerDoubleTapControl":false,"customStyleColor":"#00A0D8","preserveRank":true,"blurBackgroundOpacity":0.382,"useDefaultPlayerMode":false,"applyPlayerModeOnPlay":true,"defaultPlayerMode":"常规","useDefaultVideoQuality":true,"defaultVideoQuality":"1080P60","useDefaultDanmakuSettings":false,"enableDanmaku":true,"rememberDanmakuSettings":false,"danmakuSettings":{"subtitlesPreserve":false,"smartMask":false},"defaultPlayerLayout":"新版","defaultBangumiLayout":"新版","skipChargeList":true,"comboLike":false,"autoLightOff":false,"useCache":true,"autoContinue":true,"allowJumpContinue":false,"deadVideoTitleProvider":"稍后再看","useBiliplusRedirect":false,"biliplusRedirect":true,"framePlayback":true,"useCommentStyle":true,"imageResolution":true,"imageResolutionScale":"auto","toastInternalError":false,"i18n":false,"i18nLanguage":"日本語","playerFocus":false,"playerFocusOffset":-10,"simplifyLiveroom":false,"simplifyLiveroomSettings":{"vip":true,"fansMedal":true,"title":true,"userLevel":true,"guard":true,"systemMessage":true,"welcomeMessage":true,"giftMessage":true,"guardPurchase":true,"giftPanel":true,"kanban":true,"userEffect":true,"eventsBanner":false,"rankList":false,"popup":false,"skin":false},"customNavbar":true,"customNavbarFill":false,"customNavbarTransparent":true,"customNavbarShadow":true,"customNavbarBlur":true,"customNavbarBlurOpacity":0.7,"customNavbarOrder":{"blank1":0,"logo":1,"category":2,"rankingLink":3,"drawingLink":4,"musicLink":5,"gamesIframe":6,"livesIframe":7,"shopLink":8,"mangaLink":9,"blank2":10,"search":11,"blank3":20,"userInfo":12,"messages":13,"activities":14,"bangumi":15,"watchlaterList":16,"favoritesList":17,"historyList":18,"upload":19,"darkMode":21},"customNavbarHidden":["upload"],"customNavbarBoundsPadding":5,"customNavbarGlobalFixed":false,"playerShadow":false,"narrowDanmaku":false,"outerWatchlater":true,"videoScreenshot":false,"hideBangumiReviews":false,"filenameFormat":"[title][ - ep]","batchFilenameFormat":"[n - ][ep]","sideBarOffset":0,"noLiveAutoplay":true,"hideHomeLive":false,"noMiniVideoAutoplay":false,"useDefaultVideoSpeed":false,"defaultVideoSpeed":"1.0","hideCategory":false,"foldComment":true,"downloadVideoDefaultDanmaku":"无","downloadVideoDefaultSubtitle":"无","aria2RpcOption":{"secretKey":"","dir":"","host":"127.0.0.1","port":"6800","method":"get","skipByDefault":false,"maxDownloadLimit":"","baseDir":""},"aria2RpcOptionSelectedProfile":"","aria2RpcOptionProfiles":[{"name":"未命名","secretKey":"","dir":"","host":"127.0.0.1","port":"6800","method":"get","skipByDefault":false,"maxDownloadLimit":"","baseDir":""}],"searchHistory":[{"count":2,"keyword":"危机合约","date":"2020-07-29T07:24:45.368Z"},{"count":1,"keyword":"真伤","date":"2020-07-27T17:17:45.173Z"},{"count":2,"keyword":"恶之花","date":"2020-07-25T17:52:31.078Z"},{"count":1,"keyword":"js","date":"2020-07-22T15:54:10.930Z"},{"count":1,"keyword":"go","date":"2020-07-22T14:10:06.924Z"},{"count":1,"keyword":"DSK嗷呜","date":"2020-07-20T07:26:26.500Z"},{"count":1,"keyword":"旅游","date":"2020-07-19T13:38:14.690Z"},{"count":1,"keyword":"V1vV411k75r","date":"2020-07-16T18:07:50.800Z"},{"count":1,"keyword":"画电路板","date":"2020-07-15T16:43:42.890Z"},{"count":1,"keyword":"COD16","date":"2020-07-11T08:39:35.534Z"}],"seedsToCoins":false,"autoSeedsToCoins":true,"lastSeedsToCoinsDate":0,"autoDraw":true,"keymap":true,"doubleClickFullscreen":false,"doubleClickFullscreenPreventSingleClick":false,"simplifyHome":false,"simplifyHomeStyle":"清爽","minimalHomeSettings":{"showSearch":true,"backgroundImage":""},"ajaxHook":false,"scriptLoadingMode":"同时(自动)","scriptDownloadMode":"bundle","guiSettingsDockSide":"右侧","fullActivityContent":true,"feedsFilter":true,"feedsFilterPatterns":[],"feedsFilterTypes":[],"feedsSpecialFilterTypes":[],"feedsFilterSideCards":["1"],"activityImageSaver":true,"scriptBlockPatterns":[],"customNavbarSeasonLogo":false,"selectableColumnText":true,"downloadVideoFormat":"flv","downloadVideoDashCodec":"AVC/H.264","watchlaterExpireWarningDays":14,"superchatTranslate":false,"miniPlayerTouchMove":false,"hideBangumiSponsors":true,"hideRecommendLive":true,"hideRelatedVideos":false,"defaultMedalID":183511,"autoMatchMedal":true,"customStyles":[],"simpleHomeCategoryOrders":{"anime":0,"bangumi":1,"china":2,"manga":3,"music":4,"dance":5,"game":6,"tech":7,"digital":8,"life":9,"kichiku":10,"fashion":11,"information":12,"entertainment":13,"column":14,"movie":15,"tv":16,"film":17,"documentary":18,"ads":12},"simpleHomeBangumiLayout":"时间表","keymapJumpSeconds":85,"urlParamsClean":true,"collapseLiveSideBar":true,"removeGameMatchModule":true,"noDarkOnMember":true,"feedsTranslate":true,"feedsTranslateProvider":"Bing","feedsTranslateLanguage":"","downloadVideoQuality":120,"defaultLiveQuality":"原画","useDefaultLiveQuality":true,"recordLiveDanmaku":false,"foregroundColorMode":"自动","preserveEventBanner":true,"about":true,"bvidConvert":true,"fixedSidebars":false,"updateCdn":"GitHub","lastNewVersionCheck":1596007460039,"newVersionCheckInterval":21600000,"useDarkStyleAsUserStyle":false,"darkColorScheme":false,"autoHideSideBar":true,"livePip":true,"extendFeedsLive":true,"userImages":[],"playerOnTop":false,"restoreFloors":false,"quickFavorite":false,"quickFavoriteID":0,"bilibiliSimpleNewHomeCompatible":false,"preferAvUrl":false,"disableFeedsDetails":true,"elegantScrollbar":true,"danmakuSendBar":false,"watchLaterRedirectNavbar":true,"watchLaterRedirectPage":true,"showCoverBeforePlay":false,"volumeOverdrive":false,"autoPlay":false,"favoritesRedirect":false,"compactLayout":false,"hideOldEntry":false,"guiSettings":true,"viewCover":true,"notifyNewVersion":true,"clearCache":true,"downloadVideo":true,"enableDashDownload":true,"downloadDanmaku":true,"downloadSubtitle":true,"downloadAudio":true,"downloadLiveRecords":true,"medalHelper":true,"playerLayout":false,"forceWide":false,"useNewStyle":false,"overrideNavBar":false,"touchVideoPlayerAnimation":false,"allNavbarFill":false,"showDeadVideoTitle":false,"blurVideoControl":false,"oldTweets":false,"customNavbarCompact":false,"watchlaterExpireWarnings":false,"latestVersionLink":"https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@master/bilibili-evolved.user.js","currentVersion":"1.10.31","foreground":"#fff","blueImageFilter":"hue-rotate(1deg) saturate(100%)","pinkImageFilter":"hue-rotate(-147deg) saturate(145%)","brightness":"0%","filterInvert":"invert(1)"}

**Comment by Coulomb-G** [comment]
你的分辨率是多少?

**Comment by dskaowu** [comment]
> 你的分辨率是多少?

1080p，系统125%缩放
![image](https://user-images.githubusercontent.com/34599430/88783007-da066680-d1c0-11ea-907f-e762ced00c77.png)

**Comment by Coulomb-G** [comment]
暂时关闭「高分辨图片」这个功能吧

**Comment by the1812** [comment]
b站似乎已修复这个问题
