### ISSUE TITLE
预览离线版744.47对b站界面不生效

### ISSUE THREAD

**Issue by Rimliya** [the1812/Bilibili-Evolved#766]
**关于哪一项功能**

**问题描述**

**脚本版本**
预览离线版744.47

**浏览器版本**
Chrome 86.0.577.0 
 

**错误信息**

![image](https://user-images.githubusercontent.com/48489813/88872590-1e3f4880-d24d-11ea-9492-85128fd58829.png)

**附加截图**

![image](https://user-images.githubusercontent.com/48489813/88872551-ffd94d00-d24c-11ea-884e-42107ae6ed1c.png)

**Comment by the1812** [comment]
确认下这些依赖库能否正常打开?

https://cdn.jsdelivr.net/npm/jquery@3.4.0/dist/jquery.min.js
https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js
https://cdn.jsdelivr.net/npm/jszip@3.1.5/dist/jszip.min.js
尤其是这个 https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js
https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.js

**Comment by Rimliya** [comment]
> 确认下这些依赖库能否正常打开?
> 
> https://cdn.jsdelivr.net/npm/jquery@3.4.0/dist/jquery.min.js
> https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js
> https://cdn.jsdelivr.net/npm/jszip@3.1.5/dist/jszip.min.js
> 尤其是这个 https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js
> https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.js

![image](https://user-images.githubusercontent.com/48489813/88872878-dbca3b80-d24d-11ea-98e0-424548aec75f.png)
这样算是打开了吗

**Comment by the1812** [comment]
嗯  都能打开再去b站试试  还不行的话重装下脚本

**Comment by Rimliya** [comment]
> 嗯 都能打开再去b站试试 还不行的话重装下脚本

主要是我直接用的733
之后来github升级了就不行了

**Comment by Rimliya** [comment]
> 嗯 都能打开再去b站试试 还不行的话重装下脚本

![image](https://user-images.githubusercontent.com/48489813/88873148-935f4d80-d24e-11ea-8dd4-6ec27cfe28c5.png)
已经生效了，但是有这个提示

**Comment by the1812** [comment]
这个对应的是 https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js

**Comment by the1812** [comment]
这里可以看Tampermonkey下载的依赖

![image](https://user-images.githubusercontent.com/26504152/88873440-3a43e980-d24f-11ea-9962-5ae123741418.png)

**Comment by Rimliya** [comment]
> 这里可以看Tampermonkey下载的依赖
> 
> ![image](https://user-images.githubusercontent.com/26504152/88873440-3a43e980-d24f-11ea-9962-5ae123741418.png)

谢谢，已经多次重装解决了，还有jsDelivr的源已经403了

**Comment by ssxwcz** [comment]
同样的问题，多次重装离线预览版后恢复正常

**Comment by the1812** [comment]
有点怪  jsDelivr怎么突然挂了

**Comment by Rimliya** [comment]
> 嗯 都能打开再去b站试试 还不行的话重装下脚本

新问题，视频评论区加载不出来
![image](https://user-images.githubusercontent.com/48489813/88877046-374cf700-d257-11ea-8ea9-6d4a5efbfe6b.png)

![image](https://user-images.githubusercontent.com/48489813/88877097-5055a800-d257-11ea-8d60-68b40a85f5d5.png)

**Comment by the1812** [comment]
报的错应该跟 #770 一样
