### ISSUE TITLE
jsDelivr安装源提示403错误

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#767]
**关于哪一项功能**
在README中的安装源

**问题描述**

安装正式版和预览版时出现403，我这里是北京-联通。

**脚本版本**

**浏览器版本**

chrome 84

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/88873998-92c7b680-d250-11ea-9bad-362470b8a0b2.png)

**Comment by the1812** [comment]
#766 里也提到了
貌似`https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved`开头的都会 403

**Comment by CKylinMC** [comment]
好像是，不清楚什么问题，图片里报错是无效请求。我刚刚想去试试看最新测试版的时候发现的。

**Comment by the1812** [comment]
暂时先用着 Fast.io 源吧

**Comment by yanglr** [comment]
@CKylinMC 可能流量超了，参考这个https://github.com/jsdelivr/jsdelivr/issues/18035#issuecomment-325920823，我的个人仓库今天也出现这个问题了~

**Comment by the1812** [comment]
那里说的不是单文件不能超50MB吗

**Comment by yanglr** [comment]
> The 50 MB limit is for the whole release, not a single file. The release is ~86 MB unzipped, which means it's too big.
> In most cases, when a package is this big, there are files that are not really needed and could be removed to reduce the size. 
不是单个文件大小喔，他提到的`release`可能指的是是一个branch~

**Comment by the1812** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18238

**Comment by the1812** [comment]
jsDelivr 已修复

**Comment by CKylinMC** [comment]
README的安装源大概可以恢复了？

**Comment by the1812** [comment]
那个是因为 #770 关闭的, 大概明天恢复
