### ISSUE TITLE
显示bug

### ISSUE THREAD

**Issue by 18263212936** [the1812/Bilibili-Evolved#769]
直播经常屏蔽音量调节之类，多次刷新才显示
视频页面评论区被隐藏推荐列表与作者头像不显示
Chrome
版本 84.0.4147.105（正式版本） （64 位）

**Comment by visitgh** [comment]
是不是也不显示视频的评论了

**Comment by 18263212936** [comment]
对，整个评论区都没有了

---原始邮件---
发件人: &quot;visitgh&quot;<notifications@github.com&gt;
发送时间: 2020年7月30日 11:45:43
收件人: &quot;the1812/Bilibili-Evolved&quot;<Bilibili-Evolved@noreply.github.com&gt;;
抄送: &quot;Feather&quot;<1904942354@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [the1812/Bilibili-Evolved] 显示bug (#769)




 
是不是也不显示视频的评论了
 
&mdash;

**Comment by visitgh** [comment]
昨天晚上还好好的

**Comment by the1812** [comment]
昨晚播放器改版了
统一在 #770 讨论吧
