### ISSUE TITLE
播放器改版后bug 点赞/投币/收藏/评论区/分P选集/推荐视频 等

### ISSUE THREAD

**Issue by 1421356447** [the1812/Bilibili-Evolved#770]
**关于哪一项功能**
视频下方的点赞投币收藏按钮点击后提示需要登录，稍后再看没有问题

**问题描述**

任何视频都有此问题

**脚本版本**

1.10.31

**浏览器版本**

Chrome 84.0.4147.89

**错误信息**

stardust-video.1b2caae945b46117ca9434e84f0824ec40b81624.js?__WB_REVISION__=1b2caae945b46117ca9434e84f0824ec40b81624:7 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.1b2caae945b46117ca9434e84f0824ec40b81624.js?__WB_REVISION__=1b2caae945b46117ca9434e84f0824ec40b81624:7:40898)
    at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.1b2caae945b46117ca9434e84f0824ec40b81624.js?__WB_REVISION__=1b2caae945b46117ca9434e84f0824ec40b81624:7:57231)
...
(anonymous) @ stardust-video.1b2caae945b46117ca9434e84f0824ec40b81624.js?__WB_REVISION__=1b2caae945b46117ca9434e84f0824ec40b81624:1

**附加截图**
![Snipaste_2020-07-30_11-25-04](https://user-images.githubusercontent.com/30023789/88877107-55b2f280-d257-11ea-82c7-7bc64445db10.png)

**Comment by the1812** [comment]
关掉脚本后正常吗

**Comment by 1421356447** [comment]
关闭之后正常




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 中午11:28
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"尚桉"<1421356447@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 点赞投币收藏按钮错误 (#770)





 
关掉脚本后正常吗

**Comment by the1812** [comment]
似乎跟最近播放器的改版有关

**Comment by 1421356447** [comment]
那我先关掉插件一段时间吧

**Comment by CGleam** [comment]
**【bug补充】**
**关于哪一项功能**
无法显示视频播放数、弹幕数、UP主头像、相关推荐视频封面、评论，有视频选集的视频无法显示选集列表

**问题描述**

任何视频都有此问题。关闭脚本后恢复正常。

**脚本版本**

1.10.31

**浏览器版本**

Microsoft Edge 版本 84.0.522.49 (官方内部版本) (64 位)

**附加截图**
<img width="746" alt="image_289" src="https://user-images.githubusercontent.com/59286183/88879125-11762100-d25c-11ea-8c2b-ad7caaa41287.png">
<img width="755" alt="image_290" src="https://user-images.githubusercontent.com/59286183/88879133-163ad500-d25c-11ea-9522-39ed544e367f.png">

**Comment by CGleam** [comment]
> **附加截图**
> <img alt="image_289" width="746" src="https://user-images.githubusercontent.com/59286183/88879125-11762100-d25c-11ea-8c2b-ad7caaa41287.png">

**【bug补充】**
**关于哪一项功能**
点赞投币收藏按钮的状态也不能正确显示了，图中视频我是三连了的，但相关的按钮仍为灰色，数量也不显示

**Comment by ztelliot** [comment]
在注销状态下能正常显示，无bug

**Comment by EricEric66666** [comment]
评论区显示不出来

**Comment by Soupure** [comment]
今天bug有点多啊，评论区和一些图片都没了

**Comment by the1812** [comment]
改版导致和b站最基础的那部分代码冲突了  基本上视频页面大部分功能都会挂
在我修复之前请暂时停止使用脚本

**Comment by the1812** [comment]
同时, jsDelivr的403错误(#767)会导致新安装的脚本直接全部无效

**Comment by CKylinMC** [comment]
评论区消失是今天中午才出现的应该，上午访问还没事呢...

**Comment by 1421356447** [comment]
啊，不说评论区消失的话我还没发现

**Comment by the1812** [comment]
有些人上午就遇到了

**Comment by InoryLwc** [comment]
我也是啊，我还说是怎么回事呢，明明登陆，点赞投币什么都不行，评论区不见了，图片有些加载不出来，想了各种办法，结果油猴一关就正常了，然后发现是这个脚本的问题。
不登录的话没bug好像是这样的。

**Comment by Malus-Mill** [comment]
+1刚才还好好的，突然就BUG了

**Comment by the1812** [comment]
(GreasyFork 上已暂时下架)

**Comment by SnowMeteors** [comment]
刚刚想报告一下评论区消失，up主头像，视频封面不加载的bug，结果都报告了啊，哪我坐等修复bug

**Comment by dmddjack** [comment]
坐等修复，辛苦了

**Comment by MARINGTIN** [comment]
原来是播放器改版导致的问题，我就说怎么重启也解决不了。

**Comment by 1161474617** [comment]
为啥我一直用也没发现有那截图中的问题呢？

**Comment by 1161474617** [comment]
还有我用的不是油猴 我用的是暴力猴（和油猴相似的插件）

**Comment by 2763654419** [comment]
我这里没大问题，黑夜模式总是要清理缓存之后刷新一次才能启用
另外提示错误：Unexpected token <

**Comment by 2763654419** [comment]
坐等大佬修复了

**Comment by MARINGTIN** [comment]
> 为啥我一直用也没发现有那截图中的问题呢？

不清楚鸭，我的评论区消失，然后相关视频封面刷不出来，点赞之类的全部失效

**Comment by 1161474617** [comment]
没去点赞，，点赞 投币都没了

**Comment by lt769830300** [comment]
把视频选项中外置稍后再看这个功能关闭就恢复正常了

**Comment by MARINGTIN** [comment]
> 把视频选项中外置稍后再看这个功能关闭就恢复正常了

实测有效

**Comment by 1161474617** [comment]
> 把视频选项中外置稍后再看这个功能关闭就恢复正常了

确实有效

**Comment by the1812** [comment]
那太好了 晚上应该就能修好

**Comment by the1812** [comment]
快速收藏不会导致吗

**Comment by CGleam** [comment]
> 快速收藏不会导致吗



> 把视频选项中外置稍后再看这个功能关闭就恢复正常了

也会，这两个都要关

**Comment by MARINGTIN** [comment]
> 快速收藏不会导致吗

打开后出现了相同问题，两个都要关闭才行

**Comment by the1812** [comment]
好的 我大概知道原因了

**Comment by kuainx** [comment]
ChromiumEdge提示报错：
指示是否希望通过指定 cookie 的 SameSite 属性在跨网站请求中发送 cookie
由于未设置 cookie 的 SameSite=Lax 属性或此属性无效，所以默认值为 SameSite=Lax，这将阻止在以后版本的浏览器中跨站点请求发送此 cookie。 此行为可防止用户数据意外泄露给第三方和跨网站请求伪造。

**Comment by 2763654419** [comment]
> > 快速收藏不会导致吗
> 
> > 把视频选项中外置稍后再看这个功能关闭就恢复正常了
> 
> 也会，这两个都要关
的确有用

**Comment by Louis-Hanse** [comment]
> 刚刚想报告一下评论区消失，up主头像，视频封面不加载的bug，结果都报告了啊，哪我坐等修复bug

+1，刚报告完就发现这里有人说了同样问题

**Comment by fakedestinyck** [comment]
@the1812 还有另外一个问题不知道和上面说的有没有关系。就是把上面说的两项都禁用之后，消失的评论区什么的都出现了没问题了，但是启用`高分辨率图片`这一项会导致控制栏报错如图，并且页面会很卡：
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/16526801/88911417-63d13500-d290-11ea-8857-47ba448a684f.png">
脚本版本是离线预览版730.21，浏览器是Safari V14.0。辛苦了

**Comment by the1812** [comment]
这个你先关了吧, 两千多条错误肯定很卡

**Comment by RIKR6735** [comment]
我这里评论区没问题，倒是视频都无法显示了
![图片](https://user-images.githubusercontent.com/61101622/88912355-bc550200-d291-11ea-95ad-91f722d3df24.jpg)

**Comment by ssxwcz** [comment]
> 我这里评论区没问题，倒是视频都无法显示了
> ![图片](https://user-images.githubusercontent.com/61101622/88912355-bc550200-d291-11ea-95ad-91f722d3df24.jpg)

你是不是安装了哔哩哔哩弹幕姬，我开启这个脚本就会出现类似情况

**Comment by 1161474617** [comment]
> 我这里评论区没问题，倒是视频都无法显示了
> ![图片](https://user-images.githubusercontent.com/61101622/88912355-bc550200-d291-11ea-95ad-91f722d3df24.jpg)

先确定是不是其他关于bilibili的插件或者脚步的问题

**Comment by RIKR6735** [comment]
> > 我这里评论区没问题，倒是视频都无法显示了
> > ![图片](https://user-images.githubusercontent.com/61101622/88912355-bc550200-d291-11ea-95ad-91f722d3df24.jpg)
> 
> 你是不是安装了哔哩哔哩弹幕姬，我开启这个脚本就会出现类似情况

证实了，确实是弹幕姬的问题

**Comment by Charles276** [comment]
作者你好哈，我刚刚试了下，把样式下的夜间模式关了，然后刷新，评论，点赞投币之类就正常了。不知道其他网友是不是这样就可以呢。我也试了关闭快速收藏，还有稍后再看什么的。发现把夜间模式关了是最有效的。

**Comment by Geeyun-JY3** [comment]
> 作者你好哈，我刚刚试了下，把样式下的夜间模式关了，然后刷新，评论，点赞投币之类就正常了。不知道其他网友是不是这样就可以呢。我也试了关闭快速收藏，还有稍后再看什么的。发现把夜间模式关了是最有效的。

这个 bug 早上就发现了，我当时就没开夜间模式，目前按 https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666189125 的做法才能解决，和夜间模式无关

**Comment by the1812** [comment]
根本原因是在播放器加载完成前添加了稍后再看之类的按钮导致冲突
关夜间只是改变了加载速度 减少冲突的几率

**Comment by Kaneki521** [comment]
正想着反馈，原来已经反馈过了，那就开发者大大辛苦一下，早日修复

**Comment by wwzw27** [comment]
> > > 快速收藏不会导致吗
> > 
> > 
> > > 把视频选项中外置稍后再看这个功能关闭就恢复正常了
> > 
> > 
> > 也会，这两个都要关
> > 的确有用

两个都关了也没有效果。

**Comment by you-wanna** [comment]
B站最近改版改的有点多啊

**Comment by wwzw27** [comment]
是的 所以开发者大大你得做好准备脚本大改的准备 hhhhh




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "you-wanna"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 晚上10:16
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "2548334609"<2548334609@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved]播放器改版后bug 点赞/投币/收藏/评论区/分P选集/推荐视频 等 (#770)





 
B站最近改版改的有点多啊
 
- 
您收到此评论是因为您发表了评论。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by C9527** [comment]
无法显示评论区、相关推荐封面图片，希望大佬修复吧

**Comment by the1812** [comment]
可以试下预览版了, 没问题我就正式发布了
预览 v1.10.33 https://subterranean-rose.imfast.io/bilibili-evolved.preview.user.js
预览离线 v745.28 https://subterranean-rose.imfast.io/bilibili-evolved.preview-offline.user.js

**Comment by ssxwcz** [comment]
> 可以试下预览版了, 没问题我就正式发布了
> 预览 v1.10.33 https://subterranean-rose.imfast.io/bilibili-evolved.preview.user.js
> 预览离线 v745.28 https://subterranean-rose.imfast.io/bilibili-evolved.preview-offline.user.js

开启稍后再看和快速收藏后，以上反馈的问题“评论区无法显示”、“推荐视频无封面”、“无法点赞投币”、“up主头像不显示”等问题都已经正常了

**Comment by bigbug-dev** [comment]
> > 可以试下预览版了, 没问题我就正式发布了
> > 预览 v1.10.33 https://subterranean-rose.imfast.io/bilibili-evolved.preview.user.js
> > 预览离线 v745.28 https://subterranean-rose.imfast.io/bilibili-evolved.preview-offline.user.js
> 
> 我这边测试，开启稍后再看和快速收藏后，以上反馈的问题“评论区无法显示”、“推荐视频无封面”、“无法点赞投币”、“up主头像不显示”等问题都已经正常了

+1

**Comment by MARINGTIN** [comment]
预览版正常

**Comment by xzk-kokodayo** [comment]
> 可以试下预览版了, 没问题我就正式发布了
> 预览 v1.10.33 https://subterranean-rose.imfast.io/bilibili-evolved.preview.user.js
> 预览离线 v745.28 https://subterranean-rose.imfast.io/bilibili-evolved.preview-offline.user.js

预览版正常

**Comment by CKylinMC** [comment]
预览版正常。

**Comment by 995871491** [comment]
辛苦了，顺便能不能增加一下倍数播放的上限，现在最高3倍已经适应了，其他软件也能达到更高倍吧，但是没有快捷键就懒得用

**Comment by the1812** [comment]
> 辛苦了，顺便能不能增加一下倍数播放的上限，现在最高3倍已经适应了，其他软件也能达到更高倍吧，但是没有快捷键就懒得用

现在不会. (也许以后会

**Comment by jrdzsm** [comment]
> 可以试下预览版了, 没问题我就正式发布了
> 预览 v1.10.33 https://subterranean-rose.imfast.io/bilibili-evolved.preview.user.js
> 预览离线 v745.28 https://subterranean-rose.imfast.io/bilibili-evolved.preview-offline.user.js

预览版正常

**Comment by yy56820** [comment]
> 可以试下预览版了, 没问题我就正式发布了
> 预览 v1.10.33 https://subterranean-rose.imfast.io/bilibili-evolved.preview.user.js
> 预览离线 v745.28 https://subterranean-rose.imfast.io/bilibili-evolved.preview-offline.user.js

预览版正常

**Comment by BSDxxxx** [comment]
> 辛苦了，顺便能不能增加一下倍数播放的上限，现在最高3倍已经适应了，其他软件也能达到更高倍吧，但是没有快捷键就懒得用

推荐使用：https://github.com/xxxily/h5player

**Comment by Geeyun-JY3** [comment]
> 推荐使用：https://github.com/xxxily/h5player

温馨提醒：该脚本会与本脚本「快捷键扩展」功能冲突
相关 issue：#534

**Comment by WoeGod** [comment]
> 辛苦了，顺便能不能增加一下倍数播放的上限，现在最高3倍已经适应了，其他软件也能达到更高倍吧，但是没有快捷键就懒得用

[视频网html5播放小工具](https://greasyfork.org/zh-CN/scripts/30545-视频网html5播放小工具 )
可以试试这个插件

**Comment by qipaguan** [comment]
预览版正常

**Comment by Cairl** [comment]
希望以后新版能加入自定义弹幕字体和查询弹幕发送者的功能

**Comment by the1812** [comment]
> 希望以后新版能加入自定义弹幕字体和查询弹幕发送者的功能

这个你另开一个 issue 吧, 弹幕字体我可以写个样式给你
弹幕发送者我记得别的脚本/插件可以查询

**Comment by Cairl** [comment]
> > 希望以后新版能加入自定义弹幕字体和查询弹幕发送者的功能
> 
> 这个你另开一个 issue 吧, 弹幕字体我可以写个样式给你
> 弹幕发送者我记得别的脚本/插件可以查询

不好意思不太懂github和代码这方面的学问，只是想反馈一下希望能融合进去的功能

**Comment by TracyRuri** [comment]
1.10.33解决问题了吗

**Comment by WoeGod** [comment]
> 查询弹幕发送者的功能

这个谷歌插件有查询弹幕发送者功能[哔哩哔哩助手：bilibili.com 综合辅助扩展](https://chrome.google.com/webstore/detail/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%8A%A9%E6%89%8B%EF%BC%9Abilibilicom-%E7%BB%BC%E5%90%88%E8%BE%85%E5%8A%A9%E6%89%A9%E5%B1%95/kpbnombpnpcffllnianjibmpadjolanh)

**Comment by Geeyun-JY3** [comment]
@TracyRuri 在这条 issue 稍微往上翻翻不难吧……

**Comment by CKylinMC** [comment]
> 希望以后新版能加入自定义弹幕字体和查询弹幕发送者的功能

查询弹幕发送者目前知道最简单的是pakku，不过新版本播放器更新之后失效了，我给作者提过issue了，一周之内更新。

**Comment by huangsijun17** [comment]
![image](https://user-images.githubusercontent.com/31504595/89034483-a0be2a00-d36b-11ea-90f1-51c914a1ae50.png)
我看到的这个更加诡异，右上角没有UP主信息。

**Comment by Santo-wiar** [comment]
我把“自动展开视频简介”这一项关掉，就没问题了

**Comment by JsMoriarty** [comment]
啊哈哈哈哈，我说呢，我还找客服反映了一下，最后把插件关来关去，发现是油猴导致的，而油猴里面只有这个脚本和B站有关系，等作者更新喽～

**Comment by Kegekkk** [comment]
评论区的显示正常了，preview offline

**Comment by miaotouy** [comment]
测试了一遍发现和哔哩哔哩视频下载器（https://greasyfork.org/scripts/401077-bilibili-video-downloader）有关，
关掉下载器脚本就能正常显示了，这个脚本目前已下架

**Comment by MC-dusk** [comment]
楼上的问题都或多或少出现过，但不是每轮必复现，简单地说就是感觉开了脚本加载b站卡顿慢了许多，导致可能部分模块加载不全或错位（比如“up觉得赞”标识向右偏移），电脑（联想Y7000 2019）和浏览器（火狐）和脚本管理器（暴力猴）应该都是性能足够，网络也没问题，其他网页和脚本运行正常，个人感觉可能是因为这个脚本太大了（瞎猜的），不知道有什么好的解决办法。（比如拆分功能？）

**Comment by the1812** [comment]
up觉得很赞是我故意改的位置 见#773
脚本太大的问题会在2.0版中解决(有生之年

**Comment by CKylinMC** [comment]
脚本太大其实我觉得不是所有人都用得到所有的功能，可以拆成按需加载？每个功能一个js，如果开启了，那么，或是用户手动安装，或是由脚本来require，否则就不加载，这样插件式可能好点（貌似现在部分功能就是这样？）

**Comment by the1812** [comment]
对 以后内置只带3~4个功能 其他的给你们自己选择安装

**Comment by CKylinMC** [comment]
...越来越像一个新的插件管理器了

**Comment by Ant1597** [comment]
来迟了……不过我注意到，评论区不显示和点赞/投币/收藏弹出登录两个问题，在关闭“外置稍后再看”和“启用快速收藏”后就正常了。
Chromium 83, Tampermonkey 4.10, bilibili-Evolved 1.10.33

**Comment by XTsat** [comment]
> > 希望以后新版能加入自定义弹幕字体和查询弹幕发送者的功能
> 
> 查询弹幕发送者目前知道最简单的是[pakku](http://s.xmcp.ml/pakkujs/)（[xmcp/pakku.js](https://github.com/xmcp/pakku.js)），不过新版本播放器更新之后失效了，我给作者提过issue了，一周之内更新。
> 
> 话说自定义字体功能貌似是有的吧。。。我记得看到过啊

好像pakku的ctrl没了，但是弹幕列表还是可以用

**Comment by CKylinMC** [comment]
> 好像pakku的ctrl没了，但是弹幕列表还是可以用

有的，最新版已经更新了，功能正常

**Comment by Geeyun-JY3** [comment]
> 来迟了……不过我注意到，评论区不显示和点赞/投币/收藏弹出登录两个问题，在关闭“外置稍后再看”和“启用快速收藏”后就正常了。
> Chromium 83, Tampermonkey 4.10, bilibili-Evolved 1.10.33

https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666189125 已经提到过了，而且[正式版 v1.10.33](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.10.33) 已经修了这个 bug 了……

**Comment by Ant1597** [comment]
> > 来迟了……不过我注意到，评论区不显示和点赞/投币/收藏弹出登录两个问题，在关闭“外置稍后再看”和“启用快速收藏”后就正常了。
> > Chromium 83, Tampermonkey 4.10, bilibili-Evolved 1.10.33
> 
> @Ant1597 [#770 (comment)](https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666189125) 已经提到过了，而且 [正式版 v1.10.33](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.10.33) 已经修了这个 bug 了……

了解了，抱歉打扰了讨论串……没有注意到折叠的中间讨论。非常感谢！

**Comment by 1103940600** [comment]
什么时候可以下载4k视频

**Comment by 1103940600** [comment]
> 什么时候可以下载4k视频

不好意思，格式选dash就可以了，用了这么久我竟然不知道
