### ISSUE TITLE
评论区消失，相关视频的预览图消失

### ISSUE THREAD

**Issue by SakuraVAC** [the1812/Bilibili-Evolved#773]
关于哪一项功能
出现bug，关闭插件正常，打开插件又异常

问题描述
所有视频的评论区消失，相关视频预览图消失

脚本版本
正式版1.10.31

浏览器版本
最新版chrome

错误信息
看不太懂
![image](https://user-images.githubusercontent.com/48584237/88882959-9dd91180-d265-11ea-80ee-bf9cffc6001a.png)

附加截图
![image](https://user-images.githubusercontent.com/48584237/88882920-8568f700-d265-11ea-8263-e82bb8e70b6e.png)

**Comment by the1812** [comment]
见 #770
