### ISSUE TITLE
视频评论区及相关推荐不显示

### ISSUE THREAD

**Issue by solitary-sails** [the1812/Bilibili-Evolved#776]
开启脚本后出现评论区加载不出来的情况，并且相关推荐的视频封面加载不出来，视频播放等其他功能未发现异常。关闭脚本后评论其即可正常显示。
![Annotation 2020-07-30 132240](https://user-images.githubusercontent.com/52939914/88884063-5bfd9a80-d268-11ea-8606-b9bd08503a88.jpg)

**Comment by the1812** [comment]
#770
