### ISSUE TITLE
b站H5播放器改版后失效

### ISSUE THREAD

**Issue by qipaguan** [the1812/Bilibili-Evolved#777]
**关于哪一项功能**
全部

**问题描述**
一开始不能点赞，重新安装后功能全部失效

**脚本版本**
任何版本

**浏览器版本**
Microsoft Edge新版（Chromium内核）

**错误信息**
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:2 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/jquery@3.4.0/dist/jquery.min.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:2
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:4 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:4
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:6 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/jszip@3.1.5/dist/jszip.min.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:6
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:8 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:8
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:10 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:10
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1 ERROR: Execution of script 'Bilibili Evolved' failed! Vue is not defined
eval @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1 ReferenceError: Vue is not defined
    at Window.tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:55)
    at <anonymous>:3:90
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:3611)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:3613)
    at eval (<anonymous>)
    at <anonymous>:3:90
    at Object.c [as F_c] (<anonymous>:2:142)
    at Object.E_u (<anonymous>:3:259)
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:2 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/jquery@3.4.0/dist/jquery.min.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:2
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:4 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:4
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:6 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/jszip@3.1.5/dist/jszip.min.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:6
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:8 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:8
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:10 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:10
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1 ERROR: Execution of script 'Bilibili Evolved' failed! Vue is not defined
eval @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1 ReferenceError: Vue is not defined
    at Window.tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:55)
    at <anonymous>:3:90
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:3611)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:3613)
    at eval (<anonymous>)
    at <anonymous>:3:90
    at Object.c [as F_c] (<anonymous>:2:142)
    at Object.E_u (<anonymous>:3:259)
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:2 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/jquery@3.4.0/dist/jquery.min.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:2
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:4 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:4
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:6 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/jszip@3.1.5/dist/jszip.min.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:6
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:8 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:8
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:10 Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.js
tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:10
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1 ERROR: Execution of script 'Bilibili Evolved' failed! Vue is not defined
eval @ chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1
chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1 ReferenceError: Vue is not defined
    at Window.tms_57c3c66c_3169_47a0_b2fa_80ebf14e1fec (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:55)
    at <anonymous>:3:90
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:1)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:3611)
    at eval (chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/userscript.html?name=Bilibili%2520Evolved.user.js&id=57c3c66c-3169-47a0-b2fa-80ebf14e1fec:3613)
    at eval (<anonymous>)
    at <anonymous>:3:90
    at Object.c [as F_c] (<anonymous>:2:142)
    at Object.E_u (<anonymous>:3:259)
DevTools 无法加载 SourceMap： 无法加载 https://s1.hdslb.com/bfs/static/jinkela/international-home/css/international-home.0.5df53f298fcc518c459e41a4b5d1548a569a78ec.css.map: 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载 SourceMap： 无法加载 https://s1.hdslb.com/bfs/static/jinkela/international-home/css/international-home.1.5df53f298fcc518c459e41a4b5d1548a569a78ec.css.map: 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载 SourceMap： 无法加载 https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/vue.min.js.map: 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载 SourceMap： 无法加载 https://s1.hdslb.com/bfs/static/jinkela/international-home/1.international-home.5df53f298fcc518c459e41a4b5d1548a569a78ec.js.map: 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载 SourceMap： 无法加载 https://s1.hdslb.com/bfs/static/jinkela/international-home/international-home.5df53f298fcc518c459e41a4b5d1548a569a78ec.js.map: 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载 SourceMap： 无法加载 https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map: 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

**附加截图**
![批注 2020-07-30 133639](https://user-images.githubusercontent.com/64240783/88884696-bc410c00-d269-11ea-91ad-851c203f719d.png)

**Comment by the1812** [comment]
#770
