### ISSUE TITLE
页面加载不正常

### ISSUE THREAD

**Issue by NightSharp** [the1812/Bilibili-Evolved#778]
视频页面加载不正常
开启后视频投稿的分P和评论区均无法正常加载

1.10.31

Firefox 79.0 x64

界面对比
![显示正常_2020-07-30T05-36-54 342Z](https://user-images.githubusercontent.com/9748063/88884731-cd8a1880-d269-11ea-9e0d-032ba38a3891.png)
![显示异常_2020-07-30T05-35-53 161Z](https://user-images.githubusercontent.com/9748063/88884753-d549bd00-d269-11ea-9ff6-50a5d596204c.png)

**Comment by the1812** [comment]
#770
