### ISSUE TITLE
能修改下新版播放器网页全屏下弹幕框的自适应样式么

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#78]
新版播放器我就不喜欢这点
我习惯开两窗口边看视频边做其他的,但是新版播放器网页全屏下, 如果宽度不够,弹幕框直接隐藏了,明明空间还足够的
![1](https://user-images.githubusercontent.com/14146754/53755242-01380600-3ef1-11e9-8323-81a657a92358.png)

需要把浏览器窗口拉很宽才能显示弹幕框,但是拉太宽的话留给其他工作窗口的空间又太小了
![2](https://user-images.githubusercontent.com/14146754/53755310-2cbaf080-3ef1-11e9-9051-ebb41e15b89e.png)

**Comment by RainEffect** [comment]
你是希望在窄屏状态下可以同时显示底栏的发弹幕框对吗？

**Comment by u2shana** [comment]
> 你是希望在窄屏状态下可以同时显示底栏的发弹幕框对吗？

对啊

**Comment by RainEffect** [comment]
这个是新版播放器方面相关的问题，我测试了一下，在浏览器网页长度低于1200px的时候，会自动隐藏播放器底栏，因为要节省空间之余给用户带来更好的视频体验，嘛。。。
解决方法也很简单，仅仅是将css下在指定宽度下的样式文本无效化而已

我建议可以加入该功能至“设置”->"视频"->"变动宽度下不阉割功能块(开关)"

**Comment by u2shana** [comment]
> 这个是新版播放器方面相关的问题，我测试了一下，在浏览器网页长度低于1200px的时候，会自动隐藏播放器底栏，因为要节省空间之余给用户带来更好的视频体验，嘛。。。
> 解决方法也很简单，仅仅是将css下在指定宽度下的样式文本无效化而已
> 
> 我建议可以加入该功能至“设置”->"视频"->"变动宽度下不阉割功能块(开关)"

B站设置的1200px太过于保守了,而且弹幕框设置居中而不是动态调整也是也是问题原因之一

**Comment by RainEffect** [comment]
的确过于保守了，本身播放器底部空间足够的情况下也不至于需要这样

**Comment by the1812** [comment]
因为就一行CSS, 我直接整合到`样式调整`里了.
