### ISSUE TITLE
评论、up主头像、相关推荐的封面和视频选集的内容不显示

### ISSUE THREAD

**Issue by Louis-Hanse** [the1812/Bilibili-Evolved#781]
**问题描述**
评论、up主头像、相关推荐的封面和视频选集的内容在插件开启的状态下不显示，但是手动关闭插件后可以看到，不知道是设置问题还是bug；视频选集没有字但是仍然可以选择并跳转。
PS:不知道为啥但是用收藏夹的全部播放功能没有这问题。
 **浏览器**
基于Chromium的Edge，版本 84.0.522.49 (官方内部版本) (64 位)
**插件版本**
1.10.31
**截图**
![image](https://user-images.githubusercontent.com/50316612/88903438-4b5c1d00-d286-11ea-9e6d-1afc39ee9ee9.png)
![image](https://user-images.githubusercontent.com/50316612/88903564-7f374280-d286-11ea-9613-59f007103d85.png)

**Comment by the1812** [comment]
#770
