### ISSUE TITLE
视频下载时分段未自动合并

### ISSUE THREAD

**Issue by xuewei1215** [the1812/Bilibili-Evolved#782]
20200730下午以后下载的视频分段不会自动合并，下载为一个压缩包，如图
![image](https://user-images.githubusercontent.com/61929007/88906171-b22f0580-d289-11ea-97e4-ff5591c05bde.png)
请教一下这是什么原因（操作和设置和以前是保持一致的，所以不知道是否是我的设置问题）

**Comment by the1812** [comment]
老视频会有分段的
我从来没有什么合并功能

**Comment by xuewei1215** [comment]
感谢感谢，不好意思给您添麻烦了
