### ISSUE TITLE
今天突然出现的评论区无法显示

### ISSUE THREAD

**Issue by naive12138** [the1812/Bilibili-Evolved#784]
通过诸葛筛查发现，关闭这个脚本评论区就可以加载出来，启用就无法加载评论区，今天突然出现的这个问题。
不论是什么视频都是这个问题。今天突然出现的
版本正式版1.10.31

**浏览器版本**
84.0.4147.89

*附加截图**
![批注 2020-07-30 184819](https://user-images.githubusercontent.com/56205740/88914489-46529a00-d295-11ea-919d-d40a76c3da8f.jpg)

**Comment by the1812** [comment]
#770
