### ISSUE TITLE
首页简化模式下分区切换错误，提示错误Cannot read property 'map' of nul

### ISSUE THREAD

**Issue by 1654894194191** [the1812/Bilibili-Evolved#786]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by the1812** [comment]
从哪个区切到哪个区?

**Comment by 1654894194191** [comment]
> 从哪个区切到那里区？
有几个分区是正常的，有几个都是动画区的界面，然后就会弹出错误

**Comment by Xiaohan5349** [comment]
同样的问题，左半边还好，右半边的排行榜很多次都会读取不出来
![screenshot](https://user-images.githubusercontent.com/49458293/88998141-5e3f1380-d2bf-11ea-8c2a-3d7cb59ea800.jpg)

**Comment by Xiaohan5349** [comment]
不限于哪个区，基本每个区都有切换失败的概率，偶尔会成功，最新的v1.10.33和v1.10.31都有这个问题

**Comment by the1812** [comment]
我试了下只有切到资讯区会这样
