### ISSUE TITLE
脚本导致视频页面无法加载评论区与页面中所有图片

### ISSUE THREAD

**Issue by EdwardXiaoran** [the1812/Bilibili-Evolved#787]
**关于哪一项功能**
未知哪一项功能导致，已尝试关闭脚本，确认关闭后页面加载恢复正常

**问题描述**
脚本导致视频页面无法加载评论区与所有图片

**脚本版本**
Bilibili Evolved (Offline) 724.22

**浏览器版本**
chrome 84.0.4147.105

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/50768586/88916515-c9292400-d298-11ea-8981-bacd96bc170a.png)

**Comment by Jolkssn** [comment]
+1

**Comment by the1812** [comment]
别再开了 跟 #770 是一样的

**Comment by Geeyun-JY3** [comment]
@the1812 干脆复制这条评论链接吧：https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666189125
