### ISSUE TITLE
影片分P名不顯示

### ISSUE THREAD

**Issue by YheonYeung** [the1812/Bilibili-Evolved#788]
**关于哪一项功能**

**问题描述**

https://www.bilibili.com/video/BV1AK411n7ji

**脚本版本**

1.10.31

**浏览器版本**

Cent Browser
版本 4.2.10.171 (正式版本) (64 位元) (Chromium 80.0.3987.163)

**错误信息**

已停用Tampermonkey外其他擴充及腳本，開關腳本及重開網頁，確認問題源自此腳本，昨日都沒有這個問題。

**附加截图**
![image](https://user-images.githubusercontent.com/63342274/88919388-97668c00-d29d-11ea-8dd1-91e4d4fc637a.png)

**Comment by Edger** [comment]
我也遇到这个问题

**Comment by Geeyun-JY3** [comment]
看看置顶的 issue 吧……：https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666189125
