### ISSUE TITLE
bilibili更新后互动出现问题

### ISSUE THREAD

**Issue by Smalmo** [the1812/Bilibili-Evolved#789]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by Smalmo** [comment]
进行投币点赞的时候要验证登录信息，但是验证不了，还有就是评论区加载不出来，侧边的相关视频没有封面

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666189125
