### ISSUE TITLE
旧版动态页面支持

### ISSUE THREAD

**Issue by RainEffect** [the1812/Bilibili-Evolved#79]
地址: **"https://www.bilibili.com/account/dynamic"**

当然，这里的支持指的是多方面支持，例如：
· 将右上角的动态按钮的原跳转改为旧版动态页面。
· 在新旧版动态的某个地方添加切换按钮。
· 旧版动态顶栏显示错误的修复。
· 等。。。

**Comment by the1812** [comment]
那个顶栏是b站弃用的旧版顶栏(好像就是随着新版动态的推出弃用的), 因为改动旧顶栏还可能会影响新版顶栏, 我也就放弃那个顶栏了.
旧版动态功能上应该跟[新版动态选择投稿视频类别](https://t.bilibili.com/?tab=8)一样的, 我觉得也没什么必要跳转到旧版动态吧.

**Comment by RainEffect** [comment]
但是大部分老用户相对会更倾向于旧版动态吧，例如我和我身边的一些UP主们。
因为新版的动态页面看起来太过于多样化了，反而不习惯，更宁愿旧版那种纯粹的视频内容和简介。

(虽然说新版的“投稿视频”分栏其实和这个相同...但看起来的感觉完全不同)

**Comment by the1812** [comment]
好吧, 不过这个可能会比较迟弄出来.

**Comment by RainEffect** [comment]
![image](https://user-images.githubusercontent.com/14258727/55372741-62c1b380-5535-11e9-8732-b6abb4222cc0.png)
摸了下预览版，看到顶栏的一瞬间，心塞

**Comment by the1812** [comment]
调成遇到此顶栏不做改动了.
顶栏我计划重做一个盖在上面, 不然好多涉及顶栏的功能一有改动就要在b站这好几种顶栏来回调整(还不一定调得好). 不过要做多久就很难说了🕊

**Comment by RainEffect** [comment]
配合 #100 顶栏自定义的问题去做上感觉ok，调用B站本身的css去做其实不难。
当然，如果真的要这样做，还得注意 #92 的API问题不能出现。。。
只是注意下，部分页面的顶栏不同，例如主页(www.bilibili.com)和直播页(live.bilibili.com)
加油吧，我会一直支持着的，如果有需要也可以联系我给你一定协助(虽然我的个人能力可能不是很强，但对目前出现的一些BUG的处理能力还是可以的)

**Comment by the1812** [comment]
主页和直播页是完全不同的css, 倒还好. (重做顶栏也不打算覆盖直播区的) 主要是首页, 空间, 动态, 视频, 番剧这些地方, css大部分相同又有小部分不同, 经常做好了这边那边又崩了... 所以才有了这个想法, 也方便加一些自定义的东西

**Comment by RainEffect** [comment]
![image](https://user-images.githubusercontent.com/14258727/56464379-6355b780-641a-11e9-97ef-c1b69ad5d7e1.png)
字体颜色(溜了)。

**Comment by the1812** [comment]
可以通过隐藏功能开启自定义顶栏了(最好是预览通道的), 完成度大概80%.

**Comment by RainEffect** [comment]
![image](https://user-images.githubusercontent.com/14258727/58749223-db051080-84b5-11e9-9b15-79d0a8ee4350.png)
突然想起来好像。。。差点忘了这块。。。近期工作太忙。。。

**Comment by the1812** [comment]
你没开自定义顶栏?
![image](https://user-images.githubusercontent.com/26504152/58749254-5961b280-84b6-11e9-941f-094952970dcb.png)
