### ISSUE TITLE
7.30出现评论区和相关推荐-封面和UP主头像无法显示

### ISSUE THREAD

**Issue by pokliuy** [the1812/Bilibili-Evolved#790]
**关于哪一项功能**

**问题描述**
7.30，在视频播放页面会出现评论区和相关推荐-封面和UP主头像无法显示

**脚本版本**
正式版1.10.31

**浏览器版本**
Chrome和Chromium的Edge 84均

**错误信息**
没有错误报告哦
![image](https://user-images.githubusercontent.com/43649460/88922350-91bf7500-d2a2-11ea-93e4-99d7110afc50.png)

**附加截图**
![image](https://user-images.githubusercontent.com/43649460/88922414-ab60bc80-d2a2-11ea-9acc-9a05fb823ad9.png)
![image](https://user-images.githubusercontent.com/43649460/88922426-af8cda00-d2a2-11ea-962f-76590ef13454.png)

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666189125
