### ISSUE TITLE
点开任意视频，up头像，右下相关视频，评论区都加载不出来

### ISSUE THREAD

**Issue by Kulahala** [the1812/Bilibili-Evolved#791]
![Snipaste_2020-07-30_20-57-23](https://user-images.githubusercontent.com/54696830/88925608-51162a80-d2a7-11ea-9ee4-10949ffa4b61.png)
![Snipaste_2020-07-30_20-57-31](https://user-images.githubusercontent.com/54696830/88925614-53788480-d2a7-11ea-9ded-6cd7eebe0a73.png)

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666189125
