### ISSUE TITLE
开启外置稍后再看后会导致评论区以及推荐出错

### ISSUE THREAD

**Issue by Billons007** [the1812/Bilibili-Evolved#793]
完全无法显示，空白。以及推荐的视频预览图无法显示
问题截图在附件
![QQ截图20200731025013](https://user-images.githubusercontent.com/67461674/88956714-b9c9cb00-d2d8-11ea-8517-5f1794df65b2.png)
![QQ截图20200731025116](https://user-images.githubusercontent.com/67461674/88956732-bdf5e880-d2d8-11ea-81e1-56d63a97fe01.png)

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666421764
