### ISSUE TITLE
很多页面评论区和右边推荐视频封面一起没力

### ISSUE THREAD

**Issue by QGCmaster** [the1812/Bilibili-Evolved#794]
**关于哪一项功能**

**问题描述**

https://www.bilibili.com/video/BV1aV411z77x
很多页面评论区和右边推荐视频封面一起没力

**脚本版本**

Stable 1.10.31

**浏览器版本**

Microsoft Edge
版本 84.0.522.48 (官方内部版本) (64 位)
此浏览器基于 Chromium 开源项目及其他 开源软件。

**错误信息**

> main.js:364 购物党隐私说明（键入disable_gwd_privacy()不再显示本声明）：
> main.js:365     我们不会收集用户个人隐私信息，只会收集一些简单的产品交互行为，帮助改善产品，例如记录某个模块点击次数，更多信息请关注：
> main.js:366 隐私协议: https://www.gwdang.com/static_page/privacy_policy.html
> Bilibili Evolved.user.js:16038 scheduled bundle update
> Bilibili Evolved.user.js:16040 downloading bundle
> s1.hdslb.com/bfs/static/jinkela/video/manifest.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.json:1 Manifest: property 'start_url' ignored, should be same origin as document.
> Bilibili Evolved.user.js:16153 zip version = 1.10.31
> Bilibili Evolved.user.js:16178 bundle updated
> BV1aV411z77x:1 A cookie associated with a cross-site resource at http://apm-misaka.biliapi.net/ was set without the `SameSite` attribute. A future release of Microsoft Edge will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
> stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:1                      //         \\         //          \\       //    ##DDDDDDDDDDDDDDDDDDDDDD##    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|    ## MMMMMMMMMMMMMMMMMMMM ##    ##MMMMMMMMMMMMMMMMMMMMMM##                             Release 2.6.1. Powered by jinkela-core 2.8.3.         \/            \/
> stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7 

> Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
>     at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:40898)
>     at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:57231)
>     at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:56494
>     at f (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:56726)
>     at h (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:57317)
>     at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:60655)
>     at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:60590)
>     at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:60590)
>     at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:61055)
>     at a._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:34369)
> Bilibili Evolved.user.js:16570 

> Skipped <iframe> loading for https://message.bilibili.com/pages/nav/index_new_pc_sync**

> jsc-player.a891f2c5.js:266 [Websocket]: On Open.
> DevTools 无法加载 SourceMap： 无法加载 https://s1.hdslb.com/bfs/seed/jinkela/header-v2/header.js.map: 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

**附加截图**

**Comment by lyuinc** [comment]
遇到同样的问题了，右侧推荐视频封面不能显示。

**Comment by Geeyun-JY3** [comment]
发新版修复了：https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.10.33，而且开 issue 前建议先看看置顶 issue：https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666189125
