### ISSUE TITLE
自动定位出bug

### ISSUE THREAD

**Issue by sadkmoon** [the1812/Bilibili-Evolved#795]
进页面之后第一时间会定位到自己定的偏移量，然后又弹上去了，就像这样
![image](https://user-images.githubusercontent.com/53417811/88969720-d15a8100-d2e3-11ea-8fe8-c83ffb14a81d.png)

**Comment by the1812** [comment]
见 #483 
这个功能不保证稳定定位

**Comment by sadkmoon** [comment]
这个问题是因为先后顺序问题,默认播放器模式为宽屏时,若宽屏先运行,则会定位到准确位置,但是先定位的话 就会出现上面情况
