### ISSUE TITLE
无法正常显示右侧分P列表

### ISSUE THREAD

**Issue by BSDxxxx** [the1812/Bilibili-Evolved#796]
**关于哪一项功能**
无法正常显示右侧分P列表

**问题描述**
测试视频地址：https://www.bilibili.com/video/BV1b7411N798?p=49

**脚本版本**
正式版1.10.31

**浏览器版本**
Chrome 版本 84.0.4147.89（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/59258592/88988469-966c4380-d30b-11ea-82d1-88d2416c2f70.png)

**Comment by Geeyun-JY3** [comment]
发新版修复了：https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.10.33，而且开 issue 前建议先看看置顶 issue：https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666189125
