### ISSUE TITLE
显示失效视频信息已经无法使用

### ISSUE THREAD

**Issue by the1812** [the1812/Bilibili-Evolved#80]
官方突然清理了留在失效视频旁的原信息, 现在暂时没有办法直接获取失效视频信息了.
该功能将在下个版本隐藏.

**Comment by RainEffect** [comment]
![image](https://user-images.githubusercontent.com/14258727/53908774-1183e880-408b-11e9-9e1c-6f823a7dac92.png)
失效视频在收藏夹里倒是还能显示。。。啊~(可恶的B站，可恶的资本主义)

**Comment by ZCXLLOD** [comment]
这个情况我昨天发现的，网页端和客户端的收藏夹里都没有了，找了很久才找到一个可以显示视频标题的B站api：https://api.bilibili.com/x/player/pagelist?aid=视频av号。

**Comment by the1812** [comment]
感谢提醒, 不过这个API是取分P标题的, 视频标题除非那个视频只有1P才能取到. (封面是彻底凉了)
我可以把这个API做进去, 然后`显示失效视频信息`就改成隐藏功能好了, 怎么开隐藏功能到时候会说的.

**Comment by ZCXLLOD** [comment]
。。。今天发现稍后再看里还能显示已失效的视频的封面和标题，不知道有没有方法能把已失效的视频添加到稍后再看里～
![360截图20190309102103197](https://user-images.githubusercontent.com/19368077/54064994-4e034000-4255-11e9-8411-cc0ede85619c.jpg)

**Comment by the1812** [comment]
可以的, 稍后再看那个按钮可以重新调出来的, 加进去确实可以看到信息了.

**Comment by the1812** [comment]
在`1.7.14`版后, 此功能将作为隐藏功能, 原先就开启的用户依然有效, 不需要进一步操作.

**开启/关闭方法:**
在浏览器控制台/Console(`F12`或`Ctrl+Shift+I`召唤)中运行:
```JavaScript
// 最后那里填true是开启, false是关闭
bilibiliEvolved.monkeyApis.setValue("showDeadVideoTitle", true);
```

**功能变化**
个人空间中封面已经无法恢复, 标题只能取第一P的标题(可能跟视频标题对不上). 如果实在需要查看原来的信息, 需要先把失效视频添加到稍后再看, 再去稍后再看列表里就能看到封面和标题.

另外, 如果我之后能成功通过稍后再看反过来恢复个人空间里的信息, 这个功能会再次公开.
