### ISSUE TITLE
无法显示视频评论区

### ISSUE THREAD

**Issue by JedSunCN** [the1812/Bilibili-Evolved#800]
**关于哪一项功能**
应该是视频菜单

**问题描述**
无法显示视频的评论区，关闭脚本后正常

**脚本版本**
1.10.31 Stable

**浏览器版本**
Edge 84

**错误信息**

脚本配置：
`{"useDarkStyle":false,"hideBanner":false,"expandDanmakuList":false,"expandDescription":true,"watchLaterRedirect":true,"touchNavBar":false,"touchVideoPlayer":false,"customControlBackgroundOpacity":0.64,"customControlBackground":false,"darkScheduleStart":"18:00","darkScheduleEnd":"6:00","darkSchedule":false,"toast":true,"fullTweetsTitle":true,"fullPageTitle":false,"removeVideoTopMask":false,"removeLiveWatermark":true,"harunaScale":true,"removeAds":false,"showBlockedAdsTip":true,"hideTopSearch":false,"touchVideoPlayerDoubleTapControl":false,"customStyleColor":"#00A0D8","preserveRank":true,"blurBackgroundOpacity":0.382,"useDefaultPlayerMode":true,"applyPlayerModeOnPlay":false,"defaultPlayerMode":"宽屏","useDefaultVideoQuality":false,"defaultVideoQuality":"1080P60","useDefaultDanmakuSettings":false,"enableDanmaku":true,"rememberDanmakuSettings":false,"danmakuSettings":{"subtitlesPreserve":false,"smartMask":false},"defaultPlayerLayout":"新版","defaultBangumiLayout":"新版","skipChargeList":true,"comboLike":false,"autoLightOff":false,"useCache":true,"autoContinue":false,"allowJumpContinue":false,"deadVideoTitleProvider":"稍后再看","useBiliplusRedirect":false,"biliplusRedirect":true,"framePlayback":true,"useCommentStyle":true,"imageResolution":true,"imageResolutionScale":"auto","toastInternalError":false,"i18n":false,"i18nLanguage":"日本語","playerFocus":false,"playerFocusOffset":-10,"simplifyLiveroom":true,"simplifyLiveroomSettings":{"vip":true,"fansMedal":true,"title":true,"userLevel":true,"guard":true,"systemMessage":true,"welcomeMessage":true,"giftMessage":true,"guardPurchase":true,"giftPanel":true,"kanban":true,"userEffect":true,"eventsBanner":false,"rankList":false,"popup":false,"skin":false},"customNavbar":false,"customNavbarFill":false,"customNavbarTransparent":true,"customNavbarShadow":true,"customNavbarBlur":false,"customNavbarBlurOpacity":0.7,"customNavbarOrder":{"blank1":0,"logo":1,"category":2,"rankingLink":3,"drawingLink":4,"musicLink":5,"gamesIframe":6,"livesIframe":7,"shopLink":8,"mangaLink":9,"blank2":10,"search":11,"blank3":12,"userInfo":13,"messages":14,"activities":15,"bangumi":16,"watchlaterList":17,"favoritesList":18,"historyList":19,"upload":20,"darkMode":21},"customNavbarHidden":["blank1","drawingLink","musicLink","gamesIframe"],"customNavbarBoundsPadding":10,"customNavbarGlobalFixed":false,"playerShadow":false,"narrowDanmaku":true,"outerWatchlater":true,"videoScreenshot":true,"hideBangumiReviews":false,"filenameFormat":"[title][ - ep]","batchFilenameFormat":"[n - ][ep]","sideBarOffset":0,"noLiveAutoplay":true,"hideHomeLive":true,"noMiniVideoAutoplay":false,"useDefaultVideoSpeed":false,"defaultVideoSpeed":"1.0","hideCategory":false,"foldComment":true,"downloadVideoDefaultDanmaku":"无","downloadVideoDefaultSubtitle":"无","aria2RpcOption":{"secretKey":"","dir":"","host":"127.0.0.1","port":"6800","method":"get","skipByDefault":false,"maxDownloadLimit":"","baseDir":""},"aria2RpcOptionSelectedProfile":"","aria2RpcOptionProfiles":[{"name":"未命名","secretKey":"","dir":"","host":"127.0.0.1","port":"6800","method":"get","skipByDefault":false,"maxDownloadLimit":"","baseDir":""}],"searchHistory":[{"count":1,"keyword":"荒野的寿飞行队","date":"2020-04-05T10:25:23.214Z"},{"count":1,"keyword":"斩服少女","date":"2020-04-03T15:30:08.909Z"},{"count":1,"keyword":"pop team epic","date":"2020-04-03T15:19:31.854Z"},{"count":1,"keyword":"BNA","date":"2020-04-03T10:09:41.768Z"},{"count":1,"keyword":"龙的牙医","date":"2020-04-03T09:57:59.975Z"},{"count":1,"keyword":"bna","date":"2020-04-01T15:44:37.284Z"},{"count":1,"keyword":"结城友奈是勇者","date":"2020-04-01T14:43:11.396Z"},{"count":1,"keyword":"中正评测","date":"2020-03-29T09:12:56.952Z"}],"seedsToCoins":true,"autoSeedsToCoins":true,"lastSeedsToCoinsDate":0,"autoDraw":true,"keymap":true,"doubleClickFullscreen":false,"doubleClickFullscreenPreventSingleClick":false,"simplifyHome":false,"simplifyHomeStyle":"清爽","minimalHomeSettings":{"showSearch":true,"backgroundImage":""},"ajaxHook":false,"scriptLoadingMode":"延后(自动)","scriptDownloadMode":"bundle","guiSettingsDockSide":"左侧","fullActivityContent":true,"feedsFilter":false,"feedsFilterPatterns":[],"feedsFilterTypes":[],"feedsSpecialFilterTypes":[],"feedsFilterSideCards":[],"activityImageSaver":true,"scriptBlockPatterns":[],"customNavbarSeasonLogo":false,"selectableColumnText":true,"downloadVideoFormat":"flv","downloadVideoDashCodec":"AVC/H.264","watchlaterExpireWarningDays":14,"superchatTranslate":false,"miniPlayerTouchMove":false,"hideBangumiSponsors":true,"hideRecommendLive":true,"hideRelatedVideos":true,"defaultMedalID":0,"autoMatchMedal":false,"customStyles":[],"simpleHomeCategoryOrders":{"anime":0,"bangumi":1,"china":2,"manga":3,"music":4,"dance":5,"game":6,"tech":7,"digital":8,"life":9,"kichiku":10,"fashion":11,"information":12,"entertainment":13,"column":14,"movie":15,"tv":16,"film":17,"documentary":18,"ads":12},"simpleHomeBangumiLayout":"时间表","keymapJumpSeconds":85,"urlParamsClean":true,"collapseLiveSideBar":true,"removeGameMatchModule":true,"noDarkOnMember":true,"feedsTranslate":false,"feedsTranslateProvider":"Bing","feedsTranslateLanguage":"","downloadVideoQuality":120,"defaultLiveQuality":"原画","useDefaultLiveQuality":true,"recordLiveDanmaku":false,"foregroundColorMode":"自动","preserveEventBanner":true,"about":true,"bvidConvert":true,"fixedSidebars":false,"updateCdn":"jsDelivr","lastNewVersionCheck":1596160354604,"newVersionCheckInterval":21600000,"useDarkStyleAsUserStyle":false,"darkColorScheme":false,"autoHideSideBar":false,"livePip":true,"extendFeedsLive":true,"userImages":[],"playerOnTop":false,"restoreFloors":false,"quickFavorite":false,"quickFavoriteID":0,"bilibiliSimpleNewHomeCompatible":false,"preferAvUrl":false,"disableFeedsDetails":true,"elegantScrollbar":true,"danmakuSendBar":false,"watchLaterRedirectNavbar":true,"watchLaterRedirectPage":true,"showCoverBeforePlay":false,"volumeOverdrive":false,"autoPlay":false,"favoritesRedirect":false,"compactLayout":false,"hideOldEntry":false,"guiSettings":true,"viewCover":true,"notifyNewVersion":true,"clearCache":true,"downloadVideo":true,"enableDashDownload":true,"downloadDanmaku":true,"downloadSubtitle":true,"downloadAudio":true,"downloadLiveRecords":true,"medalHelper":true,"playerLayout":false,"forceWide":false,"useNewStyle":false,"overrideNavBar":false,"touchVideoPlayerAnimation":false,"allNavbarFill":false,"showDeadVideoTitle":false,"blurVideoControl":false,"oldTweets":false,"customNavbarCompact":false,"watchlaterExpireWarnings":false,"latestVersionLink":"https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@master/bilibili-evolved.user.js","currentVersion":"1.10.31","foreground":"#fff","blueImageFilter":"hue-rotate(1deg) saturate(100%)","pinkImageFilter":"hue-rotate(-147deg) saturate(145%)","brightness":"0%","filterInvert":"invert(1)"}`

**附加截图**
![image](https://user-images.githubusercontent.com/41063651/88993187-cf121a00-d317-11ea-8e40-fd4e2ebf3093.png)

请作者留意，谢谢。

**Comment by the1812** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666421764
