### ISSUE TITLE
所有视频均无法显示评论和右侧推荐视频的封面

### ISSUE THREAD

**Issue by rick-yao** [the1812/Bilibili-Evolved#804]
**关于哪一项功能**

**问题描述**
所有视频均无法显示评论和右侧推荐视频的封面

**脚本版本**
1.10.31

**浏览器版本**
Google Chrome 已是最新版本
版本 84.0.4147.105（正式版本） （64 位）

**错误信息**
chrome-extension://kpbnombpnpcffllnianjibmpadjolanh/vendors.bundle.js:2530  ____ _____ _      _____ ____ _____ _      _____ _    _ ______ _      _____  ______ _____|  _ |_   _| |    |_   _|  _ |_   _| |    |_   _| |  | |  ____| |    |  __ \|  ____|  __ \| |_) || | | |      | | | |_) || | | |      | | | |__| | |__  | |    | |__) | |__  | |__) ||  _ < | | | |      | | |  _ < | | | |      | | |  __  |  __| | |    |  ___/|  __| |  _  /| |_) _| |_| |____ _| |_| |_) _| |_| |____ _| |_| |  | | |____| |____| |    | |____| | \ \|____|_____|______|_____|____|_____|______|_____|_|  |_|______|______|_|    |______|_|  \_\-... .. .-.. .. -... .. .-.. ..    .... . .-.. .--. . .-.   version: 1.2.21 from: video
chrome-extension://kpbnombpnpcffllnianjibmpadjolanh/vendors.bundle.js:2530  ____ _____ _      _____ ____ _____ _      _____ _    _ ______ _      _____  ______ _____|  _ |_   _| |    |_   _|  _ |_   _| |    |_   _| |  | |  ____| |    |  __ \|  ____|  __ \| |_) || | | |      | | | |_) || | | |      | | | |__| | |__  | |    | |__) | |__  | |__) ||  _ < | | | |      | | |  _ < | | | |      | | |  __  |  __| | |    |  ___/|  __| |  _  /| |_) _| |_| |____ _| |_| |_) _| |_| |____ _| |_| |  | | |____| |____| |    | |____| | \ \|____|_____|______|_____|____|_____|______|_____|_|  |_|______|______|_|    |______|_|  \_\-... .. .-.. .. -... .. .-.. ..    .... . .-.. .--. . .-.   version: 1.2.21 from: vipPrivilege
(unknown) [URL params clean] https://www.bilibili.com/video/BV1LA411Y7mW?spm_id_from=333.851.b_7265706f7274466972737431.14 https://www.bilibili.com/video/BV1LA411Y7mW
chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/userscript.html?name=Bilibili%2520Evolved.user.js&id=a09583a7-8fe0-4aaa-96bd-5b4081167fc4:16039 scheduled bundle update
s1.hdslb.com/bfs/static/jinkela/video/manifest.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.json:1 Manifest: property 'start_url' ignored, should be same origin as document.
chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/userscript.html?name=Bilibili%2520Evolved.user.js&id=a09583a7-8fe0-4aaa-96bd-5b4081167fc4:16041 downloading bundle
BV1LA411Y7mW:1 A cookie associated with a cross-site resource at http://apm-misaka.biliapi.net/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/userscript.html?name=Bilibili%2520Evolved.user.js&id=a09583a7-8fe0-4aaa-96bd-5b4081167fc4:16154 zip version = 1.10.33
chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/userscript.html?name=Bilibili%2520Evolved.user.js&id=a09583a7-8fe0-4aaa-96bd-5b4081167fc4:16161 bundle version not match. current = 1.10.31, latest = 1.10.33
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/seed/jinkela/header-v2/header.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:1                      //         \\         //          \\       //    ##DDDDDDDDDDDDDDDDDDDDDD##    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|    ## MMMMMMMMMMMMMMMMMMMM ##    ##MMMMMMMMMMMMMMMMMMMMMM##                             Release 2.6.1. Powered by jinkela-core 2.8.3.         \/            \/
stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7:40898)
    at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7:57231)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7:56494
    at f (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7:56726)
    at h (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7:57317)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7:60655)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7:60590)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7:60590)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7:61055)
    at a.t._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7:34369)
hn.get @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7
hn @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7
(anonymous) @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7
Tn.$mount @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7
Tn.$mount @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:7
(anonymous) @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:25
ro.onReady @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:25
mo.onReady @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:25
(anonymous) @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:25
n @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:1
(anonymous) @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:18
n @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:1
(anonymous) @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:1
(anonymous) @ stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js:1
jsc-player.1a5dbc83.js:266 [Websocket]: On Open.
userscript.html?name=Bilibili%20Evolved.user.js&id=a09583a7-8fe0-4aaa-96bd-5b4081167fc4:16571 Skipped <iframe> loading for https://message.bilibili.com/pages/nav/index_new_pc_sync

全复制下来了。。

**附加截图**
![image](https://user-images.githubusercontent.com/59443488/89004161-26be7e80-d334-11ea-8d32-28bc19fade5d.png)

**Comment by sensty** [comment]
这个问题解决了吗？

**Comment by the1812** [comment]
> 这个问题解决了吗？

https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666421764

**Comment by Loss-of-time** [comment]
还在下载最新版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 晚上6:37
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 所有视频均无法显示评论和右侧推荐视频的封面 (#804)





  
这个问题解决了吗？
  
#770 (comment)

**Comment by sensty** [comment]
> > 这个问题解决了吗？
> 
> [#770 (comment)](https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666421764)

坐等正式版发布
作者大大辛苦了

**Comment by Geeyun-JY3** [comment]
> 坐等正式版发布

已经发了嘛……
