### ISSUE TITLE
视频下无法显示评论区

### ISSUE THREAD

**Issue by Jazzwind** [the1812/Bilibili-Evolved#806]
**关于哪一项功能**
整个插件导致的问题

**问题描述**

开启脚本后所有视频都无法显示评论区，且点赞投币收藏数量不显示。所有视频都不显示，关掉插件后正常

**脚本版本**

应该是正式版1.10.31？从油猴上看到的是1.10.31，应该是从Greasy Fork安装的
从插件看是stable 1.10.31

**浏览器版本**

Chrome 版本 84.0.4147.105（正式版本） （64 位）

**错误信息**

_### _看不是很懂，抱歉。全部复制粘贴了一个视频F12 Console下的全部内容__

info: mode: default blocked_vip: undefined server: https://www.biliplus.com upos_server: undefined flv_prefer_ws:  remove_pre_ad: undefined enable_in_av: undefined readyState: loading isLogin: true isLoginBiliBili: true
Grammarly.js:2 [DEFAULT]: WARN : Using DEFAULT root logger
t.printToConsole @ Grammarly.js:2
Grammarly.js:2 [WARNING] Using default timeseries implementation.
e.getRootMetric @ Grammarly.js:2
BV1pv411v7nW:1 A cookie associated with a cross-site resource at http://apm-misaka.biliapi.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
userscript.html?name=Bilibili%20Evolved.user.js&id=8a770867-dae3-4c4f-968e-fda128fb31e3:16039 scheduled bundle update
main.js:363 Object
main.js:365 购物党隐私说明（键入disable_gwd_privacy()不再显示本声明）：
main.js:366     我们不会收集用户个人隐私信息，只会收集一些简单的产品交互行为，帮助改善产品，例如记录某个模块点击次数，更多信息请关注：
main.js:367 隐私协议: https://www.gwdang.com/static_page/privacy_policy.html
s1.hdslb.com/bfs/static/jinkela/video/manifest.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.json:1 Manifest: property 'start_url' ignored, should be same origin as document.
userscript.html?name=Bilibili%20Evolved.user.js&id=8a770867-dae3-4c4f-968e-fda128fb31e3:16041 downloading bundle
userscript.html?name=Bilibili%20Evolved.user.js&id=8a770867-dae3-4c4f-968e-fda128fb31e3:16154 zip version = 1.10.33
userscript.html?name=Bilibili%20Evolved.user.js&id=8a770867-dae3-4c4f-968e-fda128fb31e3:16161 bundle version not match. current = 1.10.31, latest = 1.10.33
stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:1                      //         \\         //          \\       //    ##DDDDDDDDDDDDDDDDDDDDDD##    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|    ## MMMMMMMMMMMMMMMMMMMM ##    ##MMMMMMMMMMMMMMMMMMMMMM##                             Release 2.6.1. Powered by jinkela-core 2.8.3.         \/            \/
stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:40898)
    at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:57231)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:56494
    at f (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:56726)
    at h (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:57317)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:60655)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:60590)
    at j (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:60590)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:61055)
    at a._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e9fdf308d9fb6120cc448136f1caae76f60a0fe0.js?__WB_REVISION__=e9fdf308d9fb6120cc448136f1caae76f60a0fe0:7:34369)
jsc-player.1a5dbc83.js:266 [Websocket]: On Open.
userscript.html?name=Bilibili%20Evolved.user.js&id=8a770867-dae3-4c4f-968e-fda128fb31e3:16571 Skipped <iframe> loading for https://message.bilibili.com/pages/nav/index_new_pc_sync
VM794:1 infinite scroll
VM794:1 Array(1)
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/seed/jinkela/header-v2/header.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**附加截图**
[bilibili-evolved-settings.zip](https://github.com/the1812/Bilibili-Evolved/files/5005670/bilibili-evolved-settings.zip)
![截图样例](https://user-images.githubusercontent.com/62089810/89011197-8ae83f00-d342-11ea-893b-c8280ca6d177.png)

**Comment by Coulomb-G** [comment]
开issue前请先搜索关键词,或者看看置顶的issue

**Comment by the1812** [comment]
求求你们看看置顶吧
https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666421764

**Comment by Jazzwind** [comment]
非常抱歉！感谢！辛苦了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 下午3:32
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"没有名字"<876777762@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 视频下无法显示评论区 (#806)





 
Closed #806.
