### ISSUE TITLE
自定义弹幕字体

### ISSUE THREAD

**Issue by the1812** [the1812/Bilibili-Evolved#807]
希望以后新版能加入自定义弹幕字体的功能

_Originally posted by @Cairl in https://github.com/the1812/Bilibili-Evolved/issues/770#issuecomment-666976383_

**Comment by xzk-kokodayo** [comment]
我也希望，这个我之前也想过。我希望还能加入自定义页面背景的功能
https://github.com/wuxinTLH/bilibilibackground
不完善但是已经有人在做了

**Comment by the1812** [comment]
背景加上和页面元素并不算很协调 我不打算做这个

**Comment by the1812** [comment]
弹幕字体可以换掉, 控制台(<kbd>Ctrl + Shift + I</kbd>)里运行
```js
bilibiliEvolved.installStyle({
  name: 'danmakuFont',
  displayName: '更换弹幕字体',
  style: `.b-danmaku { font-family: 'Sarasa UI SC' !important; }`
});
```

`Sarasa UI SC`可以换成你想要的字体

**Comment by wuxinTLH** [comment]
> 我也希望，这个我之前也想过。我希望还能加入自定义页面背景的功能
> https://github.com/wuxinTLH/bilibilibackground
> 不完善但是已经有人在做了

az
