### ISSUE TITLE
下载视频功能里面，点击IDM仅能下载一个.ef2文件

### ISSUE THREAD

**Issue by whisperice** [the1812/Bilibili-Evolved#808]
无法拉起IDM下载，而且尝试用IDM开.ef2文件也没什么反应。是不是我使用姿势不对？

**Comment by CKylinMC** [comment]
IDM 任务>  导入> 从IDM导出文件导入

**Comment by whisperice** [comment]
哈哈，按你说的找到了，感谢。 还真是我的使用姿势问题。

**Comment by CKylinMC** [comment]
或许应该加个提示？

**Comment by the1812** [comment]
行

**Comment by MC-dusk** [comment]
要是能直接从浏览器发送到IDM下载就好了，就像arial2一样

**Comment by Loss-of-time** [comment]
> 要是能直接从浏览器发送到IDM下载就好了，就像arial2一样

+1

**Comment by whisperice** [comment]
> > 要是能直接从浏览器发送到IDM下载就好了，就像arial2一样
> 
> +1

+1 不知道可有实现难度

**Comment by the1812** [comment]
这你得问 IDM
不是我能决定得了的

**Comment by whisperice** [comment]
> 这你得问 IDM
> 不是我能决定得了的

是传过去视频链接IDM不能识别到并下载吗？

**Comment by the1812** [comment]
是传不过去
IDM 没有像 aria2 那样有个 RPC 模式
aria2 RPC 可以直接把链接发过去自动开始下载

**Comment by CKylinMC** [comment]
https://www.52pojie.cn/thread-726458-1-1.html

这个是要从idm那边设置的

**Comment by the1812** [comment]
> 或许应该加个提示？

加到常见问题里了
https://github.com/the1812/Bilibili-Evolved/discussions/1301
