### ISSUE TITLE
修改新的视频加载界面“你感兴趣的视频都在b站”为以前小电视的加载界面，或直接屏蔽

### ISSUE THREAD

**Issue by Decwar** [the1812/Bilibili-Evolved#809]
播放器改版后新的视频加载界面和这行字简直了

**Comment by Coulomb-G** [comment]
这行字也没啥影响，屏蔽也得先加载出来才屏蔽，该看见还是可以看见，我只能建议适应新版，老版的加载界面我们上哪去给你找？

**Comment by CKylinMC** [comment]
https://greasyfork.org/zh-CN/scripts/407958
这个可以满足你的要求吗？

**Comment by Decwar** [comment]
> https://greasyfork.org/zh-CN/scripts/407958
> 这个可以满足你的要求吗？

谢谢 这个就行 那个蒙版去掉就感觉好多了
