### ISSUE TITLE
最新预览版的逐帧播放按钮在旧版播放器下颜色看不见

### ISSUE THREAD

**Issue by u2shana** [the1812/Bilibili-Evolved#81]
新版播放器很正常,旧版播放器就出问题了,同样是白色,与播放器背景同化了
旧版播放器还是要用的,毕竟稍后再看列表播放功能只有旧版才有
![N7@N} OSPCM2$C9$15VSL$D](https://user-images.githubusercontent.com/14146754/54081844-afefa280-4346-11e9-8d23-d972f2f029ba.png)

另外 如果设置番剧为新版播放器的话,左边两个东西无法隐藏
![发撒发生的](https://user-images.githubusercontent.com/14146754/54081965-f514d400-4348-11e9-9507-4a7a2980d236.png)

**Comment by the1812** [comment]
我改成旧版里不显示按钮了, 可以直接用键盘`Shift + 左/右方向键`来调整.
番剧里侧栏没挡住的问题已经修复.

**Comment by u2shana** [comment]
> 我改成旧版里不显示按钮了, 可以直接用键盘`Shift + 左/右方向键`来调整.
> 番剧里侧栏没挡住的问题已经修复.

今天发现,直播区的播放器也有上面的第二个问题

**Comment by the1812** [comment]
已修复

**Comment by u2shana** [comment]
> 已修复

直播区的话网页全屏还没好,全屏好了

**Comment by the1812** [comment]
直播区现在可以了吗\_(:3」∠)\_

**Comment by u2shana** [comment]
> 直播区现在可以了吗_(:3」∠)_

好了,都正常了
