### ISSUE TITLE
在Safari浏览器上和“解除B站区域限制”存在冲突

### ISSUE THREAD

**Issue by qw1363673600** [the1812/Bilibili-Evolved#810]
最近才出现的问题   
在Safari使用evolved时“解除B站区域限制”会随机失效
但是在Chrome中不会出现这个问题   其他浏览器未测试

**Comment by Coulomb-G** [comment]
解除b站区域限制和我们无关,且经常性不稳定，我只能建议你改用「bilibili港澳台」
