### ISSUE TITLE
评论区无法显示用户等级以及一些用户牌子

### ISSUE THREAD

**Issue by xuanzg163** [the1812/Bilibili-Evolved#811]
**评论区无法显示用户等级以及一些用户牌子**

**问题描述**

**脚本版本**

**浏览器版本**
 
![image](https://user-images.githubusercontent.com/28886153/89120844-00dbda00-d4ec-11ea-8b61-3a0a3714c4fc.png)
![Snipaste_2020-08-02_18-17-06](https://user-images.githubusercontent.com/28886153/89120891-662fcb00-d4ec-11ea-9633-17a21cba53ed.jpg)

**Comment by xuanzg163** [comment]
> **评论区无法显示用户等级以及一些用户牌子**
> 
> **问题描述**
> 
> **脚本版本**
> 
> **浏览器版本**
> 
> ![image](https://user-images.githubusercontent.com/28886153/89120844-00dbda00-d4ec-11ea-8b61-3a0a3714c4fc.png)
> ![Snipaste_2020-08-02_18-17-06](https://user-images.githubusercontent.com/28886153/89120891-662fcb00-d4ec-11ea-9633-17a21cba53ed.jpg)

**Comment by Loss-of-time** [comment]
你也看到抖音这糟心了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月2日(星期天) 晚上6:17
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[the1812/Bilibili-Evolved] 评论区无法显示用户等级以及一些用户牌子 (#811)





 
评论区无法显示用户等级以及一些用户牌子
 
问题描述
 
脚本版本
 
浏览器版本
