### ISSUE TITLE
搜索页面顶栏左侧哔哩哔哩logo为纯白色

### ISSUE THREAD

**Issue by KB3146706** [the1812/Bilibili-Evolved#812]
**关于哪一项功能**
搜索页左上角的哔哩哔哩logo颜色

**问题描述**
搜索页面顶栏左侧哔哩哔哩logo为纯白色，在没有自定义顶栏背景颜色时看不见

**脚本版本**
1.10.33

**浏览器版本**
百分浏览器 4.2.10.171 64位 Chromium 80.0.3987.163

**附加截图**
![image](https://user-images.githubusercontent.com/57534077/89176796-c726d400-d5bc-11ea-9e6c-f8ffd9416898.png)
鼠标放上去后
![image](https://user-images.githubusercontent.com/57534077/89176820-d148d280-d5bc-11ea-8fc7-e0a2c72a5658.png)

**Comment by the1812** [comment]
这你自己可以调的
比如关掉季节logo, 然后别把主题颜色设成白色

**Comment by KB3146706** [comment]
> 这你自己可以调的
> 比如关掉季节logo, 然后别把主题颜色设成白色

是这样可以解决，但是关掉季节LOGO并把顶栏背景设为哔哩蓝时logo会自动变浅，我希望在我这种情况时logo也能“自适应”

**Comment by the1812** [comment]
除了季节logo(就是一张图)以外都是自适应的啊

**Comment by the1812** [comment]
<img height="120" src="https://user-images.githubusercontent.com/26504152/89186479-6bfddd00-d5ce-11ea-923f-5e2e40828c20.png">
<img height="100" src="https://user-images.githubusercontent.com/26504152/89186492-71f3be00-d5ce-11ea-8da1-8ebb454c1bd7.png">

**Comment by KB3146706** [comment]
> 除了季节logo(就是一张图)以外都是自适应的啊

行叭，确实是季节logo的问题，B站恰了vivo的饭，logo变成纯白色了😂
