### ISSUE TITLE
问一下，那个下载下来的弹幕怎么放在播放器里面呢？有没有教程呢？

### ISSUE THREAD

**Issue by kenandelu** [the1812/Bilibili-Evolved#816]
**关于哪一项功能**

**期望的效果**

**脚本版本**

**Comment by Coulomb-G** [comment]
在能加载弹幕文件的播放器里选择打开弹幕文件啊

**Comment by kenandelu** [comment]
> 在能加载弹幕文件的播放器里选择打开弹幕文件啊

就是说推荐个能加载弹幕的播放器呗。

**Comment by Coulomb-G** [comment]
BiliLocal,acg播放器,弹弹play等等,我并没有全部都体验一遍哪个好,这类问题还是去知乎提比较好

**Comment by CKylinMC** [comment]
ACG播放器是WIN10商店的，我推荐一个Potplayer，免费好用，不是UWP。

**Comment by kenandelu** [comment]
> ACG播放器是WIN10商店的，我推荐一个Potplayer，免费好用，不是UWP。
> 而且貌似如果视频和ASS文件同名是能自动读取的？

问一下有链接吗，谢谢。

**Comment by kenandelu** [comment]
> BiliLocal,acg播放器,弹弹play等等,我并没有全部都体验一遍哪个好,这类问题还是去知乎提比较好

bilibililocal他的github链接挂了那，有其他链接吗？

**Comment by CKylinMC** [comment]
> > ACG播放器是WIN10商店的，我推荐一个Potplayer，免费好用，不是UWP。
> > 而且貌似如果视频和ASS文件同名是能自动读取的？
> 
> 问一下有链接吗，谢谢。

https://potplayer.org/

**Comment by Geeyun-JY3** [comment]
[弹弹play](http://www.dandanplay.com) 既支持 XML 也支持 ASS，UWP 和 PC 安装版和绿色版都有。

**Comment by the1812** [comment]
PotPlayer: 总体不错 弹幕量大的时候蜜汁占内存
ACG Player: 高性能 但部分弹幕样式不遵循ass文件
弹弹play: 加载时间略长, 其他没啥问题

**Comment by MotooriKashin** [comment]
推荐两个在线的  
[BiliPlus Web Player](https://www.biliplus.com/api/h5play-local.php)：用浏览器在线加载本地视频和弹幕文件也挺方便的  
[Bilibili 修车插件](https://greasyfork.org/scripts/374449)：用B站原生播放器加载本地视频和弹幕文件，打开任意一个B站播放页面就行，不过只支持有旧版播放器的页面

**Comment by kenandelu** [comment]
> 推荐两个在线的
> [BiliPlus Web Player](https://www.biliplus.com/api/h5play-local.php)：用浏览器在线加载本地视频和弹幕文件也挺方便的
> [Bilibili 修车插件](https://greasyfork.org/scripts/374449)：用B站原生播放器加载本地视频和弹幕文件，打开任意一个B站播放页面就行，不过只支持有旧版播放器的页面

这个插件的第二个好像已经不能用了，还是我的使用方法有问题呢？

**Comment by MotooriKashin** [comment]
因为那个脚本没有适配新版播放器，旧版已于去年12月中旬下架了，毕竟作者已经是一两年前的脚本了。如果有办法找回旧版播放器还是能用的。


来自 魅族 16th

-------- 原始邮件 --------
发件人：kenandelu <notifications@github.com>
时间：2020年8月6日 22:04
收件人：the1812/Bilibili-Evolved <Bilibili-Evolved@noreply.github.com>
抄送：MotooriKashin <lianmengkexin@gmail.com>,Comment <comment@noreply.github.com>
主题：Re: [the1812/Bilibili-Evolved] 问一下，那个下载下来的弹幕怎么放在播放器里面呢？有没有教程呢？ (#816)
