### ISSUE TITLE
权限申请代码有重复

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#817]
**关于哪一项功能**
代码，油猴 `@grant`

**问题描述**

**脚本版本**

1.10.33

**浏览器版本**

**错误信息**

一个不算错误的问题，刚刚看到的。
如图，最终正式版脚本的19行~23行与24行~28行权限申请重复，想学习一下脚本时候看到的。

**附加截图**
![image](https://user-images.githubusercontent.com/11648014/89309027-822a9c80-d6a5-11ea-8e62-1fdf81cdfdd8.png)

**Comment by CKylinMC** [comment]
我大概知道为什么了

**Comment by the1812** [comment]
下面那些是以前兼容GM4写的
结果GM4上效果并不理想, 最后又懒得改回去了

**Comment by CKylinMC** [comment]
了解了
