### ISSUE TITLE
关于adblock过滤b站首页横幅

### ISSUE THREAD

**Issue by DBeidachazi** [the1812/Bilibili-Evolved#819]
**关于使用adblock**

**问题描述**
隐藏首页顶部横幅，会在打开b站时先加载横幅
使用adblock过滤规则
bilibili.com##.bili-banner
过滤后，隐藏首页顶部横幅会将页面上一些元素遮盖住

**脚本版本**
正式版1.10.33

**浏览器版本**
Microsoft Edge 是最新版本。
版本 83.0.478.58 (官方内部版本) (64 位)

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/63102882/89426249-8a014400-d76c-11ea-8342-2b6323da1478.png)

**Comment by the1812** [comment]
首页横幅为什么不直接用脚本隐藏呢

**Comment by DBeidachazi** [comment]
因为只用脚本，在打开b站时，会先加载一遍横幅，然后再隐藏，adblock可以直接隐藏

**Comment by the1812** [comment]
那就用 stylus 吧
可以建个样式直接把脚本用的 css 粘贴进去
https://github.com/the1812/Bilibili-Evolved/blob/master/src/style/hide-banner/hide-banner.css

**Comment by DBeidachazi** [comment]
表示很感谢
