### ISSUE TITLE
建议在下载的文件命名格式中，增加**视频上传时间**的可选变量

### ISSUE THREAD

**Issue by ghost** [the1812/Bilibili-Evolved#820]
**关于哪一项功能**

目前视频下载文件命名格式中的时间变量是本地时间，希望能够添加**视频上传时间**的可选变量。

**期望的效果**

使用`[uy] [uM] [ud]`来表示上传日期年、月、日的变量

**脚本版本**

Stable v1.10.33

**Comment by KinoJian** [comment]
能否再添加一个创作者名字的可选变量呢。
