### ISSUE TITLE
为什么有的视频可以看到和发送弹幕，有的不行

### ISSUE THREAD

**Issue by zibuyan** [the1812/Bilibili-Evolved#821]
除了番剧以外的视频都不能发弹幕

**Comment by Coulomb-G** [comment]
你是否开着其他的脚本,或者截图一下控制台报错信息

**Comment by zibuyan** [comment]
解决了，是和其他脚本冲突了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月8日(星期六) 凌晨2:22
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"子不言"<643403973@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 为什么有的视频可以看到和发送弹幕，有的不行 (#821)





 
你是否开着其他的脚本,或者截图一下控制台报错信息
