### ISSUE TITLE
视频显示封面后，开始播放前，鼠标移入移出会闪屏

### ISSUE THREAD

**Issue by CKylinMC** [the1812/Bilibili-Evolved#823]
**关于哪一项功能**
视频显示封面

**问题描述**

在播放器加载好之后，开始播放之前，鼠标移入移出播放器区域会导致播放器闪烁（好像重新加载了封面一样）

(鼠标移入移出时候 ID为`bilibiliPlayer`的元素会动态添加删除一个叫`bilibili-player-no-cursor`的class，不清楚是否有关)

**脚本版本**

正式版1.10.33

**浏览器版本**

Chrome 84

**错误信息**

**附加截图**
[![这是一个GIF录屏](https://fast.ckylin.site/resources/screenrecord2.gif)](https://fast.ckylin.site/resources/screenrecord2.gif)

**Comment by the1812** [comment]
你关掉控制栏那些背景模糊效果试试

**Comment by CKylinMC** [comment]
> 你关掉控制栏那些背景模糊效果试试

不行，依然这样。

[![这是另一个GIF录屏](https://fast.ckylin.site/resources/screenrecord3.gif)](https://fast.ckylin.site/resources/screenrecord3.gif)

**Comment by CKylinMC** [comment]
之前测试只关掉了其他脚本，我早上再试一下关掉其他样式和扩展看看有没有影响的。

**Comment by CKylinMC** [comment]
![image](https://user-images.githubusercontent.com/11648014/108161386-e4209000-7125-11eb-978a-f2a33cc3b2ac.png)

如果有后来的朋友有一样的问题，关掉这一项解决，通用于所有使用chrome并且显示异常的状况。但是注意这个关掉后一部分基于webgl的网页可能会无法使用。

另外，也可以试试更新显示驱动。
