### ISSUE TITLE
本脚本会适配 mylist 页面吗

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#824]
https://github.com/MotooriKashin/Bilibili-Old 看回来的，试了试问题不少，猜测没有针对适配。
对于这些古早页面考虑适配吗？

**Comment by the1812** [comment]
那个旧版播放列表吗 不适配的
因为现在有明确的替代品(收藏夹播放列表)

**Comment by Geeyun-JY3** [comment]
了解了，但建议做些优化，或者干脆某些功能直接不在这些页面加载

**Comment by the1812** [comment]
估计没空管那些页面..
