### ISSUE TITLE
大会员弹幕不能下载了

### ISSUE THREAD

**Issue by zhuqingquan5510** [the1812/Bilibili-Evolved#825]
之前上周大会员的弹幕还是可以下载的，怎么现在不行了

**Comment by Coulomb-G** [comment]
什么叫大会员的弹幕?

**Comment by zhuqingquan5510** [comment]
需要大会员才能看的番剧里的弹幕，之前可以单独下载弹幕啊!上周还用的，现在左侧栏咋没选项了。[image](https://user-images.githubusercontent.com/49781547/89708406-624aef80-d9a9-11ea-8fc4-bd5975a4dd6c.png)

**Comment by the1812** [comment]
之前你开过什么破解大会员的脚本吗

**Comment by zhuqingquan5510** [comment]
> 之前你开过什么破解大会员的脚本吗

有的，“哔哩哔哩大会员视频替换”，现在也没用了。和这个有关吗

**Comment by the1812** [comment]
有关, 有视频的时候才能下弹幕

**Comment by zhuqingquan5510** [comment]
已经删掉那个脚本了。还没用。该咋整

**Comment by the1812** [comment]
除非你再找个类似的
我这里不提供任何大会员破解

**Comment by MotooriKashin** [comment]
可以跳转往biliplus下载，我之前都是这么下载弹幕的。弹幕本身不要求大会员，只是大会员视频未加载情况下页面不会提供弹幕链接。
