### ISSUE TITLE
漫画页适配问题

### ISSUE THREAD

**Issue by wangqs97** [the1812/Bilibili-Evolved#826]
如图所示，漫画页的评论区也有问题，不知道是否会考虑适配
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/55077238/89713752-5e7c9480-d9cc-11ea-9219-c3d8d0a3a0f3.png">
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/55077238/89713786-9388e700-d9cc-11ea-8c44-c3889733fa8a.png">

**Comment by the1812** [comment]
会

**Comment by Geeyun-JY3** [comment]
#581 #641 #656 #731
夜间模式的适配道阻且长啊🙈

**Comment by the1812** [comment]
<img height="30" src="https://user-images.githubusercontent.com/26504152/89726063-e4d6bc00-da48-11ea-978d-f33b2a6059c2.png">

**Comment by Coulomb-G** [comment]
修了，之后等更新
