### ISSUE TITLE
使用简化首页会导致首页视频直接转跳av号

### ISSUE THREAD

**Issue by Lcwhhh** [the1812/Bilibili-Evolved#827]
**关于哪一项功能**
简化首页

**问题描述**

使用简化首页的话无论在首页的什么地方（包括顶栏）视频都会转跳av号
除首页以外地方还是会转跳BV号的

**脚本版本**

正式版v.1.10.33

**浏览器版本**

**错误信息**

**附加截图**

**Comment by the1812** [comment]
脚本功能里提供的链接都是av号, 跟简化首页没什么关系
