### ISSUE TITLE
bilibili link 下载中心页面夜间模式适配问题

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#829]
**关于哪一项功能**
夜间模式

**问题描述**
bilibili link 下载中心的这两个页面（[APP](https://link.bilibili.com/p/eden/download)、[PC直播姬](https://live.bilibili.com/liveHime)）考虑适配吗´_>`
（其实目前用起来也没什么问题，就是有些字看不清楚）？
***
这个 [哔哩哔哩小视频](https://vc.bilibili.com) 是刚出来的吗（下面的分区好像都还没有视频，官方貌似未正式启用，但有小部分地方夜间模式未适配）？
***
要不专门开个 issue pin 起来专门收集夜间模式未适配的页面？我开 issue 都开到烦了´_>`

**脚本版本**
正式版 v1.10.33
预览离线版 753.98

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 84.0.4147.105（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
下载中心不考虑适配,这不属于网页端用户的常用页面.小视频页面完全是半成品,我这边写夜间的话,他一次更新我就得重新适配,暂时也不会考虑,夜间模式的适配范围主要是常用页面,常用页面平时更新后需要重新适配我可以在使用过程中发现

**Comment by the1812** [comment]
> 要不专门开个 issue pin 起来专门收集夜间模式未适配的页面？我开 issue 都开到烦了´_>`

你可以往你以前开的夜间issue下接着加
专门pin一个收集的会很长的

**Comment by Geeyun-JY3** [comment]
> 专门pin一个收集所有用户的会很长的

啊这🌚
专门用一个 issue 收集不是挺好的吗🌚？反正总会有没适配的页面，就让这个 issue 一直开着。还是说这是你们的工作流不习惯怎么干?

> 如果你希望全站范围内的夜间模式适配,我觉得你还是去找b站吧

这个不强求，以后开 issue 会注意的。

**Comment by the1812** [comment]
issue越长 打开时间就越长
之前那个#770 打开拉到底下都是肉眼可见的一条一条加载出来 要等好久才看到最新一条

**Comment by Geeyun-JY3** [comment]
> issue越长 打开时间就越长

嗯确实有利有弊。
既然这样我关 issue 了。
