### ISSUE TITLE
直播间的顶栏在夜间模式下未生效

### ISSUE THREAD

**Issue by lintmx** [the1812/Bilibili-Evolved#83]
**关于哪一项功能**

夜间模式

**问题描述**

样试设置中只开启夜间模式的情况下直播间顶栏未生效

**脚本版本**

正式版 1.7.12 和 预览离线版 240.84 都有该问题

**浏览器版本**

macOS Dark Mode Chrome 73.0.3683.75

**附加截图**

预览离线版 240.84：

<img width="1956" alt="Xnip2019-03-14_21-39-24" src="https://user-images.githubusercontent.com/10807435/54361898-f6286700-46a2-11e9-888d-0570e8d263bf.png">

**Comment by the1812** [comment]
更新了一下, 现在应该可以了
