### ISSUE TITLE
无法使用顶栏的视频搜索功能

### ISSUE THREAD

**Issue by arioll-alice** [the1812/Bilibili-Evolved#830]
**关于哪一项功能**

无法使用顶栏的视频搜索功能

**问题描述**

无法正常使用：Chrome版本 84.0.4147.105（正式版本）（64 位）
在（除直播中心的）搜索栏中键入XXX后，弹出新的网页，网址栏显示https://search.bilibili.com/all?keyword=XXX&from_source=banner_search 之后立即自动关闭该网页，且无浏览器历史记录；
若直接在网址栏键入https://search.bilibili.com/all?keyword=XXX&from_source=banner_search 则不会闪退，但会重定向，网址为https://search.bilibili.com/all?keyword=XXX

可正常使用：Microsoft Edge版本 84.0.522.52 (官方内部版本) (64 位)
在搜索栏中键入XXX后，弹出新的网页，网址栏显示https://search.bilibili.com/all?keyword=XXX&from_source=banner_search 不会闪退，后重定向于https://search.bilibili.com/all?keyword=XXX

将脚本关闭后搜索，两种浏览器网址栏均为https://search.bilibili.com/all?keyword=XXX&from_source=nav_suggest_new 不会闪退，无重定向

**脚本版本**

正式版1.10.33

**浏览器版本**

Chrome版本 84.0.4147.105（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
你说的这个重定向是开了 [`网址参数清理`](https://github.com/the1812/Bilibili-Evolved/blob/master/features.md#工具) 功能吧……
关掉这个功能再试试？

**Comment by arioll-alice** [comment]
> 你说的这个重定向是开了 [`网址参数清理`](https://github.com/the1812/Bilibili-Evolved/blob/master/features.md#%E5%B7%A5%E5%85%B7) 功能吧……
> 关掉这个功能再试试？

关闭此选项后仍出现上述问题

**Comment by Geeyun-JY3** [comment]
是否开启了 `自定义顶栏`？

**Comment by arioll-alice** [comment]
> 是否开启了 `自定义顶栏`？

开启了，关闭此项后正常😅，请问是出了什么问题？

**Comment by the1812** [comment]
`from_source=banner_search`这段我该更新下了

**Comment by Geeyun-JY3** [comment]
> 请问是出了什么问题？

我不知道啊（滑稽），我只是在帮开发者排查，这是个可能相关的功能🙈
