### ISSUE TITLE
直播间屏蔽头衔时房管和 up 标志不能完全屏蔽

### ISSUE THREAD

**Issue by sea-github** [the1812/Bilibili-Evolved#831]
您好，使用脚本屏蔽直播间头衔时房管和 up 标志不能完全屏蔽，会有下图这种方框存在（粉色为 up, 黄色为房管）。望修复。https://upload.cc/i1/2020/08/10/5Fk7jS.jpg

**Comment by sea-github** [comment]
您好，使用脚本屏蔽直播间头衔时房管和 up 标志不能完全屏蔽，会有下图这种方框存在（粉色为 up, 黄色为房管）。望修复。
https://upload.cc/i1/2020/08/10/5Fk7jS.jpg

**Comment by sea-github** [comment]
> 您好，使用脚本屏蔽直播间头衔时房管和 up 标志不能完全屏蔽，会有下图这种方框存在（粉色为 up, 黄色为房管）。望修复。https://upload.cc/i1/2020/08/10/5Fk7jS.jpg

**Comment by the1812** [comment]
头衔是另一种东西了, 房管和up目前没有提供屏蔽功能
现在方框的样子只是夜间模式还没适配

**Comment by sea-github** [comment]
> 头衔是另一种东西了，房管和 up 目前没有提供屏蔽功能
> 现在方框的样子只是夜间模式还没适配

了解了。谢谢。
