### ISSUE TITLE
Aria2 RPC 发送地址的时候 获取链接失败: -404 啥都木有

### ISSUE THREAD

**Issue by ToneySun** [the1812/Bilibili-Evolved#832]
**关于哪一项功能**
获取链接失败: -404 啥都木有

**问题描述**
https://www.bilibili.com/video/BV1gE411A7H8?p=2 视频下载视频

**Comment by ToneySun** [comment]
我试了六七遍，发现可以了。

**Comment by the1812** [comment]
尽量不要一次下太多 链接容易挂
