### ISSUE TITLE
能否在关注列表里添加搜索功能

### ISSUE THREAD

**Issue by KinoJian** [the1812/Bilibili-Evolved#833]
**关于哪一项功能**

能否在关注列表中加入搜索栏？有时候想找某个关注的up，但大多时候苦于名字记不全，导致在b站的搜索栏只能搜到一大堆类似名字的人，而b站搜索的过滤器里偏偏又没有只显示已关注这个选项，就很蛋疼。

**期望的效果**
希望的是，在关注列表添加一个搜索栏，然后搜索之后，可以显示出所有与关键词相关的up。

**脚本版本**
[预览]v1.10.34

**Comment by Geeyun-JY3** [comment]
没搞错的话，这又是一个被官方率先实现的这个需求<img src="https://i0.hdslb.com/bfs/emote/bba7c12aa51fed0199c241465560dfc2714c593e.png" width="20" height="20" alt="doge">……
前几天反馈夜间模式没适配的时候没想起这个 issue：https://github.com/the1812/Bilibili-Evolved/issues/1289#issuecomment-748051083
![image](https://user-images.githubusercontent.com/49396421/103168416-07d60100-486e-11eb-9bd9-3a19131f0e29.png)
联动：#555

又是一次「鸽到官方实现也是一种不鸽」（
@the1812 出来挨打<img src="https://i0.hdslb.com/bfs/emote/bba7c12aa51fed0199c241465560dfc2714c593e.png" width="20" height="20" alt="doge">

**Comment by Geeyun-JY3** [comment]
当然如果 issue 主还想要分组内搜索的功能的话，这个 issue 说不定还能继续维持现状<img src="https://i0.hdslb.com/bfs/emote/bba7c12aa51fed0199c241465560dfc2714c593e.png" width="20" height="20" alt="doge">

**Comment by the1812** [comment]
> 看来这里这个 `help wanted` tag 的意思是请求官方实现该需求

无解决方案当然是等官方出API (

**Comment by KinoJian** [comment]
hhh，前两天就看见了，好用。另外能实现就挺好了，还要啥自行车（
