### ISSUE TITLE
无法安装最新的preview版本

### ISSUE THREAD

**Issue by Kennnnnnji** [the1812/Bilibili-Evolved#834]
是使用的最新版chrome，加载解压的扩展
![image](https://user-images.githubusercontent.com/34367558/89875909-75033580-dbf0-11ea-86be-fdf2dcc519bf.png)

**Comment by the1812** [comment]
我这不是扩展程序...

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/89876084-bf84b200-dbf0-11ea-8aae-884b03019e3c.png)

**Comment by Kennnnnnji** [comment]
原来如此= =
