### ISSUE TITLE
下载含大量分P的视频时导出失败

### ISSUE THREAD

**Issue by Kennnnnnji** [the1812/Bilibili-Evolved#835]
**关于哪一项功能**
下载视频

**问题描述**

BV1oJ411q7Do

**脚本版本**

stable 1.10.33

**浏览器版本**

Chrome 84.0.4147.105

**附加截图**
![image](https://user-images.githubusercontent.com/34367558/89876102-c6132980-dbf0-11ea-8ad9-a8980af58412.png)

**Comment by the1812** [comment]
一次批量建议控制在30P以下
太多了b站不给下的

**Comment by Kennnnnnji** [comment]
原来如此，谢谢
