### ISSUE TITLE
视频下载路径是什么，下载的视频不知道跑到哪里去啦

### ISSUE THREAD

**Issue by Dopamine2333** [the1812/Bilibili-Evolved#836]
哪里都找过啦，死活没有找到下载的视频跑到哪里去了，下载路径到底是啥诶，常见问题解答和使用说明里面也都没有写

**Comment by the1812** [comment]
字面意思啊 就是平常浏览器下载的位置
![image](https://user-images.githubusercontent.com/26504152/89882593-9ddbf880-dbf9-11ea-82c6-0f5c16b9a453.png)

**Comment by Dopamine2333** [comment]
> 字面意思啊 就是平常浏览器下载的位置
> ![image](https://user-images.githubusercontent.com/26504152/89882593-9ddbf880-dbf9-11ea-82c6-0f5c16b9a453.png)

浏览器默认下载路径也去找过啦，但是确实是没有。不过出现了下载到99%的时候浏览器所有页面都崩溃了，我以为是视频下载完了，这样来看是视频没下载成功。不过我尝试了好几个视频都会在99%之后页面崩溃。16GB内存正常应该是够的啊_(°ω°｣∠)_

**Comment by the1812** [comment]
跟你电脑内存没关系的 只要到了1GB多浏览器就会崩掉那个标签页

**Comment by the1812** [comment]
大视频只能导出不能直接下载

**Comment by Dopamine2333** [comment]
> 大视频只能导出不能直接下载

好吧

**Comment by CKylinMC** [comment]
> 大视频只能导出不能直接下载

我看到下载面板有预计大小，可以加一个如果预计大小过大 就引导用户走导出下载

**Comment by the1812** [comment]
其实超过1G一直有个警告在那, 不过我猜没什么人会注意到(

**Comment by CKylinMC** [comment]
一般一个视频也就是百十来M，，，
