### ISSUE TITLE
脚本无效且左侧不显示齿轮和设置图标

### ISSUE THREAD

**Issue by ZSC2017IM** [the1812/Bilibili-Evolved#838]
已确认安装完全版本，正式版1.10.33和预览版1.10.34皆无效。平台为win10 1909，最新油猴，chrome版本
版本 84.0.4147.125（正式版本） （64 位）
控制台信息如下：
content.js:25 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
a @ content.js:25
(anonymous) @ content.js:26
(anonymous) @ content.js:26
(anonymous) @ content.js:26
(anonymous) @ content.js:1
b @ content.js:1
c @ content.js:2
(anonymous) @ page.js:1
DevTools failed to load SourceMap: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:13290 TypeError: Cannot read property 'insertAdjacentElement' of null
    at StyleManager.applyStyleFromText (userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:15845)
    at ResourceManager.<computed> [as applyStyleFromText] (userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:15912)
    at ResourceManager.setupColors (userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:15942)
    at new ResourceManager (userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:15915)
    at eval (userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16635)
logError @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:13290
eval @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16776
async function (async)
eval @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16571
tms_96db1e66_059b_4bca_8e55_48689b7ebfec @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16778
(anonymous) @ VM831:3
eval @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:4
eval @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:5
eval @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16779
(anonymous) @ VM831:3
E_c @ VM831:3
la @ VM833:64
create @ VM833:76
e @ VM833:16
run @ VM833:16
eval @ VM833:77
(anonymous) @ VM831:3
b @ VM831:2
eval @ VM833:77
eval @ VM833:77
TM_back @ VM833:78
eval @ VM833:78
(anonymous) @ VM831:3
exec_fn @ VM831:1
(anonymous) @ VM831:11
V @ VM831:10
e @ content.js:6
send @ content.js:8
next @ content.js:13
(anonymous) @ content.js:28
(anonymous) @ content.js:27
(anonymous) @ content.js:26
(anonymous) @ content.js:26
(anonymous) @ content.js:1
b @ content.js:1
c @ content.js:2
(anonymous) @ page.js:1
Show 6 more frames
userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:14115 Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at eval (userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:14115)
    at Array.forEach (<anonymous>)
    at Observer.start (userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:14113)
    at Function.observe (userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:14142)
    at Function.childList (userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:14145)
    at ScriptBlocker.start (userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16408)
    at eval (userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16630)
eval @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:14115
start @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:14113
observe @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:14142
childList @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:14145
start @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16408
eval @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16630
Promise.then (async)
eval @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16629
async function (async)
eval @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16571
tms_96db1e66_059b_4bca_8e55_48689b7ebfec @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16778
(anonymous) @ VM831:3
eval @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:4
eval @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:5
eval @ userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16779
(anonymous) @ VM831:3
E_c @ VM831:3
la @ VM833:64
create @ VM833:76
e @ VM833:16
run @ VM833:16
eval @ VM833:77
(anonymous) @ VM831:3
b @ VM831:2
eval @ VM833:77
eval @ VM833:77
TM_back @ VM833:78
eval @ VM833:78
(anonymous) @ VM831:3
exec_fn @ VM831:1
(anonymous) @ VM831:11
V @ VM831:10
e @ content.js:6
send @ content.js:8
next @ content.js:13
(anonymous) @ content.js:28
(anonymous) @ content.js:27
(anonymous) @ content.js:26
(anonymous) @ content.js:26
(anonymous) @ content.js:1
b @ content.js:1
c @ content.js:2
(anonymous) @ page.js:1
Show 11 more frames
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/vue.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/international-home/css/international-home.0.5df53f298fcc518c459e41a4b5d1548a569a78ec.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/international-home/css/international-home.1.5df53f298fcc518c459e41a4b5d1548a569a78ec.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/international-home/international-home.5df53f298fcc518c459e41a4b5d1548a569a78ec.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/international-home/1.international-home.5df53f298fcc518c459e41a4b5d1548a569a78ec.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
userscript.html?id=96db1e66-059b-4bca-8e55-48689b7ebfec:16592 Skipped <iframe> loading for https://message.bilibili.com/pages/nav/index_new_pc_sync
DevTools failed to load SourceMap: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by Coulomb-G** [comment]
鼠标移至网页左侧中央位置也没有反应吗?

**Comment by ZSC2017IM** [comment]
无反应，网页左侧中央是“联系客服”。之前用过该脚本，现在换电脑了不行了

**Comment by the1812** [comment]
Tampermonkey设置里改一下注入模式之类的东西试试

**Comment by ZSC2017IM** [comment]
感谢，注入模式从“即时”改为“标准”即可使用了
