### ISSUE TITLE
使用批量下载功能之后，下载功能失效

### ISSUE THREAD

**Issue by mypridelife** [the1812/Bilibili-Evolved#840]
**关于哪一项功能**
下载视频功能

**问题描述**
1、打开任意多P视频页面（例如https://www.bilibili.com/video/BV1m64y1F7Bx）
2、点击批量下载，点击IDM。此时一切正常
3、刷新页面，控制台报412。单个下载和批量下载均消失（失效）。

**脚本版本**
1.10.33

**浏览器版本**
Edge  84.0.522.59 （最新版）

**附加截图**

![捕获](https://user-images.githubusercontent.com/35483539/89985342-80686680-dcad-11ea-9f1c-6cc6589ebab0.PNG)

**Comment by the1812** [comment]
批量一次少下点 不然会被封一段时间

**Comment by mypridelife** [comment]
果然，好吧，谢谢
