### ISSUE TITLE
播放界面美化建议

### ISSUE THREAD

**Issue by jvvd2020** [the1812/Bilibili-Evolved#841]
**关于哪一项功能**

**期望的效果**
播放界面居中,然后右侧部分全部删除只留下视频和评论部分
up的名字可以放在标题上方
总之就是去除右边的部分只想留下视频,评论
其实也可以只留下视频部分
**脚本版本**

**Comment by the1812** [comment]
默认宽屏 + 隐藏视频推荐 + 隐藏推荐直播
