### ISSUE TITLE
希望添加视频评论区bv/av信息显示

### ISSUE THREAD

**Issue by nd002723** [the1812/Bilibili-Evolved#842]
效果如下
https://github.com/KeJunMao/BVHover

**Comment by the1812** [comment]
#555

**Comment by nd002723** [comment]
动图效果https://ainoob.com/api/getImage/08e0f8dc-b34c-457e-815f-a8212364622a

**Comment by Geeyun-JY3** [comment]
这里推荐个效果类似功能更强的：https://greasyfork.org/scripts/402355
