### ISSUE TITLE
为何播放窗口会跳动一下

### ISSUE THREAD

**Issue by Cairl** [the1812/Bilibili-Evolved#843]
[每次刷新页面，播放器的窗口都会在视频加载好后向上移动一点，虽然不影响观看，但是十分影响长期体验，希望能够解决或得知原因

**Comment by LonelySteve** [comment]
有一个叫做「自动定位到播放器」的功能，看一下这个选项是不是被打开了：
![image](https://user-images.githubusercontent.com/34429322/90259699-08509b00-de7d-11ea-909b-d14176cfabe8.png)

**Comment by Cairl** [comment]
这个定位播放器我以前也开过，并不是像这个功能这么大幅度，很细微吧
![123](https://user-images.githubusercontent.com/20336299/90261558-b8270800-de7f-11ea-89a3-5902967519cb.gif)

**Comment by the1812** [comment]
自定义顶栏和原版顶栏高度是不一样的 这个跳动的距离就是他们的高度差

**Comment by Cairl** [comment]
> 自定义顶栏和原版顶栏高度是不一样的 这个跳动的距离就是他们的高度差

原来如此，那我想要避免这个跳动，我要把哪项功能给关了呢？

**Comment by the1812** [comment]
自定义顶栏

**Comment by Cairl** [comment]
> 自定义顶栏

解决了，蟹蟹作者！
