### ISSUE TITLE
附加功能下的下载视频按钮消失

### ISSUE THREAD

**Issue by johnCheng-96** [the1812/Bilibili-Evolved#847]
**关于哪一项功能**
下载视频

**问题描述**

在所有视频都消失了下载视频按钮

**脚本版本**

1.10.33

**浏览器版本**

Version 84.0.4147.125 (Official Build) (64-bit)

**错误信息**

![image](https://user-images.githubusercontent.com/68536707/90324441-8d34d500-dfa1-11ea-93c0-53724fad1c01.png)
![image](https://user-images.githubusercontent.com/68536707/90324442-96be3d00-dfa1-11ea-976d-e5b2d2b60dc4.png)

**附加截图**

**Comment by the1812** [comment]
见 #840
