### ISSUE TITLE
首页动态栏不好使用鼠标滚轮

### ISSUE THREAD

**Issue by Fish-Who** [the1812/Bilibili-Evolved#848]
**关于哪一项功能**
首页动态栏
![2 - 副本](https://user-images.githubusercontent.com/56763355/90324993-88bfea80-dfa8-11ea-90e3-eb9b6df7c7ab.png)
![1 - 副本](https://user-images.githubusercontent.com/56763355/90324996-8a89ae00-dfa8-11ea-83f5-8c7cd1df95aa.png)

**问题描述**

在首页启动精简首页(清爽)后,将鼠标置于动态栏上,滚动鼠标滚轮以查看后面的动态的滚动速度极慢

**脚本版本**

正式版1.10.33

**浏览器版本**

Firefox 79.0 64位

**错误信息**

并非错误,可能是参数不合理

**附加截图**

**Comment by the1812** [comment]
按住 shift 再用滚轮
