### ISSUE TITLE
点击安装链接，不能弹出安装页面。有人遇到过这种情形吗？要怎么解决呢？

### ISSUE THREAD

**Issue by kethoven** [the1812/Bilibili-Evolved#849]
点击安装链接，总是跳转到下面这样的页面。
![火狐截图_2020-08-17T07-13-49 766Z](https://user-images.githubusercontent.com/64629623/90368399-8a6ada80-e09c-11ea-8022-39524ce09eba.png)
![火狐截图_2020-08-17T06-54-35 626Z](https://user-images.githubusercontent.com/64629623/90368421-922a7f00-e09c-11ea-819d-81393d334da2.png)

不能跳转到安装页面。有人遇到过这种情形吗？要怎么解决呢？

记得以前可以直接安装的啊，现在就很奇怪、很烦人。

**Comment by kethoven** [comment]
点击安装链接，总是跳转到下面这样的页面。
![火狐截图_2020-08-17T07-13-49 766Z](https://user-images.githubusercontent.com/64629623/90368399-8a6ada80-e09c-11ea-8022-39524ce09eba.png)
![火狐截图_2020-08-17T06-54-35 626Z](https://user-images.githubusercontent.com/64629623/90368421-922a7f00-e09c-11ea-819d-81393d334da2.png)

不能跳转到安装页面。有人遇到过这种情形吗？要怎么解决呢？

记得以前可以直接安装的啊，现在就很奇怪。

**Comment by Syt100** [comment]
油猴脚本有问题吧，重新安装一下油猴脚本试试

**Comment by the1812** [comment]
哪个源的 jsDelivr?

**Comment by kethoven** [comment]
> 
> 
> 哪个安装源的 jsDelivr?

所有的都是这种情况

**Comment by kethoven** [comment]
> 
> 
> 油猴脚本有问题吧，重新安装一下油猴脚本试试

等一下试试看！

**Comment by the1812** [comment]
那可能是Tampermonkey的问题

**Comment by kethoven** [comment]
> 
> 
> 油猴脚本有问题吧，重新安装一下油猴脚本试试

太感谢了！
通过备份，重装之后确实解决了。

**Comment by kethoven** [comment]
> 
> 
> 那可能是Tampermonkey的问题

确实是tampermonkey的问题，困扰我挺长时间的问题。
刚刚备份，重新安装之后解决了。
太感谢了！
