### ISSUE TITLE
希望能加入界面i18n化的功能

### ISSUE THREAD

**Issue by Etherrrr** [the1812/Bilibili-Evolved#85]
**关于哪一项功能**
希望能加入修改界面语言的功能（日语和英语）

**期望的效果**
对主站/直播间/个人空间的主要功能按键进行翻译

**脚本版本**
正式版/预览版

> 由于国外的up主入驻逐渐增多，希望能有一个工具能帮助他们更好的使用bilibili，恳请能得到您的帮助，谢谢！
如果该功能能予以考虑，我可以提供功能所需的本地化文本。

**Comment by the1812** [comment]
我得花点时间研究一下这些问题, 如果都可以解决的话, 这个功能就可以开工了
- [x] ~~本地化文本~~
- [ ] 快速获取网页上所有的文本节点
- [ ] 更新异步加载的文本节点
- [ ] 相同词语不同语境下的翻译
- [ ] 一些固定大小的界面元素无法适应变化的文本长度

**Comment by Etherrrr** [comment]
非常感谢！期待您的联络！

**Comment by the1812** [comment]
目前界面翻译已经作为隐藏功能 (开启方法见[wiki页面](https://github.com/the1812/Bilibili-Evolved/wiki/%E9%9A%90%E8%97%8F%E5%8A%9F%E8%83%BD)) 发布了, 内部测试的时候已经加了一些翻译文本, 有新的翻译可以随时发送给我 (英语) (the1812@outlook.com) 或者Coulomb-G (日语) (965145921@qq.com), 当然 pull request 也行 (源代码在`./utils/i18n/`).

**Comment by Etherrrr** [comment]
目前发现搜索界面的标签会出现字符溢出显示区域的情况
![Snipaste_2019-04-04_19-06-46](https://user-images.githubusercontent.com/20717049/55551332-221c9280-570d-11e9-90a2-cfbe8ecc4455.png)
以及在播放界面的关注按钮会有一瞬间变为日文后变回中文
![Snipaste_2019-04-04_19-06-20](https://user-images.githubusercontent.com/20717049/55551374-395b8000-570d-11e9-8f41-3338869f33ce.png)
这种情况是可以修复的吗？

**Comment by the1812** [comment]
布局错位可以通过往`i18n.css`里加样式修正, 播放页这个问题之后会研究一下的, 翻译器目前没有检测二次更改的机制.

**Comment by the1812** [comment]
已修复样式的问题, 翻译器现在也可以检测到二次更改, 关注按钮已经可以正确翻译了.

**Comment by Etherrrr** [comment]
相簿页的下拉菜单和功能区有错位现象
![image](https://user-images.githubusercontent.com/20717049/55699186-3a85f900-59fc-11e9-9a81-3ab1e875e093.png)
希望能得到修复

**Comment by Coulomb-G** [comment]
您好,能冒昧地问一句,您是哪个字幕组来进行沟通的么?我这边经过斟酌后,感觉部分用词需微调一下,如果是油管上也是如此,那我先道个歉,近期我这边梯子暂时炸了,不太方便考证部分用词,可以的话希望可以和字幕组沟通一下部分用词的精准性和可行性,联系QQ和之前提到的邮箱是同一个(๑•̀ㅂ•́)و✧欢迎联系
