### ISSUE TITLE
添加点踩按钮

### ISSUE THREAD

**Issue by ThebestkillerTBK** [the1812/Bilibili-Evolved#850]
手机端能点踩，能降低流量，电脑端不能（指视频点踩）

**Comment by Coulomb-G** [comment]
能降低流量?你有点踩的api吗

**Comment by ThebestkillerTBK** [comment]
可以抓包

**Comment by the1812** [comment]
抓得到且不用appID之类的验证我倒是可以考虑下

**Comment by consideration-ak** [comment]
这是API:
```javascript
method: 'post',
url: `app.bilibili.com/x/v2/view/dislike`,
data: get_sign(data, appkey)
```
这是data
```javascript
    data:{
        access_key:"",
        aid: unsafeWindow.aid,
        from:7,
        appkey:"",
        ts:new Date().getTime(),
        dislike:0,
        like:0
    },
```
`get_sign()` 在  [https://static.hdslb.com/js/md5.js](https://static.hdslb.com/js/md5.js) 中定义
`access_key` 的获取方法在 [https://greasyfork.org/scripts/393096-bilibiliexp](https://greasyfork.org/scripts/393096-bilibiliexp) 中有, `appkey` 每个用户都会分配, 但我不知道怎么获取

**Comment by consideration-ak** [comment]
手机(安卓)端抓包需要安装 `xposed` 框架并安装 [JustTrustMe](https://github.com/Fuzion24/JustTrustMe), 否则过不了b站的 `SSL certificate checking`

**Comment by the1812** [comment]
很可惜这个还是手机端的API... 我之前也说了需要“抓得到且不用appID之类的验证”
这些 appkey / access_key 属于不稳定的参数, 随时可能挂掉, 我是不会加入到脚本里的

**Comment by consideration-ak** [comment]
> 很可惜这个还是手机端的API... 我之前也说了需要“抓得到且不用appID之类的验证”
> 这些 appkey / access_key 属于不稳定的参数, 随时可能挂掉, 我是不会加入到脚本里的

是的, 貌似点踩b站没有为其设计pc端api
