### ISSUE TITLE
直播丢帧、卡顿

### ISSUE THREAD

**Issue by freejool** [the1812/Bilibili-Evolved#852]
问题描述
观看直播时画面丢帧、卡顿
![图片](https://user-images.githubusercontent.com/39995589/90475200-99639280-e159-11ea-8ef2-b39b071870a2.png)
关掉脚本就正常了

脚本版本
1.10.33

浏览器版本
edge 84.0.522.59
chrome 84.0.4147.125 都有这个问题
firefox 正常

**Comment by the1812** [comment]
能否具体到某个功能上? (每次关掉几个功能测试下

**Comment by freejool** [comment]
可能是谷歌内核的问题，因为后来发现关掉脚本也卡QAQ
