### ISSUE TITLE
重定向稍后再看页面总是导向空白页

### ISSUE THREAD

**Issue by shanelex** [the1812/Bilibili-Evolved#853]
**关于哪一项功能**
重定向稍后再看页面

**问题描述**

在稍后再看页面点击任意视频总是跳转到空白页面，而顶栏稍后再看重定向可以正常使用，关掉其他插件仍然有这个现象

**脚本版本**

v1.10.33

**浏览器版本**

84.0.4147.125（正式版本） （64 位）

**错误信息**

不提示错误信息

**附加截图**
![Snipaste_2020-08-18_20-08-02](https://user-images.githubusercontent.com/69851509/90511075-8c14cb00-e18e-11ea-9f14-0d9da13b8964.png)

**Comment by the1812** [comment]
这个功能因为b站改版暂时下掉了 现在只支持顶栏
