### ISSUE TITLE
关于视频选项下 设置默认播放速度后在视频右下角的倍速显示问题

### ISSUE THREAD

**Issue by qlj1997** [the1812/Bilibili-Evolved#854]
**关于哪一项功能**
关于视频选项下 设置默认播放速度后在视频右下角的倍速显示问题

**问题描述**

视频播放页 插件设置默认倍速为两倍速, 在播放器右下角齿轮图表仍显示1.0倍速, 默认2倍速要切换回1倍速, 需要先选其他倍速, 才能切回1倍速

**脚本版本**

stable v1.10.33

**浏览器版本**

版本 85.0.4183.69（正式版本）beta （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/30916060/90526569-241caf80-e1a3-11ea-9b93-f18e869525dc.png)
![image](https://user-images.githubusercontent.com/30916060/90526628-35fe5280-e1a3-11ea-9f5a-fc41d0fe45f9.png)

**Comment by the1812** [comment]
后续请用快捷键更改速度, 对右下角这里是不做适配的

**Comment by qlj1997** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Grant Howard"<notifications@github.com&gt;; 
发送时间: 2020年8月18日(星期二) 晚上10:45
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "邱乐净"<211043494@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 关于视频选项下 设置默认播放速度后在视频右下角的倍速显示问题 (#854)





 
后续请用快捷键更改速度, 对右下角这里是不做适配的
