### ISSUE TITLE
【弹幕记录器】在直播有活动界面时连接失败

### ISSUE THREAD

**Issue by D274524** [the1812/Bilibili-Evolved#855]
**关于哪一项功能**
直播弹幕记录器

**问题描述**

https://live.bilibili.com/934514?share_source=copy_link
某个直播间举办活动，更改了直播界面后，就无法连接
**脚本版本**

最新正式版和offline版

**浏览器版本**

wiki浏览器 电脑版firefox

**错误信息**

Cannot read property 'href' of null

**附加截图**
![Screenshot_2020-08-19-05-57-53-955_com kiwibrowser browser](https://user-images.githubusercontent.com/69875121/90569802-1c91e200-e174-11ea-9eed-139d98967f00.jpg)

**Comment by D274524** [comment]
> 活动页面里直播相关功能一般都不起效的
> 可以加`blanc`转至源直播间观看 https://live.bilibili.com/blanc/934514

谷歌

**Comment by D274524** [comment]
> 活动页面里直播相关功能一般都不起效的
> 可以加`blanc`转至源直播间观看 https://live.bilibili.com/blanc/934514

今天试过了添加链接，完全没有用。还是记录不了，希望修复，或者添加一个在手机版页面的弹幕记录器

**Comment by D274524** [comment]
弹幕记录器 又不行了，记录中，就是0弹幕

**Comment by the1812** [comment]
直播间最近改版了..
