### ISSUE TITLE
Firefox中

### ISSUE THREAD

**Issue by RusterLiu** [the1812/Bilibili-Evolved#859]
**关于哪一项功能**
直接下载

**问题描述**

在直接下载栏中点击开始，下载完成后弹出Firefox内建下载，然后点击保存文件时逻辑上应该保存到本地下载文件夹，但实际上这个任务并没有进入火狐的下载队列。目前这种情况是偶尔发生的，无法确定发生条件。

**脚本版本**

1.10.33

**浏览器版本**

Firefox79

**错误信息**

**附加截图**

**Comment by RusterLiu** [comment]
这个issue能使删除吗？

**Comment by Geeyun-JY3** [comment]
@RusterLiu 如果没问题了直接关闭就行。

**Comment by RusterLiu** [comment]
the1812/Bilibili-Evolved,这个repo始终出现在我主页的repos中，无法删除。我查找原因应该是我提了这个issue，所以我要怎么删除这个issue才能让我主页的repos中不再显示这个repo。

**Comment by the1812** [comment]
我可以帮你删除这个 issue
不过我看你的主页 repos 是空的
![image](https://user-images.githubusercontent.com/26504152/104260689-f1ab8000-54be-11eb-9699-3d641737d19f.png)

**Comment by RusterLiu** [comment]
![截屏2021-01-12 上午10 21 53](https://user-images.githubusercontent.com/17938808/104261337-4996b680-54c0-11eb-8bee-bc102b45a404.png)
谢谢
