### ISSUE TITLE
番剧页面下附加功能中BV号显示问题

### ISSUE THREAD

**Issue by DuskShadows** [the1812/Bilibili-Evolved#860]
**关于哪一项功能**
番剧页面下附加功能中BV号显示

**问题描述**
在切换集数时附加功能中的BV号不随集数的切换改变，而是保留进入该番剧页面时的集数的BV号
（AV号跟随集数正常切换）

**脚本版本**
Offline 745.28

**浏览器版本**
Chrome 81.0.4044.138

**错误信息**
以下为按要求找到的相关信息，不知是否与本问题相关：

userscript.html?name=%E8%A7%A3%E9%99%A4B%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6.user.js&id=79a4a98c-d3cb-419c-a248-6241cfc2fb78:240 info: mode: default blocked_vip: undefined server: https://www.biliplus.com upos_server: undefined flv_prefer_ws:  remove_pre_ad: undefined enable_in_av: undefined readyState: loading isLogin: true isLoginBiliBili: true
VM290 ep330803:1 A cookie associated with a cross-site resource at http://biliplus.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
VM290 ep330803:1 A cookie associated with a resource at http://biliplus.com/ was set with `SameSite=None` but without `Secure`. It has been blocked, as Chrome now only delivers cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
www.biliplus.com/login?act=expiretime:1 Uncaught SyntaxError: Unexpected identifier
video.98f250de9ac06241fcf3880a14daae17e29516e3.js:1                      //         \\         //          \\       //    ##DDDDDDDDDDDDDDDDDDDDDD##    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|    ## MMMMMMMMMMMMMMMMMMMM ##    ##MMMMMMMMMMMMMMMMMMMMMM##                             Release 1.0.0. Powered by jinkela-core 2.4.8.         \/            \/
video.98f250de9ac06241fcf3880a14daae17e29516e3.js:1 true
13video.98f250de9ac06241fcf3880a14daae17e29516e3.js:1 premiereid: undefined
jsc-player.e919449d.js:266 [Websocket]: On Open.
userscript.html?name=Bilibili%20Evolved%20(Offline).user.js&id=8a9a488c-a703-423f-a597-64698fcdd270:16529 Skipped <iframe> loading for https://message.bilibili.com/pages/nav/index_new_pc_sync
video.98f250de9ac06241fcf3880a14daae17e29516e3.js:1 true
jsc-player.e919449d.js:266 [Websocket]: On Open.
DevTools failed to load SourceMap: Could not load content for chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://s1.hdslb.com/bfs/seed/jinkela/header-v2/header.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
video.98f250de9ac06241fcf3880a14daae17e29516e3.js:1 true
jsc-player.e919449d.js:266 [Websocket]: On Open.
video.98f250de9ac06241fcf3880a14daae17e29516e3.js:1 true
jsc-player.e919449d.js:266 [Websocket]: On Open.

**相关截图**
![进入页面时的集数(左上角与右下角相同)](https://user-images.githubusercontent.com/65220815/90667862-bc896180-e281-11ea-876a-1283e1e780ad.png)

![切换集数后左上角仍保留先前集数的BV号](https://user-images.githubusercontent.com/65220815/90667947-e3e02e80-e281-11ea-9a2b-43e0086a4eae.png)

**Comment by DuskShadows** [comment]
截图说明：上图为进入番剧画面时的情况（左上角与右下角信息相同）；下图为切换集数后的情况（BV号仍保持为先前集数）
补充：在切换集数后刷新则显示切换集数后的BV号

**Comment by Geeyun-JY3** [comment]
这个算 #678 的遗留 bug？
是因为切换后的是需要大会员且无法预览的剧集？

顺便还发现个 bug，通过 av 号进入此类剧集附加功能中直接不显示 av/BV 号，如 [av27382837](https://www.bilibili.com/video/av27382837/)

穷人才能发现的 bug？（逃

**Comment by DuskShadows** [comment]
我通过av号进入剧集页面的时候自动跳转到ep编号的页面了
同样以https://www.bilibili.com/video/av27382837/为例，进入页面后跳转到了https://www.bilibili.com/bangumi/play/ep232467/
AV/BV号显示正常，并没有发现附加功能中不显示的情况

**Comment by Geeyun-JY3** [comment]
> 我通过av号进入剧集页面的时候自动跳转到ep编号的页面了
> 同样以https://www.bilibili.com/video/av27382837/ 为例，进入页面后跳转到了 https://www.bilibili.com/bangumi/play/ep232467/
> AV/BV号显示正常，并没有发现附加功能中不显示的情况

穷人才能发现的 bug 实锤

**Comment by the1812** [comment]
我记得换一部番剧就能触发吧 前几天遇到过

**Comment by Geeyun-JY3** [comment]
这个 bug 好像还在，而且变成了 av 号／BV 号都不会跟着改变

> 先进入第一集 出现av/bv号 换到后面看不了的集av/bv号却没消失

这个问题也还有，即从可以看的集切换至看不了的集时 av 号／BV 号仍为先前打开的可以看的集的 av 号／BV 号。

另外还是希望切换至看不了的集时仍能在附加功能中看到其 av 号／BV 号。毕竟下方的简介也还会显示对应 BV 号。
![image](https://user-images.githubusercontent.com/49396421/92305825-527cf600-efbd-11ea-8ff6-f7c74521a2b2.png)

**Comment by the1812** [comment]
因为是直接取的`window.aid / window.bvid`, 看不了的集b站不提供这个
即使页面上有BV号, 我也不知道av号是多少

**Comment by Geeyun-JY3** [comment]
> 因为是直接取的`window.aid / window.bvid`, 看不了的集b站不提供这个
> 即使页面上有BV号, 我也不知道av号是多少

好吧，就修上面的 bug 吧。

**Comment by Geeyun-JY3** [comment]
> 先进入第一集 出现av/bv号 换到后面看不了的集av/bv号却没消失

这个问题好像还有啊
