### ISSUE TITLE
希望增加主页布局调整/主页分区隐藏功能

### ISSUE THREAD

**Issue by DuskShadows** [the1812/Bilibili-Evolved#861]
**关于哪一项功能**
主页布局调整
B站提供了让用户根据需要调整分区模块顺序的功能，能否在此基础上实现将不感兴趣的分区（乃至热门推荐）隐藏的功能？
【主页简化(清爽)功能中表现的效果很好但是能否让各模块(如活动、热门、排行榜)让用户选择是否显示？】
**期望的效果**
用户按需要对不感兴趣的分区进行隐藏（能直接隐藏最顶上的热门推荐就再好不过）
或
主页简化(清爽)功能中让用户选择是否显示各模块(如活动、热门、排行榜)

**该想法与
https://github.com/the1812/Bilibili-Evolved/issues/693
比较接近，但我希望可以直接隐藏不感兴趣的分区乃至将页面最上方的热门推荐和活动模块以及各分区排行榜纳入可编辑(隐藏)的范围**

**脚本版本**
当前使用版本:Offline 745.28

**Comment by the1812** [comment]
原首页可以做一个隐藏分区的功能
简化首页里布局设计有点问题 不能随意隐藏某个板块

**Comment by DuskShadows** [comment]
那么能否将原首页中的**活动和热门板块**也作为一个"分区"模块纳入可隐藏的范围？

**Comment by the1812** [comment]
可以
