### ISSUE TITLE
脚本无法使用

### ISSUE THREAD

**Issue by llc-c** [the1812/Bilibili-Evolved#867]
**关于哪一项功能**
所有功能

**问题描述**
安装后页面左侧无小齿轮
使用旧版本时出现了#770 的问题，于是更新

**脚本版本**
已尝试过正式版v1.10.33和预览版1.10.34（包括离线版）
也试过 #838 中修改注入模式的方法，没有变化

**浏览器版本**
Chrome 84.0.4147.135（正式版本） （32 位）
Tampermonkey v4.10

**错误信息**
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=a2624cdc-3089-4152-bce0-607caf8c8a31:1 
ERROR: Execution of script 'Bilibili Evolved (Preview)' failed! Vue is not defined
eval	@	userscript.html?name…bce0-607caf8c8a31:1
eval	@	userscript.html?name…bce0-607caf8c8a31:1
eval	@	userscript.html?name…0-607caf8c8a31:3654
eval	@	userscript.html?name…0-607caf8c8a31:3656
(anonymous)	@	VM890:3
c	@	VM890:2
(anonymous)	@	VM890:3
la	@	VM905:60
create	@	VM905:71
run	@	VM905:13
eval	@	VM905:73
(anonymous)	@	VM890:3
c	@	VM890:2
eval	@	VM905:73
eval	@	VM905:73
TM_back	@	VM905:74
eval	@	VM905:74
(anonymous)	@	VM890:3
exec_fn	@	VM890:1
(anonymous)	@	VM890:12
R	@	VM890:11
send	@	content.js:7
next	@	content.js:12
(anonymous)	@	content.js:27
(anonymous)	@	content.js:24

userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=a2624cdc-3089-4152-bce0-607caf8c8a31:1 
ERROR: Execution of script 'Bilibili Evolved (Preview)' failed! Vue is not defined
eval	@	userscript.html?name…bce0-607caf8c8a31:1
eval	@	userscript.html?name…bce0-607caf8c8a31:1
eval	@	userscript.html?name…0-607caf8c8a31:3654
eval	@	userscript.html?name…0-607caf8c8a31:3656
(anonymous)	@	VM923:3
c	@	VM923:2
(anonymous)	@	VM923:3
la	@	VM928:60
create	@	VM928:71
run	@	VM928:13
eval	@	VM928:73
(anonymous)	@	VM923:3
c	@	VM923:2
eval	@	VM928:73
eval	@	VM928:73
TM_back	@	VM928:74
eval	@	VM928:74
(anonymous)	@	VM923:3
exec_fn	@	VM923:1
(anonymous)	@	VM923:12
R	@	VM923:11
send	@	content.js:7
next	@	content.js:12
(anonymous)	@	content.js:27
(anonymous)	@	content.js:24

sentry-5.7.1.min.js:2 GET https://message.bilibili.com/api/tooltip/query.list.do net::ERR_CONNECTION_CLOSED
(anonymous) @ sentry-5.7.1.min.js:2
(anonymous) @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:93
t.exports @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:93
t.exports @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:127
Promise.then (async)
u.request @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:127
(anonymous) @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:93
(anonymous) @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:127
(anonymous) @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:127
Promise.then (async)
(anonymous) @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:127
Promise.catch (async)
$ @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:127
q @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:127
getFloatMessage @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:127
sentryWrapped @ sentry-5.7.1.min.js:2
setInterval (async)
(anonymous) @ sentry-5.7.1.min.js:2
onInit @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:127
mounted @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:127
Jt @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
en @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
insert @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
j @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
(anonymous) @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
t._update @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
r @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
hn.get @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
hn.run @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
pn @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
(anonymous) @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
Xt @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
Promise.then (async)
Gt @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
re @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
(anonymous) @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
hn.update @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
pt.notify @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
set @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:7
onLoginUpdate @ international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
(anonymous) @ international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
value @ international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
(anonymous) @ international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
g @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:18
(anonymous) @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:18
forEach.t.<computed> @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:18
n @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
c @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
Promise.then (async)
n @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
c @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
(anonymous) @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
(anonymous) @ 1.international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
(anonymous) @ international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
839 @ international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
s @ international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
373 @ international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
s @ international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
i @ international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
(anonymous) @ international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1
(anonymous) @ international-home.4cf8d6d067f3fe8154053b4923aa64b31e5d8a3f.js:1

**Comment by the1812** [comment]
依赖库下载失败了 试下访问这些库的地址吧

https://cdn.jsdelivr.net/npm/jquery@3.4.0/dist/jquery.min.js
https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js
https://cdn.jsdelivr.net/npm/jszip@3.1.5/dist/jszip.min.js
https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js
https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.js

**Comment by llc-c** [comment]
> 依赖库下载失败了 试下访问这些库的地址吧
> 
> https://cdn.jsdelivr.net/npm/jquery@3.4.0/dist/jquery.min.js
> https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js
> https://cdn.jsdelivr.net/npm/jszip@3.1.5/dist/jszip.min.js
> https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js
> https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.js

访问不了
![QQ图片20200821102419](https://user-images.githubusercontent.com/69995885/90845364-8094f000-e398-11ea-9db8-d2e2ce885f49.png)

**Comment by the1812** [comment]
换个浏览器/换个网络试试?

**Comment by llc-c** [comment]
> 
> 
> 换个浏览器/换个网络试试?

firefox可行，edge不行
问题解决了，谢谢~
