### ISSUE TITLE
下载视频功能在360极速浏览器无法正常使用

### ISSUE THREAD

**Issue by oDaShuTz** [the1812/Bilibili-Evolved#87]
**关于哪一项功能**
下载视频

**问题描述**
使用最新版的360极速浏览器，点击下载视频，不能弹出清晰度选择下拉菜单，无法正常下载视频，但是在原版Chrome就可以正常下载视频。**附注：没有下拉菜单的弹幕下载功能可以正常下载，看起来像是下拉菜单在360极速浏览器无法正常弹出。**

**脚本版本**
正式版1.7.17

**浏览器版本**

360极速浏览器
版本号： 11.0.2000.0
内核版本：69.0.3497.100

Google Chrome 
版本：73.0.3683.75（正式版本） （64 位）

**Comment by the1812** [comment]
Sorry, 脚本目前只支持原版的Chrome和Firefox哦, 其他套壳的浏览器功能多少会有点异常的

**Comment by oDaShuTz** [comment]
但是我刚开始安装的某个历史版本是可以在360极速浏览器正常运行的，更新到最新版就有这个问题了。

**Comment by the1812** [comment]
可能360那边改动了什么吧...这个下拉菜单的代码我最近一个月都没有动过, 要是失效的话应该一个月前就出问题了, 你记得是哪个版本的话我可以再细查一下.
