### ISSUE TITLE
批量导出一直提示“为防止短时间内大量下载导致封禁, 请不要选择超过32的集数.”

### ISSUE THREAD

**Issue by 624051787** [the1812/Bilibili-Evolved#871]
就算只选一集也不行，所有导出方式都试过了，都是一样的提示。

**Comment by ThebestkillerTBK** [comment]
最近很多反馈大量进行批量下载后无法再进行下载 (浏览器Console显示412错误) (#847, #840, #835)
在这里统一说明下, 短时间内大量进行批量下载会遭到b站封禁(你就只能等他过段时间解除封禁了), 所以请多加注意.
我能做的只有预防一下: 禁止批量导出32集以上的数量, 这个限制量可能还会根据之后的实际情况再做调整.
