### ISSUE TITLE
在夜间模式中直播弹幕房管图标显示出错

### ISSUE THREAD

**Issue by Malus-Mill** [the1812/Bilibili-Evolved#874]
**关于哪一项功能**
夜间模式、直播弹幕、胸章、房管图标

**问题描述**

打开直播界面；
开启夜间模式；
简化直播间设置如下图
对比
白天模式
![image](https://user-images.githubusercontent.com/53999738/91161322-33e54800-e6fd-11ea-88ef-33e5fef2d197.png)
夜间模式
![image](https://user-images.githubusercontent.com/53999738/91161377-45c6eb00-e6fd-11ea-9ff6-0c028ed77257.png)

**脚本版本**

离线版 745.28

**浏览器版本**

84.0.4147.89（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/53999738/91161086-d8b35580-e6fc-11ea-96d0-d365b22bba36.png)

**Comment by the1812** [comment]
下次更新会修复的

**Comment by Malus-Mill** [comment]
> 下次更新会修复的

主播图标也不显示。。。
![image](https://user-images.githubusercontent.com/53999738/91169645-4914a380-e70a-11ea-9957-bd300cf92fd9.png)
![image](https://user-images.githubusercontent.com/53999738/91169687-56ca2900-e70a-11ea-88b9-326a0bd01a99.png)
