### ISSUE TITLE
希望增加一个后台打开动态的功能

### ISSUE THREAD

**Issue by wasdujk** [the1812/Bilibili-Evolved#875]
**关于哪一项功能**

希望增加一个后台打开动态的功能

**期望的效果**
点击动态以_blank的方式打开新的页面

**脚本版本**

**Comment by the1812** [comment]
右键 - 新标签页打开
或者  ctrl + 点击

**Comment by Geeyun-JY3** [comment]
中键单击？

**Comment by wasdujk** [comment]
😂好吧，忘记浏览器本身具备这个功能
