### ISSUE TITLE
顶栏动态视频分栏显示加载中

### ISSUE THREAD

**Issue by GrayDeprave** [the1812/Bilibili-Evolved#879]
**关于哪一项功能**
顶栏动态视频分栏。

**问题描述**

顶栏动态视频分栏显示加载中，无法加载内容。

**脚本版本**
<预览版1.10.35>

**浏览器版本**
<Chrome 85.0.4183.83>

**错误信息**

以下为刷新页面之后的错误信息，不知道是否有用。

![image](https://user-images.githubusercontent.com/51424205/91259107-6a27d380-e7a0-11ea-832c-7f7a6739d898.png)
![image](https://user-images.githubusercontent.com/51424205/91259140-7a3fb300-e7a0-11ea-98d8-89d06c98aae5.png)

**附加截图**
![image](https://user-images.githubusercontent.com/51424205/91259353-eae6cf80-e7a0-11ea-8103-0000a0a36585.png)

**Comment by the1812** [comment]
清下缓存 这个是好几天前一个有问题的版本 4天前就修复了

**Comment by GrayDeprave** [comment]
> 清下缓存 这个是好几天前一个有问题的版本 4天前就修复了

清除脚本缓存、浏览器缓存、重新安装脚本之后，这个版本还是一样的问题。

**Comment by the1812** [comment]
代码里也搜索过了 出问题的`{{card.}}`已经删除了
我也重装了下1.10.35 没有遇到这个问题 你是哪个安装源下的?

**Comment by GrayDeprave** [comment]
> 代码里也搜索过了 出问题的`{{card.}}`已经删除了
> 我也重装了下1.10.35 没有遇到这个问题 你是哪个安装源下的?

![image](https://user-images.githubusercontent.com/51424205/91269605-01455900-e7aa-11ea-9d91-6d1aef1a1ae9.png)
这个安装源。

**Comment by the1812** [comment]
安装请去首页 https://github.com/the1812/Bilibili-Evolved
那些是 GitHub 自动存档的代码, 不是最新的

**Comment by GrayDeprave** [comment]
> 安装请去首页 https://github.com/the1812/Bilibili-Evolved
> 那些是 GitHub 自动存档的代码, 不是最新的

然后去切换tags找版本号直接下载就可以了吧，那知道了。

**Comment by GrayDeprave** [comment]
> 安装请去首页 https://github.com/the1812/Bilibili-Evolved
> 那些是 GitHub 自动存档的代码, 不是最新的

好吧我知道问题所在了，我安装的其实是那个压缩包里的正式版，换成预览版就好了。

**Comment by the1812** [comment]
反正不要按照tag或者release找 都以首页给出的链接为准
因为有热更新的存在 按tag下到的都是这个版本号下最老的文件
