### ISSUE TITLE
能否增加自动定位到播放器顶端功能

### ISSUE THREAD

**Issue by liumingye** [the1812/Bilibili-Evolved#88]
**关于哪一项功能**
增加自动定位到播放器顶端

**期望的效果**
像这个脚本的功能
https://github.com/kkren/bilibili_adjustPlayer/
![QQ截图20190318223616](https://user-images.githubusercontent.com/8676207/54538185-c6dd6700-49ce-11e9-916e-0b23605c94ee.png)

**脚本版本**
预览版

**Comment by the1812** [comment]
需要加偏移像素吗, 直接定位播放器基本上就居中了

**Comment by lintmx** [comment]
建议做成选择定位标题(id=viewbox_report)或播放器并且可以自定义偏移像素形式

定位在标题的在 1080 分辨率下感觉挺不错的
<img width="1959" alt="Xnip2019-03-27_22-18-35" src="https://user-images.githubusercontent.com/10807435/55083527-a56f3000-50de-11e9-8be9-6d52672db79a.png">

如果直接定位播放器不加偏移量的话会让人感觉是不是上面遮住了一部分
<img width="1959" alt="Xnip2019-03-27_22-18-55" src="https://user-images.githubusercontent.com/10807435/55083615-c6d01c00-50de-11e9-9237-657677e2225e.png">

**Comment by the1812** [comment]
视频那定位到标题效果确实不错, 但是番剧标题在下面, 是不是不定位好一些?

**Comment by lintmx** [comment]
看了下，番剧不跳转的位置算正好的，或者跳转到刚好把导航栏隐藏起来也不错

<img width="1960" alt="Xnip2019-04-13_11-31-08" src="https://user-images.githubusercontent.com/10807435/56074139-df7b4a00-5ddf-11e9-9039-8491188e5285.png">

**Comment by the1812** [comment]
好的, 那就默认偏移-10px吧, 两边效果都不错
