### ISSUE TITLE
希望增加视频封面上展示视频关键帧功能

### ISSUE THREAD

**Issue by RexzeLu** [the1812/Bilibili-Evolved#880]
**关于哪一项功能**

动态/视频封面展示效果

**期望的效果**
希望右上角动态弹出的视频动态列表/首页全局增加封面上左右滑动鼠标展示视频关键帧画面功能，类似b站原生展示效果，如果没有api能拿到关键帧就算咯=_=

**脚本版本**
V1.10.33
Chrome 84.0.4147.135

**Comment by the1812** [comment]
同 #747

**Comment by RexzeLu** [comment]
好吧 关键词没搜到……
