### ISSUE TITLE
进bilibili的时候，如果是后台加载的，就不会加载本插件

### ISSUE THREAD

**Issue by chncrab** [the1812/Bilibili-Evolved#881]
**关于哪一项功能**
加载

**问题描述**
进bilibili的时候，如果是后台加载的，就不会加载本插件。
如果是标签页后台打开b站，然后立刻切过去变成前台，则可以正常加载。
如果持续标签页后台等待b站加载完，则插件不会正常加载

**脚本版本**
离线预览版 v768.90 （正式v1.10.33 Preview v1.10.35等均有这个问题）

**浏览器版本**
firefox 80.0

**错误信息**
TypeError: document.head is null
    applyStyleFromText moz-extension://492c67e7-f636-47b4-85be-2b8acc566004/userscripts/Bilibili Evolved (Preview Offline).user.js?id=8e83931f-a011-4af5-997e-4a4effc3eb51:15806
    key moz-extension://492c67e7-f636-47b4-85be-2b8acc566004/userscripts/Bilibili Evolved (Preview Offline).user.js?id=8e83931f-a011-4af5-997e-4a4effc3eb51:15873
    setupColors moz-extension://492c67e7-f636-47b4-85be-2b8acc566004/userscripts/Bilibili Evolved (Preview Offline).user.js?id=8e83931f-a011-4af5-997e-4a4effc3eb51:15903
    ResourceManager moz-extension://492c67e7-f636-47b4-85be-2b8acc566004/userscripts/Bilibili Evolved (Preview Offline).user.js?id=8e83931f-a011-4af5-997e-4a4effc3eb51:15876
    tms_8e83931f_a011_4af5_997e_4a4effc3eb51 moz-extension://492c67e7-f636-47b4-85be-2b8acc566004/userscripts/Bilibili Evolved (Preview Offline).user.js?id=8e83931f-a011-4af5-997e-4a4effc3eb51:16596

Uncaught (in promise) TypeError: MutationObserver.observe: Argument 1 is not an object.
    start moz-extension://492c67e7-f636-47b4-85be-2b8acc566004/userscripts/Bilibili Evolved (Preview Offline).user.js?id=8e83931f-a011-4af5-997e-4a4effc3eb51:14115
    start moz-extension://492c67e7-f636-47b4-85be-2b8acc566004/userscripts/Bilibili Evolved (Preview Offline).user.js?id=8e83931f-a011-4af5-997e-4a4effc3eb51:14113
    observe moz-extension://492c67e7-f636-47b4-85be-2b8acc566004/userscripts/Bilibili Evolved (Preview Offline).user.js?id=8e83931f-a011-4af5-997e-4a4effc3eb51:14142
    childList moz-extension://492c67e7-f636-47b4-85be-2b8acc566004/userscripts/Bilibili Evolved (Preview Offline).user.js?id=8e83931f-a011-4af5-997e-4a4effc3eb51:14145
    start moz-extension://492c67e7-f636-47b4-85be-2b8acc566004/userscripts/Bilibili Evolved (Preview Offline).user.js?id=8e83931f-a011-4af5-997e-4a4effc3eb51:16369
    tms_8e83931f_a011_4af5_997e_4a4effc3eb51 moz-extension://492c67e7-f636-47b4-85be-2b8acc566004/userscripts/Bilibili Evolved (Preview Offline).user.js?id=8e83931f-a011-4af5-997e-4a4effc3eb51:16591

**附加截图**

**Comment by LTHPKBTE** [comment]
此问题已被提出过。详见#311 #294 #283 。
解决办法是在脚本管理器中设置运行时期为document-body（直接改源码也行）

**Comment by the1812** [comment]
有些情况可以改这里解决
![image](https://user-images.githubusercontent.com/26504152/91857145-19314700-ec9a-11ea-9bdc-0c16e8e647f1.png)

**Comment by chncrab** [comment]
谢谢,已解决。
