### ISSUE TITLE
打开特定视频, 网页会不断自动跳转

### ISSUE THREAD

**Issue by Issac-v** [the1812/Bilibili-Evolved#883]
**关于哪一项功能**

网页自动反复跳转, 仅针对此视频

**问题描述**

从B站排行榜进入, 是老番茄的视频
打开网址如右https://www.bilibili.com/video/av841881271/
网页会不断自动刷新, 网址栏反复轮换以下三个网址
https://www.bilibili.com/video/av841881271/
https://www.bilibili.com/video/BV1R54y1e7Bm/?spm_id_from=333.788.videocard_series
https://www.bilibili.com/video/BV1R54y1e7Bm/

*关闭浏览器后重开, 问题不消失*
*经测试未发现其他视频有此现象*

**脚本版本**

1.10.33

**浏览器版本**

 84.0.4147.135（正式版本） （64 位）

**错误信息**

网页跳转太快, 浏览器的刷新按钮并无变化所以也没法强制停止, 来不及复制, 直接贴图了, 见下图

**附加截图**
![image](https://user-images.githubusercontent.com/54757860/91375782-212e5880-e84e-11ea-9506-08e7a2f18a3f.png)

`Go to Issues` 点击后如下

![image](https://user-images.githubusercontent.com/54757860/91375947-884c0d00-e84e-11ea-81e7-3fb19fccec46.png)

**Comment by the1812** [comment]
关闭网址av号转换试试

**Comment by Issac-v** [comment]
> 关闭网址av号转换试试

关闭后可正常加载

**Comment by Issac-v** [comment]
> > 关闭网址av号转换试试
> 
> 关闭后可正常加载

补充: 关闭后从上面三个网址进入, 都会被重定向到https://www.bilibili.com/video/BV1R54y1e7Bm/?spm_id_from=333.788.videocard_series, 然后正常加载

**Comment by the1812** [comment]
我开着av号转换倒也没事 全部会被改回 https://www.bilibili.com/video/av841881271/

**Comment by the1812** [comment]
是不是有别的插件把网站往 https://www.bilibili.com/video/BV1R54y1e7Bm/?spm_id_from=333.788.videocard_series 导?

**Comment by Issac-v** [comment]
我在PC端测试的是关闭该脚本后打开, chrome隐身模式打开, edge(无任何插件)打开, 均会被导向https://www.bilibili.com/video/BV1R54y1e7Bm/?spm_id_from=333.788.videocard_series
但是安卓端用鸭鸭跑浏览器打开则不会被重定向
我也想不出是啥在把网址往那儿导了...但应该不是be的锅, 我把这个issue关了吧

**Comment by the1812** [comment]
#760, #712 说的应该也是这个问题, 导向的 `videocard_series` 疑似是新功能“系列视频” (#882), 只有部分用户可见, 我目前还没收到这个功能

**Comment by naive12138** [comment]
我也遇到了这个问题，推测是b站新功能系列视频的问题。会不断重定向链接，导致和bv号转换功能冲突

**Comment by 11111111111ge1** [comment]
我用Bilibili AntiBV[https://greasyfork.org/zh-CN/scripts/398499-bilibili-antibv/discussions/2446](url)插件也出现了这个问题，所以就去那边反馈版看了眼，发现早在五月份[https://greasyfork.org/zh-CN/scripts/398499-bilibili-antibv/discussions/2446](url)就有人遇到了这个bug。
而那时系列视频功能还没有出（大概），所以应该不是系列视频的问题

**Comment by 11111111111ge1** [comment]
我用[Bilibili-AntiBV](https://greasyfork.org/zh-CN/scripts/398499-bilibili-antibv)  插件也出现了这个问题，所以就去那边反馈版看了眼，发现早在五月份[https://greasyfork.org/zh-CN/scripts/398499-bilibili-antibv/discussions/2446](https://greasyfork.org/zh-CN/scripts/398499-bilibili-antibv/discussions/2446)就有人遇到了这个bug。
而那时系列视频功能还没有出（大概），所以应该不是系列视频的问题

**Comment by the1812** [comment]
至少现在是了  我已经遇到系列视频了  出现的无限跳转跟他们描述的完全一致
