### ISSUE TITLE
主页顶栏样式

### ISSUE THREAD

**Issue by KB3146706** [the1812/Bilibili-Evolved#886]
**关于哪一项功能**
主页顶栏

**问题描述**

![image](https://user-images.githubusercontent.com/57534077/91514458-69667d00-e919-11ea-83e3-a8cd80cfc3f9.png)
页面为100%缩放

**脚本版本**

正式版1.10.33

**浏览器版本**

百分浏览器4.2.10.171 Chromium 80.0.3987.163 64位

P.s.关闭脚本后顶栏变成这样
![image](https://user-images.githubusercontent.com/57534077/91514549-9f0b6600-e919-11ea-9fd3-d0f3539ce4bf.png)
也很不对劲（也是100%缩放）

**Comment by Softland99** [comment]
刚才我在chrome也有这个问题  反馈编辑一半 它又恢复了。。

**Comment by the1812** [comment]
关闭后也不对劲吧 那应该不是脚本的问题啊

**Comment by KB3146706** [comment]
> 刚才我在chrome也有这个问题 反馈编辑一半 它又恢复了。。

确实现在又好了😂

**Comment by KB3146706** [comment]
> 关闭后也不对劲吧 那应该不是脚本的问题啊

现在又好了😂，感觉是玄学或B站抽风，Close了
