### ISSUE TITLE
希望增加动态页 屏蔽直播功能

### ISSUE THREAD

**Issue by 11111111111ge1** [the1812/Bilibili-Evolved#887]
**关于哪一项功能**

关注所有up主动态的屏蔽功能 https://t.bilibili.com/
![image](https://user-images.githubusercontent.com/39661677/91659762-857a4200-eb04-11ea-9c0a-3e10c75615b0.png)
一直刷到这种动态,但屏蔽列表没法单独屏蔽直播 很烦人
![image](https://user-images.githubusercontent.com/39661677/91659798-bd818500-eb04-11ea-87ec-befa0d15fd80.png)

测试了一下,在屏蔽类型里屏蔽文字动态 即可屏蔽直播,但会正常动态的误伤
**期望的效果**

**脚本版本**
1.10.33

**Comment by the1812** [comment]
在路上了.jpg

![image](https://user-images.githubusercontent.com/26504152/91659887-37b20980-eb05-11ea-933e-c83b610cd366.png)
