### ISSUE TITLE
下载视频重复

### ISSUE THREAD

**Issue by GitHubDer** [the1812/Bilibili-Evolved#89]
最新版的视频下载功能会下载两个重复的视频 希望能修复下

**Comment by the1812** [comment]
"下载两个重复的视频"是指什么? 连续弹了两个保存文件窗口吗?

**Comment by GitHubDer** [comment]
不是，就是点一下下载视频之后，会正常下载，然后等到要保存的时候会是一个压缩包，里面就有两个视频，而且两个都是一样的，一个文件名带个1一个文件名带个2，但是我又试过其他的视频有的又不会，不知道是插件问题还是B站的问题。

**Comment by the1812** [comment]
能给个av号吗, 这种情况是从b站拿到的链接有两条, 脚本当作是两段视频处理了, 因为一些旧的视频是一个视频分成好几段的
