### ISSUE TITLE
从脚本界面访问脚本主页、issues的路径不清晰

### ISSUE THREAD

**Issue by yfdyh000** [the1812/Bilibili-Evolved#892]
**关于哪一项功能**

用户有查看readme/检索issues/提交反馈等需求时，不太容易从侧栏找到地址。一度从脚本源码查 supportURL。当然，加浏览器书签等方法是可以的。

**期望的效果**
”设置“侧栏左下的版本号无链接，是否链至github的页面（首页或releases），但功用将与“查看更新日志”重叠。
右下角的“查看更新日志”虽然实用，但字号偏小、灰色，无底色或下划线等，很容易错过，能否突出一下。
设置右上角的 ... 菜单是用户常用的“路径”，是否加”主页“、”反馈“等菜单，作者可决定。

**脚本版本**
Stable v1.10.33

**Comment by LonelySteve** [comment]
如果能在侧边栏版本号旁边添加一个复制当前脚本版本号的按钮也会更方便:smile:

**Comment by the1812** [comment]
改进了下:
- 版本号等文字可选择, 双击版本号可选中版本号, 三连击是全选
- 右下的链接调亮了一些
- 右上的`...`加了一些选项

<img width="400" src="https://user-images.githubusercontent.com/26504152/92306423-8fe38280-efc1-11ea-9d0f-b9506a1e1a76.png">

**Comment by Geeyun-JY3** [comment]
> <img alt="" width="400" src="https://user-images.githubusercontent.com/26504152/92306423-8fe38280-efc1-11ea-9d0f-b9506a1e1a76.png">

点击主页按钮好像没反应

**Comment by Geeyun-JY3** [comment]
正式版和预览版或者可以让左下版本号可点击，链接至对应 release：`https://github.com/the1812/Bilibili-Evolved/releases/tag/版本号`。
如果觉得多余那这个 issue 其实可以关了。

**Comment by the1812** [comment]
可点击好像妨碍复制版本号了吧...
要看release可以从右上菜单进

**Comment by Geeyun-JY3** [comment]
主要想的是能精准定位至当前版本的更新日志。
当然这样确实不利于复制版本号。
如果不加这个 issue 可以关了吧。
