### ISSUE TITLE
话题页面不加载内容

### ISSUE THREAD

**Issue by Junji233** [the1812/Bilibili-Evolved#894]
**关于哪一项功能**
网页加载

**问题描述**

https://t.bilibili.com/topic/下的页面
如：https://t.bilibili.com/topic/5417/feed
无论是否登录

**脚本版本**

正式版1.10.33

**浏览器版本**

Chrome  83.0.4103.116

**错误信息**

页面提示：“还没有相关动态呢~”
关闭脚本后可以正常显示

**附加截图**
![image](https://user-images.githubusercontent.com/59426358/91768014-ff650680-ebaa-11ea-9e5c-bf076394d043.png)

**Comment by Coulomb-G** [comment]
我这边是正常显示,能否提供一下更详细的报错信息

**Comment by Geeyun-JY3** [comment]
这 bug 好像有段时间了

**Comment by the1812** [comment]
关了脚本再开又正常了

**Comment by Junji233** [comment]
确实开了夜间模式就能加载出来

**Comment by Coulomb-G** [comment]
这个应该是b站自身的bug，开不开脚本都有几率复现

**Comment by Junji233** [comment]
发现了，而且现在还没解决……
