### ISSUE TITLE
播放时的稍后再看，右侧列表一直显示在加载中，显示不出顶部的内容

### ISSUE THREAD

**Issue by zeroabc** [the1812/Bilibili-Evolved#896]
如题

具体看图
![QQ截图20200901174532](https://user-images.githubusercontent.com/6105867/91835023-67831d80-ec7b-11ea-889e-76a9dd109a6d.jpg)

**Comment by zeroabc** [comment]
忘了说，从自己的稍后再看列表的中间的视频（反正不是第一个视频）点击去，就会出现图中的情况

**Comment by the1812** [comment]
关了脚本也是这样
