### ISSUE TITLE
播放器错位和视频标题重叠

### ISSUE THREAD

**Issue by aliofwind** [the1812/Bilibili-Evolved#9]
![image](https://user-images.githubusercontent.com/35068322/47650768-35568f80-dbbc-11e8-8f61-b54792920409.png)
![image](https://user-images.githubusercontent.com/35068322/47650864-82d2fc80-dbbc-11e8-9c74-46082dfcd645.png)

**Comment by the1812** [comment]
我做了一些改动, 你看看还有没有错位?
非离线版清缓存刷新几次, 离线版更新一下应该就能看到效果.

**Comment by aliofwind** [comment]
正常了，多谢
