### ISSUE TITLE
暴力猴上安装不了（可能是浏览器太垃圾？）

### ISSUE THREAD

**Issue by SunJunge08** [the1812/Bilibili-Evolved#900]
**问题描述**

greasyfork安装时跳转到暴力猴上安装不了

**脚本版本**

试了好几个旧版本，都不能安装

**浏览器版本**

Chrome 84.0.4147.105（看来我得更新一下了）

**错误信息**

显示加载脚本依赖发生错误

**附加截图**
![image](https://user-images.githubusercontent.com/70008772/92115409-f2534c00-ee24-11ea-8e24-3d843d2a0ed1.png)

**Comment by SunJunge08** [comment]
现在更新到了85.0.4183.83，还是不行。。。

**Comment by Coulomb-G** [comment]
自v1.10.14版后, 脚本的大小超出了GreasyFork规定的最大脚本大小(2000000字符), 因此GreasyFork这边只能永远停在v1.10.12版了. 要使用最新版本,尽量从GitHub这边下载吧

**Comment by SunJunge08** [comment]
greasyfork上就有人反映了

**Comment by SunJunge08** [comment]
这个我看到了，我现在看一下这个能不能吧

**Comment by SunJunge08** [comment]
已经解决了，谢谢！
