### ISSUE TITLE
加载脚本依赖发生错误

### ISSUE THREAD

**Issue by Alopece** [the1812/Bilibili-Evolved#903]
![截图](https://user-images.githubusercontent.com/70740568/92203760-84eefc00-eeb4-11ea-8631-17fde4886217.PNG)

**Comment by Alopece** [comment]
https://code.jquery.com/jquery-3.4.0.min.js
这个打不开

**Comment by the1812** [comment]
https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@master/bilibili-evolved.user.js
