### ISSUE TITLE
没有中文语言选项

### ISSUE THREAD

**Issue by InkCoal** [the1812/Bilibili-Evolved#907]
不论是运行最新正式版抑或是最新离线版，插件都没有中文。语言选项中只有日语和英语两种，希望能够增加中文语言选项。

**Comment by Geeyun-JY3** [comment]
关闭 `界面翻译` 选项即可
![image](https://user-images.githubusercontent.com/49396421/92293625-8c1b1600-ef57-11ea-8c72-e103965a6827.png)

**Comment by InkCoal** [comment]
> 关闭 `界面翻译` 选项即可
> ![image](https://user-images.githubusercontent.com/49396421/92293625-8c1b1600-ef57-11ea-8c72-e103965a6827.png)

解决了，谢谢~
