### ISSUE TITLE
4K视频无法导出下载

### ISSUE THREAD

**Issue by Shi-Guang-0901** [the1812/Bilibili-Evolved#908]
**关于哪一项功能**
视频下载

**问题描述**

下载页无法点击IDM，aria2以及aria2 RPC里面的开始下载按钮，
       点击后提示“4K视频不支持直接下载, 请使用下方的导出选项.”
但是直接点击直接下载下面的开始按钮可以下载
**脚本版本**

1.10.36

**浏览器版本**

Microsoft Edge 
版本 85.0.564.44

**错误信息**

开发者为何要加这一段代码？版权规避吗？
“if(s.quality===120){Toast.info("4K视频不支持直接下载, 请使用下方的导出选项.","下载视频",5e3);return}”
我把注释了就能下载了

**附加截图**

**Comment by the1812** [comment]
放错位置了... 应该放在直接下载那一块的

**Comment by the1812** [comment]
直接下载下4K经常挂, 所以想封掉4K直接下载
