### ISSUE TITLE
简化首页的极简模式中，热门视频都是固定的、没变化过

### ISSUE THREAD

**Issue by LyuDun** [the1812/Bilibili-Evolved#909]
**关于哪一项功能**
    简化首页的极简模式中，热门视频都是固定的视频，没有变过。

**问题描述**

好几个版本中，极简模式的热门视频，今日、三日、一周的热门视频，都没变过，都是固定的视频。

**脚本版本**

V1.0.30

**浏览器版本**

edge  版本：85.0.564.41

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
那你倒是更新一下啊

**Comment by the1812** [comment]
是我忘改了（怎么现在才有人发现
