### ISSUE TITLE
当日已投币数量不显示

### ISSUE THREAD

**Issue by solitary-sails** [the1812/Bilibili-Evolved#910]
尚不确定是不是bug，就是打开视频后投币。在显示今日从投币中获得的经验时，始终显示为（0/50）

**Comment by the1812** [comment]
这是b站的bug吧  我关了脚本投了个币也是这样
![image](https://user-images.githubusercontent.com/26504152/92304978-805e3c80-efb5-11ea-8ec8-0781acd4d8ca.png)

**Comment by solitary-sails** [comment]
哦哦。好滴，谢谢大大
