### ISSUE TITLE
哔哩哔哩音乐歌单／音频网址参数清理

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#913]
**关于哪一项功能**
网址参数清理

**期望的效果**
- 哔哩哔哩音乐首页打开的歌单网址又多了个 `?type=2` 参数
- https://github.com/the1812/Bilibili-Evolved/issues/913#issuecomment-726737084 ：UP 主音频投稿动态打开音频会有一个 `?type=7` 参数

**脚本版本**
正式版 v1.10.36

**Comment by the1812** [comment]
type这名字太广泛了, 感觉清理了会炸掉其他用到type的页面

**Comment by Geeyun-JY3** [comment]
> type这名字太广泛了, 感觉清理了会炸掉其他用到type的页面

那就针对歌单页适配？（这个参数真是莫名其妙🤦‍♂️

**Comment by Geeyun-JY3** [comment]
消息中心现在会展示弹幕点赞通知，提醒 `网址参数清理` 功能跟进，这里给个例子（暂未发现从消息中心跳转过去之后会跳转至被点赞弹幕对应时间戳）：`https://www.bilibili.com/video/BV1Y4411M7Ac?dm_progress=19669&cid=97130146&dmid=29164232841363463`

**Comment by the1812** [comment]
那个可能现在只有手机上支持

**Comment by Geeyun-JY3** [comment]
> 那个可能现在只有手机上支持

但网页端的确收到了通知（手机上确实会跳到对应分 P）。或者再观察一段时间吧

**Comment by Geeyun-JY3** [comment]
UP 投稿动态打开音频会有 `?type=7`参数，要不也清了吧
