### ISSUE TITLE
pc端 视频点击收藏夹按钮之后登陆状态也会提示需要登陆 

### ISSUE THREAD

**Issue by dmcyer** [the1812/Bilibili-Evolved#917]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by dmcyer** [comment]
关于哪一项功能
添加收藏
问题描述
在任意一个视频中，点击收藏夹按钮后，会提示你需要登陆，即使你登陆了也一样会提示。
脚本版本
1.10.12
浏览器版本
Chromium 74.0.3729.169
错误信息
![image](https://user-images.githubusercontent.com/35415011/93225332-ab5e4280-f7a4-11ea-8e7c-2ba4a7e5836a.png)

附加截图

**Comment by the1812** [comment]
更新下脚本试试?
