### ISSUE TITLE
多p视频倍速显示问题

### ISSUE THREAD

**Issue by CyberTNT** [the1812/Bilibili-Evolved#918]
**关于哪一项功能**
多p视频的倍速显示

**问题描述**
在多p视频中，如果选择了多倍速，在下一p会记住并显示所选的倍速，但此时视频的真正的倍速为1倍速

**脚本版本**
1.10.36

**浏览器版本**
Edge Beta 85.0.564.44

**错误信息**
**附加截图**

**Comment by CKylinMC** [comment]
Chrome 85.0.4183.83 有一样的问题

**Comment by the1812** [comment]
这应该是开了`默认播放速度`导致的, 用b站的播放器选择2倍, 下一P会继承2倍, 但是又被`默认播放速度`设回1了

**Comment by CyberTNT** [comment]
用新版试了一下大致正常了，只是打开第一次打开并设置/关闭**默认播放速度**时可能要刷新网页/点击下一P1~2次才能生效，而且打开**默认播放速度**并设置2倍速生效后播放器还是显示1倍速

**Comment by the1812** [comment]
播放器的倍速显示不好改 按照实际速度为准就行 也可以参考`快捷键扩展`修改倍速时的显示 那里是准确的

**Comment by CyberTNT** [comment]
好吧，那issue我就关了
