### ISSUE TITLE
选集列表滚动条跟随相关设置

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#919]
**关于哪一项功能**
选集列表

**期望的效果**
选集列表滚动条跟随相关设置，即未开启 `展开选集列表` 功能时选集列表滚动条跟随 `使用细滚动条` 设置项，夜间模式时也使用细滚动条。

**脚本版本**
正式版 v1.10.36

**Comment by the1812** [comment]
那玩意我也不知道怎么回事 设不了滚动条
`展开选集列表`当时就是因为这个而诞生的

**Comment by Geeyun-JY3** [comment]
> `展开选集列表`当时就是因为这个而诞生的(为了夜间不看到那个默认的滚动条)

怪我偷懒没先搜索 issue，看到 #229 了。
那有可能实现类似 https://github.com/the1812/Bilibili-Evolved/issues/837#issuecomment-673319457 提到的这个样式的效果吗？这个样式是可以让选集列表的滚动条也变黑的，就是细不了。

**Comment by Geeyun-JY3** [comment]
诶不对劲。在关闭 `展开选集列表` 功能的情况下先后开关一次该功能滚动条就会变成细的滚动条了（夜间模式下），但刷新后就没了。

**Comment by Geeyun-JY3** [comment]
在 Chrome 85.0.4183.83 测试了一下好像没这个问题，应该是我浏览器内核底的问题了。打扰了

**Comment by the1812** [comment]
就是这个奇怪的现象  明明代码已经指定滚动条样式了 就是没效果
删了那个样式再ctrl+z居然都能起效

**Comment by Geeyun-JY3** [comment]
@the1812 我这边 Chrome 85.0.4183.83 是没这个问题了。不知你那边如何？

**Comment by the1812** [comment]
我跟你的一样版本 没这个问题

**Comment by Geeyun-JY3** [comment]
那应该是内核的问题了，我这边 Chromium 80.0.3987.163 就还会有这个问题。

**Comment by the1812** [comment]
居然是直到最近才修复的吗(当时Chrome才60多的

**Comment by Geeyun-JY3** [comment]
刚刚再排查了一下其它脚本，基本上可以确认是内核的问题了。
