### ISSUE TITLE
清爽模式首页分区栏拖动排序时出现拖一个乱一片问题

### ISSUE THREAD

**Issue by azbhg1** [the1812/Bilibili-Evolved#920]
**关于哪一项功能**
清爽模式首页分区栏排序功能

**问题描述**

清爽模式首页分区栏拖动排序时出现拖一个乱一片问题

**脚本版本**

v1.10.36
内容包: c2c7501

**浏览器版本**

Microsoft Edge 
版本 85.0.564.44 (官方内部版本) (64 位)

**错误信息**

**附加截图**
![](https://p.sda1.dev/0/54e8ed32b42e7f8b8bdefbec226c2e07/msedge_AHJ6o4RWrQ.png)

**Comment by Geeyun-JY3** [comment]
别的不清楚，我这边任何插件脚本都不开，将「直播」拖到最后一个然后刷新，就会乱一片 ~~（其实也就后面几个）~~，好像 b 站自己这里就有 bug。

**Comment by the1812** [comment]
应该是一些新分区加进来后乱掉的, 他们打破了原有的顺序表

**Comment by azbhg1** [comment]
> 别的不清楚，我这边任何插件脚本都不开，将「直播」拖到最后一个然后刷新，就会乱一片 ~（其实也就后面几个）~，好像 b 站自己这里就有 bug。

草，原来分区排序是B站自带的？

**Comment by azbhg1** [comment]
> 应该是一些新分区加进来后乱掉的, 他们打破了原有的顺序表

请问通过插件有办法解决嘛？

**Comment by Geeyun-JY3** [comment]
> 草，原来分区排序是B站自带的？

？？？ 对啊本身就可以排序的鸭，但我不清楚 `简化首页` 是怎么实现的。

**Comment by the1812** [comment]
简化首页是我自己写的  后来忘记处理新加的分区了
