### ISSUE TITLE
弹幕下载好用potplayer|vlc打开都是堆叠在最上面一行

### ISSUE THREAD

**Issue by zheyiyuezhuo** [the1812/Bilibili-Evolved#921]
**关于哪一项功能**
弹幕下载

**问题描述**

测试了两个视频，弹幕用potplayer和vlc打开都是全部显示在第一行，堆叠在一起。
av62003379
av925691848

**脚本版本**

预览版1.10.36和正式版1.10.36

**浏览器版本**

Chrome85.0.4183.83

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/46232425/92448263-ef70a680-f1ea-11ea-8df2-98ff62c2aeee.png)

**Comment by zheyiyuezhuo** [comment]
下载的ass弹幕如下
Dialogue: 0,0:00:00.00,0:00:12.00,Medium,,0,0,0,,{\move(1945.9999999999998,30,-26,30,0,12000)}hh
Dialogue: 0,0:00:00.00,0:00:12.00,Medium,,0,0,0,,{\move(1932.9999999999998,30,-13,30,0,12000)}1
Dialogue: 0,0:00:00.00,0:00:12.00,Medium,,0,0,0,,{\move(1945.9999999999998,30,-26,30,0,12000)}号
Dialogue: 0,0:00:00.00,0:00:12.00,Medium,,0,0,0,,{\move(1971.9999999999998,30,-52,30,0,12000)}来了

**Comment by the1812** [comment]
检查下字幕设置?
![image](https://user-images.githubusercontent.com/26504152/92590458-db05da00-f2ce-11ea-9546-133ac29173a7.png)

**Comment by zheyiyuezhuo** [comment]
potplayer上刚刚看了下设置没问题，另外也用过vlc同样只有最上面一排，（用过另一个插件，那个显示正常）另现在用批量导出xml的字幕，然后手动转换成ass的，这样就没问题了

> 检查下字幕设置?
> ![image](https://user-images.githubusercontent.com/26504152/92590458-db05da00-f2ce-11ea-9546-133ac29173a7.png)

potplayer上刚刚看了下设置没问题，另外也用过vlc同样只有最上面一排，（用过另一个插件，那个显示正常）另现在用批量导出xml的字幕，然后手动转换成ass的，这样就没问题了

**Comment by the1812** [comment]
应该是我的ass转换器有问题

**Comment by pickmefly** [comment]
> 应该是我的ass转换器有问题

之前的版本还是正常的

**Comment by Youmio** [comment]
请问这个问题啥时候能解决呀，我这个月下载视频发现也是有同样的问题，全部挤在一起了

**Comment by zheyiyuezhuo** [comment]
> 请问这个问题啥时候能解决呀，我这个月下载视频发现也是有同样的问题，全部挤在一起了

暂时可以下载xml弹幕，然后手动xml转ass，暂时用一下，等作者后续更新吧，我用的是DanmakuFactory，github上搜就好了
