### ISSUE TITLE
下载视频 - aria2 RPC 对话框，无法关闭

### ISSUE THREAD

**Issue by yfdyh000** [the1812/Bilibili-Evolved#922]
**关于哪一项功能**

下载视频 - aria2 RPC，没有关闭按钮，只能刷新页面来取消。“下载视频”的关闭按钮，不能解除RPC对话框的打开状态。

**期望的效果**
关闭按钮。允许RPC面板打开后反悔，改用其他下载视频功能。

**脚本版本**
Stable v1.10.36
内容包: eae5a0c

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/92560285-ba288f00-f2a4-11ea-902c-56e26d2caa9f.png)

**Comment by yfdyh000** [comment]
这……很隐蔽😅
关闭按钮应该在新对话框的底边或右上/左上，原位置关闭真没想到，它也不像一个开关按钮（如有凸起/按下效果）或者扩展面板（边框对齐）。
如果只看图，我认为这是一个可能被遮蔽（分辨率/拖拽窗口）的上一对话框的按钮，虽然并未遮蔽。

**Comment by the1812** [comment]
能看得到开始下载, 为什么会看不到取消呢, 明明距离如此相近
而且点开的时候也应该会察觉到这个按钮的文字突变

**Comment by yfdyh000** [comment]
> 能看得到开始下载, 为什么会看不到取消呢, 明明距离如此相近
> 而且点开的时候也应该会察觉到这个按钮的文字突变

真的从没看到过……心中假定“关闭”应该在右上（x）或者右下并排（按钮），以及想过“保存配置”或许会自动关闭对话框。
点击后注意力就被大的对话框吸引走了。鼠标松开才会变，注意力已经转移。
以及上面提过的窗口化概念，不曾想关闭按钮放在被大幅遮挡的窗口上。

**Comment by the1812** [comment]
....现在你找到了就好
