### ISSUE TITLE
自动播放相关推荐的第一个视频

### ISSUE THREAD

**Issue by robert4213** [the1812/Bilibili-Evolved#923]
**关于哪一项功能**

当前视频播放结束后，自动播放相关推荐的第一个视频，类似youtube播放完之后会自动跳转至下一个视频。

**期望的效果**
1. 当前视频播放结束后，自动播放相关推荐的第一个视频。
2. 有一个按钮能控制该功能，默认关闭。开启后，跳转至下一个视频仍会继承自动播放的状态。

**脚本版本**
Stable v1.10.36

**Comment by doexee** [comment]
同样需要这个功能。

**Comment by the1812** [comment]
b站官方已经在灰度中了, 再等段时间估计就有了
![image](https://user-images.githubusercontent.com/26504152/99959933-e09b9800-2dc6-11eb-9e37-824663621133.png)

**Comment by doexee** [comment]
@the1812 好的，非常感谢您的回复。
