### ISSUE TITLE
增加按键位置调整的功能

### ISSUE THREAD

**Issue by yu4618** [the1812/Bilibili-Evolved#925]
**脚本版本**
Stable v1.10.36

1.希望增加左侧两个按键位置调整的功能，因为我有使用一个计时器的脚本，这个脚本的按键和本脚本位置产生了冲突。
这是计时器脚本的链接供测试使用：https://greasyfork.org/zh-CN/scripts/372673-%E8%AE%A1%E6%97%B6%E5%99%A8%E6%8E%8C%E6%8E%A7%E8%80%85-%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E8%B7%B3%E8%BF%87-%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A%E5%8A%A0%E9%80%9F%E5%99%A8

2.疑问：B站两三个P的视频，怎样才能下载第二集、第三集呢？

**Comment by Coulomb-G** [comment]
1:这功能难道没有吗?
2:批量下载功能不也有吗?

**Comment by yu4618** [comment]
1.解决了，不太熟悉设置。
2.原来是批量下载啊。建议访问 https://www.bilibili.com/video/BVXXXXXXXXX?p=2 时，直接默认下载P2而不是P1。

**Comment by the1812** [comment]
默认就是P2

**Comment by yu4618** [comment]
> 默认就是P2
原来是我把视频封面下载下来了，看上去像P1导致的

因为我平时用的youtube-dl下载B站没碰到过会下载视频封面的情况，是我大意了。

尴尬.jpg
