### ISSUE TITLE
新版创作团队适配、视频标签夜间模式适配

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#926]
**关于哪一项功能**
夜间模式

**问题描述**
网页端创作团队的展示方式改了，改成和客户端有点像的形式，夜间模式的适配有点问题，看下附图 1。
不知道b站在想什么，明明之前那个方案就挺好挺符合原风格的，现在这么一改展示的信息量又少了。（但愿这是在灰度测试吧

视频下方第三个开始的非频道标签夜间模式未适配，见下附图 2。

**脚本版本**
正式版 v1.10.36
预览离线版 783.99

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 85.0.4183.83（正式版本） （64 位）

**错误信息**

**附加截图**
附图 1：
![image](https://user-images.githubusercontent.com/49396421/92729521-0a871600-f3a5-11ea-8c2f-b27ba6e5f966.gif)

附图 2：
![image](https://user-images.githubusercontent.com/49396421/92729588-225e9a00-f3a5-11ea-9600-3232f924ccc2.png)

**Comment by Geeyun-JY3** [comment]
原来夜间模式没问题的两个标签是分区，一时间还没发现：
![分区](https://user-images.githubusercontent.com/49396421/93099492-a5039400-f6da-11ea-898f-8028d7f05d74.gif)
是最近网页端普通视频播放页面 [取消了视频分区信息的显示](https://t.bilibili.com/434850728462022495) 后的暂时解决方案，详见 [此文](https://www.bilibili.com/read/cv7230899) 第二十点。我去问客服得到的答复。
客服原话：
> 我们暂时将分区信息合并在播放器下方标签/tag区域展示。您将鼠标悬浮至标签/tag上方时，未出现删除/举报面板的分别是一二级分区。

![image](https://user-images.githubusercontent.com/49396421/93098668-b5ffd580-f6d9-11ea-9e9a-c8089b86243b.png)
***
顺便提醒 `消息中心 > 回复我的` 的 `发表评论` 按钮主题色掉了：
![image](https://user-images.githubusercontent.com/49396421/93100414-b5683e80-f6db-11ea-99e9-e9bfca4b4a27.png)

**Comment by Geeyun-JY3** [comment]
提醒一下 https://github.com/the1812/Bilibili-Evolved/issues/731#issuecomment-687625261 最后提到的两个互动视频相关的夜间模式适配 bug 或主题颜色未适配，主要是看到最近适配了互动视频的对话框，但实际效果有些问题。

**Comment by Geeyun-JY3** [comment]
新版创作团队（联合投稿）没适配是打算再观察👀一段时间还是怎样？

**Comment by the1812** [comment]
不是适配了吗

**Comment by Geeyun-JY3** [comment]
没有啊
![image](https://user-images.githubusercontent.com/49396421/93665966-0f3a8100-faad-11ea-969d-18c5ce0debb9.png)

**Comment by the1812** [comment]
清下缓存?
![image](https://user-images.githubusercontent.com/26504152/93666071-b7504a00-faad-11ea-9bf0-5292fcd96385.png)

**Comment by Geeyun-JY3** [comment]
> 清下缓存

解决了🤦‍♂️

**Comment by Geeyun-JY3** [comment]
@the1812 [上面提到](https://github.com/the1812/Bilibili-Evolved/issues/926#issuecomment-692105853) 的 `发表评论` 按钮主题色是不是忘了🌚

**Comment by the1812** [comment]
> @the1812 [上面提到](https://github.com/the1812/Bilibili-Evolved/issues/926#issuecomment-692105853) 的 `发表评论` 按钮主题色是不是忘了🌚

写夜间的老哥又开学了(
