### ISSUE TITLE
逐帧调整在视频末尾处无法正常地起作用

### ISSUE THREAD

**Issue by Yanstory** [the1812/Bilibili-Evolved#928]
**关于哪一项功能**
视频 - 启用逐帧调整

**问题描述**
任何一个支持助阵调整的视频里，当视频进度（包括通过逐帧调整功能跳转到的进度）达到视频的末尾几秒部分时，逐帧调整功能会无法正常跳帧（例如画面完全不动、【该部分进度条所在位置的实际画面】和【跳帧到这里后的画面】完全不符等）

> [测试视频](https://www.bilibili.com/video/av839609392)，测试目标：视频结尾一闪而过的二维码
结果：无法通过逐帧调整定位到该帧

**脚本版本**
Stable v1.10.36

**浏览器版本**
Chrome 80

**错误信息**
无错误信息

**附加截图**
无截图

**Comment by the1812** [comment]
偶尔是会这样的, 这时候就得靠你的暂停技术了(
![image](https://user-images.githubusercontent.com/26504152/93104580-9f10b180-f6e0-11ea-8e07-66071ed914de.png)
