### ISSUE TITLE
动态栏优化

### ISSUE THREAD

**Issue by YU0813** [the1812/Bilibili-Evolved#929]
感谢作者大大的优化，功能特色都很满意，但是在使用过程中，比如鼠标指向动态时，下拉内容右侧没有滚轮以持续性阅读或选择，希望改善这一栏目。

**脚本版本**
最新版1.10.36

**Comment by Coulomb-G** [comment]
你的鼠标都移动过去了,那鼠标的滚轮难道用不了?

**Comment by YU0813** [comment]
> 你的鼠标都移动过去了，那鼠标的滚轮难道用不了吗？

没有鼠标呢 只有触摸板呢

**Comment by Coulomb-G** [comment]
触摸板更简单啊,直接两根手指滑动就可以了

**Comment by YU0813** [comment]
> 触摸板更简单啊，直接两根手指滑动就可以了

卧槽 学会了大佬 我就是个小白 感谢感谢
