### ISSUE TITLE
脚本导致的浏览器崩溃问题

### ISSUE THREAD

**Issue by RainEffect** [the1812/Bilibili-Evolved#93]
原因未明确！待测试后在回复中补充！

BUG触发点：设置>视频>使用默认播放器样式...

![image](https://user-images.githubusercontent.com/14258727/54777637-b686ef80-4c4d-11e9-91e6-a033c5cb876f.png)
等待处显示是因为崩溃时会频繁闪烁，且电脑进入卡顿状态，我没办法进行GIF截图。
![image](https://user-images.githubusercontent.com/14258727/54777652-c0a8ee00-4c4d-11e9-951d-ffd2a03e0597.png)

**Comment by RainEffect** [comment]
多次测试下依然未明确原因。。。但BUG仍在。。。并非经常会触发的问题。。。

这里先贴上我的系统信息
windows系统: Windows 7 x64
OS版本: 6.1.7601 Service Pack 1 Build 7601
360安全浏览器版本: 10.0.1698.0
Chrome版本: 63.0.3239.132

**Comment by the1812** [comment]
不应该啊... 默认播放器模式里也没什么东西可能死循环的
原版Chrome会这样吗?

**Comment by RainEffect** [comment]
![image](https://user-images.githubusercontent.com/14258727/55375671-a3262f00-553f-11e9-8352-7b9e98c0ee46.png)
在和群员的一阵“激烈讨论”下，我了解了BUG的触发向相关方式！
在开启多个页面的时候，如果快速地重复开关某项功能，就会触发，然后浏览器崩溃。。。

(以下为个人猜测原因：多页面同步)
单次激活
页面A: 我开了！(丢给页面B)
页面A: 我关了！(丢给页面B)
页面B: 收到！我也开了！(丢给页面A)
页面B: 收到！我也关了！(丢给页面A)
。。。。。。
死循环诞生。

**Comment by the1812** [comment]
我把多标签页同步去掉了, 现在应该不会死循环了
