### ISSUE TITLE
禁止动态跳转详情在转发类动态的被转发动态失效时会失效

### ISSUE THREAD

**Issue by wsw296578532** [the1812/Bilibili-Evolved#931]
**关于哪一项功能**
禁止动态跳转详情

**问题描述**

https://t.bilibili.com/433713159126909433?tab=2 可以进入这个UP的空间的动态页重现问题，和我的动态页面效果相同。

**脚本版本**

正式版1.10.36

**浏览器版本**

Chrome 80（百分浏览器4.2.10.171）

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
像转发的直播结束了的动态也是一样的

**Comment by Geeyun-JY3** [comment]
`快速收起动态评论区` 和 `动态链接复制` 在此类动态下也是失效的，右上角更多菜单里也没有 `导出图片` 选项（虽然这功能在这种动态里本来就没什么用）
不知道 `展开动态内容` 是否失效，暂时找不到相应动态进行测试。
