### ISSUE TITLE
同时选择“夜间模式跟随系统”和“夜间模式计划时段”可能会出现问题

### ISSUE THREAD

**Issue by shenzhiming88** [the1812/Bilibili-Evolved#932]
**关于哪一项功能**
“夜间模式跟随系统”和“夜间模式计划时段”

**问题描述**

同时打开“夜间模式跟随系统”和“夜间模式计划时段”，在系统为非深色模式下且处于计划时间内时，就会出现“夜间模式”——“非夜间模式”——“夜间模式”的变化，十分难受

**脚本版本**

Stable v1.10.36

**浏览器版本**

Microsoft Edge 是最新版本。
版本 85.0.564.51 (官方内部版本) (64 位)

**错误信息**

无需

**附加截图**
https://cowtransfer.com/s/69c3720687df40

**Comment by the1812** [comment]
所以你为什么要同时开这两个

**Comment by Geeyun-JY3** [comment]
> 所以你为什么要同时开这两个

说不定 ta 既要跟随系统，又想在系统为浅色主题的某个时段也开夜间模式🌚

**Comment by the1812** [comment]
跟随系统就是确保和系统一致啊 发现开了夜间就关掉

**Comment by Geeyun-JY3** [comment]
> 跟随系统就是确保和系统一致啊 浅色系统发现开了夜间就关掉

我的猜测逻辑确实有问题🙈
