### ISSUE TITLE
下载视频--批量导出。下载文件名无法获取

### ISSUE THREAD

**Issue by okhuazai1011** [the1812/Bilibili-Evolved#933]
**关于哪一项功能**

**问题描述**
下载视频--批量导出。下载文件名无法获取（比如文件名是：P1 课时01-课程介绍。导入IDM文件名是：186783422-1-80.flv）

**脚本版本**
Stable v1.10.36

**浏览器版本**
Chrome 版本 72.0.3626.109（正式版本） （64 位）

IDM版本：
6.33

**错误信息**
无

**附加截图**
![image](https://user-images.githubusercontent.com/51896383/92983912-01976100-f4d9-11ea-8521-84819baa0fa5.png)
![image](https://user-images.githubusercontent.com/51896383/92983934-1673f480-f4d9-11ea-8d3a-ac22e9c634a2.png)

**Comment by the1812** [comment]
IDM就是不支持文件名的
