### ISSUE TITLE
关于更新后怎么快速选择下载多p视频

### ISSUE THREAD

**Issue by linwan623910** [the1812/Bilibili-Evolved#934]
v1.10.36之后，禁止批量导出32集以上的数量，可问题是：

我有一个教程有200集
默认打开下载页面能选中1-32集
下载完了后，我想下载33-64集，只能手动点32下（很浪费时间），后续是否考虑增加其他方法快速选中呢？
如：支持shift选择，或提供输入框我直接输入「33-64」？

**Comment by the1812** [comment]
嗯..应该支持下shift选择

**Comment by linwan623910** [comment]
期待中！
