### ISSUE TITLE
佩戴勋章失败. 错误码:65531 

### ISSUE THREAD

**Issue by GONGCHEN1003** [the1812/Bilibili-Evolved#935]
**关于哪一项功能**
直播间自动切换勋章

**问题描述**

任何有勋章的直播间都会报错

**脚本版本**

Stable v1.10.36
内容包: 515229d

**浏览器版本**

Chrome 80

**错误信息**

佩戴勋章失败. 错误码:65531 

**附加截图**

**Comment by stelllnoob** [comment]
一样的问题，勋章太多了，急需这个功能修复

**Comment by Zothany** [comment]
DD很着急！另外，手动从附加功能里选择牌子也会失败，一样的错误代码。

**Comment by Malus-Mill** [comment]
是勋章切换的API又改了，等吧
