### ISSUE TITLE
请求增加功能

### ISSUE THREAD

**Issue by PPPPPPP89898** [the1812/Bilibili-Evolved#936]
**关于主站分区列表**

**期望的效果**
重新回到以前的分区即可。没广告区很伤
不知道什么原因两个月前更新后就没了

**脚本版本**

**Comment by Geeyun-JY3** [comment]
官方 [调整分区](https://www.bilibili.com/read/cv5964996) 能有什么办法啊？[广告区入口](https://www.bilibili.com/v/ad/ad/) 都已经 404 了，稿件也已经转移了分区。

**Comment by PPPPPPP89898** [comment]
哭泣..... 广告区真的好看。 比抖音好多了。 那段时间的排行榜 我天天都看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Geeyun-JY3"<notifications@github.com&gt;; 
发送时间: 2020年9月13日(星期天) 上午9:38
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "Ash Lynx"<894848678@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 请求增加功能 (#936)





 
官方 调整分区 能有什么办法啊？广告区入口 都已经 404 了，稿件也已经转移了分区。

**Comment by the1812** [comment]
我们可不是时间机器...

**Comment by PPPPPPP89898** [comment]
网页部分


一直自动刷新。关了插件之后才好的。&nbsp;




视频部分
不自动刷新之后
有些是能正常使用 有些不行

**Comment by the1812** [comment]
看置顶..

**Comment by PPPPPPP89898** [comment]
你好。我这边下载不了&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Grant Howard"<notifications@github.com&gt;; 
发送时间: 2020年9月24日(星期四) 晚上6:36
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "Ash Lynx"<894848678@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 请求增加功能 (#936)





 
看置顶..

**Comment by Coulomb-G** [comment]
下载不了就只能等之后更新了

**Comment by PPPPPPP89898** [comment]
你好。已更新至最新版本。视频依旧是（有）重新启动的状态。有做过笔记的和快速收藏的才会。单独的话不清楚。外加是连续剧系列。就是拥有视频系列的系列视频
WIN10系统。 EDGE 浏览器&nbsp;

**Comment by the1812** [comment]
我说看置顶是指看这个 https://github.com/the1812/Bilibili-Evolved/issues/883

**Comment by PPPPPPP89898** [comment]
查看883，是用视频系列去操作吗。刷新导致一直无法进行。非系列视频的话。又没有你图上面的操作

**Comment by the1812** [comment]
不是啊 里面不是写了吗 关掉网址av号转换就行

**Comment by PPPPPPP89898** [comment]
是我卡了吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 上午10:07
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"Ash Lynx"<894848678@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 请求增加功能 (#936)





 
不是啊 里面不是写了吗 关掉网址av号转换就行

**Comment by PPPPPPP89898** [comment]
为什么我打Filter没有你那样的？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月26日(星期六) 晚上9:35
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"Ash Lynx"<894848678@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 请求增加功能 (#936)





 
我说看置顶是指看这个 #883

**Comment by the1812** [comment]
什么Filter?  关掉av号转换不就好了吗

**Comment by PPPPPPP89898** [comment]
.......那个图片不是攻略吗。。。。 我不会这个我照着图片弄的。 我想还有更多人不会的弄这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Grant Howard"<notifications@github.com&gt;; 
发送时间: 2020年9月29日(星期二) 中午11:47
收件人: "the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;; 
抄送: "Ash Lynx"<894848678@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the1812/Bilibili-Evolved] 请求增加功能 (#936)





 
什么Filter?  关掉av号转换不就好了吗

**Comment by PPPPPPP89898** [comment]
拜托教教不会的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the1812/Bilibili-Evolved"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月29日(星期二) 中午11:47
收件人:&nbsp;"the1812/Bilibili-Evolved"<Bilibili-Evolved@noreply.github.com&gt;;
抄送:&nbsp;"Ash Lynx"<894848678@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [the1812/Bilibili-Evolved] 请求增加功能 (#936)





 
什么Filter?  关掉av号转换不就好了吗

**Comment by Geeyun-JY3** [comment]
> .......那个图片不是攻略吗。。。。 我不会这个我照着图片弄的。 我想还有更多人不会的弄这个

@PPPPPPP89898 你不会是看着[原 issue](https://github.com/the1812/Bilibili-Evolved/issues/883#issue-686885120) 一开始的截图操作了吧。。。那是人家的反馈截图。

你得看下面的讨论串啊。。。

**Comment by the1812** [comment]
(我感觉我在跨服聊天了...
