### ISSUE TITLE
希望能屏蔽/隐藏动态右边的话题，谢谢！

### ISSUE THREAD

**Issue by KOHAKUchan** [the1812/Bilibili-Evolved#937]
**关于哪一项功能**

**期望的效果**

**脚本版本**

**Comment by Coulomb-G** [comment]
这功能一直都有，叫「动态过滤器」

**Comment by KOHAKUchan** [comment]
当时开了但是不出来，刚才点了下强制固定顶栏和侧栏就出来了，已解决（版本Preview Offline788.22）
