### ISSUE TITLE
按 Wiki 使用旧版 指引无法安装旧版

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#938]
按 Wiki [使用旧版](https://github.com/the1812/Bilibili-Evolved/wiki/使用旧版) 指引操作安装的还是最新的离线版脚本。

安装旧版应该点击上方的 `.js` 文件再点击 `View raw`？
![image](https://user-images.githubusercontent.com/49396421/93008550-9fa62c80-f5a8-11ea-8dd7-6088d567813f.png)

**Comment by the1812** [comment]
对的  我也忘了以前为什么写安离线版了

**Comment by Geeyun-JY3** [comment]
![image](https://user-images.githubusercontent.com/49396421/93009212-5f4aac80-f5b0-11ea-80d5-641fb31f8c4f.png)
这两个表格的链接都是链接到最新版的对吧

**Comment by the1812** [comment]
对

**Comment by the1812** [comment]
能访问GitHub Raw的话, 可以用 `https://github.com/the1812/Bilibili-Evolved/raw/{{版本号}}/bilibili-evolved.preview-offline.user.js` 安装, `{{版本号}}`可以换成`v1.10.12`之类的

**Comment by Geeyun-JY3** [comment]
Wiki 改一下吧😉
