### ISSUE TITLE
安装脚本无效，跟没安一样

### ISSUE THREAD

**Issue by kinowhunt** [the1812/Bilibili-Evolved#94]
`VM1074:64 Syntax error @ "Bilibili Evolved"!
##########################
JSHINT output:
##########################

SyntaxError: Unexpected token <
    at new Function (<anonymous>)
    at Object.E_c (<anonymous>:3:308)
    at ia (eval at exec_fn (:1:107), <anonymous>:63:272)
    at Object.create (eval at exec_fn (:1:107), <anonymous>:75:51)
    at c (eval at exec_fn (:1:107), <anonymous>:16:273)
    at Object.run (eval at exec_fn (:1:107), <anonymous>:16:387)
    at eval (eval at exec_fn (:1:107), <anonymous>:76:339)
    at Array.forEach (<anonymous>)
    at <anonymous>:2:494
    at b (<anonymous>:1:414)
(anonymous) @ VM1074:64
(anonymous) @ VM1074:25
y @ VM984:9
W @ VM984:9
e @ content.js:6
(anonymous) @ content.js:7
sendResponseAndClearCallback @ VM980 extensions::messaging:419
messageListener @ VM980 extensions::messaging:451
EventImpl.dispatchToListener @ VM973 extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ VM979 extensions::utils:138
EventImpl.dispatch_ @ VM973 extensions::event_bindings:387
EventImpl.dispatch @ VM973 extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ VM979 extensions::utils:138
dispatchOnMessage @ VM980 extensions::messaging:392
VM1074:64 Uncaught SyntaxError: Unexpected token <
    at new Function (<anonymous>)
    at Object.E_c (<anonymous>:3:308)
    at ia (eval at exec_fn (av42596764?spm_id_from=333.334.b_62696c695f64616e6365.11:1), <anonymous>:63:272)
    at Object.create (eval at exec_fn (av42596764?spm_id_from=333.334.b_62696c695f64616e6365.11:1), <anonymous>:75:51)
    at c (eval at exec_fn (av42596764?spm_id_from=333.334.b_62696c695f64616e6365.11:1), <anonymous>:16:273)
    at Object.run (eval at exec_fn (av42596764?spm_id_from=333.334.b_62696c695f64616e6365.11:1), <anonymous>:16:387)
    at eval (eval at exec_fn (av42596764?spm_id_from=333.334.b_62696c695f64616e6365.11:1), <anonymous>:76:339)
    at Array.forEach (<anonymous>)
    at <anonymous>:2:494
    at b (<anonymous>:1:414)
E_c @ VM984:3
ia @ VM1074:63
create @ VM1074:75
c @ VM1074:16
run @ VM1074:16
(anonymous) @ VM1074:76
(anonymous) @ VM984:2
b @ VM984:1
(anonymous) @ VM1074:76
(anonymous) @ VM1074:76
TM_back @ VM1074:77
(anonymous) @ VM1074:77
(anonymous) @ VM984:2
exec_fn @ VM984:1
(anonymous) @ VM984:11
W @ VM984:10
setTimeout (async)
(anonymous) @ VM984:2
c.(anonymous function) @ VM984:8
(anonymous) @ VM1074:64
(anonymous) @ VM1074:25
y @ VM984:9
W @ VM984:9
e @ content.js:6
(anonymous) @ content.js:7
sendResponseAndClearCallback @ VM980 extensions::messaging:419
messageListener @ VM980 extensions::messaging:451
EventImpl.dispatchToListener @ VM973 extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ VM979 extensions::utils:138
EventImpl.dispatch_ @ VM973 extensions::event_bindings:387
EventImpl.dispatch @ VM973 extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ VM979 extensions::utils:138
dispatchOnMessage @ VM980 extensions::messaging:392
stardust-video.2d551b8a4aea821806b572b8884b5897685677d5.js:1                      //         \\         //          \\       //    ##DDDDDDDDDDDDDDDDDDDDDD##    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|    ## MMMMMMMMMMMMMMMMMMMM ##    ##MMMMMMMMMMMMMMMMMMMMMM##                             Release 2.6.1. Powered by jinkela-core 2.4.1.         \/            \/
`

**Comment by tippsie** [comment]
![微信截图_20190322095659](https://user-images.githubusercontent.com/14216490/54795965-33838a80-4c89-11e9-8e64-0b933868ff58.png)
[www.bilibili.com-1553219463399.log](https://github.com/the1812/Bilibili-Evolved/files/2994625/www.bilibili.com-1553219463399.log)

**Comment by the1812** [comment]
请问版本号是多少?

**Comment by lintmx** [comment]
@the1812 
今天上午在脚本未更新的情况下刷新一次 B 站后出现同样问题，到目前为止未恢复。

下午清除浏览器缓存并在隐身模式下只开启该拓展情况下还是出现同样情况

测试版本： 正式版 1.7.17 和 离线预览版 247.26
测试环境：macOS 10.14.3 Chrome 73.0.3683.86 (Official Build) (64-bit)

**Comment by the1812** [comment]
那就奇怪了...正式版这星期没有任何改动, 怎么突然就炸了
我这里也试不出来这种情况, Chrome 73.0.3683.86 (64-bit) / Firefox 66.0 (64-bit)

**Comment by lintmx** [comment]
这边试着重装了一下油猴后恢复正常

**Comment by tippsie** [comment]
> 这边试着重装了一下油猴后恢复正常

噗。。我也试着重装了一下油猴，正常了。。。

**Comment by the1812** [comment]
难道是Chrome那个bug, 我遇到过几次, 好几个扩展都异常运行, 在扩展管理里禁用再启用就好了

**Comment by lintmx** [comment]
> 难道是Chrome那个bug, 我遇到过几次, 好几个扩展都异常运行, 在扩展管理里禁用再启用就好了

不清楚，主要测试时油猴其他脚本都运行正常，所以开始就没有怀疑油猴的问题。

**Comment by kinowhunt** [comment]
> 难道是Chrome那个bug, 我遇到过几次, 好几个扩展都异常运行, 在扩展管理里禁用再启用就好了

我试过禁用再启用，没用。只有删除再重装扩展才行。
