### ISSUE TITLE
在播放视频时无限加载成功又重新加载

### ISSUE THREAD

**Issue by bbcyz** [the1812/Bilibili-Evolved#941]
**关于哪一项功能**
播放视频

**问题描述**

    在观看某些视频时候会遇到播放器无限加载的情况    初始化  加载完成整个页面马上又重新初始化加载完成这样往复      因为整个页面不停加载重新加载   所以在反馈下方提供截图      截图遇到该问题的视频地址https://www.bilibili.com/video/av627068466

**脚本版本**

最新bate版1.0.37

**浏览器版本**

Chrome 85

**错误信息**

**附加截图**
![Snipaste_2020-09-14_18-51-26](https://user-images.githubusercontent.com/71243267/93077425-5c88ae00-f6bb-11ea-81ca-942fe6fc976f.png)

**Comment by the1812** [comment]
同#883
