### ISSUE TITLE
番剧全屏播放时逐帧调整右按钮丢失

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#943]
**关于哪一项功能**
启用逐帧调整

**问题描述**
番剧（找了个电影和综艺试了试没这问题）全屏播放时逐帧调整右按钮丢失（我百分浏览器里测试甚至两个都丢了，可能是其它插件脚本的问题）

**脚本版本**
正式版 v1.10.36
预览离线版 790.30

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 85.0.4183.102（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/49396421/93103327-12192880-f6df-11ea-97c7-9e0a5a2d233b.png)

**Comment by the1812** [comment]
应该是挤不下了

**Comment by Geeyun-JY3** [comment]
> 应该是挤不下了

啊这
有解决方法吗？

**Comment by wsw296578532** [comment]
我试了一下，我1080P24寸屏，把浏览器比例设置为150%在全屏状态下也会出现你图上这个情况。

**Comment by the1812** [comment]
@Geeyun-JY3 你屏幕最大化都挤不下吗?

**Comment by Geeyun-JY3** [comment]
> @Geeyun-JY3 你屏幕最大化都挤不下吗?

上面截图就是全屏，浏览器比例 100%，浏览器比例调小些会出来

**Comment by the1812** [comment]
应该可以装个小样式调一下 我之后写一个给你

**Comment by wsw296578532** [comment]
@Geeyun-JY3 你是不是4k屏开了150%系统缩放比例啊？

**Comment by the1812** [comment]
> @Geeyun-JY3 你是不是4k屏开了150%系统缩放比例啊？

看字体应该也是1080P的

**Comment by Geeyun-JY3** [comment]
> @Geeyun-JY3 你是不是4k屏开了150%系统缩放比例啊？

150% 是 150%，但屏真的只有 1080P

**Comment by the1812** [comment]
```js
bilibiliEvolved.installStyle({ name: 'danmakuCenterPadding', displayName: 'danmakuCenterPadding', style: `
.bilibili-player.mode-fullscreen .bilibili-player-video-control-bottom-center,
.bilibili-player.mode-webfullscreen .bilibili-player-video-control-bottom-center {
  padding: 0 12px !important;
}`})
```

**Comment by Geeyun-JY3** [comment]
> ```js
> bilibiliEvolved.installStyle({ name: 'danmakuCenterPadding', displayName: 'danmakuCenterPadding', style: `
> .bilibili-player.mode-fullscreen .bilibili-player-video-control-bottom-center,
> .bilibili-player.mode-webfullscreen .bilibili-player-video-control-bottom-center {
>   padding: 0 12px !important;
> }`})
> ```

问题解决

**Comment by Geeyun-JY3** [comment]
好像又出现这种情况了。普通视频还有左半边，番剧左右都没了。
