### ISSUE TITLE
全屏时快捷键F的逻辑

### ISSUE THREAD

**Issue by ChialeKuan** [the1812/Bilibili-Evolved#945]
web端的b站和YouTube，点击F键可以在全屏和普通模式之间切换。使用脚本之后，F只有了fullscreen的功能，不能退回到普通模式，只能使用⎋退出，对于没有实体⎋键的用户很不友好

**Comment by Coulomb-G** [comment]
F键是b站自带的快捷键,你是否还开着其他插件?我这边试了下是可以正常切换的

**Comment by ChialeKuan** [comment]
{"useDarkStyle":true,"hideBanner":false,"expandDanmakuList":false,"expandDescription":true,"watchLaterRedirect":true,"touchNavBar":false,"touchVideoPlayer":false,"customControlBackgroundOpacity":0.64,"customControlBackground":false,"darkScheduleStart":"18:00","darkScheduleEnd":"6:00","darkSchedule":false,"toast":true,"fullTweetsTitle":true,"fullPageTitle":false,"removeVideoTopMask":false,"removeLiveWatermark":true,"harunaScale":false,"removeAds":true,"showBlockedAdsTip":false,"hideTopSearch":false,"touchVideoPlayerDoubleTapControl":false,"customStyleColor":"#00A0D8","preserveRank":true,"blurBackgroundOpacity":0.382,"useDefaultPlayerMode":false,"applyPlayerModeOnPlay":true,"defaultPlayerMode":"常规","useDefaultVideoQuality":true,"defaultVideoQuality":"1080P+","useDefaultDanmakuSettings":false,"enableDanmaku":true,"rememberDanmakuSettings":false,"danmakuSettings":{"subtitlesPreserve":false,"smartMask":false},"defaultPlayerLayout":"新版","defaultBangumiLayout":"新版","skipChargeList":true,"comboLike":false,"autoLightOff":false,"useCache":true,"autoContinue":true,"allowJumpContinue":false,"deadVideoTitleProvider":"稍后再看","useBiliplusRedirect":false,"biliplusRedirect":false,"framePlayback":true,"useCommentStyle":true,"imageResolution":false,"imageResolutionScale":"auto","toastInternalError":false,"i18n":false,"i18nLanguage":"日本語","playerFocus":true,"playerFocusOffset":-10,"simplifyLiveroom":false,"simplifyLiveroomSettings":{"vip":true,"fansMedal":true,"title":true,"userLevel":true,"guard":true,"systemMessage":true,"welcomeMessage":true,"giftMessage":true,"guardPurchase":true,"giftPanel":true,"kanban":true,"userEffect":true,"eventsBanner":false,"rankList":false,"popup":false,"skin":false},"customNavbar":true,"customNavbarFill":false,"customNavbarTransparent":true,"customNavbarShadow":true,"customNavbarBlur":false,"customNavbarBlurOpacity":0.7,"customNavbarOrder":{"blank1":0,"logo":1,"category":2,"rankingLink":3,"drawingLink":4,"musicLink":5,"gamesIframe":6,"livesIframe":7,"shopLink":8,"mangaLink":9,"blank2":10,"search":11,"blank3":12,"userInfo":13,"messages":14,"activities":15,"bangumi":16,"watchlaterList":17,"favoritesList":18,"historyList":19,"upload":20,"darkMode":21},"customNavbarHidden":["blank1","musicLink","gamesIframe","darkMode","shopLink","drawingLink","upload"],"customNavbarBoundsPadding":10,"customNavbarGlobalFixed":false,"playerShadow":false,"narrowDanmaku":true,"outerWatchlater":true,"videoScreenshot":false,"hideBangumiReviews":false,"filenameFormat":"[title][ - ep]","batchFilenameFormat":"[n - ][ep]","sideBarOffset":0,"noLiveAutoplay":false,"hideHomeLive":false,"noMiniVideoAutoplay":false,"useDefaultVideoSpeed":true,"defaultVideoSpeed":"1.5","hideCategory":false,"foldComment":true,"downloadVideoDefaultDanmaku":"无","downloadVideoDefaultSubtitle":"无","aria2RpcOption":{"secretKey":"","dir":"","host":"127.0.0.1","port":"6800","method":"get","skipByDefault":false,"maxDownloadLimit":"","baseDir":""},"aria2RpcOptionSelectedProfile":"","aria2RpcOptionProfiles":[],"searchHistory":[{"count":1,"keyword":"啊吗粽","date":"2020-09-16T04:53:45.967Z"}],"seedsToCoins":true,"autoSeedsToCoins":true,"lastSeedsToCoinsDate":0,"autoDraw":false,"keymap":true,"doubleClickFullscreen":false,"doubleClickFullscreenPreventSingleClick":false,"simplifyHome":true,"simplifyHomeStyle":"清爽","minimalHomeSettings":{"showSearch":true,"backgroundImage":""},"ajaxHook":false,"scriptLoadingMode":"延后(自动)","scriptDownloadMode":"bundle","guiSettingsDockSide":"左侧","fullActivityContent":true,"feedsFilter":false,"feedsFilterPatterns":[],"feedsFilterTypes":[],"feedsSpecialFilterTypes":[],"feedsFilterSideCards":[],"activityImageSaver":false,"scriptBlockPatterns":[],"customNavbarSeasonLogo":false,"selectableColumnText":true,"downloadVideoFormat":"flv","downloadVideoDashCodec":"AVC/H.264","watchlaterExpireWarningDays":14,"superchatTranslate":false,"miniPlayerTouchMove":false,"hideBangumiSponsors":false,"hideRecommendLive":false,"hideRelatedVideos":false,"defaultMedalID":0,"autoMatchMedal":false,"customStyles":[],"simpleHomeCategoryOrders":{"anime":0,"bangumi":1,"china":2,"manga":3,"music":4,"dance":5,"game":6,"tech":7,"digital":8,"life":9,"kichiku":10,"fashion":11,"information":12,"entertainment":13,"column":14,"movie":15,"tv":16,"film":17,"documentary":18},"simpleHomeBangumiLayout":"时间表","simpleHomeWheelScroll":true,"keymapJumpSeconds":85,"urlParamsClean":true,"collapseLiveSideBar":true,"removeGameMatchModule":false,"noDarkOnMember":true,"feedsTranslate":false,"feedsTranslateProvider":"Bing","feedsTranslateLanguage":"","commentsTranslate":false,"downloadVideoQuality":120,"defaultLiveQuality":"原画","useDefaultLiveQuality":false,"recordLiveDanmaku":false,"foregroundColorMode":"自动","preserveEventBanner":false,"about":true,"bvidConvert":true,"fixedSidebars":false,"updateCdn":"jsDelivr","lastNewVersionCheck":0,"newVersionCheckInterval":21600000,"useDarkStyleAsUserStyle":false,"darkColorScheme":false,"autoHideSideBar":false,"livePip":true,"extendFeedsLive":true,"userImages":[],"playerOnTop":false,"restoreFloors":false,"quickFavorite":false,"quickFavoriteID":0,"bilibiliSimpleNewHomeCompatible":false,"preferAvUrl":false,"disableFeedsDetails":true,"elegantScrollbar":true,"danmakuSendBar":false,"watchLaterRedirectNavbar":true,"watchLaterRedirectPage":false,"showCoverBeforePlay":false,"volumeOverdrive":false,"seoJump":true,"copyFeedsLink":false,"copyCommentLink":false,"unfoldFeeds":true,"autoPlay":false,"favoritesRedirect":false,"compactLayout":false,"hideOldEntry":false,"guiSettings":true,"viewCover":true,"notifyNewVersion":true,"clearCache":true,"downloadVideo":true,"enableDashDownload":true,"downloadDanmaku":true,"downloadSubtitle":true,"downloadAudio":true,"downloadLiveRecords":true,"medalHelper":true,"playerLayout":false,"forceWide":false,"useNewStyle":false,"overrideNavBar":false,"touchVideoPlayerAnimation":false,"allNavbarFill":false,"showDeadVideoTitle":false,"blurVideoControl":false,"oldTweets":false,"customNavbarCompact":false,"watchlaterExpireWarnings":false,"latestVersionLink":"https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@master/bilibili-evolved.offline.user.js","currentVersion":"782.22","foreground":"#fff","blueImageFilter":"hue-rotate(1deg) saturate(100%)","pinkImageFilter":"hue-rotate(-147deg) saturate(145%)","brightness":"0%","filterInvert":"invert(1)"}

**Comment by ChialeKuan** [comment]
有的时候输入f键，他会定位到输入框，变成输入弹幕了；有的时候又没有问题。不知道是不是我设置的问题。

**Comment by the1812** [comment]
按enter会定位输入框
输入状态下按F当然不会退出全屏

**Comment by ChialeKuan** [comment]
明白了，多谢
