### ISSUE TITLE
用了动态过滤器后正在直播不会跟随页面下滑

### ISSUE THREAD

**Issue by rilegoule** [the1812/Bilibili-Evolved#946]
**关于哪一项功能**
动态过滤器

**问题描述**

打开动态过滤器就会出现，正常正在直播一栏会跟随页面下滑，打开动态过滤器就会固定不会跟随

**脚本版本**

1.10.36

**浏览器版本**

edge 85.0.564.51

**附加截图**

**Comment by the1812** [comment]
是会有个固定的效果, 但是直播栏的高度设置还有点问题
