### ISSUE TITLE
下载视频 手动输入提示请求被拦截

### ISSUE THREAD

**Issue by Futrime** [the1812/Bilibili-Evolved#950]
**关于哪一项功能**
视频下载

**问题描述**

如图，直接下载视频，包括显示链接都正常。

但是使用手动输入模式导出就不行了，即使只输入一个视频链接也不行。

av754507231

**脚本版本**

1.10.36

**浏览器版本**

Firefox 80

**错误信息**

在截图中

**附加截图**
![批注 2020-09-16 165413](https://user-images.githubusercontent.com/35801754/93315286-70f4b400-f83d-11ea-86c3-658a99213c3a.png)
![批注 2020-09-16 165434](https://user-images.githubusercontent.com/35801754/93315343-84078400-f83d-11ea-81c5-5f01671a70e6.png)

**Comment by Futrime** [comment]
@the1812

**Comment by the1812** [comment]
还没确认原因 找到原因后会修复的
