### ISSUE TITLE
宽屏模式很难受

### ISSUE THREAD

**Issue by paletree** [the1812/Bilibili-Evolved#955]
我经常用宽屏模式看b站，然后宽屏模式下，浏览器总是压住视频上侧的一点点，“自动定位到播放器”，对宽屏模式也不友好，希望可以调整一下

另外希望加一个默认宽屏播放的选项

**Comment by Geeyun-JY3** [comment]
[默认宽屏播放](https://github.com/the1812/Bilibili-Evolved/blob/master/features.md#视频) 有的：
![image](https://user-images.githubusercontent.com/49396421/93658926-9ae2ec00-fa72-11ea-867e-a8d9ea291003.png)

**Comment by hellohbt** [comment]
> [](url)
![image](https://user-images.githubusercontent.com/57857587/93660229-1fd40280-fa7f-11ea-997a-563815ed536d.png)

**Comment by hellohbt** [comment]
具体数值需要一点一点试。

**Comment by the1812** [comment]
本质还是 #483 的问题, 我目前无法解决
