### ISSUE TITLE
希望播放器内添加一个快进90秒的功能

### ISSUE THREAD

**Issue by duxing1996** [the1812/Bilibili-Evolved#956]
**关于哪一项功能**
视频播放
可以快速跳过op，实属实用好功能

**期望的效果**

![image](https://user-images.githubusercontent.com/68660594/93659818-ee0d6c80-fa7b-11ea-9004-7a2fa560e067.png)

**脚本版本**
 v1.10.36

**Comment by Coulomb-G** [comment]
开issue前,请先搜索关键词,这个功能已经有了

**Comment by duxing1996** [comment]
> 开issue前,请先搜索关键词,这个功能已经有了

是快捷键吧，感觉按钮更实用呢

**Comment by Coulomb-G** [comment]
按钮得占用播放器控制栏位置,目前位置对小屏幕用户是不够用的

**Comment by duxing1996** [comment]
> 按钮得占用播放器控制栏位置,目前位置对小屏幕用户是不够用的

感觉这个逐帧占用更大啊😂，而且可以设置开关选项嘛
