### ISSUE TITLE
空降弹幕失效

### ISSUE THREAD

**Issue by ThebestkillerTBK** [the1812/Bilibili-Evolved#957]
1.10.38的空降弹幕选项已打开，无法使用，无🚁，在[av78426409](https://www.bilibili.com/video/av78426409)中无任何显示，本人使用pakku插件，不知是否有关系

**Comment by ThebestkillerTBK** [comment]
关闭插件后故障依旧

**Comment by kdxcxs** [comment]
1.10.38版本测试并未失效

![screenshot.png](https://i.loli.net/2020/09/19/yonaB5AQ3sRkGHW.png)

能否麻烦你将设置导出分享出来看看是不是与项目本身的其他功能冲突？

**Comment by ThebestkillerTBK** [comment]
![Snipaste_2020-09-19_18-53-20](https://user-images.githubusercontent.com/62250232/93665485-6dfdfb80-faa9-11ea-8d10-78c21e858bed.png)

**Comment by ThebestkillerTBK** [comment]
没有

**Comment by Geeyun-JY3** [comment]
我在这个视频里反而是无论点那个空降弹幕都是暂停

**Comment by kdxcxs** [comment]
> 没有

你这个可能就是跟 pakku 冲突了，看那个截图的样子你应该是还没有关那个插件吧？


> 我在这个视频里反而是无论点击哪个空降弹幕效果都是暂停视频

有这个问题，只有在最上面那两三行的弹幕才有效，在弄了。
