### ISSUE TITLE
页面全屏的功能建议(可能无法实现)

### ISSUE THREAD

**Issue by RainEffect** [the1812/Bilibili-Evolved#96]
希望支持外部调用API下的页面全屏功能
目前原版下的API调用无法进行页面全屏。。。

仅此。
![image](https://user-images.githubusercontent.com/14258727/54885307-a7a27600-4eb5-11e9-90f4-1519694af6bb.png)

**Comment by the1812** [comment]
除非这个`<iframe>`上级的元素没有任何相对定位(`position: relative`)的, 给`<iframe>`加绝对定位才有机会铺满整个页面. 可能就是因为这一点嵌入播放器才隐藏了网页全屏按钮的?
我目前没什么想法...
