### ISSUE TITLE
`禁止跳转动态详情` 功能相关 bug

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#960]
**关于哪一项功能**
禁止跳转动态详情

**问题描述**
开启 `禁止跳转动态详情` 功能后，动态首页和个人空间动态 tab 下转发收藏夹动态中的收藏夹能看到「详情」二字的上部分。

附个可以比较快翻到相关动态的 up：https://space.bilibili.com/58729617/dynamic

**脚本版本**
正式版 v1.10.38 内容包: fb8224f
预览离线版 v795.29

**浏览器版本**
百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
Chrome 版本 85.0.4183.102（正式版本） （64 位）

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/49396421/93710230-8f2d1d80-fb77-11ea-8985-acbb139434e2.png)

**Comment by the1812** [comment]
哇 怎么还有分享收藏夹的..
当时可没考虑这种情况

**Comment by Geeyun-JY3** [comment]
才发现这个「详情」是这个功能加的🙈
