### ISSUE TITLE
顶栏的 动态 和 稍后再看 可以变成 新标签打开后不自动隐藏 的模式吗？

### ISSUE THREAD

**Issue by CodesHunger** [the1812/Bilibili-Evolved#961]
使用鼠标中键点击或右键点击新标签打开后下拉列表会隐藏，想要打开多个比较麻烦，请问可以改为不自动隐藏吗？

**Comment by the1812** [comment]
见#878

**Comment by CodesHunger** [comment]
> 见#878

换了浏览器解决了，可能旧的360极速里面缓存什么的太多了，换成了空的edge没问题了。
