### ISSUE TITLE
脚本自身的问题

### ISSUE THREAD

**Issue by SuperGik** [the1812/Bilibili-Evolved#962]
**关于哪一项功能**
脚本本身的问题

**问题描述**

脚本放在Tampermonkey上后，重启浏览器脚本会消失，在脚本存在的时间内访问bilibili也不生效

**脚本版本**

离线版616.33

**浏览器版本**

Microsoft Edge 44.17763.831.0（老版Edge）
Microsoft EdgeHTML 18.17763
Tampermonkey 4.9.5941

**错误信息**

2 HTML1300: 进行了导航。
bilibili.com (1,1)

%c
                     //
         \\         //
          \\       //
    ##DDDDDDDDDDDDDDDDDDDDDD##
    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___
    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \
    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \
    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \
    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \
    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\
    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|
    ## MMMMMMMMMMMMMMMMMMMM ##
    ##MMMMMMMMMMMMMMMMMMMMMM##                             Release 2.6.1. Powered by jinkela-core 2.8.3.
         \/            \/ color:#00a1d6

Syntax error @ "Bilibili Evolved (Offline)"!
##########################
JSHINT output:
##########################

SyntaxError: Expected identifier, string or number
   at C.E_c (Unknown script code:3:391)
   at ja (Function code:62:80)
   at create (Function code:73:419)
   at e (Function code:14:351)
   at r.run (Function code:14:468)
   at Anonymous function (Function code:75:218)
   at Array.prototype.forEach (native code)
   at Anonymous function (Unknown script code:3:71)
   at b (Unknown script code:2:57)
   at Anonymous function (Function code:75:194)

SCRIPT1028: SCRIPT1028: Expected identifier, string or number
www.bilibili.com (63,187)

Syntax error @ "Bilibili Evolved (Offline)"!
##########################
JSHINT output:
##########################

SyntaxError: Expected identifier, string or number
   at C.E_c (Unknown script code:3:391)
   at ja (Function code:64:80)
   at create (Function code:75:419)
   at e (Function code:16:351)
   at r.run (Function code:16:468)
   at Anonymous function (Function code:77:218)
   at Array.prototype.forEach (native code)
   at Anonymous function (Unknown script code:3:71)
   at b (Unknown script code:2:57)
   at Anonymous function (Function code:77:194)

SCRIPT1028: SCRIPT1028: Expected identifier, string or number
index_new_pc_sync (65,187)

**附加截图**
![image](https://user-images.githubusercontent.com/50985752/93763033-45aa0480-fc43-11ea-946e-2ab6ae0cbb2f.png)
![image](https://user-images.githubusercontent.com/50985752/93763096-696d4a80-fc43-11ea-86f1-1345d800c69f.png)

**Comment by SuperGik** [comment]
在新版Chromium Edge上运行正常，是不是不支持EdgeHTML的js引擎啊

**Comment by the1812** [comment]
当然不支持

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/93765468-84da5480-fc47-11ea-8d36-a5fa950e7e3d.png)
