### ISSUE TITLE
希望增加视频画中画功能

### ISSUE THREAD

**Issue by jiang9527** [the1812/Bilibili-Evolved#963]
**关于哪一项功能**

希望增加视频播放的画中画快捷按钮。

**期望的效果**

播放普通视频的时候，可以在“附加功能”栏中添加“画中画”按钮。
**脚本版本**

**Comment by the1812** [comment]
![image](https://user-images.githubusercontent.com/26504152/93765616-c2d77880-fc47-11ea-9b0a-bf6757b1bd42.png)

**Comment by Geeyun-JY3** [comment]
而且有快捷键的：<kbd>p</kbd>

此快捷键在 [v1.10.14](https://github.com/the1812/Bilibili-Evolved/releases/tag/v1.10.14) 加入，只是 [功能列表](https://github.com/the1812/Bilibili-Evolved/blob/master/features.md) 和脚本设置里的简短说明还没加。
