### ISSUE TITLE
播放器改版导致很多功能失效 触摸/双击全屏/双击控制等

### ISSUE THREAD

**Issue by XIU2** [the1812/Bilibili-Evolved#966]
**问题描述**  

默认播放器模式无论设置宽屏还是全屏，打开视频网页后都无效（依然是默认大小），而昨天该功能还正常。

**脚本版本**  

正式版1.10.38

**浏览器版本**  

Chrome 80

**Comment by the1812** [comment]
今天播放器又改了
触摸播放器, 双击控制 之类的也失效了

**Comment by the1812** [comment]
初步测得失效的功能:
- 播放器投影 - mini播放器
- 夜间模式 - mini播放器
- 触摸拖动迷你播放器
- 播放器触摸手势
- 播放器双击控制
- 自动定位到播放器
- 启用逐帧调整

以下的不但失效还无法响应视频更改:
- BiliPlus跳转
- 启用视频快速截图
- 网址参数清理
- 自动从历史记录点播放
- 默认播放器模式/倍速
- 双击全屏
- 自动展开弹幕列表
- 快捷键扩展 - 稍后再看页面点赞
- AV/BV号显示
- 默认弹幕设置
- 下载视频
- 外置稍后再看
- 启用快速收藏
- 播放前显示封面
- 跳过充电列表
- 查看封面

> b站怎么突然搞这种事...

**Comment by 995871491** [comment]
> 初步测得失效的功能:
> 
> * 播放器投影 - mini播放器
> * 夜间模式 - mini播放器
> * 触摸拖动迷你播放器
> * 播放器触摸手势
> * 播放器双击控制
> * 自动定位到播放器
> * 启用逐帧调整
> 
> 以下的不但失效还无法响应视频更改:
> 
> * BiliPlus跳转
> * 启用视频快速截图
> * 网址参数清理
> * 自动从历史记录点播放
> * 默认播放器模式/倍速
> * 双击全屏
> * 自动展开弹幕列表
> * 快捷键扩展 - 稍后再看页面点赞
> * AV/BV号显示
> * 默认弹幕设置
> * 下载视频
> * 外置稍后再看
> * 启用快速收藏
> * 播放前显示封面
> * 跳过充电列表
> * 查看封面
> 
> > b站怎么突然搞这种事...

感觉是更新完加载变慢了，我是默认宽屏的，进一个新视频要等大概18秒才会变宽，期间双击手势失效

**Comment by the1812** [comment]
@995871491 因为改版后检测不到播放器了 然后达到了脚本设置的15秒超时时间才强行运行功能

**Comment by nyano** [comment]
> @995871491 因为改版后检测不到播放器了 然后达到了脚本设置的15秒超时时间才强行运行功能

哎 这几天都15秒才能跳宽屏。。。
关键这破跳宽屏还 下移。。。烦死了
定位播放器又没用了

能不能把15秒手动设为1秒？

**Comment by the1812** [comment]
https://subterranean-rose.imfast.io/bilibili-evolved.preview.user.js
可以提前试下预览版中的效果了

**Comment by gayhub-com** [comment]
原来大家都这样,我还以为就我的问题.B站整天更新也没见得体验变好多少,反正多了很多累赘

**Comment by u2shana** [comment]
顶栏直接进去的旧版的稍后再看页面bilibili.com/watchlater/#/BVXXXXXXXXXX还没修复,依旧15s才自动宽屏

至于新版的稍后再看已经不指望能恢复这功能了

**Comment by 2217936322** [comment]
来个简单的方法 强制加载旧版本播放器 完事

**Comment by Geeyun-JY3** [comment]
@the1812 已失效视频 `BiliPlus跳转支持` 功能失效也和本次播放器改版有关吗🤔

**Comment by ThebestkillerTBK** [comment]
又改了，又失效了，弹幕还加了个快速举报的弹窗，十分烦人，希望去除

**Comment by 995871491** [comment]
双击全屏又失效了》？

**Comment by the1812** [comment]
加了个奇怪的弹幕相关浮层  所有在播放器界面上操作的东西都会失效
包括: 触摸播放器  双击控制  双击全屏 等

**Comment by XXXXuan** [comment]
默认画质的设置也失效了

**Comment by MC-dusk** [comment]
b站又双叒叕改，诶，至少向下兼容啊

**Comment by XIU2** [comment]
作者头都要秃了😳

**Comment by Geeyun-JY3** [comment]
> 至少向下兼容啊

这也和脚本怎么实现功能有关系吧🌚
不过 b 站哪用考虑改版对这种增强脚本的影响，用的人始终是少数🌚

**Comment by sky96111** [comment]
触摸控制又双叒叕失效了:（

**Comment by the1812** [comment]
目前最有效的解决方案就是 直接禁掉那个弹幕点赞的图层 所有受影响功能直接恢复正常
你们能接受的话我就这么干了

**Comment by XIU2** [comment]
> 目前最有效的解决方案就是 直接禁掉那个弹幕点赞的图层 所有受影响功能直接恢复正常
> 你们能接受的话我就这么干了

干吧！

**Comment by sky96111** [comment]
> 目前最有效的解决方案就是 直接禁掉那个弹幕点赞的图层 所有受影响功能直接恢复正常
> 你们能接受的话我就这么干了

可。平日里客户端也是最讨厌误触点赞弹幕了

**Comment by 11111111111ge1** [comment]
> > 目前最有效的解决方案就是 直接禁掉那个弹幕点赞的图层 所有受影响功能直接恢复正常
> > 你们能接受的话我就这么干了
> 
> 可。平日里客户端也是最讨厌误触点赞弹幕了

设置-弹幕设置- 弹幕便捷操作功能  把这个关掉就行了，
关掉后长按才能选中弹幕

**Comment by 11111111111ge1** [comment]
提个建议,可以把弹幕点赞功能移到这里
![image](https://user-images.githubusercontent.com/39661677/94980674-6c7b0b80-055e-11eb-8cf2-4afa0d49ed18.png)
这样两边都不影响

**Comment by the1812** [comment]
> 设置-弹幕设置- 弹幕便捷操作功能 把这个关掉就行了，
> 关掉后长按才能选中弹幕

这个在哪?
![image](https://user-images.githubusercontent.com/26504152/94980929-99c8b900-0560-11eb-9327-3e39696ce28f.png)

**Comment by 11111111111ge1** [comment]
> > 设置-弹幕设置- 弹幕便捷操作功能 把这个关掉就行了，
> > 关掉后长按才能选中弹幕
> 
> 这个在哪?
> ![image](https://user-images.githubusercontent.com/26504152/94980929-99c8b900-0560-11eb-9327-3e39696ce28f.png)

我说的是手机客户端…

**Comment by Geeyun-JY3** [comment]
> 设置-弹幕设置- 弹幕便捷操作功能 把这个关掉就行了

> 我说的是手机客户端…

这两句话的意思是这个解决方法只适用于手机客户端吗……

**Comment by the1812** [comment]
> 这两句话的意思是这个解决方法只适用于手机客户端吗……

那是手机端防止误触点赞的方法

电脑端目前还是走强制屏蔽

**Comment by imThree** [comment]
十分怀疑做网页版的一批人跟着逸献帝一块退位了
逸已死吾亦死🤪

**Comment by Ben-md5** [comment]
> 提个建议,可以把弹幕点赞功能移到这里
> ![image](https://user-images.githubusercontent.com/39661677/94980674-6c7b0b80-055e-11eb-8cf2-4afa0d49ed18.png)
> 这样两边都不影响

+1

**Comment by SCHEN1974** [comment]
> 目前最有效的解决方案就是 直接禁掉那个弹幕点赞的图层 所有受影响功能直接恢复正常
> 你们能接受的话我就这么干了

请问我不需要触摸功能，怎么恢复这项功能，今天8.13的播放器弹幕只能进行屏蔽了，无法快捷的复制了。

**Comment by Geeyun-JY3** [comment]
> 请问我不需要触摸功能，怎么恢复这项功能

目前如果要用 Bilibili Evolved 的话，没办法。
