### ISSUE TITLE
增加收藏功能

### ISSUE THREAD

**Issue by wadawada** [the1812/Bilibili-Evolved#967]
https://www.bilibili.com/bangumi/play/ep268181

**关于哪一项功能**
仅限台湾地区的影片都没有收藏按钮

**期望的效果**
在所有影片页面补回收藏按钮

**脚本版本**
v1.10.38

**ps**
本来想回报bug到bilibili官方论坛, 但是找不到网址了???

**Comment by the1812** [comment]
什么时候有过收藏按钮?
我看非地区限定的番剧也是没有的啊
