### ISSUE TITLE
简化评论区后点赞／踩按钮跟随主题色变色

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#968]
**关于哪一项功能**
简化评论区

**期望的效果**
简化评论区后点赞／踩按钮跟随主题色变色。
希望鼠标悬停点赞／踩按钮上时、点赞／踩后这两按钮能跟随主题色变色。现在悬停只变亮、点赞／踩后只变灰，给用户的指引暗示不够强。

**脚本版本**
正式版 v1.10.38 内容包: fef5fe5

**Comment by Geeyun-JY3** [comment]
建议先把夜间模式下的做了，非夜间模式下可以和 #431 一起做。

**Comment by the1812** [comment]
#431 可是有生之年了, 别对那个做完抱有期待(

**Comment by Geeyun-JY3** [comment]
> #431 可是有生之年了, 别对那个做完抱有期待(

这么说在 https://github.com/the1812/Bilibili-Evolved/issues?page=5&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc#issuecomment-721471139 建议的拆分岂不是有生之年后的有生之年😨

**Comment by the1812** [comment]
哪的拆分?

**Comment by Geeyun-JY3** [comment]
> 哪的拆分?

复制链接的时候一个脚本好像出问题了，已修改。

**Comment by the1812** [comment]
噢 那确实是的

**Comment by Geeyun-JY3** [comment]
should be closed by #1828
