### ISSUE TITLE
默认播放器模式选择网页全屏出现的问题

### ISSUE THREAD

**Issue by zippo1933** [the1812/Bilibili-Evolved#97]
**关于哪一项功能**
默认播放器模式选择网页全屏

**问题描述**
默认播放器模式选择网页全屏，没有勾选播放时应用模式，打开视频后无论是播放还是暂停，只要退出网页全屏，滚动至评论区就会回到网页全屏。

**脚本版本**
使用的是离线版243.95，也尝试过预览离线版254.23，问题依旧。

**浏览器版本**
浏览器是Cent Browser 3.9.2.45(Chromium 72.0.3626.121)，脚本管理器是Tampermonkey 4.8

麻烦帮忙看看，谢谢了。

**Comment by zippo1933** [comment]
补充一下，关闭bilibili那个迷你播放器后问题就没有了。

**Comment by the1812** [comment]
已修复
