### ISSUE TITLE
使用默认播放器模式 BUG

### ISSUE THREAD

**Issue by 2217936322** [the1812/Bilibili-Evolved#973]
**关于哪一项功能**
使用默认播放器模式
使用默认播放器速度

**问题描述**

BUG出现在所有视屏

播放模式设置 网页全屏
两种情况 一个是无法全屏 一个是 几十秒后全屏

播放器速度
变速生效 但是 现实在前端的 速度始终是1.0

**脚本版本**

Stable v1.10.38
内容包: 2855ee7

**浏览器版本**

 (Chromium 80.0.3987.163)

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
看置顶：#966，更新 v1.10.39
