### ISSUE TITLE
S10 4K直播间默认清晰度问题

### ISSUE THREAD

**Issue by aliofwind** [the1812/Bilibili-Evolved#975]
**关于哪一项功能**
直播默认画质

**问题描述**

目前B站在4K直播间给4K清晰度用的qn=800，但qn=10000的原画还是1080P，所以切换到的不是最清晰的画质选项

**脚本版本**

800.18

**浏览器版本**

Chrome 80.0.3987.163

**错误信息**

4K直播间：https://live.bilibili.com/blanc/24

**附加截图**
![image](https://user-images.githubusercontent.com/35068322/94335203-87a0c500-000c-11eb-8bee-1c2b09cafeb0.png)

**Comment by Coulomb-G** [comment]
这不是b站设置的问题么?和脚本有什么关系

**Comment by the1812** [comment]
默认直播清晰度我可以加一个4K的选项, 不过排在原画后面就是b站的问题了

**Comment by aliofwind** [comment]
我的需求是默认直播清晰度判定的时候能不能把4K判定成比原画高，因为进4K房默认是4K那档，开了默认原画会覆盖掉

**Comment by the1812** [comment]
可以先这么加上  不过如果后来原画又比4K好了会再出问题
