### ISSUE TITLE
在视频播放界面一直自动刷新

### ISSUE THREAD

**Issue by Dragonbron10086** [the1812/Bilibili-Evolved#976]
**关于哪一项功能**

**问题描述**

**脚本版本**

**浏览器版本**

**错误信息**

**附加截图**

**Comment by the1812** [comment]
看置顶.. #883

**Comment by Dragonbron10086** [comment]
已解决
非常感谢


发件人: Grant Howard<mailto:notifications@github.com>
发送时间: 2020年9月26日 19:11
收件人: the1812/Bilibili-Evolved<mailto:Bilibili-Evolved@noreply.github.com>
抄送: Dragonbron10086<mailto:zsj1808805690@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [the1812/Bilibili-Evolved] 在视频播放界面一直自动刷新 (#976)


看置顶.. #883<https://github.com/the1812/Bilibili-Evolved/issues/883>

―
