### ISSUE TITLE
可以增加记住弹幕样式的功能吗？

### ISSUE THREAD

**Issue by CodesHunger** [the1812/Bilibili-Evolved#977]
**关于哪一项功能**

记住弹幕样式

**期望的效果**
希望可以像A站一样记住弹幕的颜色、大小、位置，这样就不用每次发送弹幕都重新选择了

**脚本版本**
Stable v1.10.38
内容包: a8117fc

**Comment by CodesHunger** [comment]
另外还有一个问题，似乎是电脑太卡的原因，记住弹幕设置  里的  防挡字幕   好像会失效，可能是因为弹幕加载太慢，但奇怪的是下载之后的弹幕却没问题。请问怎样可以延迟自动防挡字幕，或者在弹幕加载完一段时间后取消再开启防挡字幕功能？

**Comment by Geeyun-JY3** [comment]
duplicate #371

**Comment by CodesHunger** [comment]
😅搜过弹幕颜色、大小、字体，就是忘了搜弹幕样式
