### ISSUE TITLE
脚本作者大大牛逼！希望能有筛选B站分区的功能，只显示想看的分区，免得麻烦在右边分区栏一个个找了！

### ISSUE THREAD

**Issue by Awesomers123** [the1812/Bilibili-Evolved#978]
**关于哪一项功能**

**期望的效果**

**脚本版本**

**Comment by LonelySteve** [comment]
主页的分区顺序是可以调整的，你可以把想看的分区放在前面。

![image](https://user-images.githubusercontent.com/34429322/94364730-19d4c600-00fe-11eb-8b31-0c96751588cc.png)

**Comment by Geeyun-JY3** [comment]
duplicate #861
