### ISSUE TITLE
默认播放器样式在后台打开的问题

### ISSUE THREAD

**Issue by RainEffect** [the1812/Bilibili-Evolved#98]
使用**后台打开新页面**的时候，即使你开了**自动播放视频**，播放也不会立刻进行，只有当你切换到该页面的时候，才会自动播放，这是好事 (以上的描述不是BUG)

但，**默认播放器样式**功能反而失去了作用，在打开页面至后台的时候，如果过段时间再回去播放，则播放器样式**不会被应用在页面中**！

因其为功能性问题，无截图。
描述完毕。

**Comment by the1812** [comment]
我推测的一些原因:
脚本里有些功能会等待一个元素出现后再执行, 总共等待15秒, 每1秒检查一次, 15秒过去还没等到就取消执行了.
挂在后台的时候, 浏览器会暂停一部分脚本的执行(到底是哪部分我也不清楚), 但是这个循环等待器是在运行的, 而b站有一些脚本却没有执行. 最后页面加载出了`<video>`元素, 但视频数据还没有加载, 也没有加载控制栏. 
`默认播放器模式`最后会等不到视频的控制栏而取消执行, 类似的还有`自动展开弹幕列表`, `播放器触摸支持`等. 而`自动播放`因为已经有了`<video>`元素, 就可以成功把播放状态改掉, 当回到页面时, 视频数据加载, 就可以开始播放了.

我之后试试看能不能改成标签在后台的时候暂停检测.
