### ISSUE TITLE
课程网址参数清理

### ISSUE THREAD

**Issue by Geeyun-JY3** [the1812/Bilibili-Evolved#981]
**关于哪一项功能**
网址参数清理

**期望的效果**
主要是看到王骁在评论区贴的链接：`https://www.bilibili.com/cheese/play/ss172?bsource=wangxiao`，也不太清楚这个参数有什么作用

**脚本版本**
正式版 v1.10.38 内容包: 3325458

**Comment by BibgyWolf** [comment]
标识来源，大致是统计客流来给链接关联的推广账号身份返利的。
