### ISSUE TITLE
自定义顶栏的透明填充功能失效

### ISSUE THREAD

**Issue by LonelySteve** [the1812/Bilibili-Evolved#983]
**关于哪一项功能**

自定义顶栏

**问题描述**

在关闭「隐藏顶部横幅」并打开「使用自定义顶栏」功能的前提下，打开「透明填充」功能，顶栏并未像预期一样透明化。

**脚本版本**

Stable v1.10.39

**浏览器版本**

- Chrome 85.0.4183.121
- Microsoft Edge 85.0.564.63

**附加截图**

![image](https://user-images.githubusercontent.com/34429322/94513212-b4ddb500-0250-11eb-8245-0d8b5ba7c2ea.png)

**错误信息**

关键问题在于设置透明填充的情况下，这个 custom-navbar 的类属性还应该添加上 transparent，但是不知道为啥并没有效果。

**可能有关的代码**

https://github.com/the1812/Bilibili-Evolved/blob/0162f85d3e0646d9e9fae14d72d48de186d2fcb4/src/style/custom-navbar/custom-navbar.ts#L82-L84

**Comment by the1812** [comment]
那个横幅是不是改版了啊  我听说有鼠标在上面移动还有特效啥的
这里的检测是基于那个横幅的  所以很可能出问题

**Comment by CyberTNT** [comment]
Microsoft Edge Beta 86.0.622.28同样的问题，应该是阿b用了新横幅的锅（

**Comment by wwzw27** [comment]
应该是横幅改了的原因

**Comment by LonelySteve** [comment]
> 那个横幅是不是改版了啊 我听说有鼠标在上面移动还有特效啥的
> 这里的检测是基于那个横幅的 所以很可能出问题

是的 ，在新横幅上移动鼠标有景深特效，甚至最下面的图层还是动图。

![demo.gif](https://i.loli.net/2020/09/29/Gka9mVJo5gc6FIx.gif)

**Comment by 1421356447** [comment]
应该是横幅问题了，望大佬尽快修复

**Comment by the1812** [comment]
国庆想修复一下  结果这横幅换成国庆的了...

**Comment by LonelySteve** [comment]
> 国庆想修复一下 结果这横幅换成国庆的了...

没事，反正国庆过去之后应该就会换回来了（

**Comment by wwzw27** [comment]
换回来了。大佬可以着手修复了。
