### ISSUE TITLE
无法双击全屏

### ISSUE THREAD

**Issue by OliverDuhamel** [the1812/Bilibili-Evolved#990]
**关于哪一项功能**
双击全屏

**问题描述**
视频无法双击全屏

**脚本版本**
v1.10.39

**浏览器版本**
85.0.4183.121（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by Coulomb-G** [comment]
提issue前,请先搜索关键词

**Comment by the1812** [comment]
见 #966
