### ISSUE TITLE
B站播放器改版，弹幕可以鼠标悬停点赞后，上一个版本加入的弹幕跳转功能失效

### ISSUE THREAD

**Issue by AQ-Official** [the1812/Bilibili-Evolved#991]
**关于哪一项功能**

**问题描述**
任何视频中，均会出现此问题
发现问题自https://www.bilibili.com/video/BV1di4y1E78y   “空降00:00”

**脚本版本**
Stable v1.10.38
内容包: 6f64aae

**浏览器版本**
Chrome 版本 85.0.4183.121（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by the1812** [comment]
也可以算进 #966 中
@kdxcxs

**Comment by Geeyun-JY3** [comment]
这功能真是命运多舛😂刚出来就碰上连续两次播放器改版。也不知道官方什么时候在网页版实现这个功能

**Comment by the1812** [comment]
但愿官方能想到吧, 这次加了弹幕的相关操作层, 官方要做的话估计很简单

**Comment by kdxcxs** [comment]
就挺迷的，有些功能手机端有电脑端没有，有些电脑端有的手机端又没有

**Comment by Coulomb-G** [comment]
因为是多个团队在做功能...

**Comment by LonelySteve** [comment]
讲道理，这个悬停点赞功能有点蠢，总是容易弄得弹幕悬停，而且必须得挪动鼠标才能恢复，要是能超时之后让弹幕自动恢复滚动或者设计一个可以关闭悬停点赞的功能就更好了。
