### ISSUE TITLE
开启夜间模式后，高能进度条的颜色，与主题色不匹配。

### ISSUE THREAD

**Issue by AQ-Official** [the1812/Bilibili-Evolved#992]
**关于哪一项功能**
开启夜间模式后，高能进度条的颜色，与主题色不匹配。

**问题描述**
任何一个有高能任务栏的页面。开启夜间模式后，高能进度条的颜色，与主题色不匹配。

**脚本版本**

Stable v1.10.38
内容包: 6f64aae

**浏览器版本**

Chrome 版本 85.0.4183.121（正式版本） （64 位）

**错误信息**

**附加截图**

**Comment by Geeyun-JY3** [comment]
同 #744

**Comment by the1812** [comment]
历史原因(
