### ISSUE TITLE
关于清爽风格首页的一些细节

### ISSUE THREAD

**Issue by RingingVolcano** [the1812/Bilibili-Evolved#995]
**关于哪一项功能**

清爽首页的一些细节

**期望的效果**
视频在线排行榜的按钮文字由“当前在线”改为“在线列表”或者“在线排行”会更合适些（https://www.bilibili.com/video/online.html）

热门和动态视频列表建议禁用鼠标指针位于时的滚轮左右滚动 用鼠标下拉页面不能一滚到底体验不太好
动态列表建议在右上角“全部动态”按钮左侧加上类似于热门列表的左右滚动按钮
以后这两个列表的左右滚动就用按钮或者触控板了（

**脚本版本**
Preview v1.10.39
内容包: 1f5d747

**Comment by XIU2** [comment]
我说怎么突然没办法鼠标滚动了，适应了之后好别扭，@the1812 做个设置选项吧，用户自己选择用滚轮滚动还是用按钮翻页。
