### ISSUE TITLE
视频双击全屏功能失效

### ISSUE THREAD

**Issue by Stevejobsa** [the1812/Bilibili-Evolved#996]
**关于哪一项功能**
视频双击全屏功能失效

**问题描述**

任意视频

**脚本版本**

正式版1.10.39

**浏览器版本**

85.0.4183.121（正式版本） 64 位

**错误信息**

无任何信息

**附加截图**

**Comment by Geeyun-JY3** [comment]
看置顶：https://github.com/the1812/Bilibili-Evolved/issues/966#issuecomment-700071936
