### ISSUE TITLE
希望能自动解析flv地址，以便IDM能抓取到有音频的flv地址

### ISSUE THREAD

**Issue by lyytemp** [the1812/Bilibili-Evolved#997]
**关于哪一项功能**

我挂着SSTAP下载地区限制的番剧时，不知道是节点限制还是其他的原因，导致aria2的下载只能持续很短一段时间，之后速度就会非常非常慢，暂停重新开始可以再次短暂的快速下载。

但是我发现在用插件的直接下载下载后，IDM的chrome插件就能获取到FLV的地址，并调用IDM下载，而IDM下载的速度和线程数都比aria2理想的多。
如果不进行插件直接下载的操作，IDM只能获取到没有音频的MP4格式。

**期望的效果**
希望能做到自动让IDM插件获取到FLV地址，thx~~~

**脚本版本**

**Comment by the1812** [comment]
点复制链接, 让IDM下载那个链接就行

**Comment by lyytemp** [comment]
> 点复制链接，让IDM下载那个链接就行

确认可用，感谢~
唯一的问题是通过IDM插件发起的下载它会自动填写网页名称为文件名，会稍微方便一点点，不过可以下载就很好了~我可以放弃插件只用这个脚本了~~~

**Comment by the1812** [comment]
IDM不支持自定义文件名
需要的话可以考虑下aria2

**Comment by lyytemp** [comment]
> IDM不支持自定义文件名
> 需要的话可以考虑下aria2

收到，thx~
