### ISSUE TITLE
为什么夜间模式不能取消"使用细滚动条"

### ISSUE THREAD

**Issue by wmjgh** [the1812/Bilibili-Evolved#998]

**Comment by the1812** [comment]
因为原版滚动条是白色的

**Comment by wmjgh** [comment]
黑色的有办法把滚动条的高度调粗一点点吗,夜间模式滚动条颜色有点难分辨,鼠标点滚动条时,屏幕往往会因为鼠标太靠屏幕边缘,没有把鼠标显示完整,导致点击滚动条时,只能靠滚动条的颜色变化来判断是非位置对了

**Comment by Geeyun-JY3** [comment]
可参考 #837
